### PR TITLE
class_attribute: delegate to an internal namespaced method

### LINKED ISSUE #53606: `class_attribute` setter redefinition discards prepended overrides in subclasses
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "8.0.0"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "minitest/autorun"

module SetterOverride
  def some_attribute=(value)
    previous_values << some_attribute
    super
  end

  def previous_values
    @previous_values ||= []
  end
end

class TestBase
  class_attribute :some_attribute

  class << self
    prepend(SetterOverride)
  end
end

class TestClass2 < TestBase
end

class BugTest < ActiveSupport::TestCase
  def test_base_and_subclass_assignment
    TestBase.some_attribute = :base_0
    TestBase.some_attribute = :base_1
    TestBase.some_attribute = :base_2

    assert_equal([nil, :base_0, :base_1], TestBase.previous_values)

    assert_equal([], TestClass2.previous_values)
    assert_equal(:base_2, TestClass2.some_attribute)

    TestClass2.some_attribute = :subclass_1
    TestClass2.some_attribute = :subclass_2
    TestClass2.some_attribute = :subclass_3

    assert_equal([:base_2, :subclass_1, :subclass_2], TestClass2.previous_values)
  end
end
```

### Expected behavior

In the above example, `TestClass2` should collect `[:base_2, :subclass_1, :subclass_2]` as `previous_values`

### Actual behavior

It only collects `[:base2]`, then the setter redefines itself without the prepended override. This seems to be caused by `TestClass2` not being equal to `owner`; i.e. this only happens in a subclass of a parent with class_attributes.

I believe this was introduced in https://github.com/rails/rails/commit/1962e8d7350aef9af3e3f42ce81f3958cc634734 (but I haven't done a bisect yet). The issue is not present in v7.2.2.

Edit: bisect does point to 1b94c8199d26dc6ad34e83ec4bd081283fe671e7

### System configuration
**Rails version**: 8.0.0

**Ruby version**: 3.3.5

### PR DESCRIPTION
**Pull request by byroot**
Fix: https://github.com/rails/rails/issues/53606

`class_attribute` never composed well with `prepend` or `alias_method_chain`. Up to 7.2, whenever the value was re-assigned, the reder method was redefined.

Now, since 8.0, we no longer redefine the reader, or at least in less cases, but then the writer is sometimes redefined too, which restrict even more how much decoration can be done.

A solution to this is to define class attributes under a namespaces and then define a two simple delegator methods to allow decoration.

Of course it's one extra method call, but that's still miles better than what it used to be, and probably acceptable.

cc @zvkemp

### CODE REVIEW

File: activesupport/lib/active_support/core_ext/class/attribute.rb [hunk 1]
```diff
@@ -93,12 +93,27 @@ def class_attribute(*attrs, instance_accessor: true,
...
+      class_methods.concat(delegators)
+      if singleton_class?
+        methods.concat(delegators)
+      else
         methods << <<~RUBY if instance_reader
           silence_redefinition_of_method def #{name}
-            defined?(@#{name}) ? @#{name} : self.class.#{name}
+            if defined?(@#{name})
+              @#{name}
+            elsif respond_to?(#{namespaced_name.inspect}, true)
```
Comment (byroot) [inline activesupport/lib/active_support/core_ext/class/attribute.rb:112]: Looks like this is causing some stack overflow 😢

Comment (byroot) [reply activesupport/lib/active_support/core_ext/class/attribute.rb:112]: Problem is we need it to handle class attribute on singleton classes. Need to spend more time to detangle all that.

**Comment by jamis** [comment]
I regret that I didn't see this sooner. The `redefined` method is not strictly declared as an internal API, so we have code that depends on it. With the signature now changed, our code breaks against Rails master.

Could the `namespaced_value` parameter be optional? That would allow it to be set without breaking compatibility.

**Comment by byroot** [comment]
> The `redefined` method is not strictly declared as an internal API,

It very much is. The entire module is `:nodoc:`, which marks private APIs. Just vendor the code if you have a similar need.
