### PR TITLE
Optimize `TextHelper.highlight` for large inputs

### LINKED ISSUE #47337: ActionView::Helpers::TextHelper # highlight is performing slow with either large text or multiple matches
### Steps to reproduce

The following test is the most simple use-case to increase the `highlight` execution time into multiple seconds. In my real world case I was trying to match 50 different items across 1000's of lines of plain text.

The test below only shows the execution times and does not fail. I can not really define what the expected performance on any hardware is supposed to be, expect that it am certain that it should be faster.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~> 7.0.0"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers
end

require "minitest/autorun"
require "minitest/benchmark"

class BugTest < Minitest::Benchmark
  include Rack::Test::Methods

  def bench_highlight_with_one_text_match
    assert_performance (proc {}) do |n|
      TestController.helpers.highlight("foo bar 1234\n" * n, "bar")
    end
  end

  def bench_highlight_with_one_match
    assert_performance (proc {}) do |n|
      TestController.helpers.highlight("foo bar 1234\n" * n, /bar/)
    end
  end

  def bench_highlight_with_two_matches
    assert_performance (proc {}) do |n|
      TestController.helpers.highlight("foo bar 1234\n" * n, /foo|bar/)
    end
  end

  def bench_highlight_with_three_matches
    assert_performance (proc {}) do |n|
      TestController.helpers.highlight("foo bar 1234\n" * n, /foo|bar|1234/)
    end
  end
end
```

### Expected behavior

The `highlight` method performs highlighting with multiple thousand of lines and multiple matches in less than a second, or even better in less than 100ms. 

### Actual behavior

| Benchmark | 1 lines | 10 lines | 100 lines | 1000 lines | 10000 lines |
| ------------- |:----------:|:----------:|:----------:|:----------:|:----------:|
| bench_highlight_with_one_text_match | 0.002027 | 0.000874 | 0.001864 | **0.072229** | **6.902236** |
| bench_highlight_with_one_match | 0.231050 | 0.001049 | 0.001921 | **0.069195** | **6.856789** |
| bench_highlight_with_two_matches | 0.000937 | 0.000907 | 0.002685 | **0.148295** | **14.246967** |
| bench_highlight_with_three_matches | 0.001286 | 0.000569 | 0.002794 | **0.208822** | **20.961633** |

The highlight method performs surprisingly slow and easily reaches multi-second execution times when having either larger text or multiple matches.

In my case I was highlighting 50 kind of matches found in multiple 1000's of lines of text. That resulted in timeouts due to the 60+ second long execution time. I did not expect highlight to be that slow and that sensitive. My matches did not consist of very complex regexes. It usually mostly consisted of simple case insensitive word matches, sometimes some simple character matching like \S+.

Initially I tried to nest `highlight` method calls for each kind of match, which resulted in even worse execution times.

### System configuration
**Rails version**:
7.0.4.2

**Ruby version**:
ruby 3.2.0
ruby 3.2.1

### Documentation
https://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-highlight

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #47337.

Previous regex used lookahead, so it was `O(n^2)` of the string size - for each detected phrase it looked forward (possibly for the rest of the string till the end) to see if it is not in the middle of the html tag.

Current approach linearly scans the text.

For the larger text (`highlight("foo bar 1234\n" * 10000, /foo|bar|1234/)`), previously it ran 30s, now - ~1s.

For smaller texts, performance is basically the same:
```ruby
Benchmark.ips do |x|
  x.report("original") do
    TestController.helpers.highlight('You searched for: rails', /for|rails/)
  end

  x.report("optimized") do
    TestController.helpers.highlight_optimized('You searched for: rails', /for|rails/)
  end

  x.compare!
end
```

```
Warming up --------------------------------------
            original   330.000  i/100ms
           optimized   357.000  i/100ms
Calculating -------------------------------------
            original      4.759k (±22.4%) i/s -     22.770k in   5.085356s
           optimized      3.559k (±18.7%) i/s -     17.493k in   5.106094s

Comparison:
            original:     4759.0 i/s
           optimized:     3559.1 i/s - same-ish: difference falls within error
```

### CODE REVIEW

**Comment by matthewd** [comment]
Nice! This does seem like it's going to do a lot of work in a large tag-rich input even with few highlight matches, though... what do you think of using `MatchData#end(0)` & `String#index(/[<>]/, offset)` to implement the previous "scan forward from end of match" behaviour, but avoid the quadratic by remembering the last scanned index?

**Comment by fatkodima** [comment]
> but avoid the quadratic by remembering the last scanned index

Isn't it linear? 🤔 

I used the suggested approach and got this:
```ruby
def do_highlight_optimized(text, pattern, highlighter: nil, &block)
  bracket_index = nil
  bracket = nil

  text.gsub(/#{pattern}/i) do |match|
    matchdata = Regexp.last_match
    offset = matchdata.end(0)

    if bracket_index.nil? || offset > bracket_index
      bracket_index = text.index(/[<>]/, offset)
      bracket_index ||= text.size
      bracket = text[bracket_index]
    end

    if bracket == ">"
      match
    elsif block_given?
      yield match
    else
      highlighter.gsub('\1', match)
    end
  end
end
```

Measured a time it took to run:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", path: "~/Desktop/oss/rails" # "~> 7.0.0"
  gem "benchmark-ips"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger
end

class TestController < ActionController::Base
end

puts "Started"
start = Process.clock_gettime(Process::CLOCK_MONOTONIC)
input = "<zoo>woo</zoo> baz\n" * 10000 + "foo"
TestController.helpers.highlight_optimized(input, /foo|bar|1234/)
delta = Process.clock_gettime(Process::CLOCK_MONOTONIC) - start
puts "Finished in #{delta.round(2)} seconds"
```

And got the same results for this version and version in the PR. Am I missing something?

File: actionview/lib/action_view/helpers/text_helper.rb [hunk 1]
```diff
@@ -139,15 +139,15 @@ def highlight(text, phrases, options = {}, &block)
...
           end.join("|")
 
           if block_given?
-            text.gsub(/(#{match})(?![^<]*?>)/i, &block)
+            do_highlight(text, pattern, &block)
           else
             highlighter = options.fetch(:highlighter, '<mark>\1</mark>')
-            text.gsub(/(#{match})(?![^<]*?>)/i, highlighter)
+            do_highlight(text, pattern, highlighter: highlighter)
           end
```
Comment (jonathanhefner) [inline actionview/lib/action_view/helpers/text_helper.rb:151]: Another alternative:

```suggestion
          patterns = Array(phrases).map { |phrase| Regexp === phrase ? phrase : Regexp.escape(phrase) }
          pattern = /(#{patterns.join("|")})/i
          highlighter = options.fetch(:highlighter, '<mark>\1</mark>') unless block

          text.scan(/<[^>]+>|[^<]+/).each do |segment|
            if !segment.start_with?("<")
              if block
                segment.gsub!(pattern, &block)
              else
                segment.gsub!(pattern, highlighter)
              end
            end
          end.join
```



Benchmark:

```ruby
# frozen_string_literal: true
require "benchmark/ips"

TestController = Class.new(ActionController::Base)

def benchmark(input, pattern)
  puts "=== input length: #{input.length} ".ljust(72, "=")

  Benchmark.ips do |x|
    x.report("original") do
      TestController.helpers.highlight(input, pattern)
    end

    x.report("commit 204fac2") do
      TestController.helpers.highlight_204fac2(input, pattern)
    end

    x.report("alternative") do
      TestController.helpers.highlight_alt(input, pattern)
    end

    x.compare!
  end
end

benchmark("foo bar 1234\n" * 10000, /foo|bar|1234/)
benchmark("You searched for: rails", /for|rails/)
```

```console
$ bin/rails r pr47339.rb
=== input length: 130000 ===============================================
Warming up --------------------------------------
            original     1.000  i/100ms
      commit 204fac2     1.000  i/100ms
         alternative     1.000  i/100ms
Calculating -------------------------------------
            original      0.017  (± 0.0%) i/s -      1.000  in  58.022911s
      commit 204fac2      0.413  (± 0.0%) i/s -      3.000  in   7.277325s
         alternative     20.534  (± 4.9%) i/s -    103.000  in   5.028064s

Comparison:
         alternative:       20.5 i/s
      commit 204fac2:        0.4 i/s - 49.77x  (± 0.00) slower
            original:        0.0 i/s - 1191.45x  (± 0.00) slower

=== input length: 23 ===================================================
Warming up --------------------------------------
            original   367.000  i/100ms
      commit 204fac2   200.000  i/100ms
         alternative   329.000  i/100ms
Calculating -------------------------------------
            original      3.776k (±14.2%) i/s -     18.717k in   5.068264s
      commit 204fac2      1.857k (±21.7%) i/s -      9.000k in   5.059772s
         alternative      2.676k (±13.3%) i/s -     13.160k in   5.012414s

Comparison:
            original:     3776.2 i/s
         alternative:     2675.8 i/s - 1.41x  (± 0.00) slower
      commit 204fac2:     1856.8 i/s - 2.03x  (± 0.00) slower
```

Comment (jonathanhefner) [reply actionview/lib/action_view/helpers/text_helper.rb:151]: The full code without the wonky diff highlighting:

```ruby
def highlight(text, phrases, options = {}, &block)
  text = sanitize(text) if options.fetch(:sanitize, true)

  if text.blank? || phrases.blank?
    text || ""
  else
    patterns = Array(phrases).map { |phrase| Regexp === phrase ? phrase : Regexp.escape(phrase) }
    pattern = /(#{patterns.join("|")})/i
    highlighter = options.fetch(:highlighter, '<mark>\1</mark>') unless block

    text.scan(/<[^>]+>|[^<]+/).each do |segment|
      if !segment.start_with?("<")
        if block
          segment.gsub!(pattern, &block)
        else
          segment.gsub!(pattern, highlighter)
        end
      end
    end.join
  end.html_safe
end
```

Comment (fatkodima) [reply actionview/lib/action_view/helpers/text_helper.rb]: 👏 👏 👏 

I was thinking initially about trying `scan`, but haven't tried it for some reason.

Added you as a co-author (should be author actually 😄)

File: actionview/lib/action_view/helpers/text_helper.rb [hunk 2]
```diff
@@ -139,16 +139,19 @@ def highlight(text, phrases, options = {}, &block)
...
-            text.gsub(/(#{match})(?![^<]*?>)/i, &block)
-          else
-            highlighter = options.fetch(:highlighter, '<mark>\1</mark>')
-            text.gsub(/(#{match})(?![^<]*?>)/i, highlighter)
-          end
+          patterns = Array(phrases).map { |phrase| Regexp === phrase ? phrase : Regexp.escape(phrase) }
+          pattern = /(#{patterns.join("|")})/i
+          highlighter = options.fetch(:highlighter, '<mark>\1</mark>') unless block
+
+          text.scan(/<[^>]+>|[^<]+/).each do |segment|
```
Comment (jhawthorn) [inline actionview/lib/action_view/helpers/text_helper.rb:146]: This regex has backtracking issues on Ruby < 3.2 for example with the string `"<"*99999`. I think that's only possible if this is called with `sanitize: false`, which seems like a misuse of this API (and actually this change alters that behaviour too), but maybe we could find an alternative way to do this?

Comment (jonathanhefner) [reply actionview/lib/action_view/helpers/text_helper.rb:146]: Interesting point!  I think the following works as well:

```suggestion
          text.scan(/<[^>]*|[^<]+/).each do |segment|
```

And doesn't exhibit backtracking issues:

```ruby
string = "<"*99999

puts Benchmark.measure { string.scan(/<[^>]+>|[^<]+/){} }
# 91.561392   0.019090  91.580482 ( 92.037754)

puts Benchmark.measure { string.scan(/<[^>]*|[^<]+/){} }
# 0.003507   0.000000   0.003507 (  0.005074)
```

I actually like that regex better, because it should ensure that no portion of the string is dropped by the `scan`, even if the string includes malformed HTML.  (Though, some highlighting might still be skipped in that case, but I think that's a reasonable trade-off.)

**Comment by matthewd** [comment]
> Isn't it linear?

Sorry, my phrasing was unclear. I meant to describe the way in which my proposal avoided the _original_ quadratic, by way of contrast to the also-linear strategy in your change.

That was what I had in mind, thanks for trying it -- I was definitely expecting the many allocations from the extra calls to be a time sink, but I guess not!

File: actionview/lib/action_view/helpers/text_helper.rb (hunk 2 above)
Comment (fatkodima) [reply actionview/lib/action_view/helpers/text_helper.rb]: Applied this change.

**Comment by jonathanhefner** [comment]
Thank you, @fatkodima! :chart_with_downwards_trend:

And thank you, @matthewd and @jhawthorn! :raised_hands:
