### PR TITLE
Don’t create storage folder if not needed

### LINKED ISSUE #51835: Storage folder seems like it is sometimes not needed
### Steps to reproduce

```
rails new myapp --skip-active-storage -d postgresql
ls
```

### Expected behavior
There should be no storage folder.

### Actual behavior
There is a storage folder.

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**: 3.3.1

### Comments

I may be wrong but it seems like the storage folder is only needed for sqlite or Active Storage. Based on some of the Rails code [here](https://github.com/rails/rails/blob/72fccfb5d665b0e16a4238e5a7c73a37f2712fa2/railties/lib/rails/generators/app_base.rb#L787) and [here](https://github.com/rails/rails/blob/72fccfb5d665b0e16a4238e5a7c73a37f2712fa2/railties/lib/rails/generators/rails/app/templates/config/deploy.yml.tt#L34-L37), it seems that when using a different database and the `--skip-active-storage` option, this folder isn't really useful. So one could argue that it should not be created by `rails new`.

### PR DESCRIPTION
**Pull request by jeromedalbert**
Fixes https://github.com/rails/rails/issues/51835.

### Motivation / Background

This Pull Request has been created because the `storage/` directory seems to be used only for sqlite or
Active Storage. If using a different database and the `--skip-active-storage` option, this directory does not seem like it is needed.

### Detail

This Pull Request changes the rails app generator to not create the storage directory if skipping Active Storage and using a database that is different from sqlite.

### Additional information

The condition I implemented is the same as the one used [further down](https://github.com/rails/rails/blob/72fccfb5d665b0e16a4238e5a7c73a37f2712fa2/railties/lib/rails/generators/app_base.rb#L787) in the generator.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by liroyleshed** [comment]
Seems like a great convention, though!

File: railties/lib/rails/generators/rails/app/app_generator.rb [hunk 1]
```diff
@@ -455,7 +455,7 @@ def create_system_test_files
       end
 
       def create_storage_files
-        build(:storage)
+        build(:storage) unless skip_active_storage? && !sqlite3?
```
Comment (justinko) [inline railties/lib/rails/generators/rails/app/app_generator.rb:458]: Maybe add a `skip_storage?` method in `app_base.rb` for reuse.

**Review by yahonda — APPROVED** [review]
