### PR TITLE
Expire caching when a download fail while proxying in ActiveStorage

### LINKED ISSUE #51284: ActiveStorage ProxyController sets Cache-Control headers on errors like FileNotFoundError
### Steps to reproduce
Ive observed occasional broken **representation** images on our site. After digging a little into this issue it became clear that the proxy cache in front of our application has cached a broken image. A cache purge always fixed it. 

After digging a little deeper i think i found the source. The proxy cache is getting a `cache-control` header instructing it to do so by the ActiveStorage::Representations::ProxyController!

Ive created a synthetic test which reproduces it. The response is successful with zero length and cache-control header set. The following test falsely passed!

```ruby
    ActiveStorage::Service::DiskService.any_instance.expects(:download).raises(ActiveStorage::FileNotFoundError)
    
    get active_storage_image_url # "/rails/active_storage/representations/proxy/..."

    assert_response :ok
    assert_equal 'image/png', response.content_type
    assert_equal "0", response.headers['Content-Length']
    assert response.headers.key? 'ETag'
    assert_equal "max-age=3155695200, public", response.headers['Cache-Control']
```

### Expected behavior
On an error like `ActiveStorage::FileNotFoundError` the response should not be successful nor should it instruct caches to cache that empty response.

### Actual behavior
On an error like `ActiveStorage::FileNotFoundError` the response is still successful (Statuscode: 200) and a cache-control header is instructing caches to cache this empty response.

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.1.2

### PR DESCRIPTION
**Pull request by JoeDupuis**
Fix #51284

Both Proxy controllers in Active Storage set the caching headers early before streaming. 

In some instances (see #51284), it is possible for the file download (from the storage service to Active Storage) to fail before we send the first byte to the client (response not yet committed). 

In those instances, this change would invalidate the cache and return a better response status before closing the stream.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activestorage/app/controllers/concerns/active_storage/streaming.rb [hunk 1]
```diff
@@ -61,6 +61,13 @@ def send_blob_stream(blob, disposition: nil) # :doc:
         blob.download do |chunk|
           stream.write chunk
         end
+      rescue ActiveStorage::FileNotFoundError
+        expires_now
+        head :not_found
+      rescue
+        expires_now
+        head :internal_server_error
```
Comment (MatheusRich) [inline activestorage/app/controllers/concerns/active_storage/streaming.rb:69]: Do we still need to do this if we are raising below?

Comment (JoeDupuis) [reply activestorage/app/controllers/concerns/active_storage/streaming.rb:69]: The two lines are still needed. If you remove them and run the tests, they will fail. 
It is counter intuitive. Perhaps I should add a comment.
 
When downloading the file from the backing service for streaming, the 200 response + cache header are already set on the response object, they're just not yet committed to the client, so they can still be changed. 

When we raise that late (send_stream's block), we still send a 200 + caching header. 
I don't think a 500 will be common, but could still happen because of bad network or something similar.

Comment (JoeDupuis) [reply activestorage/app/controllers/concerns/active_storage/streaming.rb:71]: I added a comment.
