### PR TITLE
Fix broken url configs

### LINKED ISSUE #36559: Database config options being discarded when merged with DATABASE_URL
We found this issue running the Rails 6 RC in production when the `pool` size we specified in `database.yml` was not being used. In our case, this manifested itself as `ActiveRecord::ConnectionTimeoutError` because our database pool was too small for the number of Sidekiq threads running.

It appears that when `DATABASE_URL` is set, all other options in `database.yml` are discarded UNLESS there is a [single option with a string value](https://github.com/rails/rails/blob/f6db8b8d8286730757570a8b0f92e6b6be779fa8/activerecord/lib/active_record/database_configurations.rb#L144).

Note that this behavior _seems_ to be covered by an [existing test](https://github.com/rails/rails/blob/f6db8b8d8286730757570a8b0f92e6b6be779fa8/activerecord/test/cases/connection_adapters/merge_and_resolve_default_url_config_test.rb#L247-L260), but that test happens to hit the magic scenario of a single string value. I added some test cases below that are very similar but exhibit the problematic behavior.

I spent some time attempting a fix, but [this line](https://github.com/rails/rails/blob/f6db8b8d8286730757570a8b0f92e6b6be779fa8/activerecord/lib/active_record/database_configurations.rb#L144) seems like it does something important... I'm just unclear on the intent.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
# ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

class DatabaseConnectionTest < Minitest::Test
  def resolve_config(config)
    configs = ActiveRecord::DatabaseConfigurations.new(config)
    configs.to_h
  end

  def test_merge_no_conflicts_with_database_url_and_numeric_pool
    ENV["DATABASE_URL"] = "postgres://localhost/foo"

    config   = { "default_env" => { "pool" => 5 } }
    actual   = resolve_config(config)
    expected = { "default_env" =>
                  { "adapter"  => "postgresql",
                    "database" => "foo",
                    "host"     => "localhost",
                    "pool"     => 5
                  }
                }
    assert_equal expected, actual

    ENV["DATABASE_URL"] = nil
  end

  def test_merge_no_conflicts_with_database_url_and_adapter
    ENV["DATABASE_URL"] = "postgres://localhost/foo"

    config   = { "default_env" => { "adapter" => "postgresql", "pool" => "5" } }
    actual   = resolve_config(config)
    expected = { "default_env" =>
                  { "adapter"  => "postgresql",
                    "database" => "foo",
                    "host"     => "localhost",
                    "pool"     => "5"
                  }
                }
    assert_equal expected, actual

    ENV["DATABASE_URL"] = nil
  end
end
```

### Expected behavior
The `DATABASE_URL` value should be merged with any other options, such as `pool`, `timeout`, `variables`, etc.

### Actual behavior
All options from `database.yml` are discarded.

### System configuration
**Rails version**: master  
**Ruby version**: 2.6.1

### PR DESCRIPTION
**Pull request by eileencodes**
This PR is to fix #36559 but I also found other issues that haven't been
reported.

The check for `(config.size == 1 && config.values.all? { |v| v.is_a?
String })` was naive. The only reason this passed was because we had
tests that had single hash size configs, but that doesn't mean we don't
want to create a hash config in other cases. So this now checks for
`config["database"] || config["adapter"] || ENV["DATABASE_URL"]`. In the
end for url configs we still get a UrlConfig but we need to pass through
the HashConfig to create the right kind of UrlConfig. The UrlConfig's
are really complex and I don't necessarily understand everything that's
needed in order to act the same as Rails 5.2.

I edited the connection handler test to demonstrate how the previous
implementation was broken when checking config size. Now old and new
tests pass so I think this is closer to 5.2.

Fixes #36559

cc/ @adamlogic @tenderlove @rafaelfranca @jhawthorn

### CODE REVIEW

File: activerecord/test/cases/connection_adapters/merge_and_resolve_default_url_config_test.rb [hunk 1]
```diff
@@ -273,6 +273,41 @@ def test_merge_conflicts_with_database_url
...
+        expected = { "default_env" =>
+                     { "adapter"  => "postgresql",
+                       "database" => "foo",
+                       "host"     => "localhost",
+                       "pool"     => "5"
+                     }
+        }
+        assert_equal expected, actual
+
+        ENV["DATABASE_URL"] = nil
```
Comment (jhawthorn) [inline activerecord/test/cases/connection_adapters/merge_and_resolve_default_url_config_test.rb]: I think this is already done in [`teardown`](https://github.com/rails/rails/pull/36565/files#diff-0e21b63c5ed26f357a66d05a4c6a3804R15)

Comment (eileencodes) [reply activerecord/test/cases/connection_adapters/merge_and_resolve_default_url_config_test.rb]: Yes I accidentally copied that from the script sent by the original reporter. Fixing now.

**Review by jhawthorn — APPROVED** [review]
👍 New check seems like it would work better

**Review by rafaelfranca — APPROVED** [review]

**Comment by adamlogic** [comment]
Awesome, thank you for the quick fix @eileencodes!

**Comment by eileencodes** [comment]
Backported to 6-0-stable
