### PR TITLE
Preload browser driver_path to fix system testing under parallelism

### LINKED ISSUE #36288: Error using Rails 6 parallel testing and system tests: `ChildProcess::LaunchError: Text file busy - /home/circleci/.webdrivers/chromedriver`
I'm experimenting with Rails 6 parallel testing and I've found an issue that others might run into. I've been able to work around it, but I thought it would be helpful to open an issue here to see if we want to do something within rails to address it.

### Steps to reproduce

In the https://github.com/rmacklin/rails_parallel_testing_experiments repository, I created a new rails 6.0.0.rc1 app and added a dummy system test. I configured it to run tests in parallel, and set it up to run on CircleCI.

### Expected behavior

The tests pass on CI

### Actual behavior

The tests can fail on CI with the following error:
```
ChildProcess::LaunchError: Text file busy - /home/circleci/.webdrivers/chromedriver
    test/system/sample_system_test.rb:19:in `block in <class:SampleSystemTest>'
```

Example CI build: https://circleci.com/gh/rmacklin/rails_parallel_testing_experiments/16

### System configuration
**Rails version**: 6.0.0.rc1

**Ruby version**: 2.6.1

I think the error stems from multiple forked processes trying to update chromedriver in parallel. I've configured the sample app to use 2 parallel workers, but it follows that this error will be more common as more parallel workers are used.

My workaround was to explicitly trigger a chromedriver update before parallel processes are forked: https://github.com/rmacklin/rails_parallel_testing_experiments/commit/4b3b06bbeb34ec57277c8b37ad3804cd659539db

That appears to make the issue go away, but I wanted to discuss whether or not we think this is something to address within Rails.

---

cc @eileencodes since you are the mastermind behind both [parallel testing](https://github.com/rails/rails/pull/31900) and [system tests](https://weblog.rubyonrails.org/2017/4/27/Rails-5-1-final/#system-tests)

### PR DESCRIPTION
**Pull request by jhawthorn**
The `webdrivers` gem configures `Selenium::WebDriver::Service.driver_path` as a proc which updates the web drivers and returns their path.

This commit introduces `SystemTesting::Browser#preload`, which runs this proc early. This ensures that webdrivers update is run before forking for parallel testing, but doesn't explicitly tie us to that gem (and I think anything configured as driver_path probably makes sense to eager-load).

cc @rmacklin @eileencodes

Fixes #36288
Closes #36292

### CODE REVIEW

File: actionpack/lib/action_dispatch/system_testing/driver.rb [hunk 1]
```diff
@@ -9,6 +9,7 @@ def initialize(name, **options, &capabilities)
         @screen_size = options[:screen_size]
         @options = options[:options]
         @capabilities = capabilities
+        @browser.preload
```
Comment (eileencodes) [inline actionpack/lib/action_dispatch/system_testing/driver.rb]: This is picky but can you add a space before this so it's separate from setting the instance vars?

```suggestion

        @browser.preload
```

File: actionpack/lib/action_dispatch/system_testing/browser.rb [hunk 2]
```diff
@@ -39,6 +39,19 @@ def capabilities
           end
       end
 
+      def preload
+        # driver_path can be configured as a proc. The webdrivers gem uses this
+        # proc to update web drivers. Running this proc early allows us to only
+        # update the webdriver once and avoid race conditions when using
+        # parallel tests.
```
Comment (eileencodes) [inline actionpack/lib/action_dispatch/system_testing/browser.rb]: This class is private so I think either this comment should be moved above preload and it won't load in the docs anyway, or should be removed.

**Review by eileencodes — APPROVED** [review]
I left a minor comment but this feels better and cleaner than our previous implementation.
