### PR TITLE
Restores functionality to the missing method when using enums and fixes #48651

### LINKED ISSUE #48651: Behaviour of `where.missing` changed in rails 7.0.6
### Steps to reproduce

Create a model called `Publisher` that has an enum on the `name` attribute.

```ruby
class Publisher < ApplicationRecord
  belongs_to :listing

  enum name: {
    foo: 0,
    bar: 1
  }
end
```

Create another model named `Listing` that has a `has_many` association and scoped `has_one` associations to `Publisher`.

```ruby
class Listing < ApplicationRecord
  has_many :publishers, dependent: :destroy
  has_one :foo_listing, -> { foo }, class_name: Publisher.name
  has_one :bar_listing, -> { bar }, class_name: Publisher.name
end
```

Create an instance of Listing that has a `foo` publisher but not a `bar` publisher (using Factory Bot here for brevity).

```ruby
create(:listing, publishers: [build(:publisher, :foo)])
```

Run a query using `where.missing` to select listings with a `foo` publisher but not a `bar` publisher.

```ruby
Listing.joins(:foo_listing).where.missing(:bar_listing)
```

### Expected behavior

The query should return the listing created above. This works in Rails 7.0.5.1.

### Actual behavior

No records are returned in Rails 7.0.6.

The table alias seems to have changed in the generated SQL.

Rails 7.0.5.1:

```sql
SELECT listings.*
FROM listings
    INNER JOIN publishers ON publishers.name = 0 AND publishers.listing_id = listings.id
    LEFT OUTER JOIN publishers bar_listing ON bar_listing.name = 1
        AND bar_listing.listing_id = listings.id
WHERE bar_listing.id IS NULL
```

Rails-7.0.6:

```sql
SELECT listings.*
FROM listings
    INNER JOIN publishers ON publishers.name = 0 AND publishers.listing_id = listings.id
    LEFT OUTER JOIN publishers bar_listings_listings ON bar_listings_listings.name = 1
        AND bar_listings_listings.listing_id = listings.id
WHERE publishers.id IS NULL
```

Explicitly creating the left join and checking for blank ID works in 7.0.6:

```ruby
Listing.joins(:foo_listing).left_joins(:bar_listing).where(bar_listing: {id: nil})
```

### System configuration

**Rails version**: 7.0.6

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by paulreece**
### Motivation / Background

This Pull Request has been created because of the bug raised in issue [48651](https://github.com/rails/rails/issues/48651). 

Say you have the following models in Rails 7.0.6, and have used an enum in one and aliases in the other.

```Ruby
class Publisher < ApplicationRecord
  belongs_to :listing

  enum name: {
    foo: 0,
    bar: 1
  }
end

class Listing < ApplicationRecord
  has_many :publishers, dependent: :destroy
  has_one :foo_listing, -> { foo }, class_name: Publisher.name
  has_one :bar_listing, -> { bar }, class_name: Publisher.name
end
```

If you have an instance of Listing that has a foo publisher but not a bar publisher and call:

 ```Ruby 
Listing.joins(:foo_listing).where.missing(:bar_listing)
```

It returns nothing whereas one would expect it to return the Listing you created that only has a `:foo_listing`

Please see bug fix if more detail is needed linked above. 

### Detail

This Pull Request changes the missing method in `active_record/relation/query_methods.rb`

Adds another conditional check in the missing query method  in ActiveRecord. This extra check makes sure that the values in `:joins` are different than the values in `:left_outer_joins`.  When they are it is likely that you are using an enum.  I do this checking first for the existence of values in `:joins` and `:left_outer_joins`.  Then I compare the size of the intersection of the two Arrays to the size of the `:joins` Array. If they are different then it implements the scope method excluding the desired enum alias.  The `size` method was used to keep this performant.  This passes all checks in ActiveRecord, including those from [47940](https://github.com/rails/rails/issues/47909) and [45015](https://github.com/rails/rails/pull/45015).

### Checklist

* [ X] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [ X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ X] Tests are added or updated if you fix a bug or add a feature.
* [ X] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/lib/active_record/relation/query_methods.rb [hunk 1]
```diff
@@ -110,6 +110,8 @@ def missing(*associations)
           @scope.left_outer_joins!(association)
           if @scope.table_name == reflection.table_name
             @scope.where!(association => { reflection.association_primary_key => nil })
+          elsif (@scope.values[:joins] && @scope.values[:left_outer_joins]) && ((@scope.values[:joins] & @scope.values[:left_outer_joins]).size != @scope.values[:joins].size)
```
Comment (eileencodes) [inline activerecord/lib/active_record/relation/query_methods.rb:113]: Hey @paulreece thanks for the PR.

I don't think this is the correct fix for the problem. We shouldn't need to reach into the scope values like this and make such a complex elsif statement. I'm unsure if the original fix was correct either, and don't really have the bandwidth to dig in and find the right fix. @fatkodima since you made the original changes, maybe you have an idea of what a better approach is?

Also in the future, the contributors [discord](https://discord.gg/HGRyZPXEjF) is a better place to ask for help with a PR. 😄

**Review by eileencodes — CHANGES_REQUESTED** [review]

File: activerecord/lib/active_record/relation/query_methods.rb (hunk 1 above)
Comment (eileencodes) [reply activerecord/lib/active_record/relation/query_methods.rb:113]: To be a bit clearer - I think comparing `@scope.table_name == reflection.table_name` in the original fix isn't correct because here we have a case where the table names don't match but we want the `association` as the key in the where. So we need to figure out how to know when we want an association instead of the reflection's table name.

Comment (paulreece) [reply activerecord/lib/active_record/relation/query_methods.rb:113]: I really appreciate the feedback, apologies for pinging you here and not on Discord.  I will definitely follow the Discord protocol in the future.  I'll experiment with trying to get this to work from the method setup before the original fix.

Comment (paulreece) [reply activerecord/lib/active_record/relation/query_methods.rb]: Okay, after comparing the different error cases tonight. I think I found a way simpler solution.  After deep diving into for a while I realized that it seems like we only want to use  `reflection.table_name` when the `@scope.values` hash only contains one key in `:left_outer_joins`.  This covers the problem found in [47909](https://github.com/rails/rails/issues/47909).  Then if the `@scope.values` hash has more than one key we use the `association`.  This works for both [44964](https://github.com/rails/rails/issues/44964) _and_ the newest issue this PR was submitted to address [48651](https://github.com/rails/rails/issues/48651).

The current suggested change is now:
```Ruby
if @scope.values.size > 1
  @scope.where!(association => { reflection.association_primary_key => nil })
 else
  @scope.where!(reflection.table_name => { reflection.association_primary_key => nil })
end
```

It passes the all the test cases for ActiveRecord including a new one I added for the newest issue [48651](https://github.com/rails/rails/issues/48651).

File: activerecord/lib/active_record/relation/query_methods.rb [hunk 2]
```diff
@@ -86,29 +86,11 @@ def associated(*associations)
...
-      #    # WHERE "authors"."id" IS NULL
-      #
-      # Additionally, multiple relations can be combined. This will return posts
-      # that are missing both an author and any comments:
-      #
-      #    Post.where.missing(:author, :comments)
-      #    # SELECT "posts".* FROM "posts"
-      #    # LEFT OUTER JOIN "authors" ON "authors"."id" = "posts"."author_id"
-      #    # LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id"
-      #    # WHERE "authors"."id" IS NULL AND "comments"."id" IS NULL
```
Comment (eileencodes) [inline activerecord/lib/active_record/relation/query_methods.rb:106]: Did you delete the docs by accident?

File: activerecord/lib/active_record/relation/query_methods.rb [hunk 3]
```diff
@@ -86,29 +86,11 @@ def associated(*associations)
...
       def missing(*associations)
         associations.each do |association|
           reflection = scope_association_reflection(association)
           @scope.left_outer_joins!(association)
-          if @scope.table_name == reflection.table_name
+          if @scope.values.size > 1
```
Comment (eileencodes) [inline activerecord/lib/active_record/relation/query_methods.rb:93]: This is definitely less complex and I think correct. I couldn't find an example where this has more than one scope value but wants `reflection.table_name`.

Does `associated` have the same bug? If so we should fix that in this PR too since it was changed in the other ones.

File: activerecord/lib/active_record/relation/query_methods.rb (hunk 2 above)
Comment (paulreece) [reply activerecord/lib/active_record/relation/query_methods.rb:106]: I did, apologies!  There were commented out methods for different classes I put up there when I was debugging all of this and I accidentally deleted this when I got rid of those.  I'll add them back!

File: activerecord/lib/active_record/relation/query_methods.rb (hunk 3 above)
Comment (paulreece) [reply activerecord/lib/active_record/relation/query_methods.rb:93]: Yes! It would have the same behavior introduced from the other bugs.  I will change that as well and add a test case for enum if it needs it.  Thanks for your time!

File: activerecord/lib/active_record/relation/query_methods.rb (hunk 2 above)
Comment (paulreece) [reply activerecord/lib/active_record/relation/query_methods.rb]: Just added this back.

File: activerecord/lib/active_record/relation/query_methods.rb (hunk 3 above)
Comment (paulreece) [reply activerecord/lib/active_record/relation/query_methods.rb:111]: Added this same logic to the `associated` method and added a test for it too.

File: activerecord/test/cases/relation/where_chain_test.rb [hunk 4]
```diff
@@ -75,7 +80,11 @@ def test_missing_with_multiple_association
     def test_missing_merged_with_scope_on_association
       # This query does not make much logical sense, but it is testing
       # that the generated SQL query is valid.
-      assert_equal Author.find(1).posts.count, Post.where.missing(:author).merge(Author.where(id: 1)).count
+      assert_equal Author.find(1).posts.count, Post.where.associated(:author).merge(Author.where(id: 1)).count
```
Comment (eileencodes) [inline activerecord/test/cases/relation/where_chain_test.rb:83]: I think this one was changed by accident?

**Review by eileencodes — COMMENTED** [review]
Ok, one last thing, and then I think this looks good. Once you fix the last change, please squash your commits so there's only 1 that explains the bug and the fix.

File: activerecord/test/cases/relation/where_chain_test.rb (hunk 4 above)
Comment (paulreece) [reply activerecord/test/cases/relation/where_chain_test.rb]: Yes this was, apologies again and thanks for your patience.

Comment (paulreece) [reply activerecord/test/cases/relation/where_chain_test.rb]: Just squashed everything into one branch with a helpful description of bug and fixes!  Thanks for your help.

**Review by eileencodes — APPROVED** [review]

**Comment by eileencodes** [comment]
Thanks for making those changes @paulreece and congrats on your first merged Rails PR! 🎉

**Comment by zhuravel** [comment]
Hi @eileencodes and @paulreece,

I'm encountering the same issue described in #47909 after this change was implemented. The test case remains the same, with one modification: in the last class, `order` or `unscope` must be added before applying the scopes. Here's an example:

```ruby
class BugTest < Minitest::Test
  def test_bug
    books = Book.order(created_at: :desc) # or `books = Book.unscope(:where)`

    assert_equal 0, books.completed.count
    assert_equal 0, books.without_progress.count
    assert_equal 0, books.without_progress.completed.count
  end
end

**Comment by paulreece** [comment]
@zhuravel I just ran your test file locally with the adjusted test case above.  It passed all assertions.  I copied and pasted how I have your test file setup locally just to make sure it's the same.  Let me know if it needs adjustments in order to replicate the behavior you're seeing.  I tried this with both `books = Book.order(created_at: :desc)`  and `books = Book.unscope(:where)` and it passed all 3 assertions both times.

Here's the test file with your adjusted `BugTest` above that I ran locally:
```Ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  if ARGV[0] == "main"
    gem "rails", github: "rails/rails", branch: "main"
  else
    gem "activerecord", "7.0.4.3"
  end

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table(:books, force: true) do |t|
    t.references :progress
  end

  create_table(:progresses, force: true) do |t|
    t.references :book
    t.integer :percentage, default: 0, null: false
  end
end

class Book < ActiveRecord::Base
  has_one :progress

  scope :without_progress, -> do
    where.missing(:progress)
  end

  scope :completed, -> do
    joins(:progress).merge(Progress.completed)
  end
end

class Progress < ActiveRecord::Base
  scope :completed, -> do
    where(percentage: 100)
  end
end

class BugTest < Minitest::Test
  def test_bug
    books = Book.order(created_at: :desc) # or `books = Book.unscope(:where)`

    assert_equal 0, books.completed.count
    assert_equal 0, books.without_progress.count
    assert_equal 0, books.without_progress.completed.count
  end
end
```

**Comment by eileencodes** [comment]
I'm seeing the bug reproduced locally with the script on Rails main. Unfortunately the `missing` method in Active Record is lightly tested so it's easy to introduce issues. Looking closer at the script, it seems like we only want to use the association for the key when we have `extending` or `joins` in the scope values which means checking size isn't correct (the script example has left_outer_joins and order so we fall into the wrong side of the conditional). But since we don't have great tests there could be other keys we want to check on as well.

**Comment by paulreece** [comment]
I see it now on Rails main too.  Eileen, can I work on correcting this?

**Comment by eileencodes** [comment]
Yes @paulreece go ahead. Also it'd be helpful if you can add more tests for `missing` so we can catch other possible regressions. Thanks!

**Comment by paulreece** [comment]
Thanks Eileen! I really appreciate how helpful you have been with my contributing experience.    [Here](https://github.com/rails/rails/pull/48861) is a PR I created in order to address these issues.
