### PR TITLE
Collect all file patterns when running multiple rake test tasks

### LINKED ISSUE #27801: Calling `rake test:units test:functionals` etc. only runs one group of tests
### Steps to reproduce

On Rails 5.0.0 or higher, execute `rake test:units test:functionals TESTOPTS=-v` and see only the functional tests will be run.

* Reproducer (Rails master @ c6f7c18e): https://github.com/domcleal/bug_rails_rake_chain
* Working example (4.2.7.1): https://github.com/domcleal/bug_rails_rake_chain/tree/4.2

### Expected behavior

Both groups should be run, both unit tests (models, helpers) and functional tests (controllers, mailers).

Output: https://github.com/domcleal/bug_rails_rake_chain/tree/4.2#readme

### Actual behavior

Only the _last_ argument is run, i.e. functional tests (controllers, mailers).

Output: https://github.com/domcleal/bug_rails_rake_chain/tree/master#readme

### System configuration
**Rails version**: 5.0.1, master @ c6f7c18e (works on 4.2.7.1)

**Ruby version**: 2.3.0

### PR DESCRIPTION
**Pull request by domcleal**
Fixes #27801

### CODE REVIEW

**Comment by arthurnn** [comment]
Thanks @domcleal for the bug fix.. Do you mind adding a changelog entry for this fix, and rebasing your PR against latest master?

File: railties/lib/rails/test_unit/minitest_plugin.rb [hunk 1]
```diff
@@ -60,7 +60,7 @@ def self.plugin_rails_options(opts, options)
   # Running several Rake tasks in a single command would trip up the runner,
   # as the patterns would also contain the other Rake tasks.
   def self.rake_run(patterns) # :nodoc:
-    @rake_patterns = patterns
+    (@rake_patterns ||= []).push(*patterns)
```
Comment (kaspth) [inline railties/lib/rails/test_unit/minitest_plugin.rb]: Won't this negate what the comment says above? In other words, do we need `rake_run` anymore? It might have become obsolete after moving to `autorun`.

Comment (domcleal) [inline railties/lib/rails/test_unit/minitest_plugin.rb]: The comment is still valid with `@rake_patterns` - it's targeted at fixing `rake db:migrate test` rather than two test tasks. Without it, the plugin would run tests listed in the argument list, which is `['db:migrate' ,'test']` - instead `rake_run` stores the paths from test:\* tasks so running test + non-test tasks works.

This was originally added in df744b5, but missing a test to cover it and the conditional above, so I added one in b5a9428.

I think you're right that `rake_run` (or rather `@rake_patterns`) is a bit obsolete now that `autorun` is used. The test files can be required immediately and `autorun` will handle it. I've removed `@rake_patterns` in a12803d, but kept `rake_run` as it makes the tasks in railties/lib/rails/test_unit/testing.rake a little less repetitive.

**Comment by domcleal** [comment]
@arthurnn thanks, I've rebased the PR, added two commits in response to @kaspth's comment (improve test coverage, refactor away this instance variable) and added the CHANGELOG entry.

**Comment by arthurnn** [comment]
Aren't we going to require_files twice now? https://github.com/domcleal/rails/blob/a12803dc17417437ddbbe93bc798d6b779363331/railties/lib/rails/test_unit/minitest_plugin.rb#L90

**Comment by domcleal** [comment]
@arthurnn thanks, you're right that it was called twice. `options[:pattern]` would be empty though for rake runs, but I've updated the last commit to skip the step when called via rake.

File: railties/test/application/test_runner_test.rb [hunk 2]
```diff
@@ -536,6 +536,21 @@ def test_rake_passes_multiple_TESTOPTS_to_minitest
...
+      create_test_file :models, "account"
+      create_test_file :controllers, "accountcontroller"
+      output = Dir.chdir(app_path) { `bin/rake test:models test:controllers TESTOPTS='-v'` }
+      assert_match "AccountTest#test_truth", output, "passing test:models should run test/models/"
+      assert_match "AccountcontrollerTest#test_truth", output, "passing test:controllers should run test/controllers"
+    end
+
+    def test_rake_db_and_test_tasks_parses_args_correctly
+      create_test_file :models, "account"
+      output = Dir.chdir(app_path) { `bin/rake db:migrate test:models TESTOPTS='-v' && echo ".tables" | rails dbconsole` }
```
Comment (kaspth) [inline railties/test/application/test_runner_test.rb]: Won't the piping into `dbconsole` make the test stall?

File: railties/test/application/test_runner_test.rb [hunk 3]
```diff
@@ -536,6 +536,21 @@ def test_rake_passes_multiple_TESTOPTS_to_minitest
...
+      assert_match "AccountTest#test_truth", output, "passing test:models should run test/models/"
+      assert_match "ar_internal_metadata", output, "tables should be dumped"
```
Comment (kaspth) [inline railties/test/application/test_runner_test.rb]: Let's kill the custom messages on `assert_match` here and above. Think the intention is sufficiently clear in the test code itself.

File: railties/lib/rails/test_unit/minitest_plugin.rb [hunk 4]
```diff
@@ -86,8 +85,9 @@ def run(args = [])
   def self.plugin_rails_init(options)
     ENV["RAILS_ENV"] = options[:environment] || "test"
 
-    # If run via `ruby` we've been passed the files to run directly.
-    unless run_via[:ruby]
+    # If run via `ruby` we've been passed the files to run directly, or if run
+    # via `rake` then they have already been included.
```
Comment (kaspth) [inline railties/lib/rails/test_unit/minitest_plugin.rb]: `included` is a new term, let's say `eagerly required` to stick with the established terminology.

File: railties/lib/rails/test_unit/minitest_plugin.rb [hunk 5]
```diff
@@ -59,19 +59,18 @@ def self.plugin_rails_options(opts, options)
...
-    options[:patterns] = defined?(@rake_patterns) ? @rake_patterns : opts.order!
+    options[:patterns] = opts.order! unless run_via[:rake]
   end
 
-  # Running several Rake tasks in a single command would trip up the runner,
-  # as the patterns would also contain the other Rake tasks.
   def self.rake_run(patterns) # :nodoc:
-    @rake_patterns = patterns
+    ::Rails::TestRequirer.require_files patterns
+    run_via[:rake] = true
```
Comment (kaspth) [inline railties/lib/rails/test_unit/minitest_plugin.rb]: Think it makes more sense to assign `run_via` as the first step and then require the files.

File: railties/lib/rails/test_unit/minitest_plugin.rb [hunk 6]
```diff
@@ -59,19 +59,18 @@ def self.plugin_rails_options(opts, options)
...
     options[:output_inline] = true
-    options[:patterns] = defined?(@rake_patterns) ? @rake_patterns : opts.order!
+    options[:patterns] = opts.order! unless run_via[:rake]
   end
 
-  # Running several Rake tasks in a single command would trip up the runner,
-  # as the patterns would also contain the other Rake tasks.
   def self.rake_run(patterns) # :nodoc:
-    @rake_patterns = patterns
+    ::Rails::TestRequirer.require_files patterns
```
Comment (kaspth) [inline railties/lib/rails/test_unit/minitest_plugin.rb]: Add parens around here: `::Rails::TestRequirer.require_files(patterns)`

File: railties/CHANGELOG.md [hunk 7]
```diff
@@ -1,3 +1,7 @@
+*   Fix running multiple test\* tasks specified in a single `rake` command
```
Comment (kaspth) [inline railties/CHANGELOG.md]: Don't understand what `test\*` is supposed to mean.

I'd write:

```
*   Fix running multiple tests in one `rake` command.

    E.g. `bin/rake test:models test:controllers`

# …
```

File: railties/test/application/test_runner_test.rb [hunk 8]
```diff
@@ -536,6 +536,21 @@ def test_rake_passes_multiple_TESTOPTS_to_minitest
       assert_match "seed=1234", output, "passing TEST= should run selected test"
     end
 
+    def test_rake_runs_multiple_test_tasks
+      create_test_file :models, "account"
+      create_test_file :controllers, "accountcontroller"
+      output = Dir.chdir(app_path) { `bin/rake test:models test:controllers TESTOPTS='-v'` }
```
Comment (kaspth) [inline railties/test/application/test_runner_test.rb]: Why do we pass in `TESTOPTS` here and below?

File: railties/test/application/test_runner_test.rb [hunk 9]
```diff
@@ -536,6 +536,21 @@ def test_rake_passes_multiple_TESTOPTS_to_minitest
       assert_match "seed=1234", output, "passing TEST= should run selected test"
     end
 
+    def test_rake_runs_multiple_test_tasks
+      create_test_file :models, "account"
+      create_test_file :controllers, "accountcontroller"
```
Comment (kaspth) [inline railties/test/application/test_runner_test.rb]: Let's follow Rails' naming conventions for good measure: `"accounts_controller"` :)

**Comment by kaspth** [comment]
Squash your commits down to 1 once the latest review has been addressed. Thanks for fixing this, digging it! 🤘

File: railties/test/application/test_runner_test.rb (hunk 2 above)
Comment (domcleal) [inline railties/test/application/test_runner_test.rb]: The test doesn't hang if that's what you mean, but it may take a bit longer to run. I wanted to check that the db:migrate task ran too, and this is the method used by previous tests.

File: railties/test/application/test_runner_test.rb (hunk 8 above)
Comment (domcleal) [inline railties/test/application/test_runner_test.rb]: It prints the names of the tests, so it can assert the expected tests ran using `output`.

**Comment by domcleal** [comment]
Thank you for the detailed review and comments @kaspth. I've fixed the style comments and squashed the commits.

**Comment by kaspth** [comment]
Awesome, thanks!

**Comment by domcleal** [comment]
Thanks @kaspth. Would you mind backporting it to 5-0-stable, since it's a regression vs 4.2?

**Comment by kaspth** [comment]
Apologies for not keeping you in the loop, I needed https://github.com/rails/rails/pull/27941 to be merged first.

Backported to 5-0-stable at e79ffaf...88b335e

**Comment by domcleal** [comment]
No worries, thanks @kaspth.

**Comment by kaspth** [comment]
Sounds good 👍
