### PR TITLE
Respect ActiveStorage default serving strategy

### LINKED ISSUE #41172: ActiveStorage configuration resolve_model_to_route is not picked up by rails_blob_* URL generator
### Steps to reproduce

1. Create a new rails app.
2. Set up activestorage with Amazon (S3) as backend service.
3. Set `config.active_storage.resolve_model_to_route = :rails_storage_proxy`.
3. Create a model with attachment. E.g. `class Picture < ApplicationRecord; has_one_attached :file; end`.
4. Create a new record with attachment.
5. Render `rails_blob_path`.

### Expected behavior
The link should start with `/rails/active_storage/blobs/proxy/`.

### Actual behavior
The link starts with `/rails/active_storage/blobs/redirect/`.

### System configuration
**Rails version**: 6.1.1

**Ruby version**: 2.7.2p137

### PR DESCRIPTION
**Pull request by aliismayilov**
fixes https://github.com/rails/rails/issues/41172

### Summary

`rails_blob_path` and `rails_blob_url` should be generating urls based on the ActiveStorage default serving strategy.

### Other Information

I wasn't sure where/if to add the changelog. Please let me know how to proceed.

### CODE REVIEW

File: activestorage/config/routes.rb [hunk 1]
```diff
@@ -28,7 +28,7 @@
   resolve("ActiveStorage::Preview") { |preview, options| route_for(ActiveStorage.resolve_model_to_route, preview, options) }
 
   direct :rails_blob do |blob, options|
-    route_for(:rails_service_blob, blob.signed_id, blob.filename, options)
+    route_for(ActiveStorage.resolve_model_to_route, blob, options)
```
Comment (composerinteralia) [inline activestorage/config/routes.rb:31]: If we are going to do this here, it probably makes sense to do the same sort of thing for `rails_representation` as well.

Comment (aliismayilov) [reply activestorage/config/routes.rb:27]: I think, that make sense. Thanks for pointing it out!

File: activestorage/CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,8 @@
+*   After setting `config.active_storage.resolve_model_to_route = :rails_storage_proxy`
+    `rails_blob_path` will generate proxy URLs by default.
```
Comment (composerinteralia) [inline activestorage/CHANGELOG.md:2]:
```suggestion
    `rails_blob_path` and `rails_representation_path` will generate proxy URLs by default.
```

**Review by composerinteralia — COMMENTED** [review]
Looks reasonable to me. I'll pass this off to the folks with commit access. @georgeclaghorn perhaps?

**Comment by aliismayilov** [comment]
@rafaelfranca could you please include this PR in the next rails 6.1 release as well? The bug is fixed on the main branch, but still exists in rails 6.1.x releases.
