### PR TITLE
Fix DescendantTracker.clear on Ruby 3.1

### LINKED ISSUE #43714: ActiveSupport::DescendantsTracker behavior with Ruby 3.1.0dev differs from that with Ruby 3.0.2
### Steps to reproduce
1. Install Ruby 3.1.0dev 
2. Run these steps
```
cd railties
bin/test test/application/loading_test.rb test/application/mailer_previews_test.rb test/application/query_logs_test.rb test/application/zeitwerk_integration_test.rb test/commands/routes_test.rb test/railties/engine_test.rb
```

### Expected behavior
All of the unit tests should pass.

### Actual behavior
These unit tests fail as follows.

```ruby
# Running:

F

Failure:
Rails::Command::RoutesTest#test_rails_routes_with_expanded_option [/home/yahonda/src/github.com/rails/rails/railties/test/commands/routes_test.rb:216]:
--- expected
+++ actual
@@ -4,138 +4,138 @@
 URI               | /cart(.:format)
 Controller#Action | cart#show
 --[ Route 2 ]--------------
+Prefix            | rails_service_blob
+Verb              | GET
+URI               | /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)
+Controller#Action | active_storage/blobs/redirect#show
+--[ Route 3 ]--------------
+Prefix            | rails_service_blob_proxy
+Verb              | GET
+URI               | /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)
+Controller#Action | active_storage/blobs/proxy#show
+--[ Route 4 ]--------------
+Prefix            |
+Verb              | GET
+URI               | /rails/active_storage/blobs/:signed_id/*filename(.:format)
+Controller#Action | active_storage/blobs/redirect#show
+--[ Route 5 ]--------------
+Prefix            | rails_blob_representation
+Verb              | GET
+URI               | /rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format)
+Controller#Action | active_storage/representations/redirect#show
+--[ Route 6 ]--------------
+Prefix            | rails_blob_representation_proxy
+Verb              | GET
+URI               | /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)
+Controller#Action | active_storage/representations/proxy#show
+--[ Route 7 ]--------------
+Prefix            |
+Verb              | GET
+URI               | /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)
+Controller#Action | active_storage/representations/redirect#show
+--[ Route 8 ]--------------
+Prefix            | rails_disk_service
+Verb              | GET
+URI               | /rails/active_storage/disk/:encoded_key/*filename(.:format)
+Controller#Action | active_storage/disk#show
+--[ Route 9 ]--------------
+Prefix            | update_rails_disk_service
+Verb              | PUT
+URI               | /rails/active_storage/disk/:encoded_token(.:format)
+Controller#Action | active_storage/disk#update
+--[ Route 10 ]-------------
+Prefix            | rails_direct_uploads
+Verb              | POST
+URI               | /rails/active_storage/direct_uploads(.:format)
+Controller#Action | active_storage/direct_uploads#create
+--[ Route 11 ]-------------
 Prefix            | rails_postmark_inbound_emails
 Verb              | POST
 URI               | /rails/action_mailbox/postmark/inbound_emails(.:format)
 Controller#Action | action_mailbox/ingresses/postmark/inbound_emails#create
---[ Route 3 ]--------------
+--[ Route 12 ]-------------
 Prefix            | rails_relay_inbound_emails
 Verb              | POST
 URI               | /rails/action_mailbox/relay/inbound_emails(.:format)
 Controller#Action | action_mailbox/ingresses/relay/inbound_emails#create
---[ Route 4 ]--------------
+--[ Route 13 ]-------------
 Prefix            | rails_sendgrid_inbound_emails
 Verb              | POST
 URI               | /rails/action_mailbox/sendgrid/inbound_emails(.:format)
 Controller#Action | action_mailbox/ingresses/sendgrid/inbound_emails#create
---[ Route 5 ]--------------
+--[ Route 14 ]-------------
 Prefix            | rails_mandrill_inbound_health_check
 Verb              | GET
 URI               | /rails/action_mailbox/mandrill/inbound_emails(.:format)
 Controller#Action | action_mailbox/ingresses/mandrill/inbound_emails#health_check
---[ Route 6 ]--------------
+--[ Route 15 ]-------------
 Prefix            | rails_mandrill_inbound_emails
 Verb              | POST
 URI               | /rails/action_mailbox/mandrill/inbound_emails(.:format)
 Controller#Action | action_mailbox/ingresses/mandrill/inbound_emails#create
---[ Route 7 ]--------------
+--[ Route 16 ]-------------
 Prefix            | rails_mailgun_inbound_emails
 Verb              | POST
 URI               | /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)
 Controller#Action | action_mailbox/ingresses/mailgun/inbound_emails#create
---[ Route 8 ]--------------
+--[ Route 17 ]-------------
 Prefix            | rails_conductor_inbound_emails
 Verb              | GET
 URI               | /rails/conductor/action_mailbox/inbound_emails(.:format)
 Controller#Action | rails/conductor/action_mailbox/inbound_emails#index
---[ Route 9 ]--------------
+--[ Route 18 ]-------------
 Prefix            |
 Verb              | POST
 URI               | /rails/conductor/action_mailbox/inbound_emails(.:format)
 Controller#Action | rails/conductor/action_mailbox/inbound_emails#create
---[ Route 10 ]-------------
+--[ Route 19 ]-------------
 Prefix            | new_rails_conductor_inbound_email
 Verb              | GET
 URI               | /rails/conductor/action_mailbox/inbound_emails/new(.:format)
 Controller#Action | rails/conductor/action_mailbox/inbound_emails#new
---[ Route 11 ]-------------
+--[ Route 20 ]-------------
 Prefix            | edit_rails_conductor_inbound_email
 Verb              | GET
 URI               | /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)
 Controller#Action | rails/conductor/action_mailbox/inbound_emails#edit
---[ Route 12 ]-------------
+--[ Route 21 ]-------------
 Prefix            | rails_conductor_inbound_email
 Verb              | GET
 URI               | /rails/conductor/action_mailbox/inbound_emails/:id(.:format)
 Controller#Action | rails/conductor/action_mailbox/inbound_emails#show
---[ Route 13 ]-------------
+--[ Route 22 ]-------------
 Prefix            |
 Verb              | PATCH
 URI               | /rails/conductor/action_mailbox/inbound_emails/:id(.:format)
 Controller#Action | rails/conductor/action_mailbox/inbound_emails#update
---[ Route 14 ]-------------
+--[ Route 23 ]-------------
 Prefix            |
 Verb              | PUT
 URI               | /rails/conductor/action_mailbox/inbound_emails/:id(.:format)
 Controller#Action | rails/conductor/action_mailbox/inbound_emails#update
---[ Route 15 ]-------------
+--[ Route 24 ]-------------
 Prefix            |
 Verb              | DELETE
 URI               | /rails/conductor/action_mailbox/inbound_emails/:id(.:format)
 Controller#Action | rails/conductor/action_mailbox/inbound_emails#destroy
---[ Route 16 ]-------------
+--[ Route 25 ]-------------
 Prefix            | new_rails_conductor_inbound_email_source
 Verb              | GET
 URI               | /rails/conductor/action_mailbox/inbound_emails/sources/new(.:format)
 Controller#Action | rails/conductor/action_mailbox/inbound_emails/sources#new
---[ Route 17 ]-------------
+--[ Route 26 ]-------------
 Prefix            | rails_conductor_inbound_email_sources
 Verb              | POST
 URI               | /rails/conductor/action_mailbox/inbound_emails/sources(.:format)
 Controller#Action | rails/conductor/action_mailbox/inbound_emails/sources#create
---[ Route 18 ]-------------
+--[ Route 27 ]-------------
 Prefix            | rails_conductor_inbound_email_reroute
 Verb              | POST
 URI               | /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)
 Controller#Action | rails/conductor/action_mailbox/reroutes#create
---[ Route 19 ]-------------
+--[ Route 28 ]-------------
 Prefix            | rails_conductor_inbound_email_incinerate
 Verb              | POST
 URI               | /rails/conductor/action_mailbox/:inbound_email_id/incinerate(.:format)
 Controller#Action | rails/conductor/action_mailbox/incinerates#create
---[ Route 20 ]-------------
-Prefix            | rails_service_blob
-Verb              | GET
-URI               | /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)
-Controller#Action | active_storage/blobs/redirect#show
---[ Route 21 ]-------------
-Prefix            | rails_service_blob_proxy
-Verb              | GET
-URI               | /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)
-Controller#Action | active_storage/blobs/proxy#show
---[ Route 22 ]-------------
-Prefix            |
-Verb              | GET
-URI               | /rails/active_storage/blobs/:signed_id/*filename(.:format)
-Controller#Action | active_storage/blobs/redirect#show
---[ Route 23 ]-------------
-Prefix            | rails_blob_representation
-Verb              | GET
-URI               | /rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format)
-Controller#Action | active_storage/representations/redirect#show
---[ Route 24 ]-------------
-Prefix            | rails_blob_representation_proxy
-Verb              | GET
-URI               | /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)
-Controller#Action | active_storage/representations/proxy#show
---[ Route 25 ]-------------
-Prefix            |
-Verb              | GET
-URI               | /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)
-Controller#Action | active_storage/representations/redirect#show
---[ Route 26 ]-------------
-Prefix            | rails_disk_service
-Verb              | GET
-URI               | /rails/active_storage/disk/:encoded_key/*filename(.:format)
-Controller#Action | active_storage/disk#show
---[ Route 27 ]-------------
-Prefix            | update_rails_disk_service
-Verb              | PUT
-URI               | /rails/active_storage/disk/:encoded_token(.:format)
-Controller#Action | active_storage/disk#update
---[ Route 28 ]-------------
-Prefix            | rails_direct_uploads
-Verb              | POST
-URI               | /rails/active_storage/direct_uploads(.:format)
-Controller#Action | active_storage/direct_uploads#create
 "



bin/test test/commands/routes_test.rb:204

.F

Failure:
Rails::Command::RoutesTest#test_rails_routes_with_global_search_key [/home/yahonda/src/github.com/rails/rails/railties/test/commands/routes_test.rb:53]:
--- expected
+++ actual
@@ -1,6 +1,5 @@
 "                         Prefix Verb URI Pattern                                                                                       Controller#Action
                            cart GET  /cart(.:format)                                                                                   cart#show
-  rails_conductor_inbound_email GET  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#show
              rails_service_blob GET  /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)                               active_storage/blobs/redirect#show
        rails_service_blob_proxy GET  /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)                                  active_storage/blobs/proxy#show
                                 GET  /rails/active_storage/blobs/:signed_id/*filename(.:format)                                        active_storage/blobs/redirect#show
@@ -8,4 +7,5 @@
 rails_blob_representation_proxy GET  /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)    active_storage/representations/proxy#show
                                 GET  /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)          active_storage/representations/redirect#show
              rails_disk_service GET  /rails/active_storage/disk/:encoded_key/*filename(.:format)                                       active_storage/disk#show
+  rails_conductor_inbound_email GET  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#show
 "



bin/test test/commands/routes_test.rb:44

..F

Failure:
Rails::Command::RoutesTest#test_rails_routes_displays_message_when_no_routes_are_defined [/home/yahonda/src/github.com/rails/rails/railties/test/commands/routes_test.rb:172]:
--- expected
+++ actual
@@ -1,4 +1,13 @@
 "                                  Prefix Verb   URI Pattern                                                                                       Controller#Action
+                      rails_service_blob GET    /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)                               active_storage/blobs/redirect#show
+                rails_service_blob_proxy GET    /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)                                  active_storage/blobs/proxy#show
+                                         GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                                        active_storage/blobs/redirect#show
+               rails_blob_representation GET    /rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations/redirect#show
+         rails_blob_representation_proxy GET    /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)    active_storage/representations/proxy#show
+                                         GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)          active_storage/representations/redirect#show
+                      rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                                       active_storage/disk#show
+               update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                               active_storage/disk#update
+                    rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                                    active_storage/direct_uploads#create
            rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                           action_mailbox/ingresses/postmark/inbound_emails#create
               rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                              action_mailbox/ingresses/relay/inbound_emails#create
            rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                           action_mailbox/ingresses/sendgrid/inbound_emails#create
@@ -17,13 +26,4 @@
    rails_conductor_inbound_email_sources POST   /rails/conductor/action_mailbox/inbound_emails/sources(.:format)                                  rails/conductor/action_mailbox/inbound_emails/sources#create
    rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                               rails/conductor/action_mailbox/reroutes#create
 rails_conductor_inbound_email_incinerate POST   /rails/conductor/action_mailbox/:inbound_email_id/incinerate(.:format)                            rails/conductor/action_mailbox/incinerates#create
-                      rails_service_blob GET    /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)                               active_storage/blobs/redirect#show
-                rails_service_blob_proxy GET    /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)                                  active_storage/blobs/proxy#show
-                                         GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                                        active_storage/blobs/redirect#show
-               rails_blob_representation GET    /rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations/redirect#show
-         rails_blob_representation_proxy GET    /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)    active_storage/representations/proxy#show
-                                         GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)          active_storage/representations/redirect#show
-                      rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                                       active_storage/disk#show
-               update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                               active_storage/disk#update
-                    rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                                    active_storage/direct_uploads#create
 "



bin/test test/commands/routes_test.rb:166

.F

Failure:
LoadingTest#test_descendants_loaded_after_framework_initialization_are_cleaned_on_each_request_without_cache_classes [/home/yahonda/src/github.com/rails/rails/railties/test/application/loading_test.rb:143]:
Expected: ["Post"]
  Actual: ["Post", "Post"]


bin/test test/application/loading_test.rb:112

.....................F

Failure:
ZeitwerkIntegrationTest#test_reloading_clears_autoloaded_tracked_classes [/home/yahonda/src/github.com/rails/rails/railties/test/application/zeitwerk_integration_test.rb:320]:
Expected: []
  Actual: [Child, Grandchild]


bin/test test/application/zeitwerk_integration_test.rb:293

..............F

Failure:
ApplicationTests::MailerPreviewsTest#test_mailer_preview_actions_are_added_and_removed [/home/yahonda/src/github.com/rails/rails/railties/test/application/mailer_previews_test.rb:228]:
Expected /<li><a\ href="\/rails\/mailers\/notifier\/bar">bar<\/a><\/li>/ to match # encoding: ASCII-8BIT
#    valid: true
"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>Mailer Previews</title>\n  <style>\n    body { background-color: #fff; color: #333; }\n\n    body, p, ol, ul, td {\n      font-family: helvetica, verdana, arial, sans-serif;\n      font-size:   13px;\n      line-height: 18px;\n    }\n\n    pre {\n      background-color: #eee;\n      padding: 10px;\n      font-size: 11px;\n      white-space: pre-wrap;\n    }\n\n    a { color: #000; }\n    a:visited { color: #666; }\n    a:hover { color: #fff; background-color:#000; }\n\n    h2 { padding-left: 10px; }\n\n    @media (prefers-color-scheme: dark) {\n      body {\n        background-color: #222;\n        color: #ececec;\n      }\n\n      pre {\n        background-color: #333;\n      }\n\n      a { color: #fff; }\n      a:visited { color: #999; }\n      a:hover { color: #000; background-color: #fff; }\n    }\n\n    \n  </style>\n</head>\n<body>\n\n<h3><a href=\"/rails/mailers/notifier\">Notifier</a></h3>\n<ul>\n<li><a href=\"/rails/mailers/notifier/foo\">foo</a></li>\n</ul>\n\n\n</body>\n</html>\n".


bin/test test/application/mailer_previews_test.rb:159

...................F

Failure:
ApplicationTests::MailerPreviewsTest#test_mailer_previews_are_reloaded_from_a_custom_preview_path [/home/yahonda/src/github.com/rails/rails/railties/test/application/mailer_previews_test.rb:296]:
Expected /<h3><a\ href="\/rails\/mailers\/notifier">Notifier<\/a><\/h3>/ to not match # encoding: ASCII-8BIT
#    valid: true
"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>Mailer Previews</title>\n  <style>\n    body { background-color: #fff; color: #333; }\n\n    body, p, ol, ul, td {\n      font-family: helvetica, verdana, arial, sans-serif;\n      font-size:   13px;\n      line-height: 18px;\n    }\n\n    pre {\n      background-color: #eee;\n      padding: 10px;\n      font-size: 11px;\n      white-space: pre-wrap;\n    }\n\n    a { color: #000; }\n    a:visited { color: #666; }\n    a:hover { color: #fff; background-color:#000; }\n\n    h2 { padding-left: 10px; }\n\n    @media (prefers-color-scheme: dark) {\n      body {\n        background-color: #222;\n        color: #ececec;\n      }\n\n      pre {\n        background-color: #333;\n      }\n\n      a { color: #fff; }\n      a:visited { color: #999; }\n      a:hover { color: #000; background-color: #fff; }\n    }\n\n    \n  </style>\n</head>\n<body>\n\n<h3><a href=\"/rails/mailers/notifier\">Notifier</a></h3>\n<ul>\n<li><a href=\"/rails/mailers/notifier/foo\">foo</a></li>\n</ul>\n\n\n</body>\n</html>\n".


bin/test test/application/mailer_previews_test.rb:258

..F

Failure:
ApplicationTests::MailerPreviewsTest#test_mailer_previews_are_reloaded_across_requests [/home/yahonda/src/github.com/rails/rails/railties/test/application/mailer_previews_test.rb:156]:
Expected /<h3><a\ href="\/rails\/mailers\/notifier">Notifier<\/a><\/h3>/ to not match # encoding: ASCII-8BIT
#    valid: true
"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>Mailer Previews</title>\n  <style>\n    body { background-color: #fff; color: #333; }\n\n    body, p, ol, ul, td {\n      font-family: helvetica, verdana, arial, sans-serif;\n      font-size:   13px;\n      line-height: 18px;\n    }\n\n    pre {\n      background-color: #eee;\n      padding: 10px;\n      font-size: 11px;\n      white-space: pre-wrap;\n    }\n\n    a { color: #000; }\n    a:visited { color: #666; }\n    a:hover { color: #fff; background-color:#000; }\n\n    h2 { padding-left: 10px; }\n\n    @media (prefers-color-scheme: dark) {\n      body {\n        background-color: #222;\n        color: #ececec;\n      }\n\n      pre {\n        background-color: #333;\n      }\n\n      a { color: #fff; }\n      a:visited { color: #999; }\n      a:hover { color: #000; background-color: #fff; }\n    }\n\n    \n  </style>\n</head>\n<body>\n\n<h3><a href=\"/rails/mailers/notifier\">Notifier</a></h3>\n<ul>\n<li><a href=\"/rails/mailers/notifier/foo\">foo</a></li>\n</ul>\n\n\n</body>\n</html>\n".


bin/test test/application/mailer_previews_test.rb:121

.......F

Failure:
ApplicationTests::QueryLogsTest#test_controller_and_job_tags_are_defined_by_default [/home/yahonda/src/github.com/rails/rails/railties/test/application/query_logs_test.rb:76]:
--- expected
+++ actual
@@ -1 +1 @@
-[:application, :job, :controller, :action]
+[:application, :controller, :action, :job]



bin/test test/application/query_logs_test.rb:71

..................../home/yahonda/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/sprockets-4.0.2/lib/sprockets/erb_processor.rb:25: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/home/yahonda/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/sprockets-4.0.2/lib/sprockets/erb_processor.rb:25: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
...............F

Failure:
RailtiesTest::EngineTest#test_don't_reverse_default_railties_order [/home/yahonda/src/github.com/rails/rails/railties/test/railties/engine_test.rb:182]:
Expected /Copied migration \d+_create_users\.core_engine\.rb from core_engine/ to match "Copied migration 20211124152450_create_keys.api_engine.rb from api_engine".


bin/test test/railties/engine_test.rb:150

...................

Finished in 46.717031s, 2.8041 runs/s, 8.6050 assertions/s.
131 runs, 402 assertions, 10 failures, 0 errors, 0 skips
$
```
### System configuration
**Rails version**: main branch

**Ruby version**:ruby 3.1.0dev (2021-11-24T14:06:28Z master 1dcfcb6bc5) [x86_64-linux]

### PR DESCRIPTION
**Pull request by casperisfine**
Fix: #43714

cc @yahonda 

Previously I assumed `DescendantTracker.clear` it was useless for ruby 3.1, however I was wrong.

The method is called by the reloader to give the illusion that the GC is precise. Meaning a class that will be unloaded is immediately made invisible without waiting for it to be garbage collected.

This is easy to do up to Ruby 3.0 because `DescendantTracker` keeps a map of all tracked classes.

However on 3.1 we need to use the inverse strategy, we keep a WeakMap of all the classes we cleared, and we filter the return value of `descendants` and `subclasses`.

Since `clear` is private API and is only used when reloading is enabled, to reduce the performance impact in production mode, we entirely remove this behavior when `config.cache_classes` is enabled.

### CODE REVIEW

File: activesupport/lib/active_support/descendants_tracker.rb [hunk 1]
```diff
@@ -17,8 +17,21 @@ def direct_descendants(klass)
       end
     end
 
-    if RubyFeatures::CLASS_DESCENDANTS
+    @clear_disabled = false
+
+    if RubyFeatures::CLASS_SUBCLASSES
+      @@excluded_descendants = ObjectSpace::WeakMap.new
```
Comment (casperisfine) [inline activesupport/lib/active_support/descendants_tracker.rb:23]: cc @eregon can I rely on `ObjectSpace::WeakMap` having weak keys on Truffle?

It seems like it doesn't (`truffleruby-21.2.0`):
```ruby
>> m = ObjectSpace::WeakMap.new
=> #<ObjectSpace::WeakMap:0x8668>
>> m[Object.new] = 42
=> 42
>> m.size
=> 1
>> 4.times { GC.start }
=> 4
>> m.size
=> 1
>> 4.times { GC.start }
=> 4
>> m.size
=> 1
```

whereas on MRI 3.0.2:
```ruby
>> m = ObjectSpace::WeakMap.new
=> #<ObjectSpace::WeakMap:0x00007feb039d5490>
>> m[Object.new] = 42
=> 42
>> m.size
=> 1
>> 4.times { GC.start }
=> 4
>> m.size
=> 0
```

I know it's not exactly public API, but it's so much more useful that dealing with `WeakRef`...

File: activesupport/lib/active_support/descendants_tracker.rb [hunk 2]
```diff
@@ -27,19 +40,32 @@ def descendants(klass)
           klass.descendants
         end
 
-        def clear(only: nil) # :nodoc:
-          # noop
+        def clear(classes) # :nodoc:
```
Comment (casperisfine) [inline activesupport/lib/active_support/descendants_tracker.rb:43]: The only usage left pass `only:` and it's private API, so might as well only support that.

**Comment by casperisfine** [comment]
ruby-head tests are now fully green.

I'll wait a bit to see @eregon's answer about Truffle compat, but given my quick testing I'm afraid I might need to find another solution for Truffle.

File: activesupport/lib/active_support/descendants_tracker.rb (hunk 1 above)
Comment (eregon) [reply activesupport/lib/active_support/descendants_tracker.rb:23]: On TruffleRuby `ObjectSpace::WeakMap` only has weak values, not keys.
It's essentially not possible to have both weak keys and weak values on JVM AFAIK, and it's same semantics on JRuby.
`ObjectSpace::WeakMap` is under-specified and it's unclear how it works on CRuby (I once asked and it seems nobody knew), but for portability one needs to consider only `ObjectSpace::WeakMap` values are weak, keys are strong.

If you want/need a map with weak keys, I think it needs to be introduced as a new, separate class.

Comment (casperisfine) [reply activesupport/lib/active_support/descendants_tracker.rb:23]: Ok, that's what I though, thanks for confirming. I think this solution is good for MRI, but it could cause leaks in dev mode for Truffle/JRuby. 

I suppose I could just store them in values, I'd just need to find some key that's unique and won't use memory.

Do you know if `object_id` guaranteed to be unique on Truffle/JRuby? Or at least if it's unique enough to be used in this dev scenario?

Comment (eregon) [reply activesupport/lib/active_support/descendants_tracker.rb:23]: `object_id` is unique on TruffleRuby, it's simply an atomic long incremented for every object which needs an `object_id`.
(it needs to be unique for `ObjectSpace._id2ref`, but _id2ref is really slow and should not be used).

Comment (casperisfine) [reply activesupport/lib/active_support/descendants_tracker.rb]: Ok, I added a different codepath for Jruby/Truffle. Unfortunately I don't see any decent way to feature test this, so I check `RUBY_ENGINE`.

Comment (eregon) [reply activesupport/lib/active_support/descendants_tracker.rb]: I would suggest to do `if RUBY_ENGINE != "ruby"`, it seems unlikely other Ruby implementations would admit the complexity of having a map of both weak keys and weak values for the GC implementation.

JRuby does have the semantics of weak values only: https://github.com/jruby/jruby/blob/03695f40d1c954cfdcbcef1e433b76e5d16ff068/core/src/main/java/org/jruby/RubyObjectSpace.java#L318

Longer term I think adding `WeakKeysMap` and `WeakValuesMap` (or just use `ObjectSpace::WeakMap`) to Ruby would be best: https://bugs.ruby-lang.org/issues/16038#note-14

Comment (casperisfine) [reply activesupport/lib/active_support/descendants_tracker.rb]: > I would suggest to do if RUBY_ENGINE != "ruby"

Make sense. I did that and added a bit more doc about what the hell is happening.

> Longer term I think adding WeakKeysMap and WeakValuesMap (or just use ObjectSpace::WeakMap) to Ruby would be best: https://bugs.ruby-lang.org/issues/16038#note-14

Agreed, but that wasn't really the point of that ticket, it only derived there. Originally what I was asking for was equality semantic, but maybe both subjects can be handled in the same ticket.

Either way thanks for the Truffle info!

File: activesupport/lib/active_support/descendants_tracker.rb [hunk 3]
```diff
@@ -17,8 +17,44 @@ def direct_descendants(klass)
...
+          end
+
+          def [](object)
+            @map.key?(object.object_id)
+          end
+
+          def []=(object, _present)
+            @map[object_id] = object
+          end
+        end
```
Comment (jonathanhefner) [inline activesupport/lib/active_support/descendants_tracker.rb:45]: I think this may need a `WeakSet.new` after this line.  Or am I misreading?

Comment (byroot) [reply activesupport/lib/active_support/descendants_tracker.rb:45]: No you are right I'm an idiot -_-

Comment (byroot) [reply activesupport/lib/active_support/descendants_tracker.rb:45]: https://github.com/rails/rails/commit/ff5e909b635bdc6ec0f915e101a44281dfd30b97

**Comment by headius** [comment]
Long time since this landed but we just got a bug report about slow performance in this logic.

Back then, @eregon stated:

> On TruffleRuby ObjectSpace::WeakMap only has weak values, not keys.
> It's essentially not possible to have both weak keys and weak values on JVM AFAIK, and it's the same semantics on JRuby.

This is not true; there's nothing preventing JVM-based apps from having a map with both weak keys and weak values. However the JDK does not currently provide such an implementation.

JRuby itself ships a Java collection with weak keys (used to implement WeakKeyMap), and it's a small leap from there to have both weak keys and weak values. But currently JRuby behavior does match TruffleRuby, providing weak values in ObjectSpace::WeakMap and weak keys in ObjectSpace::WeakKeyMap.

It would be good to revisit this soon and switch the logic to using the now-standard WeakKeyMap which was eventually added to CRuby in 3.3 (https://github.com/ruby/ruby/pull/5570).

Also, FWIW, if JRuby and TruffleRuby did start emulating the "weak keys and values" behavior of WeakMap, the existing workaround code would be hopelessly broken: the `object_id` keys it uses today would be almost immediately collected and the collection entry removed.
