### PR TITLE
Fix issue with expression index in insert_all

### LINKED ISSUE #39516: Expression index raises error when used in insert_all unique_by option
### Steps to reproduce
1. Create an expression index to be used in an `insert_all` or `upsert_all`.
2. Use the index name in the `unique_by` option.

```ruby
# Example table
create_table :books, id: :integer, force: true do |t|
  t.column :name, :string
  t.index "lower(name)", unique: true
end

# Usage
Book.insert_all [{ name: "MyTest" }], unique_by: :index_books_on_lower_name
```

PR with test case: #39517

### Expected behavior
https://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-insert_all

Based on the docs which state one can use the index name if desired, one would expect the method to work normally and use the `unique_by` option to determine duplicates.

### Actual behavior
```
Error:
InsertAllTest#test_insert_all_and_upsert_all_with_expression_index:
NoMethodError: undefined method `map' for "lower(name)":String
```
https://github.com/rails/rails/blob/9734dfa1a1a2d5909652dcbb80947a92ce42c431/activerecord/lib/active_record/insert_all.rb#L157

By this point, the code expects `index.columns` to be mapped to an Set representing either a single column or a composite column index. However, in the case of a expression index, `index.columns` is a string that represents the expression!

### System configuration
**Rails version**: 6.0.3.1

**Ruby version**: 2.6.6

### PR DESCRIPTION
**Pull request by austenmadden**
### Summary

#39516

Based on the docs which state unique_by option of insert_all can use the
index name if desired, one would expect the method to work normally and
use the `unique_by` option to determine duplicates.

However, there's an issue where the insert_all expects a Set instead
of the string representing the index expression it is given. This causes
an error. Returning the string expression instead of attempting to
format it works perfectly though.

### CODE REVIEW

File: activerecord/lib/active_record/insert_all.rb [hunk 1]
```diff
@@ -195,7 +195,7 @@ def extract_types_from_columns_on(table_name, keys:)
           end
 
           def format_columns(columns)
-            quote_columns(columns).join(",")
+            columns.is_a?(Enumerable) ? quote_columns(columns).join(",") : columns
```
Comment (eugeneius) [inline activerecord/lib/active_record/insert_all.rb:198]: We generally check for the method we intend to call rather than the type:

```suggestion
            columns.respond_to?(:map) ? quote_columns(columns).join(",") : columns
```

**Review by eugeneius — COMMENTED** [review]
This is great, thank you! Would you mind [adding a changelog entry](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#updating-the-changelog) and [squashing your commits](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits)?

**Comment by eugeneius** [comment]
Thank you! 💛
