### PR TITLE
Fix `insert_all` to not update existing records

### LINKED ISSUE #53753: MySQL insert_all can actually update duplicates
### Steps to reproduce
On ActiveRecord 8.0 with MySQL, and using MySQL 8.0 server, `insert_all` with `skip_duplicates?` on attempts to find a `no_op_column` by simply picking the first key in the insert object hash, which it then uses for a `ON DUPLICATE KEY UPDATE` clause. If you build your insert objects in such a way that the first key in the hash isn't part of the unique key then that column will get updated if you attempt to insert a duplicate, even though that's not the documented behavior.

TODO: I'm going to put together a test case as soon as I have some time, but wanted to put this up ASAP.

```ruby
# Your reproduction script goes here
```

### Expected behavior
The `insert_all` bulk insert should not perform any updates with the default `skip_duplicates` enabled.

### Actual behavior
The column of the first key in the hash for a constructed object to insert is updated if a duplicate already exists for that row.

### System configuration
**Rails version**: 8.0.0

**Ruby version**: 3.3.5

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #53753.

Because MySQL does not support `ON CONFLICT DO NOTHING` syntax (like PostgreSQL or SQLite), we need to use hacks like assigning the column to itself. Previously it was done that way, but was erroneously changed in https://github.com/rails/rails/pull/51274/files#diff-868f1dccfcbed26a288bf9f3fd8a39c863a4413ab0075e12b6805d9798f556d1R650 to assign to the new value from `VALUES`.

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb [hunk 1]
```diff
@@ -628,24 +628,26 @@ def default_index_type?(index) # :nodoc:
...
         # then MySQL 8.0.20 deprecates the `VALUES(<expression>)` see https://dev.mysql.com/worklog/task/?id=13325 .
         if supports_insert_raw_alias_syntax?
+          quoted_table_name = insert.model.quoted_table_name
           values_alias = quote_table_name("#{insert.model.table_name.parameterize}_values")
           sql = +"INSERT #{insert.into} #{insert.values_list} AS #{values_alias}"
 
           if insert.skip_duplicates?
             if no_op_column
-              sql << " ON DUPLICATE KEY UPDATE #{no_op_column}=#{values_alias}.#{no_op_column}"
+              sql << " ON DUPLICATE KEY UPDATE #{quoted_table_name}.#{no_op_column}=#{quoted_table_name}.#{no_op_column}"
```
Comment (kamipo) [inline activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:643]: How about just changing the right hand side?
This is only line that qualified the left hand side of the assignment in this method.

```suggestion
              sql << " ON DUPLICATE KEY UPDATE #{no_op_column}=#{quoted_table_name}.#{no_op_column}"
```
