### PR TITLE
Set correct host except development environment

### LINKED ISSUE #28184: Rails 5.1.0.beta1 crashes on Heroku (cedar-14 or heroku-16). (v5.0.1 instead works fine). Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
### Expected behavior
I was on Rails 5.0.1 and everything fine on my PC and on Heroku.
Today I upgraded just my Gemfile like this:

```
gem 'rails', '~> 5.0.1'
gem 'rails', '~> 5.1.0.beta1'
```

and in my local PC everything fine, but on my Heroku (cedar-14 or heroku-16 stack) I have this errors:

```
Feb 26 06:05:17 myApp heroku/web.1:  Starting process with command `bin/rails server -p 58126 -e production` 
Feb 26 06:05:22 myApp app/web.1:  => Booting Puma 
Feb 26 06:05:22 myApp app/web.1:  => Rails 5.1.0.beta1 application starting in production on http://localhost:58126 
Feb 26 06:05:22 myApp app/web.1:  => Run `rails server -h` for more startup options 
Feb 26 06:05:22 myApp app/web.1:  Puma starting in single mode... 
Feb 26 06:05:22 myApp app/web.1:  * Version 3.7.1 (ruby 2.4.0-p0), codename: Snowy Sagebrush 
Feb 26 06:05:22 myApp app/web.1:  * Min threads: 5, max threads: 5 
Feb 26 06:05:22 myApp app/web.1:  * Environment: production 
Feb 26 06:05:22 myApp app/web.1:  * Listening on tcp://localhost:58126 
Feb 26 06:05:22 myApp app/web.1:  Use Ctrl-C to stop 
Feb 26 06:06:05 myApp app/heroku-redis:  source=REDIS sample#active-connections=2 sample#load-avg-1m=0.065 sample#load-avg-5m=0.05 sample#load-avg-15m=0.045 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664468.0kB sample#memory-free=12804672.0kB sample#memory-cached=966624kB sample#memory-redis=310128bytes sample#hit-rate=0 sample#evicted-keys=0 
Feb 26 06:06:18 myApp heroku/web.1:  Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch 
Feb 26 06:06:18 myApp heroku/web.1:  Stopping process with SIGKILL 
Feb 26 06:06:18 myApp heroku/web.1:  Process exited with status 137 
Feb 26 06:06:18 myApp heroku/web.1:  State changed from starting to crashed 
```

If I revert the commit with my 5.0.1 Gemfile everything works.

Also this guy have the problem:

http://es.stackoverflow.com/questions/51759/problemas-con-heroku-ruby

**How to fix this?**

**Ruby version**: 2.4

### PR DESCRIPTION
**Pull request by y-yagi**
Currently `localhost` is used for the default host in all environments.
But up to Rails 5.0, `0.0.0.0` is used except for development.
So fixed to use the same value as 5.0.

Fixes #28184

### CODE REVIEW

File: railties/lib/rails/commands/server/server_command.rb [hunk 1]
```diff
@@ -99,7 +99,7 @@ class ServerCommand < Base # :nodoc:
 
       class_option :port, aliases: "-p", type: :numeric,
         desc: "Runs Rails on the specified port.", banner: :port, default: 3000
-      class_option :binding, aliases: "-b", type: :string, default: "localhost",
```
Comment (y-yagi) [inline railties/lib/rails/commands/server/server_command.rb]: I removed the default value. This is because the default value varies depending on the environment.

Comment (pixeltrix) [inline railties/lib/rails/commands/server/server_command.rb]: You could add to the description of the option that it defaults to localhost in development and 0.0.0.0 in all other environments, e.g:

``` ruby
class_option :binding, aliases: "-b", type: :string,
  desc: "Binds Rails to the specified IP - defaults to 'localhost' in development and '0.0.0.0' in other environments'.", banner: :IP

```

Comment (y-yagi) [inline railties/lib/rails/commands/server/server_command.rb]: Thanks! I updated.

**Comment by pixeltrix** [comment]
@y-yagi thanks! 👍

**Comment by schneems** [comment]
thanks a ton!
