### PR TITLE
specify minimum capybara version for system tests

### LINKED ISSUE #30952: cannot load such file -- capybara/minitest (LoadError)
### Steps to reproduce

We have Capybara locked at version 2.7.1 and see the error below when trying to require system tests. Will we be unable to load system tests until we can upgrade Capybara? Related to [this issue on the rspec-rails gem](https://github.com/rspec/rspec-rails/issues/1889#issuecomment-338520428).

```
/home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- capybara/minitest (LoadError)
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/system_test_case.rb:2:in `<top (required)>'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/fletch/scratch/rspec-rails/lib/rspec/rails/example/system_example_group.rb:28:in `<top (required)>'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/fletch/scratch/rspec-rails/lib/rspec/rails/example.rb:11:in `<top (required)>'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/fletch/scratch/rspec-rails/lib/rspec/rails.rb:13:in `<top (required)>'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/fletch/Dropbox/projects/chalk/synchroform/spec/rails_helper.rb:35:in `<top (required)>'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `require'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `block in requires='
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `each'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `requires='
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:111:in `each'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:99:in `setup'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:86:in `run'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:71:in `run'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/fletch/.rvm/gems/ruby-2.4.2/gems/rspec-core-3.7.0/exe/rspec:4:in `<top (required)>'
	from /home/fletch/.rvm/gems/ruby-2.4.2/bin/rspec:23:in `load'
	from /home/fletch/.rvm/gems/ruby-2.4.2/bin/rspec:23:in `<main>'
	from /home/fletch/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/fletch/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

### Expected behavior
Tests should run.

### Actual behavior
An error is thrown.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.2

### PR DESCRIPTION
**Pull request by lostapathy**
Resolves #30952

Upgraded rails applications may have a Gemfile without a new enough capybara to run system tests.  Setting a version here gives the user a more direct error message than they get otherwise.

### CODE REVIEW

File: actionpack/lib/action_dispatch/system_test_case.rb [hunk 1]
```diff
@@ -1,5 +1,7 @@
 # frozen_string_literal: true
 
+gem "capybara", "~> 2.13"
```
Comment (twalpole) [inline actionpack/lib/action_dispatch/system_test_case.rb]: This has a side effect of users not being able to update to Capybara 3 when it releases, since the requirement is in non user modifiable source.  Wouldn't it be better as `gem "capybara", ">= 2.13"` in this file?

Comment (lostapathy) [reply actionpack/lib/action_dispatch/system_test_case.rb]: I submitted it this way as that's what was requested on #30952.  I'm assuming the preferred convention here is to match rubygem's preference that open-ended dependencies are to be avoided.

Comment (rafaelfranca) [reply actionpack/lib/action_dispatch/system_test_case.rb]: It is fine to not allow update to capybara 3 since rails may not work with that version, but yeah, it should be 2.15. I'll update it.

Comment (twalpole) [reply actionpack/lib/action_dispatch/system_test_case.rb]: @rafael It will work with 3 since 3 is just going to be a remove deprecations and drop ruby versions release.  However, this is adding a requirement just for a warning in a non user editable file - The more restrictive requirement in the Gemfile generated for an app is correct, and where the actual restriction should be (and users can modify that when Capybara 3 is released).  I really feel this should be `>= 2.15` in this file.

Comment (MrHubble) [reply actionpack/lib/action_dispatch/system_test_case.rb]: @twalpole so I should be good to use `gem 'capybara', '~> 3.0.2', '< 4.0'` in my Rails 5.1 app? I'm experiencing https://github.com/rails/rails/issues/30952

Comment (twalpole) [reply actionpack/lib/action_dispatch/system_test_case.rb]: @MrHubble If you're using Rails 5.1 you should be able to use `gem 'capybara', '~> 2.18'` in your gem file since Rails 5.1 won't allow Capybara 3+ due to  this change (if you're using system tests).  With Rails 5.2 you should be good to use `gem 'capybara', `~> 3.0`` (note that specifying the `<4.0` is unnecessary due to the the way `~>` works

Comment (MrHubble) [reply actionpack/lib/action_dispatch/system_test_case.rb]: Great. Thanks so much for taking the time to clarify.
