### PR TITLE
Sets default mailer queue to default

### LINKED ISSUE #40846: Use 'default' as default queue for assert_enqueued_email_with for 6.1
### Steps to reproduce
Configuration problem with assert_enqueued_email_with, now default queue for 6.1 has been changed, so we need to change default value for this assertion as well

### Expected behavior
`assert_enqueued_email_with Mailer` should not require `queue` for default settings

### Actual behavior
`assert_enqueued_email_with Mailer` does not find actual job

### System configuration
**Rails version**: 6.1

**Ruby version**: 2.7

# NOTE: Working on the fix

### PR DESCRIPTION
**Pull request by pftg**
Fixes: #40846

### CODE REVIEW

**Comment by pftg** [comment]
@rafaelfranca  please check, this extends your previous pull request #40766

/cc @georgeclaghorn

File: actionmailer/lib/action_mailer/test_helper.rb [hunk 1]
```diff
@@ -123,7 +123,7 @@ def assert_enqueued_emails(number, &block)
     #       ContactMailer.with(email: 'user@example.com').welcome.deliver_later
     #     end
     #   end
-    def assert_enqueued_email_with(mailer, method, args: nil, queue: "mailers", &block)
+    def assert_enqueued_email_with(mailer, method, args: nil, queue: "default", &block)
```
Comment (pftg) [inline actionmailer/lib/action_mailer/test_helper.rb:126]: For simplicity purpose, I have not use default_queue_name, because then we need to support prefixes and other queue name computations. So for now it's simple enough.

But if you think then maybe ActionMailer::Base.default_queue_name as default will reduce duplication (a little) I could just use it

**Comment by pftg** [comment]
@kamipo could you check this

File: actionmailer/lib/action_mailer/delivery_methods.rb [hunk 2]
```diff
@@ -12,7 +12,7 @@ module DeliveryMethods
       # Do not make this inheritable, because we always want it to propagate
       cattr_accessor :raise_delivery_errors, default: true
       cattr_accessor :perform_deliveries, default: true
-      cattr_accessor :deliver_later_queue_name, default: :mailers
+      cattr_accessor :deliver_later_queue_name, default: :default
```
Comment (rafaelfranca) [inline actionmailer/lib/action_mailer/delivery_methods.rb:15]: We can't change this value. This will change the default value for all the applications that don't want to opt-in for the Rails 6.1 defaults.

File: actionmailer/lib/action_mailer/test_helper.rb (hunk 1 above)
Comment (rafaelfranca) [inline actionmailer/lib/action_mailer/test_helper.rb:126]: I think the right fix is to change this to use the computed value based on the config.

**Review by rafaelfranca — CHANGES_REQUESTED** [review]

File: actionmailer/lib/action_mailer/delivery_methods.rb (hunk 2 above)
Comment (pftg) [reply actionmailer/lib/action_mailer/delivery_methods.rb]: @rafaelfranca when we use `deliver_later_queue_name` then delivery jobs got `mailers` queue instead of `default`. So I have to change the default configuration from `nil` to `:default`

Comment (pftg) [reply actionmailer/lib/action_mailer/delivery_methods.rb]: I'm checking other options to set `default` for `deliver_later_queue_name = nil`

Comment (pftg) [reply actionmailer/lib/action_mailer/delivery_methods.rb]: my bad, removed

**Comment by pftg** [comment]
@rafaelfranca thanks for the review, added updates. Removed unrelated issues, will finish them in separate PR

File: actionmailer/lib/action_mailer/test_helper.rb [hunk 3]
```diff
@@ -123,7 +123,7 @@ def assert_enqueued_emails(number, &block)
     #       ContactMailer.with(email: 'user@example.com').welcome.deliver_later
     #     end
     #   end
-    def assert_enqueued_email_with(mailer, method, args: nil, queue: "mailers", &block)
+    def assert_enqueued_email_with(mailer, method, args: nil, queue: ActionMailer::Base.delivery_job.new.queue_name, &block)
```
Comment (pftg) [inline actionmailer/lib/action_mailer/test_helper.rb:126]: @rafaelfranca  the problem that `ActionMailer::Base.delivery_job.queue_name` does not return the same value as `ActionMailer::Base.delivery_job.new.queue_name`. I'll handle it in separate issue

File: actionmailer/lib/action_mailer/delivery_methods.rb (hunk 2 above)
Comment (pftg) [reply actionmailer/lib/action_mailer/delivery_methods.rb]: My bad, removed it

File: actionmailer/lib/action_mailer/test_helper.rb (hunk 1 above)
Comment (pftg) [reply actionmailer/lib/action_mailer/test_helper.rb]: Updated

File: actionmailer/lib/action_mailer/test_helper.rb (hunk 3 above)
Comment (rafaelfranca) [reply actionmailer/lib/action_mailer/test_helper.rb:126]: We only care about `ActionMailer::Base.deliver_later_queue_name`. If people configured a different job with a different queue than `ActionMailer::Base.deliver_later_queue_name` they should pass the `queue:` argument explicitly.

Can you change this method to use `ActionMailer::Base.deliver_later_queue_name`?

Comment (pftg) [reply actionmailer/lib/action_mailer/test_helper.rb:126]: @rafaelfranca `ActionMailer::Base.deliver_later_queue_name` returns `mailers` instead of `default` because `action_mailer.deliver_later_queue_name = nil` does not change it to  to `default`. That what I wanted to fix in separate or. Should I change default from `action_mailer.deliver_later_queue_name = nil` to `action_mailer.deliver_later_queue_name = :default`

This will change documentation and release notes, what do you think?

Comment (rafaelfranca) [reply actionmailer/lib/action_mailer/test_helper.rb:126]: > ActionMailer::Base.deliver_later_queue_name returns mailers instead of default when action_mailer.deliver_later_queue_name = nil.

Isn't that the expected behavior. If `deliver_later_queue_name` is `nil` this method should use `:mailers`, not default. It should only use `:default` if `action_mailer.deliver_later_queue_name = :default`.

Comment (rafaelfranca) [reply actionmailer/lib/action_mailer/test_helper.rb:126]: oh. that is right, we want the opposite. But how `deliver_later_queue_name` returns `:mailers` if the value is `nil`? If should only return `:mailers` if the setter was not called.

Comment (pftg) [reply actionmailer/lib/action_mailer/test_helper.rb:126]: 1. Based on https://github.com/rails/rails/issues/40730#issuecomment-737504985 I thought that you wanted to use  `default` queue instead of `mailers`
2. For the same settings `ActionMailer::Base.delivery_job.new.queue_name` returns `default` (which MailerJob use as queue name), but `ActionMailer::Base.deliver_later_queue_name` returns `mailers`

Comment (pftg) [reply actionmailer/lib/action_mailer/test_helper.rb:126]: I'll check why we have a different queue name in this issue, so then I'll fix 2 problems in one PR, if this ok

Comment (rafaelfranca) [reply actionmailer/lib/action_mailer/test_helper.rb:126]: Yes, it is fine to fix the issue in the same PR, but if we set `ActionMailer::Base.deliver_later_queue_name` to `nil` it should return `nil`.

Comment (pftg) [reply actionmailer/lib/action_mailer/test_helper.rb:126]: @rafaelfranca could you confirm that the default queue should be `default` (like it works now) (based on https://github.com/rafaelfranca/omg-rails/commit/39304496ac597c98c12981e477760f6b0e1ab04b#diff-614a0b9e89499dcd4783283bb2b1b578567aae98e5c221b5fedfd76c3a4dc1ef) instead of `mailers`.

Some thoughts:
If `ActionMailer::Base.deliver_later_queue_name => nil` then we definitely could not use it as default value for `queue: ` arg

Comment (rafaelfranca) [reply actionmailer/lib/action_mailer/test_helper.rb:126]: It should be `:defaults` only if `config.action_mailer.deliver_later_queue_name` is set to `nil` (Rails 6.1 default). If nothing is set it should be `:mailers` (Rails < 6.1 default).

> If ActionMailer::Base.deliver_later_queue_name => nil then we definitely could not use it as default value for queue: arg.

We can use queue: `queue: ActionMailer::Base.deliver_later_queue_name || "defaults"`.

**Comment by pftg** [comment]
@rafaelfranca thanks for the feedback (you prevented many problems). I added updates. Please check when you will have time.

**Review by rafaelfranca — APPROVED** [review]
