### PR TITLE
Fix `Enumerable#sole` when element is a tuple

### LINKED ISSUE #55807: `Enumerable#sole` returns only the first element of tuples
### Steps to reproduce

As of Rails 8.0.3:
```ruby
Rails::VERSION::STRING
# => "8.0.3"

enum = Enumerator.new(1) do |yielder|
  yielder.yield(1, "one")
end

enum.first
# => [1, "one"]

enum.rewind

enum.sole
# => 1
```

### Expected behavior

`Enumerable#sole` should return the full tuple, and the same value as `Enumerable#first`. This was the case prior to Rails 8.0.3:
```ruby
Rails::VERSION::STRING
# => "8.0.2.1"

enum = Enumerator.new(1) do |yielder|
  yielder.yield(1, "one")
end

enum.first
# => [1, "one"]

enum.rewind

enum.sole
# => [1, "one"]
```

### Actual behavior

#54341 changed the behavior of `Enumerable#sole`, causing it to only return the first element of tuples instead of the full tuple.

### System configuration

**Rails version**: 8.0.3

**Ruby version**: 3.4.4

### PR DESCRIPTION
**Pull request by olivier-thatch**
### Motivation / Background

This Pull Request has been created because #54341 introduced a behavior change for `Enumerable#sole` when the sole element is a tuple.

Previously, `Enumerable#sole` would return the full tuple (same as `Enumerable#first`). #54341 changed the behavior so that `Enumerable#sole` only returns the first element of the tuple.

Fixes #55807.

### Detail

This Pull Request changes `Enumerable#sole` to return the full tuple, i.e. the same value as `Enumerable#first`.

### Additional information

-

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [X] Tests are added or updated if you fix a bug or add a feature.
* [X] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activesupport/lib/active_support/core_ext/enumerable.rb [hunk 1]
```diff
@@ -212,12 +212,12 @@ def sole
     result = nil
     found = false
 
-    each do |element|
+    each do |*element|
```
Comment (byroot) [inline activesupport/lib/active_support/core_ext/enumerable.rb:215]: I fear this may have a similar issue with keyword arguments, but I need to try a few things.

**Comment by matthewd** [comment]
I imagine this would now break `[[1]].sole` too 😕

**Comment by byroot** [comment]
> I imagine this would now break `[[1]].sole` too 😕

Nope.

File: activesupport/test/core_ext/enumerable_test.rb [hunk 2]
```diff
@@ -401,6 +401,26 @@ def test_sole
...
+    def each
+      yield 1, two: 3
+    end
+  end
+
+  def test_sole_keyword_arguments
+    yielder = KeywordYielder.new
+    assert_equal [1, {two: 3}], yielder.sole
+    assert_equal yielder.first, yielder.sole
+  end
```
Comment (byroot) [inline activesupport/test/core_ext/enumerable_test.rb:422]: I pushed an extra test to make sure `*arguments` do also collect keyword args.

**Comment by byroot** [comment]
Thanks for the fix, backported to 8-0-stable, and 7-2-stable.

**Comment by olivier-thatch** [comment]
Thanks for the quick merge!
