### PR TITLE
Fix plugin generation inside applications

### LINKED ISSUE #18073: "rails generate plugin gems/engine --full" fails at vendor_app test/dummy
# inside a new rails named "app"

$ rails generate plugin gems/engine --full
      create
      create  README.rdoc
...
  vendor_app  test/dummy
Invalid application name app, constant App is already in use. Please choose another application name.

### PR DESCRIPTION
**Pull request by skipkayhil**
### Motivation / Background

Previously, generating a plugin inside an application would throw an error when trying to create a dummy_app due to the generator trying to reuse the application's name.

### Detail

This is fixed by extracting the logic used to determine the source of an application's name, and then only using the existing name as the source for the app:update and db:change tasks.

### Additional information

Closes #45824
Fixes #18073

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] There are no typos in commit messages and comments.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Feature branch is up-to-date with `main` (if not - rebase it).
* [x] Pull request only contains one commit for bug fixes and small features. If it's a larger feature, multiple commits are permitted but must be descriptive.
* [x] Tests are added if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [x] PR is not in a draft state.
* [ ] CI is passing.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
We have a failing test because of this change. Can you take a look?

File: railties/test/generators/db_system_change_generator_test.rb [hunk 1]
```diff
@@ -79,7 +79,7 @@ class ChangeGeneratorTest < Rails::Generators::TestCase
 
             assert_file("config/database.yml") do |content|
               assert_match "adapter: mysql2", content
-              assert_match "database: test_app", content
+              assert_match "database: tmp_production", content
```
Comment (skipkayhil) [inline railties/test/generators/db_system_change_generator_test.rb:82]: In a real application, `Rails.application` throws a `NoMethodError` when `bin/rails db:system:change` is run. So instead of keeping the `Rails.application.class... || File.basename` for the Change Generator I think it makes more sense for the tests to reflect the real behavior (always `File.basename`, which is `/tmp` for these tests)

Comment (rafaelfranca) [reply railties/test/generators/db_system_change_generator_test.rb:82]: But how was this passing before?

Comment (skipkayhil) [reply railties/test/generators/db_system_change_generator_test.rb:82]: The `Rails.application.class...` path was hit before because the generator test requires `generators/generators_test_helper` -> `abstract_unit` which requires `rails/all` and defines `TestApp::Application` -> sets `Rails.application`.

In the `bin_setup_test`/real application case, `config/application.rb` is never required during `bin/rails db:system:change` so it never sets `Rails.application`.
