### PR TITLE
remove redis reconnect_attempts

### LINKED ISSUE #46149: Broken defaults for redis_cache_store (reset redis connection)
Default behavior of `RedisCacheStore` is to not establish a connection. This is unintuitive default behavior.

I think the following issues are directly related:
https://github.com/rails/rails/issues/37854
https://github.com/rails/rails/issues/43767
https://github.com/rails/rails/issues/43422
https://github.com/rails/rails/issues/43082
https://github.com/rails/rails/issues/42818

Downstream effects also include accidental `nil` sessions when both of the following are configured:
```ruby
config.cache_store = :redis_cache_store
config.session_store :cache_store, key: ENV['APP_SESSION_KEY']
```
This is due to what I'd think would be a reasonable expectation ([which rails core code holds](https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/middleware/session/cache_store.rb#L55)) of expecting a cache.read to read from the cache instead of failing silently.

Odd, but noteworthy:
- ~redis-rb/redis-client has a [default reconnect attempt of 2](https://github.com/redis-rb/redis-client/blob/8c00763177f94c63a4c8f8e57410c2f147235758/lib/redis_client/sentinel_config.rb#L8)~ (edit: this is incorrect, thanks @byroot)
- redis/redis-rb/ overrides this the default with [a reconnect attempt of 1](https://github.com/redis/redis-rb/blob/3037564001edb36a839b41b577c83241c85121a8/lib/redis.rb#L66)
- rails' redis_cache_store overrides this with [a reconnect attempt of 0](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/cache/redis_cache_store.rb#L42)

Can we just change this default to 1 or 2? It will have no effect on the method signature or default error handling behavior.

### Steps to reproduce
```ruby
# application.rb
config.cache_store = :redis_cache_store
```

```ruby
Rails.cache.write('foo', 'bar')
# restart redis
Rails.cache.read('foo', 'bar')
Rails.cache.read('foo', 'bar')
```

### Expected behavior
```
"bar"
"bar"
```

### Actual behavior

```
nil
"bar"
```
cache-miss

### System configuration
**Rails version**: Rails 7.0.4

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin19.6.0]

### PR DESCRIPTION
**Pull request by hsachdeva01**
Fix: https://github.com/rails/rails/issues/46149

### Motivation / Background

This Pull Request has been created because by default `RedisCacheStore` does not establish a connection. The cache store does not attempt to reconnect to Redis if the connection fails during a request, which causes it to return a `nil` value. 

### Detail

1. This Pull Request removes the override of `reconnect_attempts: 0` line from the redis_cache_store. The spec has been updated accordingly as well. 
2. This PR also reduces the `connect_timeout` from 20 seconds to 1 second because 20 seconds is massive when combined with 1 second on `read_timeout`. Thank you @byroot   
 
Relates to: #46149

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] There are no typos in commit messages and comments.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Feature branch is up-to-date with `main` (if not - rebase it).
* [x] Pull request only contains one commit for bug fixes and small features. If it's a larger feature, multiple commits are permitted but must be descriptive.
* [x] Tests are added if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [x] PR is not in a draft state.
* [x] CI is passing.

### CODE REVIEW

File: activesupport/lib/active_support/cache/redis_cache_store.rb [hunk 1]
```diff
@@ -39,7 +39,6 @@ class RedisCacheStore < Store
         connect_timeout:    20,
```
Comment (byroot) [inline activesupport/lib/active_support/cache/redis_cache_store.rb:39]: While we're at it, a 20 seconds connect timeout is stupidly massive, and make little sense when combined with a 1 second read timeout. Might as well reduce it too.

Comment (byroot) [reply activesupport/lib/active_support/cache/redis_cache_store.rb:39]: No, 1 seconds is plenty.

File: activesupport/test/cache/stores/redis_cache_store_test.rb [hunk 2]
```diff
@@ -46,27 +46,29 @@ class LookupTest < ActiveSupport::TestCase
...
+        connect_timeout: 1, read_timeout: 1, write_timeout: 1
       ] do
         build url: []
       end
     end
 
+    test "client attempts to reconnect with default settings" do
+      client = build.redis.instance_variable_get(:@client)
+      assert client.config.retry_connecting?(0, nil)
+    end
```
Comment (byroot) [inline activesupport/test/cache/stores/redis_cache_store_test.rb:66]: Let's not test private APIs like this. We don't need that test anyway.

**Comment by byroot** [comment]
Please squash your commits into a single one, and I'm good.
