### PR TITLE
[Fix #49055] Raise an `ArgumentError` when `#accepts_nested_attributes_for` is redeclared for an association

### LINKED ISSUE #49055: `#accepts_nested_attributes_for` does not raise an error when redeclaring for an association
### Steps to reproduce

I had to hunt down a weird bug in our Rails app and it turned out that `accepts_nested_attributes_for` had been redeclared for an association with different options (exactly like in the script below). This resulted in the association writer method defined during the second declaration to get utilised instead of the first (I'm unsure yet if it's duplicated or overridden), which is not surprising considering the ordering, but unexpected if you're unaware that the declaration was duplicated.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  accepts_nested_attributes_for :comments, update_only: true
  accepts_nested_attributes_for :comments # I feel like this should raise an error on load
end

class Comment < ActiveRecord::Base
  belongs_to :post
end
```

### Expected behavior

I think this should raise an error on load. I can't think of a reason not to?

Hoping to address in https://github.com/rails/rails/pull/49056.

### Actual behavior

No error is raised. Autosave validation callbacks and association writers seem to be overridden?

### System configuration
**Rails version**: 7.0.6

**Ruby version**: 2.7.3

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

This Pull Request has been created to fix https://github.com/rails/rails/issues/49055.

### Detail

This Pull Request changes `ActiveRecord::NestedAttributes#accepts_nested_attributes_for` to raise an `ArgumentError` when it has already been declared for an association **in the same class**. There is a use case for overriding this in subclasses, that functionality is unchanged.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by joshuay03** [comment]
Looking into the failing tests, all of them seem to be from `activerecord/test/cases/nested_attributes_test.rb` due to redeclaring `accepts_nested_attributes_for `. Will fix these up soon.

File: activerecord/test/cases/nested_attributes_test.rb [hunk 1]
```diff
@@ -74,6 +75,7 @@ def test_should_raise_an_UnknownAttributeError_for_non_existing_nested_attribute
   end
 
   def test_should_disable_allow_destroy_by_default
+    Pirate.nested_attributes_options.delete :ship
```
Comment (ghiculescu) [inline activerecord/test/cases/nested_attributes_test.rb:78]: Can be this be done in `setup` or is it not needed in every test?

Comment (joshuay03) [reply activerecord/test/cases/nested_attributes_test.rb:78]: The issue is that some tests relying on the existing declaration, so they don't redeclare inside the test body, I thought this was the easiest way to get these passing again, but I'm also happy to update them so they're all consistent, so we can just do this in the setup.

File: activerecord/lib/active_record/nested_attributes.rb [hunk 2]
```diff
@@ -355,12 +355,18 @@ def accepts_nested_attributes_for(*attr_names)
         options.update(attr_names.extract_options!)
         options.assert_valid_keys(:allow_destroy, :reject_if, :limit, :update_only)
         options[:reject_if] = REJECT_ALL_BLANK_PROC if options[:reject_if] == :all_blank
+        options[:klass] = self
```
Comment (seanpdoyle) [inline activerecord/lib/active_record/nested_attributes.rb:358]: Could this assignment occur in the same Hash literal as `options = { allow_destroy: false, update_only: false }`?

```ruby
 options = { allow_destroy: false, update_only: false, klass: self }
```

File: activerecord/lib/active_record/nested_attributes.rb [hunk 3]
```diff
@@ -355,12 +355,18 @@ def accepts_nested_attributes_for(*attr_names)
...
 
         attr_names.each do |association_name|
           if reflection = _reflect_on_association(association_name)
             reflection.autosave = true
             define_autosave_validation_callbacks(reflection)
 
+            association_options = self.nested_attributes_options[association_name.to_sym]
+            if association_options && association_options[:klass] == self
```
Comment (seanpdoyle) [inline activerecord/lib/active_record/nested_attributes.rb:366]: Since we're never destructuring the `options[:klass]` into its own local variable (like `klass`), would it be appropriate to use `:class` as the Hash key, since there isn't a risk of colliding with the `class` reserved word?

File: activerecord/lib/active_record/nested_attributes.rb [hunk 4]
```diff
@@ -355,12 +355,18 @@ def accepts_nested_attributes_for(*attr_names)
...
         options.assert_valid_keys(:allow_destroy, :reject_if, :limit, :update_only)
         options[:reject_if] = REJECT_ALL_BLANK_PROC if options[:reject_if] == :all_blank
+        options[:klass] = self
 
         attr_names.each do |association_name|
           if reflection = _reflect_on_association(association_name)
             reflection.autosave = true
             define_autosave_validation_callbacks(reflection)
 
+            association_options = self.nested_attributes_options[association_name.to_sym]
```
Comment (seanpdoyle) [inline activerecord/lib/active_record/nested_attributes.rb:365]: If we invoked [Hash#dig](https://www.rubydoc.info/stdlib/core/Hash:dig) here, we could avoid the local variable assignment and the conditional chaining:

```suggestion
            if nested_attribute_options.dig(association_name.to_sym, :klass) == self
              raise ArgumentError, "Already declared #{association_name} as an accepts_nested_attributes association for #{name}."
            end
```

File: activerecord/lib/active_record/nested_attributes.rb (hunk 2 above)
Comment (joshuay03) [reply activerecord/lib/active_record/nested_attributes.rb:358]: Can do, I just thought it felt more relevant after `options.assert_valid_keys`; so it's more like an internal option that a user provided one.

Also, if it comes after `options.update`, it's not overridable via an arg.

File: activerecord/lib/active_record/nested_attributes.rb (hunk 3 above)
Comment (joshuay03) [reply activerecord/lib/active_record/nested_attributes.rb:366]: Ya true, I did it out of habit, but I think you're right, we can just use `class` here.

File: activerecord/lib/active_record/nested_attributes.rb (hunk 4 above)
Comment (joshuay03) [reply activerecord/lib/active_record/nested_attributes.rb:365]: Good call, will action.

File: activerecord/lib/active_record/nested_attributes.rb (hunk 2 above)
Comment (joshuay03) [reply activerecord/lib/active_record/nested_attributes.rb:358]: On second thought, I might leave it as is for the reasons I pointed out.

File: activerecord/lib/active_record/nested_attributes.rb (hunk 4 above)
Comment (joshuay03) [reply activerecord/lib/active_record/nested_attributes.rb]: Actioned here: https://github.com/rails/rails/compare/4cdb1c9ad91ece2ed33c51fd404806b88d4fba61..56f53113a69f5a76fb068abe6e12710bdfed5b3c

File: activerecord/lib/active_record/nested_attributes.rb (hunk 3 above)
Comment (joshuay03) [reply activerecord/lib/active_record/nested_attributes.rb]: Actioned here: https://github.com/rails/rails/compare/4cdb1c9ad91ece2ed33c51fd404806b88d4fba61..56f53113a69f5a76fb068abe6e12710bdfed5b3c

**Comment by joshuay03** [comment]
Cheers for the review @seanpdoyle I've addressed your comments.

File: activerecord/test/cases/nested_attributes_test.rb (hunk 1 above)
Comment (eileencodes) [reply activerecord/test/cases/nested_attributes_test.rb:78]: You can move the ones that need this to a new test class so that you can do it in setup.

Comment (joshuay03) [reply activerecord/test/cases/nested_attributes_test.rb:78]: @eileencodes

These are existing tests that are already in specific classes or modules, would it make sense to move them to another (nested?) class just for this?

Also, the association being asserted will vary with each test. Are you suggesting a nested class for each association? Otherwise removing the declaration for an association that the test doesn't rely on may have side effects, I'd rather be explicit about it.

File: activerecord/lib/active_record/nested_attributes.rb [hunk 5]
```diff
@@ -355,12 +355,17 @@ def accepts_nested_attributes_for(*attr_names)
...
         options[:reject_if] = REJECT_ALL_BLANK_PROC if options[:reject_if] == :all_blank
+        options[:class] = self
 
         attr_names.each do |association_name|
           if reflection = _reflect_on_association(association_name)
             reflection.autosave = true
             define_autosave_validation_callbacks(reflection)
 
+            if nested_attributes_options.dig(association_name.to_sym, :class) == self
+              raise ArgumentError, "Already declared #{association_name} as an accepts_nested_attributes association for this class."
```
Comment (chaadow) [inline activerecord/lib/active_record/nested_attributes.rb:366]: We use a model concern across multiple models that add some some association logic as well as a "generic" accepts_nested_attribute_for.

and for some models we override it to add specific options ( `allow_destroy` )

Is there a way to add a config to make raising an argument optional? @rafaelfranca  @joshuay03

Comment (rafaelfranca) [reply activerecord/lib/active_record/nested_attributes.rb:366]: This is a case of inheritance that I think we should support. But I don't think we should make this configurable. Either we raise when the same class define the same `accepts_nested_attribute_for` more than once, or we don't.

As I believe your concern is using `included` to add the `accepts_nested_attribute_for` both definitions are owned by the same class. This is a valid use case in my opinion. So I think I'll just revert this change.

Comment (joshuay03) [reply activerecord/lib/active_record/nested_attributes.rb:366]: @rafaelfranca

In my opinion, we should be raising despite this use case. I would argue that there's a higher chance of accidentally overriding it this way rather than purposefully doing so, which was the original intent behind the feature, to prevent surprising behaviour. However, I respect your decision to revert this.

What do you think about raising only if the options are different to the previous declaration? So for example:

```ruby
# will not raise

accepts_nested_attribute_for :association
accepts_nested_attribute_for :association, update_only: true 

# will not raise - multiple duplicates

accepts_nested_attribute_for :association
accepts_nested_attribute_for :association, update_only: true 
accepts_nested_attribute_for :association

# second declaration will raise

accepts_nested_attribute_for :association: true
accepts_nested_attribute_for :association: true

# third declaration will raise - multiple duplicates

accepts_nested_attribute_for :association: true
accepts_nested_attribute_for :association, update_only: true 
accepts_nested_attribute_for :association, update_only: true 
```

This will satisfy all use cases. Let me know what you think and I'll get a PR up if it's worth addressing.

Comment (ghiculescu) [reply activerecord/lib/active_record/nested_attributes.rb:366]: @rafaelfranca @chaadow the original issue had this example:

```ruby
class Post < ActiveRecord::Base
  accepts_nested_attributes_for :comments, update_only: true
  accepts_nested_attributes_for :comments # I feel like this should raise an error on load
end
```

This is a bit contrived, but I still think it should raise, because the first call is totally skipped. In a much bigger model file it might be less obvious why.

Would you accept a PR that still raises for that, but does *not* raise if the calls are in different places. So the above would raise, but this would not:

```ruby
module Commentable
  accepts_nested_attributes_for :comments, update_only: true
end

class Post < ActiveRecord::Base
  include Commentable
  accepts_nested_attributes_for :comments # Don't raise; we are overriding Commentable.
end
```

Comment (rafaelfranca) [reply activerecord/lib/active_record/nested_attributes.rb:366]: If you find a way to implement that we can raisae, but I don't think there is a way to do that, because your example is more like:

```
module Commentable
  extend ActiveSupport::Concern

  included do
    # The scope here is Post so it is the same as running inside the class itself. I see no way to differentiate this usage
    # from a direct definition inside the class, because they are actually the same.
    accepts_nested_attributes_for :comments, update_only: true
  end
end

class Post < ActiveRecord::Base
  include Commentable
  accepts_nested_attributes_for :comments # Don't raise; we are overriding Commentable.
end
```
