### PR TITLE
Lazily build path regex in PathParser

### LINKED ISSUE #39492: Jbuilder is broken in a new Rails app
I’m filing this here because I think it was broken by a recent change to Rails, not anything in Jbuilder, and it may affect other template engines like Haml.

### Steps to reproduce

1. Create a new Rails app from latest master: `railties/exe/rails new ~/Desktop/sandbox --edge`.

   * Note that [Jbuilder](https://github.com/rails/jbuilder) is included in the default Gemfile.
   * App generation may fail on the Webpacker installation step. Finish by `cd`ing into the app and running `bundle exec bin/rails webpacker:install`.

2. Add `FeedsController` with an empty `show` action:

   ```ruby
   # app/controllers/feeds_controller.rb
   class FeedsController < ApplicationController
     def show
     end
   end
   ```

3. Add singular resource routes to `FeedsController`:

   ```ruby
   # config/routes.rb
   Rails.application.routes.draw do
     resource :feed
   end
   ```

4. Add a Jbuilder view for `feeds#show`:

   ```ruby
   # app/views/feeds/show.json.jbuilder (or app/views/feeds/show.jbuilder)
   json.foo "bar"
   ```

5. Start the development web server: `bundle exec bin/rails s`.

6. Access `/feed.json`: `curl -i http://localhost:3000/feed.json`.

### Expected result

A JSON response is returned:

```
$ curl -i http://localhost:3000/feed.json
HTTP/1.1 200 OK
...
Content-Type: application/json
...

{"foo":"bar"}
```

### Actual result

The Jbuilder template is returned verbatim in the response body:

```
$ curl -i http://localhost:3000/feed.json
HTTP/1.1 200 OK
...
Content-Type: application/json
...

json.foo "bar"
```

### Notes

In attempting to reproduce this, I sometimes get the expected result after starting the development server for the first time. Requests after stopping and restarting the development server get the actual result. Stopping Spring doesn’t help. Clearing the Bootsnap cache doesn’t help.

I’ll share an example app shortly.

### PR DESCRIPTION
**Pull request by jonathanhefner**
Eagerly building the path regex can exclude handlers which are added on Action View load.

Fixes #39492.

---

/cc @jhawthorn Since you are familiar with the parts involved here.  Is there a more proper solution?

### CODE REVIEW

**Comment by jhawthorn** [comment]
Thanks. I was worried something like this might happen, but thought [my added test](https://github.com/rails/rails/commit/a70ad604cfbbf191bc27e784c3fe1913a8c7b238) would catch it. 😞

I'd really like to be able to do build this (and even glob and parse all views) on initialize, but I think this is an appropriate workaround until the boot sequence makes that possible ❤️

File: actionview/lib/action_view/template/resolver.rb [hunk 1]
```diff
@@ -60,6 +56,7 @@ def build_path_regex
       end
 
       def parse(path)
+        @regex ||= build_path_regex
```
Comment (jhawthorn) [inline actionview/lib/action_view/template/resolver.rb:59]: I worry this might be a thread safety issue on ex. jruby?

Comment (jonathanhefner) [reply actionview/lib/action_view/template/resolver.rb:59]: Hmm...  More than one thread may call `build_path_regex` before `@regex` is assigned, but it shouldn't matter which one wins since they should all derive the same result, no?

**Review by jhawthorn — APPROVED** [review]

**Comment by kaspth** [comment]
❤️
