### PR TITLE
Prevent double save of cyclic associations

### LINKED ISSUE #35597: Rails bi-directional accepts_nested_attributes_for causes double save and loss of dirty attributes
### Steps to reproduce
Let's say I have 2 models as follows:

```
class User < ActiveRecord::Base
  has_many :tasks, inverse_of: :user
  accepts_nested_attributes_for :tasks

  before_save :test
  after_save :test2

  def test
    puts "before save #{changes}"
  end

  def test2
    puts "after save #{saved_changes}"
  end
end

class Task < ActiveRecord::Base
  belongs_to :user, inverse_of: :tasks
  accepts_nested_attributes_for :user
end
```
Here is the test script:
```
u = User.new(name: 'def')
u.tasks_attributes = [{ name: 'abc' }]
u.save!
```

### Expected behavior

The same code where we remove accepts_nested_attributes_for from the task model, we get the expected result:
```
before save {"name"=>[nil, "def"]}
D, [2019-03-13T08:50:20.629287 #54423] DEBUG -- :    (0.1ms)  begin transaction
D, [2019-03-13T08:50:20.629689 #54423] DEBUG -- :   User Create (0.2ms)  INSERT INTO "users" ("name") VALUES (?)  [["name", "def"]]
D, [2019-03-13T08:50:20.630990 #54423] DEBUG -- :   Task Create (0.2ms)  INSERT INTO "tasks" ("user_id", "name") VALUES (?, ?)  [["user_id", 1], ["name", "abc"]]
after save {"id"=>[nil, 1], "name"=>[nil, "def"]}
D, [2019-03-13T08:50:20.631626 #54423] DEBUG -- :    (0.1ms)  commit transaction
```
### Actual behavior
```
before save {"name"=>[nil, "def"]}
D, [2019-03-13T08:16:27.972711 #53578] DEBUG -- :    (0.1ms)  begin transaction
D, [2019-03-13T08:16:27.973374 #53578] DEBUG -- :   User Create (0.2ms)  INSERT INTO "users" ("name") VALUES (?)  [["name", "def"]]
before save {}
after save {}
D, [2019-03-13T08:16:27.974821 #53578] DEBUG -- :   Task Create (0.2ms)  INSERT INTO "tasks" ("user_id", "name") VALUES (?, ?)  [["user_id", 1], ["name", "abc"]]
after save {}
```

As you can see, the autosave is causing the User to get re-saved from the task, even though it is the user that is creating the task in the first place, leading to attribute changes getting lost.

I have tracked this down to the fact that autosave is always true when accepts_nested_attributes_for is present and this line here:
```
saved = record.save(validate: !autosave) if record.new_record? || (autosave && record.changed_for_autosave?)
```
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/autosave_association.rb#L479

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.6.1

### LINKED ISSUE #41701: Cyclic has_one and belongs_to associations cause extra saves
Say we have two models, `Post` and `Message`, defined like so:

```ruby
class Post < ApplicationRecord
  belongs_to :postable, polymorphic: true, inverse_of: :post
end

class Message < ApplicationRecord
  has_one :post, as: :postable
end
```

Posts and messages are commonly created together:

```ruby
post = Post.create!(postable: Message.new(subject: "Hello, world!"))
```

After the above, `post.previously_new_record?` should be true, per [the docs](https://edgeapi.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-previously_new_record-3F):

> Returns true if this object was just created – that is, prior to the last save, the object didn't exist in the database and new_record? would have returned true.

However, it is actually false on latest main (currently 6d38553). This is because:
1. The post autosaves its postable `before_save` ([here](https://github.com/rails/rails/blob/6d38553b093aeea26944ae75724f35011f7cc6b0/activerecord/lib/active_record/autosave_association.rb#L212)).
2. The message autosaves its post `after_create` ([here](https://github.com/rails/rails/blob/6d38553b093aeea26944ae75724f35011f7cc6b0/activerecord/lib/active_record/autosave_association.rb#L208)). The post is created here. Its `@new_record` flag is cleared and its `@previously_new_record` flag is set.
3. The post’s `before_save` callbacks complete and it is finally saved. It’s no longer a `new_record?` because of the save in step 2, so the save is treated as an update. The update clears the post’s `@previously_new_record` flag.

The issue boils down to the post being saved twice unnecessarily. It can be avoided by creating the message and post separately:

```ruby
message = Message.create!(subject: "Foo")
post = Post.create!(postable: message)
assert post.previously_new_record?
```

…or by creating the post through the message:

```ruby
message = Message.create!(post: Post.new)
assert message.post.previously_new_record?
```

…or by removing the `inverse_of` option on the `:postable` association.

Based on other workarounds that were needed in our app, I suspect the duplicate saving also affects updates and other per-save state (like `previous_changes` and `changes_before_last_save`).

I’ve posted the obligatory reproduction script [here](https://gist.github.com/georgeclaghorn/301f9fdd9e3353882d12a391ee9614e6).

### PR DESCRIPTION
**Pull request by p8**
### Summary

Autosave will double save records with cyclic associations.

For example: a child record with a parent association.
If save is called on the child before the parent has been saved,
the child will be saved twice.
The double save of the child will clear the mutation tracker on
the child record resulting in an incorrect dirty state.

```
    # pirate has_one ship
    ship = Ship.new(name: "Nights Dirty Lightning")
    pirate = ship.build_pirate(catchphrase: "Aye")
    ship.save!
    ship.previous_changes # => returns {} but this should contain the changes.
```

When saving ship currently the following happens:
1. the `before_save` callbacks of the **ship** are called
2. the callbacks call `autosave_associated_records_for_pirate`
3. `autosave_associated_records_for_pirate` saves the **pirate**
4. the `after_save` callbacks of the **pirate** are called
5. the callbacks call `autosave_associated_records_for_ship`
6. `autosave_associated_records_for_ship` saves the **ship**
7. the **ship** is saved again by the original save

`autosave_associated_records_for_ship` saves the ship because the ship
association is set by inverse_of in a `has_one` on the pirate. This does
not happen with a `has_many` by default because the inverse is not set.
If setting the inverse on the `has_many` the problem occurs as well.

This commit adds a `@saving` state which tracks if a record is currently being saved.
If `@saving` is set to true, the record won't be saved by the autosave callbacks.

With this commit the following happens when saving a ship:
1. `@saving` is set to true on **ship**
2. the `before_save` callbacks of the **ship** are called
3. the callbacks call `autosave_associated_records_for_pirate`
5. `autosave_associated_records_for_pirate` saves the **pirate**
6. the `after_save` callbacks of the **pirate** are called
6. `autosave_associated_records_for_ship` skips saving the **ship**
8. the **ship** is saved.
9. `@saving` is set to false on ship

### Other Information

When the child is not saved in the autosave, similar children could be autosaved.
This could result in unexpected order when creating new records, as similar
children will be saved first.

Fixes #35597.
This is a reopening of #36362 which was closed but can't be reopened
because the `master` branch no longer exists.

### CODE REVIEW

File: activerecord/lib/active_record/autosave_association.rb [hunk 1]
```diff
@@ -273,7 +282,23 @@ def changed_for_autosave?
...
     private
+      # Track if this record is already being saved. If it is being saved we
+      # can skip saving it in the autosave callbacks
+      def with_saving_state_tracking
+        @saving = true
+        status = yield
+      ensure
+        @saving = false
+        status
+      end
```
Comment (georgeclaghorn) [inline activerecord/lib/active_record/autosave_association.rb:300]: Don’t need the `status` variable here. Ensure blocks don’t affect return value.

```
irb(main):001:1* def foo
irb(main):002:1*   :foo
irb(main):003:1* ensure
irb(main):004:1*   :bar
irb(main):005:1* end
irb(main):006:0> foo
=> :foo
```

I think there’s a risk that this method may be called while already saving, too (if an app callback on a child record explicitly saves its parent record). Should we track previous saving state on the stack to be safe?

```suggestion
      # Track if this record is already being saved. If it is being saved we
      # can skip saving it in the autosave callbacks
      def with_saving_state_tracking
        previously_saving = @saving
        @saving = true
  
        yield
      ensure
        @saving = previously_saving
      end
```

File: activerecord/lib/active_record/autosave_association.rb [hunk 2]
```diff
@@ -273,7 +282,23 @@ def changed_for_autosave?
...
+    # Returns whether or not this record is already being saved outside of the
+    # current autosave callback
+    def already_saving?
+      @saving
+    end
+
     private
+      # Track if this record is already being saved. If it is being saved we
+      # can skip saving it in the autosave callbacks
+      def with_saving_state_tracking
```
Comment (georgeclaghorn) [inline activerecord/lib/active_record/autosave_association.rb:294]: Little bikeshedding: any thoughts on naming this method `saving` and the corresponding predicate method `saving?`?

```ruby
def saving?
  @saving
end

private
  def saving
    previously_saving, @saving = @saving, true
    yield
  ensure
    @saving = previously_saving
  end
```

File: activerecord/lib/active_record/autosave_association.rb [hunk 3]
```diff
@@ -482,7 +507,7 @@ def save_belongs_to_association(reflection)
         return unless association && association.loaded? && !association.stale_target?
 
         record = association.load_target
-        if record && !record.destroyed?
+        if record && !record.destroyed? && !record.already_saving?
```
Comment (kaspth) [inline activerecord/lib/active_record/autosave_association.rb:510]: Should we extract a method here? 

```ruby
def associated_record_can_save?(record)
  record && !record.destroyed? && !record.already_saving?
end
```

And then in the third case:

```ruby
next unless associated_record_can_save?(record)
```

Could also consider exposing a `record.can_save?` method from autosave_association.rb, which is `# :nodoc:` for starters.

File: activerecord/lib/active_record/autosave_association.rb (hunk 1 above)
Comment (p8) [reply activerecord/lib/active_record/autosave_association.rb:300]: Ah, didn't think of that. That seems like a good idea.
I'll change it and see if I can add a test for this behaviour.

File: activerecord/lib/active_record/autosave_association.rb (hunk 2 above)
Comment (p8) [reply activerecord/lib/active_record/autosave_association.rb:294]: I think the `saving?` method is better than `already_saving?`.
It could be called outside of the autosave code where `already_saving?` might be confusing.
I like that `saving` is named similarly to `saving?` because it makes it more clear they belong together.
Although I'm afraid they might conflict with existing code bases that already have these methods defined.

File: activerecord/lib/active_record/autosave_association.rb (hunk 3 above)
Comment (p8) [reply activerecord/lib/active_record/autosave_association.rb:510]: I think that would be a good idea.
The `can_save?` method looks cleaner to me but `associated_record_can_save?` is more inline with the rest of the code. `associated_record_can_save?` won't `pollute` the public methods either.
But maybe `can_save?` will be useful outside of autosave functionality and giving it a name now is easier than extracting it later.

**Comment by kaspth** [comment]
Great work here, really dig the cleaner campsite too!

File: activerecord/lib/active_record/autosave_association.rb [hunk 4]
```diff
@@ -273,7 +282,26 @@ def changed_for_autosave?
...
+    end
+
+    def can_save? #:nodoc:
+      !destroyed? && !saving?
+    end
+
     private
+      # Track if this record is being saved. If it is being saved we
+      # can skip saving it in the autosave callbacks
+      def saving
```
Comment (kamipo) [inline activerecord/lib/active_record/autosave_association.rb:298]: Should this be `_` prefixed or more longer name?

IMHO `saving?`, `can_save?`, `saving` are too shorter naming for the internal methods, it can easily be overridden by the user defined methods.

Similar with 8a91423b92e6583bf1799a000616982147ca2467.

Comment (rafaelfranca) [reply activerecord/lib/active_record/autosave_association.rb:298]: Yes. it should. Also the documentation is missing `.` in the end of the phases. Do you want to make the changes @kamipo?

Comment (kamipo) [reply activerecord/lib/active_record/autosave_association.rb:298]: Yeah, I'll do that.

**Comment by p8** [comment]
Pretty psyched to get this merged 😄 
Thanks @kaspth and @georgeclaghorn !

**Comment by p8** [comment]
This solution was failing when foreign keys can't be null:
https://gist.github.com/p8/0d139daa3972358badedab393f7b61d0

**Comment by dmitry** [comment]
@p8 nice thing, would be great to add `saving?` to the public methods at some point of time, also to add complementary method `destroying?`. I had one of the use cases for that, and currently I'm doing the following:

```
  def destroy
    current_context, self.validation_context = validation_context, [:destroy]
    super
  ensure
    self.validation_context = current_context
  end

  def destroying?
    (Array(validation_context) & [:destroy]).present?
  end
```

/cc @kamipo @rafaelfranca WDYT?

**Comment by rafaelfranca** [comment]
This change was reverted, but if we have use cases for `saving?` maybe, but only if there is no other way to do that.

**Comment by dmitry** [comment]
@rafaelfranca we already have few cases in our codebase where `destroying?` is really helpful.

In children record we have to check if the parent record were destoyed. `destroyed?` returns true only after it was completely destroyed, but in the meanwhile when you are using `dependent: :destroy` you may not check it, except the code the code below.

```
module DestroyingConcern
  def destroy
    current_context, self.validation_context = validation_context, [:destroy]
    super
  ensure
    self.validation_context = current_context
  end

  def destroying?
    (Array(validation_context) & [:destroy]).present?
  end
end
```

With including that concern you can do the following:

```
    before_destroy prepend: true do
      if !parent.destroying? && some_other check?
        errors.add(:base, :invalid)
        throw :abort
      end
    end
```
