### PR TITLE
[Fix #53564] Ensure normalized attribute queries are consistent for `nil` and normalized `nil`

### LINKED ISSUE #53564: ActiveRecord::Normalization: SQL query does not use `IS [NOT] NULL` when normalized to `nil`
When using normalization to `nil`, the generated sql query does not use `IS NULL` when passing a blank value:

```rb
class Human  < ActiveRecord::Base
  normalizes :name, with: -> { _1.presence }
end

Human.where(name: nil).to_sql
# => SELECT "humen".* FROM "humen" WHERE "humen"."name" IS NULL
# => correctly uses `IS NULL`

Human.where(name: '').to_sql
# => SELECT "humen".* FROM "humen" WHERE "humen"."name" = NULL
# => does *not* use `IS NULL`, but `= NULL` (value is normalized)
```

I'd expect both calls to generate the same query.

### Steps to reproduce

<details>
<summary>Reproduction script</summary>

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails'

  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :humen, force: true do |t|
    t.string :name
  end
end

class Human < ActiveRecord::Base
  normalizes :name, with: -> { _1.presence }
end

class BugTest < Minitest::Test
  def test_where_query
    assert_equal(
      Human.where(name: nil).to_sql,
      Human.where(name: '').to_sql
    )
  end
end
```
</details>

### System configuration
**Rails version**:  8.0.0

**Ruby version**: 3.3.6

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

Fixes https://github.com/rails/rails/issues/53564

### Detail

Updates `Arel::Visitors::ToSql#visit_Arel_Nodes_Equality` to look ahead at the database value and check if it's `nil`, and if so, uses `IS NULL` instead of `=` in the resulting query. The value is memoised [here](https://github.com/rails/rails/blob/852d0cd4123463cf215f4b024801b256857295c4/activerecord/lib/active_record/relation/query_attribute.rb#L26-L29), so I doubt this change has any major performance implications in the case where the condition is falsey and the `=` branch is executed.

**Edit:** Looks like `ActiveRecord::Relation::QueryAttribute#nil?` already does a similar check, so I went with [this approach](https://github.com/rails/rails/compare/0957be203f2d172ccdaa9a2a0023a56b551a4db4..a6e06e11fedc753bcc8018e4aed83f967c1f94a4) instead.

### Additional information

NA

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/lib/active_record/relation/query_attribute.rb [hunk 1]
```diff
@@ -35,7 +35,7 @@ def with_cast_value(value)
       def nil?
         unless value_before_type_cast.is_a?(StatementCache::Substitute)
           value_before_type_cast.nil? ||
-            type.respond_to?(:subtype) && serializable? && value_for_database.nil?
+            (type.respond_to?(:subtype) || type.respond_to?(:normalizer)) && serializable? && value_for_database.nil?
```
Comment (byroot) [inline activerecord/lib/active_record/relation/query_attribute.rb:38]: Annoys me a bit that we have to do so many `respond_to?` against our own code... But seems to work.
