### PR TITLE
Make `reflection.klass` raise if `polymorphic?` not to be misused

### LINKED ISSUE #31876: 5.2.0.rc1 ActiveRecord polymorphic association regression
### Steps to reproduce

Ignore the (perhaps poor) naming choices for the moment:

```
class Entity < ApplicationRecord
  belongs_to :entity, polymorphic: true
end
```

In Rails 5.2.0.rc1 I receive this error:

```
> rails console
Loading development environment (Rails 5.2.0.rc1)
>> Entity.create(entity: User.last)
  User Load (0.5ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
Traceback (most recent call last):
       16: from activerecord (5.2.0.rc1) lib/active_record/inheritance.rb:66:in `new'
       15: from activerecord (5.2.0.rc1) lib/active_record/core.rb:314:in `initialize'
       14: from activemodel (5.2.0.rc1) lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
       13: from activerecord (5.2.0.rc1) lib/active_record/attribute_assignment.rb:28:in `_assign_attributes'
       12: from activemodel (5.2.0.rc1) lib/active_model/attribute_assignment.rb:41:in `_assign_attributes'
       11: from activemodel (5.2.0.rc1) lib/active_model/attribute_assignment.rb:41:in `each'
       10: from activemodel (5.2.0.rc1) lib/active_model/attribute_assignment.rb:42:in `block in _assign_attributes'
        9: from activemodel (5.2.0.rc1) lib/active_model/attribute_assignment.rb:49:in `_assign_attribute'
        8: from activemodel (5.2.0.rc1) lib/active_model/attribute_assignment.rb:49:in `public_send'
        7: from activerecord (5.2.0.rc1) lib/active_record/associations/builder/association.rb:116:in `entity='
        6: from activerecord (5.2.0.rc1) lib/active_record/associations/singular_association.rb:17:in `writer'
        5: from activerecord (5.2.0.rc1) lib/active_record/associations/belongs_to_association.rb:15:in `replace'
        4: from activerecord (5.2.0.rc1) lib/active_record/associations/association.rb:101:in `set_inverse_instance'
        3: from activerecord (5.2.0.rc1) lib/active_record/associations/belongs_to_association.rb:95:in `invertible_for?'
        2: from activerecord (5.2.0.rc1) lib/active_record/associations/belongs_to_polymorphic_association.rb:24:in `inverse_reflection_for'
        1: from activerecord (5.2.0.rc1) lib/active_record/reflection.rb:528:in `polymorphic_inverse_of'
ActiveRecord::InverseOfAssociationNotFoundError (Could not find the inverse association for entity (nil in User))
```

I do not have an inverse association in `User` (nor do I want one).

Under Rails 5.1.4 this association is working as expected.

If I change the name of the association from `:entity` to anything else (and rename the database columns), the association works correctly again under 5.2.0.rc1.

It seems as if the code looking for an inverse association for the `belongs_to :entity` is finding the `belongs_to` itself and proceeding with the expectation that `User` has an inverse association. 

### System configuration
**Rails version**: 5.2.0.rc1

**Ruby version**: 2.5.0

### PR DESCRIPTION
**Pull request by kamipo**
This is an alternative of #31877 to fix #31876 caused by #28808.

This issue was caused by a combination of several loose implementation.

* finding automatic inverse association of polymorphic without context (caused by #28808)
* returning `klass` even if `polymorphic?` (exists before #28808)
* loose verification by `valid_inverse_reflection?` (exists before #28808)

This makes `klass` raise if `polymorphic?` not to be misused.
This issue will not happen unless polymorphic `klass` is misused.

Fixes #31876.
Closes #31877.

### CODE REVIEW

File: activerecord/lib/active_record/reflection.rb [hunk 1]
```diff
@@ -416,6 +416,9 @@ def mapping
     # Active Record class.
     class AssociationReflection < MacroReflection #:nodoc:
       def compute_class(name)
+        if polymorphic?
+          raise NameError, "Polymorphic association does not support to compute class."
```
Comment (matthewd) [inline activerecord/lib/active_record/reflection.rb]: Hmm.. I see the advantage of leaning on the existing code, but I think making this a NameError is still a bit confusing: normally a NameError here is the fault of the data (a bad/unknown class name), whereas in this case it's the fault of the calling code (breaking a contract by calling a method when it shouldn't). Better to keep them separate, I think -- and then pull in the conditional from #31877 to ensure we conform to that contract.

(Otherwise some other code might also rescue NameError, and do something else -- and then they would miss out on the warning that they're misusing the API.)

Comment (kamipo) [reply activerecord/lib/active_record/reflection.rb]: Your requested changes are

* Do not use `NameError` (use `ArgumentError` instead, or another?)
* Do not attempt to automatically find the inverse of a polymorphic not to attempt to call `klass` of polymorphic

Right?

**Comment by rafaelfranca** [comment]
What misused means here? Is https://github.com/rails/rails/issues/34312 a misuse of this feature? At first glance I see nothing wrong in that code

**Comment by kamipo** [comment]
At a glance I agree that nothing wrong in that code, it seems there is a bug around polymorphic through association, so I'll take a closer look at that in this weekend.

**Comment by BrentW** [comment]
I'm wondering if you've had a chance to look at related issue https://github.com/rails/rails/issues/34312
