### PR TITLE
[ActiveStorage] Allow `variant` method to be called by `TIFF` images

### LINKED ISSUE #34698: ActiveStorage variant chokes on TIFF data, raises ActiveStorage::InvariableError
### Steps to reproduce
Use TIFF data with ActiveStorage (any variation - LZW-Compressed or not, Alpha or not) and call .variant on the data

### Expected behavior
ActiveStorage should return the variant

### Actual behavior
ActiveStorage::InvariableError is raised

### System configuration
5.2.2

**Ruby version**:
MRI 2.4.3

### PR DESCRIPTION
**Pull request by lucianosousa**
### Summary
Allow a new image extension(`tiff`) to call the `variant` method and generate custom images

### Other Information
Fixes #34698 
`TIFF` images are supported by IE and Safari browsers, but not by Chrome or Firefox

### CODE REVIEW

**Comment by lucianosousa** [comment]
CI failure are the same in master branch:
https://travis-ci.org/rails/rails/builds/473211901

**Review by sikachu — COMMENTED** [review]
I think the PR looks fine. I have one minor styling comment.

File: activestorage/app/models/active_storage/variant.rb [hunk 1]
```diff
@@ -53,7 +53,7 @@
 # * {ImageProcessing::Vips}[https://github.com/janko-m/image_processing/blob/master/doc/vips.md#methods]
 # * {ruby-vips reference}[http://www.rubydoc.info/gems/ruby-vips/Vips/Image]
 class ActiveStorage::Variant
-  WEB_IMAGE_CONTENT_TYPES = %w[ image/png image/jpeg image/jpg image/gif ]
+  WEB_IMAGE_CONTENT_TYPES = %w[ image/png image/jpeg image/jpg image/gif image/tiff]
```
[the remark this answers is not in the document]
Comment (lucianosousa) [reply activestorage/app/models/active_storage/variant.rb]: @sikachu done.

**Review by sikachu — APPROVED** [review]
Thank you!

 @georgeclaghorn I think this is ready to merge.

File: activestorage/app/models/active_storage/variant.rb [hunk 2]
```diff
@@ -53,7 +53,7 @@
 # * {ImageProcessing::Vips}[https://github.com/janko-m/image_processing/blob/master/doc/vips.md#methods]
 # * {ruby-vips reference}[http://www.rubydoc.info/gems/ruby-vips/Vips/Image]
 class ActiveStorage::Variant
-  WEB_IMAGE_CONTENT_TYPES = %w[ image/png image/jpeg image/jpg image/gif ]
+  WEB_IMAGE_CONTENT_TYPES = %w[ image/png image/jpeg image/jpg image/gif image/tiff ]
```
Comment (georgeclaghorn) [inline activestorage/app/models/active_storage/variant.rb]: Given that TIFF isn’t supported by Chrome or Firefox, I don’t think we can avoid converting TIFF variants to PNG.

File: activestorage/CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,7 @@
+*   Allow `variant` method to be called by `TIFF` images.
```
Comment (georgeclaghorn) [inline activestorage/CHANGELOG.md]:
```suggestion
*   Permit generating variants of TIFF images.
```

File: activestorage/test/models/variant_test.rb [hunk 4]
```diff
@@ -166,4 +166,14 @@ class ActiveStorage::VariantTest < ActiveSupport::TestCase
...
+
+  test "resized variation of TIFF blob" do
+    blob = create_file_blob(filename: "image.tif")
+    variant = blob.variant(resize: "50x50").processed
+    assert_match(/image\.tif/, variant.service_url)
+
+    image = read_image(variant)
+    assert_equal 36, image.width
+    assert_equal 50, image.height
+  end
```
Comment (georgeclaghorn) [inline activestorage/test/models/variant_test.rb]: Can you move this up under the `resized variation of ICO blob` test?

**Review by georgeclaghorn — CHANGES_REQUESTED** [review]

File: activestorage/test/models/variant_test.rb (hunk 4 above)
Comment (lucianosousa) [reply activestorage/test/models/variant_test.rb]: @georgeclaghorn done

File: activestorage/app/models/active_storage/variant.rb (hunk 2 above)
Comment (lucianosousa) [reply activestorage/app/models/active_storage/variant.rb]: @georgeclaghorn done

**Comment by georgeclaghorn** [comment]
Last thing: let’s convert the existing `racecar.jpg` fixture to TIFF instead of introducing a new document of unknown provenance. Generate `racecar.tif` with the following ImageMagick command:

```shell
$ convert -compress none activestorage/test/fixtures/racecar.jpg activestorage/test/fixtures/racecar.tif
```

**Comment by lucianosousa** [comment]
@georgeclaghorn well done sir! let me know if looks good!

**Review by georgeclaghorn — APPROVED** [review]
