### PR TITLE
Fix `counter_cache` double increment

### LINKED ISSUE #29762: counter_cache called twice with after_create callback
### Test Code

```ruby
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')                                                                                                                                                           
ActiveRecord::Base.logger = Logger.new(STDOUT)                                                                                                                                                                                              
                                                                                                                                                                                                                                            
ActiveRecord::Schema.define do                                                                                                                                                                                                              
  create_table :posts do |t|                                                                                                                                                                                                                
    t.integer :comments_count                                                                                                                                                                                                               
  end                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                            
  create_table :users do |t|                                                                                                                                                                                                                
    t.integer :comments_count                                                                                                                                                                                                               
  end                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                            
  create_table :comments do |t|                                                                                                                                                                                                             
    t.integer :post_id                                                                                                                                                                                                                      
    t.integer :user_id                                                                                                                                                                                                                      
    t.text :context                                                                                                                                                                                                                         
  end                                                                                                                                                                                                                                       
end                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                            
class Post < ActiveRecord::Base                                                                                                                                                                                                             
  has_many :comments                                                                                                                                                                                                                        
end                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                            
class User < ActiveRecord::Base                                                                                                                                                                                                             
  has_many :comments                                                                                                                                                                                                                        
end                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                            
class Comment < ActiveRecord::Base                                                                                                                                                                                                          
  belongs_to :post, counter_cache: true                                                                                                                                                                                                     
  belongs_to :user, counter_cache: true                                                                                                                                                                                                     
                                                                                                                                                                                                                                            
  after_create do                                                                                                                                                                                                                           
    update_attributes(context: 'Hello, World')                                                                                                                                                                                              
  end                                                                                                                                                                                                                                       
end   

class BugTest < Minitest::Test                                                                                                                                                                                                              
  def test_counter_cache                                                                                                                                                                                                                    
    post = Post.create                                                                                                                                                                                                                      
    user = User.create                                                                                                                                                                                                                      
                                                                                                                                                                                                                                            
    comment = Comment.create(post_id: post.id, user_id: user.id)                                                                                                                                                                            
                                                                                                                                                                                                                                            
    assert_equal 1, user.reload.comments_count                                                                                                                                                                                              
  end                                                                                                                                                                                                                                       
end         

```

### Test Log

```sql
-- create_table(:posts)
D, [2017-07-12T17:08:37.748693 #24562] DEBUG -- :    (2.4ms)  SELECT sqlite_version(*)
D, [2017-07-12T17:08:37.749860 #24562] DEBUG -- :    (0.3ms)  CREATE TABLE "posts" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "comments_count" integer)
   -> 0.0251s
-- create_table(:users)
D, [2017-07-12T17:08:37.751869 #24562] DEBUG -- :    (0.2ms)  CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "comments_count" integer)
   -> 0.0010s
-- create_table(:comments)
D, [2017-07-12T17:08:37.753774 #24562] DEBUG -- :    (0.2ms)  CREATE TABLE "comments" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "post_id" integer, "user_id" integer, "context" text)
   -> 0.0013s
D, [2017-07-12T17:08:37.766867 #24562] DEBUG -- :    (0.3ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)
D, [2017-07-12T17:08:37.779055 #24562] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.2ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", "environment"], ["LIMIT", 1]]
D, [2017-07-12T17:08:37.786951 #24562] DEBUG -- :    (0.1ms)  begin transaction
D, [2017-07-12T17:08:37.789930 #24562] DEBUG -- :   SQL (0.4ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "development"], ["created_at", "2017-07-12 09:08:37.788307"], ["updated_at", "2017-07-12 09:08:37.788307"]]
D, [2017-07-12T17:08:37.791653 #24562] DEBUG -- :    (0.1ms)  commit transaction
Run options: --seed 37134

# Running:

D, [2017-07-12T17:08:37.893087 #24562] DEBUG -- :    (0.1ms)  begin transaction
D, [2017-07-12T17:08:37.894903 #24562] DEBUG -- :   SQL (0.2ms)  INSERT INTO "posts" DEFAULT VALUES
D, [2017-07-12T17:08:37.895674 #24562] DEBUG -- :    (0.1ms)  commit transaction
D, [2017-07-12T17:08:37.899320 #24562] DEBUG -- :    (0.1ms)  begin transaction
D, [2017-07-12T17:08:37.900696 #24562] DEBUG -- :   SQL (0.1ms)  INSERT INTO "users" DEFAULT VALUES
D, [2017-07-12T17:08:37.901585 #24562] DEBUG -- :    (0.1ms)  commit transaction
D, [2017-07-12T17:08:37.909367 #24562] DEBUG -- :    (0.1ms)  begin transaction
D, [2017-07-12T17:08:37.912918 #24562] DEBUG -- :   SQL (0.5ms)  INSERT INTO "comments" ("post_id", "user_id") VALUES (?, ?)  [["post_id", 1], ["user_id", 1]]
D, [2017-07-12T17:08:37.926519 #24562] DEBUG -- :   Post Load (0.2ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
D, [2017-07-12T17:08:37.929551 #24562] DEBUG -- :   SQL (0.2ms)  UPDATE "posts" SET "comments_count" = COALESCE("comments_count", 0) + 1 WHERE "posts"."id" = ?  [["id", 1]]
D, [2017-07-12T17:08:37.932106 #24562] DEBUG -- :   User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
D, [2017-07-12T17:08:37.933921 #24562] DEBUG -- :   SQL (0.1ms)  UPDATE "users" SET "comments_count" = COALESCE("comments_count", 0) + 1 WHERE "users"."id" = ?  [["id", 1]]
D, [2017-07-12T17:08:37.936466 #24562] DEBUG -- :   SQL (0.2ms)  UPDATE "comments" SET "context" = ? WHERE "comments"."id" = ?  [["context", "Hello, World"], ["id", 1]]
D, [2017-07-12T17:08:37.937936 #24562] DEBUG -- :   SQL (0.1ms)  UPDATE "users" SET "comments_count" = COALESCE("comments_count", 0) + 1 WHERE "users"."id" = ?  [["id", 1]]
D, [2017-07-12T17:08:37.938745 #24562] DEBUG -- :    (0.1ms)  commit transaction
D, [2017-07-12T17:08:37.939958 #24562] DEBUG -- :   User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
F

Finished in 0.060159s, 16.6227 runs/s, 16.6227 assertions/s.

  1) Failure:
BugTest#test_counter_cache [rails-bug-report.rb:60]:
Expected: 1
  Actual: 2

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```
 
### Expected behavior

user.reload.comments_count equal to 1

### Actual behavior

user.reload.comments_count equal to 2

Condensed from as I see 

```sql
D, [2017-07-12T17:08:37.937936 #24562] DEBUG -- :   SQL (0.1ms)  UPDATE "users" SET "comments_count" = COALESCE("comments_count", 0) + 1 WHERE "users"."id" = ?  [["id", 1]]
```

execute twice, if I remove 

```ruby
  after_create do                                                                                                                                                                                                                           
    update_attributes(context: 'Hello, World')                                                                                                                                                                                              
  end   
```

from Comment, it will be ok

### System configuration
**Rails version**:
Using rails 5.2.0.alpha from git://github.com/rails/rails.git (at master@e319b01)
**Ruby version**:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

### PR DESCRIPTION
**Pull request by lugray**
Fixes #29762

### Summary
~~When an `after_create` callback did `update_attributes` on a record with multiple `belongs_to` associations with counter caches, when doing `belongs_to_counter_cache_after_update` for the first association, it would set `@_after_create_counter_called` to false to prepare for subsequent operations, but then the following association would get re-incremented.  This splits out `@_after_create_counter_called` as a hash keyed by the foreign key to track each separately.~~

The need for `@_after_create_counter_called` was removed altogether by 020abad, which also makes the test added in this PR pass.

### Other Information
~~A similar fix may be required for `@_after_replace_counter_called`, but I couldn't figure out a failing test case and so didn't want to do it unnecessarily.~~
It may also be safe to remove `@_after_replace_counter_called`.

### CODE REVIEW

**Comment by zhouguangming** [comment]
:+1:

File: activerecord/lib/active_record/counter_cache.rb [hunk 1]
```diff
@@ -180,7 +180,8 @@ def _create_record(*)
         each_counter_cached_associations do |association|
           if send(association.reflection.name)
             association.increment_counters
-            @_after_create_counter_called = true
+            @_after_create_counter_called ||= {}
```
Comment (Edouard-chin) [inline activerecord/lib/active_record/counter_cache.rb]: Any reason we are adding the `||=` to assign this ivar?

File: activerecord/lib/active_record/associations/builder/belongs_to.rb [hunk 2]
```diff
@@ -31,9 +31,10 @@ def self.add_counter_cache_methods(mixin)
         def belongs_to_counter_cache_after_update(reflection)
           foreign_key  = reflection.foreign_key
           cache_column = reflection.counter_cache_column
+          @_after_create_counter_called ||= {}
 
-          if (@_after_create_counter_called ||= false)
-            @_after_create_counter_called = false
+          if (@_after_create_counter_called[foreign_key] ||= false)
```
Comment (Edouard-chin) [inline activerecord/lib/active_record/associations/builder/belongs_to.rb]: Might just be a preference question 🤷‍♂️ , but won't it be more readable now that we have a hash to not assign in the condition and let the condition body do it?
Feels weird that the condition body is doing the same as the condition itself.

```ruby
if @_after_create_counter_called.fetch(foreign_key, false)
  @_after_create_counter_called = false
end
```

**Review by Edouard-chin — APPROVED** [review]
Checkout the branch and it works perfectly 💯

File: activerecord/lib/active_record/counter_cache.rb (hunk 1 above)
Comment (lugray) [inline activerecord/lib/active_record/counter_cache.rb]: Because it may or may not be defined yet.

File: activerecord/lib/active_record/associations/builder/belongs_to.rb (hunk 2 above)
Comment (lugray) [inline activerecord/lib/active_record/associations/builder/belongs_to.rb]: I agree with you.  I was unwisely making decisions for an easier to read diff instead of easier to read code.  I've pushed up a new version.

File: activerecord/lib/active_record/counter_cache.rb (hunk 1 above)
Comment (Edouard-chin) [inline activerecord/lib/active_record/counter_cache.rb]: But why the previous implementation assumed it was never defined?

Comment (lugray) [inline activerecord/lib/active_record/counter_cache.rb]: It doesn't assume anything.  It just wanted to set the flag to true and it didn't matter whether it was defined or not.  I just want to set the flag to true *for a key*, so I need to make sure the hash is defined.

**Comment by sgrif** [comment]
The test in this PR passes with or without the changes to the code (at least when I pull it into master). In fact, I can delete the ivar entirely and get no test failures. Can you confirm that the issue is still present on master? I would have expected this to be fixed on 5.1 but if not it may have been fixed by https://github.com/rails/rails/commit/020abadf047997cb3df18a59d210dfe4406cf166

**Comment by sgrif** [comment]
Confirmed that this was fixed by 020abad. @lugray Can you update this to remove the ivar instead? (Keep the test)

**Comment by lugray** [comment]
Can confirm, broken on `fix_counter_cache^`, fixed by 020abad.  Should we add the test?

**Comment by sgrif** [comment]
Yes, we should keep the test provided by this PR

**Comment by lugray** [comment]
Updated.

**Review by sgrif — APPROVED** [review]
You may want to update your commit message, but LGTM

**Comment by lugray** [comment]
🤦‍♀️ Commit message updated.
