### PR TITLE
Fix inconsistency with changed attributes when overriding AR attribute reader

### LINKED ISSUE #28660: ActiveRecord::AttributeMethods::Dirty#changes is inconsistent when overriding AR accessors
When `model`'s accessor is overridden, `model.changes` method returns old value as the value taken from database and new value as a result of calling accessor method. This seems very inconsistent.

```ruby
class Post < ActiveRecord::Base
  def title
    super.upcase
  end
end

post = Post.create!(title: 'hey')
post.title = 'ho'

post.changes['title']
# => ['hey', 'HO']
```
Here is the test case showing this problem:
https://gist.github.com/lukesarnacki/de66d2a4b055cd9f1e19dd4ff8bebbd6

It seems to be the same both on 4.x and 5.x rails versions (haven't checked 3).

### PR DESCRIPTION
**Pull request by bogdanvlviv**
Fixes #28660.

### CODE REVIEW

**Comment by bogdanvlviv** [comment]
Please review.

File: activerecord/test/cases/dirty_test.rb [hunk 1]
```diff
@@ -671,6 +671,25 @@ def test_datetime_attribute_doesnt_change_if_zone_is_modified_in_string
     assert binary.changed?
   end
 
+  test "changes is correct if override attribute accessor" do
```
Comment (eavgerinos) [inline activerecord/test/cases/dirty_test.rb]: I'd rewrite this example message as well as the commit message to reference `reader` or `getter` explicitly, since `writter/setter` overrides do not affect Dirty hash negatively.

Comment (bogdanvlviv) [inline activerecord/test/cases/dirty_test.rb]: Thank you

**Comment by bogdanvlviv** [comment]
Failed tests aren't related to to changes

File: activerecord/test/cases/dirty_test.rb (hunk 1 above)
Comment (eavgerinos) [inline activerecord/test/cases/dirty_test.rb]: :)

**Comment by bogdanvlviv** [comment]
Thanks for restart tests! Any thoughts about this PR?

**Comment by matthewd** [comment]
For posterity, also note follow-up in #28760
