### PR TITLE
Fixes #24239

### LINKED ISSUE #24239: Method missing when including ActionController::Cookies in Rails 5.0 API
### Steps to reproduce
Hello guys,
Can't include **ActionController::Cookies** into controller inherited from **ActionController::API**
[Here is a gist reproducing the bug] (https://gist.github.com/tenshilg/056076c0507709c587b7) 

### Expected behavior
Successfully included **ActionController::Cookies** into **ApplicationController** inherited from **ActionController::API**

### Actual behavior
Can't include module due to method missing in **ActionController::API**

### System configuration
**Rails version**: all since 5.0.0 beta1

**Ruby version**: 2.2.3, 2.3.0

### PR DESCRIPTION
**Pull request by rthbound**
The guides claim you should be able to include AC modules in your controllers, but, as reported in #24239, it's currently not possible to include ActionController::Cookies in controllers inheriting from ActionController::API.

> All Action Controller modules know about their dependent modules, so you can feel free to include any modules into your controllers, and all dependencies will be included and set up as well.

To fix this we'll simply skip calling `#helper_method` if it's not defined: if we don't have helpers, we needn't define one.

The reproduction script from the parent issue: https://gist.github.com/tenshilg/056076c0507709c587b7

@matthewd

### CODE REVIEW

**Comment by pixeltrix** [comment]
@rthbound can you add the test case to the PR please - thanks!

**Comment by rthbound** [comment]
@pixeltrix sure thing. Is the above okay?

File: actionpack/test/controller/api/with_cookies_test.rb [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+
+  def with_cookies
+    render plain: cookies[:foobar]
+  end
+end
+
+class WithCookiesTest < ActionController::TestCase
+  tests WithCookiesController
+
+  def test_flash
```
Comment (pixeltrix) [inline actionpack/test/controller/api/with_cookies_test.rb]: Method description doesn't look right - copy/paste error?

**Comment by pixeltrix** [comment]
@rthbound also a CHANGELOG entry would be helpful - thanks.

File: actionpack/test/controller/api/with_cookies_test.rb (hunk 1 above)
Comment (rthbound) [inline actionpack/test/controller/api/with_cookies_test.rb]: Exactly. Thanks :)

**Comment by rthbound** [comment]
10-4 @pixeltrix, all done

**Comment by pixeltrix** [comment]
@rthbound thanks for you contribution :+1:
