### PR TITLE
Fix: `StrictLoadingViolationError` when concatenating or setting association when non-persisted owner has primary key

### LINKED ISSUE #46689: `ActiveRecord::StrictLoadingViolationError` when concatenating or setting association when non-persisted owner has primary key
### Steps to reproduce

This is a follow-up of #4639 because the fix for this was reverted in #46688 after a side effect of the fix was found (see #46685).

This also includes a test case for setting the association (via `association=`) which also raises a `ActiveRecord::StrictLoadingViolationError`.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_concat
    post = Post.new(id: 1)
    post.strict_loading!

    post.comments << Comment.new
  end

  def test_association_set
    post = Post.new(id: 1)
    post.strict_loading!

    post.comments = [Comment.new]
  end
end

```

### Expected behavior

Concatenating or setting a association of a non-persisted record that was initialized with a primary key should not lead to a `ActiveRecord::StrictLoadingViolationError`. 

### Actual behavior

Currently both operations issue a SQL query to load the associated records of the owner, that raises the exception. It seems like both queries are required to keep the current behavior (loading existing associated records when calling one of the operations).

However those should not raise a strict loading error, because it does not seem to be possible to eager load the association in a way that does not raise. The only work around is to disable strict loading for the record.

### System configuration

**Rails version**:
main (as of https://github.com/rails/rails/commit/7ebbe3251fe75f9174f111236d656cdf20a5452c)

**Ruby version**:
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

cc @ghiculescu

### PR DESCRIPTION
**Pull request by ghiculescu**
Fixes https://github.com/rails/rails/issues/46689

I think this is a neater (and safer!) solution than https://github.com/rails/rails/pull/46613 anyway.

cc @richardboehme please verify the fix.
cc @adrianna-chang-shopify please check this doesn't cause https://github.com/rails/rails/issues/46685 again!
cc @eileencodes because strict loading.

### CODE REVIEW

**Review by adrianna-chang-shopify — COMMENTED** [review]
Looks good on my end 👍 Thanks Alex!

File: activerecord/lib/active_record/associations/association.rb [hunk 1]
```diff
@@ -45,6 +45,8 @@ def initialize(owner, reflection)
 
         reset
         reset_scope
+
+        @no_strict_loading = nil
```
Comment (eileencodes) [inline activerecord/lib/active_record/associations/association.rb:49]: From a naming perspective I would prefer `skip_strict_loading`. Otherwise this looks good to me 👍🏼
