### PR TITLE
Fix decorated type with `type_for_attribute` on the serialized attribute

### LINKED ISSUE #41138: Regression when redefining a store attribute with a new type
We have a model that defines a `store` attribute, then redefines it with a wrapper type for encryption, like so:

```ruby
class Cache < ApplicationRecord
  store :data
  encrypts :data
end
```

The `encrypts` macro boils down to:

```ruby
def encrypts(name)
  attribute name, :encrypted, subtype: type_for_attribute(name)
end
```

After 4cc9c0f, values stored in the `data` attribute no longer make it to the DB:

```
> Cache.create! data: { trial: true }
Cache Create (0.1ms)  INSERT INTO "caches" DEFAULT VALUES
```

I’ve shared a minimal reproduction script [as a gist](https://gist.github.com/georgeclaghorn/681fd8c8fdaaa956945bb440a90b9752).

Apologies in advance if we’re just Doing It Wrong and need to change the way we decorate attributes. I’m not familiar enough with Active Record’s attributes system to know that off the top of my head or to understand what Jonathan’s commit changed.

/cc @jonathanhefner @kamipo

### PR DESCRIPTION
**Pull request by kamipo**
The regression #41138 which is caused by #39929 is happened due to using `cast_type` (`:encrypted`) with `prev_decorator` (`serialize` in `store`).

Since multiple decorations (`:encrypted` on `store` on the original attribute) were never officially supported, it was just a coincidence that it worked, but I don't want to break that in exchange of allowing to ommit a type on subclasses.

IMO, even if a type on subclasses can be ommited, I'd not recommend to ommit the type on subclasses for devs.

```ruby
# app/models/post.rb
class Post < ActiveRecord::Base
  attribute :x, :integer
end

# app/models/special_post.rb
class SpecialPost < Post
  # :integer can be ommited, but it is less obvious.
  attribute :x, default: 42

  # I'd recommend to not ommit the :integer for devs.
  attribute :x, :integer, default: 42
end
```

It is a similar point of view with https://github.com/rails/rails/commit/94ba417ecec8272700805268b76be7de9a470a59#r41923157.

Fixes #41138.

cc @georgeclaghorn @kaspth @jonathanhefner

### CODE REVIEW

**Comment by jonathanhefner** [comment]
@kamipo If this PR is the direction you prefer, then I am fine with that.

However, to me, it seems like `EncryptedType` is really a decorator, and so the `encrypts` macro would be appropriately written as:

```ruby
def encrypts(name)
  attribute(name) { |subtype| EncryptedType.new(subtype: subtype) }
end
```

But this would not work currently.  We could make it work by implementing decorator stacking, as I mentioned in https://github.com/rails/rails/pull/39929#issuecomment-664389013.  Something like:

```ruby
decorator = [prev_decorator, decorator].compact.reduce(&:>>)
```

Also, I realize the `decorator` block is a private API.  However, I believe the plan is to extract `EncryptedType` to Rails.

File: activerecord/test/cases/serialized_attribute_test.rb [hunk 1]
```diff
@@ -392,6 +392,68 @@ def test_nil_is_always_persisted_as_null
...
+    assert_equal({ "trial" => true }, topic.content)
+  ensure
+    ActiveRecord::Type.registry = old_registry
+  end
+
+  def test_decorated_type_with_decorator_block
+    klass = Class.new(ActiveRecord::Base) do
+      self.table_name = Topic.table_name
+      store :content
+      attribute(:content) { |subtype| EncryptedType.new(subtype: subtype) }
```
Comment (kamipo) [inline activerecord/test/cases/serialized_attribute_test.rb:449]: I've allowed multiple decorations which can be used by such like `EncryptedType` in 70259f5e519869052a25db2c832e2c9d53349c66.

File: activerecord/lib/active_record/attributes.rb [hunk 2]
```diff
@@ -208,21 +208,30 @@ module ClassMethods
...
+          else
+            cast_type = block || -> subtype { subtype }
+          end
         end
 
-        self.attributes_to_define_after_schema_loads = attributes_to_define_after_schema_loads.merge(
-          name => [cast_type, options, decorator]
-        )
+        self.attributes_to_define_after_schema_loads =
+          attributes_to_define_after_schema_loads.merge(name => [cast_type, default])
```
Comment (jonathanhefner) [inline activerecord/lib/active_record/attributes.rb:234]: Can we assume that `attributes_to_define_after_schema_loads[name][0]` will now always be either a `Proc` or `nil`?  If so, what about:

```ruby
prev_type_proc, prev_default = attributes_to_define_after_schema_loads[name]

type_proc =
  if cast_type
    -> _ { Type.lookup(cast_type, **options, adapter: Type.adapter_name_from(self)) }
  else
    [prev_type_proc, block].compact.reduce { |f, g| -> subtype { g[f[subtype]] } }
  end

default = prev_default if cast_type.nil? && default == NO_DEFAULT_PROVIDED

self.attributes_to_define_after_schema_loads =
  attributes_to_define_after_schema_loads.merge(name => [type_proc, default])
```

The `else` condition could be written more neatly as `[prev_type_proc, block].compact.reduce(&:>>)` when we drop Ruby 2.5 support, or if we add a `Proc#>>` polyfill.

Comment (kamipo) [reply activerecord/lib/active_record/attributes.rb:234]: `cast_type` will always be `Proc` or a type object, isn't `nil`.

Comment (kamipo) [reply activerecord/lib/active_record/attributes.rb:234]: i.e. `attribute :attr_name, EncryptedType.new` should work as it is.

Comment (jonathanhefner) [reply activerecord/lib/active_record/attributes.rb:234]: Ah, right!  I forgot that case.  So then perhaps:

```ruby
prev_type_proc, prev_default = attributes_to_define_after_schema_loads[name]

type_proc =
  case cast_type
  when nil
    [prev_type_proc, block].compact.reduce { |f, g| -> subtype { g[f[subtype]] } }
  when Symbol
    -> _ { Type.lookup(cast_type, **options, adapter: Type.adapter_name_from(self)) }
  else
    -> _ { cast_type }
  end

default = prev_default if cast_type.nil? && default == NO_DEFAULT_PROVIDED

self.attributes_to_define_after_schema_loads =
  attributes_to_define_after_schema_loads.merge(name => [type_proc, default])
```

Comment (kamipo) [reply activerecord/lib/active_record/attributes.rb:234]: `default = prev_default if cast_type.nil? && default == NO_DEFAULT_PROVIDED` in the above will override database default to `nil` accidentally, and `[prev_type_proc, block].compact.reduce { |f, g| -> subtype { g[f[subtype]] } }` can be `nil`.

Personally I'm not interested creating extra block especially when `cast_type` is a symbol or a type object which are the most case, just to use `Proc#>>` in a future.

(Wrapping a block for a symbol is to avoid `bin/test` testing issue. I'll fix that in a later PR.)

Comment (jonathanhefner) [reply activerecord/lib/active_record/attributes.rb:234]: > and `[prev_type_proc, block].compact.reduce { |f, g| -> subtype { g[f[subtype]] } }` can be `nil`.

Yes.  It would require changing `load_schema!` from

```ruby
cast_type = cast_type[type_for_attribute(name)] if Proc === cast_type
```

to something like

```ruby
cast_type = type_for_attribute(name)
cast_type = type_proc[cast_type] if type_proc
```

> `default = prev_default if cast_type.nil? && default == NO_DEFAULT_PROVIDED` in the above will override database default to `nil` accidentally,

That could be addressed by adding a default value of `[nil, NO_DEFAULT_PROVIDED]` to the `attributes_to_define_after_schema_loads` Hash.


However, it seems like you have plans for this code, so let's do the way that you prefer! :+1:

File: activerecord/test/cases/serialized_attribute_test.rb [hunk 3]
```diff
@@ -392,6 +392,68 @@ def test_nil_is_always_persisted_as_null
...
+
+  def test_decorated_type_with_type_for_attribute
+    old_registry = ActiveRecord::Type.registry
+    ActiveRecord::Type.registry = ActiveRecord::Type.registry.dup
+    ActiveRecord::Type.register :encrypted, EncryptedType
+
+    klass = Class.new(ActiveRecord::Base) do
+      self.table_name = Topic.table_name
+      store :content
+      attribute :content, :encrypted, subtype: type_for_attribute(:content)
```
Comment (kaspth) [inline activerecord/test/cases/serialized_attribute_test.rb:435]: Do users have to provide a subtype or can it be inferred automatically? Feels like attribute should automatically cascade the types.

Comment (kamipo) [reply activerecord/test/cases/serialized_attribute_test.rb:435]: Do you mean that we should provide a way to inject a subtype to the type which has `subtype` option?

https://github.com/rails/rails/blob/70259f5e519869052a25db2c832e2c9d53349c66/activerecord/test/cases/serialized_attribute_test.rb#L395-L400

https://github.com/rails/rails/blob/70259f5e519869052a25db2c832e2c9d53349c66/activerecord/test/cases/serialized_attribute_test.rb#L446-L450

Comment (kamipo) [reply activerecord/test/cases/serialized_attribute_test.rb:435]: I'm not sure what you mean by "automatically cascade the types".

In 6.1, there is no reliable way. If an attribute isn't decorated (no `enum`, `serialize`, `store` are used), `attribute(:content) { |subtype| EncryptedType.new(subtype: subtype) }`, and `decorate_attribute_type("content") { |subtype| EncryptedType.new(subtype: subtype) }` works.

In main branch, `attribute(:content) { |subtype| EncryptedType.new(subtype: subtype) }` works even if `enum`, `serialize`, `store` are used on the attribute (`decorate_attribute_type` is removed in the branch).

If we provide a way for decorator officially, I feel that it is better to provide the API separately (e.g. `decorate_attribute` etc) from the `attribute`.

**Comment by georgeclaghorn** [comment]
Thank you both!

File: activerecord/test/cases/serialized_attribute_test.rb (hunk 3 above)
Comment (kaspth) [reply activerecord/test/cases/serialized_attribute_test.rb:435]: Wups, sorry, I forgot to get back to this! I'd just like to be able to do:

```ruby
store :content
attribute :content, :encrypted
```

without needing to pass the `subtype`, `attribute :content, :encrypted, subtype: type_for_attribute(:content)`.

> If we provide a way for decorator officially, I feel that it is better to provide the API separately (e.g. `decorate_attribute` etc) from the `attribute`.

That also sounds good 👍
