### PR TITLE
Validate options when managing columns and tables in migration

### LINKED ISSUE #33284: `t.references` doesn't raise an error on non-existent options
### Steps to reproduce

1. Create a migration
2. Use `create_table` to add a table called `:users` like this:
```
create_table :users, force: true do |t|
end
```
3. Use `create_table` to add a table called `:posts` that references `:users` like this:
```
create_table :posts, force: true do |t|
  t.references :users, nnull: false, uniqe: true 
end
```
 \*\*\*\* NOTE that 'nnull' and 'uniqe' are non-existent options!! \*\*\*\*
 
4. Run the migration

I created a runnable gist to illustrate the issue here: https://gist.github.com/georgewambold/16ee14cb0e5ca77b35ff3c94b4537475

### Expected behavior
An error should be raised

### Actual behavior
The migration changes are commited without raising an error

### System configuration
**Rails version**: 6.0.0.alpha

**Ruby version**: 2.5.1

### Other notes
This is my first issue and I'd love to write the fix if the issue is accepted. 

This issue is similar to [issue 8104](https://github.com/rails/rails/issues/8104) and [PR 32675](https://github.com/rails/rails/pull/32675)

### LINKED ISSUE #39230: Migrations Should Raise an Exception for Unsupported Options
### Steps to reproduce
It's easy to make a mistake in a migration and accidentally use an option that ends up being ignored.

Some options are supported by one command but not another:

```ruby
create_table :things do |t|
  # Good - Creates column_a and an index
  t.integer :column_a, index: true
end

# Bad - Creates column_b but silently ignores the index option
add_column :things, :column_b, :integer, index: true
```

And typos are allowed.  In [this example from Stack Overflow](https://stackoverflow.com/a/14271429/2622934), using `precison` instead of `precision` still created a numeric column without the precision defined.

### Expected behavior
Migrations should raise an exception for unsupported options.

### Actual behavior
Migration completes successfully without any error.

### System configuration
**Rails version**: 6.0

**Ruby version**: 2.6

### PR DESCRIPTION
**Pull request by tgxworld**
### Motivation / Background

This Pull Request has been created because invalid options used when managing columns and tables in migrations are silently ignored. 

Previous attempt in https://github.com/rails/rails/pull/33347
Resolves https://github.com/rails/rails/issues/33284
Resolves https://github.com/rails/rails/issues/39230

### Detail

This Pull Request adds a step to validate the options that are used when managing columns and tables in migrations. The intention is to only validate options for new migrations that are added. Invalid options used in old migrations are silently ignored like they always have been.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] There are no typos in commit messages and comments.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [X] Feature branch is up-to-date with `main` (if not - rebase it).
* [x] Pull request only contains one commit for bug fixes and small features. If it's a larger feature, multiple commits are permitted but must be descriptive.
* [x] Tests are added if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [X] PR is not in a draft state.
* [X] CI is passing.

### CODE REVIEW

**Comment by byroot** [comment]
I'm generally in favor of this, but I need to take the time to review carefully (probably won't have time today, so cc @casperisfine).

One concern might be backward compatibility, generally the stance on the migration API changes have been don't break previous versions. So we might need to scope this to Rails 7.1, but other than that I don't foresee much problems.

File: activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb [hunk 1]
```diff
@@ -567,7 +580,15 @@ def new_check_constraint_definition(expression, options) # :nodoc:
       end
 
       private
+        def valid_column_definition_option_keys
+          ColumnDefinition::OPTION_NAMES
+        end
+
         def create_column_definition(name, type, options)
+          unless options[:_skip_validate_options_keys]
+            options.except(*[:_uses_legacy_reference_index_name, :_skip_validate_options_keys]).assert_valid_keys(*(valid_column_definition_option_keys))
```
Comment (casperisfine) [inline activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb:589]:
```suggestion
            options.assert_valid_keys(:_uses_legacy_reference_index_name, :_skip_validate_options_keys, valid_column_definition_option_keys)
```

File: activerecord/lib/active_record/connection_adapters/mysql/schema_statements.rb [hunk 2]
```diff
@@ -154,6 +154,10 @@ def default_row_format
             @default_row_format
           end
 
+          def valid_primary_key_option_keys
```
Comment (casperisfine) [inline activerecord/lib/active_record/connection_adapters/mysql/schema_statements.rb:157]:
```suggestion
          def valid_primary_key_options
```

I think we could make the whole thing a litle bit less verbose by using a shorter naming conventions.

e.g.

  - `def valid_<thing>_options`
  - `VALID_<THING>_options`

But also drop the constants when they don't help DRYing up.

File: activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb [hunk 3]
```diff
@@ -1558,8 +1559,44 @@ def create_alter_table(name)
...
+
+        def extract_primary_key_options!(options)
+          primary_key_options = options.extract!(*valid_primary_key_option_keys)
+
+          if options[:_skip_validate_options_keys]
+            primary_key_options[:_skip_validate_options_keys] = options[:_skip_validate_options_keys]
+          end
+
+          primary_key_options
+        end
```
Comment (casperisfine) [inline activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:1590]: Wouldn't all this be much simpler if `:_skip_validate_options_keys` was part of `valid_primary_key_option_keys` etc? I don't really see a downside in doing this.

**Review by casperisfine — COMMENTED** [review]
Ok overall good for me, but I think to code can be significantly cleaned up.

File: activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb (hunk 3 above)
Comment (tgxworld) [reply activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:1590]: My thinking when doing so was that I wanted to avoid exposing an internal implementation concern in the error message when an invalid option is used. Therefore the trade off I made here was to have a cleaner error message at the expense of a more verbose private method.

Comment (casperisfine) [reply activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:1590]: I see, but that's only for `assert_valid_keys`., you can still simplify the above in a one-liner:

```ruby
options.extract!(*valid_primary_key_option_keys, :_skip_validate_options_keys)
```

So a method is likely not needed.

Comment (tgxworld) [reply activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:1590]: Just to clarify, do we agree that it'll be nicer to avoid exposing the internal options that are being used here? My question here is kind of related to the code suggestion in https://github.com/rails/rails/pull/46178#discussion_r989139368.

Comment (byroot) [reply activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:1590]: Yes we agree.

**Comment by tgxworld** [comment]
@casperisfine I've updated the PR per your review comments and included a CHANGELOG entry. Thank you for reviewing :+1:

**Comment by byroot** [comment]
Please squash your commits, and then it's good for me.

**Comment by glaszig** [comment]
this broke migrations portability. in a project i'd like to be compatible with sqlite and mysql (and postresql possibly) and for mysql i'm accustomed to use the column position option `after` but now those migrations don't work anymore with i.e. sqlite because the adapter doesn't know the keyword.

this worked perfectly before when unknown options were just being ignored. now i need to do ugly gymnastics akin to:

```rb
adapter_type = connection.adapter_name.downcase.to_sym
case adapter_type
when :mysql, :mysql2
  # ...
when :sqlite
  # ...
when :postgresql
  # ...
else
  # ...
end
```
