### PR TITLE
Correctly dump check constraints for MySQL 8.0.16+

### LINKED ISSUE #47849: Incorrect handling of check constraints in MySQL 8.0.16+
### Steps to reproduce

For our specific case, we have a MySQL 8.0 database that contains a table with a check constraint which validates a JSON column against a specific schema using the `json_schema_valid` function.

The structure.sql file was previously exported via `db:structure:dump`. I've attached a minimal version here.

1. Import the [attached SQL file](https://github.com/rails/rails/files/11139214/structure.sql.zip) into your test database (you'll need to unzip it first, GitHub doesn't allow SQL files to be attached).

```sql
DROP TABLE IF EXISTS `sample_table`;
CREATE TABLE `sample_table` (
                                `id` int NOT NULL AUTO_INCREMENT,
                                `test_column` json DEFAULT NULL,
                                PRIMARY KEY (`id`),
                                CONSTRAINT `non_empty_test_array` CHECK (json_schema_valid(_utf8mb4'\n        {\n          "oneOf": [\n            {\n              "type": "null"\n            },\n            {\n              "type": "array",\n              "minItems": 1,\n              "items": {\n                "type": "integer",\n                "minimum": 0\n              }\n            }\n          ]\n        }',`test_column`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

2. Dump the database again with `bin/rails db:schema:dump`. You'll find that the output for the check_constraint looks like this:

```ruby
ActiveRecord::Schema[7.1].define(version: 0) do
  create_table "sample_table", id: :integer, charset: "utf8mb4", collation: "utf8mb4_0900_ai_ci", force: :cascade do |t|
    t.json "test_column"
    t.check_constraint "son_schema_valid(_utf8mb4\\'\\\\n        {\\\\n          \"oneOf\": [\\\\n            {\\\\n              \"type\": \"null\"\\\\n            },\\\\n            {\\\\n              \"type\": \"array\",\\\\n              \"minItems\": 1,\\\\n              \"items\": {\\\\n                \"type\": \"integer\",\\\\n                \"minimum\": 0\\\\n              }\\\\n            }\\\\n          ]\\\\n        }\\',`test_column`", name: "non_empty_test_array"
  end

end
```

3. If you try to import this back into a clean database now, with `bin/rails db:drop db:create db:schema:load`, it will fail:

```
bin/rails aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\'\\n        {\\n          "oneOf": [\\n            {\\n              "type": "n' at line 1
/repro/db/schema.rb:14:in `block in <main>'
/repro/db/schema.rb:13:in `<main>'

Caused by:
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\'\\n        {\\n          "oneOf": [\\n            {\\n              "type": "n' at line 1
```

4. You'll note that we also have weird escape characters in the constraint; these were present in the original SQL for the constraint but should probably also be stripped out.

I couldn't get a reliably working reproduction script because I couldn't find any documentation on loading Rake tasks in for minimal scripts.

### Expected behavior

When running the `db:schema:dump` task, we should expect that any tables with check constraints are dumped such that they can be imported with `db:schema:load`.

### Actual behavior

The first and last characters of the check constraint are stripped by the SchemaDumper. This is because of https://github.com/rails/rails/blob/bcd19d95d8b0e4a6239fb4a2437296547375563c/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L529 which checks to see if the database engine is MariaDB; support for proper check constraints appears to have been added in MySQL 8.0.16.

### System configuration
**Rails version**: Rails 7.1.0.alpha

**Ruby version**: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

### PR DESCRIPTION
**Pull request by stevehill1981**
### Motivation / Background

This Pull Request has been created because Rails doesn't currently handle check constraints correctly in newer versions of MySQL 8.0.

Fixes #47849.

### Detail

If you're using MySQL 8.0.16+ and your database contains a table with a check constraint, the first and last characters of the constraint will be stripped when dumping the schema; this makes it impossible to use check constraints in a MySQL 8.0 database with the `:ruby` schema format; once dumped, they cannot be re-imported.

This is because, up until MySQL 8.0.16, all check constraints were surrounded by an extra set of parentheses; this behaviour differed from that presented by MariaDB, which handled them correctly thanks to an engine check within the AbstractMySqlAdapter.

With this change, we continue to handle MariaDB correctly, but also add an extra database version check so that MySQL 8.0.16+ behaves in the same way.

It is also possible that the exported check constraint will contain invalid and unexpected whitespace characters; we handle that here too, stripping out sequences of `\\` and `\n`, as well as any other whitespace.

### Additional information

I've tested this as thoroughly as possible against local versions of MySQL 8.0 running in Docker. I wasn't able to figure out how to write a test for the new behaviour; there's only a single test that deals with check constraints in the schema dumper and it doesn't have any MySQL-specific behaviour.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by stevehill1981** [comment]
I've arrived at a somewhat different solution here than I originally set out with; the new code now only strips the parentheses if they're present, which fixes the original bug where the constraint was being corrupted as a result of removing the first and last characters indiscriminately.

**Comment by stevehill1981** [comment]
I've figured out where to add a test for this, so I'll update with that tomorrow.

**Review by byroot — COMMENTED** [review]
Please squash you commits.

**Comment by stevehill1981** [comment]
@byroot Thanks! Squashed the commits, added the test I mentioned (and fixed the others I broke along the way). There are still some test failures in Buildkite, but of the 5 failures only one of them is related to my change - and it weirdly only fails on the Ruby 3.2 tests, all others are fine.

File: activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb [hunk 1]
```diff
@@ -648,6 +649,21 @@ def check_version # :nodoc:
...
+        # may contain strings of these characters, _not_ the escaped versions
+        # that using double quotes would produce.
+        #
+        # rubocop:disable Performance/StringReplacement
+        # rubocop:disable Style/StringLiterals
+        expression = expression.gsub('\n', "")
+        expression = expression.gsub('\\', "")
+        expression = expression.gsub(/\s{2,}/, " ")
+        # rubocop:enable Style/StringLiterals
+        # rubocop:enable Performance/StringReplacement
```
Comment (eileencodes) [inline activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:663]: We don't generally do rubocop enable/disable in the files because it pollutes them. We instead add them to the exclude list. 

This method should also be moved to the private namespace, we don't want applications to call this method.

**Review by eileencodes — CHANGES_REQUESTED** [review]

File: activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb (hunk 1 above)
Comment (stevehill1981) [reply activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:663]: Will tweak that this afternoon, thanks @eileencodes.

Comment (stevehill1981) [reply activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb]: Tweaks made!

Comment (stevehill1981) [reply activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb]: I had to add a couple of extra files to the exclusions for `Performance/StringReplacement`, when I excluded the file I edited there were other changes that Rubocop flagged. Let me know if those need to be removed again.

File: activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb [hunk 2]
```diff
@@ -714,6 +715,16 @@ def extract_precision(sql_type)
       EMULATE_BOOLEANS_TRUE = { emulate_booleans: true }.freeze
 
       private
+        def strip_whitespace_characters(expression)
+          # These statements use single quotes because the expression may contain
+          # strings of these characters, _not_ the escaped versions that using
+          # double quotes would produce.
+          expression = expression.gsub('\n', "")
+          expression = expression.gsub('\\', "")
```
Comment (byroot) [inline activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:723]: It's unclear to me if you are trying to strip `\` or `\\`.

Also it would make sense to merge these two gsub together as a regexp, that would also fix the rubocop issue.

File: .rubocop.yml [hunk 3]
```diff
@@ -319,6 +321,10 @@ Performance/ReverseEach:
 
 Performance/StringReplacement:
   Enabled: true
+  Exclude:
+    - 'activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb'
+    - 'activerecord/test/cases/validations_test.rb'
+    - 'activesupport/test/xml_mini_test.rb'
```
[the remark this answers is not in the document]
Comment (stevehill1981) [reply .rubocop.yml:327]: This is what came out of Rubocop when I ran it:

```
activesupport/test/xml_mini_test.rb:356:36: C: [Correctable] Performance/StringReplacement: Use tr instead of gsub.
      assert_equal expected_base64.gsub(/\n/, " ").strip, parser.call(base64)
                                   ^^^^^^^^^^^^^^^
activesupport/test/xml_mini_test.rb:360:36: C: [Correctable] Performance/StringReplacement: Use tr instead of gsub.
      assert_equal expected_base64.gsub(/\n/, " ").strip, parser.call(base64, "encoding" => "base64")
                                   ^^^^^^^^^^^^^^^
```

File: activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb (hunk 2 above)
Comment (stevehill1981) [reply activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:723]: 👍🏻 I'll tweak that next.

File: .rubocop.yml (hunk 3 above)
[the remark this answers is not in the document]
Comment (byroot) [reply .rubocop.yml:327]: Not sure what is going on, but you haven't touched that file, and it passes CI. Anyway, I don't think you need any of these exclusion, the code can both be made more performant and not need any exception.

[the remark this answers is not in the document]
Comment (stevehill1981) [reply .rubocop.yml]: Thanks, @byroot - I've removed the exclusions and merged the `gsub` calls as you suggested above.

File: activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb (hunk 2 above)
Comment (stevehill1981) [reply activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb]: Done 😁 Thanks for the detailed feedback on this.

File: .rubocop.yml [hunk 4]
```diff
@@ -197,6 +197,8 @@ Layout/SpaceInsideParens:
 Style/StringLiterals:
   Enabled: true
   EnforcedStyle: double_quotes
+  Exclude:
+    - 'activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb'
```
[the remark this answers is not in the document]
Comment (stevehill1981) [reply .rubocop.yml:201]: Just spotted this! Pushing a new version now.

File: activerecord/test/cases/migration/check_constraint_test.rb [hunk 5]
```diff
@@ -44,6 +54,18 @@ def test_check_constraints
             assert_equal "price > discounted_price", constraint.expression
           end
 
+          if current_adapter?(:Mysql2Adapter)
```
Comment (eileencodes) [inline activerecord/test/cases/migration/check_constraint_test.rb:57]: Code looks good but this new test is flaky https://buildkite.com/rails/rails/builds/95406#01874c8b-219b-4629-8c29-d7070ffbf1cf/1066-1075 (didn't fail on all mysql builds but did fail on some).

File: .rubocop.yml (hunk 3 above)
[the remark this answers is not in the document]
Comment (stevehill1981) [reply .rubocop.yml]: I've just added `if_exists: true` to the `remove_check_constraint` call, I'm assuming it's just a timing issue but hopefully this will help me figure out what's going wrong otherwise.

File: activerecord/test/cases/migration/check_constraint_test.rb (hunk 5 above)
Comment (stevehill1981) [reply activerecord/test/cases/migration/check_constraint_test.rb:57]: With my last change, it succeeds everywhere EXCEPT for MariaDB... which looks like it might be because the `JSON_SCHEMA_VALID` function only exists in MySQL 8.0. I'm not sure if we need to care about that or not; I'm inclined to switch to another function that definitely does exist.

Comment (stevehill1981) [reply activerecord/test/cases/migration/check_constraint_test.rb:57]: I've moved to `JSON_CONTAINS`, which looks like it's fine on both MySQL and MariaDB. It wasn't important in this case which function call was being used, just that it was correctly handled when it _was_ used.

**Review by eileencodes — APPROVED** [review]

**Comment by eileencodes** [comment]
Thanks @stevehill1981! Congrats on your first Rails commit 🎉

**Comment by stevehill1981** [comment]
Thank you @eileencodes and @byroot for shepherding me through this process and giving such useful feedback! I'm really pleased to see this landing 😃

**Comment by chen-anders** [comment]
We just got hit by this issue after we switched t usingo MySQL 8.0.32 - I see that this change did not make it to the respective 7.0.6 release - would there be a timeline for that?

**Comment by byroot** [comment]
We didn't think of backporting it. 

I just did at 0efee08e9fd7f97f3ddfeef64b821db129544d3a, you can point your gemfile at the 7-0-stable branch.
