### PR TITLE
Fix capybara driver name conflict

### LINKED ISSUE #42502: ActionDispatch::SystemTesting::Driver doesn't allow the use of more than one selenium-based driver
### Steps to reproduce

I've got a [reproducible example in a separate repo](https://github.com/cjlarose/rails-issue-system-test-case-driver-name-conflict), but for brevity, the important part is this:

```ruby
class ChromeGUITest < ActionDispatch::SystemTestCase
  driven_by :selenium, using: :chrome

  def test_stuff
    page.visit "/"
    assert_empty Capybara.current_session.driver.options[:options].args
  end
end

class ChromeHeadlessTest < ActionDispatch::SystemTestCase
  driven_by :selenium, using: :headless_chrome

  def test_stuff
    page.visit "/"
    assert_includes Capybara.current_session.driver.options[:options].args, '--headless'
  end
end
```

### Expected behavior

I'd expect the tests in `ChromeGUITest` to execute using the Capybara driver that's configured to use Chrome with a GUI and for the tests in `ChromeHeadlessTest` to execute using the Capybara driver that's configured to use headless Chrome.

### Actual behavior

If the GUI test runs first, then both tests use a GUI. If the headless test runs first, then both tests use headless Chrome.

### System configuration

**Rails version**: main at 98d48cf3a269aaae53777a19fea0a9e3740a00c5

**Ruby version**: 2.7.2

### Additional info

The `@name` instance variable for `ActionDispatch::SystemTesting::Driver` is used both as the driver name when registering the driver with Capybara as well as for determining how to construct a Capybara Driver instance. I think conflating these two roles is the source of the problem.

https://github.com/rails/rails/blob/98d48cf3a269aaae53777a19fea0a9e3740a00c5/actionpack/lib/action_dispatch/system_testing/driver.rb#L33-L40

Of course, it's possible to give a different `name` to the `ActionDispatch::SystemTesting::Driver`, but then the code for actually constructing the driver instance in `register_selenium` isn't called. So a workaround is to create a custom Driver subclass and assign it manually

```ruby
class ChromeGUITest < ActionDispatch::SystemTestCase
  class ChromeGUIDriver < ActionDispatch::SystemTesting::Driver
    private

    def registerable?
      true
    end

    def register
      Capybara.register_driver @name do |app|
        register_selenium(app)
      end
    end
  end

  self.driver = ChromeGUIDriver.new :chrome_gui, using: :chrome
  
  ...
end
```

But that's a bit cumbersome.

I think one solution to this problem is to just dynamically construct the driver name given to `Capybara.register_driver` in such a way that it's guaranteed to be unique.

### PR DESCRIPTION
**Pull request by cjlarose**
Fixes #42502

Related work: #28144, 7c9af60e5c26941dc9ec6a263f5fc5fe10050cba, #32468

### CODE REVIEW

**Comment by zzak** [comment]
@cjlarose Could you add a [CHANGELOG](https://github.com/rails/rails/blob/main/actionpack/CHANGELOG.md) please?

**Comment by cjlarose** [comment]
@zzak Done!

File: actionpack/lib/action_dispatch/system_testing/driver.rb [hunk 1]
```diff
@@ -23,15 +23,19 @@ def use
       end
 
       private
+        def name
+          @name ||= "#{@driver_type}-#{object_id}"
+        end
+
```
Comment (rmacklin) [inline actionpack/lib/action_dispatch/system_testing/driver.rb:29]: One more thought - in https://github.com/rails/rails/issues/32468, @Edouard-chin had proposed that `driven_by` could be given an additional parameter that allows consumers specify the name to use when registering the driver with Capybara. Is that something that we should consider? (It could be an optional parameter, falling back to the `#{driver}_#{using}_#{object_id}` default.)

It might make the "constructing a `Capybara::Session` manually" use case easier since the consumer could simply pass the symbol they used in the original `driven_by` declaration, rather than getting the `ActionDispatch::SystemTesting::Driver` instance and calling `name` on it.

Comment (cjlarose) [reply actionpack/lib/action_dispatch/system_testing/driver.rb]: Implemented the ability the specify the driver name explicitly in 97313e0.

File: actionpack/lib/action_dispatch/system_testing/driver.rb [hunk 2]
```diff
@@ -23,15 +23,19 @@ def use
       end
 
       private
+        def name
+          @name ||= "#{@driver_type}-#{object_id}"
+        end
```
[the remark this answers is not in the document]
Comment (cjlarose) [reply actionpack/lib/action_dispatch/system_testing/driver.rb]: Since `ActionDispatch::SystemTesting::Driver` is marked `:nodoc:`, I don't think users are meant to interact with its API directly.

That said, `ActionDispatch::SystemTestCase` doesn't right now offer an ergonomic way to temporarily switch drivers or session outside of the `driven_by` interface. `driven_by` only really works on a per-class basis, so you wanted something more granular, you'd have to use Capybara's API directly. Without a way to get the driver name, I understand that'd be cumbersome. Instead, I think offering the ability for users to specify the Capybara driver name explicitly makes sense 97313e0.

File: actionpack/lib/action_dispatch/system_testing/driver.rb (hunk 1 above)
[the remark this answers is not in the document]
Comment (cjlarose) [reply actionpack/lib/action_dispatch/system_testing/driver.rb]: Added `:using` to the computed driver names in 74fe175

I also actually ended up removing the `object_id` in dd39de9. There's pros and cons to this, but I think the `#{driver}_#{using}` solves the majority use case, and everything else is satisfied by the explicit `name` parameter.

**Review by rmacklin — COMMENTED** [review]
Latest changes look solid!

File: actionpack/lib/action_dispatch/system_testing/driver.rb [hunk 3]
```diff
@@ -3,17 +3,21 @@
...
         @options = options[:options] || {}
         @capabilities = capabilities
 
-        if name == :selenium
+        if driver_type == :selenium
           require "selenium/webdriver"
           @browser.preload
         end
+
+        @name = options[:name] || [driver_type, options[:using], object_id].compact.map(&:to_s).join("_").to_sym
```
Comment (eileencodes) [inline actionpack/lib/action_dispatch/system_testing/driver.rb:20]: `[driver_type, options[:using], object_id].compact.map(&:to_s).join("_").to_sym` feels needlessly verbose. I don't understand why we wouldn't use only `driver_type` if name is not supplied.

File: actionpack/test/dispatch/system_testing/system_test_case_test.rb [hunk 4]
```diff
@@ -5,33 +5,41 @@
 
 class SetDriverToRackTestTest < DrivenByRackTest
   test "uses rack_test" do
-    assert_equal :rack_test, Capybara.current_driver
+    assert_equal :rack_test, self.class.driver.instance_variable_get(:@driver_type)
```
Comment (eileencodes) [inline actionpack/test/dispatch/system_testing/system_test_case_test.rb:8]: These test changes on `current_driver` feel incorrect to me. `Capbyara.current_driver` isn't an API we control - it should still return the same symbol it was returning before. If we also want to test that `driver_type` returns `:rack_test` then that should be an additional assertion rather than replacing this assertion.

**Review by eileencodes — CHANGES_REQUESTED** [review]

File: actionpack/lib/action_dispatch/system_testing/driver.rb (hunk 3 above)
Comment (cjlarose) [reply actionpack/lib/action_dispatch/system_testing/driver.rb:20]: The PR as written basically just takes the stance that the Capybara driver name should be guaranteed to be unique if left unspecified because that's the least surprising behavior. Users using `driven_by` might not necessarily understand that the Capybara driver name is derived entirely from `driver_type` and that they would need to do additional work (specifying the `name` explicitly) in order to avoid conflicts.

The downside, of course, is that this would break existing test code that has a dependency on the specific Capybara driver name.

I'm fine with making the default Capybara driver name just the `driver_type` (essentially mimicking the current behavior), as long as it's clear that doing so doesn't actually address #42502 in a particularly satisfying way: it puts the burden on the user to recognize that they've got multiple drivers with the same `driver_type` (and thus, the same Capybara driver name).

Comment (cjlarose) [reply actionpack/lib/action_dispatch/system_testing/driver.rb:20]: One option that might be nice is use the `driver_type` as the default driver name as you suggest, but do it in a way that if the user registers multiple Capybara drivers with the same name, we raise an exception.

That way we can keep existing driver names in tact, but we also don't surprise users if there's a conflict.

Comment (eileencodes) [reply actionpack/lib/action_dispatch/system_testing/driver.rb:20]: > The PR as written basically just takes the stance that the Capybara driver name should be guaranteed to be unique if left unspecified because that's the least surprising behavior

I don't agree with this. I wouldn't expect the driver name to be unique. Maybe that's because I'm the author of this feature, but if I did not set a custom name I would be very surprised if Rails returned a combined name with an object id in it.

> The downside, of course, is that this would break existing test code that has a dependency on the specific Capybara driver name.

We definitely can't merge this as is without a deprecation. We should avoid changing existing behavior without a deprecation cycle.

> it puts the burden on the user to recognize that they've got multiple drivers with the same driver_type (and thus, the same Capybara driver name)

But that's how Capybara works. I think if someone is adding multiple drivers with the same type then application authors need to be aware of how to customize that.

Comment (cjlarose) [reply actionpack/lib/action_dispatch/system_testing/driver.rb:20]: How do you feel about raising an exception if the same Capybara driver name is registered multiple times?

**Comment by cjlarose** [comment]
@eileencodes I pushed up changes based on your feedback.

**Comment by cjlarose** [comment]
Rebased to fix conflicts in the CHANGELOG.

@eileencodes Please let me know if you have any other feedback.

File: actionpack/CHANGELOG.md [hunk 5]
```diff
@@ -26,6 +26,12 @@
 
     *Tadas Sasnauskas*
 
+*   Add support to `ActionDispatch::SystemTestCase::driven_by` for specifying the Capybara driver name in order to allow users to prevent conflicts among drivers that use the same driver type (selenium, poltergeist, webkit, rack test).
+
+    Fixes #42502
+
+    *Chris LaRose*
```
Comment (eileencodes) [inline actionpack/CHANGELOG.md:33]: This needs to go at the top of the changelog.

**Review by eileencodes — CHANGES_REQUESTED** [review]
Can you fix the conflicts and squash so there's only one commit?

File: actionpack/lib/action_dispatch/system_test_case.rb [hunk 6]
```diff
@@ -151,8 +151,10 @@ def self.start_application # :nodoc:
     #   driven_by :selenium, using: :firefox
     #
     #   driven_by :selenium, using: :headless_firefox
-    def self.driven_by(driver, using: :chrome, screen_size: [1400, 1400], options: {}, &capabilities)
-      driver_options = { using: using, screen_size: screen_size, options: options }
+    #
+    #   driven_by :selenium, name: :custom_driver_name
+    def self.driven_by(driver, using: :chrome, screen_size: [1400, 1400], options: {}, name: nil, &capabilities)
```
Comment (eileencodes) [inline actionpack/lib/action_dispatch/system_test_case.rb:156]: I think that `name` will not be an often used kwarg, so I'm thinking maybe it should go into the options hash instead and then deleted from the hash before being sent to capybara.

**Comment by rmacklin** [comment]
@eileencodes I'm curious about your thoughts on https://github.com/rails/rails/pull/42511#discussion_r653739650. I personally feel that raising in that situation is preferable to the existing behavior of silently ignoring the conflicting `driven_by` configuration. What do you think?

**Comment by cjlarose** [comment]
@eileencodes I squashed, fixed conflicts, moved the CHANGELOG entry, and moved `name` into the `options` hash.

File: actionpack/CHANGELOG.md [hunk 7]
```diff
@@ -1,3 +1,9 @@
+*   Add support to `ActionDispatch::SystemTestCase::driven_by` for specifying the Capybara driver name in order to allow users to prevent conflicts among drivers that use the same driver type (selenium, poltergeist, webkit, rack test).
```
Comment (zzak) [inline actionpack/CHANGELOG.md:1]: Knit: could you wrap the CHANGELOG to 80 chars, I know this isn't always followed (like the log below 👇 ) but we do [ask that you wrap them "around 80 chars"](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#updating-the-changelog). 🙏

Comment (cjlarose) [reply actionpack/CHANGELOG.md]: Fixed in 3611dd2d8e

**Comment by cjlarose** [comment]
Still just waiting on feedback, I think @rails-bot
