### PR TITLE
Fix ignored options in the `#added?` method

### LINKED ISSUE #34416: `#added?` ignores the options if the message is a symbol
### Steps to reproduce

This test case passes with ActiveRecord 5.1.6, but fails with ActiveRecord 5.2.1

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :people, force: true do |t|
    t.string :name
  end
end

class Person < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_added_checks_the_options_as_well_as_the_error_itself
    person = Person.new
    person.errors.add :name, :too_long, { count: 25 }
    
    assert person.errors.added? :name, :too_long, count: 25
    assert person.errors.added? :name, "is too long (maximum is 25 characters)"
    
    refute person.errors.added? :name, :too_long, count: 24
    refute person.errors.added? :name, :too_long
    refute person.errors.added? :name, "is too long"
  end
end
```

### Expected behavior

As documented, if the error message requires an option, then `#added?` should return `true` with the correct option, or `false` with an incorrect or missing option.

### Actual behavior

`#added?` returns `true` no matter what the option is, as long as the error is present on the attribute.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.3

### PR DESCRIPTION
**Pull request by r3trofitted**
Fixes #34416

### Summary

A bug was introduced in ActiveModel 5.2 (see commit 15cb4ef); because of it, `ActiveRecord::Errors::added?` returns `true` even when the details of the error that is checked differ. However, as documented, it should not:

> If the error message requires an option, then it returns true with the correct option, or false with an incorrect or missing option.
> 
> ```ruby
> person.errors.add :name, :too_long, { count: 25 }
> person.errors.added? :name, :too_long, count: 25                     # => true
> person.errors.added? :name, "is too long (maximum is 25 characters)" # => true
> person.errors.added? :name, :too_long, count: 24                     # => false
> person.errors.added? :name, :too_long                                # => false
> person.errors.added? :name, "is too long"                            # => false
> ```

### Other Information

`#added?` basically works in two different ways depending on the `message` attribute. If it's a string, then it looks for the message itself. If it's a symbol, it looks for the details of the error: the error itself, and its details.

(The method used to generate the message, when given a symbol, so that it could look for it has if it has been given a string. This took care of the need to take into consideration the details, since they are included in the message, but could return false positives if two errors has the same message. This is what 15cb4ef tried to fix.)

### CODE REVIEW

File: activemodel/lib/active_model/errors.rb [hunk 1]
```diff
@@ -327,11 +327,11 @@ def add(attribute, message = :invalid, options = {})
     #  person.errors.added? :name, :too_long                                # => false
     #  person.errors.added? :name, "is too long"                            # => false
     def added?(attribute, message = :invalid, options = {})
+      message = message.call if message.respond_to?(:call)
+
       if message.is_a? Symbol
-        self.details[attribute.to_sym].map { |e| e[:error] }.include? message
+        @details[attribute.to_sym].include? normalize_detail(message, options)
```
Comment (rafaelfranca) [inline activemodel/lib/active_model/errors.rb]: why `@details` and not `details?`

**Comment by r3trofitted** [comment]
I’ve switched from calling the instance variable to calling the reader accessor. Let me known if there’s anything else I should fix.

File: activemodel/test/cases/errors_test.rb [hunk 2]
```diff
@@ -228,6 +228,15 @@ def test_no_key
     assert_not person.errors.added?(:name)
   end
 
+  test "added? returns false when checking for an error with an incorrect or missing option" do
+    person = Person.new
+    person.errors.add :name, :too_long, count: 25
+
```
Comment (albertoalmagro) [inline activemodel/test/cases/errors_test.rb]: Could we please also check that it returns `true` as expected?

```suggestion
assert person.errors.added? :name, :too_long, count: 25
```

Comment (r3trofitted) [reply activemodel/test/cases/errors_test.rb]: 👍

**Review by albertoalmagro — APPROVED** [review]
Thanks @r3trofitted !!

**Comment by r3trofitted** [comment]
👍 You're welcome!

**Comment by rafaelfranca** [comment]
Looks good to me. Can you squash your commits?
