### PR TITLE
Fix: Incorrectly preloading through association records when middle association has been loaded

### LINKED ISSUE #45542: ActiveRecord: Bad handling of already loaded middle association in Associations::Preloaders::ThroughAssociation
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", "7.0.2.4"
  gem "sqlite3"
end

require "active_record"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :cards, force: true do |t|
    t.references :card_data
  end

  create_table :card_data, force: true do |t|
    t.references :player
  end

  create_table :players, force: true do |t|
    t.references :active_club
  end

  create_table :teams, force: true do |t|
    t.string :type
  end
end

class Card < ActiveRecord::Base
  belongs_to :card_data
  has_one :player, through: :card_data
  has_one :active_club, through: :player
end

class CardData < ActiveRecord::Base
  belongs_to :player
end

class Player < ActiveRecord::Base
  belongs_to :active_club, class_name: 'Club' # NB: if class_name: 'Team' this works
end

class Team < ActiveRecord::Base
end

class Club < Team
end

player = Player.create!
card_data = CardData.create!(player:)
card = Card.create!(card_data:)

card.reload.player # NB: if removed this works
::ActiveRecord::Associations::Preloader.new(records: [card], associations: :active_club).call.then(&:first)
```

### Expected behavior
The association should be loaded properly

### Actual behavior
```
/Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/through_association.rb:31:in `block (2 levels) in records_by_owner': undefined method `[]' for nil:NilClass (NoMethodError)

              source_records_by_owner[record]
                                     ^^^^^^^^
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/through_association.rb:30:in `each'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/through_association.rb:30:in `flat_map'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/through_association.rb:30:in `block in records_by_owner'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/through_association.rb:14:in `each'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/through_association.rb:14:in `each_with_object'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/through_association.rb:14:in `records_by_owner'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/association.rb:122:in `run'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/batch.rb:28:in `each'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader/batch.rb:28:in `call'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/activerecord-7.0.2.4/lib/active_record/associations/preloader.rb:118:in `call'
	from test_source_records_by_owner.rb:62:in `<main>'
```

### System configuration
**Rails version**: 7.0.2.4

**Ruby version**: 3.1.1

### LINKED ISSUE #45822: ActiveRecord: Wrong results returned by ActiveRecord::Associations::Preloader when intermediate association is already preloaded.
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", "7.0.3.1"
  gem "sqlite3"
end

require "active_record"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :a_records, force: true

  create_table :b_records, force: true do |t|
    t.references :a_record
    t.references :c_record
  end

  create_table :c_records, force: true

  create_table :d_records, force: true do |t|
    t.references :c_record
  end
end

class ARecord < ActiveRecord::Base
  has_one :b_record
  has_one :c_record, through: :b_record
  has_many :d_records, through: :c_record
end

class BRecord < ActiveRecord::Base
  belongs_to :a_record
  belongs_to :c_record
end

class CRecord < ActiveRecord::Base
  has_one :b_record
  has_many :d_records
end

class DRecord < ActiveRecord::Base
  belongs_to :c_record
end

a = ARecord.create!
c = CRecord.create!
BRecord.create!(a_record: a, c_record: c)
DRecord.create!(c_record: c)
DRecord.create!(c_record: c)

a.reload
a.c_record # NB: if removed this works

::ActiveRecord::Associations::Preloader.new(records: [a], associations: :d_records).call
puts({ record_ids: a.d_records.map(&:id), size: a.d_records.size })
```

### Expected behavior
Two records should be loaded:
`{:record_ids=>[1, 2], :size=>2}`

### Actual behavior
No records are loaded:
`{:record_ids=>[], :size=>0}`

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 2.7.5

### PR DESCRIPTION
**Pull request by joshuay03**
Fix: https://github.com/rails/rails/issues/45822

This Pull Request has been created to address https://github.com/rails/rails/issues/45822.

**Update:** Looks like this also resolves https://github.com/rails/rails/issues/45542.

### Detail

This Pull Request fixes `ActiveRecord::Associations::Preloader::ThroughAssociation#records_by_owner` to:
1. successfully fetch the loaded source records for an already loaded middle record
2. do so without performing unnecessary queries

**RE: 1**
Using a failing test and some logging, I found that the memoized keys in `source_records_by_owner` had different `object_id`s to the values in `through_records_by_owner` **at the point at which the value was fetched using `source_records_by_owner[record]`** and was therefore returning `nil`.

This was being caused by `def middle_records` loading new objects into `@preloaded_records` which would get passed in as the records for the source preloader, rather than using the already loaded through objects in `through_records_by_owner`.

This resulted in the `source_records_by_owner` hash containing keys which were different objects to the values in the `through_records_by_owner` hash.

**RE: 2**
This also happens to fix a circular dependency of sorts, since `def middle_records` would eventually call `def source_preloaders` while already in a previous call to it originating from `def source_records_by_owner`, causing the through record/s to reload and the source record/s to load, before finally loading the source records once again. These extra queries are visible in my comment below.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [x] CI is passing.

### CODE REVIEW

File: activerecord/test/cases/associations_test.rb [hunk 1]
```diff
@@ -502,6 +505,19 @@ def test_preload_grouped_queries_with_already_loaded_records
...
+    member_details = member_details(:groucho)
+    member = member_details.member
+    member_detail_ids = member.organization_member_details_2.pluck(:id)
+
+    member.reload
+    member.organization
+
+    ::ActiveRecord::Associations::Preloader.new(records: [member], associations: :organization_member_details_2).call
+
+    assert_equal member_detail_ids.sort, member.organization_member_details_2.map(&:id).sort
```
Comment (joshuay03) [inline activerecord/test/cases/associations_test.rb:518]: Fails without the fix above.

File: activerecord/test/cases/associations_test.rb [hunk 2]
```diff
@@ -502,6 +505,21 @@ def test_preload_grouped_queries_with_already_loaded_records
...
+    member = member_details.member
+    member_detail_ids = member.organization_member_details_2.pluck(:id)
+
+    member.reload
+    member.organization
+
+    ::ActiveRecord::Associations::Preloader.new(records: [member], associations: :organization_member_details_2).call
+
+    assert_no_queries do
+      assert_equal member_detail_ids.sort, member.organization_member_details_2.map(&:id).sort
```
Comment (joshuay03) [inline activerecord/test/cases/associations_test.rb:519]: Fails without the fix above.

File: activerecord/test/cases/associations_test.rb [hunk 3]
```diff
@@ -502,6 +505,21 @@ def test_preload_grouped_queries_with_already_loaded_records
...
+    member = member_details.member
+    expected_member_detail_ids = member.organization_member_details_2.pluck(:id)
+
+    member.reload
+    member.organization
+
+    ::ActiveRecord::Associations::Preloader.new(records: [member], associations: :organization_member_details_2).call
+
+    assert_no_queries do
+      assert_equal expected_member_detail_ids.sort, member.organization_member_details_2.map(&:id).sort
```
Comment (joshuay03) [inline activerecord/test/cases/associations_test.rb:519]: Fails without the fix above.

File: activerecord/lib/active_record/associations/preloader/through_association.rb [hunk 4]
```diff
@@ -12,13 +12,15 @@ def records_by_owner
           return @records_by_owner if defined?(@records_by_owner)
 
           @records_by_owner = owners.each_with_object({}) do |owner, result|
+            through_records = through_records_by_owner[owner] || []
+
             if loaded?(owner)
-              result[owner] = target_for(owner)
+              result[owner] = through_records.flat_map do |record|
+                source_records_by_owner[record] || []
+              end
```
Comment (joshuay03) [inline activerecord/lib/active_record/associations/preloader/through_association.rb:20]: When the intermediate record was preloaded, result[owner] was set with a new `target_for(owner)` instead of using the already loaded records.

This resulted in a different objects for:
- the values of `records_by_owner` of the through objects
- the keys of `records_by_owner` for the source records
which were expected to be the same.

File: activerecord/test/cases/associations_test.rb [hunk 5]
```diff
@@ -502,6 +505,24 @@ def test_preload_grouped_queries_with_already_loaded_records
...
+
+    member.reload
+    member.organization # load through record
+
+    assert_queries(1) do
+      ::ActiveRecord::Associations::Preloader.new(records: [member], associations: :organization_member_details_2).call
+    end
+
+    assert_no_queries do
+      assert_equal all_member_detail_ids.sort, member.organization_member_details_2.map(&:id).sort
```
Comment (joshuay03) [inline activerecord/test/cases/associations_test.rb:522]: Fails without the fix above.

File: activerecord/test/cases/associations_test.rb [hunk 6]
```diff
@@ -502,6 +505,24 @@ def test_preload_grouped_queries_with_already_loaded_records
...
+    all_member_detail_ids = member.organization_member_details_2.pluck(:id)
+
+    assert_equal all_member_detail_ids.sort, member.organization.member_details.map(&:id).sort
+
+    member.reload
+    member.organization # load through record
+
+    assert_queries(1) do
+      ::ActiveRecord::Associations::Preloader.new(records: [member], associations: :organization_member_details_2).call
+    end
```
Comment (joshuay03) [inline activerecord/test/cases/associations_test.rb:519]: Down from 3 queries 🎉
Screenshot 2022-11-30 at 6 28 56 pm

File: activerecord/test/cases/associations_test.rb [hunk 7]
```diff
@@ -502,6 +505,22 @@ def test_preload_grouped_queries_with_already_loaded_records
...
+
+    assert_no_queries do
+      assert_equal expected_member_detail_ids.sort, member.organization_member_details_2.map(&:id).sort
```
Comment (joshuay03) [inline activerecord/test/cases/associations_test.rb:520]: This fails without the fix above
Screenshot 2022-11-30 at 6 39 00 pm

File: activerecord/test/cases/associations_test.rb [hunk 8]
```diff
@@ -521,6 +524,22 @@ def test_preload_grouped_queries_of_through_records
...
+
+    member.reload
+    member.organization # load through record
+
+    assert_queries(1) do
+      ActiveRecord::Associations::Preloader.new(records: [member], associations: :organization_member_details_2).call
+    end
+
+    assert_no_queries do
+      assert_equal expected_member_detail_ids.sort, member.organization_member_details_2.map(&:id).sort
```
Comment (joshuay03) [inline activerecord/test/cases/associations_test.rb:539]: This fails without the fix above
Screenshot 2022-11-30 at 6 39 00 pm

File: activerecord/test/cases/associations_test.rb [hunk 9]
```diff
@@ -521,6 +524,22 @@ def test_preload_grouped_queries_of_through_records
...
 
+  def test_preload_through_records_with_already_loaded_middle_records
+    member = members(:groucho)
+    expected_member_detail_ids = member.organization_member_details_2.pluck(:id)
+
+    member.reload
+    member.organization # load through record
+
+    assert_queries(1) do
+      ActiveRecord::Associations::Preloader.new(records: [member], associations: :organization_member_details_2).call
```
Comment (joshuay03) [inline activerecord/test/cases/associations_test.rb:535]: Down from 3 queries to 1 🎉
Screenshot 2022-11-30 at 6 28 56 pm

Comment (joshuay03) [inline activerecord/test/cases/associations_test.rb:535]: Down from 3 queries to 1 🎉
Screenshot 2022-11-30 at 6 28 56 pm

File: activerecord/test/cases/associations_test.rb [hunk 10]
```diff
@@ -521,6 +524,21 @@ def test_preload_grouped_queries_of_through_records
...
+    expected_member_detail_ids = member.organization_member_details_2.pluck(:id)
+
+    member.reload.organization # load through record
+
+    assert_queries(1) do
+      ActiveRecord::Associations::Preloader.new(records: [member], associations: :organization_member_details_2).call
+    end
+
+    assert_no_queries do
+      assert_equal expected_member_detail_ids.sort, member.organization_member_details_2.map(&:id).sort
```
Comment (joshuay03) [inline activerecord/test/cases/associations_test.rb:538]: This fails without the fix above
Screenshot 2022-11-30 at 6 39 00 pm

File: activerecord/test/cases/associations_test.rb [hunk 11]
```diff
@@ -521,6 +524,21 @@ def test_preload_grouped_queries_of_through_records
...
   end
 
+  def test_preload_through_records_with_already_loaded_middle_record
+    member = members(:groucho)
+    expected_member_detail_ids = member.organization_member_details_2.pluck(:id)
+
+    member.reload.organization # load through record
+
+    assert_queries(1) do
+      ActiveRecord::Associations::Preloader.new(records: [member], associations: :organization_member_details_2).call
```
Comment (joshuay03) [inline activerecord/test/cases/associations_test.rb:534]: Down from 3 queries to 1 🎉
Screenshot 2022-11-30 at 6 28 56 pm

**Comment by zzak** [comment]
FWIW, I've confirmed this fixes the issue described in #45542, but I'm not authoritative enough to say whether or not it's a real bug.

**Comment by joshuay03** [comment]
> FWIW, I've confirmed this fixes the issue described in #45542, but I'm not authoritative enough to say whether or not it's a real bug.

Thanks! I've updated the PR description with this issue too.

**Comment by such** [comment]
This looks great! Thanks!

**Comment by joshuay03** [comment]
Cheers! @byroot

**Comment by yopzer** [comment]
Hi, Thanks for the fix, this issue was blocking application I work on from upgrading to Rails 7.0. If I understand correctly how rails releases work, this fix will be included in Rails 7.1 release as it was merged in `rails:main` branch and the work on 7.1 is already in progress. Any chances getting this in 7.0?

**Comment by yopzer** [comment]
Thanks a lot!
