### PR TITLE
Raise StaleObjectError if touched object is stale and locking is enabled

### LINKED ISSUE #19776: "touch" can corrupt lock_version and does not raise StaleObjectError
In Rails 4.2, ActiveRecord::Persistence.touch increments lock_version (if optimistic locking is in use), but bypasses ActiveRecord::Locking::Pessimistic._update_record, and thereby will happily touch an out-of-date object, possibly corrupting lock_version in the process. Consider:

   p = Post.create(title: 'Original Title') # lock_version = 0
   p2 = Post.find(p.id) # A second in-memory copy. # lock_version = 0
   p.update(title: 'New Title') # lock_version = 1
   p.update(title: 'Another New Title') # lock_version = 2
   p2.touch # Does not raise exception, resets lock_version to 1

I think that the call to touch should raise StaleObjectError. If not, it should at the very least not reset the lock_version to an already used value.

### PR DESCRIPTION
**Pull request by meinac**
Fixes #19776

### CODE REVIEW

File: activerecord/test/cases/locking_test.rb [hunk 1]
```diff
@@ -177,6 +177,16 @@ def test_touch_existing_lock
     assert_equal 1, p1.lock_version
   end
 
+  def test_touch_stale_object
+    p1 = Person.create!(first_name: 'Mehmet Emin')
+    p2 = Person.find(p1.id)
+    p1.update_attribute(:gender, 'M')
+
+    assert_raises(ActiveRecord::StaleObjectError) do
+      p2.touch
```
Comment (kaspth) [inline activerecord/test/cases/locking_test.rb]: Let's go for a bit more readability and change p1 to person and p2 to stale_person. That way we communicate the coming expectation throughout the test.

File: activerecord/lib/active_record/persistence.rb [hunk 2]
```diff
@@ -477,11 +477,21 @@ def touch(*names, time: nil)
...
+
+        if locking_enabled?
+          lock_column = self.class.locking_column
+          lock_val = send(lock_column)
+          changes[lock_column] = increment_lock
+          where_clause[lock_column] = lock_val
+        end
+
+        if self.class.unscoped.where(where_clause).update_all(changes) != 1
+          return locking_enabled? && raise(ActiveRecord::StaleObjectError.new(self, "touch"))
```
Comment (kaspth) [inline activerecord/lib/active_record/persistence.rb]: raise will automatically take us out of the current method. Can this be revised to the below?

```ruby
if self.class.unscoped.where(where_clause).update_all(changes) != 1
  raise ActiveRecord::StaleObjectError.new(self, "touch") if locking_enabled?
end
true # can we remove the true as well? 
```

Comment (meinac) [inline activerecord/lib/active_record/persistence.rb]: @kaspth by this way the method returns ```false``` if locking is not enabled and ```update_all``` result is 0.
If locking enabled and ```update_all``` result is 0 then it will raise an error.Otherwise if the ```update_all``` returns 1 it will return ```true```. If we remove ```true``` from there the method will return ```nil``` on success status. I think you missed these points. Can you look at it again?

File: activerecord/test/cases/locking_test.rb (hunk 1 above)
Comment (meinac) [inline activerecord/test/cases/locking_test.rb]: Sorry, you are right, my bad. I'll change these variable names tomorrow.

File: activerecord/lib/active_record/persistence.rb [hunk 3]
```diff
@@ -477,11 +477,21 @@ def touch(*names, time: nil)
...
         clear_attribute_changes(changes.keys)
         primary_key = self.class.primary_key
-        self.class.unscoped.where(primary_key => self[primary_key]).update_all(changes) == 1
+        where_clause = { primary_key => self[primary_key] }
+
+        if locking_enabled?
+          lock_column = self.class.locking_column
+          lock_val = send(lock_column)
+          changes[lock_column] = increment_lock
+          where_clause[lock_column] = lock_val
```
Comment (sgrif) [inline activerecord/lib/active_record/persistence.rb]: We can just make multiple calls to where, I don't like modifying the hash to pass later like this.

File: activerecord/lib/active_record/persistence.rb (hunk 2 above)
Comment (sgrif) [inline activerecord/lib/active_record/persistence.rb]: Regardless, this is extremely hard to mentally parse. I'd much rather see this split into multiple lines.

```
if scope.update_all(changes) != 1
  if locking_enabled?
    raise ActiveRecord::StaleObjectError.new(self, "touch")
  else
    false
  end
else
  true
end
```

Comment (sgrif) [inline activerecord/lib/active_record/persistence.rb]: Alternatively

```
result = scope.update_all(changes) == 1
if !result && locking_enabled?
  raise ActiveRecord::StaleObjectError.new(self, "touch")
end
result
```

**Comment by meinac** [comment]
@kaspth , @sgrif what do you think about this one?

File: activerecord/lib/active_record/persistence.rb [hunk 4]
```diff
@@ -477,11 +477,20 @@ def touch(*names, time: nil)
           changes[column] = write_attribute(column, time)
         end
 
-        changes[self.class.locking_column] = increment_lock if locking_enabled?
-
         clear_attribute_changes(changes.keys)
         primary_key = self.class.primary_key
-        self.class.unscoped.where(primary_key => self[primary_key]).update_all(changes) == 1
+
+        if locking_enabled?
```
Comment (egilburg) [inline activerecord/lib/active_record/persistence.rb]: How about

```ruby
scope = self.class.unscoped.where(primary_key => send(primary_key)

if locking_enabled?
  lock_column = self.class.locking_column
  lock_val = send(lock_column)
  scope = scope.where(lock_column => lock_val)

  if scope = scope.update_all(changes) != 1
    raise ActiveRecord::StaleObjectError.new(self, "touch")
  end

  true
else
  scope_update_all(changes) == 1
end
```
  

  
```

File: activerecord/lib/active_record/persistence.rb (hunk 2 above)
Comment (egilburg) [inline activerecord/lib/active_record/persistence.rb]: :+1: even better than my suggestion

File: activerecord/lib/active_record/persistence.rb [hunk 5]
```diff
@@ -477,11 +477,20 @@ def touch(*names, time: nil)
...
+          lock_column = self.class.locking_column
+          lock_val = send(lock_column)
+          changes[lock_column] = increment_lock
+          if self.class.unscoped.where(primary_key => send(primary_key), lock_column => lock_val).update_all(changes) != 1
+            raise ActiveRecord::StaleObjectError.new(self, "touch")
+          end
+          true
```
Comment (kaspth) [inline activerecord/lib/active_record/persistence.rb]: It's better but still hard to mentally parse. There's a lot of code crammed into these lines. I still feel like we should go with something more along @sgrif's original suggestion:

```ruby
scope = self.class.unscoped.where(primary_key => send(primary_key))

if locking_enabled?
  scope = scope.where(self.class.locking_column => send(lock_column))
  changes[self.class.locking_column] = increment_lock
end

result = scope.update_all(changes) == 1
if !result && locking_enabled?
  raise ActiveRecord::StaleObjectError.new(self, "touch")
end
result
```

**Comment by meinac** [comment]
@kaspth I think this is ok now.

File: activerecord/lib/active_record/persistence.rb [hunk 6]
```diff
@@ -477,11 +477,21 @@ def touch(*names, time: nil)
           changes[column] = write_attribute(column, time)
         end
 
-        changes[self.class.locking_column] = increment_lock if locking_enabled?
-
         clear_attribute_changes(changes.keys)
         primary_key = self.class.primary_key
-        self.class.unscoped.where(primary_key => self[primary_key]).update_all(changes) == 1
+        scope = self.class.unscoped.where(primary_key => send(primary_key))
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/persistence.rb]: why it is using `send` instead of `self`?

**Comment by kaspth** [comment]
@meinac Looks good :+1:

File: activerecord/lib/active_record/persistence.rb [hunk 7]
```diff
@@ -477,11 +477,21 @@ def touch(*names, time: nil)
...
+
+        if locking_enabled?
+          locking_column = self.class.locking_column
+          scope = scope.where(locking_column => send(locking_column))
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/persistence.rb]: Same here about `send`

File: activerecord/lib/active_record/persistence.rb [hunk 8]
```diff
@@ -477,11 +477,21 @@ def touch(*names, time: nil)
...
+          changes[locking_column] = increment_lock
+        end
+
+        result = scope.update_all(changes) == 1
+        if !result && locking_enabled?
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/persistence.rb]: Put a blank line before the `if` and after the `end`

**Comment by rafaelfranca** [comment]
Looks good to me. Just did some minor comments.

File: activerecord/lib/active_record/persistence.rb (hunk 6 above)
Comment (sgrif) [inline activerecord/lib/active_record/persistence.rb]: Calling `id` is sufficient here.

File: activerecord/lib/active_record/persistence.rb (hunk 7 above)
Comment (sgrif) [inline activerecord/lib/active_record/persistence.rb]: Agreed, but please use `_read_attribute` instead of `[]`

File: activerecord/lib/active_record/persistence.rb (hunk 6 above)
Comment (rafaelfranca) [inline activerecord/lib/active_record/persistence.rb]: If we have to get what is the primary_key anyway I think we could just get the value of the attribute without having to ask again what is the primary key

File: activerecord/lib/active_record/persistence.rb (hunk 7 above)
Comment (rafaelfranca) [inline activerecord/lib/active_record/persistence.rb]: :+1: was just looking at `[]` implementation and `_read_attribute` seems the way to go for both cases.

**Comment by sgrif** [comment]
LGTM as well, other than the comments.

**Comment by meinac** [comment]
@rafaelfranca , @sgrif thanks for the feedbacks. By this way I've learned that id method returns the primary key of the model not only the attribute which name is id. Thanks for this information.

**Comment by rafaelfranca** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by rafaelfranca** [comment]
Backported as 303649000eef76b2151205bae43bd1e53976116a

**Comment by bendilley** [comment]
@rafaelfranca If the backport to 4.2 had to be reverted, doesn't that imply that there's some feature which relies on being able to touch stale objects?! It at least implies that the failing test is doing something wrong 😕
