### PR TITLE
Fixing an issue when parsing an opclass by allowing indexed column in indexdef to be wrapped up by double quotes

### LINKED ISSUE #34493: opclass is not parsed whenever the indexed column in the indexdef is wrapped by quotes
### Steps to reproduce
Add a gin index on a colum with a name `position`.

```
add_index :players, :position, using: :gin, opclass: :gin_trgm_ops, name: 'gin_index_position_on_players'
add_index :players, :name, using: :gin, opclass: :gin_trgm_ops, name: 'gin_index_name_on_players'
```
At the moment, I have only encountered the problem on column with `position` as name. 

### Expected behavior
This should dump properly the index the `schema.rb`.
Something like 
`t.index ["position"], name: "gin_index_position_on_players", opclass: :gin_trgm_ops, using: :gin`

### Actual behavior
It creates an index wihtout an `opclass` in the `db/schema.rb`. Here is what is created: 
`t.index ["position"], name: "gin_index_position_on_positions", using: :gin`

### Investigations done on my own
Creating indexes seems fine. 
However, while checking the created indexes in db using 
```
select *
from pg_indexes
where tablename = 'players';
```
The `indexdef` of the index related to the `position` column is different. The colum name is wrapped with double quotes. 
`indexdef`:`CREATE INDEX gin_index_position_on_players ON public.players USING gin ("position" gin_trgm_ops)`

I did not find out why this particular word is wrapped up (other postgres reserved words are not wrapped up, other built-in functions are not wrapped up). 

The issue occurs while parsing the `indexdef` in `activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:127`. 

It could be fixed by adding this edge case to the regexp. 

**Why does this occurs**
After deeper explanations, I land on https://www.postgresql.org/docs/current/sql-keywords-appendix.html and it seems that this behavior happens on the `non reserved (cannot be function or type)` keyword. 

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.3

### PR DESCRIPTION
**Pull request by ThomBian**
Fixes #34493.

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb [hunk 1]
```diff
@@ -124,7 +124,7 @@ def indexes(table_name) # :nodoc:
 
               # add info on sort order (only desc order is explicitly specified, asc is the default)
               # and non-default opclasses
-              expressions.scan(/(?<column>\w+)\s?(?<opclass>\w+_ops)?\s?(?<desc>DESC)?\s?(?<nulls>NULLS (?:FIRST|LAST))?/).each do |column, opclass, desc, nulls|
+              expressions.scan(/(?<column>\w+\"?)\s?(?<opclass>\w+_ops)?\s?(?<desc>DESC)?\s?(?<nulls>NULLS (?:FIRST|LAST))?/).each do |column, opclass, desc, nulls|
```
Comment (kamipo) [inline activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb]: `"` is not part of column name, and also `\` isn't necessary.

File: activerecord/test/cases/adapters/postgresql/schema_test.rb [hunk 2]
```diff
@@ -530,6 +531,15 @@ def test_non_default_opclass_is_dumped
 
     assert_match(/opclass: \{ description: :text_pattern_ops \}/, output)
   end
+
+  def test_wrapped_column_when_creating_gin_index
+    @connection.enable_extension("pg_trgm")
+    @connection.execute "CREATE INDEX trains_position ON trains USING gin(position gin_trgm_ops)"
```
Comment (kamipo) [inline activerecord/test/cases/adapters/postgresql/schema_test.rb]: Can you add an extra test case that mixed with default opclass like `@connection.execute "CREATE INDEX trains_name_and_description ON trains USING btree(name, position text_pattern_ops)"`?
