### PR TITLE
Better handle SyntaxError in Action View

### LINKED ISSUE #48326: SyntaxError in an autoloading class referenced from a view causes "TypeError: Thread::Backtrace::Location object expected"
If a view renders code that autoloads a class that has a syntax error, `DebugExceptions` fails with a `TypeError: Thread::Backtrace::Location object expected`.

<details>
<summary>Backtrace</summary>

```
TypeError: Thread::Backtrace::Location object expected
 <internal:ast>:112:in `node_id_for_backtrace_location'
~/.rvm/gems/ruby-3.2.2@rails71/bundler/gems/rails-294be7c7de34/actionview/lib/action_view/template.rb:172:in `spot'
~/.rvm/gems/ruby-3.2.2@rails71/bundler/gems/rails-294be7c7de34/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:252:in `spot'
~/.rvm/gems/ruby-3.2.2@rails71/bundler/gems/rails-294be7c7de34/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:302:in `extract_source'
~/.rvm/gems/ruby-3.2.2@rails71/bundler/gems/rails-294be7c7de34/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:206:in `block in source_extracts'
~/.rvm/gems/ruby-3.2.2@rails71/bundler/gems/rails-294be7c7de34/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:205:in `map'
~/.rvm/gems/ruby-3.2.2@rails71/bundler/gems/rails-294be7c7de34/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:205:in `source_extracts'
~/.rvm/gems/ruby-3.2.2@rails71/bundler/gems/rails-294be7c7de34/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:125:in `create_template'
~/.rvm/gems/ruby-3.2.2@rails71/bundler/gems/rails-294be7c7de34/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:77:in `render_for_browser_request'
~/.rvm/gems/ruby-3.2.2@rails71/bundler/gems/rails-294be7c7de34/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:69:in `render_exception'
~/.rvm/gems/ruby-3.2.2@rails71/bundler/gems/rails-294be7c7de34/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:44:in `rescue in call'
~/.rvm/gems/ruby-3.2.2@rails71/bundler/gems/rails-294be7c7de34/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
```

</details>

### Steps to reproduce

`test.rb`:
```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "rack", "~> 2.0"
end

require "action_controller/railtie"

# since DebugExceptions throws its own exception, display it here
module ActionDispatch
  class ShowExceptions
    def call(env)
      @app.call(env)
    rescue Exception => exception
      request = ActionDispatch::Request.new env
      backtrace_cleaner = request.get_header("action_dispatch.backtrace_cleaner")
      wrapper = ExceptionWrapper.new(backtrace_cleaner, exception)
      puts "[SE] #{exception.inspect}"
      puts "[SE]   #{exception.backtrace.join("\n[SE]  ")}"
      if wrapper.show?(request)
        render_exception(request, wrapper)
      else
        raise exception
      end
    end
  end
end

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"
  config.consider_all_requests_local = true

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers
  append_view_path '.'

  def index
    render '/view_test_1'
  end

  # simulate a syntax error in an external, auto-loading class
  def helper_1
    eval %(
      'abc' + pluralize 'def'
    )
  end
  helper_method :helper_1
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    # expecting a DebugExceptions response
    assert_match %r{<header role="banner">|<main role="main"}, last_response.body
  end

  private
    def app
      Rails.application
    end
end
```

`view_test_1.html.erb` (placed in same base dir as test.rb):
```erb
-view-
<%= helper_1 %>
```

### Expected behavior
A standard DebugExceptions response should display the initial `SyntaxError` exception.

### Actual behavior
DebugExceptions itself raises a `TypeError` with message `Thread::Backtrace::Location object expected`, in turn causing a generic 500 error to be returned.

### System configuration
**Rails version**: main

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by cmaruz**
### Motivation / Background

Fixes #48326

This Pull Request has been created to fix an issue where syntax errors generated inside an eval method cause an Internal Server Error due to a TypeError.

### Detail

In order to display the extraced source of a syntax error, we try to locate the node id for the backtrace location. The call to RubyVM::AbstractSyntaxTree.node_id_for_backtrace_location is expecting a Thread::Backtrace::Location object, but we are passing a SourceMapLocation instead.

Once this is fixed, another issue then appears. The first location of the backtrace for an eval error does not include the filename of where eval is called, so we can't extract the source. This means that the development view fails to show the extracted source because it is hard-coded to show the source extracted for the first location.

This commit does two things:
1) it addresses the issue by making sure that we are always passing a Thread::Backtrace::Location instead
2) it allows the development view to show the extracted source fragment by ensuring the first location of the backtrace for a syntax error coming from eval includes the name of the file where eval is called

### Additional information

I have tried to keep the changes consistent with the approach introduced in https://github.com/rails/rails/pull/46171.

### CODE REVIEW

**Comment by cmaruz** [comment]
cc: @tenderlove, @byroot

File: activesupport/lib/active_support/syntax_error_proxy.rb [hunk 1]
```diff
@@ -43,7 +47,20 @@ def backtrace_locations
...
+          # error
+          location = __getobj__.backtrace_locations[0]
+          ["#{location.path}:#{location.lineno}: #{__getobj__}"]
+        else
+          __getobj__.to_s.split("\n")
+        end
+      end
+
+      def error_originated_in_eval_block?
+        __getobj__.to_s.match?(/^\(eval\)/)
```
Comment (byroot) [inline activesupport/lib/active_support/syntax_error_proxy.rb:63]:
```suggestion
        __getobj__.to_s.start_with?("(eval")
```

This won't match anymore in 3.3: https://bugs.ruby-lang.org/issues/19755

File: yarn.lock [hunk 2]
```diff
@@ -63,13 +63,6 @@
     "@jridgewell/resolve-uri" "3.1.0"
     "@jridgewell/sourcemap-codec" "1.4.14"
 
-"@rails/activestorage@>= 7.0.0-alpha1":
-  version "7.0.4"
-  resolved "https://registry.yarnpkg.com/@rails/activestorage/-/activestorage-7.0.4.tgz#56bc3052f60e8867b40a87ed5ff3c0afe536643e"
-  integrity sha512-K2fV9C0z88fapu58nt9uHzMylsmJWUFuaIFvuZQEf1WTiPMsgTsj1bf8+cD81zXfTXYMZDQNRq4164JmuBKD3A==
-  dependencies:
-    spark-md5 "^3.0.1"
-
```
Comment (byroot) [inline yarn.lock:72]: This is unrelated to your PR.

File: activesupport/lib/active_support/core_ext/thread/backtrace/location.rb [hunk 3]
```diff
@@ -9,4 +9,7 @@ def spot(ex)
     def spot(ex)
     end
   end
+  def thread_backtrace_location
```
Comment (byroot) [inline activesupport/lib/active_support/core_ext/thread/backtrace/location.rb:12]:
```suggestion

    def thread_backtrace_location
```

I don't like the idea of adding a core_ext for this.

I'd rather use `is_a?` in the caller. Polymorphism is nicer indeed, but not at the cost of reopening a core class.

Comment (cmaruz) [reply activesupport/lib/active_support/core_ext/thread/backtrace/location.rb:12]: Thanks @byroot! 

I can change the logic to use `is_a?`, but I wanted to keep in line with the spirit of https://github.com/rails/rails/pull/46171 where `Thread::Backtrace::Location` has been monkey patched. 

My fear is that if I change this code to use `is_a?`, then this is not consistent with the rest of the code, which is instead relying on `Thread::Backtrace::Location` being monkey patched.

I am happy to use `is_a?` but I wanted to hear your thoughts.

Comment (byroot) [reply activesupport/lib/active_support/core_ext/thread/backtrace/location.rb:12]: Yeah, I disagree with how @tenderlove implemented it, I think it would have been possible to not add that `Location#spot` method.

Comment (tenderlove) [reply activesupport/lib/active_support/core_ext/thread/backtrace/location.rb:12]: > Yeah, I disagree with how @tenderlove implemented it, I think it would have been possible to not add that `Location#spot` method.

If you want to refactor, I'm fine with it! 😂

One alternative would be to implement `itself` on `BacktraceLocationProxy`.  Then we wouldn't need to add another method to `Thread::Backtrace::Location`

TBH, I think this `def spot(ex)` monkey patch should actually be part of ErrorHighlight.  ErrorHighlight only works with BacktraceLocation objects, so the double dispatch / factory pattern makes sense to me.

Comment (byroot) [reply activesupport/lib/active_support/core_ext/thread/backtrace/location.rb:12]: > If you want to refactor, I'm fine with it! 😂

I know :)

I'll see if get some time to avoid that patch, in the meantime I think we should mark many of this stuff as private API: https://edgeapi.rubyonrails.org/classes/Thread/Backtrace/Location.html#method-i-spot

Comment (cmaruz) [reply activesupport/lib/active_support/core_ext/thread/backtrace/location.rb:12]: Thanks guys!

I have made the following changes to `exception_wrapper.rb`:

- Before calling `spot` on the template object, check if we have a real Thread::Backtrace::Location object to prevent calling MRI with the wrong object;
- When building the SourceMapLocation object, ensure that we are passing a Thread::Backtrace::Location object and not a BacktraceLocationProxy object

File: activesupport/lib/active_support/syntax_error_proxy.rb [hunk 4]
```diff
@@ -43,7 +43,20 @@ def backtrace_locations
...
+          # error
+          location = __getobj__.backtrace_locations[0]
+          ["#{location.path}:#{location.lineno}: #{__getobj__}"]
+        else
+          __getobj__.to_s.split("\n")
+        end
+      end
+
+      def error_originated_in_eval_block?
+        __getobj__.to_s.start_with?("(eval")
```
Comment (byroot) [inline activesupport/lib/active_support/syntax_error_proxy.rb:59]:
```suggestion
        __getobj__.path.start_with?("(eval")
```

Using `path` is simpler than rendering `Location#to_s`. Also I'm not convinced this method extraction is really worth it.

**Comment by zzak** [comment]
@cmaruz Build is failing, could you take a look? :bow:

https://buildkite.com/rails/rails/builds/99163#018a3c4e-42cc-4132-baf4-58d424793ac3/1066-1255

```
bin/rails test /rails/actionpack/test/dispatch/debug_exceptions_test.rb:645

Error:
--
  | DebugExceptionsTest#test_display_backtrace_when_error_type_is_SyntaxError_wrapped_by_ActionView::Template::Error:
  | NoMethodError: undefined method `path' for #<SyntaxError: (eval):1: syntax error, unexpected end-of-input>
  | /rails/activesupport/lib/active_support/syntax_error_proxy.rb:46:in `parse_message_for_trace'
  | /rails/activesupport/lib/active_support/syntax_error_proxy.rb:35:in `backtrace_locations'
  | /rails/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:274:in `build_backtrace'
```

**Comment by cmaruz** [comment]
Hi @zzak,

I fixed the failing test - it was due to the fact that in Ruby versions prior to 3.3, `SyntaxError` doesn't have a `path` method. Although I fixed it, I was wondering: is there a convention in the Rails codebase to isolate code which is dependant on the version of Ruby?

**Comment by byroot** [comment]
> is there a convention in the Rails codebase to isolate code which is dependant on the version of Ruby?

It depends, but generally speaking we try to check for it at definition time rather than rutime.

So in your case it could be:

```ruby
if SyntaxError.method_defined?(:path) # Ruby 3.3+
  def parse_message_for_trace
    # 3.3+ version of the method
  end
else
  def parse_message_for_trace
    # 3.2 and older version of the method
  end
end
```

**Comment by cmaruz** [comment]
I squashed the commits into a single commit and I think this PR is ready to go - the build failure seems to be unrelated and tests pass locally.

Please let me know if you have more feedback!
