### PR TITLE
Only assign @new_record_before_save once in autosave_association

### LINKED ISSUE #38120: If a callback is listed before an association and updates the parent, then parent_id is not assigned on children when parent is created
### Steps to reproduce

1. Create a has_many (children) and belongs_to (parent) relationship
2. Create a number of has_many children
3. Initialize the belongs_to parent with the children from (3) as the associations
4. Save the belongs_to parent, expect the children to have their `parent_id` column updated

**Important:** There are additional edge case steps listed in https://github.com/rails/rails/issues/38120#issuecomment-569822083 . You must have a callback listed before the `has_many` and the callback must `update` the parent in someway.

### Expected behavior

https://guides.rubyonrails.org/association_basics.html#has-many-association-reference-when-are-objects-saved-questionmark

> If the parent object (the one declaring the has_many association) is unsaved
> (that is, new_record? returns true) then the child objects are not saved when they are added.
> All unsaved members of the association will automatically be saved when the parent is saved.

The paragraph listed above lead me to believe that the `parent_id` of a child assigned before a parent is created (while `new_record?` would return true) would be nil until the parent is saved, then it would be updated such that the `parent_id` is the newly assigned id.

### Actual behavior

This was not the case, the parent had to be created first. I tried inverse_of and autosave, thinking those might help, but they didn't

[This Gist](https://gist.github.com/jules2689/62ab673933c3039baee3d773b0d2a047) has a snippet of code that reproduces what I mean

What's interesting is that until the parent is reloaded from the database, the `has_many` association is filled out as expected. Until you re-assign the has_many relationship, however, it will just be like an instance variable is assigned... nothing in the database side will change.

### Work Around

E.g. in a controller

```ruby
def create
  children =Children.where(id: parent_params.delete(:children_ids)
  parent = Parent.new(parent_params)
  if parent.save
    parent.children = children
    parent.save
    redirect_to parent_path(parent)
  else
    render "new"
  end
end
```

### System configuration
**Rails version**: `master`

**Ruby version**: `ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]`

### PR DESCRIPTION
**Pull request by jules2689**
### Summary

If we defined a callback that updates the object before we defined the association, then this ivar may end up being manipulated to being `false` when it should be `true`. We guard this be only defining it once.

The implication of it being false, in this case, is that the children aren't updated with the parent_id and so they fail to associate with one another.

Fixes https://github.com/rails/rails/issues/38120

### CODE REVIEW

File: activerecord/lib/active_record/autosave_association.rb [hunk 1]
```diff
@@ -365,7 +365,12 @@ def normalize_reflection_attribute(indexed_attribute, reflection, index, attribu
       # Is used as a before_save callback to check while saving a collection
       # association whether or not the parent was a new record before saving.
       def before_save_collection_association
-        @new_record_before_save = new_record?
+        # If we defined a callback that updates the object before we defined the association, then this ivar may end up being
+        # manipulated to being `false` when it should be `true`. We guard this be only defining it once.
+        # See https://github.com/rails/rails/issues/38120 for more details
+        unless defined?(@new_record_before_save)
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/autosave_association.rb]: Not sure if I get this fix. This instance variable is only set on associations callback so I don't see how `@new_record_before_save` would be defined when the `before_save_collection_association ` is called. Could you explain?

I can see how `new_record?` return `false` if a callback before this one salved the record, but if no other `before_save_collection_association` have run yet the `@new_record_before_save` should not be defined.

Comment (jules2689) [reply activerecord/lib/active_record/autosave_association.rb]: The linked issue has more details, but I'll go into it a bit more here too :)

autosave associations works on a before_save. What I was experiencing is that in the case where a callback is defined before the has many (and that callback updates the model), then the children records would never get updated with the parent id.

This is because the following would happen:

1. Record create called
2. Autosave's Before save called and sets ivar to true
3. After create called and updates the record
4. Autosave's Before save gets called a second time and is no longer true
5. We try to set the parent id on the children, but the ivar is false.

If we set the ivar only once, then it is unaffected in subsequent callbacks and we will only take the initial value.

In my case I had been updating a model in an after create with some computations, which is when I noticed my children models weren't associating anymore.

I had hoped to discuss the implications of such a change like this, as I'm not fully aware of what it could imply to other parts of the codebase. It is also interesting to note that updating in most other callbacks create an infinite loop of saving, this one and any after it (e.g. after commit) are the only ones in which updating is possible.

Comment (jules2689) [reply activerecord/lib/active_record/autosave_association.rb]: Oh also! There is a bug test case linked in the issue that reproduces the issue ☺️ maybe that will help too!

Comment (rafaelfranca) [reply activerecord/lib/active_record/autosave_association.rb]: Ok. This change now makes sense to me.

File: activerecord/lib/active_record/autosave_association.rb [hunk 2]
```diff
@@ -365,7 +365,12 @@ def normalize_reflection_attribute(indexed_attribute, reflection, index, attribu
       # Is used as a before_save callback to check while saving a collection
       # association whether or not the parent was a new record before saving.
       def before_save_collection_association
-        @new_record_before_save = new_record?
+        # If we defined a callback that updates the object before we defined the association, then this ivar may end up being
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/autosave_association.rb]: I think this change is more needed because callbacks can be reentrant and what matters is the state of the record before the first callback, no after each callback. I think it is safe the remove the comment given that is what the documentation tells and now we have a test to make that explicit.

**Review by rafaelfranca — COMMENTED** [review]
I made one comment about the "comment". Other than that it looks good

File: activerecord/lib/active_record/autosave_association.rb (hunk 2 above)
Comment (jules2689) [reply activerecord/lib/active_record/autosave_association.rb]: Makes sense! Removed the comment.
