### PR TITLE
Properly quote autogenerated column aliases

### LINKED ISSUE #43878: If the table name starts with a number, ActiveRecord creates an invalid query.
### Steps to reproduce
On PostgreSQL:
```sql
create table "1abc" (id int primary key);
```

Run this script:
```ruby
require 'active_record'
ActiveRecord::Base.establish_connection(adapter: 'postgresql')
ActiveRecord::Base.logger = Logger.new($stdout)
class Test < ActiveRecord::Base
  self.table_name = '1abc'
end
p Test.group(:id).count
```

### Expected behavior

create valid query
```sql
SELECT COUNT(*) AS count_all, "1abc"."id" AS "1abc_id" FROM "1abc" GROUP BY "1abc"."id"
```

### Actual behavior

create invalid query
```sql
SELECT COUNT(*) AS count_all, "1abc"."id" AS 1abc_id FROM "1abc" GROUP BY "1abc"."id"
```
and error is occurred
```
PG::SyntaxError: ERROR:  syntax error at or near "1" (ActiveRecord::StatementInvalid)
LINE 1: SELECT COUNT(*) AS count_all, "1abc"."id" AS 1abc_id FROM "1...
                                                     ^
```

This alias `1abc_id` is invalid. It must be quoted.

### System configuration
**Rails version**:
activerecord-6.1.4.3.gem

**Ruby version**:
ruby 3.0.3p157

### PR DESCRIPTION
**Pull request by casperisfine**
Fix: https://github.com/rails/rails/issues/43878

Not sure when the regression happened, but the fix makes sense IMHO.

TODO: 
- [x] backport to 7-0-stable.

### CODE REVIEW

File: activerecord/lib/active_record/relation/calculations.rb [hunk 1]
```diff
@@ -343,14 +343,15 @@ def execute_grouped_calculation(operation, column_name, distinct) # :nodoc:
         group_columns = group_aliases.zip(group_fields)
 
         column = aggregate_column(column_name)
-        column_alias = column_alias_for("#{operation} #{column_name.to_s.downcase}")
+        column_alias = column_alias_for("#{operation}_#{column_name.to_s.downcase}")
```
Comment (kamipo) [inline activerecord/lib/active_record/relation/calculations.rb:346]: My intent for using the space is to squash multiple _ in the alias. Is there any worth replacing the space to _ here?

https://github.com/rails/rails/blob/ec7f0580b3421f2ca42c22b16c79eadcaf66c485/activerecord/lib/active_record/relation/calculations.rb#L411-L413

Comment (casperisfine) [reply activerecord/lib/active_record/relation/calculations.rb:346]: My bad, I thought it was a waste to use `" "` when it would knowingly be changed for `"_"` by gsub, but it's totally out of scope here I shouldn't  have make this change anyway.

**Comment by casperisfine** [comment]
@kamipo since you're here, I feel like the proper fix would be for Arel to have a `ColumnName` node and use that instead of `SqlLiteral`, but I'm really unfamiliar with `Arel` so not too sure.

**Comment by casperisfine** [comment]
Ok, CI is green. @kamipo any objections on me merging?

**Review by kamipo — APPROVED** [review]
I’m from my iPhone now so I can’t give a detailed review, but it is fine to me.

Just one question, does https://github.com/rails/rails/commit/f50831a7c6b4cf231c46a14287b8b84739e61856 won’t work?

**Comment by casperisfine** [comment]
> Just one question, does [f50831a](https://github.com/rails/rails/commit/f50831a7c6b4cf231c46a14287b8b84739e61856) won’t work?

No it didn't work because `column_alias_for(field)` is also used to access the result hash. So we need it both in quoted and unquoted form.

> but it is fine to me.

Thanks! I'll merge and backport to 7.0
