### PR TITLE
[Fix #52332] Handle record changed case in `#save_has_one_association`'s inverse `belongs_to` association updated check

### LINKED ISSUE #52332: Behaviour of `autosave` associations has changed on edge
### Steps to reproduce

This script has different output between `7-2-stable` and `main`:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # gem "rails"
  # gem "rails", github: "rails/rails", branch: "7-2-stable"
  gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3", "~> 1.4"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.integer :address_id
    t.timestamps
  end

  create_table :addresses, force: true do |t|
    t.text :country
    t.timestamps
  end
end

class User < ActiveRecord::Base
  belongs_to :address, autosave: true
end

class Address < ActiveRecord::Base
  has_one :user
end

class BugTest < Minitest::Test
  def test_bad
    user = User.create!(address: Address.new(country: "USA"))

    user.create_address(country: "Australia")

    assert_equal "Australia", User.find(user.id).address.country
  end

  def test_fine
    user = User.create!(address: Address.new(country: "USA"))

    user.address.update!(country: "Australia")

    assert_equal "Australia", User.find(user.id).address.country
  end
end

```

### Expected behavior

Both tests should pass.

### Actual behavior

`test_bad` fails on `main` but not `7-2-stable`.

Admittedly, it's not a good way of writing the code, because the "USA" `Address` record is orphaned as a result. But I think this is still a regression.

### System configuration
**Rails version**: `main`

**Ruby version**: 3.2

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

Fixes https://github.com/rails/rails/issues/52332
Refs:
- https://github.com/rails/rails/pull/49847
- https://github.com/rails/rails/pull/52305

### Detail

Ensures that the guard clause added in https://github.com/rails/rails/pull/49847 for preventing a duplicate autosave accounts for when the record has actually changed.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/lib/active_record/autosave_association.rb [hunk 1]
```diff
@@ -447,22 +444,27 @@ def save_has_one_association(reflection)
           primary_key = Array(compute_primary_key(reflection, self)).map(&:to_s)
           primary_key_value = primary_key.map { |key| _read_attribute(key) }
 
-          if (autosave && record.changed_for_autosave?) || _record_changed?(reflection, record, primary_key_value)
```
Comment (joshuay03) [inline activerecord/lib/active_record/autosave_association.rb:450]: This looks like a lot of changes but all I've done is de-nest the logic inside this condition, and move the inverse `belongs_to` guard clause I originally added after it to so it can account for the record changed case.

File: activerecord/test/cases/autosave_association_test.rb [hunk 2]
```diff
@@ -1812,6 +1834,12 @@ def test_should_save_with_non_nullable_foreign_keys
     child.save!
     assert_equal child.reload.post, parent.reload
   end
+
+  def test_should_save_if_previously_saved
+    ship = Ship.create(name: "Nights Dirty Lightning", pirate: Pirate.new(catchphrase: "Arrrr"))
+    pirate = ship.create_pirate(catchphrase: "Savvy?")
+    assert_equal "Savvy?", ship.reload.pirate.catchphrase
```
Comment (joshuay03) [inline activerecord/test/cases/autosave_association_test.rb:1841]: Without patch:
Screenshot 2024-07-15 at 9 12 23 am
