### PR TITLE
Fix `OrderedOptions#dig` for array indexes

### LINKED ISSUE #49713: NoMethodError occurs when specifying a number as the argument of `ActiveSupport::OrderedOptions#dig`
### Steps to reproduce

Passing a number as an argument to `ActiveSupport::OrderedOptions#dig` causes an error.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  version = ENV.fetch("AS_VERSION", "7.1.1")
  gem "activesupport", version
end

require "active_support"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_ordered_options
    h = ActiveSupport::OrderedOptions.new
    h[:foo] = [{ a: 1 }]

    assert_equal 1, h.dig(:foo, 0, :a)
  end
end
```

The results are as follows.

```
$ AS_VERSION=7.0.8 ruby steps_to_reproduce.rb
# Running:

.

Finished in 0.000639s, 1564.9453 runs/s, 1564.9453 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

$ ruby steps_to_reproduce.rb
# Running:

E

Finished in 0.001081s, 925.0693 runs/s, 0.0000 assertions/s.

  1) Error:
BugTest#test_ordered_options:
NoMethodError: undefined method `to_sym' for 0:Integer
    /Users/shotokutakumi/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/ordered_options.rb:46:in `map'
    /Users/shotokutakumi/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/ordered_options.rb:46:in `dig'
    steps_to_reproduce.rb:22:in `test_ordered_options'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

There is a change in 5c15b58 that calls `to_sym` on all keys.

### Expected behavior

No errors.
Since arrays are sometimes used in credentials and custom configuration, this behavior may cause problems for some people.

### Actual behavior

Error occurs.

### System configuration
**Rails version**:
v7.1.1

**Ruby version**:
v3.2.2

### PR DESCRIPTION
**Pull request by fatkodima**
For `OrderedOptions#dig` we need to convert to symbol only the first key.
Method added in https://github.com/rails/rails/pull/44644.

Fixes #49713.

### CODE REVIEW

File: activesupport/lib/active_support/ordered_options.rb [hunk 1]
```diff
@@ -43,7 +43,8 @@ def [](key)
     end
 
     def dig(*keys)
-      super(*keys.flatten.map(&:to_sym))
+      key, *identifiers = keys
```
Comment (kamipo) [inline activesupport/lib/active_support/ordered_options.rb:46]:
```suggestion
    def dig(key, *identifiers)
```

Comment (fatkodima) [reply activesupport/lib/active_support/ordered_options.rb]: Sure, thanks!
