### PR TITLE
Fix variants not included when eager loading multiple records containing a single attachment

### LINKED ISSUE #46770: N+1 issue when listing attachement and variants
### Steps to reproduce

```
  config.active_storage.service = :amazon
  config.active_storage.track_variants = true
```

```
    object.users.with_attached_thumbnail.each do |item|
      if item.thumbnail.present?
        puts item.thumbnail.variant(resize: "196x196^").processed.key
      end
    end

```

### Expected behavior
This code should only perform 1 SQL request. 

### Actual behavior
This code perform 1 SQL request et 3 others SQL request per thumbnail. 

```
 SELECT "active_storage_variant_records".* FROM "active_storage_variant_records" WHERE "active_storage_variant_records"."blob_id" = $1 AND "active_storage_variant_records"."variation_digest" = $2 LIMIT $3  [["blob_id", 52291], ["variation_digest", "IUN7MbalQqmLKbMoWq8RDR0hgdI="], ["LIMIT", 1]]

ctiveStorage::Attachment Load (0.2ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 20412], ["record_type", "ActiveStorage::VariantRecord"], ["name", "image"], ["LIMIT", 1]]

ActiveStorage::Blob Load (0.3ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 52292], ["LIMIT", 1]]

```

### System configuration
**Rails version**:  7.0.4

**Ruby version**: 3.1.2

### PR DESCRIPTION
**Pull request by russellporter**
### Motivation / Background

When using the `with_attached_#{name}` scope for a `has_one_attached` relation, attachment variants were not eagerly loaded.

This fix is important to ensure good performance when using Active Storage variants.

This Pull Request has been created because I encountered this performance issue when developing my project.

Fixes #46770

### Detail

The scope implementation is now the same as when used with `has_many_attached`.

### Additional information

I'm very inexperienced with Ruby, so I tried follow the existing implementation and testing approach.

In particular, it would be good to remove the duplication between `has_one_attached` and `has_many_attached` that led to this bug but I am not sure the best way to achieve that.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Review by nvasilevski — COMMENTED** [review]
Looks correct to me and the test makes sense 👍 
Also fixes the reproduction script from https://github.com/rails/rails/issues/46770#issuecomment-1359595555

We'll need someone from the core team to have a look but I wanted to leave a review to add more visibility to the PR. Thanks for addressing this!

File: activestorage/test/models/variant_with_record_test.rb [hunk 1]
```diff
@@ -57,7 +57,65 @@ class ActiveStorage::VariantWithRecordTest < ActiveSupport::TestCase
...
+    assert_difference -> { ActiveStorage::VariantRecord.count }, +1 do
+      blob2.representation(resize_to_limit: [100, 100]).process
+    end
+
+    assert_no_difference -> { ActiveStorage::VariantRecord.count } do
+      user1.cover_photo.attach(blob1)
+      user2.cover_photo.attach(blob2)
+    end
+
+    users = User.where(id: [user1.id, user2.id])
```
[the remark this answers is not in the document]
Comment (russellporter) [reply activestorage/test/models/variant_with_record_test.rb]: That makes sense, I updated the test so no data is shared between the two assertions, does that resolve your concern?

File: activestorage/test/models/variant_with_record_test.rb [hunk 2]
```diff
@@ -57,7 +57,70 @@ class ActiveStorage::VariantWithRecordTest < ActiveSupport::TestCase
     assert_equal "local_public", variant.image.blob.service_name
   end
 
-  test "eager loading" do
+  test "eager loading of single attachment on each record" do
```
Comment (vipulnsward) [inline activestorage/test/models/variant_with_record_test.rb:60]:
```suggestion
  test "eager loading has_one_attached record" do
```

File: activestorage/test/models/variant_with_record_test.rb [hunk 3]
```diff
@@ -57,7 +57,70 @@ class ActiveStorage::VariantWithRecordTest < ActiveSupport::TestCase
...
+          rep = u.cover_photo.representation(resize_to_limit: [100, 100])
+          rep.processed
+          rep.key
+          rep.url
+        end
+      end
+    end
+  end
+
+  test "eager loading of many attachments" do
```
Comment (vipulnsward) [inline activestorage/test/models/variant_with_record_test.rb:123]:
```suggestion
  test "eager loading has_many_attached records" do
```

File: activestorage/test/models/variant_with_record_test.rb [hunk 4]
```diff
@@ -57,7 +57,70 @@ class ActiveStorage::VariantWithRecordTest < ActiveSupport::TestCase
...
+
+      assert_no_difference -> { ActiveStorage::VariantRecord.count } do
+        user1.cover_photo.attach(blob1)
+        user2.cover_photo.attach(blob2)
+      end
+
+      User.where(id: [user1.id, user2.id])
+    end
+
+    users = create_users()
```
Comment (vipulnsward) [inline activestorage/test/models/variant_with_record_test.rb:83]: Can we follow example below and create users only once? 
Reason- The assertions are run twice in the block, we could do reload as needed blow.

File: activestorage/CHANGELOG.md [hunk 5]
```diff
@@ -115,4 +115,11 @@
 
     *Luke Lau*
 
+*   Fix variants not included when eager loading multiple records containing a single attachment
```
Comment (vipulnsward) [inline activestorage/CHANGELOG.md:118]: This goes at top of file when being merged :-)

**Review by vipulnsward — COMMENTED** [review]
@russellporter added some comments, someone from committer team can check further 😃

File: activestorage/test/models/variant_with_record_test.rb (hunk 4 above)
Comment (russellporter) [reply activestorage/test/models/variant_with_record_test.rb]: Thanks for the review, I updated it now. I had some slight reservations about using `reload` because it made the query count assertion slightly unpredictable:

```ruby
users.reload # performs users query
users.each { ...  } # no query performed here

users.reload # performs users query
users.with_attached_cover_photo.each { ... # exact same query is performed again
```

After looking in the source it seems `reset` is what I want - this clears any caches but does not perform the query, so I used that.

**Comment by Benoit-Baumann** [comment]
What is the status of this PR ? 
We are encoutering the same performance problems. It would be awesome to have this fixed for the next Rails' release !

**Comment by nvasilevski** [comment]
@russellporter Would you mind squashing commits and rebasing? It looks like there are some conflicts. Then we can reach out on Discord for someone to have a look!

**Review by nvasilevski — APPROVED** [review]
I've asked in Discord so hopefully we can get it merged 👍
