### PR TITLE
[Fix #49796] Prevent global cache options being overwritten

### LINKED ISSUE #49796: MemoryStore#fetch with 7.1 defaults can't set `expires_at` via block opts
### Steps to reproduce

In a Rails app, use the following config:

```ruby
config.cache = :memory_store
config.load_defaults(7.1)
```

Now, use `Rails.cache.fetch` passing a block and try to set `options.expires_at`. An `ArgumentError` is raised:

```
ArgumentError: Either :expires_in or :expires_at can be supplied, but not both
```

Additionally, the cache store's options are mutated with the `expries_at` option set in the block

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class TestApp < Rails::Application
  config.root = "/tmp"
  config.eager_load = false
  config.cache = :memory_store
  config.load_defaults(7.1)

  Rails.application.initialize!
end

class BugTest < Minitest::Test
  def test_memory_store_fetch_opts
    Rails.cache.fetch(SecureRandom.alphanumeric) do |_key, opts|
      opts.expires_at = 1.minute.from_now
      Time.now.to_s
    end
  ensure
    puts "Cache options are now #{Rails.cache.options}"
  end
end
```

### Expected behavior

Cache is written with the given `expires_at` value.

### Actual behavior

An `ArgumentError` is raised saying that we're trying to set two options. `Rails.cache` options are mutated with the options from the block.

```
# Running:

Cache options are now {:compress=>true, :compress_threshold=>1024, :expires_at=>Thu, 26 Oct 2023 12:58:56.191690312 UTC +00:00}
E

Error:
BugTest#test_memory_store_fetch_opts:
ArgumentError: Either :expires_in or :expires_at can be supplied, but not both
```

### System configuration
**Rails version**: *main*

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by HolyWalley**
### Motivation / Background

Issue https://github.com/rails/rails/issues/49796

### Detail

During investigation of the issue above I found that `Rails.cache.fetch` in case when no options were passed as arguments passes global cache options to fetch block (wrapped in WriteOptions, but anyway), so, global cache options will be overwritten by those manipulations.

### Additional information

Let me know if I need to update changelog

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by HolyWalley** [comment]
I decided to check the original commit (probably something I had to do in advance) and found out that `.dup` was removed to decrease memory allocations, because at that moment options were not mutated anywhere. So, I decided to `.dup` only before passing options to the place where they will be definitely changed

**Comment by fatkodima** [comment]
Please, squash your commits into one. For small changes, you can just force push into the branch.

File: activesupport/lib/active_support/cache.rb [hunk 1]
```diff
@@ -478,7 +478,7 @@ def fetch(name, options = nil, &block)
           if entry
             get_entry_value(entry, name, options)
           else
-            save_block_result_to_cache(name, options, &block)
+            save_block_result_to_cache(name, options.dup, &block)
```
Comment (jonathanhefner) [inline activesupport/lib/active_support/cache.rb:481]: I think it would makes sense to push this down into `save_block_result_to_cache`, since that's where the options are passed to the block:

```diff
index ab4deb9b97..79c0c19b39 100644
--- a/activesupport/lib/active_support/cache.rb
+++ b/activesupport/lib/active_support/cache.rb
@@ -478,7 +478,7 @@ def fetch(name, options = nil, &block)
           if entry
             get_entry_value(entry, name, options)
           else
-            save_block_result_to_cache(name, options.dup, &block)
+            save_block_result_to_cache(name, options, &block)
           end
         elsif options && options[:force]
           raise ArgumentError, "Missing block: Calling `Cache#fetch` with `force: true` requires a block."
@@ -1053,6 +1053,8 @@ def get_entry_value(entry, name, options)
         end

         def save_block_result_to_cache(name, options)
+          options = options.dup
+
           result = instrument(:generate, name, options) do
             yield(name, WriteOptions.new(options))
           end
```

What do you think?

Comment (HolyWalley) [reply activesupport/lib/active_support/cache.rb:481]: yeah, makes sense.

**Review by jonathanhefner — APPROVED** [review]
As Dima mentioned, please squash your commits! :smiley:

But I have pushed a commit to squash them, and will merge on green.

**Comment by jonathanhefner** [comment]
Thank you, @HolyWalley! :dollar:
