### PR TITLE
Fix duplicate escaping of quotes for check constraint expressions in MySQL schema

### LINKED ISSUE #42424: Duplicate escaping of quotes in check constraint expressions (MySQL)
### Steps to reproduce
With a check constraint in the (MySQL) database and the Rails project set to use the schema.rb format I end up with duplicate escape sequences for quotes in the expression of the check constraint.

1. Add a migration that adds a check constraints with an expression that includes quotes.
2. Run the migration (it runs fine)
3. Check the generated `schema.rb`
4. The generated `schema.rb` contains duplicate escaping for the quotes in the check constraint expression
5. Trying to load the schema `rails db:schema:load` leads to an SQL syntax error

Here is an executable version of the problem (I used MySQL`Ver 8.0.23 for osx10.15 on x86_64`): 

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", "~> 6.1.3"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(
  adapter: "mysql2",
  database: 'check_constraint_schema_dump_bug',
  charset: 'utfmb4',
  encoding: 'utf8mb4',
  collation: 'utf8mb4_unicode_ci',
  username: ENV.fetch("MYSQL_USERNAME") { "rails" },
  password: ENV.fetch("MYSQL_PASSWORD") { "" },
  host: ENV.fetch("MYSQL_HOST") { "127.0.0.1" },
  port: ENV.fetch("MYSQL_PORT") { 3306 }
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.check_constraint "(title <> 'forbidden_title')"
  end
end

class BugTest < Minitest::Test
  def test_adapter_check_constraint_quoting
    expected = %q(`title` <> _utf8mb4'forbidden_title')

    assert_equal ActiveRecord::Base.connection.check_constraints('posts').first.expression, expected
  end

  def test_schema_dumper_not_including_wrong_quotes
    dumped_schema = ActiveRecord::SchemaDumper.dump(ActiveRecord::Base.connection, StringIO.new).string

    wrong = %q(t.check_constraint "`title` <> _utf8mb4\\\\'forbidden_title\\\\'")
    refute_includes dumped_schema, wrong
  end

  def test_schema_dumper_including_correct_quotes
    dumped_schema = ActiveRecord::SchemaDumper.dump(ActiveRecord::Base.connection, StringIO.new).string

    expected = %q(t.check_constraint "`title` <> _utf8mb4'forbidden_title'")
    assert_includes dumped_schema, expected
  end
end

```

### Expected behavior
E.g. a migration like this:

```ruby
create_table :posts, force: true do |t|
  t.string :title
  t.check_constraint "(title <> 'forbidden_title')"
end
```

should generate a schema like that:
```ruby
create_table "posts", charset: "utf8mb4", force: :cascade do |t|
  t.string "title"
  t.check_constraint "`title` <> _utf8mb4'forbidden_title'"
end
```

### Actual behavior
It generates a schema like this:
```ruby
create_table "posts", charset: "utf8mb4", force: :cascade do |t|
  t.string "title"
  t.check_constraint "`title` <> _utf8mb4\\'forbidden_title\\'" # <-- Notice the slashes
end
```

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.6.3

### Potential fix
I created a monkey patch which fixes the issue for my project locally:
```ruby
module ActiveRecord
  module ConnectionAdapters
    class AbstractMysqlAdapter
      def check_constraints(table_name)
        if supports_check_constraints?
          scope = quoted_scope(table_name)

          chk_info = exec_query(<<~SQL, "SCHEMA")
            SELECT cc.constraint_name AS 'name',
                  cc.check_clause AS 'expression'
            FROM information_schema.check_constraints cc
            JOIN information_schema.table_constraints tc
            USING (constraint_schema, constraint_name)
            WHERE tc.table_schema = #{scope[:schema]}
              AND tc.table_name = #{scope[:name]}
              AND cc.constraint_schema = #{scope[:schema]}
          SQL

          chk_info.map do |row|
            options = {
              name: row["name"]
            }
            expression = row["expression"].gsub("\\'", "'") # <-- replace duplicate escaping
            expression = expression[1..-2] unless mariadb? # remove parentheses added by mysql
            CheckConstraintDefinition.new(table_name, expression, options)
          end
        else
          raise NotImplementedError
        end
      end
    end
  end
end
```

If this goes into the right direction I'd open up a pull request and write the corresponding tests.
Diff: https://github.com/rails/rails/compare/main...Flixt:fix-mysql-check-constraints-quoting?expand=1

### PR DESCRIPTION
**Pull request by Flixt**
### Summary

Mysql automatically escapes quotes in generated check constraints expressions.
When Rails dumps the schema (into schema.rb) the generated schema also contains
the quotes with duplicated escaping (\\\\').
To fix this, we remove the escaping that MySQL provides from the fetched expression.

Fixes #42424

### Other Information
I decided to go with an MySQL specific test, because putting it in https://github.com/rails/rails/blob/6-1-stable/activerecord/test/cases/migration/check_constraint_test.rb leads to code like this:

```ruby
if current_adapter?(:Mysql2Adapter)
  assert_equal "`name` <> 'forbidden_string'", constraint.expression
elsif current_adapter?(:PostgreSQLAdapter)
  assert_equal "(name)::text <> 'forbidden_string'::text", constraint.expression
else
  assert_equal "name != 'forbidden_string'", constraint.expression
end
```

As the code shows, even MariaDB handles the quoting differently than MySQL.

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb [hunk 1]
```diff
@@ -445,8 +445,18 @@ def check_constraints(table_name)
...
             expression = row["expression"]
-            expression = expression[1..-2] unless mariadb? # remove parentheses added by mysql
+
+            unless mariadb?
+              # remove parentheses added by MySQL
+              expression = expression[1..-2]
+
+              # MySQL returns check constraints expression in an already escaped form.
+              # This leads to duplicate escaping later (e.g. when the expression is used in the SchemaDumper).
+              expression = expression.gsub("\\'", "'")
```
Comment (zzak) [inline activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:457]: I'm a bit curious how these got here in the first place, but not sure that question is relevant to this bug. 🤔

Comment (Flixt) [reply activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:457]: I actually don't know why MySQL does this. In fact, the `\'` finds its way into the MySQL information schema even without the use of Rails at all.

Running something like:

```sql
CREATE TABLE `posts` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `title` varchar(255), CONSTRAINT chk_rails_fa84ad2808 CHECK ((title != 'forbidden_title')))
```

And then reading back the the created constraint with:

```sql
SELECT cc.constraint_name AS 'name',
       cc.check_clause AS 'expression'
FROM information_schema.check_constraints cc
         JOIN information_schema.table_constraints tc
              USING (constraint_schema, constraint_name)
WHERE tc.table_name = 'posts'
```

(which is what ActiveRecord does in `AbstractMysqlAdapter#check_constraints`)

shows the already escaped result on the database level:

Bildschirmfoto 2021-06-10 um 17 01 20

There is a difference in string/quote handling in the MySQL world in contrast to the (ASCII) SQL standard world, as MySQL accepts backslashes as escape character. There even is a configuration value `NO_BACKSLASH_ESCAPES` for the sql_mode option of MySQL.

I tried setting it with

```sql
SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_BACKSLASH_ESCAPES';
```

But it leads to a totally different and weird error, when I try to reproduce the issue with the executable version of the problem. I was not yet able track it down (which would be unrelated to the bug here).

```
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/mysql2_adapter.rb:103:in `escape': negative string size (or size too big) (ArgumentError)
```

What I think is a bit weird is, that even when adding `NO_BACKSLASH_ESCAPES` MySQL still adds the `\` for escaping, but to be honest, I have no clue if that is a MySQL bug or desired behavior.

_Fun fact, I learned that `NO_BACKSLASH_ESCAPES` was added as as a special request from SAP https://bugs.mysql.com/bug.php?id=6368, https://github.com/mysql/mysql-server/blob/7ed30a748964c009d4909cb8b4b22036ebdef239/mysql-test/t/sql_mode.test#L85_

**Review by zzak — APPROVED** [review]

**Comment by Flixt** [comment]
Is this bugfix something we'd consider worth to be backported to 6.1 / 5.2 ?

**Comment by marcelolx** [comment]
+1

**Comment by Flixt** [comment]
I rebased it into main..

**Comment by HolyWalley** [comment]
+1
