### PR TITLE
Prioritize db_config for current env when resolving config.

### LINKED ISSUE #36894: Mysql2::Error: No database selected - Multi-database on RC2
With multiple databases set up, if a model uses connects_to, when trying to use that model it seems to not be able to find the database.

### Steps to reproduce
I created an example app that shows this issue https://github.com/ScottRobbins/RailsMultipleDatabaseIssue 

You will need to set up the necessary credentials for your local database. 

First, you can go to the commit before "Update to RC2" and run the song test like `bundle exec rails test test/models/song_test.rb`, and it should work correctly. 

Then, go to HEAD, which is now RC2 and run the same test, you will see an error: 
```
Error:
SongTest#test_the_truth:
ActiveRecord::StatementInvalid: Mysql2::Error: No database selected
```

You will notice that creating the database and running migrations is fine, it's just when trying to actually use the active-record model that the error arises.

### Expected behavior
`bundle exec rails test test/models/song_test.rb` should succeed

### Actual behavior
`bundle exec rails test test/models/song_test.rb` fails with the error above

### System configuration
**Rails version**: 6.0.0.rc2

**Ruby version**: 2.6.3

**MySQL version**: 5.6 & 5.7

### LINKED ISSUE #38440: Rails 6 Multiple databases: model connection_config missing database property
Using Rails 6, and setting up a multiple databases configuration.
I want to separate some fairly static data from the rest of the app, so I have the primary (app) and products (static) databases.
Migrations work fine, both dbs are created with the appropriate schemas. Problem is the models that are connected to the `products` db cannot connect.

Here is my database.yml file:

```
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

products: &products
  <<: *default
  migrations_paths: db/products_migrate

development:
  primary:
    <<: *default
    database: myapp_development
  products:
    <<: *products
    database: products_development
```

And here are my models:
product_record.rb
```
class ProductRecord < ApplicationRecord
  self.abstract_class = true

  connects_to database: { writing: :products, reading: :products }
end
```
product.rb
```
class Product < ProductRecord
end
```

This seems fine from what I see in the docs. But in Rails console, `Product.all` tells me 
```
ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "products" does not exist)
LINE 1: SELECT "products".* FROM "products" LIMIT $1
```

So, in the console, I check my model's connection_config:
```
irb(main):009:0> Product.connection_config
=> {:adapter=>"postgresql", :encoding=>"unicode", :host=>"db", :username=>"postgres", :password=>nil, :pool=>5, :migrations_paths=>"db/products_migrate"}
```

So there is no `database` property. Really weird thing is, it does get the "migration_paths" property, so the configuration in the model works, but it just omits the `database` property, resulting in rails not connecting to any db.

### System configuration
**Rails version**:
6.0.2.1
**Ruby version**:
2.5

### PR DESCRIPTION
**Pull request by tgxworld**
### Summary

Resolves https://github.com/rails/rails/issues/38440#issuecomment-585202320
Resolves https://github.com/rails/rails/issues/36894#issuecomment-519672987

### CODE REVIEW

File: activerecord/lib/active_record/database_configurations.rb [hunk 1]
```diff
@@ -79,10 +79,12 @@ def default_hash(env = default_env)
     # If the application has multiple databases +find_db_config+ will return
     # the first DatabaseConfig for the environment.
     def find_db_config(env)
-      configurations.find do |db_config|
-        db_config.env_name == env.to_s ||
-          (db_config.for_current_env? && db_config.name == env.to_s)
-      end
+      configurations
+        .sort_by { |db_config| db_config.for_current_env? ? 0 : 1 }
```
Comment (tgxworld) [inline activerecord/lib/active_record/database_configurations.rb:83]: I'm disregarding the fact that we're doing two loops here since the size of the configurations array should be fairly small.

**Comment by eileencodes** [comment]
Thanks for opening this PR! I can't think of a better way to fix this problem so this change seems fine to me.

**Comment by tgxworld** [comment]
@eileencodes  Thank you for reviewing :+1:
