### PR TITLE
Don't error on an empty CONTENT_TYPE

### LINKED ISSUE #26912: 5.0.0.1 / actionpack - undefined method `ref' for nil:NilClass*
### Steps to reproduce

Reproduced with **webmock** gem

``` ruby
      stub_request(:any, 'http://app')
        .to_rack(Rails.application)
```
#### Error

```
     Failure/Error: Net::HTTP.get('app', '/')

     NoMethodError:
       undefined method `ref' for nil:NilClass
```
#### Location

```
~/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.1/lib/action_controller/metal/params_wrapper.rb:280:in `_wrapper_enabled?'
```
### Expected behavior

in https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/params_wrapper.rb#L278 request.has_content_type? should be return false for nil CONTENT_TYPE header
### Actual behavior

 request.has_content_type? return true for nil CONTENT_TYPE header
### System configuration

**Rails version**: 2.3.1

**Ruby version**: 5.0.0.1

### PR DESCRIPTION
**Pull request by maclover7**
This commit prevents a possible issue wherein an empty CONTENT_TYPE
header is sent in a request to a Rails application, and then `request.content_mime_type`
would return `nil`. This is because the `has_content_type?` guard method
was not properly checking the validity of a request's content type; it
was only checking to see whether or not the header existed, not whether
it had a value stored inside.

Relatedly, after an internal discussion, it was determined that the
`has_content_type?` method is not meant to be part of the public API,
and is therefore changed to a `:nodoc:` method in this commit.

The test for this behavior is a little bit ugly, for two reasons. One is
that it was difficult to determine where to place the test... I figured
the best place would be with the rest of the ParamsWrapper stuff, since
that's where the original issue was. Also, we have to do some fancy
footwork in calling `dispatch` on the test's controller manually... this
is because `ActionController::TestCase` will throw an error if you try
and pass in a nil content type, which is exactly what we are trying to
test here... Because of that, we have to manually call in to the
controller, and bypass the `post` request helper.

Fixes #26912.

This is a regression in behavior between Rails versions 4.2.x and 5.0.x,
which was introduced via [this commit](https://github.com/rails/rails/commit/a9f28600e901b11a9222e34bfae8642bfb753186).

### CODE REVIEW

File: actionpack/test/controller/params_wrapper_test.rb [hunk 1]
```diff
@@ -212,6 +212,16 @@ def test_empty_parameter_set
       )
     end
   end
+
+  def test_handles_empty_content_type
+    with_default_wrapper_options do
+      @request.env["CONTENT_TYPE"] = ''
```
Comment (sergey-alekseev) [inline actionpack/test/controller/params_wrapper_test.rb]: Codeclimate asks for `@request.env["CONTENT_TYPE"] = ""` (double quotes).

File: actionpack/test/controller/params_wrapper_test.rb [hunk 2]
```diff
@@ -212,6 +212,16 @@ def test_empty_parameter_set
...
+      _controller_class.dispatch(:parse, @request, @response)
+
+      assert_equal 200, @response.status
+      assert_equal '', @response.body
```
Comment (sergey-alekseev) [inline actionpack/test/controller/params_wrapper_test.rb]: Codeclimate asks for `assert_equal "", @response.body` (double quotes).

**Review by sergey-alekseev — COMMENTED** [review]
Needs minor code style changes.

File: actionpack/test/controller/params_wrapper_test.rb (hunk 1 above)
Comment (rafaelfranca) [inline actionpack/test/controller/params_wrapper_test.rb]: Should not this test setting it to `nil`? Will not the new implementation of `has_content_type?` return `true` when it is a empty string?

**Comment by rafaelfranca** [comment]
I merged manually and made the changes to make sure the tests were checking the fix is doing something. Backported in 82e35c1

**Comment by rafaelfranca** [comment]
I merged manually and made the changes to make sure the tests were checking the fix is doing something. Backported in 82e35c1

**Comment by maclover7** [comment]
thanks @rafaelfranca :heart:
