### PR TITLE
Stop gap solution for long output on test cases

### LINKED ISSUE #45121: Very long test output even for simple failing tests
### Steps to reproduce

The test output in some cases is extremely long, making it difficult to see what the error is. (As far as I can tell, this is a regression; I don’t recall the issue being present in earlier versions of Rails.) The issue is currently affecting readers of the *Ruby on Rails Tutorial* 7th edition, including me (its author).

The issue is easy to reproduce with the latest version of Rails (7.0.3 as of this writing) and a simple generated Pages controller (with one action, `home`):

```
$ gem install rails -v 7.0.3
$ rails _7.0.3_ new test_output_app
$ cd test_output_app/
$ rails generate controller Pages home
$ rails test
Running 1 tests in a single process (parallelization threshold is 50)
Run options: --seed 60583

# Running:

.

Finished in 0.616127s, 1.6230 runs/s, 1.6230 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

The tests initially pass, but we can reproduce the issue by commenting out the route for the home page in `config/routes.rb`:

```
Rails.application.routes.draw do
  # get 'pages/home'        <-- this is the line that should be commented out
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end
```

This causes the generated test in `test/controllers/pages_controller_test.rb` to fail because `pages_home_url` is no longer defined:

```
require "test_helper"

class PagesControllerTest < ActionDispatch::IntegrationTest
  test "should get home" do
    get pages_home_url
    assert_response :success
  end
end
```

At this point, running `rails test` outputs a tremendous volume of text:

```
$ rails test
Running 1 tests in a single process (parallelization threshold is 50)
Run options: --seed 23908

# Running:

E

Error:
PagesControllerTest#test_should_get_home:
NameError: undefined local variable or method `pages_home_url' for 
.
.
.
```

The vertical dots here indicate a large amount of omitted text.

### Expected behavior

The output of `rails test` for this single failing test should be fairly short, making it easy to identify the precise issue and file line number—something like this:

```
$ rails test
Running 1 tests in a single process (parallelization threshold is 50)
Run options: --seed 23908

# Running:

E

Error:
PagesControllerTest#test_should_get_home:
NameError: undefined local variable or method `pages_home_url' for #<PagesControllerTest:0x0000000104f598a8>
rails test test/controllers/pages_controller_test.rb:4



Finished in 0.122953s, 8.1332 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

This would work out to around 50 words and 440 characters of total output.

### Actual behavior

The actual output is enormous—over 9,000 words and nearly 320,000 characters of total output:

```
$ rails test | wc
      18    9049  319394
```

The output is so voluminous that on many systems (including mine) it overflows the terminal’s ability to scroll back. It’s possible to route around the problem in a narrow sense by piping to `grep`, but this is an awkward hack, doesn’t work well when there are multiple failing tests, and doesn’t work at all with an automated test runner like Guard.

### System configuration

**Rails version**: 7.0.3

**Ruby version**: 3.1.2

I have reproduced the issue both on my MacBook (running macOS Monterey 12.3.1) and on AWS Cloud9 (running Ubuntu Linux).

N.B. [This Stack Overflow issue](https://stackoverflow.com/questions/66593801/rails-test-command-prints-out-a-very-long-output) seems to allude to the same behavior, though unfortunately no solution has been forthcoming.

### PR DESCRIPTION
**Pull request by tenderlove**
This patch just changes the inspect method on test case instances.
Seeing test instance internals probably isn't helpful when an exception
is raised (for example a `NoMethodError`).

This isn't as good as #45122, but should fix #45121

I don't think this is great, but should fix the immediate pain.  This does make me think we should have an API in Ruby for telling `inspect` what instance variables we would like it to use.

The implementation of `inspect` [simply loops over all instance variables](https://github.com/ruby/ruby/blob/0ad9cc16966c2e56f0fe7e5992edf76033d3a83f/object.c#L649), but interestingly it doesn't call the `instance_variables` method to determine what IVs to inspect.

To me, it feels like these two objects should have different inspect output, but they don't:

```ruby
class Foo
  def initialize
    @foo = 1
    @bar = 1
  end
end

class Bar < Foo
  def instance_variables
    [:@foo]
  end
end

p Foo.new
p Bar.new
```

Anyone have any thoughts on this PR or the above thing?  I'm happy to file a redmine ticket wrt the inspect feature.

### CODE REVIEW

**Review by byroot — APPROVED** [review]
Fine by me as a quick fix than we can easily backport until the full solution comes around.

File: activesupport/lib/active_support/test_case.rb [hunk 1]
```diff
@@ -149,5 +149,9 @@ def parallelize_teardown(&block)
     alias :assert_not_same :refute_same
 
     ActiveSupport.run_load_hooks(:active_support_test_case, self)
+
+    def inspect # :nodoc:
+      "#<#{self.class.name}:#{'%#016x' % object_id}>"
```
Comment (jhawthorn) [inline activesupport/lib/active_support/test_case.rb:154]: No strong opinion either way (non blocking). How do you feel about this vs.

``` suggestion
      Object.instance_method(:to_s).bind_call(self)
```

Comment (byroot) [reply activesupport/lib/active_support/test_case.rb]: Isn't that just `alias_method :inspect, :to_s`?

Not sure if I should be nitpicking in a quick fix PR 🤣
