### PR TITLE
Filter attributes in SQL logs

### LINKED ISSUE #41896: ActiveRecord::Base.filter_attributes doesn't filter SQL logs
### Steps to reproduce

```ruby
Rails.application.config.filter_parameters += %i[
  sekret
]

class Foo < ActiveRecord::Base
  attribute :sekret
end

Foo.find_by(sekret: 'abc')
```

### Expected behavior

This correctly filters `sekret` in controller parameters and from the record in the console, but `sekret` is still logged to `development.log`, `test.log`, and `production.log` when queried. It should also filter logs written to disk.

### Actual behavior

```sh
$ tail -f log/production.log | grep "Foo Load"
  Foo Load (0.7ms)  SELECT "foos".* FROM "foos" WHERE "foos"."sekret" = $1 LIMIT $2  [["sekret", "abc"], ["LIMIT", 1]]
```

### System configuration
**Rails version**: 6.1.3
**Ruby version**: 3.0.1

### PR DESCRIPTION
**Pull request by aishbuilds**
### Summary

SQL queries are logged when `:debug` option is used.
Previously, filter attributes were not masked in the logs.

For e.g.

```
  Foo Load (0.2ms)  SELECT "foos".* FROM "foos" WHERE "foos"."passw" = ? LIMIT ?  [["passw", "hello"], ["LIMIT", 1]]
```

`password` being one of the filter attributes, is written to disk.

With this change, filter attributes will be masked as [FILTERED] in the logs.

```
  Foo Load (0.5ms)  SELECT "foos".* FROM "foos" WHERE "foos"."passw" = ? LIMIT ?  [["passw", "[FILTERED]"], ["LIMIT", 1]]
```

The filtration is applied only when `prepared_statement` is enabled.  

Fixes https://github.com/rails/rails/issues/41896

### CODE REVIEW

**Comment by stouset** [comment]
Closes #41896

**Comment by aishbuilds** [comment]
@rafaelfranca: 👋 Given you have context on the [issue](https://github.com/rails/rails/issues/41896), could you kindly review the changes?

File: activerecord/lib/active_record/log_subscriber.rb [hunk 1]
```diff
@@ -132,6 +137,10 @@ def log_query_source
       def extract_query_source_location(locations)
         backtrace_cleaner.clean(locations.lazy).first
       end
+
+      def parameter_filters
+        ActiveSupport::ParameterFilter.new(filter_parameters)
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/log_subscriber.rb:142]: We can change this implementation to `ActiveRecord::Base.inspection_filter` and remove the need to define `filter_parameters` in the log subscriber class.

That also allows us to change the test to remove the stub for this method since we can just configure the parameter filter attributes in `ActiveRecord::Base` and return its original value after the test.

File: activerecord/CHANGELOG.md [hunk 2]
```diff
@@ -573,5 +573,21 @@
 
     *Santiago Perez Perret*
 
+    Filter attributes in SQL logs
```
Comment (rafaelfranca) [inline activerecord/CHANGELOG.md:576]: This should be in the top of the file.

**Review by rafaelfranca — CHANGES_REQUESTED** [review]

File: activerecord/CHANGELOG.md [hunk 3]
```diff
@@ -573,5 +573,21 @@
...
+    Previously, SQL queries in logs containing `ActiveRecord::Base.filter_attributes` were not filtered.
+
+    Now, the filter attributes will be masked `[FILTERED]` in the logs.
+
+    ```
+    # Before:
+      Foo Load (0.2ms)  SELECT "foos".* FROM "foos" WHERE "foos"."passw" = ? LIMIT ?  [["passw", "hello"], ["LIMIT", 1]]
+
+    # After:
+      Foo Load (0.5ms)  SELECT "foos".* FROM "foos" WHERE "foos"."passw" = ? LIMIT ?  [["passw", "[FILTERED]"], ["LIMIT", 1]]
```
Comment (kamipo) [inline activerecord/CHANGELOG.md:587]: If `prepared_statements: false` (which is by default for mysql2 adapter), should the SQL be ```Foo Load (0.5ms)  SELECT `foos`.* FROM `foos` WHERE `foos`.`passw` = [FILTERED] LIMIT 1```?

File: activerecord/lib/active_record/log_subscriber.rb (hunk 1 above)
Comment (aishbuilds) [reply activerecord/lib/active_record/log_subscriber.rb]: Nice suggestion. 

Updated the PR to use filter attributes method in `ActiveRecord::Base` and updated the test accordingly.

File: activerecord/CHANGELOG.md (hunk 3 above)
Comment (aishbuilds) [reply activerecord/CHANGELOG.md]: @kamipo: Nice catch.

It does not look like my solution will work when `prepared_statements` is `false` as the payload will have empty [`binds`](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/log_subscriber.rb#L46) in such a case.

I was not able to find an optimal solution to iterate over the [`sql`](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/log_subscriber.rb#L43) raw statement and filter the attributes. And, have consequently updated the Changelog to mention the filtration is done only when `prepared_statements` is enabled.

I will be happy to work on the case when `prepared_statements = false` as a follow-up. Keen to know your thoughts.

**Comment by stouset** [comment]
I would hate to see this fall through the cracks. Is all that's needed a few Rubocop fixes?

File: activerecord/lib/active_record/log_subscriber.rb [hunk 4]
```diff
@@ -1,5 +1,7 @@
 # frozen_string_literal: true
 
+require "active_support/parameter_filter"
```
Comment (yskkin) [inline activerecord/lib/active_record/log_subscriber.rb:3]: Looks like this is no longer needed.

**Comment by stouset** [comment]
@aishbuilds If you give me permission on this branch, I can make the needed changes.

File: activerecord/lib/active_record/log_subscriber.rb (hunk 4 above)
Comment (aishbuilds) [reply activerecord/lib/active_record/log_subscriber.rb]: Thanks @yskkin, removed.

**Comment by aishbuilds** [comment]
> @aishbuilds If you give me permission on this branch, I can make the needed changes.

Thanks @stouset for the mention and the assistance. I have updated the branch with the requested changes and resolved conflicts/rubocop offenses. 

We still have an [open thread](https://github.com/rails/rails/pull/42006#discussion_r621909722). I'll follow up to see if we can move the PR forward.

File: activerecord/CHANGELOG.md (hunk 3 above)
Comment (aishbuilds) [reply activerecord/CHANGELOG.md]: @kamipo: When you get a chance, could you let me know your thoughts on the above comment? TIA!

**Comment by stouset** [comment]
All this needs is a maintainer to look at the PR, approve it, and merge.
