### PR TITLE
Integration requests should work in contexts without setup and teardown

### LINKED ISSUE #18285: undefined method 'clear' for nil:NilClass in actionpack-4.2.0/lib/action_controller/test_case.rb
In some rspec before(:all) blocks it seems like the setup_subscriptions method in this file is not being called, resulting in the a nil instance_variable when reset_template_assertion is called.

more info can be found in this stackoverflow question

http://stackoverflow.com/questions/27727786/rails-4-2-update-method-fails-only-when-called-from-beforeall-block

    def reset_template_assertion
      RENDER_TEMPLATE_INSTANCE_VARIABLES.each do |instance_variable|
        instance_variable_get("@_#{instance_variable}").clear
      end
    end

for now I just added a check to make sure the variable is not nil before calling clear on it, but I am not sure if the problem is that the setup_subsriptions __should__ have been call and was not.

    def reset_template_assertion
      RENDER_TEMPLATE_INSTANCE_VARIABLES.each do |instance_variable|
        variable_name = "@_#{instance_variable}"
        variable = instance_variable_get(variable_name)
        variable.clear if variable
      end
    end

### PR DESCRIPTION
**Pull request by brainopia**
Fix #18285 

In rails 4.2.0 integration requests work only if are called inside setup-teardown cycle (for view-related assertions). But these methods (e.g, `#get`, `#post`) can be useful outside of current test to setup a context (cookies, session) for all requests, e.g., to use inside `before(:all)` with rspec.

### CODE REVIEW

File: actionpack/lib/action_controller/test_case.rb [hunk 1]
```diff
@@ -67,7 +67,7 @@ def process(*args)
 
     def reset_template_assertion
       RENDER_TEMPLATE_INSTANCE_VARIABLES.each do |instance_variable|
-        instance_variable_get("@_#{instance_variable}").clear
+        instance_variable_get("@_#{instance_variable}").try(:clear)
```
Comment (rafaelfranca) [inline actionpack/lib/action_controller/test_case.rb]: We usually avoid to use `try` inside the framework itself. Could you change it?

**Comment by brainopia** [comment]
@rafaelfranca done :bowtie:

**Comment by rafaelfranca** [comment]
Backported at dc99190
