### PR TITLE
Fix integer regex deprecation warnings for Ruby 2.6.0

### LINKED ISSUE #34718: Action View unit test shows `warning: deprecated Object#=~ is called on Integer; it always returns nil` with Ruby 2.6.0 rc2
[Ruby 2.6.0-rc2 Released](https://www.ruby-lang.org/en/news/2018/12/15/ruby-2-6-0-rc2-released/) and Ruby 2.6 release date is around the corner. There are some warnings with Ruby 2.6.0 rc2. Related to https://github.com/rails/rails/issues/34530

### Steps to reproduce
* Install `Ruby 2.6.0 rc2
```ruby
$ cd actionview
$ bundle exec rake test:template
```

### Expected behavior
It should work without warnings.

### Actual behavior
```ruby
$ bundle exec rake test:template
/home/yahonda/.rbenv/versions/2.6.0-rc2/bin/ruby -w -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/rake-12.3.1/lib" "/home/yahonda/.rbenv/versions/2.6.0-rc2/lib/ruby/gems/2.6.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb" "test/template/form_tag_helper_test.rb" "test/template/tag_helper_test.rb" "test/template/resolver_patterns_test.rb" "test/template/controller_helper_test.rb" "test/template/translation_helper_test.rb" "test/template/testing/fixture_resolver_test.rb" "test/template/testing/null_resolver_test.rb" "test/template/render_test.rb" "test/template/active_model_helper_test.rb" "test/template/text_helper_test.rb" "test/template/url_helper_test.rb" "test/template/date_helper_test.rb" "test/template/compiled_templates_test.rb" "test/template/test_test.rb" "test/template/text_test.rb" "test/template/template_test.rb" "test/template/template_error_test.rb" "test/template/record_identifier_test.rb" "test/template/capture_helper_test.rb" "test/template/partial_iteration_test.rb" "test/template/html_test.rb" "test/template/form_helper/form_with_test.rb" "test/template/erb_util_test.rb" "test/template/sanitize_helper_test.rb" "test/template/form_options_helper_test.rb" "test/template/javascript_helper_test.rb" "test/template/test_case_test.rb" "test/template/dependency_tracker_test.rb" "test/template/streaming_render_test.rb" "test/template/date_helper_i18n_test.rb" "test/template/digestor_test.rb" "test/template/atom_feed_helper_test.rb" "test/template/form_options_helper_i18n_test.rb" "test/template/erb/tag_helper_test.rb" "test/template/erb/form_for_test.rb" "test/template/lookup_context_test.rb" "test/template/resolver_cache_test.rb" "test/template/number_helper_test.rb" "test/template/form_helper_test.rb" "test/template/asset_tag_helper_test.rb" "test/template/form_collections_helper_test.rb" "test/template/output_safety_helper_test.rb" "test/template/log_subscriber_test.rb"
Run options: --seed 41114

# Running:

.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................../home/yahonda/git/rails/actionview/lib/action_view/helpers/text_helper.rb:231: warning: deprecated Object#=~ is called on Integer; it always returns nil
/home/yahonda/git/rails/actionview/lib/action_view/helpers/text_helper.rb:231: warning: deprecated Object#=~ is called on Integer; it always returns nil
......../home/yahonda/git/rails/actionview/lib/action_view/helpers/text_helper.rb:231: warning: deprecated Object#=~ is called on Integer; it always returns nil
/home/yahonda/git/rails/actionview/lib/action_view/helpers/text_helper.rb:231: warning: deprecated Object#=~ is called on Integer; it always returns nil
/home/yahonda/git/rails/actionview/lib/action_view/helpers/text_helper.rb:231: warning: deprecated Object#=~ is called on Integer; it always returns nil
/home/yahonda/git/rails/actionview/lib/action_view/helpers/text_helper.rb:231: warning: deprecated Object#=~ is called on Integer; it always returns nil
/home/yahonda/git/rails/actionview/lib/action_view/helpers/text_helper.rb:231: warning: deprecated Object#=~ is called on Integer; it always returns nil
/home/yahonda/git/rails/actionview/lib/action_view/helpers/text_helper.rb:231: warning: deprecated Object#=~ is called on Integer; it always returns nil
......................................................................................................................................................................................................................................................................................................................................................................................../home/yahonda/git/rails/actionview/lib/action_view/helpers/form_options_helper.rb:583: warning: deprecated Object#=~ is called on FormOptionsHelperTest::FakeZones::FakeZone; it always returns nil
/home/yahonda/git/rails/actionview/lib/action_view/helpers/form_options_helper.rb:583: warning: deprecated Object#=~ is called on FormOptionsHelperTest::FakeZones::FakeZone; it always returns nil
/home/yahonda/git/rails/actionview/lib/action_view/helpers/form_options_helper.rb:583: warning: deprecated Object#=~ is called on FormOptionsHelperTest::FakeZones::FakeZone; it always returns nil
/home/yahonda/git/rails/actionview/lib/action_view/helpers/form_options_helper.rb:583: warning: deprecated Object#=~ is called on FormOptionsHelperTest::FakeZones::FakeZone; it always returns nil
/home/yahonda/git/rails/actionview/lib/action_view/helpers/form_options_helper.rb:583: warning: deprecated Object#=~ is called on FormOptionsHelperTest::FakeZones::FakeZone; it always returns nil
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 23.822038s, 84.3337 runs/s, 188.5649 assertions/s.
2009 runs, 4492 assertions, 0 failures, 0 errors, 0 skips
$
```
### System configuration
**Rails version**:master branch whose latest commit is ce48b5a366482d4b4c4c053e1e39e79d71987197

**Ruby version**:ruby 2.6.0rc2 (2018-12-15 trunk 66408) [x86_64-linux]

### PR DESCRIPTION
**Pull request by vinistock**
### Summary

Fixes #34718 

From the description given in the issue, matching regexes for Integers or classes will always return nil in Ruby 2.6.0.

Therefore, this pull request calls to_s before matching regexes to make sure they are actually being validated.

### CODE REVIEW

**Comment by jeremy** [comment]
Test failure: https://travis-ci.org/rails/rails/jobs/469101728#L1463-L1475
```
Failure:
FormOptionsHelperTest#test_time_zone_select_with_priority_zones_is_not_implemented_with_grep [/home/travis/build/rails/rails/actionview/test/template/form_options_helper_test.rb:1282]:
Expected: <select id="firm_time_zone" name="firm[time_zone]"><option value="" disabled="disabled">-------------</option>
<option value="A">A</option>
<option value="B">B</option>
<option value="C">C</option>
<option value="D" selected="selected">D</option>
<option value="E">E</option></select>
Actual: <select name="firm[time_zone]" id="firm_time_zone"><option value="A">A</option>
<option selected="selected" value="D">D</option><option value="" disabled="disabled">-------------</option>
<option value="B">B</option>
<option value="C">C</option>
<option value="E">E</option></select>
```

**Comment by vinistock** [comment]
@jeremy I see...I looked into it and I'm having some trouble understanding why there would be a deprecation warning.

[This] line seems to be throwing the warning, but I thought the ```=~``` method was overridden [here]. Using to_s or grabbing the TimeZone's name breaks the same test.

Any ideas on the path forward for this one?

[This]: https://github.com/rails/rails/blob/528c5bb224a2f9ea6eee7b15ef5de5e9d17bf309/actionview/lib/action_view/helpers/form_options_helper.rb#L583
[here]: https://github.com/rails/rails/blob/528c5bb224a2f9ea6eee7b15ef5de5e9d17bf309/activesupport/lib/active_support/values/time_zone.rb#L333

File: actionview/lib/action_view/helpers/form_options_helper.rb [hunk 1]
```diff
@@ -580,7 +580,7 @@ def time_zone_options_for_select(selected = nil, priority_zones = nil, model = :
 
         if priority_zones
           if priority_zones.is_a?(Regexp)
-            priority_zones = zones.select { |z| z =~ priority_zones }
+            priority_zones = zones.select { |z| z.to_s =~ priority_zones }
```
Comment (y-yagi) [inline actionview/lib/action_view/helpers/form_options_helper.rb]: It is expected that instance of `ActiveSupport::TimeZone` be passed to `zones`. 
Since `ActiveSupport::TimeZone` has a `=~` method, so this warning should not normally show.
https://github.com/rails/rails/blob/0fa5b5510c6faefc33ab3715e08b2604195a1063/activesupport/lib/active_support/values/time_zone.rb#L331-L335 

The reason why this happens in the test is that the `=~` is not defined in the Fake class used in the test, so let's add the `=~` to the Fake class to deal with it.

Comment (vinistock) [reply actionview/lib/action_view/helpers/form_options_helper.rb]: Thanks for the assistance! That did the trick.

Comment (vinistock) [reply actionview/lib/action_view/helpers/form_options_helper.rb]: @y-yagi thanks for guidance! Wanted to contribute on this one, but was having a hard time figuring out the expected behavior for that particular test.

**Comment by y-yagi** [comment]
@vinistock Thanks!
