### PR TITLE
Fix `include?` on composite key relations

### LINKED ISSUE #51995: Composite key relations raise when calling `include?`
### Steps to reproduce
When calling `Model.objects.include? object` when the object has a composite primary key will raise an argument error `ArgumentError: Unsupported argument type: 1 (Integer)` instead of validating the object for inclusion in the relation. 

```
# frozen_string_literal: true

require "bundler/inline"
require "pry"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", path: "/Users/jackozi/ruby/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true, primary_key: %i[user_id account_id] do |t|
    t.bigint 'user_id', null: false
    t.bigint 'account_id', null: false
  end
end

ActiveRecord::Schema.define do
  create_table :comments, force: true, primary_key: %i[post_id account_id] do |t|
    t.bigint 'post_id', null: false
    t.bigint 'account_id', null: false
  end
end

class Post < ActiveRecord::Base
  has_many :comments, foreign_key: %i[post_id account_id]
end

class Comment < ActiveRecord::Base
  belongs_to :post, foreign_key: %i[post_id account_id]
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(user_id: 1, account_id: 1)
    comment = post.comments.create!(account_id: 1)

    assert post.comments.include? comment
  end
end

```

### Expected behavior
No error is raised and the relation is validated against inclusion in the relation. 

`assert post.comments.include? comment` in the example should pass.

### Actual behavior
`ArgumentError: Unsupported argument type: 1 (Integer)` is being raised.

### System configuration
**Rails version**:
Latest main branch

**Ruby version**:
3.3.1

### PR DESCRIPTION
**Pull request by jackozi**
Fixes #51995 

Calling `exists?` does not work with composite keys (#51295) which is used internally for `include?` here it zips the primary key values into a hash with the primary key keys, a format that is supported by `exists?` so it does not raise and returns the expected result.

### CODE REVIEW

**Comment by Jay0921** [comment]
@jackozi , Both your issue and fix seem valid to me. However, I see that many tests are failing. Perhaps you can rerun the tests. It will be easier for the Core team to merge when they see it.

File: activerecord/lib/active_record/associations/collection_association.rb [hunk 1]
```diff
@@ -260,7 +260,17 @@ def include?(record)
...
+              target.include?(record)
+            else
+              id = if record.class.composite_primary_key?
+                record.class.primary_key.zip(record.id).to_h
+              else
+                record.id
+              end
+
+              scope.exists?(id)
+            end
```
Comment (Jay0921) [inline activerecord/lib/active_record/associations/collection_association.rb:273]: Trivial: Probably, we can use this opportunity to refactor the code a little bit for better readability. Something like this: 

```ruby
def include?(record)
  klass = reflection.klass
  return false unless record.is_a?(klass)

  if record.new_record?
    include_in_memory?(record)
  elsif loaded?
    target.include?(record)
  else
    record_id = klass.composite_primary_key? ? klass.primary_key.zip(record.id).to_h : record.id
    scope.exists?(record_id)
  end
end
```

Comment (jackozi) [reply activerecord/lib/active_record/associations/collection_association.rb]: Thank you, that indeed looks cleaner!
