### PR TITLE
Optimize Active Record batching further when using ranges

### LINKED ISSUE #51242: Avoidable resource consumption when using "in_batches(use_ranges: true)"
### Steps to reproduce

In ActiveRecord 7.1, a new option was added to [ActiveRecord::Batches#in_batches](https://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-in_batches), `use_ranges: true`, that enables a more efficient way to generate queries from the provided scope for each batch.

The resulting queries use ranges to select record ids, e.g. `WHERE id > 10000 AND id <= 20000` instead of passing a possibly very long list of ids in an `IN` clause, e.g. `IN (10000, 10001, [...,] 19999, 20000)`.

This option was implemented in https://github.com/rails/rails/pull/45414.

The implementation of `use_ranges: true` relies on the already implemented strategy to select all ids from the range (needed for `use_ranges: false`), when generating the scope for each batch.

The typical SQL query to generate a scope for a batch is (example with batches of 10k records):

```sql
SELECT "users"."id" FROM "users" WHERE "users"."id" > ... ORDER BY "users"."id" ASC LIMIT 10000;
```

But subsequently, all these ids but the last one are discarded:

https://github.com/rails/rails/blob/v7.1.3.2/activerecord/lib/active_record/relation/batches.rb#L379-L380

**This method wastes resources in the database (CPU, I/O), in transit (bandwidth) and in the Ruby process (RAM).**

### Expected behavior

Only the last id of the batch should be selected and returned from the database, thus saving resources.

### Actual behavior

All ids from the batch are returned, thus wasting resources.

### System configuration

**Rails version**: `7.1.3.2` / `main`

**Ruby version**: `3.2.3`

### PR DESCRIPTION
**Pull request by maximerety**
### Motivation / Background

Fixes https://github.com/rails/rails/issues/51242

In ActiveRecord 7.1, a new option was added to [ActiveRecord::Batches#in_batches](https://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-in_batches), `use_ranges: true`, that enables a more efficient way to generate queries from the provided scope for each batch.

The resulting queries use ranges to select record ids, e.g. `WHERE id > 10000 AND id <= 20000` instead of passing a possibly very long list of ids in an `IN` clause, e.g. `IN (10000, 10001, [...,] 19999, 20000)`.

This option was implemented in https://github.com/rails/rails/pull/45414.

The implementation of `use_ranges: true` relies on the already implemented strategy to select all ids from the range (needed for `use_ranges: false`), when generating the scope for each batch.

The typical SQL query to generate a scope for a batch is (example with batches of 10k records):

```sql
SELECT "users"."id" FROM "users" WHERE "users"."id" > ... ORDER BY "users"."id" ASC LIMIT 10000;
```

But subsequently, all these ids but the last one are discarded:

https://github.com/rails/rails/blob/v7.1.3.2/activerecord/lib/active_record/relation/batches.rb#L379-L380

**This method wastes resources in the database (CPU, I/O), in transit (bandwidth) and in the Ruby process (RAM).**

This Pull Request is a proposal to save these resources by implementing **an additional optimisation**.

### Detail

The description below applies only to the use of `in_batches` **with** the option `use_ranges: true`.

Instead of returning all the ids for each batch, we use `OFFSET` to search for the last id in the next batch and return just one id, e.g.

```diff
  -- queries for all batches but the last (before/after)
- SELECT "users"."id" FROM "users" WHERE "users"."id" > ... ORDER BY "users"."id" ASC LIMIT 10000;
+ SELECT "users"."id" FROM "users" WHERE "users"."id" > ... ORDER BY "users"."id" ASC LIMIT 1 OFFSET 9999;
```

There is one downside, however.

Our `OFFSET`-based query won't be able to return the last id if the next batch is smaller than the limit or if there's no next batch. We always need one additional query to get the size and last id of the very last batch. We use the same query as before the optim for that purpose:

```diff
  -- queries for the last batch (before/after)
- SELECT "users"."id" FROM "users" WHERE "users"."id" > ... ORDER BY "users"."id" ASC LIMIT 10000;
+ SELECT "users"."id" FROM "users" WHERE "users"."id" > ... ORDER BY "users"."id" ASC LIMIT 1 OFFSET 9999;
+ SELECT "users"."id" FROM "users" WHERE "users"."id" > ... ORDER BY "users"."id" ASC LIMIT 10000;
```

Unless we only have a handful of small batches, this strategy is a winner overall, as it reduces the time and network resources spent generating batches, as shown by the benchmark below.

#### Benchmark

Let's reuse the benchmark from the description of https://github.com/rails/rails/pull/45414, i.e. the same `users` table with `10M` records, but with two modifications:

* Batches of 10k records instead of 1k;
* No call to `batch.count` on each batch since we are measuring only on the time and resources needed to generate the scopes, not to use them.

Here is the code used:

```sql
CREATE TABLE users (id bigserial PRIMARY KEY, val integer DEFAULT 0);
INSERT INTO users SELECT i FROM generate_series(1, 10000000) AS i;
```

```ruby
start = Process.clock_gettime(Process::CLOCK_MONOTONIC)

count = 0
User.in_batches(of: 10_000) do |batch|
  count += 1  # previously: batch.count, but we don't want to trigger any other queries in this benchmark
end

puts "Count = #{count}"
elapsed = Process.clock_gettime(Process::CLOCK_MONOTONIC) - start
puts "Elapsed: #{elapsed}s"
```

The benchmark is executed on a single machine (a recent macbook), with a round-trip-time < 1ms.

The network (I/O) stats are obtained by comparing the result of this command before/after a benchmark run:

```
docker stats --no-stream postgres --format 'table {{.NetIO}}'
```

**Here are the results:**

| Batching method                      | Duration | Network (I/O)     |
|--------------------------------------|---------:|------------------:|
| in_batches(use_ranges: true)         |    5.6 s.  |   &nbsp;&nbsp;1.2 MB / &nbsp;&nbsp;180 MB   |
| in_batches(use_ranges: true) + optim from this PR |     2.3 s.  |   &nbsp;&nbsp;< 0.5 MB /  < 0.2 MB   |

In this benchmark, we managed to **generate scopes for batches `x2.4` times faster and with `x900` times less bandwidth**. These results will of course typically vary with the batch size used, and the network speed.

The absolute values may not seem like huge gains, but I'm considering using `in_batches(use_ranges: true)` on tables with over 3 billion records, where this benchmark would show a saving of at least `16+ minutes` and `52.7 GB` of bandwidth (+ the database resources needed to extract/send this traffic).

#### Other strategies considered

Using `OFFSET` is not be the only way to achieve the same kind of optimisation.

For example, we could consider using a strategy based on the calculation of the maximum id + batch size for each batch (details folded below).

<details>
  <summary>Using a CTE</summary>
<br />
We could use a CTE like this one:

```sql
WITH "batch_ids" AS (
    -- same query as today
    SELECT "users"."id" FROM "users" WHERE (id > 10000) ORDER BY "users"."id" ASC LIMIT 10000
)
SELECT COUNT(id) AS last_batch_size, MAX(id) AS last_batch_id FROM batch_ids;
```

This would be advantageous, as we would not have to use that "extra" query for the last batch as we did above.

Nevertheless, using a CTE would have the following downsides:

1. CTEs are not supported yet by all RDBMS supported by Active Record (MySQL < 8.0)
2. To my knowledge, ActiveRecord does not provide any way to easily generate a query with two distinct calculations such as a count and a maximum. The "manual" workarounds for this could be complicated.

For the record, the query above can be generated with:

```ruby
User.connection.select_one(
  User
    .with(batch_ids: User.select('id').where('id > 10000').order(:id).limit(10000))
    .from('batch_ids')
    .select('COUNT(id) AS last_batch_size', 'MAX(id) AS last_batch_id')
)
```
</details>

<details>
  <summary>Using a subquery</summary>
<br />
We could use a subquery like this one:

```sql
SELECT
    COUNT(id) AS last_batch_size, MAX(id) AS last_batch_id
FROM (
    -- same query as today
    SELECT "users"."id" FROM "users" WHERE (id > 10000) ORDER BY "users"."id" ASC LIMIT 10000
) subquery;
```

Even better than the CTE version because this would be compatible with all RDBMS supported by ActiveRecord.

For the record, the query above can be generated with:

```ruby
User.connection.select_one(
  User.select('COUNT(id) AS last_batch_size', 'MAX(id) AS last_batch_id').from(
    User.select('id').where('id > 10000').order(:id).limit(10000)
  )
)
```

But to support all sorts of primary keys (including composite) and multiple calculations in a single query, I suspect some complicated work is required in Active Record. If you think this is feasible at a reasonable cost, please provide some guidance 🙏 
</details>

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/lib/active_record/relation/batches.rb [hunk 1]
```diff
@@ -373,32 +373,44 @@ def batch_on_unloaded_relation(relation:, start:, finish:, load:, order:, use_ra
           if load
             records = batch_relation.records
             ids = records.map(&:id)
+            ids_size = ids.size
+            ids_last = ids.last
```
Comment (yawboakye) [inline activerecord/lib/active_record/relation/batches.rb:377]: @maximerety are we guaranteed that ids are sorted? or it doesn't matter here?

File: activerecord/lib/active_record/relation/batches.rb [hunk 2]
```diff
@@ -373,32 +373,44 @@ def batch_on_unloaded_relation(relation:, start:, finish:, load:, order:, use_ra
...
+            ids_size = batch_limit
+            ids_last = batch_relation.offset(batch_limit - 1).limit(1).ids.first
+            # If the last id is not found using offset, there is at most one more batch of size < batch_limit.
+            # We retry getting the list of ids so that we have the exact size and last id.
+            unless ids_last
+              ids = batch_relation.ids
+              ids_size = ids.size
+              ids_last = ids.last
+            end
+            if ids_last
```
Comment (yawboakye) [inline activerecord/lib/active_record/relation/batches.rb:391]: @maximerety good stuff removing the confusing second introduction of `finish` in this scope. thank you ❤️

**Review by yawboakye — COMMENTED** [review]
@maximerety if we're generating a significantly different sql query now, it might be worth it adding a test case for the specific sql statement that was generated? especially to include the `offset` clause. otherwise lgtm!

File: activerecord/lib/active_record/relation/batches.rb (hunk 1 above)
Comment (maximerety) [reply activerecord/lib/active_record/relation/batches.rb:377]: These ids are already sorted indeed, because the `batch_relation` used is reordered with `reorder(batch_orders.to_h)` at the beginning of the method.

Note that I'm merely caching some values earlier here, but I did not change the logic of checking them later in the implementation. So it was already expected that the list was sorted.

**Comment by maximerety** [comment]
>Implementor of use_ranges here. I originally considered selecting only the last record, but the win was already so large, that I didn't bothered to make the code more complicated. But 👍 for the idea.
>
> Depending on what you are trying to achieve on yours 3 billion records table and how often you do this, you may even consider something like [efficient code example...]

@fatkodima Thank you for the original optimization and the additional context about its implementation. Indeed, it did make sense to focus on the biggest gain then.

I used your alternative strategy in some places already (it wasn't a Rails project) and I can confirm it is the fastest option where suited. Thanks for the reminder!

> If we're generating a significantly different sql query now, it might be worth it adding a test case for the specific sql statement that was generated? especially to include the offset clause. otherwise lgtm!

@yawboakye Good idea.

There were no assertions previously on the queries to generate the relations for each batch (only assertions on the queries subsequently created when using the relations). I've completed existing tests with assertions for both kinds of queries, and splitted in two steps to clarify what we are testing.

Please ket me know if it makes sense you 🙏.

**Comment by yawboakye** [comment]
Looks ready to me. Great win! cc @fatkodima

**Comment by maximerety** [comment]
@fatkodima I'd be grateful for your feedback on this PR again, now that the tests on the queries have been updated.

Let me know if you think anything should be changed/improved, and whether that change seems interesting enough to be integrated.

Thank you.

File: activerecord/CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,19 @@
+*   Optimize Active Record batching further when using ranges.
+
+    When used for full table iterations, or with the `use_ranges: true` option, `in_batches`
```
Comment (fatkodima) [inline activerecord/CHANGELOG.md:3]: While this info is inspiring and interesting, it is pretty long and I am not sure that users reading the CHANGELOG need to read this. Maybe paste these into the commit body itself?

For this change, I would leave only the first line and the last one (starting with `E.g., tested ....`)

File: activerecord/lib/active_record/relation/batches.rb [hunk 4]
```diff
@@ -373,32 +373,44 @@ def batch_on_unloaded_relation(relation:, start:, finish:, load:, order:, use_ra
...
+            # Efficiently peak at the last id for the next batch using offset and limit.
+            ids_size = batch_limit
+            ids_last = batch_relation.offset(batch_limit - 1).limit(1).ids.first
+            # If the last id is not found using offset, there is at most one more batch of size < batch_limit.
+            # We retry getting the list of ids so that we have the exact size and last id.
+            unless ids_last
+              ids = batch_relation.ids
+              ids_size = ids.size
+              ids_last = ids.last
+            end
```
Comment (fatkodima) [inline activerecord/lib/active_record/relation/batches.rb:390]: Up to you, but this conditional can be avoided by making the `else` branch for `if ids_last` with something like
```ruby
else
  ids_size = nil
end
```

and then instead of checking `break if ids_size == 0` do `break unless ids_size`.

**Review by fatkodima — COMMENTED** [review]
Looks good 👏 

When finished, I encourage you to ask for review on the Discord channel.

File: activerecord/lib/active_record/relation/batches.rb (hunk 4 above)
Comment (maximerety) [reply activerecord/lib/active_record/relation/batches.rb:390]: The code as currently implemented goes through each of these steps in order:

1. Find batch size and last id using OFFSET and LIMIT (fast path)
2. When 1. failed (no result), retry by querying the whole range of ids (slow path)
3. If either 1. of 2. was able to return at least one id, build the yielded relation and actually yield it

If I understand your comment correctly, we would try to remove step 2. and add an `else` branch to step 3.

I don't see how this could work, but maybe I misunderstood your proposal?

File: activerecord/CHANGELOG.md (hunk 3 above)
Comment (maximerety) [reply activerecord/CHANGELOG.md]: Good point, I made that changelog entry way too complicated.
I've updated it as you suggested.

File: activerecord/lib/active_record/relation/batches.rb (hunk 4 above)
Comment (maximerety) [reply activerecord/lib/active_record/relation/batches.rb]: Note: this snippet is a bit outdated since this branch has been updated to comply with https://github.com/rails/rails/pull/52384.

But the logic stays the same, so I still don't see how I could change the implementation with breaking the logic.

**Comment by fatkodima** [comment]
@maximerety Can you rebase this PR?

**Comment by fatkodima** [comment]
For the default batch size (1000), from my measurements, it is now 2x faster and allocates 6x less memory.

**Comment by maximerety** [comment]
> @maximerety Can you rebase this PR?

@fatkodima I just saw that it was merged when I came back from paternity leave :wink: Thanks for taking care of it!

**Comment by fatkodima** [comment]
Thanks for the PR and improving rails! ❤️
