### PR TITLE
Make Active Support Cache treat deserialization errors like cache misses

### LINKED ISSUE #48611: Error loading cached data after upgrade to 7.1 `dump format error`
We have a Rails `7.0.5.1` app set with `config.load_defaults 6.0`

When attempting to upgrade to 7.1.0-alpha, with cached data already present in the app (Redis cache) I'm getting an error when Rails attempts to read the data with `Marshal.load` in `Marshal61WithFallback` ([here](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/cache/serializer_with_fallback.rb#L147)). 

```
Argument Error 
dump format error (user class)
```

The cached data is correctly identified as 6.1 with `Marshal61WithFallback::MARSHAL_SIGNATURE` but fails to load.  

I've created an [example app](https://github.com/matthutchinson/rails-caching-example) where you can easily replicate this, (see reproduction instructions below).

From reading recent commits and the [CHANGELOG](https://github.com/rails/rails/blob/main/activesupport/CHANGELOG.md), I can see that @jonathanhefner did make some --recent changes in here, but from what I can see, this should just work, without any necessary cache migration.  

### Steps to reproduce

```
git clone https://github.com/matthutchinson/rails-caching-example
cd rails-caching-example
bin/setup
rails db:seed
rails dev:cache
rails server
open https://localhost:3000

# visit page, causing partials to be cached
# stop server
# edit Gemfile, set to use edge rails from gh master

bundle update rails
rails server
open https://localhost:3000
# page errors when loading cached data with dump format error (user class)

```

Here's a what the [dumped var](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/cache/serializer_with_fallback.rb#L26) looks like in my [example app](https://github.com/matthutchinson/rails-caching-example) and I'm caching partials in `high_scores#index` with;

`<%= render partial: "high_score", collection: @high_scores, cached: true %>`

```
"\u0004\bo: ActiveSupport::Cache::Entry\t:\v@valueIC:\u001DActionView::OutputBuffer\"\u0001\xAB<div id=\"high_score_1\">\n  <p>\n    <strong>Game:</strong>\n    <a href=\"/high_scores/1\">Tetris</a>\n  </p>\n\n  <p>\n    <strong>Score:</strong>\n    100000\n  </p>\n\n</div>\n<hr/>\n\a:\u0006ET:\u000F@html_safeT:\r@versionI\"\u001920230628145327125454\u0006;\bT:\u0010@created_atf\u00060:\u0010@expires_in0"
```

### Expected behavior

Cached partial data should be loaded and displayed without error

### Actual behavior

Error raised when loading cached data from `Marshal.load`

```
Argument Error 
dump format error (user class)
```

Screenshot 2023-06-28 at 16 35 43

### System configuration

**Rails version**: `7.1.0-alpha` (migrating from `7.0.5.1`)
**Ruby version**: `3.1.2` and `3.2.0` 

#### Other Notes:

* I thought [this commit](https://github.com/jonathanhefner/rails/commit/e2524e574b2f8f157190c00e7c2d1377995d2fdd) might have been the cause, but reverting to the commit before that, I get the same issue.
* Clearing the cache will fix the issue, but in production, we'd really prefer not to have to do that.  
* If clearing the cache _is a requirement_, we should update the docs and upgrade guide to explain that.

cc @jonathanhefner

### PR DESCRIPTION
**Pull request by casperisfine**
Fix: https://github.com/rails/rails/issues/48611

This help treating caches entries as expandable.

Because Marshal will hapily serialize almost everything, It's not uncommon to inadvertently cache a class that's not particularly stable, and cause deserialization errors on rollout when the implementation changes.

E.g. https://github.com/sporkmonger/addressable/pull/508

FYI: @jonathanhefner @matthewd @matthutchinson

### CODE REVIEW

File: activesupport/test/cache/behaviors/cache_store_format_version_behavior.rb [hunk 1]
```diff
@@ -26,6 +26,24 @@ module CacheStoreFormatVersionBehavior
       end
     end
 
+    FORMAT_VERSIONS.each do |format_version|
+      test "Marshal undefined class/module deserialization error with #{format_version} format" do
+        format_was = ActiveSupport::Cache.format_version
+        ActiveSupport::Cache.format_version = format_version
```
Comment (jonathanhefner) [inline activesupport/test/cache/behaviors/cache_store_format_version_behavior.rb:32]: Considering that we are using `with_format` below, is this assignment still necessary?

File: activesupport/test/cache/behaviors/cache_store_format_version_behavior.rb [hunk 2]
```diff
@@ -26,6 +26,24 @@ module CacheStoreFormatVersionBehavior
...
+        self.class.const_set(:Foo, Class.new)
+        @store = with_format(format_version) { lookup_store }
+        @store.write("foo", self.class::Foo.new)
```
Comment (jonathanhefner) [inline activesupport/test/cache/behaviors/cache_store_format_version_behavior.rb:35]: Should this use a randomly generated key to prevent flakey tests a la #43670?

**Review by jonathanhefner — COMMENTED** [review]
:+1:
