### PR TITLE
Make sure there are no duplicated nested records with create_with

### LINKED ISSUE #33610: Duplicate nested records created with `create_with` & `find_or_create_by` for >= rails 5.2
### Steps to reproduce
I've created a gist that demonstrates the issue, testing:
* 5.1.6 - works as expected
* 5.2.0 - creates duplicate nested record
* 5.2.1 - creates duplicate nested record
* rails master - creates duplicate nested record

Gist tests each of the above in a random order (with the same results)
https://gist.github.com/abrom/e9ff2cda1676d749677e31af7af604c6

### Expected behavior
With the following models:
```
class Foo < ActiveRecord::Base
  has_many :bars
  accepts_nested_attributes_for :bars
end

class Bar < ActiveRecord::Base
  belongs_to :foo
end
```

expect the following to create one `Foo` and one `Bar` record:
```
Foo.create_with(
  bars_attributes: [{ bar_name: 'bar_test' }]
).find_or_create_by!(
  foo_name: 'foo_test'
)
```

### Actual behavior
Rails 5.1.6 (as expected) creates one `Foo` and one `Bar` record:
```
Foo Load (0.2ms)  SELECT  "foos".* FROM "foos" WHERE "foos"."foo_name" = ? LIMIT ?  [["foo_name", "foo_test"], ["LIMIT", 1]]
 (0.1ms)  begin transaction
SQL (0.3ms)  INSERT INTO "foos" ("foo_name") VALUES (?)  [["foo_name", "foo_test"]]
SQL (0.1ms)  INSERT INTO "bars" ("bar_name", "foo_id") VALUES (?, ?)  [["bar_name", "bar_test"], ["foo_id", 2]]
 (0.6ms)  commit transaction
```

Rails >= 5.2 creates one `Foo` but *TWO* `Bar` records
```
Foo Load (0.2ms)  SELECT  "foos".* FROM "foos" WHERE "foos"."foo_name" = ? LIMIT ?  [["foo_name", "foo_test"], ["LIMIT", 1]]
 (0.0ms)  begin transaction
Foo Create (0.4ms)  INSERT INTO "foos" ("foo_name") VALUES (?)  [["foo_name", "foo_test"]]
Bar Create (0.1ms)  INSERT INTO "bars" ("bar_name", "foo_id") VALUES (?, ?)  [["bar_name", "bar_test"], ["foo_id", 3]]
Bar Create (0.0ms)  INSERT INTO "bars" ("bar_name", "foo_id") VALUES (?, ?)  [["bar_name", "bar_test"], ["foo_id", 3]]
 (0.7ms)  commit transaction
```

Also note, if two nested bar attributes are provided, 4 records are created etc. 

### System configuration
**Rails version**:
Various - see above

**Ruby version**:
Tested with Ruby 2.4.4 and 2.5.0

### PR DESCRIPTION
**Pull request by darwin67**
### Summary
Fixes https://github.com/rails/rails/issues/33610

Looks like the issue is happening at `populate_with_current_scope_attributes` where it shouldn't try to assign the `scope_attributes` on the initial evaluation, which results in a duplicate record.

e.g.) In the test example, when creating a `Man` record, the current behaviour with `:create_with` attribute registered in a `Relation` is that it will try to create an `Interest` record before  the owner `Man`, instead of creating `Man` first, then build `Interest` based on `Man`.

making `scope_attributes?` truly returns boolean should fix it instead returning an empty relation that evaluates to true.

### CODE REVIEW

**Comment by darwin67** [comment]
okay great, tests are failing. i guess the `.present?` will evaluate and load the relation object from the database.

**Comment by darwin67** [comment]
Would you mind taking a look? @rafaelfranca

**Comment by rafaelfranca** [comment]
This fix seems indeed hacky. I think first we need to understand why it started to fail given it was working on 5.1. Can you try to bisect to see which commit introduced this bug?

**Comment by darwin67** [comment]
Sure, how can I install `arel 9.0.0.alpha`?

I was 3 steps in bisect between `v5.1.0` and `master` and now I'm seeing this when I try to run the reproduction script.
`rails/arel` doesn't seem to tag it's pre-releases and I don't have a git ref for the `arel` at the time so I'm not sure how I can get this working.
```
/var/lib/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/resolver.rb:55:in `rescue in start': Bundler could not find compatible versions for gem "arel": (Bundler::VersionConflict)
  In Gemfile:
    activerecord was resolved to 5.2.0.alpha, which depends on
      arel (= 9.0.0.alpha)

Could not find gem 'arel (= 9.0.0.alpha)', which is required by gem 'activerecord', in any of the sources.
```

**Comment by darwin67** [comment]
This is the script I'm running. I have rails as a symlink inside the VM so I can just reference the specific version while bisecting.

```
#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  # gem 'rails', path: 'rails'
  gem 'activerecord', path: 'rails'
  gem "minitest"
  gem 'sqlite3'
  # gem 'mysql2'
  # gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# sqlite3
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
# ActiveRecord::Base.establish_connection(adapter: 'mysql2', database: 'test', username: 'root', password: 'root')
# ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: 'test', username: 'vagrant')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  # STEP TWO: Define your tables here.
  create_table :foos do |t|
    t.string :foo_name
  end

  create_table :bars do |t|
    t.string :bar_name
    t.references :foo
  end

  create_table :foobars do |t|
    t.string :foobar_name
    t.references :foo
  end
end

# Define models
class Foo < ActiveRecord::Base
  has_one :foobar
  has_many :bars
  accepts_nested_attributes_for :bars
  accepts_nested_attributes_for :foobar
end

class Bar < ActiveRecord::Base
  belongs_to :foo
end

class Foobar < ActiveRecord::Base
  belongs_to :foo
end

# Test the issue
class BugTest < ActiveSupport::TestCase
  teardown do
    Foo.delete_all
    Bar.delete_all
    Foobar.delete_all
  end

  def test_1
    assert_changes -> { Foo.count }, from: 0, to: 1 do
      assert_changes -> { Bar.count }, from: 0, to: 1 do
        assert_changes -> { Foobar.count }, from: 0, to: 1 do
          Foo.create_with(
            bars_attributes: [{ bar_name: 'bar_test' }],
            foobar_attributes: { foobar_name: 'foobar_test' }
          ).find_or_create_by!(
            foo_name: 'foo_test'
          )
          puts "Number of Bar: #{Bar.count}"
          puts "Number of Foobar: #{Foobar.count}"
        end
      end
    end
  end
end
```

**Comment by darwin67** [comment]
This seems to have introduced it. https://github.com/rails/rails/commit/d4007d5a54b60bd6924eeffb52c126ed32e9f31f

**Comment by rafaelfranca** [comment]
Cool. That seems a better place to fix. cc @kamipo if you have pointers on how the best fix this.

**Comment by kamipo** [comment]
We should not change the `scope_attributes?`, at least this PR would break the following `create_with` with `scoping` use case:

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  # STEP TWO: Define your tables here.
  create_table :foos, force: true do |t|
    t.string :foo_name
  end

  create_table :bars, force: true do |t|
    t.string :bar_name
    t.references :foo
  end

  create_table :foobars, force: true do |t|
    t.string :foobar_name
    t.references :foo
  end
end

# Define models
class Foo < ActiveRecord::Base
  has_one :foobar
  has_many :bars
  accepts_nested_attributes_for :bars
  accepts_nested_attributes_for :foobar
end

class Bar < ActiveRecord::Base
  belongs_to :foo
end

class Foobar < ActiveRecord::Base
  belongs_to :foo
end

# Test the issue
class BugTest < ActiveSupport::TestCase
  teardown do
    Foo.delete_all
    Bar.delete_all
    Foobar.delete_all
  end

  def test_1
    assert_changes "Foo.count", from: 0, to: 1 do
      assert_changes "Bar.count", from: 0, to: 1 do
        assert_changes "Foobar.count", from: 0, to: 1 do
          Foo.create_with(
            bars_attributes: [{ bar_name: 'bar_test' }],
            foobar_attributes: { foobar_name: 'foobar_test' }
          ).scoping do
            Foo.create!(foo_name: 'foo_test')
          end
          puts "Number of Bar: #{Bar.count}"
          puts "Number of Foobar: #{Foobar.count}"
        end
      end
    end
  end
end
```

**Comment by darwin67** [comment]
Oh, thank you for pointing that out. I'll add that case to the test as well.
I guess I'll have to look into the `create_with_scope` and attributes being passed in then.

**Comment by darwin67** [comment]
Okay, I finally see the issue here. My previous estimates were pretty off target.

Due to the change in https://github.com/rails/rails/commit/d4007d5a54b60bd6924eeffb52c126ed32e9f31f, attributes being passed into `klass.new` now includes the `create_with_value` too.

Which results in double assigning at
```
initialize_internals_callback
```
and
```
assign_attributes(attributes) if attributes
```
in https://github.com/rails/rails/blob/master/activerecord/lib/active_record/core.rb#L304-L315

This is usually fine most of the time since double assignment of the same attributes on a record is idempotent. However, if the attributes includes nested attributes (only for `has_many`), this will result in trying to assign `<child>_attributes` twice, which then leads to the duplicate record in #33610 .

I've been trying a couple different things like adding an additional flag to `scope_for_create`,  or create a different method `values_for_create` for `create!` to consume
```
    def scope_for_create
      where_values_hash.merge!(create_with_value.stringify_keys)
    end

    def values_for_create(attributes = nil)
      attributes ? scope_for_create.merge!(attributes) : scope_for_create
    end
```
but will always result in something else breaking.

Any better ideas of how to approach this? @kamipo

**Comment by darwin67** [comment]
Oh, actually it seems to work. But I'm not fully aware of the edge cases. Can you think or any that this change could break? @kamipo

File: activerecord/lib/active_record/relation.rb [hunk 1]
```diff
@@ -554,10 +554,12 @@ def where_values_hash(relation_table_name = klass.table_name)
...
 
-    def scope_for_create(attributes = nil)
-      scope = where_values_hash.merge!(create_with_value.stringify_keys)
-      scope.merge!(attributes) if attributes
-      scope
+    def scope_for_create
+      where_values_hash.merge!(create_with_value.stringify_keys)
+    end
+
+    def values_for_create(attributes = nil)
```
Comment (kamipo) [inline activerecord/lib/active_record/relation.rb]: Add `# :nodoc:`

**Comment by kamipo** [comment]
Can you add an extra test like this?

```diff
diff --git a/activerecord/test/cases/relations_test.rb b/activerecord/test/cases/relations_test.rb
index d03b412efb..c14dc23cf3 100644
--- a/activerecord/test/cases/relations_test.rb
+++ b/activerecord/test/cases/relations_test.rb
@@ -9,6 +9,7 @@
 require "models/author"
 require "models/entrant"
 require "models/developer"
+require "models/project"
 require "models/person"
 require "models/computer"
 require "models/reply"
@@ -1405,6 +1406,16 @@ def test_explicit_create_with
     assert_equal "cock", hens.new.name
   end
 
+  def test_create_with_nested_attributes
+    assert_difference("Project.count", 1) do
+      developers = Developer.where(name: "Aaron")
+      developers = developers.create_with(
+        projects_attributes: [{ name: "p1" }]
+      )
+      developers.create!
+    end
+  end
+
   def test_except
     relation = Post.where(author_id: 1).order("id ASC").limit(1)
     assert_equal [posts(:welcome)], relation.to_a
```

File: activerecord/lib/active_record/relation.rb (hunk 1 above)
Comment (darwin67) [reply activerecord/lib/active_record/relation.rb]: sure, should I make this method private then?

Comment (kamipo) [reply activerecord/lib/active_record/relation.rb]: Yeah, that would be great.

**Comment by darwin67** [comment]
Added suggested test and great catch.
Unfortunately, this will require me to make an ugly change to get things to work. :(

File: activerecord/lib/active_record/relation.rb [hunk 2]
```diff
@@ -708,5 +706,19 @@ def tables_in_string(string)
...
+
+      def values_for_create(attributes = nil)
+        result = attributes ? where_values_hash.merge!(attributes) : where_values_hash
+
+        # NOTE: if there are same keys in both create_with and result, create_with should be used.
+        # This is to make sure nested attributes don't get passed to the klass.new,
+        # while keeping the precedence of the duplicate keys in create_with.
+        # Sorry, this doesn't look nice but it's the only way now. :(
+        create_with_value.stringify_keys.each do |k, v|
+          result[k] = v if result[k]
```
Comment (kamipo) [inline activerecord/lib/active_record/relation.rb]: Can you change this line to pass the following test?

```diff
diff --git a/activerecord/test/cases/scoping/default_scoping_test.rb b/activerecord/test/cases/scoping/default_scoping_test.rb
index 2127b2ea3d..0637aba4ec 100644
--- a/activerecord/test/cases/scoping/default_scoping_test.rb
+++ b/activerecord/test/cases/scoping/default_scoping_test.rb
@@ -366,6 +366,11 @@ def test_create_with_reset
     assert_equal "Jamis", jamis.name
   end
 
+  def test_create_with_takes_precedence_over_where
+    developer = Developer.where(name: nil).create_with(name: "Aaron").new
+    assert_equal "Aaron", developer.name
+  end
+
   def test_create_with_nested_attributes
     assert_difference("Project.count", 1) do
       Developer.create_with(
```

File: activerecord/test/cases/scoping/default_scoping_test.rb [hunk 3]
```diff
@@ -366,6 +366,16 @@ def test_create_with_reset
     assert_equal "Jamis", jamis.name
   end
 
+  def test_create_with_nested_attributes
+    assert_difference("Project.count", 1) do
```
Comment (kamipo) [inline activerecord/test/cases/scoping/default_scoping_test.rb]: Isolation test would be failed without `require "models/project"`.

File: activerecord/lib/active_record/relation.rb [hunk 4]
```diff
@@ -708,5 +706,19 @@ def tables_in_string(string)
...
         string.scan(/([a-zA-Z_][.\w]+).?\./).flatten.map(&:downcase).uniq - ["raw_sql_"]
       end
+
+      def values_for_create(attributes = nil)
+        result = attributes ? where_values_hash.merge!(attributes) : where_values_hash
+
+        # NOTE: if there are same keys in both create_with and result, create_with should be used.
+        # This is to make sure nested attributes don't get passed to the klass.new,
+        # while keeping the precedence of the duplicate keys in create_with.
+        # Sorry, this doesn't look nice but it's the only way now. :(
```
Comment (kamipo) [inline activerecord/lib/active_record/relation.rb]: Can you remove this line?
This doesn't look nice, but it will be resolved in the near future by refactoring internal scoping things.

File: activerecord/test/cases/scoping/default_scoping_test.rb (hunk 3 above)
Comment (darwin67) [reply activerecord/test/cases/scoping/default_scoping_test.rb]: oh, my bad. I thought it was included.

File: activerecord/lib/active_record/relation.rb (hunk 4 above)
Comment (darwin67) [reply activerecord/lib/active_record/relation.rb]: just line 716 or the entire comment?

File: activerecord/lib/active_record/relation.rb [hunk 5]
```diff
@@ -708,5 +706,19 @@ def tables_in_string(string)
...
+
+      def values_for_create(attributes = nil)
+        result = attributes ? where_values_hash.merge!(attributes) : where_values_hash
+
+        # NOTE: if there are same keys in both create_with and result, create_with should be used.
+        # This is to make sure nested attributes don't get passed to the klass.new,
+        # while keeping the precedence of the duplicate keys in create_with.
+        keys = result.keys
+        create_with_value.stringify_keys.each do |k, v|
+          result[k] = v if keys.include?(k)
```
Comment (kamipo) [inline activerecord/lib/active_record/relation.rb]: Use `result.key?(k)` instead.

**Review by kamipo — APPROVED** [review]
Looks good. Can you squash your commits into one?

**Comment by kamipo** [comment]
Thanks!
