### PR TITLE
Fix GROUP BY queries to apply LIMIT/OFFSET after aggregations

### LINKED ISSUE #8103: Limit replaces select clause when used with having
Practical Problem:
`Thing.group("things.id, other_things.id").having("other_things.id = 1").
                        includes(:other_things).count`
vs
`Thing.group("things.id, other_things.id").having("other_things.id = 1").
                    includes(:other_things).limit(1)`

Easy way to reproduce it:

`Thing.select("b").group("things.id").having("other_things.id = 1").includes(:other_things).limit(1)`

`SELECT DISTINCT `things`.id FROM `things` LEFT OUTER JOIN `other_things` ON `other_things`.`thing_id` = `things`.`id` ...`

the select clause is completely replaced

`Thing.select("b").group("things.id").having("other_things.id = 1").includes(:other_things).count`

`SELECT COUNT(DISTINCT b) AS count_b, b, things.id AS things_id FROM `things` 
LEFT OUTER JOIN `other_things` ON `other_things`.`thing_id` = `things`.`id` GROUP BY things.id 
HAVING other_things.id = 1`

---

.count has the correct behavior, and leaves the extra columns in the select clause. .limit() replaces the select clause and breaks the query.

### PR DESCRIPTION
**Pull request by kamipo**
If `eager_loading` is true, `apply_join_dependency` force applies
LIMIT/OFFSET before JOINs by `limited_ids_for` to keep parent records
count. But for aggregation queries, LIMIT/OFFSET should be applied after
aggregations the same as SQL semantics.

And also, we could not replace SELECT list by `limited_ids_for` when a
query has a GROUP BY clause. It had never been worked since it will
causes generating invalid SQL for MySQL, PostgreSQL, and probably most
backends.

```
% ARCONN=postgresql be ruby -w -Itest test/cases/calculations_test.rb -n test_group_by_with_limit
Using postgresql
Run options: -n test_group_by_with_limit --seed 20925

# Running:

E

Error:
CalculationsTest#test_group_by_with_limit:
ActiveRecord::StatementInvalid: PG::GroupingError: ERROR:  column "posts.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT  DISTINCT "posts"."id", "posts"."type" AS alias_0 FRO...                         ^
: SELECT  DISTINCT "posts"."id", "posts"."type" AS alias_0 FROM "posts" LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id" GROUP BY "posts"."type" ORDER BY "posts"."type" ASC LIMIT $1
```

Fixes #8103.
Closes #27249.

### CODE REVIEW

File: activerecord/lib/active_record/relation/finder_methods.rb [hunk 1]
```diff
@@ -409,10 +409,11 @@ def construct_relation_for_association_calculations
       def apply_join_dependency(relation, join_dependency)
         relation = relation.except(:includes, :eager_load, :preload).joins!(join_dependency)
 
-        if using_limitable_reflections?(join_dependency.reflections)
+        if using_limitable_reflections?(join_dependency.reflections) ||
+            relation.group_values.any? || relation.having_clause.any?
```
Comment (matthewd) [inline activerecord/lib/active_record/relation/finder_methods.rb]: This doesn't read right to me: the existing condition is taking a shortcut if that shortcut is known to be safe, while the new alternatives are allowing additional paths when that condition has specifically declared it *not* safe to limit.

Comment (kamipo) [inline activerecord/lib/active_record/relation/finder_methods.rb]: `limited_ids_for` is not always safe for a GROUP BY query in the first place.
What should we do in that case?

**Comment by kamipo** [comment]
Related #27249.

**Comment by afdev82** [comment]
This MR probably is the reason for the bug in this gem: https://github.com/patricklindsay/wice_grid/issues/60.
I don't know how to fix this, but reverting the commit solved the problem.
