### PR TITLE
Fix ActiveStorage has_one_attached when blob or record are not persisted

### LINKED ISSUE #37069: ActiveStorage `has_one_attached` not purging attachments
I'm not able to purge an attachment using `has_one_attached` and the newest version of Rails.

I was working to update an open-source project from Rails 5.2 to Rails 6.0 and I encountered this issue.

I've created a dummy app with a failing test.

Basically I have a model `Bucket` with a `has_one_attached :image` attribute. I'm able to set the attachment but I'm not able to call `purge` in order to delete it.

I don't know what I'm missing here.

### Steps to reproduce

Just clone the repo:
https://github.com/marclerodrigues/active-storage-not-purging

And run the following commands:
```
bundle install
bundle exec rails db:setup
bundle exec rspec
```

### Expected behavior
Whenever I call `purge` the attachment and its associated blob should be deleted.

### Actual behavior
When I call `purge`, I'm getting a `FrozenError (can't modify frozen Hash)`.

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.3

### PR DESCRIPTION
**Pull request by intrip**
### Summary

- Purging a not persisted blob no longer raise a `FrozenError`.
- Purging a not persisted record no longer raise an `ActiveRecord::ActiveRecordError`.

Fixes #37069

### CODE REVIEW

**Comment by intrip** [comment]
@georgeclaghorn since you provided guidance for the related issue could you please check?

**Comment by zzak** [comment]
Unfortunately I think George has resigned from the Rails core, so I doubt we'll get an answer from him.

This approach seems reasonable to me though. What happens for `has_many_attached`?

File: activestorage/lib/active_storage/attached.rb [hunk 1]
```diff
@@ -16,6 +16,10 @@ def initialize(name, record)
       def change
         record.attachment_changes[name]
       end
+
+      def reset_changes
```
Comment (zzak) [inline activestorage/lib/active_storage/attached.rb:20]: This method sticks out to me, I wonder if we shouldn't be using [Attached::Changes](https://github.com/rails/rails/blob/d9749bebf64d26f9afb467ee7bad124ba38ad68d/activestorage/lib/active_storage/attached/changes.rb) interface instead? 🤔

**Comment by intrip** [comment]
> This approach seems reasonable to me though. What happens for `has_many_attached`?

Good point! Right now `has_many_attached` is not covered, if record is `nil` it will raise `NoMethodError: undefined method 'purge' for #<ActiveStorage::Attached::Many:0x0000561374d53490>`; I didn't touch it (yet) because I wasn't sure if we should fix it in this PR or we need to open a new one: what do you suggest?

File: activestorage/lib/active_storage/attached.rb (hunk 1 above)
Comment (intrip) [reply activestorage/lib/active_storage/attached.rb:20]: I understand your feeling, I'm just not sure how we could do it: we need to reset the changes which weren't being applied yet (because we are purging the attachment); how can make changes reset themselves?

In https://github.com/rails/rails/blob/d9749bebf64d26f9afb467ee7bad124ba38ad68d/activestorage/lib/active_storage/attached/model.rb#L196-L212 we have already some logic to manipulate attachments, you think adding this logic here is more consistent?

**Comment by intrip** [comment]
@zzak thank you for the review! I've answered your questions, could you please check ? 🙇

File: activestorage/lib/active_storage/attached.rb (hunk 1 above)
Comment (zzak) [reply activestorage/lib/active_storage/attached.rb:20]: @intrip Somehow I missed this, yeah I'm not sure the best place but I was just calling it out incase there was any better ideas. At least it's easy to refactor later as long as the API is private? 🙏

Comment (intrip) [reply activestorage/lib/active_storage/attached.rb:20]: @zzak Indeed: method visibility allows easy refactoring later on, if you agree I'd keep this change as it is for now.

**Comment by intrip** [comment]
@zzak what's your take about https://github.com/rails/rails/pull/42256#issuecomment-844963368 ? I don't mind either handling it here or in a new PR

**Comment by zzak** [comment]
@intrip Let's make sure this is the correct approach before applying it to `has_many_attached`. Perhaps we can lean on @pixeltrix here for some feedback :pray:

Once this one is merged tho, feel free to open a new PR unless otherwise!

File: activestorage/lib/active_storage/attached.rb (hunk 1 above)
Comment (pixeltrix) [reply activestorage/lib/active_storage/attached.rb:20]: The `attachment_changes` api is definitely a weak spot - if you want to create a validator that checks an image before it's uploaded to S3 or whatever then you end up having to [reach deep inside some private apis][1] 😬 

I'd like to expose that in a better way but that's for a different PR - I think this is fine for the moment.

[1]: https://github.com/alphagov/e-petitions/blob/master/app/validators/image_validator.rb#L20-L39

File: activestorage/app/models/active_storage/blob.rb [hunk 2]
```diff
@@ -293,8 +293,9 @@ def delete
   # blobs. Note, though, that deleting the file off the service will initiate an HTTP connection to the service, which may
   # be slow or prevented, so you should not use this method inside a transaction or in callbacks. Use #purge_later instead.
   def purge
+    previously_persisted = persisted?
     destroy
-    delete
+    delete if previously_persisted
```
Comment (pixeltrix) [inline activestorage/app/models/active_storage/blob.rb:298]: I think this could be an Active Record method - we have `previously_new_record?` for example. However let's do that in a different PR.

**Review by pixeltrix — APPROVED** [review]

**Comment by pixeltrix** [comment]
@intrip can you add a CHANGELOG entry, please.

Regarding `has_many_attached` - would you prefer to do it in this PR or open a new one?

File: activestorage/app/models/active_storage/blob.rb (hunk 2 above)
Comment (intrip) [reply activestorage/app/models/active_storage/blob.rb:298]: Good point, I'll make a follow up PR.

**Comment by intrip** [comment]
@pixeltrix thanks for the review!

CL entry added.

> Regarding `has_many_attached` - would you prefer to do it in this PR or open a new one?

I prefer to make a new PR

**Comment by zzak** [comment]
Thanks @intrip and @pixeltrix!! 💓
