### PR TITLE
Fix crash in `ActionController::TestCase` in rspec

### LINKED ISSUE #70: Getting "undefined local variable or method `executor_around_each_request'" after edge rails upgrade
This commit to "rails": https://github.com/rails/rails/commit/5046d1cce90e56e3dc7f42cb394bbd5e740163c8 appears to have affected the rails-controller-testing gem.
Steps to reproduce:
 1. Clone my repo, https://github.com/jasnow/show-me-the-foodedge .
 2. Run "rake" to see a clean run before change.
 3. Run "bundle" to get a new version of edge rails.
 4. Run "rake" again and see the following errors in this gist:
    * https://gist.github.com/jasnow/c1affdc4a7f6371743d164ac5deaae2a
    
  Thanks.

### PR DESCRIPTION
**Pull request by ghiculescu**
Fixes https://github.com/rails/rails-controller-testing/issues/70, which found a regression in https://github.com/rails/rails/pull/43734

### CODE REVIEW

File: actionpack/lib/action_controller/test_case.rb [hunk 1]
```diff
@@ -581,7 +581,7 @@ def setup_request(controller_class_name, action, parameters, session, flash, xhr
         end
 
         def wrap_execution(&block)
-          if executor_around_each_request && defined?(Rails.application) && Rails.application
+          if ActionController::TestCase.executor_around_each_request && defined?(Rails.application) && Rails.application
```
Comment (byroot) [inline actionpack/lib/action_controller/test_case.rb:584]: We should replace the `class_attribute` by a `singleton_class.attr_accessor`, there's no point having the extra inheritance code and instance accessor if we don't use it.

Comment (ghiculescu) [reply actionpack/lib/action_controller/test_case.rb:584]: Thanks, updated.

**Review by byroot — APPROVED** [review]

**Comment by ghiculescu** [comment]
Red build seems unrelated
