### PR TITLE
Frozen truncate

### LINKED ISSUE #36106: Truncate helper doesn't always return frozen string
### Steps to reproduce
```ruby
"foobar".truncate(6).frozen?
=> false
"foobar".truncate(5).frozen?
=> true
```

### Expected behavior
Strings returned from `truncate` (or any ActionView helper) should consistently return a frozen string.

### Actual behavior
When the string is not long enough to be truncated the original, unfrozen, string is returned. When it is long enough to be truncated a new frozen string is returned. 

### System configuration
**Rails version**: 5.2.3

**Ruby version**:  2.5.3

### PR DESCRIPTION
**Pull request by jordanthomas**
### Summary

Return from truncate is inconsistent. When the string is not long enough to be truncated an unfrozen string is returned. When it is long enough to be truncated a new frozen string is returned.

Fixes https://github.com/rails/rails/issues/36106.

### CODE REVIEW

File: activesupport/lib/active_support/core_ext/string/filters.rb [hunk 1]
```diff
@@ -64,7 +64,7 @@ def remove!(*patterns)
   #   'And they found that many people were sleeping better.'.truncate(25, omission: '... (continued)')
   #   # => "And they f... (continued)"
   def truncate(truncate_at, options = {})
-    return dup unless length > truncate_at
+    return dup.freeze unless length > truncate_at
```
Comment (rafaelfranca) [inline activesupport/lib/active_support/core_ext/string/filters.rb]: I think it should be the opposite, we should always return a non-frozen string. In the same way as `gsub` and `strip` don't. I believe it only return frozen strings because of the `frozen_string_literal` pragm in this file and because we are using interpolation before returning.

Comment (rafaelfranca) [reply activesupport/lib/active_support/core_ext/string/filters.rb]:
```
>> 'foo'.freeze.gsub('a', '').frozen?
=> false
>> 'foo'.freeze.gsub('o', '').frozen?
=> false
```

Comment (jordanthomas) [reply activesupport/lib/active_support/core_ext/string/filters.rb]: Ah right on, I think that's even more predictable. I wrongly interpreted that the `frozen_string_literal` thing was trying to ensure returns were frozen.

I'll swap it.

**Comment by rafaelfranca** [comment]
Thank you!
