### PR TITLE
Fixed odd behavior of inverse_of with multiple belongs_to to same class 

### LINKED ISSUE #35204: Odd behavior of inverse_of with multiple belongs_to to same class
### Steps to reproduce

```rb
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  ruby '2.5.3'

  gem 'activerecord', '5.2.2'
  gem 'sqlite3'
end

require 'active_record'
require 'logger'
require 'minitest/autorun'

ActiveRecord::Base.establish_connection(
  adapter: 'sqlite3',
  database: ':memory:'
)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :writer_id
    t.integer :user_id
  end

  create_table :users, force: true
end

class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :writer, class_name: 'User'
end

class User < ActiveRecord::Base
  has_one :post
end

class ExampleTest < Minitest::Test
  def setup
    @user = ::User.create!
    @post = ::Post.create!(writer: @user)
  end

  def test_association
    assert_nil @user.post
  end

  def test_save
    @user.save!
    assert_nil @post.user_id
  end
end
```

### Expected behavior

I can't judge whether `#test_association` should pass or not, but I think `#test_save` should pass.

### Actual behavior

```
-- create_table(:posts, {:force=>true})
D, [2019-02-09T12:28:28.801280 #89035] DEBUG -- :    (0.0ms)  DROP TABLE IF EXISTS "posts"
D, [2019-02-09T12:28:28.802074 #89035] DEBUG -- :    (0.6ms)  SELECT sqlite_version(*)
D, [2019-02-09T12:28:28.802439 #89035] DEBUG -- :    (0.3ms)  CREATE TABLE "posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "writer_id" integer, "user_id" integer)
   -> 0.0038s
-- create_table(:users, {:force=>true})
D, [2019-02-09T12:28:28.802753 #89035] DEBUG -- :    (0.0ms)  DROP TABLE IF EXISTS "users"
D, [2019-02-09T12:28:28.802999 #89035] DEBUG -- :    (0.1ms)  CREATE TABLE "users" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL)
   -> 0.0005s
D, [2019-02-09T12:28:28.820916 #89035] DEBUG -- :    (0.1ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)
D, [2019-02-09T12:28:28.828087 #89035] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.1ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", "environment"], ["LIMIT", 1]]
D, [2019-02-09T12:28:28.831514 #89035] DEBUG -- :    (0.1ms)  begin transaction
D, [2019-02-09T12:28:28.832293 #89035] DEBUG -- :   ActiveRecord::InternalMetadata Create (0.1ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "default_env"], ["created_at", "2019-02-09 03:28:28.831855"], ["updated_at", "2019-02-09 03:28:28.831855"]]
D, [2019-02-09T12:28:28.832491 #89035] DEBUG -- :    (0.1ms)  commit transaction
Run options: --seed 29796

# Running:

D, [2019-02-09T12:28:28.847826 #89035] DEBUG -- :    (0.0ms)  begin transaction
D, [2019-02-09T12:28:28.848247 #89035] DEBUG -- :   User Create (0.0ms)  INSERT INTO "users" DEFAULT VALUES
D, [2019-02-09T12:28:28.848486 #89035] DEBUG -- :    (0.0ms)  commit transaction
D, [2019-02-09T12:28:28.853539 #89035] DEBUG -- :    (0.0ms)  begin transaction
D, [2019-02-09T12:28:28.854115 #89035] DEBUG -- :   Post Create (0.1ms)  INSERT INTO "posts" ("writer_id") VALUES (?)  [["writer_id", 1]]
D, [2019-02-09T12:28:28.854290 #89035] DEBUG -- :    (0.0ms)  commit transaction
D, [2019-02-09T12:28:28.854459 #89035] DEBUG -- :    (0.0ms)  begin transaction
D, [2019-02-09T12:28:28.855129 #89035] DEBUG -- :   Post Update (0.1ms)  UPDATE "posts" SET "user_id" = ? WHERE "posts"."id" = ?  [["user_id", 1], ["id", 1]]
D, [2019-02-09T12:28:28.855316 #89035] DEBUG -- :    (0.0ms)  commit transaction
FD, [2019-02-09T12:28:28.855622 #89035] DEBUG -- :    (0.0ms)  begin transaction
D, [2019-02-09T12:28:28.855951 #89035] DEBUG -- :   User Create (0.0ms)  INSERT INTO "users" DEFAULT VALUES
D, [2019-02-09T12:28:28.856121 #89035] DEBUG -- :    (0.0ms)  commit transaction
D, [2019-02-09T12:28:28.856364 #89035] DEBUG -- :    (0.0ms)  begin transaction
D, [2019-02-09T12:28:28.856680 #89035] DEBUG -- :   Post Create (0.0ms)  INSERT INTO "posts" ("writer_id") VALUES (?)  [["writer_id", 2]]
D, [2019-02-09T12:28:28.856833 #89035] DEBUG -- :    (0.0ms)  commit transaction
F

Finished in 0.011394s, 175.5310 runs/s, 175.5310 assertions/s.

  1) Failure:
ExampleTest#test_save [/Users/r7kamura/Desktop/active_record_inverse_test.rb:53]:
Expected 1 to be nil.

  2) Failure:
ExampleTest#test_association [/Users/r7kamura/Desktop/active_record_inverse_test.rb:48]:
Expected #<Post id: 2, writer_id: 2, user_id: nil> to be nil.

2 runs, 2 assertions, 2 failures, 0 errors, 0 skips
```

### System configuration

**Rails version**: 5.2.2

**Ruby version**: 2.5.3p105

### PR DESCRIPTION
**Pull request by ktmouk**
Fix: #35204.

This PR added validation to `automatic_inverse_of` that foreign_keys are the same.

If class has multiple `belongs_to` to same class, `automatic_inverse_of` can find the wrong `inverse_name`.

```ruby
class Room < ActiveRecord::Base
  belongs_to :user
  belongs_to :owner, class_name: "User"
end

class User < ActiveRecord::Base
  has_one :room
  has_one :owned_room, class_name: "Room", foreign_key: "owner_id"
end

user = User.create!
owned_room = Room.create!(owner: user)

p user.room
```

The current `automatic_inverse_of` validates the `reflection` that found from associations.
However, its validation does not validate that foreign keys are the same.

so this issue can be fixed by adding a validation of foreign keys.

### CODE REVIEW

**Comment by kamipo** [comment]
As I said in the Slack, can you elaborate on the context bit more in the commit message?

I know the context that what is the cause and a way to prevent the issue, but it is preferable to share the context for other reviewers and future readers.

File: activerecord/test/models/user.rb [hunk 1]
```diff
@@ -10,6 +10,8 @@ class User < ActiveRecord::Base
     class_name: "Job",
     join_table: "jobs_pool"
 
+  has_one :room
+  has_one :owned_room, class_name: "Room", foreign_key: "owner_id"
```
Comment (kamipo) [inline activerecord/test/models/user.rb:14]: Let's remove the unused `owned_room` association.

Comment (kamipo) [reply activerecord/test/models/user.rb:14]: ah it is used in the line, nvm.

https://github.com/rails/rails/blob/1f969fc944bdeffc1518edd6e22b31680816ffea/activerecord/test/cases/associations/inverse_associations_test.rb#L98

File: activerecord/test/cases/associations/inverse_associations_test.rb [hunk 2]
```diff
@@ -85,6 +87,17 @@ def test_has_many_and_belongs_to_should_find_inverse_automatically_for_sti
...
+    user = User.create!
+    owned_room = Room.create!(owner: user)
+
+    assert_nil user.room
+    assert_nil owned_room.user
+
+    assert_equal user, owned_room.owner
+    assert_equal owned_room, user.owned_room
+  end
+
```
Comment (kamipo) [inline activerecord/test/cases/associations/inverse_associations_test.rb:100]: Can you also test `reflection.inverse_of`?

```ruby
  def test_has_one_and_belongs_to_with_custom_association_name_should_not_find_wrong_inverse_automatically
    user_reflection = Room.reflect_on_association(:user)
    owner_reflection = Room.reflect_on_association(:owner)
    room_reflection = User.reflect_on_association(:room)

    assert_predicate user_reflection, :has_inverse?
    assert_equal room_reflection, user_reflection.inverse_of

    assert_not_predicate owner_reflection, :has_inverse?
    assert_not_equal room_reflection, owner_reflection.inverse_of
  end
```

Comment (ktmouk) [reply activerecord/test/cases/associations/inverse_associations_test.rb:100]: Thanks, I added.

File: activerecord/CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,7 @@
+*   Fixed odd behavior of inverse_of with multiple belongs_to to same class #35204
```
Comment (kamipo) [inline activerecord/CHANGELOG.md:1]:
```suggestion
*   Fix odd behavior of inverse_of with multiple belongs_to to same class.

    Fixes #35204.
```

Ref https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#updating-the-changelog

**Comment by kamipo** [comment]
> ```ruby
> user = User.create!
> owned_room = Room.create!(owner: owned_room)
> ```

Typo s/owned_room/user/

```ruby
user = User.create!
owned_room = Room.create!(owner: user)
```

File: activerecord/CHANGELOG.md (hunk 3 above)
Comment (ktmouk) [reply activerecord/CHANGELOG.md]: Thank you. I fixed.

**Comment by kamipo** [comment]
Thank you and congrats for your first contribution 🎉

**Comment by ktmouk** [comment]
Thank you, too!
