### PR TITLE
Fix in_order_of for integer enums

### LINKED ISSUE #43317: ActiveRecord::QueryMethods#in_order_of not working as expected with Rails enum
### Steps to reproduce
We have a `User` model with `role` column as integer type. We have set `role` as enum in `User` model.

```ruby
class User < ApplicationRecord
  enum role: [:normal_user, :admin, :super_user]
end
```

When we use `in_order_of` for `role` column, the result is not ordered as per the provided sequence.

```irb
User.in_order_of(:role, %w[super_user normal_user admin])

User Load (0.3ms)  SELECT "users".* FROM "users" /* loading for inspect */ ORDER BY CASE "users"."role" WHEN 'super_user' THEN 1 WHEN 'normal_user' THEN 2 WHEN 'admin' THEN 3 ELSE 4 END ASC LIMIT ?  [["LIMIT", 11]]

 => #<ActiveRecord::Relation [#<User id: 1, email: "alkesh26@gmail.com", role: "normal_user">, #<User id: 2, email: "1alkesh26@gmail.com", role: "admin">, #<User id: 3, email: "2alkesh26@gmail.com", role: "super_user">]> 
```

But if `role` is of `string` data type the results are returned in expected sequence.

### Expected behavior

The results should be returned in the provided order

```irb
User.in_order_of(:role, %w[super_user normal_user admin])

User Load (0.3ms)  SELECT "users".* FROM "users" /* loading for inspect */ ORDER BY CASE "users"."role" WHEN 'super_user' THEN 1 WHEN 'normal_user' THEN 2 WHEN 'admin' THEN 3 ELSE 4 END ASC LIMIT ?  [["LIMIT", 11]]

 => #<ActiveRecord::Relation [#<User id: 3, email: "2alkesh26@gmail.com", role: "super_user">, #<User id: 1, email: "alkesh26@gmail.com", role: "normal_user">, #<User id: 2, email: "1alkesh26@gmail.com", role: "admin">]> 
```

### Actual behavior

Seems like `in_order_of` is not working for Rails enum based columns.

### System configuration

**Rails version**: 7.0.0.alpha

**Ruby version**: 2.7.2p137

### PR DESCRIPTION
**Pull request by alexandreruban**
Closes #43317

### Summary

Using `in_order_of` with enums stored as integers in the database doesn't work as expected: 

```rb
class User < ApplicationRecord
  enum role: [:normal_user, :admin, :super_user]
end

# Currently, this doesn't return the expected result
User.in_order_of(:role, %w[super_user normal_user admin])
```

This is because the strings "super_user", "normal_user" and "admin" are compared with integers in the database. To be able to compare those strings with the integers in the database, we need to convert the strings to match the integers in the database with `type_cast_for_database`.

### CODE REVIEW

File: activerecord/lib/active_record/relation/query_methods.rb [hunk 1]
```diff
@@ -432,6 +432,7 @@ def in_order_of(column, values)
       references = column_references([column])
       self.references_values |= references unless references.empty?
 
+      values = values.map { |value| type_caster.type_cast_for_database(column, value) }
```
Comment (intrip) [inline activerecord/lib/active_record/relation/query_methods.rb:435]: Minor: what about using `map!` instead? Should be a minor performance improvement

Comment (alexandreruban) [reply activerecord/lib/active_record/relation/query_methods.rb]: @intrip thank you very much for the review! 
I updated the PR to use `map!` instead of `map`.

File: activerecord/test/cases/relation/field_ordered_values_test.rb [hunk 2]
```diff
@@ -13,6 +14,22 @@ def test_in_order_of
     assert_equal(order, posts.map(&:id))
   end
 
+  def test_in_order_of_with_enums_values
+    order    = %w[written published proposed]
+    books    = Book.in_order_of(:status, order.dup)
+    expected = order.map { |status| Array.new(Book.where(status: status).count, status) }.flatten
```
Comment (p8) [inline activerecord/test/cases/relation/field_ordered_values_test.rb:20]: Without looking at the book fixtures, I think it's a bit difficult to understand what the value of `expected` is.
The names of the book fixtures won't help much either.
```suggestion
    expected = [books(,adwr), books(:rdr), books(:ddd)]
```

Maybe creating records instead could be clearer? 🤷

Comment (alexandreruban) [reply activerecord/test/cases/relation/field_ordered_values_test.rb]: @p8 thank you very much for your review! 
I updated the tests to make them more easy to understand (by creating my own data as you suggested).

File: activerecord/lib/active_record/relation/query_methods.rb [hunk 3]
```diff
@@ -432,6 +432,7 @@ def in_order_of(column, values)
       references = column_references([column])
       self.references_values |= references unless references.empty?
 
+      values.map! { |value| type_caster.type_cast_for_database(column, value) }
```
Comment (ghiculescu) [inline activerecord/lib/active_record/relation/query_methods.rb:435]: I'm not sure this should mutate the argument. It could be used for other things, and it results in odd `.dup` calls in your tests.

**Comment by ghiculescu** [comment]
Could you update the CHANGELOG?

File: activerecord/lib/active_record/relation/query_methods.rb (hunk 3 above)
Comment (alexandreruban) [reply activerecord/lib/active_record/relation/query_methods.rb]: @ghiculescu thank you very much for your review!
I agree that the `.dup` call in the tests is odd. I reverted the changes from `values.map!` to `values = values.map` and updated the CHANGELOG.

**Comment by alexandreruban** [comment]
@ghiculescu sorry for the silly question but what is the process when the tests are red but I don't think it's related to the current PR? Should I re run them to make them green?
