### PR TITLE
Make ActiveSupport::Logger Fiber-safe

### LINKED ISSUE #36752: Rails.logger is not fiber safe
similar to #20490

### Steps to reproduce

1. Change `Rails.logger.local_level` inside a Ruby Fiber
2. Check `Rails.logger.level` in another Fiber

Example code:
```rb
Rails.logger.level = 1
p "Main is debug? #{Rails.logger.debug?}"

Fiber.new {
  Rails.logger.local_level = 0
  p "Thread is debug? #{Rails.logger.debug?}"
}.resume

p "Main is debug? #{Rails.logger.debug?}"
```

### Expected behavior
Logger local level is changed only inside the Fiber

Expected output:
```
=> "Main is debug? false"
=> "Thread is debug? true"
=> "Main is debug? false"
```

### Actual behavior
Logger local level is changed for all Fibers in current Thread

Expected output:
```
=> "Main is debug? false"
=> "Thread is debug? true"
=> "Main is debug? true"
```

### System configuration
**Rails version**: 5.2.2.1

**Ruby version**: 2.6.2

This issue makes particular sense if you use a Rails application with a FiberPool ([rack-fiber_pool](https://github.com/alebsack/rack-fiber_pool)). Let's say you want to change log level at rutime for one request but not for all requests which run in the same app/thread.

Fibers have their own isolated container for `Thread.current[]` so why can't we make the Rails.logger set the local_level per Fiber and not per Thread?

Rails uses `Thread.current.__id__` in order to differentiate between Threads ([source code link](https://github.com/rails/rails/blob/5-2-stable/activesupport/lib/active_support/logger_thread_safe_level.rb#L14)).

`Fiber.current.__id__` is unique in new Threads too so can we just use `Fiber.current.__id__` there instead?

### PR DESCRIPTION
**Pull request by cmrd-senya**
### Summary

Use Fiber.current.__id__ in ActiveSupport::Logger#local_level= in order to make log level local to Ruby Fibers in addition to Threads.

Fixes #36752

### CODE REVIEW

File: activesupport/test/logger_test.rb [hunk 1]
```diff
@@ -258,6 +258,50 @@ def test_logger_level_local_thread_safety
...
+          another_fiber.resume
+          assert_level(Logger::DEBUG)
+        end
+      end
+
+      assert_level(Logger::INFO)
+    end.resume
+
+    assert_level(Logger::INFO)
+  end
```
Comment (ayanko) [inline activesupport/test/logger_test.rb]: We could also split and rename test_logger_level_local_thread_safety to
test_logger_level_local_thread_safety
test_logger_level_local_fiber_safety
to explicitly show that we test now two different contexts

File: activesupport/lib/active_support/logger_thread_safe_level.rb [hunk 2]
```diff
@@ -28,7 +29,7 @@ def after_initialize
     end
 
     def local_log_id
-      Thread.current.__id__
```
Comment (ayanko) [inline activesupport/lib/active_support/logger_thread_safe_level.rb]: Should we rename it to more general one?
`ActiveSupport::LoggerSafeLocalLevel`

Comment (rafaelfranca) [reply activesupport/lib/active_support/logger_thread_safe_level.rb]: No need to rename this module.
