### PR TITLE
Fix NumericData.average test on 2.6.0-dev

### LINKED ISSUE #34600: CalculationsTest#test_should_return_nil_as_average fails with Ruby 2.6.0
One of Active Record unit test have been failing with ruby-head at Travis CI.
I have not found which Ruby 2.6 change introduces this failure yet, let me report it first.

* The first failed one: https://travis-ci.org/rails/rails/builds/462532899
```
ruby 2.6.0dev (2018-12-02 trunk 66129) [x86_64-linux]
```

* The last successful one: https://travis-ci.org/rails/rails/builds/462285019
```
ruby 2.6.0dev (2018-12-01 trunk 66113) [x86_64-linux]
```

### Steps to reproduce
```ruby
$ cd activerecord
$ bundle exec ruby -w -Itest test/cases/calculations_test.rb -n test_should_return_nil_as_average
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
$ bundle exec ruby -w -Itest test/cases/calculations_test.rb -n test_should_return_nil_as_average
Using sqlite3
Run options: -n test_should_return_nil_as_average --seed 60743

# Running:

F

Failure:
CalculationsTest#test_should_return_nil_as_average [test/cases/calculations_test.rb:61]:
Expected 0.0 to be nil.


rails test test/cases/calculations_test.rb:60



Finished in 0.047892s, 20.8803 runs/s, 20.8803 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
$
```

### System configuration
**Rails version**:master branch

**Ruby version**:ruby 2.6.0dev (2018-12-03 trunk 66147) [x86_64-linux]

### PR DESCRIPTION
**Pull request by abdallahalsamman**
Fixes #34600 

### Summary

NumericData.average was returning nil on ruby versions <= ruby 2.6.0dev (2018-12-03 trunk 66154)

Now it returns 0.0 instead of nil

### CODE REVIEW

**Comment by kamipo** [comment]
Can you investigate why `NumericData.average` with Ruby 2.6 returns 0.0?

**Comment by evexoio** [comment]
@kamipo Sure, that's what I'm doing right now.

https://github.com/rails/rails/issues/34600#issuecomment-443649497

**Comment by evexoio** [comment]
@kamipo This should be the commit that caused this issue. https://github.com/ruby/ruby/commit/a0e438cd3c28d2eaf4efa18243d5b6edafa14d88#diff-6b866d482baf2bdfd8433893fb1f6d36R144

What's the right action to take right now?

File: activerecord/test/cases/calculations_test.rb [hunk 1]
```diff
@@ -58,7 +58,7 @@ def test_should_return_integer_average_if_db_returns_such
   end
 
   def test_should_return_nil_as_average
-    assert_nil NumericData.average(:bank_balance)
```
Comment (kamipo) [inline activerecord/test/cases/calculations_test.rb]: This assertion actually would be failed without Ruby 2.6.0 if bigdecimal 1.4.0.pre.20181130a is used.

https://github.com/rails/rails/blob/e7717ec7a09ca83f92a9819303f7a93e038a2679/activerecord/lib/active_record/relation/calculations.rb#L400-L405

How about checking `nil.respond_to?(:to_d)`?

```diff
--- a/activerecord/test/cases/calculations_test.rb
+++ b/activerecord/test/cases/calculations_test.rb
@@ -57,8 +57,12 @@ def test_should_return_integer_average_if_db_returns_such
     assert_equal 3, value
   end
 
-  def test_should_return_nil_as_average
-    assert_nil NumericData.average(:bank_balance)
+  def test_should_return_nil_to_d_as_average
+    if nil.respond_to?(:to_d)
+      assert_equal BigDecimal(0), NumericData.average(:bank_balance)
+    else
+      assert_nil NumericData.average(:bank_balance)
+    end
   end
 
   def test_should_get_maximum_of_field
```

Comment (evexoio) [reply activerecord/test/cases/calculations_test.rb]: Makes sense, Thanks for helping out 🙌

**Comment by rafaelfranca** [comment]
I think this should still return `nil`. Can someone fix it?

**Comment by albertoalmagro** [comment]
I'm on it @rafaelfranca
