### PR TITLE
Prevent autosave association with has_one defined on child class

### LINKED ISSUE #51280: Unnecessary auto save is triggered for polymorphic has_one defined in child class using single-table inheritance
### Steps to reproduce

This bug is directly related to https://github.com/rails/rails/issues/44986.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :pictures, force: true do |t|
    t.references :imageable, polymorphic: true
  end

  create_table :employees, force: true do |t|
    t.string :type
    t.string :name
  end
end

class Picture < ActiveRecord::Base

  belongs_to :imageable, polymorphic: true, optional: true

  after_save :count_saves

  def count_saves
    @count ||= 0
    @count += 1
  end

end

class Employee < ActiveRecord::Base

end

class CaliforniaEmployee < Employee

  has_one :picture, as: :imageable

end

class ArizonaEmployee < Employee

  has_one :picture, as: :imageable

end

class BugTest < Minitest::Test

  def test_association_not_saved_on_update
    picture = Picture.create!

    cali_employee = CaliforniaEmployee.create!(name: "Cali", picture: picture)

    cali_employee.update!(name: "Cali Fornia")

    assert_equal "Employee", picture.imageable_type
    assert_equal cali_employee.id, picture.imageable_id

    # Saves on create of picture and create of employee
    assert_equal 2, picture.instance_variable_get(:@count)
  end

  def test_association_saved_on_actual_model_change
    picture = Picture.create!

    CaliforniaEmployee.create!(name: "Cali", picture: picture)
    az_employee = ArizonaEmployee.create!(name: "Arizona")

    az_employee.update!(picture: picture)

    assert_equal "Employee", picture.imageable_type
    assert_equal az_employee.id, picture.imageable_id

    # Saves on create of picture, create of cali employee, and update to az employee
    assert_equal 3, picture.instance_variable_get(:@count)
  end

end
```

### Expected behavior

There is no reason to trigger a save on the Picture record when updating a field on CaliforniaEmployee, since the picture record is already correctly pointing at the existing Employee.

### Actual behavior

`inverse_polymorphic_association_changed?` is returning true for this use case causing a subsequent autosave to be triggered on Picture, leading to a failure in both test cases:

```
Failure:
BugTest#test_association_not_saved_on_update [rails-issue.rb:73]:
Expected: 2
  Actual: 3

Failure:
BugTest#test_association_saved_on_actual_model_change [rails-issue.rb:85]:
Expected: 3
  Actual: 4
```

### Additional Context

This appears to specifically fail when the has_one is defined on a child class using Single-table Inheritance. If the `has_one` in the test case above is moved up to the `Employee` model, then the expectation will pass.

The issue appears to be here: https://github.com/rails/rails/blob/83702d64c80637cc0debc3917c3419d327f8ee1b/activerecord/lib/active_record/autosave_association.rb#L495-L497.

That currently reads the class for the record from the `foreign_type` and then attempts to convert it to the right class for polymorphic relationships, but I believe this is unnecessary, since it already would have been converted to the correct type when set.

Instead `reflection.active_record` should actually be updated to use the `polymorphic_name` otherwise we risk looking at the wrong model name that would be ultimately saved.

Updating line 497 to this gets these test cases passing for me:

```
reflection.active_record.polymorphic_name != class_name
```

### System configuration
**Rails version**: 7.1.3.2, main

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by dfritsch**
### Motivation / Background

Adjusts the logic in inverse_polymorphic_association_changed? to determine if a has_one association's polymorphic association should autosave the associated record for a type change.

Previously this would see the type as changed every time if the has_one is defined on a child class, since the polymorphic relationship saves the parent class as the *_type value. The new check resolves the correct class name to avoid these extra saves.

Fixes #51280

### Detail

Also confirmed that the new test fails without the code change:

```
Failure:
TestAutosaveAssociationOnAHasOneAssociation#test_should_not_saved_for_unchanged_sti_type_on_polymorphic_association [test/cases/autosave_association_test.rb:1652]:
Expected: 2
  Actual: 3


bin/rails test test/cases/autosave_association_test.rb:1620
```

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by dfritsch** [comment]
Just wanted to check in and see if there is anything else I should be doing on this PR. The build failure seems like a runtime issue, but I'm not sure if I have the power to rerun things?

File: activerecord/lib/active_record/autosave_association.rb [hunk 1]
```diff
@@ -517,7 +517,7 @@ def inverse_polymorphic_association_changed?(reflection, record)
         return false unless reflection.inverse_of&.polymorphic?
 
         class_name = record._read_attribute(reflection.inverse_of.foreign_type)
-        reflection.active_record != record.class.polymorphic_class_for(class_name)
+        reflection.active_record.polymorphic_name != class_name
```
Comment (byroot) [inline activerecord/lib/active_record/autosave_association.rb:530]: Hum, `polymorhpic_class_for` handles the `store_full_class_name` setting. I wonder if this may have an impact here.

Comment (byroot) [reply activerecord/lib/active_record/autosave_association.rb:530]: I think the proper fix might actually be to call `.to_s` on the return of `record.class.polymorphic_class_for(class_name)`.

Comment (byroot) [reply activerecord/lib/active_record/autosave_association.rb:530]: Nevermind.

**Review by byroot — APPROVED** [review]

**Comment by byroot** [comment]
Backported to `8-0-stable` and `7-2-stable`.
