### PR TITLE
Fix enum losing attribute type cast.

### LINKED ISSUE #39897: Using non-integer enum types should still be read
### Steps to reproduce

```ruby
rozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "mysql2", username: "rails", database: "activerecord_unittest")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.column :state, "TINYINT(1)"
  end
end

class Post < ActiveRecord::Base
  attribute :unread, :integer
  enum state: {
         start: 0,
         middle: 1,
         finish: 2
       }
end

class BugTest < Minitest::Test
  def test_association_stuff
    p = Post.create(state: :middle)

    assert_equal "middle", p.state # FAILS WITH p.state => nil
  end
end
```

Behavior changed with: https://github.com/rails/rails/pull/39820

Specifically changing

```
decorate_attribute_type(attr, :enum) do |subtype|
```
to
```
attribute(attr, **default) do |subtype|
```

CC: @kamipo 

### Expected behavior
The enum should be read and cast to the correct value

### Actual behavior
The column is always nil

### System configuration
**Rails version**: edge

**Ruby version**: 2.7

### PR DESCRIPTION
**Pull request by tgxworld**
Resolves https://github.com/rails/rails/issues/39897

### CODE REVIEW

**Comment by tgxworld** [comment]
@kamipo Can you review this for me? 

cc @eileencodes @HParker

File: activerecord/lib/active_record/enum.rb [hunk 1]
```diff
@@ -182,7 +182,13 @@ def enum(definitions)
         detect_enum_conflict!(name, "#{name}=")
 
         attr = attribute_alias?(name) ? attribute_alias(name) : name
+        type, options = attributes_to_define_after_schema_loads[attr]
+
         attribute(attr, **default) do |subtype|
+          if type && !type.is_a?(Proc)
+            subtype = _lookup_cast_type(attr, type, options)
+          end
```
Comment (tgxworld) [inline activerecord/lib/active_record/enum.rb:190]: This is similar to https://github.com/rails/rails/blob/71c8a89edd663dd21231f333ddb09b41bf94be37/activerecord/lib/active_record/attribute_methods/serialization.rb#L73-L78

**Comment by tgxworld** [comment]
Thank you for the review @kamipo 👍
