### PR TITLE
Skip persisted through targets when autosaving collection associations

### LINKED ISSUE #54176: Loading `has_many :through` association in a `before_save` callback creates duplicate records
### Steps to reproduce

```ruby
# typed: true
# frozen_string_literal: true
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", github: "rails/rails", branch: "main"
  
  gem "sqlite3"
end
require "active_record/railtie"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults(Rails::VERSION::STRING.to_f)
  config.eager_load = false
  config.logger = Logger.new($stdout)
  config.secret_key_base = "secret_key_base"
end

Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table "appointments", force: true do |t|
    t.integer  "doctor_id"
    t.integer  "patient_id"
  end

  create_table "doctors", force: true do |t|
    t.string   "name"
  end

  create_table "patients", force: true do |t|
    t.string   "name"
  end
end

class Doctor < ActiveRecord::Base
  has_many :appointments
  has_many :patients, through: :appointments

  before_save do
    appointments.map(&:patient) + patients
  end
end

class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :doctors, through: :appointments
end

class Appointment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :patient
end

class BugTest < ActiveSupport::TestCase
  def test_association_stuff
    doctor = Doctor.new(name: "Dr Dolittle")
    appointment = doctor.appointments.build
    patient = appointment.build_patient(name: "John")

    doctor.save!

    assert_equal(1, doctor.appointments.size)
  end
end
```

### Expected behavior
1 appointment is created.

### Actual behavior
2 appointments are created. Without the `before_save`, 1 appointment is being created.

After a bit of digging, this is what I believe is happening:
1. https://github.com/rails/rails/pull/51114 fixed an issue where through association targets are not always properly set. `AutosaveAssociation#save_collection_association` calls `ActiveRecord::AutosaveAssociation#associated_records_to_validate_or_save` to get the associated records to save, which gets them via the [target method on the association](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/autosave_association.rb#L300). So, previously, the target was not set and no records were returned, and thus no records were saved. But now, the target is set properly and the method does return a record (the patient) to save, which leads to another appointment being created.
2. With the `before_save`, it sets the has many through association. Without the before save doing this, `AutosaveAssociation#save_collection_association` would be a no-op for the has many through association between `Doctor` and `Patient`. This is because [`association_instance_get(reflection.name)`](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/autosave_association.rb#L416) would return `nil` and [`ActiveRecord::AutosaveAssociation#associated_records_to_validate_or_save`](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/autosave_association.rb#L426) would never be run. 

cc: @joshuay03

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

Fixes https://github.com/rails/rails/issues/54176

### Detail

I recommend reading through the issue linked above, as well as the comments, which provide all the context behind this change.

To summarize all that, I recently merged a bunch of patches (linked below) that ensure that new through records built by the middle record are also set on the through parent when the through association reader is called. That has resulted in duplicate autosaving of collection through records, first by the through parent, then by the direct parent i.e. the middle record. The former is new behaviour as that collection would previously be empty.

This fix ensures that we only autosave new/changed through records when saving the through parent, as the through record would already have been autosaved by the direct parent, and we don't want to autosave the persisted (i.e. not new/changed) through record again. This was pretty much the behavior before my patches, its just that now we need to specifically exclude previously unset records, while also ensuring we continue to autosave other manually built/updated (`changed_for_autosave?`) through records.

- https://github.com/rails/rails/pull/51114
- https://github.com/rails/rails/pull/53869
- https://github.com/rails/rails/pull/53957
- https://github.com/rails/rails/pull/54046

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/test/cases/autosave_association_test.rb [hunk 1]
```diff
@@ -1147,6 +1150,34 @@ def test_autosave_new_record_with_after_create_callback_and_habtm_association
...
+  end
+
+  def test_autosave_new_record_with_hmt_and_middle_record_built_by_parent
+    family = FamilyLoadingMiddleAndThroughRecordsBeforeSave.new
+    family_tree = family.family_trees.build
+    member = family_tree.build_member
+    family.save!
+    family.reload
+
+    assert_equal 1, family.family_trees.size
```
Comment (joshuay03) [inline activerecord/test/cases/autosave_association_test.rb:1167]: On main:
Screenshot 2025-01-14 at 7 11 34 pm

File: activerecord/test/cases/autosave_association_test.rb [hunk 2]
```diff
@@ -1147,6 +1150,34 @@ def test_autosave_new_record_with_after_create_callback_and_habtm_association
...
+  end
+
+  def test_autosave_new_record_with_hmt_and_middle_record_built_by_through_record
+    family = FamilyLoadingMiddleAndThroughRecordsBeforeSave.new
+    member = family.members.build
+    family_tree = family.family_trees.build(member: member)
+    family.save!
+    family.reload
+
+    assert_equal 1, family.family_trees.size
```
Comment (joshuay03) [inline activerecord/test/cases/autosave_association_test.rb:1178]: On main:
Screenshot 2025-01-14 at 7 12 18 pm

**Review by adrianna-chang-shopify — COMMENTED** [review]
Thanks for taking a look at this -- I've verified this fixes the issues on our end! 🙇‍♀️

**Review by gmcgibbon — APPROVED** [review]

**Comment by gmcgibbon** [comment]
Thanks!
