### PR TITLE
Round some numbers more humanely

### LINKED ISSUE #20869: ActionView::Helpers::NumberHelper.number_to_human formatting incorrectly on rounding
When rounding numbers up to the next significant digit, `number_to_human` is incorrectly formatting with the wrong value + unit quantifier:

```
number_to_human(1_000_000) # => 1 Million (Correct)
number_to_human(999_999) # => 1000 Thousand (Incorrect, expected '1 Million')
```

```
number_to_human(1_000_000_000) # => 1 Billion (Correct)
number_to_human(999_999_999) # => 1000 Million (Incorrect, expected '1 Billion')
```

This happens when the number is high enough to warrant rounding up to the next unit quantifier (ie. Thousands => Millions, Millions => Billions)

##### Steps to reproduce
```
$ rails new test_app
$ cd test_app && rails c
irb(main):001:0> ActionView::Base.new.number_to_human(999999999)
=> "1000 Million"
```

##### Versions
Rails: `4.2.3`
Ruby: `2.2.2p95`
OSX: `10.10.4`

### PR DESCRIPTION
**Pull request by maxjacobson**
Fix #20869

### CODE REVIEW

File: activesupport/test/number_helper_test.rb [hunk 1]
```diff
@@ -293,6 +293,8 @@ def test_number_to_human
           assert_equal '1.2346 Million', number_helper.number_to_human(1234567, :precision => 4, :significant => false)
           assert_equal '1,2 Million', number_helper.number_to_human(1234567, :precision => 1, :significant => false, :separator => ',')
           assert_equal '1 Million', number_helper.number_to_human(1234567, :precision => 0, :significant => true, :separator => ',') #significant forced to false
+          assert_equal '1 Million', number_helper.number_to_human(999999)
+          assert_equal '1 Billion', number_helper.number_to_human(999999999)
```
Comment (chirag7jain) [inline activesupport/test/number_helper_test.rb]: check your changelog

Comment (maxjacobson) [inline activesupport/test/number_helper_test.rb]: I think the assertion is correct and the changelog entry could have been written better

Comment (chirag7jain) [inline activesupport/test/number_helper_test.rb]: You have written - changelog - Fix `number_to_human` rounding 999999999 to "1000 Million" instead of "1 Billion".

test - assert_equal '1 Billion', number_helper.number_to_human(999999999)  -- shouldn't it be 1000 million

Comment (maxjacobson) [inline activesupport/test/number_helper_test.rb]: Yea, apologies, I didn't word the changelog well.

The current behavior on master is that it returns "1000 Million". I think that's a bug, and it should return "1 Billion".

File: activesupport/CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,10 @@
+*   Fix `number_to_human` so it produces "1 Billion" from 999999999 isntead of
+    "1000 Million".
```
Comment (sliuu) [inline activesupport/CHANGELOG.md]: *instead

**Comment by nickcherryjiggz** [comment]
:ship:

**Comment by sgrif** [comment]
Agreed the changelog is confusing. I'm going to merge manually and update the changelog to something which is a bit less confusing.

**Comment by sgrif** [comment]
Thanks! 
image

**Comment by maxjacobson** [comment]
@sgrif niiiice

**Comment by goddamnhippie** [comment]
This doesn't work for spanish (1 Billón == 1_000_000_000_000), would that have to be specified on a locale file?

**Comment by jaimerave** [comment]
This only apply to the US, in Colombia 1 billion = 1.000.000.000.000

**Comment by sgrif** [comment]
None of this is new as a result of this pull request, which fixed a bug in the existing behavior. This should be directed at the Rails core mailing list.
