### PR TITLE
Fix `SELECT COUNT` queries when rendering ActiveRecord collections

### LINKED ISSUE #40837: Rendering ActiveRecord collections as non-derived partials results in `SELECT COUNT` query
When a partial is derived from a collection, `collection.map` is called first which loads the relation.

https://github.com/rails/rails/blob/v6.1.0/actionview/lib/action_view/renderer/collection_renderer.rb#L119

However, when it's non-derived, `collection.size` gets called first, which results in the `SELECT COUNT` query.

https://github.com/rails/rails/blob/v6.1.0/actionview/lib/action_view/renderer/collection_renderer.rb#L147

The collection should probably be loaded with a `to_a` somewhere.

/cc @tenderlove 

### Steps to reproduce

Render a collection using a non-derived partial:

```rb
<%= render collection: Post.all, partial: "post" %>
```

This results in the following queries:

```sql
SELECT COUNT(*) FROM "posts"
CACHE  SELECT COUNT(*) FROM "posts"
Post Load SELECT "posts".* FROM "posts"
```

Rendering a collection with a derived partial:

```rb
<%= render Post.all %>
```

This results in the following queries:

```sql
Post Load SELECT "posts".* FROM "posts"
```

### Expected behavior

Rendering an ActiveRecord collection with a non-derived partial should not execute a `SELECT COUNT` query.

### System configuration
**Rails version**:

6.1.0

**Ruby version**:

2.7.1

### PR DESCRIPTION
**Pull request by aar0nr**
Fixes #40837

When rendering collections, calling `size` when the collection is an
ActiveRecord relation causes unwanted `SELECT COUNT(*)` queries. This
change ensures the collection is loaded before getting the size.

### CODE REVIEW

File: actionview/lib/action_view/renderer/collection_renderer.rb [hunk 1]
```diff
@@ -144,7 +144,7 @@ def render_collection(collection, view, path, template, layout, block)
           "render_collection.action_view",
           identifier: identifier,
           layout: layout && layout.virtual_path,
-          count: collection.size
+          count: collection.to_a.size
```
Comment (rafaelfranca) [inline actionview/lib/action_view/renderer/collection_renderer.rb:147]: Would not this load the collection too early making the preload that happens inside `PreloadCollectionIterator` not happen anymore?

Comment (aar0nr) [reply actionview/lib/action_view/renderer/collection_renderer.rb:147]: No because the `PreloadCollectionIterator` has already been instantiated, and preloading has been [disabled](https://github.com/rails/rails/blob/v6.1.0/actionview/lib/action_view/renderer/collection_renderer.rb#L73) (the relation hasn't been loaded at that point). Then, `to_a` will load the relation without preloading. Finally, the `PreloadCollectionIterator` will [handle the preloading of the associations](https://github.com/rails/rails/blob/v6.1.0/actionview/lib/action_view/renderer/collection_renderer.rb#L83).

Comment (rafaelfranca) [reply actionview/lib/action_view/renderer/collection_renderer.rb:147]: Great! Thank you for investigating.

**Comment by rafaelfranca** [comment]
Is it possible to write test to make sure someone doesn't remove that `to_a` from there?

**Comment by aar0nr** [comment]
I added a test. I couldn't think of a better way to test this other than asserting on the queries during a render. Kind of hard to test since it's a complete side-effect.

I've never contributed to Rails before, so I'm not sure if I'm following the correct patterns or not, so let me know if I'm doing it wrong. There seems to be many different styles accumulated over the years. 🤣

File: actionview/test/activerecord/partial_rendering_query_test.rb [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+
+class PartialRenderingQueryTest < ActiveRecordTestCase
+  def setup
+    @view = ActionView::Base
+      .with_empty_template_cache
+      .with_view_paths(ActionController::Base.view_paths, {})
+
+    @queries = []
+
+    ActiveSupport::Notifications.subscribe("sql.active_record") do |*, payload|
```
Comment (natematykiewicz) [inline actionview/test/activerecord/partial_rendering_query_test.rb:13]: You should unsubscribe to the notification after this test, or use a `subscribed` block to automatically unsubscribe. Otherwise, all subsequent tests will push to this array.

File: actionview/lib/action_view/renderer/collection_renderer.rb (hunk 1 above)
Comment (kamipo) [reply actionview/lib/action_view/renderer/collection_renderer.rb:147]: How about using `collection.length` instead?

```suggestion
          count: collection.length
```

`to_a` for relation will dup extra records.

https://github.com/rails/rails/blob/9c120d7559b964d2a619a75faa9776b8f03c5cf7/activerecord/lib/active_record/relation.rb#L243-L246

Comment (aar0nr) [reply actionview/lib/action_view/renderer/collection_renderer.rb]: @kamipo Good suggestion, thanks. The only catch was I had to put a check for the length method because there are tests that rely on passing collections that don't respond to `length`, so I delegate back to `size` if `length` isn't available.

File: actionview/test/activerecord/partial_rendering_query_test.rb (hunk 2 above)
Comment (natematykiewicz) [inline actionview/test/activerecord/partial_rendering_query_test.rb:13]: Looking at some of the other tests, you'll want to store the subscription in a variable, so you can unsubscribe at the end of the test. Right now, all subsequent tests are pushing their SQL into this array (a memory leak in the test suite).

For example: https://github.com/rails/rails/blob/f130c780f6c6cb09ad68ac89de9af90102fa2d80/activerecord/test/cases/instrumentation_test.rb#L22

Comment (aar0nr) [reply actionview/test/activerecord/partial_rendering_query_test.rb]: @natematykiewicz Thanks, I've done as you suggested.
