### PR TITLE
Fix: ensure PostgreSQL enum types can contain commas

### LINKED ISSUE #54140: Ensure enum types with commas are dumped correctly
### Steps to reproduce
```ruby
#!/usr/bin/env ruby

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", github: "rails/rails", branch: "main"
  gem "pg"
end

require "active_record/railtie"
require "minitest/autorun"

ENV["DATABASE_URL"] = "postgresql://localhost/ar_enum_test"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
  config.secret_key_base = "secret_key_base"
  config.active_record.schema_format = :ruby
end
Rails.application.initialize!
ActiveRecord::Tasks::DatabaseTasks.create_current

ActiveRecord::Schema.define do
  create_enum :funky_enum, ["Yes", "Yes, with reservations", "No"]
end

class BugTest < ActiveSupport::TestCase
  def test_funky_enum_gets_dumped_correctly
    output = StringIO.new

    ActiveRecord::SchemaDumper.dump(ActiveRecord::Base.connection_pool, output)

    # It gets dumped as:
    # create_enum \"funky_enum\", [\"Yes\", \"Yes\", \" but with reservations\", \"No\"]

    assert_includes output.string, "create_enum \"funky_enum\", [\"Yes\", \"Yes, but with reservations\", \"No\"]"
  end
end

```

### Expected behavior
The `SchemaDumper` should dump enums correctly, allowing for commas in their values.

### Actual behavior
The `SchemaDumper` splits enum types on commas, corrupting `schema.rb` on every schema dump.

### System configuration
**Rails version**: 8.0.1

**Ruby version**: 3.2.1

### PR DESCRIPTION
**Pull request by arthurhess**
### Motivation / Background

PostgreSQL enums can have commas in their values, but this is not supported by the current implementation in ActiveRecord::ConnectionAdapters::PostgreSQL::SchemaDumper

This PR fixes this by updating `PostgreSQLAdapter.enum_types` to use PG `array_agg` instead of `string_agg`, effectively passing an array to the SchemaDumper and removing the need for splitting on commas.

### Detail

Fixes #54140

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [X] Tests are added or updated if you fix a bug or add a feature.
* [X] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by arthurhess** [comment]
Now, considering e23207e, I wonder if this is expected behavior and if this is not a bug fix. I couldn't find it in the docs, though.

File: activerecord/test/cases/schema_dumper_test.rb [hunk 1]
```diff
@@ -902,6 +902,28 @@ def down
...
+    end
+
+    migration.migrate(:up)
+    output = dump_all_table_schema
+
+    assert_match %r{create_enum "enum_with_comma", \["value1", "value,2", "value3"\]}, output
+  ensure
+    migration.migrate(:down) if migration
+    $stdout = original
+  end if current_adapter?(:PostgreSQLAdapter)
```
Comment (fatkodima) [inline activerecord/test/cases/schema_dumper_test.rb:926]:
```suggestion
  if current_adapter?(:PostgreSQLAdapter)
    def test_schema_dump_keeps_enum_intact_if_it_contains_comma
      original, $stdout = $stdout, StringIO.new

      migration = Class.new(ActiveRecord::Migration::Current) do
        def up
          create_enum "enum_with_comma", ["value1", "value,2", "value3"]
        end

        def down
          drop_enum "enum_with_comma"
        end
      end

      migration.migrate(:up)
      output = dump_all_table_schema

      assert_includes output, 'create_enum "enum_with_comma", ["value1", "value,2", "value3"]'
    ensure
      migration.migrate(:down) if migration
      $stdout = original
    end
  end
```

**Review by fatkodima — COMMENTED** [review]
Now the `enum_types` returns for values an array instead of the string, as before. This is kinda a breaking change.

Also, make sure to always keep PRs in a single commit via force push.

File: activerecord/test/cases/schema_dumper_test.rb (hunk 1 above)
Comment (arthurhess) [reply activerecord/test/cases/schema_dumper_test.rb:926]: Right. Unfortunately, this raises `ActiveSupport::RaiseWarnings::WarningError: Test is missing assertions: (...)` when testing a different adapter.

**Comment by arthurhess** [comment]
> Now the enum_types returns for values an array instead of the string, as before. This is kinda a breaking change.

Ugh. This method is so specific that I thought it was private API.

File: activerecord/test/cases/schema_dumper_test.rb (hunk 1 above)
Comment (fatkodima) [reply activerecord/test/cases/schema_dumper_test.rb:926]: Even with `if current_adapter?` at the beginning, as suggested?

Comment (arthurhess) [reply activerecord/test/cases/schema_dumper_test.rb:926]: I see. Either way works, but I chose to follow the style I found in the file, [as suggested](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#follow-the-coding-conventions).

> Follow the conventions in the source you see used already.

File: activerecord/test/cases/schema_dumper_test.rb [hunk 2]
```diff
@@ -902,6 +902,28 @@ def down
       $stdout = original
     end
   end
+
+  def test_schema_dump_keeps_enum_intact_if_it_contains_comma
+    original, $stdout = $stdout, StringIO.new
```
Comment (tenderlove) [inline activerecord/test/cases/schema_dumper_test.rb:907]: Should we use [`capture_io`](https://github.com/minitest/minitest/blob/d84437f874b42be1c3d46b81640904144fc7dac4/lib/minitest/assertions.rb#L538)?

File: activerecord/test/cases/schema_dumper_test.rb (hunk 1 above)
Comment (fatkodima) [reply activerecord/test/cases/schema_dumper_test.rb:926]: Line 313, for example. Before marking the conversation as resolved, take a look at other changes I suggested in the diff.

File: activerecord/test/cases/schema_dumper_test.rb (hunk 2 above)
Comment (arthurhess) [reply activerecord/test/cases/schema_dumper_test.rb:907]: I used it to suppress the output of the up and down migrations, as I saw in other examples. The output of the dump is already being captured with `capture_io`.

Maybe it's better to remove this line entirely?

File: activerecord/test/cases/schema_dumper_test.rb (hunk 1 above)
Comment (arthurhess) [reply activerecord/test/cases/schema_dumper_test.rb:926]: I appreciate your willingness to help @fatkodima, I really do, but I think I'm missing your point. In this codebase, is nesting methods in an if statement preferred over writing it inline?

Comment (arthurhess) [reply activerecord/test/cases/schema_dumper_test.rb]: Nevermind, I just saw another block for the PG adapter and put it in there. It does look cleaner. Let me know what you think. Thanks.

File: activerecord/test/cases/schema_dumper_test.rb [hunk 3]
```diff
@@ -433,6 +433,28 @@ def test_schema_dump_include_limit_for_float4_field
...
+          drop_enum "enum_with_comma"
+        end
+      end
+
+      migration.migrate(:up)
+      output = dump_all_table_schema
+
+      assert_match %r{create_enum "enum_with_comma", \["value1", "value,2", "value3"\]}, output
+    ensure
+      migration.migrate(:down) if migration
```
Comment (fatkodima) [inline activerecord/test/cases/schema_dumper_test.rb:455]: Already suggested in the previous snippet - without regexp looks simpler and `migration` can't be nil
```suggestion
      assert_includes output, 'create_enum "enum_with_comma", ["value1", "value,2", "value3"]', output
    ensure
      migration.migrate(:down)
```

**Comment by chaadow** [comment]
Yeah I can confirm this broke `database_consistency` here : https://github.com/djezzzl/database_consistency/blob/f7d0162672192f051a245590cbbc4dc0b333f12f/lib/database_consistency/checkers/column_checkers/enum_value_checker.rb#L41
