### PR TITLE
Fixes #41521, ActiveModel::Dirty fails on to_json

### LINKED ISSUE #41521: ActiveModel::Dirty fails on to_json
### Steps to reproduce
I have this `Person` class
```
class Person
    include ActiveModel::Dirty

    define_attribute_methods :name

    def initialize
      @name = nil
    end

    def name
      @name
    end

    def name=(val)
      name_will_change! unless val == @name
      @name = val
    end

    def save
      # do persistence work

      changes_applied
    end

    def reload!
      # get the values from the persistence layer

      clear_changes_information
    end

    def rollback!
      restore_attributes
    end
  end
```
`person = Person.new() => #<Person:0x00007f9f50718120 @name=nil>`
`person.to_json => "{'name': null}"`
`person.name = 'test'`
```
perons.to_json => 
SystemStackError: stack level too deep
from /Users/USER/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.5/lib/active_support/core_ext/object/json.rb:172:in `each'
```
### Expected behavior
`person.to_json => "{'name': 'test'}"`

### Actual behavior
```
perons.to_json => 
SystemStackError: stack level too deep
from /Users/USER/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.5/lib/active_support/core_ext/object/json.rb:172:in `each'
```
### System configuration
**Rails version**:
rails 6.0.3.5
**Ruby version**:
ruby-2.7.0

(FYI `to_yaml` works fine)

### PR DESCRIPTION
**Pull request by anilmaurya**
### Summary

This PR fixes #41521

ActiveModel::Dirty adds `mutation_from_database` attribute which contains `ActiveModel::ForcedMutationTracker` object.
`ActiveModel::ForcedMutationTracker` has attributes pointing to ActiveModel::Dirty class which again has `ActiveModel::ForcedMutationTracker`. This causes to_json to  stuck in forever loop.

Example:
```
class Person
  include ActiveModel::Dirty

  define_attribute_methods :name

  def initialize
    @name = nil
    @profile = Profile.new(20, "21/21/21")
  end

  def name
    @name
  end

  def name=(val)
    name_will_change! unless val == @name
    @name = val
  end

  def save
    # do persistence work

    changes_applied
  end

  def reload!
    # get the values from the persistence layer

    clear_changes_information
  end

  def rollback!
    restore_attributes
  end
end

class Profile
  attr_accessor :age, :dob
  
  def initialize(age, dob)
    @age = age
    @dob = dob
  end
end

person = Person.new()
person.name = 'test'

p person
{"name"=>"test",
 "profile"=>#<Profile:0x00007fc9ef5d4bf0 @age=20, @dob="21/21/21">,
 "mutations_from_database"=>
  #<ActiveModel::ForcedMutationTracker:0x00007fc9ef5d4ad8
   @attributes=
    #<Person:0x00007fc9ef5d4c40
     @mutations_from_database=#<ActiveModel::ForcedMutationTracker:0x00007fc9ef5d4ad8 ...>,
     @name="test",
     @profile=#<Profile:0x00007fc9ef5d4bf0 @age=20, @dob="21/21/21">>,
   @finalized_changes=nil,
   @forced_changes={"name"=>nil}>}


```
This PR excludes "mutations_from_database" when invoking to_json on ActiveModel::Dirty

### CODE REVIEW

File: activemodel/lib/active_model/dirty.rb [hunk 1]
```diff
@@ -139,6 +139,11 @@ def initialize_dup(other) # :nodoc:
       @mutations_from_database = nil
     end
 
+    def as_json(options = {})
```
Comment (gklsan) [inline activemodel/lib/active_model/dirty.rb:142]: Documentation is missing!!

**Review by gklsan — CHANGES_REQUESTED** [review]

File: activemodel/lib/active_model/dirty.rb (hunk 1 above)
Comment (anilmaurya) [reply activemodel/lib/active_model/dirty.rb:144]: Added Documentation, please review again.

**Review by gklsan — APPROVED** [review]
LGTM

File: activemodel/test/cases/dirty_test.rb [hunk 2]
```diff
@@ -237,4 +238,9 @@ def save
   test "model can be dup-ed without Attributes" do
     assert @model.dup
   end
+
+  test "to_json should work on model" do
+   @model.name = "Dmitry"
+   assert_equal @model.to_json, "{\"name\":\"Dmitry\",\"color\":null,\"size\":null,\"status\":\"initialized\"}"
```
Comment (zzak) [inline activemodel/test/cases/dirty_test.rb:244]: @anilmaurya How does this test fail before the patch?

Comment (anilmaurya) [reply activemodel/test/cases/dirty_test.rb:244]: Test fails with error

```
/home/vagrant/rails/activesupport/lib/active_support/core_ext/object/json.rb:174:in `as_json'
    /home/vagrant/rails/activesupport/lib/active_support/core_ext/object/json.rb:58:in `as_json'
    /home/vagrant/rails/activesupport/lib/active_support/core_ext/object/json.rb:175:in `block in as_json'
    /home/vagrant/rails/activesupport/lib/active_support/core_ext/object/json.rb:174:in `each'
    /home/vagrant/rails/activesupport/lib/active_support/core_ext/object/json.rb:174:in `as_json'
    /home/vagrant/rails/activesupport/lib/active_support/core_ext/object/json.rb:58:in `as_json'
    /home/vagrant/rails/activesupport/lib/active_support/json/encoding.rb:35:in `encode'
    /home/vagrant/rails/activesupport/lib/active_support/json/encoding.rb:22:in `encode'
    /home/vagrant/rails/activesupport/lib/active_support/core_ext/object/json.rb:43:in `to_json'
    /home/vagrant/rails/activemodel/test/cases/dirty_test.rb:244:in `block in <class:DirtyTest>'
```

**Review by zzak — APPROVED** [review]

File: activemodel/lib/active_model/dirty.rb [hunk 3]
```diff
@@ -139,6 +139,13 @@ def initialize_dup(other) # :nodoc:
       @mutations_from_database = nil
     end
 
+    # Exclude +mutations_from_database+ attribute from json as it lead to
+    # recursive call to as_json method
+    def as_json(options = {})
+      options[:except] = "mutations_from_database"
```
Comment (zzak) [inline activemodel/lib/active_model/dirty.rb:145]: @anilmaurya Do any of the other options cause recursion issues?

**Comment by zzak** [comment]
@anilmaurya Could you also add a CHANGELOG and rebase? :bow:

File: activemodel/lib/active_model/dirty.rb (hunk 3 above)
Comment (anilmaurya) [reply activemodel/lib/active_model/dirty.rb:145]: No, as far as I know.

**Comment by anilmaurya** [comment]
> @anilmaurya Could you also add a CHANGELOG and rebase? 🙇

Yes, will do that tonight.

**Comment by anilmaurya** [comment]
> @anilmaurya Could you also add a CHANGELOG and rebase? 🙇

Done @zzak

File: activemodel/CHANGELOG.md [hunk 4]
```diff
@@ -1,3 +1,9 @@
+*   Fix `to_json` for `ActiveModel::Dirty` object
```
Comment (rafaelfranca) [inline activemodel/CHANGELOG.md:1]:
```suggestion
*   Fix `to_json` for `ActiveModel::Dirty` object.
```

File: activemodel/CHANGELOG.md [hunk 5]
```diff
@@ -1,3 +1,9 @@
...
+    
+    Exclude +mutations_from_database+ attribute from json as it lead to recursion
```
Comment (rafaelfranca) [inline activemodel/CHANGELOG.md:3]:
```suggestion
    Exclude +mutations_from_database+ attribute from json as it lead to recursion.
```

File: activemodel/lib/active_model/dirty.rb [hunk 6]
```diff
@@ -140,6 +140,13 @@ def initialize_dup(other) # :nodoc:
       @mutations_from_database = nil
     end
 
+    # Exclude +mutations_from_database+ attribute from json as it lead to
+    # recursive call to as_json method
```
Comment (rafaelfranca) [inline activemodel/lib/active_model/dirty.rb:144]:
```suggestion
```

We don't add comments to code, only documentation. This is already covered by the commit message.

File: activemodel/lib/active_model/dirty.rb [hunk 7]
```diff
@@ -140,6 +140,13 @@ def initialize_dup(other) # :nodoc:
...
+    def as_json(options = {})
```
Comment (rafaelfranca) [inline activemodel/lib/active_model/dirty.rb:145]:
```suggestion
    def as_json(options = {}) # :nodoc:
```

File: activemodel/test/cases/dirty_test.rb (hunk 2 above)
Comment (rafaelfranca) [inline activemodel/test/cases/dirty_test.rb:244]:
```suggestion
   assert_equal "{\"name\":\"Dmitry\",\"color\":null,\"size\":null,\"status\":\"initialized\"}", @model.to_json
```

**Review by rafaelfranca — CHANGES_REQUESTED** [review]
A few comments. When you finish, can you squash all commits in one please? Thank you.

**Comment by anilmaurya** [comment]
> A few comments. When you finish, can you squash all commits in one please? Thank you.

Done @rafaelfranca

File: activemodel/test/cases/dirty_test.rb [hunk 8]
```diff
@@ -237,4 +238,9 @@ def save
   test "model can be dup-ed without Attributes" do
     assert @model.dup
   end
+
+  test "to_json should work on model" do
+   @model.name = "Dmitry"
+   assert_equal "{\"name\":\"Dmitry\",\"color\":null,\"size\":null,\"status\":\"initialized\"}", @model.to_json
+ end
```
Comment (kamipo) [inline activemodel/test/cases/dirty_test.rb:245]:
```suggestion
    @model.name = "Dmitry"
    assert_equal "{\"name\":\"Dmitry\",\"color\":null,\"size\":null,\"status\":\"initialized\"}", @model.to_json
  end
```

File: activemodel/test/cases/dirty_test.rb [hunk 9]
```diff
@@ -237,4 +238,9 @@ def save
   test "model can be dup-ed without Attributes" do
     assert @model.dup
   end
+
+  test "to_json should work on model" do
+    @model.name = "Dmitry"
+    assert_equal "{\"name\":\"Dmitry\",\"color\":null,\"size\":null,\"status\":\"initialized\"}", @model.to_json
```
Comment (kamipo) [inline activemodel/test/cases/dirty_test.rb:244]: Should also test `to_json` with `:except` option.

Comment (anilmaurya) [reply activemodel/test/cases/dirty_test.rb:244]: Done @kamipo , please review again.
