### PR TITLE
round before calculating exponent in number_to_human_converter

### LINKED ISSUE #25664: number_to_human tries to use larger units than provided
### Steps to reproduce

```
number_to_human(1_000_000, units: { unit: 'meter', thousand: 'kilometer' })
```

This should return "1000 kilometer", as it did in Rails 4.x. Instead it returns "1" (i.e. no unit) in Rails 5

Runnable gist: https://gist.github.com/daniel-rikowski/3fb29004560fae2ab7c08ddc2df8c0ef
### Expected behavior

When `number_to_human` receives a list of units it should only use the units given and not larger ones.
### Actual behavior

Instead it tries to use the best machting unit, even if it wasn't provided. For a hash parameter this results in an empty unit, for a I18n scope parameter this results in a lookup exception.
### System configuration

**Rails version**: 5.0
### Remarks
- I want to use this to display distances on a map, where even large numbers like "6371 km" are more favorable than "6 million meter" or "6 thousand kilometer"
- I think the cause was PR https://github.com/rails/rails/pull/20872: First `calculate_exponent(units)` finds the largest exponent matching the given units, but then the rounding loop (lines 23-26) increases the exponent where it possibly exceeds the given units and their exponents.

### PR DESCRIPTION
**Pull request by mjhoy**
### Summary

Fixes #25664

Introduced in: https://github.com/rails/rails/commit/597a9276671f5d7884a0ee1a617656dd5ee4b0ea

Other PRs:
- 1: https://github.com/rails/rails/pull/25742
- 2: https://github.com/rails/rails/pull/26433

I think the real problem is that `NumberToHumanConverter` does not round before calling `calculate_exponent`, which led to the confusing [workaround](https://github.com/rails/rails/commit/597a9276671f5d7884a0ee1a617656dd5ee4b0ea) that introduced #25664 in the first place.

Unfortunately the code to round in `NumberToRoundedConverter` (with options for precision and significant digits) is tied to formatting it as a string. The motivation for adding a new class `RoundingHelper` is to extract this part of the code so it can reused in `NumberToHumanConverter`.

I am fairly new to the Rails codebase, so I'm unsure of where to put the helper class. Should it go in its own file? Should it be a module?

There is also the messy fact that `NumberToHumanConverter` is rounding twice. I suppose the formatting code could be extracted as well.

### CODE REVIEW

File: activesupport/test/number_helper_test.rb [hunk 1]
```diff
@@ -344,6 +344,9 @@ def test_number_to_human_with_custom_units
           #Spaces are stripped from the resulting string
           assert_equal "4", number_helper.number_to_human(4, units: { unit: "", ten: "tens " })
           assert_equal "4.5  tens", number_helper.number_to_human(45, units: { unit: "", ten: " tens   " })
+
+          #Uses only the provided units and does not try to use larger ones
+          assert_equal "1000 kilometers", number_helper.number_to_human(1_000_000, units: {unit: "meter", thousand: "kilometers"})
```
Comment (bquorning) [inline activesupport/test/number_helper_test.rb]: May I suggest you also add these examples (in the “gangster” group, right after line 341):
```rb
assert_equal "1000 hundred bucks", number_helper.number_to_human(100_000, :units => gangster)
assert_equal "1 thousand quids", number_helper.number_to_human(999_999, :units => gangster)
assert_equal "1 thousand quids", number_helper.number_to_human(1_000_000, :units => gangster)
```
The first 2 fail on master, exposing another bug introduced by #20872. All 3 pass using your code.

File: activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb [hunk 2]
```diff
@@ -16,16 +15,74 @@ def convert
           else
             @number = number.to_d
           end
+        end
+      end
 
-          if options.delete(:significant) && precision > 0
```
Comment (bquorning) [inline activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb]: I really like that you’ve removed these `delete` calls :heart:

File: activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb [hunk 3]
```diff
@@ -1,12 +1,11 @@
...
-      def convert
-        precision = options.delete :precision
+    class RoundingHelper # :nodoc:
+      attr_reader :number, :options
 
+      def initialize(number, options)
+        @number = number
+        @options = options
         if precision
           case number
```
Comment (bquorning) [inline activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb]: Good call on moving this part into a constructor. It also means that line 7 (`@number = number`) can be moved to an `else` clause to the `if precision` call.

File: activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb [hunk 4]
```diff
@@ -16,16 +15,74 @@ def convert
...
             rounded_number = number.round(precision)
             rounded_number = rounded_number.to_i if precision == 0 && rounded_number.finite?
             rounded_number = rounded_number.abs if rounded_number.zero? # prevent showing negative zeros
           end
+        else
+          rounded_number = number
+        end
+
+        rounded_number
+      end
```
Comment (bquorning) [inline activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb]: I’m wondering if this method reads better without the `rounded_number` local variables. What do you think?
```rb
def round
  if precision
    if options[:significant] && precision > 0
      round_significant
    else
      rounded_number = number.round(precision)
      rounded_number = rounded_number.to_i if precision == 0 && rounded_number.finite?
      rounded_number = rounded_number.abs if rounded_number.zero? # prevent showing negative zeros
      rounded_number
    end
  else
    number
  end
end
```

**Review by bquorning — COMMENTED** [review]
In my opinion, since `RoundedHelper` is being used by other classes than `NumberToRoundedConverter`, it should be in its own file (activesupport/lib/active_support/number_helper/rounding_helper.rb). Probably it should be autoloaded from activesupport/lib/active_support/number_helper.rb like the other number converter files are.

I’m thinking, perhaps this PR should be 2 commits: 1) extracting `RoundedHelper`, and 2) fixing the bug in `NumberToHumanConverter`.

In the Rails codebase, the convention is to indent all code following the `private` keyword with 2 extra spaces, and to have a whitespace inside `{` and `}` in hashes – which is why the build fails ;-)

File: activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb (hunk 4 above)
Comment (mjhoy) [inline activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb]: The nested ifs confuse me a little there, but perhaps just because I don't usually write my code like that.

Another idea I had was

```ruby
def round
  return number unless precision

  if options[:significant] && precision > 0
    round_significant
  else
    rounded_number = number.round(precision)
    rounded_number = rounded_number.to_i if precision == 0 && rounded_number.finite?
    rounded_number = rounded_number.abs if rounded_number.zero? # prevent showing negative zeros
    rounded_number
  end
end
```

Comment (bquorning) [inline activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb]: The nested `if`s are indeed confusing. Extracting the `else` part to a method may make the rest acceptable. 

I'm also thinking: we have a special case for 'if precision` in both this method and the initializer. Should we have an e.g. `NoPrecisionRounder.new(number)` to return in this case?

Comment (mjhoy) [inline activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb]: @bquorning I'm wondering if the method `round` (or maybe `rounded`) should just be an accessor to an instance variable set up in the initializer, where the rounding happens, so there is just one big if statement there.

**Comment by mjhoy** [comment]
@bquorning OK, see what you think, I think I got to all your comments, and I tried to get rid of the duplicated branching on `precision` as well.

File: activesupport/lib/active_support/number_helper/rounding_helper.rb [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+          when Rational
+            @number = BigDecimal(number, digit_count(number.to_i) + precision)
+          else
+            @number = number.to_d
+          end
+          @number = round_with_precision
+        else
+          @number = number
+        end
+      end
```
Comment (bquorning) [inline activesupport/lib/active_support/number_helper/rounding_helper.rb]: This has become quite a complex initializer. I actually think it would be good to keep the *rounding* functionality separate from the initializer (I know I said the opposite in the previous comment – sorry). It’s also confusing that after the initialization, `@number` is a `BigDecimal` if precision is on, but it may be a string or an integer or whatever if precision if off.

File: activesupport/lib/active_support/number_helper/rounding_helper.rb [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+
+      def digit_count(number)
+        number.zero? ? 1 : (Math.log10(absolute_number(number)) + 1).floor
```
Comment (bquorning) [inline activesupport/lib/active_support/number_helper/rounding_helper.rb]: I think a guard clause `return 1 if number.zero?` would be ok here.

File: activesupport/lib/active_support/number_helper/rounding_helper.rb [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+          else
+            rounded_number = number.round(precision)
+            rounded_number = rounded_number.to_i if precision == 0 && rounded_number.finite?
+            rounded_number = rounded_number.abs if rounded_number.zero? # prevent showing negative zeros
+            rounded_number
+          end
+        end
+
+        def round_significant
+          if zero?
```
Comment (bquorning) [inline activesupport/lib/active_support/number_helper/rounding_helper.rb]: `return 0 if zero?`?

File: activesupport/lib/active_support/number_helper/rounding_helper.rb [hunk 8]
```diff
@@ -0,0 +1,66 @@
...
+
+      private
+        def round_with_precision
+          if options[:significant] && precision > 0
+            round_significant
+          else
+            rounded_number = number.round(precision)
+            rounded_number = rounded_number.to_i if precision == 0 && rounded_number.finite?
+            rounded_number = rounded_number.abs if rounded_number.zero? # prevent showing negative zeros
+            rounded_number
```
Comment (bquorning) [inline activesupport/lib/active_support/number_helper/rounding_helper.rb]: Should we extract lines 32–35 to a method?

**Comment by mjhoy** [comment]
thanks @bquorning -- quick question about making changes, rails bot seems to suggest adding more commits as the review happens, and then squashing at the end?

**Comment by eileencodes** [comment]
@mjhoy it's up to you. If you want to fixup/squash as you commit that's fine too. We prefer a squash at the end because it doesn't make sense to merge 3 commits for a single change. GitHub allows us to squash before merge too so it's really not a big deal :smile:

**Comment by mjhoy** [comment]
@eileencodes I prefer squashing as I go, but the bot seemed to suggest that reviewers wouldn't be able to follow as well if I did. Did the new review system fixed that?

**Comment by eileencodes** [comment]
The new review system does make it easier to see what's changed. For larger PR's (big features or yak shaves) it makes more sense to add individual commits.

But I'm assigned this PR and I almost never look at individual commits and usually look at the PR as a whole so I don't mind if you add more commits.

**Comment by mjhoy** [comment]
@bquorning Thanks for the input, I definitely see what you mean about the initializer. I restructured the class a bit, removing the `@number` instance variable altogether, and broke out some (hopefully more descriptive) methods. I also removed the `zero?` method as it had a needless `respond_to` check (the number at that point is guaranteed to be a BigDecimal). I took out the one line `calculate_rounded_number(multiplier)` method which I think had a confusing name, and moved the code to the `round_significant` method, as it only applies to calculating the rounded number with respect to significant digits.

**Comment by bquorning** [comment]
👍 I like this solution.

File: activesupport/lib/active_support/number_helper/rounding_helper.rb [hunk 9]
```diff
@@ -0,0 +1,64 @@
...
+      def digit_count(number)
+        return 1 if number.zero?
+        (Math.log10(absolute_number(number)) + 1).floor
+      end
+
+      private
+        def round_without_significant(number)
+          number = number.round(precision)
+          number = number.to_i if precision == 0 && number.finite?
+          number = number.abs if number.zero?
```
Comment (bquorning) [inline activesupport/lib/active_support/number_helper/rounding_helper.rb]: Perhaps `number = 0 if number.zero?` is easier to understand?

Either way, I think this line is obscure enough that you should keep the `prevent showing negative zeros` comment.

Comment (mjhoy) [inline activesupport/lib/active_support/number_helper/rounding_helper.rb]: Agreed, I removed that unintentionally, whoops!

File: activesupport/lib/active_support/number_helper/rounding_helper.rb [hunk 10]
```diff
@@ -0,0 +1,64 @@
...
+          return 0 if number.zero?
+          digits = digit_count(number)
+          multiplier = 10 ** (digits - precision)
+          (number / BigDecimal.new(multiplier.to_f.to_s)).round * multiplier
+        end
+
+        def convert_to_decimal(number)
+          case number
+          when Float, String
+            number = BigDecimal(number.to_s)
```
Comment (bquorning) [inline activesupport/lib/active_support/number_helper/rounding_helper.rb]: Ping @mjhoy

**Comment by mjhoy** [comment]
@esparta Thanks, I agree. However I would like to know whether this solution is even likely to be merged before working on it more. ( @eileencodes ?)

**Comment by eileencodes** [comment]
Out of the 3 PR's fixing the mentioned issue this one seems to best address concerns of "what are the edge cases we're not thinking of beyond the one reported issue".

I have a few style changes I'd like to see but before I ask you to do more work @mjhoy I want to see what @matthewd thinks about the implementation since he disagreed with the original. This is also a blocker for 5.0.1. Let me know what you think @matthewd.

**Comment by bquorning** [comment]
I’d love to see this PR moving forward again.

@mjhoy Would you please rebase on master? There’s just one easy-to-resolve conflict caused by fe1f4b2ad5.

@matthewd Perhaps you overlooked the request from Eileen earlier. Would you have time to take a look at this PR, please?

**Comment by mjhoy** [comment]
@bquorning Sure.

**Comment by daniel-rikowski** [comment]
Is there a chance to have this in Rails 5.1? 🤞 The failed tests don't seem to be related to the code changes...

**Comment by bquorning** [comment]
> Perhaps you overlooked the request from Eileen earlier. Would you have time to take a look at this PR, please?

Ping @matthewd

**Review by matthewd — APPROVED** [review]
TBH I'd prefer it if we weren't introducing another object allocation, but this looks great!

**Comment by eileencodes** [comment]
Backported to 5.1 in 55c3e1ff956c53f4a3b85325982102f9fd889269

**Comment by bquorning** [comment]
Thank you @eileencodes . FYI the previous attempts at solving this issue #25742 and #26433 can be closed, too.
