### PR TITLE
Clarify intentions around method redefinitions

### LINKED ISSUE #14021: class_attribute not thread-safe
I'm encountering this issue in a production application with the Paper Trail gem. (See https://github.com/airblade/paper_trail/issues/307). It's running in JRuby/TorqueBox under Rails 3.2.16. The implementation in Rails 4 looks nearly identical.

If I understand the [implementation](https://github.com/rails/rails/blob/v3.2.16/activesupport/lib/active_support/core_ext/class/attribute.rb#L80) of `class_attribute` correctly, every time you set the class attribute, it undefines the existing singleton method and defines a new singleton method that simply returns the new value.

In my app, several threads are setting the class attribute of different instances of the same class. This causes the singleton method of the class to be undefined in one thread, and then another thread raises a `NameError` because the method has been temporarily removed.

It sounds like an unlikely scenario, but this is happening a couple times a day in a relatively low-traffic app.

`class_attribute` is pretty complex, so I'm not sure how to fix this while retaining the existing functionality. Any advice would be appreciated. Perhaps putting a mutex around the code that undefines/defines would be best?

### LINKED ISSUE #26758: Attributes created using class_attribute are not thread-safe
We are building a large Rails application and ran into concurrency issues. Digging into them, we found that using class_attribute causes a non-thread-safe configuration. With this I don't mean that class_attribute isn't thread-safe - please let me elaborate in more detail:

In issue #14021 @dwbutler initially stated that class_attribute is not thread-safe but then precised: "every time you set the class attribute, it undefines the existing singleton method and defines a new singleton method that simply returns the new value." @thedarkone commented: "setting class_attribute at the class level is only supposed to be done at/during boot time". The discussion was later abandoned.
We think that there **two different concepts** here, getting mixed up: One being that the method class_attribute isn't thread-safe and needs to be done in a single-threaded boot phase. However, even with a clean design respecting this, the program is not going to work, because the **setter method generated by class_attribute is not thread-safe either**.

A working counterexample can be found in https://gist.github.com/kalsan/cdecebb51830075af7bfdc058a4de1a1

The code mentionned above works fine on Ruby version: 2.3.1, Ruby engine: ruby, ActiveSupport: 5.0.0.1
However, on Ruby version: 2.3.1, Ruby engine: jruby, ActiveSupport: 5.1.0.alpha, the program fails. On my system, failure occurs sometimes with 1'000 and always with 10'000 threads. The error is the following:
`NameError: Undefined method setting for 'MyClass'`

This is not surprising, since the following code is in [class_attribute, line 89](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/class/attribute.rb#L89):

```
89: remove_possible_method(name)
90: define_method(name) { val }
```

This code is **not called in the boot phase, but as the attribute :setting is accessed in the multi-threaded running phase.** Clearly it is not thread-safe: if an access takes place in between those two lines, the symbol _setting_ is undefined, which explains the above failure.

Again, this does not happen in cruby, possibly due to the GIL story ( [link](http://stackoverflow.com/questions/24953702/multi-threading-in-ruby-mri), "But what about the GIL?"). Also, putting a global lock (just for testing!) around the two lines mentioned above makes the problem disappear (of course this ugly workaround is not a solution, but it indicates that the problem is located in there indeed).

Of course, we could use an alternative method in our application for our own calls. However, since Rails itself heavily uses class_attribute, the question arises whether or not Rails is thread-safe on jruby. We have been investigating a lot and found traces indicating that data races might even take place in rails itself.

Feedback and discussion would be much appreciated. We would like to find out how deep this behavour goes and what parts of Rails are affected.

### PR DESCRIPTION
**Pull request by matthewd**
Don't use remove_method or remove_possible_method just before a new definition: at best the purpose is unclear, and at worst it creates a race condition.

Instead, prefer redefine_method when practical, and silence_redefinition_of_method otherwise.

By eliminating the remove+define pattern, this fixes #26758, fixes #14021.

### CODE REVIEW

File: activesupport/lib/active_support/core_ext/module/remove_method.rb [hunk 1]
```diff
@@ -1,3 +1,5 @@
+require "active_support/core_ext/module/redefine_method"
```
Comment (matthewd) [inline activesupport/lib/active_support/core_ext/module/remove_method.rb]: Compatibility, because that file now contains `redefine_method`, which was previously in here.

File: activesupport/lib/active_support/core_ext/module/redefine_method.rb [hunk 2]
```diff
@@ -0,0 +1,38 @@
+class Module
+  # Marks the named method as intended to be redefined, if it exists.
+  # Suppresses the Ruby method redefinition warning. Prefer
+  # #redefine_method where possible.
+  def silence_redefinition_of_method(method)
+    if method_defined?(method) || private_method_defined?(method)
+      # This suppresses the "method redefined" warning; the self-alias
+      # looks odd, but means we don't need to generate a unique name
+      alias_method method, method
```
Comment (matthewd) [inline activesupport/lib/active_support/core_ext/module/redefine_method.rb]: The validity of this self-alias pattern is potentially an open question: https://bugs.ruby-lang.org/issues/13574

But if we have to switch to a generated-name alternative, that's fine too.

**Review by kaspth — APPROVED** [review]
Dig the clarification 👍
