### PR TITLE
Use the current Rails->npm_version for package.json

### LINKED ISSUE #42012: Generated package.json file uses version constraints that may be too loose
### Steps to reproduce

Generate a new rails 6.0 app: `rails _6.0.3.6_ new sample_app`

### Expected behavior

I expected the app to install the `@rails/actioncable`, `@rails/activestorage`, and `@rails/ujs` javascript packages at the corresponding version `6.0.3-6`

### Actual behavior
The app installed the `@rails/actioncable`, `@rails/activestorage`, and `@rails/ujs` javascript packages at version `6.1.3`

### System configuration
**Rails version**: 6.0.3.6

**Ruby version**: any supported version

### More information

This happens because the [generated `package.json` file](https://github.com/rails/rails/blob/v6.0.3.6/railties/lib/rails/generators/rails/app/templates/package.json.tt) declares the dependencies with a loose version constraint:
```json
  "dependencies": {
    "@rails/actioncable": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
```

(`^6.0.0` will match the latest `6.x.y` version)

I don't think this has really been an issue so far since these packages haven't really had any significant changes. Thus, version 6.1 of the npm packages is likely compatible with a rails 6.0 server. But I wanted to bring this up because I'm not sure this behavior was desired/intentional. I know that rails only expects each framework gem (activerecord, activestorage, etc) to be compatible with the other framework gems of the same exact version, which simplifies maintenance. If that should extend to the npm packages, too, then we probably want to change the generated `package.json` to prevent this behavior.

### PR DESCRIPTION
**Pull request by zzak**
Fixes #42012.

This takes the [npm_version method from rails/release.rb](https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/tasks/release.rb#L26-L36) and just copies it.

We probably could refactor this to be DRY but it seems like `release.rb` doesn't call any Rails internals. :thinking:

### CODE REVIEW

**Comment by zzak** [comment]
I haven't tested this yet, and we may want to add a unit test -- but just writing down a PoC while it's fresh in my head

File: railties/lib/rails/generators/app_base.rb [hunk 1]
```diff
@@ -298,6 +298,10 @@ def rails_version_specifier(gem_version = Rails.gem_version)
         end
       end
 
+      def npm_version
```
Comment (zzak) [inline railties/lib/rails/generators/app_base.rb:301]: I'm not sure if this should be `:nodoc:` or `:doc:` but I guess we don't want to expose it as public API yet?

Also, I wasn't sure if we should add the origin of this method which has a much better description:
https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/tasks/release.rb#L26-L36

**Review by lfalcao — APPROVED** [review]

File: railties/lib/rails/generators/app_base.rb (hunk 1 above)
Comment (zzak) [reply railties/lib/rails/generators/app_base.rb:301]: Note to self: https://guides.rubyonrails.org/api_documentation_guidelines.html#method-visibility

It seems this whole class is [nodoc'd](https://edgeapi.rubyonrails.org/classes/Rails/Generators/AppBase.html) so probably adding these comments to the method won't make a difference.

Comment (zzak) [reply railties/lib/rails/generators/app_base.rb:311]: Fixed in 9080c8f5b5

**Comment by zzak** [comment]
Added test in 46e1b01 but I realized that if someone is using `--main` the version `7.0.0-alpha` is not yet released to npm and setup will probably fail 🤔 

One idea is to just pick `^6.0.0` if the `--main` flag is set 🤔

**Comment by lfalcao** [comment]
Doing this, in every Rails release we'll have to remember to change the generator to use the last available version at npm.

**Comment by zzak** [comment]
@lfalcao Can you explain what you mean?

My assumption was that this will only affect new apps using `$ rails new` and whatever version of version is installed will pin the package.json to use `Rails.version`. The problem I was describing is when that version doesn't have a matching version on npm.

**Comment by lfalcao** [comment]
I mean, in the future of `8.0.0-alpha` for example, using '--main' parameter will point to '^6.0.0'. So we'll always have to remember to update this base version.

File: railties/lib/rails/generators/rails/app/templates/package.json.tt [hunk 2]
```diff
@@ -2,10 +2,10 @@
   "name": "<%= app_name.underscore.dasherize %>",
   "private": true,
   "dependencies": {
-    "@rails/ujs": "^6.0.0"<% unless options[:skip_turbolinks] %>,
+    "@rails/ujs": "^<%= npm_version %>"<% unless options[:skip_turbolinks] %>,
```
Comment (ghiculescu) [inline railties/lib/rails/generators/rails/app/templates/package.json.tt:5]: What do you think about matching the exact version at the same time (as noted in https://github.com/rails/rails/issues/42012)?

```suggestion
    "@rails/ujs": "<%= npm_version %>"<% unless options[:skip_turbolinks] %>,
```

Comment (ghiculescu) [reply railties/lib/rails/generators/rails/app/templates/package.json.tt:5]: I think we should update the App Updater too. I can help with that if you like.

**Comment by zzak** [comment]
> I mean, in the future of 8.0.0-alpha for example, using '--main' parameter will point to '^6.0.0'. So we'll always have to remember to update this base version.

yeah or we could just ask `npm` for the latest version and use that 🤔 doesn't npm also support tags like `latest`?

File: railties/lib/rails/generators/rails/app/templates/package.json.tt (hunk 2 above)
Comment (zzak) [reply railties/lib/rails/generators/rails/app/templates/package.json.tt:5]: @ghiculescu Good idea! Feel free to commit to this branch or if you want to open another PR is fine w/ me too :bow:

I think removing the `^` is a good idea, also we can add a condition for `--main` to just use `latest` tag for that edge case.

Comment (ghiculescu) [reply railties/lib/rails/generators/rails/app/templates/package.json.tt:5]: I don’t have commit access, but if you give me access to your fork, can do.

Comment (zzak) [reply railties/lib/rails/generators/rails/app/templates/package.json.tt:5]: @ghiculescu done! 🙏

**Comment by lfalcao** [comment]
@zzak the problem of using always the latest is that you can break compatibility with older Rails versions - for example Rails 6 using latest package intended for Rails 8... :thinking: 

The best solution imho, would package.json point to the same version as the rails. 

Something like:
`
"dependencies": {
    "turbolinks": "git://github.com/turbolinks/turbolinks.git#main",
    "turbolinks": "git://github.com/turbolinks/turbolinks.git#v7.0.0"
}

**Comment by ghiculescu** [comment]
> update: maybe when using '--main' set the github url, then in the other cases use `Rails.version` 👀

Yes - this is what I was thinking too.

File: railties/test/generators/app_generator_test.rb [hunk 3]
```diff
@@ -537,7 +537,7 @@ def test_package_json_uses_current_version
     version = generator.send(:npm_version)
 
     assert_file "package.json" do |content|
-      assert_match(/"@rails\/ujs": "\^#{version}"/, content)
+      assert_match(/"@rails\/ujs": "#{version}"/, content)
```
Comment (zzak) [inline railties/test/generators/app_generator_test.rb:540]: @ghiculescu While we're here, how about adding tests for the skip options?

File: railties/lib/rails/generators/app_base.rb [hunk 4]
```diff
@@ -298,6 +298,20 @@ def rails_version_specifier(gem_version = Rails.gem_version)
...
+      # versioning system, so they must be transformed to "5.0.0-rc1" and "5.0.0-beta1-1" respectively.
+
+      # "5.0.1"     --> "5.0.1"
+      # "5.0.1.1"   --> "5.0.1-1" *
+      # "5.0.0.rc1" --> "5.0.0-rc1"
+      #
+      # * This makes it a prerelease. That's bad, but we haven't come up with
+      # a better solution at the moment.
+      def npm_version
+        Rails.version.gsub(/\./).with_index { |s, i| i >= 2 ? "-" : s }
```
Comment (zzak) [inline railties/lib/rails/generators/app_base.rb:312]: If we want to support `--main`, I think we need to do something like here:

https://github.com/rails/rails/blob/0f5201a756399911c3ce00f83047a1598240540a/railties/lib/rails/generators/app_base.rb#L268-L284

We may also want to support these other tags too :)

Comment (ghiculescu) [reply railties/lib/rails/generators/app_base.rb]: this'll get us started https://github.com/rails/rails/pull/42263/commits/b5593614aed68d311c39b4c97fd5103f62e7ffa4

**Comment by ghiculescu** [comment]
I've backpedalled on my idea about the App Updater. Instead I've added details to the upgrade guide. My thinking is:

- For new apps, if we are setting an exact package version in `package.json`, changing this is pretty easy for the user to do. Meanwhile, automating it seems hard.
- We already ask the user to change their Rails version in the `Gemfile`, so this isn't that much more of a stretch.
- We can always fix this in a future PR. The scope of this one is just to fix the [incorrectly loose constraints](https://github.com/rails/rails/issues/42012).

File: railties/lib/rails/generators/app_base.rb [hunk 5]
```diff
@@ -298,6 +298,40 @@ def rails_version_specifier(gem_version = Rails.gem_version)
...
+      #
+      # * This makes it a prerelease. That's bad, but we haven't come up with
+      # a better solution at the moment.
+      def npm_version
+        # TODO: support `options.dev?`
+
+        if options.edge? || options.main?
+          # TODO: ideally this would read from Github
+          # https://github.com/rails/rails/blob/main/actioncable/app/assets/javascripts/action_cable.js
+          # https://github.com/rails/rails/blob/main/activestorage/app/assets/javascripts/activestorage.js
```
Comment (ghiculescu) [inline railties/lib/rails/generators/app_base.rb:317]: Because https://github.com/rails/rails/blob/main/activestorage/package.json isn't a top level file - unlike https://github.com/turbolinks/turbolinks, or the examples in https://docs.npmjs.com/cli/v7/configuring-npm/package-json#git-urls-as-dependencies - I'm not sure how to point a gif ref to it.

**Review by ghiculescu — APPROVED** [review]
I'm pretty happy with this @zzak. What do you think?

File: railties/lib/rails/generators/app_base.rb (hunk 5 above)
Comment (ghiculescu) [reply railties/lib/rails/generators/app_base.rb:317]: `latest` is a bit of a compromise. I imagine someone who knows more about npm than me could make this work.

File: guides/source/upgrading_ruby_on_rails.md [hunk 6]
```diff
@@ -27,17 +37,18 @@ The process should go as follows:
...
-Rails generally stays close to the latest released Ruby version when it's released:
+1. Change the Rails version number in the `Gemfile` and run `bundle update`.
+2. Change the versions for Rails JavaScript packages in `package.json` and run `yarn install`.
+3. Run the [Update task](#the-update-task).
+4. Run your tests.
 
-* Rails 7 requires Ruby 2.7.0 or newer.
-* Rails 6 requires Ruby 2.5.0 or newer.
-* Rails 5 requires Ruby 2.2.2 or newer.
+You can find a list of all released Rails gems [here](https://rubygems.org/gems/rails/versions).
```
Comment (zzak) [inline guides/source/upgrading_ruby_on_rails.md:51]: Should we link to the npm packages too?

**Comment by zzak** [comment]
@ghiculescu This is looking good! I think using `latest` is a good compromise and better than the current behavior, we can always improve.

Would you mind adding a changelog and squashing our commits? 🙇 

Thanks so much for your work on this! 🎉

File: guides/source/upgrading_ruby_on_rails.md (hunk 6 above)
Comment (ghiculescu) [reply guides/source/upgrading_ruby_on_rails.md:51]: I thought about it but decided against it, as there's several pages and no one page that lists all of them. Didn't want to clutter this up or detract attention away from the gem, which is the main thing.

**Comment by ghiculescu** [comment]
Added `thisweekinrails` as I think people will want to know about this when upgrading to 7 (and if you're on 6.1 you should be aware that you should tighten your package.json requirements).

**Review by ghiculescu — APPROVED** [review]

**Comment by zzak** [comment]
@ghiculescu I went to rebase the CHANGELOG and lost your contribution 😭 Would you mind fixing it? I will see if we can get some more eyes on this. 🙏

File: railties/lib/rails/generators/app_base.rb [hunk 7]
```diff
@@ -298,6 +298,20 @@ def rails_version_specifier(gem_version = Rails.gem_version)
         end
       end
 
+      # This "npm-ifies" the current version number
+      # With npm, versions such as "5.0.0.rc1" or "5.0.0.beta1.1" are not compliant with its
+      # versioning system, so they must be transformed to "5.0.0-rc1" and "5.0.0-beta1-1" respectively.
+
```
Comment (kamipo) [inline railties/lib/rails/generators/app_base.rb:304]:
```suggestion
      #
```

**Comment by ghiculescu** [comment]
@zzak fixed 👍
