### PR TITLE
[Fix #55525] Address deprecation of `Aws::S3::Object#upload_stream` in `ActiveStorage::Service::S3Service`

### LINKED ISSUE #55525: `ActiveStorage::Service::S3ServiceTest#test_uploading_a_large_object_in_multiple_parts` gets `RailsStrictWarnings::WarningError`
Managed to reproduce CI failure at https://buildkite.com/rails/rails-nightly/builds/2709#0198c422-4221-41bc-9dc4-e0d09f494d79/1197-1277

### Steps to reproduce

```ruby
git clone https://github.com/rails/rails
cd rails/activestorage
```
- Edit the `test/service/configurations.yml` and enable the s3 one (values are masked)
```ruby
s3:
  service: S3
  access_key_id: "***"
  secret_access_key: "***"
  region: "***"
  bucket: "***"
```

```ruby
bundle update aws-sdk-s3 --conservative
RAILS_STRICT_WARNINGS=1 bin/test test/service/s3_service_test.rb -n test_compose
```

### Expected behavior
It should pass.

### Actual behavior

It raises the `RailsStrictWarnings::WarningError` because of the "Called deprecated method `upload_stream` of Aws::S3::Object. Use `Aws::S3::TransferManager#upload_stream` instead." warning since `aws-sdk-s3` 1.197.0 

```ruby
$ bundle update aws-sdk-s3 --conservative
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Resolving dependencies...
Using aws-sdk-core 3.229.0 (was 3.215.1)
Using aws-sdk-s3 1.197.0 (was 1.177.0)
Bundle updated!
1 installed gem you directly depend on is looking for funding.
  Run `bundle fund` for details
$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 5d1be453e1..86450fb7c7 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -126,16 +126,19 @@ GEM
     ast (2.4.2)
     aws-eventstream (1.3.0)
     aws-partitions (1.1037.0)
-    aws-sdk-core (3.215.1)
+    aws-sdk-core (3.229.0)
       aws-eventstream (~> 1, >= 1.3.0)
       aws-partitions (~> 1, >= 1.992.0)
       aws-sigv4 (~> 1.9)
+      base64
+      bigdecimal
       jmespath (~> 1, >= 1.6.1)
+      logger
     aws-sdk-kms (1.96.0)
       aws-sdk-core (~> 3, >= 3.210.0)
       aws-sigv4 (~> 1.5)
-    aws-sdk-s3 (1.177.0)
-      aws-sdk-core (~> 3, >= 3.210.0)
+    aws-sdk-s3 (1.197.0)
+      aws-sdk-core (~> 3, >= 3.228.0)
       aws-sdk-kms (~> 1)
       aws-sigv4 (~> 1.5)
     aws-sdk-sns (1.92.0)
$ RAILS_STRICT_WARNINGS=1 bin/test test/service/s3_service_test.rb -n test_compose
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/capybara-3.40.0/lib/capybara/session/config.rb:95: warning: URI::RFC3986_PARSER.make_regexp is obsolete. Use URI::RFC2396_PARSER.make_regexp explicitly.
== 20170806125915 CreateActiveStorageTables: migrating ========================
-- create_table(:active_storage_blobs, {id: :primary_key})
   -> 0.0006s
-- create_table(:active_storage_attachments, {id: :primary_key})
   -> 0.0005s
-- create_table(:active_storage_variant_records, {id: :primary_key})
   -> 0.0004s
== 20170806125915 CreateActiveStorageTables: migrated (0.0015s) ===============

==  ActiveStorageCreateUsers: migrating =======================================
-- create_table(:users)
   -> 0.0002s
==  ActiveStorageCreateUsers: migrated (0.0002s) ==============================

==  ActiveStorageCreateGroups: migrating ======================================
-- create_table(:groups)
   -> 0.0002s
==  ActiveStorageCreateGroups: migrated (0.0002s) =============================

Run options: -n test_compose --seed 5866

# Running:

#################### DEPRECATION WARNING ####################
Called deprecated method `upload_stream` of Aws::S3::Object. Use `Aws::S3::TransferManager#upload_stream` instead.
Method `upload_stream` will be removed in next major version.
#############################################################
/home/yahonda/src/github.com/rails/rails/activestorage/lib/active_storage/service/s3_service.rb:103:in 'ActiveStorage::Service::S3Service#compose'
/home/yahonda/src/github.com/rails/rails/activestorage/test/service/shared_service_tests.rb:156:in 'block (2 levels) in <module:SharedServiceTests>'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest/test.rb:94:in 'block (2 levels) in Minitest::Test#run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest/test.rb:190:in 'Minitest::Test#capture_exceptions'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest/test.rb:89:in 'block in Minitest::Test#run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:368:in 'Minitest::Runnable#time_it'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest/test.rb:88:in 'Minitest::Test#run'
/home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/executor/test_helper.rb:5:in 'block in ActiveSupport::Executor::TestHelper#run'
/home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/execution_wrapper.rb:104:in 'ActiveSupport::ExecutionWrapper.perform'
/home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/executor/test_helper.rb:5:in 'ActiveSupport::Executor::TestHelper#run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:1208:in 'Minitest.run_one_method'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:447:in 'Minitest::Runnable.run_one_method'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:434:in 'block (2 levels) in Minitest::Runnable.run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:430:in 'Array#each'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:430:in 'block in Minitest::Runnable.run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:472:in 'Minitest::Runnable.on_signal'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:459:in 'Minitest::Runnable.with_info_handler'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:429:in 'Minitest::Runnable.run'
/home/yahonda/src/github.com/rails/rails/railties/lib/rails/test_unit/line_filtering.rb:10:in 'Rails::LineFiltering#run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:332:in 'block in Minitest.__run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:332:in 'Array#map'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:332:in 'Minitest.__run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:288:in 'Minitest.run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:86:in 'block in Minitest.autorun'
E

Error:
ActiveStorage::Service::S3ServiceTest#test_compose:
RailsStrictWarnings::WarningError: #################### DEPRECATION WARNING ####################
Called deprecated method `upload_stream` of Aws::S3::Object. Use `Aws::S3::TransferManager#upload_stream` instead.
Method `upload_stream` will be removed in next major version.
#############################################################
/home/yahonda/src/github.com/rails/rails/activestorage/lib/active_storage/service/s3_service.rb:103:in 'ActiveStorage::Service::S3Service#compose'
/home/yahonda/src/github.com/rails/rails/activestorage/test/service/shared_service_tests.rb:156:in 'block (2 levels) in <module:SharedServiceTests>'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest/test.rb:94:in 'block (2 levels) in Minitest::Test#run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest/test.rb:190:in 'Minitest::Test#capture_exceptions'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest/test.rb:89:in 'block in Minitest::Test#run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:368:in 'Minitest::Runnable#time_it'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest/test.rb:88:in 'Minitest::Test#run'
/home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/executor/test_helper.rb:5:in 'block in ActiveSupport::Executor::TestHelper#run'
/home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/execution_wrapper.rb:104:in 'ActiveSupport::ExecutionWrapper.perform'
/home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/executor/test_helper.rb:5:in 'ActiveSupport::Executor::TestHelper#run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:1208:in 'Minitest.run_one_method'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:447:in 'Minitest::Runnable.run_one_method'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:434:in 'block (2 levels) in Minitest::Runnable.run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:430:in 'Array#each'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:430:in 'block in Minitest::Runnable.run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:472:in 'Minitest::Runnable.on_signal'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:459:in 'Minitest::Runnable.with_info_handler'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:429:in 'Minitest::Runnable.run'
/home/yahonda/src/github.com/rails/rails/railties/lib/rails/test_unit/line_filtering.rb:10:in 'Rails::LineFiltering#run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:332:in 'block in Minitest.__run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:332:in 'Array#map'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:332:in 'Minitest.__run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:288:in 'Minitest.run'
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:86:in 'block in Minitest.autorun'

    /home/yahonda/src/github.com/rails/rails/tools/strict_warnings.rb:35:in 'RailsStrictWarnings#warn'


bin/test test/service/shared_service_tests.rb:142



Finished in 2.519935s, 0.3968 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
``` 

### System configuration

**Rails version**:  main branch

**Ruby version**:  ruby 3.4.5 (2025-07-16 revision 20cda200d3) +PRISM [x86_64-linux]

### PR DESCRIPTION
**Pull request by joshuay03**
Closes https://github.com/rails/rails/issues/55525
Closes https://github.com/rails/rails/issues/55546

Refs:
- https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/CHANGELOG.md?rgh-link-date=2025-08-21T05%3A37%3A51.000Z#11970-2025-08-19
- https://github.com/aws/aws-sdk-ruby/pull/3281

### Detail

Addresses the deprecation of `Aws::S3::Object#upload_stream` which is used in `ActiveStorage::Service::S3Service` by utilising `Aws::S3::TransferManager` for stream uploads if it's available.

### Additional information

N/A

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by yahonda** [comment]
Thanks for Thanks for opening a pull request to fix https://github.com/rails/rails/issues/55525 .

Looks like you have no S3 configured, here are test results with S3 is configured.

```ruby
$ gh pr checkout 55541
$ bundle update aws-sdk-s3 --conservative
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Resolving dependencies...
Using aws-sdk-core 3.230.0 (was 3.215.1)
Using aws-sdk-s3 1.197.0 (was 1.177.0)
Bundle updated!
1 installed gem you directly depend on is looking for funding.
  Run `bundle fund` for details
yahonda@myubuntu:~/src/github.com/rails/rails/activestorage$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 5d1be453e1..390d3fe242 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -126,16 +126,19 @@ GEM
     ast (2.4.2)
     aws-eventstream (1.3.0)
     aws-partitions (1.1037.0)
-    aws-sdk-core (3.215.1)
+    aws-sdk-core (3.230.0)
       aws-eventstream (~> 1, >= 1.3.0)
       aws-partitions (~> 1, >= 1.992.0)
       aws-sigv4 (~> 1.9)
+      base64
+      bigdecimal
       jmespath (~> 1, >= 1.6.1)
+      logger
     aws-sdk-kms (1.96.0)
       aws-sdk-core (~> 3, >= 3.210.0)
       aws-sigv4 (~> 1.5)
-    aws-sdk-s3 (1.177.0)
-      aws-sdk-core (~> 3, >= 3.210.0)
+    aws-sdk-s3 (1.197.0)
+      aws-sdk-core (~> 3, >= 3.228.0)
       aws-sdk-kms (~> 1)
       aws-sigv4 (~> 1.5)
     aws-sdk-sns (1.92.0)
$ RAILS_STRICT_WARNINGS=1 bin/test test/service/s3_service_test.rb -n test_compose
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/capybara-3.40.0/lib/capybara/session/config.rb:95: warning: URI::RFC3986_PARSER.make_regexp is obsolete. Use URI::RFC2396_PARSER.make_regexp explicitly.
== 20170806125915 CreateActiveStorageTables: migrating ========================
-- create_table(:active_storage_blobs, {id: :primary_key})
   -> 0.0006s
-- create_table(:active_storage_attachments, {id: :primary_key})
   -> 0.0004s
-- create_table(:active_storage_variant_records, {id: :primary_key})
   -> 0.0003s
== 20170806125915 CreateActiveStorageTables: migrated (0.0014s) ===============

==  ActiveStorageCreateUsers: migrating =======================================
-- create_table(:users)
   -> 0.0002s
==  ActiveStorageCreateUsers: migrated (0.0002s) ==============================

==  ActiveStorageCreateGroups: migrating ======================================
-- create_table(:groups)
   -> 0.0001s
==  ActiveStorageCreateGroups: migrated (0.0002s) =============================

Run options: -n test_compose --seed 39669

# Running:

E

Error:
ActiveStorage::Service::S3ServiceTest#test_compose:
NoMethodError: undefined method 'create_multipart_upload' for an instance of Aws::S3::Resource
    /home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/aws-sdk-s3-1.197.0/lib/aws-sdk-s3/multipart_stream_uploader.rb:45:in 'Aws::S3::MultipartStreamUploader#initiate_upload'
    /home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/aws-sdk-s3-1.197.0/lib/aws-sdk-s3/multipart_stream_uploader.rb:36:in 'block in Aws::S3::MultipartStreamUploader#upload'
    /home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/aws-sdk-core-3.230.0/lib/aws-sdk-core/plugins/user_agent.rb:90:in 'Aws::Plugins::UserAgent.metric'
    /home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/aws-sdk-s3-1.197.0/lib/aws-sdk-s3/multipart_stream_uploader.rb:35:in 'Aws::S3::MultipartStreamUploader#upload'
    /home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/aws-sdk-s3-1.197.0/lib/aws-sdk-s3/transfer_manager.rb:239:in 'Aws::S3::TransferManager#upload_stream'
    lib/active_storage/service/s3_service.rb:116:in 'ActiveStorage::Service::S3Service#compose'
    test/service/shared_service_tests.rb:156:in 'block (2 levels) in <module:SharedServiceTests>'


bin/test test/service/shared_service_tests.rb:142



Finished in 3.128825s, 0.3196 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

**Comment by yahonda** [comment]
Here are all Active Storage tests with Amazon S3 configured.

```ruby
$ bundle update aws-sdk-s3 --conservative
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Resolving dependencies...
Using aws-sdk-core 3.230.0 (was 3.215.1)
Using aws-sdk-s3 1.197.0 (was 1.177.0)
Bundle updated!
1 installed gem you directly depend on is looking for funding.
  Run `bundle fund` for details
$ RAILS_STRICT_WARNINGS=1 bin/test
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/capybara-3.40.0/lib/capybara/session/config.rb:95: warning: URI::RFC3986_PARSER.make_regexp is obsolete. Use URI::RFC2396_PARSER.make_regexp explicitly.
== 20170806125915 CreateActiveStorageTables: migrating ========================
-- create_table(:active_storage_blobs, {id: :primary_key})
   -> 0.0005s
-- create_table(:active_storage_attachments, {id: :primary_key})
   -> 0.0005s
-- create_table(:active_storage_variant_records, {id: :primary_key})
   -> 0.0003s
== 20170806125915 CreateActiveStorageTables: migrated (0.0015s) ===============

==  ActiveStorageCreateUsers: migrating =======================================
-- create_table(:users)
   -> 0.0002s
==  ActiveStorageCreateUsers: migrated (0.0002s) ==============================

==  ActiveStorageCreateGroups: migrating ======================================
-- create_table(:groups)
   -> 0.0002s
==  ActiveStorageCreateGroups: migrated (0.0002s) =============================

Skipping GCS Direct Upload tests because no GCS configuration was supplied
Skipping Azure Storage Direct Upload tests because no Azure Storage configuration was supplied
Skipping Azure Storage Public Service tests because no Azure configuration was supplied
Skipping Azure Storage Service tests because no Azure configuration was supplied
Skipping GCS Public Service tests because no GCS configuration was supplied
Skipping GCS Service tests because no GCS configuration was supplied
Skipping S3 Public Service tests because no S3 configuration was supplied
Run options: --seed 19082

# Running:

yarn run v1.22.22
(node:115303) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
$ yarn lint
(node:115325) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
$ eslint app/javascript
$ rollup --config rollup.config.js

app/javascript/activestorage/index.js → app/assets/javascripts/activestorage.js...
created app/assets/javascripts/activestorage.js in 166ms

app/javascript/activestorage/index.js → app/assets/javascripts/activestorage.esm.js...
created app/assets/javascripts/activestorage.esm.js in 125ms
Done in 0.78s.
.................................................................................................................................................................................................................................................................................................................../home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/azure-storage-common-2.0.4/lib/azure/storage/common/core/utility.rb:222: warning: method redefined; discarding old private?
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/3.4.0/ipaddr.rb:298: warning: previous definition of private? was here
/home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/azure-storage-common-2.0.4/lib/azure/core/http/http_request.rb:140: warning: method redefined; discarding old body=
.......................................................................................................................................E

Error:
ActiveStorage::Service::S3ServiceTest#test_compose:
NoMethodError: undefined method 'create_multipart_upload' for an instance of Aws::S3::Resource
    /home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/aws-sdk-s3-1.197.0/lib/aws-sdk-s3/multipart_stream_uploader.rb:45:in 'Aws::S3::MultipartStreamUploader#initiate_upload'
    /home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/aws-sdk-s3-1.197.0/lib/aws-sdk-s3/multipart_stream_uploader.rb:36:in 'block in Aws::S3::MultipartStreamUploader#upload'
    /home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/aws-sdk-core-3.230.0/lib/aws-sdk-core/plugins/user_agent.rb:90:in 'Aws::Plugins::UserAgent.metric'
    /home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/aws-sdk-s3-1.197.0/lib/aws-sdk-s3/multipart_stream_uploader.rb:35:in 'Aws::S3::MultipartStreamUploader#upload'
    /home/yahonda/.local/share/mise/installs/ruby/3.4.5/lib/ruby/gems/3.4.0/gems/aws-sdk-s3-1.197.0/lib/aws-sdk-s3/transfer_manager.rb:239:in 'Aws::S3::TransferManager#upload_stream'
    lib/active_storage/service/s3_service.rb:116:in 'ActiveStorage::Service::S3Service#compose'
    test/service/shared_service_tests.rb:156:in 'block (2 levels) in <module:SharedServiceTests>'


bin/test test/service/shared_service_tests.rb:142

........E

Error:
ActiveStorage::Service::S3ServiceTest#test_uploading_a_large_object_in_multiple_parts:
NameError: undefined local variable or method 'destination_key' for an instance of ActiveStorage::Service::S3Service
    lib/active_storage/service/s3_service.rb:157:in 'ActiveStorage::Service::S3Service#upload_with_multipart'
    lib/active_storage/service/s3_service.rb:36:in 'block in ActiveStorage::Service::S3Service#upload'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/notifications.rb:210:in 'block in ActiveSupport::Notifications.instrument'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/notifications/instrumenter.rb:58:in 'ActiveSupport::Notifications::Instrumenter#instrument'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/notifications.rb:210:in 'ActiveSupport::Notifications.instrument'
    lib/active_storage/service.rb:169:in 'ActiveStorage::Service#instrument'
    lib/active_storage/service/s3_service.rb:30:in 'ActiveStorage::Service::S3Service#upload'
    test/service/s3_service_test.rb:172:in 'block in <class:S3ServiceTest>'


bin/test test/service/s3_service_test.rb:165

.............................................................

Finished in 92.122946s, 5.6663 runs/s, 16.9013 assertions/s.
522 runs, 1557 assertions, 0 failures, 2 errors, 0 skips
$
```

**Comment by joshuay03** [comment]
@yahonda Thanks! I ended up just creating a bucket and testing locally. This now passes on both this branch and with the upgraded gem.

**Comment by byroot** [comment]
Thanks for this PR. I took the liberty to push b80a0f3e2f1d345ff962dad701fe993ea2372458 to simplify the code a bit.

**Comment by byroot** [comment]
Oops c60bd6002e8540e9bf0d9e097c8f3eb24116f924

File: activestorage/lib/active_storage/service/s3_service.rb [hunk 1]
```diff
@@ -16,6 +16,8 @@ class Service::S3Service < Service
 
     def initialize(bucket:, upload: {}, public: false, **options)
       @client = Aws::S3::Resource.new(**options)
+      @s3_client = @client.client
+      @transfer_manager = Aws::S3::TransferManager.new(client: @s3_client) if defined?(Aws::S3::TransferManager)
```
Comment (byroot) [inline activestorage/lib/active_storage/service/s3_service.rb]: Are we sure that transfert manager can be shared? Doesn't it have some internal state or something that may not be thread safe?

Comment (byroot) [reply activestorage/lib/active_storage/service/s3_service.rb]: Answering my own question. I went into the gem. The client have a pool of connection, so seems thread safe, the manager has basically no state. So yes, we can share all that.

Comment (joshuay03) [reply activestorage/lib/active_storage/service/s3_service.rb]: Yes, you beat me to it. It essentially just wraps an `Aws::S3::Client` which is thread safe (and already used here by the `Aws::S3::Resource`).

**Comment by chaadow** [comment]
@joshuay03 @byroot I've looked into [TransferManager](https://github.com/aws/aws-sdk-ruby/blob/55bb8ae5674001b4368ee4cb49fca4c6e200fa2a/gems/aws-sdk-s3/lib/aws-sdk-s3/transfer_manager.rb)  and I wanted your thoughts on whether it would be valuable to re-factor [S3Service#download and S3Service#download_chunk](https://github.com/rails/rails/blob/afbc35a18dede2f3a0e0484d94a0c7648ae4db59/activestorage/lib/active_storage/service/s3_service.rb#L41-L61) to use the new API ( which is `TransferManager#download_file` ) which can handle both cases

If so, I can work on a PR similar to this one if you're ok with the idea.

**Comment by byroot** [comment]
If it's not deprecated I'd rather not change the code.
