### PR TITLE
Fix double logging in `ActiveRecord::QueryLogs`

### LINKED ISSUE #46103: Query log tags docs are unclear on configuration steps
I found the [Active Record query log tags documentation](https://api.rubyonrails.org/classes/ActiveRecord/QueryLogs.html) confusing on what needs to be configured in which file to result in the behaviour I was looking for. Happy to open a PR and make it more clear, but I also wanted to check I'm not running in a bug.

### Steps to reproduce
```
rails new query_log_tags
cd query_log_tags
bin/rails g scaffold post
bin/rails db:migrate
```
Reading the docs: "The tags used in a query can be configured directly [example 1] or via Rails configuration: [example 2]". Opening up `config/application.rb` and added a tweaked version of example 2:
```ruby
config.active_record.query_log_tags = [
  :controller,
  :action,
  :job,
  {
    request_id: ->(context) { context[:controller]&.request&.request_id },
    job_id: ->(context) { context[:job]&.job_id },
  },
]
```
run `bin/rails s` and visit http://localhost:3000/posts results in:
```
Post Load (0.1ms)  SELECT "posts".* FROM "posts"
```
That's not working. I find https://github.com/rails/rails/pull/42240 and learn about `query_log_tags_enabled` which is not mentioned in the docs at all 😬. 

The bottom of `config/application.rb` now looks like this:
```ruby
config.active_record.query_log_tags_enabled = true
config.active_record.query_log_tags = [
  :controller,
  :action,
  :job,
  {
    request_id: ->(context) { context[:controller]&.request&.request_id },
    job_id: ->(context) { context[:job]&.job_id },
  },
]
```
Restarting the Rails server and trying again results in:
```
Post Load (0.3ms)  SELECT "posts".* FROM "posts" Post Load (0.1ms)  SELECT "posts".* FROM "posts" /*controller:posts,action:index,request_id:486050d1-76c8-4afa-b88d-35b6ffb04ff4,controller:posts,action:index*/
```
I'm seeing double! Perhaps application.rb is too early in the boot process? I'll move it to `config/initializers/query_log_tags.rb` based on a mention of initializers at the bottom of the API guide and try again:
```ruby
Rails.application.config.active_record.query_log_tags_enabled = true
Rails.application.config.active_record.query_log_tags = [
  :controller,
  :action,
  :job,
  {
    request_id: ->(context) { context[:controller]&.request&.request_id },
    job_id: ->(context) { context[:job]&.job_id },
  },
]
```
Resulting in:
```
Post Load (0.1ms)  SELECT "posts".* FROM "posts" /*controller:#<PostsController:0x00000001080ec4d8>,request_id:6de8f562-cb44-4b71-ad53-db7d72a986cb*/
```
Not the controller output I was expecting and it's missing the action.

After some more fiddling, I get the expected output to work in the following way:
```ruby
# config/application.rb
config.active_record.query_log_tags_enabled = true

# config/initializers/query_log_tags.rb
Rails.application.config.active_record.query_log_tags = [
  :controller,
  :action,
  :job,
  {
    request_id: ->(context) { context[:controller]&.request&.request_id },
    job_id: ->(context) { context[:job]&.job_id },
  },
]
```
Result:
```
Post Load (0.1ms)  SELECT "posts".* FROM "posts" /*controller:posts,action:index,request_id:8f56eaac-c05a-406a-9df4-692055f1a58f*/
```

### How to fix [the documentation](https://api.rubyonrails.org/classes/ActiveRecord/QueryLogs.html)
While this split between `application.rb` and an initializer works, it seems overly dependant on the order of the Rails initialization process and when the [Action Controller](https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/actionpack/lib/action_controller/railtie.rb#L108-L124) and [Active Job](https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/activejob/lib/active_job/railtie.rb#L60-L72) railties are lazily loaded? 

If it is supposed to work this way, that deserves to be documented more clearly alongside the the missing mention of `query_log_tags_enabled = true`. I'm happy to rewrite the docs after confirmation this is working correctly or not.

### System configuration
**Rails version**:
7.0.4
**Ruby version**:
3.1.2

### PR DESCRIPTION
**Pull request by ghiculescu**
Fixes https://github.com/rails/rails/issues/46103

An issue exists if you set `config.active_record.query_log_tags` to an array that includes `:controller`, `:action`, or `:job`; the relevant item will get duplicated in the log line. This occured because the relevant railties would add the item to `config.active_record.query_log_tags` again during setup. This PR fixes that by only adding those items to the config if they aren't already set.

The issue proposed more documentation to work around this, but I think it's a bug and should be fixed directly.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [x] CI is passing.

### CODE REVIEW

File: actionpack/lib/action_controller/railtie.rb [hunk 1]
```diff
@@ -112,7 +112,9 @@ class Railtie < Rails::Railtie # :nodoc:
         app.config.action_controller.log_query_tags_around_actions
 
       if query_logs_tags_enabled
-        app.config.active_record.query_log_tags += [:controller, :action]
+        [:controller, :action].each do |tag|
+          app.config.active_record.query_log_tags << tag unless app.config.active_record.query_log_tags.include?(tag)
+        end
```
Comment (byroot) [inline actionpack/lib/action_controller/railtie.rb:117]:
```suggestion
        app.config.active_record.query_log_tags |= [:controller, :action]
```

Would be simpler, no?

Comment (ghiculescu) [reply actionpack/lib/action_controller/railtie.rb:117]: Haha yes it would.

File: activejob/lib/active_job/railtie.rb [hunk 2]
```diff
@@ -72,7 +72,7 @@ class Railtie < Rails::Railtie # :nodoc:
         app.config.active_job.log_query_tags_around_perform
 
       if query_logs_tags_enabled
-        app.config.active_record.query_log_tags << :job
+        app.config.active_record.query_log_tags << :job unless app.config.active_record.query_log_tags.include?(:job)
```
Comment (byroot) [inline activejob/lib/active_job/railtie.rb:75]:
```suggestion
        app.config.active_record.query_log_tags |= [:job]
```

Might as well simplify here too.

**Review by byroot — APPROVED** [review]

File: activejob/lib/active_job/railtie.rb (hunk 2 above)
Comment (ghiculescu) [reply activejob/lib/active_job/railtie.rb]: Ahh, I didn't want to initialize the extra array, but I guess that's pretty trivial in the scheme of things. Thanks!

**Comment by bdewater** [comment]
@byroot could this be backported to `7-0-stable` please?

**Comment by ghiculescu** [comment]
FYI I found another bug here, it's fixed in https://github.com/rails/rails/pull/46642 - @byroot any chance you could take a look?
