### PR TITLE
Fixed `where` for polymorphic associations when passed an array containing different types.

### LINKED ISSUE #17011: ActiveRecord's `.where` cannot handle polymorphic arrays containing different types
Example: https://gist.github.com/pvande/2e346213ace076cd0edb

ActiveRecord supports [filtering on a polymorphic association](http://guides.rubyonrails.org/active_record_querying.html#equality-conditions), including filtering on an array of related objects, permitting users to write queries like this:

```ruby
PriceEstimate.where(estimate_of: [treasure1, treasure2]).count
```

This generally works pretty well, generating an SQL query like this:

```sql
SELECT COUNT(*)
FROM "price_estimates"
WHERE (
  "price_estimates"."estimate_of_type" = 'Treasure' AND
  "price_estimates"."estimate_of_id" IN (1, 2)
)
```

When attempting such a query with multiple related types however, the query breaks down.

```ruby
# Both Parrot and Pirate are valid polymorphic types for Treasure
parrot, pirate = Parrot.find(1), Pirate.find(1)
Treasure.where(looter: [parrot, pirate]).count
```
```sql
SELECT COUNT(*)
FROM "treasures"
WHERE (
  "treasures"."looter_type" = 'Parrot' AND
  "treasures"."looter_id" IN (1, 1)
)
```

The expected result for the above query would include all Treasure looted by either `Parrot#1` or `Pirate#1`.

### PR DESCRIPTION
**Pull request by phuibonhoa**
Fixes #17011

When passing in an array of different types of objects to `where`, ActiveRecord would only take into account the class of the first object in the array:

``` ruby
    PriceEstimate.where(estimate_of: [Treasure.find(1), Car.find(2)])
    # => SELECT "price_estimates".* FROM "price_estimates"
    #    WHERE ("price_estimates"."estimate_of_type" = 'Treasure' AND "price_estimates"."estimate_of_id" IN (1, 2))
```

The above query would return the wrong results, as it would return the `PriceEstimate` associated with: `[Treasure.find(1), Treasure.find(2)]` rather than `[Treasure.find(1), Car.find(2)]`.  This is fixed to properly return records by matching on both type and id:

``` ruby
    PriceEstimate.where(estimate_of: [Treasure.find(1), Car.find(2)])
    # => SELECT "price_estimates".* FROM "price_estimates"
    #    WHERE (("price_estimates"."estimate_of_type" = 'Treasure' AND "price_estimates"."estimate_of_id" = 1)
    #    OR ("price_estimates"."estimate_of_type" = 'Car' AND "price_estimates"."estimate_of_id" = 2))
```

---
#### Review Comments
- [x] eileencodes [Remove extra space](https://github.com/rails/rails/pull/22365#discussion_r49125458)
- [x] matthewd [Group sql where clause](https://github.com/rails/rails/pull/22365#discussion_r49138888)
- [x] sgrif [Pull switching logic into factory method](https://github.com/rails/rails/pull/22365#discussion_r49133706)
- [x] sgrif [Refactor polymorphic check](https://github.com/rails/rails/pull/22365#discussion-diff-49133829)
- [x] sgrif [Use &:or instead of block](https://github.com/rails/rails/pull/22365#discussion_r49133485)

### CODE REVIEW

**Comment by phuibonhoa** [comment]
@kaspth - Just wanted to make sure this was on your radar.  I've been rebasing master to keep it mergeable, but if it'll be a while until you can get to it, I'll hold off rebasing as frequently.  Thanks!

**Comment by kaspth** [comment]
Thanks for keeping this so well groomed! Overall I think it looks good, but I'll have to cede the more granular evaluation to someone more capable with Active Record.

r+

**Comment by kaspth** [comment]
r+ @rails-bot

**Comment by kaspth** [comment]
r+ @rails-bot

File: activerecord/test/cases/relation/where_test.rb [hunk 1]
```diff
@@ -114,6 +115,22 @@ def test_polymorphic_nested_array_where
       assert_equal expected.to_sql, actual.to_sql
     end
 
+    def test_polymorphic_array_where_multiple_types
+      treasure = Treasure.new
+      treasure.id = 1
+      car = Car.new
+      car.id = 2
+
+
```
Comment (eileencodes) [inline activerecord/test/cases/relation/where_test.rb]: Can you remove the extra space here? Thanks!

**Comment by kaspth** [comment]
Will now exploit Eileens good will :heart:

r? @eileencodes

File: activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_handler.rb [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+        queries = {}
+
+        table = value.associated_table
+        queries = value.types_and_ids.map do |type, id|
+          { table.association_foreign_type.to_s => type, table.association_foreign_key.to_s => id }
+        end
+
+        predicates = queries.map { |query| predicate_builder.build_from_hash(query) }
+        type_and_ids_predicates = predicates.map { |type_predicate, id_predicate| Arel::Nodes::Grouping.new(type_predicate.and(id_predicate)) }
+        type_and_ids_predicates.inject { |composite, predicate| composite.or(predicate) }
```
Comment (sgrif) [inline activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_handler.rb]: This can just be `&:or`

File: activerecord/lib/active_record/relation/predicate_builder.rb [hunk 3]
```diff
@@ -40,9 +42,12 @@ def expand(column, value)
       # For polymorphic relationships, find the foreign key and type:
       # PriceEstimate.where(estimate_of: treasure)
       if table.associated_with?(column)
-        value = AssociationQueryValue.new(table.associated_table(column), value)
+        if polymorphic_array?(value)
```
Comment (sgrif) [inline activerecord/lib/active_record/relation/predicate_builder.rb]: This logic feels kinda strange here to me. Can we move this conditional into a factory method on `AssociationQueryHandler`?

File: activerecord/lib/active_record/relation/predicate_builder.rb [hunk 4]
```diff
@@ -145,5 +150,9 @@ def can_be_bound?(column_name, value)
         handler_for(value).is_a?(BasicObjectHandler) &&
         !table.associated_with?(column_name)
     end
+
+    def polymorphic_array?(value)
+      value.is_a?(Array) && value.map(&:class).map { |e| e.try(:base_class) }.uniq.size > 1
```
Comment (sgrif) [inline activerecord/lib/active_record/relation/predicate_builder.rb]: Since this takes user provided input, it should probably be `::Array === value`

Comment (sgrif) [inline activerecord/lib/active_record/relation/predicate_builder.rb]: This line definitely can be more efficient. This also needs to return immediately if the first element of the array isn't an Active Record object, as this has introduced a > linear time performance regression whenever an array is passed to `where`

Comment (sgrif) [inline activerecord/lib/active_record/relation/predicate_builder.rb]: We should probably check if the association is actually polymorphic before this loop

Comment (phuibonhoa) [inline activerecord/lib/active_record/relation/predicate_builder.rb]: Sorry, didn't realize the performance implications of iterating over this array would have any significant impact.

> We should probably check if the association is actually polymorphic before this loop

Not sure what you mean by this- the purpose of the loop is to check if it is an array of polymorphic objects.  If there's a better way to do this, we can bypass the loop entirely.  How would I check if it's polymorphic before (or without) iterating through the array?

Comment (sgrif) [inline activerecord/lib/active_record/relation/predicate_builder.rb]: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/reflection.rb#L509

File: activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_handler.rb (hunk 2 above)
Comment (matthewd) [inline activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_handler.rb]: Is it worth grouping by type, so we can generate `x_type = 'A' AND x_id IN (1,2,3) OR x_type = 'B' AND x_id IN (4,5,6)`?

We generally avoid doing substantial contortions just for the sake of nicer SQL, but if it's relatively easy, the gain seems likely worthwhile here, IMO.

File: activerecord/lib/active_record/relation/predicate_builder.rb (hunk 4 above)
Comment (phuibonhoa) [inline activerecord/lib/active_record/relation/predicate_builder.rb]: @sgrif Sorry, for my unfamiliarity, but at this point `value` would be an array of AR objects, not necessarily a relation, so I don't think I would have access to `polymorphic?`  If that's the case, I'm going to try your suggestion of moving the switch to a factory method on AssociationQueryValue and move this there with an early exit.

Comment (sgrif) [inline activerecord/lib/active_record/relation/predicate_builder.rb]: Take a look at the implementation of `associated_with?`, where we look up
whether the reflection object is present.

File: activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_handler.rb (hunk 2 above)
Comment (phuibonhoa) [inline activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_handler.rb]: :+1: Will swap to grouping (without unnecessary iterations over the array).

File: activerecord/lib/active_record/relation/predicate_builder.rb (hunk 4 above)
Comment (phuibonhoa) [inline activerecord/lib/active_record/relation/predicate_builder.rb]: Thanks @sgrif!  I've addressed your comments in the latest commit.  Mind giving it a look over, would value your feedback on it.  

CI is red for unrelated changes (looks like it's red on the latest run of other PRs for the same timezone related tests).  I can't rebuild, so I'll push an empty commit later, once I see some other builds go green.

Comment (sgrif) [inline activerecord/lib/active_record/relation/predicate_builder.rb]: Blurgh. The bot should have pinged me when I broke the build... It *should*
be passing on master now.

**Comment by phuibonhoa** [comment]
Thanks @matthewd for rebuilding.  @serif - I'll wait for you to review my [last commit](https://github.com/phuibonhoa/rails/commit/1ba645f0e36b02ca4934a49255b048511118b297) which addresses your feedback before rebasing master and squashing my commits.

**Comment by phuibonhoa** [comment]
@sgrif - If you'd prefer I rebase before you review, just let me know (mostly didn't want to risk losing your comments)

**Comment by sgrif** [comment]
No, you can leave it. I'm about to head out for the day but I've got an alarm to make sure I look at this tomorrow.

**Comment by phuibonhoa** [comment]
@sgrif - Thanks for all the time you've put into this and Rails in general!  Cheers!

File: activerecord/lib/active_record/relation/predicate_builder/association_query_handler.rb [hunk 5]
```diff
@@ -1,6 +1,17 @@
 module ActiveRecord
   class PredicateBuilder
     class AssociationQueryHandler # :nodoc:
+
+      class << self
+        def value_for(table, column, value)
+          if table.associated_with?(column).polymorphic? && ::Array === value && value.first.is_a?(Base)
```
Comment (sgrif) [inline activerecord/lib/active_record/relation/predicate_builder/association_query_handler.rb]: We shouldn't rely on the return value of `associated_with?` being anything other than truthy/falsey.

File: activerecord/lib/active_record/relation/predicate_builder/association_query_handler.rb [hunk 6]
```diff
@@ -1,6 +1,17 @@
 module ActiveRecord
   class PredicateBuilder
     class AssociationQueryHandler # :nodoc:
+
+      class << self
+        def value_for(table, column, value)
```
Comment (sgrif) [inline activerecord/lib/active_record/relation/predicate_builder/association_query_handler.rb]: Please use `def self.` here

File: activerecord/lib/active_record/relation/predicate_builder/association_query_handler.rb [hunk 7]
```diff
@@ -1,6 +1,17 @@
 module ActiveRecord
   class PredicateBuilder
     class AssociationQueryHandler # :nodoc:
+
```
Comment (sgrif) [inline activerecord/lib/active_record/relation/predicate_builder/association_query_handler.rb]: :scissors:

File: activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_handler.rb [hunk 8]
```diff
@@ -0,0 +1,59 @@
+module ActiveRecord
+  class PredicateBuilder
+    class PolymorphicArrayHandler # :nodoc:
+      def initialize(predicate_builder)
+        @predicate_builder = predicate_builder
+      end
+
+      def call(attribute, value)
+        queries = {}
```
Comment (sgrif) [inline activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_handler.rb]: This line seems like it's not doing anything.

File: activerecord/test/cases/relation/where_test.rb [hunk 9]
```diff
@@ -114,6 +115,25 @@ def test_polymorphic_nested_array_where
...
+      car = Car.new
+      car.id = 3
+
+      table = PriceEstimate.arel_table
+      where_arel = table.grouping(table[:estimate_of_type].eq('Treasure').and(table[:estimate_of_id].in([1, 2])))
+                        .or(table.grouping(table[:estimate_of_type].eq('Car').and(table[:estimate_of_id].eq(3))))
+      expected = table.project(table[Arel.star]).where(where_arel)
+      actual   = PriceEstimate.where(estimate_of: [treasure_1, treasure_2, car])
+
+      assert_equal expected.to_sql, actual.to_sql
```
Comment (sgrif) [inline activerecord/test/cases/relation/where_test.rb]: Please avoid testing the generated SQL or using Arel ASTs here, and instead test that the query returns the correct values.

Comment (phuibonhoa) [inline activerecord/test/cases/relation/where_test.rb]: Ahh- the other tests in this file are asserting based of generated sql, so I was just copying that format.  I can swap to checking the query result, but just wanted to double check as that would slow down the test (since it's hitting the db now) and may add complexity, as I'll need to load the fixtures for these models or at least my test will need to know how to create valid and savable models.

Comment (sgrif) [inline activerecord/test/cases/relation/where_test.rb]: Yeah, we usually try to avoid more tests that only focus on generated SQL

File: activerecord/lib/active_record/relation/predicate_builder/association_query_handler.rb (hunk 5 above)
Comment (phuibonhoa) [inline activerecord/lib/active_record/relation/predicate_builder/association_query_handler.rb]: Doh- nice catch.

**Comment by phuibonhoa** [comment]
@sgrif - Latest comments addressed in the last 3 commits:

 * [Clean up code formatting / style.](https://github.com/phuibonhoa/rails/commit/940b941a9b7548d8e6360aa07adca36339d088e1)
 * [Convert test to assert results instead of sql](https://github.com/phuibonhoa/rails/commit/886b6c7ec6467b32e42442d916e1c9252f422434)
 * [Swap from using associated_with? to associated_table](https://github.com/rails/rails/commit/5aa1a36727bbad7788b65b280f4d7e83f14b5334)

Cheers!

**Comment by phuibonhoa** [comment]
@sgrif - Ready for review (in case you missed my previous message).  Otherwise please feel free to punt until it reaches the top of your queue.

Cheers mate.

File: activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_handler.rb [hunk 10]
```diff
@@ -0,0 +1,57 @@
...
+        end
+
+        predicates = queries.map { |query| predicate_builder.build_from_hash(query) }
+
+        if predicates.size > 1
+          type_and_ids_predicates = predicates.map { |type_predicate, id_predicate| Arel::Nodes::Grouping.new(type_predicate.and(id_predicate)) }
+          type_and_ids_predicates.inject(&:or)
+        else
+          predicates.first
+        end
```
Comment (sgrif) [inline activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_handler.rb]: Could this whole if statement be replaced with:

```ruby
predicates.reduce do |result, (type_predicate, id_predicate)|
  result.or(Arel::Nodes::Grouping.new(type_predicate.and(id_predicate)))
end
```

**Comment by sgrif** [comment]
One last nitpick. Please also squash and rebase.

File: activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_handler.rb (hunk 10 above)
Comment (phuibonhoa) [inline activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_handler.rb]: On the first iteration, `result` is the array of predicates so it raises: `NoMethodError: undefined method `or' for #<Array:0x007f874b75b348>`.  I can't think of a good initial value to pass to reduce that would avoid this problem without adding an extra `or`.  

I could remove the `if predicates.size > 1` but when there is only one object passed, the resulting sql gets an extra set of `()` and it breaks a test.  Happy to remove the conditional and update the test to assert against the results instead of the generated sql as it sounds like that's preferred now.  LMK.

**Comment by phuibonhoa** [comment]
@sgrif - Squashed and rebased.  One last [outstanding comment](https://github.com/rails/rails/pull/22365#discussion_r50490738). 

This may be good to go as is, but happy to still try to work in the inject or remove the special handling one the case of one object passed in, just LMK.

**Comment by phuibonhoa** [comment]
@sgrif - ping

**Comment by phuibonhoa** [comment]
@sgrif - All rebased and green.  I'll try to keep it rebased (but tend to do the rebasing late at night pst).
