### PR TITLE
Strict loading cascade down to middle records

### LINKED ISSUE #42421: Strict loading does not cascade down to middle records of through associations
### Steps to reproduce

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', github: 'rails/rails', branch: 'main'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :categories, force: true do |t|
  end

  create_table :posts, force: true do |t|
    t.integer :category_id
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Category < ActiveRecord::Base
  has_many :posts
  has_many :comments, through: :posts
end

class Post < ActiveRecord::Base
  belongs_to :category
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post, optional: true
  has_one :category, through: :post
end

class BugTest < Minitest::Test
  def test_preload_has_many_through_association_middle_records_are_strict_loading_because_parent_is_strict_loading
    category = Category.create!
    post = Post.create!(category: category)
    post.comments << Comment.create!

    # strict_loading? is true as expected
    assert Category.strict_loading.includes(:posts, :comments).first.posts.first.strict_loading?
    # strict loading does not cascade to posts as expected allowing comments to be lazy loaded
    Category.strict_loading.includes(:comments, :posts).first.posts.first.comments.to_a
    Category.strict_loading.includes(:comments).first.posts.first.comments.to_a
    # these asserts fail: strict_loading? is unexpectedly false
    assert Category.strict_loading.includes(:comments, :posts).first.posts.first.strict_loading?
    assert Category.strict_loading.includes(:comments).first.posts.first.strict_loading?
  end

  def test_preload_has_one_through_association_middle_record_is_strict_loading_because_parent_is_strict_loading
    category = Category.create!
    post = Post.create!(category: category)
    post.comments << Comment.create!

    # strict_loading? is true as expected
    assert Comment.strict_loading.includes(:post, :category).first.post.strict_loading?
    # strict loading does not cascade to post as expected allowing comments to be lazy loaded
    Comment.strict_loading.includes(:category, :post).first.post.comments.to_a
    Comment.strict_loading.includes(:category).first.post.comments.to_a
    # these asserts fail: strict_loading? is unexpectedly false
    assert Comment.strict_loading.includes(:category, :post).first.post.strict_loading?
    assert Comment.strict_loading.includes(:category).first.post.strict_loading?
  end
end
```

### Expected behavior
Strict loading cascades down to middle records of through associations regardless of if those middle records are already preloaded through a direct association.

### Actual behavior
Strict loading does not cascade down to the middle records of through associations if those middle records are not already preloaded.

### System configuration
**Rails version**: main, 6.1.3.2

**Ruby version**: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

### PR DESCRIPTION
**Pull request by intrip**
### Summary

`strict_loading` now cascade to middle records of through associations.

Fixes #42421

### CODE REVIEW

File: activerecord/lib/active_record/associations/preloader/association.rb [hunk 1]
```diff
@@ -239,11 +239,11 @@ def build_scope
               scope.merge!(preload_scope)
             end
 
-            if preload_scope && preload_scope.strict_loading_value
-              scope.strict_loading
-            else
-              scope
-            end
+            propagate_strict_loading(scope)
```
Comment (eileencodes) [inline activerecord/lib/active_record/associations/preloader/association.rb:242]: Even though this is a private method, I'd prefer `cascade` over `propagate` for the name.

Comment (intrip) [reply activerecord/lib/active_record/associations/preloader/association.rb]: Renamed to `cascade_strict_loading` as suggested.

**Comment by intrip** [comment]
@eileencodes thanks for the review! I've applied the requested changes, could you check again?

**Comment by eileencodes** [comment]
Thank you!
