### PR TITLE
use singular table name if pluralize_table_names is setted as false whil...

### LINKED ISSUE #19643: ActiveRecord::Migration table.references() ignores ActiveRecord::Base.pluralize_table_names = false
It appears that in **Rails** / **ActiveRecord** `4.2.1`, that the `references` column "type" ignores `ActiveRecord::Base.pluralize_table_names` or doesn't work as expected when configured to `false`:

```sh
$ grep plural config/environment.rb
ActiveRecord::Base.pluralize_table_names = false
```

```sh
$ rails generate model foo
      invoke  active_record
      create    db/migrate/015_create_foo.rb
      create    app/models/foo.rb
      invoke    minitest
      create      test/models/foo_test.rb
      create      test/fixtures/foos.yml

$ rails generate model bar foo:references
      invoke  active_record
      create    db/migrate/016_create_bar.rb
      create    app/models/bar.rb
      invoke    minitest
      create      test/models/bar_test.rb
      create      test/fixtures/bars.yml

$ cat db/migrate/015_create_foo.rb
class CreateFoo < ActiveRecord::Migration
  def change
    create_table :foo do |t|

      t.timestamps null: false
    end
  end
end

$ cat db/migrate/016_create_bar.rb
class CreateBar < ActiveRecord::Migration
  def change
    create_table :bar do |t|
      t.references :foo, index: true, foreign_key: true

      t.timestamps null: false
    end
  end
end

$ rake db:migrate
...
ActiveRecord::StatementInvalid: Mysql2::Error: Can't create table 'planner_dev.#sql-52f_b' (errno: 150): ALTER TABLE `bar` ADD CONSTRAINT `fk_rails_e70b15738f`
FOREIGN KEY (`foo_id`)
  REFERENCES `foos` (`id`)
```

### PR DESCRIPTION
**Pull request by meinac**
use singular table name if pluralize_table_names is setted as false while creating foreign key

Closes #19643

### CODE REVIEW

**Comment by senny** [comment]
@meinac could you add a test-case to prevent against regressions?

**Comment by meinac** [comment]
@senny I've created a test case for this situation.

File: activerecord/test/cases/migration/references_foreign_key_test.rb [hunk 1]
```diff
@@ -12,6 +12,7 @@ class ReferencesForeignKeyTest < ActiveRecord::TestCase
       teardown do
         @connection.drop_table "testings", if_exists: true
         @connection.drop_table "testing_parents", if_exists: true
+        @connection.drop_table "testing", if_exists: true
```
Comment (senny) [inline activerecord/test/cases/migration/references_foreign_key_test.rb]: can you move that `drop_table` into an ensure clause for the specific test. No need to run it for every other test if the table is only created in one of em.

File: activerecord/test/cases/migration/references_foreign_key_test.rb [hunk 2]
```diff
@@ -105,6 +106,18 @@ class ReferencesForeignKeyTest < ActiveRecord::TestCase
           @connection.remove_reference :testings, :testing_parent, foreign_key: true
         end
       end
+
+      test "foreign key column can be added for singular table" do
+        ActiveRecord::Base.stubs(:pluralize_table_names).returns(false)
```
Comment (senny) [inline activerecord/test/cases/migration/references_foreign_key_test.rb]: instead of stubbing, we usually assign the value and restore the configuration. Something along the lines of:

```ruby
begin
  original_pluralize_table_names = ActiveRecord::Base.pluralize_table_names
  ActiveRecord::Base.pluralize_table_names = false
ensure
  ActiveRecord::Base.pluralize_table_names = original_pluralize_table_names
end
```

File: activerecord/test/cases/migration/references_foreign_key_test.rb [hunk 3]
```diff
@@ -105,6 +106,18 @@ class ReferencesForeignKeyTest < ActiveRecord::TestCase
...
+        @connection.create_table :testing
+        @connection.change_table :testing_parents do |t|
+          t.references :testing, foreign_key: true
+        end
+
+        fk = @connection.foreign_keys("testing_parents").first
+        assert_equal "testing_parents", fk.from_table
+        assert_equal "testing", fk.to_table
```
Comment (senny) [inline activerecord/test/cases/migration/references_foreign_key_test.rb]: Let's incorporate removing the key as well. I suspect this line needs to be changed in lockstep: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L670

**Comment by meinac** [comment]
@senny what about this?

File: activerecord/test/cases/migration/references_foreign_key_test.rb [hunk 4]
```diff
@@ -105,6 +105,44 @@ class ReferencesForeignKeyTest < ActiveRecord::TestCase
...
+          @connection.change_table :testing_parents do |t|
+            t.references :testing, foreign_key: true
+          end
+
+          fk = @connection.foreign_keys("testing_parents").first
+          assert_equal "testing_parents", fk.from_table
+          assert_equal "testing", fk.to_table
+        ensure
+          ActiveRecord::Base.pluralize_table_names = original_pluralize_table_names
+          @connection.drop_table "testing_parents"
```
Comment (meinac) [inline activerecord/test/cases/migration/references_foreign_key_test.rb]: I have to drop testing parent table here because I'm adding foreign key to it. If you don't drop it you can't drop testing table too.

**Comment by meinac** [comment]
@senny I believe this is ok now :)
I have to drop testing_parents table before the testing table because foreign key constraint will fail with foreign key constraint if I try to drop testing table before testing_parents table.

**Comment by meinac** [comment]
I've remove drop table for testing_parents table because I'm removing foreign key from this table inside of the test case so don't need to drop this table before testing table

**Comment by senny** [comment]
@meinac thank you.

I'll look into a backport to `4-2-stable`.
