### PR TITLE
Fix #12537 performance regression when preloading has_many_through association

### LINKED ISSUE #12537: Major performance regression when preloading has_many_through association
Between Rails 3.2 and 4.1.0 beta, the performance of preloading a has_many_through association has declined. A commit, #12090, brought performance back to the range of one third the speed of Rails 3.2. However, between a3dd738c38df634a46a2261a0de27fd31de7ae51 and the current codebase, the performance has again dropped approximately 5.5 times.

Here are some benchmarks.

```
                                         3.2.14 - postgresql
                                              user     system      total        real
limit 100 has_many                         0.070000   0.000000   0.070000 (  0.086018)
limit 100 has_many_through                 0.030000   0.000000   0.030000 (  0.034133)
limit 100 double has_many_through          0.040000   0.010000   0.050000 (  0.057401)
limit 1000 has_many                        0.110000   0.000000   0.110000 (  0.122771)
limit 1000 has_many_through                0.230000   0.010000   0.240000 (  0.249680)
limit 1000 double has_many_through         0.460000   0.000000   0.460000 (  0.488896)

                                         4.1.0.beta (a3dd738c38df634a46a2261a0de27fd31de7ae51) - postgresql
                                              user     system      total        real
limit 100 has_many                         0.060000   0.000000   0.060000 (  0.070222)
limit 100 has_many_through                 0.070000   0.010000   0.080000 (  0.075542)
limit 100 double has_many_through          0.090000   0.010000   0.100000 (  0.107504)
limit 1000 has_many                        0.130000   0.000000   0.130000 (  0.136422)
limit 1000 has_many_through                0.680000   0.010000   0.690000 (  0.719953)
limit 1000 double has_many_through         1.320000   0.010000   1.330000 (  1.343767)

                                         4.1.0.beta - postgresql
                                              user     system      total        real
limit 100 has_many                         0.020000   0.000000   0.020000 (  0.025983)
limit 100 has_many_through                 0.130000   0.000000   0.130000 (  0.140196)
limit 100 double has_many_through          0.130000   0.010000   0.140000 (  0.149074)
limit 1000 has_many                        0.140000   0.000000   0.140000 (  0.152584)
limit 1000 has_many_through                3.490000   0.030000   3.520000 (  3.542585)
limit 1000 double has_many_through         7.250000   0.030000   7.280000 (  7.390997)
```

To be clear, the issue does not occur using eager_load, only when using preload.

A quick look at the call graph shows invocations of hash[]= have jumped from 8865 to almost 9.4 million. 

```
# Rails 3.2.14     0.19%	 0.19%	 0.01	 0.01	 0.00	 0.00	 8865	     Hash#[]=
# Rails 4.1.0 beta 76.78%	 15.66%	 114.09	 23.27	 0.00	 90.82	 9384486	 Hash#[]=
```

I've created a gist for other to repeat my tests in case I've missed something major.
https://gist.github.com/njakobsen/6393783

Through a process of elimination, I identified a likely source of the regression to this commit e5299c1ef693ef434f55811027a7da975cd55ba5. All subsequent commits that I tested exhibited the slow performance, all preceding commits I tested did not. I know @tenderlove has been working on preloader recently, reducing the number of objects that are created, perhaps he can shed some light onto the major structural he's been applying, and how we might help optimize this section of code.

### PR DESCRIPTION
**Pull request by yuroyoro**
Fix #12537

I profiled the benchmark code that preloads has_many_through association,
and found that most of time spent by calling `CollectionAssociation#reader` method  in `associated_records_by_owner`.

Here is a result of profiling `associated_records_by_owner` method.
- https://gist.github.com/yuroyoro/b68f673c2ac24f0fe29a
- (dumpfile) https://www.dropbox.com/s/lqsqr86nrfrqvlq/stackprof-cpu-prelading-4.2-2015-03-10-12-40-24.dump?dl=0

`CollectionAssociation#reader` creates new `CollectionProxy` object if it doesn't exists.
But, instantiate `CollectionProxy` is expensive operation.
Because creating the `Relation` object by calling `Association#scope` is expensive,
and merging it into `CollectionProxy` is also.

https://github.com/rails/rails/commit/c86a32d7451c5d901620ac58630460915292f88b#commitcomment-5384529

In this case, the association's records are already loaded by the preloader.
It just read records by `Association#target` that returns loaded records,
instead of `reader` method.

Here are benchmark results.

```
================================================================================
3.2.21 - postgresql
================================================================================

Calculating -------------------------------------
  limit 100 has_many    12.000  i/100ms
limit 100 has_many_through
                         5.000  i/100ms
limit 100 double has_many_through
                         3.000  i/100ms
 limit 1000 has_many     1.000  i/100ms
limit 1000 has_many_through
                         1.000  i/100ms
limit 1000 double has_many_through
                         1.000  i/100ms
-------------------------------------------------
  limit 100 has_many    129.401  (± 3.9%) i/s -    648.000
limit 100 has_many_through
                         53.440  (± 7.5%) i/s -    270.000
limit 100 double has_many_through
                         31.399  (± 6.4%) i/s -    156.000
 limit 1000 has_many     15.410  (± 6.5%) i/s -     77.000
limit 1000 has_many_through
                          6.097  (± 0.0%) i/s -     31.000
limit 1000 double has_many_through
                          3.520  (± 0.0%) i/s -     18.000

================================================================================
5.0.0.alpha - postgresql
================================================================================

Calculating -------------------------------------
  limit 100 has_many     8.000  i/100ms
limit 100 has_many_through
                         1.000  i/100ms
limit 100 double has_many_through
                         1.000  i/100ms
 limit 1000 has_many     1.000  i/100ms
limit 1000 has_many_through
                         1.000  i/100ms
limit 1000 double has_many_through
                         1.000  i/100ms
-------------------------------------------------
  limit 100 has_many     92.615  (± 4.3%) i/s -    464.000
limit 100 has_many_through
                          8.574  (± 0.0%) i/s -     43.000
limit 100 double has_many_through
                          5.300  (± 0.0%) i/s -     27.000
 limit 1000 has_many     12.712  (± 0.0%) i/s -     64.000
limit 1000 has_many_through
                          0.892  (± 0.0%) i/s -      5.000  in   5.610751s
limit 1000 double has_many_through
                          0.516  (± 0.0%) i/s -      3.000  in   5.814872s

================================================================================
5.0.0.alpha (after) - postgresql
================================================================================

Calculating -------------------------------------
  limit 100 has_many     8.000  i/100ms
limit 100 has_many_through
                         3.000  i/100ms
limit 100 double has_many_through
                         1.000  i/100ms
 limit 1000 has_many     1.000  i/100ms
limit 1000 has_many_through
                         1.000  i/100ms
limit 1000 double has_many_through
                         1.000  i/100ms
-------------------------------------------------
  limit 100 has_many     91.012  (± 4.4%) i/s -    456.000
limit 100 has_many_through
                         31.822  (± 3.1%) i/s -    159.000
limit 100 double has_many_through
                         19.298  (± 5.2%) i/s -     97.000
 limit 1000 has_many     10.621  (± 0.0%) i/s -     54.000
limit 1000 has_many_through
                          3.767  (± 0.0%) i/s -     19.000
limit 1000 double has_many_through
                          2.144  (± 0.0%) i/s -     11.000
```

In the benchmark case "limit 1000 double has_many_through", it still slower than 3.2, but faster then master.

This is a benchmarks code that I used.

https://gist.github.com/yuroyoro/89fae1150e285658db45

### CODE REVIEW

File: activerecord/lib/active_record/associations/preloader/through_association.rb [hunk 1]
```diff
@@ -18,7 +18,8 @@ def associated_records_by_owner(preloader)
           through_records = owners.map do |owner|
             association = owner.association through_reflection.name
 
-            [owner, Array(association.reader)]
+            center = association.loaded? ? association.target : association.reader
```
Comment (kuldeepaggarwal) [inline activerecord/lib/active_record/associations/preloader/through_association.rb]: I think we can extract this logic into a method and use it at the both the places.

**Comment by kuldeepaggarwal** [comment]
@yuroyoro Can we add a test case for this?

File: activerecord/lib/active_record/associations/preloader/through_association.rb (hunk 1 above)
Comment (yuroyoro) [inline activerecord/lib/active_record/associations/preloader/through_association.rb]: I created a method `target_records_from_association` and put that line into it.

**Comment by yuroyoro** [comment]
I wrote test that asserts the `reader` method should never called when preloading has_many_through records.

I think this assertion will be failed when changing behavior of preloader on future.
So I commented why the preloader avoids calling `reader` in this case. 
For helping decision that this assertion should be modified or removed .

**Comment by kuldeepaggarwal** [comment]
Please squash your commits.

**Comment by yuroyoro** [comment]
Sorry, I squashed

**Comment by amatsuda** [comment]
@sgrif This looks great. Can you take a look?

**Comment by mrbrdo** [comment]
@rafaelfranca this is quite old, what is the status? has this already been fixed?

File: activerecord/lib/active_record/associations/preloader/through_association.rb [hunk 2]
```diff
@@ -89,6 +90,10 @@ def through_scope
 
           scope
         end
+
+        def target_records_from_association(association)
+          association.loaded? ? association.target : association.reader
```
Comment (bogdan) [inline activerecord/lib/active_record/associations/preloader/through_association.rb]: @yuroyoro why do you check against `loaded?` here? It seems that association is always loaded in this case and all tests remain green when I delete it. Can you add a test that fails without it?
