### PR TITLE
Ensure `file_fixture_path` is set even when Active Record is not present

### LINKED ISSUE #46529: `ActiveSupport::Testing::FileFixtures#file_fixture` fails when skipping Active Record
### Steps to reproduce

When generating an app with `--skip-active-record`, the `file_fixture` helper will fail with `no implicit conversion of nil into String` because `file_fixture_path` is only defined if `ActiveRecord::Base` is defined: https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/railties/lib/rails/test_help.rb#L15-L29

### Expected behavior

The helper should work when skipping Active Record fixtures - `test/fixtures/files` is still generated for the app and the file fixtures helper doesn't rely on any AR behaviour anyway.

### Actual behavior

```
$ bin/rails test test/models/foo_test.rb
Running 1 test in a single process (parallelization threshold is 50)
Run options: --seed 52272

# Running:

E

Error:
FooTest#test_case:
TypeError: no implicit conversion of nil into String
    test/models/foo_test.rb:27:in `load_fixture'
    test/models/foo_test.rb:10:in `block in <class:FooTest>'
```

The workaround is to set `file_fixture_path` manually on `ActiveSupport::TestCase`

```ruby
class ActiveSupport::TestCase
  # Run tests in parallel with specified workers
  parallelize(workers: :number_of_processors)

  # Add more helper methods to be used by all tests here...

  self.file_fixture_path = "#{Rails.root}/test/fixtures/files"
end
```

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #46529.

### CODE REVIEW

File: railties/lib/rails/test_help.rb [hunk 1]
```diff
@@ -31,6 +31,10 @@
   ActiveSupport.on_load(:action_dispatch_integration_test) do
     self.fixture_path = ActiveSupport::TestCase.fixture_path
   end
+else
+  ActiveSupport.on_load(:active_support_test_case) do
```
Comment (ghiculescu) [inline railties/lib/rails/test_help.rb:35]: It seems like the `if defined?(ActiveRecord::Base)` check should only wrap this code:

```ruby
  begin
    ActiveRecord::Migration.maintain_test_schema!
  rescue ActiveRecord::PendingMigrationError => e
    puts e.to_s.strip
    exit 1
  end
```

Since nothing else inside that if statement interacts with Active Record.

Comment (ghiculescu) [inline railties/lib/rails/test_help.rb:35]: What do you think of this as a solution? https://gist.github.com/ghiculescu/3e7a1f40cdae0617e7530027ce876f12

It removes the duplicated code, instead it just wraps the bits that interact with AR in if statements.

Comment (fatkodima) [reply railties/lib/rails/test_help.rb:35]: `fixture_path` is defined in `ActiveRecord::TestFixtures`, so there is a need to add more conditions. Not sure which variant will become better.

Comment (ghiculescu) [reply railties/lib/rails/test_help.rb:35]: Ahh good point, this is probably better then.
