### PR TITLE
[Fix #40109] Incorrect joins for polymorphic `has_many through:` with association scope

### LINKED ISSUE #40109: has_many through with scope block, STI and polymorphic associations that worked in 5.0 breaks in 6.0+
We have a `has_many …, through:` that also involves a scope block, STI and polymorphic associations (bingo!).

Joining on this association worked fine in Rails 5.0.7.2, but broke when updating to 5.1.7. We've checked and it also fails on 5.2.4.3 and 6.0.3.2.

### Steps to reproduce

UPDATE: See reproduction script in https://github.com/rails/rails/issues/40109#issuecomment-680799482 instead.

Set up associations similar to

``` ruby
class Item < ApplicationRecord
  has_many :invoice_lines, as: :invoicable

  has_many :item_invoices,
    -> { where("buyer_invoices.type" => ItemInvoice.name).distinct },  # STI stores leaf class.
    through: :invoice_lines,
    source: :invoice,
    source_type: "BuyerInvoice"  # Polymorphic stores base class.

class InvoiceLine < ApplicationRecord
  belongs_to :invoicable, polymorphic: true  # E.g. Item
  belongs_to :invoice, polymorphic: true  # BuyerInvoice or SellerInvoice
end
```

For context, `ItemInvoice` is a STI subclass of `BuyerInvoice`. There is a `buyer_invoices` table. `SellerInvoice`/`seller_invoices` are a completely separate table and inheritance chain.

Now, try this:

```
Item.joins(:item_invoices).to_a
```

### Expected behavior

It works, returning an array of invoices.

### Actual behavior

It raises

> ActiveRecord::StatementInvalid:
>  PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "buyer_invoices"

The reason is that it applies the scope block *twice*. Both when joining `invoice_lines` and when joining `buyer_invoices`.

But the condition in the scope block is not valid when joining `invoice_lines` (there's no `buyer_invoices` table to reference yet) and so it causes this error.

This is the query (I renamed some things to simplify for this example, believe it or not, so I hope I got it right):

``` sql
SELECT "items".* FROM "items"
INNER JOIN "invoice_lines"
  ON "invoice_lines"."invoicable_type" = 'Item'
  AND "invoice_lines"."invoice_type" = 'BuyerInvoice'
  AND "invoice_lines"."invoicable_id" = "items"."id"
  AND "invoices"."type" = 'ItemInvoice'  -- This shouldn't be here!
INNER JOIN "invoices"
  ON "invoices"."type" = 'ItemInvoice'
  AND "invoices"."id" = "invoice_lines"."invoice_id"
```

Note that the `"invoices"."type" = 'ItemInvoice'` condition is included both when joining invoice lines and when joining invoices. In Rails 5.0, it was only included when joining invoices, and then the query worked fine.

`some_item.item_invoices` works fine. The issue happens when `join`ing (or `eager_load`ing, or `include`ing if it chooses to use JOINs).

We've worked around it by joining an association without the condition, and then adding the condition on top: https://stackoverflow.com/a/63506810/6962 But this makes our code uglier and adds duplication.

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.6.6

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

Fixes https://github.com/rails/rails/issues/40109

### Detail

Updates `ActiveRecord::Reflection::PolymorphicReflection#join_scopes` to not apply the previous reflection's join scopes if it's a through reflection, as the scope will eventually be built in the context of the polymorphic reflection.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/test/cases/associations/nested_through_associations_test.rb [hunk 1]
```diff
@@ -639,6 +639,19 @@ def test_polymorphic_has_many_through_joined_different_table_twice
...
+    Post.delete_all
+
+    post = Post.create!(title: "Catchy Title", body: "Interesting body.")
+    category = Category.create!(name: "Anything")
+    Post::CategoryPost.create!(post: post, category: category)
+
+    author = authors(:bob)
+    Essay.create!(writer: author, category: category)
+
+    assert_equal 1, Post.joins(:authors_of_essays_named_bob).count
```
Comment (joshuay03) [inline activerecord/test/cases/associations/nested_through_associations_test.rb:652]: Before patch:

Screenshot 2024-04-06 at 1 14 02 PM

Comment (joshuay03) [reply activerecord/test/cases/associations/nested_through_associations_test.rb:652]: ### SQL comparison

**Before:**

```SQL
"SELECT \"posts\".* FROM \"posts\" INNER JOIN \"categories_posts\" ON \"categories_posts\".\"post_id\" = \"posts\".\"id\" INNER JOIN \"categories\" ON \"categories\".\"id\" = \"categories_posts\".\"category_id\" INNER JOIN \"essays\" ON \"essays\".\"name\" = 'Bob' AND \"essays\".\"writer_type\" = 'Author' AND \"essays\".\"category_id\" = \"categories\".\"name\" INNER JOIN \"authors\" ON \"authors\".\"name\" = 'Bob' AND \"authors\".\"name\" = \"essays\".\"writer_id\""
```

**After:**

```SQL
"SELECT \"posts\".* FROM \"posts\" INNER JOIN \"categories_posts\" ON \"categories_posts\".\"post_id\" = \"posts\".\"id\" INNER JOIN \"categories\" ON \"categories\".\"id\" = \"categories_posts\".\"category_id\" INNER JOIN \"essays\" ON \"essays\".\"writer_type\" = 'Author' AND \"essays\".\"category_id\" = \"categories\".\"name\" INNER JOIN \"authors\" ON \"authors\".\"name\" = 'Bob' AND \"authors\".\"name\" = \"essays\".\"writer_id\""
```
