### PR TITLE
Rack 3 static lowercase headers.

### LINKED ISSUE #47456: Lower case HTTP headers when rails serves files
### Steps to reproduce

When using Rails Edge, some HTTP headers appears like `content-type` next to `Context-Type`.
To reproduce, from a new Rails application:
```bash
% rails assets:precompile
I, [2023-02-21T17:56:19.789769 #55874]  INFO -- : Writing /Users/stac/project/public/assets/application-e908707cbd3f4136efe68dfbbecf05e37659161b146c4ac3c9d41acd50cb4b90.css
I, [2023-02-21T17:56:19.789917 #55874]  INFO -- : Writing /Users/stac/project/public/assets/application-e908707cbd3f4136efe68dfbbecf05e37659161b146c4ac3c9d41acd50cb4b90.css.gz
[...]
% RAILS_SERVE_STATIC_FILES=1 RAILS_ENV=production rails s
Rack::Server is deprecated and replaced by Rackup::Server
Rack::Handler is deprecated and replaced by Rackup::Handler
=> Booting Puma
=> Rails 7.1.0.alpha application starting in production http://0.0.0.0:3000
=> Run `bin/rails server --help` for more startup options
/Users/lstacul/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-3.0.4.1/lib/rack/chunked.rb:6: warning: Rack::Chunked is deprecated and will be removed in Rack 3.1
Puma starting in single mode...
* Puma version: 5.6.5 (ruby 3.1.3-p185) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 56239
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
```
Then we try to query the statics (for clarity I only query headers)
```bash
% curl -I http://localhost:3000/assets/application-e908707cbd3f4136efe68dfbbecf05e37659161b146c4ac3c9d41acd50cb4b90.css
HTTP/1.1 200 OK
last-modified: Tue, 21 Feb 2023 16:56:19 GMT
content-type: text/css
Content-Type: text/css
Vary: Accept-Encoding
Content-Length: 661272
```
If we accept compressed resources, we can evan have different `content-type` values:
```bash
% curl -I 'http://localhost:3000/assets/application-e908707cbd3f4136efe68dfbbecf05e37659161b146c4ac3c9d41acd50cb4b90.css' -H 'Accept: text/css,*/*;q=0.1' -H 'Accept-Encoding: gzip, deflate, br'
HTTP/1.1 200 OK
last-modified: Tue, 21 Feb 2023 16:56:19 GMT
content-type: application/x-gzip
Content-Type: text/css
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 45665
``` 

### Expected behavior
When I run the same against Rails 7.0.4.1 (stable), it does not show any lower case HTTP header.

```bash
% curl -I 'http://localhost:3000/assets/application-e908707cbd3f4136efe68dfbbecf05e37659161b146c4ac3c9d41acd50cb4b90.css' -H 'Accept: text/css,*/*;q=0.1' -H 'Accept-Encoding: gzip, deflate, br'
HTTP/1.1 200 OK
Last-Modified: Tue, 21 Feb 2023 16:56:19 GMT
Content-Type: text/css
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 45665
```

### Actual behavior

HTTP reply shows lower case header with potentially different value compared to the non-lower case counterparts. On some other cases, I can see `last-modified` header.

This can fool the browsers. For instance Chrome errors with the following message:
> Failed ro load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/x-gzip". Strict MIME type checking is enforced for module scripts per HTML spec.

### System configuration
**Rails version**: Rails 7.1.0.alpha (commit: 1bf6dc00fb350ca48cece7b96a31e828e79a8c0a (yesterday))

**Ruby version**: ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [arm64-darwin22]

### PR DESCRIPTION
**Pull request by ioquatix**
`ActionDispatch::Static` uses mixed-case headers and merges them with lower case headers. This produces duplicate headers. Prefer lowercase headers to avoid this situation.

Fixes <https://github.com/rails/rails/issues/47456>.

### CODE REVIEW

File: actionpack/lib/action_dispatch/middleware/static.rb [hunk 1]
```diff
@@ -20,6 +20,7 @@ def initialize(app, path, index: "index", headers: {})
     end
 
     def call(env)
+      binding.irb
```
Comment (adrienpoly) [inline actionpack/lib/action_dispatch/middleware/static.rb:23]:
```suggestion
```

Comment (ioquatix) [reply actionpack/lib/action_dispatch/middleware/static.rb]: Oops :) Thanks!

**Comment by zzak** [comment]
Should this behavior depend on which version of Rack they are using? I'm not sure.

**Comment by ioquatix** [comment]
@zzak no, lower case headers should always be preferred. Rack 2 specifically calls out this behaviour, i.e. assuming the response headers is a hash. The only safe way to do this on Rack 2 is to use `Rack::Utils::HeaderHash` or manually call `response.headers.each{|k, v| ...}` and build your own hash. That's why we changed it for Rack 3, because the Rack 2 behaviour is at best inefficient and at worst broken.

**Comment by ioquatix** [comment]
@matthewd thanks!!

**Comment by smridge** [comment]
> Should this behavior depend on which version of Rack they are using? I'm not sure.

I believe so. This broke for me when doing a `assets:precompile` on the Rails `main` branch with the following browser error:
```
Expected a JavaScript module script but the server responded with a MIME type of “application/x-gzip”
```

Once I force updated `rack-session` to version `2.0.0` to in turn allow for `rack` version `3`, all was good. My guess is that this change was the cause but I'm not 100% sure on that.

**Comment by ioquatix** [comment]
Code which fails in this way is almost certainly already incorrect/buggy. However, in many cases, it worked sufficiently well since people ossified "Title-Case" style headers.

I don't argue that it's good or bad, it's clearly incorrect - but usually it worked.

Now, we deliberately broke it because it's the normal form as recommended by the modern RFCs. Some cases which were "incorrect but worked" are now "incorrect and don't work" because of this change. Those places can be made compatible by using header normalization, which is "correct and works".

**Comment by smridge** [comment]
> Now, we deliberately broke it because it's the normal form as recommended by the modern RFCs. Some cases which were "incorrect but worked" are now "incorrect and don't work" because of this change. Those places can be made compatible by using header normalization, which is "correct and works".

Ya, I think it's worth calling out it's a `BREAKING CHANGE` in the `CHANGELOG`. It took be a minute to determine this change was likely the cause. [As it stands](https://github.com/rails/rails/commit/859b526c5b9f1e516df3fc1b388c949da3fa9c4e), it does not look like Rails 7.1 will require rack 3 which would make rails "just work".

**Comment by ghiculescu** [comment]
FYI seems like there may still be an issue here https://github.com/rails/rails/issues/48225
