### PR TITLE
Anchor BacktraceCleaner gem filter regexp

### LINKED ISSUE #40196: ActiveSupport::BacktraceCleaner might wrongly remove supposed gem path
It seems that the `ActiveSupport::BacktraceCleaner` is possibly removing parts of the backtrace paths, which resembles gem path but they are actually not gem path.
E.g. given that:
* the `gem_paths` RegExp [[1]] is `(?-mix:(\/builddir\/\.gem\/ruby|\/usr\/share\/gems|\/usr\/local\/share\/gems)\/(bundler\/)?gems\/([^\/]+)-([\w.]+)\/(.*))`
* and there is this backtrace line `/builddir/build/BUILD/web-console-4.0.4/usr/share/gems/gems/web-console-4.0.4/lib/web_console/evaluator.rb:28:in `eval'`,
* the output of such filter will be ```/builddir/build/BUILD/web-console-4.0.4web-console (4.0.4) lib/web_console/evaluator.rb:28:in `eval'``` which is wrong.

The possible fix might check for additional whitespace befor the path, e.g.:

~~~
$ git diff
diff --git a/activesupport/lib/active_support/backtrace_cleaner.rb b/activesupport/lib/active_support/backtrace_cleaner.rb
index ad80b8855f..785af44ba0 100644
--- a/activesupport/lib/active_support/backtrace_cleaner.rb
+++ b/activesupport/lib/active_support/backtrace_cleaner.rb
@@ -91,7 +91,7 @@ def add_gem_filter
         gems_paths = (Gem.path | [Gem.default_dir]).map { |p| Regexp.escape(p) }
         return if gems_paths.empty?
 
-        gems_regexp = %r{(#{gems_paths.join('|')})/(bundler/)?gems/([^/]+)-([\w.]+)/(.*)}
+        gems_regexp = %r{(#{gems_paths.map {|path| "\s#{path}"}.join('|')})/(bundler/)?gems/([^/]+)-([\w.]+)/(.*)}
         gems_result = '\3 (\4) \5'
         add_filter { |line| line.sub(gems_regexp, gems_result) }
       end
~~~

[1]: https://github.com/rails/rails/blob/580eefe1bc5d7241a4b2f3ee863523c5b8fd2f80/activesupport/lib/active_support/backtrace_cleaner.rb#L94

### PR DESCRIPTION
**Pull request by jonathanhefner**
This ensures the default gem filter does not affect backtrace lines that have a subpath incidentally matching a gem path.

Fixes #40196.

### CODE REVIEW

File: activesupport/lib/active_support/backtrace_cleaner.rb [hunk 1]
```diff
@@ -91,7 +91,7 @@ def add_gem_filter
         gems_paths = (Gem.path | [Gem.default_dir]).map { |p| Regexp.escape(p) }
```
Comment (eugeneius) [inline activesupport/lib/active_support/backtrace_cleaner.rb:91]: I was concerned about relative paths in `Gem.path`, but it looks like they're always expanded:

```bash
$ GEM_PATH=relative_gems ruby -e 'p Gem.path'
["/Users/eugene/test/relative_gems", "/Users/eugene/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0"]
```

https://github.com/rubygems/rubygems/blob/v3.1.4/lib/rubygems/path_support.rb#L71
