### PR TITLE
Address StarStarMimeControllerTest#test_javascript_with_no_format_only_star_star failure

### LINKED ISSUE #38094: StarStarMimeControllerTest#test_javascript_with_no_format_only_star_star sometime fails
StarStarMimeControllerTest#test_javascript_with_no_format_only_star_star sometime fails at Rails CI as follows.

https://buildkite.com/rails/rails/builds/65916#23a83567-6812-4dd7-b617-85c4ad712775
https://buildkite.com/rails/rails/builds/65946#2a4368fb-c7fa-4d34-a7a7-0f9378af3561
https://buildkite.com/rails/rails/builds/65943#70208757-6778-45ee-bf8a-eb3abdd9db08

I have not found how to always reproduce this error yet.

### Steps to reproduce
```
% cd actionpack
% bundle exec ruby -w -Itest test/controller/mime/accept_format_test.rb --seed 63915
```

### Expected behavior
It should pass.

### Actual behavior

It fails frequently fails like 7 of 10 attempts.

```ruby
% bundle exec ruby -w -Itest test/controller/mime/accept_format_test.rb --seed 63915
Run options: --seed 63915

# Running:

.....E

Error:
StarStarMimeControllerTest#test_javascript_with_no_format_only_star_star:
ArgumentError: Invalid formats: :iphone
    /Users/yahonda/src/github.com/yahonda/rails/actionview/lib/action_view/lookup_context.rb:287:in `formats='
    /Users/yahonda/src/github.com/yahonda/rails/actionview/lib/action_view/view_paths.rb:11:in `formats='
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/rendering.rb:29:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/callbacks.rb:98:in `run_callbacks'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/abstract_controller/callbacks.rb:41:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/rescue.rb:22:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/notifications.rb:203:in `block in instrument'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/notifications.rb:203:in `instrument'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/abstract_controller/base.rb:136:in `process'
    /Users/yahonda/src/github.com/yahonda/rails/actionview/lib/action_view/rendering.rb:39:in `process'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal.rb:190:in `dispatch'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/test_case.rb:512:in `process'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/test_case.rb:390:in `get'
    test/controller/mime/accept_format_test.rb:28:in `test_javascript_with_no_format_only_star_star'


rails test test/controller/mime/accept_format_test.rb:26



Finished in 0.228798s, 26.2240 runs/s, 39.3360 assertions/s.
6 runs, 9 assertions, 0 failures, 1 errors, 0 skips
%
```
### System configuration
**Rails version**:master branch

**Ruby version**:ruby 2.7.0dev (2019-12-25T09:47:47Z master e1e1d92277) [x86_64-darwin19]

### PR DESCRIPTION
**Pull request by yahonda**
### Summary

This pull request addresses StarStarMimeControllerTest#test_javascript_with_no_format_only_star_star failure.

Fix #38094

* Steps to reproduce:

```ruby
% cd actionpack
% MT_CPU=0 bundle exec ruby -w -Itest test/controller/mime/accept_format_test.rb -n "/^(?:MimeControllerLayoutsTest#(?:test_missing_layout_renders_properly)|StarStarMimeControllerTest#(?:test_javascript_with_no_format_only_star_star))$/" --verbose --seed 15759
```

* Actual result without this commit:

```ruby
% cd actionpack
% MT_CPU=0 bundle exec ruby -w -Itest test/controller/mime/accept_format_test.rb -n "/^(?:MimeControllerLayoutsTest#(?:test_missing_layout_renders_properly)|StarStarMimeControllerTest#(?:test_javascript_with_no_format_only_star_star))$/" --verbose --seed 15759
Run options: -n "/^(?:MimeControllerLayoutsTest#(?:test_missing_layout_renders_properly)|StarStarMimeControllerTest#(?:test_javascript_with_no_format_only_star_star))$/" --verbose --seed 15759

MimeControllerLayoutsTest#test_missing_layout_renders_properly = 0.18 s = .
StarStarMimeControllerTest#test_javascript_with_no_format_only_star_star = 0.00 s = E

Error:
StarStarMimeControllerTest#test_javascript_with_no_format_only_star_star:
ArgumentError: Invalid formats: :iphone
    /Users/yahonda/src/github.com/yahonda/rails/actionview/lib/action_view/lookup_context.rb:287:in `formats='
    /Users/yahonda/src/github.com/yahonda/rails/actionview/lib/action_view/view_paths.rb:11:in `formats='
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/rendering.rb:29:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/callbacks.rb:98:in `run_callbacks'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/abstract_controller/callbacks.rb:41:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/rescue.rb:22:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/notifications.rb:203:in `block in instrument'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/yahonda/src/github.com/yahonda/rails/activesupport/lib/active_support/notifications.rb:203:in `instrument'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/abstract_controller/base.rb:136:in `process'
    /Users/yahonda/src/github.com/yahonda/rails/actionview/lib/action_view/rendering.rb:39:in `process'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/metal.rb:190:in `dispatch'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/test_case.rb:512:in `process'
    /Users/yahonda/src/github.com/yahonda/rails/actionpack/lib/action_controller/test_case.rb:390:in `get'
    test/controller/mime/accept_format_test.rb:28:in `test_javascript_with_no_format_only_star_star'

rails test test/controller/mime/accept_format_test.rb:26

Finished in 0.180610s, 11.0736 runs/s, 11.0736 assertions/s.
2 runs, 2 assertions, 0 failures, 1 errors, 0 skips
%
```

* How to diagnose this error:

At first Restore `require "action_view/base"` to `actionpack/lib/action_dispatch/middleware/debug_exceptions.rb` addresses this error,
then isolated which lines are required then found this line is required.

https://github.com/rails/rails/blob/22483b86a6c779743b30e2f23bb46accfbf96b28/actionpack/lib/action_dispatch.rb#L117

```ruby
  ActionView::Base.default_formats ||= Mime::SET.symbols
```

### CODE REVIEW

**Comment by kaspth** [comment]
@yahonda thanks for the detailed reports and fix 🙏

File: actionpack/test/controller/mime/accept_format_test.rb [hunk 1]
```diff
@@ -1,6 +1,7 @@
 # frozen_string_literal: true
 
 require "abstract_unit"
+ActionView::Base.default_formats ||= Mime::SET.symbols
```
Comment (kaspth) [inline actionpack/test/controller/mime/accept_format_test.rb]: @Edouard-chin just double checking, is there another way we should express this? Or make it obsolete another way? From the issue it seems like this was more fallout from https://github.com/rails/rails/pull/38026 😊

Comment (Edouard-chin) [reply actionpack/test/controller/mime/accept_format_test.rb]: 👋 Thanks for investigating the issue @yahonda ! I need to dig a bit deeper to understand the issue. I don't understand yet why this test ever worked since https://github.com/rails/rails/blob/22483b86a6c779743b30e2f23bb46accfbf96b28/actionpack/lib/action_dispatch.rb#L117 shouldn't have been evaluated as AFAIK we don't run railtie in actionpack test suite.  Will post back when I understand a bit more
