### PR TITLE
[close #24435] Send user_supplied_options to server

### LINKED ISSUE #24435: Rails 5 - Puma default port does not take effect
Especially prevents from comfortable SOA development, as you can't start different services at the same time and test the interactions between them.
### Steps to reproduce
1. Create new rails project (normal or api).
2. Change a line in `config/puma.rb` to: `port ENV.fetch("PORT") { 3010 }`.
3. Run `$ rails s`.
### Expected behavior

Puma server should run on port `3010`.
### Actual behavior

`Listening on tcp://localhost:3000`
Puma server runs on port `3000` instead of `3010`.
### System configuration

**Rails version**: `5.0.0.beta3`

**Ruby version**: `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]`

### PR DESCRIPTION
**Pull request by schneems**
Currently when Puma gets a `:Port` it doesn't know if it is Rails' default port or if it is one that is specified by a user. Because of this it assumes that the port passed in is always a user defined port and therefor 3000 always "wins" even if you specify `port` inside of the `config/puma.rb` file when booting your server with `rails s`.

The fix is to record the options that are explicitly passed in from the user and pass those to the Puma server (or all servers really). Puma then has enough information to know when `:Port` is the default and when it is user defined. I went ahead and did this for all values rails server exposes as server side options for completeness.

The hardest thing was converting the input say `-p` or `--port` into the appropriate "name", in this case `Port`. There may be a more straightforward way to do this with Thor, but I'm not an expert here.

### CODE REVIEW

**Comment by schneems** [comment]
cc/ @nateberkopec @evanphx

**Review by rafaelfranca — APPROVED** [review]
LGTM

**Review by maclover7 — CHANGES_REQUESTED** [review]
Looks good, can you squash down?

File: railties/lib/rails/commands/server/server_command.rb [hunk 1]
```diff
@@ -133,22 +133,53 @@ def perform
...
+                end
+                user_supplied_options << name
+              end
+            end
+            user_supplied_options
+          end
+        end
+
         def port
           ENV.fetch("PORT", options[:port]).to_i
```
Comment (matthewd) [inline railties/lib/rails/commands/server/server_command.rb]: Seems like `ENV["PORT"]` should count as user-supplied for our purposes here, too.

Comment (schneems) [inline railties/lib/rails/commands/server/server_command.rb]: Good call.

**Comment by swrobel** [comment]
Any chance of this making it into 5.0.2?

**Comment by schneems** [comment]
We can backport it, however right now it does nothing until Puma is updated to deal with the extra information.

**Comment by rafaelfranca** [comment]
5.0.2 is pass the backport phase out, but in 5.0.3 is possible
