### PR TITLE
Fix derived foreign key to return correctly when association id is part of query constraints

### LINKED ISSUE #50346: Incorrect derived foreign key for models with query constraints
### Steps to reproduce

When we initialise a model with an associated active record object, the foreign key for the associated record is not being derived correctly when the associated model is a part of query constraints.

This works correctly for without query constraints.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "7.1"
  gem "sqlite3"
  gem 'pry'
end

require "active_record"
require "logger"
require "minitest/autorun"
require 'pry'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  create_table :tenants, force: true do |t|
    t.string :name
  end

  create_table :comments, force: true do |t|
    t.integer :tenant_id
    t.integer :post_id
    t.integer :author_id
    t.string :body
    t.integer :position
  end

  create_table :authors, force: true do |t|
    t.integer :tenant_id
  end
end

class Tenant < ActiveRecord::Base
end

class Author < ActiveRecord::Base
  query_constraints :tenant_id, :id

  belongs_to :tenant
end

class Comment < ActiveRecord::Base
  query_constraints :tenant_id, :id

  belongs_to :tenant
  belongs_to :author
end

class BugTest < Minitest::Test
  def test_assoc
    tenant = Tenant.create!
    comment = Comment.new(body: "hello", tenant: tenant, author: Author.new(tenant: tenant))

    assert_equal tenant, comment.tenant
    assert_equal tenant.id, comment.tenant_id
  end
end

# Your reproduction script goes here
```

### Expected behavior

- `comment.tenent_id` should return the value for `tenant.id`

### Actual behavior

- `comment.tenant_id` returns `nil`

### System configuration
**Rails version**: 7.1

**Ruby version**: 2.7.8

### PR DESCRIPTION
**Pull request by iamradioactive**
### Motivation / Background

Fixes #50346 

### Detail

This PR updates the method [derive_fk_query_constraints](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/reflection.rb#L785) to return correct value when association id is part of query constraints.

Context
- Model having Query constraints as `[:associated_model_id, :id]`
- Model having belong to association with `associated_model`

Current Behaviour
- Derived foreign key value is `[associated_model_id, associated_model_id]`

Updated Behaviour
- Derived foreign key value should be `associated_model_id`

### Additional information

Please refer to #50346 

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by iamradioactive** [comment]
Are these results flaky? Build for the same commit failed for Ruby 3.0 when it was pushed as part of #50297 and it's passing now.

Old Reference : https://buildkite.com/rails/rails/builds/102725
Current Reference: https://buildkite.com/rails/rails/builds/102744

File: activerecord/lib/active_record/reflection.rb [hunk 1]
```diff
@@ -804,6 +804,8 @@ def derive_fk_query_constraints(foreign_key)
             MSG
           end
 
+          return foreign_key if primary_query_constraints.include?(foreign_key)
```
Comment (rubyrider) [inline activerecord/lib/active_record/reflection.rb:807]: The expected return of this method is either an array of both pk and fk or an exception. 
https://github.com/rails/rails/pull/50347/files#diff-b1aed4985f41ad87dc1be30472b728a19f1a7354f25ce71bf6ce9a7744a9cd0dR814

This change may break unhidingly. So I consider to rather fix the case in the #foreign_key and add a test case to demonstrate a fix. The foreign key should handle the result and return the right key when dealing with this method.

**Review by rubyrider — COMMENTED** [review]
I feel like this changes will break the nature of return objects of this method.

File: activerecord/lib/active_record/reflection.rb (hunk 1 above)
Comment (rubyrider) [reply activerecord/lib/active_record/reflection.rb:807]: I have prepared a suggestion for you. My suggestion passes your provided test cases reported in the bug https://github.com/rails/rails/issues/50346 

My suggestion is here: https://github.com/rubyrider/rails/pull/2

Feel free if you like to pick it up. :)

Comment (iamradioactive) [reply activerecord/lib/active_record/reflection.rb:807]: @rubyrider, I could not find this method being used anywhere else in the code. I don't anticipate any issues, the return type of its caller `foreign_key` seems to adhere to a similar pattern. However, if you've found something that suggests otherwise, could you provide a script to reproduce that scenario?

As for moving the logic to the foreign_key method, I believe it is best placed here as all the behaviour related to the query constraints is encapsulated in this method.

I reviewed the changes you proposed. While they address the current scenario, they don't extend the behavior to provide support for it. What I mean by that is they don't take into account the valid cases where the expected result is an array, which is the case with every other scenario involving query constraints except the current one.

Comment (rubyrider) [reply activerecord/lib/active_record/reflection.rb:807]: so my solution actually fixes the test you provided in your issue. you may check :) Basically the issue what I could see was with the foreign_key. well I am hapoy to correct myself. :)

Comment (iamradioactive) [reply activerecord/lib/active_record/reflection.rb:807]: Well, It is not about fixing a test case. In general, it should be about fixing a behaviour or extending it. Query constraints were introduced to make efficient queries using composite keys. You are changing that behaviour by turning the derived key to a single valued attribute again.

I request **Core members** or anyone familiar with the Query Constraints feature to correct me if I'm wrong. Feel free to add any other comments as well.

Let me try to convey my point using the same example. I will make a comparison on the return values for the `foreign_key` method which is going to be used to perform a query on the association and manage stale state.

---
#### Without Query Constraints

`comment.author`

- Expected : author_id
- Actual : author_id

`comment.tenant`

- Expected: tenant_id
- Actual : tenant_id
---
#### With Query Constraints

`comment.author`

- Expected : [tenant_id, author_id]
- Actual : [tenant_id, author_id]

`comment.tenant`

- Expected: tenant_id
- **Actual : [tenant_id, tenant_id]**
- This is the case which needs to be fixed
---

For additional context, When using query constraints expected query to fetch an Author for a comment should be 

`SELECT "authors".* FROM "authors" WHERE "authors"."tenant_id" = ? AND "authors"."id" = ? LIMIT ?` 


I hope it makes sense.

Comment (rubyrider) [reply activerecord/lib/active_record/reflection.rb:807]: @iamradioactive got your point! I am happy to work on this. So is there someone from the core who can contribute a little to  Query Constraints feature?

**Review by nvasilevski — APPROVED** [review]
Indeed there is an issue and the fix seems correct

**Comment by spuyet** [comment]
@nvasilevski can we merge these changes and put it in the next rails release please ?

**Comment by eileencodes** [comment]
Thanks for the PR!

Backported to 7-1-stable in e58d59ce489f7b7c48c0ace1b9d2ac03cb458258
