### PR TITLE
Disable session in ActiveStorage blobs and representations proxy controllers

### LINKED ISSUE #44136: Delivering assets through CloudFlare requires monkey-patch
### Steps to reproduce

It appears that delivering ActiveStorage assets through CloudFlare (free plan) can be done as suggested [here](https://edgeguides.rubyonrails.org/active_storage_overview.html#proxy-mode) + [here](https://github.com/rails/rails/pull/34477#issuecomment-660490231):
- add `Rails.application.config.active_storage.resolve_model_to_route = :rails_storage_proxy` to `config/initializers/active_storage.rb` OR use `rails_storage_proxy_path` in the views (e.g. `rails_storage_proxy_path(content.poster.variant(resize_to_limit: [size, size]))`). There is it seems no need to define a `direct :cdn_image` like in the docs, as the CDN host remains the same when using CloudFlare.
- monkey-patch `request.session_options[:skip] = true` in the `ProxyController`s ([ref](https://github.com/rails/rails/pull/34477#issuecomment-660490231))

### Expected behavior

- No monkey-patch should be needed. 
- It would be helpful to have some documentation to use CloudFlare with ActiveStorage.

### Actual behavior

After doing the above, I can see my images have headers `cache-control: public, max-age=3155695200` and `cf-cache-status: HIT` (after the second request). However, a monkey-patch was necessary to achieve this, so @zzak [recommended](https://github.com/rails/rails/pull/42363#issuecomment-1008824861) I open this issue.

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.3

### PR DESCRIPTION
**Pull request by brunoprietog**
### Motivation / Background

When configuring ActiveStorage with resolve_model_to_route in rails_storage_proxy, you would expect a CDN such as CloudFlare to cache the files. However, in the case of CloudFlare, by default, anything that has session cookies will not cache them. To work around this you can use custom rules or patch these ActiveStorage proxy controllers.

### Detail

Session now is disabled in `ActiveStorage::Blobs::ProxyController` and `ActiveStorage::Representations::ProxyController`, including the new concern `ActiveStorage::DisableSession` in both controllers that does the work.

This way it will not be necessary to create custom rules and works by default.

Thanks to @fleck for the idea in this [comment](https://github.com/rails/rails/pull/34477#issuecomment-660490231).

Fixes #44136

### Additional information

I'm not sure if or how to test this, because there is no way to access the session in `ActionDispatch::IntegrationTest`.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by brenogazzola** [comment]
Beyond CDN compatibility, this will also prevent a footgun for developers who are starting to handle on their own infra and want to use something like nginx object cache, where they cache the file but forget to remove the `Set-Cookie` header from the response doing so. 

This is a problem because rails uses said header to store its session, which might contain sensitive data. Worst case scenario, it might contain the ID of the logged user, which means that when the file is served, the user will be automatically switched to a different account.

File: activestorage/app/controllers/concerns/active_storage/disable_session.rb [hunk 1]
```diff
@@ -0,0 +1,13 @@
+# frozen_string_literal: true
+
+# This concern disables the session in order to allow caching by default in some CDNs as CloudFlare.
+
```
Comment (rafaelfranca) [inline activestorage/app/controllers/concerns/active_storage/disable_session.rb:4]:
```suggestion
```
