### PR TITLE
Fix assignment for frozen value in HWIA

### LINKED ISSUE #18550: Cannot assign a frozen Array to a HashWithIndifferentAccess
This was broken in Rails 4.0, because `ActiveSupport::HashWithIndifferentAccess#convert_value` calls `#map!` on the frozen value, not a dup, which raises the exception. I presume that was an optimisation? A check for `#frozen?` would fix this. Here's a demo:

```
Loading development environment (Rails 4.2.0)
> value = [1, 2, 3].freeze
 => [1, 2, 3]
> hash = {}.with_indifferent_access
 => {}
> hash[:key] = value
RuntimeError: can't modify frozen Array
```

### PR DESCRIPTION
**Pull request by aditya-kapoor**
Fixes #18550

### CODE REVIEW

File: activesupport/lib/active_support/hash_with_indifferent_access.rb [hunk 1]
```diff
@@ -94,7 +94,11 @@ def self.[](*args)
     #
     # This value can be later fetched using either +:key+ or +'key'+.
     def []=(key, value)
-      regular_writer(convert_key(key), convert_value(value, for: :assignment))
+      if value.frozen?
+        regular_writer(convert_key(key), convert_value(value))
+      else
+        regular_writer(convert_key(key), convert_value(value, for: :assignment))
+      end
```
Comment (jasonhutchens) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: Sorry, but I think this fix is at the wrong level, because `convert_value` recurses into `Hash` and `Array` values, and may hit a frozen object deeper down. Probably better for `convert_value` to check `frozen?` internally.

Comment (aditya-kapoor) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: I initially followed that approach but @senny fixed the same in https://github.com/rails/rails/pull/10784, that would have a 'side effect' as described in the PR.

Comment (jasonhutchens) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: :+1: thanks for the heads-up, have added to the discussion on the bug

Comment (aditya-kapoor) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: :green_heart:

File: activesupport/lib/active_support/hash_with_indifferent_access.rb [hunk 2]
```diff
@@ -94,7 +94,11 @@ def self.[](*args)
     #
     # This value can be later fetched using either +:key+ or +'key'+.
     def []=(key, value)
-      regular_writer(convert_key(key), convert_value(value, for: :assignment))
```
Comment (egilburg) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: How about

```ruby
converted_value = if value.frozen?
  convert_value(value)
else
  convert_value(value, for: :assignment)
end

regular_writer(convert_key(key), converted_value)

Comment (aditya-kapoor) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: Yes looks much better... :+1: 
updating it right away...

File: activesupport/lib/active_support/hash_with_indifferent_access.rb (hunk 1 above)
Comment (pixeltrix) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: You could have it inside `check_value` if it was combined with the check for `options[:for] == :assignment` or am I missing something?, e.g:

``` ruby
elsif value.is_a?(Array)
  unless options[:for] == :assignment && !value.frozen?
    value = value.dup
  end
  value.map! { |e| convert_value(e, options) }
else
```

Given the short-circuiting of conditionals it shouldn't even have any noticeable effects.

Comment (pixeltrix) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: You could have it inside `check_value` if it was combined with the check for `options[:for] == :assignment` or am I missing something?, e.g:

``` ruby
elsif value.is_a?(Array)
  if options[:for] != :assignment || value.frozen?
    value = value.dup
  end
  value.map! { |e| convert_value(e, options) }
else
```

Given the short-circuiting of conditionals it shouldn't have any noticeable effect.

Comment (aditya-kapoor) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: I think this will create the duplicate of `value` whenever we are not passing `:for` key in the `options` hash, since `convert_value` is also called from [here](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/hash_with_indifferent_access.rb#L135).

Comment (pixeltrix) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: :for        | frozen | duped 
-------------|--------|-------
 :assignment | true   | true  
 :assignment | false  | false 
 :to_hash    | true   | true  
 :to_hash    | false  | true  
 nil         | true   | true  
 nil         | false  | true  

It's 8am in the morning and I've only had the one cup of coffee so my logic may be fuzzy :smile:

Comment (pixeltrix) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: > I think this will create the duplicate of value whenever we are not passing :for key

Doesn't the current implementation do that?

``` ruby
elsif value.is_a?(Array)
  unless options[:for] == :assignment
    value = value.dup
  end
  value.map! { |e| convert_value(e, options) }
else
```

That dups it if `:for` is anything other than `:assignment` including nil.

Comment (aditya-kapoor) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: OOPS...my bad... :cry: 
I think I might need some coffee...
You are correct, updating it as suggested.

**Comment by pixeltrix** [comment]
@aditya-kapoor sorry, can you also add a CHANGELOG entry as well - thanks!

**Comment by aditya-kapoor** [comment]
@pixeltrix I have added the entry in Changelog, Please have a look.

File: activesupport/CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,8 @@
+*   Fixes assignment of frozen values in HashWithIndifferentAccess.
+    Fixes #18550
+
+    *Aditya Kapoor*
+
```
Comment (pixeltrix) [inline activesupport/CHANGELOG.md]: Can you reword this a bit - something along the lines of:

``` markdown
Duplicate frozen array when assigning it to a HashWithIndifferentAccess so 
that it doesn't raise a `RuntimeError` when calling `map!` on it in `convert_value`.

Fixes #18550.

*Aditya Kapoor*
```

Once that's done it should be good to merge.

**Comment by aditya-kapoor** [comment]
@pixeltrix I have made the changes suggested by you. :smile:

**Comment by pixeltrix** [comment]
@aditya-kapoor thanks for your patience :green_heart:

**Comment by tonywok** [comment]
Is this fix going to be released in a 4.2.x?
