### PR TITLE
Preserve timezone and locale in ActiveJob exception handlers

### LINKED ISSUE #52183: ActiveJob does not use the job locale inside the rescue_from block
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "active_job"
require "minitest/autorun"

class BuggyJobTest < ActiveJob::TestCase
  class BuggyJob < ActiveJob::Base
    rescue_from(StandardError) do |error|
      $i18n_locale_is_eq_job_locale = I18n.locale.to_s == locale.to_s
    end

    def perform
      raise 'error'
    end
  end

  def test_stuff
    I18n.available_locales = %i(en ja)
    I18n.with_locale(:ja) do
      BuggyJob.perform_later
    end

    perform_enqueued_jobs
    assert($i18n_locale_is_eq_job_locale)
  end
end

```

### Expected behavior
The `I18n.locale` inside the `rescue_from` should be the same of `job.locale`

### Actual behavior
The `I18n.locale` inside the `rescue_from` is the current locale

### System configuration
**Rails version**: 7.1.3.4

**Ruby version**: 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #52183.

The problem was that the locale and the timezone are set only when running the `perform` method of the job
https://github.com/rails/rails/blob/16d8b82d5e2aca4780c5d10b1fe9a90b33a0e84e/activejob/lib/active_job/translation.rb#L8-L10
https://github.com/rails/rails/blob/16d8b82d5e2aca4780c5d10b1fe9a90b33a0e84e/activejob/lib/active_job/execution.rb#L45-L51
https://github.com/rails/rails/blob/16d8b82d5e2aca4780c5d10b1fe9a90b33a0e84e/activejob/lib/active_job/execution.rb#L65-L70

But when the job raises https://github.com/rails/rails/blob/16d8b82d5e2aca4780c5d10b1fe9a90b33a0e84e/activejob/lib/active_job/execution.rb#L52-L58, we are outside of `around_perform` block and so the global values are not correctly set. So we need to wrap the whole `perform_now` method.

### CODE REVIEW

File: activejob/lib/active_job/base.rb [hunk 1]
```diff
@@ -71,8 +70,7 @@ class Base
     include Exceptions
     include Instrumentation
     include Logging
-    include Timezones
-    include Translation
+    include TimezonesAndTranslation
```
Comment (fatkodima) [inline activejob/lib/active_job/base.rb:73]: Not the best name. I wanted to use `CurrentAttributes`, but it can be confusing why it sets only a locale and a timezone.

Comment (byroot) [reply activejob/lib/active_job/base.rb:73]: Maybe something like `ExecutionState`?

**Comment by byroot** [comment]
I think this would be valuable if cleaned up a bit.

On a more general note, I think we're overusing callbacks to implement Active Job itself, it's quite awful when looking at an Active Job backtrace... We should probably prefer classic method redefinition + super

**Comment by fatkodima** [comment]
Renamed to `ExecutionState`.

> We should probably prefer classic method redefinition + super

yeah, this PR actually uses this approach.

File: activejob/lib/active_job/execution_state.rb [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+  module ExecutionState # :nodoc:
+    extend ActiveSupport::Concern
+
+    included do
+      def perform_now
+        I18n.with_locale(locale) do
+          Time.use_zone(timezone) { super }
+        end
+      end
+    end
```
Comment (byroot) [inline activejob/lib/active_job/execution_state.rb:13]:
```suggestion
    def perform_now
      I18n.with_locale(locale) do
        Time.use_zone(timezone) { super }
      end
    end
```
No need for `included` here.
