### PR TITLE
Fix #45389 | `updated_at` not updating in `before_update` callback

### LINKED ISSUE #45389: updated_at is not affected by attribute changes in before_update callback
### Steps to reproduce

* Modify an attribute in a before_update callback.
* call save on an instance of a model with said callback

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| 'https://github.com/#{repo}.git' }

  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '~> 6.1.4.1'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :updaty_posts, force: true do |t|
    t.string :name
    t.timestamps
  end

  create_table :savy_posts, force: true do |t|
    t.string :name
    t.timestamps
  end
end

class UpdatyPost < ActiveRecord::Base
  before_update :mutate_name

  private

  def mutate_name
    return if new_record?

    self.name = 'something different'
  end
end

class SavyPost < ActiveRecord::Base
  before_save :mutate_name

  private

  def mutate_name
    return if new_record?

    self.name = 'something different'
  end
end


class BugTest < Minitest::Test
  def test_association_stuff
    upost = UpdatyPost.create!
    spost = SavyPost.create!

    before_upost_updated_at = upost.updated_at
    before_spost_updated_at = spost.updated_at

    refute_equal 'something different', spost.name
    refute_equal 'something different', upost.name

    sleep 2

    upost.save!
    spost.save!

    assert_equal 'something different', spost.name
    assert_equal 'something different', upost.name

    refute_equal spost.updated_at, before_spost_updated_at, 'changed attribute did not change timestamps in before_save'
    refute_equal upost.updated_at, before_upost_updated_at, 'changed attribute did not change timestamps in before_update'
  end
end
```

### Expected behavior
Based on the warning in [the guide](https://guides.rubyonrails.org/active_record_callbacks.html#updating-an-object) 

> Avoid updating or saving attributes in callbacks. For example, don't call update(attribute: "value") within a callback. This can alter the state of the model and may result in unexpected side effects during commit. Instead, you can safely assign values directly (for example, self.attribute = "value") in before_create / before_update or earlier callbacks.

I would expect updated_at to change when changing an attr in a before_update callback.

### Actual behavior
updated_at does not change.

### System configuration
**Rails version**: 6.1.4.1 (but tested my reproduction above in rails 7 with same result)

**Ruby version**: ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-darwin21]
(but also seen on other ruby 2.7.x versions on heroku-20 stack)

Not sure if this is an actual bug or intended behavior, but I be happy to open a PR against the guides if it's the latter.

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

Fixes #45389.

As documented in the issue linked above, it would be expected that mutations made within `update` callbacks also update the `updated_at` timestamp, especially since this behaviour already occurs with `save` callbacks.

### Detail

This Pull Request ensures that timestamps are **rewritten** once all `update` callbacks have run so that mutations made within them (if any) are recognised as updates, updating the `updated_at` timestamp as a result.

I initially considered just changing the ordering of when timestamps are set to be after all callbacks have been completed, but that would introduce a regression with the changes made [in this commit](https://github.com/rails/rails/commit/dddbccb25a709e1897326e2a25d37da83bbfd717) seeing as timestamps always need to be available inside callbacks.

I've also improved coverage for some related tests where timestamps are expected to exist within callbacks. These now test create, update and save callbacks (one type each) and not just a single create callback. I did this because I failed the only test that existed when working on my solution and thought it'd be valuable to cover all 3 of these callback types to ensure no regressions are intorduced.

### Additional information

Shoutout to @markhallen for their debugging efforts and producing a failing test which (which I've stolen for this PR).

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/test/cases/timestamp_test.rb [hunk 1]
```diff
@@ -253,6 +253,56 @@ def change_name
...
+    @developer = klass.create!
+    @previously_updated_at = @developer.updated_at
+    @previous_name = @developer.name
+
+    travel(1.second) do
+      @developer.save!
+    end
+
+    assert_not_equal @previous_name, @developer.name
+    assert_not_equal @previously_updated_at, @developer.updated_at
```
Comment (joshuay03) [inline activerecord/test/cases/timestamp_test.rb:281]: Failing assertion:
Screenshot 2023-03-25 at 5 56 32 pm

File: activerecord/test/cases/timestamp_test.rb [hunk 2]
```diff
@@ -253,6 +253,56 @@ def change_name
...
+  end
+
+  def test_saving_an_unchanged_record_with_a_non_mutating_before_update_callback_does_not_update_its_timestamp
```
Comment (joshuay03) [inline activerecord/test/cases/timestamp_test.rb:284]: Regression test for when callbcks are executed without mutations.

File: activerecord/test/cases/timestamp_test.rb (hunk 1 above)
Comment (ghiculescu) [reply activerecord/test/cases/timestamp_test.rb:281]:
```suggestion
    assert_not_equal @previously_updated_at, @developer.updated_at
    assert_not_equal @previously_updated_at, @developer.reload.updated_at
```

This ensures that the correct timestamp is persisted, too.

Comment (ghiculescu) [reply activerecord/test/cases/timestamp_test.rb:281]: (Should do the same on the other test.)

File: activerecord/lib/active_record/callbacks.rb [hunk 3]
```diff
@@ -460,7 +460,7 @@ def _create_record
     end
 
     def _update_record
-      _run_update_callbacks { super }
+      _run_update_callbacks { _update_record { super } }
```
Comment (ghiculescu) [inline activerecord/lib/active_record/callbacks.rb:463]: I get what this is doing after reading it a few times, but it is pretty confusing at first glance because the method being called has the same method name. I wonder if it's worth refactoring this and calling a more appropriately named method explicitly instead of relying on `super`.

File: activerecord/lib/active_record/timestamp.rb [hunk 4]
```diff
@@ -124,6 +126,8 @@ def _update_record
         end
       end
 
+      return yield if block_given? && @called_already
```
Comment (ghiculescu) [inline activerecord/lib/active_record/timestamp.rb:129]: Am I right in saying that the point here is to have the implementation run twice?

If so I think there's probably a more appropriate name for the ivar.

Comment (joshuay03) [reply activerecord/lib/active_record/timestamp.rb]: Did away with the ivar altogether for what I think is a cleaner implementation?: https://github.com/rails/rails/compare/a25a55b1ac11a7de8ca8584e278d78ee26f63d35..ba69cd2d2130cf6d42bd201da9b67ebd756ec4a4.

File: activerecord/lib/active_record/callbacks.rb (hunk 3 above)
Comment (joshuay03) [reply activerecord/lib/active_record/callbacks.rb]: Hmm I agree. What do you think about this?
https://github.com/rails/rails/compare/a25a55b1ac11a7de8ca8584e278d78ee26f63d35..ba69cd2d2130cf6d42bd201da9b67ebd756ec4a4

File: activerecord/test/cases/timestamp_test.rb (hunk 1 above)
Comment (joshuay03) [reply activerecord/test/cases/timestamp_test.rb:283]: Actioned!
https://github.com/rails/rails/compare/ba69cd2d2130cf6d42bd201da9b67ebd756ec4a4..f2d622adeb4847361c64bdb6d9b0ce30b9b106fb

**Review by ghiculescu — APPROVED** [review]
