### PR TITLE
Change default branch for new Rails projects and plugins to main

### LINKED ISSUE #40214: Change the default branch name for new Rails projects from `master` to `main`
### Steps to reproduce

```bash
$ rails new temp_experiment
# app is created
$ cd temp_experiment
$ cat .git/HEAD
ref: refs/heads/master
```

### Expected behavior
.git/HEAD should contain `ref: refs/heads/main`

###### References
* https://github.com/github/roadmap/issues/63
* https://github.com/github/renaming
* Rationale: https://dev.to/afrodevgirl/replacing-master-with-main-in-github-2fjf

### Actual behavior
.git/HEAD contains `ref: refs/heads/master`

### System configuration
**Rails version**: 6.0.3.3

**Ruby version**: 2.7.1p83

### PR DESCRIPTION
**Pull request by prateekkish**
This PR changes the default branch of new Rails projects and plugins from master to main.

### Summary

Fixes #40214

If a user has `init.defaultBranch` set in their `.gitconfig`, then that is taken into account.
If not, then the new project/plugin would be initialized with `main` as its default branch.

### CODE REVIEW

File: railties/test/generators/app_generator_test.rb [hunk 1]
```diff
@@ -1042,6 +1042,35 @@ def test_version_control_initializes_git_repo
...
+  def test_default_branch_main_without_user_default
+    current_default_branch = `git config --global init.defaultBranch`
+    `git config --global --unset init.defaultBranch`
+
+    run_generator [destination_root]
+    assert_file ".git/HEAD", /main/
+
+    if !current_default_branch.strip.empty?
+      `git config --global init.defaultBranch #{current_default_branch}`
+    end
```
Comment (SampsonCrowley) [inline railties/test/generators/app_generator_test.rb:1054]: this seems like something that should be inside an ensure block. otherwise a failing test would permanently remove a suite-runners's git config

File: railties/test/generators/app_generator_test.rb [hunk 2]
```diff
@@ -1042,6 +1042,35 @@ def test_version_control_initializes_git_repo
...
+    `git config --global init.defaultBranch master`
+
+    run_generator [destination_root]
+    assert_file ".git/HEAD", /master/
+
+    if current_default_branch.strip.empty?
+      `git config --global --unset init.defaultBranch`
+    else
+      `git config --global init.defaultBranch #{current_default_branch}`
+    end
```
Comment (SampsonCrowley) [inline railties/test/generators/app_generator_test.rb:1071]: also something that should be inside an ensure block. otherwise a failing test would permanently add a default branch to a suite-runners's git config

File: railties/test/generators/plugin_generator_test.rb [hunk 3]
```diff
@@ -92,6 +92,28 @@ def test_initializes_git_repo
...
+    `git config --global init.defaultBranch master`
+
+    run_generator
+    assert_file ".git/HEAD", /master/
+
+    if current_default_branch.strip.empty?
+      `git config --global --unset init.defaultBranch`
+    else
+      `git config --global init.defaultBranch #{current_default_branch}`
+    end
```
Comment (SampsonCrowley) [inline railties/test/generators/plugin_generator_test.rb:114]: same here. anytime you modify a config that would permanently affect the machine running the test suite, setting the config back to original should be ensured (in an ensure block)

**Review by SampsonCrowley — CHANGES_REQUESTED** [review]
@prateekkish I'm not a maintainer, but these are the problems I see off the bat

**Comment by prateekkish** [comment]
@SampsonCrowley Thanks for the input. I've updated the PR with the fixes.

**Comment by jayqui** [comment]
@prateekkish thank you so much for this work!

**Comment by lunarkitty7** [comment]
If `init.defaultBranch` is already set `rails new` creates a project with the custom default branch name. I think changing the default behaviors for a new project created with `rails new` that differs from `git init` would be undesirable because it would be unexpected. I think most users wanting a custom default branch name would have already set `init.defaultBranch`, whereas not setting it implies that you want the default to be `master`.

**Comment by prateekkish** [comment]
> It's likely that most users wanting a custom default branch name would have already set `init.defaultBranch`, whereas those leaving it unset likely expect `master` to be the default.

I don't think that is the case. With Github moving strongly towards this, even [changing the default branch for new repositories](https://github.com/github/renaming), there might be new repos being created where the default branch is main, but if they used `rails new` locally, it is master. 

Even after this change, we still do respect `init.defaultBranch` if it exists, and only use main when they don't have a preference, making it an opt-out, just like Github's strat.

**Comment by kitty-alt** [comment]
The issue is, it is out of scope for Rails to be trying to manage Git defaults, it's Git's job, and trying to patch it with Rails is improper. It's important to distinguish Git from Github, there are other services for code hosting Git repos to consider as well. If you want better Github integration it may be better to detect the Github cli client and ask the user if they want to use that instead of Git? All of this seems like a lot of work for something that is managed very cleanly already with `init.defaultBranch` though.

File: railties/lib/rails/generators/rails/app/app_generator.rb [hunk 4]
```diff
@@ -69,6 +69,9 @@ def gitignore
     def version_control
       if !options[:skip_git] && !options[:pretend]
         run "git init", capture: options[:quiet], abort_on_failure: false
+        if user_default_branch.strip.empty?
+          `git symbolic-ref HEAD refs/heads/main`
```
Comment (rafaelfranca) [inline railties/lib/rails/generators/rails/app/app_generator.rb:73]: Instead of doing this. I think we should set the -b argument to `git init`.

**Comment by rafaelfranca** [comment]
Those are valid concerns @kitty-alt, and while I understand them, I also know that the direction we want to go is to generate Rails repositories using `main` as the name of the branch or the one defined by `init.defaultBranch`. This means that the behavior of `rails new` will be different from `git init`, but I see no problem on that. One of the Rails tents is providing good defaults, even on top of existing tools. `main` is a default that we believe it is better than the git's default. Some people may disagree, and for that, they can configure in the way that please them.

File: railties/lib/rails/generators/rails/app/app_generator.rb (hunk 4 above)
Comment (prateekkish) [reply railties/lib/rails/generators/rails/app/app_generator.rb:73]: Did you mean switch to `main` using `git checkout -b main`?
To my knowledge, there's no `-b` argument for `git init`.

Comment (rafaelfranca) [reply railties/lib/rails/generators/rails/app/app_generator.rb:77]: No. I mean switching `git init` to be `git init -b main`. There is since git 2.28.  We could check the version of git and only use that option on git 2.28.

https://git-scm.com/docs/git-init

```
-b <branch-name>
--initial-branch=<branch-name>
Use the specified name for the initial branch in the newly created repository. If not specified, fall back to the default name (currently master, but this is subject to change in the future; the name can be customized via the init.defaultBranch configuration variable).
```
