### PR TITLE
[Fix #55460] Make `ActiveSupport::Logger` `#freeze`-friendly

### LINKED ISSUE #55460: `Rails.logger` is not `#freeze`-friendly
### Steps to reproduce

Not exactly a bug, but more of a question about whether `Rails.logger` should be `#freeze`-friendly.

We're implementing a custom railtie that freezes `Rails.logger` to prevent unintentional modifications by gem initializers or application code. This addresses a recurring issue where we've accidentally changed the Rails logger level when configuring logging for gems that share the same logger instance.

For example, when a gem shares `Rails.logger` and we configure its logging level in an initializer like:
```ruby
# config/initializers/some_gem.rb

SomeGem.logger.level = Logger::DEBUG  # Oops! This changes Rails.logger.level too
```

This has happened a few times in our codebase, causing production log level changes that resulted in either lost log messages (when accidentally set to a higher level) or excessive logging (when set to a lower level).

The railtie works by freezing the logger after Rails completes its logger setup but before any `config/initializers` run. However, we discovered that Rails' `ActiveSupport::LoggerThreadSafeLevel` module attempts to modify the logger's singleton class when accessing `.level`, which fails when the logger is frozen (see link in code comment).

Our current workaround is to call `Rails.logger.level` before freezing to trigger the lazy initialization of the thread-local key, but this feels like an implementation detail we shouldn't have to know about. It would be ideal if Rails loggers were designed to be freeze-friendly, allowing safe freezing without requiring knowledge of internal lazy initialization patterns.

```ruby
# frozen_string_literal: true

# This railtie freezes the singleton Rails logger instance to prevent unintentional modifications
# during initialisation or runtime. This ensures that in production, we don't lose log messages due
# to a config initializer for a gem changing the logger level when sharing the same logger instance.
#
class FreezeLoggerRailtie < Rails::Railtie
  # rspec-mocks relies on proxies for method stubbing and expectations,
  # and frozen objects cannot be proxied.
  unless Rails.env.test?
    initializer :freeze_logger, after: :initialize_logger, before: :load_config_initializers do
      # We need to read the logger level before freezing the logger because the thread-local key to store
      # the level is lazily assigned to an instance variable.
      #
      # See: https://github.com/rails/rails/blob/3235827585d87661942c91bc81f64f56d710f0b2/activesupport/lib/active_support/logger_thread_safe_level.rb#L43-L45
      Rails.logger.level
      Rails.logger.freeze

      if Rails.logger.is_a?(ActiveSupport::BroadcastLogger)
        Rails.logger.broadcasts.each do |logger|
          logger.level
          logger.freeze
        end
      end
    end
  end
end

```

### Expected behavior

Calling `Rails.logger.level` or `Rails.logger.info` or any common method on `Rails.logger` shouldn't raise an error when `Rails.logger.freeze` has been called beforehand.

### Actual behavior

Calling `Rails.logger.level` or `Rails.logger.info` on `Rails.logger` when `Rails.logger.freeze` has been called beforehand raises an error during boot:

```
/Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/activesupport-8.0.2/lib/active_support/logger_thread_safe_level.rb:44:in 'ActiveSupport::LoggerThreadSafeLevel#local_level_key': can't modify frozen #<Class:#<ActiveSupport::Logger:0x000000014bf3d170>>: #<ActiveSupport::Logger:0x000000014bf3d170 @level=1, @progname=nil, @default_formatter=#<Logger::Formatter:0x000000014bc515d8 @datetime_format=nil>, @formatter=#<ProductionLoggerFormatter:0x000000014bd3ed88 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x0000000160516380 @shift_period_suffix="%Y%m%d", @shift_size=1048576, @shift_age=0, @filename="/Users/joshuayoung/Projects/buildkite/buildkite/log/production.log", @dev=#<File:/Users/joshuayoung/Projects/buildkite/buildkite/log/production.log>, @binmode=false, @reraise_write_errors=[], @skip_header=false, @mon_data=#<Monitor:0x000000014bc51498>, @mon_data_owner_object_id=5768>, @level_override={}> (FrozenError)
	from /Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/activesupport-8.0.2/lib/active_support/logger_thread_safe_level.rb:11:in 'ActiveSupport::LoggerThreadSafeLevel#local_level'
	from /Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/activesupport-8.0.2/lib/active_support/logger_thread_safe_level.rb:31:in 'ActiveSupport::LoggerThreadSafeLevel#level'
	from /Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/activesupport-8.0.2/lib/active_support/broadcast_logger.rb:109:in 'Array#map'
	from /Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/activesupport-8.0.2/lib/active_support/broadcast_logger.rb:109:in 'ActiveSupport::BroadcastLogger#level'
	from /Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/activerecord-8.0.2/lib/active_record/railtie.rb:68:in 'block in <class:Railtie>'
	from /Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/railtie.rb:272:in 'block in Rails::Railtie#run_console_blocks'
	from /Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/railtie.rb:297:in 'Array#each'
	from /Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/railtie.rb:297:in 'Rails::Railtie#each_registered_block'
	from /Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/railtie.rb:272:in 'Rails::Railtie#run_console_blocks'
	from /Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/application.rb:582:in 'block in Rails::Application#run_console_blocks'
	from /Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine/railties.rb:15:in 'Array#each'
	from /Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine/railties.rb:15:in 'Rails::Engine::Railties#each'
	from /Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/application.rb:582:in 'Rails::Application#run_console_blocks'
	from /Users/joshuayoung/Projects/buildkite/buildkite/.bundle/ruby/3.4.0/gems/railties-8.0.2/lib/rails/engine.rb:455:in 'Rails::Engine#load_console'
```

### System configuration

**Rails version**: 8.0.1

**Ruby version**: 3.4.5

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

Closes https://github.com/rails/rails/issues/55460

### Detail

Updates `ActiveSupport::LoggerThreadSafeLevel` to eagerly intialize its ivars (just `@local_level_key`) so that a frozen `ActiveSupport::Logger` doesn't raise a `FrozenError` when simply reading it's level or calling the log method (e.g. `#debug`).

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activesupport/lib/active_support/logger_thread_safe_level.rb [hunk 1]
```diff
@@ -40,8 +45,6 @@ def log_at(level)
     end
 
     private
-      def local_level_key
-        @local_level_key ||= :"logger_thread_safe_level_#{object_id}"
-      end
+      attr_reader :local_level_key
```
Comment (joshuay03) [inline activesupport/lib/active_support/logger_thread_safe_level.rb:48]: Making this private isn't really necessary since the module is nodoc-ed, but I thought I'd do it for consistency with the current implementation.

File: activesupport/test/logger_test.rb [hunk 2]
```diff
@@ -382,6 +382,37 @@ def test_logger_level_thread_safety
     ActiveSupport::IsolatedExecutionState.isolation_level = previous_isolation_level
   end
 
+  def test_logger_freeze
+    logger = @logger.clone
+    logger.freeze
+
+    assert_nothing_raised do
+      assert_equal Logger::DEBUG, logger.level
```
Comment (joshuay03) [inline activesupport/test/logger_test.rb:390]: Without patch:

Screenshot 2025-08-08 at 7 33 17 am
