### PR TITLE
fix to_param to maximize content

### LINKED ISSUE #23635: AR's to_param does not work as documented
The documentation states truncation by words to limit to 20 characters, but that's not quite what happens:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '5.0.0'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :firms, force: true do |t|
    t.string :name
  end
end

class Firm < ActiveRecord::Base
  to_param :name
end

class BugTest < Minitest::Test
  def test_to_param_truncation
    firm = Firm.create!(name: "If I look at words")

    expected = "1-if-i-look-at-words"
    assert_equal expected, firm.to_param, firm.name

    firm.name << " why do I get shorter?"
    assert_equal expected, firm.to_param, firm.name
  end
end
```

### PR DESCRIPTION
**Pull request by rab**
To fix #23635

The documentation states that parameter values longer than 20 characters
will be truncated by words, but the example shows that a parameter based
on "David Heinemeier Hansson" (with id: 125) becomes "125-david" when
"David Heinemeier".length == 16 so why so short?

The answer lies in the use of the #truncate option omission: nil which
seems to have been intended to mean "nothing", but which actually causes
the default string "..." to be used. This causes #truncate to cleave
words until the "..." can be added and still remain within the requested
size of 20 characters.

The better option is omission: '' (which is probably what was originally
intended).

Furthermore, since the use of #parameterize will remove non-alphanumeric
characters, we can maximize the useful content of the output by calling
parameterize first and then giving truncate a separator: /-/ rather than
a space.

### CODE REVIEW

File: activerecord/lib/active_record/integration.rb [hunk 1]
```diff
@@ -100,7 +100,7 @@ def to_param(method_name = nil)
           define_method :to_param do
             if (default = super()) &&
                  (result = send(method_name).to_s).present? &&
-                   (param = result.squish.truncate(20, separator: /\s/, omission: nil).parameterize).present?
+                   (param = result.squish.parameterize.truncate(20, separator: /-/, omission: '')).present?
```
Comment (vipulnsward) [inline activerecord/lib/active_record/integration.rb]: I think it would be safer to keep parameterize towards the end to not cause any side effects from truncate affect parameterization.

File: activerecord/test/cases/integration_test.rb [hunk 2]
```diff
@@ -1,3 +1,4 @@
+# coding: utf-8
```
Comment (vipulnsward) [inline activerecord/test/cases/integration_test.rb]: Is this needed?

Comment (rab) [inline activerecord/test/cases/integration_test.rb]: No, it no longer is w/ current rubies, but Emacs puts that in when it detects the need. I can remove it before merging.

File: activerecord/lib/active_record/integration.rb (hunk 1 above)
Comment (rab) [inline activerecord/lib/active_record/integration.rb]: Please refer to my response near the test for this change (lines 39-44) below.

File: activerecord/test/cases/integration_test.rb [hunk 3]
```diff
@@ -29,10 +30,23 @@ def test_to_param_class_method
...
 
+  def test_to_param_class_method_truncates_words_properly
+    firm = Firm.find(4)
+    firm.name << ', Inc.'
+    assert_equal '4-flamboyant-software', firm.to_param
+  end
+
+  def test_to_param_class_method_truncates_after_parameterize
+    firm = Firm.find(4)
+    firm.name = "Huey, Dewey, & Louie LLC"
```
Comment (rab) [inline activerecord/test/cases/integration_test.rb]: I don't understand your concern. The benefit to parameterizing prior to truncation is that characters that will no make it into the final result do not influence the truncation. In this case, the commas and the ampersand will not be used in the result, but that makes the length 4 characters more for no reason. In this way we are truncating the URL parameter rather than parameterizing the truncated attribute.

**Comment by rab** [comment]
The conflicts are with the `CHANGELOG.md` and will be resolved with a rebase/squash as soon as it is requested. Is there anything else that you'd like to see from me?

**Comment by rab** [comment]
Updated/rebased the fix to be against master now that 5.0.0 is released. The to_param code is unchanged.

**Comment by matthewd** [comment]
:+1: please squash to a single commit

**Comment by rab** [comment]
Squashed!

**Comment by matthewd** [comment]
Thanks!

This will presumably cause some (URL-based) cache misses, for things that have learned to fit more detail, but that seems fine. /cc @jeremy, Defender of the Cache
