### PR TITLE
Fix 6.1 change_column setting datetime precision

### LINKED ISSUE #48965: Upgrading to Rails 7.0 changes precision when changing column type to datetime
In Rails 6.1 and below, precision is nil when using `change_column` to set the column type to datetime without explicit option. In Rails 7.0, precision is 6 even if the migration version is specified as `ActiveRecord::Migration[6.1]`. This will result in different schemas when running `rails db:migrate` in Rails 6.1 and Rails 7.0.

https://github.com/rails/rails/pull/42297 changed the default datetime precision to 6. In Rails7.0, `ActiveRecord::Migration[6.1]` or lower version includes the following support to maintain the original behavior.
- https://github.com/rails/rails/blob/2fa54931cf3fee16cc1e7f1fad851078910f83e5/activerecord/lib/active_record/migration/compatibility.rb#L204 
- https://github.com/rails/rails/blob/2fa54931cf3fee16cc1e7f1fad851078910f83e5/activerecord/lib/active_record/migration/compatibility.rb#L174 

but there seems to be no support for `change_column`

### Steps to reproduce

Using PostgreSQL because I can't reproduce with sqlite3

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# docker run --rm -e POSTGRES_PASSWORD=postgres -p 9999:5432 postgres
ActiveRecord::Base.establish_connection("postgres://postgres:postgres@localhost:9999/postgres")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema[6.1].define do
  create_table :posts, force: true do |t|
    t.date :published_at
  end
end

class ChangePublishedAt < ActiveRecord::Migration[6.1]
  def change
    change_column :posts, :published_at, :datetime
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_precision_when_change_column_to_datetime
    ChangePublishedAt.migrate(:up)
    Post.reset_column_information
    published_at_column = Post.columns.find { |c| c.name == "published_at" }
    assert_nil published_at_column.precision # fail. Expected 6 to be nil.
  end
end
```

### Expected behavior

the test pass

### Actual behavior

the test fails.

### System configuration
**Rails version**:
7.0.7
**Ruby version**:
3.2.2

### PR DESCRIPTION
**Pull request by skipkayhil**
### Motivation / Background

Fix #48965 

This is already the case for add_column and create_table, but change_column was missed

### Additional Information

This needs to be backported to 7.0, but the test change won't backport cleanly because the Migrator signature in the test changed. I'll make a PR for 7-0-stable as well if that would be easier

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/lib/active_record/migration/compatibility.rb [hunk 1]
```diff
@@ -178,6 +178,15 @@ def add_column(table_name, column_name, type, **options)
           super
         end
 
+        def change_column(table_name, column_name, type, **options)
+          if type == :datetime
+            options[:precision] ||= nil
+          end
+
+          type = PostgreSQLCompat.compatible_timestamp_type(type, connection)
+          super
```
Comment (yahonda) [inline activerecord/lib/active_record/migration/compatibility.rb:187]: What do you think about extracting this logic into a helper method that can be shared between the `add_column' and `change_column' methods?

Comment (skipkayhil) [reply activerecord/lib/active_record/migration/compatibility.rb:187]: Thanks for the review! I do think there's an opportunity for a refactor here, but I'm not 100% sure what it should be yet (maybe we want to use this new method in all of the `V6_1` column methods?). Going through these tests it appears that coverage isn't great so I think I would prefer to fix those issues first and ensure everything is working as expected before refactoring. How does that sound?

Comment (yahonda) [reply activerecord/lib/active_record/migration/compatibility.rb:187]: That makes sense.

**Comment by yahonda** [comment]
`activerecord/CHANGELOG.md` conflict needs resolved.

**Comment by yahonda** [comment]
Would you make a back port pull request for the 7-0-stable branch?

> I'll make a PR for 7-0-stable as well if that would be easier

**Comment by yahonda** [comment]
Backported to the 7-0-stable branch via https://github.com/rails/rails/pull/49006
