### PR TITLE
Disable colorize logging of SQL and reduce unnecessary invocation of sql_color matching

### LINKED ISSUE #38685: sql_color is slow for long sql queries
This has been brought up here before https://github.com/rails/rails/issues/24330 but is still an issue occasionally. The application of these regular expressions can sometimes dominate the request time, including the SQL server processing the query and instantiating a lot of AR-objects as a result. I have had cases in my app where  disabling `sql_color` has reduced request times for a request from 4.8 to 1.2 seconds.

### Steps to reproduce
- Generate a long sql query and send it through AR (e.g. `find_by_sql`)
- Observe that a lot of time is spent in ruby case matching using `Regexp.===` (for example using some profiler)
- Narrow this down to inefficient regular expressions being applied by `sql_color`
### Expected behavior
`sql_color` should not slow down query processing (in production)
### Actual behavior
I am unsure.
Maybe `sql_color` can be configured (perhaps optionally) to be disabled in production, maybe the regular expressions can be made faster?
### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.3

### PR DESCRIPTION
**Pull request by abhaynikam**
When the `colorize_logging` is disabled, logs do not colorize the SQL queries. But the `sql_color` method is always invoked which due to regex matching results in slow queries.

This PR fixes #38685 and removes unnecessary invocation of `sql_color` method when `colorize_logging` is disabled

### CODE REVIEW

File: activerecord/lib/active_record/log_subscriber.rb [hunk 1]
```diff
@@ -43,8 +43,10 @@ def sql(event)
         binds.prepend("  ")
       end
 
-      name = colorize_payload_name(name, payload[:name])
-      sql  = color(sql, sql_color(sql), true)
+      if colorize_logging
+        name = colorize_payload_name(name, payload[:name])
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/log_subscriber.rb]: Do this need to be inside the `if`. `color` will take care of it.

**Review by rafaelfranca — COMMENTED** [review]
This is in the right direction but we should expose this

File: activerecord/lib/active_record/log_subscriber.rb (hunk 1 above)
Comment (abhaynikam) [reply activerecord/lib/active_record/log_subscriber.rb]: @rafaelfranca I did the necessary changes for it. Please have a look. Thanks
