### PR TITLE
[Fix #51463] Raise an error when invalid `:only` or `:except` options are given to `#resource` or `#resources`

### LINKED ISSUE #51463: `#resource` and `#resources` fail quietly and succeed quietly when invalid arguments are passed to `:only` and `:except` options respectively
This came up when pairing with a dev who is newish to Rails. They assumed that passing a custom action argument to `:only` when using `#resources` would auto-magically define a route for it with some defaults. Reading the examples in the documentation for these methods, it's not clear (especially to beginners) what all the accepted arguments for these options are, [there are only examples using default actions](https://www.rubydoc.info/docs/rails/ActionDispatch%2FRouting%2FMapper%2FResources:resources).

I think it would be beneficial if an error was raised if invalid arguments are passed in.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_invalid_resources_only_option
    assert_raises(ArgumentError) do # ❌ fails quietly, no routes generated
      app.routes.draw do
        resources :posts, only: :foo
      end

      # => routes: []
      Rails.logger.info("routes: #{app.routes.routes.map { |r| r.defaults[:action] }}")
    end
  end

  def test_invalid_resources_except_option
    assert_raises(ArgumentError) do # ❌ succeeds quietly, all default routes generated
      app.routes.draw do
        resources :posts, except: :foo
      end

      # => routes: ["index", "create", "new", "edit", "show", "update", "update", "destroy"]
      Rails.logger.info("routes: #{app.routes.routes.map { |r| r.defaults[:action] }}")
    end
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior

Passing invalid options to `:only` or `:except` should raise an error with an informative message.

### Actual behavior

Passing invalid options to `:only` fails quietly and no routes are generated.
Passing invalid arguments to `:except` succeeds quietly and all default routes are generated (index, create, new, show, update, and destroy).

### System configuration
**Rails version**: Edge

**Ruby version**: 3.3.0

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

Fixes https://github.com/rails/rails/issues/51463.

### Detail

Raises an `ArgumentError` when a `ActionDispatch::Routing::Mapper::Resources::Resource` is initalized with `:only` or `:except` options that aren't default (index, create, new, show, update, and destroy) actions .

### Additional information

See my comment below as to why this seems like more changes than it needs to be.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by joshuay03** [comment]
Hmm the test failures are scenarios where the scope's `:only` or `:except` includes `:index` which a nested singleton resource inherits. I think a good solution is to only merge in scoped actions that are applicable to the resource type.

File: actionpack/lib/action_dispatch/routing/mapper.rb [hunk 1]
```diff
@@ -1168,13 +1168,27 @@ module Resources
...
           attr_reader :controller, :path, :param
 
           def initialize(entities, api_only, shallow, options = {})
             if options[:param].to_s.include?(":")
               raise ArgumentError, ":param option can't contain colons"
             end
 
+            if (invalid_actions = (options.values_at(:only, :except).flatten.compact - default_actions)).any?
+              raise ArgumentError, "expected :only and :except to be one or more of #{default_actions}, got #{invalid_actions}"
+            end
```
Comment (pixeltrix) [inline actionpack/lib/action_dispatch/routing/mapper.rb:1190]: The method `assert_valid_keys` would be a better approach as it's used elsewhere within Rails to perform the same task, e.g.

https://github.com/rails/rails/blob/778039b896be1dcb3da606f761921d006cab67c9/actionview/lib/action_view/helpers/output_safety_helper.rb#L43-L50

Comment (joshuay03) [reply actionpack/lib/action_dispatch/routing/mapper.rb:1190]: Good shout, I'll address.

Comment (joshuay03) [reply actionpack/lib/action_dispatch/routing/mapper.rb:1190]: I don't think it works here since we're asserting the values and not the keys.

File: actionpack/CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,7 @@
+*   Raise an `ArgumentError` when invalid `:on` or `:except` options are passed into `#resouce` and `#resources`.
```
Comment (willianveiga) [inline actionpack/CHANGELOG.md:1]:
```suggestion
*   Raise an `ArgumentError` when invalid `:on` or `:except` options are passed into `#resource` and `#resources`.
```

File: actionpack/lib/action_dispatch/routing/mapper.rb [hunk 3]
```diff
@@ -1168,13 +1168,27 @@ module Resources
...
+          class << self
+            def default_actions(api_only)
+              if api_only
+                [:index, :create, :show, :update, :destroy]
+              else
+                [:index, :create, :new, :show, :update, :destroy, :edit]
+              end
+            end
+          end
+
```
Comment (willianveiga) [inline actionpack/lib/action_dispatch/routing/mapper.rb:1180]: Not tested:
```suggestion
        API_ONLY_DEFAULT_ACTIONS = [:index, :create, :show, :update, :destroy].freeze
        DEFAULT_ACTIONS = (API_ONLY_DEFAULT_ACTIONS + [:new, :edit]).freeze
        private_constant :API_ONLY_DEFAULT_ACTIONS, :DEFAULT_ACTIONS

        class Resource # :nodoc:
          class << self
            def default_actions(api_only)
              return API_ONLY_DEFAULT_ACTIONS if api_only

              DEFAULT_ACTIONS
            end
          end

```

File: actionpack/lib/action_dispatch/routing/mapper.rb [hunk 4]
```diff
@@ -1168,13 +1168,27 @@ module Resources
...
           attr_reader :controller, :path, :param
 
           def initialize(entities, api_only, shallow, options = {})
             if options[:param].to_s.include?(":")
               raise ArgumentError, ":param option can't contain colons"
             end
 
+            if (invalid_actions = (options.values_at(:only, :except).flatten.compact - default_actions)).any?
```
Comment (willianveiga) [inline actionpack/lib/action_dispatch/routing/mapper.rb:1188]: `(options.values_at(:only, :except).flatten.compact - default_actions)` could be extracted to an `invalid_actions` method.

File: actionpack/lib/action_dispatch/routing/mapper.rb [hunk 5]
```diff
@@ -1168,13 +1168,27 @@ module Resources
...
+              raise ArgumentError, "expected :only and :except to be one or more of #{default_actions}, got #{invalid_actions}"
```
Comment (willianveiga) [inline actionpack/lib/action_dispatch/routing/mapper.rb:1189]: `(options.values_at(:only, :except).flatten.compact - default_actions)` could be extracted to a memoized `invalid_actions` method. After that we can use it on both places.

File: actionpack/lib/action_dispatch/routing/mapper.rb [hunk 6]
```diff
@@ -1263,6 +1273,16 @@ def singleton?; false; end
         end
 
         class SingletonResource < Resource # :nodoc:
+          class << self
+            def default_actions(api_only)
+              if api_only
+                [:show, :create, :update, :destroy]
+              else
+                [:show, :create, :update, :destroy, :new, :edit]
+              end
```
Comment (willianveiga) [inline actionpack/lib/action_dispatch/routing/mapper.rb:1282]: We can have a [similar approach](https://github.com/rails/rails/pull/51464/files#r1621482919) here.

File: actionpack/CHANGELOG.md (hunk 2 above)
Comment (joshuay03) [reply actionpack/CHANGELOG.md]: Thanks, fixed.

File: actionpack/lib/action_dispatch/routing/mapper.rb (hunk 3 above)
Comment (joshuay03) [reply actionpack/lib/action_dispatch/routing/mapper.rb:1185]: Hmm personally I think the current version is much easier to follow. I'd also like to keep cosmetic changes/refactors to a minimum to allow for an easier review.

File: actionpack/lib/action_dispatch/routing/mapper.rb (hunk 6 above)
Comment (joshuay03) [reply actionpack/lib/action_dispatch/routing/mapper.rb:1287]: See reply on previous comment.

File: actionpack/lib/action_dispatch/routing/mapper.rb (hunk 5 above)
Comment (joshuay03) [reply actionpack/lib/action_dispatch/routing/mapper.rb:1194]: This is only used once when creating the resource, what's the benefit in memoizing it?

> After that we can use it on both places.

Not sure what you mean by this. Both a `Resource` and `SingletonResource` execute this just once on initialisation (see https://github.com/rails/rails/blob/cacf96ecd053f0a3d64c7bf478dac63f98e6aa6d/actionpack/lib/action_dispatch/routing/mapper.rb#L1272).

Comment (willianveiga) [reply actionpack/lib/action_dispatch/routing/mapper.rb:1194]: I see. If you want, you can still encapsulate the code without the memoization. You can document the code with a good method name and separate responsibilities.

Comment (joshuay03) [reply actionpack/lib/action_dispatch/routing/mapper.rb]: Fair call, I've addressed in [these changes](https://github.com/rails/rails/compare/1b40f99aebbec5a520c50f56b9ac5a8338b1153a..6692c5ec7c7fee8b18884b3c542137dd3231a8c3).

In doing so I realized that the validation logic didn't account for `api_only` when comparing against the default actions, so I fixed that. This resulted in some test failures in action mailbox since it generates some resource routes and doesn't account for whether the app is api only or not when using `only:`, I've fixed that here too.

File: actionmailbox/config/routes.rb [hunk 7]
```diff
@@ -16,7 +16,9 @@
 
   # TODO: Should these be mounted within the engine only?
   scope "rails/conductor/action_mailbox/", module: "rails/conductor/action_mailbox" do
-    resources :inbound_emails, as: :rails_conductor_inbound_emails, only: %i[index new show create]
+    inbound_emails_default_actions = %i[index show create]
+    inbound_emails_default_actions << :new unless Rails.application.config.api_only
```
Comment (rafaelfranca) [inline actionmailbox/config/routes.rb:20]: I like this PR but I don't like this change. Can we change the validation to not take in consideration api_only? Let's just check if the values are inside `[:index, :create, :new, :show, :update, :destroy, :edit]` always.

**Review by rafaelfranca — CHANGES_REQUESTED** [review]

File: actionmailbox/config/routes.rb (hunk 7 above)
Comment (joshuay03) [reply actionmailbox/config/routes.rb]: Thanks for the review, I've actioned this.

File: actionpack/CHANGELOG.md [hunk 8]
```diff
@@ -1,3 +1,7 @@
+*   Raise an `ArgumentError` when invalid `:on` or `:except` options are passed into `#resource` and `#resources`.
```
Comment (bquorning) [inline actionpack/CHANGELOG.md:1]: I think you mean `:only`, not `:on`.

Comment (joshuay03) [reply actionpack/CHANGELOG.md:1]: Whoops, thank you!

https://github.com/rails/rails/pull/53214

**Comment by pdobb** [comment]
After this change, I can't use `only: :none` or `except: :all` anymore. I thought these were still valid options? (Though I can't find them documented anywhere in recent Rails docs.) Instead, I have to do e.g. `only: []` or `only: nil`.

**Comment by joshuay03** [comment]
> After this change, I can't use `only: :none` or `except: :all` anymore. I thought these were still valid options? (Though I can't find them documented anywhere in recent Rails docs.) Instead, I have to do e.g. `only: []` or `only: nil`.

Hmm I'm not aware of such behavior and cannot find any references in the docs or code. My understanding is that if it hasn't been documented, it could be changed or removed at any time. I can see how `only: :none` may have worked before since `:none` is an invalid action and it simply would've silently skipped all actions, but I can't understand how `except: :all` could have worked. If you can open an issue reproducing both behaviors using [the template](https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller.rb) I'd be happy to have a look.

**Comment by pdobb** [comment]
@joshuay03 Thanks for the insight on undocumented things being eligible for deletion. The most recent mention of this that I can find in the docs is from Rails 2.3.8: https://apidock.com/rails/ActionController/Resources/resources

> :only and :except may be set to :all, :none, an action name or a list of action names

I'm fine with that. I can just update my code easy enough. Probably more than a few will be surprised by this, though. Either way, thanks for making the update and making Rails better! 🍻
