### PR TITLE
Ensure cache fragment keys (i.e. dependency tree digests) include all relevant templates

### LINKED ISSUE #38984: Fragment caching within render layout: block does not include all necessary template digests
Given two views like this:

```html+erb
<!-- views/pages/home.html.erb -->
<%= render layout: "wrapper" do %>
  <%= cache @post %>
  <!-- cache fragment name: ["pages/_wrapper:3f4bbb56698f60f9616533df83be7694", #<Post id: 1, …>] -->
    HOME
  <%= end %>
<%= end %>
```

```html+erb
<!-- views/pages/about.html.erb -->
<%= render layout: "wrapper" do %>
  <%= cache @post %>
  <!-- cache fragment name: ["pages/_wrapper:3f4bbb56698f60f9616533df83be7694", #<Post id: 1, …>] -->
    ABOUT
  <%= end %>
<%= end %>
```

The `cache @post` calls returns the same cache key (and thus same fragment cache) despite being called from different views. It only includes a template digest of the `wrapper.html.erb` file, but not the template (`home.html.erb` or `about.html.erb` it's being called from).

Interestingly, when not including @post as a cache key, the cache fragment name includes the URL of the current page, and thus ends up being unique per view.

### Steps to reproduce

I've created a [demo rails app](https://github.com/marckohlbrugge/cache_layout_digest_bug) showcasing the problem:

```
git clone https://github.com/marckohlbrugge/cache_layout_digest_bug
cd cache_layout_digest_bug
bin/rails db:migrate
rails dev:cache
rails server
open https://localhost:3000
open https://localhost:3000/about
```

Alternatively you can see [this commit](https://github.com/marckohlbrugge/cache_layout_digest_bug/commit/774b7c542c154501519b071dba1638589497dbe8) to view all the relevant code.

Note that I accidentally created the demo app with Rails 5.2.4.2, but the same issue occurs in Rails 6.

### Expected behavior

Using `cache` within a `render layout:` block should include a template digest of the view the cache method is called (or something else unique like the URL).

### Actual behavior

Using `cache` within a `render layout:` block does **not** include a template digest of the view the cache method is called. The means different views unexpectedly end up sharing the same fragment caches.

### System configuration

**Rails version**: 6.0.2.2

**Ruby version**: 2.6.6p146

### Possibly related

- https://github.com/rails/rails/issues/14991
- https://github.com/rails/rails/commit/da1b8a786cad277c1e4dc1a9f03acec4268dda1f

### PR DESCRIPTION
**Pull request by alipman88**
### Summary

A Rails view may rely on several templates (e.g. layouts and partials) in addition to the template for the action being rendered (e.g. "show.html.erb"). To track which view file is currently being rendered for the purpose of generating template tree digests used in cache fragment keys, Action View uses a stack, the top item of which is accessed via the `@current_template` variable (introduced in 1581cab).

Consider the following template:

    
    <%= render layout: "wrapper" do %>
      <%= cache "foo" %>
        HOME
      <%= end %>
    <%= end %>

Inside the block passed to the render helper, `@current_template` corresponds to the wrapper.html.erb template instead of home.html.erb. As wrapper.html.erb is then used as the root node for generating the template tree digest used in the cache fragment key, the cache fragment fails to expire upon changes to home.html.erb. Additionally, should a second template use the wrapper.html.erb layout and contain a cache fragment with the same key, the cache fragment keys for both templates will be identical - causing cached content to "leak" from one view to another (as described in #38984).

This PR skips adding templates to the stack when rendered as a layout with a block via the render helper. This results in `@current_template` corresponding to the view file currently being rendered, ensuring correctly-expiring and unique cache fragment digests. Additionally, the `virtual_path` keyword arguments found in CacheHelper are removed as they no longer possess any function. (Following the introduction of `@current_template`, virtual path is accessed via `@current_template.virtual_path` rather than as a standalone variable.) Lastly, the `@virtual_path` instance variable is removed from the codebase entirely, and all references to it are replaced with `@current_template.virtual_path.`

### Other Changes

The controller cache store used in actionview/test/template/render_test.rb is now set to `:memory_store` (was previously nil). This was necessary to provide a failing test fixed by this PR.

### Other Information

This PR is split into two separate commits. The first commit contains the minimum changes necessary to fix the bug described in #38984 while passing all tests. The second commit provides a refactor removing the redundant `@virtual_path` variable from the codebase entirely, and replacing it with `@current_template.virtual_path`. I've left them as separate commits to make it easier for reviewers to follow what changes fix #38984 and what's part of a tangential refactor, but happy to rebase into a single commit prior to merging.

### CODE REVIEW

**Comment by alipman88** [comment]
Hi @tenderlove, would you care to review this PR? It touches upon your work from 1581cab. Appreciate any attention!

File: actionview/lib/action_view/helpers/cache_helper.rb [hunk 1]
```diff
@@ -243,10 +237,10 @@ def fragment_name_with_digest(name, virtual_path, digest_path)
 
       def fragment_for(name = {}, options = nil, &block)
         if content = read_fragment_for(name, options)
-          @view_renderer.cache_hits[@virtual_path] = :hit if defined?(@view_renderer)
+          @view_renderer.cache_hits[@current_template&.virtual_path] = :hit if defined?(@view_renderer)
```
Comment (tenderlove) [inline actionview/lib/action_view/helpers/cache_helper.rb:240]: Before this change was `@virtual_path` nil sometimes?

**Review by tenderlove — APPROVED** [review]
I like this change.  Can you rebase to eliminate the conflict and I'll merge?

It would be nice if we could initialize the `@current_template` with a null object so that we can avoid using `&.` so much, but I think this PR is a win regardless.  Thank you!

File: actionview/lib/action_view/helpers/translation_helper.rb [hunk 2]
```diff
@@ -124,10 +124,10 @@ def localize(object, **options)
         def scope_key_by_partial(key)
           stringified_key = key.to_s
           if stringified_key.start_with?(".")
-            if @virtual_path
+            if @current_template&.virtual_path
               @_scope_key_by_partial_cache ||= {}
-              @_scope_key_by_partial_cache[@virtual_path] ||= @virtual_path.gsub(%r{/_?}, ".")
-              "#{@_scope_key_by_partial_cache[@virtual_path]}#{stringified_key}"
+              @_scope_key_by_partial_cache[@current_template&.virtual_path] ||= @current_template&.virtual_path.gsub(%r{/_?}, ".")
+              "#{@_scope_key_by_partial_cache[@current_template&.virtual_path]}#{stringified_key}"
```
Comment (jonathanhefner) [inline actionview/lib/action_view/helpers/translation_helper.rb:130]: I think there's no need for `&.` here because we're inside `if @current_template&.virtual_path`, yes?

File: actionview/lib/action_view/helpers/cache_helper.rb (hunk 1 above)
Comment (alipman88) [reply actionview/lib/action_view/helpers/cache_helper.rb:240]: Yeah, when using inline rendering:

```
class DemoController < ActionController::Base
  def index
    render inline: "<%= @virtual_path.nil? %>"
  end
end
```

File: actionview/lib/action_view/helpers/translation_helper.rb (hunk 2 above)
Comment (alipman88) [reply actionview/lib/action_view/helpers/translation_helper.rb]: Good catch, rebased accordingly!

**Comment by alipman88** [comment]
Thanks, @tenderlove! I've fixed the merge conflict.
