### PR TITLE
[Fix #50803] Consistently raise an `ArgumentError` when passing an invalid argument to a nested attributes association writer

### LINKED ISSUE #50803: Passing an invalid argument when assigning nested attributes only raises an `ArgumentError` for collection associations
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_one :last_comment, -> { order(id: :desc) }, class_name: "Comment"
  has_many :comments

  accepts_nested_attributes_for :last_comment
  accepts_nested_attributes_for :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  # ❌ Fails - Throws NoMethodError: undefined method `with_indifferent_access' for "foo":String
  def test_assigning_nested_attributes_for_singular_association_with_invalid_argument
    assert_raises(ArgumentError) do
      Post.create!(last_comment_attributes: "foo")
    end
  end

  # ✅ Passes
  def test_assigning_nested_attributes_for_collection_association_with_invalid_argument
    assert_raises(ArgumentError) do
      Post.create!(comments_attributes: "bar")
    end
  end
end
```

### Expected behavior

Passing an invalid argument when assigning nested attributes for both a singular and collection association should raise a similar `ArgumentError`.

### Actual behavior

Passing an invalid argument when assigning nested attributes for a collection association raises an `ArgumentError`, but it errors out with a `NoMethodError: undefined method 'with_indifferent_access' for "foo":String` for singular associations.

### System configuration
**Rails version**: Edge

**Ruby version**: 3.3.0

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

Fixes #50803.

### Detail

Updates `ActiveRecord::NestedAttributes#assign_nested_attributes_for_one_to_one_association` to raise an ArgumentError when given an invalid `attributes` argument similar to [`ActiveRecord::NestedAttributes#assign_nested_attributes_for_collection_association`](https://github.com/rails/rails/blob/9c3ffab47c3bf59320ba08e9dafdb0275cf91a5a/activerecord/lib/active_record/nested_attributes.rb#L488-L490).

Also makes a slight improvement to the existing error for collection associations.

### Additional information

None.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/lib/active_record/nested_attributes.rb [hunk 1]
```diff
@@ -421,10 +421,15 @@ def _destroy
       # update_only is true, and a <tt>:_destroy</tt> key set to a truthy value,
       # then the existing record will be marked for destruction.
       def assign_nested_attributes_for_one_to_one_association(association_name, attributes)
-        options = nested_attributes_options[association_name]
         if attributes.respond_to?(:permitted?)
           attributes = attributes.to_h
         end
+
+        unless attributes.is_a?(Hash)
+          raise ArgumentError, "Hash expected for `#{association_name}` attributes, got #{attributes.class.name} (#{attributes.inspect})"
```
Comment (byroot) [inline activerecord/lib/active_record/nested_attributes.rb:429]: Don't `attributes.inspect` risk leaking personal information into the error tracker / logs? Also is potentially very large.

I think just the class name is enough.

Comment (joshuay03) [reply activerecord/lib/active_record/nested_attributes.rb:429]: Ya good point, I'll adjust.

Comment (joshuay03) [reply activerecord/lib/active_record/nested_attributes.rb]: Actioned [here](https://github.com/rails/rails/compare/1cb4855aa1f76e0c1682bc071a286784c10accb9..1eab83a0a8d8c6b67ba83ab8e0abefa6ee8af4a8)
