### PR TITLE
Explicitly ignored wildcard verbs from head_routes

### LINKED ISSUE #18698: header fetching does not work any more with rails 4.2
Hi,

I have the following setup:

routes.rb
```ruby
   get 'is-alive-token' => 'heart_beat#index'
```
heart_beat_controller,rb

```ruby
class HeartBeatController < ApplicationController
  def index
    render json: {}, status: 200
  end
end
```

When I use:

```
  curl -I http://127.0.0.1:3000/is-alive-token
```

prior rails 4.2 I got `HTTP/1.1 200`

with rails 4.2 I get `HTTP/1.1 404` + an exception

```ruby
ActionController::RoutingError (No route matches [HEAD] "/is-alive-token")
```

Is there a new directive within the routes to get HEAD calls up and running?

regards
dieter

### PR DESCRIPTION
**Pull request by tsun1215**
In match_head_routes, deleted the routes in which request.request_method was empty (matches all HTTP verbs) when responding to a HEAD request. This prevents catch-all routes (such as Racks) from intercepting the HEAD request.

Fixes #18698

### CODE REVIEW

File: actionpack/lib/action_dispatch/journey/router.rb [hunk 1]
```diff
@@ -122,6 +122,7 @@ def find_routes req
 
         def match_head_routes(routes, req)
           head_routes = match_routes(routes, req)
+          head_routes.delete_if { |route| route.verb == // }
```
Comment (tgxworld) [inline actionpack/lib/action_dispatch/journey/router.rb]: I don't think that the responsibility of rejecting routes without a `request_method` should be handled by `match_head_routes`. [`AD::Journey::Route#matches`](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/journey/route.rb#L93) should reject routes which does not have a `request_method` constraint.

cc @pixeltrix WDYT?

Comment (tsun1215) [inline actionpack/lib/action_dispatch/journey/router.rb]: The problem comes because we are explicitly rejecting catch-all routes when doing a HEAD request. Since a head request is a special case of a GET request, we don't want to allow anything that doesn't explicitly accept HEAD requests. However, after the initial pass-through of the routes, and nothing is found, we fall back to allow GET routes (and catch-all routes) to respond. As a result, if we put the rejection in `matches?` the fallback becomes more difficult.

Comment (pixeltrix) [inline actionpack/lib/action_dispatch/journey/router.rb]: @tgxworld I went through this with @tsun1215 at the Open Academy yesterday and I think it's probably the least invasive method of doing it at the moment that we can backport to 4-2-stable. I suspect that this block of code will be rewritten again before Rails 5.0 ships

File: actionpack/test/dispatch/routing_test.rb [hunk 2]
```diff
@@ -3477,6 +3477,20 @@ def test_scope_where_as_is_empty
...
+    draw do
+      get '/home' => 'test#index'
+      mount rack_app, at: '/'
+    end
+    head '/home'
+    assert_response :success
+    head '/'
+    assert_response :not_found
+  end
+
```
Comment (pixeltrix) [inline actionpack/test/dispatch/routing_test.rb]: @tsun1215 can you reformat the test a bit to tidy it up:

``` ruby
def test_head_fetch_with_mount_on_root
  draw do
    get '/home' => 'test#index'
    mount lambda { |env|  [404, {"Content-Type" => "text/html"}, ["Not Found"]] }, at: '/'
  end

  head '/home'
  assert_response :success

  head '/'
  assert_response :not_found
end

```

**Comment by pixeltrix** [comment]
@tsun1215 this will also need a CHANGELOG entry before it can be merged

File: actionpack/CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,23 @@
+*   Explicitly ignored wildcard verbs when searching for HEAD routes before fallback
+
+    Fixes and issue where a mounted rack app at root would intercept the HEAD
```
Comment (tgxworld) [inline actionpack/CHANGELOG.md]: `Fixes and issue` I think there is a typo here :smile:

File: actionpack/lib/action_dispatch/journey/router.rb (hunk 1 above)
Comment (tgxworld) [inline actionpack/lib/action_dispatch/journey/router.rb]: @pixeltrix @tsun1215 Ok :smile_cat: 

Could we perhaps delete the routes before matching them?

```ruby
head_routes.delete_if { |route| route.verb == // }
head_routes = match_routes(routes, req)
```
Since we're going to reject them, we can do it earlier to avoid matching them.

Comment (pixeltrix) [inline actionpack/lib/action_dispatch/journey/router.rb]: @tgxworld yep, I think that should be okay - @tsun1215 can you change the PR please.

**Comment by tgxworld** [comment]
@tsun1215  Looks good  :) It'll be good if you can squash your commits.

http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html
> Please squash your commits into a single commit when appropriate. This simplifies future cherry picks, and also keeps the git log clean.

Thanks for fixing this :smile:

**Comment by tsun1215** [comment]
Squished into a single commit. Hopefully everything is fine now

**Comment by pixeltrix** [comment]
@tsun1215 thanks and congratulations on your first contribution to Rails

**Comment by tgxworld** [comment]
:clap:

**Comment by jeremy** [comment]
Looks like this means HEAD requests to mounted Rack apps will no longer work. We're missing a test case for that, so it slipped through the cracks!

**Comment by jeremy** [comment]
Hmm, I don't think we can fix both situations. We'd need to change `get` from "match GET" to "match GET & HEAD" instead of doing two passes, one matching HEAD then another matching GET.

**Comment by 42001983** [comment]
What or who is this why I get these emails

**Comment by jeremy** [comment]
Reverting this so master can move forward with passing tests. Please do revisit!

**Comment by hmarr** [comment]
Seems this [made it into 4.2.1](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/journey/router.rb#L124), and has prevented mounted rack apps from serving HEAD requests entirely (as @jeremy suggested it would).

Example here: https://gist.github.com/hmarr/054ee23e5a66afae2f7b

Until we have a proper solution, it'd be great to get a 4.2.x release out with this regression fixed.

**Comment by rafaelfranca** [comment]
> Until we have a proper solution, it'd be great to get a 4.2.x release out with this regression fixed.

Sorry, but we had the longest release candidate cycle in the whole story of the Rails framework and since this regression was not reported we are not going to rush a new release. Expect a new 4.2.x release in approximately one month.

**Comment by rafaelfranca** [comment]
Reverted on 4-2-stable. Lets track #19431
