### PR TITLE
Casting aggregated value takes attribute type precedence over database type

### LINKED ISSUE #39271: `SUM` is no longer casting to Integer with our custom MySQL adapter
In #39039 and then followup PRs the types on calculation got changed.                                                                                        
                                                                                                                                                             
We have a custom adapter at GitHub and the client for that adapter follows the MySQL spec - that `SUM` on integers should return a `BigDecimal`. See https://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html#function_sum for more information on that. 
                                                                                                                                                                                                                      
We have been unable to reproduce this outside of our application and at the moment our adapter and client are private so we can't share a reproduction script that actually breaks. The one provided here passes, but we've added notes about the behavior in GitHub.                                                     
                                                                                                                                                             
In our case the `BigDecimal` for `sum` calls was converted into `Integer` and now remains a `BigDecimal`. We have found that we can "fix" this by calling `yield` when we're using `sum` in `type_cast_calculated_value`, however that breaks other enum tests and we're not sure of next steps.

It also feels odd that the `type_cast_calculated_value` method only yields in the case of max and min, but the code makes it look like it always yields. With our bug it seems like there are more cases we should yield to ensure we deserialize.
                                                                                                                                                             
Here is the diff that fixes our use case, but breaks enums:                                                                                                                                   
                                                                                                                                                             
``` ruby
--- a/activerecord/lib/active_record/relation/calculations.rb
+++ b/activerecord/lib/active_record/relation/calculations.rb
@@ -417,7 +417,7 @@ def type_for(field, &block)
       def type_cast_calculated_value(value, operation)
         case operation
         when "count", "sum"
-          value || 0
+          yield value || 0
         when "average"
           value&.respond_to?(:to_d) ? value.to_d : value
         else # "minimum", "maximum"
```                                                                                                                            
                                                                                                                                                             
                                                                                                                                                             
And here is the script that doesn't fail for MySQL or other adapters, but fails with our adapter.                                                                                        
                                                                                                                                                             
```ruby
require "active_record"                                                                                                                                      
require "minitest/autorun"                                                                                                                                   
require "logger"                                                                                                                                             
                                                                                                                                                             
ActiveRecord::Base.establish_connection(adapter: "mysql2", database: "activerecord_unittest")                                                                
ActiveRecord::Base.logger = Logger.new(STDOUT)                                                                                                               
                                                                                                                                                             
ActiveRecord::Schema.define do                                                                                                                               
  create_table :posts, force: true do |t|                                                                                                                      end                                                                                                                                                        
                                                                                                                                                             
  create_table :comments, force: true do |t|                                                                                                                 
    t.integer :post_id                                                                                                                                       
    t.integer :stars                                                                                                                                         
  end                                                                                                                                                        
end                                                                                                                                                          
                                                                                                                                                             
class Post < ActiveRecord::Base                                                                                                                              
  has_many :comments                                                                                                                                         
                                                                                                                                                               def sum_comment_stars                                                                                                                                      
    comments.where('1=1').sum(:stars)                                                                                                                        
  end                                                                                                                                                        end                                                                                                                                                          
                                                                                                                                                             
class Comment < ActiveRecord::Base                                                                                                                           
  belongs_to :post                                                                                                                                           
end                                                                                                                                                          
                                                                                                                                                             
class BugTest < Minitest::Test                                                                                                                               
  def test_association_stuff                                                                                                                                 
    post = Post.create!                                                                                                                                      
    post.comments << Comment.create!(stars: 20)                                                                                                              
    post.comments << Comment.create!(stars: 300)                                                                                                             
                                                                                                                                                             
    assert_equal 320, post.sum_comment_stars                                                                                                                 
    assert_equal Integer, post.sum_comment_stars.class # This returns BigDecimal in our app.                                                                 
  end                                                                                                                                                        
end                                                                                                                                                          
```
                                                                                                                                                             
This is unfortunately blocking our Rails upgrade and we're not sure how to fix this. @kamipo can you take a look and let us know what you think?

Thanks!

### PR DESCRIPTION
**Pull request by kamipo**
Follow up to #39255, #39039.

One of the purpose of #39039 was to unify the behavior between the
databases.

Original code was:

```ruby
    type   = result.column_types.fetch(column_alias) do
      type_for(column_name)
    end
```

The code will attempt looking up type from `column_types`, then fallback
to attribute types, so I supposed the code was originally intended to
cast a value by the database types.

But now, most modern clients will already return casted values, and no
longer use `column_types`, except Postgres.
As a result, now most adapter accidentally fallback to attribute types.
Since casted by attribute types sometimes doesn't return numeric values,
I've unified the behavior to use database types consistently in #39039.

But later, I've learned that attribute types have important settings
like time zone aware attributes (#39255), and some existing code relying
on attribute types over database types (#39271).

I've changed all aggregated values are casted by attribute types.

Fixes #39271.

cc @eileencodes

### CODE REVIEW

File: activerecord/lib/active_record/relation/calculations.rb [hunk 1]
```diff
@@ -416,8 +416,10 @@ def type_for(field, &block)
...
       def type_cast_calculated_value(value, operation)
         case operation
-        when "count", "sum"
-          value || 0
+        when "count"
+          value.to_i
+        when "sum"
+          yield value || 0
         when "average"
           value&.respond_to?(:to_d) ? value.to_d : value
```
Comment (kamipo) [inline activerecord/lib/active_record/relation/calculations.rb:424]: Note that historically "count" and "average" didn't use type cast originally.

**Comment by eileencodes** [comment]
Thanks for the quick fix with this one @kamipo! 💖
