### PR TITLE
Set default variant format from blob content type

### LINKED ISSUE #39921: Vips::Error: No known saver for '/tmp/image_processing20200724-11554-lsl5p1.jfif'
### Steps to reproduce

```ruby
class SomeModel < ApplicationRecord
  has_one_attached :file
end

model = SomeModel.create!
model.file.attach(io: File.open('image.jfif'), filename: 'image.jfif', content_type: 'image/jpeg')
model.file.representation({resize_to_fit: [1920, 1920]}).processed
```

### Expected behavior
Generate a representation

### Actual behavior
```
Error:
CollectionTest#test_jfif_file_format:
Vips::Error: No known saver for '/tmp/image_processing20200724-11554-lsl5p1.jfif'.
```

### System configuration
**Rails version**: 6.0.3.1

**Ruby version**: 2.5.1p57

Used image: [image.zip](https://github.com/rails/rails/files/4972128/image.zip)

### LINKED ISSUE #39983: Variant PNG image without file format causes transparency to be lost
### Steps to reproduce
```
class Blog < ApplicationRecord
  has_one_attached :image
end

blog = Blog.create!
blog.image.attach(io: File.open('png_image_without_format'), filename: 'png_image_without_format', content_type: 'image/png')

# variant image lost transparency
image_tag(blog.image.variant(resize: '100x100'))
```

[png_image_without_format.zip](https://github.com/rails/rails/files/5025922/png_image_without_format.zip)

### Expected behavior
Variant image should be generated as `png` and maintain transparency.

### Actual behavior
Variant image is created as `jpg` causing the transparency to be lost. 

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.5.0

### PR DESCRIPTION
**Pull request by georgeclaghorn**
VIPS determines the destination file format from its extension, and unlike ImageMagick, it never defaults to the source format. ImageProcessing falls back to JPEG when we don’t we don’t provide a format, so if we want to preserve the source format, we must explicitly specify it.

Supersedes #39984 by leaning on the variation to specify the desired destination format. This allows customizing the destination format.

Fixes #39921.
Fixes #39983.
Closes #38160.

To-do:
- [x] Decide on a MIME type database. We have four(!) available in a typical Rails app: `Mime::Type`, `Rack::Mime`, `MiniMime`, `MimeMagic`.
- [x] Add tests for the default.
- [x] Add tests for customization.

### CODE REVIEW

File: activestorage/app/models/active_storage/blob/representable.rb [hunk 1]
```diff
@@ -95,6 +95,26 @@ def representable?
   end
 
   private
+    def default_transformations
+      { format: default_variant_format }
+    end
```
Comment (jonathanhefner) [inline activestorage/app/models/active_storage/blob/representable.rb:100]: Since this is only used by `variant` (and not `preview`), would it be better to indicate that in the name, i.e. `default_variant_transformations`?

File: activestorage/app/models/active_storage/variation.rb [hunk 2]
```diff
@@ -43,16 +43,32 @@ def initialize(transformations)
...
   end
 
+  def default_to(defaults)
+    self.class.new transformations.reverse_merge(defaults)
+  end
+
   # Accepts a File object, performs the +transformations+ against it, and
   # saves the transformed image into a temporary file. If +format+ is specified
   # it will be the format of the result image, otherwise the result image
   # retains the source format.
```
Comment (jonathanhefner) [inline activestorage/app/models/active_storage/variation.rb:53]: :scissors: 
```suggestion
  # saves the transformed image into a temporary file.
```

**Review by jonathanhefner — COMMENTED** [review]
I love how this makes the code even more readable!

File: activestorage/app/models/active_storage/blob/representable.rb (hunk 1 above)
Comment (georgeclaghorn) [reply activestorage/app/models/active_storage/blob/representable.rb:100]: My thinking was that these indirectly apply to previews, too, since `ActiveStorage::Preview` ends up calling `variant` on the generated preview image blob. But I do think it’s better as `default_variant_transformations`.

**Comment by SamSaffron** [comment]
Note, Mail already has a dependency to mini_mime (which has 100% parity DB wise with the mime types gem - it uses the same db), might as well just keep using it it solves the problem, it has the smallest memory footprint. Recommend against Rack::Mime cause the db is not nearly complete https://www.rubydoc.info/gems/rack/Rack/Mime 

not sure about mimemagick this is the first time I heard about it.
