### PR TITLE
Keep configuration of smtp_settings consistent between 6.1 and 7.0

### LINKED ISSUE #44059: Behaviour of `smtp_settings` config has changed between Rails 6 to Rails 7
### Steps to reproduce
I've created a repo here https://github.com/iCareWorld/rails-7-clobber-smtp-settings-example which outlines the problem in greater detail and provides a way of easily recreating the issue using Docker Compose.

### Overview
Rails 7 has introduced new behaviour that resets the `smtp_settings` of the Action Mailer config to `nil` when the `ActionMailer::Base` class is loaded.

### Expected behavior
Rails 7 would follow the same behaviour as Rails 6 or a note would be added to the changelog about the new behaviour.

### Actual behavior
When `ActionMailer::Base` is loaded, the `smtp_settings` of the action mailer config is set to nil. This breaks any further code which relies on values in these settings.

#### Rails 6 (original behaviour)

```ruby
root@1c47d009f88c:/usr/src/app# rails c
Running via Spring preloader in process 32
Loading development environment (Rails 6.1.4.4)
irb(main):001:0> Rails.configuration.action_mailer.smtp_settings
=> {:domain=>"example.com"}
irb(main):002:0> ApplicationMailer
=> ApplicationMailer
irb(main):003:0> Rails.configuration.action_mailer.smtp_settings
=> {:domain=>"example.com"}
irb(main):004:0>
```

#### Rails 7 (new behaviour)
```ruby
root@d78adf052815:/usr/src/app# rails c
Loading development environment (Rails 7.0.0)
irb(main):001:0> Rails.configuration.action_mailer.smtp_settings
=> {:domain=>"example.com"}
irb(main):002:0> ApplicationMailer
=> ApplicationMailer
irb(main):003:0> Rails.configuration.action_mailer.smtp_settings
=> nil
irb(main):004:0>
```

### System configuration
**Rails version**: 7.00
**Ruby version**: 3.0.3

### PR DESCRIPTION
**Pull request by andrehjr**
### Summary

When configuring a new default for smtp_settings we ended up deleting the key from Rails.configuration.action_mailer.smtp_settings [here](https://github.com/rails/rails/commit/52db7f2ef3c4a902227cac163657c89282986e25#diff-b2555388d34f4657f98f10cd106ccac94433e322044fb9455724b09247984850R48-R50).

Ideally I think people should rely on ActionMailer::Base.smtp_settings instead of Rails.configuration.action_mailer.smtp_settings.

But in order to keep the same behavior as previous versions, this is an attempt to keep things as they were while adding the new defaults for smtp_timeouts.

Fixes #44059

### CODE REVIEW

File: actionmailer/lib/action_mailer/railtie.rb [hunk 1]
```diff
@@ -45,13 +46,9 @@ class Railtie < Rails::Railtie # :nodoc:
...
         end
 
-        if smtp_settings = options.delete(:smtp_settings)
-          self.smtp_settings = smtp_settings
-        end
-
         if smtp_timeout = options.delete(:smtp_timeout)
-          self.smtp_settings[:open_timeout] ||= smtp_timeout
-          self.smtp_settings[:read_timeout] ||= smtp_timeout
+          options.smtp_settings[:open_timeout] ||= smtp_timeout
```
Comment (rafaelfranca) [inline actionmailer/lib/action_mailer/railtie.rb:50]: We should not be mutating the `options` here. I think we can just avoid doing a delete a dup the options before passing.

File: railties/test/application/configuration_test.rb [hunk 2]
```diff
@@ -2745,21 +2745,31 @@ def index
...
+      RUBY
 
       app "development"
 
-      assert_equal 5, ActionMailer::Base.smtp_settings[:open_timeout]
-      assert_equal 5, ActionMailer::Base.smtp_settings[:read_timeout]
+      smtp_settings = { domain: "example.com", open_timeout: 5, read_timeout: 5 }
+
+      assert_equal smtp_settings, ActionMailer::Base.smtp_settings
+      assert_equal smtp_settings, Rails.configuration.action_mailer.smtp_settings
```
Comment (rafaelfranca) [inline railties/test/application/configuration_test.rb:2758]: This should only contain `domain` to keep the same behavior.

**Review by rafaelfranca — CHANGES_REQUESTED** [review]

File: railties/test/application/configuration_test.rb (hunk 2 above)
Comment (andrehjr) [reply railties/test/application/configuration_test.rb:2758]: On 6.1 smtp_settings is passed down directly into ActionMailer from the config, and it's the same object. That's why I added this line. Maybe I'm missing something? 

```
Loading development environment (Rails 6.1.4.4)
irb(main):001:0> Rails.configuration.action_mailer.smtp_settings
=> {:domain=>"example.com"}
irb(main):002:0> ActionMailer::Base.smtp_settings
=> {:domain=>"example.com"}
irb(main):003:0> ActionMailer::Base.smtp_settings.object_id
=> 12100
irb(main):004:0> Rails.configuration.action_mailer.smtp_settings.object_id
=> 12100
irb(main):005:0> Rails.configuration.action_mailer.smtp_settings["foo"] = "bar"
=> "bar"
irb(main):006:0> ActionMailer::Base.smtp_settings
=> {:domain=>"example.com", "foo"=>"bar"}
```

Comment (rafaelfranca) [reply railties/test/application/configuration_test.rb:2758]: hmmm, I see.
