### PR TITLE
Multi-database: better support pending migration checks

### LINKED ISSUE #37524: ActiveRecord::PendingMigrationError is not raised when non-primary database migration is down with multi-db
### Steps to reproduce
ActiveRecord::PendingMigrationError is not raised when non-primary database migrations are down with multi-db.

config database.yml 

```
development:
  backbone:
    <<: *default
    database: backbone_development
  library:
    <<: *default
    database: library_development
    migrations_paths: db/library_migrate
```

run the following
```
bin/rails g scaffold User title 
bin/rails g scaffold Book title --db library
bin/rails db:create db:migrate
bin/rails s
# in another console
bin/rails g migration add_published_at_to_books published_at:datetime --db library
```
access http://localhost:3000/users or http://localhost:3000/books

### Expected behavior
Raise ActiveRecord::PendingMigrationError because add_published_at_to_books migration status is down

```
$ bin/rails db:migrate:status

database: backbone_development
 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20191022014341  Create users

database: library_development

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20191022023152  Create books
  down    20191022023755  Add published at to books
```

```
$ rails db:abort_if_pending_migrations
You have 1 pending migration:
  20191022023755 AddPublishedAtToBooks
Run `rails db:migrate` to update your database then try again.
```
### Actual behavior
There is no error

### System configuration
Rails 6.0.0
Ruby 2.6.5

### PR DESCRIPTION
**Pull request by hkdsun**
Co-authored-by: Guo Xiang Tan <gxtan1990@gmail.com> 
cc @tgxworld 

### Motivation / Background

Another attempt at fixing https://github.com/rails/rails/issues/37524

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] There are no typos in commit messages and comments.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Feature branch is up-to-date with `main` (if not - rebase it).
* [x] Pull request only contains one commit for bug fixes and small features. If it's a larger feature, multiple commits are permitted but must be descriptive.
* [x] Tests are added if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [x] PR is not in a draft state.
* [ ] CI is passing.

Closes https://github.com/rails/rails/issues/37524

### CODE REVIEW

**Review by hkdsun — COMMENTED** [review]
@eileencodes mind having a look here? I wasn't sure how we'd want the code to be structured exactly but the logic passes tests, so that's a good start

File: activerecord/lib/active_record/migration.rb [hunk 1]
```diff
@@ -621,6 +621,17 @@ def build_watcher(&block)
         def connection
           ActiveRecord::Base.connection
         end
+
+        def check_pending_migrations_unsafely
+          prev_db_config = Base.connection_db_config
+          all_configs = ActiveRecord::Base.configurations.configs_for # this needs an env_name parameter but i can't figure it out
```
Comment (eileencodes) [inline activerecord/lib/active_record/migration.rb:627]: You can grab the ENV from `ActiveRecord::ConnectionHandling::DEFAULT_ENV.call`.

File: activerecord/lib/active_record/migration.rb [hunk 2]
```diff
@@ -681,6 +693,18 @@ def migrate(direction)
       def disable_ddl_transaction!
         @disable_ddl_transaction = true
       end
+
+      private
+        def check_pending_migrations_unsafely
+          prev_db_config = Base.connection_db_config
+          all_configs = ActiveRecord::Base.configurations.configs_for(env_name: Rails.env)
```
Comment (eileencodes) [inline activerecord/lib/active_record/migration.rb:700]: In this one we could pass `all_configs` to `check_pending_migrations` since we have them in `load_schema_if_pending!`.

The method `load_schema_if_pending!` is only called from parallel testing which is why it's safe to use `Rails.env` here. It has to load the env for that to work, but in the other location we need to follow the contract that Active Record works without Rails.

File: activerecord/lib/active_record/migration.rb [hunk 3]
```diff
@@ -598,7 +598,7 @@ def call(env)
         @mutex.synchronize do
           @watcher ||= build_watcher do
             @needs_check = true
-            ActiveRecord::Migration.check_pending!(connection)
+            check_pending_migrations_unsafely
```
Comment (eileencodes) [inline activerecord/lib/active_record/migration.rb:601]: I'd prefer to just call this `check_pending_migrations` rather than have the `unsafely` 😄 (especially since it's an internal method).

**Review by eileencodes — COMMENTED** [review]
Looking good so far, added some comments about how to get the env and style/implementation. Thanks for working on this!

File: activerecord/lib/active_record/migration.rb (hunk 1 above)
Comment (hkdsun) [reply activerecord/lib/active_record/migration.rb:627]: Oh, after looking at its definition I see why it's used in a few places!

**Comment by hkdsun** [comment]
Hmm this is a strange CI failure for this PR 💭 

```
# Running:
--
  |  
  | .............F
  |  
  | Failure:
  | LoadingTest#test_descendants_loaded_after_framework_initialization_are_cleaned_on_each_request_if_reloading_is_enabled [test/application/loading_test.rb:142]:
  | --- expected
  | +++ actual
  | @@ -1 +1 @@
  | -["Post"]
  | +["ActionMailbox::InboundEmail", "ActionMailbox::Record", "Post"]
  |  
  |  
  |  
  | rails test test/application/loading_test.rb:112
  |  
  | ....
```

**Comment by eileencodes** [comment]
Looks like the test failure is caused by the call to `Migrator.migrations_paths` which causes ActionMailbox to load due to this line https://github.com/rails/rails/blob/main/actionmailbox/test/test_helper.rb#L7. I'm not sure why this is problematic in `build_watcher` but working fine when called from the connection directly.

File: railties/test/application/loading_test.rb [hunk 4]
```diff
@@ -139,9 +139,11 @@ class Post < ApplicationRecord
 
     assert_equal initial, ActiveRecord::Base.descendants.collect(&:to_s).sort.uniq
     get "/load"
-    assert_equal [Post].collect(&:to_s).sort, ActiveRecord::Base.descendants.collect(&:to_s).sort - initial
+    assert_equal 200, last_response.status
```
Comment (hkdsun) [inline railties/test/application/loading_test.rb:142]: In a very interesting cascade of events, turns out the failing test was actually because this was returning a 500 due to a `table 'posts' not found`!! The table was not being found because the new connection switching code in the `check_pending_migrations` call re-establishes the `Base.connection`, even if there is only a single database configured, which is usually fine, except the `setup_ar!` method of this test file was for some reason overriding the SQLite database name to `:memory:`, which lo and behold, means getting a fresh/empty database on every reconnect (essentially dropping the table by the time we actually run the request).

> Instead, a new database is created purely in memory. The database ceases to exist as soon as the database connection is closed. Every :memory: database is distinct from every other. So, opening two database connections each with the filename ":memory:" will create two independent in-memory databases.

(see https://www.sqlite.org/inmemorydb.html)

🤯

Comment (hkdsun) [reply railties/test/application/loading_test.rb:142]: Anyway, I have improved a few issues I saw with the assertions in this test as well. Namely, 

1. asserting that the last request actually succeeded 
2. not referencing `Post` from outside the app, because otherwise our assertion would be invalid

Comment (eileencodes) [reply railties/test/application/loading_test.rb:142]: Just so we can be sure this is unrelated to your changes, do you mind sending these changes as a separate PR that I'll merge first?

Comment (hkdsun) [reply railties/test/application/loading_test.rb:142]: https://github.com/rails/rails/pull/46237
