### PR TITLE
Fix `insert_all`/`upsert_all` to handle STI

### LINKED ISSUE #46404: Bulk upsert/insert does not respect Single Table Inheritance
### Steps to reproduce

Create a model with single table inheritance, and use the subclassed model to do an insert/upsert call. The type value is not respected, so the models created/updated can only be referenced via the main table class.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :foos, force: true do |t|
       t.string :type, null: false
       t.integer :value
  end
end

class Foo < ActiveRecord::Base
end

class Bar < Foo
end

class BugTest < Minitest::Test
  def test_sti_upsert
    new_bars = 5.times.map do |i|
        { value: i }
   end
    Bar.insert_all(new_bars)

    assert_equal 5, Bar.count # fails here: there are no Bar records
    assert_equal new_bars.pluck(:value), Bar.all.pluck(:value)
  end
end
```

### Expected behavior

The `type` value should be inferred by the STI class name.

### Actual behavior

The `type` field is set to `nil` unless explicitly added into the hash.

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #46404.

### CODE REVIEW

File: activerecord/test/cases/insert_all_test.rb [hunk 1]
```diff
@@ -282,6 +283,26 @@ def test_insert_all_and_upsert_all_with_aliased_attributes
...
+    assert_difference -> { Category.count }, 2 do
+      SpecialCategory.insert_all [{ name: "First" }, { name: "Second", type: nil }]
+    end
+
+    first, second = Category.last(2)
+    assert_equal "SpecialCategory", first.type
+    assert_nil second.type
+
+    if supports_insert_on_duplicate_update?
+      SpecialCategory.upsert_all [{ id: 103, name: "First" }, { id: 104, name: "Second", type: nil }]
```
Comment (simi) [inline activerecord/test/cases/insert_all_test.rb:296]: :thinking: Any chance to use different model with some unique column to not hardcode ids in here? Not sure if that's possible with Rails test suite setup, but I had hard time debugging similar randomly failing specs due to this.

Comment (fatkodima) [reply activerecord/test/cases/insert_all_test.rb:296]: This is a style used in this test file (see the test above this, for example), so 🤷.

Comment (simi) [reply activerecord/test/cases/insert_all_test.rb:296]: Yeah, I have checked. IMHO It is better late than never. Anyway it is just nitpick. PR looks good. :muscle:
