### PR TITLE
Change `ActionDispatch::Response#content_type` returning Content-Type header as it is

### LINKED ISSUE #35709: Rails ignoring provided content-type parameters other than charset
### Steps to reproduce
In a controller, render something with a specified content-type:

``` ruby
render body: "test content",
       content_type: "text/html; sandwiches=tasty; charset=utf-8; birds=flying"
```

See https://gist.github.com/85892fccc12d05d60c3d60c76c14500e for a single-file reproduction or https://github.com/leequarella/content-type-rails-bug for a rails app reproducing the problem.

### Expected behavior
It includes all key/value pairs `sandwiches=tasty` and `birds=flying` in the Content-Type header returned to the browser.

### Actual behavior
It strips out all key/value pairs and returns a content-type of `text/html; charset=utf-8" to the browser.

### System configuration
**Rails version**:
Current master (4c8a333)

**Ruby version**:
2.5.1

### Related PRs
https://github.com/rails/rails/pull/35549 - This seems to have started the behavior when it fixed certain issues with the character set portion of the content-type
https://github.com/rails/rails/pull/35706 - This fixed the issue in Rails 5.2 but not Rails 6.0

/cc @leequarella, @cpruitt, @jhawthorn

### PR DESCRIPTION
**Pull request by y-yagi**
Since #35549, `Response#conten_type` returns only MIME type correctly.
It is a documented behavior that this method only returns MIME type, so this change seems appropriate.
https://github.com/rails/rails/blob/39de7fac0507070e3c5f8b33fbad6fced84d97ed/actionpack/lib/action_dispatch/http/response.rb#L245-L249

But unfortunately, some users expect this method to return all Content-Type that does not contain charset. This seems to be breaking changes.

We can change this behavior with the deprecate cycle.
But, in that case, a method needs that include Content-Type with additional parameters. And that method name is probably the `content_type` seems to properly.

So I changed the new behavior to more appropriate another method(`mime_type`) and restored `Response#conten_type` to the original behavior.

The original `conten_type` method seems to have some problems with charset parsing (it implicitly expects charset to be at the end). So I think we should consider the appropriate behavior again later.

Fixes #35709.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/pull/16018.

I'm not sure how we end up with that much code since I opened that PR but it seems we are doing too much work to get the `content_type`. Do we need all that code?

**Comment by rafaelfranca** [comment]
> Since #35709, `Response#conten_type` returns only MIME type correctly.

That was always the case. Unless I'm missing something. That was the behavior I found when I opened #16018.

**Comment by y-yagi** [comment]
In my understanding, this not always the case. Until #35709, `Response#conten_type` returned media type parameters. 
Following script passes with Rails 5.2.2.1, but not with Rails 6.0.0. 

```ruby 
require "bundler/inline"

gemfile(true) do
  # gem "rails", "6.0.0.rc1"
  gem "rails", "5.2.2.1"
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_content_type
    resp = ActionDispatch::Response.new(200, "Content-Type" => "application/fhir+json; fhirVersion=1; charset=utf-8;")
    assert_equal "application/fhir+json; fhirVersion=1", resp.content_type
  end
end
``` 

**5.2.2.1**

``` 
$ ruby 36034.rb
Run options: --seed 30174

# Running:

.

Finished in 0.009994s, 100.0630 runs/s, 100.0630 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

**6.0.0** 

```
$ ruby 36034.rb
# Running:

F

Failure:
BugTest#test_content_type [36034.rb:13]:
--- expected
+++ actual
@@ -1 +1 @@
-"application/fhir+json; fhirVersion=1"
+"application/fhir+json"



rails test 36034.rb:11



Finished in 0.021647s, 46.1949 runs/s, 46.1949 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
``` 

I have doubts whether this was an intentional behavior, but I'm concerned about incompatibilities due to a change in behavior. 
(I missed #16018. It seems to me that it is the good approach.)

**Comment by rafaelfranca** [comment]
:+1: I think we should just do what #16018 did. It means that charset will be now in the `content_type` return, but that will also allow all the methods that I tested in #16018 will work again. With a good CHANGELOG entry and an entry in the upgrade guide I think we can get far with #16018.

**Comment by kaspth** [comment]
@rafaelfranca so that would mean apps should generally use `request.media_type` instead of `request.content_type`?

**Comment by rafaelfranca** [comment]
Depends on what they want. If they want all the things they expect in #35709 they should be using `content_type`. If they only want the mime type like `application/json` they should be using `mime_type`.

**Comment by y-yagi** [comment]
I updated PR based on #16018.

File: actionpack/lib/action_dispatch/http/response.rb [hunk 1]
```diff
@@ -243,8 +243,13 @@ def content_type=(content_type)
     end
 
     # Content type of response.
-    # It returns just MIME type and does NOT contain charset part.
     def content_type
+      type = super
+      type&.empty? ? nil : type
```
Comment (kamipo) [inline actionpack/lib/action_dispatch/http/response.rb]: This line is a bit hard to understand. Is it not enough `super.presence`?

Comment (y-yagi) [reply actionpack/lib/action_dispatch/http/response.rb]: :+1:  I fixed with 22274d320e36a4750fd83b096fb3a490c96559d6. Thanks!

File: actionpack/test/controller/render_xml_test.rb [hunk 2]
```diff
@@ -92,11 +92,11 @@ def test_should_render_formatted_xml_erb_template
 
   def test_should_render_xml_but_keep_custom_content_type
```
Comment (abhaynikam) [inline actionpack/test/controller/render_xml_test.rb]: @y-yagi : Should we rename the test description here from `content_type` to `media_type`? I made the changes but was not sure to raise PR. 

At other places, it looked fine to me. Only test desc here should maybe change.

Comment (y-yagi) [reply actionpack/test/controller/render_xml_test.rb]: This is test is to confirm that `content_type` takes precedence when specifying `render` and `content_type`. 
https://github.com/rails/rails/blob/90d6237762da832d0c6302b31fd68d3efb771c64/actionpack/test/controller/render_xml_test.rb#L39
So I think the current test name is appropriate.

**Comment by cpruitt** [comment]
This change just landed into our latest `6-0-stable` update at GitHub and turned out to be a breaking change causing quite a few failures. Overall I think the changes to `content_type` are probably justified, but it's a difficult switch to make for us while we're running our app against 5.2 at the same time. This change means 5.2 and 6.0 have different `content_type` return values making for a non-trivial number of conditionals.

**Comment by y-yagi** [comment]
Thanks for your feedback. I think your point is correct. I will try to add a config to control the behavior.

**Comment by themilkman** [comment]
>  I will try to add a config to control the behavior.

@y-yagi is there a way to configure the old behavior? As mentioned in  #35709 this has an big impact.
