### PR TITLE
Fix state leakage between tests

### LINKED ISSUE #47203: PostgreSQLAdapterTest#test_only_check_for_insensitive_comparison_capability_once fails
Managed to reproduce https://buildkite.com/rails/rails/builds/93254#018606ea-3aa9-43e1-a578-ca7c99db5472 failure via #47199

### Steps to reproduce

```ruby
cd activerecord
ARCONN=postgresql bin/test test/cases/validations/uniqueness_validation_test.rb test/cases/adapters/postgresql/postgresql_adapter_test.rb -n "/^(?:UniquenessValidationTest#(?:test_validate_case_insensitive_uniqueness)|ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#(?:test_unparsed_defaults_are_at_least_set_when_saving|test_only_check_for_insensitive_comparison_capability_once))$/" --seed 60206 -v
```

### Expected behavior
It should pass like using `--seed 42840`

```ruby
$ ARCONN=postgresql bin/test test/cases/validations/uniqueness_validation_test.rb test/cases/adapters/postgresql/postgresql_adapter_test.rb -n "/^(?:UniquenessValidationTest#(?:test_validate_case_insensitive_uniqueness)|ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#(?:test_unparsed_defaults_are_at_least_set_when_saving|test_only_check_for_insensitive_comparison_capability_once))$/" --seed 42840 -v
Using postgresql
Run options: -n "/^(?:UniquenessValidationTest#(?:test_validate_case_insensitive_uniqueness)|ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#(?:test_unparsed_defaults_are_at_least_set_when_saving|test_only_check_for_insensitive_comparison_capability_once))$/" --seed 42840 -v

# Running:

UniquenessValidationTest#test_validate_case_insensitive_uniqueness = 0.09 s = .
ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#test_only_check_for_insensitive_comparison_capability_once = 0.01 s = .
ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#test_unparsed_defaults_are_at_least_set_when_saving = 0.01 s = .

Finished in 0.122733s, 24.4432 runs/s, 211.8414 assertions/s.
3 runs, 26 assertions, 0 failures, 0 errors, 0 skips
$
```

### Actual behavior
It always fails as follows.

```ruby
$ ARCONN=postgresql bin/test test/cases/validations/uniqueness_validation_test.rb test/cases/adapters/postgresql/postgresql_adapter_test.rb -n "/^(?:UniquenessValidationTest#(?:test_validate_case_insensitive_uniqueness)|ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#(?:test_unparsed_defaults_are_at_least_set_when_saving|test_only_check_for_insensitive_comparison_capability_once))$/" --seed 60206 -v
Using postgresql
Run options: -n "/^(?:UniquenessValidationTest#(?:test_validate_case_insensitive_uniqueness)|ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#(?:test_unparsed_defaults_are_at_least_set_when_saving|test_only_check_for_insensitive_comparison_capability_once))$/" --seed 60206 -v

# Running:

UniquenessValidationTest#test_validate_case_insensitive_uniqueness = 0.08 s = .
ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#test_unparsed_defaults_are_at_least_set_when_saving = 0.01 s = .
ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#test_only_check_for_insensitive_comparison_capability_once = 0.00 s = F


Failure:
ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#test_only_check_for_insensitive_comparison_capability_once [/home/yahonda/src/github.com/rails/rails/activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb:495]:
1 or more queries expected, but none were executed..
Expected 0 to be >= 1.


bin/test test/cases/adapters/postgresql/postgresql_adapter_test.rb:487


Finished in 0.113529s, 26.4250 runs/s, 211.4003 assertions/s.
3 runs, 24 assertions, 1 failures, 0 errors, 0 skips
$
```

### System configuration
**Rails version**:  main branch

**Ruby version**: ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]

### PR DESCRIPTION
**Pull request by jessicajoly88**
### Motivation / Background
Fixes https://github.com/rails/rails/issues/47203

### Detail

The issue was about a test failing when executed in a particular order as part a series of tests described as below:
```
ARCONN=postgresql bin/test test/cases/validations/uniqueness_validation_test.rb test/cases/adapters/postgresql/postgresql_adapter_test.rb -n "/^(?:UniquenessValidationTest#(?:test_validate_case_insensitive_uniqueness)|ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#(?:test_unparsed_defaults_are_at_least_set_when_saving|test_only_check_for_insensitive_comparison_capability_once))$/" --seed 21290 -v
```

This test command runs the following tests in that order:

1. UniquenessValidationTest#test_validate_case_insensitive_uniqueness
2. ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#test_unparsed_defaults_are_at_least_set_when_saving
3. ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#test_only_check_for_insensitive_comparison_capability_once

The 1st and 2nd tests passes but the last one fails.

The below assertion is where the test fails because it's expecting queries to be run when `case_insensitive_comparison` is called but no queries are executed. 
```
assert_queries :any, ignore_none: true do
  @connection.case_insensitive_comparison(attribute, "foo")
end
```

This is happening for two reasons: 
**1) Schema cache not being cleared between tests**

 The purpose of the `case_insensitive_comparison` method is to perform a case insensitive comparison for the given attribute against a value. But the method needs to know if a comparison is possible based on the column type of the attribute being compared. To find out if it is capable of doing it, it run queries against Postgres which will return a boolean result. `true` if case insensitive comparison is possible for the column type of the attribute, otherwise `false`.

However, querying the database every time the method `case_insensitive_comparison` is called is not optimal for performance. So, a prior [PR](https://github.com/rails/rails/commit/b39050e8d574b814d3580688276e933a3d08aca8) tackled this issue by introducing a local cache layer aka `@case_insensitive_cache`, so that queries to the database are only done once.

So when debugging the 3rd test, we noticed that the `case_insensitive_comparison` method was looking up the column type `integer` in the cache `@case_insensitive_cache` when it should have been looking up  `example_type` based on the table created in the test. first_screenshot

We noticed that both the failing test and the second test ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#test_unparsed_defaults_are_at_least_set_when_saving both create a table called "ex" but with different column_types for the `number` attribute. When we skip the second test, the failing test now passes because it now looks up `example_type` in the `@case_insensitive_cache`.  We printed out the logs when debugging to see exactly what was happening behind the scenes and we saw that both tests were properly creating and dropping the tables during their lifecycle. We confirmed this by checking the postgres database. 

This led us to discover that Rails has a schema cache for performance reasons. We realized that the column_type used by the failing test was coming from the schema cache and NOT from what was defined in the table creation within the test. 
The third test (failing one) is  loading the  column_type for `number` from the schema cache populated by the table creation in the second test because both tests have the same table name e.g. "ex" and column name e.g. "number". 

To fix that, we clear the schema cache using `clear_data_source_cache!` on the table "ex". 

**2) `@case_insensitive_cache` not being cleared between tests**

The `case_insensitive_comparison` method uses a local cache between successive calls and the failing test was testing the functionality of that cache, and asserting that the queries against postgres were only performed once assuming that the cache was empty. But we found that the cache was not empty when the 3rd test executes because the 1st test also calls the `case_insensitive_comparison` method which populated the cache for column type `integer`. 
The 3rd test already passes by just clearing the schema cache. So why do we clear the `@case_insensitive_cache` again?
If another test is added that also calls the `case_insensitive_comparison` method with an attribute of the same column type e.g. `integer` or even `example_type`, then the 3rd test will fail because the cache knows about those column types. So, clearing `@case_insensitive_cache` ensures that the 3rd test will never fail the `assert_queries :any`.

You can see the cache being populated by the first test in the top section of this screenshot:
latest

### Additional information

- Is force clearing the schema cache the right approach? We would have expected the schema cache to be destroyed as part of the table drop 🤔 

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb [hunk 1]
```diff
@@ -659,6 +659,10 @@ def initialize_type_map(m) # :nodoc:
         end
       end
 
+      def clear_case_insensitive_cache
+        @case_insensitive_cache = { "citext" => false }
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:663]: This is exposing code that is only needed for tests. We can set the instance variable in the test to `nil` instead

File: activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb [hunk 2]
```diff
@@ -481,6 +481,7 @@ def test_unparsed_defaults_are_at_least_set_when_saving
 
           first_number.save!
           assert_equal 4, first_number.reload.number
+          @connection.schema_cache.clear_data_source_cache!(number_klass.table_name)
```
Comment (rafaelfranca) [inline activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb:484]: Why only those two tests needs to clean the schema cache given this table is used in more places than here?

File: activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb (hunk 1 above)
Comment (jessicajoly88) [reply activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb]: Oh yes, that worked. Thank you!

File: activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb (hunk 2 above)
Comment (jessicajoly88) [reply activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb:484]: We were thinking about that too e.g. does this need to happen for all the tests that use the same table name but we wanted to start by addressing this failure case. Should we do this for every test using the same table?

It feels weird to have to explicitly clear the schema cache to begin with. We were expecting the schema cache to be automatically cleared whenever a table is dropped.

Comment (fredma) [reply activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb:484]: An alternative we discussed would be to only clear the schema cache in the failing test just before table creation.

File: activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb [hunk 3]
```diff
@@ -485,13 +485,16 @@ def test_unparsed_defaults_are_at_least_set_when_saving
...
         @connection.execute("CREATE DOMAIN example_type AS integer")
+        @connection.schema_cache.clear_data_source_cache!(table_name)
 
         with_example_table "id SERIAL PRIMARY KEY, number example_type" do
           number_klass = Class.new(ActiveRecord::Base) do
-            self.table_name = "ex"
+            self.table_name = table_name
           end
           attribute = number_klass.arel_table[:number]
+          @case_insensitive_cache = nil
```
Comment (matthewd) [inline activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb:497]: This particular line won't do what we need, because it's setting an instance variable in the wrong object.

> 2) @case_insensitive_cache not being cleared between tests

Is this currently a problem? It's a horrible hack, but my intention in https://github.com/rails/rails/compare/rails:3349c3b...rails:fcf3388 was to side-step this issue by giving the column a unique-to-this-test type name.

File: activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb (hunk 2 above)
Comment (rafaelfranca) [reply activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb]: I'd investigate why the schema cache is keeping this information in this test only. If it is always keeping the information and other tests aren't failing because they are not exercising this codepath, we should make a generic "clean the cache after tests on this table" otherwise other tests could be added later that would fail for the same reason and we would have to investigate it again.

Comment (fredma) [reply activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb]: We looked into the lifecycle of the schema cache during test run, and we can see (using debug print) that the `schema_cache` is instantiated upon connection creation. The information builds up in the `schema_cache` as and when calls are made to retrieve column information e.g. `columns_hash`, `column_for_attribute`. The `schema_cache` is never cleared between tests. Looking at `DdlHelper` which creates table via `with_example_table`, we can see that tables are dropped by executing a raw query without calling the clear method on the schema cache. Interestingly, the `SchemaStatements` module clears the schema cache as part of the `drop_table` method.
So, I think it makes sense to go with the generic "clean the cache after tests on this table".

File: activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb (hunk 3 above)
Comment (jessicajoly88) [reply activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb]: Hey @matthewd 👋 , this isn't currently a problem but we see now that we were maybe future-proofing for something that has a low probability (but still a chance) of happening in that another test could be added in the future also using `example_type` as the column_type. 

We've removed our proposed changes to clearing `@case_insensitive_cache` in the tests so that our PR focuses solely on clearing the `schema_cache`.

**Comment by jessicajoly88** [comment]
## Update

We found that the `schema_cache` for a table was never cleared in a test context. This is because the method used to drop tables within our tests `with_example_table` doesn't use the `drop_table` method from [schema_statements](https://github.com/rails/rails/blob/e184d33dfcef9e7265781ec84af559af4781765c/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L57) which is what is usually used and takes care of clearing the `schema_cache` and dropping the table. 

Our proposed change replaces the raw query used to drop the table in `with_example_table` with the `drop_table` method mentioned above.
