### PR TITLE
thrown ActiveRecord::AssociationTypeMismatch when assigning a wrong value for a namespaced association

### LINKED ISSUE #20541: NameError instead of AssociationTypeMismatch when passing the wrong class of object to namespaced model associations
Suppose you have a Car model and a Wheel model, where Wheel belongs_to Car and Car has_many Wheels.  If you attempt to do `Wheel.new(car: "hi")`, you receive an error of type ActiveRecord::AssociationTypeMismatch because `"hi"`is not of class Car.  This works if Wheel and Car are at the root namespace.  If Wheel and Car are in a namespace, however, you receive a confusing `NameError: uninitialized constant Car`.  I'm guessing that this is thrown inside of Rails while trying to do the type checking or throw the correct error.

Here's a test case.  The relationships and assertions are the same, the only difference is that one is namespaced in the `Namespace` module and one is not.  I had to use 2 differently named sets of models so that the error for `Namespace::Apple` didn't accidentally reference `::Apple`.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '4.2.1'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "cars", force: :cascade do |t|
  end

  create_table "wheels", force: :cascade do |t|
    t.integer  "car_id"
  end

  create_table "namespace_apples", force: :cascade do |t|
    t.integer  "teacher_id"
  end

  create_table "namespace_teachers", force: :cascade do |t|
  end
end

class Wheel < ActiveRecord::Base
  belongs_to :car
end

class Car < ActiveRecord::Base
  has_many :wheels
end

module Namespace
  def self.table_name_prefix
    'namespace_'
  end
end

class Namespace::Teacher < ActiveRecord::Base
  has_many :apples
end

class Namespace::Apple < ActiveRecord::Base
  belongs_to :teacher
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_raises(ActiveRecord::AssociationTypeMismatch) { Namespace::Apple.new(teacher: "hello") }
    assert_raises(ActiveRecord::AssociationTypeMismatch) { Wheel.new(car: "hello") }
  end
end
```

### PR DESCRIPTION
**Pull request by dcrec1**
fixes #20541

### CODE REVIEW

File: activerecord/lib/active_record/associations/association.rb [hunk 1]
```diff
@@ -211,7 +211,7 @@ def foreign_key_present?
         # the kind of the class of the associated objects. Meant to be used as
         # a sanity check when you are about to assign an associated record.
         def raise_on_type_mismatch!(record)
-          unless record.is_a?(reflection.klass) || record.is_a?(reflection.class_name.constantize)
+          unless record.is_a?(reflection.klass) || (record.is_a?(reflection.class_name.constantize) rescue false)
```
Comment (matthewd) [inline activerecord/lib/active_record/associations/association.rb]: `safe_constantize`

Comment (dcrec1) [inline activerecord/lib/active_record/associations/association.rb]: Sorry, do you mean this?:

    record.is_a?(reflection.class_name.safe_constantize)

This breaks the tests because `#safe_constantize` returns `nil` when couldn't find a match and `record.is_a?(nil)` will thrown `TypeError: class or module required`.

**Comment by dcrec1** [comment]
@rafaelfranca

File: activerecord/test/models/admin/region.rb [hunk 2]
```diff
@@ -0,0 +1,6 @@
+# The class Region (without namespace) shouldn't exist
+# in order to the test test_type_mismatch_with_namespaced_class
+# be valid
+class Admin::Region < ActiveRecord::Base
```
Comment (senny) [inline activerecord/test/models/admin/region.rb]: Do we need to create new global models for a single test-case? We generally try to avoid extending those further. Would be nice if we can reproduce the problem with models defined in the test-case itself.

File: activerecord/lib/active_record/associations/association.rb (hunk 1 above)
Comment (senny) [inline activerecord/lib/active_record/associations/association.rb]: @dcrec1 you have to split up the one-liner. Using `safe_constantize` is preferred to `rescue false` as it doesn't hide programming errors:

```ruby
tpyo rescue false # => false
```

Something along the lines of:

```ruby
if klass = reflection.class_name.constantize
  record.is_a?(klass)
end
```

File: activerecord/lib/active_record/associations/association.rb [hunk 3]
```diff
@@ -211,12 +211,18 @@ def foreign_key_present?
...
         # a sanity check when you are about to assign an associated record.
         def raise_on_type_mismatch!(record)
-          unless record.is_a?(reflection.klass) || record.is_a?(reflection.class_name.constantize)
+          unless record.is_a?(reflection.klass) || valid_reloaded_class_for?(record)
             message = "#{reflection.class_name}(##{reflection.klass.object_id}) expected, got #{record.class}(##{record.class.object_id})"
             raise ActiveRecord::AssociationTypeMismatch, message
           end
         end
 
+        def valid_reloaded_class_for?(record)
```
Comment (dcrec1) [inline activerecord/lib/active_record/associations/association.rb]: @senny do you think this is a valid method name? wasn't so sure about how to call this.

File: activerecord/test/models/admin/region.rb (hunk 2 above)
Comment (dcrec1) [inline activerecord/test/models/admin/region.rb]: The test should be done with a class that only exists in a namespace, but maybe a possibility is to undefine `Account` and use `Admin::Account`. Do you think is better?

Also, I added a new validation to the test to ensure that it is really testing what it should.

Comment (senny) [inline activerecord/test/models/admin/region.rb]: wouldn't defining the class inside the test-case fit that description?

```ruby
class NamespacedBelongsToAssociationsTest < ActiveRecord::TestCase
  class Region < ActiveRecord::Base
  end
end
```

Comment (dcrec1) [inline activerecord/test/models/admin/region.rb]: Yes, defining `Admin::Region` in the test works, I'm updating the code, thanks :)

File: activerecord/test/schema/schema.rb [hunk 4]
```diff
@@ -23,6 +23,10 @@ def except(adapter_names_to_exclude)
     t.string :name
   end
 
+  create_table :admin_region, force: true do |t|
```
Comment (senny) [inline activerecord/test/schema/schema.rb]: please create the table in the test-case as well.

File: activerecord/test/models/admin/user.rb [hunk 5]
```diff
@@ -14,6 +14,7 @@ def load(s)
   end
 
   belongs_to :account
+  belongs_to :region
```
Comment (senny) [inline activerecord/test/models/admin/user.rb]: using a subclass you should be able to define the association in the test-case as well.

**Comment by dcrec1** [comment]
@senny do you think another change is needed?

File: activerecord/lib/active_record/associations/association.rb (hunk 3 above)
Comment (senny) [inline activerecord/lib/active_record/associations/association.rb]: @dcrec1 I think it's better to inline that into `raise_on_type_mismatch!`

File: activerecord/test/cases/associations/belongs_to_associations_test.rb [hunk 6]
```diff
@@ -147,6 +168,12 @@ def test_type_mismatch
     assert_raise(ActiveRecord::AssociationTypeMismatch) { Account.find(1).firm = Project.find(1) }
   end
 
+  def test_type_mismatch_with_namespaced_class
+    Admin::User.belongs_to(:region)
+    assert_nil defined?(Region), "This test should be done with a only namespaced class"
+    assert_raise(ActiveRecord::AssociationTypeMismatch) { Admin::User.new(region: 'wrong value') }
+  end
```
Comment (senny) [inline activerecord/test/cases/associations/belongs_to_associations_test.rb]: You should be able to define everything inline. The classes for example:

```ruby
  def test_type_mismatch_with_namespaced_class
    Admin.const_set "RegionalUser", (Class.new(Admin::User) {
                                       belongs_to(:region)
                                     })
    Admin.const_set "Region", Class.new(Admin::User)
    e = assert_raise(ActiveRecord::AssociationTypeMismatch) {
      Admin::RegionalUser.new(region: 'wrong value')
    }
    assert_match(/^Region\([^)]+\) expected, got String\([^)]+\)$/, e.message)
  ensure
    Admin.send :remove_const, "Region" if Admin.const_defined?("Region")
    Admin.send :remove_const, "RegionalUser" if Admin.const_defined?("RegionalUser")
  end
```

Some goes with the schema modifications that you currently do in `setup` and `teardown`. No need to do that for every test.

**Comment by senny** [comment]
@dcrec1 this also needs an entry in the changelog.

File: activerecord/lib/active_record/associations/association.rb (hunk 3 above)
Comment (dcrec1) [inline activerecord/lib/active_record/associations/association.rb]: Like this?:

    unless record.is_a?(reflection.klass) ||  (record.is_a?(klass) if klass = reflection.class_name.safe_constantize)

Note that this conditional is almost never evaluated, so doing something like this would be less efficient:

    valid_reloaded_class = record.is_a?(klass) if klass = reflection.class_name.safe_constantize
    unless record.is_a?(reflection.klass) ||  valid_reloaded_class

Which way should I go?

Comment (senny) [inline activerecord/lib/active_record/associations/association.rb]: note that it's possible to nest the conditionals:

```ruby
unless record.is_a?(reflection.klass)
  fresh_class =  reflection.class_name.safe_constantize
  unless record.is_a?(fresh_class)
    raise ActiveRecord::AssociationTypeMismatch
  end
end
```

Comment (dcrec1) [inline activerecord/lib/active_record/associations/association.rb]: This way works, will change the code.

**Comment by senny** [comment]
I merged a slightly modified version of this PR. The changes are contained in the merge commit (8e27fd95945ac9f81a5ad1b30e5d6c5f32878afa).

@dcrec1 thank you :yellow_heart:

**Comment by dcrec1** [comment]
thanks @senny
