### PR TITLE
Ignore test env in DatabaseTasks when DATABASE_URL is present

### LINKED ISSUE #28827: rake db:* tasks ignore DATABASE_URL settings, partly
### Steps to reproduce
1. export DATABASE_URL with settings different from `database.yml`
2. run any databased related rake tasks (db:setup, db:create, db:drop, etc) with RAILS_ENV set to `development` or unset

### Expected behavior
Settings in DATABASE_URL, such as MySQL host, is used for both `development` and 'test' databases.

### Actual behavior
Settings in DATABASE_URL are used when the task is run for `development` environment, but they are not used for `test` environment

### System configuration
**Rails version**:
5.0.2

**Ruby version**:
2.3.1

### PR DESCRIPTION
**Pull request by bbuchalter**
Fixes https://github.com/rails/rails/issues/28827.

The steps to reproduce are as follows:
```
git clone git@github.com:bbuchalter/rails-issue-28827.git
cd rails-issue-28827
bundle install
bin/rails db:create
```

Observe that we create both `development` and `test` databases when invoking `db:create` . Now observe what happens when we invoke our drop command while using `DATABASE_URL`.

```
DATABASE_URL=sqlite3://$(pwd)/db/database_url.sqlite3 bin/rails db:create
```

As expected, the `development` environment now uses the DATABASE_URL. What is unexpected is that the `test` environment does not.

It's unclear what the expected behavior should be in this case, but the cause of it is this: https://github.com/rails/rails/blob/9f2c74eda07ea5a9e4e624d5575a717714088dbf/activerecord/lib/active_record/tasks/database_tasks.rb#L494

Because of `each_local_configuration`, there seems to be no way invoke these database rake on only the `development` environment to ensure `DATABASE_URL` is respected.

The smallest scope of change I can think to make would be to conditionalize this behavior so it does not get applied when `DATABASE_URL` is present.

cc: @jhawthorn @eileencodes 

P.S. Forgive my omission of tests and a CHANGELOG entry. Wanted to put this up here to see if it got any interest before investing more time.

### CODE REVIEW

File: activerecord/lib/active_record/tasks/database_tasks.rb [hunk 1]
```diff
@@ -491,7 +491,7 @@ def class_for_adapter(adapter)
 
         def each_current_configuration(environment, spec_name = nil)
           environments = [environment]
-          environments << "test" if environment == "development"
+          environments << "test" if environment == "development" && ENV["DATABASE_URL"]
```
Comment (eileencodes) [inline activerecord/lib/active_record/tasks/database_tasks.rb]: This is going to break apps that don't use database url.

It's saying "include test if the environment if development and database url is set". You want "include test if the environment is development and database url is not set".

It's not accidental that we include test in development mode when running this. It has been discussed extensively here https://github.com/rails/rails/issues/32926.

**Review by eileencodes — CHANGES_REQUESTED** [review]

File: activerecord/lib/active_record/tasks/database_tasks.rb (hunk 1 above)
Comment (bbuchalter) [reply activerecord/lib/active_record/tasks/database_tasks.rb]: Ah, yes, of course, that's what I meant to implement. I'll fix.

**Comment by bbuchalter** [comment]
Anything I can do to resolve other questions about this? What do you think about how to add tests?

**Comment by bbuchalter** [comment]
Just a friendly poke here to see what I can do to help move this along.

**Review by bekicot — APPROVED** [review]

**Comment by jhawthorn** [comment]
I pushed a test onto this branch (which would fail on master) to show the difference.

Before this, if you were to specify a `DATABASE_URL`, you'd get the database created at `DATABASE_URL` as the development DB and then another created from the database.yml as the test environment's DB. I think this is probably not what the user wants in this case, if they're specifying a `DATABASE_URL` it's because they don't want the values from `database.yml`.

The behvaiour difference that with no `DATABASE_URL` we create a test DB and with `DATABASE_URL` we don't is a little weird/unfortunate. But since it's only one value and we can't know what the URL would be for test, I agree not creating it is the best way to handle it.

I think this change makes sense to do.

**Review by eileencodes — APPROVED** [review]
Once there is a changelog this seems fine to me 👍

**Comment by jhawthorn** [comment]
Thanks Brian! ❤️
