### PR TITLE
Fix `Enumerable#sum` for `Enumerator#lazy`

### LINKED ISSUE #48712: Enumerator::Lazy#sum and Enumerator#sum behave differently after Rails 7 update if block relies on side effect
### Steps to reproduce
I'm doing an update from rails `6.1.7.2` to `7.0.6` and some of our tests failed. This seems related to the deprecation of `Enumerable#sum` in Rails 7.

Basically the problem is that `Enumerator::Lazy#sum` and `Enumerator#sum` - when used without initial value - behave differently if the block relies on a side effect.
```ruby
input1 = "\xEF\xBB\xBFinput1"
input2 = "\xEF\xBB\xBFinput2"

# returns a lazy enumerator
remove_first_bom = proc do |enum|
  # external state
  first = true
  
  enum.lazy.map do |str|
    if first
      # side effect
      first = false
      str[1..]
    else
      str
    end
  end
end

# when using deprecated Enumerator::Lazy#sum the BOM bytes [239, 187, 191] are not removed.
remove_first_bom.call([input1, input2]).sum.bytes
=> [239, 187, 191, 105, 110, 112, 117, 116, 49, 239, 187, 191, 105, 110, 112, 117, 116, 50]

# when using deprecated Enumerator#sum the BOM bytes are removed as expected when
# lazy enumerator is forced to evaluate before using sum
remove_first_bom.call([input1, input2]).force.sum.bytes
=> [105, 110, 112, 117, 116, 49, 239, 187, 191, 105, 110, 112, 117, 116, 50]

# when the initial value for sum is provided this seems to work, so in that sense not using the deprecated behaviour fixes the issue
remove_first_bom.call([input1, input2]).sum("").bytes
 => [105, 110, 112, 117, 116, 49, 239, 187, 191, 105, 110, 112, 117, 116, 50] 
```
I suspect that there might be some peeking behaviour which has the side effect of setting `first = false`. I'm pretty sure I saw this when adding `puts` into the conditional.

I confirmed that this doesn't happen in `6.1.7.2`.

### Expected behavior
`Enumerator::Lazy#sum` and `Enumerator#sum` should return the same result.

### Actual behavior
`Enumerator::Lazy#sum` and `Enumerator#sum` return different values if the block relies on a side effect

### System configuration
**Rails version**: `7.0.6`

**Ruby version**:  `3.1.2`

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #48712.

The problem was that `.first` method call, used in the condition, evaluated lazy enumerator, and thus lead to the problematic behavior.

### CODE REVIEW

**Comment by guilleiguaran** [comment]
Don't we need a changelog entry for this fix?

**Comment by matthewd** [comment]
Lazy is a notable example, but I guess we're just generally wrong to assume it's safe to call `first` and then restart iteration.

Perhaps we should allow this faster check only for a specific list of known common enumerables, and otherwise always fall back to an implementation that guarantees a single invocation of `each`.

**Comment by fatkodima** [comment]
@guilleiguaran Added a changelog entry.

@matthewd If we will check for known safe enumerables, we need to also include `Enumerable` in this list to not to start generating deprecations for custom enumerable classes (currently these are accepted without deprecations), see https://github.com/rails/rails/blob/4c7f7923711b958a5608887c2c2eb1170d68addf/activesupport/test/core_ext/enumerable_test.rb#L72 But `Enumerator::Lazy` is also an `Enumerable`, so that branch will be called for it too and this won't work. We will need a more complex solution 🤔. How about to go ahead with the current implementation, since lazy enumerator is the only one reported so far, and maybe change the implementation to more complex if more cases will be reported?

**Comment by matthewd** [comment]
My point is that custom Enumerable-implementing classes are not safe to call `first` on. It's true that this is the first report we've seen, but I'm rather uncomfortable with the idea of noticing a general problem, yet only introducing a specific fix for the one stdlib class we know is affected.

I think I'm specifically suggesting that we need to do something like:

```ruby
enum = enum_for(:each)
first_value =
  begin
    first_value = enum.next
  rescue StopIteration
    return 0
  end
unless first_value.is_a?(Numeric) || first_value.respond_to?(:coerce)
  # warn
end
Enumerator.produce(first_value) { enum.next }.inject(:+)
```

or maybe it's easier to just reimplement the inject:

```ruby
initial = true
a = 0
each do |e|
  if initial
    initial = false
    unless e.is_a?(Numeric) || e.respond_to?(:coerce)
      # warn
    end
    a = e
  else
    a += e
  end
end
a

**Comment by fatkodima** [comment]
@matthewd Thanks, applied the first suggestion and added you as a coauthor 👍 .

File: activesupport/lib/active_support/core_ext/enumerable.rb [hunk 1]
```diff
@@ -76,19 +76,21 @@ def sum(identity = nil, &block)
...
+        rescue StopIteration
+          return 0
+        end
+      unless first_value.is_a?(Numeric) || first_value.respond_to?(:coerce)
+        ActiveSupport::Deprecation.warn(<<-MSG.squish)
+          Rails 7.0 has deprecated Enumerable.sum in favor of Ruby's native implementation available since 2.4.
+          Sum of non-numeric elements requires an initial argument.
+        MSG
+      end
+      Enumerator.produce(first_value) { enum.next }.inject(:+) || 0
```
Comment (jonathanhefner) [inline activesupport/lib/active_support/core_ext/enumerable.rb:93]: This is just my opinion, but I feel like @matthewd's second suggestion is more straightforward (and more efficient).  If we want a less `for`-loop-like implementation, we could also use `reduce` (aka `inject`) instead of `each`:

```ruby
reduce(nil) do |sum, value|
  if sum.nil?
    unless value.is_a?(Numeric) || value.respond_to?(:coerce)
      # warn
    end
    value
  else
    sum + value
  end
end || 0
```

Comment (matthewd) [reply activesupport/lib/active_support/core_ext/enumerable.rb]: That assumes the enumerable doesn't start with nil values / `sum + value` never returns nil.

Comment (matthewd) [reply activesupport/lib/active_support/core_ext/enumerable.rb]: (I agree the Enumerator version is probably overcomplicated / needlessly inefficient)

Comment (fatkodima) [reply activesupport/lib/active_support/core_ext/enumerable.rb]: > That assumes the enumerable doesn't start with nil values / `sum + value` never returns nil.

When we have `nil`s at the beginning (`[nil, nil, 2, 3, 4]`), the branch with `if sum.nil?` will be executed for all of them. When we have `nil` in the middle somewhere (`[1, 2, nil, 3]`), we will get an error about not able to coerce, like in native `sum`. Am I missing something?

Comment (matthewd) [reply activesupport/lib/active_support/core_ext/enumerable.rb]: > the branch with if sum.nil? will be executed for all of them

That's a behaviour change.

(More obscurely, a redefined `NilClass#+` would also deviate.)

Comment (jonathanhefner) [reply activesupport/lib/active_support/core_ext/enumerable.rb]: > That assumes the enumerable doesn't start with nil values / `sum + value` never returns nil.

It does, but we want `[nil].sum == 0`:

https://github.com/rails/rails/blob/f61bcfb315c31f042a343249995c7e6e21e64334/activesupport/test/core_ext/enumerable_test.rb#L140-L142

I don't think `+` would purposefully return `nil` because `nil + anything` would raise (unless you override `NilClass#+`, which seems... unwise).  But I suppose we could be masking an error here.  Alternatively:

```ruby
first = true

reduce(nil) do |sum, value|
  if first
    unless value.is_a?(Numeric) || value.respond_to?(:coerce)
      # warn
    end

    first = false
    value
  else
    sum + value
  end
end || 0
```

Comment (matthewd) [reply activesupport/lib/active_support/core_ext/enumerable.rb]: > we want [nil].sum == 0

Ah, fair.

> unless you override NilClass#+, which seems... unwise

Agree, but even while "unwise" might be a reasonable line in main, I think we should aim for unreasonable accomodation in stable branches.

(And I _can_ imagine a risky but loosely-plausible NilClass#+ that exclusively accepts some specific CustomClass as its argument)

Comment (fatkodima) [reply activesupport/lib/active_support/core_ext/enumerable.rb]: Updated with the `if first` variant.

**Comment by jonathanhefner** [comment]
Thank you, @fatkodima! :one:
