### PR TITLE
Fix count queries on `includes+references` for models with composite primary keys

### LINKED ISSUE #51634: ActiveRecord/Postgresql composite primary keys breaks count query on includes+references
### Steps to reproduce
ActiveRecord 7.1.3.2, Ruby 3.3.0, PostgreSQL adapter

Assuming you have tables

```
class ItemType < ApplicationRecord
  self.primary_key = 'item_type_cd'
end

class Item < ApplicationRecord
  self.primary_key = %i[item_type_cd some_other_column]
  belongs_to :item_type, foreign_key: 'item_type_cd'
end
```

Running a query

`
Item.where(item_type_col1: 'x').includes(:item_type).references(:item_type).count
`

Crashes because it generates 

`
SELECT COUNT(DISTINCT ["item_type_cd", "some_other_column"]) FROM "items" LEFT OUTER JOIN "item_types" ON "item_types"."item_type_cd" = "item"."item_type_cd" WHERE "item_types"."item_type_col1" = $1
`

### Expected behavior

It should generate count(*) 

### Actual behavior

Invalid SQL generated

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #51634.

SQLite and older MySQL do not support using `COUNT DISTINCT` with multiple columns, so we need to use a subquery for them.

### CODE REVIEW

File: activerecord/lib/active_record/relation/calculations.rb [hunk 1]
```diff
@@ -632,12 +632,30 @@ def type_cast_calculated_value(value, operation, type)
...
+            column = arel_column(field.to_s) do |attr_name|
+              Arel.sql(attr_name)
+            end
+
+            if column.is_a?(Arel::Nodes::SqlLiteral)
+              column
+            else
+              "#{adapter_class.quote_table_name(column.relation.name)}.#{adapter_class.quote_column_name(column.name)}"
+            end
+          end.join(", ")
```
Comment (fatkodima) [inline activerecord/lib/active_record/relation/calculations.rb:646]: As with the models used in the added test case (which have duplicate column names), we need to be explicit to reference the table name too to not get the ambiguous column error.
