### PR TITLE
Modify respond_to behaviour always setting the response's content type based on the request format

### LINKED ISSUE #37345: Inconsistent `render ...` behavior when used with `respond_to`
### Steps to reproduce

Use `render :plain` inside of `respond_to { |f| f.any { ... } }` block:

``` ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "6.0.0"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/any-json"   => "test#any_json"
    get "/any-plain"  => "test#any_plain"
    get "/solo-json"  => "test#solo_json"
    get "/solo-plain" => "test#solo_plain"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def any_json
    respond_to do |format|
      format.xml { render :xml => %(<?xml version="1.0" encoding="UTF-8"?><message>ok</message>) }
      format.any { render :json => { "data" => "ok" } }
    end
  end

  def any_plain
    respond_to do |format|
      format.xml { render :xml => %(<?xml version="1.0" encoding="UTF-8"?><message>ok</message>) }
      format.any { render :plain => "ok" }
    end
  end

  def solo_json
    render :json => { "data" => "ok" }
  end

  def solo_plain
    render :plain => "ok"
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_any_json
    get "/any-json.csv"
    assert %r{\Aapplication/json(;|\z)}.match? last_response.content_type
  end

  def test_any_plain
    get "/any-plain.csv"
    assert %r{\Atext/plain(;|\z)}.match? last_response.content_type
  end

  def test_solo_json
    get "/solo-json.csv"
    assert %r{\Aapplication/json(;|\z)}.match? last_response.content_type
  end

  def test_solo_plain
    get "/solo-plain.csv"
    assert %r{\Atext/plain(;|\z)}.match? last_response.content_type
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behaviour

``` ruby
respond_to do |f|
  f.any { render :plain => "ok" }
end
```

Should render response with `Content-Type: text/plain`. 

``` ruby
respond_to do |f|
  f.any { render :json => { "message" => "ok" } }
end
```

Should render response with `Content-Type: application/json`. 

### Actual behaviour

Rendered response will have `Content-Type` whichever `params[:format]` was (fallback to `text/html`).

### System configuration

**Rails version**:

5.0, 5.1, 5.2, 6.0

**Ruby version**:

2.5+ (in fact it's not important)

### PR DESCRIPTION
**Pull request by Edouard-chin**
Modify respond_to behaviour always setting the request's content type:

- `respond_to any` doesn't allow to specify a content type and
  the content type in the response will be based on the request
  format.

  ```ruby
    def my_action
      respond_to do |format|
        format.html { render(html: 'hello') }
        format.any { render(json: { foo: 'bar'}) }
      end
    end

    get('my_action.csv')
    # Before this patch, content type was `text/csv'
    # Ather this patch, content type is correctly set to whateve we did in the `format.any` block
  ```

  If the client specify the type of data he wants but the server
  doesn't know how to handle it and return plain text (or whatever)
  I don't think it make sense to falsey claim that we are returning
  a `text/csv` a response where in fact we are returning something else.

  Fix #37345

### CODE REVIEW

File: actionpack/test/controller/mime/respond_to_test.rb [hunk 1]
```diff
@@ -157,6 +157,13 @@ def handle_any
     end
   end
 
+  def handle_any_doesnt_set_request_content_type
+    respond_to do |type|
+      type.html { render body: "HTML" }
+      type.any { render json: { foo: "bar" } }
```
Comment (rafaelfranca) [inline actionpack/test/controller/mime/respond_to_test.rb]: what happens if you try to render a template?

File: actionpack/lib/action_controller/metal/mime_responds.rb [hunk 2]
```diff
@@ -209,7 +209,7 @@ def respond_to(*mimes)
           raise ActionController::RespondToMismatchError
         end
         _process_format(format)
-        _set_rendered_content_type format
+        _set_rendered_content_type(format) unless collector.any_response?
```
Comment (etiennebarrie) [inline actionpack/lib/action_controller/metal/mime_responds.rb]: `_set_rendered_content_type` has a guard against setting the `Content-Type`/`media_type`:
https://github.com/rails/rails/blob/4f9f9ca23a39b2b529782f957be645741a20cf20/actionpack/lib/action_controller/metal/rendering.rb#L74-L76

and `AbstractController::Rendering#render` uses that method passing the `rendered_format`:
https://github.com/rails/rails/blob/4f9f9ca23a39b2b529782f957be645741a20cf20/actionpack/lib/abstract_controller/rendering.rb#L29

which is `text/plain` by default in `AbstractController::Rendering`:
https://github.com/rails/rails/blob/4f9f9ca23a39b2b529782f957be645741a20cf20/actionpack/lib/abstract_controller/rendering.rb#L55-L56

but is overridden by `ActionView::Rendering`:
https://github.com/rails/rails/blob/4f9f9ca23a39b2b529782f957be645741a20cf20/actionview/lib/action_view/rendering.rb#L29

In the case of `render json:` (and similarly `:js` and `:xml`), the response content type is set during the call to `render`, again with a guard against overriding any existing value, because you could have set it manually before `render` or with `render(content_type: :csv)`.
https://github.com/rails/rails/blob/4f9f9ca23a39b2b529782f957be645741a20cf20/actionpack/lib/action_controller/metal/renderers.rb#L166

---

All of this to say that I also tried moving the call to `_set_rendered_content_type` after the call to `response.call` without the guard that you introduced, and it also resulted in the right `Content-Type` being set (the one from rendering, not the one from the request `Accept` header).

I think that would make more sense as the response content type should come more from what happens during rendering than what has been asked. e.g. what should we return when we do this? 

```ruby
      format.xml { render json: { foo: "bar" } }
```

IMO JSON, but that would take a pass of deprecation warnings. The problem doing it this way is that now we have a compatibility issue because it impacts more than the `any` case (which I agree was fine to change). Also doing this makes a lot of test fail and I haven't yet figured out why so we probably need to store the content type that was asked and use it unless another one was set during rendering.

File: actionpack/test/controller/mime/respond_to_test.rb [hunk 3]
```diff
@@ -549,6 +556,12 @@ def test_handle_any
     assert_equal "Either JS or XML", @response.body
   end
 
+  def test_handle_any_doesnt_set_request_content_type
```
Comment (etiennebarrie) [inline actionpack/test/controller/mime/respond_to_test.rb]: It's the response content type that's being set from the request Accept header. And the response is set, so it's a bit of a weird phrasing.

**Review by etiennebarrie — COMMENTED** [review]
Sorry for being pedantic, but it's not the request format exactly but its `Accept` header, you can have a POST request with a JSON `Content-Type` that wants a CSV response.

File: actionpack/lib/action_controller/metal/mime_responds.rb (hunk 2 above)
Comment (Edouard-chin) [reply actionpack/lib/action_controller/metal/mime_responds.rb]: Thanks for digging in this rabbit hole with me :) 

> All of this to say that I also tried moving the call to _set_rendered_content_type after the call to response.call

Originally I went that path and thought we should modify the `respond_to` mehod entirely, because as you mentioned in your example `format.xml { render json: { foo: "bar" } }` returning a `text/xml` response type seemed wrong.

However after second reflexion I think returning `text/xml` makes sense. Let me clarify why.
If a controller action specify how to handle a specific format `xml` in that case, the server knows that the client expects (and in some certain cases, only accepts) a XML response, returning a JSON response breaks the contract and is a developer mistake. 

On the other hand, it's impossible for an application to handle all formats inside `format.any` and thus the framework shouldn't make assumption that the server will for sure return a response based on what the client asked.

File: actionpack/test/controller/mime/respond_to_test.rb (hunk 1 above)
Comment (Edouard-chin) [reply actionpack/test/controller/mime/respond_to_test.rb]: If we render a template, there is 2 possibilities but the response content-type will be always based on the request format.

1) In case a template handles a particular format
```csv.erb
# filename: foo.csv.erb

foo,bar,baz
1,2,3
```

```ruby
type.any { render 'foo' } 
# Response's content type will be `text/csv`
```

2) In case a template doesn't handle a particular format
```
# filename: foo.erb

Hello world
```

```ruby
type.any { render 'foo' } 
# Response's content type will be `text/csv`
```

**Review by rafaelfranca — CHANGES_REQUESTED** [review]
Can you add a changelog entry and an entry in the upgrade guide? I can see this behavior breaking expectations when we release 6.1

**Comment by Edouard-chin** [comment]
Done

File: actionpack/CHANGELOG.md [hunk 4]
```diff
@@ -1,3 +1,23 @@
...
+      def my_action
+        respond_to do |format|
+          format.any { render(json: { foo: 'bar' }) }
+        end
+      end
+
+      get('my_action.csv')
+    ```
+    Previous behaviour was returning a `text/csv` response's Content-Type which
+    is innacurate since we are returning a JSON response.
```
Comment (etiennebarrie) [inline actionpack/CHANGELOG.md]:
```suggestion
    is inaccurate since we are returning a JSON response.
```

File: actionpack/CHANGELOG.md [hunk 5]
```diff
@@ -1,3 +1,23 @@
...
+    ```ruby
+      def my_action
+        respond_to do |format|
+          format.any { render(json: { foo: 'bar' }) }
+        end
+      end
+
+      get('my_action.csv')
+    ```
+    Previous behaviour was returning a `text/csv` response's Content-Type which
```
Comment (etiennebarrie) [inline actionpack/CHANGELOG.md]:
```suggestion
    The previous behaviour was to respond with a `text/csv` Content-Type which
```

File: actionpack/CHANGELOG.md [hunk 6]
```diff
@@ -1,3 +1,23 @@
...
+    is innacurate since we are returning a JSON response.
+    Current behaviour correctly returns a `application/json` response's Content-Type
```
Comment (etiennebarrie) [inline actionpack/CHANGELOG.md]:
```suggestion
    Now it correctly returns a `application/json` Content-Type.
```

**Comment by Edouard-chin** [comment]
Thanks @etiennebarrie !

File: guides/source/upgrading_ruby_on_rails.md [hunk 7]
```diff
@@ -72,6 +72,37 @@ The new Rails version might have different configuration defaults than the previ
...
+  def my_action
+    respond_to do |format|
+      format.any { render(json: { foo: 'bar' }) }
+    end
+  end
+
+  get('my_action.csv')
+```
+
+Previous behaviour was returning a `text/csv` response's Content-Type which is innacurate since w are returning a JSON response.
```
Comment (rafaelfranca) [inline guides/source/upgrading_ruby_on_rails.md]:
```suggestion
Previous behaviour was returning a `text/csv` response's Content-Type which is inaccurate since a JSON response is being rendered.
```

File: actionpack/CHANGELOG.md [hunk 8]
```diff
@@ -1,3 +1,23 @@
...
+      def my_action
+        respond_to do |format|
+          format.any { render(json: { foo: 'bar' }) }
+        end
+      end
+
+      get('my_action.csv')
+    ```
+    The previous behaviour was to respond with a `text/csv` Content-Type which
+    is inaccurate since we are returning a JSON response.
```
Comment (rafaelfranca) [inline actionpack/CHANGELOG.md]:
```suggestion
    is inaccurate since a JSON response is being rendered.
```
