### PR TITLE
Fix `config.log_level` being ignored when using a Broadcast Logger

### LINKED ISSUE #50324: `ActiveSupport::BroadcastLogger` does not respect `config.log_level` in Rails 7.1
I am working on upgrading an app from Rails 7 to 7.1 and onto edge. I've come across an issue that I think is a bug, but could also be configuration not being used as intended.

Rails 7 config:

```ruby
# config/application.rb
config.logger = Logist::Logger.new($stdout)
other_logger = AnotherLogger.new

config.logger.extend(ActiveSupport::Logger.broadcast(other_logger))

config.log_level = :info if Rails.env.production?
```

With this config, `Rails.logger.debug` does nothing in production. 🟢 

The Rails 7 config relied on the private API described in https://github.com/rails/rails/pull/48615, so we have to refactor it for 7.1. 7.1/Edge Rails config:

```ruby
# config/application.rb
config.logger = Logist::Logger.new($stdout)
other_logger = AnotherLogger.new

config.logger = ActiveSupport::BroadcastLogger.new(config.logger, other_logger)

config.log_level = :info if Rails.env.production?
```

With this config, `Rails.logger.debug` logs in production. 🔴 

I think the issue comes from https://github.com/rails/rails/pull/49721, since the `log_level` is no longer being assigned to the broadcast loggers. I would expect `config.log_level` to work for whatever you assign `config.logger` too, and if that's changing it seems like a breaking change to me.

Is the expectation that if you use `BroadcastLogger`, you set the `level` manually on loggers?

cc @Edouard-chin @andrewn617  @rafaelfranca 

### System configuration
**Rails version**: `main`

**Ruby version**: 3.2

### PR DESCRIPTION
**Pull request by Edouard-chin**
ℹ️ To backport to 7-1 stable please 🙇 
______________________________________

### Motivation / Background

If an application has configured a Broadcast Logger, setting the `config.log_level` to any value has no effect:

```ruby
# config/application.rb

config.logger = ActiveSupport::BroadcastLogger.new(Logger.new(STDOUT))
config.log_level = :warn

puts Rails.logger.broadcasts.map(&:level) #=> [Logger::DEBUG]
```

This is a side effect of #49621 which tried to fix the `log_level` default value overriding the whole broadcasts.

##### Context

The `log_level` default's value shouldn't apply to a Broadcast Logger, as otherwise it overrides whatever the application previously configured. While this behaviour is the same with a vanilla logger, at least we can workaround it:

```ruby
###############################
# When using a vanilla logger #
###############################

config.logger = Logger.new(STDOUT, level: LOGGER::WARN)
# Once the app boots, the level is overriden to DEBUG. We need to add the following line.
config.log_level = :warn

#################################
# When using a broadcast logger #
#################################

stdout = Logger.new(STDOUT, level: Logger::INFO)
stderr = Logger.new(STDERR, level: Logger::ERROR)
config.logger = ActiveSupport::BroadcastLogger(stdout, stderr)

# Once the app boots the whole broadcast level is overriden to DEBUG.
# There is no way to workaround this as you can't fine grain the level of each
# loggers with `config.log_level=`.
```

##### Solution

This PR ignores the default `log_level` value when using a Broadcast Logger, but ensure it gets used if an application manually sets it.

Fix #50324
cc/ @ghiculescu 

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by byroot** [comment]
Backported to 7-1-stable.

**Comment by Edouard-chin** [comment]
Thanks Jean!

File: railties/lib/rails/application/bootstrap.rb [hunk 1]
```diff
@@ -55,7 +55,11 @@ module Bootstrap
           logger
         end
 
-        unless Rails.logger.is_a?(ActiveSupport::BroadcastLogger)
+        if Rails.logger.is_a?(ActiveSupport::BroadcastLogger)
+          if config.broadcast_log_level
```
Comment (rafaelfranca) [inline railties/lib/rails/application/bootstrap.rb:59]: Is this a new config?

Comment (byroot) [reply railties/lib/rails/application/bootstrap.rb:59]: It's an alias: https://github.com/rails/rails/pull/50337/files#diff-9f26e965e7e2a6842bd6ea755924a621038bc9dd8d63cfa6b34092aa32ede02cR376-R383

Comment (Edouard-chin) [reply railties/lib/rails/application/bootstrap.rb:59]: Yep it's an alias ish, also added a `:nodoc:` as there is no reason to use is for the user.
