### PR TITLE
Use PG::Connection#close_prepared when available

### LINKED ISSUE #55653: Postgres: Use Protocol Prepared Statement Deallocation Instead of Statement
Currently it appears that rail deallocates prepared statements via statement instead[0]. This is not efficient and does not work well with pgbouncer. See the Deallocation functionality in psycopg [2] as an example of protocol prepared statement Deallocation.

If I understand correctly it appears that rails uses the ruby-pg library [3] to execute protocol level prepare [4, 5]. Similarly I believe it should be a matter of invoking the `close_prepared` function in ruby-pg.

I have not tested the below code but I believe the solution could be something like this.

```diff
diff --git a/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb b/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb
index 18de389..9001f5a 100644
--- a/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb
+++ b/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb
@@ -310,7 +310,9 @@ def dealloc(key)
             # don't need the complication of with_raw_connection because
             # a reconnect would invalidate the entire statement pool.)
             if conn = @connection.instance_variable_get(:@raw_connection)
-              conn.query "DEALLOCATE #{key}" if conn.status == PG::CONNECTION_OK
+              if conn.status == PG::CONNECTION_OK
+                conn.close_prepared "#{key}"
+              end
             end
           rescue PG::Error
           end

```

[0] https://github.com/rails/rails/blob/681c86674fa16996e4563b93aab4e9c494f6a651/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L313
[1] https://www.postgresql.org/docs/current/protocol-message-formats.html#PROTOCOL-MESSAGE-FORMATS-CLOSE
[2] https://github.com/psycopg/psycopg/blob/94583702ada92187c8b1bb4da8de0d30a879c8bd/psycopg/psycopg/_connection_base.py#L489
[3] https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/PostgreSQLAdapter.html
[4] https://deveiate.org/code/pg/PG/Connection.html#method-i-prepare
[5] https://github.com/rails/rails/blob/681c86674fa16996e4563b93aab4e9c494f6a651/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L927
[6] https://deveiate.org/code/pg/PG/Connection.html#method-i-close_prepared

### PR DESCRIPTION
**Pull request by skipkayhil**
Fix #55653

pgbouncer does not support "DEALLOCATE #{key}", but it does support "protocol level Close" (#close_prepared) starting in version 1.21.

This commit changes the PostgreSQL adapter to use #close_prepared (when available) to better support pgbouncer.

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb [hunk 1]
```diff
@@ -304,15 +308,32 @@ def next_key
...
+              # This is ugly, but safe: the statement pool is only
+              # accessed while holding the connection's lock. (And we
+              # don't need the complication of with_raw_connection because
+              # a reconnect would invalidate the entire statement pool.)
+              if conn = @connection.instance_variable_get(:@raw_connection)
+                if @connection.supports_close_prepared?
+                  conn.close_prepared key if conn.status == PG::CONNECTION_OK
+                else
+                  conn.query "DEALLOCATE #{key}" if conn.status == PG::CONNECTION_OK
+                end
```
Comment (skipkayhil) [inline activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb]: Also wondering if `conn.status == PG::CONNECTION_OK` is still needed after https://github.com/rails/rails/pull/44527

File: activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb [hunk 2]
```diff
@@ -304,15 +308,32 @@ def next_key
...
 
         private
-          def dealloc(key)
-            # This is ugly, but safe: the statement pool is only
-            # accessed while holding the connection's lock. (And we
-            # don't need the complication of with_raw_connection because
-            # a reconnect would invalidate the entire statement pool.)
-            if conn = @connection.instance_variable_get(:@raw_connection)
-              conn.query "DEALLOCATE #{key}" if conn.status == PG::CONNECTION_OK
+          if PG::Connection.method_defined?(:close_prepared) # pg 1.6.0 & libpq 17
```
Comment (matthewd) [inline activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb]: Put this on `supports_close_prepared?` instead?

File: activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb (hunk 1 above)
Comment (matthewd) [reply activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb]: Without checking, I'd guess it's probably still wanted, to be safe around the dealloc-during-raise process? But can probably move it up as a `return unless` rather than duplicate the conditional.

Comment (byroot) [inline activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb]:
```suggestion
                if conn.status == PG::CONNECTION_OK
                  if @connection.supports_close_prepared?
                    conn.close_prepared key
                  else
                    conn.query "DEALLOCATE #{key}"
                  end
                end
```

**Review by matthewd — APPROVED** [review]

**Review by byroot — APPROVED** [review]
