### PR TITLE
Fix find_by with association subquery issue

### LINKED ISSUE #20817: ActiveRecord 4.2 breaks find_by association subquery
Active Record 4.2.x (4.2.0 - 4.2.3) breaks association subqueries that worked in 4.1.x (4.1.6 - 4.1.11).

It looks like the subquery in a `find_by(association_id: subquery)` statement is interpreted as a bind parameter. Interestingly enough using the `find_by(association: subquery)` format seems to work.

[bugtest](https://gist.github.com/griffithchaffee/852a1a218951d160d033)

### Overview:

```ruby
# always works
# SELECT  "admins".* FROM "admins"  WHERE "admins"."group_id" IN (SELECT "groups"."id" FROM "groups"  WHERE "groups"."id" = 1) LIMIT 1
good_query = Admin.find_by(group: Group.where(id: group))

# breaks in AR 4.2
# SELECT  "admins".* FROM "admins" WHERE "admins"."group_id" = ? LIMIT 1  [["group_id", nil]]
bad_query  = Admin.find_by(group_id: Group.where(id: group))
```

### PR DESCRIPTION
**Pull request by akihiro17**
In this commit, `find_by` doesn't cache arguments if they are an `ActiveRecord::Relation`
so that `find_by` with association subquery works correctly.

Fixes #20817

### CODE REVIEW

**Comment by arthurnn** [comment]
Can you add a changelog for the fix?

thanks

**Comment by akihiro17** [comment]
@arthurnn 

I added a changelog.

File: activerecord/test/cases/finder_test.rb [hunk 1]
```diff
@@ -265,6 +265,11 @@ def test_find_by_sql_with_sti_on_joined_table
     assert_equal [Account], accounts.collect(&:class).uniq
   end
 
+  def test_find_by_association_subquery
+    author = authors(:david)
+    assert_equal author.post, Post.find_by(author_id: Author.where(id: author))
```
Comment (arthurnn) [inline activerecord/test/cases/finder_test.rb]: can you also add a test for `assert_equal author.post, Post.find_by(author: Author.where(id: author))` ?
Btw, is that case working right now, or this patch fix that too?

Comment (akihiro17) [inline activerecord/test/cases/finder_test.rb]: I added a test.

> Btw, is that case working right now, or this patch fix that too?

That case works without this patch because of the following code.

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/core.rb#L184
```ruby
# core.rb line 184
return super unless hash.keys.all? { |k| columns_hash.has_key?(k.to_s) }
```

**Comment by arthurnn** [comment]
thanks
