### PR TITLE
Make the master.key readable only by the owner

### LINKED ISSUE #32604: Make the master.key file private upon generation?
### Steps to reproduce

    rails new app

### Expected behavior

The `config/master.key` file should not be world-/group-readable (at least on POSIX-compliant systems).

### Actual behavior

The `config/master.key` is readable by all users in the system.

    ls -l config/master.key
    -rw-r--r--   1 user  group    32 Jan 1 00:00 master.key

### System configuration
**Rails version**: 5.2.0, master

**Ruby version**: 2.5.1

### Suggestion

Perhaps after:

https://github.com/rails/rails/blob/c8dc4f2e41afa07c2b2ec701e2ba4682e5ccdd37/railties/lib/rails/generators/rails/encryption_key_file/encryption_key_file_generator.rb#L11

add:

```ruby
key_path.chmod 0600
```

### PR DESCRIPTION
**Pull request by jlduran**
This change may only apply to POSIX-compliant systems.

Previously:

    $ ls -l config/master.key
    -rw-r--r--   1 owner  group      32 Jan 1 00:00 master.key

Now:

    $ ls -l config/master.key
    -rw-------   1 owner  group      32 Jan 1 00:00 master.key

Fixes #32604.

### CODE REVIEW

**Comment by pixeltrix** [comment]
@jlduran thanks for the PR - does the `chmod` command silently fail on Windows or does it raise an error? if the latter we need a check before running the command. Also a test added to `app_generator_test.rb` would be good too. 👍

**Comment by jlduran** [comment]
@pixeltrix 
> does the chmod command silently fail on Windows or does it raise an error?

According to [this SO answer](https://stackoverflow.com/a/10957498), `chmod` is a noop on Windows. I do not have a machine to test it at the moment.

> Also a test added to `app_generator_test.rb` would be good too.

What is the recommended way to skip testing on Windows?

```ruby
unless Gem.win_platform?
  # test here
end
```

**Comment by pixeltrix** [comment]
@jlduran yes, looks like `Gem.win_platform?` is the check we've used elsewhere.

File: railties/test/generators/app_generator_test.rb [hunk 1]
```diff
@@ -941,6 +941,14 @@ def test_system_tests_directory_generated
     assert_directory("test/system")
   end
 
+  unless Gem.win_platform?
+    def test_master_key_is_only_readable_by_the_owner
+      run_generator
+
+      assert_nil File.world_readable?("config/master.key")
```
Comment (pixeltrix) [inline railties/test/generators/app_generator_test.rb]: Since we're setting the group read bit as well we should make this more explicit like:

``` ruby
stat = File.stat("config/master.key")
assert_equal "100600", sprintf("%o, stat.mode)
```

**Comment by pixeltrix** [comment]
Once you've made the test change can you squash your commits and then we're good to go - thanks 👍
