### PR TITLE
Use optimized subclass of StringInquirer for Rails.env

### LINKED ISSUE #37803: StringInquirer for Rails.env is unnecessarily heavy
### Steps to reproduce
Call `Rails.env.development?` from any code.

### Expected behavior
It should not have to dispatch through `method_missing`.

### Actual behavior
It dispatches through `method_missing`

### System configuration
**Rails version**: 5+

**Ruby version**: all

In order to allow using `Rails.env.development?` instead of `Rails.env == 'development'`, the env string is currently forced into a StringInquirer instance:

https://github.com/rails/rails/blob/1ccc407e9dc95bda4d404c192bbb9ce2b8bb7424/railties/lib/rails.rb#L67-L81

StringInquirer in turn uses `method_missing` to turn the `development?` call into `self == "development"` by cropping off the `?`.

https://github.com/rails/rails/blob/1ccc407e9dc95bda4d404c192bbb9ce2b8bb7424/activesupport/lib/active_support/string_inquirer.rb

This is unnecessarily heavy:

* Dispatching through method_missing is generally more expensive than calling a simple method.
* A new string object must be constructed for each call.

This is also doing work for each call that is unnecessary; the content of the string does not change over time, so performing the check once would be sufficient.

In the application I was benchmarking, Redmine, this call was made at least once per request, and multiple times in some cases. I have heard anecdotal evidence from others that their apps may use `production?` and `test?` heavily to allow minor behavioral diffferences in those environments.

I believe this env string should instead use a subclass of String that defines proper methods for at least the standard three environments (development, test, and production), and if possible it should define such methods for all configurable environments in the boot configs.

```
class EnvironmentString < StringInquirer
  def initialize(env)
    @development = env == 'development'
    @test = env == 'test'
    @production = env == 'production'
  end

  def development?; @development; end
  def test?; @test; end
  def production?; @production; end
end
```

A more aggressive optimization would define these as singleton methods specific to the incoming env string; this would only be done once at env-setting time and therefore the singleton would not be any more significant in memory than having a specific named class for this purpose.

### PR DESCRIPTION
**Pull request by headius**
### Summary
This adds a StringInquirer subclass EnvironmentInquirer that
predefines the three default environments as query methods, in
order to avoid dispatching through `method_missing` for every call
to those methods. The original StringInquirer was not modified due
to the side effects of having new env-related methods on it. This
new class was not implemented using lazy method definition to
avoid the open-ended possibility of defining a new method for all
query calls. The three default environments should cover a high
percentage of real-world uses, and users with custom environments
could add their own to this class.

Fixes #37803.

I am open to discussion about the following points:

* Whether to lazily define all queries as they are called. Concerns include: runaway method definition, complexity.
* Whether to do these methods on StringInquirer itself, which currently is only used for `Rails.env` in the Rails codebase (but may be used for other purposes in userland code). Concerns include: new predefined env-related methods on what previously only had custom `*_missing` methods.

### Other Information

Using the following benchmark, `EnvironmentInquirer` is over 10x faster than plain `StringInquirer` on CRuby 2.6.4.

```ruby
require 'benchmark/ips'

require 'active_support/core_ext/string/inquiry'

Benchmark.ips do |ips|
  si = ActiveSupport::StringInquirer.new('development')
  env = ActiveSupport::EnvironmentInquirer.new('development')

  ips.report('StringInquirer') do |i|
    while i > 0
      si.development?
      i-=1
    end
  end

  ips.report('EnvironmentInquirer') do |i|
    while i > 0
      env.development?
      i-=1
    end
  end
end
```

Results:

```
Warming up --------------------------------------
      StringInquirer   145.978k i/100ms
 EnvironmentInquirer   367.087k i/100ms
Calculating -------------------------------------
      StringInquirer      2.332M (±10.8%) i/s -     11.532M in   5.019755s
 EnvironmentInquirer     27.333M (± 3.4%) i/s -    136.556M in   5.001554s
```

### CODE REVIEW

File: activesupport/lib/active_support/environment_inquirer.rb [hunk 1]
```diff
@@ -0,0 +1,16 @@
+# frozen_string_literal: true
+
+module ActiveSupport
+  # This is a special case of StringInquirer that defines the three default
+  # environments at construction time based on the environment string.
+  class EnvironmentInquirer < StringInquirer
```
Comment (tenderlove) [inline activesupport/lib/active_support/environment_inquirer.rb]: This should be `:nodoc:`.  I don't think people should know about this class or use it.

**Comment by headius** [comment]
Force-pushed to remove RuboCop whitespace issues.

File: activesupport/lib/active_support/environment_inquirer.rb [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+    DEFAULT_ENVIRONMENTS = ["development", "test", "production"]
+    def initialize(env)
+      super(env)
+
+      DEFAULT_ENVIRONMENTS.each do |default_env|
+        singleton_class.define_method(:"#{env}?", (env == default_env).method(:itself))
+      end
```
Comment (tenderlove) [inline activesupport/lib/active_support/environment_inquirer.rb]: Do we need to do this in initialize on the singleton class?  Why not just make regular methods that do this work?  I understand that this optimizes out the comparison on subsequent calls, but is that really a necessary optimization?

**Review by tenderlove — COMMENTED** [review]
Seems alright.  I'm still skeptical this is a bottleneck for any application, but 🤷‍♀️.

As I said in the original issue, the best practice is not to be using this object at runtime.  I understand that some people do in the real world, but this is really really not meant to be used at runtime.  Really.

File: activesupport/lib/active_support/environment_inquirer.rb (hunk 2 above)
Comment (headius) [reply activesupport/lib/active_support/environment_inquirer.rb]: There's three options as I see it:

* This one, which is the fastest (lowest overhead) per call to the query methods. Main cost is having the singleton.
* Storing ivars for `@development` etc and calculating them at init time. Additional cost is retrieving the var and a subclass of String that adds ivars.
* Defining methods that compare self to `"development"` etc. Additional cost is string comparison on each call.

I'd like to avoid introducing block-based `define_method` methods since they still have more overhead than all other types of methods on CRuby. The second option above is probably acceptable, but is only like 6x faster than the method_missing 🤷‍♂️

File: activesupport/lib/active_support/environment_inquirer.rb (hunk 1 above)
Comment (headius) [reply activesupport/lib/active_support/environment_inquirer.rb]: Can do. I dislike having to add a new class, but the other one is public and documented and I don't feel like it should be tweaked in this way.

File: activesupport/lib/active_support/environment_inquirer.rb (hunk 2 above)
Comment (jeremy) [reply activesupport/lib/active_support/environment_inquirer.rb]: Consider letting the base class take responsibility for hinted optimizations and keeping env inquiry concerns in Railties:

```ruby
class StringInquirer
  def initialize(string, inquiry_hints: [ … ])
    …
    define_hinted_inquiries(inquiry_hints)
  end

  private
    def define_hinted_inquiries(hints)
      hints.each { … }
    end
end
```

Then we could do a private class in Railties:

```ruby
class RailsEnvironmentInquirer < StringInquirer
  def initialize(environment)
    super environment,  %i[ development test production ]
  end
end
private_constant :RailsEnvironmentInquirer

def env
  @_env ||= RailsEnvironmentInquirier.new(…)
```

Could dispense with a subclass altogether, but that's a bit fussier:
```ruby
DEFAULT_ENVIRONMENTS = %i[ development test production ]

def env=(environment)
  @_env = ActiveSupport::StringInquirer.new(environment, DEFAULT_ENVIRONMENTS)
end

# changing this up so we don't repeat StringInquirer.new invocation
def env
  unless defined?(@_env)
    self.env = ENV["RAILS_ENV"].presence || ENV["RACK_ENV"].presence || "development"
  end
  @_env
end
```

Comment (headius) [reply activesupport/lib/active_support/environment_inquirer.rb]: I'd rather not add functionality to the public base class. This is just about fixing one common usage, not making this a customizable query method delegate. That's too much scope creep here.

I would however be interested in making the env class private and perhaps passing the environments in from a location more suited to knowing them.

**Comment by headius** [comment]
Here's a simplified version that just optimizes the three standard environments. Support for configuring this is considered out of scope, as is modifying the base class `StringInquirer` to allow eager or lazy method definitions.

```ruby
# frozen_string_literal: true

require "active_support/string_inquirer"

module ActiveSupport
  class EnvironmentInquirer < StringInquirer #:nodoc:
    DEFAULT_ENVIRONMENTS = ["development", "test", "production"]
    def initialize(env)
      super(env)

      DEFAULT_ENVIRONMENTS.each do |default|
        instance_variable_set :"@#{default}", env == default
      end
    end

    DEFAULT_ENVIRONMENTS.each do |env|
      class_eval "def #{env}?; @#{env}; end"
    end
  end
end
```

This is clearly simpler and doesn't create a singleton, but the performance gain is reduced:

ruby 2.6.4
```
Warming up --------------------------------------
      StringInquirer   149.811k i/100ms
 EnvironmentInquirer   341.512k i/100ms
Calculating -------------------------------------
      StringInquirer      2.452M (± 3.3%) i/s -     12.285M in   5.015769s
 EnvironmentInquirer     21.205M (± 3.0%) i/s -    106.210M in   5.013412s
```
