### PR TITLE
EventedFileUpdateChecker boots once per process

### LINKED ISSUE #24990: Controllers and models don't reload in dev with Puma Workers enabled
### Steps to reproduce

1. Create a new Rails 5.0.0rc1 app
2. Create a dummy route, controller, and controller action
3. Uncomment the `workers ENV.fetch("WEB_CONCURRENCY") { 2 }` line from `puma.rb`
4. `rails server`
5. Visit your action
6. Introduce an exception into the action
7. Re-visit the action

### Expected behavior
The new exception that was introduced should be raised.

### Actual behavior
The page loads fine and the new code added to the action is ignored.

### System configuration
**Rails version**: 5.0.0rc1

**Ruby version**: 2.3.1

### LINKED ISSUE #25259: Booting puma shows "WARNING: Detected 21 Thread(s) started in app boot"
### Steps to reproduce

I'm just spinning up a brand new Rails 5 project to kick the tyres and find out what's new. It comes with puma by default (which is awesome, and saves me installing it later!). Straight out of the box, it works fine. Then I follow the [Heroku guidelines for configuring it](https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server), which essentially boils down to uncommenting the following lines in `config/puma.rb`:

```ruby
workers ENV.fetch("WEB_CONCURRENCY") { 2 }
preload_app!
on_worker_boot do
  ActiveRecord::Base.establish_connection if defined?(ActiveRecord)
end
```

Now when I boot the server, with `bundle exec puma -C config/puma.rb` I get:

```
[15663] Puma starting in cluster mode...
[15663] * Version 3.4.0 (ruby 2.3.1-p112), codename: Owl Bowl Brawl
[15663] * Min threads: 5, max threads: 5
[15663] * Environment: development
[15663] * Process workers: 2
[15663] * Preloading application
[15663] * Listening on tcp://0.0.0.0:3000
[15663] ! WARNING: Detected 21 Thread(s) started in app boot:
[15663] ! #<Thread:0x007fe40cd38040@/Users/mathie/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/listen-3.0.8/lib/listen/internals/thread_pool.rb:6 sleep> - /Users/mathie/.rbenv/versions/2.3.1/lib/ruby/ge
ms/2.3.0/gems/rb-fsevent-0.9.7/lib/rb-fsevent/fsevent.rb:42:in `select'
[ ... repeated, presumably ~20 more times ...]
[15663] Use Ctrl-C to stop
[15663] - Worker 1 (pid: 15707) booted, phase: 0
[15663] - Worker 0 (pid: 15706) booted, phase: 0
```

The bit that bothers me is the warning about multiple threads, in case that wasn't clear.

If I were to hazard a guess, I'd say whatever's new in Rails 5 that has introduced the dependency on `listen` is responsible for this, but I don't know what that is. I also don't know if it needs its threads restarted `on_worker_boot` or whether Rails already handles that correctly, automatically. It would be ace if, between you and the Puma team, you could figure out how to elide the warning. I don't like ignoring warnings!

Having written this up, I suspect I should be submitting an issue to the Rails repo instead, but since it's now such little effort to do so, I'm going to flag it up here, too. 😄 

### Expected behavior

I expect a brand new Rails app, configured to run in a popular deployment scenario, to boot with zero warnings.

### Actual behavior

In reality, with what I believe is a fairly standard deployment configuration, the Rails app boots with several warnings, as shown above, which is a suboptimal new user experience.

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.1

### PR DESCRIPTION
**Pull request by schneems**
We need one file checker booted per process as talked about in #24990. Before we do a check to see if any updates have been registered by the listener we first check to make sure that the current process has booted a listener.

We are intentionally not starting a listener when the checker is created. This way we can avoid #25259 in which puma warns of multiple threads created before fork. As written the listener for each process will be invoked by the `ActionDispatch::Executor` middleware when the `updated?` method is called. This is the first middleware on the stack and will be invoked before application code is read into memory.

The downside of this approach is that the API is a little less obvious. I.e. that you have to call `updated?` to get the listener to start is not intuitive. We could make `boot!` not private if we want to make the API a little nicer. Alternatively we could boot when the checker is initialized however this reintroduces the puma threads warning, and also means that in cases of `rails server` or when using `preload!` that we have extra threads notifying of changes on a process that we don't care about.

[close #24990] [close #25259]

### CODE REVIEW

**Comment by schneems** [comment]
Updated with logic to ensure we're never in a situation where a process has stale data.

File: activesupport/lib/active_support/evented_file_update_checker.rb [hunk 1]
```diff
@@ -28,11 +57,12 @@ def initialize(files, dirs = {}, &block)
             raise LoadError, "Could not load the 'listen' gem. Add `gem 'listen'` to the development group of your Gemfile", e.backtrace
           end
         end
-        Listen.to(*dtw, &method(:changed)).start
       end
+      boot!
     end
 
     def updated?
+      boot! unless @pid_hash[Process.pid]
```
Comment (sgrif) [inline activesupport/lib/active_support/evented_file_update_checker.rb]: Does this need to be atomic? e.g.

```
pid = Process.pid
@pid_hash.compute_if_absent(pid) { boot! }
@pid_hash[pid] = true
```

**Comment by sgrif** [comment]
I definitely think we need the API to be more explicit here. The fact that `updated?` is what causes the checker to boot makes the code path that causes this to work to become really nonlocal. (I was actually convinced that this didn't fix the issue at first, took about 20 minutes to see why it does).

It'd be good to add an integration test for this to the railties test suite as well.

File: activesupport/lib/active_support/evented_file_update_checker.rb (hunk 1 above)
Comment (schneems) [inline activesupport/lib/active_support/evented_file_update_checker.rb]: In practice it's fine if we accidentally boot more than one listener per process, we want to make sure we boot at least once though. `Concurrent::Hash` doesn't have a `compute_if_absent` locking method

**Comment by schneems** [comment]
We need some hook that we know will be called in each process, in this case I know `updated?` will be executed in the middleware. If we had some kind of `on_fork` callback this logic would all be much simpler, but nothing like that exists and I don't feel like monkey patching `fork` is a great idea.

> It'd be good to add an integration test for this to the railties test suite as well.

I can look into that.

**Comment by schneems** [comment]
I added a test, i'm pretty pleased with the result. Using pipes to synchronize the two processes.

File: activesupport/lib/active_support/evented_file_update_checker.rb (hunk 1 above)
Comment (thedarkone) [inline activesupport/lib/active_support/evented_file_update_checker.rb]: > `Concurrent::Hash` doesn't have a `compute_if_absent` locking method

The method is from `Concurrent::Map` (`Conc::Map` is a `Hash`-like data structure with a few concurrency methods thrown in, `Concurrecy::Hash` is just a synchronized carbon copy of Ruby `Hash`).

Do we even need hash for this? Can't we just have `@listen_started_on_pid` and check `Process.pid == @listen_started_on_pid`, with `@listen_started_on_pid = Process.pid` in `boot!`?

Comment (sgrif) [inline activesupport/lib/active_support/evented_file_update_checker.rb]: We should still use an atomic even if it's not a hash. While it's technically fine to have more than one listener, it's unnecessary and easy to avoid.

**Comment by schneems** [comment]
Updated to have a threadsafe `boot!` process, also using a instance variable instead of a `Concurrent::Hash`

**Comment by sgrif** [comment]
Going to go forward with this one. I think my previous concerns were rooted in thinking that the `changed` callback did more than it actually does. I think we should eventually consider an explicit `Rails.application.forked!` call which needs to occur if you're using a forking web server, but that is out of scope for 5.0.0 at this point.

**Comment by schneems** [comment]
Yay! Thanks! Just saw this notification in my email.

My only concern is that it's kinda weird that `update?` returns true on the first call. It makes sense for our application of the checker but it's an odd implementation artifact that maybe shouldn't live in this class.

As an alternative we could implement a `EventedFileChecker#forked?` that takes a block and use that in the middleware. Something like:

```ruby
evented_file_checker.forked? {|checker|
  checker.updated.make_true
  checker.boot!
end
```
