### PR TITLE
Preserve duplicate columns in `ActiveRecord::Base#select`

### LINKED ISSUE #53715: `#select` generates wrong number of columns when `Arel::Nodes::Quoted` has the same value
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true
end

class User < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_ok
    query = User.all.select([Arel::Nodes::Quoted.new('a'), Arel::Nodes::Quoted.new('b')]).to_sql

    assert_equal("SELECT 'a', 'b' FROM \"users\"", query)
  end

  def test_ng
    query = User.all.select([Arel::Nodes::Quoted.new('a'), Arel::Nodes::Quoted.new('a')]).to_sql

    assert_equal("SELECT 'a', 'a' FROM \"users\"", query)
  end
end
```

### Expected behavior
Pass the tests

### Actual behavior
```
  1) Failure:
BugTest#test_ng:
--- expected
+++ actual
@@ -1 +1 @@
-"SELECT 'a', 'a' FROM \"users\""
+"SELECT 'a' FROM \"users\""
```

### System configuration
**Rails version**: 7.2.1.1

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #53715 (see there for the problem description).

### CODE REVIEW

**Comment by kamipo** [comment]
How should `posts = Post.select(:id, :id); posts.merge(posts)` behave?

**Comment by fatkodima** [comment]
I think it should behave the same way. Changed the code to reflect that.

File: activerecord/test/cases/relation_test.rb [hunk 1]
```diff
@@ -293,6 +293,15 @@ def test_relation_merging_with_joins_as_join_dependency_pick_proper_parent
       assert_equal 3, relation.where(id: post.id).pluck(:id).size
     end
 
+    def test_merge_preserves_duplicate_columns
+      quoted_posts_id = Regexp.escape(quote_table_name("posts.id"))
+      quoted_posts = Regexp.escape(quote_table_name("posts"))
+      posts = Post.select(:id)
+      assert_queries_match(/SELECT #{quoted_posts_id}, #{quoted_posts_id} FROM #{quoted_posts}/i) do
+        posts.merge(posts).to_a
```
Comment (kamipo) [inline activerecord/test/cases/relation_test.rb:301]: I'm ok to allow explicit `select(:id, :id)` duplication, but it is not the expected behavior that values that users has not touched are duplicated each time `merge` is called. Fixed by 31d3caece6be5511dbfb5269f926dcf1648b59ac.
