### PR TITLE
Infer `:inverse_of` for `has_many ..., through:`

### LINKED ISSUE #49574: Active Record join class is unable to infer value for `belongs_to ..., inverse_of:`
### Steps to reproduce

An Active Record join model accessed through a `has_many ..., through:` association is unable to infer its `inverse_of:` association by pluralizing a predictably pluralizable class name.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "listings", force: :cascade do |t|
    t.bigint "list_id", null: false
    t.bigint "pin_id", null: false
  end

  create_table "lists", force: :cascade do |t|
  end

  create_table "pins", force: :cascade do |t|
  end
end

class Pin < ActiveRecord::Base
  has_many :listings
end

class List < ActiveRecord::Base
  has_many :listings
  has_many :pins, through: :listings
end

class Listing < ActiveRecord::Base
  belongs_to :list
  belongs_to :pin
end

class BugTest < Minitest::Test
  def test_association_stuff
    list = List.create!
    pin = list.pins.new

    pin.save!

    assert_equal [pin], list.reload.pins
    assert_equal 1, list.reload.pins.count
  end
end
```

### Expected behavior

The call to `list.reload.pins` should include `pin`, and the `Listing.belongs_to :pin` association should be able to infer its inverse by pluralizing its class name to `:listings`.

### Actual behavior

```
Failure:
BugTest#test_association_stuff [bug.rb:64]:
--- expected
+++ actual
@@ -1 +1 @@
-[#<Pin id: 1, created_at: "2023-10-10 22:12:52.792230000 +0000", updated_at: "2023-10-10 22:12:52.792230000 +0000">]
+#<ActiveRecord::Associations::CollectionProxy []>

Failure:
BugTest#test_association_stuff [bug.rb:64]:
Expected: 1
  Actual: 0
```

When declared as `Listing.belongs_to :pin, inverse_of :listings`, the tests pass.

```diff
diff --git a/activerecord/bug.rb b/activerecord/bug.rb
index ffd9d384e0..16974dc6df 100644
--- a/activerecord/bug.rb
+++ b/activerecord/bug.rb
@@ -51,7 +51,7 @@ class List < ActiveRecord::Base
 
 class Listing < ActiveRecord::Base
   belongs_to :list
-  belongs_to :pin
+  belongs_to :pin, inverse_of: :listings
 end
 
 class BugTest < Minitest::Test
```

### System configuration

**Rails version**:

`activerecord` at `main@c8149e6`

**Ruby version**:

```
❯ ruby -v
ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin22]
```

### PR DESCRIPTION
**Pull request by seanpdoyle**
### Motivation / Background

Closes [#49574][]

Issue #49574 outlines how an Active Record join model accessed through a `has_many ..., through:` association is unable to infer an appropriate `:inverse_of` association by pluralizing a predictably pluralizable class name.

### Detail

This commit resolves that issue by also checking a model's reflections for a pluralized inverse name in addition to whatever's provided through the `:as` option or inferred in the singular.

### Additional information

The issue shares a code sample:

```ruby
ActiveRecord::Schema.define do
  create_table "listings", force: :cascade do |t|
    t.bigint "list_id", null: false
    t.bigint "pin_id", null: false
  end

  create_table "lists", force: :cascade do |t|
  end

  create_table "pins", force: :cascade do |t|
  end
end

class Pin < ActiveRecord::Base
  has_many :listings
end

class List < ActiveRecord::Base
  has_many :listings
  has_many :pins, through: :listings
end

class Listing < ActiveRecord::Base
  belongs_to :list
  belongs_to :pin
end

class BugTest < Minitest::Test
  def test_association_stuff
    list = List.create!
    pin = list.pins.new

    pin.save!

    assert_equal [pin], list.reload.pins
    assert_equal 1, list.reload.pins.count
  end
end
```

Unfortunately, there isn't a one-to-one mapping in the test suite's `test/model` directory for this type of structure. The most similar associations were between the `Book`, `Subscription`, and `Subscriber`. For the sake of ease, this commit wraps the test block in a new `skipping_validations_for` helper method to ignore validations declared on the `Subscription` join table model.

[#49574]: https://github.com/rails/rails/issues/49574

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activestorage/app/models/active_storage/blob.rb [hunk 1]
```diff
@@ -31,7 +31,7 @@ class ActiveStorage::Blob < ActiveStorage::Record
   # :method:
   #
   # Returns the associated ActiveStorage::Attachment instances.
-  has_many :attachments
+  has_many :attachments, inverse_of: false
```
Comment (seanpdoyle) [inline activestorage/app/models/active_storage/blob.rb:34]: I do not understand why this change is necessary. It was motivated by [test suite failures](https://buildkite.com/rails/rails/builds/102569). 

Surprisingly, this change **does not** fix the test failures:

```diff
--- a/activestorage/app/models/active_storage/blob.rb
+++ b/activestorage/app/models/active_storage/blob.rb
@@ -31,7 +31,7 @@ class ActiveStorage::Blob < ActiveStorage::Record
   # :method:
   #
   # Returns the associated ActiveStorage::Attachment instances.
-  has_many :attachments, inverse_of: false
+  has_many :attachments, inverse_of: :blob
 
   ##
   # :singleton-method:
```

nor does defining `:inverse_of` for both sides of the association:

```diff
--- a/activestorage/app/models/active_storage/attachment.rb
+++ b/activestorage/app/models/active_storage/attachment.rb
@@ -30,7 +30,7 @@ class ActiveStorage::Attachment < ActiveStorage::Record
   # :method:
   #
   # Returns the associated ActiveStorage::Blob.
-  belongs_to :blob, class_name: "ActiveStorage::Blob", autosave: true
+  belongs_to :blob, class_name: "ActiveStorage::Blob", autosave: true, inverse_of: :attachments
 
   delegate_missing_to :blob
   delegate :signed_id, to: :blob
diff --git a/activestorage/app/models/active_storage/blob.rb b/activestorage/app/models/active_storage/blob.rb
index f180853979..ef9c6e09c6 100644
--- a/activestorage/app/models/active_storage/blob.rb
+++ b/activestorage/app/models/active_storage/blob.rb
@@ -31,7 +31,7 @@ class ActiveStorage::Blob < ActiveStorage::Record
   # :method:
   #
   # Returns the associated ActiveStorage::Attachment instances.
-  has_many :attachments, inverse_of: false
+  has_many :attachments, inverse_of: :blob
 
   ##
   # :singleton-method:
```

**Comment by seanpdoyle** [comment]
@kamipo could you review? According to `git blame`, you reverted https://github.com/rails/rails/pull/33729 (authored by @kddnewton) and have opened https://github.com/rails/rails/pull/35116, so you might have context around inferring the association.

File: activestorage/app/models/active_storage/blob.rb (hunk 1 above)
Comment (Edouard-chin) [reply activestorage/app/models/active_storage/blob.rb:32]: 👋 I created a PR in https://github.com/rails/rails/pull/50800 to fix this. Hopefully it will unblock this change !

**Comment by iamradioactive** [comment]
This PR also fixes a case where dependent records are not deleted when a parent record is destroyed in a `has_many - belongs_to` relationship after the collection is already loaded. Please refer to the reproduction script provided below.

<details>
<summary>Reproduction Script</summary>

```ruby
# frozen_string_literal: true
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  # gem "rails", github: "seanpdoyle/rails", branch: "close-49574"
  gem "rails"

  gem "sqlite3"
  gem "pry"
end

require "active_record"
require "minitest/autorun"
require "logger"
 
# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.has_many_inversing = true
 
ActiveRecord::Schema.define do
  create_table :orders, force: true do |t|
  end
 
  create_table :order_items, force: true do |t|
    t.integer :order_id
  end
end
 
class Order < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
end
 
class OrderItem < ActiveRecord::Base
  belongs_to :order#, inverse_of: :order_items
end
 
class BugTest < Minitest::Test
  def test_association_stuff
    order = Order.create!
    OrderItem.create!(order: order)
    OrderItem.create!(order: order)
    puts order.order_items
    # This last record won't be deleted without an explicit inverse_of on belong to association since the collection is already loaded
    OrderItem.create!(order: order)
    order.destroy!

    assert_equal(0, OrderItem.count)
   end
 end
```
</details>

cc: @Edouard-chin

**Comment by iamradioactive** [comment]
> > Please perform checks on your side as well just to be sure.
> 
> I'm happy to expand the test coverage on this branch. Could you share some (pseudo-)code to help me understand?

@seanpdoyle , You can refer to these comments

- https://github.com/rails/rails/pull/50284#issuecomment-1900343406
- https://github.com/rails/rails/issues/50782#issuecomment-1899009267

File: activestorage/app/models/active_storage/blob.rb (hunk 1 above)
Comment (byroot) [reply activestorage/app/models/active_storage/blob.rb:32]: I merged #50800

**Comment by seanpdoyle** [comment]
Thank you for the review and merge @byroot! I hadn't had an opportunity to add coverage to ensure that this change closes https://github.com/rails/rails/issues/50782#issuecomment-1899009267. Are you able to verify that or is it worthwhile to open a follow-up?

**Comment by seanpdoyle** [comment]
@byroot also, https://github.com/rails/rails/pull/50280 is related to this issue, and ready for review.

**Comment by Edouard-chin** [comment]
> Thank you for the review and merge @byroot! I hadn't had an opportunity to add coverage to ensure that this change closes [#50782 (comment)](https://github.com/rails/rails/issues/50782#issuecomment-1899009267). Are you able to verify that it closes that issue, or is it worthwhile to open a follow-up pull request?

It does solve it 👍 . I don't think adding another test is necessary, the one in this patch is enough (title of the issue is misleading, the problem was what you solved). Thank you 🙇 !

**Comment by andrewyoo** [comment]
@seanpdoyle This has the side effect of linking associations on unsaved records. Is that the intent as well?

```
class User < ApplicationRecord
  has_many :shifts
end

class Shift < ApplicationRecord
  belongs_to :user
end
```

Before:
```
Loading development environment (Rails 7.2.0.alpha)
irb(main):001> u = User.new
=> 
#<User:0x000000010ecb3518
...
irb(main):002> s = Shift.new user: u
=> #<Shift:0x000000010c111810 id: nil, user_id: nil>
irb(main):003> s.user
=> 
#<User:0x000000010ecb3518>
irb(main):004> u.shifts
=> []
```

After:
```
Loading development environment (Rails 7.2.0.alpha)
umami(dev)> u = User.new
=> 
#<User:0x000000012c399b30
...
umami(dev)> s = Shift.new user: u
=> #<Shift:0x0000000129e31d98 id: nil, user_id: nil>
umami(dev)> s.user
=> 
#<User:0x000000012c399b30>
umami(dev)> u.shifts
=> [#<Shift:0x0000000129e31d98 id: nil, user_id: nil>]
```

Areas in my codebase is double saving, because i believe now that the `user.shifts` has an unsaved record, it is [autosaving](https://api.rubyonrails.org/classes/ActiveRecord/AutosaveAssociation.html) on top of my normal `save`.

**Comment by rafaelfranca** [comment]
Yes. That is intended.

**Comment by byroot** [comment]
To expand on Rafael's answer.

Unfortunately setting the `inverse_of` can lead to compatibility issue with some patterns of code.

However it does bring performance and other benefits so I think it's the way forward, and shouldn't be reverted if we can avoid it.

To solve your problem short term, I believe that setting `inverse_of: false` on that impacted relation should restore the old behavior for you.

We could consider gating this whole change behind a configuration flag as to offer a deprecation period for older code.

**Comment by andrewyoo** [comment]
@rafaelfranca @byroot 

Thanks for the clarification. I'm not opposed to this change, but this does change the long standing behavior and i was wondering if this was intentional or an oversight which would be reverted once i update my project code.

Thanks!

**Comment by byroot** [comment]
> We could consider gating this whole change behind a configuration flag as to offer a deprecation period for older code.

Thinking more about this, I think it's indeed necessary to go through a deprecation because the impact is much bigger than I thought. Users should be able to just set `inverse_of: false` to keep the old behavior forever, but a deprecation should help locate the associations that need it.

**Comment by rosa** [comment]
👋 I arrived here from trying to upgrade one of our apps to Rails edge and it seems this might have some unintended consequences related to [`ActiveRecord::Suppressor`](https://github.com/rails/rails/blob/f404a949ce678dd41212a90521b3db6f3344a6ff/activerecord/lib/active_record/suppressor.rb#L32-L57), especially around linking associations on unsaved records, as @andrewyoo pointed out 🤔 I'm seeing this on regular `has_many` associations, where we suppress the creation of the `has_many` target. We might end up with an unsaved record (before there would be no record) that's saved later on when we do further operations on the association owner. 

This might be a problem in our code, and passing `inverse_of: false` on that `has_many` association fixes it but I don't believe this is the right long-term fix for us 😅. I need to come up with a minimal reproducible case, because it might be desirable to fix `ActiveRecord::Suppressor`, I think.

**Comment by rosa** [comment]
I finally was able to summarise the change in behaviour we had seen in our app stemming from this change, which I think could be fixed in Rails, but wanted to raise the issues in case you disagree and it's just a matter of clarifying what the behaviour should be so we can fix it in the app.

**Comment by byroot** [comment]
@rosa this change will be behind a configuration flag for Rails 7.2: https://github.com/rails/rails/pull/50883

It was known from the start that while the change makes thing better, existing code may be incompatible with it. I was just slow on adding the configuration flag.

**Comment by rosa** [comment]
@byroot yes! I saw that, but for those two cases, I wouldn't want to turn this change off via a configuration flag, because, as you said, the change in this PR makes things better, and because the two cases are seemingly unrelated to `has_many ..., through:` associations. I think, rather than existing app code being incompatible with this change, this has surfaced some flaws in existing _Rails_ code 🤔  At least in the case of Active Record's Suppressor, it does look like that. I also think the issue with `empty?` and `size` being inconsistent is a Rails's issue, rather than incompatible app code. 

In both cases, I'm addressing this in our app either by switching away from `any?/empty?` or by patching `ActiveRecord::Suppressor`, not by disabling this new behaviour, which is desirable.

**Comment by byroot** [comment]
Alright, I guess I don't quite understand the issue.

If you think there's a bug, it would be best to open an issue with a repro script.

**Comment by rosa** [comment]
@byroot thank you! Already did: 

- https://github.com/rails/rails/issues/51388
- https://github.com/rails/rails/issues/51392

Both have repro scripts.

**Comment by rosa** [comment]
I wanted to add another case that we ran into in Basecamp, and it made me more convinced that this change is too confusing, introducing some really sneaky bugs and situations you wouldn't expect at all. 

We have the following associations:
```ruby
class Person < ApplicationRecord
  has_many :reminders, dependent: :destroy
end

class Recording < ApplicationRecord
  has_many :reminders
end

class Reminder < ApplicationRecord
  belongs_to :person
  belongs_to :recording
end
```
And we create reminders like this: 
```ruby
class Reminder::Scheduler
  def initialize(recording, remindee)
    @recording, @remindee = recording, remindee
  end
...
    def create_reminder(time)
      remindee.reminders.create! recording: recording, remind_at: time
    rescue ActiveRecord::RecordNotUnique
    end
```
The `rescue ActiveRecord::RecordNotUnique` is because we have a unique index on `["person_id", "recording_id", "remind_at"]`, and we might create reminders simultaneously in concurrent jobs. 

The call to 
```ruby
remindee.reminders.create! recording: recording, remind_at: time
```
sets an unsaved reminder in `recording.reminders`, and that might end up being saved later on. This is completely unknown to the caller, as there's no connection between `recording` and the associated invalid reminder we end up with. 

To work around this, we'd have to set
```ruby
class Reminder < ApplicationRecord
  belongs_to :recording, inverse_of: false
end
```
but there's a big disconnection between what that does: no clue that setting that `inverse_of` will have this effect 😕 It makes you think that this is not the inverse of 
```ruby
class Recording < ApplicationRecord
  has_many :reminders
end
```
or something like that 🤔

**Comment by tagliala** [comment]
Hello,

this change seems related to `has_many ..., through:` but I have some deprecations outside of the `through:` context and it is not clear to me what I need to do

standalone reproducible test case:

```rb
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', git: 'https://github.com/rails/rails.git', ref: 'a2a870a' # main at the moment I'm writing
  gem 'sqlite3'
end

require 'active_record'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  create_table 'bars' do |t|
    t.string :name
    t.references :foo
  end

  create_table 'foos' do |t|
    t.string :name
  end
end

class Bar < ActiveRecord::Base
  belongs_to :foo
end

class Foo < ActiveRecord::Base
  has_many :bars
end

foo = Foo.create! name: 'foo'
Bar.create! name: 'bar', foo: foo
```

output:
```
$ ruby active_record_plural_dep.rb 
Fetching https://github.com/rails/rails.git
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
-- create_table("bars")
   -> 0.0095s
-- create_table("foos")
   -> 0.0002s
DEPRECATION WARNING: The `Bar#foo` inverse association could have been automatically inferred as `Foo#bars` but wasn't because `automatically_invert_plural_associations` is disabled.

If automatic inference is intended, you can consider enabling `config.active_record.automatically_invert_plural_associations`.

If automatic inference is not intended, you can silence this warning by defining the association with `inverse_of: false`. (called from <main> at active_record_plural_dep.rb:36)
```

**Comment by byroot** [comment]
> this change seems related to `has_many ..., through:`

Yeah, the title is a bit misleading, it doesn't apply exclusively to those.

> it is not clear to me what I need to do

If it doesn't break your application, just enable `config.active_record.automatically_invert_plural_associations` and that's it. It's all explained in the deprecation message.

**Comment by rosa** [comment]
@byroot, I just realised that:

> To solve your problem short term, I believe that setting `inverse_of: false` on that impacted relation should restore the old behavior for you.

would break a lot of things in general, for example, if we set:
```ruby
class Reminder < ApplicationRecord
  belongs_to :recording, inverse_of: false
end
```
we can no longer do: 
```ruby
reminder.recording
```
because that'd be `nil`. I think, in general, the cases where people would run into trouble with this change won't be cases where they want to opt out of the inverse, so suggesting that might cause more harm than good 🤔 

We also noticed that this:
```ruby
    def create_reminder(time)
      remindee.reminders.create! recording: recording, remind_at: time
    rescue ActiveRecord::RecordNotUnique
    end
```
And this: 
```ruby
    def create_reminder(time)
      remindee.reminders.create_or_find_by! recording: recording, remind_at: time
    end
```
behave exactly in the same way. I haven't had time to dig deeper, but we were expecting the second to set the found `reminder` in `recording.reminders`, instead of an invalid one. 

A way to bypass this, BTW, and get the previous behaviour, is to do this: 
```ruby
    def create_reminder(time)
      remindee.reminders.create! recording_id: recording.id, remind_at: time
    rescue ActiveRecord::RecordNotUnique
    end
```
which I'm not sure it's intended either 🤔

**Comment by rosa** [comment]
Ok, I got a reproduction script for a case where `inverse_of: false` breaks previous behaviour and doesn't work as a way to opt out of `automatically_invert_plural_associations = true`. Adding it here in case it helps anyone else encountering this while trying to solve all of the new warnings:

```ruby
# frozen_string_literal: true
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
  gem "debug"
end

require "active_record"
require "minitest/autorun"
require "logger"
require "debug"


# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.has_many_inversing = true

ActiveRecord::Schema.define do
  create_table :reminders, force: true do |t|
    t.references :recording
  end

  create_table :recordings, force: true do |t|
    t.string :email_address
  end
end

class Recording < ActiveRecord::Base
  has_many :reminders

  after_destroy :destroy_reminders

  private
    def destroy_reminders
      reminders.in_batches.destroy_all
    end
end

class Reminder < ActiveRecord::Base
  belongs_to :recording, inverse_of: false

  after_destroy :notify_remindable

  private
    def notify_remindable
      logger.info "emailing #{recording.email_address}"
    end
end

class BugTest < Minitest::Test
  def test_destroying_reminders
    recording = Recording.create!(email_address: "someone@example.com")
    reminder = recording.reminders.create!(recording: recording)

    Recording.find(recording.id).destroy
  end
end

```

This passes with: 

```ruby
class Reminder < ActiveRecord::Base
  belongs_to :recording
```

But with:

```ruby
class Reminder < ActiveRecord::Base
  belongs_to :recording, inverse_of: false
```

it fails with

```
E

Error:
BugTest#test_destroying_reminders:
NoMethodError: undefined method `email_address' for nil
    test.rb:53:in `notify_remindable'
    test.rb:42:in `destroy_reminders'
    test.rb:62:in `test_destroying_reminders'
```

Still need to look into `create_or_find_by!` and the other case where the inverse is not inferred but might be unintended (passing `record.id` instead of `record` to `create!`).

**Comment by casperisfine** [comment]
Alright, I think it's in part a documentation issue. `inverse_of: false` does more than what it actually advertise. And I'm not quite sure whether it's correct to be honest.

So long story short, we only have the `has_many :remainders -> belong_to :recording` inverse_of, but that's enough for assigning the `Recording` instance when we create a record through `recording.reminders`, thanks to `Association#set_inverse_instance`. 

In other words, `Reminder.recording` doesn't know it's the inverse of `Recording.reminders`, but the opposite is known.

What isn't explicited in the doc is that setting `inverse_of: false` doesn't only skip inferring the inversion, it also prevent any association from considering it an inverse in this context.

Short term we can update the deprecation to recommend setting `inverse_of: nil`, and it will have the behavior we want, but this needs a bit of clarification.

**Comment by ezekg** [comment]
Sorry to ping everyone here but could I get some eyes on this related issue https://github.com/rails/rails/issues/51853? I think this change has had an effect on order of operations when saving nested associations, resulting in some validation and constraint errors.
