### PR TITLE
Fix `current_page?` regression:

### LINKED ISSUE #28846: Wrong number of arguments (0 for 1) when passing model to link_to_unless_current
### Steps to reproduce

- Pass a model object as the second argument to `link_to_unless_current` in Rails 5.1.0.rc2:

```slim
            ul.vertical.menu
              - columns_with_published_posts.each do |column|
                li = link_to_unless_current column.name, column do
                  = link_to column.name, column, class: :active
```

### Expected behavior

- Pass the object to `url_for` to determine the path to compare against

### Actual behavior

```
wrong number of arguments (given 1, expected 0)
```

Full stack trace: https://gist.github.com/jbhannah/fd3fef8e2a8a341d8b29fc5f772ea5a6

### System configuration
**Rails version**: 5.1.0.rc2

**Ruby version**: 2.4.1

### PR DESCRIPTION
**Pull request by Edouard-chin**
Hey guys 👋 

- `check_parameters` kwargs was added to the `current_page?` method, the implementation was assuming only hashes responds to `delete`. This was causing issues when `current_page?` was called with a Active Model object
- `current_page?` should work with any kind of options that are accepted by [url_for](https://github.com/rails/rails/blob/master/actionview/lib/action_view/routing_url_for.rb#L77)
- ref https://github.com/rails/rails/pull/27549
- Fixes #28846

### CODE REVIEW

File: actionview/lib/action_view/helpers/url_helper.rb [hunk 1]
```diff
@@ -542,7 +542,7 @@ def current_page?(options, check_parameters: false)
 
         return false unless request.get? || request.head?
 
-        check_parameters ||= !options.is_a?(String) && options.try(:delete, :check_parameters)
+        check_parameters ||= options.respond_to?(:to_hash) && options.try(:delete, :check_parameters)
```
Comment (pixeltrix) [inline actionview/lib/action_view/helpers/url_helper.rb]: This still feels risky to me - would not going with an established pattern be better, e.g:

``` ruby
def current_page?(*args)
  options = args.extract_options!
  check_parameters = options.delete(:check_parameters)
  url_for_options = args.first || options

  # rest of implementation
end
```

If a model implements `to_hash` for some reason then it would still call `delete` on it.

@matthewd wdyt? (also wasn't my fault :wink:)

Comment (Edouard-chin) [inline actionview/lib/action_view/helpers/url_helper.rb]: I like your solution!

Comment (matthewd) [inline actionview/lib/action_view/helpers/url_helper.rb]: Maybe just change the type check to `is_a?(Hash)` instead? (And no need for the `try`)

That way we can keep the kwarg, which seems better for documentation.

Comment (Edouard-chin) [inline actionview/lib/action_view/helpers/url_helper.rb]: Thanks for your input. Sounds good to me, just want to point out that if `current_page?` gets called with a `ActionController::Parameters` then the check_parameter thing won't work.

Comment (rafaelfranca) [inline actionview/lib/action_view/helpers/url_helper.rb]: I think that is fine. To `check_parameter` be inside a Parameters instance either the end user would have to submit that information in the request (which I think it is a really bad idea) or the developer would have to merge the Paremeters with the option (in this case they should be using the named argument).

**Comment by Edouard-chin** [comment]
Update PR to follow @matthewd recommendation. Let me know if this is good enough and I'll squash

**Comment by matthewd** [comment]
Looks good, thanks. Squash away!

**Comment by rafaelfranca** [comment]
Backported in a72041597e
