### PR TITLE
Do not attempt to return connection with open transaction to pool

### LINKED ISSUE #23989: Delivering mail causes tests to fail
### Steps to reproduce

````
rails new demo
cd demo
rails generate scaffold Order invoice:string
rails generate scaffold Cart
rails db:migrate
rails generate mailer OrderNotifier received shipped
edit app/controllers/orders_controller.rb
    >>> insert "OrderNotifierMailer.received.deliver_later"
rails test
```

 * [Full log of scenario](http://intertwingly.net/tmp/aj_reload.html)

### Expected behavior
Tests should continue to pass

### Actual behavior
Tests fail

### System configuration
**Rails version**: `Rails 5.0.0.beta3` (https://github.com/rails/rails/commit/5bdeb9bfd72a97ad578efc6cce95283f589f1555)
**Ruby version**: `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]`

```
5bdeb9bfd72a97ad578efc6cce95283f589f1555 is the first bad commit
commit 5bdeb9bfd72a97ad578efc6cce95283f589f1555
Author: Matthew Draper <matthew@trebex.net>
Date:   Fri Feb 26 16:17:01 2016 +1030

    Use AS::Reloader to support reloading in ActiveJob

:040000 040000 34118e38e533d6510538180ad80981099e50ffdc 27beb3711c94cf49845a9b05182c501dd864ee23 M	activejob
bisect run success
```

### LINKED ISSUE #24491: Transaction deadlock with rails 5 beta 3
### Steps to reproduce

We have a complex test with rspec, database cleaner, factorygirl. Some runs are deadlocking. Debugging showed that there is a transaction started but not finished.

A simplified case:
https://gist.github.com/mfazekas/ccf9bee10dc4fe23f39d1da1b914993b

### Expected behavior
Pass or error, but not a deadlock

### Actual behavior

Deadlock. Test doesn't finish

### System configuration
**Rails version**: 5.0.0.beta3
**Ruby version**: 2.3.0

cannot repro in 4.2.0

### PR DESCRIPTION
**Pull request by sgrif**
When the query cache completes, if Active Record is still inside of a
transaction, it is because the transaction is meant to be left open
above this unit of work (such as transactional fixtures in tests). There
were several tests around the behavior of "tests" that were invalid, as
tests are not run through the executor. They have been changed to
reflect the new behavior, which is closer to what actually occurs in
Rails tests.

Fixes #23989
Fixes #24491
Close #24500

### CODE REVIEW

**Comment by matthewd** [comment]
My concern with this is that it means we'll leak connections if (for whatever reason) there's a transaction left open. Obviously returning them to the pool is also unwise, but IMO we should more likely be raising, or discarding the connection, if we "finish" with it dirty.

To me #24608 is more correct, both because the test *is* a unit of work, and most critically because the test body is user code that can trigger a load -- without it, we lose thread safety.

**Comment by sgrif** [comment]
The only way that a transaction would be opened (in a way that `transaction_open?` can detect) should be through `ActiveRecord::Base.transaction` which rolls back or commits in an `ensure` block. Even if we did somehow leak one, it would get reaped once the thread finishes regardless

**Comment by sgrif** [comment]
Perhaps another approach might be to check if the connection is established when the unit of work begins, and only return it if the connection was established as part of this work.

File: activerecord/lib/active_record/query_cache.rb [hunk 1]
```diff
@@ -44,8 +44,9 @@ def self.install_executor_hooks(executor = ActiveSupport::Executor)
       executor.register_hook(self)
 
       executor.to_complete do
-        # FIXME: This should be skipped when env['rack.test']
-        ActiveRecord::Base.clear_active_connections!
+        unless ActiveRecord::Base.connection.transaction_open?
+          ActiveRecord::Base.clear_active_connections!
+        end
```
Comment (mfazekas) [inline activerecord/lib/active_record/query_cache.rb]: I think it should be more like this, as ActiveRecord::Base.clear_active_connections! will clear current thread connection on all connection pool
```ruby
ActiveRecord::Base.connection_handler.connection_pool_list.each do |pool|
   pool.release_connection unless pool.active_connection? && pool.connection.transaction_open?
end
```

**Comment by mfazekas** [comment]
I think #24608 is neccesary, and yes ideally this one would verify the assumptions about connections at the run callback, but it might be better to raise if the assumption is not correct. That is likely a result of a configuration error - user should add outer executor vs a runtime error. 
FYI there is also a PR at lower level to raise if we attempt to checkin a connection with opened transactions on it: see https://github.com/rails/rails/pull/24493/files

**Comment by sgrif** [comment]
So after thinking about it a bit more, I'm more convinced that this is the right way forward. Ideally our semantics would instead be something like: "check if a connection is already established when the unit of work begins. If not, establish one, and return it to the pool at the end of the unit of work". However, I think that would be much more likely to leak connections that this path is, simply because a middleware somewhere might establish a connection before we get here without realizing the implications.

Unfortunately, I think this is just a side effect of the fact that the query cache held the responsibility for managing the connection pool, rather than something more explicitly meant to keep that role. Given that we haven't had clear semantics on the ownership roles at play here, any significant changes would likely cause subtle breakage.

As such, I think dealing with a transaction being open as our main indicator is both closest to the previous condition of `env["rack.test"]` being present, but also most closely tied to the semantics that we're looking for.

File: activerecord/lib/active_record/query_cache.rb (hunk 1 above)
Comment (sgrif) [inline activerecord/lib/active_record/query_cache.rb]: Given that the discussion here is about the ownership of the connection for the current thread, and whether we should try to release it, the pool shouldn't be involved at all here. Clearing unused connections from other threads is a side effect of checking the current connection in, not the main goal.

**Comment by sgrif** [comment]
@matthewd WDYT re ---^?

File: activerecord/lib/active_record/query_cache.rb (hunk 1 above)
Comment (mfazekas) [inline activerecord/lib/active_record/query_cache.rb]: @sgrif my code should not be deal with other thread's connections. It tries to deal with current thread's connections on multiple connection pools.
In other words it's about connections to different databases.

**Comment by matthewd** [comment]
I did come close to implementing it that way ("leave the connection in whatever state it was when we started")... the reasons I didn't were twofold: 1) the danger that something else makes the connection before we run, as you've described, and 2) I realised the test already needed to be wrapped by the executor for thread safety, which obviated this behaviour.

So, I don't feel strongly that we *shouldn't* make the change you're describing... but I do believe it only solves one of two problems.

**Comment by sgrif** [comment]
Going to go forward with this, as I think we've addressed the only concern with this specific change. #24608 is likely a change we should make in addition to this.

**Comment by mfazekas** [comment]
@sgrif i don't think my comment regarding multiple database connections was addressed, was it? https://github.com/rails/rails/pull/24610#discussion_r60229602

As a concrete case: If you have the default connection to sqlite and another to postgresql, but you only have fixtures for classes stored in postgresql, then no transaction will be opened on sqlite - ```ActiveRecord::Base.connection```. So this code will put the psql connection with opened transaction back to the pool. Shall i write a testcase demonstrating it?

**Comment by sgrif** [comment]
If it can be demonstrated through the public API only, then yes. That doesn't sound like something that can occur in a normal Rails app, though.

**Comment by mfazekas** [comment]
@sgrif so this one reproduces deadlock using public API but with multiple db connections:
https://gist.github.com/mfazekas/55ba95e52d4959bfca94787481313ca7

I agree it's not a normal rails app, but i don't think it deserves this kind of punishment.

I was wrong about rails fixtures, as  ```enlist_fixture_connections``` actually returns all the connections, irrespective where we have fixtures (which sounds correct), so with fixtures this cannot be reproduced, as fixtures puts a transaction on all connections.

**Comment by ojab** [comment]
#24004 is also fixed by this PR, should it be closed or it's better to wait for #24608 and recheck?

**Comment by yasinsa** [comment]
[havuz](https://www.cilekhavuz.com.tr)
[sauna](https://www.cilekhavuz.com.tr)
[yapımı](https://www.cilekhavuz.com.tr)
