### PR TITLE
Fix rollback of parent destruction with nested dependent:destroy

### LINKED ISSUE #40550: Rollback of parent destruction when children association throws :abort on third level
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'activesupport', path: '../../activesupport/'
  gem 'activemodel', path: '../../activemodel/'
  gem 'activerecord', path: '../'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.references :user_account
  end

  create_table :user_accounts, force: true do |t|
    t.references :profile, null: false
  end

  create_table :profiles, force: true do |t|
  end
end

class User < ActiveRecord::Base
  belongs_to :user_account,
             dependent: :destroy
end

class UserAccount < ActiveRecord::Base
  belongs_to :profile,
             dependent: :destroy
  has_one :user,
          dependent: :destroy
end

class Profile < ActiveRecord::Base
  has_one :user

  before_destroy prepend: true do
    throw :abort
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    user = User.create!(user_account: UserAccount.new(profile: Profile.new))

    assert_equal 1, User.count
    assert !user.destroy
    assert_equal 1, User.count
  end
end

```

### Expected behavior

User and UserAccount should not be destroyed.
Any `DELETE`s should not be `COMMIT`ed but to be `ROLLBACK`.
`#destroy` should return `false`.

### Actual behavior

User and UserAccount is deleted from DB.
`#destroy` returns `true`.

### System configuration
**Rails version**: 5.x and 6.0 (and 6.1.0rc2)
**Ruby version**: any

### Related
- https://github.com/rails/rails/issues/32376
- https://github.com/rails/rails/issues/32022

### PR DESCRIPTION
**Pull request by intrip**
### Summary

When a class has a `:belongs_to` relation with `dependent :destroy` enabled nested multiple levels doesn't delete the object if one of his children wasn't deleted.

Example:

    class User < ActiveRecord::Base
      belongs_to :user_account, dependent: :destroy
    end

    class UserAccount < ActiveRecord::Base
      belongs_to :profile, dependent: :destroy
    end

    class Profile < ActiveRecord::Base
      before_destroy prepend: true do
        throw :abort
      end
    end

    user = User.create!(user_account: UserAccount.new(profile: Profile.new))
    user.destroy

    user.destroyed? # expected: false; actual: true;

Fixes #40550

### CODE REVIEW

File: activerecord/lib/active_record/associations/belongs_to_association.rb [hunk 1]
```diff
@@ -9,8 +9,7 @@ def handle_dependency
 
         case options[:dependent]
         when :destroy
-          target.destroy
-          raise ActiveRecord::Rollback unless target.destroyed?
+          raise ActiveRecord::Rollback unless target.destroy
```
Comment (intrip) [inline activerecord/lib/active_record/associations/belongs_to_association.rb:12]: when `ActiveRecord::Rollback` is raised the result of `target.destroy` is `nil`. Relying on that allows to handle nested `belongs_to` with `dependent: :destroy` correctly. 
Previously `destroyed?` relied on `@destroyed` which is `true` with callbacks nested starting three or more levels.
This change also ensures that `destroyed?` returns correctly `false` in this case.

Comment (dmitry) [reply activerecord/lib/active_record/associations/belongs_to_association.rb:12]: @intrip nice, thank you for the explanation and elegant solution. I remember that I have tried to get somehow transaction status, but gave up.
