### PR TITLE
Fix `Enumerable#many?` to handle previous enumerator methods parameters

### LINKED ISSUE #46445: Enumerable#many? doesn't forward all block parameters to the caller's block
### Steps to reproduce
Call `many?` with a block, and in a chain with another function that passes an additional block parameter, such as `each_with_index`.  The block will only receive the element; additional block parameters are not forwarded.  This is different behavior than `any?`, which does forward all block parameters.

```ruby
# frozen_string_literal: true
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activesupport", "~> 6.1.0"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "active_support/core_ext/enumerable"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    [1, 2, 3].each_with_index.many? do |element, index|
      assert index.present?
      assert index == element - 1
    end
  end
end
```

### Expected behavior
The caller's block receives all block parameters.

### Actual behavior
The caller's block receives only the element.

### System configuration
**Rails version**: 6.1.6.1

**Ruby version**: 2.7.5p203

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #46445.

### CODE REVIEW

File: activesupport/lib/active_support/core_ext/enumerable.rb [hunk 1]
```diff
@@ -144,8 +144,8 @@ def index_with(default = (no_default = true))
   def many?
     cnt = 0
     if block_given?
-      any? do |element|
-        cnt += 1 if yield element
+      any? do |element, *args|
+        cnt += 1 if yield element, *args
```
Comment (casperisfine) [inline activesupport/lib/active_support/core_ext/enumerable.rb:148]:
```suggestion
      any? do |*args|
        cnt += 1 if yield *args
```
Why not?

But this then begs the question of: What about keyword arguments?

Comment (fatkodima) [reply activesupport/lib/active_support/core_ext/enumerable.rb:148]: With the `element` it is more explicit to me, but I do not have a strong opinion on this.
Aren't keyword arguments already working with this change?
