### PR TITLE
Fix rails restart issue with Puma

### LINKED ISSUE #23910: rails restart doesn't work with puma3
### Steps to reproduce

    rails new foo
    cd foo
    rails server
    rails restart

### Expected behavior
Server should restart.

### Actual behavior
Puma notices the change to `tmp/restart.txt`, stops the server, and attempts to restart the server with its own ideas of what ARGV should look like.  Rails doesn't like what it sees in ARGV, and spits out usage instructions.  At that point, the server is down.

The problem also occurs with `rails dev:cache`.

### System configuration
**Rails version**: Rails 5.0.0.beta3 (`master`)

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
- We need to pass the restart command to Puma so that it will use it
  while restarting the server.
- Besides that we need to remove the pid file for the previous running
  server because otherwise Rack complains about it's presence.
- This also requires some changes on Puma side which are being tracked
  here - https://github.com/puma/puma/pull/936.
- Fixes #23910.

r? @rafaelfranca cc @evanphx

### CODE REVIEW

File: railties/lib/rails/commands/server.rb [hunk 1]
```diff
@@ -94,7 +94,8 @@ def default_options
         environment:        (ENV['RAILS_ENV'] || ENV['RACK_ENV'] || "development").dup,
         daemonize:          false,
         caching:            nil,
-        pid:                Options::DEFAULT_PID_PATH
+        pid:                Options::DEFAULT_PID_PATH,
+        restart_cmd:        'bin/rails s'
```
Comment (rubys) [inline railties/lib/rails/commands/server.rb]: Question: if I start the rails server using, say:

    rails server -b 0.0.0.0 -p 4567

And then restart the server using:

    rails touch

Will the same options be used?

Comment (prathamesh-sonpatki) [inline railties/lib/rails/commands/server.rb]: @rubys No. It will start on port 3000 instead of 4567.

```
$ rails server -b 0.0.0.0 -p 4567
=> Booting Puma
=> Rails 5.0.0.beta3 application starting in development on http://0.0.0.0:4567
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.2.0 (ruby 2.3.0-p0), codename: Spring Is A Heliocentric Viewpoint
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:4567
Use Ctrl-C to stop
* Restarting...
=> Booting Puma
=> Rails 5.0.0.beta3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.2.0 (ruby 2.3.0-p0), codename: Spring Is A Heliocentric Viewpoint
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
* Closing unused inherited connection: tcp://0.0.0.0:4567
Use Ctrl-C to stop
```

I hadn't thought of this scenario. I will check how to make it work.

Comment (prathamesh-sonpatki) [inline railties/lib/rails/commands/server.rb]: @rubys I fixed it here - https://github.com/rails/rails/pull/24331/commits/233798977f5b01016e7ce40aa50c547a183bf9b8.

Now it works as expected.

```
$ rails server -b 0.0.0.0 -p 4567
=> Booting Puma
=> Rails 5.0.0.beta3 application starting in development on http://0.0.0.0:4567
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.2.0 (ruby 2.3.0-p0), codename: Spring Is A Heliocentric Viewpoint
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:4567
Use Ctrl-C to stop
* Restarting...
=> Booting Puma
=> Rails 5.0.0.beta3 application starting in development on http://0.0.0.0:4567
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.2.0 (ruby 2.3.0-p0), codename: Spring Is A Heliocentric Viewpoint
* Min threads: 5, max threads: 5
* Environment: development
* Inherited tcp://0.0.0.0:4567
Use Ctrl-C to stop
```

File: railties/lib/rails/dev_caching.rb [hunk 2]
```diff
@@ -15,6 +15,7 @@ def enable_by_file
         end
 
         FileUtils.touch 'tmp/restart.txt'
+        FileUtils.rm_f('tmp/pids/server.pid')
```
Comment (kaspth) [inline railties/lib/rails/dev_caching.rb]: Let's extend the existing test which asserts that the temp file has been removed to also assert that the pid file is removed.

File: railties/lib/rails/tasks/restart.rake [hunk 3]
```diff
@@ -2,4 +2,5 @@ desc "Restart app by touching tmp/restart.txt"
 task :restart do
   FileUtils.mkdir_p('tmp')
   FileUtils.touch('tmp/restart.txt')
+  FileUtils.rm_f('tmp/pids/server.pid')
```
Comment (kaspth) [inline railties/lib/rails/tasks/restart.rake]: Ditto here.

File: railties/test/commands/server_test.rb [hunk 4]
```diff
@@ -118,4 +118,17 @@ def test_default_options
       assert_equal old_default_options, server.default_options
     end
   end
+
+  def test_restart_command_contains_customized_options
+    args = ["-p", "4567"]
+    ARGV.replace args
```
Comment (kaspth) [inline railties/test/commands/server_test.rb]: Is this inline mutation a good idea? Wouldn't at least be better to capture the old ARGV value and reset in ensure.

File: railties/lib/rails/commands/server.rb [hunk 5]
```diff
@@ -130,5 +131,9 @@ def log_to_stdout
           Rails.logger.extend(ActiveSupport::Logger.broadcast(console))
         end
       end
+
+      def restart_command
+        "bin/rails s #{ARGV.join(' ')}"
```
Comment (kaspth) [inline railties/lib/rails/commands/server.rb]: Can we just expand the `s` to `server`? 😁

File: railties/lib/rails/commands/server.rb [hunk 6]
```diff
@@ -94,7 +94,8 @@ def default_options
         environment:        (ENV['RAILS_ENV'] || ENV['RACK_ENV'] || "development").dup,
         daemonize:          false,
         caching:            nil,
-        pid:                Options::DEFAULT_PID_PATH
+        pid:                Options::DEFAULT_PID_PATH,
+        restart_cmd:        restart_command
```
Comment (kaspth) [inline railties/lib/rails/commands/server.rb]: Is `restart_cmd` guaranteed to work for other servers people might use in dev?

Comment (kaspth) [inline railties/lib/rails/commands/server.rb]: By "work" I mean that they won't blow up on unsupported keys for instance (not that they will automatically use the generated command).

File: railties/lib/rails/commands/server.rb (hunk 5 above)
Comment (rafaelfranca) [inline railties/lib/rails/commands/server.rb]: :+1:

File: railties/test/commands/server_test.rb (hunk 4 above)
Comment (rafaelfranca) [inline railties/test/commands/server_test.rb]: :+1:

File: railties/lib/rails/commands/server.rb (hunk 6 above)
Comment (prathamesh-sonpatki) [inline railties/lib/rails/commands/server.rb]: I tested on Thin, Unicorn and Webrick. The `restart_cmd` has no effect on them. Meaning `rails restart` continues to **not work** while using those servers as before.

Comment (prathamesh-sonpatki) [inline railties/lib/rails/commands/server.rb]: Also these servers don't blow up on unsupported key `restart_cmd`.

File: railties/lib/rails/commands/server.rb (hunk 5 above)
Comment (prathamesh-sonpatki) [inline railties/lib/rails/commands/server.rb]: Done.

File: railties/lib/rails/tasks/restart.rake (hunk 3 above)
Comment (prathamesh-sonpatki) [inline railties/lib/rails/tasks/restart.rake]: Added coverage.

File: railties/lib/rails/dev_caching.rb (hunk 2 above)
Comment (prathamesh-sonpatki) [inline railties/lib/rails/dev_caching.rb]: Added coverage.

**Comment by prathamesh-sonpatki** [comment]
@kaspth Thanks for the review! I updated the code.

File: railties/test/commands/server_test.rb [hunk 7]
```diff
@@ -118,4 +118,18 @@ def test_default_options
...
+
+    options = Rails::Server::Options.new.parse! args
+    server = Rails::Server.new options
+    expected = "bin/rails server -p 4567"
+
+    assert_equal expected, server.default_options[:restart_cmd]
+  ensure
+    ARGV.replace original_args
```
Comment (prathamesh-sonpatki) [inline railties/test/commands/server_test.rb]: Made sure that original ARGV are replaced at the end of test. The other option was to use test specific constant TEST_ARGV like SPEC_ARGV in Puma tests but I preferred this option over that.

**Comment by rafaelfranca** [comment]
Tests are broken.

**Comment by prathamesh-sonpatki** [comment]
Thanks, I fixed the tests.

File: railties/test/commands/server_test.rb (hunk 7 above)
Comment (prathamesh-sonpatki) [inline railties/test/commands/server_test.rb]: The other option is to use `ARGV[0..-1] = args` instead of `ARGV.replace`. 

@rafaelfranca What do you think about `ARGV[0..-1] = args`?

Comment (rafaelfranca) [inline railties/test/commands/server_test.rb]: `replace` is fine to me.

**Comment by kaspth** [comment]
❤️🤘

**Comment by steakknife** [comment]
This should be backported to stable branches. It's a minimal change needed ASAP.

https://github.com/puma/puma/issues/1117

**Comment by rafaelfranca** [comment]
Which stable branch are you talking about? This is already in 5.0.0.

**Comment by prathamesh-sonpatki** [comment]
I looked into this issue. With Puma 3.5.0 and above, I am getting this error, https://gist.github.com/prathamesh-sonpatki/bc0cac8929dbf17316e8b4b7dda93e20.

With Puma 3.4 and 3.3, the `rails restart` command is working as expected. I will look into why it stopped working with Puma 3.5.

**Comment by prathamesh-sonpatki** [comment]
I have opened https://github.com/puma/puma/pull/1120 to fix this issue for Pume 3.5 and above.
