### PR TITLE
Check that entire collection has been loaded before short circuiting

### LINKED ISSUE #37730: After_initialize on STI that references association breaks preloading
When preloading data on a has_one/through association and the through association is an STI model that has an `after_initialize` hook that references the associated model, the next record in the collection will not have data preloaded correctly.

This works correctly in 5.1.7, but is broken in both Rails 5.2 and 6.0

### Steps to reproduce
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Rails 5.2
  gem 'activerecord', '~> 5.2.3'
  gem 'sqlite3', '~> 1.3.6'
  # Rails 6
  # gem 'activerecord', '~> 6.0.1'
  # gem 'sqlite3', '~> 1.4.1
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :authors, force: true do |t|
    t.string :name
  end

  create_table :posts, force: true do |t|
    t.references :author
    t.string :type
  end

  create_table :comments, force: true do |t|
    t.references :post
  end
end

class Author < ActiveRecord::Base
  has_many :posts
  has_many :comments, through: :posts
end

class Post < ActiveRecord::Base
  belongs_to :author
  has_many :comments, inverse_of: :post
end

class Comment < ActiveRecord::Base
  belongs_to :post, inverse_of: :comments
  has_one :author, through: :post
end

class Post::NewArticle < Post; end
class Post::OldArticle < Post
  after_initialize do
    author
  end
end

class BugTest < Minitest::Test
  def setup
    author1 = Author.create(name: 'Author 1')
    post1 = author1.posts.create(type: 'Post::OldArticle')
    comment1 = post1.comments.create

    author2 = Author.create(name: 'Author 2')
    post2 = author2.posts.create(type: 'Post::NewArticle')
    comment2 = post2.comments.create

    author3 = Author.create(name: 'Author 3')
    post3 = author3.posts.create(type: 'Post::OldArticle')
    comment3 = post3.comments.create

    author4 = Author.create(name: 'Author 4')
    post4 = author4.posts.create(type: 'Post::NewArticle')
    comment4 = post4.comments.create
  end

  def test_association
    comments = Comment.includes(:author).all
    # changing includes to
    # Comment.includes(post: :author).all
    # seems to work correctly

    puts comments.collect{ |c| c.author.try(:name) }

    assert_equal 4, comments.length
    refute_nil comments[0].author
    refute_nil comments[1].author
    refute_nil comments[2].author
    refute_nil comments[3].author
  end
end
```

### Expected behavior
With this test script, I would expect the `puts` statement to render:

```
Author 1
Author 2
Author 3
Author 4
```
### Actual behavior
This is the output:

```
Author 1

Author 3

```
### System configuration
**Rails version**: 5.2.3, 6.0.1

**Ruby version**: 2.5.3

### PR DESCRIPTION
**Pull request by bradleyprice**
### Summary

Currently, when checking that the collection has been loaded, only the first
record is checked. In specific scenarios, if a record is fetched via an `after_initialize`
hook, there is a chance that the first record has been loaded, but other records in the
collection have not.

In order to successfully short circuit the fetching of data, we need to verify that
all of the records in the collection have been loaded.

* Create test for edge case
* Move `reset_callbacks` method to `cases/helper`, since it has been defined in multiple
  locations.

Closes #37730

### CODE REVIEW

File: activerecord/lib/active_record/associations/preloader.rb [hunk 1]
```diff
@@ -184,7 +184,7 @@ def records_by_owner
         # and attach it to a relation. The class returned implements a `run` method
         # that accepts a preloader.
         def preloader_for(reflection, owners)
-          if owners.first.association(reflection.name).loaded?
+          if owners.map { |o| o.association(reflection.name).loaded? }.all?
```
Comment (kamipo) [inline activerecord/lib/active_record/associations/preloader.rb]:
```suggestion
          if owners.all? { |o| o.association(reflection.name).loaded? }
```

File: activerecord/test/cases/helper.rb [hunk 2]
```diff
@@ -57,6 +57,20 @@ def supports_default_expression?
   end
 end
 
+def reset_callbacks(klass, kind)
```
Comment (kamipo) [inline activerecord/test/cases/helper.rb]: Add new helper method in the `test/cases/test_case.rb`.
https://github.com/rails/rails/blob/master/activerecord/test/cases/test_case.rb

File: activerecord/lib/active_record/associations/preloader.rb (hunk 1 above)
Comment (bradleyprice) [reply activerecord/lib/active_record/associations/preloader.rb]: Fixed.

**Comment by bradleyprice** [comment]
@kamipo I've made the requested changes. How does this get ported to rails 5.2? Should I create a separate PR for that?

**Comment by kamipo** [comment]
Can you squash your commits into one?

I'll backport a bugfix to 6-0-stable (5-2-stable too) after this is getting merged, since 5-2-stable is before a final release.

**Comment by bradleyprice** [comment]
Squashed. Thanks for the help!
