### PR TITLE
Fix through association to respect source scope for `includes`/`preload`

### LINKED ISSUE #39376: Included association with unscope does not apply the unscope in has many through
`includes`ing an association that is defined using `unscope` or `unscoped` does not apply the unscoping to the query when applied via a has many through.

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.3.1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end

  create_table :responses, force: true do |t|
    t.integer :comment_id
    t.string :locale
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  has_many :responses, through: :comments
  has_many :unscoped_responses, through: :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
  has_many :responses
  has_many :unscoped_responses, -> { unscope(:where) }, class_name: :Response
  # unscope, unscope(:where) and unscope(where: :locale) all result in the same behaviour
end

class Response < ActiveRecord::Base
  belongs_to :comment

  default_scope { where(locale: :en) }
end

class BugTest < Minitest::Test
  def test_has_many_through_unscoped_includes
    post = Post.create!
    comment = post.comments.create!

    comment.responses.create!(locale: :en)
    comment.responses.create!(locale: :fr)

    assert_equal 2, Comment.includes(:unscoped_responses).first.unscoped_responses.length
    assert_equal 2, Post.includes(:unscoped_responses).first.unscoped_responses.length
  end
end
```

### Expected behavior
Both tests should succeed.

### Actual behavior
The first test succeeds, but the second one fails, on Rails 6.0.3.1 and `master`. Both tests succeed on Rails 5.2.4.3.

### System configuration
**Rails version**: 6.0.3.1

**Ruby version**: 2.6.2

### PR DESCRIPTION
**Pull request by kamipo**
`reflection.scope` is not aware of all source scopes if the association
is through association.

It should use `reflection.join_scopes` for that.

Fixes #39376.

### CODE REVIEW

File: activerecord/test/cases/associations/nested_through_associations_test.rb [hunk 1]
```diff
@@ -538,7 +538,7 @@ def test_nested_has_many_through_with_conditions_on_source_associations
   end
 
   def test_nested_has_many_through_with_conditions_on_source_associations_preload
-    author = assert_queries(4) { Author.includes(:misc_post_first_blue_tags_2).third }
+    author = assert_queries(2) { Author.includes(:misc_post_first_blue_tags_2).third }
```
Comment (kamipo) [inline activerecord/test/cases/associations/nested_through_associations_test.rb:541]: Before the change, `assert_queries(4)` (author -> posts -> taggings -> tags) was caused due to lost the source reflection scopes.

https://github.com/rails/rails/blob/8538dfdc084555673d18cfc3479ebef09f325c9c/activerecord/test/models/author.rb#L151-L155

https://github.com/rails/rails/blob/8538dfdc084555673d18cfc3479ebef09f325c9c/activerecord/test/models/post.rb#L135-L137

`Post.has_many :first_blue_tags_2` references the through `taggings` table, so the association should not be load one by one queries theoretically.

**Comment by dvandersluis** [comment]
Thanks for the fix @kamipo! I can confirm my failing test now succeeds. Can this be backported to 6-0-stable so that it can be released before 6.1? 🙌

**Comment by kamipo** [comment]
Backported in a415e804279c21b4dfbeb877ec0e40c12c2c8886.

**Comment by Edouard-chin** [comment]
Hi @kamipo , I think this fix created a super edge case ish regression when we try to preload a **polymorphic** association with a **scope**.

Here is the reproduction script https://gist.github.com/Edouard-chin/af5511a7544afe9596fabdb1da24fc3e

The error happens because when we call `reflection.join_scopes`, the reflection raises an ArgumentError when it tries to compute the class https://github.com/rails/rails/blob/0571da95934ff8004e0116cf6a91d9182707fb23/activerecord/lib/active_record/reflection.rb#L426

**Comment by kamipo** [comment]
ah... thanks for the report, I'll take a look it later.
