### PR TITLE
Fix open redirects in active storage

### LINKED ISSUE #42935: Active Storage redirect controllers broken by open redirect protection
After 5e93cff, `ActiveStorage::Blobs::RedirectController#show` raises the following for a blob stored in an S3 bucket:

```
ArgumentError: Unsafe redirect "https://█████.s3.amazonaws.com/█████...", use :allow_other_host to redirect anyway.
```

This controller and `ActiveStorage::Representations::RedirectController` probably just need `allow_other_host: true`, but we’re missing tests that exercise them with remote storage services.

/cc @gmcgibbon

### PR DESCRIPTION
**Pull request by brenogazzola**
### Summary
Fixes https://github.com/rails/rails/issues/42935

Adds `allow_other_host: true` do the redirect controllers and tests

### CODE REVIEW

File: activestorage/test/controllers/representations/redirect_controller_test.rb [hunk 1]
```diff
@@ -132,3 +132,57 @@ class ActiveStorage::Representations::RedirectControllerWithPreviewsWithStrictLo
...
+            filename: blob.filename,
+            signed_blob_id: blob.signed_id,
+            variation_key: ActiveStorage::Variation.encode(resize_to_limit: [100, 100]))
+
+      assert_redirected_to(/racecar\.jpg/)
+    end
+  end
+
+  private
+    def with_raise_on_open_redirects
```
Comment (ghiculescu) [inline activestorage/test/controllers/representations/redirect_controller_test.rb:177]: could you put this method here https://github.com/rails/rails/blob/main/activestorage/test/test_helper.rb

rather than duplicating it in both tests

**Comment by brenogazzola** [comment]
@ghiculescu I need a little help getting the service names right. I used `s3`, `gcs` and `azure`, which I copied from their respective `service_test` files. I also tested `s3` locally by using my own credentials in the `configuration.yml` file and it worked fine. But they are not working in the CI. What am I missing here?

**Comment by ghiculescu** [comment]
Ahhh, I don't think the service tests actually run in CI *except* on the main branch. Then tests like this one will run: https://github.com/rails/rails/blob/7e84afcdeb84bb4fa0a3f210ce27519a6bd3dce4/activestorage/test/service/s3_service_test.rb

My understanding is that https://github.com/rails/rails/blob/7e84afcdeb84bb4fa0a3f210ce27519a6bd3dce4/activestorage/test/service/configurations.yml.enc only gets decrypted on the main branch and that's where all the test service configuration lives. See https://github.com/rails/rails/pull/30252

So to get CI green here I think you'll want to wrap your tests in `SERVICE_CONFIGURATIONS[:s3]` (etc), and then hope for the best on main.

**Review by ghiculescu — APPROVED** [review]

**Comment by brenogazzola** [comment]
Ack! 😱

Ok, I've done my best to get this right. I've wrapped each test in their own `SERVICE_CONFIGURATIONS`, then I've run then using my own credentials, and without any credentials. Now I just have to hope they work in `main`.

**Comment by brenogazzola** [comment]
Broken tests are the ActionMailer and Railtie ones that are breaking many of the recent CI runs

**Comment by kaspth** [comment]
Nice! Well done. It might be a little tough to remember to add `allow_other_host: true` to other redirects if we ever add a new controller, but that's a separate issue (and may not be a big deal).

**Comment by brenogazzola** [comment]
Thanks! ❤️
