### PR TITLE
Use the config value directly when call `secrets`

### LINKED ISSUE #28618: Secrets not being read because of issue with production.rb
### Steps to reproduce

I am trying to add paperclip s3 config to my `production.rb`, e.g.

```
config.paperclip_defaults = {
    storage: :s3,
    s3_credentials: {
      bucket: Rails.application.secrets.S3_BUCKET_NAME,
      access_key_id: Rails.application.secrets.AWS_ACCESS_KEY_ID,
      secret_access_key: Rails.application.secrets.AWS_SECRET_ACCESS_KEY,
      s3_region: Rails.application.secrets.AWS_REGION
    }
  }
```
In the command line I enter: `RAILS_ENV=production rails c` to get into the rails command, then I enter `Appname::Application.secrets`

### Expected behavior

This should read the secrets in the `secrets.yaml.enc` and the paperclip configuration should be set up.

### Actual behavior

I only get the secrets from my `secrets.yml` file. I am just wondering if `config.paperclip_defaults = {` is a valid syntax for production.rb? 

I had another similar issue when I tried to set my send grid smtp settings in a similar way in the production.rb, I ended up having to move the code into environment.rb (adding this just in case it helps)

```
ActionMailer::Base.smtp_settings = {
  user_name: Rails.application.secrets.sendgrid_username,
  password: Rails.application.secrets.sendgrid_password,
  domain: 'app-name.herokuapp.com',
  address: 'smtp.sendgrid.net',
  port: 587, # 465 for ssl connections
  authentication: :plain,
  enable_starttls_auto: true
}

```

### System configuration
**Rails version**: 5.1.0.rc1

**Ruby version**: 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Edit:**

Here is the sample repo. 

https://github.com/hahmed/secretly

Initial commit (with the paperclip config): https://github.com/hahmed/secretly/blob/5740b6bf95cbc6665ef124adcbaa1638a6adbf3f/config/environments/production.rb#L79

```
haroon-mbp:secretly haroon$ RAILS_ENV=production rails c
Running via Spring preloader in process 1567
Loading production environment (Rails 5.1.0.rc1)
irb(main):001:0> Secretly::Application.secrets
=> {:api_key=>123, :secret_key_base=>nil, :secret_token=>nil}
irb(main):002:0> quit

```
Second commit (hide the paperclip config): 
https://github.com/hahmed/secretly/blob/master/config/environments/production.rb#L79

```
haroon-mbp:secretly haroon$ RAILS_ENV=production rails c
Running via Spring preloader in process 1722
Loading production environment (Rails 5.1.0.rc1)
irb(main):001:0> Secretly::Application.secrets
=> {:api_key=>123, :secret_key_base=>nil, :external_api_key=>"1466aac22e6a869134be3d09b9e89232fc2c2289", :sky=>"has_gots_to_fly", :me=>"the_admins_boy", :secret_token=>nil}
irb(main):002:0> 
```

Let me know if there is anything else you need for this.

### PR DESCRIPTION
**Pull request by y-yagi**
Currently, `read_encrypted_secrets` is set with initializer.
Therefore if refer to `secrets` in config, `read_encrypted_secrets` is false,
so can not get the value of `secrets.yml.enc`.

In order to be able to refer to secrets in config, modified to refer to
`config.read_encrypted_secrets` when calling `secrets`.

Fixes #28618.

r? @kaspth

### CODE REVIEW

File: railties/lib/rails/application.rb [hunk 1]
```diff
@@ -386,7 +386,8 @@ def config=(configuration) #:nodoc:
     def secrets
       @secrets ||= begin
         secrets = ActiveSupport::OrderedOptions.new
-        secrets.merge! Rails::Secrets.parse(config.paths["config/secrets"].existent, env: Rails.env)
+        secrets.merge! Rails::Secrets.parse(config.paths["config/secrets"].existent, env: Rails.env,
```
Comment (kaspth) [inline railties/lib/rails/application.rb]: How about we just filter out the encrypted secrets file instead:

```ruby
files = config.paths["config/secrets"].existent
files = files.reject { |path| path.end_with?(".enc") } unless config.read_encrypted_secrets
secrets.merge! Rails::Secrets.parse(files, env: Rails.env)
```

Then `preprocess` becomes (which will barf if the key is missing):

```ruby
def preprocess(path)
  if path.end_with?(".enc")
    decrypt(IO.binread(path))
  else
    IO.read(path)
  end
end
```

**Comment by kaspth** [comment]
Can we write a regression test for this? For instance, generate a Rails app and then reference the `secrets` in `production.rb`.

Something like:

```ruby
Rails::Secrets.write(<<-end_of_yaml)
  production:
    some_secret: yeah yeah
end_of_yaml

add_to_config "config/environments/production.rb", <<-end_of_config
  config.dereferenced_secret = config.secrets.some_secret
end_of_config

Dir.chdir(app_path) do
  assert_equal "yeah yeah", `bin/rails runner "puts Rails.config.dereferenced_secret"`
end
```

File: railties/lib/rails/application.rb (hunk 1 above)
Comment (y-yagi) [inline railties/lib/rails/application.rb]: Thanks for reviewing!
Looks good. I updated. Also, I added tests.

**Comment by kaspth** [comment]
Sweet, thanks!

**Comment by lserman** [comment]
Will this make it into 5.1 branch? Master is using 5.2. Without this fix you can't use Rails.application.secrets for DB config because `db:create`, `db:migrate`, etc will not pickup the `read_encrypted_secrets` value.

**Comment by rafaelfranca** [comment]
It is already there.

**Comment by maclover7** [comment]
For reference, this was backported via b7a038a1c5e199736b7aeb1f2fb5c95fdc8ccbea.

**Comment by lserman** [comment]
Thanks everyone, I was using the v5.1.0.rc1 tag instead of the 5-1-stable branch 👍
