### PR TITLE
Fix timestamp type for sqlite3

### LINKED ISSUE #41310: Inconsistency for timestamp column type
### Steps to reproduce

1. Use `sqlite3` database adapter
2. Run following 3 migrations

```
class CreateMeetings < ActiveRecord::Migration[5.2]
  def change
    create_table :meetings do |t|
      t.string :title
      t.date :date

      t.timestamps
    end
  end
end
```

```
class AddStartTimeToMeetings < ActiveRecord::Migration[5.2]
  def change
    add_column :meetings, :start_time, :timestamp
  end
end
```

```
class ChangeMeetingsDateToEndTime < ActiveRecord::Migration[5.2]
  def change
    rename_column :meetings, :date, :end_time
    change_column :meetings, :end_time, :timestamp
  end
end
```

3. Open db console using `rails db` console and check meetings table schema:
meetings rails db 2021-02-03 12-37-27

### Expected behavior

Both `start_time` and `end_time` should have same column type as timestamp.

### Actual behavior

Both `start_time` is having datime as column type and `end_time` is having timestamp as column type

### System configuration
**Rails version**:
Rails 5.2.0

**Ruby version**:
ruby 2.4.4p296

### PR DESCRIPTION
**Pull request by eileencodes**
According to the tests and code, sqlite3 converts the `timestamp` type
from `timestamp` to `datetime.` This can be seen in the change schema
tests.

This caused behavior to differ from `add_column` and `change_column`
because `change_column` wasn't calling `aliased_types`. The change here
fixes `change_column` so that it calls `aliased_types` the same way
`add_column` does.

Fixes #41310

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb [hunk 1]
```diff
@@ -270,8 +270,8 @@ def change_column_null(table_name, column_name, null, default = nil) #:nodoc:
 
       def change_column(table_name, column_name, type, **options) #:nodoc:
         alter_table(table_name) do |definition|
-          definition[column_name].instance_eval do
-            self.type = type
+          definition[column_name].instance_eval do |x|
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:273]: Do we need the `|x|` here?

**Review by rafaelfranca — APPROVED** [review]

File: activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb (hunk 1 above)
Comment (eileencodes) [reply activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:273]: Whoops, no that was from my debugging, removing now.

**Comment by eileencodes** [comment]
Backported to 6-1-stable in d1fd6370fcb3c776419ad1bbf670350e46ff7b76 and 6-0-stable in 4b6b98432b8b1fad3757dd4441ee8ad3fd626edd
