### PR TITLE
Bugfix: Fix false autosave for has_one :through association

### LINKED ISSUE #35680: Autosave happens every time on has_one :through
### Steps to reproduce
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: 'rails/rails'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users do |t|
    t.references :representer, null: false
    t.timestamps
  end

  create_table :representers do |t|
    t.timestamps
  end

  create_table :posts do |t|
    t.references :representer, null: false
    t.timestamps
  end

  create_table :logs do |t|
    t.timestamps
  end
end

class Log < ActiveRecord::Base; end

class User < ActiveRecord::Base
  belongs_to :representer

  after_commit -> { Log.create! }
end

class Representer < ActiveRecord::Base
  has_one :user

  after_commit -> { Log.create! }
end

class Post < ActiveRecord::Base
  belongs_to :representer
  has_one :user, through: :representer
end

class BugTest < Minitest::Test
  def setup
    # It's false positive when post_id == user_id
    # make user_id different from post_id
    User.create!(representer: Representer.create!)

    @representer = Representer.create!
    @user = User.create!(representer: @representer)
    @post = Post.create!(representer: @representer)
  end

  def test_autosave_for_a_user
    log_count = Log.count
    @post.tap(&:user).save!
    assert_equal(log_count, Log.count)
  end

  def test_autosave_for_a_representer
    log_count = Log.count
    @post.tap(&:representer).save!
    assert_equal(log_count, Log.count)
  end
end
```

### Expected behavior
`after_commit` should not be called on `User` on `Post` saving

### Actual behavior
`after_commit` is called on `User` despite it was not changed

### System configuration
**Rails version**:
git master 7c6343078a566264ce6df6e531c9790ff2d2f432

**Ruby version**:
`2.5.3p105`

The problem happens here:

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/autosave_association.rb#L460

Because User has foreign_key for the representer, and it's representer_id, not post_id. When both IDs don't match, it thinks that the association was changed, and triggers commit for User too

### PR DESCRIPTION
**Pull request by Kukunin**
### Summary

Fixes #35680 

### Other Information

The problem occurred, when a `has one through` association contains a foreign key (it belongs to the intermediate association).

For example, Comment belongs to Post, Post belongs to Author, and Author `has_one :first_comment, through: :first_post`.

In this case, the value of the foreign key is comparing with the original record, and since they are likely different, the association is marked as changed.  So it updates every time when the origin record updates.

### CODE REVIEW

**Comment by Kukunin** [comment]
How can this be backported to 5.2.x branch?

File: activerecord/lib/active_record/autosave_association.rb [hunk 1]
```diff
@@ -456,9 +456,18 @@ def save_has_one_association(reflection)
...
-          record.will_save_change_to_attribute?(reflection.foreign_key)
+        return true if record.new_record?
+        return true if association_key_changed?(reflection, record, key)
+        return true if record.will_save_change_to_attribute?(reflection.foreign_key)
+
+        false
+      end
+
+      # If association foreign key was changed
+      def association_key_changed?(reflection, record, key)
```
Comment (eileencodes) [inline activerecord/lib/active_record/autosave_association.rb]: Instead of leaving a comment can you update the method name to be `association_foreign_key_changed?` and then move this to a private namespace since we don't want anyone using this directly in their applications.

File: activerecord/lib/active_record/autosave_association.rb [hunk 2]
```diff
@@ -456,9 +456,18 @@ def save_has_one_association(reflection)
 
       # If the record is new or it has changed, returns true.
       def record_changed?(reflection, record, key)
-        record.new_record? ||
-          (record.has_attribute?(reflection.foreign_key) && record[reflection.foreign_key] != key) ||
-          record.will_save_change_to_attribute?(reflection.foreign_key)
+        return true if record.new_record?
+        return true if association_key_changed?(reflection, record, key)
+        return true if record.will_save_change_to_attribute?(reflection.foreign_key)
```
Comment (eileencodes) [inline activerecord/lib/active_record/autosave_association.rb]: This is so much nicer to read 😍

**Review by eileencodes — CHANGES_REQUESTED** [review]
Thanks for fixing @Kukunin - please don't backport until we have decided whether to merge this PR. Once merged we will backport or ask you to open a new PR if there are conflicts with the backport.

I restarted the travis build because there were a lot of broken builds but they seemed related to some problem with travis and not here - but also meant it couldn't verify the tests passed.

I also left a few comments but otherwise this is looking good 👍

File: activerecord/lib/active_record/autosave_association.rb (hunk 1 above)
Comment (Kukunin) [reply activerecord/lib/active_record/autosave_association.rb]: good point. as for the private, it's already inside the private space, but I added `_` prefix to it, to mark the name as private too

Comment (eileencodes) [reply activerecord/lib/active_record/autosave_association.rb]: Sorry didn't realize it was already private - you can leave it without the `_` prefix then.

Comment (Kukunin) [reply activerecord/lib/active_record/autosave_association.rb]: I saw a method below with underscore, so assume that it's ok too. I would leave it as is

**Comment by Kukunin** [comment]
@eileencodes does it look good now?

File: activerecord/lib/active_record/autosave_association.rb [hunk 3]
```diff
@@ -456,9 +456,17 @@ def save_has_one_association(reflection)
 
       # If the record is new or it has changed, returns true.
       def record_changed?(reflection, record, key)
-        record.new_record? ||
-          (record.has_attribute?(reflection.foreign_key) && record[reflection.foreign_key] != key) ||
-          record.will_save_change_to_attribute?(reflection.foreign_key)
+        return true if record.new_record?
+        return true if _association_foreign_key_changed?(reflection, record, key)
```
Comment (kamipo) [inline activerecord/lib/active_record/autosave_association.rb]: I think `a || b || c` is much readable enough.

```diff
diff --git a/activerecord/lib/active_record/autosave_association.rb b/activerecord/lib/active_record/autosave_association.rb
index d77d76cb1e..07c20c3ad1 100644
--- a/activerecord/lib/active_record/autosave_association.rb
+++ b/activerecord/lib/active_record/autosave_association.rb
@@ -457,7 +457,7 @@ def save_has_one_association(reflection)
       # If the record is new or it has changed, returns true.
       def record_changed?(reflection, record, key)
         record.new_record? ||
-          (record.has_attribute?(reflection.foreign_key) && record[reflection.foreign_key] != key) ||
+          _association_foreign_key_changed?(reflection, record, key) ||
           record.will_save_change_to_attribute?(reflection.foreign_key)
       end
 
```

File: activerecord/lib/active_record/autosave_association.rb [hunk 4]
```diff
@@ -456,9 +456,17 @@ def save_has_one_association(reflection)
...
+        return true if record.will_save_change_to_attribute?(reflection.foreign_key)
+
+        false
+      end
+
+      def _association_foreign_key_changed?(reflection, record, key)
+        return false if reflection.through_reflection
```
Comment (kamipo) [inline activerecord/lib/active_record/autosave_association.rb]: Use `through_reflection?`.

```suggestion
        !reflection.through_reflection? &&
          record.has_attribute?(reflection.foreign_key) && record[reflection.foreign_key] != key
```

File: activerecord/lib/active_record/autosave_association.rb [hunk 5]
```diff
@@ -456,9 +456,17 @@ def save_has_one_association(reflection)
...
-          (record.has_attribute?(reflection.foreign_key) && record[reflection.foreign_key] != key) ||
-          record.will_save_change_to_attribute?(reflection.foreign_key)
+        return true if record.new_record?
+        return true if _association_foreign_key_changed?(reflection, record, key)
+        return true if record.will_save_change_to_attribute?(reflection.foreign_key)
+
+        false
+      end
+
+      def _association_foreign_key_changed?(reflection, record, key)
```
Comment (kamipo) [inline activerecord/lib/active_record/autosave_association.rb]: The leading `_` is less worth, since it is private (people can't call it directly), and the four words method name is less likely to conflict with user-defined method names, either is fine through.

**Comment by Kukunin** [comment]
@kamipo @eileencodes so we got a conflict on condition form:

````ruby
return true if some_condition_A
return true if some_condition_B
return true if some_extremely_long_condition_C

false
```

or 

```ruby
some_condition_A ||
 some_condition_B ||
 some_extremely_long_condition_C
```

Which one should I use in this PR?

**Comment by kamipo** [comment]
We usually don’t use multiple early returning.

By extracted a little complex condition, this is already simple enough.
Just use `a || b || c`

File: activerecord/lib/active_record/autosave_association.rb (hunk 4 above)
Comment (Kukunin) [reply activerecord/lib/active_record/autosave_association.rb]: I dared to leave this as is. Comparing with the other case, where are 3 guards, here is only one. 
And mentally things are different enough to not join them into a single complex condition phrase. I consider this as a mentally easier, however less concise

File: activerecord/lib/active_record/autosave_association.rb (hunk 5 above)
Comment (Kukunin) [reply activerecord/lib/active_record/autosave_association.rb]: Agree, removed the leading underscore

**Review by kamipo — APPROVED** [review]
Looks good to me.
Can you squash your commits into one?

**Comment by Kukunin** [comment]
Can’t you merge squashed? GitHub supports this feature. If no, I’ll squash it in a couple of hours

**Comment by Kukunin** [comment]
squashed, ready to merge
