### PR TITLE
Fix bug with long stream identifiers when using Postgres adapter

### LINKED ISSUE #28751: ActionCable's stream_for creates channel identifiers are too long for postgres
The `stream_for` method of `ActionCable::Channel` can make database identifiers that are invalid for Postgres, which has a 63 character limit. I am using UUIDs for ids in my database and `stream_for` uses `to_gid_param` to make the name, creating an identifier that is often over 80 characters. I was able to get things to work by just using `model.id` instead of `model.to_gid_param` as in the [base class](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/actioncable/lib/action_cable/channel/broadcasting.rb#L21).

Fix in app/channels/application_cable/channel.rb:

````ruby
module ApplicationCable
  class Channel < ActionCable::Channel::Base

    def self.broadcasting_for(model)
      case
      when model.is_a?(Array)
        model.map { |m| broadcasting_for(m) }.join(":")
      when model.respond_to?(:id)
        model.id
      else
        model.to_param
      end

    end
````

### PR DESCRIPTION
**Pull request by palkan**
Fixes #28751.

PostgreSQL has a limit on identifiers length (63 chars, [docs]( https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS)).

Provided fix minifies identifiers longer than 63 chars by hashing them with SHA1.
Although it has an impact on performance, I think, it's negligible.

It would be great to use non-cryptographic hash functions (such as Murmur or CityHash), but that would require adding new dependencies.

### CODE REVIEW

File: actioncable/test/subscription_adapter/common.rb [hunk 1]
```diff
@@ -32,7 +33,7 @@ def subscribe_as_queue(channel, adapter = @rx_adapter)
     subscribed.wait(WAIT_WHEN_EXPECTING_EVENT)
     assert subscribed.set?
 
-    yield queue
+    Timeout.timeout(WAIT_WHEN_EXPECTING_EVENT) { yield queue }
```
Comment (matthewd) [inline actioncable/test/subscription_adapter/common.rb]: :-1:

File: actioncable/test/subscription_adapter/postgresql_test.rb [hunk 2]
```diff
@@ -12,7 +12,7 @@ def setup
     if Dir.exist?(ar_tests)
       require File.join(ar_tests, "config")
       require File.join(ar_tests, "support/config")
-      local_config = ARTest.config["arunit"]
+      local_config = ARTest.config["connections"]["postgresql"]["arunit"]
```
Comment (matthewd) [inline actioncable/test/subscription_adapter/postgresql_test.rb]: ❓

**Review by matthewd — COMMENTED** [review]
I'm fine with SHA1 -- it shouldn't be user-controlled data, so I see no risk of collision. And it's used for network communication, so the extra time spent hashing should indeed be negligible.

It does seem a bit unfortunate to leave it totally opaque, though... is it worth keeping the first 22 characters?

File: actioncable/test/subscription_adapter/postgresql_test.rb (hunk 2 above)
Comment (palkan) [inline actioncable/test/subscription_adapter/postgresql_test.rb]: As I understand, we want to use the same DB configuration as in ActiveRecord tests (that's why we're using `ARTest`).

`ARTest.config["arunit"]` is always `nil`, 'cause databases [config](https://github.com/rails/rails/blob/master/activerecord/test/config.example.yml) has nested structure (connections -> adapter -> id).

I'm using custom PostgreSQL credentials in `config.yml`, and it turned out that there is a bug here.

Comment (palkan) [inline actioncable/test/subscription_adapter/postgresql_test.rb]: It can be extracted into a separate PR, 'cause it does nothing with the bug under consideration.

File: actioncable/test/subscription_adapter/common.rb (hunk 1 above)
Comment (palkan) [inline actioncable/test/subscription_adapter/common.rb]: Could you, please, clarify?

That's an easiest way to handle blocking `queue.pop` calls in these tests (which cause a process to stuck forever).

Of course, it would be better to refactor the tests to not use blocking calls though.

Another idea is to "enhance" `Queue#pop` with built-in timeout through refinements:

```ruby
refine Queue do
  def pop(timeout)
    while empty?
      sleep 0.1
      timeout -= 0.1
      return nil unless timeout > 0
    end
    super
  end
end
```

Or we can add custom queue class.

But either way, I think, we should be able to make tests fail (which is impossible now).

**Comment by palkan** [comment]
> is it worth keeping the first 22 characters?

Keeping in mind that we're working with long GlobalIDs, I'm not sure that would help, 'cause in that case the prefix would contain only a part of a namespace, e.g. "gid://app/MySuperModule/SubModule/Person/5" => "gid://app/MySuperModul".

**Comment by palkan** [comment]
@matthewd Codebase was cleaned up. Anything else I can do to get it merged?

**Comment by matthewd** [comment]
Sorry I didn't reply on this earlier.

Beyond general concern about Timeout, allocating a single `WAIT_WHEN_EXPECTING_EVENT` to an arbitrarily-long block of code (which could, itself, contain one or more waits) doesn't really honour the implied contract. Tests failing when things are broken is certainly a good thing, though, so finding some way to make that true seems like a good idea. I think I'd still be hesitant for any "set up a subscription" helper to apply a surprise time limit on its contained block, though.

As for the ARTest thing -- yeah, I just couldn't work out why that was necessary for this change. If it's Just Wrong, we should definitely fix that. 🙈

**Comment by eric1234** [comment]
If someone needs this backported to a released version of Rails the following will work:

```
# Backport of https://github.com/rails/rails/commit/2bce7777b70efe81f45e4ae8dc61b25f1e18771e
require 'action_cable/subscription_adapter/postgresql'

module PostgresChannelShortener
  def broadcast channel, payload
    super channel_identifier(channel), payload
  end

  def subscribe channel, callback, success_callback=nil
    super channel_identifier(channel), callback, success_callback
  end

  def unsubscribe channel, callback
    super channel_identifier(channel), callback
  end

  private

  def channel_identifier channel
    channel.size > 63 ? Digest::SHA1.hexdigest(channel) : channel
  end
end
ActionCable::SubscriptionAdapter::PostgreSQL.prepend PostgresChannelShortener
```

I drop this in my `lib` directory then just require it from my `config/application.rb` file.
