### PR TITLE
[Fix #48080] Use `group` over `distinct` in `ActiveRecord::Calculations#ids` with `includes(...).order(...)`

### LINKED ISSUE #48080: Broken order(...).includes(...).ids in PostgreSQL
### Steps to reproduce

This bug was introduced by a change to exclude duplicate rows from the id. https://github.com/rails/rails/pull/46503
A `DISTINCT` clause has been added to avoid duplication, but this is an error because the implementation does not consider the case where an `ORDER(column_other_than_pk)` clause exists.

I tried to fix it, but couldn't figure out how to fix it.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "pg"
end

require 'active_record'
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
begin
  config = { adapter: "postgresql", encoding: 'unicode', url: "postgresql://postgres@localhost:5432", password: 'postgres', database: 'rails-test' }
  ActiveRecord::Base.establish_connection(config.except(:database))
  ActiveRecord::Base.connection.drop_database(config[:database]) rescue nil
  ActiveRecord::Base.connection.create_database(config[:database])
end

ActiveRecord::Base.establish_connection(config)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.timestamps
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_includes_ids
    Post.order(:created_at).includes(:comments).ids
  end
end
```

### Expected behavior

no exception

### Actual behavior

```
ActiveRecord::StatementInvalid: PG::InvalidColumnReference: ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list
```

### System configuration
**Rails version**: main

**Ruby version**:

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

This Pull Request has been created to fix https://github.com/rails/rails/issues/48080.
As mentioned in the issue, a regression was introduced in https://github.com/rails/rails/pull/46503 where `includes(...).order(...)` would error with `#ids` due to a `DISTINCT` that wouldn't contain the ordering columns as required by `postgres` and `mysql`.

From the `PostgreSQL` docs:

Screenshot 2023-05-01 at 3 16 49 pm

### Detail

This Pull Request changes `ActiveRecord::Calculations#ids` to use `#group` over `#distinct` to avoid having a `DISTINCT` that would be incompatible with the selected columns.

I went with this approach since:
- `group` will give us the same result using the same execution plan (both use `HashAggregate`).
- Including the ordering columns in the `SELECT` is not an option as we want to `SELECT` only the primary key/s for `#ids`.
- The only other alternative I could think of was constructing a subquery for the above which seems overcomplicated and would probably introduce unnecessary overhead.

### Additional information

Not relevant to the issue but https://github.com/rails/rails/pull/46697 is a related follow up PR to the one that introduced the regression.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/test/cases/calculations_test.rb [hunk 1]
```diff
@@ -1049,6 +1049,12 @@ def test_ids_with_includes
     assert_equal Company.all.map(&:id).sort, Company.all.includes(:contracts).ids.sort
   end
 
+  def test_ids_with_includes_and_non_primary_key_order
+    rating = 1
+    Company.all.each { |company| company.update!(rating: rating += 1) }
+    assert_equal Company.all.sort_by(&:rating).map(&:id), Company.includes(:comments).order(:rating).ids
```
Comment (joshuay03) [inline activerecord/test/cases/calculations_test.rb:1055]: Before the fix:
Screenshot 2023-05-01 at 9 14 51 am

**Comment by eileencodes** [comment]
cc/ @nvasilevski can you review this?

**Review by nvasilevski — COMMENTED** [review]
No concerns apart from a nitpick 👍

File: activerecord/lib/active_record/relation/calculations.rb [hunk 2]
```diff
@@ -325,19 +325,22 @@ def async_pick(*column_names)
     #   Person.ids # SELECT people.id FROM people
     #   Person.joins(:companies).ids # SELECT people.id FROM people INNER JOIN companies ON companies.id = people.company_id
     def ids
+      primary_keys = Array(primary_key)
```
[the remark this answers is not in the document]
Comment (joshuay03) [reply activerecord/lib/active_record/relation/calculations.rb]: I agree with the naming, updated to use `primary_key_array` here: https://github.com/rails/rails/pull/48101/commits/4a496d194703ddf2aef3ad93d8adafee6daf5d47.

**Comment by joshuay03** [comment]
> No concerns apart from a nitpick 👍

Cheers @nvasilevski, I've updated the PR!

File: activerecord/test/cases/calculations_test.rb (hunk 1 above)
Comment (javieromar7) [reply activerecord/test/cases/calculations_test.rb:1055]: what would  solution to solve this breaking change?.

use `pluck(:id)` over ,ids. change `includes` to `joins`. but include generates left outer join and join generates inner join. so it would not be the same.
