### PR TITLE
use Thor option parser in server commands parse

### LINKED ISSUE #26964: handle_argument_error
rails server -b 0.0.0.0 -p 4000 -e development

ERROR: "rails server" was called with arguments ["-b", "0.0.0.0", "-p", "4000", "-e", "development"] (Thor::InvocationError)
Usage: "bin/rails server [options]"

### PR DESCRIPTION
**Pull request by y-yagi**
### Summary

In master, when start rails server with arguments, it will fail. 

``` 
$ ./bin/rails -v
Rails 5.1.0.alpha
$ ./bin/rails s -p 3001
/home/yaginuma/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:483:in `handle_argument_error': ERROR: "rails server" was called with arguments ["-p", "3001"] (Thor::InvocationError)
Usage: "bin/rails server [options]"
	from /home/yaginuma/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:34:in `rescue in run'
	from /home/yaginuma/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:21:in `run'
	from /home/yaginuma/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/yaginuma/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/yaginuma/program/rails/master_y_yagi/rails/railties/lib/rails/command/base.rb:61:in `perform'
	from /home/yaginuma/program/rails/master_y_yagi/rails/railties/lib/rails/command.rb:34:in `invoke'
	from /home/yaginuma/program/rails/master_y_yagi/rails/railties/lib/rails/commands.rb:16:in `<top (required)>'
	from ./bin/rails:9:in `require' 
```

The `ServerCommand` inherits Thor, but it does not use Thor is the
parse of the argument.
Therefore, if leave the argument of Thor as it is, it becomes an error by the
argument checking of Thor.
To avoid it, to clear the argument of Thor.

Fixes #26964

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Can we use the Thor option parser instead of reimplementing it?

**Comment by y-yagi** [comment]
If I am not mistaken, it is possible. I will try.

File: railties/lib/rails/commands/server/server_command.rb [hunk 1]
```diff
@@ -6,52 +6,8 @@
...
-
-          opts.on("-h", "--help", "Shows this help message.") { puts opts; exit }
-        end
-      end
-    end
-
-    def initialize(*)
-      super
+    def initialize(options = nil)
+      super(options)
```
Comment (rafaelfranca) [inline railties/lib/rails/commands/server/server_command.rb]: Does not only `super` work here?

File: railties/lib/rails/commands/server/server_command.rb [hunk 2]
```diff
@@ -140,21 +80,72 @@ def restart_command
 
   module Command
     class ServerCommand < Base # :nodoc:
-      def help
-        puts Rails::Server::Options.new.option_parser(Hash.new)
+      DEFAULT_PID_PATH = File.expand_path("tmp/pids/server.pid").freeze
+
+      class_option :port, aliases: "-p", type: :numeric,
+        desc: "Runs Rails on the specified port.", banner: :port
```
Comment (rafaelfranca) [inline railties/lib/rails/commands/server/server_command.rb]: Can we keep the default in the description?

File: railties/lib/rails/commands/server/server_command.rb [hunk 3]
```diff
@@ -140,21 +80,72 @@ def restart_command
...
+      class_option :binding, aliases: "-b", type: :string,
+        desc: "Binds Rails to the specified IP.", banner: :IP
```
Comment (rafaelfranca) [inline railties/lib/rails/commands/server/server_command.rb]: Same thing about the default

File: railties/test/commands/server_test.rb [hunk 4]
```diff
@@ -132,12 +136,28 @@ def test_restart_command_contains_customized_options
...
-    assert_equal expected, server.default_options[:restart_cmd]
+    assert_equal expected, options[:restart_cmd]
   ensure
     ARGV.replace original_args
   end
+
+  private
+
+    def parse_arguments(args)
+      Rails::Command::ServerCommand.class_eval do
```
Comment (rafaelfranca) [inline railties/test/commands/server_test.rb]: I believe you can asset those things only initializing a command object. `Rails::Command::ServerCommand.new` should expose everything you can.

**Review by rafaelfranca — DISMISSED** [review]

File: railties/lib/rails/commands/server/server_command.rb [hunk 5]
```diff
@@ -140,21 +80,72 @@ def restart_command
...
+        def port
+          options[:port] || ENV.fetch("PORT", 3000).to_i
+        end
+
+        def host
+          options[:binding] || ENV.fetch("HOST", "localhost")
+        end
+
+        def environment
+          options[:environment] || (ENV["RAILS_ENV"] || ENV["RACK_ENV"] || "development")
```
Comment (kaspth) [inline railties/lib/rails/commands/server/server_command.rb]: I wrote a `Rails::Command.environment` method for this.

File: railties/lib/rails/commands/server/server_command.rb [hunk 6]
```diff
@@ -140,21 +80,72 @@ def restart_command
...
+        end
+
+        def restart_command
+          "bin/rails server #{ARGV.join(' ')}"
```
Comment (kaspth) [inline railties/lib/rails/commands/server/server_command.rb]: I don't think the command infrastructure guarantees argv to be unharmed. We should add one test that uses every option and ensures every one option is present in the rerun command.

File: railties/test/commands/server_test.rb [hunk 7]
```diff
@@ -132,12 +136,28 @@ def test_restart_command_contains_customized_options
...
     expected = "bin/rails server -p 4567"
 
-    assert_equal expected, server.default_options[:restart_cmd]
+    assert_equal expected, options[:restart_cmd]
   ensure
     ARGV.replace original_args
   end
+
+  private
+
```
Comment (kaspth) [inline railties/test/commands/server_test.rb]: ✂️

File: railties/test/commands/server_test.rb (hunk 4 above)
Comment (kaspth) [inline railties/test/commands/server_test.rb]: Not sure, I had to do something similar for the other commands. But if we can make it happen, great 👍

File: railties/lib/rails/commands/server/server_command.rb [hunk 8]
```diff
@@ -140,21 +80,72 @@ def restart_command
...
+      class_option :port, aliases: "-p", type: :numeric,
+        desc: "Runs Rails on the specified port.", banner: :port
+      class_option :binding, aliases: "-b", type: :string,
+        desc: "Binds Rails to the specified IP.", banner: :IP
+      class_option :config, aliases: "-c", type: :string, default: "config.ru",
+        desc: "Uses a custom rackup configuration.", banner: :file
+      class_option :daemon, aliases: "-d", type: :boolean, default: false,
+        desc: "Runs server as a Daemon."
+      class_option :environment, aliases: "-e", type: :string,
+        desc: "Specifies the environment to run this server under (test/development/production).", banner: :name
```
Comment (kaspth) [inline railties/lib/rails/commands/server/server_command.rb]: `(development/test/production)` is the usual order we'd write this in.

File: railties/lib/rails/commands/server/server_command.rb [hunk 9]
```diff
@@ -89,18 +41,6 @@ def middleware
       Hash.new([])
     end
 
-    def default_options
```
Comment (kaspth) [inline railties/lib/rails/commands/server/server_command.rb]: The reason I didn't pursue writing these options using Thor in the first place was that `Rails::Server` interops with `Rack::Server` in certain ways as seen by the `super` here.

Thus, since some of the methods you removed were also public, I figured they were part of `Rails::Server`'s public API and to remove them we'd need to go through a deprecation cycle.

cc @rafaelfranca

File: railties/lib/rails/commands/server/server_command.rb (hunk 1 above)
Comment (kaspth) [inline railties/lib/rails/commands/server/server_command.rb]: Probably not. See my comment about `Rack::Server` interop.

File: railties/lib/rails/commands/server/server_command.rb [hunk 10]
```diff
@@ -6,52 +6,8 @@
...
-        args, options = args.dup, {}
-
-        option_parser(options).parse! args
-
-        options[:log_stdout] = options[:daemonize].blank? && (options[:environment] || Rails.env) == "development"
-        options[:server]     = args.shift
-        options
-      end
-
-      def option_parser(options) # :nodoc:
```
Comment (kaspth) [inline railties/lib/rails/commands/server/server_command.rb]: This is also a method that's overriden from `Rack::Server`.

**Comment by guilleiguaran** [comment]
`./bin/rails runner` is failing for me using this branch when passing a second arg (the arg for the command that I'm trying to run with runner)

**Comment by guilleiguaran** [comment]
My bad, looks like this PR is fixing only the `rails server` command not the `rails runner` one

**Comment by kaspth** [comment]
@guilleiguaran correct. I'll handle the `runner` command not working with multiple args like it used to.

**Comment by y-yagi** [comment]
I was misunderstanding. Option parser is necessary even in the rack server. Therefore, I restored `Rails::Server::Options`.

File: railties/lib/rails/commands/server/server_command.rb [hunk 11]
```diff
@@ -140,21 +95,72 @@ def restart_command
...
+        def host
+          ENV.fetch("HOST", options[:binding])
+        end
+
+        def environment
+          options[:environment] || Rails::Command.environment
+        end
+
+        def restart_command
+          "bin/rails server #{ARGV.join(' ')}"
```
Comment (kaspth) [inline railties/lib/rails/commands/server/server_command.rb]: We need to be careful when mentioning `ARGV` in commands. I think this should be:

```ruby
"bin/rails server #{@server} #{args.join(" ")}"
```

(Note that it needs to use double quoted strings here too.)

File: railties/lib/rails/commands/server/server_command.rb [hunk 12]
```diff
@@ -140,21 +95,72 @@ def restart_command
...
+        Rails::Server.new(server_options).tap do |server|
           # Require application after server sets environment to propagate
           # the --environment option.
           require APP_PATH
           Dir.chdir(Rails.application.root)
           server.start
         end
       end
+
+      def server_options
```
Comment (kaspth) [inline railties/lib/rails/commands/server/server_command.rb]: In Thor any public instance method is a command, so we'd need to wrap this in a `no_commands do` block.

File: railties/lib/rails/commands/server/server_command.rb [hunk 13]
```diff
@@ -7,51 +7,14 @@
...
-          opts.on("-h", "--help", "Shows this help message.") { puts opts; exit }
-        end
+        Rails::Command::ServerCommand.new([], args).server_options
       end
     end
 
-    def initialize(*)
-      super
+    def initialize(options = nil)
+      @default_options = options.nil? ? {} : options
```
Comment (kaspth) [inline railties/lib/rails/commands/server/server_command.rb]: How about this? `@default_options = options || {}`

File: railties/lib/rails/commands/server/server_command.rb [hunk 14]
```diff
@@ -7,51 +7,14 @@
...
-        option_parser(options).parse! args
-
-        options[:log_stdout] = options[:daemonize].blank? && (options[:environment] || Rails.env) == "development"
-        options[:server]     = args.shift
-        options
-      end
-
-      def option_parser(options) # :nodoc:
-        OptionParser.new do |opts|
-          opts.banner = "Usage: rails server [puma, thin etc] [options]"
```
Comment (kaspth) [inline railties/lib/rails/commands/server/server_command.rb]: Can't we port over the server argument with this:

```ruby
argument :server, optional: true, banner: '[puma, thin etc]'
```

**Review by kaspth — COMMENTED** [review]
Think we're getting close ✌️

File: railties/lib/rails/commands/server/server_command.rb (hunk 14 above)
Comment (y-yagi) [inline railties/lib/rails/commands/server/server_command.rb]: If `argument` used, need to specify the "server" argument twice to specify server(e.g. `./bin/rails server server webrick`).  
Therefore, override `.banner` instead.

File: railties/lib/rails/commands/server/server_command.rb (hunk 11 above)
Comment (y-yagi) [inline railties/lib/rails/commands/server/server_command.rb]: In this context, the `args` variable does not contain any arguments. 
Therefore, kept the argument in the constructor and used it.

**Comment by y-yagi** [comment]
Thanks for reviewing! I updated commit!

**Comment by kaspth** [comment]
Way cool, thanks!

**Comment by y-yagi** [comment]
Thanks!!

**Comment by DougMaisells** [comment]
I am running Rails 5.1.1 and I get an error that looks like the same thing.  What am I missing?   
rails s –p 5000
/Users/douglas.maisells/.rvm/gems/ruby-2.3.1@chronus/gems/thor-0.19.4/lib/thor/base.rb:484:in `handle_argument_error': ERROR: "rails server" was called with arguments ["5000"] (Thor::InvocationError)
Usage: "rails server [puma, thin etc] [options]"
	from /Users/douglas.maisells/.rvm/gems/ruby-2.3.1@chronus/gems/thor-0.19.4/lib/thor/command.rb:34:in `rescue in run'
