### PR TITLE
Fix test flakyness due to `test_truncate_tables`

### LINKED ISSUE #35941: Two of PolymorphicFullStiClassNamesTest tests fail
Found these failures at https://buildkite.com/rails/rails/builds/60325#c0a7fa75-4232-4aea-8435-d821b1ea504b by #35838 I have opened this issue as I do not think these failures are related with #35838.

### Steps to reproduce

```ruby
$ cd activerecord
$ ARCONN=mysql2 bin/test test/cases/associations/nested_through_associations_test.rb test/cases/adapter_test.rb test/cases/associations/eager_load_includes_full_sti_class_test.rb -n "/^(?:NestedThroughAssociationsTest#(?:test_nested_has_many_through_with_conditions_on_through_associations_preload_via_joins)|ActiveRecord::AdapterTestWithoutTransaction#(?:test_truncate)|PolymorphicFullStiClassNamesTest#(?:test_class_names|test_class_names_with_find_by))$/" --seed 3195

```

### Expected behavior
It should pass.

### Actual behavior

```ruby
$ ARCONN=mysql2 bin/test test/cases/associations/nested_through_associations_test.rb test/cases/adapter_test.rb test/cases/associations/eager_load_includes_full_sti_class_test.rb -n "/^(?:NestedThroughAssociationsTest#(?:test_nested_has_many_through_with_conditions_on_through_associations_preload_via_joins)|ActiveRecord::AdapterTestWithoutTransaction#(?:test_truncate)|PolymorphicFullStiClassNamesTest#(?:test_class_names|test_class_names_with_find_by))$/" --seed 3195
Using mysql2
Run options: -n "/^(?:NestedThroughAssociationsTest#(?:test_nested_has_many_through_with_conditions_on_through_associations_preload_via_joins)|ActiveRecord::AdapterTestWithoutTransaction#(?:test_truncate)|PolymorphicFullStiClassNamesTest#(?:test_class_names|test_class_names_with_find_by))$/" --seed 3195

# Running:

..F

Failure:
PolymorphicFullStiClassNamesTest#test_class_names_with_find_by [/home/yahonda/git/rails/activerecord/test/cases/associations/eager_load_includes_full_sti_class_test.rb:65]:
Expected #<Tagging id: 1, tag_id: 1, super_tag_id: 2, taggable_type: "Post", taggable_id: 1, comment: nil, type: nil> to be nil.


bin/test test/cases/associations/eager_load_includes_full_sti_class_test.rb:61

F

Failure:
PolymorphicFullStiClassNamesTest#test_class_names [/home/yahonda/git/rails/activerecord/test/cases/associations/eager_load_includes_full_sti_class_test.rb:34]:
Expected #<Tagging id: 2, tag_id: 1, super_tag_id: nil, taggable_type: "Post", taggable_id: 2, comment: nil, type: nil> to be nil.


bin/test test/cases/associations/eager_load_includes_full_sti_class_test.rb:31



Finished in 0.808339s, 4.9484 runs/s, 9.8968 assertions/s.
4 runs, 8 assertions, 2 failures, 0 errors, 0 skips
$
``` 

### System configuration
**Rails version**: master branch

**Ruby version**: ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]

### PR DESCRIPTION
**Pull request by itsWill**
### Summary

Fixes: https://github.com/rails/rails/issues/35941

The order that caused the test two fail was if the tests ran in the following order:
1. `test_nested_has_many_through_with_conditions_on_through_associations_preload_via_joins` 
2. `test_truncate`
3. `eager_load_includes_full_sti_class_test` would run `test_class_names_with_find_by` and `test_class_names`

The first test uses `fixtures :taggings, :posts` this would insert a set of `Tagging` and `Post` records in the database. 

When `test_truncate` would run it would call `TRUNCATE TABLE posts` which also resets the `AUTOINCREMENT` value. The `Posts` would be deleted but the `Taggings` remained in the database. 

When the posts in `test_class_names_with_find_by` and `test_class_names_with_find_by` would have an ID that equal to the previous `Posts` deleted in the `truncate_tables` test, this would cause `post.tagging` to return the old taggins despite the fact that we expected them to be `nil`, causing the tests to fail. 

The approach I took to fix this, is to store the `Post` values before the `test_truncate_tables` and reset them once the test is done. 

### Other Information

A couple of other approaches I thought of: 
* running this within a transaction: wasn't possible because `TRUNCATE` is a DDL statment and causes an implicit commit inside a transaction.
* clearing the taggings before the running the tests in `eager_load_includes_full_sti_class_test` in the setup. I thought the current approach was simpler since we wouldn't have to run the `destroy_all` before ever test case. 

cc: @kamipo and @rafaelfranca

### CODE REVIEW

File: activerecord/test/cases/adapter_test.rb [hunk 1]
```diff
@@ -485,11 +485,17 @@ def setup
...
 
     def test_truncate
+      posts_attributes = Post.all.map(&:attributes)
+
       assert_operator Post.count, :>, 0
 
       @connection.truncate("posts")
 
       assert_equal 0, Post.count
+    ensure
```
Comment (gmcgibbon) [inline activerecord/test/cases/adapter_test.rb]: Would it make more sense to do this instead?

```
ActiveRecord::FixtureSet.reset_cache
ActiveRecord::FixtureSet.create_fixtures(FIXTURES_ROOT, "posts")
```

**Review by gmcgibbon — COMMENTED** [review]
There appears to be other tests that truncate tables in this test case. They should probably also re-insert fixtures of truncated tables.

File: activerecord/test/cases/adapter_test.rb (hunk 1 above)
Comment (itsWill) [reply activerecord/test/cases/adapter_test.rb]: seems like a good idea, and the way to extend for the other tests that truncate tables.

Comment (itsWill) [reply activerecord/test/cases/adapter_test.rb]: I've gone ahead and implemented the suggested approach on other tests as well, thanks!

**Review by gmcgibbon — APPROVED** [review]
👍

File: activerecord/test/cases/adapter_test.rb [hunk 2]
```diff
@@ -514,6 +517,8 @@ def test_truncate_tables
       assert_equal 0, Post.count
       assert_equal 0, Author.count
       assert_equal 0, AuthorAddress.count
+    ensure
+      reset_fixtures('posts', 'authors', 'author_addresses')
```
Comment (kamipo) [inline activerecord/test/cases/adapter_test.rb]: I'm not sure why codeclimate raises no offence, but we have `.rubocop.yml` and this violates the `Style/StringLiterals` cop. cc6bff3daa4da4d2c6935761d0ab059201f772e2

https://github.com/rails/rails/blob/cc6bff3daa4da4d2c6935761d0ab059201f772e2/.rubocop.yml#L165-L167

Comment (itsWill) [reply activerecord/test/cases/adapter_test.rb]: 🙇 thanks for following up and fixing that for me ❤️
