### PR TITLE
Fix uninitialized constant error on Puma boot

### LINKED ISSUE #49323: Puma fails to boot in production with default config due to missing `Concurrency` constant (Rails 7.1.0.beta1)
### Steps to reproduce

1. Generate an app using `rails new` with Rails 7.1.0.beta1
2. Run `RAILS_ENV=production bundle exec puma -C ./config/puma.rb`

### Expected behavior

Puma should start.

### Actual behavior

```
./config/puma.rb:16:in `block in _load_from': uninitialized constant Puma::DSL::Concurrent (NameError)
	from ./config/puma.rb:16:in `fetch'
	from ./config/puma.rb:16:in `_load_from'
```

The problem lies in the `config/puma.rb` file generated by `rails new`, specifically this statement that was added in #46838:

```ruby
ENV.fetch("WEB_CONCURRENCY") { Concurrent.physical_processor_count }
```

At the time Puma evals this statement, `Bundler.require` has not yet been run, and so the `concurrent-ruby` gem has not yet been loaded. That is why the `Concurrent` constant is not defined and we see an `uninitialized constant` error when Puma starts.

### Workaround

Set the `WEB_CONCURRENCY` env var or change the `ENV.fetch` statement `config/puma.rb` as follows:

```ruby
ENV.fetch("WEB_CONCURRENCY") do
  require "concurrent-ruby"
  Concurrent.physical_processor_count
end
```

### System configuration

**Rails version**: 7.1.0.beta1

**Ruby version**: 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]

### PR DESCRIPTION
**Pull request by mattbrictson**
### Motivation / Background

This Pull Request has been created to fix #49323: **Puma fails to boot in production with default config due to missing `Concurrency` constant (Rails 7.1.0.beta1)**

### Detail

Before, using the default `puma/config.rb` generated by `rails new`, Puma would fail to boot in production with this error:

```
./config/puma.rb:16:in `block in _load_from': uninitialized constant Puma::DSL::Concurrent (NameError)
	from ./config/puma.rb:16:in `fetch'
	from ./config/puma.rb:16:in `_load_from'
```

This was because `Concurrent.physical_processor_count` was being referenced before the `Concurrent` constant was initialized.

Fix by requiring `concurrent-ruby` just before the `Concurrent` constant is needed.

Fixes #49323

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] ~~Tests are added or updated if you fix a bug or add a feature.~~ The [original PR](https://github.com/rails/rails/pull/46838) that introduced `Concurrent.physical_processor_count` did not have any tests
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: railties/lib/rails/generators/rails/app/templates/config/puma.rb.tt [hunk 1]
```diff
@@ -13,7 +13,12 @@ threads min_threads_count, max_threads_count
 
 # Specifies that the worker count should equal the number of processors in production.
 if ENV["RAILS_ENV"] == "production"
-  worker_count = Integer(ENV.fetch("WEB_CONCURRENCY") { Concurrent.physical_processor_count })
+  worker_count = Integer(
+    ENV.fetch("WEB_CONCURRENCY") do
+      require "concurrent-ruby"
+      Concurrent.physical_processor_count
+    end
+  )
```
Comment (guilleiguaran) [inline railties/lib/rails/generators/rails/app/templates/config/puma.rb.tt:21]: I don't mind about just adding the require before of the line where it's used:

```suggestion
  require "concurrent-ruby"
  worker_count = Integer(ENV.fetch("WEB_CONCURRENCY") { Concurrent.physical_processor_count })
```

**Comment by mattbrictson** [comment]
@guilleiguaran I accepted your suggestion and squashed down to 1 commit.
