### PR TITLE
Fix parent record should not get saved with duplicate children records

### LINKED ISSUE #32940: Error does not bubble up from duplicate associated record
### Steps to reproduce

Models:
```ruby
class Parent < ApplicationRecord
  has_many :children
end

class Child < ApplicationRecord
  belongs_to :parent
  validates :name, uniqueness: true
end
```

Code:
```ruby
parent = Parent.new(children: [Child.new(name: 'Wiske'), Child.new(name: 'Wiske')])
parent.save
parent.errors.any?
```

[Executable test](https://gist.github.com/Mangara/a3b248c3123a8e496fe218c653fed005)

### Expected behavior
The children are invalid, so there should be an error on `parent`.

### Actual behavior
There is no error on `parent`, only on the second child:

```ruby
parent = Parent.new(children: [Child.new(name: 'Wiske'), Child.new(name: 'Wiske')])
parent.valid? # true
  # Child Exists (0.6ms)  SELECT  1 AS one FROM `children` WHERE `children`.`name` = BINARY 'Wiske' LIMIT 1
  # Child Exists (0.5ms)  SELECT  1 AS one FROM `children` WHERE `children`.`name` = BINARY 'Wiske' LIMIT 1
parent.save # true
  #  (0.6ms)  BEGIN
  # Child Exists (0.6ms)  SELECT  1 AS one FROM `children` WHERE `children`.`name` = BINARY 'Wiske' LIMIT 1
  # Child Exists (0.5ms)  SELECT  1 AS one FROM `children` WHERE `children`.`name` = BINARY 'Wiske' LIMIT 1
  # Parent Create (0.5ms)  INSERT INTO `parents` (`created_at`, `updated_at`) VALUES ('2018-05-20 19:14:06', '2018-05-20 19:14:06')
  # Child Exists (0.6ms)  SELECT  1 AS one FROM `children` WHERE `children`.`name` = BINARY 'Wiske' LIMIT 1
  # Child Create (7.2ms)  INSERT INTO `children` (`name`, `parent_id`) VALUES ('Wiske', 5)
  # Child Exists (0.6ms)  SELECT  1 AS one FROM `children` WHERE `children`.`name` = BINARY 'Wiske' LIMIT 1
  #  (2.8ms)  COMMIT
parent.errors.any? # false
parent.children # [#<Child id: 6, name: "Wiske", parent_id: 5>, #<Child id: nil, name: "Wiske", parent_id: 5>]
parent.children[1].errors.any? # true
parent.children[1].errors.full_messages # ["Name has already been taken"]
parent.valid? # false
  # Child Exists (0.7ms)  SELECT  1 AS one FROM `children` WHERE `children`.`name` = BINARY 'Wiske' LIMIT 1
parent.errors.any? # true
parent.errors.full_messages # ["Children is invalid"]
```

Since there are no uniqueness problems between each child individually and what's already in the database, validation of the parent passes. Each child is revalidated before being saved, so when the second child is saved, the duplication is detected and an error is added to the child model. However, this error does not propagate to the parent as typically happens with validation errors.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

(See also https://github.com/rails/rails/issues/32939)

### PR DESCRIPTION
**Pull request by mechanicles**
- Fixes #32940

### CODE REVIEW

**Comment by Mangara** [comment]
Thanks for taking a look at this so quickly! Could you verify that the fix also works with these test cases?

[many-to-many relation](https://gist.github.com/Mangara/1d58641bf538e608c5fbe308f48a8b6d)
[many-to-many :through](https://gist.github.com/Mangara/bc778db44281d0705992840414f57ab5)

**Comment by Mangara** [comment]
I'm not sure if it's worth creating new models for the test cases. Would something similar to the tests in PR https://github.com/rails/rails/pull/11851 work here?

**Comment by mechanicles** [comment]
Removed newly created models and used existing ones.

**Comment by mechanicles** [comment]
@eugeneius I have updated the code. Please check.

File: activerecord/lib/active_record/autosave_association.rb [hunk 1]
```diff
@@ -392,18 +392,22 @@ def save_collection_association(reflection)
...
-                elsif !reflection.nested?
-                  association_saved = association.insert_record(record)
-                  if reflection.validate?
-                    saved = association_saved
+                else
+                  if !reflection.nested?
+                    validate = reflection.options[:validate] != false
+                    if validate
+                      valid = association_valid?(reflection, record, index)
+                      saved = valid ? association.insert_record(record) : false
```
Comment (eugeneius) [inline activerecord/lib/active_record/autosave_association.rb]: Calling `association_valid?` on the line above validates the record:

https://github.com/rails/rails/blob/36390b6bdc75fca70e7a9d74c6270e3f40e77799/activerecord/lib/active_record/autosave_association.rb#L329

Calling `insert_record` also validates the record:

https://github.com/rails/rails/blob/36390b6bdc75fca70e7a9d74c6270e3f40e77799/activerecord/lib/active_record/associations/collection_association.rb#L376-L382

We should pass `false` as the second argument to `insert_record`, to avoid the unnecessary second validation.

File: activerecord/lib/active_record/autosave_association.rb [hunk 2]
```diff
@@ -392,18 +392,22 @@ def save_collection_association(reflection)
...
               if autosave != false && (@new_record_before_save || record.new_record?)
                 if autosave
                   saved = association.insert_record(record, false)
-                elsif !reflection.nested?
-                  association_saved = association.insert_record(record)
-                  if reflection.validate?
-                    saved = association_saved
+                else
+                  if !reflection.nested?
+                    validate = reflection.options[:validate] != false
```
Comment (eugeneius) [inline activerecord/lib/active_record/autosave_association.rb]: Is there any reason to switch from `reflection.validate?` to this?

File: activerecord/lib/active_record/autosave_association.rb [hunk 3]
```diff
@@ -392,18 +392,22 @@ def save_collection_association(reflection)
...
-
               if autosave != false && (@new_record_before_save || record.new_record?)
                 if autosave
                   saved = association.insert_record(record, false)
-                elsif !reflection.nested?
-                  association_saved = association.insert_record(record)
-                  if reflection.validate?
-                    saved = association_saved
+                else
+                  if !reflection.nested?
```
Comment (eugeneius) [inline activerecord/lib/active_record/autosave_association.rb]: This was fine as an `elsif`, no need to change it.

File: activerecord/lib/active_record/autosave_association.rb [hunk 4]
```diff
@@ -392,18 +392,22 @@ def save_collection_association(reflection)
               records -= records_to_destroy
             end
 
-            records.each do |record|
+            records.each_with_index do |record, index|
               next if record.destroyed?
 
               saved = true
-
```
Comment (eugeneius) [inline activerecord/lib/active_record/autosave_association.rb]: There's no need to remove this line ✂️

File: activerecord/CHANGELOG.md [hunk 5]
```diff
@@ -1,3 +1,9 @@
+*   Fix parent record should not get saved with duplicate children records
+
+    Fixes #32940 & #32939
```
Comment (eugeneius) [inline activerecord/CHANGELOG.md]: https://github.com/rails/rails/issues/32939 was already fixed by https://github.com/rails/rails/pull/32796.

**Comment by mechanicles** [comment]
@eugeneius I have updated the code. Now I have passed the second argument `false` to `insert_method`. Please check and let me know if I missed something.

**Review by kamipo — APPROVED** [review]

**Comment by jasonperrone** [comment]
I have a question about this code. Am I seeing it right that insert_record is called with validate=false if reflection.validate? is true, and called with validate=true if reflection.validate? is false?
