### PR TITLE
Fix regression, enforce fresh ETag header after collection contents change

### LINKED ISSUE #38078: cache_key for AR relations is broken for usage in ConditionalGet API
### Steps to reproduce

Lets get some relation and check `cache_key` for it:

```ruby
2.6.3 :001 > ActiveRecord::Base.collection_cache_versioning
 => true
2.6.3 :002 > user = User.first
  User Load (1.0ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
 => #<User id: >
2.6.3 :003 > user.cors_domains.ordered.count
   (1.5ms)  SELECT COUNT(*) FROM "cors_domains" WHERE "cors_domains"."user_id" = $1  [["user_id", 1]]
 => 3
2.6.3 :004 > user.cors_domains.ordered.maximum(:updated_at)
   (0.7ms)  SELECT MAX("cors_domains"."updated_at") FROM "cors_domains" WHERE "cors_domains"."user_id" = $1  [["user_id", 1]]
 => 2019-12-23 11:58:23 UTC
2.6.3 :005 > user.cors_domains.ordered.cache_key
   (0.8ms)  SELECT COUNT(*) AS "size", MAX("cors_domains"."updated_at") AS timestamp FROM "cors_domains" WHERE "cors_domains"."user_id" = $1  [["user_id", 1]]
 => "cors_domains/query-199f662dcd4578830fd25ee2ac98eef5"
```

Looks good. Now lets remove one record from `cors_domains` table and check `cache_key` again:

```ruby
2.6.3 :007 > user.cors_domains.ordered.count
   (0.7ms)  SELECT COUNT(*) FROM "cors_domains" WHERE "cors_domains"."user_id" = $1  [["user_id", 1]]
 => 2
2.6.3 :008 > user.cors_domains.ordered.maximum(:updated_at)
   (0.7ms)  SELECT MAX("cors_domains"."updated_at") FROM "cors_domains" WHERE "cors_domains"."user_id" = $1  [["user_id", 1]]
 => 2019-12-23 11:58:23 UTC
2.6.3 :009 > user.cors_domains.ordered.cache_key
   (0.7ms)  SELECT COUNT(*) AS "size", MAX("cors_domains"."updated_at") AS timestamp FROM "cors_domains" WHERE "cors_domains"."user_id" = $1  [["user_id", 1]]
 => "cors_domains/query-199f662dcd4578830fd25ee2ac98eef5"
```

As we can see, in results we have the same value **"cors_domains/query-199f662dcd4578830fd25ee2ac98eef5"**, which is incorrect and influence on https://api.rubyonrails.org/classes/ActionController/ConditionalGet.html methods. 

Like this example will not work correctly:

```ruby
def index
  @articles = Article.all
  fresh_when(@articles)
end
```

Because `ActiveSupport::Cache.expand_cache_key(Article.all)` will be the same all the time. You can rewrite in this way, so it will work correctly (but it is not effective):

```ruby
def index
  @articles = Article.all
  fresh_when(etag: @articles.to_a, last_modified: @articles.maximum(:updated_at))
end
```

### Expected behavior

https://github.com/rails/rails/blob/v6.0.2.1/activerecord/lib/active_record/relation.rb#L316 should calculate `cache_key` based on `COUNT(*) AS "size", MAX("cors_domains"."updated_at")`, but it ignore this information.

### Actual behavior

https://github.com/rails/rails/blob/v6.0.2.1/activerecord/lib/active_record/relation.rb#L316 instead it just calculating hexdigest based on query text:

```
    def compute_cache_key(timestamp_column = :updated_at) # :nodoc:
      query_signature = ActiveSupport::Digest.hexdigest(to_sql)
      key = "#{klass.model_name.cache_key}/query-#{query_signature}"

      if cache_version(timestamp_column)
        key
      else
        "#{key}-#{compute_cache_version(timestamp_column)}"
      end
    end
```

Also `cache_version(timestamp_column)` not used for key, only in condition check. This lead, that:

```ruby
[4] pry(#<CorsDomain::ActiveRecord_AssociationRelation>)> to_sql
=> "SELECT \"cors_domains\".* FROM \"cors_domains\" WHERE \"cors_domains\".\"user_id\" = 1 ORDER BY \"cors_domains\".\"id\" ASC"
[5] pry(#<CorsDomain::ActiveRecord_AssociationRelation>)> ActiveSupport::Digest.hexdigest(to_sql)
=> "199f662dcd4578830fd25ee2ac98eef5"
[6] pry(#<CorsDomain::ActiveRecord_AssociationRelation>)> ActiveSupport::Digest.hexdigest(to_sql)
=> "199f662dcd4578830fd25ee2ac98eef5"
```

The same `cache_key`, even if relation have different records.

### System configuration
**Rails version**: 6.0.1
**Ruby version**: 2.6.3p62

### PR DESCRIPTION
**Pull request by alipman88**
Add `ActiveRecord::Relation#cache_key_with_version`. This method will be used by ActionController::ConditionalGet to ensure that when collection cache versioning is enabled, requests using ConditionalGet don't return the same ETag header after a collection is modified.

Prior to the introduction of collection cache versioning in 4f2ac80d4cdb01c4d3c1765637bed76cc91c1e35, `ActiveRecord::Relation#cache_key` was suitable for the purposes of ConditionalGet as all cache keys included a version. However, with collection cache versioning enabled, keys remain constant. In turn, ETag headers remain constant, rendering them ineffective.

This commit takes the `cache_key_with_version` logic used for individual Active Record objects (from aa8749eb52d7919a438940c9218cad98d892f9ad), abstracts it into a module, and applies it to both individual Active Record objects and collections.

Fixes #38078

### CODE REVIEW

**Comment by alipman88** [comment]
Note that this commit adds a couple integration tests to `actionpack/test/controller/api/conditional_get_test.rb`. Adding these tests feels prudent, as they would have prevented the regression introduced in 4f2ac80d4cdb01c4d3c1765637bed76cc91c1e35. However, as a relatively new Rails contributor, I'm not exactly certain where tests that involve multiple components should live within the Rails test suite.

If my test infringes on any Rails conventions, any feedback on how to better meet said conventions is appreciated!

**Comment by le0pard** [comment]
Thanks @alipman88 

https://github.com/rails/rails/issues/38078#issuecomment-568910198

Should you add fix for collection `cache_key` in this PR or it should be separate? As you remember, AR relation `cache_key` (with `ActiveRecord::Base.collection_cache_versioning = true`) still doing SQL for `cache_version`, which is not used for generation of a key.

**Comment by alipman88** [comment]
I submitted the PR eliminating the unnecessary query separately - #38099.

File: actionpack/test/controller/api/conditional_get_test.rb [hunk 1]
```diff
@@ -3,6 +3,10 @@
 require "abstract_unit"
 require "active_support/core_ext/integer/time"
 require "active_support/core_ext/numeric/time"
+require "active_record"
```
Comment (rafaelfranca) [inline actionpack/test/controller/api/conditional_get_test.rb]: Action Pack tests can't depend on Active Record. If you really need to test this behavior in a controller you will need to write a test in the railtie folder.

File: activerecord/lib/active_record/cache_key_with_version.rb [hunk 2]
```diff
@@ -0,0 +1,14 @@
+# frozen_string_literal: true
+
+module ActiveRecord
+  module CacheKeyWithVersion
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/cache_key_with_version.rb]: I prefer to copy this method to relation than adding a new module just for this method.

File: activerecord/CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,9 @@
+*   Enforce fresh ETag header after a collection's contents change by adding
+    ActiveRecord::Relation#cache_key_with_version. This method will be used by
+    ActionController::ConditionalGet to ensure that when collection cache versioning
+    is enabled, requests using ConditionalGet don't return the same ETag header
+    after a collection is modified. Fixes #38078. *Aaron Lipman*
```
Comment (rafaelfranca) [inline activerecord/CHANGELOG.md]: You name needs to be in a different line

**Review by rafaelfranca — CHANGES_REQUESTED** [review]

File: activerecord/CHANGELOG.md (hunk 3 above)
Comment (alipman88) [reply activerecord/CHANGELOG.md]: Rebased accordingly - but the Rails guide seems to indicate that a single paragraph is appropriate:

> Your name can be added directly after the last word if there are no code examples or multiple paragraphs. Otherwise, it's best to make a new paragraph.

https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#updating-the-changelog

File: activerecord/lib/active_record/cache_key_with_version.rb (hunk 2 above)
Comment (alipman88) [reply activerecord/lib/active_record/cache_key_with_version.rb]: Reasonable, rebased accordingly.

File: actionpack/test/controller/api/conditional_get_test.rb (hunk 1 above)
Comment (alipman88) [reply actionpack/test/controller/api/conditional_get_test.rb]: Thanks for the clarification. I've removed the Action Pack tests. (I'm ambivalent on whether there really needs to be a test for this. Now that `cache_key` and `cache_version` have been split into separate methods, I expect this interface will remain stable.)
