### PR TITLE
Fix retrieving PostgreSQL indexes with keyword-named columns

### LINKED ISSUE #54057: Postgresql issue retrieving index column for `position` column
Related to https://github.com/rails/rails/pull/45381/files#r1897211411

cc @fatkodima 

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  gem "rails", github: "rails/rails", branch: "main"

  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "ar_enum_test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :organizations, force: true do |t|
    t.integer :position, null: false
    t.string :internal_name, null: false
    t.timestamps
  end
  add_index :organizations, %i[internal_name position], unique: true
end

class Organization < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_enum_stuff
    expected_index_columns = Organization.connection.indexes('organizations').first.columns

    assert_equal ['internal_name', 'position'], expected_index_columns
  end
end

```

### Expected behavior
the columns of a composite index containing the word `position` should not have extra quotes

### Actual behavior
image

### System configuration
**Rails version**: main ( SHA `d8a3011ce12c8c3c43ba3968e3b867ca06eea9ba` )

**Ruby version**: `3.4.1`

psql (PostgreSQL) 16.4 (Homebrew)

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #54057.
Closes #54058.

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb [hunk 1]
```diff
@@ -112,7 +112,7 @@ def indexes(table_name) # :nodoc:
             inddef = row[3]
             comment = row[4]
             valid = row[5]
-            columns = decode_string_array(row[6])
+            columns = decode_string_array(row[6]).map { |c| Utils.unquote_identifier(c.strip.gsub('""', '"')) }
```
Comment (chaadow) [inline activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb:115]: what do you think of moving the map inside `decode_string_array` or should this be used only in this context?

Comment (fatkodima) [reply activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb:115]: it is possible foreign keys have the same problem, if yes, then probably a good idea. Will take a look
