### PR TITLE
Fix #41661 attaching multiple times within transaction

### LINKED ISSUE #41661: Multiple attachment files are not persisted to storage service when attached separately within a transaction
Hello!

I've encountered an issue with multiple ActiveStorage attachments that occurs when calling `#attach` more than once on the same model within a transaction.

Specifically, the `ActiveStorage::Attachment` objects are all created as expected, however all attachments except the last silently fail to be persisted to the storage service. Attempting to access these files (e.g., by calling `#download`) throws `ActiveStorage::FileNotFoundError`.

This issue does not appear to occur when attaching multiple attachments in a single call to `#attach` within a transaction, nor does it occur with multiple calls to `#attach` that are not wrapped in a transaction.

I found a similar recent (but closed) bug related to ActiveStorage attachments and transactions which could be related: https://github.com/rails/rails/issues/40630

Thanks!

### Steps to reproduce

[This gist](https://gist.github.com/reshleman/25edc7854e9d8a262e6fff9e5a8f26ab) contains a reproduction script with a failing test case (along with 3 passing test cases which do not meet all the conditions to trigger the issue).

### Expected behavior

Multiple calls to `#attach` inside a transaction persist all attached files to the storage service.

### Actual behavior

Multiple calls to `#attach` inside a transaction creates `ActiveStorage::Attachment` objects, but only the last attached file is persisted to the storage service.

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 2.6.5p114

### PR DESCRIPTION
**Pull request by santib**
### Summary

Fix #41661 . Similar to https://github.com/rails/rails/commit/836eb915b14f01eca8a5ea655e4f30b6a8a7ce38 when attaching multiple times within a transaction we need to check for `change&.attachables` instead of just `blobs`.

In the test I created a blob outside the transaction on purpose to make sure it won't get deleted because of the code change

### CODE REVIEW

**Comment by santib** [comment]
ugh I just realized there was https://github.com/rails/rails/pull/42178 already open 😅

**Comment by zzak** [comment]
@santib Do your tests apply to the other PR too? I think that they are not covered 🤔

**Comment by santib** [comment]
> @santib Do your tests apply to the other PR too? I think that they are not covered 🤔

I think my tests are mostly the same as https://github.com/rails/rails/pull/42178/files#diff-3bd9077ea52e958612487234f70cabcab87e1014266ec902c1402b8452a736b4R94-R102 the difference being that I added an existing attachment before the transaction just to make sure my changes weren't going to remove it by mistake

**Comment by zzak** [comment]
@santib Since that PR was open first, would you mind offering your suggestion over there? I think it's easier to review a single PR -- but if not we can also open a PR after that one is merged to make it better ;)

**Comment by santib** [comment]
> @santib Since that PR was open first, would you mind offering your suggestion over there? I think it's easier to review a single PR -- but if not we can also open a PR after that one is merged to make it better ;)

Hey @zzak I just left my concerns in the other PR. I'm ok however you proceed 👍

**Comment by zzak** [comment]
I think we are OK to move forward with this PR, based on this thread: https://github.com/rails/rails/pull/42178#issuecomment-850008022

/cc #41661, #41903, #40630

**Review by lfalcao — APPROVED** [review]

File: activestorage/lib/active_storage/attached/many.rb [hunk 1]
```diff
@@ -29,7 +29,7 @@ def blobs
     #   document.images.attach([ first_blob, second_blob ])
     def attach(*attachables)
       if record.persisted? && !record.changed?
-        record.public_send("#{name}=", blobs + attachables.flatten)
+        record.public_send("#{name}=", (change&.attachables || blobs) + attachables.flatten)
```
Comment (pixeltrix) [inline activestorage/lib/active_storage/attached/many.rb:32]: This is the same code block as in the `else` clause - can we DRY this up, thanks :+1:

**Review by pixeltrix — CHANGES_REQUESTED** [review]

**Comment by pixeltrix** [comment]
@santib can you check this change against the reproduction script in #42343 - it still seems to fail for me afterwards.

**Comment by pixeltrix** [comment]
> @santib can you check this change against the reproduction script in #42343 - it still seems to fail for me afterwards.

Seems like the failures I'm getting are related to the `replace_on_assign_to_many` configuration option. There was some discussion about deprecating this in 6.1 but doesn't appear to have been done so too late to do it now. Need to make sure that the code in question works in both scenarios. Also this seems a very expensive way to do things - it will generate 12 insertions for 3 attachments (2 for the first `attach`, 4 for the second `attach` and 6 for the final `attach`). I think the change in 836eb91 worked okay because it wasn't doing `save` so was only ever working on in-memory objects.

**Comment by santib** [comment]
> > @santib can you check this change against the reproduction script in #42343 - it still seems to fail for me afterwards.
> 
> Seems like the failures I'm getting are related to the `replace_on_assign_to_many` configuration option. There was some discussion about deprecating this in 6.1 but doesn't appear to have been done so too late to do it now. Need to make sure that the code in question works in both scenarios. Also this seems a very expensive way to do things - it will generate 12 insertions for 3 attachments (2 for the first `attach`, 4 for the second `attach` and 6 for the final `attach`). I think the change in [836eb91](https://github.com/rails/rails/commit/836eb915b14f01eca8a5ea655e4f30b6a8a7ce38) worked okay because it wasn't doing `save` so was only ever working on in-memory objects.

Good catch 💯 I'll try to think on alternative solutions as soon as I have some time, but if you already have the solution in mind then please go ahead.

Attaching here how logs looks with the current implementation for a test attaching 3 files within a transaction:
image

I see:
- 6 Blob creations => are 3 of them being left stale?
- 6 Attachment create + 3 Attachment delete => Amounts look good, but this doesn't seem performant as Andrew pointed out.

**Comment by pixeltrix** [comment]
If you set `replace_on_assign_to_many` to false, then the following code:

``` ruby
    User.transaction do
      3.times do |i|
        user.documents.attach(
          content_type: "text/plain",
          io: ::StringIO.new("doc-#{i}"),
          filename: "doc-#{i}.txt"
        )
      end
    end
```

ends up with 6 blobs and 1 hash in attachables when the `after_commit` hook runs 😭 

> if you already have the solution in mind then please go ahead

I have nothing at this time 😬

**Comment by pixeltrix** [comment]
Yeah, so it appears `attach` is very broken - doing the following:

``` ruby
user.documents.attach(user.documents.blobs)
```

will end up trying to double the number of attachments because of `blobs + attachables.flatten`.

The `attach` method isn't meant to replace the whole set of attachments, so it seems that going through the setter method isn't the right way to implement this. Also the `attachment_change` instance variable  with a hash feels quite brittle and I wonder whether a changeset of service operations that lives on the proxy object would be better. 🤔

**Comment by santib** [comment]
> Yeah, so it appears `attach` is very broken - doing the following:
> 
> ```ruby
> user.documents.attach(user.documents.blobs)
> ```
> 
> will end up trying to double the number of attachments because of `blobs + attachables.flatten`.
> 
> The `attach` method isn't meant to replace the whole set of attachments, so it seems that going through the setter method isn't the right way to implement this. Also the `attachment_change` instance variable with a hash feels quite brittle and I wonder whether a changeset of service operations that lives on the proxy object would be better. 🤔

An update. We have been working on this with @brunvez and @jeroig. In the `attach` method instead of calling the setter we are using `ActiveStorage::Attached::Changes::CreateMany` directly. It's still a WIP but then what we are doing is having in the `ActiveStorage::Attached::Changes::CreateMany` object the accumulation of the files that need to be uploaded until the `after_commit` hook takes place. The rest of the code is not affected.

**Comment by brunvez** [comment]
@pixeltrix we've updated the PR with the solution @santib mentioned. We're now basically accumulating attachables that were not previously uploaded as the last optional parameter in `CreateMany`. This allows us to have all changes in the `after_commit` where the files are actually uploaded which we were previously missing since they were being overridden by the setter.

We decided against changing the current hash implementation in favor of a proxy object since that'd have added too much complexity to this PR but it's definitely a good idea for a following one.

Please take a look and let us know what you think! 😄

**Comment by jorgemanrubia** [comment]
Hey @santib thanks for working on this one, and I'm sorry it got closed automatically. I'm going to reopen and review. We'll get this merged!

File: activestorage/lib/active_storage/attached/many.rb [hunk 2]
```diff
@@ -28,12 +28,14 @@ def blobs
...
-      if record.persisted? && !record.changed?
-        record.public_send("#{name}=", blobs + attachables.flatten)
-        record.save
-      else
-        record.public_send("#{name}=", (change&.attachables || blobs) + attachables.flatten)
+      if Array(attachables).any?
+        record.attachment_changes[name] = ActiveStorage::Attached::Changes::CreateMany.new(name,
+                                                                                           record,
+                                                                                           blobs + attachables.flatten,
+                                                                                           pending_upload: change&.try(:pending_upload))
```
Comment (jorgemanrubia) [inline activestorage/lib/active_storage/attached/many.rb:35]: I think this logic of passing the pending uploads to the change object would be in the attribute setter definition in `ActiveStorage::Attached::Model::Model#has_many_attached`:

https://github.com/rails/rails/blob/4f191b975431dbf8071d73a48505e27b19c283e6/activestorage/lib/active_storage/attached/model.rb#L147

That way, we keep the concern of instantiating `ActiveStorage::Attached::Changes::CreateMany` in a single place. Also we could lean on the same `#{name}=` method here.

File: activestorage/lib/active_storage/attached/changes/create_many.rb [hunk 3]
```diff
@@ -29,7 +29,9 @@ def save
 
     private
       def subchanges
-        @subchanges ||= attachables.collect { |attachable| build_subchange_from(attachable) }
+        @subchanges ||= attachables.collect { |attachable| build_subchange_from(attachable) }.tap do |subchanges|
+          @pending_upload += subchanges.reject { |subchange| subchange.attachable.is_a?(ActiveStorage::Blob) }
```
Comment (jorgemanrubia) [inline activestorage/lib/active_storage/attached/changes/create_many.rb:33]: It's a bit implicit that invoking `#subchanges` will accumulate the pending uploads. Maybe we can do this explicitly in the constructor:

```ruby

def initialize
...
  @pending_upload += subchanges_without_blobs
...
end

private
  ...
  def subchanges_without_blobs
    subchanges.reject { |subchange| subchange.attachable.is_a?(ActiveStorage::Blob) }
  end
```

File: activestorage/lib/active_storage/attached/changes/create_many.rb [hunk 4]
```diff
@@ -2,10 +2,10 @@
 
 module ActiveStorage
   class Attached::Changes::CreateMany #:nodoc:
-    attr_reader :name, :record, :attachables
+    attr_reader :name, :record, :attachables, :pending_upload
```
Comment (jorgemanrubia) [inline activestorage/lib/active_storage/attached/changes/create_many.rb:5]: Maybe rename to plural `pending_uploads` to indicate it's a list of objects?

File: activestorage/lib/active_storage/attached/many.rb [hunk 5]
```diff
@@ -28,12 +28,14 @@ def blobs
     #   document.images.attach(io: File.open("/path/to/racecar.jpg"), filename: "racecar.jpg", content_type: "image/jpeg")
     #   document.images.attach([ first_blob, second_blob ])
     def attach(*attachables)
-      if record.persisted? && !record.changed?
-        record.public_send("#{name}=", blobs + attachables.flatten)
-        record.save
-      else
-        record.public_send("#{name}=", (change&.attachables || blobs) + attachables.flatten)
+      if Array(attachables).any?
+        record.attachment_changes[name] = ActiveStorage::Attached::Changes::CreateMany.new(name,
```
Comment (jorgemanrubia) [inline activestorage/lib/active_storage/attached/many.rb:32]: Format: I'd try to remove the long tabulation before each argument. I [think this format](https://github.com/rails/rails/blob/40d63cee31a99e57c05d86cab12507b535af135f/actionmailbox/test/unit/mail_ext/addresses_test.rb#L8-L13) is more idiomatic in the Rails codebase. Maybe one single line would do it here, I think the line can be shortened if you move it to the place suggested in my other comment.

**Review by jorgemanrubia — COMMENTED** [review]
Thanks for working on this @santib. I spent some good time looking into this one and it's a tricky one. I like your solution here. 

I left some comments. Also, could you please rebase with `main`, solve conflicts and add a CHANGELOG entry for Active Storage 🙏?

I'll make sure this gets merged this time.

**Comment by santib** [comment]
> Hey @santib thanks for working on this one, and I'm sorry it got closed automatically. I'm going to reopen and review. We'll get this merged!

Thanks Jorge, I appreciate it 🙌  I'll take a look later today and address the review comments

**Comment by santib** [comment]
@jorgemanrubia Done! Let me know if you have any other comments. Thanks for your time in such an old PR 😄

**Comment by jorgemanrubia** [comment]
Wonderful @santib, thanks for addressing the feedback and for the prompt response 🙏.

One last request I forgot in my initial review: could you please add some assertions in the tests to make sure it's not creating more attachments or blobs than necessary. When playing with the code and [checking previous comments](https://github.com/rails/rails/pull/42300#issuecomment-852282843) this looks like an unwanted side-effect it's worth testing against. For example:

```ruby
  assert_difference -> { ActiveStorage::Blob.count }, +2 do
    ....
  end

  assert_equal 2, @user.highlights.count
```

**Comment by santib** [comment]
Thanks for the heads up @jorgemanrubia, you made me realize we forgot to test with `replace_on_assign_to_many = false` so I also added a fix and some more tests for that too 😌 

Fortunately, that config is going to be removed on 7.1, it's hard to remember all the configs that can affect things 😅

File: activestorage/lib/active_storage/attached/model.rb [hunk 6]
```diff
@@ -144,7 +144,7 @@ def #{name}=(attachables)
                 if attachables.none?
                   ActiveStorage::Attached::Changes::DeleteMany.new("#{name}", self)
                 else
-                  ActiveStorage::Attached::Changes::CreateMany.new("#{name}", self, attachables)
+                  ActiveStorage::Attached::Changes::CreateMany.new("#{name}", self, attachables, pending_uploads: attachment_changes["#{name}"].try(:pending_uploads))
```
Comment (jorgemanrubia) [inline activestorage/lib/active_storage/attached/model.rb:147]: Hey @santib I think we can extract a variable here outside of the `if` to remove the duplication:

```ruby
pending_uploads = attachment_changes["#{name}"].try(:pending_uploads)
```

Then you can reuse it in both invocations: `... pending_uploads: pending_uploads`.

With that in place I'll get this merged I promise 😊. Thanks a lot for your work here!

**Review by jorgemanrubia — CHANGES_REQUESTED** [review]

File: activestorage/lib/active_storage/attached/model.rb (hunk 6 above)
Comment (santib) [reply activestorage/lib/active_storage/attached/model.rb]: of course! no worries 😄

Comment (jorgemanrubia) [reply activestorage/lib/active_storage/attached/model.rb]: Great thanks. Cc @Jeremy to merge

**Review by jeremy — APPROVED** [review]
