### PR TITLE
Don't add `RAILS_ENV` in generate action

### LINKED ISSUE #34979: Unexpected argument passed to generator
### Steps to reproduce

I believe this change: https://github.com/rails/rails/commit/f173ec77fc35ce57e94398310308e868689366bb#diff-5036eb99239f9418c0458f2a2ec4f496R228
introduced a regression whereby `RAILS_ENV=test` is added as an argument to the generator.  This is only apparent if the generator uses arguments.  One generator that does so is the `devise` generator. See https://github.com/plataformatec/devise/issues/5007

### Expected behavior

It should not pass RAILS_ENV as an argument to the generator

### Actual behavior

it is passing RAILS_ENV as an agrument

### System configuration
**Rails version**: 6.0.0.beta1

**Ruby version**: 2.6.0

### PR DESCRIPTION
**Pull request by y-yagi**
In the case of generator, `RAILS_ENV` is interpreted as an argument as it　is. Avoid this because it will result unintended by the user.

Fixes #34979.

---

By the way, I think that this is a problem that does not occur if env is specified before the command. 
I did not understand why env was last specified(it seems that was due to the first commit d57b19380eaad8bda63743107f085e72935343b9), so this time I leave it as it is.

### CODE REVIEW

File: railties/lib/rails/generators/actions.rb [hunk 1]
```diff
@@ -284,14 +285,15 @@ def log(*args) # :doc:
...
+          env = options[:env] || ENV["RAILS_ENV"] || "development"
+          rails_env = " RAILS_ENV=#{env}" unless options[:without_rails_env]
           sudo = options[:sudo] && !Gem.win_platform? ? "sudo " : ""
           config = { verbose: false }
 
           config[:capture] = options[:capture] if options[:capture]
           config[:abort_on_failure] = options[:abort_on_failure] if options[:abort_on_failure]
 
-          in_root { run("#{sudo}#{extify(executor)} #{command} RAILS_ENV=#{env}", config) }
+          in_root { run("#{sudo}#{extify(executor)} #{command}#{rails_env}", config) }
```
Comment (kaspth) [inline railties/lib/rails/generators/actions.rb]: Could we fix this by prefixing the command with the Rails environment? Seems off that the environment handling leaks into the generate method.

Comment (kaspth) [reply railties/lib/rails/generators/actions.rb]: Wait, so if I run a rake task and set an env variable at the end it’s actually not bash that makes it available in ENV, but Rake? I did not know that!

Comment (deivid-rodriguez) [reply railties/lib/rails/generators/actions.rb]: Yeah, the shell assumes nothing about program's arguments, no matter whether they include an equal sign :smiley: 

```shell
$ touch a.txt; cat a.txt RAILS_ENV=production
cat: 'RAILS_ENV=production': No existe el archivo o el directorio
```

Comment (y-yagi) [reply railties/lib/rails/generators/actions.rb]: @deivid-rodriguez 
Thanks for your useful information. I was wondering if this feature works on Windows. By doing this, I think that rake was working as expected on Windows.  

@kaspth 
In my understanding, the same fix as rake is necessary for rails command. On unix, there is no problem if you specify the environment variable before the command, but on Windows it is aware that rake and rails are necessary to provide equivalent functionality. What do you think?

Comment (deivid-rodriguez) [reply railties/lib/rails/generators/actions.rb]: @y-yagi That's a very good point :+1:.

Another idea would be to add support for passing env to [thor's run method](https://github.com/erikhuda/thor/blob/master/lib/thor/actions.rb#L245-L268). [`system`](https://ruby-doc.org/core-2.6/Kernel.html#method-i-system) already supports passing an env to it, and backticks would need to be replaced with [`Open3.capture2e`](https://ruby-doc.org/stdlib-2.5.3/libdoc/open3/rdoc/Open3.html#method-c-capture2e) or something similar.

Comment (matthewd) [reply railties/lib/rails/generators/actions.rb]: I suspect that `rails` might need to learn to recognise such env-like parameters, at least while we're transitioning subcommands from rake to thor, even if we mark them as deprecated along the way. (I'm a little surprised we haven't hit this yet, but imagine it'll be more noticeable as we cover more commands, that are run in more varied circumstances.)

As implied by the mention of deprecation, though, I'd prefer we didn't use that as our internal mechanism. 

While I always prefer a many-args strategy for running subcommands, including passing env "properly", I'm not sure it'd work reliably here: I don't recall _when_ it comes into play, but that `#{sudo}` looks ominous. 

All of that said, though, if we know we're running a `rails` subcommand, might it be worth considering invoking `Rails::Command`-type stuff directly?

Comment (y-yagi) [reply railties/lib/rails/generators/actions.rb]: Thanks, I think your concern is correct. 

Originally, `generate` action did not recognize `env` (document has no explanation). And since I can not think of a use case that needs to specify `env` when executing generator, I think there is no need to support that.
Since processing to eliminate `RAILS_ENV` is necessary, I will merge this PR first, especially if there is no objection. 

I would like to consider separately about the behavior when `rails` action is executed.
