### PR TITLE
[#55866] Fix SQLite3 data loss during table alterations with CASCADE foreign keys.

### LINKED ISSUE #55866: Migrations that alter SQLite table structure can cause data loss
[A mere add_foreign_key can wipe out your whole Rails+SQLite production table](https://kyrylo.org/software/2025/09/27/a-mere-add-foreign-key-can-wipe-out-your-whole-rails-sqlite-production-table.html)

We likely should be disabling and re-enabling the `foreign_keys` PRAGMA before/after the transaction to change the table per the [sqlite docs](https://www.sqlite.org/lang_altertable.html#otheralter).

Edit: actually it looks like we already do that since https://github.com/rails/rails/commit/45881b0a64b4039e3b0d27e2c4d959dc2d744b9d

Edit2: Ah, this is complex. We currently do

```
transaction do
  disable_referential_integrity do
```

but it should be

```
disable_pragma_foreign_keys do
  transaction do
    enable_defer_foreign_keys do
```

because `PRAGMA foreign_keys`

> is a no-op within a transaction; foreign key constraint enforcement may only be enabled or disabled when there is no pending [BEGIN](https://www.sqlite.org/lang_transaction.html) or [SAVEPOINT](https://www.sqlite.org/lang_savepoint.html).

per [doc](https://www.sqlite.org/pragma.html#pragma_foreign_keys), and "`PRAGMA foreign_keys` before `TRANSACTION`" is the order recommended in the first sqlite doc link above. However, `PRAGMA defer_foreign_keys` is [set _per transaction_](https://www.sqlite.org/pragma.html#pragma_defer_foreign_keys) so it has to be inside the transaction block.

### PR DESCRIPTION
**Pull request by ruyrocha**
### Motivation / Background

This Pull Request has been created because #55866.

### Detail

Fix SQLite3 data loss during table alterations with CASCADE foreign keys

When altering a table in SQLite3 that is referenced by child tables with `ON DELETE CASCADE` foreign keys, ActiveRecord would silently delete all data from the child tables. This occurred because SQLite requires table recreation for schema changes, and during this process:

1. The original table is temporarily dropped
2. CASCADE deletes fire immediately on child tables
3. The table is recreated, but child data is already gone

This issue could result in catastrophic production data loss when adding columns, renaming tables, or adding foreign keys to tables that are referenced by other tables with CASCADE constraints.

The fix simply reverses the order to follow the [official SQLite 12-step ALTER TABLE procedure](https://www.sqlite.org/lang_altertable.html#otheralter).

This Pull Request fixes #55866.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb [hunk 1]
```diff
@@ -639,11 +639,28 @@ def alter_table(
...
+
+            if fk_enabled
+              violations = execute("PRAGMA foreign_key_check").to_a
+              if violations.any?
+                raise ActiveRecord::StatementInvalid,
+                      "Foreign key violations detected after schema change: #{violations.inspect}"
+              end
+            end
+          rescue => _
+            execute("PRAGMA foreign_keys = ON") if fk_enabled
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb]: Would not this execute `execute("PRAGMA foreign_keys = ON")` again if there is any violation?

File: activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb [hunk 2]
```diff
@@ -639,11 +639,28 @@ def alter_table(
...
+
+            execute("PRAGMA foreign_keys = ON") if fk_enabled
+
+            if fk_enabled
+              violations = execute("PRAGMA foreign_key_check").to_a
+              if violations.any?
+                raise ActiveRecord::StatementInvalid,
+                      "Foreign key violations detected after schema change: #{violations.inspect}"
+              end
+            end
```
Comment (skipkayhil) [inline activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb]: I believe this is supposed to run inside the transaction according the the [sqlite docs](https://sqlite.org/lang_altertable.html) (steps 10-12)

Comment (skipkayhil) [reply activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb]: Thinking out loud: 

- I wonder if the real problem here is just the ordering of `disable_referential_integrity` and the `transaction`
- `defer_foreign_keys` inside `disable_referential_integrity` seems to be unnecessary as long as it wraps `transaction` and not the opposite
- fixture insertion also has `transaction` wrapping `disable_referential_integrity`, maybe could also be inverted?

File: activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb (hunk 1 above)
Comment (ruyrocha) [reply activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb]: It won't be required anymore, @rafaelfranca :)

File: activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb (hunk 2 above)
Comment (ruyrocha) [reply activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb]: You're absolutely right, @skipkayhil, regarding the order - it's fixed now.

Regarding fixtures insertion, should we address this in the same PR or create a separate issue/PR for the fixture loading bug?

**Comment by byroot** [comment]
Thank you. Backported to 8.1, 8.0 and 7.2
