### PR TITLE
[Fix #55379] Default branch in github ci templates

### LINKED ISSUE #55379: Git default branch is not specified in the github actions
### Steps to reproduce

```ruby
cat ~/.gitconfig
[init]
    defaultBranch = master
...

rails new demo-app
...

cat demo-app/.github/workflows/ci.yml
name: CI

on:
  pull_request:
  push:
    branches: [ main ]
...
```
### Expected behavior

Having the default branch specified on the gitconfig (git config init.defaultBranch)

### Actual behavior

A static value defined [here](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/app/templates/github/ci.yml.tt#L6)

### System configuration

**Rails version**: Rails 8.0.2

**Ruby version**: ruby 3.4.3 (2025-04-14 revision d0b7e5b6a0) +PRISM [x86_64-linux]

### PR DESCRIPTION
**Pull request by endenis**
### Motivation / Background

Fixes #55379

When generating a new rails app or a plugin, the config templates for GitHub workflow CI contain hardcoded "main" branch name.
Instead, they should take the default branch name from the `git config init.defaultbranch` if it is specified.

### Detail

1. I used the existing method `user_default_branch` inside template files to fetch the name of the default git branch.
2. The `user_default_branch` method was modified so that it uses `capture_command` inside. This way it does not crash on an error (if, for example, git is not installed) and there is no need to call `.strip` on each usage.
3. I changed the existing tests `test_version_control_initializes_git_repo_with_user_default_branch` to also verify the branch name in the generated CI config files.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Review by skipkayhil — APPROVED** [review]

File: railties/lib/rails/generators/app_base.rb [hunk 1]
```diff
@@ -760,11 +760,11 @@ def keep_file(destination)
       end
 
       def user_default_branch
-        @user_default_branch ||= `git config init.defaultbranch`
+        @user_default_branch ||= `git config init.defaultbranch`.strip
```
Comment (Edouard-chin) [inline railties/lib/rails/generators/app_base.rb]: I'm not sure how frequent this is, but if a user doesn't have git installed and runs `rails new my_app --skip-git` this will now crash the process.

Comment (skipkayhil) [reply railties/lib/rails/generators/app_base.rb]: That's interesting, maybe `--skip-git` should imply `--skip-ci`

Comment (endenis) [reply railties/lib/rails/generators/app_base.rb]: Interesting! Thank you for your comments.
In a new commit I added a begin-rescue block to cover this case.

Comment (skipkayhil) [reply railties/lib/rails/generators/app_base.rb]: ~Maybe an even easier solution: `$default-branch`~

~https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/~

Nevermind, this appears to be a "workflow template" level feature

File: railties/lib/rails/generators/app_base.rb [hunk 2]
```diff
@@ -760,11 +760,16 @@ def keep_file(destination)
       end
 
       def user_default_branch
-        @user_default_branch ||= `git config init.defaultbranch`
+        @user_default_branch ||=
```
Comment (Edouard-chin) [inline railties/lib/rails/generators/app_base.rb]:
```suggestion
        @user_default_branch ||= capture_command('git config init.defaultbranch', /.*/)
```

**Review by Edouard-chin — COMMENTED** [review]
> That's interesting, maybe --skip-git should imply --skip-ci

That's a good point. I think the fix in this case is simple enough to continue generating a github CI config.
Either way, it seems a bit more robust to rescue from system calls and not fail the whole `rails new` just to get the user's default branch.

File: railties/lib/rails/generators/app_base.rb (hunk 2 above)
Comment (endenis) [reply railties/lib/rails/generators/app_base.rb]: Thank you, I've applied this change

**Review by Edouard-chin — APPROVED** [review]
