### PR TITLE
Fixes #43279 by filtering unchanged attributes when default function is available for insert

### LINKED ISSUE #43279: Problem using uuid type using as default gen_random_uuid()
### Steps to reproduce

```ruby
bin/rails generate scaffold post title:string content:string uuid:uuid
```

You need to modified the migration with following changes:

```
class CreatePosts < ActiveRecord::Migration[7.0]
  def change
    enable_extension 'pgcrypto' unless extension_enabled?('pgcrypto')

    create_table :posts do |t|
      t.string :title
      t.text :content
      t.uuid :uuid, default: "gen_random_uuid()", null: false

      t.timestamps
    end
  end
end
```

So, now you need to add tests to make sure create of posts:

```
require "test_helper"

class PostTest < ActiveSupport::TestCase
  def test_it_creates_post
    post = Post.new
    post.title = "Title"
    post.content = "Content"

    assert post.save
  end
end
```

Finally, run the test

```
bin/rails test test/models/post_test.rb
```

### Expected behavior

I expected that post has been created so it had a uuid value like to "01d31c6f-bdbc-43e6-956d-d96ba3cf667a"

### Actual behavior

```
Run options: --seed 10782

# Running:

E

Error:
PostTest#test_it_creates_post:
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "uuid" violates not-null constraint
DETAIL:  Failing row contains (980190963, Title, Content, null, 2021-09-21 19:42:23.062987, 2021-09-21 19:42:23.062987).

    test/models/post_test.rb:9:in `test_it_creates_post'


rails test test/models/post_test.rb:4

Finished in 0.050630s, 19.7511 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```
### System configuration
**Rails version**: 7.0.0.alpha2

**Ruby version**: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233)

### PR DESCRIPTION
**Pull request by the-spectator**
### Summary

Fixes https://github.com/rails/rails/issues/43279

When `partial_inserts` are disabled, Rails will try to insert all values for columns present. But this can cause issues when a column is backed by a `default_function` with `not null` constraint, Rails will try to insert a `null` value.

This fix will filter/skip the attributes which have not been changed by the user and are backed by `default_function` and hence will avoid the above mentioned scenario for inserts.

`Co-authored-by: Jacopo <beschi.jacopo@gmail.com>`

### CODE REVIEW

File: activerecord/lib/active_record/attribute_methods/dirty.rb [hunk 1]
```diff
@@ -229,7 +229,13 @@ def attribute_names_for_partial_updates
         end
 
         def attribute_names_for_partial_inserts
-          partial_inserts? ? changed_attribute_names_to_save : attribute_names
+          if partial_inserts?
+            changed_attribute_names_to_save
+          else
+            attribute_names.delete_if do |attr_name|
+              !attribute_changed?(attr_name) && column_for_attribute(attr_name).default_function
+            end
```
Comment (intrip) [inline activerecord/lib/active_record/attribute_methods/dirty.rb:237]: What about extracting this code into a separate method?

**Review by intrip — CHANGES_REQUESTED** [review]
Can you please:
- Add a test such that we'll avoid future regressions
- Add a Changelog entry
?

Would be great also if you [co-author](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) the PR with me. 
You just need to add to the bottom of the commit message:
`Co-authored-by: Jacopo <beschi.jacopo@gmail.com> `

**Comment by the-spectator** [comment]
@intrip Added the co-authored to commit. Thank you again for your guidance and help!!

I will work on the test tomorrow as it's getting too late here.

File: activerecord/lib/active_record/attribute_methods/dirty.rb [hunk 2]
```diff
@@ -229,7 +229,13 @@ def attribute_names_for_partial_updates
         end
 
         def attribute_names_for_partial_inserts
-          partial_inserts? ? changed_attribute_names_to_save : attribute_names
+          if partial_inserts?
+            changed_attribute_names_to_save
+          else
+            attribute_names.delete_if do |attr_name|
```
Comment (byroot) [inline activerecord/lib/active_record/attribute_methods/dirty.rb:235]: This seems wrong, `delete_if` returns what was removed from the array: https://ruby-doc.org/core-2.5.0/Array.html#method-i-delete_if

```ruby
scores = [ 97, 42, 75 ]
scores.delete_if {|score| score < 80 }   #=> [97]
```

So I think you just want `reject` here.

Comment (the-spectator) [reply activerecord/lib/active_record/attribute_methods/dirty.rb:235]: @byroot thank you for the review.

I think `delete_if` returns the elements that remained after deletion. In the example code block the return value is `[97]` and deleted items are `[42, 75]` (score < 80).

**Comment by the-spectator** [comment]
Added tests and changelog entry.

File: activerecord/lib/active_record/attribute_methods/dirty.rb (hunk 1 above)
Comment (the-spectator) [reply activerecord/lib/active_record/attribute_methods/dirty.rb]: Extracted to `changed_attribute_names_without_default_function` but can use better name.

File: activerecord/lib/active_record/attribute_methods/dirty.rb (hunk 2 above)
Comment (byroot) [reply activerecord/lib/active_record/attribute_methods/dirty.rb]: 🤦 my bad I should have finished my coffee before reviewing.

File: activerecord/test/cases/dirty_test.rb [hunk 3]
```diff
@@ -941,6 +941,51 @@ def check_around
     assert_not_predicate person, :changed?
   end
 
+  test "partial insert off with unchanged default function attribute" do
+    partial_inserts_was = Aircraft.partial_inserts
+    Aircraft.partial_inserts = false
+    Aircraft.connection.add_column(:aircraft, :manufactured_at, :timestamp, default: -> { "now()" })
```
Comment (byroot) [inline activerecord/test/cases/dirty_test.rb:947]: I think it would be cleaner to just change the model.

File: activerecord/test/cases/dirty_test.rb [hunk 4]
```diff
@@ -941,6 +941,51 @@ def check_around
...
+
+    aircraft = nil
+    assert_sql(/(?!manufactured_at)/i) do
```
Comment (byroot) [inline activerecord/test/cases/dirty_test.rb:950]: I'm not sure this is a good assertion. You can hope that there's only a single query emitted, in which case it does work, but if for some reason the driver emit multiple queries, then it doesn't test anywhing because `assert_sql` is basically a `any?` check.

It's also a bit redundant with `ActiveRecord::SQLCounter.log_all.none?`

File: activerecord/lib/active_record/attribute_methods/dirty.rb (hunk 2 above)
Comment (byroot) [reply activerecord/lib/active_record/attribute_methods/dirty.rb]: That said, `reject` would be better, because here you mutate an array, but don't do anything with it.

File: activerecord/test/cases/dirty_test.rb (hunk 3 above)
Comment (the-spectator) [reply activerecord/test/cases/dirty_test.rb]: moved the column to `aircraft` schema.

File: activerecord/test/cases/dirty_test.rb (hunk 4 above)
Comment (the-spectator) [reply activerecord/test/cases/dirty_test.rb]: @byroot @intrip Can you suggest the correct assertion to be used for this? I tried `ActiveRecord::SQLCounter.log_all.none?` but I am not able to correctly assert the absence of the `manufactured_at` column in the insert query.

Comment (byroot) [reply activerecord/test/cases/dirty_test.rb]: I'd give up trying to assert the emitted query directly, and just test the actual behavior. e..g assert the unsaved model has no `manufactured_at`, save, assert it has one.

File: activerecord/lib/active_record/attribute_methods/dirty.rb [hunk 5]
```diff
@@ -229,7 +228,13 @@ def attribute_names_for_partial_updates
         end
 
         def attribute_names_for_partial_inserts
-          partial_inserts? ? changed_attribute_names_to_save : attribute_names
+          partial_inserts? ? changed_attribute_names_to_save : attribute_names_without_changed_default_function_attributes
+        end
+
+        def attribute_names_without_changed_default_function_attributes
+          attribute_names.reject do |attr_name|
+            !attribute_changed?(attr_name) && column_for_attribute(attr_name).has_default?
```
Comment (the-spectator) [inline activerecord/lib/active_record/attribute_methods/dirty.rb:236]: had to use `#has_default?` instead of `#default_function` because sqlite3 treats `CURRENT_TIMESTAMP` as default value instead of default function.

**Comment by the-spectator** [comment]
PR is ready for another round of review and we got a green 🍏 CI

File: activerecord/lib/active_record/attribute_methods/dirty.rb (hunk 5 above)
Comment (intrip) [reply activerecord/lib/active_record/attribute_methods/dirty.rb:237]: I think SQLite limitation is related to the current [Schema statement implementation](https://github.com/rails/rails/blob/fe4377098b3800c3998f0583549a414b99b72b19/activerecord/lib/active_record/connection_adapters/sqlite3/schema_statements.rb#L143).

Instead of using `has_default?` I suggest to still use `default_function` and just skip the test for Sqlite.
We can extend SQLite in a follow up PR.

File: activerecord/test/cases/dirty_test.rb [hunk 6]
```diff
@@ -941,6 +941,41 @@ def check_around
     assert_not_predicate person, :changed?
   end
 
+  test "partial insert off with unchanged default function attribute" do
+    with_partial_writes Aircraft, false do
+      aircraft = Aircraft.new(name: "Boeing")
+
+      assert_equal "Boeing", aircraft.name
+      assert_nil aircraft.manufactured_at
```
Comment (intrip) [inline activerecord/test/cases/dirty_test.rb:949]: minor: IMO I don't find this and some other assertion useful
```suggestion
```

File: activerecord/test/cases/dirty_test.rb [hunk 7]
```diff
@@ -941,6 +941,41 @@ def check_around
...
+    end
+  end
+
+  test "partial insert off with changed default function attribute" do
+    with_partial_writes Aircraft, false do
+      manufactured_at = 1.years.ago
+      aircraft = Aircraft.new(name: "Boeing2", manufactured_at: manufactured_at)
+
+      assert_equal "Boeing2", aircraft.name
+      assert_equal manufactured_at.to_i, aircraft.manufactured_at.to_i
```
Comment (intrip) [inline activerecord/test/cases/dirty_test.rb:967]: why is not possible to just compare the Time values?

**Review by intrip — CHANGES_REQUESTED** [review]

**Comment by the-spectator** [comment]
Pushed changes with resolved feedback. Please have another look. 🙇

**Review by byroot — APPROVED** [review]
Two minor nitpicks but LGTM and I'd be happy to merge. @intrip any concerns?

**Review by intrip — APPROVED** [review]
@byroot @the-spectator  LGTM as well 🎉
