### PR TITLE
fixes #27157 CSRF protection documentation

### LINKED ISSUE #27157: Confusing / unclear documentation for CSRF protection
I also [asked this on StackOverflow](http://stackoverflow.com/q/40706394/305019), but I think it's worth raising an issue. At the very least to improve documentation and make it clearer.

The [documentation on Request Forgery Protection](http://edgeapi.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html) is a little confusing and unclear in certain parts. Specifically the example and surrounding text on the main text:

> It's important to remember that XML or JSON requests are also affected and if you're building an API you should change forgery protection method in ApplicationController (by default: :exception):
> 
> ```ruby
> class ApplicationController < ActionController::Base
>   protect_from_forgery unless: -> { request.format.json? }
> end
> ```
> CSRF protection is turned on with the protect_from_forgery method. By default protect_from_forgery protects your session with :null_session method, which provides an empty session during request.
> 
> We may want to disable CSRF protection for APIs since they are typically designed to be state-less. That is, the request API client will handle the session for you instead of Rails.

If I read this correctly, the first sentence says that "XML / JSON requests are also affected" (i.e. susceptible to CSRF attacks?), but then recommend bypassing CSRF protection for JSON requests.

Is this a contradiction? Or perhaps "affected" is there to mean "blocked (unnecessarily?) by CSRF protection" ?

Another source of confusion for me is whether turning off CSRF protection always implies managing your own session.

Lastly, I think it's worth pointing out (and please correct me if I'm wrong) that CSRF protection [isn't necessary for XHR](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Protecting_REST_Services:_Use_of_Custom_Request_Headers) as long as CORS is blocked for requests from untrusted domains. The last point is one I'm hoping to get some more clarity (and hence the SO question I mentioned).

Hope it's the right place to report or discuss this, but especially when it comes to security, it's very important that threats and countermeasures are crystal clear.

### PR DESCRIPTION
**Pull request by gingerlime**
### Summary

* removed reference to GET requests where it applies also to other HTTP verbs
* clarified language about what Rails does rather than slightly more generic 
   statements about what protection should be in place.
* updated documentation to try and better explain how CSRF protection
   works with XHR, and the potential exposure with CORS

### CODE REVIEW

File: actionpack/lib/action_controller/metal/request_forgery_protection.rb [hunk 1]
```diff
@@ -31,16 +31,23 @@ class InvalidCrossOriginRequest < ActionControllerError #:nodoc:
...
+  # Ajax) requests are allowed to make requests for JavaScript responses.
   #
-  # It's important to remember that XML or JSON requests are also affected and if
-  # you're building an API you should change forgery protection method in
+  # It's important to remember that XML or JSON requests are also checked by default. If
+  # you're building an API or an SPA you could change forgery protection method in
   # <tt>ApplicationController</tt> (by default: <tt>:exception</tt>):
   #
   #   class ApplicationController < ActionController::Base
   #     protect_from_forgery unless: -> { request.format.json? }
```
Comment (Umofomia) [inline actionpack/lib/action_controller/metal/request_forgery_protection.rb]: Because this applies generally to XHR requests, should this guidance also be changed to `request.xhr?` instead of `request.format.json?`.

Comment (gingerlime) [reply actionpack/lib/action_controller/metal/request_forgery_protection.rb]: It's just an example, but sounds like a good idea to cover the general case 👍 (happy to change it, but I didn't get any feedback on this PR so far and not sure if anybody's interested unfortunately)

Comment (Umofomia) [reply actionpack/lib/action_controller/metal/request_forgery_protection.rb]: I happened to find your PR while researching the safety of excluding XHRs from CSRF protection. The clarifications you made to the documentation here was very helpful to me, for what it's worth.

Given that it appears to be generally safe to do so (I found a more detailed explanation [here](https://markitzeroday.com/x-requested-with/cors/2017/06/29/csrf-mitigation-for-ajax-requests.html)), I'm also wondering whether it instead makes sense for Rails to exclude CSRF protection for XHR calls by default (i.e., should `verified_request?` simply return true for `request.xhr?` too?): https://github.com/rails/rails/blob/0a6b866ff2f45cea50598fc054763b89ea7affbe/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L283-L291

With this change, you would no longer need to add the boilerplate `unless: -> { request.xhr? }` to every API-driven Rails project.

Comment (gingerlime) [reply actionpack/lib/action_controller/metal/request_forgery_protection.rb]: Thanks for the positive feedback. Those suggested changes to the doc came about after a little of my own frustration trying to understand whether it's safe or not, or in which situations exactly. 

Please take a look at the second part of the suggested updates however. Whilst generally safe, there is a subtle risk here if combined with too permissive CORS I believe. I too often see places that define wildcard `Access-Control-Allow-Origin "*"`. Usually as a quickfix to solving cross-domain limitations. When combined, sites open themselves to CSRF again as far as I can tell.

So I would still imagine this is a safer / more sane default to have. But of course if you know what you're doing, and don't open up CORS to everyone, it seems totally safe to bypass CSRF protection to XHR.

I hope this PR can be merged so that the advice is clearer. I'm not entirely sure what needs to happen for it to get merged though. I'm not a regular contributor to rails. It's my first PR.

**Comment by schneems** [comment]
Thanks!
