### PR TITLE
Return correct date in ActiveModel for time to date conversions

### LINKED ISSUE #28521: date_select causing wrong date when using discard_year and include_blank
When using discard_year together with include_blank the date_helper sets year to "1" using a hidden field. That somehow causes the saved date value to be altered in a way, that the "day" part of the date increases by two ...

So choosing "january" "1" from the two selects saves the date "0001-01-03" instead of "0001-01-01"

But if the value of the year part is set anything from 201 upto 300 or 1583 upto 2017 the day and month parts remains as entered, which makes no sense to me. 

### Steps to reproduce

`rails new app_test_discard_year`
`cd app_test_discard_year/`
`rails generate scaffold test_day day:date`
`rails db:migrate`

Add `{ discard_year: true, include_blank: true }` to the date_select in 

> app/views/test_days/_form.html.erb

so it looks like this `<%= f.date_select :day, { discard_year: true, include_blank: true } %>`

> http://localhost:3000/test_days 

Start server and try creating a new "Test Day" choosing january 1st and save. 

Rails 5.0.2
ruby 2.4.0p0

### PR DESCRIPTION
**Pull request by Sayanc93**
time.to_date conversion happens considering leap years in Ruby.
So a conversion of  Day.new({"day(1i)"=>"1", "day(2i)"=>"1", "day(3i)"=>"1"}) or 0001-01-01 00:00:00 UTC results in saving the date in DB as Mon, 03 Jan 0001.
Which might seem weird on the user level, hence falling back to parsing on string level resolves this data mismatch respecting the parameters passed
Fixes #28521

### CODE REVIEW

**Comment by Sayanc93** [comment]
cc @kamipo

File: activemodel/lib/active_model/type/date.rb [hunk 1]
```diff
@@ -47,7 +47,7 @@ def new_date(year, mon, mday)
 
         def value_from_multiparameter_assignment(*)
           time = super
-          time && time.to_date
+          time && fallback_string_to_date(time.to_s)
```
Comment (kamipo) [inline activemodel/lib/active_model/type/date.rb]: How about here?

```diff
--- a/activemodel/lib/active_model/type/date.rb
+++ b/activemodel/lib/active_model/type/date.rb
@@ -47,7 +47,7 @@ def new_date(year, mon, mday)

         def value_from_multiparameter_assignment(*)
           time = super
-          time && time.to_date
+          time && new_date(time.year, time.mon, time.mday)
         end
     end
   end
```

File: activemodel/CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,18 @@
+*   Return correct date while converting parameters in value_from_multiparameter_assignment
+    for ActiveModel::Type::Date
+
+    Before:
+        Day.new({"day(1i)"=>"1", "day(2i)"=>"1", "day(3i)"=>"1"})
+        => #<Day id: nil, day: "0001-01-03", created_at: nil, updated_at: nil>
+
+    After:
+        Day.new({"day(1i)"=>"1", "day(2i)"=>"1", "day(3i)"=>"1"})
```
Comment (kamipo) [inline activemodel/CHANGELOG.md]: Need a blank line.

https://github.com/Sayanc93/rails/blob/bc6931af97c4a452a6253ce6ac5bde736e2d2e15/activemodel/CHANGELOG.md

image

File: activemodel/CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,18 @@
+*   Return correct date while converting parameters in value_from_multiparameter_assignment
+    for ActiveModel::Type::Date
```
Comment (kamipo) [inline activemodel/CHANGELOG.md]: ... in `value_from_multiparameter_assignment` for `ActiveModel::Type::Date`.

**Comment by Sayanc93** [comment]
Thank a lot for your feedback @kamipo ! I have made changes accordingly. 
While testing `value_from_multiparameter_assignment` in `Helpers::AcceptsMultiparameterTime` I found that default_timezone is undefined in test environment atleast (while performing operations in view or console it gets set in `ActiveRecord::Type::Internal::Timezone` but not in test environment)
https://github.com/rails/rails/blob/master/activemodel/lib/active_model/type/helpers/accepts_multiparameter_time.rb#L28
I have borrowed default_timezone method from Helpers::TimeValue instead of including the entire module, since the module seemed more appropriate for DateTime but not Date. What do you think?

**Comment by Sayanc93** [comment]
@schneems could you take a look at this PR?
