### PR TITLE
[AR] Fix uniqueness validation on association not using overridden PK

### LINKED ISSUE #45775: Uniqueness validation on association does not use the correct primary key
### Steps to reproduce

I'm not _entirely_ sure if this is considered a bug, or intended behavior that's not well-documented for `uniqueness` validations on associations.

I'm happy to help improve the documentation on this if that would be the most helpful way forward, or if this _is_ considered a bug, I can take a stab at a PR. 

It looks like the issue is that `build_relation` on the uniqueness validator calls [`bind_attribute` on `ActiveRecord::Relation`](https://github.com/rails/rails/blob/408d061a80a49878ad26b305616ed9ba88ee1411/activerecord/lib/active_record/relation.rb#L45), which properly takes into account the reflection's foreign_key, but not primary key if it's been overridden. 

Here's a test that reproduces the issue:

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '~> 7.0.3.1'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  adapter: 'sqlite3',
  database: ':memory:'
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :prescriptions, force: true do |t|
    t.string :rx_number
  end

  create_table :fills, force: true do |t|
    t.string :rx_number
  end
end

class Prescription < ActiveRecord::Base
  has_many :fills, foreign_key: :rx_number, primary_key: :rx_number
end

class Fill < ActiveRecord::Base
  belongs_to :prescription, foreign_key: :rx_number, primary_key: :rx_number

  validates :prescription, uniqueness: true
end

class BugTest < Minitest::Test
  def test_fill_unique_by_rx_number
    Fill.create!(rx_number: '1234')
    prescription = Prescription.create!(rx_number: '1234')
    new_fill = prescription.fills.new
    refute new_fill.save
  end
end
```

### Expected behavior
The uniqueness validation query would use the `rx_number` value of the `Prescription` to query for an existing `Fill` since that is what is set as the associations `primary_key`. 

### Actual behavior
The uniqueness validation query uses the `id` value of the `Prescription` to query for existing fills, disregarding the association's overridden `primary_key`.

This test passes if I patch bind_attribute to read the primary key from the reflection instead of directly from the reflection's klass:

```ruby
module ActiveRecord
  # = Active Record \Relation
  class Relation
    def bind_attribute(name, value) # :nodoc:
      if reflection = klass._reflect_on_association(name)
        name = reflection.foreign_key
        primary_key = reflection.association_primary_key || reflection.klass.primary_key
        value = value.read_attribute(primary_key) unless value.nil?
      end

      attr = table[name]
      bind = predicate_builder.build_bind_attribute(attr.name, value)
      yield attr, bind
    end
  end
end
```

We were able to work around this by adding the uniqueness validation to the `rx_number` attribute instead of the association. If this is the desired way to handle this, I can open a PR to add a note about this to the docs, as it took us by surprise that validation on the association wouldn't use the defined key to get the value to query.

### System configuration
**Rails version**: `7.0.3.1`

**Ruby version**: `3.1.2`

### PR DESCRIPTION
**Pull request by mikeletscher**
### Summary

Resolves #45775 

Fixes what I believe is a bug where a uniqueness validation on a belongs_to association was not using the correct value in the query for existing records. The ID of the associated model was being used instead of the overridden `primary_key` column value.

### Other Information

From some quick grepping, it doesn't look like this `bind_attribute` method is used anywhere other this uniqueness validation.

### CODE REVIEW

File: activerecord/lib/active_record/relation.rb [hunk 1]
```diff
@@ -45,7 +45,7 @@ def initialize_copy(other)
     def bind_attribute(name, value) # :nodoc:
       if reflection = klass._reflect_on_association(name)
         name = reflection.foreign_key
-        value = value.read_attribute(reflection.klass.primary_key) unless value.nil?
+        value = value.read_attribute(reflection.association_primary_key) unless value.nil?
```
Comment (mikeletscher) [inline activerecord/lib/active_record/relation.rb:48]: This falls back to klass.primary_key if not overridden:

```ruby
def association_primary_key(klass = nil)
        if primary_key = options[:primary_key]
          @association_primary_key ||= -primary_key.to_s
        else
          primary_key(klass || self.klass)
        end
      end
```

**Comment by yahonda** [comment]
As I commented at https://github.com/rails/rails/issues/45775#issuecomment-1209230585 
, the original issue is due to missing/incorrect `self.primary_key` at the referenced model.

**Comment by mikeletscher** [comment]
@yahonda I left a comment on the issue, but following up here. It appears to me that ActiveRecord already supports this use case—there's an existing [test model](https://github.com/rails/rails/blob/main/activerecord/test/models/company.rb#L69) and [test](https://github.com/rails/rails/blob/main/activerecord/test/cases/associations/eager_test.rb#L1286) using the `primary_key` options for an association to a model that has no primary_key defined. The PR was to address that the uniqueness validation doesn't seem to also support this behavior.

**Comment by yahonda** [comment]
After thinking about this pull request for some time, I have decided to merge this pull request. Thanks for the contribution.

**Comment by fatkodima** [comment]
Created a backport for `7-0-stable` - https://github.com/rails/rails/pull/49300.
