### PR TITLE
Show common commands when calling `rails -h` outside a Rails dir

### LINKED ISSUE #40823: No way to list common rails commands from CLI outside a rails app directory
### Steps to reproduce
- `rails --help`
- `rails help`
- `rails -h`

### Expected behavior

Using `rails --help` should print usage instructions for common Rails commands.

```
rails --help
```

<details>
<summary>Command output</summary>
<pre>
The most common rails commands are:
 generate     Generate new code (short-cut alias: "g")
 console      Start the Rails console (short-cut alias: "c")
 server       Start the Rails server (short-cut alias: "s")
 test         Run tests except system tests (short-cut alias: "t")
 test:system  Run system tests
 dbconsole    Start a console for the database specified in config/database.yml
              (short-cut alias: "db")

All commands can be run with -h (or --help) for more information.
In addition to those commands, there are:
</pre>
</details>

### Actual behavior

It prints usage instructions specific to `rails new` instead.

```
rails --help
```

<details>
<summary>Command output</summary>
<pre>
Usage:
  rails new APP_PATH [options]

Options:
      [--skip-namespace], [--no-skip-namespace]              # Skip namespace (affects only isolated engines)
      [--skip-collision-check], [--no-skip-collision-check]  # Skip collision check
  -r, [--ruby=PATH]                                          # Path to the Ruby binary of your choice
                                                             # Default: /Users/olivierlacan/.rbenv/versions/2.7.2/bin/ruby
  -m, [--template=TEMPLATE]                                  # Path to some application template (can be a filesystem path or URL)
  -d, [--database=DATABASE]                                  # Preconfigure for selected database (options: mysql/postgresql/sqlite3/oracle/sqlserver/jdbcmysql/jdbcsqlite3/jdbcpostgresql/jdbc)
                                                             # Default: sqlite3
      [--skip-gemfile], [--no-skip-gemfile]                  # Don't create a Gemfile
  -G, [--skip-git], [--no-skip-git]                          # Skip .gitignore file
      [--skip-keeps], [--no-skip-keeps]                      # Skip source control .keep files
  -M, [--skip-action-mailer], [--no-skip-action-mailer]      # Skip Action Mailer files
      [--skip-action-mailbox], [--no-skip-action-mailbox]    # Skip Action Mailbox gem
      [--skip-action-text], [--no-skip-action-text]          # Skip Action Text gem
  -O, [--skip-active-record], [--no-skip-active-record]      # Skip Active Record files
      [--skip-active-job], [--no-skip-active-job]            # Skip Active Job
      [--skip-active-storage], [--no-skip-active-storage]    # Skip Active Storage files
  -P, [--skip-puma], [--no-skip-puma]                        # Skip Puma related files
  -C, [--skip-action-cable], [--no-skip-action-cable]        # Skip Action Cable files
  -S, [--skip-sprockets], [--no-skip-sprockets]              # Skip Sprockets files
      [--skip-spring], [--no-skip-spring]                    # Don't install Spring application preloader
      [--skip-listen], [--no-skip-listen]                    # Don't generate configuration that depends on the listen gem
  -J, [--skip-javascript], [--no-skip-javascript]            # Skip JavaScript files
      [--skip-turbolinks], [--no-skip-turbolinks]            # Skip turbolinks gem
      [--skip-jbuilder], [--no-skip-jbuilder]                # Skip jbuilder gem
  -T, [--skip-test], [--no-skip-test]                        # Skip test files
      [--skip-system-test], [--no-skip-system-test]          # Skip system test files
      [--skip-bootsnap], [--no-skip-bootsnap]                # Skip bootsnap gem
      [--dev], [--no-dev]                                    # Set up the application with Gemfile pointing to your Rails checkout
      [--edge], [--no-edge]                                  # Set up the application with Gemfile pointing to Rails repository
      [--master], [--no-master]                              # Set up the application with Gemfile pointing to Rails repository master branch
      [--rc=RC]                                              # Path to file containing extra configuration options for rails command
      [--no-rc], [--no-no-rc]                                # Skip loading of extra configuration options from .railsrc file
      [--api], [--no-api]                                    # Preconfigure smaller stack for API only apps
      [--minimal], [--no-minimal]                            # Preconfigure a minimal rails app
  -B, [--skip-bundle], [--no-skip-bundle]                    # Don't run bundle install
  --webpacker, [--webpack=WEBPACK]                           # Preconfigure Webpack with a particular framework (options: react, vue, angular, elm, stimulus)
      [--skip-webpack-install], [--no-skip-webpack-install]  # Don't run Webpack install

Runtime options:
  -f, [--force]                    # Overwrite files that already exist
  -p, [--pretend], [--no-pretend]  # Run but do not make any changes
  -q, [--quiet], [--no-quiet]      # Suppress status output
  -s, [--skip], [--no-skip]        # Skip files that already exist

Rails options:
  -h, [--help], [--no-help]        # Show this help message and quit
  -v, [--version], [--no-version]  # Show Rails version number and quit

Description:
    The 'rails new' command creates a new Rails application with a default
    directory structure and configuration at the path you specify.

    You can specify extra command-line arguments to be used every time
    'rails new' runs in the .railsrc configuration file in your home directory,
    or in $XDG_CONFIG_HOME/rails/railsrc if XDG_CONFIG_HOME is set.

    Note that the arguments specified in the .railsrc file don't affect the
    defaults values shown above in this help message.

Example:
    rails new ~/Code/Ruby/weblog

    This generates a skeletal Rails installation in ~/Code/Ruby/weblog.
</pre>
</details>

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.7.2

It seems like there's a bad assumption in `Rails::Command#invoke` where we think the `command_name` could be `--help` but it can't be at the root (`rails --help` without a subcommand) since this conditional will always assign `command_name` to `"application"`: 
https://github.com/rails/rails/blob/95a8c83d2ec7aa34ab127f7fa6def4d8891eb662/railties/lib/rails/command.rb#L31-L41

Since the `command_name` is set (incorrectly IMO) to `"application"`, a call to `rails --help` results in the instantiation of a `Rails::Command::ApplicationCommand`
https://github.com/rails/rails/blob/95a8c83d2ec7aa34ab127f7fa6def4d8891eb662/railties/lib/rails/command.rb#L48-L51 

When `#perform` is called on that instance, the `help` method "punts" to `Rails::Generators::AppGenerator` with no arguments, which is why we end up with `rails new` usage instructions, which are somewhat helpful, although quite verbose and unrelated to our request (IMO, again). 

Try as I might I couldn't find how to print the `USAGE` from `HelpCommand` [which clearly exists](https://github.com/rails/rails/blob/95a8c83d2ec7aa34ab127f7fa6def4d8891eb662/railties/lib/rails/commands/help/USAGE#L1-L16) and which I definitely remember seeing in the past. Not with `rails` and no arguments (prints `rails new` usage), not with `rails help` no with `rails commands`. 

This is problematic because it means for someone new to the Rails command line, there's no way to list available commands. The only solution is to look up [the Rails Guide](https://guides.rubyonrails.org/command_line.html#command-line-basics) or trudge through the source (which seems unlikely for newcomers).

### PR DESCRIPTION
**Pull request by p8**
### Motivation

When running `rails -h` or just `rails` outside a Rails application, Rails outputs all options for running the `rails new` command. This can be confusing to users when they probably want to see the common Rails commands.

Instead, we should always show the common commands when running `rails -h` inside or outside a Rails application.

### Detail

With this change help works as follows...

Outside a Rails application we never show the extended commands: db:migrate, etc...
The extended commands require a Rails application. They also take up a lot screen space.

- `rails`        outputs the help for the gem commands
- `rails -h`     outputs the help for the gem commands.
- `rails new -h` outputs the help for the new command.

Inside a Rails application it works mostly as before. The only change is that calling plain `bin/rails` now only outputs the common commands and not the extended commands.

- `bin/rails`    outputs the help for the common commands
- `bin/rails -h` outputs the help for the common commands and the
  extended commands

### Additional information

This was previously submitted in https://github.com/rails/rails/pull/41425 but that PR was stale and I can no longer access the branch.

Fixes: #40823

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] There are no typos in commit messages and comments.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Feature branch is up-to-date with `main` (if not - rebase it).
* [x] Pull request only contains one commit for bug fixes and small features. If it's a larger feature, multiple commits are permitted but must be descriptive.
* [x] Tests are added if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [x] PR is not in a draft state.
* [x] CI is passing.

### CODE REVIEW

**Comment by p8** [comment]
Hey @jonathanhefner, you did the original review of #41425.
Do you think this is good to go?

File: railties/test/application/help_test.rb [hunk 1]
```diff
@@ -21,5 +21,31 @@ def teardown
...
+    assert_match "The most common rails commands are", output
+    assert_no_match "In addition to those commands", output
+  end
+
+  def gem_rails(cmd)
+    cmd = "#{Gem.ruby} #{RAILS_FRAMEWORK_ROOT}/railties/exe/rails #{cmd}"
+    output = `#{cmd}`
+    raise "Command #{cmd.inspect} failed. Output:\n#{output}" unless $?.success?
+    output
   end
```
Comment (jonathanhefner) [inline railties/test/application/help_test.rb:50]: `gem_rails` should probably be a private method.  Also, I'm inclined to use `system` with the `exception: true` option, though I don't have a strong preference:

```suggestion
  private
    def gem_rails(cmd)
      capture(:stdout) do 
        system("#{Gem.ruby} #{RAILS_FRAMEWORK_ROOT}/railties/exe/rails #{cmd}", exception: true)
      end
    end
```

**Review by jonathanhefner — COMMENTED** [review]
For posterity, here are the before and after comparisons, which are basically as they were in https://github.com/rails/rails/pull/41425#issuecomment-844780945:

<details>
  <summary>Before, outside a Rails app</summary>

  ```
  Usage:
    rails new APP_PATH [options]

  Options:
            [--skip-namespace], [--no-skip-namespace]              # Skip namespace (affects only isolated engines)
            [--skip-collision-check], [--no-skip-collision-check]  # Skip collision check
    -r, [--ruby=PATH]                                              # Path to the Ruby binary of your choice
                                                                   # Default: .../.rubies/ruby-3.1.2/bin/ruby
    -n, [--name=NAME]                                              # Name of the app
    -m, [--template=TEMPLATE]                                      # Path to some application template (can be a filesystem path or URL)
    -d, [--database=DATABASE]                                      # Preconfigure for selected database (options: mysql/postgresql/sqlite3/oracle/sqlserver/jdbcmysql/jdbcsqlite3/jdbcpostgresql/jdbc)
                                                                   # Default: sqlite3
    -G, [--skip-git], [--no-skip-git]                              # Skip git init, .gitignore and .gitattributes
            [--skip-keeps], [--no-skip-keeps]                      # Skip source control .keep files
    -M, [--skip-action-mailer], [--no-skip-action-mailer]          # Skip Action Mailer files
            [--skip-action-mailbox], [--no-skip-action-mailbox]    # Skip Action Mailbox gem
            [--skip-action-text], [--no-skip-action-text]          # Skip Action Text gem
    -O, [--skip-active-record], [--no-skip-active-record]          # Skip Active Record files
            [--skip-active-job], [--no-skip-active-job]            # Skip Active Job
            [--skip-active-storage], [--no-skip-active-storage]    # Skip Active Storage files
    -C, [--skip-action-cable], [--no-skip-action-cable]            # Skip Action Cable files
    -A, [--skip-asset-pipeline], [--no-skip-asset-pipeline]        # Indicates when to generate skip asset pipeline
    -a, [--asset-pipeline=ASSET_PIPELINE]                          # Choose your asset pipeline [options: sprockets (default), propshaft]
                                                                   # Default: sprockets
    -J, --skip-js, [--skip-javascript], [--no-skip-javascript]     # Skip JavaScript files
            [--skip-hotwire], [--no-skip-hotwire]                  # Skip Hotwire integration
            [--skip-jbuilder], [--no-skip-jbuilder]                # Skip jbuilder gem
    -T, [--skip-test], [--no-skip-test]                            # Skip test files
            [--skip-system-test], [--no-skip-system-test]          # Skip system test files
            [--skip-bootsnap], [--no-skip-bootsnap]                # Skip bootsnap gem
            [--skip-dev-gems], [--no-skip-dev-gems]                # Skip development gems (e.g., web-console)
            [--dev], [--no-dev]                                    # Set up the application with Gemfile pointing to your Rails checkout
            [--edge], [--no-edge]                                  # Set up the application with a Gemfile pointing to the main branch on the Rails repository
    --master, [--main], [--no-main]                                # Set up the application with Gemfile pointing to Rails repository main branch
            [--rc=RC]                                              # Path to file containing extra configuration options for rails command
            [--no-rc], [--no-no-rc]                                # Skip loading of extra configuration options from .railsrc file
            [--api], [--no-api]                                    # Preconfigure smaller stack for API only apps
            [--minimal], [--no-minimal]                            # Preconfigure a minimal rails app
    -j, --js, [--javascript=JAVASCRIPT]                            # Choose JavaScript approach [options: importmap (default), webpack, esbuild, rollup]
                                                                   # Default: importmap
    -c, [--css=CSS]                                                # Choose CSS processor [options: tailwind, bootstrap, bulma, postcss, sass] check https://github.com/rails/cssbundling-rails for more options
    -B, [--skip-bundle], [--no-skip-bundle]                        # Don't run bundle install
            [--skip-decrypted-diffs], [--no-skip-decrypted-diffs]  # Don't configure git to show decrypted diffs of encrypted credentials

  Runtime options:
    -f, [--force]                    # Overwrite files that already exist
    -p, [--pretend], [--no-pretend]  # Run but do not make any changes
    -q, [--quiet], [--no-quiet]      # Suppress status output
    -s, [--skip], [--no-skip]        # Skip files that already exist

  Rails options:
    -h, [--help], [--no-help]        # Show this help message and quit
    -v, [--version], [--no-version]  # Show Rails version number and quit

  Description:
      The `rails new` command creates a new Rails application with a default
      directory structure and configuration at the path you specify.

      You can specify extra command-line arguments to be used every time
      `rails new` runs in the .railsrc configuration file in your home directory,
      or in $XDG_CONFIG_HOME/rails/railsrc if XDG_CONFIG_HOME is set.

      Note that the arguments specified in the .railsrc file don't affect the
      default values shown above in this help message.

  Examples:
      `rails new ~/Code/Ruby/weblog`

      This generates a new Rails app in ~/Code/Ruby/weblog.

      `rails new weblog --api`

      This generates a new Rails app in API mode in ./weblog.

      `rails new weblog --skip-action-mailer`

      This generates a new Rails app without Action Mailer in ./weblog.
      Any part of Rails can be skipped during app generation.
  ```
</details>



<details>
  <summary>Before, inside a Rails app</summary>

  ```
  The most common rails commands are:
   generate     Generate new code (short-cut alias: "g")
   console      Start the Rails console (short-cut alias: "c")
   server       Start the Rails server (short-cut alias: "s")
   test         Run tests except system tests (short-cut alias: "t")
   test:system  Run system tests
   dbconsole    Start a console for the database specified in config/database.yml
                (short-cut alias: "db")
   new          Create a new Rails application. "rails new my_app" creates a
                new application called MyApp in "./my_app"
   plugin new   Create a new Rails railtie or engine

  All commands can be run with -h (or --help) for more information.
  In addition to those commands, there are:

    about
    action_mailbox:ingress:exim
    action_mailbox:ingress:postfix
    action_mailbox:ingress:qmail
    action_mailbox:install
    action_mailbox:install:migrations
    action_text:install
    action_text:install:migrations
    active_storage:install
    app:template
    app:update
    assets:clean[keep]
    assets:clobber
    assets:environment
    assets:precompile
    cache_digests:dependencies
    cache_digests:nested_dependencies
    credentials:diff
    credentials:edit
    credentials:show
    db:create
    db:drop
    db:encryption:init
    db:environment:set
    db:fixtures:load
    db:migrate
    db:migrate:down
    db:migrate:redo
    db:migrate:status
    db:migrate:up
    db:prepare
    db:reset
    db:rollback
    db:schema:cache:clear
    db:schema:cache:dump
    db:schema:dump
    db:schema:load
    db:seed
    db:seed:replant
    db:setup
    db:system:change
    db:version
    destroy
    dev:cache
    encrypted:edit
    encrypted:show
    importmap:install
    initializers
    log:clear
    middleware
    notes
    restart
    routes
    routes:invoke_command
    runner
    runner:looks_like_a_file_path?
    secret
    secrets:edit
    secrets:setup
    secrets:show
    stats
    stimulus:install
    stimulus:install:importmap
    stimulus:install:node
    test:all
    test:channels
    test:controllers
    test:db
    test:generators
    test:helpers
    test:integration
    test:jobs
    test:mailboxes
    test:mailers
    test:models
    time:zones[country_or_offset]
    tmp:clear
    tmp:create
    turbo:install
    turbo:install:importmap
    turbo:install:node
    turbo:install:redis
    version
    yarn:install
    zeitwerk:check
  ```
</details>



<details>
  <summary>After, outside a Rails app</summary>

  ```
  The most common rails commands are:
   generate     Generate new code (short-cut alias: "g")
   console      Start the Rails console (short-cut alias: "c")
   server       Start the Rails server (short-cut alias: "s")
   test         Run tests except system tests (short-cut alias: "t")
   test:system  Run system tests
   dbconsole    Start a console for the database specified in config/database.yml
                (short-cut alias: "db")
   new          Create a new Rails application. "rails new my_app" creates a
                new application called MyApp in "./my_app"
   plugin new   Create a new Rails railtie or engine

  All commands can be run with -h (or --help) for more information.
  ```
</details>



<details>
  <summary>After, inside a Rails app</summary>

  ```
  The most common rails commands are:
   generate     Generate new code (short-cut alias: "g")
   console      Start the Rails console (short-cut alias: "c")
   server       Start the Rails server (short-cut alias: "s")
   test         Run tests except system tests (short-cut alias: "t")
   test:system  Run system tests
   dbconsole    Start a console for the database specified in config/database.yml
                (short-cut alias: "db")
   new          Create a new Rails application. "rails new my_app" creates a
                new application called MyApp in "./my_app"
   plugin new   Create a new Rails railtie or engine

  All commands can be run with -h (or --help) for more information.
  In addition to those commands, there are:
    about
    action_mailbox:ingress:exim
    action_mailbox:ingress:postfix
    action_mailbox:ingress:qmail
    action_mailbox:install
    action_mailbox:install:migrations
    action_text:install
    action_text:install:migrations
    active_storage:install
    app:template
    app:update
    assets:clean[keep]
    assets:clobber
    assets:environment
    assets:precompile
    cache_digests:dependencies
    cache_digests:nested_dependencies
    credentials:diff
    credentials:edit
    credentials:show
    db:create
    db:drop
    db:encryption:init
    db:environment:set
    db:fixtures:load
    db:migrate
    db:migrate:down
    db:migrate:redo
    db:migrate:status
    db:migrate:up
    db:prepare
    db:reset
    db:rollback
    db:schema:cache:clear
    db:schema:cache:dump
    db:schema:dump
    db:schema:load
    db:seed
    db:seed:replant
    db:setup
    db:system:change
    db:version
    destroy
    dev:cache
    encrypted:edit
    encrypted:show
    importmap:install
    initializers
    log:clear
    middleware
    notes
    restart
    routes
    routes:invoke_command
    runner
    runner:looks_like_a_file_path?
    secret
    secrets:edit
    secrets:setup
    secrets:show
    stats
    stimulus:install
    stimulus:install:importmap
    stimulus:install:node
    test:all
    test:channels
    test:controllers
    test:db
    test:generators
    test:helpers
    test:integration
    test:jobs
    test:mailboxes
    test:mailers
    test:models
    time:zones[country_or_offset]
    tmp:clear
    tmp:create
    turbo:install
    turbo:install:importmap
    turbo:install:node
    turbo:install:redis
    version
    yarn:install
    zeitwerk:check
  ```
</details>

> This can be confusing to users when they probably want to see the common Rails commands.

Looking back at #40823, I can see both sides of the argument re: https://github.com/rails/rails/issues/40823#issuecomment-745371193.  But it is weird to have `rails --help` behave differently depending on the working directory.  So, overall, I think this is good. :+1:

> Outside a Rails application we never show the extended commands: db:migrate, etc...
> The extended commands require a Rails application. They also take up a lot screen space.

Most of the common commands also require a Rails application.  So I think it would be reasonable to show the common commands for `rails` (with no args) and the extended commands for `rails -h`, regardless of the working directory.

> * `bin/rails`    outputs the help for the common commands
> * `bin/rails -h` outputs the help for the common commands and the extended commands

Currently (in this PR), `rails help` and `bin/rails help` output the common commands only.  I think it would be good to make them output the extended commands too, the same as `rails -h`.

One more thing that I wanted to point out: if a user types `rails my_cool_app` (instead of `rails new my_cool_app`) outside of a Rails app directory, they will still be shown the help for `rails new`.  I think that is very good.  It might be worth adding a test for it.

**Comment by p8** [comment]
Thanks @jonathanhefner for the extensive review 🙇 
I'll make the suggested changes.

**Comment by p8** [comment]
> Currently (in this PR), `rails help` and `bin/rails help` output the common commands only. I think it would be good to make them output the extended commands too, the same as `rails -h`.

I tried implementing this for calling `rails help` outside a rails application directory.
But even showing the extended commands requires an application directory to load the Rake tasks.
Without these the rails command fails.

**Comment by p8** [comment]
> One more thing that I wanted to point out: if a user types rails my_cool_app (instead of rails new my_cool_app) outside of a Rails app directory, they will still be shown the help for rails new. I think that is very good. It might be worth adding a test for it.

If I run `rails generate -h` outside a Rails app directory I also get the help for rails new.
Which is kind of confusing when the USAGE states:
`All commands can be run with -h (or --help) for more information.`

**Comment by jonathanhefner** [comment]
> But even showing the extended commands requires an application directory to load the Rake tasks.
> Without these the rails command fails.
> Maybe I can get it to work by requiring the tasks.

I suppose that instead of trying to unify the behavior regardless of working directory, we could embrace the dichotomy.  For example, outside of an app directory, all help commands (`rails`, `rails -h`, `rails help`) could print:

```
You must specify a command:

  new          Create a new Rails application. "rails new my_app" creates a
               new application called MyApp in "./my_app"
  plugin new   Create a new Rails railtie or engine

Inside a Rails application directory, some common commands are:

  console      Start the Rails console
  server       Start the Rails server
  test         Run tests except system tests

All commands can be run with -h (or --help) for more information.
```

And, inside an app directory, all help commands could print:

```
You must specify a command. The most common commands are:

  generate     Generate new code (short-cut alias: "g")
  console      Start the Rails console (short-cut alias: "c")
  server       Start the Rails server (short-cut alias: "s")
  test         Run tests except system tests (short-cut alias: "t")
  test:system  Run system tests
  dbconsole    Start a console for the database specified in config/database.yml
               (short-cut alias: "db")
  plugin new   Create a new Rails railtie or engine

All commands can be run with -h (or --help) for more information.

In addition to those commands, there are:

#{extended_command_list}
```

(Kind of related to your changes in #46837.)

> > One more thing that I wanted to point out: if a user types rails my_cool_app (instead of rails new my_cool_app) outside of a Rails app directory, they will still be shown the help for rails new. I think that is very good. It might be worth adding a test for it.
>
> If I run `rails generate -h` outside a Rails app directory I also get the help for rails new.
> Which is kind of confusing when the USAGE states:
> `All commands can be run with -h (or --help) for more information.`

I think splitting the commands like above or in #46837 helps with that.

Also, revisiting what I said about `rails my_cool_app`, it might be nice to prepend a "Did you mean?" to the `rails new` help.  For example:

```console
$ rails my_cool_app
Did you mean `rails new my_cool_app`?

Usage:
  rails new APP_PATH [options]

Options:
...
```

That might offer a clue if a user runs `rails generate -h` outside of an app directory, because it would print "Did you mean \`rails new generate\`?".

But I think that can be investigated in a separate PR.

**Comment by p8** [comment]
@jonathanhefner I've split the commands to inside and outside the application.
Adding DidYouMean to `rails my_cool_app` is something I could pick after this.

File: railties/lib/rails/command.rb [hunk 2]
```diff
@@ -89,7 +84,9 @@ def root
       def printing_commands # :nodoc:
         lookup!
 
-        (subclasses - hidden_commands).flat_map(&:printing_commands)
+        visible_commands = (subclasses - hidden_commands).flat_map(&:printing_commands)
+
+        (visible_commands - COMMANDS_IN_USAGE).sort
```
Comment (jonathanhefner) [inline railties/lib/rails/command.rb:89]: This won't work because `visible_commands` is an array of tuples (e.g. `[["command_name", "description"], ...]`), and `COMMANDS_IN_USAGE` is an array of names.

Also, though, I'm not sure if we should perform this filtering here.  It seems like a concern of `HelpCommand` (and of `HelpCommand#help_extended` specifically).  Or is there a reason we want to do this filtering centrally?

Comment (p8) [reply railties/lib/rails/command.rb:89]: Hmm, weird I moved COMMANDS_IN_USAGE in https://github.com/rails/rails/commit/f52b1ccd0d637cfb9911ddf3b118b7e2c5ad5b49 with the exact same reason 🙂 .
I'll fix this...

File: railties/lib/rails/commands/help/help_command.rb [hunk 3]
```diff
@@ -7,20 +7,14 @@ class HelpCommand < Base # :nodoc:
...
+      def help_extended(*)
+        help
 
-        def printing_commands_not_in_usage # :nodoc:
-          Rails::Command.printing_commands.reject do |command, _|
-            command.in?(COMMANDS_IN_USAGE)
-          end
-        end
+        say "In addition to those commands, there are:"
+        print_table(Rails::Command.printing_commands, indent: 1, truncate: true)
```
[the remark this answers is not in the document]
Comment (p8) [reply railties/lib/rails/commands/help/help_command.rb:16]: Yes, I think we can remove the indent.

File: railties/lib/rails/commands/help/help_command.rb [hunk 4]
```diff
@@ -7,20 +7,14 @@ class HelpCommand < Base # :nodoc:
...
-        private_constant :COMMANDS_IN_USAGE
+      def help_extended(*)
+        help
 
-        def printing_commands_not_in_usage # :nodoc:
-          Rails::Command.printing_commands.reject do |command, _|
-            command.in?(COMMANDS_IN_USAGE)
-          end
-        end
+        say "In addition to those commands, there are:"
```
[the remark this answers is not in the document]
Comment (p8) [reply railties/lib/rails/commands/help/help_command.rb:15]: 👍

File: railties/lib/rails/command.rb (hunk 2 above)
Comment (p8) [reply railties/lib/rails/command.rb]: I've added assertions to make sure the commands are filtered.

File: railties/lib/rails/commands/help/help_command.rb (hunk 3 above)
[the remark this answers is not in the document]
Comment (p8) [reply railties/lib/rails/commands/help/help_command.rb]: I've removed the indent.

**Comment by jonathanhefner** [comment]
Thank you, @p8! :sos:

**Comment by p8** [comment]
Thanks @jonathanhefner ❤️ !
