### PR TITLE
Fix `upsert` warning for MySQL

### LINKED ISSUE #51268: ActiveRecord.upset generates a databases warning with MySQL 8
### Steps to reproduce

When using MySQL 8.0.34 `ActiveRecord.upset` causes a database warning 

```ruby
ActiveRecord::Schema.define do
  create_table :products, force: true do |t|
    t.text :handle
    t.text :title
  end
end

class Product < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_upsert
    id = Product.where(handle: handle).pick(:id)
    Product.upsert({
      id:,
      handle: handle,
      title:,
    })
  end
end
```

I think the query is generated from here
https://github.com/rails/rails/blob/f7353283fd771e99b9675bcb9394e398964195f8/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L653-L654

### Expected behavior

The generated query should be compatible with the future database release.

### Actual behavior

Getting a warning code `1287` 

```
#<ActiveRecord::SQLWarning:
'VALUES function' is deprecated and will be removed in a future release.
Please use an alias (INSERT INTO ... VALUES (...) AS alias) and replace VALUES(col)
in the ON DUPLICATE KEY UPDATE clause with alias.col instead>
```

And `ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter#handle_warnings` is causing visible overhead

### System configuration
**Rails version**:

**Ruby version**:

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #51268.

The code looks scary we these `if`s, but I am not sure we will make it much better extracting pieces into some other places.

### CODE REVIEW

**Comment by casperisfine** [comment]
That aliasing doesn't work on MySQL 5?

**Comment by casperisfine** [comment]
Seems like not :/

File: activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb [hunk 1]
```diff
@@ -639,18 +639,34 @@ def default_index_type?(index) # :nodoc:
       end
 
       def build_insert_sql(insert) # :nodoc:
-        sql = +"INSERT #{insert.into} #{insert.values_list}"
+        new_on_duplicate_syntax = (!mariadb? && database_version >= "8.0.0")
+
+        if new_on_duplicate_syntax
```
[the remark this answers is not in the document]
Comment (fatkodima) [reply activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb]: > I think I'd prefer a single top level if `new_on_duplicate_syntax` even if that means some level of duplication.

This was my original thought. Updated with this version.

File: activerecord/test/cases/insert_all_test.rb [hunk 2]
```diff
@@ -336,6 +337,22 @@ def test_upsert_logs_message_including_model_name
     end
   end
 
+  def test_upsert_and_db_warnings
+    skip unless supports_insert_on_duplicate_update?
+
+    begin
+      with_db_warnings_action(:raise) do
```
Comment (casperisfine) [inline activerecord/test/cases/insert_all_test.rb:344]: Not worth doing here, more for a followup, but I wonder if it would make sense to run CI/tests with DB warnings treated as errors by default. I think it might have caught this issue way sooner.

Also we probably should backport that fix.

File: activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb [hunk 3]
```diff
@@ -639,18 +639,37 @@ def default_index_type?(index) # :nodoc:
...
+        if !mariadb? && database_version >= "8.0.0"
+          values_alias = quote_table_name("#{insert.model.table_name}_values")
+          sql = +"INSERT #{insert.into} #{insert.values_list} AS #{values_alias}"
+
+          if insert.skip_duplicates?
+            sql << " ON DUPLICATE KEY UPDATE #{no_op_column}=#{values_alias}.#{no_op_column}"
+          elsif insert.update_duplicates?
+            sql << " ON DUPLICATE KEY UPDATE "
+            if insert.raw_update_sql?
+              sql << insert.raw_update_sql
```
Comment (gabriel-amaral) [inline activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:654]: > Note: we have been ignoring the MySQL warning

Currently, we have a couple of places that provide a `raw_update_sql` pointing to the `VALUES(...)`, which, with this change, created a mixed query:

```
INSERT table (...) VALUES (...) as table_alias ON DUPLICATE KEY UPDATE x=VALUES(x)
```

The query didn't work as expected, and the expected behavior broke. We may need some way to keep using the previous behavior for a while. (I'm working on a PR unless someone beat me)

cc: @matthewd

Comment (rafaelfranca) [reply activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:654]: Yes. If the `raw_update_sql` is provided, we should not try to alias, because we don't even know the alias.

Comment (gabriel-amaral) [reply activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:654]: Created this [PR](https://github.com/rails/rails/pull/51325) to address this issue.
