### PR TITLE
Do not use `Arel.star` when `ignored_columns`

### LINKED ISSUE #27914: AR::Base#reload and ignored_columns
The `ignored_columns` list is ignored after you do `reload` on a record:

On master:

```ruby
require 'bundler/setup'
require 'active_record'
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "users" do |t|
    t.string "name"
    t.integer "age"
  end
end

class User < ActiveRecord::Base
  self.ignored_columns = ["age"]
end

class BugTest < Minitest::Test
  def test_association_stuff
    user = User.create!
    refute user.respond_to?(:age) # passes
    refute user.respond_to?(:age=) # passes
    user.reload
    refute user.respond_to?(:age) # test fails here because `age` is not available
  end
end
```

I guess this happens because on reload we do `SELECT *`.
Do we consider it as a bug?

@sgrif @matthewd

### PR DESCRIPTION
**Pull request by sobrinho**
Closes #27918

Closes #27914

### CODE REVIEW

**Comment by sobrinho** [comment]
cc @rafaelfranca

**Comment by rafaelfranca** [comment]
Let me know when the tests are green

**Comment by sobrinho** [comment]
@rafaelfranca the failures aren't related to this change anymore (not sure why they are happening at all now, maybe an intermittent failure).

I'm not sure if this is going to the right direction, can you please review the test changes and confirm this is the way to go?

File: activerecord/test/cases/scoping/default_scoping_test.rb [hunk 1]
```diff
@@ -118,76 +118,76 @@ def test_unscope_after_reordering_and_combining
   end
 
   def test_unscope_with_where_attributes
-    expected = Developer.order("salary DESC").collect(&:name)
-    received = DeveloperOrderedBySalary.where(name: "David").unscope(where: :name).collect(&:name)
+    expected = Developer.order("salary DESC").order(:name).collect(&:name)
```
Comment (rafaelfranca) [inline activerecord/test/cases/scoping/default_scoping_test.rb]: Do you remember why we need to add a new order here?

**Review by rafaelfranca — COMMENTED** [review]
Changes looks good to me. Only one question. Restarted the jobs to see if they now pass.

File: activerecord/test/cases/scoping/default_scoping_test.rb (hunk 1 above)
Comment (sobrinho) [reply activerecord/test/cases/scoping/default_scoping_test.rb]: The build was resulting in a different order between expected and received, I normalized both by using a predictable order.

Not sure why it started to fail in this PR but I have assumed that Postgres changed the order of the results for some reason (there is no guarantee in the order of the results in Postgres unless specified, in that case, if the salary is the same we do not have a guaranteed order of the records [there is but it is the order of the record on the disk that may vary from time to time]).

In the other hand, I'm not sure if this is the real problem but since this PR change should not impact on this test at all I assumed it was that.

**Comment by sobrinho** [comment]
@rafaelfranca the build is green now 🤘 :shipit:

File: activerecord/test/cases/scoping/default_scoping_test.rb (hunk 1 above)
Comment (joevandyk) [reply activerecord/test/cases/scoping/default_scoping_test.rb]: might be better to do `assert_equal(expected.sort, received.sort)`

File: activerecord/test/cases/adapters/mysql2/explain_test.rb [hunk 2]
```diff
@@ -1,23 +1,23 @@
...
 class Mysql2ExplainTest < ActiveRecord::Mysql2TestCase
-  fixtures :developers
+  fixtures :authors
 
   def test_explain_for_one_query
-    explain = Developer.where(id: 1).explain
-    assert_match %(EXPLAIN for: SELECT `developers`.* FROM `developers` WHERE `developers`.`id` = 1), explain
-    assert_match %r(developers |.* const), explain
+    explain = Author.where(id: 1).explain
+    assert_match %(EXPLAIN for: SELECT `authors`.* FROM `authors` WHERE `authors`.`id` = 1), explain
```
Comment (kamipo) [inline activerecord/test/cases/adapters/mysql2/explain_test.rb]: Why are you changing mysql2's tests only from Developer to Author?

File: activerecord/test/cases/scoping/default_scoping_test.rb [hunk 3]
```diff
@@ -470,9 +470,9 @@ def test_default_scope_with_references_works_with_find_by
   end
 
   test "a scope can remove the condition from the default scope" do
-    scope = DeveloperCalledJamis.david2
+    scope = DeveloperCalledJamis.jamis2
     assert_equal 1, scope.where_clause.ast.children.length
-    assert_equal Developer.where(name: "David"), scope
+    assert_equal DeveloperCalledJamis.where("salary < 10000").to_a, scope.to_a
```
Comment (kamipo) [inline activerecord/test/cases/scoping/default_scoping_test.rb]: Is this change necessary?

File: activerecord/test/cases/scoping/default_scoping_test.rb (hunk 1 above)
Comment (kamipo) [reply activerecord/test/cases/scoping/default_scoping_test.rb]: Yeah, we've used `sort` and `sort_by` for that. 75cfb3dbdbb520147a532bd92ad6111c0e2ebf88 93c65ae4efd62933618193c088ed1dadef47793d 625bdb164ed7cb06dd88bec57c338b63460628d7

File: activerecord/test/cases/adapters/mysql2/explain_test.rb (hunk 2 above)
Comment (sobrinho) [reply activerecord/test/cases/adapters/mysql2/explain_test.rb]: The original author wanted to keep the EXPLAIN with the STAR and for that, the model had to be changed.

I can update the EXPLAIN test to keep the Developer model and update the regexp to match against the new query.

What do you think?

File: activerecord/test/cases/scoping/default_scoping_test.rb (hunk 3 above)
Comment (sobrinho) [reply activerecord/test/cases/scoping/default_scoping_test.rb]: I have no idea, I left as the original author wrote, I will try to revert that and see what happen.

File: activerecord/test/cases/scoping/default_scoping_test.rb (hunk 1 above)
Comment (sobrinho) [reply activerecord/test/cases/scoping/default_scoping_test.rb]: Pretty much the same, should I change it to sort in ruby instead of the database?

File: activerecord/test/cases/adapters/mysql2/explain_test.rb (hunk 2 above)
Comment (rafaelfranca) [reply activerecord/test/cases/adapters/mysql2/explain_test.rb]: I think it is better to fix all other explain tests to use Author to not have a fragile test that will have to change every time the list of ignored column at Developers change.

File: activerecord/test/cases/scoping/default_scoping_test.rb (hunk 1 above)
Comment (rafaelfranca) [reply activerecord/test/cases/scoping/default_scoping_test.rb]: I prefer to because of the already existing `order` that we have on those tests

File: activerecord/test/cases/adapters/mysql2/explain_test.rb (hunk 2 above)
Comment (sobrinho) [reply activerecord/test/cases/adapters/mysql2/explain_test.rb]: I'm thinking in creating a specific model for that feature, in that way the model will be exclusive for that feature and won't break anything around that.

Or even use something like that:

```ruby
test '...' do
  begin
    Developer.ignored_columns = [:first_name, :last_name]

    assertions here
  ensure
    Developer.ignored_columns = []
  end
end
```

What you think?

Comment (rafaelfranca) [reply activerecord/test/cases/adapters/mysql2/explain_test.rb]: I think changing to author is a good solution already that doesn't require adding any new code.

Comment (sobrinho) [reply activerecord/test/cases/adapters/mysql2/explain_test.rb]: So change the other specs to use author too?

Comment (rafaelfranca) [reply activerecord/test/cases/adapters/mysql2/explain_test.rb]: Yeah :+1:

**Comment by sobrinho** [comment]
@rafaelfranca can you take a look again?

**Review by rafaelfranca — CHANGES_REQUESTED** [review]
:+1: Can you squash your commits?

**Comment by sobrinho** [comment]
@rafaelfranca like this?

**Comment by rafaelfranca** [comment]
This works, but you could at least three commits in your PR because they were atomic.

**Comment by sobrinho** [comment]
@rafaelfranca done!

**Review by rafaelfranca — APPROVED** [review]

**Comment by rafaelfranca** [comment]
Thanks! I'll merge in a minute
