### PR TITLE
Adjust docs of create_or_find_by

### LINKED ISSUE #36027: create_or_find_by doesn't attempt to find the record when you also have validates_uniqueness_of :field
### Steps to reproduce
``` ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :email
    t.index :email, unique: true
  end

  create_table :comments, force: true do |t|
    t.string :email
    t.index :email, unique: true
  end
end

class Post < ActiveRecord::Base
end

class Comment < ActiveRecord::Base
  validates :email, uniqueness: true
end

class BugTest < Minitest::Test
  def test_without_validation
    count = Post.count
    post = Post.create_or_find_by!(email: 'test@example.com')
    assert_equal count+1, Post.count

    post2 = Post.create_or_find_by!(email: 'test@example.com')
    assert_equal count+1, Post.count # count didn't change
    assert_equal post.id, post2.id
  end

  def test_with_validation
    count = Comment.count
    comment = Comment.create_or_find_by!(email: 'test@example.com')
    assert_equal count+1, Comment.count

    # raises ActiveRecord::RecordInvalid: Validation failed: Email has already been taken
    comment2 = Comment.create_or_find_by!(email: 'test@example.com')
    assert_equal count+1, Comment.count
    assert_equal comment.id, comment2.id
  end
end
```

### Expected behavior
`create_or_find_by` should find the existing record when there is a uniqueness validation on the field.

### Actual behavior
An `ActiveRecord::RecordInvalid` exception is raised because the record is validated before it is created, which checks the database and finds an existing record. `create_or_find_by` doesn't get the `ActiveRecord::RecordNotUnique` exception it is expecting so it doesn't attempt to `find` the record.

### System configuration
**Rails version**: master

**Ruby version**: ruby 2.5.3p105

### PR DESCRIPTION
**Pull request by intrip**
### Summary

- Mention explicitly in the docs that `create_of_find_by` requires a DB constraint.

Closes #36027

### CODE REVIEW

**Comment by intrip** [comment]
@alexcameron89 since you were involved in the issue can you take a peek 🙏 ?

**Comment by zzak** [comment]
@intrip TIL we probably don't want to use `[ci skip]` anymore since even spellcheck is run in CI 😆

**Comment by intrip** [comment]
> @intrip TIL we probably don't want to use `[ci skip]` anymore since even spellcheck is run in CI 😆 So would you mind removing it from the PR description and commit messages (if any)?

@zzak 😮  thanks for the tip! I've removed the `[ci skip]` and the linter ran successfully.

Do we have already a PR to remove the outdated comment in the guides https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation ?
"For documentation changes, your pull request title should include **[ci skip]**. This will skip running..."

If not I'll be happy to make one.

File: activerecord/lib/active_record/relation.rb [hunk 1]
```diff
@@ -182,18 +182,19 @@ def find_or_create_by!(attributes, &block)
       find_by(attributes) || create!(attributes, &block)
     end
 
-    # Attempts to create a record with the given attributes in a table that has a unique constraint
+    # Attempts to create a record with the given attributes in a table that has a unique DB constraint
```
Comment (eileencodes) [inline activerecord/lib/active_record/relation.rb:185]:
```suggestion
    # Attempts to create a record with the given attributes in a table that has a unique database constraint
```

File: activerecord/lib/active_record/relation.rb [hunk 2]
```diff
@@ -182,18 +182,19 @@ def find_or_create_by!(attributes, &block)
...
     # on one or several of its columns. If a row already exists with one or several of these
     # unique constraints, the exception such an insertion would normally raise is caught,
     # and the existing record with those attributes is found using #find_by!.
     #
     # This is similar to #find_or_create_by, but avoids the problem of stale reads between the SELECT
     # and the INSERT, as that method needs to first query the table, then attempt to insert a row
-    # if none is found.
+    # if none is found. The use of this method is suggested when #find_by! rarely returns a record,
```
Comment (eileencodes) [inline activerecord/lib/active_record/relation.rb:192]: This new addition is unclear. Reading this I'm thinking when is a record rarely returned? I think what you mean is when you want to find or create use that otherwise use find. I don't think we use `find_or_create` when there's rarely a record, it's used for specific application behavior when you absolutely want a record to exist - usually in the case of a transaction rollback due to a uniqueness constraint.

File: activerecord/lib/active_record/relation.rb [hunk 3]
```diff
@@ -182,18 +182,19 @@ def find_or_create_by!(attributes, &block)
...
+    # otherwise it's suggested to use #find_or_create_by.
     #
     # There are several drawbacks to #create_or_find_by, though:
     #
-    # * The underlying table must have the relevant columns defined with unique constraints.
+    # * The underlying table must have the relevant columns defined with unique DB constraints.
```
Comment (eileencodes) [inline activerecord/lib/active_record/relation.rb:197]:
```suggestion
    # * The underlying table must have the relevant columns defined with unique database constraints.
```

**Review by eileencodes — CHANGES_REQUESTED** [review]

**Comment by alexcameron89** [comment]
I second the feedback that Eileen provided, and I had one additional thought: I find the documentation confusing to read, what do you think of clarifying it as well:
> This method will return a record if all given attributes are covered by unique constraints (unless the INSERT -> DELETE -> SELECT race condition is triggered), but if creation was attempted and failed due to validation errors it won't be persisted, you get what #create returns in such situation.

It took me a few times to read it and test it out myself to understand that it's saying essentially that validations may case the record creation to fail, and instead of returning the record, it returns a non-persisted record with errors, resembling the result of calling `Model.create(attributes)`. What do you think of changing it to something like:

"This method will return a record if all given attributes are covered by unique constraints (unless the INSERT -> DELETE -> SELECT race condition is triggered). If the record's model contains validations and creation fails due to errors from validations, then the record will not be persisted, and in this case you get what the #create method would return in such a situation."

Feel free to re-word that or ignore the feedback altogether! 😄

**Comment by zzak** [comment]
> @zzak 😮 thanks for the tip! I've removed the [ci skip] and the linter ran successfully.

@intrip Done in 6faacea222 :bow:

File: activerecord/lib/active_record/relation.rb (hunk 2 above)
Comment (intrip) [reply activerecord/lib/active_record/relation.rb]: This is a poor rephrase of: 
>"I believe the intent of the method create_or_find_by is to get to get to the INSERT portion as fast as it can, and this is helpful for tables where find_by rarely returns a record (meaning you're going to INSERT much more than you're going to find the record). "

Honestly after re-reading I don't think this would add much value, if you don't mind I've just removed such addition.

Apologies for my lack of English skills 😞

**Comment by intrip** [comment]
@eileencodes Thanks for the review! 

I've applied the suggestions and removed the unclear addition.

@alexcameron89 thanks for the comment! Honestly I didn't find any difficulties in understanding such part but if you have strong opinion on that I don't mind updating it as well.

**Review by alexcameron89 — APPROVED** [review]
That looks great, thank @intrip! 👍
