### PR TITLE
[ci skip] Fix the API docs for Bi-directional associations

### LINKED ISSUE #20528: inverse_of option without an object has been shared
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations.rb#L965

And it came to share the object automatically is from version 4.1.0.

```ruby
gem "activerecord", ">= 4.1.0"
require "active_record"

ActiveRecord::Base.logger = ActiveSupport::Logger.new(STDOUT)
ActiveSupport::LogSubscriber.colorize_logging = false
ActiveRecord::Migration.verbose = false
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Schema.define do
  create_table :dungeons do |t|
    t.integer :level
  end
  create_table :traps do |t|
    t.belongs_to :dungeon
  end
  create_table :evil_wizards do |t|
    t.belongs_to :dungeon
  end
end

class Dungeon < ActiveRecord::Base
  has_many :traps
  has_one :evil_wizard
end

class Trap < ActiveRecord::Base
  belongs_to :dungeon
end

class EvilWizard < ActiveRecord::Base
  belongs_to :dungeon
end

dungeon = Dungeon.create!
dungeon.traps.create!
dungeon.create_evil_wizard!

d = Dungeon.first
t = d.traps.first
d.level == t.dungeon.level # => true
d.level = 10
d.level == t.dungeon.level # => true
# >>    (0.4ms)  CREATE TABLE "dungeons" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "level" integer) 
# >>    (0.1ms)  CREATE TABLE "traps" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "dungeon_id" integer) 
# >>    (0.1ms)  CREATE TABLE "evil_wizards" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "dungeon_id" integer) 
# >>    (0.0ms)  begin transaction
# >>   SQL (0.1ms)  INSERT INTO "dungeons" DEFAULT VALUES
# >>    (0.0ms)  commit transaction
# >>    (0.0ms)  begin transaction
# >>   SQL (0.1ms)  INSERT INTO "traps" ("dungeon_id") VALUES (?)  [["dungeon_id", 1]]
# >>    (0.0ms)  commit transaction
# >>    (0.0ms)  begin transaction
# >>   SQL (0.1ms)  INSERT INTO "evil_wizards" ("dungeon_id") VALUES (?)  [["dungeon_id", 1]]
# >>    (0.0ms)  commit transaction
# >>   EvilWizard Load (0.1ms)  SELECT  "evil_wizards".* FROM "evil_wizards" WHERE "evil_wizards"."dungeon_id" = ? LIMIT 1  [["dungeon_id", 1]]
# >>   Dungeon Load (0.1ms)  SELECT  "dungeons".* FROM "dungeons"  ORDER BY "dungeons"."id" ASC LIMIT 1
# >>   Trap Load (0.2ms)  SELECT  "traps".* FROM "traps" WHERE "traps"."dungeon_id" = ?  ORDER BY "traps"."id" ASC LIMIT 1  [["dungeon_id", 1]]
```

### PR DESCRIPTION
**Pull request by repinel**
The examples now take in consideration when [Active Record finds inverse
associations automatically](https://github.com/rails/rails/pull/9522).

Fix #20528

### CODE REVIEW

File: activerecord/lib/active_record/associations.rb [hunk 1]
```diff
@@ -955,35 +955,53 @@ def association_instance_set(name, association)
     # The +traps+ association on +Dungeon+ and the +dungeon+ association on +Trap+ are
     # the inverse of each other and the inverse of the +dungeon+ association on +EvilWizard+
     # is the +evil_wizard+ association on +Dungeon+ (and vice-versa). By default,
-    # Active Record doesn't know anything about these inverse relationships and so no object
-    # loading optimization is possible. For example:
+    # Active Record uses an automatic guessing of the inverse association based on the name
```
Comment (zzak) [inline activerecord/lib/active_record/associations.rb]: "Active Record can guess the inverse of the association based on the name.."

File: activerecord/lib/active_record/associations.rb [hunk 2]
```diff
@@ -955,35 +955,53 @@ def association_instance_set(name, association)
...
+    # of the class. The result is the following:
     #
     #    d = Dungeon.first
     #    t = d.traps.first
     #    d.level == t.dungeon.level # => true
     #    d.level = 10
-    #    d.level == t.dungeon.level # => false
+    #    d.level == t.dungeon.level # => true
```
Comment (zzak) [inline activerecord/lib/active_record/associations.rb]: This example doesn't make sense to me..

File: activerecord/lib/active_record/associations.rb [hunk 3]
```diff
@@ -955,35 +955,53 @@ def association_instance_set(name, association)
...
     #
     # The +Dungeon+ instances +d+ and <tt>t.dungeon</tt> in the above example refer to
-    # the same object data from the database, but are actually different in-memory copies
-    # of that data. Specifying the <tt>:inverse_of</tt> option on associations lets you tell
+    # the same in-memory instance thanks the heuristic applied. For this similar case:
```
Comment (zzak) [inline activerecord/lib/active_record/associations.rb]: Not sure this is an improvement.

File: activerecord/lib/active_record/associations.rb [hunk 4]
```diff
@@ -955,35 +955,53 @@ def association_instance_set(name, association)
...
     #
     #    class Dungeon < ActiveRecord::Base
-    #      has_many :traps, inverse_of: :dungeon
+    #      has_many :traps, inverse_of: :special_dungeon
     #      has_one :evil_wizard, inverse_of: :dungeon
     #    end
     #
     #    class Trap < ActiveRecord::Base
-    #      belongs_to :dungeon, inverse_of: :traps
+    #      belongs_to :special_dungeon, class_name: 'Dungeon', foreign_key: :dungeon_id, inverse_of: :traps
```
Comment (zzak) [inline activerecord/lib/active_record/associations.rb]: Doesn't this complicate the example?

File: activerecord/lib/active_record/associations.rb [hunk 5]
```diff
@@ -955,35 +955,53 @@ def association_instance_set(name, association)
...
     #    end
     #
     #    class EvilWizard < ActiveRecord::Base
     #      belongs_to :dungeon, inverse_of: :evil_wizard
     #    end
     #
-    # Then, from our code snippet above, +d+ and <tt>t.dungeon</tt> are actually the same
+    # Then, from the same snippet, +d+ and <tt>t.dungeon</tt> are actually the same
```
Comment (zzak) [inline activerecord/lib/active_record/associations.rb]: If we're going to show the code above, this should stay the same.

**Comment by repinel** [comment]
@zzak Thanks for the feedback!

I shrunk the changes to avoid over complicating the docs. I still have the example in a similar way, so let me know if it's clear.

**Comment by zzak** [comment]
@repinel This is much more clear, thank you!!

**Comment by repinel** [comment]
Thanks :heart:
