### PR TITLE
Fix `pluck` and `select` with `from` if `from` has original table name

### LINKED ISSUE #35359: Ambiguous column name when using `scope.from`
We bumped GitHub to test Rails 6 and had a bunch of failures.

One of them was like this:

```
Column 'id' in field list is ambiguous
```

After doing a bisect I found this commit was the cause https://github.com/rails/rails/commit/0ee96d13de29680e148ccb8e5b68025f29fd091c (cc/ @kamipo) but wasn't immediately able to reproduce it and wanted to verify we weren't doing something weird before pinging you.

It seems that this happens when we use `from` on a given `scope` and then `pluck` from that scope.

Here's a reproduction script with SQLite3:

```ruby
# frozen_string_literal: true

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t| 
    t.string :title
    t.integer :author_id
  end 

  create_table :categories, force: true do |t| 
    t.string :name
  end 

  create_table :categorizations, force: true do |t| 
    t.integer :post_id
    t.integer :category_id
  end 
end

class Post < ActiveRecord::Base
  has_many :categorizations
  has_many :categories, through: :categorizations
end

class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :posts, through: :categorizations
end

class Categorization < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

class BugTest < Minitest::Test
  def test_association_stuff
    p = Post.create!(title: "a post")

    p.categorizations.build(category: Category.create!(name: "a category"))

    scope = p.categories
    # this is the problematic line
    scope = scope.from("#{scope.quoted_table_name}")
    # throws a ambiguous column error
    scope.joins(:posts).pluck(:id)
  end
end
```

With this change the sql looks like:

```sql
SELECT "id" FROM "categories" INNER JOIN "categorizations" "categorizations_categories_join" ON "categorizations_categories_join"."category_id" = "categories"."id" INNER JOIN "posts" ON "posts"."id" = "categorizations_categories_join"."post_id" INNER JOIN "categorizations" ON "categories"."id" = "categorizations"."category_id" WHERE "categorizations"."post_id" = ?  [["post_id", 1]]
```

Without the change the sql looks like:

```sql
SELECT "categories"."id" FROM "categories" INNER JOIN "categorizations" "categorizations_categories_join" ON "categorizations_categories_join"."category_id" = "categories"."id" INNER JOIN "posts" ON "posts"."id" = "categorizations_categories_join"."post_id" INNER JOIN "categorizations" ON "categories"."id" = "categorizations"."category_id" WHERE "categorizations"."post_id" = ?  [["post_id", 1]]
```

cc/ @tenderlove @jhawthorn @cpruitt for visibility

### PR DESCRIPTION
**Pull request by kamipo**
This is caused by 0ee96d1.

Since #18744, `select` columns doesn't be qualified by table name if
using `from`. 0ee96d1 follows that for `pluck` as well.

But people depends that `pluck` columns are qualified even if using
`from`.

So I've fixed that to be qualified if `from` has the original table name
to keep the behavior as much as before.

Fixes #35359.

cc @eileencodes

### CODE REVIEW

File: activerecord/test/cases/relations_test.rb [hunk 1]
```diff
@@ -182,6 +182,42 @@ def test_finding_with_subquery_without_select_does_not_change_the_select
...
+  def test_pluck_with_quoted_original_table_name_in_from
+    relation = Comment.joins(:post).order(:id)
+    subquery = Comment.from(Comment.quoted_table_name).joins(:post).order(:id)
+    assert_equal relation.pluck(:id), subquery.pluck(:id)
+  end
+
+  def test_select_with_subquery_in_from_uses_original_table_name
+    relation = Comment.joins(:post).select(:id).order(:id)
+    subquery = Comment.from(Comment.all, Comment.quoted_table_name).joins(:post).select(:id).order(:id)
+    assert_equal relation.map(&:id), subquery.map(&:id)
```
Comment (kamipo) [inline activerecord/test/cases/relations_test.rb]: Weird... This test isn't failed locally... I suspect a bug on SQLite3...

https://travis-ci.org/rails/rails/jobs/496726410#L1198-L1208

Comment (rafaelfranca) [reply activerecord/test/cases/relations_test.rb]: It did fail on buildkite as well https://buildkite.com/rails/rails/builds/58981

Comment (kamipo) [reply activerecord/test/cases/relations_test.rb]: ah... skipped on buildkite as well for now a333ba3f7f24dff3c50c7cf26a2fe2caa748a851.
