### PR TITLE
Fix unscope with subquery

### LINKED ISSUE #26323: `unscope` causes too many parameters to be supplied when used with subquery
### Steps to reproduce

I've created [this minimal example](https://gist.github.com/Midnighter/8ddfad43ea22515f8a4bf3d480d6d58e).
### Expected behavior

In the test case `test_subquery_unscope`  `p2` and `p3` are `ActiveRecord::Relation`s thus causing a subquery with a join to be used. Using `unscope` to remove the first condition, I expect the query to work and only the parameters from `p3` to be applied.
### Actual behavior

The SQL generated includes both the parameters from `p2` _and_ `p3` thus supplying too many parameters and causing an `ActiveRecord::StatementInvalid` error. As can be seen in `test_avoid_subquery_unscope`, simplifying the first condition by using `p2.first` and thus avoiding a subquery there, unscope works as expected and the new condition with a subquery can be applied.
### System configuration

**Rails version**: master but also on 4.2.6 (haven't tested any others)

**Ruby version**:  ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

### PR DESCRIPTION
**Pull request by kamipo**
Currently cannot unscope subquery properly.
This commit fixes the issue.

Fixes #26323.

### CODE REVIEW

File: activerecord/lib/active_record/relation/where_clause.rb [hunk 1]
```diff
@@ -25,9 +25,27 @@ def merge(other)
       end
 
       def except(*columns)
+        offset = 0
+
         WhereClause.new(
-          predicates_except(columns),
-          binds_except(columns),
+          *predicates.each_with_object([[], []]) { |node, (prts, bvs)|
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/relation/where_clause.rb]: This method is too complicated. Can we refactor it so the code is more intention revealing?

Like what is `prts` and `bvs`?

What this loop is doing?

What that case is trying to find?

What that `unless` block is doing?

**Review by rafaelfranca — CHANGES_REQUESTED** [review]

**Comment by kamipo** [comment]
I refactored to keep the indentation of the original case statement to reduce the diff. I think it is easier to read than the previous implementation.

File: activerecord/lib/active_record/relation/where_clause.rb [hunk 2]
```diff
@@ -132,20 +129,32 @@ def invert_predicate(node)
...
+          except_binds = []
+          binds_index = 0
+
+          predicates = self.predicates.reject do |node|
             case node
             when Arel::Nodes::Between, Arel::Nodes::In, Arel::Nodes::NotIn, Arel::Nodes::Equality, Arel::Nodes::NotEqual, Arel::Nodes::LessThan, Arel::Nodes::LessThanOrEqual, Arel::Nodes::GreaterThan, Arel::Nodes::GreaterThanOrEqual
+              binds_contains = node.grep(Arel::Nodes::BindParam).size
               subrelation = (node.left.kind_of?(Arel::Attributes::Attribute) ? node.left : node.right)
               columns.include?(subrelation.name.to_s)
+            end.tap do |except|
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/relation/where_clause.rb]: This tap is confusing. Can you avoid it?

**Review by rafaelfranca — CHANGES_REQUESTED** [review]

File: activerecord/lib/active_record/relation/where_clause.rb [hunk 3]
```diff
@@ -132,20 +129,35 @@ def invert_predicate(node)
...
+          predicates = self.predicates.reject do |node|
+            except = \
+              case node
+              when Arel::Nodes::Between, Arel::Nodes::In, Arel::Nodes::NotIn, Arel::Nodes::Equality, Arel::Nodes::NotEqual, Arel::Nodes::LessThan, Arel::Nodes::LessThanOrEqual, Arel::Nodes::GreaterThan, Arel::Nodes::GreaterThanOrEqual
+                binds_contains = node.grep(Arel::Nodes::BindParam).size
+                subrelation = (node.left.kind_of?(Arel::Attributes::Attribute) ? node.left : node.right)
+                columns.include?(subrelation.name.to_s)
+              end
+
+            if except && binds_contains > 0
```
Comment (kamipo) [inline activerecord/lib/active_record/relation/where_clause.rb]: I avoided using `tap`.

**Review by rafaelfranca — APPROVED** [review]
