### PR TITLE
Fix #45339 attachments for new record within transaction

### LINKED ISSUE #45339: Attachments in a single transaction are uploaded multiple times
Rails: latest main (https://github.com/rails/rails/commit/34934071c61bcc89edb805ccc50430df93b96f73 currently).
Ruby: `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]`.

Reproduction script:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", ref: "main"
  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }

  config.active_storage.replace_on_assign_to_many = true
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true
end

class User < ActiveRecord::Base
  has_many_attached :files
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_upload_and_download
    user = User.create! do |user|
      user.files.attach \
        io: StringIO.new("hello"),
        content_type: "text/plain",
        filename: "1.txt"

      user.files.attach \
        io: StringIO.new("world"),
        content_type: "text/plain",
        filename: "2.txt"
    end

    assert_equal 2, user.files.count
  end
end
```

Expected: pass.

Actual:

```
Error:
BugTest#test_upload_and_download:
ActiveStorage::IntegrityError: ActiveStorage::IntegrityError
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/service/disk_service.rb:164:in `ensure_integrity_of'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/service/disk_service.rb:22:in `block in upload'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/notifications.rb:206:in `block in instrument'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/notifications.rb:206:in `instrument'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/service.rb:163:in `instrument'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/service/disk_service.rb:20:in `upload'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/app/models/active_storage/blob.rb:268:in `upload_without_unfurling'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/attached/changes/create_one.rb:28:in `upload'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/attached/changes/create_many.rb:23:in `each'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/attached/changes/create_many.rb:23:in `upload'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/core_ext/object/try.rb:15:in `public_send'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/core_ext/object/try.rb:15:in `try'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/attached/model.rb:200:in `block in has_many_attached'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:445:in `instance_exec'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:445:in `block in make_lambda'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:261:in `block in conditional'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:599:in `block in invoke_after'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:599:in `each'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:599:in `invoke_after'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:108:in `run_callbacks'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/callbacks.rb:929:in `_run_commit_callbacks'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/transactions.rb:321:in `committed!'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:177:in `commit_records'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:412:in `block in commit_transaction'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:396:in `commit_transaction'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:473:in `block in within_new_transaction'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:425:in `within_new_transaction'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/transactions.rb:302:in `save!'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/suppressor.rb:54:in `save!'
    /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activerecord/lib/active_record/persistence.rb:55:in `create!'
    bug.rb:59:in `test_upload_and_download'
```

With a debugger stopped at `ActiveStorage::Attached::Changes::CreateMany#upload`, `pending_uploads` contains two `ActiveStorage::Attached::Changes::CreateOneOfMany` objects for the first attachable:

```
[18, 27] in /Users/george/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rails-34934071c61b/activestorage/lib/active_storage/attached/changes/create_many.rb
   18:     def blobs
   19:       @blobs ||= subchanges.collect(&:blob)
   20:     end
   21: 
   22:     def upload
=> 23:       pending_uploads.each(&:upload)
   24:     end
   25: 
   26:     def save
   27:       assign_associated_attachments
(byebug) pending_uploads
[#<ActiveStorage::Attached::Changes::CreateOneOfMany:0x000000010b1a2e38 @attachable={:io=>#<StringIO:0x000000010b728920>, :content_type=>"text/plain", :filename=>"1.txt"}, @record=#<User id: 1>, @name="files", @blob=#<ActiveStorage::Blob id: nil, key: nil, filename: "1.txt", content_type: "text/plain", metadata: {"identified"=>true}, service_name: "local", byte_size: 5, checksum: "XUFAKrxLKna5cZ2REBfFkg==", created_at: nil>, @attachment=#<ActiveStorage::Attachment id: nil, name: "files", record_type: "User", record_id: nil, blob_id: nil, created_at: nil>>, #<ActiveStorage::Attached::Changes::CreateOneOfMany:0x000000010ad0ff10 @attachable={:io=>#<StringIO:0x000000010b728920>, :content_type=>"text/plain", :filename=>"1.txt"}, @record=#<User id: 1>, @name="files", @blob=#<ActiveStorage::Blob id: 1, key: "w7lb7ia2gwqwwrcacww3w2q47elk", filename: "1.txt", content_type: "text/plain", metadata: {"identified"=>true}, service_name: "local", byte_size: 5, checksum: "XUFAKrxLKna5cZ2REBfFkg==", created_at: "2022-06-13 12:21:19.589382000 +0000">, @attachment=#<ActiveStorage::Attachment id: 1, name: "files", record_type: "User", record_id: 1, blob_id: 1, created_at: "2022-06-13 12:21:19.592854000 +0000">>, #<ActiveStorage::Attached::Changes::CreateOneOfMany:0x000000010b910b70 @attachable={:io=>#<StringIO:0x000000010ad1f460>, :content_type=>"text/plain", :filename=>"2.txt"}, @record=#<User id: 1>, @name="files", @blob=#<ActiveStorage::Blob id: 2, key: "c2gp0zf92yt9h746mdq0ygcv7hcj", filename: "2.txt", content_type: "text/plain", metadata: {"identified"=>true}, service_name: "local", byte_size: 5, checksum: "fXkwN6B2AYZXSwKC8vQ15w==", created_at: "2022-06-13 12:21:19.597202000 +0000">, @attachment=#<ActiveStorage::Attachment id: 2, name: "files", record_type: "User", record_id: 1, blob_id: 2, created_at: "2022-06-13 12:21:19.599980000 +0000">>]
```

The `ActiveStorage::IntegrityError` occurs because the second attempt to upload `1.txt` reads from the end of the IO.

Bisects to #42300. /cc @santib @Jeremy

### PR DESCRIPTION
**Pull request by santib**
### Summary

First attempt to fix #45339 by not using the `change.attachables` on the `#attach` method.

That change was introduced in https://github.com/rails/rails/commit/836eb915b14f01eca8a5ea655e4f30b6a8a7ce38 when fixing #36806 however when reverting the change, the test that was introduced along with it, still passes (except when append on assign).

~We added a new failing test just in case but seems that the bug already existed even before #42300 . So it might be worth tackling it separately.~

cc @georgeclaghorn

### CODE REVIEW

File: activestorage/test/models/attached/many_test.rb [hunk 1]
```diff
@@ -219,6 +232,21 @@ class ActiveStorage::ManyAttachedTest < ActiveSupport::TestCase
     end
   end
 
+  test "attaching many new blobs within a transaction with append_on_assign on a new record uploads all the files" do
```
[the remark this answers is not in the document]
Comment (santib) [reply activestorage/test/models/attached/many_test.rb:235]: removed

**Comment by santib** [comment]
cc @jorgemanrubia just in case 😄

**Review by jorgemanrubia — APPROVED** [review]
Fix looks good to me @santib 👍, we'll get this merged. I added a minor suggestion below. Thanks!

File: activestorage/lib/active_storage/attached/many.rb [hunk 2]
```diff
@@ -55,7 +55,7 @@ def attach(*attachables)
           false
         end
       else
-        record.public_send("#{name}=", (change&.attachables || blobs) + attachables.flatten)
+        record.public_send("#{name}=", blobs + attachables.flatten)
```
Comment (jorgemanrubia) [inline activestorage/lib/active_storage/attached/many.rb:58]: @santib Very minor, but now that we assign the same value I think we can remove the duplication by extracting a method:

```ruby
def attach(*attachables)
  if record.persisted? && !record.changed?
    self.attachables = attachables
    if record.save
      record.public_send("#{name}")
    else
      false
    end
  else
    self.attachables = attachables
  end
end

private
  def attachables=(attachables)
    record.public_send("#{name}=", blobs + attachables.flatten)
  end
```

Comment (santib) [reply activestorage/lib/active_storage/attached/many.rb:58]: @jorgemanrubia what do you think about

```ruby
    def attach(*attachables)
      record.public_send("#{name}=", blobs + attachables.flatten)

      return unless record.persisted? && !record.changed?

      if record.save
        record.public_send("#{name}")
      else
        false
      end
    end
```

not sure if my version can be affecting the implicit return value in some case?

Comment (jorgemanrubia) [reply activestorage/lib/active_storage/attached/many.rb:58]: @santib I thought of extracting the common line too, but my concern was changing the return value as you suggest. The method always returns the list of attachables unless it can't be saved, in which case it returns false. I would try to leave that unchanged

Comment (jonathanhefner) [reply activestorage/lib/active_storage/attached/many.rb]: I noticed that [`record.public_send("#{name}=", ...)`](https://github.com/rails/rails/blob/2077524d5efc270658b27be4d8b7ec63e394f3f7/activestorage/lib/active_storage/attached/model.rb#L143-L161) returns a different value than [`record.public_send("#{name}")`](https://github.com/rails/rails/blob/2077524d5efc270658b27be4d8b7ec63e394f3f7/activestorage/lib/active_storage/attached/model.rb#L135-L136).  If we do care about the *truthy* return value, is there a reason to not be consistent about it?  e.g.:

```ruby
def attach(*attachables)
  record.public_send("#{name}=", blobs + attachables.flatten)
  return false if record.persisted? && !record.changed? && !record.save
  record.public_send("#{name}")
end
```

Comment (jorgemanrubia) [reply activestorage/lib/active_storage/attached/many.rb]: Thanks @santib.

@jonathanhefner That suggestion is more compact but I think it makes it less clear that the method can save the record, with the `save` is placed at the end of the inline conditions. It's a minor detail in any case. For me the patch is good to go, if you want to merge. I think we need to kick the test suite again though, lots of errors that seem unrelated?

Comment (jorgemanrubia) [reply activestorage/lib/active_storage/attached/many.rb]: @jonathanhefner oh good point about the return type. I had assumed those were the same. There is also a test enforcing [that type](https://github.com/rails/rails/blob/b77be3f427c9d4be092b2a488e6286546c779990/activestorage/test/models/attached/many_test.rb#L852-L851). Also good point on the symmetry of the methods 👍. I like your implementation after having played a bit more with it:

```ruby
def attach(*attachables)
  record.public_send("#{name}=", blobs + attachables.flatten)
  return false if record.persisted? && !record.changed? && !record.save
  record.public_send("#{name}")
end
```

@santib could you please make that last change 🙏? Sorry about the back and forth.

Comment (santib) [reply activestorage/lib/active_storage/attached/many.rb]: Sure thing, thanks Jonathan for the improvement. The `attach` method looks so much better now

**Comment by jonathanhefner** [comment]
Thank you @santib and @jorgemanrubia! :raised_hands:
