### PR TITLE
Don't recommend disabling CSRF protection [ci skip]

### LINKED ISSUE #38388: Issue for documentation - `RequestForgeryProtection` doc seems has wrong guide
There is a wrong guide in [RequestForgeryProtection comment](https://github.com/rails/rails/blob/08e4a71d02ee8556e5a7ebc4b0f8c364e0b8abd6/actionpack/lib/action_controller/metal/request_forgery_protection.rb) and [documentation](https://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html)

```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }
end
```

> It is generally safe to exclude XHR requests from CSRF protection (like the code snippet above does), because XHR requests can only be made from the same origin.

However, as I know same origin policy cannot protect CSRF attack because [it does not prevent sending requests.](https://stackoverflow.com/a/33324803/2566679)

> ... one origin is permitted to send information to another origin, but one origin is not permitted to receive information from another origin   [Same Origin Policy
](https://www.w3.org/Security/wiki/Same_Origin_Policy)

If this is true, I think this guide must be modified, soon.

### PR DESCRIPTION
**Pull request by eugeneius**
Fixes https://github.com/rails/rails/issues/38388.

The previous example disables CSRF protection for JSON format requests, which allows any request to bypass it by adding the right Accept header.

Accept is one of the few headers that doesn't trigger a CORS preflight:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Examples_of_access_control_scenarios

Instead of disabling it entirely, the simple case where authentication is handled without a session (e.g. when using API keys) can be solved by switching to the `:null_session` strategy.

For more complex cases (e.g. an API that uses session authentication), I don't think a copy-and-paste-able example is appropriate; the user needs to understand CSRF protection in order to make an informed choice.

### CODE REVIEW

File: actionpack/lib/action_controller/metal/request_forgery_protection.rb [hunk 1]
```diff
@@ -32,29 +32,22 @@ class InvalidCrossOriginRequest < ActionControllerError #:nodoc:
...
   #   end
   #
-  # It is generally safe to exclude XHR requests from CSRF protection
-  # (like the code snippet above does), because XHR requests can only be made from
-  # the same origin. Note however that any cross-origin third party domain
-  # allowed via {CORS}[https://en.wikipedia.org/wiki/Cross-origin_resource_sharing]
-  # will also be able to create XHR requests. Be sure to check your
-  # CORS configuration before disabling forgery protection for XHR.
-  #
-  # CSRF protection is turned on with the <tt>protect_from_forgery</tt> method.
```
Comment (vipulnsward) [inline actionpack/lib/action_controller/metal/request_forgery_protection.rb:50]: I was confused by this and then the documentation below that the default is `:null_session`(which it is on the method, but not really because we default to call it with `protect_from_forgery with: :exception` from initializers). 

Think we should bring that in line as well, and make `:exception` the default since it has always been default since 5.2 and before.

File: actionpack/lib/action_controller/metal/request_forgery_protection.rb [hunk 2]
```diff
@@ -32,29 +32,22 @@ class InvalidCrossOriginRequest < ActionControllerError #:nodoc:
...
+  # which allows unverified requests to be handled, but with an empty session:
   #
   #   class ApplicationController < ActionController::Base
-  #     protect_from_forgery unless: -> { request.format.json? }
+  #     protect_from_forgery with: :null_session
   #   end
   #
-  # It is generally safe to exclude XHR requests from CSRF protection
-  # (like the code snippet above does), because XHR requests can only be made from
-  # the same origin. Note however that any cross-origin third party domain
```
Comment (vipulnsward) [inline actionpack/lib/action_controller/metal/request_forgery_protection.rb:45]: Think we should keep around this warning on cors.

File: actionpack/lib/action_controller/metal/request_forgery_protection.rb (hunk 1 above)
Comment (eugeneius) [reply actionpack/lib/action_controller/metal/request_forgery_protection.rb:50]: Yeah, it's confusing that `:exception` is the default behaviour if you do nothing, but `:null_session` is the default behaviour if you call the method without no arguments.

Maybe we should change the latter to match the former, but it would need a deprecation cycle or a new framework default, which is beyond the scope of this pull request IMO. I'm happy to explore it as a followup.

File: actionpack/lib/action_controller/metal/request_forgery_protection.rb (hunk 2 above)
Comment (eugeneius) [reply actionpack/lib/action_controller/metal/request_forgery_protection.rb:45]: It's only relevant if you disable CSRF protection, which I was trying to avoid mentioning at all... it also only makes sense for requests which would otherwise be unaffected by CSRF.

That's the case when `xhr?` returns true, since the `X-Requested-With` header will force a CORS preflight. It's _not_ the case for XHR requests is general, and I worry that people will confuse the two. I also think it's too easy to add CORS headers later, months or years after you read this documentation, and introduce a vulnerability.

File: actionpack/lib/action_controller/metal/request_forgery_protection.rb (hunk 1 above)
Comment (vipulnsward) [reply actionpack/lib/action_controller/metal/request_forgery_protection.rb:50]: Oh not in this, in follow up 👍

**Review by vipulnsward — APPROVED** [review]

File: actionpack/lib/action_controller/metal/request_forgery_protection.rb [hunk 3]
```diff
@@ -32,29 +32,22 @@ class InvalidCrossOriginRequest < ActionControllerError #:nodoc:
...
   # Ajax) requests are allowed to make requests for JavaScript responses.
   #
-  # It's important to remember that XML or JSON requests are also checked by default. If
-  # you're building an API or an SPA you could change forgery protection method in
-  # <tt>ApplicationController</tt> (by default: <tt>:exception</tt>):
+  # Subclasses of <tt>ActionController::Base</tt> are protected by default with the
+  # <tt>:exception</tt> strategy, which raises an
+  # <tt>ActionController::InvalidAuthenticityToken</tt> error on unverified requests.
+  #
+  # It's important to remember that XML or JSON requests are also checked by default.
```
Comment (eugeneius) [inline actionpack/lib/action_controller/metal/request_forgery_protection.rb:39]: I kept this line from the previous version, but reading it again today I don't think it adds anything. Gonna ✂️ it!
