### PR TITLE
Fix eager loading models without primary keys

### LINKED ISSUE #29374: model w/o primary key defined as association beeing eager loaded is not populated
### Steps to reproduce
migration:

```
def up
    create_table :institution_hierarchies, id: false do |t|
      t.integer :parent_id, index: true
      t.integer :child_id, index: true
    end
    create table :clients do |t|
      t.integer :institution_id
    end
end

```
models:
```
class InstitutionHierarchy < ActiveRecord::Base
end
```
```
class Client < ActiveRecord::Base
   has_many :institution_hierarchies, foreign_key: :child_id,  primary_key: :institution_id
end
```

reproduce:
  ```
InstitutionHierarchy.create!({child_id: 2, parent_id: 1})
  Client.create!({institution_id: 2})
  puts Client.eager_load(:institution_hierarchies).first.institution_hierarchies.inspect
```

### Expected behavior
The Collection with a single object representing the previously inserted row should be printed

### Actual behavior
An empty collection is printed

### Solution
execute following migration:
```
def change
    add_column :institution_hierarchies, :id, :primary_key
end
```

then execute:

```
puts Client.eager_load(:institution_hierarchies).first.institution_hierarchies.inspect
```

Now the collection contains the desired Object.
I'm not sure if this is in fact a bug or if i'm just missing something, but i could not find any documentation exactly on that topic.

### System configuration
**Rails version**:  4.2.1

**Ruby version**:  2.2.3

**Database**: postgresql 9.5

### PR DESCRIPTION
**Pull request by mattalat**
### Summary

Eager-loading models without primary keys does not function correctly.

Fixes #29374

### Example

Consider the following and assume that the second model is backed by a DB object without a primary key (like a view):

```rb
class MyModel < ActiveRecord::Base
   has_one :model_without_primary_key, primary_key: :some_other_column
end

class ModelWithoutPrimaryKey < ActiveRecord::Base
   belongs_to :my_model, primary_key: :some_other_column
end
```
If we create a couple of records, we can see that `eager_load` produces incorrect results:

```rb
MyModel.create # => #<MyModel id: 1>
ModelWithoutPrimaryKey.create(some_other_column: 100, my_model_id: 1)

my_instance = MyModel.eager_load(:model_without_primary_key).first
my_instance.model_without_primary_key # => nil

my_instance.reload
my_instance.model_without_primary_key #=> #<ModelWithoutPrimaryKey ... >
```

This issue comes up during normal ActiveRecord use-cases when models are backed by DB views. It can also come up  with chains like:

```rb
my_instance.includes(:model_without_primary_key).order('model_without_primary_key.name')
```

### Credit

I give 95% of the credit to @chopraanmol1 and based this PR on their GH-30212, which looks to have gone stale a couple of years ago.

### CODE REVIEW

File: activerecord/lib/active_record/associations/join_dependency.rb [hunk 1]
```diff
@@ -248,22 +248,25 @@ def construct(ar_parent, parent, row, seen, model_cache, strict_loading_value)
...
               nil_association.loaded!
               next
             end
 
-            model = seen[ar_parent][node][id]
+            # Only cache when we have a primary key. This avoids issues when
+            # the non-unique foreign key is used as a fallback.
+            model = seen[ar_parent][node][id] if node.primary_key
 
             if model
```
Comment (alipman88) [inline activerecord/lib/active_record/associations/join_dependency.rb:264]: will `model` always be defined here if `node.primary_key` is nil?

I've pulled your code locally and ran the tests - and I believe the answer is yes. But it's difficult to verify from reading the code.

**Comment by alipman88** [comment]
This seems like a definite improvement.

File: activerecord/lib/active_record/associations/join_dependency.rb (hunk 1 above)
Comment (mattalat) [reply activerecord/lib/active_record/associations/join_dependency.rb:264]: Could you please explain a bit more? I tried a few things out but have seen failed tests in each case.

Comment (alipman88) [reply activerecord/lib/active_record/associations/join_dependency.rb:264]: `model` is a local variable belonging to the `construct` function, right?

If `model` isn't declared, `if model` will raise a NameError: `NameError (undefined local variable or method `model' for main:Object)`

Before changing:

```ruby
model = seen[ar_parent][node][id]
```

to:

```ruby
model = seen[ar_parent][node][id] if node.primary_key
```

we know for certain the `model` variable has been declared. But if `node.primary_key` is false/nil, then we're relying on `model` having been declared somewhere else.

Comment (alipman88) [reply activerecord/lib/active_record/associations/join_dependency.rb:264]: Ha! I never knew that.

> If you think this is too indirect, I'd be happy to change the code to be clearer.

While Ruby's behavior unexpected, I think the code's good as is.

**Review by alipman88 — APPROVED** [review]

File: activerecord/lib/active_record/associations/join_dependency.rb (hunk 1 above)
Comment (mattalat) [reply activerecord/lib/active_record/associations/join_dependency.rb:264]: Great!

**Comment by mattalat** [comment]
@alipman88 are you able to approve the workflows for this PR or do I need to contact someone about it?

**Comment by alipman88** [comment]
> are you able to approve the workflows for this PR or do I need to contact someone about it?

Looks like a member of the Rails team needs to do that. I'll try flagging @jonathanhefner, who's helped me in the past.

**Comment by jonathanhefner** [comment]
:rocket:

**Comment by mattalat** [comment]
@alipman88 @jonathanhefner Is there anything I should do to get the attention of someone with write access to the repository? I'm hesitant to nag anyone I haven't had contact with, and I don't mind fixing the conflicts every few days, so I'll be content if neither of you knows.

**Comment by mattalat** [comment]
Hey @jonathanhefner, do you have merge rights for this repository now? I've been resolving conflicts every few days for the past few months and it would be neat if the PR was merged.

**Review by jonathanhefner — COMMENTED** [review]
Although the code changes are small, I feel like I would have some difficulty understanding this code outside of the context of this PR.  So I played around with it a bit, and pushed a commit here with the result (c02a775698aee85376ad9ee2d8e895aa347056ee).  Let me know what you think.  If you're satisfied with all of the changes, you or I can squash the commits.

I also added @chopraanmol1 as a co-author in my commit, due to his work on #30212.

**Comment by jonathanhefner** [comment]
@mattalat I went ahead and squashed the commits and rebased.  Thank you for working on this! :tada:

By the way, in case it helps in the future, rebasing is only strictly necessary right before a merge, especially for minor conflicts such as the `CHANGELOG`.  In other words, you can wait until a committer indicates intent to merge or otherwise asks for a rebase.

**Comment by mattalat** [comment]
Thank you @jonathanhefner. Sorry, I couldn't respond earlier: your changes look great.

And I take your point on the `CHANGELOG` conflicts. I was _just a touch_ overexcited for my first Rails contribution, you could say 🙂 .
