### PR TITLE
Fix validations on child record when record parent has validate: false

### LINKED ISSUE #17621: AR is erroneously validating existing records on a has_many :through
Its Friday, so entirely possible I just need a drink and some sleep. But after upgrading a legacy app to the latest and greatest, I've started to see unexpected validations when creating new records with existing associations on a `has_many :through`.

See attached gist: https://gist.github.com/uberllama/1d0323438700d4f23bbb

I have a Conversation class, which has many `:users` through `:conversation_users`. When a user creates a new Conversation, they specify which Users they want to include in the Conversation. This boils down to:

```ruby
class Conversation < ActiveRecord::Base
  has_many :conversation_users
  has_many :users, through: :conversation_users
end

class ConversationUser < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user
end

class User < ActiveRecord::Base
  has_many :conversation_users
  has_many :conversations, through: :conversation_users
  validates :name, presence: true
end

conversation = Conversation.new(user_ids: [1,2,3])
conversation.save
```

When calling `save` on the new Conversation instance, AR is validating the associated Users even though they are existing, non-dirty objects. This results in huge amounts of unnecessary weight on every Conversation save. It should not be the responsibility of a model to validate its associated objects unless those objects are being created or modified along with the parent model.

What am I missing?

### PR DESCRIPTION
**Pull request by eileencodes**
Fixes #17621. This 5 year old (or older) issue causes validations to fire when a parent record has `validate: false` option and a child record is saved. It's not the responsibility of the model to validate an associated object unless the object was created or modified by the parent.

Also cleaned up tests related to validations
`assert_nothing_raised` is not benefiting us in these tests
Corrected spelling of "respects"
It's better to use `assert_not_operator` over `assert !r.valid`

Originally @tenderlove and I had put the definition of `should_validate?` in ActiveModel but I found later that `persisted?`, `changed?` and `marked_for_destruction?` are not defined in ActiveModel so those tests were failing. I moved that code completely into AR. If there is another suggestion to a better place for this method I'm open to suggestions. 

P.S. I'm on vacation this week so I might be slow to respond if you have questions :sunny: :smile:

### CODE REVIEW

File: activerecord/lib/active_record/validations/uniqueness.rb [hunk 1]
```diff
@@ -28,6 +29,10 @@ def validate_each(record, attribute, value)
         end
       end
 
+      def should_validate?(record)
+        !record.persisted? || record.changed? || record.marked_for_destruction?
```
Comment (sgrif) [inline activerecord/lib/active_record/validations/uniqueness.rb]: Should this be extracted somewhere, since it's re-used three times?

**Comment by sgrif** [comment]
We might want to benchmark this, since calling `record.changed?` repeatedly will probably cause a major regression.

**Comment by tenderlove** [comment]
It looks like `changed?` is just checking to see if a hash is empty.  Is it doing something more?  Also this change only impacts specific validations, I have a hard time believing it would cause a major speed regression in an app.

**Comment by sgrif** [comment]
The hash calculates in-place changes.

**Comment by sgrif** [comment]
Maybe "major" is a bit far, but I would expect it to move the needle for `Model#save` if it has multiple presence validations.

**Comment by eileencodes** [comment]
Thanks for the feedback @sgrif - I'll consolidate the code and run benchmarks when I'm back in town this weekend.

**Comment by eileencodes** [comment]
@sgrif - I moved the `should_validate?` definition into ActiveModel but am not calling it from there so the tests pass. That was the only shared file between the validations - if this is undesirable the only other place I can think to put it would be it's own file. :smile_cat: 

Regarding benchmarks: Maybe I have vacation brain but I'm thinking about the benchmarks for this and struggling to get something that makes sense and we can be confident in.

Technically I can't run the validation on `#save` and benchmark it before the change because it will raise `ActiveRecord::RecordInvalid` (the reason for this PR). When an error is raised the benchmark doesn't finish so I have 2 options: tack on a `validate: false` onto the second call to save or  `rescue` the `ActiveRecord::RecordInvalid`.

`validate: false` isn't going to work because we're then skipping the code section I added so it would be the same benchmark on master vs this branch. The code added in this branch is faster than a rescue but I don't think that's what we're looking for - I already expected rescue to be slower. Would love any suggestions to point me in a direction where I can get solid benchmarks. 

This branch:
```
Calculating -------------------------------------
with should_validate? method
                        46.000  i/100ms
-------------------------------------------------
with should_validate? method
                        479.288  (± 3.1%) i/s -      2.438k
```
Master with a rescue for ActiveRecord::RecordInvalid
```
Calculating -------------------------------------
with rescue ActiveRecord::RecordInvalid
                        43.000  i/100ms
-------------------------------------------------
with rescue ActiveRecord::RecordInvalid
                        435.397  (± 4.8%) i/s -      2.193k
```

**Comment by eileencodes** [comment]
Ugg I do have vacation brain - forgot I had the `#save!` on the test scripts :grin:

Here are the benchmarks master vs my branch. There is a little bit of a slow down.

```
Calculating -------------------------------------
master
                        46.000  i/100ms
-------------------------------------------------
master
                        466.578  (± 5.1%) i/s -      2.346k
```

```
Calculating -------------------------------------
with should_validate?
                        44.000  i/100ms
-------------------------------------------------
with should_validate?
                        448.450  (± 5.6%) i/s -      2.244k
```

**Comment by bgott** [comment]
Yo @tenderlove I ran the benchmarks against master and this branch. The standard deviation shows that there isn't much difference between the two branches. 

```
Calculating -------------------------------------
master
                        39.000  i/100ms
-------------------------------------------------
master
                        407.243  (± 4.4%) i/s -      2.067k


Calculating -------------------------------------
with should_validate?
                        40.000  i/100ms
-------------------------------------------------
with should_validate?
                        415.600  (± 3.4%) i/s -      2.080k
```

**Comment by sgrif** [comment]
Thanks for running the benchmarks, guys. I just want to confirm, since nobody posted the script they used, this was benchmarking modifying existing records, not creating new ones, right?

**Comment by eileencodes** [comment]
@sgrif I ran both and the results for the difference were the same

**Comment by sgrif** [comment]
:+1:

File: activerecord/test/cases/validations/uniqueness_validation_test.rb [hunk 2]
```diff
@@ -386,4 +386,21 @@ def test_validate_uniqueness_on_empty_relation
...
+
+    reply = Reply.new(content: "Topic Title")
+    reply.save!(validate: false)
+    assert reply.persisted?
+
+    topic = Topic.new(reply_ids: [reply.id])
+    topic.save!
+
+    assert_equal topic.replies.size, 1
+    assert reply.valid?
```
Comment (pacoguzman) [inline activerecord/test/cases/validations/uniqueness_validation_test.rb]: I have one question about this. Does this mean the reply will be valid from now on? I mean I thought calling valid? must execute the validations again

Comment (hundredwatt) [inline activerecord/test/cases/validations/uniqueness_validation_test.rb]: @pacoguzman It thought this was odd too. If you look at the new `should_validate?` method:
```
   def should_validate?(record) # :nodoc:
      !record.persisted? || record.changed? || record.marked_for_destruction?
    end
```
When `assert reply.valid?`, the record is [x] persisted, [x] un-changed, [x] not marked for destruction, so the uniqueness validation isn't performed. Before this PR was merged, the validation would have been run, but now it isn't.

Comment (hundredwatt) [inline activerecord/test/cases/validations/uniqueness_validation_test.rb]: As an example, if you change a different attribute, say `title`, then the validations will be run:

```
  def test_does_not_validate_uniqueness_of_if_parent_record_is_validate_false
    ...
    assert_equal topic.replies.size, 1
    assert reply.valid?
    reply.title = "Change An Attribute"
    assert reply.valid? #=> Fails!
    ...
  end
```

Comment (pacoguzman) [inline activerecord/test/cases/validations/uniqueness_validation_test.rb]: Understood thanks for the response. It's a big change for me. Then some
validations will run and others don't when the record has no changes.
Anyway I always add a condition on the uniqueness validations to avoid
extra queries
