### PR TITLE
Fix CTE construction when passed arrays with more than 2 queries

### LINKED ISSUE #53110: `#with` doesn't accept three or more sub-queries
### Steps to reproduce

`#with` method doesn't accept three or more sub-queries.

```ruby
# 2 sub-queries are OK
irb> User.with(foo: [User.select(:id), User.select(:id)]).to_sql
=> "WITH `foo` AS ( SELECT `users`.`id` FROM `users` UNION ALL SELECT `users`.`id` FROM `users` ) SELECT `users`.* FROM `users`"

# 3 sub-queries raise an error
irb> User.with(foo: [User.select(:id), User.select(:id), User.select(:id)]).to_sql
in `<main>': undefined method `union' for an instance of Arel::Nodes::UnionAll (NoMethodError)

        when Array then value.map { |q| build_with_expression_from_value(q) }.reduce { |result, value| result.union(:all, value) }
                                                                                                             ^^^^^^
```

### Expected behavior

Build a query that combined all sub-queries with `UNION ALL`

### Actual behavior

An error occurs

> undefined method `union' for an instance of Arel::Nodes::UnionAll (NoMethodError)

### System configuration
**Rails version**: 7.2.1

**Ruby version**: 3.3.0

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #53110.

I also did a small refactoring to make the code more readable.

### CODE REVIEW

File: activerecord/lib/active_record/relation/query_methods.rb [hunk 1]
```diff
@@ -1915,7 +1915,14 @@ def build_with_expression_from_value(value)
         when Arel::Nodes::SqlLiteral then Arel::Nodes::Grouping.new(value)
         when ActiveRecord::Relation then value.arel
         when Arel::SelectManager then value
-        when Array then value.map { |q| build_with_expression_from_value(q) }.reduce { |result, value| result.union(:all, value) }
+        when Array
+          parts = value.map { |q| build_with_expression_from_value(q) }
+          parts.reduce do |result, value|
+            Arel::Nodes::UnionAll.new(
+              result.try(:ast) || result,
```
Comment (byroot) [inline activerecord/lib/active_record/relation/query_methods.rb:1922]: Not a big fan of using `.try ||` here. It's often indicative of unclear APIs.

Comment (byroot) [reply activerecord/lib/active_record/relation/query_methods.rb]: @fatkodima I pushed 9d9414b35e592362eb8429308d6103e586ecf23c, let me know what you think.

File: activerecord/lib/active_record/relation/query_methods.rb [hunk 2]
```diff
@@ -1915,7 +1915,14 @@ def build_with_expression_from_value(value)
         when Arel::Nodes::SqlLiteral then Arel::Nodes::Grouping.new(value)
         when ActiveRecord::Relation then value.arel
         when Arel::SelectManager then value
-        when Array then value.map { |q| build_with_expression_from_value(q) }.reduce { |result, value| result.union(:all, value) }
+        when Array
+          parts = value.map { |q| build_with_expression_from_value(q).ast }
```
Comment (fatkodima) [inline activerecord/lib/active_record/relation/query_methods.rb:1919]: This will fail on `.ast` not defined when we pass non AR::Relation in the array. For example, line 1915 - `Arel::Nodes::SqlLiteral` instances do not respond to `.to_ast`

Comment (byroot) [reply activerecord/lib/active_record/relation/query_methods.rb:1919]: We probably ought to add a test for that then.

**Comment by npezza93** [comment]
Sweet! Ill close https://github.com/rails/rails/pull/52211 in favor of this.

File: activerecord/lib/active_record/relation/query_methods.rb (hunk 2 above)
Comment (fatkodima) [reply activerecord/lib/active_record/relation/query_methods.rb]: Updated the test case to also test this.

File: activerecord/lib/arel/visitors/sqlite.rb [hunk 3]
```diff
@@ -33,6 +33,31 @@ def visit_Arel_Nodes_IsDistinctFrom(o, collector)
           collector << " IS NOT "
           visit o.right, collector
         end
+
+        # Queries used in UNION should not be wrapped by parentheses,
+        # because it is an invalid syntax in SQLite.
+        def infix_value_with_paren(o, collector, value, suppress_parens = false)
```
Comment (fatkodima) [inline activerecord/lib/arel/visitors/sqlite.rb:39]: Need this for sqlite to make sure that queries used in `UNION` are not wrapped by parenthesis, because it is an invalid syntax.

`select .. union select ..` is good, but `(select ..) union (select ..)` is invalid 🤦
