### PR TITLE
Don't freeze input strings

### LINKED ISSUE #24185: ActiveModel::Type::ImmutableString, ActiveModel::Type::String #cast_value(value) freeze string value in-place
### Steps to reproduce

not_frozen_string = ''
not_frozen_string.frozen? # false
cast_value(not_frozen_string)
not_frozen_string.frozen? # true
### Expected behavior

ActiveModel::Type::String#cast_value(value) doesn't freeze string value in-place
ActiveModel::Type::ImmutableString#cast_value(value) doesn't freeze string value in-place
### Actual behavior

ActiveModel::Type::String#cast_value(value) freezes string value in-place
ActiveModel::Type::ImmutableString#cast_value(value) freezes string value in-place
### System configuration

Rails master
### My monkey patch

``` ruby
ActiveModel::Type::ImmutableString.class_eval do
  def cast_value(value)
    case value
    when true then 't'.freeze
    when false then 'f'.freeze
    when ::String then ::String.new(value).freeze
    else value.to_s.freeze
    end
  end
end
```

### LINKED ISSUE #28718: Freeze attributes when I create new Active record object with them
I faced one unexpected behavior: when I have one new active record object and build second with first's attributes, attributes of first object will be frozen.

For example:
I have ActiveRecord model 'User' with 2 attributes - 'first_name' and 'last_name'
### Steps to reproduce
```ruby
user = User.new(first_name: 'Alex', last_name: 'Kosh')
user.first_name.frozen? #=> false
User.new(user.attributes)
user.first_name.frozen? #=> true
```

### Expected behavior
user.attributes are not frozen

### System configuration
Rails version: 5.0.2
Ruby version: 2.3.3

### PR DESCRIPTION
**Pull request by matthewd**
See 34321e4a433bb7eef48fd743286601403f8f7d82 for background on ImmutableString vs String.

Our String type cannot delegate typecasting to ImmutableString, because the latter freezes its input: duplicating the value after that gives us an unfrozen result, but still mutates the originally passed object.

Fixes #24185
Fixes #28718

### CODE REVIEW

File: activemodel/lib/active_model/type/string.rb [hunk 1]
```diff
@@ -12,7 +12,12 @@ def changed_in_place?(raw_old_value, new_value)
       private
 
         def cast_value(value)
-          ::String.new(super)
+          case value
+          when ::String then ::String.new(value)
+          when true then "t".freeze
```
Comment (rafaelfranca) [inline activemodel/lib/active_model/type/string.rb]: It just sucks that we have to duplicate the conditionals and the true and false cases.

**Review by rafaelfranca — APPROVED** [review]

File: activemodel/lib/active_model/type/string.rb (hunk 1 above)
Comment (kaspth) [inline activemodel/lib/active_model/type/string.rb]: True, but it seems the rate of change on these branches is fairly low.

**Comment by matthewd** [comment]
1949a2574d, 1fb87ea559
