### PR TITLE
ActiveJob::Core#serialize stores provider_job_id (fixes #26581).

### LINKED ISSUE #26581: ActiveJob: `provider_job_id` is not serialized after enqueuing the job
### Steps to reproduce
- Implement job based on `ActiveJob::Base` class with callbacks `after_enqueue` and `before_perform`. Callbacks will print out `provider_job_id`.
  
  ``` ruby
  class FooJob < ActiveJob::Base
      after_enqueue do |job|
          puts job.provider_job_id
      end
      before_perform do |job|
          puts job.provider_job_id
      end
      def perform
          # do something
      end
  end
  ```
### Expected behavior
- Both callbacks should print out identical `provider_job_id`.
### Actual behavior
- Only `after_enqueue` callback prints out correct `provider_job_id`. In `before_perform` `provider_job_id` is equal to `nil`
- It is probably related to the serialization/deserialization code. `provider_job_id` is not stored in job data.
  
  In `ActiveJob::Core#deserialize` (https://github.com/rails/rails/blob/master/activejob/lib/active_job/core.rb#L111) `provider_job_id` is mentioned, but in `ActiveJob::Core#serialize` it is not.
### System configuration

**Rails version**: 5.0.0.1
**Ruby version**: 2.3.1p112

### PR DESCRIPTION
**Pull request by utilum**
### Summary

Fixes #26581, adds provider_job_id to the hash returned by ActiveJob::Core#serialize, and a test.

### CODE REVIEW

File: activejob/lib/active_job/core.rb [hunk 1]
```diff
@@ -80,6 +80,7 @@ def serialize
       {
         "job_class"  => self.class.name,
         "job_id"     => job_id,
+        "provider_job_id" => provider_job_id,
```
Comment (jvanbaarsen) [inline activejob/lib/active_job/core.rb]: If the enqueue system does not provide a provider_job_id, will this still work? (I assume it will, but might be worth checking)

Comment (utilum) [inline activejob/lib/active_job/core.rb]: @jvanbaarsen The first assertion tests this, but perhaps it can be made clearer. I'll patch.

Comment (jvanbaarsen) [inline activejob/lib/active_job/core.rb]: :+1:

**Comment by cristianbica** [comment]
The `provider_job_id` is not guaranteed to be present on every adapter and is even less present at execution time. The way `provider_job_id` works on most adapters is:

- we enqueue the job (at this point we call `serialize`)
- from the response we get from the adapter we try to extract the `provider_job_id` and assign it to the `ActiveJob::Base` instance
- at execution time, when initializing the `ActiveJob::Base` instance from the adapter job wrapper,  we try to fetch the `provider_job_id` and assign it (from quickly looking at the code it seems it only works for [sidekiq](https://github.com/rails/rails/blob/b326e82dc012d81e9698cb1f402502af1788c1e9/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb#L40))

So this PR won't do much good as the `serialize` is called before obtaining the `provider_job_id`. However there's room for improving support for `provider_job_id` as I think we might be able to extract the `provider_job_id` at execution time for other adapters.

**Comment by utilum** [comment]
This PR does (in my understanding) resolve #26581.
I'm sure there's room for improving support for `provider_job_id` yet more, but if `serialize` does not include it, it won't be available to `deserialize`.

**Comment by utilum** [comment]
I don't understand the CI error log. Help? @maclover7 ?

**Comment by maclover7** [comment]
@utilum Sorry for the trouble, restarted the randomly failing build, should be green now.

**Comment by utilum** [comment]
Thank you @maclover7 . This is something only you members can launch, right?

**Comment by utilum** [comment]
rebased.

**Comment by utilum** [comment]
rebased. failures seem unrelated (to my innocent eyes).

**Comment by utilum** [comment]
I assume this is still relevant... ?
cc @maclover7

File: activejob/test/cases/job_serialization_test.rb [hunk 2]
```diff
@@ -44,4 +44,12 @@ class JobSerializationTest < ActiveSupport::TestCase
     job.deserialize({})
     assert_equal "en", job.locale
   end
+
+  test "serialize stores provider_job_id" do
+    job = HelloJob.new
+    assert job.serialize["provider_job_id"].nil?
```
Comment (rafaelfranca) [inline activejob/test/cases/job_serialization_test.rb]: `assert_nil`

**Review by rafaelfranca — CHANGES_REQUESTED** [review]

**Comment by utilum** [comment]
But of course! Thank you, fixed.
