### PR TITLE
Fix escaping in OptimizedFileSystemResolver

### LINKED ISSUE #37107: View templates cannot be found if the path to the project includes parentheses
### Steps to reproduce
Create a new Rails project such that the path to the project folder includes parentheses:
```bash
rails new "path-escape-bug (testing)"
cd "path-escape-bug (testing)"
rails g controller public example
bin/rails s
# open "http://localhost:3000/public/example" in your browser
```

### Expected behavior
The page renders successfully.
Screen Shot 2019-09-02 at 2 53 10 PM

### Actual behavior
Rails is unable to locate the view template.
Screen Shot 2019-09-02 at 2 51 44 PM

### System configuration
**Rails version**: 6.0.0
**Ruby version**: 2.6.4p104

### Additional notes
This appears to be a bug in `ActionView::PathResolver#escape_entry`, as called by `ActionView::OptimizedFileSystemResolver#build_regex`:
https://github.com/rails/rails/blob/88fe8d9e7ca687f4253090bcc2c634595a19d203/actionview/lib/action_view/template/resolver.rb#L265-L267

When Rails tries to determine where to search for a template, it escapes the parentheses in the path incorrectly. As a result, it builds a regex that fails to match the actual project path.

You can see this from the Rails console by running the following:
```ruby
# Project path does not include parentheses
project_path = '/Users/rofreg/Desktop/path-escape-bug'
template_path = 'app/views/public/example'
full_path_regex = ActionView::OptimizedFileSystemResolver.new(project_path).send(:build_regex, template_path, { locale: [], formats: [], variants: [], handlers: [] })
full_path_regex.match?(File.join(project_path, template_path))
# result: true

# Project path DOES include parentheses
project_path = '/Users/rofreg/Desktop/path-escape-bug (testing)'
template_path = 'app/views/public/example'
full_path_regex = ActionView::OptimizedFileSystemResolver.new(project_path).send(:build_regex, template_path, { locale: [], formats: [], variants: [], handlers: [] })
full_path_regex.match?(File.join(project_path, template_path))
# result: false
```

### LINKED ISSUE #37719: Rails 6 app does not render templates when started from a Dropbox folder
### Steps to reproduce
```

myuser@192 Dropbox % pwd
/Users/myuser/Dropbox
myuser@192 Dropbox % rails new bugreport
myuser@192 Dropbox % cd bugreport 
myuser@192 bugreport % bundle
myuser@192 bugreport % rails g controller testc index
myuser@192 bugreport % rails s

http://localhost:3000/ # Yay! You’re on Rails!

http://localhost:3000/testc/index 
# No template for interactive request
# TestcController#index is missing a template for request formats: text/html

Exit Server

myuser@192 bugreport % cd ..
myuser@192 Dropbox % mv bugreport ../
myuser@192 Dropbox % cd ../bugreport 
myuser@192 bugreport % pwd
/Users/myuser/bugreport
myuser@192 bugreport % rails s

http://localhost:3000/testc/index 
# Testc#index
# Find me in app/views/testc/index.html.erb

```

### Expected behavior
The app should work independant from the folder it is started from. Just like it did in 5.2 which is not affected by this issue.

### Actual behavior
Rendering any ERB view fails.

Log output:
```

`Completed 406 Not Acceptable in 5ms (ActiveRecord: 0.0ms | Allocations: 1970)
 
ActionController::MissingExactTemplate (TestcController#index is missing a template for request formats: text/html):`
```

### System configuration
**Rails version**:
6

**Ruby version**:
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**Operating System**
Mac Os Catalina

### PR DESCRIPTION
**Pull request by jonathanhefner**
`OptimizedFileSystemResolver` builds a regular expression to match view template paths.  Prior to this patch, only file globbing special characters were escaped when building this regular expression, leaving other regular expression special characters unescaped.

This patch properly escapes all regular expression special characters, and adds test coverage for paths that include these characters.

Fixes #37107.

### CODE REVIEW

File: actionview/test/template/resolver_shared_tests.rb [hunk 1]
```diff
@@ -79,6 +79,17 @@ def test_can_find_with_any_variant_format_and_handler
     assert_kind_of ActionView::Template::Handlers::ERB, templates[0].handler
   end
 
+  def test_can_find_when_special_chars_in_path
+    special_chars = ((" ".."~").grep(/\W/) - ["|", "/", "\\"]).join("_")
```
Comment (jhawthorn) [inline actionview/test/template/resolver_shared_tests.rb]: I think some of these are reserved on windows. I think it would probably be sufficient for this test to just test for ex. parens since that exposes the existing issue here and feels like the most likely use.

```
dir = "my_project (testing)"
```

**Review by jhawthorn — COMMENTED** [review]
Thanks! ❤️

Left one suggestion for tests.

**Comment by jonathanhefner** [comment]
@jhawthorn Thank you for the review!  I've made the suggested change.

**Comment by eugeneius** [comment]
I backported this to 6-0-stable in 4e3fd9290059b453a2074603c3237a5c668db00a, since it fixes a regression from 5.2 that has been reported again twice since it was merged (https://github.com/rails/rails/issues/37641, https://github.com/rails/rails/issues/38415).
