### PR TITLE
Touch model records after ActiveStorage::Blob is analyzed

### LINKED ISSUE #45567: Record not touched when ActiveStorage::Blob is analyzed
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true do |t|
    t.timestamps
  end
end

class User < ActiveRecord::Base
  has_one_attached :profile
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_upload_and_download
    user = User.create!(
      profile: {
        content_type: "text/plain",
        filename: "dummy.txt",
        io: ::StringIO.new("dummy"),
      }
    )

    old_updated_at = user.updated_at

    # Sanity test, since some database adapters truncate microseconds
    assert_equal user.reload.updated_at, old_updated_at

    # Analyze the blob
    user.profile.blob.analyze

    # User should have been touched
    refute_equal user.reload.updated_at, old_updated_at
  end
end
```

### Expected behavior
Analyzing an ActiveStorage Blob should touch all of the models that the blob is attached to.

### Actual behavior
The model is untouched.

### System configuration
**Rails version**: 6.1.6

**Ruby version**: 2.6

### Additional Context

ActiveStorage Blobs are considered immutable. The table has no `updated_at` column, and the documentation states:

> Blobs are intended to be immutable in as-so-far as their reference to a specific file goes. You're allowed to update a blob's metadata on a subsequent pass, but you should not update the key or change the uploaded file. If you need to create a derivative or otherwise change the blob, simply create a new blob and purge the old one.

In this case, I've added an analyzer and need to update old records to have the additional metadata. This is not a new concept, as Rails added a few new analyzers in Rails 7.0.0 and presumably people would like to have this additional metadata on old records. 
I ran `ActiveStorage::Blob.find_each(&:analyze_later)` to re-analyze my records, but this did not touch my model records that they're associated to, and therefore various caches were not invalidated.

A similar problem can happen due to the fact that attachments are analyzed later. When an attachment is uploaded, `analyze_later` is called, and a background job then downloads the blob, analyzes it, and updates the `ActiveStorage::Blob` to have new metadata.

This means that it's very possible to experience this race condition:

1. Upload attachment (this will create an ActiveStorage::Blob, ActiveStorage::Attachment, and `touch` the model) 
2. Enqueue analyze job
3. Request record
4. Build a cache for that record
5. Analyze the attachment. 
6. Request the record again
7. Serve a cache that doesn't include data from the analyzers, because the cache was built before it got analyzed, and the updated_at hasn't changed.

Right now when an `ActiveStorage::Attachment` changes, the attachments's `record` is `touch`ed. I believe that when a Blob changes, all of the attachments' records should be updated as well.

I'm currently running this patch and it does what I expect. I'm wondering if this feels like a PR that Rails would be willing to accept.

```ruby
module ActiveStorageBlobTouchAssociated
  extend ActiveSupport::Concern

  included do
    after_update :touch_attachment_records, if: :saved_change_to_metadata?
  end

private

  def touch_attachment_records
    attachments.includes(:record).each do |attachment|
      attachment.record.touch
    end
  end
end

ActiveSupport.on_load :active_storage_blob do
  include ActiveStorageBlobTouchAssociated
end
```

As an aside, it does make me wonder if the table should have an `updated_at`. While the file you've uploaded to your ActiveStorage Service (like S3) cannot change, the ActiveStorage::Blob can definitely change as analyzers are added/fixed, and more metadata is extracted from the raw file.

### PR DESCRIPTION
**Pull request by natematykiewicz**
### Summary

This fixes a race condition where a record can be requested and have a
cache entry built, before the initial `analyze_later` completes, which
will not be invalidated until something else updates the record.

1. Upload attachment (this will create an ActiveStorage::Blob,
   ActiveStorage::Attachment, and touch the model)
2. Enqueue analyze job
3. Request record
4. Build a cache for that record
5. Analyze the attachment.
6. Request the record again
7. Serve a cache that doesn't include data from the analyzers, because
   the cache was built before it got analyzed, and the updated_at
   hasn't changed.

This also invalidates cache entries when a blob is re-analyzed, which
is helpful if a bug is fixed in an analyzer or a new analyzer is added.

Fixes #45567

### CODE REVIEW

**Comment by natematykiewicz** [comment]
The one failing ActiveRecord test seems unrelated. One ActiveRecord test timed out, I guess.

File: activestorage/app/models/active_storage/blob.rb [hunk 1]
```diff
@@ -402,6 +404,12 @@ def service_metadata
       end
     end
 
+    def touch_attachment_records
+      attachments.includes(:record).each do |attachment|
+        attachment.record.touch
+      end
```
Comment (natematykiewicz) [inline activestorage/app/models/active_storage/blob.rb:410]: My goal is that when the ActiveStorage::Blob changes (which has no updated_at column), the corresponding attachments' records change to invalidate cache.

The associations are currently:

```ruby
class ActiveStorage::Blob < ActiveStorage::Record
  has_many :attachments
end

ActiveStorage::Attachment < ActiveStorage::Record
  belongs_to :record, polymorphic: true, touch: true
  belongs_to :blob, class_name: "ActiveStorage::Blob", autosave: true
end
```

Any time the Attachment changes, it touches `record`. So perhaps I should just make the Blob touch all of its Attachments and let the Attachments touch the `record`s? This change would make my test pass. It does feel a bit weird that right now we can have the Blob change, the `record` change, but not the Attachment.

```suggestion
      attachments.includes(:record).each do |attachment|
        attachment.touch
      end
```

Comment (casperisfine) [reply activestorage/app/models/active_storage/blob.rb:410]: Yeah, I think you should rely on that `touch: true` by just calling `attachment.touch`.

File: activestorage/test/models/blob_test.rb [hunk 2]
```diff
@@ -80,6 +80,25 @@ class ActiveStorage::BlobTest < ActiveSupport::TestCase
...
+      }
+    )
+
+    old_updated_at = user.reload.updated_at
+
+    # Analyze the blob
+    user.avatar.blob.analyze
+
+    # User should have been touched
+    assert_not_equal user.reload.updated_at, old_updated_at
```
Comment (casperisfine) [inline activestorage/test/models/blob_test.rb:99]:
```suggestion
    assert_changes -> { user.reload.updated_at } do
       ...
```

I think you can use `assert_changes` here for clarity.

File: activestorage/app/models/active_storage/blob.rb (hunk 1 above)
Comment (natematykiewicz) [reply activestorage/app/models/active_storage/blob.rb]: Sounds good

File: activestorage/test/models/blob_test.rb (hunk 2 above)
Comment (natematykiewicz) [reply activestorage/test/models/blob_test.rb]: Oh, nice!

**Review by byroot — APPROVED** [review]
Looks good to me.

**Comment by axlekb** [comment]
Just upgraded to `7.1.1` from `7.0.8`

I believe this change is resulting a new unexpected `after_commit` callback on an abstract/parent `ActiveRecord` instance. 
 Unfortunately the `ActiveStorage::Blob#attachments` association loads the abstract/parent instances, and in my case that means the abstract/parent method gets called instead of the instantiated class.  In my case that is `raise 'Define in subclass'`.

**Comment by natematykiewicz** [comment]
Can you put together a script to reproduce the problem in a new issue? 

It's just using ActiveStorage attachments, which have a polymorphic `belongs_to` to your model record, and it is `touch`ing each one. I imagine `touch` probably does trigger an `after_commit` callback, but I don't see why that'd be a problem. Perhaps your `after_commit` could use an `if` to only do logic when certain attributes change, to avoid running on `touch`. A reproduction script would help understand what's going on though.

**Comment by zzak** [comment]
I believe that is fixed by #49723, but as a new feature it cannot be backported. 🤔

**Comment by axlekb** [comment]
Yes, I was able to work around the issue in the way you suggested, however, I did want to report the issue as that may not be possible in all implementations.  It was also a bit surprising

Here's a script I started with (it's not working.... I couldn't get the `touch` to show up in the db log output).  My expectation would be that it would fail because `User#do_something` would get called instead of `SpecialUser#do_something`

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", '7.1.1'
  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: 'Disk'
    }
  }
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true
end

class User < ActiveRecord::Base
  has_one_attached :profile

  after_commit :do_something

  def do_something
    raise 'Define in subclass!'
  end
end

class SpecialUser < User
  def do_something
    puts "Executing subclass callback"
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_analyze
    user = SpecialUser.create!(
      profile: {
        content_type: "text/plain",
        filename: "dummy.txt",
        io: ::StringIO.new("dummy"),
      }
    )
      
  end
end
```

**Comment by zzak** [comment]
@axlekb This is not an issue with Active Storage, but the expected behavior of callbacks in general. This is because you are overriding the definition of `do_something` in the subclass.

You can reproduce the same behavior with just AR:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", path: "~/code/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true
end

class User < ActiveRecord::Base
  after_commit :do_something

  def do_something
    raise 'Define in subclass!'
  end
end

class SpecialUser < User
  def do_something
    puts "Executing subclass callback"
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    SpecialUser.create!
  end
end
```

If you can create a reproduction of your issue, please open a new ticket.

Thank you!

**Comment by axlekb** [comment]
I understand how ActiveRecord works, and that's not the point.

Yes, I am struggling to recreate the issue in a script to reproduce the issue which I openly admitted in my comment.  I thought I was close, and explained what I thought should happen in the script (not in ActiveRecord by default).

ActiveStorage uses the parent class name as the polymorphic reference class name.  With the change in this PR, when the the analyze job instantiates the reference to `touch` it, it creates an instance of the parent class, not the child class.  If you have need different "after_touch" callbacks for different subclasses, you're screwed.

**Comment by natematykiewicz** [comment]
> ActiveStorage uses the parent class name as the polymorphic reference class name.

So are you attaching an ActiveStorage attachment to a Single Table Inheritance model? ActiveStorage just uses a normal polymorphic belongs_to. It's not doing anything special that wouldn't happen with any other polymorphic belongs_to.

Can you look at your ActiveStorage::Attachment records and see what record_type you have in there? Is it the parent or child?

**Comment by axlekb** [comment]
I have looked at my records (and I ran into this issue in my production app), and that's why I'm reporting it here.

Until this change (as far as I understand it), there weren't any built-in calls on an `ActiveStorage::Blob` that would touch its associated `Attachment`.

The `Attachment` touch then causes a `touch` on the polymorphic `record`... but `Attachment` uses the parent record_type, not whatever class was instantiated.

```
class ActiveStorage::Attachment < ActiveStorage::Record
  self.table_name = "active_storage_attachments"

  belongs_to :record, polymorphic: true, touch: true
```

Apologies if I'm not explaining this well.

**Comment by natematykiewicz** [comment]
> Until this change (as far as I understand it), there weren't any built-in calls on an ActiveStorage::Blob that would touch its associated Attachment.

On the ActiveStorage::Blob, no. But every time you attach a blob to a record (create an ActiveStorage::Attachment), it'd touch the record. You were always running this callback every time you attached a file. It just now runs a 2nd time once the Blob has been analyzed.

That's why I'm confused about this being a new problem for you. I'm not presently at a computer currently to dig into how STI models interact with a polymorphic belongs_to.

You never actually answered my question though. Oh your production server, if you run this:

```ruby
ActiveStorage::Attachment.group(:record_type).count
```

Do you see your parent class names or child class names listed? This is an important question to have an answer to.

**Comment by axlekb** [comment]
Apologies for not being more clear. Parent class names are listed.  Thought that was clear from the initial comment:

> Unfortunately the ActiveStorage::Blob#attachments association loads the abstract/parent instances.


Here are some logs that show the two consecutive touches.  The first touch (line 3) occurs on an instance of the subclass (`ProductImport` in this case).
The second touch (line 11) happens on an instance of the parent class `Import` in this case.
```
1  15:24:43 web.1            |   ActiveStorage::Blob Create (3.5ms)  INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "metadata", "byte_size", "checksum", "created_at", "service_name") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"  [["key", "lmz050bpk7p1rs31b53ugco495xc"], ["filename", "xxxx.csv"], ["content_type", "text/csv"], ["metadata", "{\"identified\":true}"], ["byte_size", 35634], ["checksum", "FQH4syh3dL5+3jYyUT2G+g=="], ["created_at", "2023-11-07 20:24:43.925276"], ["service_name", "local"]]
2  15:24:43 web.1            |   ActiveStorage::Attachment Create (2.7ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "csv"], ["record_type", "Import"], ["record_id", 1367], ["blob_id", 1366], ["created_at", "2023-11-07 20:24:43.930857"]]
3  15:24:43 web.1            |   ProductImport Update (3.0ms)  UPDATE "imports" SET "updated_at" = $1 WHERE "imports"."id" = $2  [["updated_at", "2023-11-07 20:24:43.934791"], ["id", 1367]]
4  15:24:43 web.1            |   TRANSACTION (0.6ms)  COMMIT
5  15:24:43 worker_sidekiq.1 | 2023-11-07T20:24:43.946Z pid=24362 tid=b0m class=ImportProcessJob jid=90cd9689245d9bf3e67574db INFO: start
6  15:24:43 web.1            |   Disk Storage (0.5ms) Uploaded file to key: lmz050bpk7p1rs31b53ugco495xc (checksum: FQH4syh3dL5+3jYyUT2G+g==)
7  15:24:43 web.1            |   TRANSACTION (0.6ms)  BEGIN
8  15:24:43 web.1            |   ActiveStorage::Blob Update (1.6ms)  UPDATE "active_storage_blobs" SET "metadata" = $1 WHERE "active_storage_blobs"."id" = $2  [["metadata", "{\"identified\":true,\"analyzed\":true}"], ["id", 1366]]
9  15:24:43 web.1            |   ActiveStorage::Attachment Load (0.6ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."blob_id" = $1  [["blob_id", 1366]]
10 15:24:43 web.1            |   Import Load (1.6ms)  SELECT "imports".* FROM "imports" WHERE "imports"."id" = $1  [["id", 1367]]
11 15:24:43 web.1            |   Import Update (0.7ms)  UPDATE "imports" SET "updated_at" = $1 WHERE "imports"."id" = $2  [["updated_at", "2023-11-07 20:24:43.955711"], ["id", 1367]]
12 15:24:43 web.1            |   TRANSACTION (0.6ms)  COMMIT
13 15:24:43 web.1            | Completed 500 Internal Server Error in 367ms (ActiveRecord: 98.9ms | Allocations: 293294)
14 15:24:43 web.1            | 
15 15:24:43 web.1            | 
16 15:24:43 web.1            |   
17 15:24:43 web.1            | RuntimeError (Define in subclass):
```
Perhaps `rails` association's `inverse` knows to use the instantiated subclass object on the first `touch`.   Its clear that the second touch reloads the association (which is stored with the parent class type).

**Comment by colszowka** [comment]
Hey all,

is there a suggested way how to handle this best together with the optimistic locking feature?

As it stands, due to this change code like this starts getting "random" failures after 7.1 when the user table has a `lock_version` column, because of the touch in the background:

```ruby
user = User.create! name: "Hello"
user.avatar.attach(io: Rails.root.join("public/apple-touch-icon.png").open, filename: "avatar.png")
sleep rand
user.update! name: "World"
```

*Note: I've moved this comment from https://github.com/rails/rails/issues/45567 where I originally posted it as the PR seems more fitting as it introduced this problem, not the issue reported there that was addressed via this PR*

**Comment by feliperaul** [comment]
Having the same issue reported by @colszowka 

Upgrading to 7.1, our rich text editors can't save anymore after pasting any images, because the AnalyzeJob is touching the associated record and bumping `lock_version`, which makes the save fail with 409 Conflict.

**Comment by natematykiewicz** [comment]
Does that mean `touch` is bumping `lock_version`? Because I don't think it should. The lock is there to prevent changes from being lost due to a stale read. But a `touch` only changes `updated_at`. A stale `updated_at` isn't a problem, as the update will just increment it to an even higher timestamp.

**Comment by feliperaul** [comment]
@natematykiewicz Yes, `#lock` bumps `lock_version`.  Just try in your console with any model that has a `lock_version` column, and `Model.last.touch` will bump it.

The code path for #touch is non trivial, but following it, you'll find out that:

`active_record/persistence.rb` defines `#touch` that will call `#_touch_row`:

https://github.com/rails/rails/blob/23729cec4eb591995f6ac6e88e49fd444e011f3c/activerecord/lib/active_record/persistence.rb#L808

And despite there being a `_touch_row` method defined in the same file (persistence.rb), it will actually hit `attribute_methods/dirty.rb` earlier in the call chain:

https://github.com/rails/rails/blob/23729cec4eb591995f6ac6e88e49fd444e011f3c/activerecord/lib/active_record/attribute_methods/dirty.rb#L204-L207

Which will then, finally, hit `locking/optimistic.rb`, where the locking_column is added to @_touch_attr_names

https://github.com/rails/rails/blob/23729cec4eb591995f6ac6e88e49fd444e011f3c/activerecord/lib/active_record/locking/optimistic.rb#L87-L90

Lastly, `active_record/persistence.rb#touch` calls `#_update_row`, which `locking/optimistic.rb` also overrides to actually bump the lock_version.

**Comment by jdelStrother** [comment]
Before I start adding awful monkeypatches to our codebase, did anyone find a decent workaround to prevent `touch` from bumping `lock_version` ?
