### PR TITLE
Fix caching of missed translations

### LINKED ISSUE #45571: MISSING_TRANSLATION from ActionView::Helpers::TranslationHelper is cached in the I18n cache and read back as a different Object
We try upgrading to Rails 6.1 and have the following Problem.
If we call something like `t('some_untranslated_key', default: :hello)` in a view twice the result changes.
This can be reproduced with Rails Rails 7.0.3.

```
(ruby) t('some_untranslated_key', default: :hello)
"Hello world"
(ruby) t('some_untranslated_key', default: :hello)
#<Object:0x00007f96ec466ce0>
```

It might be related to this change https://github.com/rails/rails/commit/d81926fdacbeb384d211e22cff66195c1a753eb5.
The `translated` value from the I18n cache is not `true` for `translated.equal?(MISSING_TRANSLATION)`
The problem is not related to the `default` so I left it out for the example code.

### Steps to reproduce

-  Setup new Rails 7.0.3 application
-  Add i18n caching
-  Put two times the same untranslated i18n call into the view.

```
diff --git a/config/initializers/i18n_cache.rb b/config/initializers/i18n_cache.rb
new file mode 100644
index 0000000..4e305d6
--- /dev/null
+++ b/config/initializers/i18n_cache.rb
@@ -0,0 +1,3 @@
+I18n::Backend::Simple.send(:include, I18n::Backend::Cache)
+
+I18n.cache_store = ActiveSupport::Cache.lookup_store(:memory_store)
```

```
railties-7.0.3/lib/rails/templates/rails/welcome/index.html.erb
  <%= t('foo') %>
  <%= t('foo') %>
```

### Expected behavior
Prints the key of the translation two times

### Actual behavior
Prints the key on the first call and an object on the second call

```
Foo
#<Object:0x00007fbece7dc668>
```

### System configuration
**Rails version**: 7.0.3
**Ruby version**: ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-darwin21]

### Analysis
**First call to t('foo')**

actionview/lib/action_view/helpers/translation_helper.rb#translate
- sets `default = MISSING_TRANSLATION`
- `default` is `#<Object:0x00007fbece12c3b8>`
- calls `translated = ActiveSupport::HtmlSafeTranslation.translate(key, **options, default: default)`

activesupport/lib/active_support/html_safe_translation.rb#translate
- calls `I18n.translate(key, **options)`

i18n-1.11.0/lib/i18n.rb#translate
- calls `translate_key(key, throw, raise, locale, backend, options)`

i18n-1.11.0/lib/i18n.rb#translate_key
- calls `backend.translate(locale, key, options)`

i18n-1.11.0/lib/i18n/backend/cache.rb#translate
- `I18n.perform_caching?` is `true`
- calls `fetch(cache_key(locale, key, options)) { super }`

i18n-1.11.0/lib/i18n/backend/cache.rb#fetch
- calls `result = _fetch(cache_key, &block)`
- `result` is `#<Object:0x00007fbece12c3b8>`

i18n-1.11.0/lib/i18n/backend/cache.rb#_fetch
- calls `result = I18n.cache_store.read(cache_key)`
- `result` is `nil`
- ...
- calls `result = catch(:exception, &block)`
- `result` is `#<Object:0x00007fbece12c3b8>` that is the same as `MISSING_TRANSLATION`

When I call `I18n.cache_store.read(cache_key)` now or later with a second call to `t('foo')` the result allways changes.
Example: `#<Object:0x00007fbedd3a9ed8>`

**Second call to t('foo')**

actionview/lib/action_view/helpers/translation_helper.rb#translate
- calls `translated = ActiveSupport::HtmlSafeTranslation.translate(key, **options, default: default)`
- `translated` is `#<Object:0x00007fbece7dc668>` and `translated.equal?(MISSING_TRANSLATION)` is `false`

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #45571.

When using `Object.new` as a default, we get another object when it is fetched from the cache store - https://github.com/ruby-i18n/i18n/blob/5963031f2cc52847a6c431be2b2b38229b1793d2/lib/i18n/backend/cache.rb#L89

So I used some random number as a default.

### CODE REVIEW

File: actionview/lib/action_view/helpers/translation_helper.rb [hunk 1]
```diff
@@ -119,7 +119,7 @@ def localize(object, **options)
       alias :l :localize
 
       private
-        MISSING_TRANSLATION = Object.new
+        MISSING_TRANSLATION = -1327903252
```
Comment (jonathanhefner) [inline actionview/lib/action_view/helpers/translation_helper.rb:122]: Interesting idea!  Though I am somewhat wary of choosing magic numbers.  `Class.new` also seems to work, but I'm not sure if it works with all cache stores (but maybe that doesn't matter, given the use case).

Another possibility would be to choose a sufficiently unlikely string (e.g. a string of unprintable characters), and change [`equal?`](https://github.com/rails/rails/blob/3cbc7279fbbe3d941f1b0aac4bc13c1620c3c4eb/actionview/lib/action_view/helpers/translation_helper.rb#L93) to `==`.

But I don't know how any of these options affect performance both when using `I18n::Backend::Cache` and not.  And I'm not sure if performance is even a practical concern when using `I18n::Backend::Cache` — see https://github.com/rails/rails/issues/45571#issuecomment-1181930469.

Comment (jonathanhefner) [reply actionview/lib/action_view/helpers/translation_helper.rb:122]: > at least in redis/memcached, where objects are serialized/deserialized.

Objects are [serialized](https://github.com/rails/rails/blob/05ae3faaf3779d53935ab983b75f2dc7c6dfb7fa/activesupport/lib/active_support/cache/memory_store.rb#L188) for `MemoryStore` too, hence the current issue. :wink:  But yes, the implementation may be different.

> I am not sure this is better than just the number.

Generally speaking, using a random anything concerns me because nothing prevents someone else from "randomly" using that thing too.  Another concern, though, is that we'd still be relying on `equal?` to return true for a deserialized object.  For MRI, that's true for smaller numbers (like the one you've chosen), but do you know if that is part of the Ruby spec?

If not, I think using `==` would be safer.  And if we're using `==`, I think using an intentional string like `"\0\a"` or `"\aMISSING"` or similar makes sense.  Although if benchmarks show a significant difference, then I am open to using a number.  But I would feel better about using a larger number (or, in the negative, smaller).

Comment (jonathanhefner) [reply actionview/lib/action_view/helpers/translation_helper.rb]: > I haven't measured, but for sure there will be only a minor difference, if any.

`I18n.translate` can have a [surprising performance difference](https://github.com/rails/rails/pull/44299#discussion_r798781173) depending on the type of its arguments.  I would encourage you to benchmark this. :wink: 

Additionally, whichever constant we choose, would mind also applying it [here](https://github.com/rails/rails/blob/4f818c7202ee26b8d33f8817c6064ba94e386596/activemodel/lib/active_model/naming.rb#L214) and [here](https://github.com/rails/rails/blob/4f818c7202ee26b8d33f8817c6064ba94e386596/activemodel/lib/active_model/translation.rb#L38)?

Comment (jonathanhefner) [reply actionview/lib/action_view/helpers/translation_helper.rb]: I wanted to see how the results compared with `Object.new`, so I adapted my benchmark script from #44299:

<details>
  <summary><strong>Benchmark script</strong></summary>

  ```ruby
  require "benchmark/ips"

  class BaseModel
    extend ActiveModel::Translation
  end

  BlogPost = Class.new(BaseModel)

  NAMED_CLASS = Class.new

  [true, false].each do |missing|
    [false, true].each do |caching|
      I18n.backend = Class.new(I18n::Backend::Simple).new
      if caching
        I18n.backend.class.include(I18n::Backend::Cache)
        I18n.cache_store = ActiveSupport::Cache.lookup_store(:memory_store)
      end

      if !missing
        I18n.backend.store_translations(:en, activemodel: { models: { blog_post: "Blerg" } })
      end

      puts ""
      puts "--- missing: #{missing}, caching: #{caching} ".ljust(72, "-")
      puts ""

      [Object.new, NAMED_CLASS, "\aMISSING\a", 2**30, 2**60].each do |sentinel|
        ActiveModel::Name.send(:remove_const, :MISSING_TRANSLATION)
        ActiveModel::Name.const_set(:MISSING_TRANSLATION, sentinel)

        Benchmark.ips do |x|
          x.report(sentinel.inspect) { BlogPost.model_name.human }
        end
      end
    end
  end
  ```
</details>

The results I got appear to be different than yours:

```
--- missing: true, caching: false --------------------------------------

#<Object:0x00007f376...> 27.906k (± 1.3%) i/s -    140.550k in   5.037437s
         NAMED_CLASS     27.876k (± 0.8%) i/s -    140.913k in   5.055406s
       "\aMISSING\a"     13.512k (± 1.1%) i/s -     68.100k in   5.040470s
          1073741824     27.889k (± 1.0%) i/s -    139.850k in   5.015039s
 1152921504606846976     27.768k (± 1.2%) i/s -    139.850k in   5.037131s

--- missing: true, caching: true ---------------------------------------

#<Object:0x00007f376...> 21.390k (± 1.0%) i/s -    108.579k in   5.076757s
         NAMED_CLASS     23.524k (± 1.3%) i/s -    119.187k in   5.067600s
       "\aMISSING\a"     26.392k (± 0.9%) i/s -    132.300k in   5.013182s
          1073741824     27.862k (± 1.1%) i/s -    140.300k in   5.036137s
 1152921504606846976     27.827k (± 1.0%) i/s -    139.450k in   5.011886s

--- missing: false, caching: false -------------------------------------

#<Object:0x00007f2c4...> 18.859k (± 1.4%) i/s -     94.600k in   5.017336s
         NAMED_CLASS     18.952k (± 0.8%) i/s -     96.186k in   5.075477s
       "\aMISSING\a"     18.905k (± 1.4%) i/s -     96.084k in   5.083430s
          1073741824     18.827k (± 0.9%) i/s -     95.268k in   5.060580s
 1152921504606846976     18.734k (± 1.3%) i/s -     95.064k in   5.075230s

--- missing: false, caching: true --------------------------------------

#<Object:0x00007f376...> 24.845k (± 1.1%) i/s -    124.350k in   5.005617s
         NAMED_CLASS     26.684k (± 1.0%) i/s -    136.017k in   5.097946s
       "\aMISSING\a"     26.510k (± 1.0%) i/s -    134.844k in   5.087075s
          1073741824     26.715k (± 1.1%) i/s -    134.500k in   5.035266s
 1152921504606846976     26.728k (± 1.1%) i/s -    133.950k in   5.012120s
```

If you run my script, do you see similar results?  If so, what is causing the discrepancy with the results you posted?

In particular, I would like to point out that when "missing: true" (which is common enough for e.g. `model_name.human`), caching in almost every case appears to be slower than not caching while using `MISSING_TRANSLATION = Object.new`.  However, caching *does* appear to provide a significant speed-up when "missing: false".  Those are the kind of results I was looking for in https://github.com/rails/rails/issues/45571#issuecomment-1181930469.

On the plus side, it looks like there is a strong case for using a large integer for `MISSING_TRANSLATION`. :smiley:

Comment (fatkodima) [reply actionview/lib/action_view/helpers/translation_helper.rb]: It was kinda obvious that the number should be faster than the string 😄 
I am seeing similar results with your benchmark. My benchmark was very simple and on the view context.
There is a very little probability someone will use a random 32-bits integer, but lets use a bigger integer, since it shows the same results.

And thank you for the patience and detailed comments ❤️! I hope this will be merged this time 😄

**Comment by jonathanhefner** [comment]
To wind this down, I pushed a commit to replace `1152921504606846976` with `2**60`.  I did not want future readers to wonder whether the number was significant (or random).  Also, it occured to me that, if caching is involved, all three `MISSING_TRANSLATION` values should be kept in sync, and that's easier to verify with `2**60`.  (If you want to submit a PR with a more robust strategy or even just more test coverage, I will gladly take a look!)

Thank you, @fatkodima! :raised_hands:
