### PR TITLE
Fix adding non-null column to existing SQLite3 table

### LINKED ISSUE #38129: Cannot Directly Create Not-Null Columns in Existing SQLite3 Table
### Steps to reproduce
Run the following code:
```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table(:foo) { }
  create_table(:bar) { }
end

class BugTest < Minitest::Test
  def test_add_not_null_column_directly
    ActiveRecord::Schema.define do
      change_table :foo do |t|
        t.string :name, null: false
      end
    end
  end

  def test_add_not_null_column_with_copy
    ActiveRecord::Schema.define do
      change_table :bar do |t|
        t.string :name, null: true
        t.change :name, :string, null: false
      end
    end
  end

end
```

### Expected behavior
Both tests pass.

### Actual behavior
`test_add_not_null_column_directly` test fails with message `ActiveRecord::StatementInvalid: SQLite3::SQLException: Cannot add a NOT NULL column with default value NULL`                                                         

### System configuration
**Rails version**: `6.1.0.alpha` (`master@3c28e79`)
**Ruby version**: `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]`

===

So I can't find this in previous issues though I'm surprised because it has apparently [existed](https://stackoverflow.com/questions/3170634/how-to-solve-cannot-add-a-not-null-column-with-default-value-null-in-sqlite3) since at least 2013, but basically SQLite3 doesn't support directly adding non-null columns to tables after they are created, even if they are empty. As a result, attempting to add such a column using a simple `add_column` will fail.

`AR`, however, implements a (somewhat hacky, yet necessary) workaround to *change* columns in SQLite3 schemas (as there is no `ALTER COLUMN` support), and this same workaround could be utilized to achieve the desired result in this case. (i.e Create the column as nullable and then immediately invoke the relevant method to make it not nullable.)

Will take a stab at a PR for this shortly.

### PR DESCRIPTION
**Pull request by mvastola**
Forces adding the column by way of copying the table due to lack of support in SQLite3 adapter.

Fixes #38129

### Summary

See #38129

### Other Information

Test case added as well.

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb [hunk 1]
```diff
@@ -365,7 +365,7 @@ def table_structure(table_name)
         # See: https://www.sqlite.org/lang_altertable.html
         # SQLite has an additional restriction on the ALTER TABLE statement
         def invalid_alter_table_type?(type, options)
-          type.to_sym == :primary_key || options[:primary_key]
+          type.to_sym == :primary_key || options[:primary_key] || !options.fetch(:null, true)
```
Comment (kamipo) [inline activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb]: https://www.sqlite.org/lang_altertable.html

> If a NOT NULL constraint is specified, then the column must have a default value other than NULL.

```suggestion
          type.to_sym == :primary_key || options[:primary_key] ||
            options[:null] == false && options[:default].nil?
```

Comment (mvastola) [reply activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb]: Good catch. Thanks!

**Comment by kamipo** [comment]
Looks good to me. Can you squash commits into one?

**Comment by mvastola** [comment]
@kamipo, on it. Also, what do you make of the [failed CI test](https://buildkite.com/rails/rails/builds/66133)? Is this a transient issue or something changed in the buildkite config? 

My PR doesn't touch ActionView or the other components at issue, and this was [working before](https://buildkite.com/rails/rails/builds/66080) I adopted your suggested change (which looks fine to me).

**Comment by kamipo** [comment]
That failure is already fixed on master by #38136.

**Comment by mvastola** [comment]
@kamipo, oh, Did my accepting your change on the GitHub site somehow automatically rebase my fork with the latest master? It's weird that it didn't tell me it was going to do that, but that's the only explaination since I never ran `git rebase` or equivalent.

In any case, squash is done. Waiting for new CI test.

**Comment by mvastola** [comment]
Oh, wait, that means I should have rebased from upstream master before squashing and I didn't. Fixing now.

**Comment by mvastola** [comment]
Ok. Still getting a couple of failures, but fewer than before.

**Comment by kamipo** [comment]
CI failure on Ruby master is due to fully positional arguments and keyword arguments separation https://github.com/ruby/ruby/pull/2794, not for this PR.
