### PR TITLE
Fix: Ensure association target is only set if there is not a foreign key mismatch

### LINKED ISSUE #40018: `unscoped` and `or` active record queries incorrectly refer to inverse instance
### Steps to reproduce
([gist](https://gist.github.com/1a0b8ee9753be9b6db95d236c6994102))

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :authors, force: true do |t|
  end

  create_table :books, force: true do |t|
    t.references :author
  end
end

class Author < ActiveRecord::Base
  has_many :books

  def all_books
    books.unscope(:where)
  end
end

class Book < ActiveRecord::Base
  belongs_to :author
end

class BugTest < Minitest::Test
  def test_unscoped
    Book.delete_all
    Author.delete_all
    author_a = Author.create!
    author_b = Author.create!

    Book.create(author: author_a)

    book = author_b.all_books.first

    assert_equal book.author, author_a
  end

  def test_or
    Book.delete_all
    Author.delete_all
    author_a = Author.create!
    author_b = Author.create!

    Book.create(author: author_a)

    book = author_b.books.or(author_a.books).first

    assert_equal book.author, author_a
  end
end
```

### Expected behavior
Here we would expect `author_b.all_books.first.author` and `author_b.books.or(author_a.books).first.author` to return `author_a`

### Actual behavior
Instead they seem to be taking the inverse and returning `author_b` in each case.

### System configuration
**Rails version**: 6.1.0.alpha (also fails in 6.0.3 and 5.2.4)

**Ruby version**: 2.7.1

### PR DESCRIPTION
**Pull request by leequarella**
fixes #40018

Prior to this commit, the following test would fail. `book`'s author was
actually being returned as `author_b`. (The same would happen for
`unscope`.)

```ruby
    def test
      author_a = Author.create!
      author_b = Author.create!

      Book.create(author: author_a)

      book = author_b.books.or(author_a.books).first

      assert_equal book.author, author_a
    end
```

Fixed here by ensuring `inverse` is not set incorrectly.

### CODE REVIEW

**Review by jhawthorn — APPROVED** [review]
Seems good to me.

I'm a little concerned the extra checks might slow down large association loads, but of course correctness is more important.

File: activerecord/lib/active_record/associations/association.rb [hunk 1]
```diff
@@ -321,6 +325,19 @@ def skip_statement_cache?(scope)
...
         end
+
+        def inversable?(record)
+          record &&
+            ((!record.persisted? || !owner.persisted?) || matches_foreign_key?(record))
+        end
+
+        def matches_foreign_key?(record)
+          if foreign_key_for?(record)
+            record.read_attribute(reflection.foreign_key) == owner.id
```
Comment (kamipo) [inline activerecord/lib/active_record/associations/association.rb:336]: This check isn't perfectly correct for polymorphic association.

Comment (leequarella) [reply activerecord/lib/active_record/associations/association.rb:336]: If I'm understanding correctly, this should also check to make sure the type matches in order to be completely correct? I have written some code locally to check for this type match in addition to the key match. But since we are always looking at reflections I struggle to setup a situation with a type mismatch to write a test against.

**Comment by artygus** [comment]
@leequarella very unexpected bug, thanks for addressing this one! any chance this could get merged anytime soon?

File: activerecord/lib/active_record/associations/association.rb (hunk 1 above)
Comment (jhawthorn) [reply activerecord/lib/active_record/associations/association.rb:340]: I couldn't find a way to test for this being an issue. The issue this fixes comes from expanding the association scope using `.or` or similar, but I don't think we can expand it in a way to include a different table or primary key collisions (at least not that I know of in a way that's reasonably supported)

**Review by jhawthorn — APPROVED** [review]
