### PR TITLE
`allow_nil` should work for casted value in `NumericalityValidator`

### LINKED ISSUE #40750: NumericalityValidator `allow_nil` option doesn't work anymore for params coming from a controller
`numericality` validation helper behaviour on attributes of an ActiveRecord object created using  `ActionController::Parameters` has changed in Rails 6.1.0.rc2. It could be related to [this refactoring](https://github.com/rails/rails/commit/4cc438a1df75e4c230f19cafe9258dbab969cd27)

### Steps to reproduce

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", '6.1.0.rc2'
  gem "sqlite3"
end

require "action_controller"
require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :comments, force: true do |t|
     t.integer :priority
  end
end

class Comment < ActiveRecord::Base
  validates :priority, numericality: { greater_than: 0 }, allow_nil: true
end

class BugTest < Minitest::Test
  def test_numericality_validation
    params = ActionController::Parameters.new({ comment: { priority: '' } })
    comment = Comment.new(params.require(:comment).permit!)

    assert comment.valid?
  end
end
```

### Expected behavior
`allow_nil` option should allow to skip numericality validation for empty `ActionController::Parameters` fields. Having to switch to `allow_blank` option would be a breaking change.

### Actual behavior
`numericality` validation fails with empty fields even if `allow_nil` option is specified.

### System configuration
**Rails version**: 6.1.0.rc2

**Ruby version**: 2.7.2

### PR DESCRIPTION
**Pull request by kamipo**
It is a regression for 4cc438a1df75e4c230f19cafe9258dbab969cd27.

`NumericalityValidator` basically takes the value before typecasting,
but `allow_nil` should work for the typecasted value for the
compatibility.

Fixes #40750.

### CODE REVIEW

File: activemodel/lib/active_model/validator.rb [hunk 1]
```diff
@@ -167,7 +168,9 @@ def check_validity!
 
     private
       def read_attribute_for_validation(record, attr_name)
-        record.read_attribute_for_validation(attr_name)
+        value = record.read_attribute_for_validation(attr_name)
+        throw(:allowed) if (value.nil? && options[:allow_nil]) || (value.blank? && options[:allow_blank])
```
Comment (rafaelfranca) [inline activemodel/lib/active_model/validator.rb:172]: Moving the checks here actually make the API for custom validations worse. Users need to know that they need to deal with those options inside `read_attribute_for_validation` while before they didn't. I believe we should continue doing this check inside to keep users not needing to worry about checking for those options.

Can we split the job of `read_attribute_for_validation` in two? One which does `record.read_attribute_for_validation(attr_name)` and we use for the options checks and the other than calculate `value` that we will pass to `validate_each`? This will also avoid the `throw/abort`.

Comment (kamipo) [reply activemodel/lib/active_model/validator.rb]: I agree that it is not ideal, the intent of the implementation was to avoid extra `value` argument for `read_attribute_for_validation`.
I've given up that finally, splited the job and add `value` argument for `read_attribute_for_validation` in 720a60e68cf1945b6f486faca322d3acfa59c652 (perhaps `read_attribute_for_validation` no longer appropriate name now?).

Comment (rafaelfranca) [reply activemodel/lib/active_model/validator.rb]: Agree the name is not matching the behaviour anymore. I'd call it `prepare_value_for_validation`.
