### PR TITLE
Fix generated projection fields in group by query

### LINKED ISSUE #21922: Count query grouped by association may trigger a SQL error (ambiguous column name)
When doing a count query grouped by an association, the foreign key is not prepended with the table name  in the generated sql query. That triggers a "ambiguous column name" SQL error if a joined table contains a column with the same name.

Test case: https://gist.github.com/jplang/7c08634b61210b4193f9

Result with Rails 4.2:

```
  1) Error:
BugTest#test_group_by_association_doesnt_error_with_ambiguous_column_name:
ActiveRecord::StatementInvalid: SQLite3::SQLException: ambiguous column name: au
thor_id: SELECT COUNT(*) AS count_all, author_id AS author_id FROM "books" INNER
 JOIN "photos" ON "photos"."book_id" = "books"."id" GROUP BY author_id
```

### PR DESCRIPTION
**Pull request by rafaelsales**
1. 1st commit: Fix generated projection fields in group by query (closes #21922)
   
   Let `Book(id, author_id)`, `Photo(id, book_id, author_id)` and `Author(id)`
   
   Running `Book.group(:author_id).joins(:photos).count` will produce:
   - Rails 4.2 - conflicts `author_id` in both projection and group by:
   
   ``` sql
   SELECT COUNT(*) AS count_all, author_id AS author_id
     FROM "books" INNER JOIN "photos" ON "photos"."book_id" = "books"."id"
    GROUP BY author_id
   ```
   - Master (9d02a25) - conflicts `author_id` only in projection:
   
   ``` sql
   SELECT COUNT(*) AS count_all, author_id AS author_id
     FROM "books" INNER JOIN "photos" ON "photos"."book_id" = "books"."id"
    GROUP BY "books"."author_id"
   ```
   - With this fix:
   
   ``` sql
   SELECT COUNT(*) AS count_all, "books"."author_id" AS books_author_id
     FROM "books" INNER JOIN "photos" ON "photos"."book_id" = "books"."id"
    GROUP BY "books"."author_id"
   ```
2. 2nd commit: Refactor Calculations#execute_grouped_calculation and clean AR test case
   - Removing "Company has_many :accounts" test/models/company.rb because:
   
   ``` sql
   ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: accounts.company_id:
    SELECT COUNT(*) AS count_all, "companies"."firm_id" AS companies_firm_id
       FROM "companies" INNER JOIN "accounts" ON "accounts"."company_id" = "companies"."id"
   GROUP BY "companies"."firm_id"
   ```
   - The refactor on Calculations class was just to simplify the code

### CODE REVIEW

**Comment by mrageh** [comment]
:+1:

File: activerecord/test/models/company.rb [hunk 1]
```diff
@@ -10,7 +10,6 @@ class Company < AbstractCompany
   has_one :dummy_account, :foreign_key => "firm_id", :class_name => "Account"
   has_many :contracts
   has_many :developers, :through => :contracts
-  has_many :accounts
```
Comment (pixeltrix) [inline activerecord/test/models/company.rb]: Is this being deleted because it was also defined in `Firm` ?

Comment (rafaelsales) [inline activerecord/test/models/company.rb]: @pixeltrix 
Not only that, but also because `Account` is defined as:
```ruby
  create_table :accounts, force: true do |t|
    t.integer :firm_id
    t.string  :firm_name
    t.integer :credit_limit
  end
```
So, `company.accounts` fails because `accounts` doesn't have `company_id`. ITOH, `firm.accounts` works because `accounts` has `firm_id`

Comment (pixeltrix) [inline activerecord/test/models/company.rb]: :+1:

Comment (pixeltrix) [inline activerecord/test/models/company.rb]: Turns out that definition originated in this commit: 99307b959b1c16ab1dd0400a7398019fe9d5494b - where I don't think it was actually used. :smile:

Comment (rafaelsales) [inline activerecord/test/models/company.rb]: Yeah... probably just small oversight of a pair eyes tired of hard work

**Comment by mrageh** [comment]
@rafaelsales it would be nice if you could update your branch with the latest master and hopefully we can get it merged in today

**Comment by rafaelsales** [comment]
@mrageh @arthurnn @pixeltrix  done

**Comment by rafaelsales** [comment]
Ping. Waiting for Pong from committer so I can rebase again

**Comment by pixeltrix** [comment]
@rafaelsales please rebase and I'll merge today if it's green

**Comment by rafaelsales** [comment]
@pixeltrix Rebased and tests passed
