### PR TITLE
Fix ActiveJob arguments serialization to correctly serialize String subclasses having custom serializers

### LINKED ISSUE #50076: Incorrect serialization of `ActiveSupport::StringInquirer` instances
### Steps to reproduce

Consider the following MRE:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activejob", "~> 7.1.0"
  gem "sidekiq", "~> 7.2.0"
end

require "minitest/autorun"
require "active_job"
require "active_support/core_ext/string/inquiry"

class BuggyJob < ActiveJob::Base
  self.queue_adapter = :sidekiq

  def perform(argument)
    p argument
  end
end

class BuggyJobTest < ActiveJob::TestCase
  def test_stuff
    BuggyJob.perform_later("paid".inquiry)
    perform_enqueued_jobs
  end

  def queue_adapter_for_test
    ActiveJob::QueueAdapters::SidekiqAdapter.new
  end
end
```

Basically we pass an instance of `ActiveSupport::StringInquirer` to `.perform_later` (note that queue adapter is set to `sidekiq`), and I expect it to be serialized correctly. In fact, an exception occurs (I believe that's because of [this](https://github.com/sidekiq/sidekiq/issues/5246) sidekiq change.)

It happenes because here

https://github.com/rails/rails/blob/6b93fff8af32ef5e91f4ec3cfffb081d0553faf0/activejob/lib/active_job/arguments.rb#L74-L76

first comparsion (with `PERMITTED_TYPES`) passes because that's equivalent with

```ruby
[String].any? { "foo".inquiry.is_a? _1 }
true
```

Unfortunately, it cannot be bypassed "in place" (without monkeypatching) with custom AJ serializer (via `Rails.application.config.active_job.custom_serializers << ` API) because checking against String subclass passes, so fallback for custom serializer doesn't happen.

### Expected behavior
I expect an instance of `ActiveSupport::StringInquirer` to be serialized and serialized correctly.

Serialization should be as easy as

```ruby
class StringInquirerSerializer < ObjectSerializer # :nodoc:
  def serialize(argument)
    super("value" => argument.to_s)
  end

  def deserialize(argument)
    argument["value"].inquiry
  end

  private
    def klass
      ActiveSupport::StringInquirer
    end
end
```

so I don't see why this custom serializer (with taking into account the issue I mentioned above) wouldn't work. 

### Actual behavior
```
  1) Error:
BuggyJobTest#test_stuff:
ArgumentError: Job arguments to BuggyJob must be native JSON types, but "paid" is a ActiveSupport::StringInquirer.
See https://github.com/sidekiq/sidekiq/wiki/Best-Practices
To disable this error, add `Sidekiq.strict_args!(false)` to your initializer.


.../sidekiq-7.2.0/lib/sidekiq/job_util.rb:33:in `verify_json'
.../sidekiq-7.2.0/lib/sidekiq/client.rb:92:in `push'
.../sidekiq-7.2.0/lib/sidekiq/job.rb:361:in `client_push'
...
```

### System configuration
**Rails version**: 7.0.8, 7.1.2
**Ruby version**: 3.2.2
**Sidekiq version**: 7.2.0

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #50076 (look there for a lengthy discussion).

Should we also raise a deprecation warning for String subclasses without custom serializers? It worked before this change.

cc @byroot

### CODE REVIEW

File: activejob/lib/active_job/arguments.rb [hunk 1]
```diff
@@ -72,8 +72,14 @@ def deserialize(arguments)
 
       def serialize_argument(argument)
         case argument
-        when *PERMITTED_TYPES
```
Comment (byroot) [inline activejob/lib/active_job/arguments.rb:75]: `PERMITTED_TYPES` is now only used in `deserialize_argument`, perhaps we can get rid of it.

**Review by byroot — APPROVED** [review]

File: activejob/lib/active_job/arguments.rb (hunk 1 above)
Comment (fatkodima) [reply activejob/lib/active_job/arguments.rb:75]: Thanks, deleted.

**Comment by byroot** [comment]
Backported to 7-1-stable as 49ac7e511db007085c0c911f10215f20b5c5dd99
