### PR TITLE
While using perform_enqueued_jobs enqueued jobs must be stored as well

### LINKED ISSUE #38584: ActiveJob perform_enqueued_jobs filters out enqueued jobs
ActiveJob `perform_enqueued_jobs` must not filter out jobs which should go to the enqueued jobs list.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activejob", "6.0.0"
end

require "minitest/autorun"
require "active_job"

class PerformJob < ActiveJob::Base
  def perform
    puts "performed"
  end
end

class EnqueueJob < ActiveJob::Base
  def perform
    puts "performed"
  end
end

class EnqueueJobTest < ActiveJob::TestCase
  def test_stuff
    perform_enqueued_jobs(only: PerformJob) do
      assert_enqueued_with(job: EnqueueJob) do
        PerformJob.perform_later
        EnqueueJob.perform_later
      end
    end
  end
end
```

### Expected behavior

While using `perform_enqueued_jobs` enqueued jobs must be stored for the later check with `assert_enqueued_with`.

### Actual behavior

Current behaviour filters out all the jobs which are not being performed. Because of that you are not able to make an `assert_enqueued_with` of the jobs were not included in `only` option.

### System configuration
**Rails version**: 6.0
**Ruby version**: 2.6.1

### PR DESCRIPTION
**Pull request by dmitry**
Resolves #38584

### CODE REVIEW

File: activejob/lib/active_job/queue_adapters/test_adapter.rb [hunk 1]
```diff
@@ -26,15 +26,11 @@ def performed_jobs
       end
 
       def enqueue(job) #:nodoc:
-        return if filtered?(job)
-
         job_data = job_to_hash(job)
         perform_or_enqueue(perform_enqueued_jobs, job, job_data)
```
Comment (etiennebarrie) [inline activejob/lib/active_job/queue_adapters/test_adapter.rb]: What do you think about keeping the filtering logic in these two methods, just tweaking the boolean argument, that way we don't add that responsibility to `perform_or_enqueue`?

Comment (dmitry) [reply activejob/lib/active_job/queue_adapters/test_adapter.rb]: @etiennebarrie it will be slower a bit, as in case of non perform condition `filtered?` will be called anyway. I'd leave it as it is, but in other case I can change `perform_or_enqueue` to the following interface `perform, job, job_data, filtered`.

Comment (etiennebarrie) [reply activejob/lib/active_job/queue_adapters/test_adapter.rb]: I don't think it would be any slower to have something like `perform_or_enqueue(perform_enqueued_jobs && !filtered?(job), job, job_data)`. 
Similarly to your changes, it would only call `filtered?` if `perform_enqueued_jobs` is false, it just keep the logic here rather than inside `perform_or_enqueue`.

Comment (dmitry) [reply activejob/lib/active_job/queue_adapters/test_adapter.rb]: @etiennebarrie :+1: I will change it to your solution.

**Comment by etiennebarrie** [comment]
cc @rafaelfranca
