### PR TITLE
Consistency between first() and last() with limit

### LINKED ISSUE #23607: Model.limit(1).first orders on primary key, but Model.limit(1).last does not
I noticed today that in some ways the ActiveRecord methods`first` and `last` are not fully symmetrical.

For instance, on their own they produce parallel queries:

```
Unit.first
  > SELECT  "units".* FROM "units" ORDER BY "units"."id" ASC LIMIT $1  [["LIMIT", 1]]

Unit.last
  > SELECT  "units".* FROM "units" ORDER BY "units"."id" DESC LIMIT $1  [["LIMIT", 1]]
```

But chain a `limit` relation, and they no longer behave the same:

```
Unit.limit(1).first
  > SELECT  "units".* FROM "units" ORDER BY "units"."id" ASC LIMIT $1  [["LIMIT", 1]]

Unit.limit(1).last
  > SELECT  "units".* FROM "units" LIMIT $1  [["LIMIT", 1]]
```

This results in the fact that:
`Unit.limit(1).first == Unit.first`
but:
`Unit.limit(1).last != Unit.last`.

### LINKED ISSUE #23979: ActiveRecord first() and last() behave differently with limit()
### Steps to reproduce

``` ruby
5.times do
  Topic.create!
end

Topic.limit(1).first(2)
  Topic Load (0.8ms)  SELECT  "topics".* FROM "topics" ORDER BY "topics"."id" ASC LIMIT $1  [["LIMIT", 2]]
=> [#<Topic id: 1>, #<Topic id: 2>]

Topic.limit(1).last(2)
  Topic Load (0.3ms)  SELECT  "topics".* FROM "topics" LIMIT $1  [["LIMIT", 1]]
=> [#<Topic id: 5>]
```
### Expected behavior

I would expect that, for any ActiveRecord relation, `first(n).size` and `last(n).size` would always be equal.
### Actual behavior

The `first(n)` method seems to "overwrite" the `limit(1)`, whereas the `last(n)` method respects it. As a result, `Topic.limit(1).first(2).size` is 2 and `Topic.limit(1).last(2).size` is 1.

In my opinion the behavior of the `last(n)` method is correct. This is consistent with DHH's comments here, for instance: https://github.com/rails/rails/pull/23598#issuecomment-189675440.

This would seem to suggest that the `first(n)` method should ought to return an array of size 1 in the case of `Topic.limit(1).first(2)`.
### System configuration

**Rails version**: current `master` (https://github.com/rails/rails/commit/75097933e26e5147f666f485d41b38967c76311c)

**Ruby version**: 2.3.0

### PR DESCRIPTION
**Pull request by brchristian**
Fixes #23979.

As discussed in #23979, there was an inconsistency between the way that `first()` and `last()` would interact with `limit`. Specifically:

```Ruby
> Topic.limit(1).first(2).size
=> 2
> Topic.limit(1).last(2).size
=> 1
```

This PR is a refactor and rebase of #24124, with a simpler test suite and simpler implementation.

Discussion with Rails community members as well as DHH in https://github.com/rails/rails/pull/23598#issuecomment-189675440 showed that the behavior or `first` should be brought into line with `last` (rather than vice-versa).

This PR resolves the inconsistency between `first` and `last` when used in conjunction with `limit`.

### CODE REVIEW

**Comment by kamipo** [comment]
Can you rebase?

**Comment by brchristian** [comment]
@kamipo Rebased to latest `master` 👍

File: activerecord/lib/active_record/relation/finder_methods.rb [hunk 1]
```diff
@@ -533,6 +533,12 @@ def find_nth_with_limit(index, limit)
           relation = ordered_relation
 
           if limit_value.nil? || index < limit_value
+
+            if limit_value.present?
+              limit = [limit_value - index, limit].min
+              limit = [limit, 0].max
```
Comment (kamipo) [inline activerecord/lib/active_record/relation/finder_methods.rb]: If `limit <= 0`, we don't need a query to database.

```diff
diff --git a/activerecord/lib/active_record/relation/finder_methods.rb b/activerecord/lib/active_record/relation/finder_methods.rb
index e61cacf6a7..50d0f14b98 100644
--- a/activerecord/lib/active_record/relation/finder_methods.rb
+++ b/activerecord/lib/active_record/relation/finder_methods.rb
@@ -532,7 +532,11 @@ def find_nth_with_limit(index, limit)
         else
           relation = ordered_relation
 
-          if limit_value.nil? || index < limit_value
+          if limit_value
+            limit = [limit_value - index, limit].min
+          end
+
+          if limit > 0
             relation = relation.offset(offset_index + index) unless index.zero?
             relation.limit(limit).to_a
           else
```

File: activerecord/test/cases/finder_test.rb [hunk 2]
```diff
@@ -693,6 +693,11 @@ def test_take_and_first_and_last_with_integer_should_return_an_array
     assert_kind_of Array, Topic.last(5)
   end
 
+  def test_take_and_first_and_last_with_limit_should_return_same_size
+    topics = Topic.limit(1)
+    assert_equal topics.first(2).size, topics.last(2).size
```
Comment (kamipo) [inline activerecord/test/cases/finder_test.rb]: `first` with `limit` doesn't work as expected, and inconsistent with `last` is true.
But it is also inconsistent with loaded `first` with `limit`.
Can you more exercise tests like `test_last_on_relation_with_limit_and_offset`?

```ruby
  def test_find_on_relation_with_limit_and_offset
    post = posts("sti_comments")

    comments = post.comments.order(id: :asc)
    assert_equal comments.limit(2).to_a.first, comments.limit(2).first
    assert_equal comments.limit(2).to_a.first(2), comments.limit(2).first(2)
    assert_equal comments.limit(2).to_a.first(3), comments.limit(2).first(3)

    assert_equal comments.offset(2).to_a.first, comments.offset(2).first
    assert_equal comments.offset(2).to_a.first(2), comments.offset(2).first(2)
    assert_equal comments.offset(2).to_a.first(3), comments.offset(2).first(3)

    comments = comments.offset(1)
    assert_equal comments.limit(2).to_a.first, comments.limit(2).first
    assert_equal comments.limit(2).to_a.first(2), comments.limit(2).first(2)
    assert_equal comments.limit(2).to_a.first(3), comments.limit(2).first(3)
  end
```
 
https://github.com/rails/rails/blob/7c69351277edaa47ee395c72d59623162eb8682f/activerecord/test/cases/finder_test.rb#L672-L688

File: activerecord/lib/active_record/relation/finder_methods.rb (hunk 1 above)
Comment (brchristian) [reply activerecord/lib/active_record/relation/finder_methods.rb]: Great point! I have updated the PR.

File: activerecord/test/cases/finder_test.rb (hunk 2 above)
Comment (brchristian) [reply activerecord/test/cases/finder_test.rb]: No problem, I have added additional tests for compatibility here between `limit(x).first(y)` and `limit(x).to_a.first(y)`, and they all now pass as well.

**Comment by brchristian** [comment]
@kamipo Thanks for code review. I have refactored and added the additional tests.

File: activerecord/test/cases/finder_test.rb [hunk 3]
```diff
@@ -693,6 +693,30 @@ def test_take_and_first_and_last_with_integer_should_return_an_array
     assert_kind_of Array, Topic.last(5)
   end
 
+  def test_first_and_last_with_limit_should_return_same_size_loaded_or_not
+    topics = Topic
+
+    assert_equal topics.limit(1).to_a.first(2).size, topics.limit(1).first(2).size
+    assert_equal topics.limit(2).to_a.first(2).size, topics.limit(2).first(2).size
+    assert_equal topics.limit(3).to_a.first(2).size, topics.limit(3).first(2).size
```
Comment (kamipo) [inline activerecord/test/cases/finder_test.rb]: Can you remove `.size`? These need to be the same result regardless of whether they are loaded or not.

File: activerecord/test/cases/finder_test.rb [hunk 4]
```diff
@@ -693,6 +693,30 @@ def test_take_and_first_and_last_with_integer_should_return_an_array
...
+
+    assert_equal topics.limit(1).to_a.last(2).size, topics.limit(1).last(2).size
+    assert_equal topics.limit(2).to_a.last(2).size, topics.limit(2).last(2).size
+    assert_equal topics.limit(3).to_a.last(2).size, topics.limit(3).last(2).size
```
Comment (kamipo) [inline activerecord/test/cases/finder_test.rb]: These assersions have already been covered by `test_last_on_relation_with_limit_and_offset`.

https://github.com/rails/rails/blob/7c69351277edaa47ee395c72d59623162eb8682f/activerecord/test/cases/finder_test.rb#L672-L688

File: activerecord/CHANGELOG.md [hunk 5]
```diff
@@ -1,3 +1,11 @@
+*   Fixed inconsistency between `first(n)` and `last(n)` when
+    used with `limit()` The `first` finder respects the `limit()`,
+    making it consistent with `last(n)`.
```
Comment (kamipo) [inline activerecord/CHANGELOG.md]: I think that we should note fixing inconsistency `first(n)` with either loaded or not.
Previously, we need to use `relation.to_a.first(n)` as a workaround, but now, we can use `relation.first(n)` simply.

File: activerecord/test/cases/finder_test.rb [hunk 6]
```diff
@@ -693,6 +693,30 @@ def test_take_and_first_and_last_with_integer_should_return_an_array
...
+  def test_first_and_last_with_limit_should_return_same_size
+    topics = Topic
+
+    assert_equal topics.limit(1).first(2).size, topics.limit(1).last(2).size
+    assert_equal topics.limit(2).first(2).size, topics.limit(2).last(2).size
+    assert_equal topics.limit(3).first(2).size, topics.limit(3).last(2).size
+
+    assert_equal topics.limit(1).to_a.first(2).size, topics.limit(1).to_a.last(2).size
+    assert_equal topics.limit(2).to_a.first(2).size, topics.limit(2).to_a.last(2).size
+    assert_equal topics.limit(3).to_a.first(2).size, topics.limit(3).to_a.last(2).size
```
Comment (kamipo) [inline activerecord/test/cases/finder_test.rb]: `Array#first` and `Array#last` are in the Ruby Core. These assertions are not necessary.

http://ruby-doc.org/core-2.5.0/Array.html#method-i-first
http://ruby-doc.org/core-2.5.0/Array.html#method-i-last

File: activerecord/test/cases/finder_test.rb [hunk 7]
```diff
@@ -693,6 +693,30 @@ def test_take_and_first_and_last_with_integer_should_return_an_array
...
+    assert_equal topics.limit(2).to_a.last(2).size, topics.limit(2).last(2).size
+    assert_equal topics.limit(3).to_a.last(2).size, topics.limit(3).last(2).size
+  end
+
+  def test_first_and_last_with_limit_should_return_same_size
+    topics = Topic
+
+    assert_equal topics.limit(1).first(2).size, topics.limit(1).last(2).size
+    assert_equal topics.limit(2).first(2).size, topics.limit(2).last(2).size
+    assert_equal topics.limit(3).first(2).size, topics.limit(3).last(2).size
```
Comment (kamipo) [inline activerecord/test/cases/finder_test.rb]: Previously `relation.to_a.first(n)`, `relation.to_a.last(n)`, and `relation.last(n)` works expected, but only `relation.first(n)` does not.
Consistency between `relation.to_a.last(n)` and `relation.last(n)` have already been covered by `test_last_on_relation_with_limit_and_offset`.
Whether `relation.first(n)` works correctly should compare `relation.to_a.first(n)` rather than `relation.last(n)`.

**Comment by brchristian** [comment]
@kamipo Great points about the tests and CHANGELOG. I agree with you and I have made all the changes you suggested.

**Review by kamipo — APPROVED** [review]
Looks good to me 👍 
Can you squash your commits into one?

**Comment by brchristian** [comment]
@kamipo Squashed 👍

**Comment by brchristian** [comment]
(PS, Special thanks to @mmlindeboom for helpful discussion!)
