### PR TITLE
assert_file understands paths with special characters

### LINKED ISSUE #20042: assert_file fails when filename has special characters (~, +)
See https://github.com/mperham/sidekiq/issues/2065 for background. These are used to give special meanings to package names in debian (x.y.z~something, means a lower version of x.y.z. this is used to convey ~alpha, ~beta or ~rc should be updated by x.y.z version). I hope this will will be fixed.

### PR DESCRIPTION
**Pull request by dcrec1**
fixes #20042

### CODE REVIEW

**Comment by dcrec1** [comment]
@senny is this fix valid?

File: railties/lib/rails/generators/testing/assertions.rb [hunk 1]
```diff
@@ -23,7 +23,7 @@ module Assertions
         #     end
         #   end
         def assert_file(relative, *contents)
-          absolute = File.expand_path(relative, destination_root).shellescape
+          absolute = File.expand_path(relative, destination_root).gsub(" ", "\\ ")
```
Comment (senny) [inline railties/lib/rails/generators/testing/assertions.rb]: Can you point me in the direction why this `gsub` is needed?

Given:

```
$ ls spaces
file with spaces.txt v0.1.4~alpha+nightly
```

The following script outputs:

```ruby
path = File.expand_path("../spaces/file with spaces.txt", __FILE__)
path # => /Users/senny/Projects/ruby/spaces/file with spaces.txt
File.exist?(path) # => true

path = File.expand_path("../spaces/v0.1.4~alpha+nightly", __FILE__)
path # => /Users/senny/Projects/ruby/spaces/v0.1.4~alpha+nightly
File.exist?(path) # => true
```

Comment (dcrec1) [inline railties/lib/rails/generators/testing/assertions.rb]: @senny Is to avoid breaking this [test](https://github.com/rails/rails/pull/12606/files#diff-1c12e9f760307fdabb690b66537de420R370) in #12606 . It breaks because the [path](https://github.com/rails/rails/pull/12606/files#diff-1c12e9f760307fdabb690b66537de420R371) got `shellescaped`. If `shellescape` is removed from this line, the test pass. 

May I edit the test?

Comment (senny) [inline railties/lib/rails/generators/testing/assertions.rb]: yes, please do.

**Comment by senny** [comment]
Thank you :yellow_heart:
