### PR TITLE
Fix in-place modification of shared `_counter_cache_columns` class attribute

### LINKED ISSUE #49132: Column not updated when counter_cache columns overlap with model db field
### Steps to reproduce

This works fine with 7.0.7.2 but fails on main. ~~I'm fairly sure it has something to do with #48665.~~

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :tags, force: true do |t|
    t.integer :post_count
  end
  create_table :posts, force: true do |t|
  end
  create_table :user_statuses, force: true do |t|
  end
end

class Tag < ActiveRecord::Base
end

class UserStatus < ActiveRecord::Base
end

class Post < ActiveRecord::Base
  belongs_to :user_status, counter_cache: :post_count
end

class BugTest < Minitest::Test
  def test_association_stuff
    tag = Tag.create!(post_count: 4)
    tag.update!(post_count: 10)

    assert_equal(10, tag.reload.post_count)
  end
end
```

### Expected behavior
The column should be updated.

### Actual behavior
The column remains the same.

### System configuration
**Rails version**: main

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #49132.

`_counter_cache_columns` class attribute is defined on `ActiveRecord::Base` class and all models share its value. We should not modify it in place, but reassign to it.

### CODE REVIEW

File: activerecord/lib/active_record/associations/builder/belongs_to.rb [hunk 1]
```diff
@@ -37,7 +37,7 @@ def self.add_counter_cache_callbacks(model, reflection)
       }
 
       klass = reflection.class_name.safe_constantize
-      klass._counter_cache_columns << cache_column if klass && klass.respond_to?(:_counter_cache_columns)
+      klass._counter_cache_columns |= [cache_column] if klass && klass.respond_to?(:_counter_cache_columns)
```
Comment (akhilgkrishnan) [inline activerecord/lib/active_record/associations/builder/belongs_to.rb:40]: @fatkodima Just curious to know, how this exactly fixes the issue. In both cases, we are appending the column to the `_counter_cache_columns` right?

**Comment by Earlopain** [comment]
Just to confirm, this fixes my original issue. That was a strange experience initially since it only reproduced when creating an elasticsearch index but the root cause was probably the models being accessed in a different order which makes a lot of sense.

File: activerecord/lib/active_record/associations/builder/belongs_to.rb (hunk 1 above)
Comment (fatkodima) [reply activerecord/lib/active_record/associations/builder/belongs_to.rb:40]: For `<<` we modify the original object, but for `|=` we create a new object with the original contents and the new column and assign to the attribute (original object is intact).
