### PR TITLE
Action Cable owns database connection, not Active Record

### LINKED ISSUE #27547: Postgresql Action Cable connection adapter breaks code-reloading in development
### Steps to reproduce

Initial state:
1. Create a `Widget` model.
1. Create an Action Cable channel which is loaded on the root url.
1. Configure the Postgres adapter for Action Cable in development.

I've created a minimal application with a minimal configuration [here](https://github.com/mcolyer/actioncable-postgres-issue) .

Once the application is running:
1. Load the root url ("/") in a browser.
1. Restart the server and wait for the websocket to re-connect.
1. Edit the `Widget` model file to require code-reloading.
1. Reload the root url in the browser

I've added some debug logging to illustrate how many AR connections are used at a given time as well as the backtraces when they are checked out. 

Based on my investigation so far I'm guessing that the reloading code isn't expecting a long lived database connection (from the postgresql connection adapter) to be running.

### Expected behavior
Code reloading works as it normally does.

### Actual behavior
It hangs (and sometimes deadlocks the process)

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.1

### PR DESCRIPTION
**Pull request by maclover7**
### Summary

Before this commit, the database connection used in Action Cable's
PostgreSQL adapter was "owned" by `ActiveRecord::Base.connection_pool`.
This meant that if, for example, `#clear_reloadable_connections!` was called on the pool, Active
Record would "steal" the database connection from Action Cable, and
would cause all sorts of issues. This became evident during file
reloads; despite Action Cable trying its hardest to return its borrowed
database connection to Active Record via `@pubsub.shutdown`, Active Record calls
`#clear_reloadable_connections!` on the connection pool, and due to the order of callbacks, Active
Record's callback was being executed first. This meant that if you tried
to rerender a view after a file was reloaded, you would have to wait
through Active Record's timeout and such.

Now, Action Cable takes direct ownership of the database connection it
uses. It removes the connection from the pool to avoid the situation
described above. Action Cable also makes sure to call `#disconnect!` on
the connection when appropriate, to match the previous behavior of
Active Record.

Fixes #27547.

r? @matthewd

### CODE REVIEW

File: actioncable/lib/action_cable/subscription_adapter/postgresql.rb [hunk 1]
```diff
@@ -29,15 +29,20 @@ def shutdown
...
-          pg_conn = ar_conn.raw_connection
-
-          unless pg_conn.is_a?(PG::Connection)
-            raise "The Active Record database must be PostgreSQL in order to use the PostgreSQL Action Cable storage adapter"
-          end
+        ar_conn = ActiveRecord::Base.connection_pool.checkout.tap do |conn|
+          # Action Cable is taking ownership over this database connection, and
+          # will perform the necessary cleanup tasks
+          ActiveRecord::Base.connection_pool.remove(conn)
+        end
```
Comment (jeremy) [inline actioncable/lib/action_cable/subscription_adapter/postgresql.rb]: Perhaps we should be managing our own connection pool instead of peeling conns off of another one.

File: actioncable/lib/action_cable/subscription_adapter/postgresql.rb [hunk 2]
```diff
@@ -29,15 +29,20 @@ def shutdown
...
 
-          yield pg_conn
+        pg_conn = ar_conn.raw_connection
+        unless pg_conn.is_a?(PG::Connection)
+          raise "The Active Record database must be PostgreSQL in order to use the PostgreSQL Action Cable storage adapter"
         end
```
Comment (jeremy) [inline actioncable/lib/action_cable/subscription_adapter/postgresql.rb]: Seems late to be checking this. Would expect an error when the subscription adapter is created.

File: actioncable/lib/action_cable/subscription_adapter/postgresql.rb [hunk 3]
```diff
@@ -29,15 +29,20 @@ def shutdown
...
-          end
+        ar_conn = ActiveRecord::Base.connection_pool.checkout.tap do |conn|
+          # Action Cable is taking ownership over this database connection, and
+          # will perform the necessary cleanup tasks
+          ActiveRecord::Base.connection_pool.remove(conn)
+        end
 
-          yield pg_conn
+        pg_conn = ar_conn.raw_connection
+        unless pg_conn.is_a?(PG::Connection)
```
Comment (jeremy) [inline actioncable/lib/action_cable/subscription_adapter/postgresql.rb]: This will break with other PG-backed adapters.

File: actioncable/lib/action_cable/subscription_adapter/postgresql.rb [hunk 4]
```diff
@@ -29,15 +29,20 @@ def shutdown
...
+          raise "The Active Record database must be PostgreSQL in order to use the PostgreSQL Action Cable storage adapter"
         end
+
+        yield pg_conn
+
+        ar_conn.disconnect! if ar_conn.requires_reloading?
```
Comment (jeremy) [inline actioncable/lib/action_cable/subscription_adapter/postgresql.rb]: Do we need this conditional if we know it's a PG adapter?

File: actioncable/test/subscription_adapter/postgresql_test.rb [hunk 5]
```diff
@@ -37,4 +37,27 @@ def teardown
   def cable_config
     { adapter: "postgresql" }
   end
+
+  def test_clear_active_record_connections_adapter_still_works
```
Comment (jeremy) [inline actioncable/test/subscription_adapter/postgresql_test.rb]: Got a name that precisely, concisely indicates what we're testing?

File: actioncable/lib/action_cable/subscription_adapter/postgresql.rb (hunk 1 above)
Comment (matthewd) [inline actioncable/lib/action_cable/subscription_adapter/postgresql.rb]: AR's "connect and give up control" public API feels like a narrower dependency than trying to steal its connection config and connect for ourselves... and forcing the user to duplicate the details just seems unnecessary.

File: actioncable/lib/action_cable/subscription_adapter/postgresql.rb (hunk 3 above)
Comment (matthewd) [inline actioncable/lib/action_cable/subscription_adapter/postgresql.rb]: We're relying on the `pg` gem's notify API, so that's intended.

File: actioncable/lib/action_cable/subscription_adapter/postgresql.rb (hunk 4 above)
Comment (matthewd) [inline actioncable/lib/action_cable/subscription_adapter/postgresql.rb]: We don't need the conditional. We do need the disconnect.

File: actioncable/lib/action_cable/subscription_adapter/postgresql.rb [hunk 6]
```diff
@@ -29,15 +29,20 @@ def shutdown
...
-        ActiveRecord::Base.connection_pool.with_connection do |ar_conn|
-          pg_conn = ar_conn.raw_connection
-
-          unless pg_conn.is_a?(PG::Connection)
-            raise "The Active Record database must be PostgreSQL in order to use the PostgreSQL Action Cable storage adapter"
-          end
+        ar_conn = ActiveRecord::Base.connection_pool.checkout.tap do |conn|
+          # Action Cable is taking ownership over this database connection, and
+          # will perform the necessary cleanup tasks
+          ActiveRecord::Base.connection_pool.remove(conn)
```
Comment (matthewd) [inline actioncable/lib/action_cable/subscription_adapter/postgresql.rb]: We only want to do this for the subscription connection, not broadcasts: those should still use AR's `with_connection`.

.. which may be a wrinkle in the viability of this as a backportable solution. :confused:

File: actioncable/test/subscription_adapter/postgresql_test.rb (hunk 5 above)
Comment (matthewd) [inline actioncable/test/subscription_adapter/postgresql_test.rb]: Does this test even currently fail?

File: actioncable/lib/action_cable/subscription_adapter/postgresql.rb (hunk 2 above)
Comment (matthewd) [inline actioncable/lib/action_cable/subscription_adapter/postgresql.rb]: Even ignoring the difficulty of checking earlier, that would seem pretty defensive to me.

Here, its purpose is more to translate the error you'd get from the block into something immediately obvious -- it's just easier to check the condition first instead of using a rescue.

**Comment by maclover7** [comment]
@jeremy @matthewd updated per comments

**Comment by al2o3cr** [comment]
Will this result in one more connection than the pool size specified in `database.yml` being created? If so, I suspect users in resource-constrained environments (small Heroku PG plans, ferinstance) will want a heads-up in the release notes or something.

File: actioncable/lib/action_cable/subscription_adapter/postgresql.rb [hunk 7]
```diff
@@ -45,6 +50,14 @@ def listener
           @listener || @server.mutex.synchronize { @listener ||= Listener.new(self, @server.event_loop) }
         end
 
+        def verify_and_yield!(pg_conn, &block)
```
Comment (kaspth) [inline actioncable/lib/action_cable/subscription_adapter/postgresql.rb]: Think this handles two separate concerns: verifying and satisfying the surrounding code's usage.

`_and_yield!` also reads like a smell. Ruby code usually doesn't advertise its yieldyness 😊

I think moving yield out to the callers and going with this would be clearer:

```ruby
def verify(conn)
  unless conn.is_a?…
    raise …
  end
end
```

**Comment by mcolyer** [comment]
Just wanted to check in and see if there's anything I can do to help, having this merged in would definitely help me out.

File: actioncable/test/subscription_adapter/postgresql_test.rb (hunk 5 above)
Comment (jeremy) [inline actioncable/test/subscription_adapter/postgresql_test.rb]: @maclover7 ?

Comment (maclover7) [inline actioncable/test/subscription_adapter/postgresql_test.rb]: @jeremy yep, I believe it fails on master.

File: actioncable/lib/action_cable/subscription_adapter/postgresql.rb [hunk 8]
```diff
@@ -28,14 +28,23 @@ def shutdown
...
+          ActiveRecord::Base.connection_pool.remove(conn)
+        end
+        pg_conn = ar_conn.raw_connection
 
-          unless pg_conn.is_a?(PG::Connection)
-            raise "The Active Record database must be PostgreSQL in order to use the PostgreSQL Action Cable storage adapter"
-          end
+        verify!(pg_conn)
+        yield pg_conn
+        ar_conn.disconnect!
```
Comment (arthurnn) [inline actioncable/lib/action_cable/subscription_adapter/postgresql.rb]: should this disconnect be in a `ensure` block?

**Review by arthurnn — COMMENTED** [review]
Left one comment, besides I am OK with this.

**Comment by maclover7** [comment]
Apologies for my delay, updated @arthurnn

**Review by rafaelfranca — APPROVED** [review]

**Comment by mcolyer** [comment]
Any chance that this will be merged?
