### PR TITLE
touch parent model when an attachment is purged

### LINKED ISSUE #39858: Purge on attachment does not touch the parent model
### Steps to reproduce

```
class Post < ApplicationRecord
  has_one_attached :image
end
```

```
@post.image.purge
```

### Expected behavior

`purge` should update the `updated_at` on `@post`.

### Actual behavior

`updated_at` is not `touch`ed.

Thus the `cache` in the views (and  `fresh_when`) don't work properly and include an image that is already deleted...

### System configuration

**Rails version**: 6.0
**Ruby version**: 2.6

### PR DESCRIPTION
**Pull request by victorperez**
### Summary

Currently `delete` is used on the `purge` and `purge_later` methods, that prevent any callbacks to be triggered which causes the parent model to not be updated when an attachment is purged. This behaviour cause issues on some caching strategies as reported here: https://github.com/rails/rails/issues/39858

Changes:

* Add `record&.touch` on `attachment#purge`
* Add `record&.touch` on `attachment#purge_later`
* Remove extra blank line on `attachment.rb`
* Add tests which are failing before this change and pass after the change

### Other Information

`delete` has not been changed to `destroy` to avoid to trigger the `after_destroy_commit :purge_dependent_blob_later`

### CODE REVIEW

File: activestorage/app/models/active_storage/attachment.rb [hunk 1]
```diff
@@ -22,12 +22,14 @@ class ActiveStorage::Attachment < ActiveRecord::Base
   # Synchronously deletes the attachment and {purges the blob}[rdoc-ref:ActiveStorage::Blob#purge].
   def purge
     delete
+    record&.touch
```
Comment (eugeneius) [inline activestorage/app/models/active_storage/attachment.rb:25]: I think delete and touch should be wrapped in a transaction here, as they would have been on Rails 5.2 when the touch happened in an `after_destroy` callback.

```suggestion
    transaction do
      delete
      record&.touch
    end
```

File: activestorage/test/models/attached/many_test.rb [hunk 2]
```diff
@@ -445,12 +445,15 @@ class ActiveStorage::ManyAttachedTest < ActiveSupport::TestCase
       @user.highlights.attach blobs
       assert @user.highlights.attached?
 
+      updated_at_before_purge = @user.updated_at
+
       @user.highlights.purge
```
Comment (eugeneius) [inline activestorage/test/models/attached/many_test.rb:450]: How about using `assert_changes` here?

```suggestion
      assert_changes -> { @user.updated_at } do
        @user.highlights.purge
      end
```

**Review by eugeneius — COMMENTED** [review]
It looks like this touch used to happen in Rails 5.2, but was lost in https://github.com/rails/rails/pull/33303.

Could you add a changelog entry?

File: activestorage/app/models/active_storage/attachment.rb (hunk 1 above)
Comment (victorperez) [reply activestorage/app/models/active_storage/attachment.rb]: @eugeneius  Change done on `purge` and `purge_later`.

File: activestorage/test/models/attached/many_test.rb (hunk 2 above)
Comment (victorperez) [reply activestorage/test/models/attached/many_test.rb]: @eugeneius Changed done on all tests, `assert_changes` looks easier to read 👍

**Comment by victorperez** [comment]
@eugeneius Changelog entry added and requested changes completed.

**Comment by eugeneius** [comment]
Thank you! 🙏
