### PR TITLE
Remove jquery-rails gem from generator if --skip-sprockets is true

### LINKED ISSUE #23431: rails --skip-sprockets option creates many undocumented issues for the unwary
Sprockets integration is systemic starting with Rails 3 and cannot be trivially disabled without introducing other issues.  [The Asset Pipeline](https://github.com/rails/rails/blob/8b2c618cefef1ccd83d270cbacdd19abf4be9b2f/guides/source/asset_pipeline.md#L32) guide makes it appear easy to disable sprockets by using `--skip-sprockets` without any warnings or caveats.

One caveat is that using `--skip-sprockets` leaves `jquery-rails` in the generated Gemfile.  But `jquery-rails` relies on vendor/assets/javascripts in order to work. Most Rails devs would expect that app/assets wouldn't work after disabling the pipeline, but many others I've talked to are surprised that jquery-rails doesn't work because 1) the official rails generator includes it and 2) they may be less familiar with how the asset pipeline functions.

Other caveats:
* some Rails Engines don't work properly, such as [bootstrap-rails-engine](https://github.com/yjchen/bootstrap-rails-engine)
* gems such as [active_scaffold](https://github.com/activescaffold/active_scaffold) and [cells](https://github.com/apotonick/cells) don't work properly
* `remote: true` no longer functions -- this particularly affects constructs using `form_for` and ajax. Notice that the [Working with Javascript in Rails](http://edgeguides.rubyonrails.org/working_with_javascript_in_rails.html) guide does not mention that this feature is dependent on `jquery-ujs` (located in the `jquery-rails` gem, which is broken by disabling the asset pipeline).

Many junior (and even some senior) Rails developers are confused by these issues because it isn't obvious how the asset pipeline is involved and the integration errors arising from these situations can be difficult to diagnose.

There should be some warning about the extended consequences so that Rails developers can make an informed decision about whether to disable the asset pipeline or not.

### PR DESCRIPTION
**Pull request by vipulnsward**
- app generate option --skip-sprockets leaves jquery-rails gem, which relies on sprockets environment
- Remove jquery-rails gem from generator if --skip-sprockets is true

Fixes #23431

### CODE REVIEW

**Comment by vipulnsward** [comment]
I see https://github.com/rails/rails/issues/23431#issuecomment-179291623 now. 
@coldnebo if you'd like to work on it, I can close this.

File: railties/lib/rails/generators/app_base.rb [hunk 1]
```diff
@@ -321,8 +321,11 @@ def javascript_gemfile_entry
           []
         else
           gems = [coffee_gemfile_entry, javascript_runtime_gemfile_entry]
```
Comment (rafaelfranca) [inline railties/lib/rails/generators/app_base.rb]: All this group should not be added. Neither turbolinks will work without sprockets.

Comment (vipulnsward) [inline railties/lib/rails/generators/app_base.rb]: Done.

**Comment by coldnebo** [comment]
@vipulnsward , thanks! I'll focus on the doc and other possible changes this weekend.
