### PR TITLE
[#52698] Fix `TimeZoneConverter#==` method so objects will be properly compared by their type, scale, limit & precision.

### LINKED ISSUE #52698: ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter equality is buggy
### Steps to reproduce

While writing some tests involving the Rails cache (the details aren't really important), I discovered an issue where an instance of `ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter` would fail to compare as equal to a duplicate of itself. In my case, this occurs when serializing a value to the cache then deserializing a fresh instance back and trying to make an assertion about equality, which fails.

The problem is that `TimeZoneConverter` is actually a `DelegateClass`, so it forwards `#==` to the underlying `__getobj__`: https://github.com/ruby/delegate/blob/1c9f9cb37de9c1baa31dad5f67b00f59b765e22a/lib/delegate.rb#L156-L159

The underlying `__getobj__` (in my case, an instance of `ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Timestamp`) will then generally use `ActiveModel::Type::Value#==`, which compares the classes: https://github.com/rails/rails/blob/11f1f35b0a5ce48db7583eb830b3c120af4f1a13/activemodel/lib/active_model/type/value.rb#L121-L127

However, the `self.class` above will just be the underlying `__getobj__.class`, while `other.class` is still going to be the `TimeZoneConverter` wrapper itself. The rest of the values (`precision`, `scale`, `limit`) compare the same via delegation, but the wrapper class gets in the way.

By contrast, `#eql?` (aliased to `#==` in the `Value` class) works because `DelegateClass` swaps the order of args around and winds up incidentally "unwrapping" both sides: https://github.com/ruby/delegate/blob/1c9f9cb37de9c1baa31dad5f67b00f59b765e22a/lib/delegate.rb#L172-L175

So then the only reason a given `TimeZoneConverter` compares as `#==` to itself is because `DelegateClass` short-circuits if the incoming argument is `#equal?`. Duplicating the instance through any means will result in false `==` comparisons.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", "~> 7.1"
  gem "pg"
end

require "active_record"
require "minitest/autorun"

ActiveRecord::Base.establish_connection(adapter: "postgresql", host: "localhost", username: "postgres")

class BugTest < Minitest::Test
  def test_equality
    subtype = ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Timestamp.new
    wrapper = ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter.new(subtype)
    duped = wrapper.dup

    assert_equal wrapper.__getobj__, duped.__getobj__, 'underlying objects should be =='
    assert wrapper.eql?(duped), 'wrapper should be hash-equivalent to duplicate'
    assert_equal wrapper, duped, 'wrapper should be == to duplicate'
  end

  def test_more_realistic_situation
    subtype = ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Timestamp.new
    value = ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter.new(subtype)
    value_from_cache = Marshal.load(Marshal.dump(value)) # writing then reading from cache makes a Marshal round trip
    assert_equal value, value_from_cache
  end
end
```

### Expected behavior

I would expect the duplicated value to be `==` to the original, where "duplication" could happen through a simple `#dup`, a more complex marshalling back & forth, or any number of other scenarios where the object has an equivalent structure.

### Actual behavior

```console
$ ruby /tmp/repro.rb
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Run options: --seed 59380

# Running:

FF

Finished in 0.085907s, 23.2810 runs/s, 46.5620 assertions/s.

  1) Failure:
BugTest#test_more_realistic_situation [/tmp/repro.rb:31]:
No visible difference in the ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter#inspect output.
You should look at the implementation of #== on ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter or its members.
#<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Timestamp:0xXXXXXX @precision=nil, @scale=nil, @limit=nil, @timezone=nil>

  2) Failure:
BugTest#test_equality [/tmp/repro.rb:24]:
wrapper should be == to duplicate.
No visible difference in the ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter#inspect output.
You should look at the implementation of #== on ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter or its members.
#<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Timestamp:0xXXXXXX @precision=nil, @scale=nil, @limit=nil, @timezone=nil>

2 runs, 4 assertions, 2 failures, 0 errors, 0 skips
```

### System configuration

**Rails version**: 7.1

**Ruby version**: 3.3.4

### PR DESCRIPTION
**Pull request by ruyrocha**
### Motivation / Background

This Pull Request has been created because the comparison for `Timestamp` on `TimeZoneConverter` was misbehaving. 

### Detail

This Pull Request changes `TimeZoneConverter#==` so it can correctly check the comparison with `other` objects.

Fixes #52698 

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by MatheusRich** [comment]
@ruyrocha please add a changelog entry for this

**Comment by ruyrocha** [comment]
> @ruyrocha please add a changelog entry for this

Done, @MatheusRich

File: activerecord/lib/active_record/connection_adapters/postgresql/oid/timestamp.rb [hunk 1]
```diff
@@ -8,6 +8,13 @@ class Timestamp < DateTime # :nodoc:
           def type
             real_type_unless_aliased(:timestamp)
           end
+
+          def ==(other)
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/connection_adapters/postgresql/oid/timestamp.rb:12]: Would not this only fix the problem with the postgresql timestamp? I think the problem happens with any type that uses `TimeZoneConverter`, which also includes `DateTime`

**Review by rafaelfranca — COMMENTED** [review]
Thank you for the pull request but I think it is incomplete and probably fixing in the wrong place.

File: activerecord/lib/active_record/connection_adapters/postgresql/oid/timestamp.rb (hunk 1 above)
Comment (ruyrocha) [reply activerecord/lib/active_record/connection_adapters/postgresql/oid/timestamp.rb:12]: Got it, @rafaelfranca 

I'll push a new fix for reviews quite soon

File: activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb [hunk 2]
```diff
@@ -32,6 +32,13 @@ def cast(value)
           end
         end
 
+        def ==(other)
```
Comment (ajvondrak) [inline activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb:35]: @ruyrocha Hey, thanks for the PR! Just got around to taking a look. Perhaps worth noting that this introduces kind of the opposite problem described by #52698.

Before:

```ruby
subtype = ActiveRecord::Type::DateTime.new
value = ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter.new(subtype)
value == "something that doesn't respond to precision/scale/limit/type"
#=> false
```

After:

```ruby
subtype = ActiveRecord::Type::DateTime.new
value = ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter.new(subtype)
value == "something that doesn't respond to precision/scale/limit/type"
#=> NoMethodError: undefined method `precision' for an instance of String
```

I guess there might be arguments about duck typing, but for a method like `#==`, I'd say it's probably a good idea to be resilient to comparing two completely unrelated values. 🤷 The class check of the original method would catch such problems, but in a way that's too strict for the `DelegateClass` usage, which results in false negatives. Maybe an `other.is_a?(ActiveModel::Type::Value)` at the front of this definition would suffice?

Comment (rafaelfranca) [reply activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb:35]: Thanks. Does this fix the issue you were having and the new one?

```
diff --git a/activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb b/activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb
index 27e83ec6dd..26e974d83a 100644
--- a/activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb
+++ b/activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb
@@ -33,10 +33,7 @@ def cast(value)
         end
 
         def ==(other)
-          precision == other.precision &&
-            scale == other.scale &&
-            limit == other.limit &&
-            type == other.type
+          other.is_a?(self.class) && __getobj__ == other.__getobj__
         end
 
         private
diff --git a/activerecord/test/cases/attribute_methods/time_zone_converter_test.rb b/activerecord/test/cases/attribute_methods/time_zone_converter_test.rb
index 5deb026f15..dac23f1ab2 100644
--- a/activerecord/test/cases/attribute_methods/time_zone_converter_test.rb
+++ b/activerecord/test/cases/attribute_methods/time_zone_converter_test.rb
@@ -13,6 +13,7 @@ def test_comparison_with_date_time_type
           value_from_cache = Marshal.load(Marshal.dump(value))
 
           assert_equal value, value_from_cache
+          assert_not_equal value, "foo"
         end
       end
     end
```

Comment (ruyrocha) [reply activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb:35]: It looks good, @rafaelfranca, and I think it'll fix the issues @ajvondrak was facing. I'd only put it first to be consistent with other `#==` methods, e.g:

```ruby
        def ==(other)
          other.is_a?(self.class) && __getobj__ == other.__getobj__ &&
            precision == other.precision &&
            scale == other.scale &&
            limit == other.limit &&
            type == other.type
        end
```

I'm happy to push it if you don't have any objections

Comment (ajvondrak) [reply activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb:35]: Hmm, I suppose `other.is_a?(self.class)` would technically change another piece of behavior from the old version in the case of comparing a timezone-wrapped datetime to just a raw datetime.

Before:

```ruby
unwrapped = ActiveRecord::Type::DateTime.new
wrapped = ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter.new(unwrapped)

# since wrapped.== delegates to the underlying unwrapped.==, this is equivalent to unwrapped == unwrapped:
wrapped == unwrapped
#=> true

# but unwrapped.== doesn't know to unwrap the wrapped value:
unwrapped == wrapped
#=> false
```

After:

```ruby
unwrapped = ActiveRecord::Type::DateTime.new
wrapped = ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter.new(unwrapped)

# now, unwrapped.is_a?(TimeZoneConverter) fails:
wrapped == unwrapped
#=> false

# this is unchanged:
unwrapped == wrapped
#=> false
```

I think the After behavior actually makes more sense, since it keeps `==` symmetric. So yeah, I can't think of any other gotchas offhand with the `is_a?` + `__getobj__ == __getobj__` check. 👍 

@ruyrocha FWIW, I don't think that the precision/scale/limit/type comparisons are necessary with the proposed definition given that we'd be delegating to `__getobj__ == other.__getobj__`, which will already house its own logic for comparing those attributes.

Comment (ruyrocha) [reply activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb:35]: @ajvondrak @rafaelfranca #52726 is ready, but I don't know how to proceed:

- #52698 needs to be open again?
- a separate issue?
