### PR TITLE
[Fix #48925] fix "class_name" required for STI class

### LINKED ISSUE #48925: Make "class_name" option for polymorphic `has_many` relation to STI required
### Steps to reproduce
Models:
```ruby
class Product < ApplicationRecord
  has_many :requests, as: :requestable, dependent: :destroy
end

# STI tables
class Request < ApplicationRecord
  belongs_to :requestable, polymorphic: true

  validate :request_type, presence: true
end

class ProductRequest < Request
  belongs_to :user
end
```
Then running in your console:
```ruby
Product.joins(requests: :user).where(requests: { user: { role: "admin" } })
```
Raises you an error:
```ruby
/Users/some/.rvm/gems/ruby-3.1.1/gems/activerecord-7.0.4/lib/active_record/table_metadata.rb:22:in `has_column?': undefined method `key?' for nil:NilClass (NoMethodError)
```

### Expected behavior
To raise a detailed error, like "provide a `class_name` option to use joins on STI table with polymorphic, or make required option `class_name` for polymorphic relation with STI", like:
```ruby
class Product < ApplicationRecord
  has_many :requests, as: :requestable, class_name: "ProductRequest", dependent: :destroy
end

# STI tables
class Request < ApplicationRecord
  belongs_to :requestable, polymorphic: true

  validate :request_type, presence: true
end

class ProductRequest < Request
  belongs_to :user
end
```

### Actual behavior
Unknown error 🙂 
```ruby
/Users/some/.rvm/gems/ruby-3.1.1/gems/activerecord-7.0.4/lib/active_record/table_metadata.rb:22:in `has_column?': undefined method `key?' for nil:NilClass (NoMethodError)
```

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.1

### PR DESCRIPTION
**Pull request by xfifix**
### Motivation / Background

Fix: #48925
@matthewd

### Detail

This Pull Request add safe navigation operator in the has_column? function

### Checklist

Before submitting the PR make sure the following are checked:

* [ ] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/lib/active_record/table_metadata.rb [hunk 1]
```diff
@@ -19,7 +19,7 @@ def type(column_name)
     end
 
     def has_column?(column_name)
-      klass&.columns_hash.key?(column_name)
+      klass&.columns_hash&.key?(column_name)
```
Comment (byroot) [inline activerecord/lib/active_record/table_metadata.rb:22]:
```suggestion
      klass.columns_hash.key?(column_name) if klass
```

Would perhaps be more readable, but no big deal.
