### PR TITLE
Fix `missing(:association)` and `associated(:association)` for composite primary keys

### LINKED ISSUE #52182: `where.missing(:association)` broken for composite primary keys
### Steps to reproduce
When using CPK missing tries to lookup a single column instead of a column per key generating an invalid query when using missing and having composite primary keys: 

```ruby
# frozen_string_literal: true

require "bundler/inline"
require "pry"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true, primary_key: %i[user_id account_id] do |t|
    t.bigint "user_id", null: false
    t.bigint "account_id", null: false
  end
end

ActiveRecord::Schema.define do
  create_table :comments, force: true, primary_key: %i[post_id account_id] do |t|
    t.bigint "post_id", null: false
    t.bigint "account_id", null: false
  end
end

class Post < ActiveRecord::Base
  has_one :comment, foreign_key: %i[post_id account_id]
end

class Comment < ActiveRecord::Base
  belongs_to :post, foreign_key: %i[post_id account_id]
end

class BugTest < Minitest::Test
  def test_association_stuff
    Post.create!(user_id: 1, account_id: 1)

    assert Post.where.missing(:comment).any?
  end
end
```

### Expected behavior
The records with a missing relation should be returned. 

### Actual behavior
`ActiveRecord::StatementInvalid` is being raised. 

### System configuration
**Rails version**: Rails 8.0.0.alpha

**Ruby version**: ruby 3.3.1

### PR DESCRIPTION
**Pull request by jackozi**
Fixes #52182 

### Detail

Make a hash of the composite primary key so the where clause knows to check for multiple columns, one column per key, instead of a single column with all the key names.

### CODE REVIEW

File: activerecord/lib/active_record/relation/query_methods.rb [hunk 1]
```diff
@@ -124,10 +124,23 @@ def missing(*associations)
...
+          association_primary_key = reflection.association_primary_key
           if reflection.options[:class_name]
-            @scope.where!(association => { reflection.association_primary_key => nil })
+            if association_primary_key.is_a?(Array)
+              association_primary_key.each do |key|
+                @scope.where!(association => { key => nil })
+              end
+            else
+              @scope.where!(association => { reflection.association_primary_key => nil })
+            end
```
Comment (fatkodima) [inline activerecord/lib/active_record/relation/query_methods.rb:135]: I think, you can replace the special handling by something like:
```ruby
association_primary_key = Array(reflection.association_primary_key)

@scope.where!(association => { association_primary_key => [nil] * association_primary_key.size })
```

**Review by fatkodima — COMMENTED** [review]
You also need to fix `where.associated`.

**Comment by jackozi** [comment]
> You also need to fix `where.associated`.

Thanks, I also updated that one.

File: activerecord/lib/active_record/relation/query_methods.rb (hunk 1 above)
Comment (jackozi) [reply activerecord/lib/active_record/relation/query_methods.rb]: This won't work as the array will be checked multiple times instead of checking the individual values each respectively; resulting in a query like: 

```
WHERE "comments"."[""post_id"", ""account_id""]" IS NOT NULL AND "comments"."[""post_id"", ""account_id""]" IS NOT NULL
```

If you have any suggestions on how to overcome that, it would be welcome, as it would clean up this piece quite a bit.

Comment (fatkodima) [reply activerecord/lib/active_record/relation/query_methods.rb]: Try this?
```ruby
association_primary_key = Array(reflection.association_primary_key)

@scope.where!(association => association_primary_key.to_h { |column| [column, nil] })
```

Comment (jackozi) [reply activerecord/lib/active_record/relation/query_methods.rb]: Tweaked that a little and it cleaned up nice, thank you! 

Still not 100% happy with the name `association_primary_key_hash` 🤔

File: activerecord/lib/active_record/relation/query_methods.rb [hunk 2]
```diff
@@ -92,10 +92,11 @@ def associated(*associations)
             @scope.joins!(association)
           end
 
+          association_primary_key_hash = Array(reflection.association_primary_key).index_with { |key| nil }
```
Comment (fatkodima) [inline activerecord/lib/active_record/relation/query_methods.rb:95]:
```suggestion
          association_conditions = Array(reflection.association_primary_key).index_with(nil)
```

**Review by fatkodima — APPROVED** [review]
💪
