### PR TITLE
Make sure `assert_enqueued_with()` & `assert_performed_with()` work reliably with hash arguments

### LINKED ISSUE #33847: assert_enqueued_with can fail even when arguments are equal to expectation
### Steps to reproduce

Run the following test case

```ruby
# test/jobs/kwarg_job_test.rb
require 'test_helper'

class KwargJobTest < ActiveJob::TestCase
  test "job is enqueued" do
    assert_enqueued_with job: KwargJob, args: [{a: 1, b: 1}] do
      KwargJob.perform_later(b: 1, a: 1) # change to a: 1, b: 1 for it to pass
    end
  end
end
```

```ruby
# app/jobs/kwarg_job.rb
class KwargJob < ApplicationJob
  queue_as :default

  def perform(a:, b:)
  end
end
```

### Expected behavior
It should pass. Since `{a: 1, b: 1} == {b: 1, a: 1}` 

### Actual behavior
It fails. `assert_enqueued_with` uses `ActiveJob::Arguments.serialize` before comparing, which inserts a key `_aj_symbol_keys` that is an array about the symbols in the argument. `assert_enqueued_with` ends up using `==` to compare, which is order sensitive when it comes to arrays.

`assert_performed_with` suffers from the same problem, I think.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

### PR DESCRIPTION
**Pull request by sharang-d**
The test helpers now treat `{ a: 1, b: 2 }` and `{ b: 2, a: 1 }` as equals

Fixes #33847

### CODE REVIEW

File: activejob/test/jobs/multiple_kwargs_job.rb [hunk 1]
```diff
@@ -0,0 +1,9 @@
+# frozen_string_literal: true
+
+require_relative "../support/job_buffer"
+
+class MultipleKwargsJob < ActiveJob::Base
+  def perform(argument1:, argument2:)
+    JobBuffer.add("Job with argument1: #{argument1}, argument2: #{argument2}")
```
Comment (sharang-d) [inline activejob/test/jobs/multiple_kwargs_job.rb]: I don't think this line is required but I added it as it was added in other classes. I can remove it if need be.

File: activejob/test/jobs/multiple_kwargs_job.rb [hunk 2]
```diff
@@ -0,0 +1,9 @@
+# frozen_string_literal: true
+
+require_relative "../support/job_buffer"
+
+class MultipleKwargsJob < ActiveJob::Base
```
Comment (sharang-d) [inline activejob/test/jobs/multiple_kwargs_job.rb]: I can modify https://github.com/rails/rails/blob/90982d850eea56a97ff7c3b6dacba61d60729741/activejob/test/jobs/kwargs_job.rb to accept two keyword arguments and not add this new class instead. I'd have to modify one existing test if I do that and I wasn't sure if we do that so I added a new class instead.

File: activejob/test/cases/test_helper_test.rb [hunk 3]
```diff
@@ -555,6 +556,12 @@ def test_assert_enqueued_with_with_no_block_with_at_option
     assert_enqueued_with(job: HelloJob, at: Date.tomorrow.noon)
   end
 
+  def test_assert_enqueued_with_with_hash_arg
```
Comment (sharang-d) [inline activejob/test/cases/test_helper_test.rb]: Please let me know if there's something else I should test instead(or at some other place).

File: activejob/lib/active_job/arguments.rb [hunk 4]
```diff
@@ -77,7 +77,7 @@ def serialize_argument(argument)
           result[WITH_INDIFFERENT_ACCESS_KEY] = serialize_argument(true)
           result
         when Hash
-          symbol_keys = argument.each_key.grep(Symbol).map(&:to_s)
+          symbol_keys = argument.each_key.grep(Symbol).map(&:to_s).sort
```
Comment (rafaelfranca) [inline activejob/lib/active_job/arguments.rb]: This should not need to change to make a test pass. This is making production code slower. I think we should sort on the test side.

**Comment by sharang-d** [comment]
Yes, I thought so too. Was waiting to see what others thought about it.
I'll try to make the change, thanks!

File: activejob/lib/active_job/test_helper.rb [hunk 5]
```diff
@@ -358,7 +358,13 @@ def assert_enqueued_with(job: nil, args: nil, at: nil, queue: nil)
       end
 
       matching_job = jobs.find do |enqueued_job|
-        serialized_args.all? { |key, value| value == enqueued_job[key] }
+        serialized_args.all? do |key, value|
```
Comment (sharang-d) [inline activejob/lib/active_job/test_helper.rb]: @rafaelfranca I've changed the technique to compare the arguments.
I don't really like it. It's too custom IMO.

Can you suggest some way to make this approach better?
Or else, do you think I should deserialize the arguments in `enqueued_job` and compare those with the un-serialized arguments passed to the test helper method? It will be a little bit cleaner that way. However, I am not sure how much of a performance hit it would be to deserialize all arguments for every `enqueued_job` in `jobs`(it might just be ok for tests, I don't know).

File: activejob/test/cases/test_helper_test.rb [hunk 6]
```diff
@@ -555,6 +556,12 @@ def test_assert_enqueued_with_with_no_block_with_at_option
...
+    assert_enqueued_with(job: MultipleKwargsJob, args: [{ argument1: 1, argument2: { a: 1, b: 2 } }]) do
```
Comment (sharang-d) [inline activejob/test/cases/test_helper_test.rb]: I've updated the tests to have nested hashes.

File: activejob/lib/active_job/test_helper.rb (hunk 5 above)
Comment (rafaelfranca) [reply activejob/lib/active_job/test_helper.rb]: I think it is fine to deserialize the arguments and compare them. We want to compare the arguments deserialized anyway.

We want to do:

```ruby
assert_enqueued_with(args: [Model.first])
```

Not `[Model.first.to_global_id]`

Comment (sharang-d) [reply activejob/lib/active_job/test_helper.rb]: I didn't completely understand the code example you posted but I'll go ahead and make the change to compare deserialized arguments and then we can discuss further.

Comment (sharang-d) [reply activejob/lib/active_job/test_helper.rb]: Got it :)

**Comment by sharang-d** [comment]
Hey @rafaelfranca, did you get a chance to review this yet?

**Review by rafaelfranca — COMMENTED** [review]
I like this. Great work! Can you squash your commit?

**Comment by sharang-d** [comment]
@rafaelfranca Thanks! I rebased the branch with master and squashed the commits.
