### PR TITLE
Except keys of `build_record`'s argument from `create_scope` in initi…

### LINKED ISSUE #21893: `collection.build` attributes do not override has_many hash condition attributes
To my surprise, attributes passed to `collection.build` do not override attributes taken from the where condition hash defined in the has_many association. Is this wanted behaviour or is this a bug?

I'd expect `Post.create!.comments.build(flag: false).flag` to be false, if the has_many association was defined as `has_many :comments, -> { where(flag: true) }`

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'rack', github: 'rack/rack'
  gem 'sprockets', github: 'rails/sprockets'
  gem 'sprockets-rails', github: 'rails/sprockets-rails'
  gem 'sass-rails', github: 'rails/sass-rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true  do |t|
  end

  create_table :comments, force: true  do |t|
    t.integer :post_id
    t.boolean :flag, default: false
  end
end

class Post < ActiveRecord::Base
  has_many :comments_with_scope, -> { active }, class_name: 'Comment'
  has_many :comments_with_hash_condition, -> { where(flag: true) }, class_name: 'Comment'
  has_many :comments_with_sql_condition, -> { where('flag is true') }, class_name: 'Comment'
end

class Comment < ActiveRecord::Base
  belongs_to :post

  scope :active, -> { where(flag: true) }
end

class BugTest < Minitest::Test
  def test_with_scope
    assert_equal false, Post.create!.comments_with_scope.build(flag: false).flag
  end

  def test_with_hash_condition
    assert_equal false, Post.create!.comments_with_hash_condition.build(flag: false).flag
  end

  def test_with_sql_condition
    assert_equal false, Post.create!.comments_with_sql_condition.build(flag: false).flag
  end
end
```

### PR DESCRIPTION
**Pull request by yui-knk**
…alize_attributes

If argument of `build_record` has key and value which is same as
default value of database, we should also except the key from
`create_scope` in `initialize_attributes`.
Because at first `build_record` initialize record object with argument
of `build_record`, then assign attributes derived from Association's scope.
In this case `record.changed` does not include the key, which value is
same as default value of database, so we should add the key to except list.

Fix #21893.

### CODE REVIEW

**Comment by yui-knk** [comment]
I am not sure:

* interface of `initialize_attributes`
  Is it better to change second args of `initialize_attributes` to array of strings and remove`attributes.keys.map(&:to_s)` to `build_record`?
* test cases
  I write a minimal test case, are there any test cases we should add too?

**Comment by yui-knk** [comment]
r? @sgrif

because he is a assignee of #21893.

**Comment by sgrif** [comment]
Can we put the huge comment in the commit message rather than a code comment?

File: activerecord/lib/active_record/associations/association.rb [hunk 1]
```diff
@@ -163,9 +163,15 @@ def marshal_load(data)
...
-      def initialize_attributes(record) #:nodoc:
+      def initialize_attributes(record, except_from_scope_attributes = {}) #:nodoc:
         skip_assign = [reflection.foreign_key, reflection.type].compact
-        attributes = create_scope.except(*(record.changed - skip_assign))
+        assigned_keys = record.changed
+        # If argument of +build_record+ has key and value which is same as
+        # default value of database, we should also except the key from
+        # +create_scope+. Because +record+ has been initialized with
+        # argument of +build_record+, the key is not included +record.changed+.
+        assigned_keys += except_from_scope_attributes.keys.map(&:to_s) if except_from_scope_attributes.respond_to?(:keys)
```
Comment (sgrif) [inline activerecord/lib/active_record/associations/association.rb]: Why do we need the `respond_to` check?

File: activerecord/test/cases/associations/has_many_associations_test.rb [hunk 2]
```diff
@@ -206,6 +206,11 @@ def test_create_from_association_should_respect_default_scope
 
     bulb = car.bulbs.create(:name => 'exotic')
     assert_equal 'exotic', bulb.name
+
+    # {frickinawesome: false} is same to default value of
+    # Bulb#frickinawesome.
```
Comment (sgrif) [inline activerecord/test/cases/associations/has_many_associations_test.rb]: I think we can :scissors: this comment. Maybe we can add some code to make sure this test is testing the right thing?

**Comment by yui-knk** [comment]
I wrote same same contents for commit message and code comment, so I can remove code comment in `initialize_attributes` :)

File: activerecord/test/cases/associations/has_many_associations_test.rb (hunk 2 above)
Comment (yui-knk) [inline activerecord/test/cases/associations/has_many_associations_test.rb]: How about to separate to another test method?

**Comment by yui-knk** [comment]
@sgrif updated!

**Comment by pixeltrix** [comment]
I'm not sure it is right to change this behaviour - for example the case given in #21893 is as follows:

``` ruby
class Post < ActiveRecord::Base
  has_many :comments, -> { where(flag: true) }
end
```

``` irb
>> Post.create.comments.build(flag: false).flag
=> true
```

By changing it so that it can be overridden from build you can effectively add an object to the association in memory that wouldn't be there after reload - this is likely to lead to lots of head scratching.

@rafaelfranca @matthewd wdyt?

**Comment by yui-knk** [comment]
@pixeltrix even before this commit, there was [a test case](https://github.com/yui-knk/rails/blob/69f72223e82a4a4f16f16ad7abb36ebfd162a366/activerecord/test/cases/associations/has_many_associations_test.rb#L207) where default scope is overridden by arguments of `build`. I think this commit is not inconsistent with the test case.

**Comment by yui-knk** [comment]
4-1-stable and 4-2-stable has same problem, I feel it is good to backport this.

**Comment by pixeltrix** [comment]
> even before this commit, there was a test case where default scope is overridden by arguments of build. I think this commit is not inconsistent with the test case.

@yui-knk the thing is that default scope is unrelated to association scope, whereas in this case you're creating an object on an association that doesn't actually belong to the association which just seems wrong to me.

**Comment by yui-knk** [comment]
@pixeltrix Sorry.

> you can effectively add an object to the association in memory that wouldn't be there after reload

In your opinion tests in [here](https://github.com/rails/rails/issues/21893#issuecomment-156812325) should be below to respect association? :

```ruby
  def test_flag_true_1_false
    assert_equal true, Post.create!.flag_true_1.build(flag: false).flag
  end

  def test_flag_true_1_nil
    assert_equal true, Post.create!.flag_true_1.build(flag: nil).flag
  end

  def test_flag_true_2_false # NG => true
    assert_equal true, Post.create!.flag_true_2.build(flag: false).flag
  end

  def test_flag_true_2_nil
    assert_equal true, Post.create!.flag_true_2.build(flag: nil).flag
  end

  def test_flag_true_3_false
    assert_equal true, Post.create!.flag_true_3.build(flag: false).flag
  end

  def test_flag_true_3_nil
    assert_equal true, Post.create!.flag_true_3.build(flag: nil).flag
  end
```

**Comment by pixeltrix** [comment]
> In your opinion tests in here should be below to respect association?

In my opinion, yes they should. However I am but one person :smile:

**Comment by sgrif** [comment]
> By changing it so that it can be overridden from build you can effectively add an object to the association in memory that wouldn't be there after reload

I'm not sure I understand your objection. `build` doesn't persist anything.

> 4-1-stable and 4-2-stable has same problem, I feel it is good to backport this.

I'd rather be conservative here. I consider this a bug, but not obviously so. Since the old behavior didn't error, this could potentially change the behavior of working code. I think this is fine for 5.0, but I'd rather not change in a minor.

**Comment by sgrif** [comment]
Ah I think I understand the objection better now. Yeah, you're right it does feel odd to me. I suppose I can see a use case where you're actually wanting to define the inverse, etc. Also worth noting that people do nasty stuff w/ `rewhere` in scopes, though they could just call `build` on that in this case.

I honestly don't feel strongly either way here.
