### PR TITLE
Prevent adding the same record twice on build when using source record in attribute when using has_many_inversing  #40378

### LINKED ISSUE #40378: Prevent from adding the same record on build when using source record in attribute within belongs_to on using has_many_inversing
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile do
  source 'https://rubygems.org'

  ruby '2.6.1'

  gem 'activesupport', path: '../../activesupport/'
  gem 'activemodel', path: '../../activemodel/'
  gem 'activerecord', path: '../'
  gem 'sqlite3'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Base.has_many_inversing = true

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end

  create_table :phone_numbers, force: true do |t|
    t.references :user, null: false
  end
end

class User < ActiveRecord::Base
  has_many :phone_numbers, inverse_of: :user
end

class PhoneNumber < ActiveRecord::Base
  belongs_to :user, inverse_of: :phone_numbers
end

class BugTest < Minitest::Test
  def test_build_with_belongs_to_association_record_in_attribute
    u = User.create
    u.phone_numbers.build(
      user: u
    )
    assert_equal 1, u.phone_numbers.size
    u.save!
    assert_equal 1, u.phone_numbers.size
  end
end

```

### Expected behavior

When using .build on has_many association and passing source (belongs_to) association as attributes, it should store and return only one associated record.

### Actual behavior

It returns 2 records, because `add_to_target` not replaces already existing record, but adds additional one. In result there are two identical records in has_many association.

### System configuration
**Rails version**: 6.1.alpha
**Ruby version**: 2.7

### PR DESCRIPTION
**Pull request by dmitry**
Prevent adding the same record twice on build when using source record in attribute when using has_many_inversing 

Record should be replaced via add_to_target, not added as a separate record to an array.

More details on this issue: #40378

### CODE REVIEW

File: activerecord/lib/active_record/associations/collection_association.rb [hunk 1]
```diff
@@ -105,7 +105,7 @@ def build(attributes = nil, &block)
         if attributes.is_a?(Array)
           attributes.collect { |attr| build(attr, &block) }
         else
-          add_to_target(build_record(attributes, &block))
+          add_to_target(build_record(attributes, &block), replace: true)
```
Comment (gmcgibbon) [inline activerecord/lib/active_record/associations/collection_association.rb:108]: Replace uses `Array#index` which uses `==` to compare, but that seems safe in this context because active record's `==` uses `===` unless an ID is present. There's also no test coverage that disagrees with doing this, so 👍

**Review by gmcgibbon — APPROVED** [review]
Thanks for fixing this!

File: activerecord/lib/active_record/associations/collection_association.rb (hunk 1 above)
Comment (ghiculescu) [reply activerecord/lib/active_record/associations/collection_association.rb:108]: I haven't fully figured it out, but we had a scenario where we override `<=>` (but not `==`) on a model, and this change made calling `.build` for that model really really slow. Any chance `Array#index` calls `<=>`?
