### PR TITLE
Formatter ISO8601 to avoid scientific notation in more cases

### LINKED ISSUE #42344: ActiveSupport::Duration#iso8601 can produce unparsable values
### Steps to reproduce

```ruby
# OK
999_999.seconds.iso8601 # => "PT999999S"
ActiveSupport::Duration.parse("PT999999S") # => 999999 seconds

# Fails
1_000_000.seconds.iso8601 # => "PT1e+06S"
ActiveSupport::Duration.parse("PT1e+06S") # => ActiveSupport::Duration::ISO8601Parser::ParsingError: Invalid ISO 8601 duration: "PT1e+06S"
```

### Expected behavior

Values of one million seconds and above should not be represented in scientific notation.

### Actual behavior

Values of one million seconds and above are represented in scientific notation, and cannot be parsed by `ActiveSupport::Duration.parse`.

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.7.3

### PR DESCRIPTION
**Pull request by HParker**
### Summary

I was unaware until today, but %f and %g return different values for large second durations

```ruby
sprintf("%g", 1_000_000) # => "1e+06"
```

```ruby
sprintf("%0.2f", 1_000_000) # => "1000000.00"
```

for ISO8601 we never want scientific notation

closes: https://github.com/rails/rails/issues/42344

### CODE REVIEW

**Comment by HParker** [comment]
Ah, I misunderstood how `%f` with no prefix works. Let me update this.

File: activesupport/test/time_zone_test.rb [hunk 1]
```diff
@@ -375,6 +375,12 @@ def test_iso8601_with_invalid_value_parseable_by_date__iso8601
     assert_equal "invalid date", exception.message
   end
 
+  def test_iso8601_with_seconds_durations
+    time = 1_000_000.seconds
+    duration = time.iso8601
+    assert_equal time, ActiveSupport::Duration.parse(duration)
+  end
```
Comment (HParker) [inline activesupport/test/time_zone_test.rb:382]: I want to move this test to `core_ext/duraction_test.rb`

**Comment by HParker** [comment]
I wasn't able to find a formatter that would remove unnecessary trailing zeros like `%g`, but doesn't also convert numbers to scientific notation when they are large or small. Instead this defaults to 2 significant digits when converting seconds to iso8601. I think this is a good default with less unexpected behavior then before.

That being said, if someone knows the magic string formatter incantation I would prefer to not often add meaningless trailing fractional seconds.

**Comment by HParker** [comment]
I tried `%.0f` and it doesn't always return what we want. for example:

```ruby
sprintf("%.0f", 8.55) # => "9"
sprintf("%g", 8.55)   # => "8.55"
```

**Comment by SkipKayhil** [comment]
Ack, I guess I was missing something...

I found [something that looks like what we want](https://github.com/rails/rails/blob/58b46e9440f3460e93b8164205614e3ab85784da/activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb#L50) in the `NumberHelper`. 

Maybe the line could be changed to something like:
```ruby
time << "#{format_number(parts[:seconds])}S"

def format_number(number)
  if @precision
    sprintf("%0.0#{@precision}f", number)
  else
    escaped_separator = Regexp.escape(".")
    number.sub(/(#{escaped_separator})(\d*[1-9])?0+\z/, '\1\2').sub(/#{escaped_separator}\z/, "")
end
```

File: activerecord/test/cases/adapters/postgresql/interval_test.rb [hunk 2]
```diff
@@ -58,8 +58,8 @@ def test_interval_type
       legacy_term:  "33 years",
     )
     i = IntervalDataType.last!
-    assert_equal "P6Y5M4DT3H2M1S",     i.maximum_term.iso8601
-    assert_equal "P1Y2M3DT4H5M6.235S", i.minimum_term.iso8601
+    assert_equal "P6Y5M4DT3H2M1.00S",  i.maximum_term.iso8601
+    assert_equal "P1Y2M3DT4H5M6.24S", i.minimum_term.iso8601
```
Comment (marivaldo) [inline activerecord/test/cases/adapters/postgresql/interval_test.rb:62]:
```suggestion
    assert_equal "P1Y2M3DT4H5M6.24S",  i.minimum_term.iso8601
```

**Review by marivaldo — CHANGES_REQUESTED** [review]

File: activerecord/test/cases/adapters/postgresql/interval_test.rb (hunk 2 above)
Comment (HParker) [reply activerecord/test/cases/adapters/postgresql/interval_test.rb]: Thanks for noticing this!

File: activesupport/test/core_ext/duration_test.rb [hunk 3]
```diff
@@ -653,7 +654,7 @@ def test_iso8601_output_precision
   def test_iso8601_output_and_reparsing
     patterns = %w[
       P1Y P0.5Y P0,5Y P1Y1M P1Y0.5M P1Y0,5M P1Y1M1D P1Y1M0.5D P1Y1M0,5D P1Y1M1DT1H P1Y1M1DT0.5H P1Y1M1DT0,5H P1W +P1Y -P1Y P-1Y
-      P1Y1M1DT1H1M P1Y1M1DT1H0.5M P1Y1M1DT1H0,5M P1Y1M1DT1H1M1S P1Y1M1DT1H1M1.0S P1Y1M1DT1H1M1,0S P-1Y-2M3DT-4H-5M-6S
+      P1Y1M1DT1H1M P1Y1M1DT1H0.5M P1Y1M1DT1H0,5M P1Y1M1DT1H1M1S P1Y1M1DT1H1M1.0S P1Y1M1DT1H1M1,0S P-1Y-2M3DT-4H-5M-6S PT1000000.00S
```
Comment (zzak) [inline activesupport/test/core_ext/duration_test.rb:657]: Is the precision 2 on this test, and that's why we get that string?

Is there already a test for `sprintf("%0.0#{@precision}f", seconds)`?

Comment (HParker) [reply activesupport/test/core_ext/duration_test.rb:657]: Ah, thanks! this won't get generated anymore and there are other tests here for different second precisions. I'll remove this change.

**Comment by SkipKayhil** [comment]
> I feel silly. Please tell me if I am not thinking of a case, but I just realized I think I described `to_s` right? 🤦

I think the only thing `to_s` won't do (vs `%g`) is removing excess zeroes. I think? that would still be beneficial to have but I'm not sure

**Comment by HParker** [comment]
> I think the only thing to_s won't do (vs %g) is removing excess zeroes.

I believe it does. for example,
```ruby
irb(main):009:0> sprintf("%g", 1.2) # => "1.2"
irb(main):010:0> sprintf("%.2f", 1.2) # => "1.20"
irb(main):011:0> 1.2.to_s # => "1.2"
```

All the cases I can think of `to_s` on the duration is seconds returns what we want.

I am more happy with this solution compared with defaulting to 2 decimal places. All the duration tests pass without modification and we support a wider variety of durations which is nice win-win.

**Review by skipkayhil — APPROVED** [review]

**Comment by HParker** [comment]
New discover `to_s` on `Float`s will still convert to scientific notation for very large (larger than with `%g`) or small numbers, but integers never change to scientific notation.
```ruby
1_000_000_000_000_000.00.to_s # => "1.0e+15"
0.00001.to_s # => "1.0e-05"
```

Maybe this is an acceptable problem to have? if you are using durations over 1x10^15 (over 300 millennium) or smaller then 1x10^-5 (one millisecond).

**Comment by zzak** [comment]
@HParker Didn't Ruby introduce some core functionality for nanoseconds? 🤔 I have no clue about overflow.. maybe there is `BigTime`? :trollface:

**Comment by HParker** [comment]
Yeah durations less then 1 millisecond seems a little more likely to matter. It is still better then before, but maybe we can do even better? 🤷‍♂️

**Comment by zzak** [comment]
I'm sold this change is enough for this PR. Happy to revisit this later 🙏
