### PR TITLE
Fix renaming primary key index when renaming a PostgreSQL table having uuid primary key

### LINKED ISSUE #49994: Primary key index not renamed when renaming table in Postgres when using UUIDs as pkey
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "pg", "~> 1.1"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Using some utility commands installed by PostgreSQL to setup a test database
dbname = "test_postgres_uuid_rename_table"
system("dropdb --username=postgres --force '#{dbname}'")
system("createdb --username=postgres '#{dbname}'")

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: dbname)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  enable_extension "pgcrypto"
  enable_extension "plpgsql"
end

class PostgresqlUuidPkeyRenameTableTest < Minitest::Test
  def setup
    @connection = ActiveRecord::Base.connection
    @connection.create_table :before_rename, id: :uuid, default: -> { "gen_random_uuid()" }, force: true
  end

  def teardown
    @connection.drop_table "before_rename", if_exists: true
    @connection.drop_table "after_rename", if_exists: true
  end

  def test_renaming_a_table_also_renames_the_primary_key_index
    assert_equal 1, num_indices_named("before_rename_pkey")
    assert_equal 0, num_indices_named("after_rename_pkey")

    @connection.rename_table :before_rename, :after_rename

    assert_equal 0, num_indices_named("before_rename_pkey")
    assert_equal 1, num_indices_named("after_rename_pkey")
  end

  private
    def num_indices_named(name)
      @connection.execute(<<~SQL).values.length
        SELECT 1 FROM "pg_index"
          JOIN "pg_class" ON "pg_index"."indexrelid" = "pg_class"."oid"
          WHERE "pg_class"."relname" = '#{name}'
      SQL
    end
end
```

### Expected behavior

The primary index should change along with the table name, just like it happens for tables that don't make use of UUIDs as their primary key.

See: https://github.com/rails/rails/blob/main/activerecord/test/cases/adapters/postgresql/rename_table_test.rb

### Actual behavior

The index name on the primary key column does not get renamed.

### Related
* https://github.com/rails/rails/issues/12856

### System configuration
**Rails version**: 7.1 (main, see test script)

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #49994.

Rails uses `gen_random_uuid()` function as a default for `uuid` primary key for PostgreSQL, which is not correctly fetched from the pg_catalog.

### CODE REVIEW

File: activerecord/test/cases/adapters/postgresql/rename_table_test.rb [hunk 1]
```diff
@@ -14,6 +13,28 @@ def teardown
...
+
+    assert_changes(-> { num_indices_named("before_rename_pkey") }, from: 1, to: 0) do
+      assert_changes(-> { num_indices_named("after_rename_pkey") }, from: 0, to: 1) do
+        @connection.rename_table :before_rename, :after_rename
+      end
+    end
+  end
+
+  test "renaming a table with uuid primary key and default also renames the primary key index" do
+    @connection.create_table :before_rename, force: true, id: :uuid, default: -> { "gen_random_uuid()" }
```
Comment (jonathanhefner) [inline activerecord/test/cases/adapters/postgresql/rename_table_test.rb:36]: Since `gen_random_uuid` is already the default function for PostgreSQL >= 9.4, this is exercising the same code path as the previous test.  Perhaps both tests should specify a default, one for `uuid_generate_v4` and one for `gen_random_uuid`?

**Comment by fatkodima** [comment]
Implemented suggestions. Please take a look.

**Comment by jonathanhefner** [comment]
Thank you, @fatkodima! :key:
