### PR TITLE
Use algorithm while removing index with db:rollback

### LINKED ISSUE #24190: Rolling back add_index should use the same concurrently algorithm
### Steps to reproduce
- Create and run the following migrations to create a `products` table with an index:

``` ruby
class CreateProducts < ActiveRecord::Migration[5.0]
  def change
    create_table :products do |t|
      t.string :name
    end
  end
end
```

``` ruby
class AddProductNameIndex < ActiveRecord::Migration[5.0]
  disable_ddl_transaction!

  def change
    add_index(:products, :name, algorithm: :concurrently)
  end
end
```
- Run `rake db:migrate` to run the migrations
- Run `rake db:rollback` to undo the index migration
### Expected behavior

Since the migration created the index concurrently, I would expect undoing it to drop the index concurrently i.e. run the following SQL:

``` sql
DROP INDEX CONCURRENTLY "index_products_on_name"
```
### Actual behavior

Currently undoing the migration does not drop the index concurrently i.e. it runs the following SQL:

``` sql
DROP INDEX "index_products_on_name"
```
### System configuration

**Rails version**: 5.0.0.beta3

**Ruby version**: ruby-2.2.2

### PR DESCRIPTION
**Pull request by meinac**
More information can be found in #24190.

Closes #24190

### CODE REVIEW

File: activerecord/lib/active_record/migration/command_recorder.rb [hunk 1]
```diff
@@ -163,8 +163,8 @@ def invert_add_index(args)
         table, columns, options = *args
         options ||= {}
 
-        index_name = options[:name]
-        options_hash = index_name ? { name: index_name } : { column: columns }
+        options_hash = options.slice(:name, :algorithm)
```
[the remark this answers is not in the document]
Comment (kamipo) [reply activerecord/lib/active_record/migration/command_recorder.rb]: I confirmed that `remove_index` handles only `:name` and `:algorithm`.

File: activerecord/lib/active_record/migration/command_recorder.rb [hunk 2]
```diff
@@ -163,8 +163,8 @@ def invert_add_index(args)
...
+        options_hash.merge!(column: columns) if !options_hash[:name]
```
Comment (kamipo) [inline activerecord/lib/active_record/migration/command_recorder.rb]: `.merge!(column: columns)` creates extra new `column: columns` hash.
How about `options_hash[:column] = columns unless options_hash[:name]` or simply one line fix as following?

```diff
--- a/activerecord/lib/active_record/migration/command_recorder.rb
+++ b/activerecord/lib/active_record/migration/command_recorder.rb
@@ -163,6 +163,7 @@ def invert_add_index(args)
 
           index_name = options[:name]
           options_hash = index_name ? { name: index_name } : { column: columns }
+          options_hash[:algorithm] = options[:algorithm] if options[:algorithm]
 
           [:remove_index, [table, options_hash]]
         end
```

Comment (meinac) [reply activerecord/lib/active_record/migration/command_recorder.rb]: Thanks for your comment, I agree using `merge!` was not the best way.
Updated the pr.
