### PR TITLE
Fix stale state for composite foreign keys in belongs_to association

### LINKED ISSUE #50256: Rails 7.1: query_constraints: causes relation to not be loaded.
While trying to use `query_constraints` (awesome feature 🙏 ) I have seen a case where a relation is `nil` on `after_add` callback.

I reduced my application to this reproduction script and to cause `comment.author` to be nil with `query_constraints` we need to have: Default order in `comments` & `after_initialize` that touches the model.

See the script below to better understand my reproduction.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.1.0"
  gem "pg"
end

require "active_record"
require "logger"

ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  database: "test",
  encoding: "unicode",
  host: "localhost",
  port: "5432",
  password: "12345",
  username: "test")

ActiveRecord::Schema.define do
  create_table :comments, force: true do |t|
    t.integer :tenant_id
    t.integer :author_id
    t.string :body
    t.integer :position
  end

  create_table :authors, force: true do |t|
    t.integer :tenant_id
  end
end

class Author < ActiveRecord::Base
  query_constraints :tenant_id, :id

  has_many :comments, -> { order(position: :asc) }, after_add: :on_comment_added

  def on_comment_added(comment)
    puts "added comment: #{comment.author}"
  end
end

class Comment < ActiveRecord::Base
  query_constraints :tenant_id, :id

  belongs_to :author

  after_initialize :calculate_rating, if: :new_record?

  def calculate_rating
    # In our-case since we access `self.author` in `after_initialize` (which always be empty in this case - valid)
    # this will make `comment.author` to be later (in `on_comment_added`) to be blank.
    #
    # In real-world we call this in `after_initialize` and in other callbacks.
    puts "author_id: #{self.author}"
  end
end

author = Author.create!(tenant_id: 1)
author.comments << Comment.create(body: "hello", tenant_id: 1)
```

### Expected behavior

`comment.author` to be accesible in `on_comment_added`, so if we run the reproduce script without `query_constraints`,
we should get this output:
```
author_id: 
added comment: #<Author:0x00000001312f6a48>
```

### Actual behavior

`comment.author` is nil in `on_comment_added`, so we get this output:
```
author_id: 
added comment: 
```

### System configuration
**Rails version**: 7.1
**Ruby version**: `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]`

### LINKED ISSUE #51231: #update on CPK association requires an explicit reload to work correctly
### Steps to reproduce
Save the below script as `ar.rb` and run
```shell
ruby ar.rb
```

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books, force: true, primary_key: %i[number] do |t|
    t.integer :number
    t.string :title
    t.integer :main_chapter_number, null: true
  end

  create_table :chapters, force: true, primary_key: %i[book_number number] do |t|
    t.integer :book_number
    t.integer :number
    t.string :title
  end

  add_foreign_key :books, :chapters, column: [:number, :main_chapter_number], primary_key: [:book_number, :number]
end

class Book < ActiveRecord::Base
  self.primary_key = %i[number]
  has_many :chapters,
           foreign_key: :book_number,
           inverse_of: :book

  belongs_to :main_chapter, class_name: "Chapter",
             query_constraints: %i[number main_chapter_number],
             optional: true,
             inverse_of: :book
end

class Chapter < ActiveRecord::Base
  self.primary_key = %i[book_number number]

  belongs_to :book, foreign_key: :book_number, inverse_of: :chapters
end

class BugTest < Minitest::Test
  def test_association_stuff
    book = Book.create!(number: 1, title: "First book")

    book.chapters << Chapter.new(book:, number: 1, title: "Chapter one") << Chapter.new(book:, number: 2, title: "Chapter two")

    assert_equal 2, book.chapters.count
    assert_equal 2, Chapter.count
    assert_equal nil, book.main_chapter_number

    book.update!(main_chapter: book.chapters.first)
    assert_equal 1, book.main_chapter_number

    # book.reload # This is a workaround that will make it work, but it should not be necessary

    book.update!(main_chapter_number: nil) # This one will not update the database.
    assert_equal nil, book.main_chapter_number
  end
end
```

### Expected behavior
I expect
```
1 runs, 5 assertions, 0 failures, 0 errors, 0 skips
```

### Actual behavior
It fails with
```
Failure:
BugTest#test_association_stuff [ar.rb:72]:
Expected: nil
  Actual: 1
```

See comment in script for workaround

### System configuration
**Rails version**: `main`

**Ruby version**: 3.2.2

**Maybe related issues**: https://github.com/rails/rails/issues/49597

### PR DESCRIPTION
**Pull request by iamradioactive**
### Motivation / Background

Fixes #50256 
Fixes #51231

**Context :** 
- A Model having query constraints and a belongs_to association.
- Associated record is loaded once.

**Action :** 
- Update Foreign key for the belongs_to association.
- Call `model.association` to refer to the associated object.

**Current Behaviour:**
- State is not changed and no reload is triggered.
- Association still points to the old record.

**Updated Behaviour:**
- State is updated and reload is triggered.
- Association points to the updated record.

### Detail

This Pull Request updates `stale_state` method in `belongs_to association` to handle composite foreign keys

### Additional information

For Additional context Please refer to #50256 

### ~Dependency~
- ~This PR has a dependency on #50347 and is to be merged after those changes are approved and merged.~
- ~It is an independent bug, however when the stale state is updated correctly it results in loss of information because of the bug to be fixed in the mentioned PR.~
- ~Please refer to this [comment](https://github.com/rails/rails/pull/50297#issuecomment-1852817664) for additional description.~

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by yosiat** [comment]
@iamradioactive this PR introduces a new bug, which causes nested association to not be saved.. apparently it causes `reset` on the association because of "stale_target"

```
[3600] doing reset stale_state=, stale_state=1,
/Users/yosi/.rvm/gems/ruby-3.2.2/bundler/gems/rails-6d89b876f012/activerecord/lib/active_record/associations/belongs_to_association.rb:45:in `reset'
/Users/yosi/.rvm/gems/ruby-3.2.2/bundler/gems/rails-6d89b876f012/activerecord/lib/active_record/associations/association.rb:72:in `reload'
/Users/yosi/.rvm/gems/ruby-3.2.2/bundler/gems/rails-6d89b876f012/activerecord/lib/active_record/associations/singular_association.rb:11:in `reader'
/Users/yosi/.rvm/gems/ruby-3.2.2/bundler/gems/rails-6d89b876f012/activerecord/lib/active_record/associations/builder/association.rb:104:in `author'
```


Reproduction script:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  # gem "activerecord", "~> 7.1.0"
  gem "rails", github: "iamradioactive/rails", branch: "handle_composite_foreign_keys"
  gem "pg"
end

require "active_record"
require "logger"
require "minitest/autorun"

ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  database: "test",
  encoding: "unicode",
  host: "localhost",
  port: "5432",
  password: "12345",
  username: "test")

ActiveRecord::Schema.define do
  create_table :tenants, force: true do |t|
    t.string :name
  end

  create_table :comments, force: true do |t|
    t.integer :tenant_id
    t.integer :post_id
    t.integer :author_id
    t.string :body
    t.integer :position
  end

  create_table :posts, force: true do |t|
    t.integer :tenant_id
  end

  create_table :author, force: true do |t|
    t.integer :tenant_id
  end
end

class Tenant < ActiveRecord::Base
end

class Post < ActiveRecord::Base
  query_constraints :tenant_id, :id

  has_many :comments
  belongs_to :tenant
end

class Author < ActiveRecord::Base
  query_constraints :tenant_id, :id
  belongs_to :tenant
end

class Comment < ActiveRecord::Base
  query_constraints :tenant_id, :id

  before_save :touch_author

  belongs_to :tenant
  belongs_to :post
  belongs_to :author

  def touch_author
    puts "author: #{self.author}"
  end
end

class BugTest < Minitest::Test
  def test_assoc
    Author.destroy_all
    Post.destroy_all
    Comment.destroy_all
    Tenant.destroy_all

    tenant = Tenant.create!

    post = Post.create!(tenant: tenant)
    post.comments << Comment.new(body: "hello", tenant: tenant, author: Author.new(tenant: tenant))
    post.save!

    assert_equal 1, Post.count, "single post"
    assert_equal 1, Comment.count, "2 comments"
    assert_equal 1, Author.count, "1 author"
  end
end
```

This test passes on rails 7.1, but not on your branch.

**Comment by iamradioactive** [comment]
@yosiat , Interestingly, It seems to be another bug uncovered by these changes. Thank you for testing it out. I have updated the PR.

On Rails 7.1 stable, if you verify the value of `tenant_id` before calling save.

**With Query Constraints**
 - comment.tenant id is `nil`.
 - comment.tenant points to tenant with id 1.

**Without Query Constraints**
 - comment.tenant id is 1
 - comment.tenant points to tenant with id 1.

Since, Stale state is not working correctly on main branch as of now, reload is not getting triggered when the tenant id changes and there is no loss of unsaved associations. After this update, `stale_state` method started to detect changes and state was reset as soon as the `tenant_id` is changed.

**Comment by nvasilevski** [comment]
If we are pivoting the fix from `stale_state` towards properly deriving the foreign key, could we change the PR title & description?

**Comment by yosiat** [comment]
Hi @iamradioactive 

I am bit confused, what this PR is going to fix? there were two issues:
- Original one: accessing the `comment.author` and it's not loaded
- The nested save

I saw this comment about inversing (https://github.com/rails/rails/issues/50256#issuecomment-1851087930) which issue does it the address? the first one?

**Comment by iamradioactive** [comment]
@nvasilevski , @yosiat 

These are two independent and valid bugs. I'm gonna open a separate PR to derive the foreign key using the [commit](https://github.com/rails/rails/pull/50297/commits/0192b35e3bd711e32bab1b0a2bbddbcdd3975e76) and mark the new PR as a dependency for this one.

There are two bugs to be fixed 

- State state for composite foreign keys. (Original one)
- Derived/Inferred foreign key for models with Query constraints. (Nested save)

I will update the PRs and drop a comment here.

**Comment by iamradioactive** [comment]
I have updated the PR, this one contains only the changes related to the fix for `stale_state`. However it has a dependency on #50347 and is to be merged once those changes are approved and merged.

cc: @nvasilevski  @yosiat

**Comment by jarl-dk** [comment]
Can someone please rebase this branch as the branch suffers from https://github.com/rails/rails/issues/49597 and I think it makes noise in the verification/fix for this bug.

**Comment by iamradioactive** [comment]
> Can someone please rebase this branch as the branch suffers from #49597 and I think it makes noise in the verification/fix for this bug.

@jarl-dk , I have rebased the branch with latest code from main.

**Comment by iamradioactive** [comment]
@nvasilevski , Can you please review this again? The dependency #50347 is merged now

File: activerecord/lib/active_record/associations/belongs_to_association.rb [hunk 1]
```diff
@@ -148,8 +148,11 @@ def invertible_for?(record)
         end
 
         def stale_state
-          result = owner._read_attribute(reflection.foreign_key) { |n| owner.send(:missing_attribute, n, caller) }
-          result && result.to_s
+          result = Array(reflection.foreign_key).map do |fk|
+            owner._read_attribute(fk) { |n| owner.send(:missing_attribute, n, caller) }
+          end.join(",")
```
Comment (nvasilevski) [inline activerecord/lib/active_record/associations/belongs_to_association.rb:153]: Do we need to turn it into a string? I think the return value can be an array as all we need is to compare the values so returning an Array should just work 

```suggestion
          end
```

Comment (iamradioactive) [reply activerecord/lib/active_record/associations/belongs_to_association.rb:153]: @nvasilevski , I tried doing that already. There was a test case failing related to`rails_6_1_associations cache`. What it seems to be doing is ensuring compatibility between Marshal formats. My thought was that we would want to preserve the behaviour unless there are strong reasons not to do so.

Reference: https://buildkite.com/rails/rails/builds/102586#018c4591-20a3-4654-883f-31b465b76125/1095-1105

Comment (nvasilevski) [reply activerecord/lib/active_record/associations/belongs_to_association.rb:153]: Ah, ok, thanks for clarifying. Since `stale_state` should be internal it's okay to go with a string

**Comment by jarl-dk** [comment]
Seems like a fix has been provided a long time ago. Is this soon to be fixed/closed?

**Comment by jarl-dk** [comment]
Maybe related:
https://github.com/rails/rails/issues/54881
https://github.com/rails/rails/issues/54882

**Comment by jarl-dk** [comment]
@iamradioactive What is preventing you from merging this?

**Comment by jarl-dk** [comment]
@nvasilevski, Can you please take a look at this?

**Review by nvasilevski — APPROVED** [review]
Thanks! The fix does look correct. `foreign_key` can be an array (composite) so `owner._read_attribute(reflection.foreign_key)` definitely needed to be changed

**Comment by jarl-dk** [comment]
@iamradioactive : I believe you can merge now.
