### PR TITLE
Resolve conflict between counter cache and optimistic locking

### LINKED ISSUE #16449: Counter cache does not work well with optimistic locking
Counter cache and optimistic locking don't play well together. The example below illustrated the problem:

``` ruby
require 'active_record'
require 'minitest/autorun'
require 'sqlite3'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection 'sqlite3::memory:'

ActiveRecord::Schema.define do
  create_table :people do |t|
    t.string :name
    t.integer :lock_version, null: false, default: 0
    t.integer :vehicles_count, null: false, default: 0
    t.integer :jobs_count, null: false, default: 0
    t.timestamps
  end

  create_table :jobs do |t|
    t.belongs_to :person
  end

  create_table :vehicles do |t|
    t.belongs_to :owner, polymorphic: true
  end
end

class Person < ActiveRecord::Base
  has_many :jobs,                 dependent: :destroy, counter_cache: true
  has_many :vehicles, as: :owner, dependent: :destroy, counter_cache: true
end

class Job < ActiveRecord::Base
  belongs_to :person, counter_cache: true
end

class Vehicle < ActiveRecord::Base
  belongs_to :owner, polymorphic: true, counter_cache: true
end

class BugTest < Minitest::Test
  def test_locking_simple_non_polymorphic
    person = Person.create!
    person.jobs << Job.create!

    # Fails on the next expression. jobs#<< updates the lock_version in the
    # database, but not in the loaded object. Raises StaleObjectError.

    person.destroy
  end

  def test_locking_simple_polymorphic
    person = Person.create!
    person.vehicles << Vehicle.create!

    # Should fail on the next expression if counter_cache worked for
    # polymorphic relationships. It doesn't at the time of writing so the
    # test passes. Fails on top of #16445

    person.destroy
  end
end
```

Note that one of the tests passes, because counter cache does not work on polymorphic associations. If that is fixed (#16445), both tests will fail.

As far as I can tell, the expected behaviour is for counter cache to bump the `lock_version`. It does so in the database, but in some situations it fails to update it in the loaded object. I've created a [gist with test cases](https://gist.github.com/skanev/f442394e81463588e9d6) that tests this behaviour in detail. All of the tests currently fail.

One way to get the tests in the gist to pass is to add `touch: true` to both `belongs_to` relationships (after applying #16445 and #16448, which fix some bugs). `touch: true` seems to do a good job of updating `lock_version` in the loaded model when necessary.

I see three possible ways to resolve this issue:
1. **Don't bump `lock_version` for `counter_cache`**. This makes some sense to me – the version is not bumped if there is no `counter_cache` and I don't see why adding a cache should change this. The user can always intentionally get it by passing `touch: true`.
2. **Have the counter cache do what `touch: true` does**. I gave this a shot, but couldn't get it to work in all cases. It might introduce some duplication between `counter_cache` and `touch`. It makes the `counter_cache` code very aware of (and non-orthogonal to) the optimistic locking code.
3. **Always set `touch: true` in the association when there is a counter cache**. It's a cheap solution :smile: . Not sure how it can be implemented, but it's seems to be the simplest thing that will (1) preserve the behaviour and (2) fix the issue. Also – no duplication.

There might be other possibilities that I haven't thought of.

My personal favourite is the first one. It gives the user the most options and it doesn't require changing the `counter_cache` too much. Not changing the `lock_version` behaviour also makes sense to me. However, I understand it might not be the desired solution.

Thoughts?

/cc @senny

P.S.: Whichever of the three (or more) options makes the most sense, I'd love to try implementing it :smile:

### PR DESCRIPTION
**Pull request by alipman88**
### Summary

Bump an ActiveRecord instance's lock version after updating its counter cache. This avoids raising an unnecessary `ActiveRecord::StaleObjectError` upon subsequent transactions by maintaining parity with the corresponding database record's `lock_version` column. Fixes #16449.

### CODE REVIEW

**Comment by kaspth** [comment]
This seems conceptually ok to me. But I'd like @kamipo to have a look as well.

File: activerecord/lib/active_record/associations/belongs_to_association.rb [hunk 1]
```diff
@@ -76,7 +76,9 @@ def replace(record)
         def update_counters(by)
           if require_counter_update? && foreign_key_present?
             if target && !stale_target?
-              target.increment!(reflection.counter_cache_column, by, touch: reflection.options[:touch])
+              target.increment!(reflection.counter_cache_column, by, touch: reflection.options[:touch]) &&
+                (target[target.class.locking_column] += 1 if target.locking_enabled?)
```
Comment (eugeneius) [inline activerecord/lib/active_record/associations/belongs_to_association.rb:80]: This will leave the record dirty, i.e. `lock_version_changed?` will return true, and saving it will write to the database again. That could be solved with `clear_attribute_change`, but it seems like the root of the problem is actually the `increment!` method, since it's reproducible by using it directly:

```ruby
car = Car.create!
car.increment!(:wheels_count)
car.update!(name: "herbie")
```

Comment (kamipo) [reply activerecord/lib/active_record/associations/belongs_to_association.rb:80]: Yeah, it should be solved in `increment!`.

Comment (alipman88) [reply activerecord/lib/active_record/associations/belongs_to_association.rb]: Thank you @eugeneius and @kamipo. I've moved the patch to `ActiveRecord::Persistence#increment!` and called `clear_attribute_change` after modifying an instance's lock version. (Also added an assertion that lock_version doesn't change.)

File: activerecord/lib/active_record/persistence.rb [hunk 2]
```diff
@@ -709,6 +709,12 @@ def increment!(attribute, by = 1, touch: nil)
       increment(attribute, by)
       change = public_send(attribute) - (attribute_in_database(attribute.to_s) || 0)
       self.class.update_counters(id, attribute => change, touch: touch)
+
+      if locking_enabled?
+        self[self.class.locking_column] += 1
+        clear_attribute_change(self.class.locking_column)
+      end
```
Comment (jonathanhefner) [inline activerecord/lib/active_record/persistence.rb:716]: Since `Persistence` shouldn't necessarily be concerned with locking, what about moving this to a `Locking::Optimistic#increment!` override?  Something similar to [`_create_record`](https://github.com/rails/rails/blob/c360644ed90a350d75b1722837ec306b38268ab5/activerecord/lib/active_record/locking/optimistic.rb#L64-L71).

Comment (alipman88) [reply activerecord/lib/active_record/persistence.rb]: @jonathanhefner - that's even better, I've rebased accordingly.

(Congrats on joining the Rails team, btw!)

File: activerecord/lib/active_record/locking/optimistic.rb [hunk 3]
```diff
@@ -60,6 +60,17 @@ def locking_enabled? #:nodoc:
...
+      def increment!(attribute, by = 1, touch: nil) #:nodoc:
+        super
+
+        if locking_enabled?
+          self[self.class.locking_column] += 1
+          clear_attribute_change(self.class.locking_column)
+        end
+
+        self
+      end
```
Comment (eugeneius) [inline activerecord/lib/active_record/locking/optimistic.rb:72]: I'd prefer to avoid duplicating the method signature and return value:

```suggestion
      def increment!(*, **) #:nodoc:
        super.tap do
          if locking_enabled?
            self[self.class.locking_column] += 1
            clear_attribute_change(self.class.locking_column)
          end
        end
      end
```

File: activerecord/CHANGELOG.md [hunk 4]
```diff
@@ -1,3 +1,14 @@
+*   Resolve conflict between counter cache and optimistic locking.
+
+    Bump an ActiveRecord instance's lock version after updating its counter
```
Comment (eugeneius) [inline activerecord/CHANGELOG.md:3]:
```suggestion
    Bump an Active Record instance's lock version after updating its counter
```

File: activerecord/lib/active_record/locking/optimistic.rb (hunk 3 above)
Comment (alipman88) [reply activerecord/lib/active_record/locking/optimistic.rb]: Thanks, rebased accordingly. (I was unfamiliar with that pattern, that's very handy.)

File: activerecord/CHANGELOG.md (hunk 4 above)
Comment (alipman88) [reply activerecord/CHANGELOG.md]: Whoops, fixed. (Updated commit message as well.)

**Comment by eugeneius** [comment]
Thanks @alipman88! 🙌 

Backported to 6-0-stable in https://github.com/rails/rails/commit/9366f528b2d7fc18e4836b670fddcc75ea450333.
