### PR TITLE
Move advisory lock to it's own connection

### LINKED ISSUE #37748: Multiple databases and migrations using models problem
### Description
- Given multiple databases are configured according to https://guides.rubyonrails.org/active_record_multiple_databases.html#setting-up-your-application, i.e.
    - a primary and a replica databases are defined in database.yml
    - connections to both databases are established in `ApplicationRecord` using `connects_to database: { writing: :primary, primary_replica: :primary }`

- When a migration is using a model class inheriting from `ApplicationRecord`
- Then executing such migration will raise `ActiveRecord::StatementInvalid: PG::ConnectionBad: connection is closed`

### Steps to reproduce

- clone https://github.com/tomgi/rails-multi-db-migration-problem
- run the following commands to install gems and create the database
```bash
docker-compose build
docker-compose run --rm bundle install
docker-compose run --rm app rails db:create
```
- migrate the database with
```bash
docker-compose run --rm app rails db:migrate
```

### Expected behavior

`rails db:migrate` executes all migrations and doesn't raise any errors

### Actual behavior

Executing the migration raises the following error
```
rails aborted!
ActiveRecord::StatementInvalid: PG::ConnectionBad: connection is closed
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `async_exec'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `block (2 levels) in query'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `block in query'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:718:in `block (2 levels) in log'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:717:in `block in log'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:708:in `log'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `query'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:98:in `query_value'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:383:in `release_advisory_lock'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1384:in `with_advisory_lock'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1229:in `migrate'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1061:in `up'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1036:in `migrate'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:85:in `block (3 levels) in <main>'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:83:in `each'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:83:in `block (2 levels) in <main>'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/bundle/vendor/gems/railties-6.0.1/lib/rails/command.rb:48:in `invoke'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands.rb:18:in `<main>'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
/app/bin/rails:9:in `<top (required)>'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/bundle/vendor/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/bundle/vendor/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/bundle/vendor/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
PG::ConnectionBad: connection is closed
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `async_exec'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `block (2 levels) in query'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `block in query'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:718:in `block (2 levels) in log'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:717:in `block in log'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:708:in `log'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `query'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:98:in `query_value'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:383:in `release_advisory_lock'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1384:in `with_advisory_lock'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1229:in `migrate'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1061:in `up'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/migration.rb:1036:in `migrate'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:85:in `block (3 levels) in <main>'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:83:in `each'
/bundle/vendor/gems/activerecord-6.0.1/lib/active_record/railties/databases.rake:83:in `block (2 levels) in <main>'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/bundle/vendor/gems/railties-6.0.1/lib/rails/command.rb:48:in `invoke'
/bundle/vendor/gems/railties-6.0.1/lib/rails/commands.rb:18:in `<main>'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/bundle/vendor/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/bundle/vendor/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
/app/bin/rails:9:in `<top (required)>'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/bundle/vendor/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/bundle/vendor/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/bundle/vendor/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/bundle/vendor/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

### System configuration
**Rails version**:
6.0.1

**Ruby version**:
2.6.3

### PR DESCRIPTION
**Pull request by eileencodes**
This PR moves advisory lock to it's own connection instead of
`ActiveRecord::Base` to fix #37748. As a note the issue is present on
both mysql and postgres. We don't see it on sqlite3 because sqlite3
doesn't support advisory locks.

The underlying problem only appears if:

1) the app is using multiple databases, and therefore establishing a new
connection in the abstract models
2) the app has a migration that loads a model (ex `Post.update_all`)
which causes that new connection to get established.

This is because when Rails runs migrations the default connections are
established, the lock is taken out on the `ActiveRecord::Base`
connection. When the migration that calls a model is loaded, a new
connection will be established and the lock will automatically be
released.

When Rails goes to release the lock in the ensure block it will find
that the connection has been closed. Even if the connection wasn't
closed the lock would no longer exist on that connection.

We originally considered checking if the connection was active, but
ultimately that would hide that the advisory locks weren't working
correctly because there'd be no lock to release.

We also considered making the lock more granular - that it only blocked
on each migration individually instead of all the migrations for that
connection. This might be the right move going forward, but right now
multi-db migrations that load models are very broken in Rails 6.0 and
master.

John and I don't love this fix, it requires a bit too much knowledge of
internals and how Rails picks up connections. However, it does fix the
issue, makes the lock more global, and makes the lock more resilient to
changing connections.

Co-authored-by: John Crepezzi <john.crepezzi@gmail.com>

cc/ @rafaelfranca @tenderlove @jhawthorn @matthewd @seejohnrun

### CODE REVIEW

File: activerecord/lib/active_record/migration.rb [hunk 1]
```diff
@@ -1374,9 +1374,14 @@ def use_advisory_lock?
         Base.connection.advisory_locks_enabled?
       end
 
+      AdvisoryLockBase = Class.new(ActiveRecord::Base) do
+        self.connection_specification_name = "AdvisoryLockBase"
+      end
```
Comment (jhawthorn) [inline activerecord/lib/active_record/migration.rb]: For `SchemaMigration` and `InternalMetadata` we do

``` ruby
def self._internal?
  true
end
```

Feels like we should do the same here

Comment (jhawthorn) [reply activerecord/lib/active_record/migration.rb]: Also maybe this should be `self.abstract_class = true`?

**Comment by eileencodes** [comment]
Ok I moved the AdvisoryLockBase into its own class, added `_internal`, and `abstract_class`. This fixed the test failures in Railties due to framework loading.

**Comment by matthewd** [comment]
My grasp of the connection model is slipping (I guess I don't understand how ApplicationRecord's connection-twiddling would affect a connection belonging to its superclass).. but does this literally create an additional TCP connection to the database server? If so, that seems Rather Undesirable.. a database in maintenance mode might only allow a single connection (or a single connection from a maintainer-level user).

IIRC there was a specific reason it was important for the lock to wrap the full set of migrations, but I don't recall what it was -- we might have to find the corresponding PR to check that.

**Comment by eileencodes** [comment]
> My grasp of the connection model is slipping (I guess I don't understand how ApplicationRecord's connection-twiddling would affect a connection belonging to its superclass)

A default connection is opened by https://github.com/rails/rails/blob/master/activerecord/lib/active_record/railtie.rb#L204 on `ActiveRecord::Base`. Then the advisory lock code takes out a lock https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration.rb#L1379. In multi-db we need a `connects_to` in order to connect the replicas in `ApplicationRecord`. When a migration runs that calls a model like `Post` it will load `ApplicationRecord` and call `connects_to`. `connects_to` eventually calls to `establish_connection` in https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L1042. `establish_connection` will look up the pool by the connection_specification_name. It will find that and remove it here https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L1049

Once it's removed it establishes a new connection, which means that we cannot hold onto the lock. Even worse, the way migrations work we need a lock for each connection so if the lock was meant to be global, even if it wasn't throwing an exception due to a closed connection, we're still not protecting all migrations from a concurrent migration.

> but does this literally create an additional TCP connection to the database server

Yea it does, and I don't see any other way around this. I'm open to other ideas but everything we explored was not possible. 

At the moment the only fix for this is saying we do not support advisory locks for multiple databases. We have no way of knowing if an app is multi-db so we can't even check for that and warn the user.

**Comment by eileencodes** [comment]
@matthewd do you have any ideas how we can fix the problem? We either need a more global lock (that protects all migrations regardless of connection) or a more granular lock (only protects the current running migration).

**Comment by matthewd** [comment]
> I don't understand how ApplicationRecord's connection-twiddling would affect a connection belonging to its superclass

Okay, it turns out my confusion is because that behaviour's special-cased here: https://github.com/rails/rails/blob/2c07d162b392f693ddbba020cad8b23b8b30eb2e/activerecord/lib/active_record/connection_handling.rb#L188

Given that we're re-configuring the same-named connection, I wonder if we could/should recognise that the new connection config matches the already-active one, and therefore we don't need to dis/reconnect at all?

Otherwise I don't think I can suggest anything that wouldn't involve some sort of change in connection management, so if that's off the table, I guess it's just a matter of choosing the less-bad trade-off (which I agree is this PR -- we have to support multi-DB migrations), and apologising to any future reader who's here because migrations started taking two connections. 🤷🏻‍♂️

**Comment by eileencodes** [comment]
> Given that we're re-configuring the same-named connection, I wonder if we could/should recognise that the new connection config matches the already-active one, and therefore we don't need to dis/reconnect at all?

So don't remove the connection if it already exists? I did wonder why we do that in the first place. I think it's because you should establish a new connection with a different config but the same name. Eventually maybe that shouldn't be possible. Now that we're using objects everywhere it might be a lot easier for us to inspect the connection db config and figure out if it is the same and if it is the same don't remove it.

I think that's a little more involved and probably an improvement for 6.1. I'm thinking we should merge this for 6.0 and 6.1 because migrations are effectively broken and then work on not removing the connection in 6.1 and undoing this change if we're successful. Does that sound like a fair compromise? I'll add a CHANGELOG as well.

**Comment by trammel** [comment]
This fix got merged to master, did it also make it in to the 6.0.2.2 branch/release?

**Comment by eileencodes** [comment]
> did it also make it in to the 6.0.2.2 branch/release?

No, 6.0.2.2 was only security and 6.0.2.1 was also only security. This will make it into the 6.0.3 release.
