### PR TITLE
Fix autosave validation context regression

### LINKED ISSUE #37192: Validations failing to fire on non-dirty belongs_to associations when a custom context is used
Since https://github.com/rails/rails/pull/36671 was introduced, validations are no longer fired on non-dirty dependent association records, even when a custom validation context is used.

Skipping the associations validations when it hasn't been marked as dirty is undesirable is that it breaks the ability to vary validations based on contexts. This test fails where previously it would have passed: 

```ruby
  def test_belongs_to_validations_fire_based_on_validation_context
    old_validators = Mouse._validators.deep_dup
    old_callbacks = Mouse._validate_callbacks.deep_dup
    Mouse.clear_validators!
    Mouse.validates :name, presence: true, on: :rename

    mouse = Mouse.create!
    squeak = Squeak.create!(mouse: mouse)
    assert_equal true, squeak.valid?
    assert_equal false, squeak.valid?(:rename) # this now fails
  ensure
    Mouse._validators = old_validators
    Mouse._validate_callbacks = old_callbacks
  end
```

Other related issues: https://github.com/rails/rails/issues/36822 and https://github.com/rails/rails/pull/36828.

### PR DESCRIPTION
**Pull request by tekin**
This fixes a regression introduced by #36671 by ensuring autosaved associations always perform validations when a custom validation context is being used.

Prior to #36671, validations on a dependent singular association would always fire, regardless of whether the associated record was `changed_for_autosave?` or not. That change brought the autosave behaviour for both singular and collection associations inline such that dependent associations would only be validated/saved if they needed to be, according to `changed_for_autosave?`. The problem this highlighted/introduced is that the use of custom validation contexts became a bit broken in that the validations on the associated records now only fire if the associated records had actual changes on them, ignoring the fact that a custom context is a strong indicator that the context might be different to when the record was last save, and therefor their validity should be reconsidered.

This PR reinstates the previous behaviour for singular associations, but also updates the behaviour for collection associations so that they both behave consistently: if a custom validation context is used, the validations will always fire on the association records.

The first commit updates an existing regression test that became a false-positive when #36671 was merged.

Resolves #37192 and #36822.

### CODE REVIEW

File: activerecord/lib/active_record/autosave_association.rb [hunk 1]
```diff
@@ -302,7 +302,7 @@ def nested_records_changed_for_autosave?
       def validate_single_association(reflection)
```
Comment (gklsan) [inline activerecord/lib/active_record/autosave_association.rb]:
```suggestion
      def validate_single_association(reflection)
           record = association_instance_get(reflection.name)&.reader
           association_valid?(reflection, record) if record&.changed_for_autosave? || custom_validation_context?
        end
```

Comment (tekin) [reply activerecord/lib/active_record/autosave_association.rb]: @gklsan I'm not sure I follow your suggestion here

**Comment by tekin** [comment]
Does anyone have any thoughts on this? @kamipo?

**Comment by kamipo** [comment]
Can you squash your commits into one?

**Comment by tekin** [comment]
I can but I just want to double check that’s definitely what you want as I think we’d lose something in the history’s focus. The first commit isn’t directly related to the custom context regression. The first commit rewrites an unrelated spec that became a potential false-positive when #36671 was merged. The second commit fixes the actual custom context regression.

**Comment by kamipo** [comment]
Personally I'd not think there is worth for the first commit, but if you want to make that in this PR, please squash into one in this PR.

**Comment by tekin** [comment]
OK, I've squashed the commits. 

Just to be clear, the change to the test is genuinely removing a potential false positive. The test was originally written to protect against this bug: #14106. But because validations no longer fire on non-dirty singular associations, the original test would have passed, even if the code introduced by #14924 to prevent `:update` and `:create` contexts being passed on to association validations was removed.

**Comment by tekin** [comment]
Thanks @kamipo! Will this be back-ported to 6-0-stable and 5-2-stable?

**Comment by kamipo** [comment]
Yes, backported.

**Comment by RKushnir** [comment]
Unfortunately, I think this doesn't fully resolve the bug that has been introduced. You may not be using a custom validation context, but the associated object's validations may depend on the current object's state. Thus, even though the associated object itself stays unchanged, the validation logic may become different.

```ruby
class User
  has_many :orders
  validate :billing_address_must_be_present

  def billing_address_must_be_present
    if orders.where(state: "confirmed").any? && billing_address.blank?
      errors.add :billing_address, :blank
    end
  end
end

class Order
  belongs_to :user
  validates_associated :user
  accepts_nested_attributes_for :user
end

user = User.create!(billing_address: nil)
order = user.orders.create!(state: "pending")
order.state = "confirmed"
order.save # => true
order.valid? # => false

# rails 5.2.3
order.errors.messages # => {:user=>["is invalid"], :"user.billing_address"=>["can't be blank"]}

# rails 5.2.4
order.errors.messages # => {:user=>["is invalid"]}
```

**Comment by kamipo** [comment]
@RKushnir I agree that #36671 is a breaking change. Can you create an issue which is affected by a breaking change with executable script (https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)?
