### PR TITLE
Eagerly validate pool arguments in Redis and MemCache stores

### LINKED ISSUE #48352: Type Conversion of Environment Variables in Redis Cache Configuration
In my project, I am using Redis as a cache store.   
I have configured it to retrieve the settings from environment variables.   
However, I have encountered the following issue.

I have come here through [Rails Discussion](https://discuss.rubyonrails.org/t/type-conversion-of-environment-variables-in-redis-cache-configuration/82923).

### Steps to reproduce

```ruby
# config/environments/development.rb
config.cache_store = :redis_cache_store, {
  url: ENV.fetch('CACHE_REDIS_URL'),
  pool_size: ENV.fetch('CACHE_REDIS_POOL_SIZE', 5),
  :
}
```

IRB

```ruby
[1] pry(main)> Rails.cache.write("/foo", "bar")
```

### Expected behavior

The string value is specified as it is, but an error occurs during cache writing.  
 Therefore, when I discovered this issue, I initially thought that an error should occur during the startup of Rails.   
However, after discussions in the Rails Discussion, I have come to the conclusion that it should not impact the launch of Rails.

In Figaro, there is an implementation to output warning logs, and it would be desirable to have similar warning logs outputted in this case as well.

```ruby
# When Rails starts
WARNING: The cache_store(:pool_size) is specified as a string.
```

> reference: https://github.com/laserlemon/figaro/issues/248

### Actual behavior

```ruby
/usr/local/bundle/gems/connection_pool-2.3.0/lib/connection_pool/timed_stack.rb:67:in `+': String can't be coerced into Float (TypeError)
```

> https://github.com/mperham/connection_pool/blob/main/lib/connection_pool/timed_stack.rb:67

It seems that the values retrieved from the environment variables remain as strings, which causes the above error.   
Of course, the values retrieved from environment variables are of string type.   
This issue can be resolved by using to_i .

### System configuration
**Rails version**: 7.0.5

**Ruby version**: 3.2.2

redis(gem): 5.0.6

### PR DESCRIPTION
**Pull request by casperisfine**
Fix: https://github.com/rails/rails/issues/48352

While we should ensure instantiating the store doesn't immediately attempt to connect, we should eagerly process arguments so that if they are somehow invalid we fail early during boot rather than at runtime.

Additionally, since it's common to get pool parameters from environment variable, we can use `Integer` and `Float` so that string representations are valid.

### CODE REVIEW

**Comment by okabe-yuya** [comment]
@byroot 
Thank you for your support.  
I am extremely happy and honored.

File: activesupport/lib/active_support/cache.rb [hunk 1]
```diff
@@ -186,35 +186,44 @@ class << self
...
-
-                if options[:pool_timeout]
-                  ActiveSupport.deprecator.warn(<<~MSG)
-                    Using :pool_timeout is deprecated and will be removed in Rails 7.2.
-                    Use `pool: { timeout: #{options[:pool_timeout].inspect} }` instead.
-                  MSG
-                  pool_options[:timeout] = options.delete(:pool_timeout)
-                end
-              end
+              pool_options = true
```
Comment (bbraschi) [inline activesupport/lib/active_support/cache.rb:210]: @casperisfine it seems that this change the default behavior of
`ActiveSupport::Cache::Store.retrieve_pool_options`
and causes [ActiveSupport::Cache::RedisCacheStore#initialize](https://github.com/rails/rails/blob/600a052c8cf6d355bd2d3f867cecce7cefdb1894/activesupport/lib/active_support/cache/redis_cache_store.rb#L148-L152) to use a `::ConnectionPool ` when it did not before
 
```ruby
if pool_options = self.class.send(:retrieve_pool_options, redis_options)
  @redis = ::ConnectionPool.new(pool_options) { self.class.build_redis(**redis_options) }
else
  @redis = self.class.build_redis(**redis_options)
end
```  

WDYT?

Comment (byroot) [reply activesupport/lib/active_support/cache.rb:210]: It's on purpose, 99% of the time not using a pool is unintentional.

Worst case if you only need a single connection, `ConnectionPool` lazily create them so it's fine.

Is this causing problem to you?

Comment (bbraschi) [reply activesupport/lib/active_support/cache.rb:210]: When we upgraded to Rails 7.1, our use of `scan_each`, [here](https://www.rubydoc.info/gems/redis/Redis/Commands/Keys#scan_each-instance_method), broke because `scan_each` is not implemented by the `::ConnectionPool` that `ActiveSupport::Cache::RedisCacheStore#redis` is now returning. 
No big deal.
