### PR TITLE
Avoid assigning duplicate values to join_values

### LINKED ISSUE #38052: Inconsistent results with #or in ActiveRecord::Relation after merged scope
When you join 2 tables and if you do merge several scopes with `merge` then `or` returning error.

### Steps to reproduce
```
[9] pry(main)> scope1 = User.joins(:profile).where('users.email like ?', '%chris%')
  User Load (1.0ms)  SELECT "users".* FROM "users" INNER JOIN "profiles" ON "profiles"."user_id" = "users"."id" WHERE (users.email like '%chris%')
[10] pry(main)> scope1.size
=> 2

[18] pry(main)> scope2 = User.joins(:profile).where('users.email like ?', '%nolan%')
  User Load (1.0ms)  SELECT "users".* FROM "users" INNER JOIN "profiles" ON "profiles"."user_id" = "users"."id" WHERE (users.email like '%nolan%')
[19] pry(main)> scope2.size
=> 4

[20] pry(main)> scope3 = User.joins(:profile).where('users.email like ?', '%dark.night%')
  User Load (0.7ms)  SELECT "users".* FROM "users" INNER JOIN "profiles" ON "profiles"."user_id" = "users"."id" WHERE (users.email like '%dark.night%')
[21] pry(main)> scope3.size
=> 1

[23] pry(main)> merged_scope = scope1.merge(scope2)
  User Load (0.8ms)  SELECT "users".* FROM "users" INNER JOIN "profiles" ON "profiles"."user_id" = "users"."id" WHERE (users.email like '%chris%') AND (users.email like '%nolan%')
[24] pry(main)> merged_scope.size
=> 1

[25] pry(main)> merged_scope.or(scope3)
ArgumentError: Relation passed to #or must be structurally compatible. Incompatible values: [:joins]

```

### Expected behavior
```
[25] pry(main)> merged_scope.or(scope3)
> SELECT "users".* FROM "users" INNER JOIN "profiles" ON "profiles"."user_id" = "users"."id" WHERE ((users.email like '%chris%') AND (profiles.name like '%nolan%') OR (users.email like '%dark.night%'))
```

### Actual behavior
```
[25] pry(main)> merged_scope.or(scope3)
ArgumentError: Relation passed to #or must be structurally compatible. Incompatible values: [:joins]
````

### System configuration
**Rails version**: 5.1.6.2

**Ruby version**: 2.5.3

### PR DESCRIPTION
**Pull request by sinsoku**
The ArgumentError occurs even though structures is compatible.
Because some query methods keep duplicate values.

For example, the behavior of `joins` method is as following:

```ruby
relation = Post.joins(:author).joins(:author)
relation.joins_values
#=> [:author, :author]
relation.or(Post.joins(:author))
#=> ArgumentError: Relation passed to #or must be structurally compatible. Incompatible values: [:joins]
```

This commit changes to not keep duplicate values.

Fixes #38052

### CODE REVIEW

File: activerecord/test/cases/relation/or_test.rb [hunk 1]
```diff
@@ -138,5 +138,15 @@ def test_or_with_scope_on_association
         author.top_posts.or(author.other_top_posts)
       end
     end
+
+    def test_or_with_multiple_joins
+      assert_nothing_raised do
+        Post.joins(:author).joins(:author).or(Post.joins(:author))
```
Comment (kamipo) [inline activerecord/test/cases/relation/or_test.rb]: If the purpose of this PR is to allow such like values for `or`, `joins` and `left_joins` are not only the case (e.g. `eager_load` etc).

Comment (sinsoku) [reply activerecord/test/cases/relation/or_test.rb]: Thank you for your review.
I checked the methods in [STRUCTURAL_OR_METHODS](https://github.com/rails/rails/blob/9171763d197bdd814fafaff0278712b2aed4d737/activerecord/lib/active_record/relation/query_methods.rb#L1360-L1367).

```ruby
ActiveRecord::QueryMethods::STRUCTURAL_OR_METHODS
#=> [:includes, :eager_load, :preload, :select, :group, :order, :joins, :left_outer_joins, :optimizer_hints, :annotate, :limit, :offset, :lock, :readonly, :reordering, :reverse_order, :distinct, :create_with, :skip_query_cache, :from]
```

### includes, eager_load, preload, group, joins, left_outer_joins

I fixed.

### limit, offset, lock, readonly, reordering, reverse_order, distinct, create_with, skip_query_cache

These use `=` instead of `+=` and do not need to be fixed.

### optimizer_hints

It uses `|=` and do not need to be fixed.

### annotate

An error occurs if the SQL comment is different, but I think it should not be an error.
I want to receive the opinion from Rails committer before the changes.

```ruby
assert_equal 'SELECT "posts".* FROM "posts" /* foo */ /* bar */',
  Post.annotate('foo').or(Post.annotate('bar')).to_sql
#=> ArgumentError: Relation passed to #or must be structurally compatible. Incompatible values: [:annotate]
```

<details>
<summary>test_script.rb</summary>

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.0"
  # gem "activerecord", path: '/Users/sinsoku/ghq/github.com/rails/rails/activerecord'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table(:posts, force: true)
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_or_with_annotate
    assert_equal 'SELECT "posts".* FROM "posts" /* foo */',
      Post.annotate('foo').or(Post.annotate('foo')).to_sql
    # Success

    assert_equal 'SELECT "posts".* FROM "posts" /* foo */ /* bar */',
      Post.annotate('foo').or(Post.annotate('bar')).to_sql
    #=> ArgumentError: Relation passed to #or must be structurally compatible. Incompatible values: [:annotate]
  end
end
```
</details>

### select, order

`select` and `order` have the same problem.

```ruby
Post.select(:id).select(:id).values[:select].size
#=> 2
Post.order(:id).order(:id).values[:order].size
#=> 2
```

However, the use case used with the `or` method does not come to mind.
Should I fix these?

### from

The from method uses `=`, but the same value causes an error.

```ruby
Post.from('users').or(User.from('users'))
#=> ArgumentError (Relation passed to #or must be structurally compatible. Incompatible values: [:from])
```

I can't imagine a use case that would be used with or.
Should I fix `from` to work with `or`?

Comment (kamipo) [reply activerecord/test/cases/relation/or_test.rb]: * `annotate`

If we will change to merge condition not only `where` and `having` but also `annotate`, it is notable change and also the doc should be updated. I prefer to discuss about that in another PR.

https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-or

* `select`, `order`

`select` and `order` is order dependent (e.g. dedup `select_values = [:id, "other_table.id", :id]` to `select_values = [:id, "other_table.id"]` will change public behavior), so it should be kept as it is from that point of view.

* `from`

This is probably easy to fix with like this:

```diff
diff --git a/activerecord/lib/active_record/relation/from_clause.rb b/activerecord/lib/active_record/relation/from_clause.rb
index 93b129ce99..222b1c70f0 100644
--- a/activerecord/lib/active_record/relation/from_clause.rb
+++ b/activerecord/lib/active_record/relation/from_clause.rb
@@ -21,6 +21,10 @@ def empty?
       def self.empty
         @empty ||= new(nil, nil).freeze
       end
+
+      def ==(other)
+        self.class == other.class && value == other.value && name == other.name
+      end
     end
   end
 end
```

File: activerecord/test/cases/relation/or_test.rb [hunk 2]
```diff
@@ -138,5 +138,16 @@ def test_or_with_scope_on_association
         author.top_posts.or(author.other_top_posts)
       end
     end
+
+    def test_structurally_incompatible_values
+      assert_nothing_raised do
+        Post.includes(:author).includes(:author).or(Post.includes(:author))
+        Post.eager_load(:author).eager_load(:author).or(Post.eager_load(:author))
+        Post.preload(:author).preload(:author).or(Post.preload(:author))
+        Post.group(:author).group(:author).or(Post.group(:author))
```
Comment (kamipo) [inline activerecord/test/cases/relation/or_test.rb]: `group` doesn't support association name, this will generate invalid (unknown column) SQL.

```suggestion
        Post.group(:author_id).group(:author_id).or(Post.group(:author_id))
```

File: activerecord/test/cases/relation/or_test.rb (hunk 1 above)
Comment (sinsoku) [reply activerecord/test/cases/relation/or_test.rb]: Thanks.
I fixed the `or` method to work with the `from` clause with the same value.

I will create an another PR  that changes the behavior when used with `annotate`.

File: activerecord/test/cases/relation/or_test.rb (hunk 2 above)
Comment (sinsoku) [reply activerecord/test/cases/relation/or_test.rb]: Oops. I fixed it.

**Comment by kamipo** [comment]
Changes looks good to me.
Can you update the commit message to reflect the current implementation?
This no longer only change the behavior `joins`.

**Comment by sinsoku** [comment]
I updated the commit message and force-pushed.
