### PR TITLE
Make AbstractAdapter#lock thread local by default

### LINKED ISSUE #45994: LoadInterlockAwareMonitor deadlock when clearing cache (multiple databases, test)
With multiple databases, we observe hangs within system tests.

See also https://gitlab.com/gitlab-org/gitlab/-/issues/371468 (GitLab is at Rails 6.1, Ruby 2.7.5)

### Steps to reproduce

Here's a minimal reproduction with Rails 7.0.3.1

1. Checkout https://gitlab.com/tkuah/multi_database_system_test
2. `bundle install`
3. `bundle exec rails db:migrate`
4. `bundle exec rails test test/system/home_pages_test.rb`

The conditions are:

1. Multiple databases
2. System test where there's an async request which overlaps with the main thread

### Expected behavior

It does not hang, and the test completes

### Actual behavior

It hangs. It looks like it's hanging when clearing query cache (see https://gitlab.com/gitlab-org/gitlab/-/issues/371468#note_1087203883, and https://gitlab.com/gitlab-org/gitlab/-/issues/371468#note_1088779499)

A backtrace dump taken while the test is hanging [sigdump-68442.log](https://github.com/rails/rails/files/9539878/sigdump-68442.log)

My suspicion is that:

1. `lock_thread` is true for system tests
3. Therefore both the main thread, and the Puma thread attempt to clear query cache for the same set of connections

So we have two connections:

1. Puma thread takes a `LoadInterlockAwareMonitor` lock for primary connection via `Post.transaction`
2. Main thread takes a `LoadInterlockAwareMonitor` lock for animal connection via implicit transaction that `create` does
3. Due to 2, main thread attempts to clear query cache for primary connection. **Waits for 1's lock**
4. Due to 1, and because of `lock_thread`, puma thread clears query cache for primary connection. It takes a `LoadInterlockAwareMonitor` lock for primary connection which succeds
5. Due to 1, puma thread now attempts clears query cache for animal connection. **Waits for 2's lock**

See [`clear_query_caches_for_current_thread` method](https://github.com/rails/rails/blob/e24fbf71fa0a10f63346b9b42604451958740844/activerecord/lib/active_record/connection_handling.rb#L244-L248)

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [arm64-darwin21]

### PR DESCRIPTION
**Pull request by casperisfine**
Fix: https://github.com/rails/rails/issues/45994

A semi-common issue since Ruby 3.0.2 is that using a fiber inside a transaction cause a deadlock:

```ruby
Post.transaction do
 enum =  Enumerator.new do |y|
   y.yield Post.first # stuck
 end
 enum.next
end
```

This is because in https://bugs.ruby-lang.org/issues/17827 Ruby changed Monitor to be owned by the calling Fiber rather than Thread.

And since the Active Record connection pool is per Thread, we end up in a situation where a Fiber tries to acquire a lock owned by another fiber with no change to ever resolve.

In https://github.com/rails/rails/pull/46519 We've made that lock optional as it's only needed for system tests.

Now this PR introduce an alternative lock implementation that behave like Monitor used to up to Ruby 2.7, and we use this one if `ActiveSupport::IsolatedExecutionState.context` is a Thread.

If it's a Fiber, we continue to use the implementation derived from the stdlib that is Fiber based.

Co-Authored-By: @wildmaples

FYI @eileencodes @matthewd @rafaelfranca @ngan @simi

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/abstract_adapter.rb [hunk 1]
```diff
@@ -173,10 +173,13 @@ def initialize(config_or_deprecated_connection, deprecated_logger = nil, depreca
       end
 
       def synchronized=(synchronized) # :nodoc:
-        @lock = if synchronized
-          ActiveSupport::Concurrency::LoadInterlockAwareMonitor.new
-        else
-          ActiveSupport::Concurrency::NullLock
+        @lock = case synchronized
```
Comment (matthewd) [inline activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:176]: Newline after the `=` will convince rubocop to allow formatting this in a way that looks less terrible

File: activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb [hunk 2]
```diff
@@ -29,5 +27,42 @@ def synchronize(&block)
...
+          @count += 1
+        end
+
+        def mon_enter
+          @mutex.lock if @owner != Thread.current
+          @owner = Thread.current
+          @count += 1
+        end
+
+        def mon_exit
```
Comment (matthewd) [inline activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:60]: I think this will quietly go negative if misused... which is low probability given our intended usage, but still maybe worth a touch more protection. Maybe just `raise if @owner != Thread.current`?

File: activerecord/lib/active_record/connection_adapters/abstract_adapter.rb [hunk 3]
```diff
@@ -173,10 +173,13 @@ def initialize(config_or_deprecated_connection, deprecated_logger = nil, depreca
       end
 
       def synchronized=(synchronized) # :nodoc:
```
Comment (matthewd) [inline activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:175]: `synchronized` sounds boolean, but we've switched to actually needing its object value. Perhaps we should rename to `lock_thread` for now, while acknowledging that we already ought to rename that on the pool given the execution state changes?

**Comment by ngan** [comment]
@casperisfine -- @wildmaples and I backported this to our app and ran it on Ruby 3.1. We're still seeing:
```
ActiveRecord::StatementInvalid:
  | Mysql2::Error: This connection is in use by: #<Thread:0x00007fb86ec4f030@puma srv tp 004 /var/www/vendor/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/thread_pool.rb:107 sleep>
```

Looking into this some more, our backtrace was showing that the error was happening in the `ActiveSupport::Concurrency::NullLock#synchronize`. This means that a request came into Puma _right after_ [`lock_thread` was set to `false`](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/test_fixtures.rb#L157). I think there's a race condition such that a JavaScript-initiated web request can still hit the web server during teardown. I _think_ the web server is [started once and kept running](https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/system_test_case.rb#L196) for the entirety of the test suite.

Rails 7.0.4 sets `lock_thread = false`, but it doesn't mean much since [`ConnectionPool#current_thread`](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L532-L534) pretty much always returns `Thread.current`. Whereas, with this change, we're switching back and forth between `NullLock` and `ThreadLoadInterlockAwareMonitor`.

**Comment by byroot** [comment]
Could you share the full backtrace of both threads (the one currently using the connection, and the one that hit the error) ? because it's hard to answer based only on your description.

Based on my understanding what you describe simply can't happen because to use the connection you have to check it out of the pool which sets `lock_thread`.

So for two threads to use the same connection, you'd need to bypass the connection pool somehow.

**Comment by ngan** [comment]
OK, the failures were our bad. We had missed the `@lock_thread` fix you made: https://github.com/rails/rails/pull/46553/files#diff-642b90553b888bd2c724c093a1a685a5408a7d8293f3751366c25dc548936eb7R178

This is why we were still seeing errors and why we were always assigned the `NullLock` 🤦 

This change is 👌 and our build is green! Thanks @casperisfine!

**Comment by casperisfine** [comment]
👍 .

I won't merge before next week, I want to give Eileen the opportunity to review.

**Comment by simi** [comment]
Looks amazing @casperisfine. I'll give it a try in our app where we had to bandaid this problem and report back.

**Review by eileencodes — APPROVED** [review]
This looks good to me, thanks for chasing this down @casperisfine

**Comment by kyrofa** [comment]
Any chance this can be back-ported to 7-0-stable?

**Comment by byroot** [comment]
None at all.

**Comment by rafaelfranca** [comment]
https://rubyonrails.org/maintenance#bug_fixes
