### PR TITLE
Fix HashWithIndifferentAccess#default when include?(nil)

### LINKED ISSUE #29738: ActionController::Parameters assignment array problem
```ruby
params = ActionController::Parameters.new

params[:settings] = [ { nil => "bug?" } ]

params[:settings].first[:any]

=> "bug?"
```

**Rails 5.1.0**:

**Ruby ruby-2.3.0**:

### PR DESCRIPTION
**Pull request by lugray**
Fixes #29738 

### Summary

The implementation of `HashWithIndifferentAccess#default` didn't distinguish `default` from `default(nil)`, which caused an incorrect result for `default` if `nil` was used as a key.

### CODE REVIEW

File: activesupport/lib/active_support/hash_with_indifferent_access.rb [hunk 1]
```diff
@@ -78,7 +78,7 @@ def initialize(constructor = {})
     def default(*args)
       arg_key = args.first
 
-      if include?(key = convert_key(arg_key))
+      if include?(key = convert_key(arg_key)) && args.size > 0
         self[key]
```
Comment (matthewd) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: Huh. This line (i.e., not your change) sounds notably unlike Hash#default. :confused:

```
[2] pry(main)> Hash.new { 5 }.merge(1 => 2).default(3)
=> 5
[3] pry(main)> Hash.new { 5 }.merge(1 => 2).with_indifferent_access.default(3)
=> 5
[4] pry(main)> Hash.new { 5 }.merge(1 => 2).default(1)
=> 5
[5] pry(main)> Hash.new { 5 }.merge(1 => 2).with_indifferent_access.default(1)
=> 2
```

Comment (lugray) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: Yes it does, but otherwise `HashWithIndifferentAccess#dig` doesn't work. #23414 fixes #18909.

Comment (matthewd) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: Hmm... sounds like we need to define our own `dig`: the one from the superclass [uses rb_hash_aref directly](https://github.com/ruby/ruby/blob/2430822b96a399ce5983b26637f597019690eb3e/hash.c#L2878), so doesn't get the `convert_key` treatment. 

It currently then "works" because after the aref misses, it falls back to the default value, which we lie about here to turn it into a second-chance lookup-by-key -- which is how all lookups worked prior to #18909.

So yeah, I think #23414 was just the wrong fix for the reported issue: #18909 should have added `dig` at the same time it added `[]` (but presumably missed it because `dig` was super-new at the time, IIRC).

Comment (lugray) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: `default` vs `default(nil)` behaved poorly even before the less-than-ideal `dig` fix.  My inclination is to leave that portion as is, and once this is merged, I'd be more than happy to pr a better `dig` with conforming `default`.

Comment (lugray) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: Never mind.  It was easier than I anticipated.

**Comment by lugray** [comment]
I've put up a potentially better fix in a new commit and can squash the two together if you agree with this approach.

File: activesupport/lib/active_support/hash_with_indifferent_access.rb [hunk 2]
```diff
@@ -186,6 +176,20 @@ def fetch(key, *extras)
...
+    # Same as <tt>Hash#dig</tt> where the key passed as argument can be
+    # either a string or a symbol:
+    #
+    #   counters = ActiveSupport::HashWithIndifferentAccess.new
+    #   counters[:foo] = { bar: 1 }
+    #
+    #   counters.dig('foo', 'bar')     # => 1
+    #   counters.dig(:foo, :bar)       # => 1
+    #   counters.dig(:zoo)             # => nil
+    def dig(*args)
```
Comment (rafaelfranca) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: Dig is only present on Ruby 2.3 and we still support Ruby 2.2. So we need to define it only conditionally.

File: activesupport/test/hash_with_indifferent_access_test.rb [hunk 3]
```diff
@@ -536,6 +536,18 @@ def test_nested_dig_indifferent_access
...
+    h = Hash.new(:default)
+    h[nil] = "defined"
+    h = h.with_indifferent_access
+    assert_equal :default, h.default
+  end
+
+  def test_default_with_argument
+    h = Hash.new { 5 }.merge(1 => 2).with_indifferent_access
+    assert_equal 5, h.default(1)
+  end
```
Comment (rafaelfranca) [inline activesupport/test/hash_with_indifferent_access_test.rb]: Maybe we need a test for the original issue. In the original issue there is no mention to default. Only the nil key was set in the hash and later tried to read a random key and got the value equivalent to `nil`.

**Comment by matthewd** [comment]
Nice!

I think we do still need a `default` like #18909's:

```ruby
Hash.new { |h, k| k }.with_indifferent_access[:foo] # => "foo"
Hash.new { |h, k| k }.with_indifferent_access.default(:foo) # => should be "foo", not :foo
```

File: activesupport/lib/active_support/hash_with_indifferent_access.rb (hunk 2 above)
Comment (matthewd) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: Ah, yes, I think we do that for Parameters already.

File: activesupport/test/hash_with_indifferent_access_test.rb (hunk 3 above)
Comment (lugray) [inline activesupport/test/hash_with_indifferent_access_test.rb]: `test_argless_default_with_existing_nil_key` is the test for the original issue.  I just added `:default` to make the test more clear in what was supposed to be happening.

**Comment by lugray** [comment]
Could I get another round of review for this?

**Review by spxtr — APPROVED** [review]

File: activesupport/test/hash_with_indifferent_access_test.rb (hunk 3 above)
Comment (sgrif) [inline activesupport/test/hash_with_indifferent_access_test.rb]: The original issue was specifically about `[]` though. I agree that we should test the issue as demonstrated originally with `[]` doing the expected thing.

Comment (lugray) [inline activesupport/test/hash_with_indifferent_access_test.rb]: 👍 Added a test.

**Comment by rafaelfranca** [comment]
@lugray can you create a backport PR to 5-1-stable branch since this PR does not apply clearly.
