### PR TITLE
Fix default key length on cipher

### LINKED ISSUE #25185: New app: "key must be 32 bits".
### Steps to reproduce
Run ```rails s```. No more... (new app)

### Expected behavior
It should display my index. 

### Actual behavior
It fails.

Here is what is going wrong:
capture d ecran 2016-05-28 a 21 18 13

Can you help me? Don't understand at all.

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.4.0dev

### PR DESCRIPTION
**Pull request by vipulnsward**
We default to using aes-256-cbc as our verification/signing cipher. It can accept key lengths of 128, 192 or 256-bit, whereas currently we were providing twice the acceptable value.

ruby < 2.4 allowed accepting these values, as extra key bits were ignored. Since https://github.com/ruby/ruby/commit/ce635262f53b760284d56bb1027baebaaec175d1 this now has a strict checking on key length.

Default to key length 32 bytes, to match the compatible length for  aes-256-cbc

Fixes #25185

### CODE REVIEW

**Comment by vipulnsward** [comment]
r? @jeremy
review @jeremy @tenderlove 
cc @rhenium

File: activesupport/test/key_generator_test.rb [hunk 1]
```diff
@@ -19,7 +19,7 @@ def setup
   test "Generating a key of the default length" do
     derived_key = @generator.generate_key("some_salt")
     assert_kind_of String, derived_key
-    assert_equal OpenSSL::Digest::SHA1.new.block_length, derived_key.length, "Should have generated a key of the default size"
+    assert_equal OpenSSL::Cipher::Cipher.new('aes-256-cbc').key_len, derived_key.length, "Should have generated a key of the default size"
```
Comment (rhenium) [inline activesupport/test/key_generator_test.rb]: This should be OpenSSL::Cipher.new(...). OpenSSL::Cipher::Cipher has been deprecated since Ruby 1.9.

**Comment by vipulnsward** [comment]
Adding this to 5.0 since, 5.0 Apps can't start on ruby 2.4 without this.

File: activesupport/test/message_encryptor_test.rb [hunk 2]
```diff
@@ -15,7 +15,7 @@ def load(value)
   end
 
   def setup
-    @secret    = SecureRandom.hex(64)
+    @secret    = SecureRandom.hex(16)
```
Comment (yui-knk) [inline activesupport/test/message_encryptor_test.rb]: I think `SecureRandom.random_bytes(32)` is more readable :)

**Comment by sgrif** [comment]
Moving off the 5.0.0 milestone since we don't need to block the release for something that only affects unreleased versions of Ruby.

File: activesupport/test/message_encryptor_test.rb (hunk 2 above)
Comment (tenderlove) [inline activesupport/test/message_encryptor_test.rb]: Agree with @yui-knk

**Comment by tenderlove** [comment]
@vipulnsward can you update with @yui-knk's suggestion and then I'll merge.

File: activesupport/test/message_encryptor_test.rb [hunk 3]
```diff
@@ -51,7 +51,7 @@ def test_signed_round_tripping
   def test_alternative_serialization_method
     prev = ActiveSupport.use_standard_json_time_format
     ActiveSupport.use_standard_json_time_format = true
-    encryptor = ActiveSupport::MessageEncryptor.new(SecureRandom.hex(64), SecureRandom.hex(64), :serializer => JSONSerializer.new)
+    encryptor = ActiveSupport::MessageEncryptor.new(SecureRandom.hex(16), SecureRandom.hex(64), :serializer => JSONSerializer.new)
```
Comment (tenderlove) [inline activesupport/test/message_encryptor_test.rb]: Change this one to `random_bytes` too please.

**Comment by vipulnsward** [comment]
Updated all occurrences.

**Comment by rafaelfranca** [comment]
Backported to 5-0-stable in ff0b426

**Comment by matthewd** [comment]
I think this may be a backwards-incompatible change -- given the same inputs (but using the default key size), we'll now produce different output.

**Comment by jeremy** [comment]
Argh yes. Back to `hex`?

**Comment by tenderlove** [comment]
`hex` shouldn't make a difference since it was just in the test files.  The only changes in `lib` changed the defanlt key size.  @matthewd does reverting the key size change fix it for you?  I would guess the key size depends on the cipher.

**Comment by vipulnsward** [comment]
Hmm, this is going to affect existing cookies/signed data.  We could/should have had this as a config maybe.
For now, will need to revert from 5-0 branches, and will need to have rolling keys support that @matthewd was speaking about.

**Comment by Fudoshiki** [comment]
Any option for support 2.4 ruby by edge rails?

**Comment by schneems** [comment]
> will need to have rolling keys support that @matthewd was speaking about.

Is this being worked on?

I re-opened the attached issue since the change was reverted.

**Comment by alexch** [comment]
I'm getting this error with Ruby 2.4.0p0 and Rails 4.2.7.1. Are there plans to support Ruby 2.4 with Rails 4.2?

**Comment by wpp** [comment]
@alexch Yes. See: https://github.com/rails/rails/pull/27473

**Comment by benoittgt** [comment]
On my personal projet I use a key size of 128 chars. This change break my code. I'm using rails 4.2.8 and ruby 2.4.0.

```ruby
def encryptor(id)
  ActiveSupport::MessageEncryptor.new(key(id)) # key(id).length = 128
end

def key(id)
  ActiveSupport::KeyGenerator.new(
    Digest::SHA512.base64digest(
      id.to_s + (0...64).map { ('a'..'z').to_a[rand(26)] }.join
    )
  ).generate_key((0...64).map { ('a'..'z').to_a[rand(26)] }.join, 128)
end
```

I get
```
ArgumentError:
       key must be 32 bytes
```

Does it means I can use 128 key size?

**Comment by matthewd** [comment]
@benoittgt this PR changed the default value of an argument you're explicitly supplying; it is not involved in the change you're seeing.

The change you care about is  https://github.com/ruby/ruby/commit/ce635262f53b760284d56bb1027baebaaec175d1, which is not in Rails.

**Comment by benoittgt** [comment]
Thanks @matthewd. Sorry for the noise.

**Comment by vanbumi** [comment]
still no idea how the steps to fix this ? help pelase

**Comment by MartinNowak** [comment]
This needs some more work IMO.
One option would be to keep implicitly slicing the cipher secret (but not the signature secret), at best with some deprecation warning.
In any case the documentation should to be updated http://api.rubyonrails.org/classes/ActiveSupport/MessageEncryptor.html (`secret must be at least as long as the cipher key size.`).

As a workaround for people updating their code, provide a sliced secret for encryption but the full length for signing.
```rb
ActiveSupport::MessageEncryptor.new(mykey[0, 32], mykey)
```

**Comment by MartinNowak** [comment]
Forgot to mention people @vipulnsward, @matthewd, @vanbumi
