### PR TITLE
Specify `table.name` only when `scope.table` and `table` are different

### LINKED ISSUE #29045: AR containing an attribute of it's pluralized name cause typecasting exceptions.
### Steps to reproduce
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end

  create_table :hours, force: true do |t|
    t.integer  "user_id"
    t.float :hours
  end
end

class User < ActiveRecord::Base
  has_many :hours
end

class Hour < ActiveRecord::Base
  belongs_to :user
end

class BugTest < Minitest::Test
  # This passes on Rails 5.0.x, fails on 5.1.x
  def test_collection_with_plural_of_class_name_as_attribute_fails_typecasting
    user = User.create!
    hour = user.hours.build
    assert hour.save
  end
end
```
### Expected behavior
A new hour object is built, and saved with only the attribute user_id assigned.

### Actual behavior
An error in typecasting attempted to convert the hash `{"user_id"=>1}` to a float.

### System configuration
Using activerecord 5.1.0
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

### PR DESCRIPTION
**Pull request by kamipo**
Fixes #29045.

### CODE REVIEW

File: activerecord/lib/active_record/associations/association_scope.rb [hunk 1]
```diff
@@ -159,6 +159,14 @@ def add_constraints(scope, owner, refl, chain_head, chain_tail)
           scope
         end
 
+        def apply_scope(scope, table, key, value)
+          if scope.table == table
+            scope.where!(key => value)
```
Comment (matthewd) [inline activerecord/lib/active_record/associations/association_scope.rb]: I had to go up 4 methods to confirm it was okay for this to mutate. I really just don't see the benefit of proliferating `where!`.

**Comment by rnubel** [comment]
@kamipo thanks for your work on this. I can confirm that this fix resolves the issue I was seeing (described specifically by https://github.com/rails/rails/issues/29878, but the same as the issue in the original description). Anything I can do to help get this into an upcoming release?

**Comment by jgelo** [comment]
This issue is blocking our upgrade to the 5.1 release, what concerns/issues are holding this fix back?

File: activerecord/lib/active_record/associations/association_scope.rb (hunk 1 above)
Comment (rafaelfranca) [inline activerecord/lib/active_record/associations/association_scope.rb]: agree. We can keep `where` here.

Comment (kamipo) [inline activerecord/lib/active_record/associations/association_scope.rb]: The `AssociationScope` returns newly created `scope` from `#scope`.
`#scope` creates `scope = klass.unscoped` and mutates the `scope` by `scope.extending! reflection.extensions`.

```ruby
      def scope(association)
        klass = association.klass
        reflection = association.reflection
        scope = klass.unscoped
        owner = association.owner
        alias_tracker = AliasTracker.create(klass.connection, klass.table_name)
        chain_head, chain_tail = get_chain(reflection, association, alias_tracker)

        scope.extending! reflection.extensions # mutate the `scope`
        add_constraints(scope, owner, reflection, chain_head, chain_tail)
      end
```

`#add_constraints` also mutates the `scope` (I have another bug fix PR #29659. it also mutate the `scope` in `#add_constraints`).

```ruby
      private

        def add_constraints(scope, owner, refl, chain_head, chain_tail)
          owner_reflection = chain_tail
          table = owner_reflection.alias_name
          scope = last_chain_scope(scope, table, owner_reflection, owner)

          reflection = chain_head
          while reflection
            table = reflection.alias_name
            next_reflection = reflection.next

            unless reflection == chain_tail
              foreign_table = next_reflection.alias_name
              scope = next_chain_scope(scope, table, reflection, foreign_table, next_reflection)
            end

            reflection.constraints.each do |scope_chain_item|
              item = eval_scope(reflection, table, scope_chain_item, owner)

              if scope_chain_item == refl.scope
                scope.merge! item.except(:where, :includes) # mutate the `scope`
              end

              reflection.all_includes do
                scope.includes! item.includes_values # mutate the `scope`
              end

              scope.unscope!(*item.unscope_values) # mutate the `scope`
              scope.where_clause += item.where_clause # mutate the `scope`
              scope.order_values |= item.order_values # mutate the `scope`
            end

            reflection = next_reflection
          end

          scope
        end
```

`#last_chain_scope` and `#next_chain_scope` are called via `#add_constraints`.
Since `#add_constraints` mutates the `scope`, I think it is no worth to avoid mutations in `#last_chain_scope` and `#next_chain_scope`. In addition, extra `spawn` to avoid mutations has a overhead (ref https://github.com/rails/rails/pull/29009#issuecomment-321773151).

I placed the `apply_scope` at the bottom of private methods because the common logic is only used for internal private methods. I think that usually users don't read the code from the bottom of private methods.

WDYT?
