### PR TITLE
Raise error when passing invalid arguments on subscription instead of failing silently

### LINKED ISSUE #39610: ActiveSupport::Notifications not unsubscribe symbol pattern
### Steps to reproduce

Add the following test case to [activesupport/test/notifications_test.rb](https://github.com/rails/rails/blob/master/activesupport/test/notifications_test.rb), and run by `bundle exec rake test TEST=test/notifications_test.rb TESTOPTS="--name=test_unsubscribe_symbol"`

```rb
module Notifications
  # new test case
  class SubscribeToSymbolPattern < TestCase
    def test_unsubscribe_symbol
      notifier = ActiveSupport::Notifications::Fanout.new
      symbol = :foo

      subscriber = notifier.subscribe(symbol) { |*_| }
      assert_equal [subscriber], notifier.listeners_for(symbol)

      notifier.unsubscribe(symbol)
      assert_equal [], notifier.listeners_for(symbol)
    end
  end
end
```

### Expected behavior

Test pass

### Actual behavior

```
Failure:
Notifications::Notifications::SubscribeToSymbolPattern#test_unsubscribe_symbol [/Users/wendi/Workspace/rails/activesupport/test/notifications_test.rb:213]:
--- expected
+++ actual
@@ -1 +1 @@
-[#<ActiveSupport::Notifications::Fanout::Subscribers::Timed:0xXXXXXX @pattern=#<ActiveSupport::Notifications::Fanout::Subscribers::Matcher:0xXXXXXX @pattern=:foo, @exclusions=#<Set: {}>>, @delegate=#<Proc:0xXXXXXX@/Users/wendi/Workspace/rails/activesupport/test/notifications_test.rb:212>, @can_publish=false>]
+[]
```

### System configuration
**Rails version**: 6.1.0.alpha
**Ruby version**: 2.7

### Analysis

I'm using `ActiveSupport::Notifications` in a project for instrumentation, and I've noticed that by using a symbol pattern name, it worked well for `subscribe`, but not for `unsubscribe`.

By looking into the code here,

https://github.com/rails/rails/blob/49baf092439fc74fc3377b12e3334c3dd9d0752f/activesupport/lib/active_support/notifications/fanout.rb#L24-L56

both `subscribe` and `unsubscribe` _only_ check `String` as named subscriptions and leave the symbol name as "other" subscriptions, which are supposed to be regex or nil pattern name. The bug is hidden as subscription with symbol name works well, accidentally. It only runs into trouble with unsubscription.

I think a proper fix is to handle `Symbol` as `String` in the code. I can help throw a fix if the analysis sounds valid.

### PR DESCRIPTION
**Pull request by vipulnsward**
Currently subscription api on notifications is only supported for String, Regex or nil. If we pass anything different, this causes issues like  #39610 because it gets added to "other subscribers" silently.

We now raise an argument error instead if something invalid is passed.

Partially accesses original class implementation from https://github.com/rails/rails/commit/4f2a04cc085b9117e8af8079a95a063f671d7a3d which used the case/when

Does not do the same ArgumentError on unsubscribe, since subscribe would already fail.

Closes #39610

### CODE REVIEW

File: activesupport/lib/active_support/notifications/fanout.rb [hunk 1]
```diff
@@ -24,12 +24,15 @@ def initialize
...
+          case pattern
+          when String
             @string_subscribers[pattern] << subscriber
             @listeners_for.delete(pattern)
-          else
+          when NilClass, Regexp
             @other_subscribers << subscriber
             @listeners_for.clear
+          else
+            raise ArgumentError,  "pattern must be specified as a String, Regexp or empty"
```
Comment (tgxworld) [inline activesupport/lib/active_support/notifications/fanout.rb:35]: I think this check should happen much earlier so that we don't have to create a `Subscribers` object when the argument isn't valid.

File: activesupport/lib/active_support/notifications.rb [hunk 2]
```diff
@@ -231,6 +231,13 @@ def instrument(name, payload = {})
       #   ActiveSupport::Notifications.subscribe(/render/) do |event|
       #     @event = event
       #   end
+      #
+      # Only accepts a String, Regex or empty(matches all events) event name.
+      # Raises an error if invalid event name type is passed:
+      #
+      #  ActiveSupport::Notifications.subscribe(/render/) {|*args| ...}
```
Comment (tgxworld) [inline activesupport/lib/active_support/notifications.rb:238]:
```suggestion
      #  ActiveSupport::Notifications.subscribe(:render) {|*args| ...}
```

`/render/` will be valid since it is a regexp.

File: activesupport/lib/active_support/notifications.rb [hunk 3]
```diff
@@ -231,6 +231,13 @@ def instrument(name, payload = {})
       #   ActiveSupport::Notifications.subscribe(/render/) do |event|
       #     @event = event
       #   end
+      #
+      # Only accepts a String, Regex or empty(matches all events) event name.
```
Comment (tgxworld) [inline activesupport/lib/active_support/notifications.rb:235]: I don't think we need to repeat this again since the comments above already states 

>      # You can subscribe to events by passing a String to match exact event
>      # names, or by passing a Regexp to match all events that match a pattern.

File: activesupport/lib/active_support/notifications/fanout.rb (hunk 1 above)
Comment (vipulnsward) [reply activesupport/lib/active_support/notifications/fanout.rb:35]: This will not be a hot-path and will immediately fail, so doesn't seem like ideal to move params check before others as an extra step.

Comment (tgxworld) [reply activesupport/lib/active_support/notifications/fanout.rb:35]: That is true, thank you for clarifying :+1:

**Comment by tgxworld** [comment]
@vipulnsward Should we reopen this?
