### PR TITLE
Fix the AS::Callbacks terminator regression from 4.2.3

### LINKED ISSUE #21122: AS::Callbacks unreachable code
After #17227 introduced a [default callback terminator](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/callbacks.rb#L525) to take care of halt conditions, it seems that [conditional](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/callbacks.rb#L281) and [simple](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/callbacks.rb#L283) methods will never be reached for `before`, `after` or `around` callbacks.

@claudiob Any thoughts here?

### PR DESCRIPTION
**Pull request by repinel**
Rails 4.2.3 AS::Callbacks will not halt chain if `false` is returned. That is the behavior of specific callbacks like AR::Callbacks and AM::Callbacks.

The two test cases from https://gist.github.com/repinel/93ab39881825d913466d might illustrate my point.

Fixes #21122

@claudiob @kaspth What do you think?

### CODE REVIEW

**Comment by claudiob** [comment]
Give me a couple of days to look at this :calendar: thanks!

**Comment by repinel** [comment]
Sounds good, thanks! :heart:

**Comment by kaspth** [comment]
@claudiob have you had a chance to look at this yet? :smile:

**Comment by claudiob** [comment]
Ooops, I'm the worst :sweat_smile:

**Comment by claudiob** [comment]
Okay @repinel, sorry for the delay, I finally looked at your PR.

First of all, you are right: there is a specific case that would not work as expected when updating an app from Rails 4.2 to Rails 5.0. You showed the example in [your gist](https://gist.github.com/repinel/93ab39881825d913466d), and here is the gist of that gist:

* In Rails 4.2, if the user invokes a set of callbacks without setting any terminator, then **all callbacks** are invoked, no matter what. That's because the [simple](https://github.com/rails/rails/blob/e57bf9d28be9e480df827d4c83a42ecfa166b092/activesupport/lib/active_support/callbacks.rb#L193-L199) method is invoked, which does not check at all for callback being halted or terminated
* In Rails 5.0, if the user invokes a set of callbacks without setting any terminator, then any callback returning `false` will halt the callback chain and emit a deprecation warning.

The reason why this happen is that "checking whether a callback returns `false`" was a task that was relegated to ActiveRecord and ActiveModel and that I wrongly moved to ActiveSupport in [this line of the PR #17227](https://github.com/rails/rails/pull/17227/files#diff-1ecd313ff0ab827af30014553cf8918dR606).

In the current PR, you are correctly reverting that thinking, moving back the `false` to ActiveRecord and ActiveModel. I think your PR is moving in the correct direction… however it raises new questions:

1. should `default_false_terminator` live inside ActiveSupport? Did you put it there just because it's used both by ActiveRecord and ActiveModel or do you think it's more generic than that?
1. should the deprecation warning change? After your change, it will be valid to return `false` in a callback and not see any warning
1. should the deprecation warning actually be moved to ActiveModel and ActiveRecord?

I don't have full answers for these, I still need to delve into the code.

I appreciate your effort in looking inside such a complex class, and I agree that this needs to be fixed before Rails 5.0.

**Comment by claudiob** [comment]
More in details, #17227 has a set of commits; most of them are correct but the one that wrongly changed the behavior of ActiveSupport is https://github.com/rails/rails/commit/d217daf6a740de7e4925872abe632982cfaab89b

**Comment by claudiob** [comment]
Okkkkkay @repinel I went through the whole PR again and I think you did the right thing :+1: 

I'll comment your PR line by line with some notes: if you could fix those, then this PR is good to go.

File: activemodel/lib/active_model/callbacks.rb [hunk 1]
```diff
@@ -103,6 +103,7 @@ def self.extended(base) #:nodoc:
     def define_model_callbacks(*callbacks)
       options = callbacks.extract_options!
       options = {
+        terminator: default_false_terminator,
```
Comment (claudiob) [inline activemodel/lib/active_model/callbacks.rb]: I have two suggestions:

1. rename this method to `deprecated_false_terminator`, so its intent is clearer
2. pass as an argument the current module, that is, `terminator: deprecated_false_terminator(ActiveModel)`

I'll show in the next comment why I think 2. is a good idea

File: activemodel/lib/active_model/validations/callbacks.rb [hunk 2]
```diff
@@ -23,6 +23,7 @@ module Callbacks
       included do
         include ActiveSupport::Callbacks
         define_callbacks :validation,
+                         terminator: default_false_terminator,
```
Comment (claudiob) [inline activemodel/lib/active_model/validations/callbacks.rb]: Same as before, I would use `terminator: deprecated_false_terminator(ActiveModel::Validations)`

File: activerecord/lib/active_record/transactions.rb [hunk 3]
```diff
@@ -11,6 +11,7 @@ module Transactions
                        :before_commit_without_transaction_enrollment,
                        :commit_without_transaction_enrollment,
                        :rollback_without_transaction_enrollment,
+                       terminator: default_false_terminator,
```
Comment (claudiob) [inline activerecord/lib/active_record/transactions.rb]: Same as before, I would use `terminator: deprecated_false_terminator(ActiveRecord::Transactions)`

File: activerecord/test/cases/attribute_test.rb [hunk 4]
```diff
@@ -5,7 +5,6 @@ module ActiveRecord
   class AttributeTest < ActiveRecord::TestCase
     setup do
       @type = Minitest::Mock.new
-      @type.expect(:==, false, [false])
```
Comment (claudiob) [inline activerecord/test/cases/attribute_test.rb]: I'm not sure this belongs to the same commit as the rest…

File: activesupport/lib/active_support/callbacks.rb [hunk 5]
```diff
@@ -318,33 +283,6 @@ def self.halting(callback_sequence, user_callback)
...
-
-        def self.simple(callback_sequence, user_callback)
-          callback_sequence.around do |env, &run|
-            user_callback.call(env.target, env.value) {
-              run.call.value
-            }
-            env
-          end
-        end
-        private_class_method :simple
```
Comment (claudiob) [inline activesupport/lib/active_support/callbacks.rb]: All the code above fixes #21122 and it's a slightly different problem than what this PR is addressing.

For this reason, I have made a separate PR #21616 which only deals with removing the unused code above.

If #21616 gets merged into master, then you can rebase this PR on top of that and these deletions should be gone.

File: activesupport/lib/active_support/callbacks.rb [hunk 6]
```diff
@@ -826,6 +754,30 @@ def get_callbacks(name)
       def set_callbacks(name, callbacks)
         send "_#{name}_callbacks=", callbacks
       end
+
+      def default_false_terminator
```
Comment (claudiob) [inline activesupport/lib/active_support/callbacks.rb]: See above, I would pass a `klass` argument to this method.

File: activesupport/lib/active_support/callbacks.rb [hunk 7]
```diff
@@ -826,6 +754,30 @@ def get_callbacks(name)
...
+        Proc.new do |target, result_lambda|
+          terminate = true
+          catch(:abort) do
+            result = result_lambda.call if result_lambda.is_a?(Proc)
+            if CallbackChain.halt_and_display_warning_on_return_false && result == false
+              display_deprecation_warning_for_false_terminator
```
Comment (claudiob) [inline activesupport/lib/active_support/callbacks.rb]: And then I would pass the `klass` through here, that is: `display_deprecation_warning_for_false_terminator(klass)`.

File: activesupport/lib/active_support/callbacks.rb [hunk 8]
```diff
@@ -826,6 +754,30 @@ def get_callbacks(name)
...
+              terminate = false
+            end
+          end
+          terminate
+        end
+      end
+
+      private
+
+      def display_deprecation_warning_for_false_terminator
```
Comment (claudiob) [inline activesupport/lib/active_support/callbacks.rb]: This would get the `klass` as well.

File: activesupport/lib/active_support/callbacks.rb [hunk 9]
```diff
@@ -826,6 +754,30 @@ def get_callbacks(name)
...
+        ActiveSupport::Deprecation.warn(<<-MSG.squish)
+          Returning `false` in a callback will not implicitly halt a callback chain in the next release of Rails.
+          To explicitly halt a callback chain, please use `throw :abort` instead.
```
Comment (claudiob) [inline activesupport/lib/active_support/callbacks.rb]: And finally… this message would be much clearer like this:

```ruby
ActiveSupport::Deprecation.warn(<<-MSG.squish)
  Returning `false` in an #{klass} callback will not implicitly halt a callback chain in the next release of Rails.
  To explicitly halt an #{klass} callback chain, please use `throw :abort` instead.
MSG
```

So the users would understand that the behavior has changed **only** for ActiveModel, ActiveModel::Validations and ActiveRecord, and not for any other third-party app using ActiveSupport::Callbacks

File: activesupport/test/callbacks_test.rb [hunk 10]
```diff
@@ -781,13 +779,11 @@ def setup
...
+    def test_returning_false_does_not_halt_callback_if_config_variable_is_true
       obj = CallbackFalseTerminator.new
-      assert_deprecated do
-        obj.save
-        assert_equal :second, obj.halted
-        assert !obj.saved
-      end
+      obj.save
+      assert_equal nil, obj.halted
+      assert obj.saved
```
Comment (claudiob) [inline activesupport/test/callbacks_test.rb]: :+1: with these new tests

File: activesupport/lib/active_support/callbacks.rb [hunk 11]
```diff
@@ -826,6 +754,30 @@ def get_callbacks(name)
       def set_callbacks(name, callbacks)
         send "_#{name}_callbacks=", callbacks
       end
+
+      def default_false_terminator
+        Proc.new do |target, result_lambda|
+          terminate = true
+          catch(:abort) do
+            result = result_lambda.call if result_lambda.is_a?(Proc)
+            if CallbackChain.halt_and_display_warning_on_return_false && result == false
```
Comment (claudiob) [inline activesupport/lib/active_support/callbacks.rb]: Since this terminator is getting moved *outside* of the `CallbackChain` class, we could simplify the code even more by replacing the current 

```ruby
ActiveSupport::Callbacks::CallbackChain.halt_and_display_warning_on_return_false
```

with 

```ruby
ActiveSupport::Callbacks.halt_and_display_warning_on_return_false
```
In other words, we could make `halt_and_display_warning_on_return_false` a module accessor.

Note that this change is independent of the rest, and independent of this commit.
I just think it would be nicer, but deserves its own commit, since we would also have to change any snippet of code where `halt_and_display_warning_on_return_false` (such as the CHANGELOG files)

**Comment by claudiob** [comment]
Finally, your PR should also change [these lines of the CHANGELOG](https://github.com/rails/rails/blame/master/activesupport/CHANGELOG.md#L265-L292) since what is described there is no longer true.

Those lines should instead say:

```markdown
*   Change the way in which callback chains can be halted.

    The preferred method to halt a callback chain from now on is to explicitly
    `throw(:abort)`.
    In the past, callbacks could only be halted by explicitly providing a 
    terminator and by having a callback match the conditions of the terminator.

*   Add `Callbacks.halt_and_display_warning_on_return_false`

    Setting `Callbacks.halt_and_display_warning_on_return_false` to `true` will 
    let an app support the deprecated way of halting ActiveRecord, ActiveModel
    and ActiveModel::Validations callback chains by returning `false`.

    Setting the value to `false` will tell the app to ignore any `false` value
    returned by those callbacks, and only halt the chain upon `throw(:abort)`.

    The value can also be set with the Rails configuration option
    `config.active_support.halt_callback_chains_on_return_false`.

    When the configuration option is missing, its value is `true`, so older apps
    ported to Rails 5.0 will not break (but display a deprecation warning).
    For new Rails 5.0 apps, its value is set to `false` in an initializer, so
    these apps will support the new behavior by default.

    *claudiob and Roque Pinel*
```

**Comment by repinel** [comment]
Awesome, @claudiob! I'll review all your comments. Thanks :smile:

**Comment by claudiob** [comment]
@repinel The other PR was merged, so feel free to rebase on master

File: activesupport/test/callbacks_test.rb (hunk 10 above)
Comment (kaspth) [inline activesupport/test/callbacks_test.rb]: I don't understand this change. Didn't we want `throw(:abort)` to be the default if the config isn't set?

File: activerecord/lib/active_record/transactions.rb [hunk 12]
```diff
@@ -11,6 +11,7 @@ module Transactions
                        :before_commit_without_transaction_enrollment,
                        :commit_without_transaction_enrollment,
                        :rollback_without_transaction_enrollment,
+                       terminator: deprecated_false_terminator(ActiveRecord::Transactions),
```
Comment (kaspth) [inline activerecord/lib/active_record/transactions.rb]: I'm actually against this change. `ActiveRecord::Transactions` would make no sense to the average user. It would be much better to just say Active Record callbacks.

File: activemodel/lib/active_model/callbacks.rb [hunk 13]
```diff
@@ -103,6 +103,7 @@ def self.extended(base) #:nodoc:
     def define_model_callbacks(*callbacks)
       options = callbacks.extract_options!
       options = {
+        terminator: deprecated_false_terminator(ActiveModel),
```
Comment (kaspth) [inline activemodel/lib/active_model/callbacks.rb]: Same here. Should be mention the callbacks here instead of just the module?

File: activemodel/lib/active_model/validations/callbacks.rb [hunk 14]
```diff
@@ -23,6 +23,7 @@ module Callbacks
       included do
         include ActiveSupport::Callbacks
         define_callbacks :validation,
+                         terminator: deprecated_false_terminator(ActiveModel::Validations),
```
Comment (kaspth) [inline activemodel/lib/active_model/validations/callbacks.rb]: I'd say `validation callbacks` would make more sense.

File: activesupport/CHANGELOG.md [hunk 15]
```diff
@@ -266,20 +266,17 @@
...
-    either not work at all or display a deprecation warning.
+    In the past, callbacks could only be halted by explicitly providing a
+    terminator and by having a callback match the conditions of the terminator.
 
 *   Add `Callbacks::CallbackChain.halt_and_display_warning_on_return_false`
 
     Setting `Callbacks::CallbackChain.halt_and_display_warning_on_return_false`
-    to `true` will let an app support the deprecated way of halting callback
-    chains by returning `false`.
+    to `true` will let an app support the deprecated way of halting ActiveRecord,
```
Comment (kaspth) [inline activesupport/CHANGELOG.md]: Since we aren't referring to the constant we should put a space in there: `Active Record, Active Model, and Active Model validations`.

File: activesupport/CHANGELOG.md [hunk 16]
```diff
@@ -266,20 +266,17 @@
...
     `throw(:abort)`.
-    In the past, returning `false` in an ActiveSupport callback had the side
-    effect of halting the callback chain. This is not recommended anymore and,
-    depending on the value of
-    `Callbacks::CallbackChain.halt_and_display_warning_on_return_false`, will
-    either not work at all or display a deprecation warning.
+    In the past, callbacks could only be halted by explicitly providing a
+    terminator and by having a callback match the conditions of the terminator.
 
 *   Add `Callbacks::CallbackChain.halt_and_display_warning_on_return_false`
```
Comment (kaspth) [inline activesupport/CHANGELOG.md]: This whole item feels tough to understand to me. How about just:

```
To aid migration set `Callbacks::CallbackChain.halt_and_display_warning_on_return_false` to `true`, then returning `false` in a callback halts callback execution like in previous Rails versions.
```

File: activerecord/test/cases/attribute_test.rb (hunk 4 above)
Comment (repinel) [inline activerecord/test/cases/attribute_test.rb]: This is no longer needed since `CallbackChain#default_terminator` now does not check if the returned value is `false`.

File: activesupport/test/callbacks_test.rb (hunk 10 above)
Comment (claudiob) [inline activesupport/test/callbacks_test.rb]: Exactly. 

In Rails 5 you halt the callback chain by throwing `:abort`. If you return false, the chain is not halted and the object is saved

File: activerecord/lib/active_record/transactions.rb (hunk 12 above)
Comment (claudiob) [inline activerecord/lib/active_record/transactions.rb]: Ehehe, I thought about that and I wasn't sure which one to pick.

Since it confuses you, I'd say let's go with `ActiveRecord` instead!

File: activemodel/lib/active_model/validations/callbacks.rb (hunk 14 above)
Comment (claudiob) [inline activemodel/lib/active_model/validations/callbacks.rb]: Ok… maybe the idea of passing the module was not great.

I just thought of having something to pass through, so it would make for a better deprecation error.

If we just said "returning false in callbacks is deprecated", that would be misleading, because it's not in *all* callbacks, just AR and AM ones.

@kaspth… given all your feedback, I wonder whether we should drop the idea of passing these modules around at all, and simply fix the string in the `deprecated_false_terminator` model to say "returning false in ActiveRecord and ActiveModel callbacks is deprecated" and call it a day.

File: activesupport/lib/active_support/callbacks.rb (hunk 11 above)
Comment (kaspth) [inline activesupport/lib/active_support/callbacks.rb]: I'm :+1: on doing this. `CallbackChain` doesn't feel like something people should know about.

But @claudiob, doesn't having the setting on `ActiveSupport::Callbacks` feel out of place with you saying it only affects Active Record and Active Model callbacks?

File: activesupport/test/callbacks_test.rb (hunk 10 above)
Comment (kaspth) [inline activesupport/test/callbacks_test.rb]: Ah do'h! Thanks :+1:

File: activemodel/lib/active_model/validations/callbacks.rb (hunk 14 above)
Comment (kaspth) [inline activemodel/lib/active_model/validations/callbacks.rb]: When it comes to deprecation warnings I think it would be nicer to have it as static as possible (easier grepping perhaps).

So I'm :+1: on saying `returning false in Active Record and Active Model callbacks in deprecated` (remember the spaces in the names when we aren't referring to the constants :grin:)

@claudiob I still don't understand why Active Support callbacks aren't affected by this — can you elaborate? I especially don't understand given this: https://github.com/rails/rails/pull/21218/files#r39675510

File: activesupport/lib/active_support/callbacks.rb (hunk 11 above)
Comment (claudiob) [inline activesupport/lib/active_support/callbacks.rb]: @kaspth That's the same concern I expressed [in my initial comment](https://github.com/rails/rails/pull/21218#issuecomment-139924781):

> should default_false_terminator live inside ActiveSupport? Did you put it there just because it's used both by ActiveRecord and ActiveModel or do you think it's more generic than that?

"Logically", it should live inside AR and AM… in other words there should be **two different settings**, like:

```ruby
ActiveRecord.halt_and_display_warning_on_return_false = ...
ActiveModel.halt_and_display_warning_on_return_false = ...
```

The benefit of having the setting in ActiveSupport is that you can have it just once.

Do you think that's a strong enough argument? Or you'd rather have it "logically" duplicated?

Comment (kaspth) [inline activesupport/lib/active_support/callbacks.rb]: Oh no, there should only be one setting. I just don't understand why Active Support callbacks shouldn't be affected by it?

Comment (claudiob) [inline activesupport/lib/active_support/callbacks.rb]: Because in ActiveSupport <= 4.2, the value returned by callbacks was (already) ignored.

Therefore, the behavior in Rails 5 does not change for ActiveSupport itself.

It only changes for AR and AM that were using ActiveSupport::Callbacks, but specifying a custom terminator that said "if any callback returns `false`, halt the chain".

Therefore, if someone returns `false` in AR or AM callbacks in Rails 5, we have to *warn* them that they should change their code if they really want the chain to be halted, otherwise their code will not have any effect starting with Rails 5.1.

Comment (kaspth) [inline activesupport/lib/active_support/callbacks.rb]: Ah, now I get it. Thanks for the explanation :+1:

It would still feel weird to have a setting on Active Support that then only mentions Active Record and Active Model.

There's some things we could do. Rename the config to `Rails.application.config.callbacks.halt_and_display_warning_on_return_false` and bump these specifics to the upgrading guide.

It also sounds like using Active Support callbacks directly is an edge case, so in our deprecation message it's fine to treat AR and AM callbacks as all the callbacks IMO.

Unless we already have them, we should add some instructions to support `throw(:abort)` for the libraries that define their own callbacks with AS.

What do you think, @claudiob @repinel? :smile:

Comment (claudiob) [inline activesupport/lib/active_support/callbacks.rb]: Agreed, except for:

> It also sounds like using Active Support callbacks directly is an edge case, so in our deprecation message it's fine to treat AR and AM callbacks as all the callbacks IMO.

It's not the edge case. Rails itself uses AS callbacks directly, as well as third-party gems.

Comment (kaspth) [inline activesupport/lib/active_support/callbacks.rb]: I mean edge case from the perspective of a user's application. People aren't defining their own types of callbacks. That's for Rails and libraries.

Comment (kaspth) [inline activesupport/lib/active_support/callbacks.rb]: @repinel what do you think of our suggestions? :smile:

Comment (repinel) [inline activesupport/lib/active_support/callbacks.rb]: Thanks for the ping! I would go with just one configuration option and one proposed by @kaspth  seems generic enough.

File: activemodel/lib/active_model/validations/callbacks.rb (hunk 14 above)
Comment (repinel) [inline activemodel/lib/active_model/validations/callbacks.rb]: Indeed. It looks simpler to say `Active Record and Active Model` instead of using an argument.

All in favor of changing it back and improving the message?

File: activesupport/lib/active_support/callbacks.rb (hunk 11 above)
Comment (claudiob) [inline activesupport/lib/active_support/callbacks.rb]: @repinel Tell me if you'd like to conclude this PR with our suggestions. If you are busy, I can do that.

Comment (repinel) [inline activesupport/lib/active_support/callbacks.rb]: I can work on it :wink: 

Thanks for all the feedback!

**Comment by repinel** [comment]
@claudiob @kaspth I changed `display_deprecation_warning_for_false_terminator` back. It now has a static message mentioning Active Record and Active Model callbacks.

File: activesupport/lib/active_support/callbacks.rb (hunk 11 above)
Comment (repinel) [inline activesupport/lib/active_support/callbacks.rb]: It seems to me that there is not longer a configuration option `config.active_support.halt_callback_chains_on_return_false`, as you can see from 0a120a818d413c64ff9867125f0b03788fc306f8. Am I mistaken?

I suggest having a new PR that would also fix the docs that still mention the option. If not on `ActiveSupport`, would the configuration go to a `Callbacks` module?

**Comment by claudiob** [comment]
@repinel This looks good to me.

@kaspth Do you want to give it a look? If you are also fine, just merge :grinning:

File: activesupport/lib/active_support/callbacks.rb (hunk 11 above)
Comment (kaspth) [inline activesupport/lib/active_support/callbacks.rb]: Nah, let's just leave it on `ActiveSupport`. Yeah, send a PR for the doc change (remember the changelogs).

**Comment by kaspth** [comment]
:heart:

File: activesupport/lib/active_support/callbacks.rb (hunk 11 above)
Comment (repinel) [inline activesupport/lib/active_support/callbacks.rb]: Sounds good. Thanks

**Comment by repinel** [comment]
Thank you all for reviewing it :heart:
