### PR TITLE
[#35782] Allow loading seeds without ActiveJob (~> 5.2.3)

### LINKED ISSUE #35782: NoMethodError: undefined method `active_job' for Rails::Application::Configuration
### Steps to reproduce
I have an app where I do not need Active Job, so its commented at application.rb:
<pre>
# require "active_job/railtie"
</pre>

In last version of rails 5.2.3 errors appear every time I ran: bundle exec rake db:setup.
I believe it is because this commit:
https://github.com/rails/rails/commit/44133fdd9110d8103e6a352ceb79b8b14a2de8ff

<pre>
rake aborted!
NoMethodError: undefined method `active_job' for #<Rails::Application::Configuration:0x000055b978c05a30>
/home/runner/bole.to/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/railtie/configuration.rb:97:in `method_missing'
/home/runner/bole.to/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:662:in `with_inline_jobs'
/home/runner/bole.to/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:551:in `load_seed'
/home/runner/bole.to/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/home/runner/bole.to/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <main>'
/home/runner/bole.to/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/runner/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/home/runner/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
</pre> 

### Expected behavior
When require is not commented:
Loading development environment (Rails 5.2.3)
[1] pry(main)> Rails.application.config.active_job.queue_adapter
=> :async

### Actual behavior
When require is commented:
<pre>
Loading development environment (Rails 5.2.3)
[1] pry(main)> Rails.application.config.active_job.queue_adapter
NoMethodError: undefined method `active_job' for #<Rails::Application::Configuration:0x0000000115f6ecd8>
from /Users/kivanio/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/railtie/configuration.rb:97:in `method_missing'
</pre>

### System configuration
**Rails version**:
5.2.3

**Ruby version**:
2.5.1

### PR DESCRIPTION
**Pull request by jlw**
### Summary

This fixes https://github.com/rails/rails/issues/35782.

https://github.com/rails/rails/pull/34953 introduced a change to process engine's seed files with ActiveJob. However, ActiveJob has always been an optional framework, and this change (released in Rails 5.2.3) breaks `rake db:seed` (and `rake db:setup` frequently used in CI/CD) for any apps that are not loading ActiveJob.

This change should allow for engine seeding to continue with ActiveJob when available, and without ActiveJob when not available.

### Other Information

This change should be applied to any future Rails 5.2 bug fix releases as well as Rails 6.x, but I'm not sure of the best way to go about that.

### CODE REVIEW

File: railties/test/railties/engine_test.rb [hunk 1]
```diff
@@ -1511,21 +1537,25 @@ def app
     end
 
     # Restrict frameworks to load in order to avoid engine frameworks affect tests.
-    def restrict_frameworks
+    def restrict_frameworks(remove: [])
```
Comment (jlw) [inline railties/test/railties/engine_test.rb]: _I started with the assumption that removing ActiveJob during the "boot" process would be the appropriate approach, but it was not enough as I noted on lines 906-908. As such, it's possible this part of the change is no longer necessary._

Comment (gmcgibbon) [reply railties/test/railties/engine_test.rb]: This might be tricky because we boot rails per test. If we can't emulate the `NoMethodError` we could try mocking it instead.

**Comment by bjeanes** [comment]
I think #35905 supersedes this, and is already merged.

**Comment by jlw** [comment]
@bjeanes - #35905 is already merged, but it still expects ActiveJob to be loaded and will still throw an exception otherwise.

**Comment by bjeanes** [comment]
Ah yes, I see now.

File: railties/lib/rails/engine.rb [hunk 2]
```diff
@@ -552,7 +552,7 @@ def load_seed
       seed_file = paths["db/seeds.rb"].existent.first
       return unless seed_file
 
-      if config.active_job.queue_adapter == :async
+      if config.try(:active_job).try(:queue_adapter) == :async
```
[the remark this answers is not in the document]
Comment (jlw) [reply railties/lib/rails/engine.rb]: @gmcgibbon - I tried `&.` first, but it is less forgiving than `try` and threw exceptions (at least in my imperfect test scenario).

File: railties/test/railties/engine_test.rb (hunk 1 above)
Comment (jlw) [reply railties/test/railties/engine_test.rb]: @gmcgibbon - I'm not super familiar with minitest anymore, and it looks like stubbing this out correctly is just not possible without bringing in another test double library, which doesn't makes sense. (I don't want to get into an argument about libraries, but in RSpec stubbing this out without affecting the rest of `config` would be straightforward.)

Comment (gmcgibbon) [reply railties/test/railties/engine_test.rb]: 😄 Yes, rspec is much better at stubbing/mocking than minitest, I agree. Thinking further I think you can just forgo mocking and do this:

```
test "seed data can be loaded when ActiveJob is not present" do
  @plugin.write "db/seeds.rb", <<-RUBY
    Bukkits::Engine.config.bukkits_seeds_loaded = true
  RUBY

  app_file "db/seeds.rb", <<-RUBY
    Rails.application.config.app_seeds_loaded = true
  RUBY

  boot_rails

  # In a real app, active_job would be undefined
  undefine_config_option(:active_job)

  Rails.application.load_seed
  assert Rails.application.config.app_seeds_loaded
  Bukkits::Engine.load_seed
  assert Bukkits::Engine.config.bukkits_seeds_loaded
end

private

  def undefine_config_option(name)
    Rails.application.config.class.class_variable_get(:@@options).delete(name)
  end
```

Comment (jlw) [reply railties/test/railties/engine_test.rb]: @gmcgibbon - that's great! I've added both of your suggestions, and will squash the commits and force push my branch after this is approved.

**Comment by jlw** [comment]
@gmcgibbon, could you review this again for me?

Is there anything special to be done to help ensure that this fix is included in any future Rails 5.2.x release?

**Review by gmcgibbon — APPROVED** [review]
👍 Tested this locally and seeding now runs without Active Job. Please squash your commits. I believe since this is a fix for a released bug, we also need a changelog to railties too. We should be able to backport your commit to `5-2-stable` and release from there, no need to do anything extra.

**Comment by jlw** [comment]
@gmcgibbon - I've rebased from the latest (at least for the moment) master and amended my commit with a changelog entry.

**Comment by rafaelfranca** [comment]
@gmcgibbon did you backport this PR to 5-2-stable?

**Comment by gmcgibbon** [comment]
Sorry for the delay, backported in a6bf032b7c31c430b16c1e22fdb4f97f67241656

**Comment by micdijkstra** [comment]
Is this change going to be included in a patch release?

**Comment by rafaelfranca** [comment]
Yes. Next 5.2.x
