### PR TITLE
Fix `ActiveSupport::TimeWithZone#localtime`

### LINKED ISSUE #26644: A bug around ActiveSupport.to_time_preserves_timezone
### Steps to reproduce

I swear that I tried to create a single file script to reproduce the issue, but I couldn't.
Here is the instruction [as well as a repo with complete app with a failing test](https://github.com/kirs/rails_to_time_preserves_timezone_bug).

1. `bundle exec railties/exe/rails new ../events_blog_five --dev --skip-turbolinks --skip-action-cable --skip-sprockets`
2. `rails g model event happened_at:datetime `
3. Apply the diff:

```diff
diff --git a/config/application.rb b/config/application.rb
index 8ce1279..f67478a 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -21,5 +21,6 @@ module EventsBlogFive
     # Settings in config/environments/* take precedence over those specified here.
     # Application configuration should go into files in config/initializers
     # -- all .rb files in that directory are automatically loaded.
+    config.time_zone = "Eastern Time (US & Canada)"
   end
 end
diff --git a/config/initializers/new_framework_defaults.rb b/config/initializers/new_framework_defaults.rb
index 0b910f7..a2a9f60 100644
--- a/config/initializers/new_framework_defaults.rb
+++ b/config/initializers/new_framework_defaults.rb
@@ -12,7 +12,8 @@ Rails.application.config.action_controller.forgery_protection_origin_check = tru
 
 # Make Ruby 2.4 preserve the timezone of the receiver when calling `to_time`.
 # Previous versions had false.
-ActiveSupport.to_time_preserves_timezone = true
+# Disable for reproducing purposes
+# ActiveSupport.to_time_preserves_timezone = true
 
 # Require `belongs_to` associations by default. Previous versions had false.
 Rails.application.config.active_record.belongs_to_required_by_default = true
diff --git a/test/fixtures/events.yml b/test/fixtures/events.yml
new file mode 100644
index 0000000..5b96641
--- /dev/null
+++ b/test/fixtures/events.yml
@@ -0,0 +1,4 @@
+one:
+  happened_at: 2016-05-02 11:00:00
+two:
+  happened_at: 2016-05-02 11:00:00
diff --git a/test/models/event_test.rb b/test/models/event_test.rb
new file mode 100644
index 0000000..457a410
--- /dev/null
+++ b/test/models/event_test.rb
@@ -0,0 +1,8 @@
+require 'test_helper'
+
+class EventTest < ActiveSupport::TestCase
+  test "tz" do
+    times = Event.all.map(&:happened_at).sort.map { |n| n.to_s(:long) }
+    assert_equal ["May 02, 2016 07:00", "May 02, 2016 07:00"], times
+  end
+end
```

4. Run the test with `TZ=UTC rails test test/models/event_test.rb`. Output:

```ruby
Failure:
EventTest#test_tz [/Users/kir/Projects/opensource/events_blog_five/test/models/event_test.rb:6]:
--- expected
+++ actual
@@ -1 +1 @@
-["May 02, 2016 07:00", "May 02, 2016 07:00"]
+["May 02, 2016 07:00", "May 02, 2016 11:00"]
```

### Expected behavior

That the `happened_at` values will be equal, as described in fixtures.

### Actual behavior

Second value is mutated: `["May 02, 2016 07:00", "May 02, 2016 11:00"]`

### System configuration
**Rails version**: today's master (`21ecf42730de2004a95d913038c1f417c24496be`)

**Ruby version**: `ruby 2.3.1p112`

this is probably related to https://github.com/rails/rails/commit/c9c5788a527b70d7f983e2b4b47e3afd863d9f48
cc @pixeltrix

### PR DESCRIPTION
**Pull request by tbalthazar**
### Summary

Fix `ActiveSupport::TimeWithZone#localtime` when called with different `utc_offset` values.

Previously memoization in `localtime` wasn't taking the `utc_offset` parameter into account when returning a cached value. It now caches the computed value depending on the `utc_offset` parameter, e.g:

``` ruby
Time.zone = "US/Eastern"

t = Time.zone.local(2016,5,2,11)
# => Mon, 02 May 2016 11:00:00 EDT -04:00

t.localtime(-7200)
# => 2016-05-02 13:00:00 -0200

t.localtime(-3600)
# => 2016-05-02 14:00:00 -0100
```

Fixes #26644.

### CODE REVIEW

**Comment by pixeltrix** [comment]
@tbalthazar thanks! 👍

**Comment by pixeltrix** [comment]
Backported to 5-0-stable in f7e9f1a - the fix I made for 4-2-stable to address the original performance issue isn't affected because it just caches `to_time` which doesn't take a utc_offset.

File: activesupport/test/core_ext/time_with_zone_test.rb [hunk 1]
```diff
@@ -54,6 +54,12 @@ def test_localtime
     assert_instance_of Time, @dt_twz.localtime
   end
 
+  def test_localtime_with_offset
+    assert_equal 0, @twz.localtime.gmt_offset
```
Comment (matthewd) [inline activesupport/test/core_ext/time_with_zone_test.rb]: @pixeltrix  this isn't passing for me

```
  1) Failure:
TimeWithZoneTest#test_localtime_with_offset [test/core_ext/time_with_zone_test.rb:58]:
Expected: 0
  Actual: 37800
```

Comment (pixeltrix) [inline activesupport/test/core_ext/time_with_zone_test.rb]: The build was green - hmm. What timezone are you in?
