### PR TITLE
Preload Selenium driver_path before parallelizing system tests

### LINKED ISSUE #49906: Race condition with parallel system tests: Text file busy - chromedriver
When running system tests in parallel using `parallelize(workers: :number_of_processors)`, there is a race condition due to the chromedriver executable to being downloaded simultaneously by multiple worker processes. The following error occurs:

```
Text file busy - /home/circleci/.cache/selenium/chromedriver/linux64/116.0.5845.96/chromedriver
```

This race condition was previously reported in #36288 and subsequently addressed in #36592. At the time, the fix was to "preload" the Selenium driver path by calling `driver_path.try(:call)`. That fix was specific to how the `webdrivers` gem worked. The `webdrivers` gem assigned a Proc to `driver_path`, which could then be lazily invoked.

That fix is no longer effective, because starting in Rails 7.1, Rails apps no longer ship with the `webdrivers` gem (see #48847). Instead, the `selenum-webdriver` gem itself now contains a "Selenium Manager" private internal implementation that installs drivers on demand. This new implementation is susceptible to a race condition when used with Rails parallel testing.

In short, the "preload" fix in #36592 works when the `webdrivers` gem is used, but a different solution is needed when `webdrivers` is not being used.

### Steps to reproduce

1. Use a Rails 7.1.1 app
2. Ensure that `selenium-webdriver` is in the Gemfile
3. Ensure that `webdrivers` is **not** in the Gemfile
4. Configure `ApplicationSystemTestCase` with `driven_by :selenium, using: :chrome`
5. Run a large suite of system tests in parallel. I am using `parallelize(workers: 16)` on a CircleCI Docker/Medium instance.

(Apologies, I don't have a standalone script or repo that can be used to reproduce.)

### Expected behavior

Tests should run without errors.

### Actual behavior

Sporadic failures with the following error:

```
Text file busy - /home/circleci/.cache/selenium/chromedriver/linux64/116.0.5845.96/chromedriver
```

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by mattbrictson**
### Motivation / Background

When the `webdrivers` gem is not present (which is the default scenario in Rails 7.1+), the Selenium `driver_path` starts out as `nil`. This means the driver is located lazily, and deferred until a system test is run.

If parallel testing is used, this leads to a race condition, where each worker process tries to resolve the driver simultaneously. The result is an error as described in #49906.

### Detail

This commit fixes the race condition by changing the implementation of `Browser#preload`. The previous implementation worked when `driver_path` was set to a Proc by the `webdrivers` gem, but doesn't work when the `webdrivers` gem is not being used and the `driver_path` is `nil`.

If the `driver_path` is `nil`, `Browser#preload` will now use the `DriverFinder` utility provided by the `selenium-webdriver` gem to eagerly resolve the driver path. This ensures that `driver_path` is set before parallel test workers are forked.

Fixes #49906.

### Additional information

This solution mimics the code within Selenium that determines the driver executable on demand:

```
service.executable_path ||= WebDriver::DriverFinder.path(options, service.class)
```

https://github.com/SeleniumHQ/selenium/blob/7680b7cf25579217cb62a0893c4b2b69c0186062/rb/lib/selenium/webdriver/common/local_driver.rb#L41

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: actionpack/lib/action_dispatch/system_testing/browser.rb [hunk 1]
```diff
@@ -70,6 +69,15 @@ def set_headless_firefox_browser_options
...
           end
         end
+
+        def resolve_driver_path(namespace)
+          service = namespace::Service
+          service.driver_path ||= ::Selenium::WebDriver::DriverFinder.path(
+            options || namespace::Options.new,
+            service
+          )
+          service.driver_path.try(:call)
```
Comment (jonathanhefner) [inline actionpack/lib/action_dispatch/system_testing/browser.rb:79]: Looking at the source code for `DriverFinder.path` [in `selenium-webdriver` 4.11](https://github.com/SeleniumHQ/selenium/blob/selenium-4.11.0/rb/lib/selenium/webdriver/common/driver_finder.rb#L23-L25) (for Ruby >= 3) and [in `selenium-webdriver` 4.9](https://github.com/SeleniumHQ/selenium/blob/selenium-4.9.0/rb/lib/selenium/webdriver/common/driver_finder.rb#L23-L25) (for Ruby < 3), I think we can simply set `driver_path` to its return value.

`DriverFinder.path` will use `Service.driver_path` if present, eliminating the need for `||=`.  It will also evaluate the `Proc` if necessary, eliminating the need for `service.driver_path.try(:call)`.

```suggestion
          namespace::Service.driver_path = ::Selenium::WebDriver::DriverFinder.path(
            options || namespace::Options.new,
            namespace::Service
          )
```

What do you think?

File: actionpack/test/dispatch/system_testing/driver_test.rb [hunk 2]
```diff
@@ -148,7 +148,7 @@ class DriverTest < ActiveSupport::TestCase
     end
   end
 
-  test "preloads browser's driver_path" do
+  test "preloads browser's driver_path if it is set to a Proc" do
```
Comment (jonathanhefner) [inline actionpack/test/dispatch/system_testing/driver_test.rb:151]: If we drop `service.driver_path.try(:call)`, I think we can drop this test too, because Rails would no longer be responsible for this behavior.

Thought it might be worth adding a test for when `driver_path` is set to an actual path (to verify that it is not overwritten).

File: actionpack/test/dispatch/system_testing/driver_test.rb [hunk 3]
```diff
@@ -161,6 +161,21 @@ class DriverTest < ActiveSupport::TestCase
...
 
+  test "preloads browser's driver_path with DriverFinder if a path isn't already specified" do
+    original_driver_path = ::Selenium::WebDriver::Chrome::Service.driver_path
+    ::Selenium::WebDriver::Chrome::Service.driver_path = nil
+
+    # Our stub must return a path to a real executable, otherwise an internal Selenium assertion will fail.
+    found_executable = RbConfig.ruby
+    ::Selenium::WebDriver::DriverFinder.stub(:path, found_executable) do
+      ActionDispatch::SystemTesting::Driver.new(:selenium, screen_size: [1400, 1400], using: :chrome)
+    end
```
Comment (jonathanhefner) [inline actionpack/test/dispatch/system_testing/driver_test.rb:172]: I'm hesitant to stub `DriverFinder.path` since we're relying on it directly.  Does this test blow up if we don't stub?  Perhaps it would be slightly better to stub `SeleniumManager.driver_path`, which `DriverFinder.path` calls?

Comment (mattbrictson) [reply actionpack/test/dispatch/system_testing/driver_test.rb:172]: I used a stub to avoid a network call to download chromedriver, which would slow down the test and perhaps make it less reliable. However I agree that the test is more realistic and valuable without the stub. I'll remove it.

File: actionpack/lib/action_dispatch/system_testing/browser.rb (hunk 1 above)
Comment (mattbrictson) [reply actionpack/lib/action_dispatch/system_testing/browser.rb:79]: Great suggestion. Thanks!

File: actionpack/test/dispatch/system_testing/driver_test.rb (hunk 2 above)
Comment (mattbrictson) [reply actionpack/test/dispatch/system_testing/driver_test.rb:151]: Agreed. I'll drop the Proc test and add another test to verify an existing value is not overwritten.

Comment (mattbrictson) [reply actionpack/test/dispatch/system_testing/driver_test.rb]: Addressed in 916efae770 and 868599937a

File: actionpack/test/dispatch/system_testing/driver_test.rb (hunk 3 above)
Comment (mattbrictson) [reply actionpack/test/dispatch/system_testing/driver_test.rb]: Addressed in be39f0c695

**Comment by mattbrictson** [comment]
@jonathanhefner I've addressed your review comments and squashed down to 1 commit.

File: actionpack/test/dispatch/system_testing/driver_test.rb (hunk 3 above)
Comment (jonathanhefner) [reply actionpack/test/dispatch/system_testing/driver_test.rb]: > to avoid a network call to download chromedriver

Ah, right, in that case we _should_ stub.  (Sorry! :pray:)  But I think stubbing `SeleniumManager.driver_path` might be a better choice because if the behavior of `DriverFinder.path` changes, then we will be more likely to catch it.

Comment (mattbrictson) [reply actionpack/test/dispatch/system_testing/driver_test.rb]: OK, addressed in 3f089b3aa1 ✅

**Comment by mattbrictson** [comment]
@jonathanhefner thanks for your feedback and your patience. This is ready for another review.

**Comment by jonathanhefner** [comment]
Looks good!  Though I pushed a commit to change `With help from @jonathanhefner` in the commit message.  When you put someone's GitHub username in a commit message, GitHub notifies them every time that commit message is pushed, e.g. when rebasing, cherry picking, etc.  And there's no way to disable those notifications.  (It is a major failing on GitHub's part.)  So if you want to credit a co-author, you can [add `Co-authored-by: Name <email@example.com>` to the end of the commit message](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-the-command-line).  An easy way to get the appropriate name / email is to visit a PR or commit on GitHub that the person has authored and append ".patch" to the URL.  For example, https://github.com/rails/rails/pull/49908.patch shows `Matt Brictson <matt@mattbrictson.com>`.

Thank you, @mattbrictson! :racing_car:

**Comment by lazyatom** [comment]
I _think_ this might break system tests where the Chrome binary is not in the default path, e.g. where `selenium-webdriver` has downloaded a version of "Chrome for Testing" into a local cache. I'm investigating more and will report back when I have something concrete.

**Comment by lazyatom** [comment]
OK, here's what I think is happening. Deep in `selenium-webdriver`, the call to `Selenium::WebDriver::SeleniumManager.driver_path` has a _side-effect_ of setting `binary` in the `option` Hash it has been passed as an argument. This Hash is eventually used to determine the "capabilities" to send to `chromedriver`, in particular the `capabilities["goog:chromeOptions"]["binary"]` value, which tells chromedriver to launch _that_ binary instead of whatever's available in `PATH`.

With this change, we are setting `Selenium::WebDriver::Chrome::Driver.driver_path` in advance, which then _prevents_ us from calling `SeleniumManager.driver_path(options)` later, resulting in the binary never being sent to `chromedriver` as part of the capabilities hash.

Is this a bug in Rails? Or an issue with `selenium-webdriver` relying on this _side-effect_ to populate the binary option? Who is to say.

**Comment by jonathanhefner** [comment]
@lazyatom Thank you for investigating, but I'm not sure I follow.  Why does `SeleniumManager.driver_path` produce a different result later?  Could you provide a reproduction script or an example test setup?

**Comment by lazyatom** [comment]
@jonathanhefner thanks for replying. I've created a new issue (#50287) with a replication script and a hopefully-clearer description/explanation. The only thing I can't achieve with the script is making sure that you don't already have Chrome installed -- that's key to demonstrating this issue.

**Comment by majkelcc** [comment]
Hi @mattbrictson, it looks like the `resolve_driver_path` method is always trying to look for a local binary, which breaks containerized setups using remote browsers. Can you confirm it was missed, should I create a bug report? Everything was working fine in Rails 7.1.1.

Code example that's failing:
```
class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  driven_by :selenium,
    using: :headless_chrome,
    options: {
      url: "http://chrome:4444",
      browser: :remote
    }
  end
end
```

With this `::Selenium::WebDriver::DriverFinder.path` inside `resolve_driver_path` is downloading a local binary after not finding one.

**Comment by mattbrictson** [comment]
@majkelcc that sounds like it should be a new bug report.

I am not verify familiar with how remote browsers work with Selenium, but apparently Rails does not consult `options[:browser]` when preloading. As you can see in the following code, only `:using` is considered, and other options (like `browser: :remote`) are ignored.

https://github.com/rails/rails/blob/1eda300a21c997c2dd2f4c20a3ed09336dd83ad5/actionpack/lib/action_dispatch/system_testing/driver.rb#L18-L19

I suspect Rails 7.1.1 was working for you because prior to 7.1.2, the `preload` mechanism only worked if `driver_path` was set to a Proc, which was being done by the `webdrivers` gem. So if you used 7.1.1 without `webdrivers`, essentially `preload` was a no-op. In 7.1.2 (i.e. as a result of this PR), the preload mechanism now calls `Selenium::WebDriver::DriverFinder` explicitly, hence the local download that you are seeing.
