### PR TITLE
Added fixed links to code for Rails Guides ActiveSupport

### LINKED ISSUE #29055: Broken links in Rails Guides ActiveSupport
It looks like currently the [Rails Guides ActiveSupport](http://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support) page has broken links which are supposed to link to the methods used in the various examples.

Ex. http://guides.rubyonrails.org/active_support_core_extensions.html#blank-questionmark-and-present-questionmark The link to `active_support/core_ext/object/blank.rb.` returns a 404 from Github.

My understanding is that it's supposed to link to the ActiveSupport codebase with that method. 

Unless anyone has objections. I'll submit a PR for this in the coming hours.

### PR DESCRIPTION
**Pull request by juliusdelta**
# Fixed #29055 
       
The links in the [Rails Guide for ActiveSupport](http://guides.rubyonrails.org/active_support_core_extensions.html) were fixed to actually lead to the codebase as they were originally linking to a 404 Github page.

Most were like this
```markdown
`active_support/core_ext/object/blank.rb.`
```
and they were changed to 
```markdown
[`active_support/core_ext/object/blank.rb.`](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/object/blank.rb)

### CODE REVIEW

**Comment by robin850** [comment]
Hello @juliusdelta,

Congratulations on sending your first patch to Ruby on Rails ! ❤️ 

Actually, these links are automatically generated by [this method](https://github.com/rails/rails/blob/b30760a4846d04bc48c787c95013208950906f5e/guides/rails_guides/markdown/renderer.rb#L93-L108) so hard-coding the URL isn't a solution as we want to dynamically inject the current version.

Could you please update your patch to update [this line](https://github.com/rails/rails/blob/b30760a4846d04bc48c787c95013208950906f5e/guides/rails_guides/markdown/renderer.rb#L96) to be this instead:

~~~ruby
root = file_path[%r{(\w+)/}, 1]
~~~

The problem is that the regular expression will catch too much chars from the file path while we only want to take the chars before the first `/` char. Could you also explain that in your commit message ? That would be really awesome !

For future references, this issue has been introduced in https://github.com/rails/rails/commit/771a802c374ebe7b2931ba6cf8ffa3b7bf0e92e0.

**Comment by juliusdelta** [comment]
@robin850 Thanks! I can definitely do that. I'll push an updated commit later this afternoon with that change.

**Comment by juliusdelta** [comment]
@robin850 Done.

File: guides/rails_guides/markdown/renderer.rb [hunk 1]
```diff
@@ -93,16 +93,15 @@ def convert_notes(body)
...
-            case root
-            when "abstract_controller", "action_controller", "action_dispatch"
-              "actionpack/lib/#{file_path}"
-            when /\A(action|active)_/
-              "#{root.sub("_", "")}/lib/#{file_path}"
-            else
-              file_path
-            end
+          root = file_path[%r{(\w+)/}, 1]
+          path = case root
```
Comment (robin850) [inline guides/rails_guides/markdown/renderer.rb]: Could you remove this change please ? Actually the previous style is the preferred one.

**Comment by robin850** [comment]
Thanks @juliusdelta ! Once the above comment is addressed, could you add `[ci skip]` at the very end of the commit message and remove the merge commit please ? If you need help with the latter, feel free to ask me.

**Comment by juliusdelta** [comment]
Ahh forgot the [ci skip]. 😅 mybad.

**Comment by robin850** [comment]
@juliusdelta: No problem, awesome ! I will let @matthewd merge that !

**Comment by pixeltrix** [comment]
Thanks @juliusdelta 👍

**Comment by perlun** [comment]
Old PR, but this issue has now reappeared in a different form...

[This page](http://guides.rubyonrails.org/active_support_core_extensions.html) has links being generated that looks like this: https://github.com/rails/rails/tree/v5.1.2/activesupport/core_ext/object/lib/active_support/core_ext/object/blank.rb

But the correct URL is now https://github.com/rails/rails/blob/v5.1.2/activesupport/lib/active_support/core_ext/object/blank.rb (note how the folder structure has been rearranged).

@robin850 do you want me to file a separate issue about this? I don't know where the fix should go; I looked briefly at https://github.com/rails/rails/blob/master/guides/rails_guides/markdown/renderer.rb but it's not obvious how the URL is trickled together.

**Comment by robin850** [comment]
@perlun : Thanks for reporting this but actually that's because this pull request hasn't been back-ported to the 5-1-stable branch and guides are tied to a release of Rails so if the generation is fixed, it doesn't mean that the guides are fixed as well. If you look on [edge guides](http://edgeguides.rubyonrails.org/active_support_core_extensions.html), everything seems to work fine.

@pixeltrix : Could you back-port this to 5-1-stable please ? :-)

**Comment by rafaelfranca** [comment]
@robin850 just did
