### PR TITLE
[ActiveStorage] Take `ActiveRecord` affixes into account for `ActiveStorage` database models

### LINKED ISSUE #35811: Active Storage models ignore table_name_prefix
### Steps to reproduce
1. `rails new astest`
2. `cd astest/`
3. Edit `config/application.rb` and add set a general table prefix with `config.active_record.table_name_prefix = 'abc_'`
4. Create ActiveStorage models `bundle exec rake active_storage:install db:migrate`

Observe: tables are created with prefix (`abc_active_storage_attachements` and `*_blobs`).

5. Create a user model via `bundle exec rails generate model User name:string` and attach an avatar to it
```
class User < ApplicationRecord
  has_one_attached :avatar
end
```
6. Add an Avatar via console
```
2.6.1 :002 > u.avatar.attach(io: File.open(Rails.root.join('public', 'apple-touch-icon.png')))
Traceback (most recent call last):
        1: from (irb):2
ActiveRecord::StatementInvalid (Could not find table 'active_storage_attachments')
```

Observe: ActiveRecord cannot find its table.

### Expected behavior
ActiveStorage::Attachment should use the prefixed table name the migration created previously.

### Actual behavior
ActiveStorage::Attachment cannot find its table as it looks for the non-prefixed table name.

Which is hardcoded in ActiveStorage::Attachment [here](https://github.com/rails/rails/blob/d2542882b20f6205e1c40ab34ff075eefc2d589c/activestorage/app/models/active_storage/attachment.rb#L9) and in ActiveStorage::Blob [here](https://github.com/rails/rails/blob/d2542882b20f6205e1c40ab34ff075eefc2d589c/activestorage/app/models/active_storage/blob.rb#L27)

### System configuration
**Rails version**: 5.2.3
**Ruby version**: 2.6.1

### PR DESCRIPTION
**Pull request by chaadow**
EDIT: Partially Fixes #35811 ( Only AR suffix will work, prefix is a global engine issue that will be handled in a separate PR
Follow up to the closed PR #35828 

Follow up to https://github.com/rails/rails/pull/30095

### Motivation / Background

This Pull Request has been created because ActiveStorage db model table names are hardcoded. Making it impossible to be compatible with ActiveRecord prefix/suffix configuration.

What's also problematic is that AS generated migrations ( with `activestorage:install` task ) respects the prefix/suffix configuration, which makes it then impossible to use AS models in a Rails application.

### Detail

To fix this issue we remove the hard coded lines. But then we need to also override an internal method for specifying the prefix. the full explanation is here: https://github.com/rails/rails/pull/50167#discussion_r1405175059

### Additional information

Some tests were refactored to remove hard coded table name references, making ActiveStorage test suite compatible with ActiveRecord config.

https://github.com/rails/rails/blob/354d68e8a63b21e47a529105a508411bfe8be869/activerecord/lib/active_record/model_schema.rb#L597-L611

- **I believe the root cause lies inside ActiveRecord model schema file** but I can't find the solution... for now ( **EDIT: solution found here: https://github.com/rails/rails/pull/50167#discussion_r1405175059 )** 
- This issue is also present in action_text, but I want to focus for now on activestorage and make sure it works properly before porting it

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activestorage/test/models/record_test.rb [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+class ActiveStorage::RecordTest < ActiveSupport::TestCase
+  setup do
+    @old_prefix = ActiveRecord::Base.table_name_prefix
+    @old_suffix = ActiveRecord::Base.table_name_suffix
+
+    ActiveRecord::Base.table_name_prefix = @prefix = "prefix_"
+    ActiveRecord::Base.table_name_suffix = @suffix = "_suffix"
+
+    @descendants = ActiveStorage::Record.descendants
+    @descendants.map(&:reset_table_name)
```
Comment (chaadow) [inline activestorage/test/models/record_test.rb:15]: calling `reset_table_name` is necessary for affixes to be taken into consideration

File: activestorage/test/migrations_test.rb [hunk 2]
```diff
@@ -53,7 +53,7 @@ def rerun_migration
     end
 
     def active_storage_tables
-      [:active_storage_blobs, :active_storage_attachments, :active_storage_variant_records]
+      @active_storage_tables ||= ActiveStorage::Record.descendants.map { |klass| klass.table_name.to_sym }
```
Comment (chaadow) [inline activestorage/test/migrations_test.rb:56]: this follows the logic that table names should not be hard coded

File: activestorage/app/models/active_storage/record.rb [hunk 3]
```diff
@@ -2,6 +2,10 @@
 
 class ActiveStorage::Record < ActiveRecord::Base # :nodoc:
   self.abstract_class = true
+
+  def self.full_table_name_prefix
+    table_name_prefix + super
```
Comment (chaadow) [inline activestorage/app/models/active_storage/record.rb:7]: I had to add this here, but I believe this is a global rails/ActiveRecord issue, for any application that wans to have "Base classes" that respects ActiveRecord prefixes

I believe this should be investigated in another PR. for now this changes fixes the issue **and is not breaking for existing applications**

Comment (chaadow) [reply activestorage/app/models/active_storage/record.rb:7]: I believe since ActiveStorage is an engine, `ActiveStorage.table_name_prefix` is set
image

which makes
```ruby
def full_table_name_prefix # :nodoc:
 (module_parents.detect { |p| p.respond_to?(:table_name_prefix) } || self).table_name_prefix
end
```

returns only `active_storage_` and discarding completely ActiveRecord prefix config

and for Suffix
```ruby
def full_table_name_suffix # :nodoc:
(module_parents.detect { |p| p.respond_to?(:table_name_suffix) } || self).table_name_suffix
end
```

the `detect` call will be nil, hence relying on `self` and since `self` is the AS model, then it will be `ActiveStorage::Blob.table_name_suffix` 

==> I believe we fully understand what's happening now.

Comment (chaadow) [reply activestorage/app/models/active_storage/record.rb:7]: I think that this is a global issue for Engines issue that use `isolate_namespace`

**Comment by chaadow** [comment]
Hi @prathamesh-sonpatki do you mind taking a look please? 🙏🏼

**Comment by jonathanhefner** [comment]
As you mentioned, this seems to affect all engines that use `isolate_namespace`.  Here is a reproduction script of #35811 for an arbitrary engine:

<details>
  <summary>Reproduction script</summary>
  
  ```ruby
  # frozen_string_literal: true

  require "bundler/inline"

  gemfile(true) do
    source "https://rubygems.org"

    git_source(:github) { |repo| "https://github.com/#{repo}.git" }

    gem "rails", github: "rails/rails", branch: "main"
    gem "sqlite3"
  end

  require "rails/all"

  module TestEngine
    class Engine < Rails::Engine
      isolate_namespace TestEngine
    end

    class Record < ActiveRecord::Base
    end
  end

  class TestApp < Rails::Application
    config.load_defaults Rails::VERSION::STRING.to_f

    config.root = __dir__
    config.hosts << "example.org"
    config.eager_load = false
    config.session_store :cookie_store, key: "cookie_store_key"
    config.secret_key_base = "secret_key_base"

    config.logger = Logger.new($stdout)
    Rails.logger  = config.logger

    config.active_record.table_name_prefix = "abc_"
    config.active_record.table_name_suffix = "_xyz"
  end

  ENV["DATABASE_URL"] = "sqlite3::memory:"

  Rails.application.initialize!

  ActiveRecord::Schema.define do
    create_table :test_engine_records do |t|
      t.string :value
    end
  end

  require "minitest/autorun"

  class EngineTest < Minitest::Test
    def test_record_table_name
      assert_equal "abc_test_engine_records_xyz", TestEngine::Record.table_name
    end

    def test_record
      TestEngine::Record.create!(value: "foo")
      assert_equal "foo", TestEngine::Record.first.value
    end
  end
  ```
</details>

Output:

  ```
  Failure:
  EngineTest#test_record_table_name:
  Expected: "abc_test_engine_records_xyz"
    Actual: "test_engine_records_xyz"

  Error:
  EngineTest#test_record:
  ActiveRecord::StatementInvalid: Could not find table 'test_engine_records_xyz'
  ```

There are two important observations:

1. `config.active_record.table_name_suffix` __does__ work.  That implies `config.active_record.table_name_prefix` should also work.  (If neither worked, there would be more of an argument for "that's just the way it is.")

2. Basic Active Record operations __do not__ work at all for engine namespaced models when `config.active_record.table_name_prefix` is set.  This is really important because it means that fixing `table_name_prefix` for engines won't break apps that rely on the existing behavior (because those apps couldn't have worked in the first place).

So, I think it would be better to fix the root cause and address this issue for all engines that use `isolate_namespace`.

**Comment by chaadow** [comment]
@jonathanhefner Thank you for the reproduction script and for the review!

I have a suggestion, if you don't mind, can I just keep the fix regarding the hardcoded table names ( which are redundant since they're already covered by `isolate_namespace` and non breaking)

And I remove this part and the tests related to it
```ruby
  def self.full_table_name_prefix
    table_name_prefix.to_s + super
  end
```

Then I can try to fix this global issue for all engines in another PR using your reproduction script?🙏🏼 

If it's ok with you, I will first create an issue and use the reproduction script in the description, then I can work on a fix.

**Comment by jonathanhefner** [comment]
> can I just keep the fix regarding the hardcoded table names ( which are redundant since they're already covered by `isolate_namespace` and non breaking)

It looks like `isolate_namespace` was added later in #30095, which is why the table names were originally hard-coded.  So, as a follow-up to #30095, removing them seems fine.

> If it's ok with you, I will first create an issue and use the reproduction script in the description, then I can work on a fix.

Sounds good. :+1:

File: activestorage/CHANGELOG.md [hunk 4]
```diff
@@ -1,3 +1,10 @@
+*   Remove hard coded table names for all ActiveStorage database models.
+    This will allow for AS models to respect ActiveRecord suffix configuration.
+    However it will not work for AR prefix because of a global issue with Engines
+    using `isolate_namespace`.
```
[the remark this answers is not in the document]
Comment (chaadow) [reply activestorage/CHANGELOG.md:4]: > Hmm, I feel like it's out of place to mention the isolate_namespace bug here. What do you think about moving the Active Storage CHANGELOG entry from this PR to https://github.com/rails/rails/pull/50247 instead?
Yes sure!

Also thanks for the explanation, duly noted!

File: activestorage/CHANGELOG.md [hunk 5]
```diff
@@ -1,3 +1,7 @@
+*   Remove hard coded table names for all Active Storage database models.
```
Comment (chaadow) [inline activestorage/CHANGELOG.md:1]: @jonathanhefner  I'm not sure if you want me to remove the entirety of the changelog entry. or only the part about isolate_namespace

Please if so tell and i would remove it entirely. thanks!

Comment (chaadow) [reply activestorage/CHANGELOG.md:1]: Alright let's do this 👍🏼

Comment (chaadow) [reply activestorage/CHANGELOG.md]: I've changed the CHANGELOG following your suggestion.

**Comment by jonathanhefner** [comment]
Thank you, @chaadow! :card_file_box:
