### PR TITLE
Only configure smtp_settings if provided on configuration

### LINKED ISSUE #44161: SMTP Connection Error
### Steps to reproduce
- Upgrade Rails to latest version (7.0.1)
- Upgrade Ruby to 3.1.0
- Ether setup a new Rails app or upgrade an existing one. Configure SMTP settings (Sendgrid, Mailgun, etc...) in ether development or production environment files. 
- Configure Mailer, if needed
- In Rails console, your app or tests, try sending an email using your newly created SMTP settings.

In this case, I'm using Mailgun SMTP

```ruby
config.action_mailer.default_url_options = { host: ENV['CONFIG_HOST']}
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.perform_deliveries = true

  ActionMailer::Base.smtp_settings = {
    user_name: ENV['MAILGUN_SMTP_LOGIN'],
    password:ENV['MAILGUN_SMTP_PASSWORD'],
    address: ENV['MAILGUN_SMTP_SERVER'],
    port: ENV['MAILGUN_SMTP_PORT']
  }
```

### Expected behavior
It should successfully connect to Mailgun. Just for sanity, I tried using Sendgrid and received the same error.

### Actual behavior
Errors
```
Completed 500 Internal Server Error in 421ms (ActiveRecord: 88.7ms | Allocations: 12176)
2022-01-12T21:35:52.958940+00:00 app[web.1]: F, [2022-01-12T14:35:52.958881 #4] FATAL -- : [32dcea9c-8055-4cfe-a179-146744357e61]
2022-01-12T21:35:52.958951+00:00 app[web.1]: [32dcea9c-8055-4cfe-a179-146744357e61] Errno::ECONNREFUSED (Connection refused - connect(2) for 127.0.0.1:25):
```

### System configuration
Rails 7.0.1

**Ruby version**:
Ruby 3.1.0

### PR DESCRIPTION
**Pull request by andrehjr**
### Summary

There's a bug when `ActionMailer::Base.smtp_settings=` is set before ActionMailer gets initialized and `config.action_mailer.smtp_settings` is not set. This ends up overriding ActionMailer::Base.smtp_settings.

Some users may configure ActionMailer::Base.smtp_directly instead of using it via `config.action_mailer.smtp_settings`. 

In order to fix that this PR does not try to configure smtp_settings when it's not present on the config hash.   

Fixes #44161 and Follow up from #44061

### CODE REVIEW

**Review by Edouard-chin — CHANGES_REQUESTED** [review]
Thank you for the Pull Request @andrehjr .  The issue you are describing is a common mistake where users would prematurely reference a constant (such as ActionMailer::Base, ActionController::Base) which messes up the boot process and ultimately result in the problem you were seeing.

Application shouldn't be doing that and should instead use a [Lazy Load hook](https://edgeapi.rubyonrails.org/classes/ActiveSupport/LazyLoadHooks.html). In your example it would look something like

```ruby
ActiveSupport.on_load(:action_mailer) do
  self.smtp_settings = { ... }
end
# This code will be executed once Rails itself uses the ActionMailer::Base constant. 
```

**Comment by andrehjr** [comment]
You're totally right @Edouard-chin. I also advise on using Lazy Load Hooks and avoiding calling those constants prematurely. Thanks for taking a look into this PR.

The issue is that on https://github.com/rails/rails/pull/44061 there is still another behavior missing. Something that used to work on previous Rails versions is not working on Rails 7+ properly. This PR attempts to keep that between versions.

That means fewer surprises when upgrading if someone by mistake was using ActionMailer::Base directly. But, as it's not a good practice, rails may also decide not to fix it.

**Comment by Edouard-chin** [comment]
Ah yeah I understand the nice intention to keep everyone's application working the same way despite the new changes, but IMO this kind of problem will always arise at some and it's better for users to fix the root cause.

Just my 2cents, I'll let the core team decides.

File: actionmailer/lib/action_mailer/railtie.rb [hunk 1]
```diff
@@ -46,9 +45,13 @@ class Railtie < Rails::Railtie # :nodoc:
           self.delivery_job = delivery_job.constantize
         end
 
+        if options.smtp_settings
+          self.smtp_settings = options.smtp_settings
+        end
+
         if smtp_timeout = options.delete(:smtp_timeout)
```
Comment (rafaelfranca) [inline actionmailer/lib/action_mailer/railtie.rb:52]: Isn't this going to raise an exception when `options.smtp_settings` is not present? Should not this be moved to inside that conditional?

Comment (andrehjr) [reply actionmailer/lib/action_mailer/railtie.rb]: It shouldn't fail when `options.smtp_settings` is not present because ActionMailer::Base does have a [default value](https://github.com/rails/rails/blob/main/actionmailer/lib/action_mailer/delivery_methods.rb#L20-L27). 

So if `options.smtp_settings` is nil this code basically adds smtp_timeout for the default smtp_settings from ActionMailer::Base. I've added a test for that.

Although It could raise an error if someone does `ActionMailer::Base.smtp_settings = nil` before Rails loads. So, I addressed that case and added another test to ensure it does not raise.

Comment (rafaelfranca) [reply actionmailer/lib/action_mailer/railtie.rb]: But we are deleting from `options` not `self.smtp_settings`, so the default value doesn't apply.

Comment (rafaelfranca) [reply actionmailer/lib/action_mailer/railtie.rb]: Forget about it. I'm confused.
