### PR TITLE
Fix `automatic_inverse_of` not to be disabled if extension block is given

### LINKED ISSUE #28806: Using an ActiveRecord extension changes the caching behavior of related models
#### Test passes without extension:
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
  gem "pry"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.boolean :needs_moderation, default: false
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.boolean :moderated, default: false
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  validate :comments_compatible

  def comments_compatible
    comments.each do |comment|
      comment.validate_post
    end
  end
end

class Comment < ActiveRecord::Base
  belongs_to :post

  def validate_post
    unless post.needs_moderation == moderated
      post.errors.add(:needs_moderation, :not_all_comments_are_same)
    end
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    comment = post.comments.create
    post.needs_moderation = true

    assert_equal post.valid?, false
  end
end
```

#### Test fails when a block is passed to the `comments` association on `post`:
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
  gem "pry"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.boolean :needs_moderation, default: false
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.boolean :moderated, default: false
  end
end

class Post < ActiveRecord::Base
  has_many :comments do
  end
  validate :comments_compatible

  def comments_compatible
    comments.each do |comment|
      comment.validate_post
    end
  end
end

class Comment < ActiveRecord::Base
  belongs_to :post

  def validate_post
    unless post.needs_moderation == moderated
      post.errors.add(:needs_moderation, :not_all_comments_are_same)
    end
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    comment = post.comments.create
    post.needs_moderation = true

    assert_equal post.valid?, false
  end
end
```

### Expected behavior
No change in the caching behavior when a block is passed to an association.
In the call to `validate_post`, the attributes of `post` should reflect the new assignment.

### Actual behavior
When a block is passed to the association the caching behavior changes.
In the call to `validate_post`, the attributes of `post` are stale and no longer reflect the new assignment of `needs_moderation`.

### System configuration
**Rails version**: 5.2.0.alpha

**Ruby version**: 2.3.3

### PR DESCRIPTION
**Pull request by kamipo**
If an association has a scope, `automatic_inverse_of` is to be disabled.
But extension block is obviously not a scope. It should not be regarded
as a scope.

Fixes #28806.

### CODE REVIEW

File: activerecord/test/cases/associations/eager_load_nested_include_test.rb [hunk 1]
```diff
@@ -107,11 +107,11 @@ def setup
     @first_categorization = @davey_mcdave.categorizations.create(category: Category.first, post: @first_post)
   end
 
-  teardown do
-    @davey_mcdave.destroy
-    @first_post.destroy
+  def teardown
```
Comment (rafaelfranca) [inline activerecord/test/cases/associations/eager_load_nested_include_test.rb]: Is there any reason for this change?

File: activerecord/lib/active_record/associations/builder/collection_association.rb [hunk 2]
```diff
@@ -66,17 +66,5 @@ def #{name.to_s.singularize}_ids=(ids)
         end
       CODE
     end
-
-    def self.wrap_scope(scope, mod)
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/associations/builder/collection_association.rb]: The fact that you removed this and nothing breaks concerns me. This seems like something we need to do otherwise the association scope will not extend the module passed in the `:extend` option. Maybe we are missing test coverage. Can you check if this would make any difference in the public API?

File: activerecord/test/cases/associations/eager_load_nested_include_test.rb (hunk 1 above)
Comment (kamipo) [inline activerecord/test/cases/associations/eager_load_nested_include_test.rb]: Changing destroying order is for preventing counter_cache updates destroyed inverse_of record (destroying `@first_comment` causes updating destroyed `@first_post`).

https://github.com/rails/rails/blob/v5.1.0.rc2/activerecord/test/models/comment.rb#L9
https://github.com/rails/rails/blob/v5.1.0.rc2/activerecord/lib/active_record/associations/belongs_to_association.rb#L50

Changing `teardown do` to `def teardown` is for easing to see stacktrace.

Before:

```
  1) Error:
EagerLoadNestedIncludeWithMissingDataTest#test_missing_data_in_a_nested_include_should_not_cause_errors_when_constructing_objects:
RuntimeError: can't modify frozen Hash
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/attribute_set.rb:54:in `write_from_user'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/attribute_methods/write.rb:56:in `write_attribute_with_type_cast'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/attribute_methods/write.rb:38:in `write_attribute'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/attribute_methods.rb:359:in `[]='
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/persistence.rb:347:in `increment'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/persistence.rb:358:in `increment!'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/associations/belongs_to_association.rb:50:in `update_counters'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/associations/belongs_to_association.rb:38:in `decrement_counters'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/counter_cache.rb:198:in `block in destroy_row'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/counter_cache.rb:209:in `block in each_counter_cached_associations'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/counter_cache.rb:208:in `each'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/counter_cache.rb:208:in `each_counter_cached_associations'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/counter_cache.rb:194:in `destroy_row'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/locking/optimistic.rb:117:in `destroy_row'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/persistence.rb:195:in `destroy'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/callbacks.rb:321:in `block in destroy'
    /Users/kamipo/src/github.com/rails/rails/activesupport/lib/active_support/callbacks.rb:97:in `run_callbacks'
    /Users/kamipo/src/github.com/rails/rails/activesupport/lib/active_support/callbacks.rb:824:in `_run_destroy_callbacks'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/callbacks.rb:321:in `destroy'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:303:in `block in destroy'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
    /Users/kamipo/.rbenv/versions/2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:210:in `transaction'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:303:in `destroy'
    test/cases/associations/eager_load_nested_include_test.rb:113:in `block in <class:EagerLoadNestedIncludeWithMissingDataTest>'
    /Users/kamipo/src/github.com/rails/rails/activesupport/lib/active_support/callbacks.rb:413:in `instance_exec'
    /Users/kamipo/src/github.com/rails/rails/activesupport/lib/active_support/callbacks.rb:413:in `block in make_lambda'
    /Users/kamipo/src/github.com/rails/rails/activesupport/lib/active_support/callbacks.rb:270:in `block in simple'
    /Users/kamipo/src/github.com/rails/rails/activesupport/lib/active_support/callbacks.rb:511:in `block in invoke_after'
    /Users/kamipo/src/github.com/rails/rails/activesupport/lib/active_support/callbacks.rb:511:in `each'
    /Users/kamipo/src/github.com/rails/rails/activesupport/lib/active_support/callbacks.rb:511:in `invoke_after'
    /Users/kamipo/src/github.com/rails/rails/activesupport/lib/active_support/callbacks.rb:132:in `run_callbacks'
    /Users/kamipo/src/github.com/rails/rails/activesupport/lib/active_support/testing/setup_and_teardown.rb:45:in `after_teardown'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/fixtures.rb:875:in `after_teardown'
```

After:

```
  1) Error:
EagerLoadNestedIncludeWithMissingDataTest#test_missing_data_in_a_nested_include_should_not_cause_errors_when_constructing_objects:
RuntimeError: can't modify frozen Hash
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/attribute_set.rb:54:in `write_from_user'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/attribute_methods/write.rb:56:in `write_attribute_with_type_cast'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/attribute_methods/write.rb:38:in `write_attribute'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/attribute_methods.rb:359:in `[]='
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/persistence.rb:347:in `increment'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/persistence.rb:358:in `increment!'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/associations/belongs_to_association.rb:50:in `update_counters'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/associations/belongs_to_association.rb:38:in `decrement_counters'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/counter_cache.rb:198:in `block in destroy_row'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/counter_cache.rb:209:in `block in each_counter_cached_associations'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/counter_cache.rb:208:in `each'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/counter_cache.rb:208:in `each_counter_cached_associations'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/counter_cache.rb:194:in `destroy_row'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/locking/optimistic.rb:117:in `destroy_row'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/persistence.rb:195:in `destroy'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/callbacks.rb:321:in `block in destroy'
    /Users/kamipo/src/github.com/rails/rails/activesupport/lib/active_support/callbacks.rb:97:in `run_callbacks'
    /Users/kamipo/src/github.com/rails/rails/activesupport/lib/active_support/callbacks.rb:824:in `_run_destroy_callbacks'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/callbacks.rb:321:in `destroy'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:303:in `block in destroy'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
    /Users/kamipo/.rbenv/versions/2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:210:in `transaction'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
    /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/transactions.rb:303:in `destroy'
    test/cases/associations/eager_load_nested_include_test.rb:113:in `teardown'
```

File: activerecord/lib/active_record/associations/builder/collection_association.rb (hunk 2 above)
Comment (kamipo) [inline activerecord/lib/active_record/associations/builder/collection_association.rb]: I changed `def has_many(name, scope = nil, options = {}, &extension)` to `def has_many(name, scope = nil, **options, &extension)` to don't mutate passed `options`. And then do `options[:extend] = Array(options[:extend]) + [extension] if extension`.
Is it not enough?

https://github.com/rails/rails/pull/28830/files#diff-a215bfc911ab0913d92695a0f20310efR1395
https://github.com/rails/rails/pull/28830/files#diff-5870816b49b90e43340607bb11ed2514R41

Comment (kamipo) [inline activerecord/lib/active_record/associations/builder/collection_association.rb]: Ah, I understood what you meant. Actually this changes the following result:

```ruby
post_reflection = Post.reflect_on_association(:comments)
p post_reflection.options # => {:extend=>[PostCommentsAssociationExtension]}
```

But `HasManyReflection ` is `:nodoc:` class.
https://github.com/rails/rails/blob/v5.1.0.rc2/activerecord/lib/active_record/reflection.rb#L681

If we should not change the behavior, I'll change this PR to keep the previous behavior.

File: activerecord/test/cases/associations/inverse_associations_test.rb [hunk 3]
```diff
@@ -64,6 +65,15 @@ def test_has_many_and_belongs_to_should_find_inverse_automatically
     assert_equal rating_reflection, comment_reflection.inverse_of, "The Comment reflection's inverse should be the Rating reflection"
   end
 
+  def test_has_many_and_belongs_to_should_find_inverse_automatically_for_extension_block
+    comment_reflection = Comment.reflect_on_association(:post)
+    post_reflection = Post.reflect_on_association(:comments)
+
+    assert_predicate post_reflection, :has_inverse?
+    assert_equal comment_reflection, post_reflection.inverse_of
+    assert_equal({}, post_reflection.options)
```
Comment (kamipo) [inline activerecord/test/cases/associations/inverse_associations_test.rb]: I changed this PR to keep the previous behavior (don't mutate `options[:extend]`) and added a test case.

File: activerecord/lib/active_record/associations/builder/collection_association.rb (hunk 2 above)
Comment (rafaelfranca) [inline activerecord/lib/active_record/associations/builder/collection_association.rb]: What I mean is that now the scope defined by the association is not extending anymore the class since `extending` is not being called in the scope.

Comment (kamipo) [inline activerecord/lib/active_record/associations/builder/collection_association.rb]: I see. This PR changes the`reflection.constraints` result:

Before:

```ruby
Post.reflect_on_association(:comments).constraints
# => [#<Proc:0x007f89c1d5f488@~/lib/active_record/associations/builder/collection_association.rb:78>]
```

After:

```ruby
Post.reflect_on_association(:comments).constraints
# => []
```

But the association is only specified extension block, doesn't be specified a scope. Should `reflection.constraints` return the scope in that case?

https://github.com/rails/rails/blob/v5.1.0.rc2/activerecord/test/models/post.rb#L50

And `HasManyReflection` is `:nodoc:` class. Should we test the `reflection.constraints` result?

File: activerecord/test/cases/associations/has_many_associations_test.rb [hunk 4]
```diff
@@ -2578,22 +2578,22 @@ def test_association_with_rewhere_doesnt_set_inverse_instance_key
...
   test "extend option affects per association" do
     post = posts(:welcome)
-    assert_equal "lifo",  post.comments_with_extend.author
-    assert_equal "lifo",  post.comments_with_extend_2.author
-    assert_equal "hello", post.comments_with_extend.greeting
-    assert_equal "hullo", post.comments_with_extend_2.greeting
+    assert_equal "lifo", post.comments_with_extend.author
+    assert_equal "lifo", post.comments_with_extend_2.author
+    assert_equal "hello :)", post.comments_with_extend.greeting
+    assert_equal "hullo :)", post.comments_with_extend_2.greeting
```
Comment (kamipo) [inline activerecord/test/cases/associations/has_many_associations_test.rb]: https://github.com/rails/rails/pull/28830#discussion_r113633741

> The fact that you removed this and nothing breaks concerns me. This seems like something we need to do otherwise the association scope will not extend the module passed in the `:extend` option. Maybe we are missing test coverage. Can you check if this would make any difference in the public API?

I finally get your point. The extension block is used in `association.extensions` and `association.scope`.

https://github.com/rails/rails/blob/3bd534287139549cee10e10364344d66139d9237/activerecord/lib/active_record/associations/collection_proxy.rb#L29-L36

https://github.com/rails/rails/blob/3bd534287139549cee10e10364344d66139d9237/activerecord/lib/active_record/associations/association.rb#L139-L147

The former is simple and covered by the tests. Extracting the extension module just moves from `association.rb#L143` to `association.rb#L140` by this change. I've exercised the tests to ensure the extending order just in case.

The latter is hard to testing (the extension block can't affect to `eval_scope` loop both the former and the latter).
Extracting the extension block just moves from `association_scope.rb#136` to `association_scope.rb#28`.
 
https://github.com/rails/rails/blob/3bd534287139549cee10e10364344d66139d9237/activerecord/lib/active_record/associations/association_scope.rb#L24-L28

https://github.com/rails/rails/blob/3bd534287139549cee10e10364344d66139d9237/activerecord/lib/active_record/associations/association_scope.rb#L130-L137
