### PR TITLE
Fix counter caches to work for models with composite primary keys

### LINKED ISSUE #50968: counter_cache doesn't work with composite PKs
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :test_background_check_requests, force: true do |t|
    t.integer :candidate_id
    t.integer :account_id
    t.string :name
  end

  create_table :test_candidates, force: true, primary_key: %i[candidate_id account_id] do |t|
    t.integer :candidate_id
    t.integer :account_id
    t.integer :test_background_check_requests_count
    t.string :name
  end
end

class TestCandidate < ActiveRecord::Base
  self.primary_key = %i[candidate_id account_id]
  has_many :test_background_check_requests, query_constraints: [:candidate_id, :account_id], inverse_of: :test_candidate
end

class TestBackgroundCheckRequest < ActiveRecord::Base
  belongs_to :test_candidate, counter_cache: true, query_constraints: [:candidate_id, :account_id]
end

class BugTest < Minitest::Test
  def test_association_stuff
    test_candidate = TestCandidate.create!(candidate_id: 1, account_id: 1, name: "Foo Barson")
    test_candidate.test_background_check_requests.create!(candidate_id: 1, account_id: 1, name: "Background check request 1")

    assert_equal 1, TestBackgroundCheckRequest.count
    assert_equal 1, test_candidate.reload.test_background_check_requests_count
  end
end
```

### Expected behavior
It is expected that the creation of the `TestBackgroundCheckRequest` will succeed, and that the associated `TestCandidate` would have a `test_background_check_request_count` of `1`.

### Actual behavior

The creation of the `TestBackgroundCheckRequest` fails with the following exception:

```
3.2.2 :057 > candidate.test_background_check_requests.create!(candidate_id: 1, account_id: 1, name: "Background check request 1")
D, [2024-02-05T15:23:08.589637 #90419] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2024-02-05T15:23:08.589781 #90419] DEBUG -- :   TestBackgroundCheckRequest Create (0.2ms)  INSERT INTO "test_background_check_requests" ("candidate_id", "account_id", "name") VALUES (?, ?, ?) RETURNING "id"  [["candidate_id", 1], ["account_id", 1], ["name", "Background check request 1"]]
D, [2024-02-05T15:23:08.589958 #90419] DEBUG -- :   TRANSACTION (0.0ms)  rollback transaction
/Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/predicate_builder.rb:82:in `block (2 levels) in expand_from_hash': Expected corresponding value for ["candidate_id", "account_id"] to be an Array (ArgumentError)

              raise ArgumentError, "Expected corresponding value for #{key} to be an Array" unless ids_set.is_a?(Array)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/predicate_builder.rb:81:in `map'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/predicate_builder.rb:81:in `block in expand_from_hash'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/predicate_builder.rb:79:in `each'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/predicate_builder.rb:79:in `flat_map'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/predicate_builder.rb:79:in `expand_from_hash'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/predicate_builder.rb:25:in `build_from_hash'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/query_methods.rb:1530:in `build_where_clause'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/relation/query_methods.rb:943:in `where!'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/counter_cache.rb:116:in `update_counters'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/locking/optimistic.rb:182:in `update_counters'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/persistence.rb:976:in `increment!'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/locking/optimistic.rb:64:in `increment!'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/callbacks.rb:436:in `increment!'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/associations/belongs_to_association.rb:106:in `update_counters'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/associations/belongs_to_association.rb:58:in `increment_counters'
	from /Users/markosfragkakis/.rvm/gems/ruby-3.2.2/bundler/gems/rails-0add5dba834f/activerecord/lib/active_record/counter_cache.rb:203:in `block in _create_record'
	... 44 levels...
3.2.2 :058 > 
```

### System configuration
**Rails version**:
7.1.3
**Ruby version**:
3.2.2

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #50968.

### CODE REVIEW

**Review by nvasilevski — APPROVED** [review]
Thank you!

File: activerecord/test/cases/counter_cache_test.rb [hunk 1]
```diff
@@ -148,6 +164,17 @@ class ::SpecialReply < ::Reply
     end
   end
 
+  test "reset counters for cpk model" do
+    order = Cpk::Order.first
+    # throw the count off by 1
+    Cpk::Order.increment_counter(:books_count, order.id)
+
+    # check that it gets reset
+    assert_difference "order.reload.books_count", -1 do
```
Comment (bogdan) [inline activerecord/test/cases/counter_cache_test.rb:173]: Are you sure eval is cool here? It might be slow. How about lambda?

```suggestion
    assert_difference ->{ order.reload.books_count }, -1 do
```

Comment (fatkodima) [reply activerecord/test/cases/counter_cache_test.rb]: That is the style used within this file. The slowness won't be noticeable, but I also don't like this pattern, so time to break it.

File: activerecord/lib/active_record/counter_cache.rb [hunk 2]
```diff
@@ -66,7 +66,11 @@ def reset_counters(id, *counters, touch: nil)
           updates.merge!(touch_updates)
         end
 
-        unscoped.where(primary_key => object.id).update_all(updates) if updates.any?
+        if updates.any?
+          id = object.id
+          id = [id] if composite_primary_key? && id.is_a?(Array) && !id[0].is_a?(Array)
```
Comment (byroot) [inline activerecord/lib/active_record/counter_cache.rb:71]: I think we're way past the point where we need to take a step back and figure out how to not have to check for CPK in such a ad hoc way everywhere.

Even if we ignore how ugly this is, and fix all the call sites we may have missed, we're likely to constantly break CPK support when adding new features.

Comment (nvasilevski) [reply activerecord/lib/active_record/counter_cache.rb:71]: Generally we expected that `where(primary_key => id)` will "just work", or at least `where(primary_key => [id])` will work regardless of what shape `id` has.
But it looks like we end up in a situation where only "multi" `where(primary_key => [id])` where `[id]` is an array of arrays for composite primary key models and array of plan ids for regular models.


One of the possible options that was considered is to introduce some kind of a `Model.primary_key_scope(id_or_ids)` helper (at least for internal use) which will always know how to build a correct relation. The helper implementation may end up having similar `if` checks but at least consumers won't need to bother.

It may be a bit harder but in the long term if we had `primary_key_scope` concept we could make sure that CPK relations and regular model relations have different implementation of the method so there will be no branching

Comment (nvasilevski) [reply activerecord/lib/active_record/counter_cache.rb:71]: Hey @fatkodima, do you remember why this line needed the array wrap as well?

In this case we know that `id = object.id` will always represent one identifier so ` unscoped.where(primary_key => [id])` should just work. I tried it quickly and none of the tests seem to fail

The `update_counters` does need at least something as indeed we can't know whether passed `id` is an array of ids or just a composite primary key array

Comment (fatkodima) [reply activerecord/lib/active_record/counter_cache.rb:71]: Yeah, correct 🤦 We had `object.id`, not just `id`.

File: activerecord/lib/active_record/counter_cache.rb [hunk 3]
```diff
@@ -113,6 +113,7 @@ def reset_counters(id, *counters, touch: nil)
       #   #    `updated_at` = '2016-10-13T09:59:23-05:00'
       #   #  WHERE id IN (10, 15)
       def update_counters(id, counters)
+        id = [id] if composite_primary_key? && id.is_a?(Array) && !id[0].is_a?(Array)
```
Comment (nvasilevski) [inline activerecord/lib/active_record/counter_cache.rb:116]: @casperisfine So after a small tweak this is the only place where we end up with a "not so pretty" handling. How would you feel about merging this as a bugfix but we will still work on a solution to make sure we get rid of `composite_primary_key? ` branches and everything that comes with it in a separate PR. Because even if we come up with something I'd prefer to ship it separately as this bugfix will need to be backported while a refactoring can be released in the next major

**Comment by byroot** [comment]
Backported as 26aa77dba2e1b346ea026ccdd6dc8289753c1d6d

File: activerecord/lib/active_record/counter_cache.rb (hunk 2 above)
Comment (brendon) [reply activerecord/lib/active_record/counter_cache.rb]: I've come across this when implementing composite primary keys in the [positioning](https://github.com/brendon/positioning) gem. The format for a composite key (needing to be an array wrapped in an array) was surprising but as you say @nvasilevski, it does work fine. At least it means the codebase doesn't care about composite primary keys in terms of implementation detail. Is there a reason for the double-wrapping requirement? And was there any further progress on a `primary_key_scope`?
