### PR TITLE
Prevent `RequestEncoder#encode_params` to parse falsey params

### LINKED ISSUE #33388: Unwanted query parameter "null=" added to the url in a get request test using as: :json
### Steps to reproduce
when calling [this method](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb#L17) (i'm calling it from rspec request test)

using `as: :json` for a get request (so we can easilly have the json headers) adds a parameter to the url `null=`

This happens because in [this line](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb#L236)

it encodes the `nil` parameters as json, and `nil.to_json`  is `null`

I solved it by re registering the json_encoder like this (for now, in an initializer)

```ruby
ActionDispatch::IntegrationTest.register_encoder(
  :json,
  param_encoder: -> params { params ? params.to_json : nil },
  response_parser: -> body { JSON.parse(body) }
)
```

### Expected behavior
It should not add `null=` to the url

### Actual behavior
it adds a  `null=` to the url

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

### PR DESCRIPTION
**Pull request by al3rez**
Fixes #33388 - When a `get` method called with `as: :json` and `params: nil`
(explicitly or implicitly) `RequestEncoder#encode_params` converts it
into a `null` value which includes a unexpected `null=` query string
into request URL. From now on `RequestEncoder#encode_params` checks
whether `params` is nil or not otherwise returns.

### CODE REVIEW

**Comment by azbshiri** [comment]
@rafaelfranca

File: actionpack/test/controller/integration_test.rb [hunk 1]
```diff
@@ -4,6 +4,7 @@
 require "controller/fake_controllers"
 require "rails/engine"
 
+
```
Comment (bogdanvlviv) [inline actionpack/test/controller/integration_test.rb]: Could you remove this extra line?

File: actionpack/lib/action_dispatch/testing/request_encoder.rb [hunk 2]
```diff
@@ -34,7 +34,7 @@ def accept_header
     end
 
     def encode_params(params)
-      @param_encoder.call(params)
+      @param_encoder.call(params) unless params.nil?
```
Comment (bogdanvlviv) [inline actionpack/lib/action_dispatch/testing/request_encoder.rb]: I think it shouldn't be fixed in `actionpack/lib/action_dispatch/testing/integration.rb` See diff:
```diff
diff --git a/actionpack/lib/action_dispatch/testing/integration.rb b/actionpack/lib/action_dispatch/testing/integration.rb
index 7637febd1c..9c6075ad0c 100644
--- a/actionpack/lib/action_dispatch/testing/integration.rb
+++ b/actionpack/lib/action_dispatch/testing/integration.rb
@@ -233,7 +233,7 @@ def process(method, path, params: nil, headers: nil, env: nil, xhr: false, as: n

         request_env = {
           :method => method,
-          :params => request_encoder.encode_params(params),
+          :params => params.nil? ? nil : request_encoder.encode_params(params),
```

File: actionpack/test/controller/integration_test.rb (hunk 1 above)
Comment (azbshiri) [reply actionpack/test/controller/integration_test.rb]: done

File: actionpack/lib/action_dispatch/testing/request_encoder.rb (hunk 2 above)
Comment (azbshiri) [reply actionpack/lib/action_dispatch/testing/request_encoder.rb]: done

**Comment by bogdanvlviv** [comment]
@azbshiri Could you squash commits  into one commit?

File: actionpack/lib/action_dispatch/testing/request_encoder.rb (hunk 2 above)
Comment (kaspth) [reply actionpack/lib/action_dispatch/testing/request_encoder.rb]: @bogdanvlviv why shouldn't it be fixed in here? Isn't it a special case of the request encoder to handle?

I'd write it as `@param_encoder.call(params) if params` though.

Should we update some documentation too? E.g. to say that a request encoder will only be asked to encode params when they aren't nil or similar?

**Comment by azbshiri** [comment]
done

File: actionpack/lib/action_dispatch/testing/request_encoder.rb (hunk 2 above)
Comment (bogdanvlviv) [reply actionpack/lib/action_dispatch/testing/request_encoder.rb]: Yeah, probably would be better just to write `@param_encoder.call(params) if params` in  `ActionDispatch::RequestEncoder`, Since it is private api we haven't written any documentation.
By the way if

```ruby
get "/foos_json", as: :json, params: false
request.url # => http://www.example.com/foos_json?false
```
condition `if params` would fix it too.

@azbshiri My apologies for confusing. Could you apply `@param_encoder.call(params) if params`, and update the commit message accordance this change?

Comment (azbshiri) [reply actionpack/lib/action_dispatch/testing/request_encoder.rb]: done

File: actionpack/lib/action_dispatch/testing/integration.rb [hunk 3]
```diff
@@ -233,7 +233,7 @@ def process(method, path, params: nil, headers: nil, env: nil, xhr: false, as: n
 
         request_env = {
           :method => method,
-          :params => request_encoder.encode_params(params),
+          :params => params.nil? ? nil : request_encoder.encode_params(params),
```
Comment (silva96) [inline actionpack/lib/action_dispatch/testing/integration.rb]: I would remove it from here since this is a specific usage of the encode_params which already handles it.

Comment (tsolar) [inline actionpack/lib/action_dispatch/testing/integration.rb]: if `encode_params` returns `nil` if `params` not present, then this conditional is not necessary

File: actionpack/lib/action_dispatch/testing/request_encoder.rb (hunk 2 above)
Comment (azbshiri) [reply actionpack/lib/action_dispatch/testing/request_encoder.rb]: I didn't commit and push the changes of Yesterday, it's ready to be merged.

**Review by bogdanvlviv — APPROVED** [review]

File: actionpack/lib/action_dispatch/testing/integration.rb (hunk 3 above)
Comment (azbshiri) [reply actionpack/lib/action_dispatch/testing/integration.rb]: @tsolar yeah it was the case, but i didn't commit yesterday.

Comment (azbshiri) [reply actionpack/lib/action_dispatch/testing/integration.rb]: as i mentioned in tsolar reply that was the case, but i forgot to commit.

**Comment by kaspth** [comment]
Thanks!
