### PR TITLE
Fix polymorphic association subquery

### LINKED ISSUE #47335: Incorrect subquery for a polymorphic `has_one` association
### Steps to reproduce

```ruby
require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Schema.define do
  create_table :pins do |t|
    t.string :code, null: false
  end
  create_table :cards do |t|
  end
  create_table :access_tools do |t|
    t.references :item, polymorphic: true
  end
end

class Pin < ActiveRecord::Base
  has_one :access_tool, as: :item
end

class Card < ActiveRecord::Base
  has_one :access_tool, as: :item
end

class AccessTool < ActiveRecord::Base
  belongs_to :item, polymorphic: true
end

Pin.create!(code: "1111")
AccessTool.create!(item: Card.create!)
AccessTool.create!(item: Pin.create!(code: "2222"))

Pin.where(access_tool: AccessTool.all).count # => 2 (expected 1)
```

### Expected behavior

I expected the subquery to automatically filter by the source type, because Active Record has the information about this. So, I expected `Pin.where(access_tool: AccessTool.all)` to filter access tools by `item_type = "Pin"`:

```sql
SELECT "pins".* FROM "pins" WHERE "pins"."id" IN (
  SELECT "access_tools"."item_id" FROM "access_tools" WHERE "access_tools"."item_type" = "Pin"
)
```

### Actual behavior

What happened was that the subquery didn't include any source type filters, so the query would return PINs with IDs from other source types. The actual subquery didn't contain any `item_type` filters:

```sql
SELECT "pins".* FROM "pins" WHERE "pins"."id" IN (
  SELECT "access_tools"."item_id" FROM "access_tools"
)
```

I find this subquery to be incorrectly inferred from my `has_one` association declaration, because it's missing the `item_type = "Pin"` filter. Active Record should either generate the complete subquery, or raise an error that it cannot generate it. I find the current behavior to be dangerous, because it gave me the illusion that it succeeded in generating the requested subquery, but it was only partial.

This is the second time I got surprised by this behavior; the first time it was just me running something in the console, but the second time it actually caused a bug in production. So I thought I would report it.

### System configuration

**Rails version**: 7.0.4.2

**Ruby version**: 2.7.6

### PR DESCRIPTION
**Pull request by lazaronixon**
### Motivation / Background

Fix where on association with has_one/has_many polymorphic relations.

Before:
```ruby
Treasure.where(price_estimates: PriceEstimate.all)
#=> SELECT (...) WHERE "treasures"."id" IN (SELECT "price_estimates"."estimate_of_id" FROM "price_estimates")
```

Later:
```ruby
Treasure.where(price_estimates: PriceEstimate.all)
#=> SELECT (...) WHERE "treasures"."id" IN (SELECT "price_estimates"."estimate_of_id" FROM "price_estimates" WHERE "price_estimates"."estimate_of_type" = 'Treasure')
```

Fixes #47335

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/lib/active_record/relation/predicate_builder/association_query_value.rb [hunk 1]
```diff
@@ -25,7 +25,10 @@ def queries
         def ids
           case value
           when Relation
-            value.select_values.empty? ? value.select(primary_key) : value
+            relation = value
+            relation = relation.select(primary_key) if relation.select_values.empty?
+            relation = relation.rewhere(primary_type => polymorphic_name) if primary_type
```
Comment (byroot) [inline activerecord/lib/active_record/relation/predicate_builder/association_query_value.rb:30]: Why `rewhere` rather than just `where` here?

File: activerecord/test/cases/relation/where_test.rb [hunk 2]
```diff
@@ -458,6 +458,13 @@ def test_where_on_association_with_select_relation
       assert_equal essays(:david_modest_proposal), essay
     end
 
+    def test_where_on_association_with_collection_polymorphic_relation
+      expected = Treasure.where(price_estimates: PriceEstimate.where(estimate_of_type: "Treasure"))
+      actual   = Treasure.where(price_estimates: PriceEstimate.all)
+
+      assert_equal expected.to_sql, actual.to_sql
```
Comment (byroot) [inline activerecord/test/cases/relation/where_test.rb:465]: I fear this test might be a bit too dynamic, it could easily end up passing even if the actual feature is broken, as it rely a bit too much on higher level APIs.

Could we have a test similar to the one reported in the issue? One that actually perform the query and ensure only the record we want are returned?

**Review by byroot — COMMENTED** [review]
Thanks a lot for providing a fix.

Have a few minor concerns, but overall this looks pretty good.

Would also be good to add a changelog entry for this.

File: activerecord/lib/active_record/relation/predicate_builder/association_query_value.rb (hunk 1 above)
Comment (lazaronixon) [reply activerecord/lib/active_record/relation/predicate_builder/association_query_value.rb:30]: Hey, thanks for the quick response. If we don't use `rewhere` we can end up having duplicated where conditions and the test below will fail. It won't change the behavior, it just generates duplicated conditions.

```ruby
Treasure.where(price_estimates: PriceEstimate.where(estimate_of_type: "Treasure"))
#=> SELECT (...) WHERE "treasures"."id" IN (SELECT (...) FROM "price_estimates" WHERE "price_estimates"."estimate_of_type" = 'Treasure' AND "price_estimates"."estimate_of_type" = 'Treasure')
```

File: activerecord/test/cases/relation/where_test.rb [hunk 3]
```diff
@@ -458,6 +458,11 @@ def test_where_on_association_with_select_relation
       assert_equal essays(:david_modest_proposal), essay
     end
 
+    def test_where_on_association_with_collection_polymorphic_relation
+      treasures = Treasure.where(name: ["diamond", "emerald"], price_estimates: PriceEstimate.all)
```
Comment (lazaronixon) [inline activerecord/test/cases/relation/where_test.rb:462]: Now we have a `Car` and `Treasure` with the same id. Before this fix it was returning false treasures with `price_estimates`.

File: activerecord/lib/active_record/relation/predicate_builder/association_query_value.rb [hunk 4]
```diff
@@ -37,6 +40,22 @@ def primary_key
...
+        def polymorphic_name
+          associated_table.polymorphic_name_association
+        end
+
+        def select_values?
+          value.select_values.present?
+        end
+
+        def polymorphic_clause?
+          primary_type && !value.where_values_hash.has_key?(primary_type)
```
Comment (lazaronixon) [inline activerecord/lib/active_record/relation/predicate_builder/association_query_value.rb:56]: If we want to use `where` we can follow the pattern for `select` and only add the condition if it's not present.

File: activerecord/lib/active_record/relation/predicate_builder/association_query_value.rb (hunk 1 above)
Comment (lazaronixon) [reply activerecord/lib/active_record/relation/predicate_builder/association_query_value.rb]: https://github.com/rails/rails/pull/48362/files#diff-8083725fa779d54362134c43c404662915037be49d44f05c04e114889ff26c71R55-R57

File: activerecord/test/cases/relation/where_test.rb (hunk 2 above)
Comment (lazaronixon) [reply activerecord/test/cases/relation/where_test.rb]: Now we have a Car and Treasure with the same id. Before this fix, it was returning emerald that in this case doesn't have a PriceEstimate and wrongly relating to honda Car just because both have the same id.

https://github.com/rails/rails/blob/a3e85f7c6f3e3922b3a93c8c8603e63465502b71/activerecord/test/cases/relation/where_test.rb#L461-L464

File: activerecord/lib/active_record/relation/predicate_builder/association_query_value.rb (hunk 1 above)
Comment (byroot) [reply activerecord/lib/active_record/relation/predicate_builder/association_query_value.rb]: I think it's fine. I prefer that over some condition potentially being ignored.

**Comment by byroot** [comment]
Thank you!
