### PR TITLE
Fail more gracefully from ActiveStorage missing file exceptions

### LINKED ISSUE #33647: ActiveStorage: Fail more gracefully if file is not found using DiskService
I propose that `Errno:ENOENT` arising from ActiveStorage DiskService should be rescued and should return 404.

## Motivation

It is very common for developers using ActiveStorage to use a cloud service in production and DiskService in development. Also, I doubt I’m the only one who copies my production database on to my development machine as a general practice. That means that when ActiveStorage::Blobs are resolved, valid references to S3 become invalid references to `./storage/...` Especially when loading an index page that displays many attached images, the log is drowned in very long stack traces for the numerous `Errno:ENOENT` errors that arise. It’s a bad development experience.

## Implementation (?)

If people think this is a good idea, I’d like to tackle it. This is what I’m thinking, although it could be quite off base.

I could simply add

```ruby
rescue_from Errno::ENOENT do
  head :not_found
end
```

to `ActiveStorage::DiskController` and `ActiveStorage::RepresentationsController`.

Alternatively, if that’s too specific for the level of abstraction those controllers are at, I could modify `ActiveStorage::Service::DiskService` to raise a more semantic error (`ActiveStorage::FileNotFoundError`?) that could be handled somewhere. (Is there an engine-specific version of `config.action_dispatch.rescue_responses`?)

I welcome your thoughts and hope you find this a reasonable proposal. I would love to stop having to run `Thing.all.each { |x| x.image.detach }` every time I clone down my production db.

### PR DESCRIPTION
**Pull request by cbothner**
This PR translates service-specific missing object exceptions into one generic `ActiveStorage::FileNotFoundError` so that the application can fail more gracefully when a missing file is accessed. Specifically, this PR lets `DiskController` rescue this error and respond with 404 instead of 500. This improves the development experience especially when working, in `development`, with a database of Blob records that point to files in the `production` service.

### Outstanding question
`RepresentationsController` does not presently handle `ActiveStorage::FileNotFoundError`, since @georgeclaghorn argued it truly is exceptional for the service not to have a file that corresponds to a specific blob in the database. I don’t disagree with this, but hope we can nevertheless find a way to reduce the flood of stack traces that fill our `development` logs when loading an index view that tries to display many thumbnails of images stored in our `production` service.

### Related issue

Resolves #33647

### CODE REVIEW

File: activestorage/lib/active_storage/service/azure_storage_service.rb [hunk 1]
```diff
@@ -34,16 +34,26 @@ def download(key, &block)
         end
       else
         instrument :download, key: key do
-          _, io = blobs.get_blob(container, key)
-          io.force_encoding(Encoding::BINARY)
+          begin
+            _, io = blobs.get_blob(container, key)
+            io.force_encoding(Encoding::BINARY)
+          rescue Azure::Core::Http::HTTPError => e
+            raise e unless e.type == "BlobNotFound"
```
Comment (georgeclaghorn) [inline activestorage/lib/active_storage/service/azure_storage_service.rb]: Let’s use bare `raise` instead of `raise e` to avoid munging the backtrace:

```ruby
if e.type == "BlobNotFound"
  raise ActiveStorage::FileNotFoundError
else
  raise
end
```

File: activestorage/lib/active_storage/service/azure_storage_service.rb [hunk 2]
```diff
@@ -34,16 +34,26 @@ def download(key, &block)
...
       instrument :download_chunk, key: key, range: range do
-        _, io = blobs.get_blob(container, key, start_range: range.begin, end_range: range.exclude_end? ? range.end - 1 : range.end)
-        io.force_encoding(Encoding::BINARY)
+        begin
+          _, io = blobs.get_blob(container, key, start_range: range.begin, end_range: range.exclude_end? ? range.end - 1 : range.end)
+          io.force_encoding(Encoding::BINARY)
+        rescue Azure::Core::Http::HTTPError => e
+          raise e unless e.type == "BlobNotFound"
+          raise ActiveStorage::FileNotFoundError
+        end
```
Comment (georgeclaghorn) [inline activestorage/lib/active_storage/service/azure_storage_service.rb]: Can we extract a private `handle_errors` method to avoid duplicating the error handling logic in `download` and `download_chunk`?

```ruby
def download_chunk(key, range)
  instrument :download_chunk, key: key, range: range do
    handle_errors do
      _, io = blobs.get_blob(container, key, start_range: range.begin, end_range: range.exclude_end? ? range.end - 1 : range.end)
      io.force_encoding(Encoding::BINARY)
    end
  end
end
```

Comment (cbothner) [reply activestorage/lib/active_storage/service/azure_storage_service.rb]: I was half tempted to put such a private method on the parent class (taking a service specific exception as an argument) but worried it was gonna be too much magic. Is this just needed because of the extra type checking needed for Azure errors? (Related bug fix PR #33667 that should probably do it the same way…)

Comment (georgeclaghorn) [reply activestorage/lib/active_storage/service/azure_storage_service.rb]: I wouldn’t put it on the parent class. It’s a service-specific method.

File: activestorage/lib/active_storage/service/azure_storage_service.rb [hunk 3]
```diff
@@ -157,5 +151,17 @@ def stream(key)
...
+        begin
+          yield
+        rescue Azure::Core::Http::HTTPError => e
+          if e.type == "BlobNotFound"
+            raise ActiveStorage::FileNotFoundError
+          else
+            raise
+          end
+        end
+      end
```
Comment (georgeclaghorn) [inline activestorage/lib/active_storage/service/azure_storage_service.rb]: You don’t need the `begin`/`end` block here:

```ruby
def handle_errors
  yield
rescue Azure::Core::Http::HTTPError => e
  # ...
end
```

File: activestorage/lib/active_storage/service/disk_service.rb [hunk 4]
```diff
@@ -122,6 +126,18 @@ def path_for(key) #:nodoc:
...
+      def stream(key)
+        begin
+          File.open(path_for(key), "rb") do |file|
+            while data = file.read(5.megabytes)
+              yield data
+            end
+          end
+        rescue Errno::ENOENT
+          raise ActiveStorage::FileNotFoundError
+        end
```
Comment (georgeclaghorn) [inline activestorage/lib/active_storage/service/disk_service.rb]: Ditto: you don’t need the `begin`/`end` block here.

**Comment by georgeclaghorn** [comment]
Last thing: can you please squash your commits? I think two are appropriate: one for rescuing `Errno::ENOENT` in `DiskController` and one for translating service-specific missing object exceptions.

I also think these changes merit separate changelog entries, since they're independent:

* `ActiveStorage::Blob#download` and `ActiveStorage::Blob#open` raise `ActiveStorage::FileNotFoundError` when the corresponding file is missing from the storage service. Services translate service-specific missing object exceptions (e.g. `Google::Cloud::NotFoundError` for the GCS service and `Errno::ENOENT` for the disk service) into `ActiveStorage::FileNotFoundError`.

* `ActiveStorage::DiskController#show` generates a 404 Not Found response when the requested file is missing from the disk service. It previously raised `Errno::ENOENT`.

**Comment by cbothner** [comment]
Done 👍 

Is there anything to do about the errors raised in `RepresentationsController` for the sake of developer experience, or is that inappropriate to handle at the framework level?

**Comment by georgeclaghorn** [comment]
The [`DebugExceptions`](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb) middleware logs the full backtrace if none of the lines in the trace come from the application, which is the case for `ActiveStorage::FileNotFoundError`s triggered by requests to `RepresentationsController`:

https://github.com/rails/rails/blob/cdee52079cdd88d376d9664a61a40348d45e819c/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb#L179-L188

I’m not immediately sure what we can do about that. I’m going to think about it and merge this in the meantime.
