### PR TITLE
Store correct environment in `internal_metadata` when run `rails db:prepare`

### LINKED ISSUE #46845: rails db:prepare will save "environment=development" for ar_internal_metadata in test database
### Steps to reproduce

I created [a sample app](https://github.com/JunichiIto/db-prepare-sandbox) to reproduce this problem. Please run the following commands:

```
git clone https://github.com/JunichiIto/db-prepare-sandbox.git
cd db-prepare-sandbox 
bin/setup 
rails test
```

Then, you'll see:

``` 
rails aborted!
ActiveRecord::EnvironmentMismatchError: You are attempting to modify a database that was last run in `development` environment.
You are running in `test` environment. If you are sure you want to continue, first set the environment using:

        bin/rails db:environment:set RAILS_ENV=test


Tasks: TOP => db:test:load => db:test:purge => db:check_protected_environments
(See full trace by running task with --trace)
Running 0 tests in a single process (parallelization threshold is 50)
Run options: --seed 54729

# Running:



Finished in 0.000382s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

The sample app was created like this:

```
rails new db-prepare-sandbox --api
cd db-prepare-sandbox
rails g model Book title
rails db:migrate
```

### Expected behavior

Test finishes without any error messages:

``` 
Running 0 tests in a single process (parallelization threshold is 50)
Run options: --seed 2686

# Running:



Finished in 0.000362s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

### Actual behavior

Test finishes with ActiveRecord::EnvironmentMismatchError:

``` 
rails aborted!
ActiveRecord::EnvironmentMismatchError: You are attempting to modify a database that was last run in `development` environment.
You are running in `test` environment. If you are sure you want to continue, first set the environment using:

        bin/rails db:environment:set RAILS_ENV=test


Tasks: TOP => db:test:load => db:test:purge => db:check_protected_environments
(See full trace by running task with --trace)
Running 0 tests in a single process (parallelization threshold is 50)
Run options: --seed 54729

# Running:



Finished in 0.000382s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

### System configuration
**Rails version**: 7.0.4

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

## My investigation

[`bin/setup` calles `bin/rails db:prepare`](https://github.com/JunichiIto/db-prepare-sandbox/blob/main/bin/setup#L26
).

`db:prepare` task calls `prepare_all` method and [it establishes connection for test database](https://github.com/rails/rails/blob/v7.0.4/activerecord/lib/active_record/tasks/database_tasks.rb#L192).

Then, `ActiveRecord::Migrator#record_environment` is called. The problem is [here](https://github.com/rails/rails/blob/v7.0.4/activerecord/lib/active_record/migration.rb#L1341):

```
      # Stores the current environment in the database.
      def record_environment
        return if down?
        ActiveRecord::InternalMetadata[:environment] = ActiveRecord::Base.connection.migration_context.current_environment
      end
```

`ActiveRecord::Base.connection.migration_context.current_environment` returns "development" and the value is saved as "environment=development" in ar_internal_metadata table:

```
$ RAILS_ENV=test rails db
SQLite version 3.37.0 2021-12-09 01:34:53
Enter ".help" for usage hints.
sqlite> select * from ar_internal_metadata;
environment|development|2022-12-28 10:53:13.357309|2022-12-28 10:53:13.357309
```

But it should be "test" for test database. This causes ActiveRecord::EnvironmentMismatchError.

## Similar discussions
- [Test database is created with environment='development' when running rake db:test:prepare · Issue \#26731 · rails/rails](https://github.com/rails/rails/issues/26731)
- [Ignore test env in DatabaseTasks when DATABASE\_URL is present by bbuchalter · Pull Request \#37351 · rails/rails](https://github.com/rails/rails/pull/37351)

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #46845.

[Rendered without space changes](https://github.com/rails/rails/pull/46879/files?w=1)

My suggestion (https://github.com/rails/rails/issues/46845#issuecomment-1370057047) was to have something like
```diff
--- a/activerecord/lib/active_record/migration.rb
+++ b/activerecord/lib/active_record/migration.rb
@@ -1427,7 +1427,7 @@ def migrate_without_lock
       def record_environment
         return if down?

-        @internal_metadata[:environment] = connection.migration_context.current_environment
+        @internal_metadata[:environment] = connection.pool.db_config.env_name
       end

       def ran?(migration)
```

But that did not worked out, because `db_config.env_name` is envs (top level keys) from the `database.yml`, but the rake task tries to store basically the `RAILS_ENV`, which could not be the same? Several test cases started to fail, for example, https://github.com/rails/rails/blob/c70a8f75d7a41212cbe358b2a0122a28321b040d/activerecord/test/cases/migration_test.rb#L691-L713

So I went with my original suggestion (https://github.com/rails/rails/issues/46845#issuecomment-1366646524) and enhanced it a bit to not depend on the rails' application presence.

It is not very elegant, but it works.

cc @eileencodes

### CODE REVIEW

File: activerecord/lib/active_record/tasks/database_tasks.rb [hunk 1]
```diff
@@ -624,6 +626,26 @@ def check_current_protected_environment!(db_config)
           rescue ActiveRecord::NoDatabaseError
           end
         end
+
+        def with_env(env)
```
Comment (eileencodes) [inline activerecord/lib/active_record/tasks/database_tasks.rb:630]: I'm going to take a look at this this week. We can't merge this method as is, we need to do this without accessing Rails env at all.

**Review by eileencodes — CHANGES_REQUESTED** [review]

**Comment by eileencodes** [comment]
I think the tests that are failing when using `db_config.env_name` are wrong.

Let's say you have an environment "foofoo" and try to run migrations. You'll get an error because there is no configuration corresponding to the "foofoo" environment. Locally with a demo app if I try to run mgirations against an env that does not exist, and therefore does not have a matching config I get this error:

```
$ RAILS_ENV=foofoo bin/rails db:migrate
rails aborted!
ActiveRecord::AdapterNotSpecified: The `foofoo` database is not configured for the `foofoo` environment.

  Available database configurations are:

  default
development: primary, primary_replica, animals, animals_replica
test: primary, primary_replica, animals, animals_replica

Tasks: TOP => db:migrate => db:load_config
(See full trace by running task with --trace)
```

I get the same error with `db:prepare`. So in a real world example we can't set the env to a config that does not exist. The tests should be updated so we can get the env from the db_config. It's how we do it when we set the environment in `load_schema`. `record_environment` should match that behavior. https://github.com/rails/rails/blob/main/activerecord/lib/active_record/tasks/database_tasks.rb#L362

**Comment by fatkodima** [comment]
@eileencodes Made suggested changes, thank you for the review. 
CI failed 1 job due to timeout - not sure if this is caused by this PR or not.

**Review by eileencodes — APPROVED** [review]
Re-ran the build and it passed. I doubt it is related - we see timeouts occasionally. More likely something on the buildkite end. 

Thank you for working on this!

**Comment by eileencodes** [comment]
Hey @fatkodima do you know if to fix this on 7-0-stable do we need both https://github.com/rails/rails/pull/45464 and this change? Do you want to work on a backport?

**Comment by fatkodima** [comment]
> If not I can do it, just wanted to ask first.

Please feel free to do so 🙏

**Comment by zzak** [comment]
@eileencodes Do you think this is worth a changelog?

**Comment by eileencodes** [comment]
> Do you think this is worth a changelog?

No, it's fixing a bug and we usually only put features / major changes in the changelog.

**Comment by eileencodes** [comment]
The backport wasn't straight forward, ended up reimplementing the commits because they didn't backport cleanly. Backport commit: 4505c2f508418e40c2cf82701cc9144cb7e4e83d
