### PR TITLE
Raise when defining an enum not backed by a database column

### LINKED ISSUE #45668: enum definition silences UnknownAttributeError & misbehaves with outdated schema cache
Defining an enum to a ActiveRecord model has the affect that typical safeguards / checks for *unknown attributes* are bypassed, for example when there was a typo in the database migration related to an enum.

**How was this observed?**

A process (example a worker processor like sidekiq), which had the enum definition loaded already, and another process/system changed the database with a migration, adding the column for which the enum was defined. Later on expected data was not stored into the database (instead the default value for the column). Assumption: Since the background process did not refresh the schema cache it ignores the change for the enum attribute. But because `Enum` module defines an `attribute` activerecord considers it not a problem that the column is not really present.

**Comment:**

I would totally understand if this considered an extreme edge case but I just thought it would be worthwhile to report. While thinking about about a potential solution, I realize that a potential solution is not even obvious. Should the enum definition cause an error when the model is loaded? Should every update to an Enum attribute check whether or not the column exists?

### Steps to reproduce

- define enum attribute in model for a non existing column name
- try to store a value into this attribute with the same name
- no error is raised. The desired data is not stored

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
# ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: "rails_enum_bug.sqlite")
# ActiveRecord::Base.establish_connection(adapter: "mysql2", database: "rails_enum_bug_report", username: 'root', host: '127.0.0.1')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
  enum :wrong_attributee, [:default_value, :middle_value, :other_value]
end

class AddAttributeToPosts < ActiveRecord::Migration[7.0]
  def change
    add_column :posts, :wrong_attrib, :integer, default: 0
  end
end

class AddEnumToPosts < ActiveRecord::Migration[7.0]
  def change
    add_column :posts, :wrong_attributee, :integer, default: 0
  end
end

class BugTest < Minitest::Test
  def test_with_outdated_schema_cache
    assert_equal ["id"], Post.column_names # to load schema cache
    AddAttributeToPosts.migrate(:up)
    AddEnumToPosts.migrate(:up)
    assert_equal ["id"], Post.column_names
    new_post = Post.create!(wrong_attributee: :other_value) # column is not in the schema cache, so why no error?
    Post.reset_column_information

    assert_equal "default_value", new_post.reload.wrong_attributee # database default is used
    assert_equal "other_value", new_post.reload.wrong_attributee # actual value is 0 (sqlite default)
  end

  def test_unknown_attribute
    AddAttributeToPosts.migrate(:up)
    Post.reset_column_information

    # expected/normal behaviour
    assert_raises(ActiveModel::UnknownAttributeError) do
      Post.create!(wrong_attribute: :other_value)
    end
    new_post = Post.create!(wrong_attributee: :other_value) # bug, this should raise an error

    assert_nil new_post.reload.wrong_attributee
    assert_nil new_post.reload.wrong_attrib
    assert_equal "other_value", new_post.reload.wrong_attributee # not really expected behaviour :)
  end

  def teardown
    Post.delete_all
    AddAttributeToPosts.migrate(:down)
    AddEnumToPosts.migrate(:down) if ActiveRecord::Base.connection.column_exists?(:posts, :wrong_attributee)
    Post.reset_column_information
  end
end

```

### Expected behavior

- UnknownAttributeError would get raised at *some point* 

### Actual behavior

- no error is raised
- record gets created/modified without the desired value
- in the case of a successful migration for a column with a default value but a missing schema cache update, the record gets created without the desired data in that column but the default value

### System configuration
**Rails version**:

7

**Ruby version**:

3

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #45668. 
Look there for the details.

### CODE REVIEW

File: activerecord/lib/active_record/enum.rb [hunk 1]
```diff
@@ -198,6 +198,11 @@ def _enum(name, values, prefix: nil, suffix: nil, scopes: true, **options)
 
         value_method_names = []
         _enum_methods_module.module_eval do
+          define_method("#{name}=") do |value|
+            raise UnknownAttributeError.new(self, name) unless self.class.columns_hash.key?(name)
+            super(value)
+          end
```
Comment (byroot) [inline activerecord/lib/active_record/enum.rb:204]: Hum, I really don't like this overhead :/

The core of the problem is that we have to define the enum when the model is loaded, but it's only later, when the schema is loaded, that we'll know if the column exist.

Having an overhead on every assignment doesn't feel right when this could be checked only once when the schema is loaded.

I think there are some precedent for module that redefine the `load_schema` method (not sure what the actual name is just like that) to use it as a hook to validate some previous declarations.

Comment (byroot) [reply activerecord/lib/active_record/enum.rb:204]: Ah it's `load_schema!`, and here's the example I had in mind: https://github.com/rails/rails/blob/3661d0d8a46a2725b3e7bacbc230e4f183fb67dc/activerecord/lib/active_record/attributes.rb#L263-L269


It's still not quite ideal because the error would be raised much later than when the error is made, but still better than on the first assignment. Especially in prod where the first assignment will be during a request, whereas loading the schema is at boot, so you fail the deploy vs serving 500s.

Comment (fatkodima) [reply activerecord/lib/active_record/enum.rb]: > Especially in prod where the first assignment will be during a request

I hope the first assignment is in people's tests, not in prod 😄 

@byroot  Thank you for the review, as usual ❤️ Changed with the suggestion.

File: activerecord/lib/active_record/attributes.rb [hunk 2]
```diff
@@ -264,6 +264,7 @@ def load_schema! # :nodoc:
         super
         attributes_to_define_after_schema_loads.each do |name, (cast_type, default)|
           cast_type = cast_type[type_for_attribute(name)] if Proc === cast_type
+          raise UnknownAttributeError.new(self, name) if Enum::EnumType === cast_type && !columns_hash.key?(name)
```
Comment (byroot) [inline activerecord/lib/active_record/attributes.rb:267]: Ideally we'd do this from the `Enum` module. You can redefine `load_schema!` there and call `super`.

File: activerecord/test/cases/enum_test.rb [hunk 3]
```diff
@@ -1006,4 +1006,17 @@ def self.name
...
+  test "raises for columnless enums" do
+    klass = Class.new(ActiveRecord::Base) do
+      def self.name
+        "Book"
+      end
+      enum columnless_genre: [:adventure, :comic]
+    end
+
+    assert_raises(ActiveRecord::UnknownAttributeError) do
+      klass.columns # load schema
```
[the remark this answers is not in the document]
Comment (fatkodima) [reply activerecord/test/cases/enum_test.rb:1019]: Yes, we can. I think this is fine. If other changes will be needed, I will update this too.

**Comment by fatkodima** [comment]
I also updated several failed schema statements tests to use another model, because the `Book` has several enums and when changing table name, the schema needs to be reloaded and thus that tests are failing.

File: activerecord/test/cases/enum_test.rb [hunk 4]
```diff
@@ -1006,4 +1006,17 @@ def self.name
...
+
+  test "raises for columnless enums" do
+    klass = Class.new(ActiveRecord::Base) do
+      def self.name
+        "Book"
+      end
+      enum columnless_genre: [:adventure, :comic]
+    end
+
+    assert_raises(ActiveRecord::UnknownAttributeError) do
```
Comment (byroot) [inline activerecord/test/cases/enum_test.rb:1018]: Would be good to assert on the error message, I'd like to see if it's somewhat actionable given that the backtrace won't point to the source of the error.

File: activerecord/test/cases/statement_cache_test.rb [hunk 5]
```diff
@@ -112,29 +112,29 @@ def test_unprepared_statements_dont_share_a_cache_with_prepared_statements
     end
 
     def test_find_by_does_not_use_statement_cache_if_table_name_is_changed
-      book = Book.create(name: "my book")
```
Comment (simi) [inline activerecord/test/cases/statement_cache_test.rb:115]: Maybe inline model would be easier to use in here, since there will be no need for cleanup. :thinking:

File: activerecord/test/cases/enum_test.rb (hunk 4 above)
Comment (fatkodima) [reply activerecord/test/cases/enum_test.rb]: Good idea. We can not use `ActiveRecord::UnknownAttributeError` here, because it is for use with the actual records. So changed this too.

File: activerecord/test/cases/enum_test.rb (hunk 3 above)
[the remark this answers is not in the document]
Comment (fatkodima) [reply activerecord/test/cases/enum_test.rb:1019]: Left as is, `load_schema!` is a private api, which is used by `load_schema` which is a private method and does extra things. Better to be at a safe place. And this is the way schema is loaded in tests, as I have seen previously.

File: activerecord/lib/active_record/enum.rb [hunk 6]
```diff
@@ -121,6 +121,13 @@ def inherited(base) # :nodoc:
       super
     end
 
+    def load_schema! # :nodoc:
+      attributes_to_define_after_schema_loads.each do |name, (cast_type, _default)|
+        cast_type = cast_type[type_for_attribute(name)] if Proc === cast_type
+        raise "Unknown attribute '#{name}' for #{self.name}" if Enum::EnumType === cast_type && !columns_hash.key?(name)
```
Comment (byroot) [inline activerecord/lib/active_record/enum.rb:127]:
```suggestion
        unless columns_hash.key?(name)
          cast_type = cast_type[type_for_attribute(name)] if Proc === cast_type
          raise UnknownAttributeError.new(self, name) if Enum::EnumType === cast_type
        end
```

A bit of a nitpick, but since we expect this not to happen, it may make sense to optimize for the columns to exist.

Comment (byroot) [reply activerecord/lib/active_record/enum.rb:127]: Also maybe we should mention `enum` in the error message to make it easier to realize the source of the error is a faulty `enum` definition.

**Comment by fatkodima** [comment]
@byroot this is ready to merge.

**Comment by arianf** [comment]
I feel like `db:migrate` shouldn't throw this error, but it currently does...
