### PR TITLE
Stop logging all noisy stack trace when actual trace is empty and simply point where to configure trace

### LINKED ISSUE #24434: Rails.backtrace_cleaner.add_silencer doesn't work, but filters do
### Steps to reproduce

in initializers/backtrace_silencers.rb

`Rails.backtrace_cleaner.add_silencer { |line| line =~ /lib/ }`

and restart the server
### Expected behavior

I expect to see in log file only

`ActionController::RoutingError (No route matches [GET] "/admin/roles")`

 but
### Actual behaviour

```
  ActionController::RoutingError (No route matches [GET] "/admin/roles"):
  actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:21:in 'call'
  actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in 'call'
  railties (4.1.8) lib/rails/rack/logger.rb:38:in 'call_app'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in 'block in call'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in 'block in tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in 'tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in 'tagged'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in 'call'
```

In the same time `Rails.backtrace_cleaner.add_filter { |line| line.sub('lib', '') }` works exactly as expected.

It seems I am not alone:

http://stackoverflow.com/questions/28836767/backtrace-silencer-not-working
http://stackoverflow.com/questions/35879335/how-to-prevent-logging-rails-stack-trace/
http://stackoverflow.com/questions/29169059/rails-backtrace-silencers-do-not-work-while-filters-do
### System configuration

**Rails version - 4.1.8, 4.2.6**:

**Ruby version - 2.2.1**:

### LINKED ISSUE #25219: Backtrace silencing should happen even against a pure framework trace
When an exception is raised where the backtrace doesn't include user code, we default to showing the whole thing. That results in stuff like this:

```
irb(main):011:0> eit
NameError: undefined local variable or method `eit' for main:Object
Did you mean?  exit
	from (irb):11
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/console.rb:65:in `start'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/david/Code/demos/blog/bin/rails:9:in `<top (required)>'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/commands/rails.rb:6:in `call'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:191:in `block in serve'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:161:in `fork'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:161:in `serve'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

That's not a reasonable response to something so simple. I'd like to see:

```
irb(main):011:0> eit
NameError: undefined local variable or method `eit' for main:Object
Did you mean?  exit
[Backtrace silenced by Rails. Tweak config/initializers/backtrace_silencer.rb if needed]
```

### PR DESCRIPTION
**Pull request by vipulnsward**
r? @dhh 

First pass at: Stop logging all noisy stack trace when actual trace is empty and simply point where to configure trace.

Fixes #25219
See also #24434

### CODE REVIEW

File: actionpack/lib/action_dispatch/middleware/debug_exceptions.rb [hunk 1]
```diff
@@ -146,14 +146,15 @@ def render(status, body, format)
       [status, {'Content-Type' => "#{format}; charset=#{Response.default_charset}", 'Content-Length' => body.bytesize.to_s}, [body]]
     end
 
+    EMPTY_BACKTRACE_MESSAGE = ["[Backtrace silenced by Rails. Tweak config/initializers/backtrace_silencer.rb if needed]"]
```
Comment (dhh) [inline actionpack/lib/action_dispatch/middleware/debug_exceptions.rb]: Let's get a little more specific: `[Framework-specific backtrace silenced by Rails. Tweak config/initializers/backtrace_silencer.rb if needed]`.

**Comment by matthewd** [comment]
I don't understand how this is an improvement. If something has gone wrong in the framework code, the first thing anyone will need in order to diagnose it is the framework backtrace; this just seems likely to result in people turning off the silencer, then being worse off on normal application errors.

(This change is unrelated to @dhh's issue in #25219 -- that's about an error in the console, caused by a typo. This is about suppressing the backtrace when something goes wrong inside, say, Action Controller... or perhaps more likely, some third party gem's middleware.)

**Comment by dhh** [comment]
It's to address #24434 as well. We might have said "that's expected behavior", but I think that's a wrong expected behavior. We shouldn't be exposing the user to a framework trace when the exception is part of the public interface (rather than because Rails died unexpectedly inside itself).

**Comment by matthewd** [comment]
Yeah, agreed on the public-interface exception. But I'd hope we can do a better job of distinguishing them than simply assume any exception from inside the framework is capable of standing on its own, devoid of context.

Actually, are there exceptions other than RoutingError for which this is true? That particular exception is raised *in this very middleware*, so giving it special treatment isn't unreasonable... in fact, [we already do](https://github.com/rails/rails/blob/5-0-stable/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb#L124).

**Comment by dhh** [comment]
Yeah, that's all fair. If we can close all the public-interface exceptions,
console/routing/whatever, then I'm happy to see that path play out as well.
Though I'll say it's been a very long time since I've seen a genuine
framework error bubble up through user code like this as well.

**Comment by vipulnsward** [comment]
Yes, as pointed out, I haven't addressed the console scenario. I am looking into it, and its a bit tricky than middlewares. IRB has its own cleanup  https://github.com/ruby/ruby/blob/trunk/lib/irb/workspace.rb#L91-L110 . I am trying to see if we can hook into it cleanly.

**Comment by gsamokovarov** [comment]
I have something similar for web-console, when evaluating code in it: https://github.com/rails/web-console/blob/master/lib/web_console/evaluator.rb. You may try something similar providing an interface like `Binding` (e.g. `#eval`) and doing the cleanup there. E.g. wrap the `TOPLEVEL_BINDING` in this self-cleaning object and pass it straight to IRB when starting it.

**Comment by vipulnsward** [comment]
Sweet. Thanks, let me see.

**Comment by gsamokovarov** [comment]
Although, there seem to be type checks in the IRB code, so this approach may not be feasible. 😞  Anyway, just an idea. 😄

**Comment by vipulnsward** [comment]
@matthewd @dhh this takes care of the filtering/cleaning, and uses existing setup, config, etc. Do we want to go down this path for cleanup on console?

```ruby
module IRB # :nodoc:
  class WorkSpace # :nodoc:
    alias :orig_filter_backtrace :filter_backtrace
    def filter_backtrace(bt)
      res = orig_filter_backtrace(bt)
      res = Rails.backtrace_cleaner.clean([res.to_s])[0]
      res
    end
  end
end
```

File: railties/lib/rails/commands/console.rb [hunk 2]
```diff
@@ -7,6 +7,12 @@ module Rails
   class Console
     include ConsoleHelper
 
+    module BacktraceCleaner
+      def filter_backtrace(bt)
+        (v = super) && Rails.backtrace_cleaner.filter([v]).first
```
Comment (gsamokovarov) [inline railties/lib/rails/commands/console.rb]: A small cosmetic nit: we can avoid reverencing the named argument, as we are not using it (may avoid Ruby warnings). We can also make the condition a bit more explicit.

```ruby
def filter_backtrace(_)
  if v = super
    Rails.backtrace_cleaner.filter([v]).first
  end
end
```

**Comment by vipulnsward** [comment]
Updated.
@matthewd 
- This doesn't collide with pry/debug etc, they have a wrapper around for exception trapping and don't rely on our console.
- I tried to add some test for this, but its a bit unusual since it goes to interactive mode. There are no related tests on https://github.com/ruby/ruby/tree/trunk/test/irb that could be used for reference.

I believe the plan of action is to get https://github.com/rails/rails/pull/25343 in first and then this.

**Comment by matthewd** [comment]
@vipulnsward this PR is changing two things that are only very loosely related; better to split it in two. (Particularly as I'm not yet sold on the non-irb change being the right approach. And it has nothing to do with the original issue description in #25219.)

We also still need the "and then" part of my proposed plan here.

**Comment by vipulnsward** [comment]
Cool, let me create a new PR for that change and discussion. I will restrict this one for IRB changes.

File: railties/lib/rails/commands/console.rb [hunk 3]
```diff
@@ -7,6 +7,14 @@ module Rails
   class Console
     include ConsoleHelper
 
+    module BacktraceCleaner
+      def filter_backtrace(bt)
+        if _res = super
```
Comment (matthewd) [inline railties/lib/rails/commands/console.rb]: Why the underscore / abbr?

**Comment by vipulnsward** [comment]
Updated to just have the backtrace cleaner for IRB

**Comment by matthewd** [comment]
:heart:

The "and then" I mentioned above is amending https://github.com/rails/rails/blob/master/railties/lib/rails/backtrace_cleaner.rb#L5 so it considers `(irb)` to be 'application code'. (Maybe we should just match on `/^\(/`. That'd be good for pry... do we know of anything else that uses a `(foo)`-style fake filename?)

File: railties/test/backtrace_cleaner_test.rb [hunk 4]
```diff
@@ -1,24 +1,37 @@
...
+
+  test "should consider traces from irb lines as User code" do
+    backtrace = [ "from (irb):1",
+                  "from /Path/to/rails/railties/lib/rails/commands/console.rb:77:in `start'",
+                  "from /Path/to/rails/railties/lib/rails/commands/console_helper.rb:9:in `start'",
+                  "from /Path/to/rails/railties/lib/rails/commands/commands_tasks.rb:78:in `console'",
+                  "from /Path/to/rails/railties/lib/rails/commands/commands_tasks.rb:49:in `run_command!'",
+                  "from /Path/to/rails/railties/lib/rails/commands.rb:18:in `<top (required)>'",
+                  "from bin/rails:4:in `require'",
+                  "from bin/rails:4:in `<main>'" ]
```
Comment (matthewd) [inline railties/test/backtrace_cleaner_test.rb]: That's a lot of array, given the following assertion is only checking that the first entry survives :smile:

File: railties/test/backtrace_cleaner_test.rb [hunk 5]
```diff
@@ -1,24 +1,32 @@
...
+      backtrace = [ "#{target_dir}/gems/nosuchgem-1.2.3/lib/foo.rb" ]
+      result = @cleaner.clean(backtrace, :all)
+      assert_equal "nosuchgem (1.2.3) lib/foo.rb", result[0]
     end
   end
+
+  test "should consider traces from irb lines as User code" do
+    backtrace = [ "from (irb):1",
+                  "from /Path/to/rails/railties/lib/rails/commands/console.rb:77:in `start'",
+                  "from bin/rails:4:in `<main>'" ]
```
Comment (vipulnsward) [inline railties/test/backtrace_cleaner_test.rb]: Pushed a variant to just have three different kind of traces 😄

**Comment by kaspth** [comment]
@vipulnsward 👏

**Comment by chiefbigfro** [comment]
@matthewd @dhh apologize for being so late to the party, but I don't think we're getting the the behavior intended re: app traces versus stack traces ...

@matthewd wrote

>Actually, are there exceptions other than RoutingError for which this is true? That particular exception is raised in this very middleware, so giving it special treatment isn't unreasonable... in fact, we already do.

which points to

```
      trace_to_show = 'Application Trace'
      if traces[trace_to_show].empty? && wrapper.rescue_template != 'routing_error'
        trace_to_show = 'Full Trace'
      end
```
**_But_**, I'm pretty sure that means I shouldn't be getting this:

```
15:11:11 web.1       | ActionController::RoutingError (No route matches [GET] "/uploads/store/user_avatars/f09944d311.jpg"):
15:11:11 web.1       |   
15:11:11 web.1       | actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
15:11:11 web.1       | actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
15:11:11 web.1       | railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
15:11:11 web.1       | railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
15:11:11 web.1       | activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
15:11:11 web.1       | activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
15:11:11 web.1       | activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
```

**Comment by matthewd** [comment]
Yeah, it looks like that change (https://github.com/rails/rails/issues/24434) fell off the radar: [this line](https://github.com/rails/rails/blob/8b89415f5dab0bcec8acd110774a53dd9d05a491/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb#L166) needs an extra condition to make it more like [the one you quoted](https://github.com/rails/rails/blob/8b89415f5dab0bcec8acd110774a53dd9d05a491/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb#L134). The above is used to decide whether/which trace to show in the HTML response, but the decision for the log is made separately.
