### PR TITLE
Fix casting long strings to Date, Time or DateTime

### LINKED ISSUE #45003: ActiveModel::Type::Date raises for strings longer than 128 characters
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activemodel", "~> 7.0.0"

end

require "active_model"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    assert_nil ActiveModel::Type::Date.new.cast(" " * 129)
  end
end
```

### Expected behavior
An invalid string longer than 128 characters should parse to `nil`. 

### Actual behavior
It raises an error: `ArgumentError: string length (129) exceeds the limit 128`.

### System configuration
**Rails version**: 7.0.2.4

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

### PR DESCRIPTION
**Pull request by fatkodima**
128 is a [default value for `_parse`](https://ruby-doc.org/stdlib-3.1.2/libdoc/date/rdoc/Date.html#method-c-_parse).

Closes #45003

### CODE REVIEW

File: activemodel/lib/active_model/type/date.rb [hunk 1]
```diff
@@ -52,8 +52,8 @@ def fast_string_to_date(string)
           end
         end
 
-        def fallback_string_to_date(string)
-          new_date(*::Date._parse(string, false).values_at(:year, :mon, :mday))
+        def fallback_string_to_date(string, limit: 128)
+          new_date(*::Date._parse(string, false, limit: limit).values_at(:year, :mon, :mday)) if string.length <= limit
```
Comment (jonathanhefner) [inline activemodel/lib/active_model/type/date.rb:56]: Since strings longer than the limit are likely a rare mistake, what do you think about simply rescuing the error?  e.g.:

```suggestion
        def fallback_string_to_date(string)
          parts = begin
            ::Date._parse(string, false)
          rescue ArgumentError
          end

          new_date(*parts.values_at(:year, :mon, :mday)) if parts
```

It's more verbose, but it doesn't tie us to a specific limit.  So if Ruby changes the contract of `Date._parse` again in the future, we may be covered.

Comment (fatkodima) [reply activemodel/lib/active_model/type/date.rb:56]: I'm not sure I'm comfortable rescuing generic exceptions like `ArgumentError`, even though this pattern is popular in the rails codebase. What do you think about at least matching an error message?

This is not very probably that the ruby will change `_parse` method signature, but in this case suggested approach  will potentially also have problems and we will get `ArgumentError` for another reason than we originally intended.

Comment (jonathanhefner) [reply activemodel/lib/active_model/type/date.rb:56]: I am also a bit wary of rescuing `ArgumentError`.  But my thinking was: if Ruby reduces the set of accepted inputs again (whether by changing the limit or adding some other default argument), then our response would be same -- we would prevent the error from bubbling up, and return nil.

I feel like matching on the error message may be too fragile (more so than rescuing `ArgumentError`).

**Review by byroot — APPROVED** [review]
👍 

Can you squash your commits please? Also it's likely worth a Changelog entry.

**Comment by fatkodima** [comment]
@byroot squashed and updated changelog.
