### PR TITLE
Fix io copy stream raises type error when writing

### LINKED ISSUE #57186: IO.copy_stream raises TypeError when writing to ActionController::Live::Buffer
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"
require "minitest/autorun"
require "rack/test"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.root = __dir__
  config.eager_load = false
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
end
Rails.application.initialize!

Rails.application.routes.draw do
  get "/", to: "test#index"
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers
  include ActionController::Live

  def index
    sio = StringIO.new("Ho")
    IO.copy_stream sio, response.stream
    response.stream.write "me"
  ensure
    response.stream.close
  end
end

class BugTest < ActiveSupport::TestCase
  include Rack::Test::Methods

  def test_copy_stream_works
    get "/"    
    
    assert_equal "Home", last_response.body
  end

  private
    def app
      Rails.application
    end
end

```

### Expected behavior

IO.copy_stream successfully writes to the stream without errors.

### Actual behavior

copy_stream does write to the stream, but a TypeError is raised and the stream is broken.
Note that in the test, `response.stream` is a `ActionDispatch::Response::Buffer`, and in a production environment with Puma, it is a `ActionController::Live::Buffer`, but both cases fail.

Error message: 

<details><summary>Details</summary>
<p>

```
I, [2026-04-14T13:19:25.022881 #424842]  INFO -- : Completed 500 Internal Server Error in 0ms (GC: 0.0ms)


F, [2026-04-14T13:19:25.023506 #424842] FATAL -- :
IOError (closed stream):
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_dispatch/http/response.rb:149:in `write'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/live.rb:328:in `rescue in block (3 levels) in process'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/live.rb:325:in `block (3 levels) in process'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/activesupport-8.1.3/lib/active_support/isolated_execution_state.rb:68:in `share_with'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/live.rb:323:in `block (2 levels) in process'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/activesupport-8.1.3/lib/active_support/concurrency/share_lock.rb:161:in `sharing'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/activesupport-8.1.3/lib/active_support/dependencies/interlock.rb:42:in `running'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/live.rb:316:in `block in process'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/live.rb:408:in `block in new_controller_thread'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/concurrent-ruby-1.3.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:382:in `run_task'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/concurrent-ruby-1.3.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:372:in `block (3 levels) in create_worker'
  <internal:kernel>:187:in `loop'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/concurrent-ruby-1.3.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:361:in `block (2 levels) in create_worker'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/concurrent-ruby-1.3.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:358:in `catch'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/concurrent-ruby-1.3.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:358:in `block in create_worker'


F, [2026-04-14T13:19:25.023566 #424842] FATAL -- :
TypeError (no implicit conversion of Array into Integer):
  action_controller.rb:38:in `copy_stream'
  action_controller.rb:38:in `index'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/basic_implicit_render.rb:8:in `send_action'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/abstract_controller/base.rb:221:in `process_action'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/rendering.rb:199:in `process_action'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/abstract_controller/callbacks.rb:267:in `block in process_action'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/activesupport-8.1.3/lib/active_support/callbacks.rb:110:in `run_callbacks'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/abstract_controller/callbacks.rb:266:in `process_action'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/rescue.rb:36:in `process_action'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/instrumentation.rb:76:in `block in process_action'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/activesupport-8.1.3/lib/active_support/notifications.rb:210:in `block in instrument'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/activesupport-8.1.3/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/activesupport-8.1.3/lib/active_support/notifications.rb:210:in `instrument'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/instrumentation.rb:75:in `process_action'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/abstract_controller/base.rb:154:in `process'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionview-8.1.3/lib/action_view/rendering.rb:40:in `process'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/live.rb:324:in `block (3 levels) in process'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/activesupport-8.1.3/lib/active_support/isolated_execution_state.rb:68:in `share_with'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/live.rb:323:in `block (2 levels) in process'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/activesupport-8.1.3/lib/active_support/concurrency/share_lock.rb:161:in `sharing'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/activesupport-8.1.3/lib/active_support/dependencies/interlock.rb:42:in `running'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/live.rb:316:in `block in process'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/actionpack-8.1.3/lib/action_controller/metal/live.rb:408:in `block in new_controller_thread'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/concurrent-ruby-1.3.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:382:in `run_task'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/concurrent-ruby-1.3.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:372:in `block (3 levels) in create_worker'
  <internal:kernel>:187:in `loop'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/concurrent-ruby-1.3.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:361:in `block (2 levels) in create_worker'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/concurrent-ruby-1.3.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:358:in `catch'
  /home/develop/.rvm/gems/ruby-3.3.7/gems/concurrent-ruby-1.3.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:358:in `block in create_worker'

```

</p>
</details> 

### System configuration

**Rails version**: 8.1.3
**Ruby version**: 3.3.7

### PR DESCRIPTION
**Pull request by joaoGabriel55**
### Motivation / Background

Fixes: https://github.com/rails/rails/issues/57186

`IO.copy_stream(src, response.stream)` raised a `TypeError: no implicit conversion of Array into Integer` when writing to Rails response stream buffers. This is because `Buffer#write` was returning the buffer array (result of `Array#push`) instead of an Integer representing bytes written, which is what `IO.copy_stream` expects from a destination `write` method.

A second, silent data-corruption bug was also present: `IO.copy_stream` reuses its internal string buffer after each call to `write` returns. Since `Buffer#write` stored the passed string by reference rather than duplicating it first, the buffered content could be mutated after being enqueued, silently corrupting the response body.

Both `ActionDispatch::Response::Buffer#write` and `ActionController::Live::Buffer#write` were affected.

### Detail

This Pull Request changes `Buffer#write` in two places:

**`ActionDispatch::Response::Buffer#write`** (`actionpack/lib/action_dispatch/http/response.rb`):
- Pushes `string.dup` onto the buffer instead of the original reference, preventing `IO.copy_stream`'s internal buffer reuse from corrupting already-enqueued chunks.
- Returns `string.bytesize` so that `IO.copy_stream` (and any other `IO`-compatible consumer) receives the expected Integer return value.

**`ActionController::Live::Buffer#write`** (`actionpack/lib/action_controller/metal/live.rb`):
- Returns `string.bytesize` for the same reason.

Tests are added for both classes to verify:
1. `#write` returns the correct byte count.
2. `IO.copy_stream` produces the correct response body without corruption.

### Additional information

`IO.copy_stream` documents that the destination's `write` method must return the number of bytes written (an Integer). The root cause was that `Array#push` returns the array itself, which propagated back as the return value of `Buffer#write`, causing `IO.copy_stream` to raise immediately.

Affects Rails 8.1.3 / Ruby 3.3.7 and likely all prior versions.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: actionpack/lib/action_dispatch/http/response.rb [hunk 1]
```diff
@@ -150,7 +150,8 @@ def write(string)
 
         @str_body = nil
         @response.commit!
-        @buf.push string
+        @buf.push string.dup
```
Comment (joaoGabriel55) [inline actionpack/lib/action_dispatch/http/response.rb]: Does this `.dup` solution can cause performance side-effects? 🤔

Comment (byroot) [reply actionpack/lib/action_dispatch/http/response.rb]: Should be minor.
