### PR TITLE
Handle nil key for MemCacheStore#normalize_key

### LINKED ISSUE #41352: Logging breaks Rails.cache.read_multi when no arguments are passed and the :mem_cache_store adapter is being used
### Steps to reproduce

Here's a (mostly) [working example repository](https://github.com/patbl/test-app-6.1).

1. `rails _6.1.1_ new test-app-6.1`
2. Apply [this diff](https://github.com/patbl/test-app-6.1/commit/c8be8eb934fb8880a6ae95ccbb0dea1cc48f58aa):

```diff
diff --git a/Gemfile b/Gemfile
index 1beee36..9144005 100644
--- a/Gemfile
+++ b/Gemfile
@@ -54,3 +54,4 @@ end

 # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
 gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
+gem 'dalli'
diff --git a/Gemfile.lock b/Gemfile.lock
index aa632a0..82ecabc 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -78,6 +78,7 @@ GEM
     childprocess (3.0.0)
     concurrent-ruby (1.1.8)
     crass (1.0.6)
+    dalli (2.7.11)
     erubi (1.10.0)
     ffi (1.14.2)
     globalid (0.4.2)
@@ -207,6 +208,7 @@ DEPENDENCIES
   bootsnap (>= 1.4.4)
   byebug
   capybara (>= 3.26)
+  dalli
   jbuilder (~> 2.7)
   listen (~> 3.3)
   puma (~> 5.0)
diff --git a/config/environments/development.rb b/config/environments/development.rb
index 7a9f6c3..a113ff6 100644
--- a/config/environments/development.rb
+++ b/config/environments/development.rb
@@ -14,21 +14,7 @@ Rails.application.configure do
   # Show full error reports.
   config.consider_all_requests_local = true

-  # Enable/disable caching. By default caching is disabled.
-  # Run rails dev:cache to toggle caching.
-  if Rails.root.join('tmp', 'caching-dev.txt').exist?
-    config.action_controller.perform_caching = true
-    config.action_controller.enable_fragment_cache_logging = true
-
-    config.cache_store = :memory_store
-    config.public_file_server.headers = {
-      'Cache-Control' => "public, max-age=#{2.days.to_i}"
-    }
-  else
-    config.action_controller.perform_caching = false
-
-    config.cache_store = :null_store
-  end
+  config.cache_store = :mem_cache_store, '127.0.0.1:11211:1'

   # Store uploaded files on the local file system (see config/storage.yml for options).
   config.active_storage.service = :local
```
3. Ensure Memcached is running at the specified address.
4. In a Rails console, run `ActiveSupport::Cache::Store.logger = Rails.logger`.

### Expected behavior

In a Rails console, `Rails.cache.read_multi` should return `{}`:

```
irb(main):001:0> Rails.cache.read_multi
=> {}
```

### Actual behavior

An exception (```NoMethodError (undefined method `force_encoding' for nil:NilClass)```) is raised:

```
irb(main):001:0> ActiveSupport::Cache::Store.logger = Rails.logger
=> #<ActiveSupport::Logger:0x000000000368d938 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x000000000368dbb8 @datetime_format=nil>,...
irb(main):002:0> Rails.cache.read_multi
Traceback (most recent call last):
        1: from (irb):2
NoMethodError (undefined method `force_encoding' for nil:NilClass)
irb(main):003:0> puts $!.backtrace
/home/ubuntu/code/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/cache/mem_cache_store.rb:189:in `normalize_key'
/home/ubuntu/code/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/cache.rb:715:in `instrument'
/home/ubuntu/code/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/cache.rb:392:in `read_multi'
(irb):2:in `irb_binding'
```

### System configuration
**Rails version**: 6.1.1

**Ruby version**: 2.7.2.

### PR DESCRIPTION
**Pull request by fatkodima**
Closes #41352  

There is already an existing test case for this 
https://github.com/rails/rails/blob/8db3fefac00eb642357656d792516ffba1d25751/activesupport/test/cache/behaviors/cache_store_behavior.rb#L113-L117

But it passed for memcached because of `@store.silence!` and the relevant branch with a bug was skipped.

### CODE REVIEW

File: activesupport/lib/active_support/cache/mem_cache_store.rb [hunk 1]
```diff
@@ -188,10 +188,12 @@ def delete_entry(key, **options)
...
         def normalize_key(key, options)
-          key = super.dup
-          key = key.force_encoding(Encoding::ASCII_8BIT)
-          key = key.gsub(ESCAPE_KEY_CHARS) { |match| "%#{match.getbyte(0).to_s(16).upcase}" }
-          key = "#{key[0, 212]}:hash:#{ActiveSupport::Digest.hexdigest(key)}" if key.size > 250
+          key = super
+          if key
+            key = key.dup.force_encoding(Encoding::ASCII_8BIT)
+            key = key.gsub(ESCAPE_KEY_CHARS) { |match| "%#{match.getbyte(0).to_s(16).upcase}" }
+            key = "#{key[0, 213]}:md5:#{ActiveSupport::Digest.hexdigest(key)}" if key.size > 250
```
Comment (rafaelfranca) [inline activesupport/lib/active_support/cache/mem_cache_store.rb:195]: you change here the key format back to md5. Next time please make sure the patch is up-to-date

Comment (fatkodima) [reply activesupport/lib/active_support/cache/mem_cache_store.rb:195]: Oops. Sorry 💦
