### PR TITLE
Fix `wait_timeout` to configurable for mysql2 adapter

### LINKED ISSUE #26556: No way to specify wait_timeout via DATABASE_URL for mysql2
### Steps to reproduce

Using the mysql2 gem, open a console with DATABASE_URL using `wait_timeout` configuration, e.g.:

`DATABASE_URL="mysql2://localhost:3306/test-db?wait_timeout=60&checkout_timeout=42" bundle exec rails console`

```
pry(main)> ActiveRecord::Base.connection.execute("SHOW VARIABLES LIKE \"wait_timeout\"").to_a
=> [["wait_timeout", "2147483"]]
```

I believe the culprit is the Integer/Fixnum check [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L848), which was introduced as some sort of backwards compatibility, because `wait_timeout` was also used by the connection pool configuration.

There is no way to get the parameter typed as `Integer` when using a DATABASE_URL, which seems like undesirable behaviour from my point of view. 
### Expected behavior

The configured `wait_timeout` should be 60 all connections.
### Actual behavior

The configured `wait_timeout` is the default of 2147483 on all connections.
### System configuration

**Rails version**:
Tested with ActiveRecord 4.2.7.1, possibly more versions affected.

**Ruby version**:
Tested with ruby 2.3.1

### PR DESCRIPTION
**Pull request by kamipo**
Fixes #26556.

### CODE REVIEW

**Comment by pixeltrix** [comment]
A couple of points:

1. The test doesn't really address #26556 - I'd prefer if we were testing via DATABASE_URL, but if it's a lot of work to setup then it's probably okay.

2. I think this warrants a CHANGELOG entry, can you add one - thanks.

File: activerecord/test/cases/adapters/mysql2/connection_test.rb [hunk 1]
```diff
@@ -85,6 +85,22 @@ def test_active_after_disconnect
...
+    run_without_connection do |orig_connection|
+      ActiveRecord::Base.establish_connection(orig_connection.merge(wait_timeout: "60"))
+      result = ActiveRecord::Base.connection.select_value("SELECT @@SESSION.wait_timeout")
+      assert_equal 60, result
+    end
+  end
+
+  def test_wait_timeout_as_url
+    run_without_connection do |orig_connection|
+      ActiveRecord::Base.establish_connection(orig_connection.merge("url" => "mysql2:///?wait_timeout=60"))
```
Comment (kamipo) [inline activerecord/test/cases/adapters/mysql2/connection_test.rb]: @pixeltrix Testing connection via `DATABASE_URL` is hard to me.
Actually `DATABASE_URL` is merged to `config["url"]`.

https://github.com/rails/rails/blob/0ce641839aa59d8c8306ec21cfd5f31aaa9b169c/activerecord/lib/active_record/connection_handling.rb#L76-L79

So I added a `test_wait_timeout_as_url` instead.
How about it?

**Comment by rafaelfranca** [comment]
Backported in e269aedf5f and 86ec05b55c
