### PR TITLE
handle long or duplicated screenshot filenames

### LINKED ISSUE #32346: Errno::ENAMETOOLONG on system test screenshot
### Steps to reproduce

Have a sufficiently long series of describes/contexts such that their combined name causes the error. One example from my app is 
```
Errno::ENAMETOOLONG:
              File name too long @ rb_sysopen - /home/circleci/project/tmp/screenshots/failures_r_spec_example_groups_client_exports_a_csv_of_exceptions_by_visiting_the_exception_report_page_and_clicking_export_to_csv_and_filling_out_the_export_form_with_valid_information_and_clicking_download_downloads_a_file_named_"exception_report_csv"_599.png
```

### Expected behavior

Screenshot should save successfully in some fashion without error - maybe by truncating the name?

### Actual behavior

`Errno::ENAMETOOLONG` error and no screenshot saved.

### System configuration
**Rails version**: 5.1.5

**Ruby version**: 2.5.0

### PR DESCRIPTION
**Pull request by JosieMcClellan**
Fixes #32346

Long screenshot filenames in system tests had been throwing `Errno::ENAMETOOLONG`. This was mostly a problem with a Linux/RSpec combo because the EXT4 filesystem limits filenames to 255 characters, and RSpec Rails uses the full `describe`/`context`/`it` nesting in the filename. This commit rescues `Errno::ENAMETOOLONG` and truncates the name to its first 225 characters plus the seconds since epoch.

This commit also handles duplicate filenames, which become more common when truncating. E.g, a long `describe`/`context` nesting may have the same first 225 chars for many tests. It was already possible though, especially with multiple manual screenshots:
```ruby
take_screenshot
click_on(something) # I'm trying to isolate this effect
take_screenshot
```
With this commit, duplicate filenames have a unique suffix appended instead of overwriting the existing file.

Other changes:
- improve testing slightly
  - address some previously untested behavior
  - make a few tests more isolated
  - break down some lib methods to make them more testable
- remove `#absolute_image_path` because `#image_path` had become absolute
- tiny refactors

### CODE REVIEW

File: actionpack/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb [hunk 1]
```diff
@@ -34,54 +34,70 @@ def take_screenshot
...
+            prefix = "failures_" if failed? # else nil
+            "#{prefix}#{filename_base}#{@screenshot_unique_suffix}.png"
+          end
+
+          def filename_base
+            @screenshot_filename_base ||= method_name
+          end
 
-            # Default to outputting a path to the screenshot
-            output_type ||= "simple"
```
Comment (oniofchaos) [inline actionpack/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb]: I don't see this logic anymore, is that intended?

Comment (JosiMcClellan) [reply actionpack/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb]: I'm new to open source, so I apologize if I overstepped what I should change. It seemed the `"simple"` value wasn't actually used for anything; only the special values `"artifact"` and `"inline"` were used. I'm happy to put "simple" back as the default.

**Review by eileencodes — CHANGES_REQUESTED** [review]
Hey @JosiMcClellan thanks for opening your first PR to Rails. I know you're new so don't take this personally but I think the changes here are a lot broader than they need to be.

Do we know the max length that is allowed by the filename? I think in that case we should auto-truncate the name before we even get a `ENAMETOOLONG` error.

**Comment by JosiMcClellan** [comment]
Thank you for the review. I put back simple and started truncating immediately. Is there anything else covered by "broader than they needed to be" that I should undo? Or, I could go back and really just change the bare minimum to add truncation... which would just be adding `[0...225]` I think

**Comment by eileencodes** [comment]
Sorry for being unclear - yea I meant to undo everything and just make the bare minimum changes to limit the filename length.

**Comment by JosiMcClellan** [comment]
Okay, this one is the bare minimum. Thanks for taking the time to help me learn.

**Review by eileencodes — APPROVED** [review]

**Comment by eileencodes** [comment]
Thank you!
