### PR TITLE
[AR] Fix result with anonymous PG columns of different type from json

### LINKED ISSUE #45758: ActiveRecord 6.1 and JSONB: Incorrect results value/type when using both arrow operator and double arrow operator in the same SELECT statement
### Issue Description

Generally when using JSONB operators `->` (arrow operator) and `->>` (double arrow operator) in SELECT statement, 
ActiveRecord returns correct result types: objects for `->` operator and string for `->>` operator.
But when using both operators in the same select statement, the returned results may have an unexpected type or be `nil`.

### Steps to reproduce with Expected behaviour in tests and Actual behaviour in comments

```ruby
# file: activerecord_6_1_jsonb_test.rb
# run: ruby activerecord_6_1_jsonb_test.rb

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", "6.1.6.1" # the same behaviour for version "7.0.3.1"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

pg_opts = {adapter: "postgresql", database: "jsonb_activerecord_issue"}
begin
  ActiveRecord::Base.establish_connection(pg_opts.except(:database))
  ActiveRecord::Base.connection.create_database(pg_opts[:database])
  puts "Database #{pg_opts[:database]} was created."
rescue => ActiveRecord::DatabaseAlreadyExists
  puts "Database #{pg_opts[:database]} alredy exists."
end
ActiveRecord::Base.establish_connection(pg_opts)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :entries, force: true do |t|
    t.jsonb :value
  end
end

class Entry < ActiveRecord::Base
end
Entry.create(value: {a: "a", b: "b", c: {}})

class BugTest < Minitest::Test
  # passed
  def test_jsonb_arrow_operator
    assert_equal [["a", "b"]], Entry.pluck(Arel.sql("value->'a', value->'b'"))
    assert_equal [[{}, "b"]], Entry.pluck(Arel.sql("value->'c', value->'b'"))
  end

  # passed
  def test_jsonb_double_arrow_operator
    assert_equal [["a", "b"]], Entry.pluck(Arel.sql("value->>'a', value->>'b'"))
    assert_equal [["{}", "b"]], Entry.pluck(Arel.sql("value->>'c', value->>'b'"))
  end

  # failed (this test results are differ in activerecord 6.0)
  def test_jsonb_arrow_operator_and_double_arrow_operator
    assert_equal [["a", "b"]], Entry.pluck(Arel.sql("value->'a', value->>'b'")) # Actual [["a", nil]]
    assert_equal [[{}, "b"]], Entry.pluck(Arel.sql("value->'c', value->>'b'")) # Actual [[{}, nil]]
  end

  # failed
  def test_jsonb_double_arrow_operator_and_arrow_operator
    assert_equal [["a", "b"]], Entry.pluck(Arel.sql("value->>'a', value->'b'")) # Actual [[nil, "b"]]
    assert_equal [["{}", "b"]], Entry.pluck(Arel.sql("value->>'c', value->'b'")) # Actual [[{}, "b"]]
  end
end
```

### PostgreSQL results 

```sql
SELECT
  pg_typeof(value->'a'), value->'a',
  pg_typeof(value->'b'), value->'b',
  pg_typeof(value->'c'), value->'c',
  pg_typeof(value->>'a'), value->>'a',
  pg_typeof(value->>'b'), value->>'b',
  pg_typeof(value->>'c'), value->>'c'
FROM "entries";

 pg_typeof | ?column? | pg_typeof | ?column? | pg_typeof | ?column? | pg_typeof | ?column? | pg_typeof | ?column? | pg_typeof | ?column?
-----------+----------+-----------+----------+-----------+----------+-----------+----------+-----------+----------+-----------+----------
 jsonb     | "a"      | jsonb     | "b"      | jsonb     | {}       | text      | a        | text      | b        | text      | {}
(1 row)
```

### System configuration
**Rails version**: 6.1.6.1

**Ruby version**: 3.1.0

### Similar issue in different versions of ActiveRecord

There is a similar issue but with slightly different behaviour in AR 6.0. Created another issue: #45757

Please confirm or comment on the expected behaviour.
Thank you.

### PR DESCRIPTION
**Pull request by shhavel**
Fix #45758 

Updates ActiveRecord PostgreSQL adapter and ActiveRecord::Result to handle DB result with no-name columns (`?column?`) of different type.

cc @fatkodima @skipkayhil

### CODE REVIEW

File: activerecord/lib/active_record/result.rb [hunk 1]
```diff
@@ -141,9 +141,11 @@ def freeze # :nodoc:
     end
 
     private
-      def column_type(name, type_overrides = {})
+      def column_type(name, index, type_overrides)
         type_overrides.fetch(name) do
-          column_types.fetch(name, Type.default_value)
+          column_types.fetch(name) do
```
Comment (fatkodima) [inline activerecord/lib/active_record/result.rb:146]: `column_types` keys are indexes, so I think this line is not needed.

File: activerecord/test/cases/adapters/postgresql/json_test.rb [hunk 2]
```diff
@@ -33,6 +33,11 @@ def test_deserialize_with_array
     x.reload
     assert_equal ["foo" => "bar"], x.objects
   end
+
+  def test_noname_columns_of_different_types_with_arrow_operator_and_double_arrow_operator
```
Comment (fatkodima) [inline activerecord/test/cases/adapters/postgresql/json_test.rb:37]: We can use just `test_noname_columns_of_different_types` as a name here, imo.

**Review by fatkodima — COMMENTED** [review]
💪

File: activerecord/lib/active_record/result.rb (hunk 1 above)
Comment (shhavel) [reply activerecord/lib/active_record/result.rb]: Rechecked to ensure that isn't used with column name keys in different adapters. Removed. Thank you for the sugestion.

File: activerecord/test/cases/adapters/postgresql/json_test.rb (hunk 2 above)
Comment (shhavel) [reply activerecord/test/cases/adapters/postgresql/json_test.rb]: Renamed test. Thank you!

**Comment by skipkayhil** [comment]
Test failures look real

**Comment by fatkodima** [comment]
I investigated a bit. So `Result#column_types` are accessed directly in several places by name, like https://github.com/rails/rails/blob/aa00ef35eb0314c2b68103a7dfaf2d75a33cbc0b/activerecord/lib/active_record/querying.rb#L66-L70 or https://github.com/rails/rails/blob/aa00ef35eb0314c2b68103a7dfaf2d75a33cbc0b/activerecord/lib/active_record/relation/calculations.rb#L427 and more. But we want to be accessed by the index. So that's why CI is red.

We can make `Result#column_type` method public https://github.com/rails/rails/blob/aa00ef35eb0314c2b68103a7dfaf2d75a33cbc0b/activerecord/lib/active_record/result.rb#L143-L148 and implement it with something like
```ruby
def column_type(name, type_overrides = {})
  type_overrides.fetch(name) do
    column_types.fetch(name) do
      index = columns.index(name)
      column_types[index] || Type.default_value
    end
end
```

and use it everywhere I mentioned before?

This time we will have a small overhead from `index = columns.index(name)`. Probably needs benchmarking.

**Comment by shhavel** [comment]
@fatkodima Thank you so much for the guidance, review and investigation so far.

I think to workaround the issue with duplicated column names in PG result and also to maintain the current behaviour of  `AR::Result#column_types`, it is possible to save type for both column's index and column's name. For column's index store explicitly a default type. And prioritise column's index type lookup over column's name type lookup.

**Comment by shhavel** [comment]
@skipkayhil @fatkodima The tests are now fixed with having `types` stored for both column names and column indexes. Thank you.

**Comment by shhavel** [comment]
@fatkodima @skipkayhil Hi. Merged `main` branch, resolved the conflicts. 
What do you think about the PR? 
Thank you.

**Comment by fatkodima** [comment]
Looks good to me. Make sure you squashed the commits.

**Comment by simi** [comment]
:thinking: CI seems sad about the change, is that failure anyhow related? By quick look it doesn't seem to.

**Comment by shhavel** [comment]
@simi I think failed CI tests are unrelated to the changes. Thank you.
