### PR TITLE
Execute default_scope defined by abstract class within the scope of subclass

### LINKED ISSUE #23413: Default scopes defined on abstract classes are missing table names when called from subclasses
Similar to https://github.com/rails/rails/issues/10658 except this only seems to affect uses of `default_scope` on master. I created [an executable test case](https://gist.github.com/swrobel/7247955f409f4b24f253) to show the failure. This happens with all supported database adapters, as far as I can tell, although the way that each fails when the `table_name` is missing is different. This does not happen if `default_scope` is defined as a class method, - only when using the `default_scope -> { }` syntax.

### PR DESCRIPTION
**Pull request by meinac**
This commit will fix #23413 and #10658. In old behaviour it tries to execute block given by `default_scope` within the context of abstract class and in this case it can't find the table name. Now it tries to execute the block within subclass and everything works.

### CODE REVIEW

**Comment by meinac** [comment]
I've fixed the failing tests but travis is not working, maybe we need to close and reopen this.
Also WDYT about this change @sgrif?

**Comment by swrobel** [comment]
:clap:

File: activerecord/lib/active_record/scoping/default.rb [hunk 1]
```diff
@@ -115,7 +115,10 @@ def build_default_scope(base_rel = nil) # :nodoc:
             base_rel ||= relation
             evaluate_default_scope do
               default_scopes.inject(base_rel) do |default_scope, scope|
-                default_scope.merge(base_rel.scoping { scope.call })
+                scoped = base_rel.scoping do
+                  scope.is_a?(Proc) ? instance_exec(&scope) : scope.call
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/scoping/default.rb]: Is there any case where scope is not a `Proc`?

Comment (meinac) [inline activerecord/lib/active_record/scoping/default.rb]: Yes, any kind of object can be used in default scope if the object is callable. I saw this in Rails tests, for example [in this case](https://github.com/rails/rails/blob/master/activerecord/test/cases/scoping/default_scoping_test.rb#L37) it uses OpenStruct.
But now I think that I have to handle the `call` method case also in correct context. Change is on the way.

**Comment by meinac** [comment]
@rafaelfranca I've changed the logic. If you have a look at the line you can see that we can use any kind of object which respond to call method as default scope and now we can handle it in correct context.
Thank you for looking into this pr.

**Comment by rafaelfranca** [comment]
This looks good to me. r? @sgrif WDYT?

File: activerecord/lib/active_record/scoping/default.rb [hunk 2]
```diff
@@ -115,7 +115,8 @@ def build_default_scope(base_rel = nil) # :nodoc:
             base_rel ||= relation
             evaluate_default_scope do
               default_scopes.inject(base_rel) do |default_scope, scope|
-                default_scope.merge(base_rel.scoping { scope.call })
+                scope = scope.is_a?(Proc) ? scope : scope.method(:call)
```
Comment (sgrif) [inline activerecord/lib/active_record/scoping/default.rb]: Should this be `respond_to?(:to_proc)`?

File: activerecord/lib/active_record/scoping/default.rb [hunk 3]
```diff
@@ -115,7 +115,8 @@ def build_default_scope(base_rel = nil) # :nodoc:
...
+                default_scope.merge(base_rel.scoping{instance_exec(&scope)})
```
Comment (sgrif) [inline activerecord/lib/active_record/scoping/default.rb]: Should this just be `base_rel.instance_exec(&scope)`? Or can't this even be `default_scope.merge(&scope)`?

**Comment by meinac** [comment]
@sgrif rebased updated this.

**Comment by prathamesh-sonpatki** [comment]
@sgrif Should this be backported to `4-2-stable` as per https://github.com/rails/rails/issues/23413#issuecomment-178952846
