### PR TITLE
[ActiveStorage] Fix `ActiveStorage:Representations::ProxyController` returning the wrong preview

### LINKED ISSUE #47071: Active Storage previewable not resized when using proxy mode on storage service local
### Steps to reproduce

Active proxy mode or use rails_storage_proxy_path to generate preview of a video or pdf.
Rails.application.config.active_storage.resolve_model_to_route = :rails_storage_proxy

```ruby
development.rb
config.active_storage.service = :local

active_storage.rb
Rails.application.config.active_storage.resolve_model_to_route = :rails_storage_proxy

In a view
image_tag message.video.preview(resize_to_limit: [100, 100]) 
```

### Expected behavior
An jpg version resized to limit 100x100

### Actual behavior
Returns a jpg version in the same size as the original video (or pdf)

If you turn off rails_storage_proxy it works as expected.

### System configuration
Rails 7.0.4.1
ffmpeg version 5.1.2 (also tried version 3.x and 4.x with the same result)
mutool version 1.20.0

Ruby 3.1.2

### PR DESCRIPTION
**Pull request by chaadow**
Fixes #47071

### Motivation / Background

When a blob is a representable of kind `previewable`, the preview
image that's being proxied is always the original preview image,
discarding completely the `variation_key` param passed in the request.

As all 3 classes are now 100% interchangeable, we can deprecate the use
of `Representable#image`. Users of this class won't need to call this
method as it's become obsolete. and in case of `Preview#image`
erroneous.

### Detail

This PR fixes this by editing `Preview` and `VariantWithRecord` to
have full synchronized API with `Variant`. this will then allow the
ProxyController to not call `representable#image` but `representable`
instead.

 As all 3 classes are now 100% interchangeable, we can deprecate the use
    of `Representable#image`. Users of this class won't need to call this
    method as it's become obsolete. and in case of `Preview#image`
    erroneous.

### Additional information
I've added missing failing tests that would have caught this issue.

It wasn't straightforward to fix. Because of some mismatches between `AS::Variant` / `AS::VariantWithRecord` / `AS::Preview` 
For example `AS::Variant` adds a lot of redundant methods like `#filename`simply because `AS::Variant#image` returns `self` ( and **not** a AS blob). and any methods that are used with `send_blob_stream`

Here are the the lines that call `@representation.image`
https://github.com/rails/rails/blob/438cad462638b02210fc48b700c29dcd0428a8b7/activestorage/app/controllers/active_storage/representations/proxy_controller.rb#L14-L16

which I changed to call `send_blob_stream @representation` getting rid of `#image` and we can deprecate it in a future PR

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activestorage/test/controllers/representations/proxy_controller_test.rb [hunk 1]
```diff
@@ -126,15 +128,19 @@ class ActiveStorage::Representations::ProxyControllerWithPreviewsWithStrictLoadi
...
-        variation_key: ActiveStorage::Variation.encode(resize_to_limit: [100, 100]))
+        variation_key: ActiveStorage::Variation.encode(transformations))
     end
 
     assert_response :ok
     assert_match(/^inline/, response.headers["Content-Disposition"])
+    assert_equal @blob.representation(transformations).download, response.body
+
     @blob.reload # became free of strict_loading?
     assert_predicate @blob.preview_image, :attached?
```
Comment (chaadow) [inline activestorage/test/controllers/representations/proxy_controller_test.rb:146]: I'm not gonna lie, I don't understand the purpose of reading the image by doing `image = read_image(@blob.preview_image.variant(resize_to_limit: [100, 100]).processed)`

This has already been tested. I believe what's important is to check that the "rack response" have : 
1- the proper status code
2- proper http headers
3- proper body

If possible I would like to remove them now that I've added: `assert_equal @blob.representation(transformations).download, response.body`

File: activestorage/test/controllers/representations/proxy_controller_test.rb [hunk 2]
```diff
@@ -37,6 +38,20 @@ class ActiveStorage::Representations::ProxyControllerWithVariantsTest < ActionDi
     assert_equal 67, image.height
   end
 
+  test "showing untracked variant" do
```
Comment (chaadow) [inline activestorage/test/controllers/representations/proxy_controller_test.rb:41]: as expected when variant tracking is disabled, there is an `NoMethodError: undefined method `forced_disposition_for_serving' for #<ActiveStorage::Variant:0x0000000108838110`

image

File: activestorage/app/models/active_storage/variant.rb [hunk 3]
```diff
@@ -91,6 +91,14 @@ def filename
     ActiveStorage::Filename.new "#{blob.filename.base}.#{variation.format.downcase}"
   end
 
+  def content_type_for_serving
```
Comment (chaadow) [inline activestorage/app/models/active_storage/variant.rb:94]: juste like with `def filename` above i've implemented the missing methods, since we do not deal with a real blob.

My theory is that `tracking variants` became the default at some point in rails, and the proxycontroller evolved, without taking into account the untracked variants use case

( Indeed, tests were missing that would have caught this)

Should I open a separate for this, or since it's all related to ProxyController and `representations` as a whole, I can keep my second commit on this PR?

File: activestorage/app/models/active_storage/preview.rb [hunk 4]
```diff
@@ -53,7 +53,11 @@ def processed
 
   # Returns the blob's attached preview image.
   def image
-    blob.preview_image
+    if variant?
+      variant.processed.image if processed?
```
Comment (chaadow) [inline activestorage/app/models/active_storage/preview.rb:57]: i delegate to the variant `#image` method, which can either be a AS::Blob ( for tracked variants) or `AS::Variant` ruby object, non AR, instance.

File: activestorage/app/models/active_storage/preview.rb [hunk 5]
```diff
@@ -53,7 +53,11 @@ def processed
...
+    else
+      preview_image
+    end
```
Comment (jonathanhefner) [inline activestorage/app/models/active_storage/preview.rb:60]: Although this is arguably the desired behavior, this would be a breaking change.  Since this method is part of the public API, we would need to implement some sort of deprecation if we went this route.

File: activestorage/app/models/active_storage/variant.rb (hunk 3 above)
Comment (jonathanhefner) [reply activestorage/app/models/active_storage/variant.rb:94]: Non-tracked variants not working with `ActiveStorage::Representations::ProxyController` is definitely an issue by itself.  So let's fix that in a separate PR and merge that PR first.

Comment (chaadow) [reply activestorage/app/models/active_storage/variant.rb]: done, extracted to #50107

File: activestorage/app/models/active_storage/preview.rb (hunk 5 above)
Comment (chaadow) [reply activestorage/app/models/active_storage/preview.rb:60]: I just got and idea to avoid this deprecation and fix `AS::Representations::ProxyController`.

since `Variant` is already defining the missing methods to make itself a `ActiveStorage::Blob` compliant ruby model. 

how about we change : 
```ruby
send_blob_stream @representation.image, disposition: params[:disposition]
```
to 
```ruby 
send_blob_stream @representation, disposition: params[:disposition]
```

Then what's left is to add to both `VariantWithRecord` and `Preview` these : 

```ruby
delegate :forced_disposition_for_serving, :forced_disposition_for_serving, :filename, to: :image
```

This way:
1- We make all three classes truly compatible and implementing all the methods
2- Fix `ProxyController` for all the 3 representables.
3- We can separate fixing `Preview#image` in another refactoring PR if needed

@jonathanhefner

File: activestorage/test/controllers/representations/proxy_controller_test.rb (hunk 2 above)
Comment (chaadow) [reply activestorage/test/controllers/representations/proxy_controller_test.rb]: done in #50107

File: activestorage/app/models/active_storage/variant.rb (hunk 3 above)
Comment (chaadow) [inline activestorage/app/models/active_storage/variant.rb:94]: This diff should disappear once #50107 is merged

Comment (chaadow) [reply activestorage/app/models/active_storage/variant.rb:94]: with the new Servable module

File: activestorage/test/controllers/representations/proxy_controller_test.rb [hunk 6]
```diff
@@ -6,42 +6,37 @@
 class ActiveStorage::Representations::ProxyControllerWithVariantsTest < ActionDispatch::IntegrationTest
   setup do
```
Comment (chaadow) [inline activestorage/test/controllers/representations/proxy_controller_test.rb:7]: Since I'm technically changing the proxy controller with this solution, I believe we can change and improve all the tests in this file if you don't mind

File: activestorage/app/models/active_storage/preview.rb [hunk 7]
```diff
@@ -33,6 +33,8 @@
 class ActiveStorage::Preview
   class UnprocessedError < StandardError; end
 
+  delegate :forced_disposition_for_serving, :content_type_for_serving, :filename, to: :presentation
```
Comment (jonathanhefner) [inline activestorage/app/models/active_storage/preview.rb:36]: What are your thoughts on including `ActiveStorage::Blob::Servable` here as well?  We would still need to delegate `filename` and `content_type`, but if new (required) methods were added to `ActiveStorage::Blob::Servable` in the future, we would automatically pick those up.

File: activestorage/app/models/active_storage/variant_with_record.rb [hunk 8]
```diff
@@ -8,6 +8,7 @@ class ActiveStorage::VariantWithRecord
   attr_reader :blob, :variation
   delegate :service, to: :blob
   delegate :content_type, to: :variation
+  delegate :forced_disposition_for_serving, :content_type_for_serving, to: :image
```
Comment (jonathanhefner) [inline activestorage/app/models/active_storage/variant_with_record.rb:11]: Likewise, what are your thoughts on including `ActiveStorage::Blob::Servable` here too?  `VariantWithRecord` already implements `filename` and delegates `content_type`.

With that approach, the first argument to `send_blob_stream` will always be `is_a?(ActiveStorage::Blob::Servable)`, which is kind of nice from a typing perspective.

File: activestorage/test/controllers/representations/proxy_controller_test.rb [hunk 9]
```diff
@@ -18,10 +18,7 @@ class ActiveStorage::Representations::ProxyControllerWithVariantsTest < ActionDi
 
     assert_response :ok
     assert_match(/^attachment/, response.headers["Content-Disposition"])
-
-    image = read_image(@blob.variant(@transformations))
-    assert_equal 100, image.width
-    assert_equal 67, image.height
+    assert_equal @blob.representation(@transformations).download, response.body
```
Comment (jonathanhefner) [inline activestorage/test/controllers/representations/proxy_controller_test.rb:21]: Since this test specifically targets variants (not previews), let's use `variant` instead of `representation` here.

```suggestion
    assert_equal @blob.variant(@transformations).download, response.body
```

I know they are equivalent, but using `variant` feels more correct here.  It also feels slightly more like double checking since, presumably, it hits a different code path [than `ProxyController` does](https://github.com/rails/rails/blob/8b34759596efe31909a3cf632903c6d1a2479b62/activestorage/app/controllers/active_storage/representations/base_controller.rb#L14).

File: activestorage/CHANGELOG.md [hunk 10]
```diff
@@ -1,3 +1,11 @@
+*   Fix `ActiveStorage::Representations::ProxyController` not returning the proper
+    preview image variant for previewable files. All `representables` ( `Variant`
+    `VariantWithRecord` and `Preview`) have now full interchangeable APIs, and
+    the use of `ActiveStorage::Blob#representation` is now recommended over
+    `ActiveStorage::Blob#variant` or `ActiveStorage::Blob#preview`.
```
[the remark this answers is not in the document]
Comment (chaadow) [reply activestorage/CHANGELOG.md]: > Why would ActiveStorage::Blob#representation now be recommended over ActiveStorage::Blob#variant or ActiveStorage::Blob#preview (in the case where you know that you have one or the other)?

Because technically speaking, even if we have a `has_one_attached :pdf_file` we can **never** know whether a blob is variable or previewable or neither. At least in ActiveStorage( unless we use a third party gem like active_storage_validations)
I believe the safest way, in ActiveStorage to ask for some variant or preview is with: 
```ruby
begin 
  @blob.representation({..}) # the blob can be of any content type technically.
rescue UnrepresentableError
 # re-raise or ignore depending on the use case.
 end
 ```
 
 The main goal of this PR was to fix the wrong preview image transformation. However since it led to harmonizing with the `include Servable` (I'm summarizing), I thought I might add some info related to that in the changelog

File: activestorage/app/models/active_storage/preview.rb (hunk 7 above)
Comment (chaadow) [reply activestorage/app/models/active_storage/preview.rb]: Yes I agree!

File: activestorage/app/models/active_storage/variant_with_record.rb (hunk 8 above)
Comment (chaadow) [reply activestorage/app/models/active_storage/variant_with_record.rb]: Yes I agree as well!

File: activestorage/test/controllers/representations/proxy_controller_test.rb (hunk 9 above)
Comment (chaadow) [reply activestorage/test/controllers/representations/proxy_controller_test.rb]: Alright let's do this.

If I undrstand correctly, I will also change from `.representation` to `.preview` in the preview tests!

Please let me know if I got it wrong

**Review by chaadow — COMMENTED** [review]
@jonathanhefner Thanks for the review! I've applied all the suggested changes and rebased with main.

Regarding the Changelog I would like a reply if you don't mind.

File: activestorage/CHANGELOG.md (hunk 10 above)
[the remark this answers is not in the document]
Comment (jonathanhefner) [reply activestorage/CHANGELOG.md]: > I believe the safest way, in ActiveStorage to ask for some variant or preview

In terms of not raising an exception, yes.  However, if your application logic is expecting a variable (image-like) file, then you probably want to use `variant` because `representation` could mask a problem.  For example, if you have `has_one_attached :avatar`, and the user uploads a video instead of an image, then `representation` would sweep the problem under the rug.

But also, regardless of which method you prefer, I don't think any that of changed in this PR, right?  We fixed how `ProxyController` handles previews, but we didn't expose any new behavior otherwise.  `ActiveStorage::Blob::Servable` is still a private API.  Likewise, even though we made it possible to pass `Variant`, `VariantWithRecord`, or `Preview` to `send_blob_stream`, we haven't made that part of its public API.  The public API for `send_blob_stream` still requires an `ActiveStorage::Blob` instance.

[the remark this answers is not in the document]
Comment (chaadow) [reply activestorage/CHANGELOG.md]: @jonathanhefner  Alright I agree.

> The public API for send_blob_stream still requires an ActiveStorage::Blob instance.

This is true. And thankfully, since our proxy tests now properly test all cases ( + not calling `#image`), if `send_blob_stream` evolves,  for example, by calling `blob.method_that_does_not_exist_on_variant`,  our tests will catch it. So this is now reassuring!

However, my concern regarding the `Preview#image` still remains. But that's for another day.

Thanks for replying!

**Review by chaadow — COMMENTED** [review]
the whole test suite is failing but I feel it's unrelated to my PR @jonathanhefner

**Comment by jonathanhefner** [comment]
Thank you, @chaadow!  :framed_picture:
