### PR TITLE
fix nested `has many :through` associations on unpersisted parent instances

### LINKED ISSUE #16313: nested `has many :though` associations don't work as expected on unpersisted instances
gist to reproduce this issue: https://gist.github.com/zoltankiss/bd8a28fb749e66b449b5

If we have

``` ruby
class Post < ActiveRecord::Base
  has_many :books, through: :author
  has_many :subscriptions, through: :books
end

class Author < ActiveRecord::Base
  has_one :post
  has_many :books
  has_many :subscriptions, through: :books
end

class Book < ActiveRecord::Base
  belongs_to :author
  has_many :subscriptions
end

class Subscription < ActiveRecord::Base
  belongs_to :book
end
```

then if `post` is not persisted, e.g `post = Post.new`, then
`post.subscriptions` will be empty no matter what.

In contrast if `post` is persisted,
e.g if `post = Post.create!` then `post.subscriptions` works as
expected.

This property could be considered even more unusual since
associations in general, work on records that are not persisted.

e.g if

``` ruby
class Post < ActiveRecord::Base
  has_many :subscriptions, through: :author
end
```

then `post.subscriptions` works as expected in all of the
above cases.

### PR DESCRIPTION
**Pull request by zoltankiss**
Fixes: https://github.com/rails/rails/issues/16313

If we have

``` ruby
class Post < ActiveRecord::Base
  has_many :books, through: :author
  has_many :subscriptions, through: :books
end

class Author < ActiveRecord::Base
  has_one :post
  has_many :books
  has_many :subscriptions, through: :books
end

class Book < ActiveRecord::Base
  belongs_to :author
  has_many :subscriptions
end

class Subscription < ActiveRecord::Base
  belongs_to :book
end
```

then if `post` is not persisted, e.g `post = Post.new`, then
`post.subscriptions` will be empty no matter what.

In contrast if `post` is persisted,
e.g if `post = Post.create!` then `post.subscriptions` works as
expected.

This property could be considered even more unusual since
associations in general, work on records that are not persisted.

e.g if

``` ruby
class Post < ActiveRecord::Base
  has_many :subscriptions, through: :author
end
```

then `post.subscriptions` works as expected in all of the
above cases.

### CODE REVIEW

File: activerecord/lib/active_record/reflection.rb [hunk 1]
```diff
@@ -139,6 +139,17 @@ def primary_key_type
         klass.type_for_attribute(klass.primary_key)
       end
 
+      def belongs_to?
+        false
+      end
+
+      def through_reflection
+      end
```
Comment (eileencodes) [inline activerecord/lib/active_record/reflection.rb]: The `belongs_to?` and `through_reflection` definition aren't needed here because they're defined in AssociationReflection and all the reflections below (HM, BT, HMT) all inherit from AssociationReflection.

**Comment by zoltankiss** [comment]
@eileencodes thanks! I removed those unneeded method definitions and rebased.

**Comment by marnen** [comment]
@zoltankiss Unfortunately, I think you rebased onto Rails 5, so this patch is no longer usable with Rails 4 (and because you force-pushed, I can't use the older version).

**Comment by zoltankiss** [comment]
@marnen cool that would definitely be beneficial.

**Comment by marnen** [comment]
@zoltankiss See https://github.com/marnen/rails/tree/allow-nested-has-many-associations-on-unpersisted-parent-instances-backport-to-4.2.1. Note, however, that while the tests pass, the functionality doesn't actually seem to work, unless I'm missing something.

**Comment by zoltankiss** [comment]
@marnen this is a bit vague - could you please define what you mean by "the functionality doesn't actually seem to work", either via a script that reproduces the issue or with a sample app? Thanks!

**Comment by marnen** [comment]
@zoltankiss Since you took 11 months to respond, I no longer recall the context in which I made those comments.
