### PR TITLE
Move advisory locks to own connection handler.

### LINKED ISSUE #39157: `rails db:migrate:{namespace}` does not work with shards defined in ApplicationRecord
Running namespaced migrations in multi-db apps does not work when shards are defined in the ApplicationRecord model.
[This line of code](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_handling.rb#L224) seems to be the problem as referencing ApplicationRecord here runs the [connects_to](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_handling.rb#L81) method which is resetting it to the default connection. This can be reproduced on a rails console in addition to testing it by setting breakpoints while running a migration (`rails db:migrate:primary_shard_one`).

Screen Shot 2020-05-05 at 6 30 24 PM

image

### Steps to reproduce

- Create 2 databases - primary and primary_shard_one - and set their migration paths
- Add ApplicationRecord and setup the shard connections using [connects_to](https://github.com/rails/rails/pull/38531/files#diff-1ed2907b3b8f148c2533558a77673ffaR21)
- Create a migration under primary_shard_one
- Run rails db:migrate:primary_shard_one

### Expected behavior

Migrates primary_shard_one database

### Actual behavior

Migrates primary database and adds the migration defined in the `primary_shard_one` folder to `primary` schema_migrations

### System configuration
**Rails version**:
Rails 6.1.0.alpha

**Ruby version**:
ruby 2.6.3p62

**Database*
mysql2, TBD if the migration runs on the wrong shard on sqlite and other dbs

### PR DESCRIPTION
**Pull request by tgxworld**
### Summary

Resolves https://github.com/rails/rails/issues/39157

Removes the use of `ActiveRecord::AdvisoryLockBase` since it inherits
from `ActiveRecord::Base` and hence share module attributes that are defined in `ActiveRecord::Base`.
This is problematic because establishing connections through
`ActiveRecord::AdvisoryLockBase` can end up changing state of the default
connection handler of `ActiveRecord::Base` leading to unexpected
behaviors in a Rails application.

In the case of https://github.com/rails/rails/issues/39157,

Running migrations with `rails db:migrate:primary_shard_one` was not working as
the application itself defined the following

```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to shards: {
    default: { writing: :primary },
    shard_one: { writing: :primary_shard_one }
  }
end
```

In the database migrate rake task, the default connection was
established with the database config of `primary_shard_one`. However,
the default connection was altered to that of `primary` because
`ActiveRecord::AdvisoryLockBase.establish_connection` ended up loading
`ApplicationRecord` which calls `connects_to shards:`. Since all we
really need here is just a normal database connection, we can avoid
accidentally altering the default connection handler state during the migration
by creating a custom connection handler used for retrieving a connection.

### Other Information

Alternate take on https://github.com/rails/rails/pull/38235

### CODE REVIEW

**Comment by tgxworld** [comment]
cc @eileencodes @seejohnrun 

I didn't add a test for this because the bug has to be reproduced through the use of `ActiveRecord::AdvisoryLockBase`.

File: activerecord/lib/active_record/migration.rb [hunk 1]
```diff
@@ -1376,18 +1376,25 @@ def use_advisory_lock?
...
-        yield
-      ensure
-        if got_lock && !connection.release_advisory_lock(lock_id)
-          raise ConcurrentMigrationError.new(
-            ConcurrentMigrationError::RELEASE_LOCK_FAILED_MESSAGE
+
+        @advisory_lock_pool ||= begin
+          ActiveRecord::ConnectionAdapters::ConnectionHandler.new.establish_connection(
+            ActiveRecord::Base.connection_db_config
           )
```
Comment (eileencodes) [inline activerecord/lib/active_record/migration.rb:1383]: What does the memoization get us here? I'm not sure it's necessary since we only take a lock out once per migration command.

**Review by eileencodes — COMMENTED** [review]
Sorry for the delay in reviewing, I've been 100% focused on our Ruby upgrade at GitHub. Now that that's done I think this looks good, I just have one question about the memoization. Thanks for working on this 💖

File: activerecord/lib/active_record/migration.rb (hunk 1 above)
Comment (tgxworld) [reply activerecord/lib/active_record/migration.rb]: That is a good point, I looked through the code and we indeed only take a lock once per migration. Updated the PR :+1:

**Comment by tgxworld** [comment]
@eileencodes I've updated the PR as per your comment. Thank you for taking the time to review this :+1:

**Comment by eileencodes** [comment]
Postgres and mysql tests are failing with:

```
Failure:
  | MigrationTest#test_with_advisory_lock_raises_the_right_error_when_it_fails_to_release_lock [/rails/activerecord/test/cases/migration_test.rb:941]:
  | [ActiveRecord::ConcurrentMigrationError] exception expected, not
  | Class: <NoMethodError>
  | Message: <"undefined method `connection' for nil:NilClass">
  | ---Backtrace---
  | /rails/activerecord/test/cases/migration_test.rb:944:in `block (3 levels) in test_with_advisory_lock_raises_the_right_error_when_it_fails_to_release_lock'
  | /rails/activerecord/lib/active_record/migration.rb:1388:in `block in with_advisory_lock'
  | /rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:467:in `with_connection'
  | /rails/activerecord/lib/active_record/migration.rb:1384:in `with_advisory_lock'
  | /rails/activerecord/test/cases/migration_test.rb:943:in `block (2 levels) in test_with_advisory_lock_raises_the_right_error_when_it_fails_to_release_lock'
  | /rails/activesupport/lib/active_support/testing/stream.rb:11:in `silence_stream'
  | /rails/activerecord/test/cases/migration_test.rb:942:in `block in test_with_advisory_lock_raises_the_right_error_when_it_fails_to_release_lock'
```

I think that `connection.release_advisory_lock` doesn't have the `connection` defined since it's defined in a `with_connection` block above.

**Comment by tgxworld** [comment]
@eileencodes The test should be fixed now. Apologies for not checking.

**Comment by eileencodes** [comment]
Thanks!

**Comment by tgxworld** [comment]
Thank you for reviewing too :)
