### PR TITLE
Fix rollbacks following serialization failures or deadlocks

### LINKED ISSUE #43130: Healthy DB connections are thrown away after transaction serialization failure
Hello :)

Last week we updated from 6.1.3.2 to 6.1.4.1 and noticed that there are many connections dropped and reestablished now.
We also got ActiveRecord::ConnectionNotEstablished within nested transactions in some special cases. (Explained in more detail at the bottom)

After some digging, i noticed that connections are thrown away after an ActiveRecord::TransactionRollbackError is raised. Which is the parent class for ActiveRecord::SerializationFailure and ActiveRecord::Deadlocked.
At least for the ActiveRecord::SerializationFailure exception, this behavior is giving us some trouble. 

We are using the transaction isolation level "serializable", where SerializationFailure's are a common thing.

We are currently using CockroachDB but as far as i know neither mysql nor postgresql leaves the connection in an undefined state after a SerializationFailure. Simply rollback and retry the transaction on the same connection is a valid way to go. So dropping the connection is not necessary. If there is a case with a DB where dropping the connection is actually required, can we maybe only drop the connection in that case?

https://github.com/rails/rails/compare/v6.1.3.2...v6.1.4#diff-353f4f101b1bb04938d761b6e29c88e0f147084e9e276854a77ae5d9a9a3b2a8R3
https://github.com/rails/rails/compare/v6.1.3.2...v6.1.4#diff-dd0ea9dfea1fd486f2b1b5eac8c798f839467173a1c2315d3ad04f4098f7dda3R333

I don't know if this was meant to be a performance improvement or actually a real issue with some databases that i don't know of. But skipping a ROLLBACK and dropping a connection are two different things. I think, but i'm not 100% sure about it right now, that the ROLLBACK [SAVEPOINT ...] is still required after a SerializationFailure.
I think you have to signal the DB that you want to ROLLBACK the failed transaction if you attempt to retry it on the same connection. This probably depends on the DB? If there is different behavior, maybe leave it to the adapter to decide what way to go? So far i don't understand why this changes were made.

**Example time! :)**
We are currently running two different implementations of retryable transactions.

1. A basic one with simple exponential backoff, which still works but issues unnecessary reconnects.
```ruby
  # simplified code
  simple_retryable_transaction do
    return yield if within_transaction? # no retries for nested transactions

    loop do
      break ActiveRecord::Base.connection.transaction { yield } # RealTransaction
    rescue ActiveRecord::SerializationFailure => error      
      #  update metrics / APM to see contention
      raise unless more_retries?
      sleep exponential_backoff_seconds
   end
 end
```

2. A more specialised and faster one, where a savepoint is rolled back. Probably only featured by CockroachDB? This one is now broken. After the first SerializationFailure the Inner- and Outer-Transaction are not on the same connection anymore.

```ruby
  # simplified code
  advanced_retryable_transaction do
    return yield if within_transaction? 

    ActiveRecord::Base.connection.transaction(joinable: false) do
      loop do
       # on the second iteration, this will create a RealTransaction on a new connection.
        break ActiveRecord::Base.connection.transaction(requires_new: true) { yield }
      rescue ActiveRecord::SerializationFailure => error      
        #  update metrics / APM to see contention
        # since the DB is prioritising the session with the most retries during contention evaluation:
        #   no sleep and no limited amount of retries
     end
     # If we had a SerializationFailure during the loop which we solved by retrying,
     #   this transaction is now attempting to issue a COMMIT on a closed connection \o/
   end
end
```

If required i'll try to put together some examples with https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case

Best regards,
Eric

### Expected behavior
Keep the connection after ActiveRecord::SerializationFailure and probably even after ActiveRecord::Deadlocked.

### Actual behavior
Connections are thrown away after ActiveRecord::SerializationFailure and ActiveRecord::Deadlocked.

### System configuration
**Rails version**: 6.1.4.1

**Ruby version**: 2.7.3

### PR DESCRIPTION
**Pull request by zarqman**
### Summary

This PR restores rollbacks for real/parent transactions after encountering serialization failures or deadlocks. This fixes the current problem (introduced in 6.1.4) of the database connection being dropped when encountering these two errors.

It continues to skip rollbacks for savepoint/child transactions.

Fixes #43130
Replaces #43381

### Other Information

PR #30922 identified that MySQL cannot handle rollbacks of savepoints once a serialization failure or deadlock has occurred. It added an `:invalidated` transaction state to track this and used it to skip *all* rollbacks.

With these transactions no longer being rolled back, the underlying connections began to be thrown away. The connection discard facility was added in #40541 to address errors *during* rollback.

Unfortunately, the combination of #30922 and #40541 resulted in throwing away the connection upon every deadlock and serialization failure--assuredly not what either PR intended.

Note that PostgreSQL allows rollbacks of savepoints and skipping them is only necessary for MySQL. ~~However, skipping savepoint rollbacks in the case at hand does not appear to harm PostgreSQL so the implemented logic is not database specific. An alternative would be to add another supports-type flag to the database adapters and limit the skip behavior to only MySQL.~~ (edited to add:) Accordingly, a database adapter flag has been added to limit the skip behavior to MySQL only.

### Monkeypatch

For anyone that wants to test this on v6.1.4.1 or v7.0.1, here's a monkeypatch that can be added to an initializer. Using it with a v6.1.4.1 app here results in tests passing without excess dropped connections.

```ruby
require 'active_record/connection_adapters/abstract/transaction'
module ActiveRecord
  module ConnectionAdapters
    class SavepointTransaction < Transaction
      def rollback
        unless @state.invalidated?
          connection.rollback_to_savepoint(savepoint_name) if materialized?
        end
        @state.rollback!
      end
    end
    class TransactionManager
      def rollback_transaction(transaction = nil)
        @connection.lock.synchronize do
          transaction ||= @stack.pop
          transaction.rollback
          transaction.rollback_records
        end
      end
    end
  end
end
```

### CODE REVIEW

**Comment by zarqman** [comment]
bump

File: activerecord/test/cases/adapters/mysql2/nested_deadlock_test.rb [hunk 1]
```diff
@@ -68,8 +69,11 @@ class Sample < ActiveRecord::Base
           else
             raise e
           end
+        rescue ActiveRecord::ConnectionNotEstablished => e
+          flunk "Connection thrown away due to error from improper ROLLBACK TO SAVEPOINT query issued for savepoint that no longer exists due to deadlock: #{e}"
         end
       end
+      assert connection.active?
```
Comment (rafaelfranca) [inline activerecord/test/cases/adapters/mysql2/nested_deadlock_test.rb:76]:
```suggestion
      assert_predicate connection, :active?
```

File: activerecord/test/cases/adapters/mysql2/transaction_test.rb [hunk 2]
```diff
@@ -60,6 +61,7 @@ class Sample < ActiveRecord::Base
           thread.join
         end
       end
+      assert connection.active?
```
Comment (rafaelfranca) [inline activerecord/test/cases/adapters/mysql2/transaction_test.rb:64]:
```suggestion
      assert_predicate connection, :active?
```

File: activerecord/test/cases/transactions_test.rb [hunk 3]
```diff
@@ -18,6 +18,10 @@ def setup
     @first, @second = Topic.find(1, 2).sort_by(&:id)
   end
 
+  teardown do
+    ActiveRecord::Base.clear_all_connections!
```
Comment (rafaelfranca) [inline activerecord/test/cases/transactions_test.rb:22]: Why do we need to clear the connections here?

**Review by rafaelfranca — DISMISSED** [review]

File: activerecord/test/cases/transactions_test.rb (hunk 3 above)
Comment (zarqman) [reply activerecord/test/cases/transactions_test.rb:22]: If one of the tests added in #40541 fail, hundreds of unrelated tests fail because the DB is left in an inconsistent state. Resetting the connections preemptively during teardown limits those unrelated failures so that any problem can be much more easily debugged. Can remove if this is an overreach.

**Comment by matthewd** [comment]
> skipping savepoint rollbacks in the case at hand does not appear to harm PostgreSQL

Do all `TransactionRollbackError`s irrecoverably abort the entire top-level transaction in Postgres? Under other error conditions, it's possible to selectively rollback to an intermediate savepoint, and then resume other work still inside the original transaction -- which client code can do by rescuing the exception at an appropriate level. 

On a related but contrasting note, should we be explicitly refusing to run any query while we're inside an invalidated transaction, if we're semantically still inside, but MySQL has eagerly rolled back? Given `transaction { query_causing_rollback rescue nil; update_query; raise Rollback }`, I think it would be reasonable to expect an ultimately-unchanged database -- am I correct in understanding we may currently end up with the update committed?

**Comment by zarqman** [comment]
> Do all `TransactionRollbackError`s irrecoverably abort the entire top-level transaction in Postgres?

A serialization error can only be sourced from a top-level, real transaction since a savepoint isn't a real transaction and cannot use `isolation: :serializable`. So, those must abort back to the parent.

The Postgres docs on deadlocks say that a deadlock causes one of the deadlocked *transactions* to be aborted. Since savepoints aren't real transactions, I read that as aborting back to the parent as well.

> On a related but contrasting note, should we be explicitly refusing to run any query while we're inside an invalidated transaction, if we're semantically still inside, but MySQL has eagerly rolled back? Given `transaction { query_causing_rollback rescue nil; update_query; raise Rollback }`, I think it would be reasonable to expect an ultimately-unchanged database -- am I correct in understanding we may currently end up with the update committed?

While conceptually related, I think this is beyond the scope of this PR as I don't believe this PR changes the behavior of your example on MySQL. And, rescuing database exceptions inside a transaction is always fraught with risk. The Rails docs on transactions address this to some degree by warning against it.

For additional background however, #30922 attempted to add checks to prevent a commit in an invalidated state, but didn't provide any tests to support those checks. In that PR the question was also raised as to whether such a level of transaction state management was even appropriate given that it's not done elsewhere. Those checks were removed in 115d4a3994a92abc5010ad074d44e68c24debc21.

**Comment by matthewd** [comment]
I've just experimentally confirmed that in both cases, the PostgreSQL transaction is recoverable by rolling back to the nearest preceding savepoint (with the caveat, of course, that retrying from that point may just produce the same serialization failure, etc).

I think that means we're obliged to specialize the implementation for MySQL, as I suspect [without having made further survey] that it's going to be the outlier: a user of another DBMS would be entirely justified in expecting that they're able to resume querying after the exception bubbles out of the innermost savepoint-holding transaction block. 

It seems the answer to [this question](https://github.com/rails/rails/pull/30922/files#r469666781) is **no**. I think that's probably the best place to ask the question, and the best question to ask, though. In other words: I suggest that we only `invalidate` on MySQL, instead of putting the additional required logic into the `rollback` behaviour.

File: activerecord/test/cases/transactions_test.rb (hunk 3 above)
Comment (zarqman) [reply activerecord/test/cases/transactions_test.rb]: Thanks for highlighting the issue with the `sqlite3_mem` suite. I've been using rails-dev-box which doesn't seem to run that suite, so missed the failures.

I've changed this to an ensure clause on just the two related tests. Let me know if you had a different pattern in mind though.

**Comment by zarqman** [comment]
I stand corrected on Postgres and Deadlocks--they are recoverable in nested transactions/savepoints. I've added a test for this. To make this work, invalidation is now limited to MySQL only by adding an adapter flag as suggested.

As to SerializationErrors, I've tried to write a test demonstrating a recovery of a nested transaction, but  am coming up short. My attempts are showing that Postgres is waiting to return the SerializationError until the commit for the parent transaction. If indeed it's possible to trigger them mid-transaction, then I'll need some help identifying a set of operations to build the test.

**Comment by matthewd** [comment]
Sure! I was just working in two `psql` windows, and I did:

```sql
-- CREATE TABLE foo (a integer); CREATE TABLE bar (a integer);

BEGIN ISOLATION LEVEL SERIALIZABLE;
UPDATE foo SET a = 2;
                                            BEGIN ISOLATION LEVEL SERIALIZABLE;
                                            SAVEPOINT x;
                                            UPDATE foo SET a = 3;
                                            -- blocks until:
COMMIT;
                                            -- ERROR
                                            ROLLBACK TO SAVEPOINT x;
                                            INSERT INTO bar VALUES (99);
                                            COMMIT;
```

Because the outer transaction hasn't been restarted, any second attempt to update `foo` will immediately hit the same serialization error... but we can still recover and write to something the first transaction didn't touch.

**Comment by zarqman** [comment]
Thanks much! Added a test for nested transaction serialization recovery. I think everything is good to go now.

**Comment by matthewd** [comment]
Great! Thanks for digging in to this, and especially for iterating on those tests & backend behaviour differences.

File: activerecord/test/cases/adapters/postgresql/transaction_nested_test.rb [hunk 4]
```diff
@@ -68,15 +77,56 @@ class Sample < ActiveRecord::Base
...
+          Sample.transaction(isolation: :serializable, requires_new: false) do
+            assert_raises(ActiveRecord::SerializationFailure) do
+              Sample.transaction(requires_new: true) do
+                Sample.create value: 3
+                commit_left.set
+                finish_right.wait(2)
+                Sample.update_all value: 4
+              end
+            end
+            Bit.create value: 1
```
Comment (nvasilevski) [inline activerecord/test/cases/adapters/postgresql/transaction_nested_test.rb:109]: Hey folks 👋 
Sorry for bumping an old PR, but recently I've been working around some transaction logic and realized that some tests have slightly misleading setup, including this one.
Specifically, the test implies that it uses a `SavepointTransaction` when in reality it's not because the nested transaction is going to be an instance of `RestartParentTransaction` as long as the parent transaction has no queries.
You may want to see more details here - https://github.com/rails/rails/pull/44686

I was able to fix most of the tests by adding a dummy query to force Rails to open an actual savepoint transaction without breaking existing tests expect this one.
You can find a changed version of the test in the PR mentioned below, but when I make this test to use a savepoint transaction, it starts to fail on `Bit.create value: 1` with the following exception (also available on the PR's CI):
```ruby


ActiveRecord::SerializationFailure: PG::TRSerializationFailure: ERROR:  could not serialize access due to read/write dependencies among transactions
--
  | DETAIL:  Reason code: Canceled on identification as a pivot, during conflict in checking.
  | HINT:  The transaction might succeed if retried.
```

I'm going to dig into this, but just wanted to share this feedback just in case you may see the issue off the top of your head. Cause there is still a chance that my setup is wrong but it also plausible that assumptions made about postgresql behaviour were wrong. Don't want to make any premature assumptions yet!

Thanks!

Comment (nvasilevski) [reply activerecord/test/cases/adapters/postgresql/transaction_nested_test.rb:109]: Just to close the loop here. I can confirm that the original test was ok and used a savepoint transaction, so this PR is not involved in the issue I'm looking into.
I can confirm that the issue is reproducible on https://github.com/rails/rails/pull/44526 but not going to say that this is the cause yet.
Just wanted to mention that this PR is unrelated, sorry for bothering! 
And thanks for the pointer ❤️
