### PR TITLE
Use WeakRef in Reaper to avoid leaking connection pools

### LINKED ISSUE #36330: Rails 6rc1 connected_to(database: ...) leaks connections.
We are using rails 6 rc1 and the new connected_to method to perform report queries against a replica DB. This does work, however, the below seems to be making a brand new connection pool for every single query we send. This looks to be causing leaked DB connections.

We have monkey patched this in our code for now.

It appears this line is establishing a new connection every time:
https://github.com/rails/rails/blob/9c5135ce6a10c8318e25a587620c8cde4563f348/activerecord/lib/active_record/connection_handling.rb#L129

We fixed by changing this line to:
`handler.establish_connection(config_hash) unless handler.connected?(config_hash[:name])`

However, this probably won't work for everyone as the value of config_hash[:name] will currently always be "primary" (which is ok for us)

Is this intended behavior or am I missing something possibly?

### Steps to reproduce
```
10.times do
    ActiveRecord::Base.connected_to(database: :slow_replica) do
        ActiveRecord::Base.exec(QUERYHERE)
    end
end
```

### Expected behavior
Should connect to the database `slow_replica` once.

### Actual behavior
Creates a new connection pool for every call

### System configuration
**Rails version**: 6.0.0rc1

**Ruby version**: 2.6.2

### PR DESCRIPTION
**Pull request by jhawthorn**
Prior to #36296 the Reaper thread would hold a reference to connection pools indefinitely, preventing the connection pool from being garbage collected, and also leaking the Thread.

Since #36296, there is only one Reaper Thread for all pools, however all pools are still stored in a class variable, preventing them from being garbage collected.

This commit instead holds reference to the pools through a WeakRef. This way, connection pools referenced elsewhere will be reaped, any others will be able to be garbage collected.

I don't love resorting to WeakRef to solve this, but I believe it's the simplest way to accomplish the the desired behaviour. (Alternatives I can think of would be attaching the reaper thread to a higher object like the connection handler)

Fixes #36330

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb [hunk 1]
```diff
@@ -297,20 +298,29 @@ def initialize(pool, frequency)
         @@mutex = Mutex.new
         @@pools = {}
```
Comment (kamipo) [inline activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb]: Is not enough using `@mutex` and `@pools`?
Looks like the `@@mutex` and `@@pools` are not touched from any Reaper instance.

File: activerecord/test/cases/connection_adapters/connection_handler_test.rb [hunk 2]
```diff
@@ -16,6 +16,19 @@ def setup
...
+        # The pool we want to be GC'd
+        pool = @handler.establish_connection(:arunit)
+        original_ref = WeakRef.new(pool)
+
+        # Establish a new connection and drop the local variable reference
+        pool = @handler.establish_connection(:arunit)
+
+        GC.start
+
+        assert_not original_ref.weakref_alive?
```
Comment (kamipo) [inline activerecord/test/cases/connection_adapters/connection_handler_test.rb]:
```suggestion
        assert_not_predicate original_ref, :weakref_alive?
```

Comment (jhawthorn) [reply activerecord/test/cases/connection_adapters/connection_handler_test.rb]: I removed the test since it [seemed flaky on CI](https://buildkite.com/rails/rails/builds/61330)

**Comment by eileencodes** [comment]
Backported to 6.0
