### PR TITLE
load relationship after autosave if it's not already loaded

### LINKED ISSUE #34255: When using autosave, inverse relationship gets unset during save of parent
### Steps to reproduce

The following specs show what specifically needs to be done to create the issue.  In words:

1. Create two models, `Thing` and `Widget`, with an inverse `has_one/belongs_to` relationship.  Set `autosave: true` on the `has_one`
1. Load an instance of `Thing` with an associated `Widget`
1. Call `thing.widget.reload`
1. Call `thing.save`
1. Now, `thing.widget.thing` is `nil`, but it should not be.  It should be a reference to `thing`

Note: If, when setting up either association, you explicitly set the `foreign_key`, this issue will not happen.

----

<details>
  <summary>Click Here to See Unit Test</summary>

 ----

```
ENV["RAILS_ENV"] ||= 'test'
require File.expand_path("../../../config/environment", __FILE__)

describe "Issue with autosave on inverse relationship" do

    before(:each) do
        drop_tables

        ActiveRecord::Base.connection.execute(%Q~
            CREATE TABLE things (
                id int not null,
                PRIMARY KEY( id )
            );

            insert into things (id) values (42);
        ~)

        %w(widgets sprockets zorps).each do |tablename|
            ActiveRecord::Base.connection.execute(%Q~
                CREATE TABLE #{tablename} (
                    id int not null,
                    thing_id int not null,
                    prop text,
                    PRIMARY KEY( id )
                );

                insert into #{tablename} (id, thing_id) values (1, 42);
            ~)
        end
    end

    after(:each) do
        drop_tables
    end

    def drop_tables
        %w(widgets sprockets zorps things).each do |tablename|
            ActiveRecord::Base.connection.execute(%Q~
                DROP table if exists #{tablename};
            ~)
        end
    end

    class Thing < ActiveRecord::Base

        # We set up one has_one association without explicitly defining
        # the foreign_key, and another where we explicitly define it (but still
        # set it to the default value).  The issue will only appear with the
        # first association (the one that does not explicitly define the foreign key)
        has_one :widget, :autosave => true
        has_one :sprocket, :autosave => true, :foreign_key => :thing_id
        has_one :zorp
    end

    class Widget < ActiveRecord::Base
        belongs_to :thing
    end

    class Sprocket < ActiveRecord::Base
        belongs_to :thing
    end

    class Zorp < ActiveRecord::Base
        belongs_to :thing
    end

    it "should not lose the inverse reference after a reload and a save" do
        # this one fails
        check_if_it_is_broken(:widget, true)
    end

    it "should not lose the inverse reference after save with no reload" do
        # this one passes because we don't do the reload
        check_if_it_is_broken(:widget, false)
    end

    it "should not lose the inverse reference after a reload and a save when specifying the foreign_key" do
        # this one passes because we explicitly set the foreign_key on the association
        check_if_it_is_broken(:sprocket, true)
    end

    it "should not lose the inverse reference after a reload and a save when autosave is not set" do
        # this one passes because we did not set autosave
        check_if_it_is_broken(:zorp, true)
    end

    def check_if_it_is_broken(assoc, should_reload)
        thing = Thing.first

        # this issue only happens if we've reloaded the associated object
        thing.send(assoc).reload if should_reload

        # we need to change the associated object to force the save
        thing.send(assoc).prop = 'changed'

        # this line just proves that the association has a thing (We do this
        # on a separate instance of the thing so we don't muck up the instance we're
        # testing with)
        expect(Thing.find(thing.id).send(assoc).thing).not_to be_nil
        thing.save

        # hey! Where did my widget's thing go?
        expect(thing.send(assoc).thing).not_to be_nil
    end


end
```

</details>

----

### System configuration
**Rails version**:
5.2.1

**Ruby version**:
ruby 2.5.0p0

### PR DESCRIPTION
**Pull request by stevenweber**
fixes: #34255
pair: @rebeldroid12

### Summary

This fixes an issue where a relationship wasn't being loaded causing a nil return value. The behavior looks to have been introduced apart of #31214, an optimization to not reload associations that had been loaded.

### CODE REVIEW

**Comment by stevenweber** [comment]
Please let me know if there are any more details that would help a review.

**Comment by stevenweber** [comment]
@eugeneius I see that you assigned this to yourself -- let me know if you'd like me to resolve the conflicts to help it along.

**Comment by eugeneius** [comment]
The conflicts are only in tests, I'll review the implementation soon and ping you to rebase if I think it's good to merge.

File: activerecord/test/cases/associations/inverse_associations_test.rb [hunk 1]
```diff
@@ -729,6 +729,18 @@ def test_inversed_instance_should_not_be_reloaded_after_stale_state_changed_with
...
+  def test_inverse_instance_should_be_loaded_after_autosave_if_it_is_not_already_loaded
+    man = Man.create!
+    man.create_autosave_face!
+
+    man.autosave_face.reload # clear cached load of autosave_man
+    man.autosave_face.description = "new description"
+
+    assert_equal(false, Man.find(man.id).autosave_face.autosave_man.nil?)
+    man.save!
+    assert_equal(false, man.autosave_face.autosave_man.nil?)
```
Comment (eugeneius) [inline activerecord/test/cases/associations/inverse_associations_test.rb:741]:
```suggestion
    man.save!

    assert_not_nil man.autosave_face.autosave_man
```

I don't think we need to assert that the inverse association works correctly before the record is saved.

File: activerecord/test/schema/schema.rb [hunk 2]
```diff
@@ -1023,6 +1023,7 @@
     t.integer :horrible_polymorphic_man_id
     t.string  :horrible_polymorphic_man_type
     t.references :human, polymorphic: true, index: false
+    t.integer :autosave_man_id
```
Comment (eugeneius) [inline activerecord/test/schema/schema.rb:1026]:
```suggestion
```

I don't think we need to add a new column here, the autosave associations can reuse the same foreign key.

File: activerecord/test/models/face.rb [hunk 3]
```diff
@@ -2,6 +2,7 @@
 
 class Face < ActiveRecord::Base
   belongs_to :man, inverse_of: :face
+  belongs_to :autosave_man, class_name: "Man", foreign_key: :autosave_man_id, inverse_of: :autosave_face
```
Comment (eugeneius) [inline activerecord/test/models/face.rb:5]:
```suggestion
  belongs_to :autosave_man, class_name: "Man", foreign_key: :man_id, inverse_of: :autosave_face
```

(This will be `human_id` after a rebase.)

File: activerecord/test/models/man.rb [hunk 4]
```diff
@@ -2,6 +2,7 @@
 
 class Man < ActiveRecord::Base
   has_one :face, inverse_of: :man
+  has_one :autosave_face, class_name: "Face", autosave: true, foreign_key: :autosave_man_id, inverse_of: :autosave_man
```
Comment (eugeneius) [inline activerecord/test/models/man.rb:5]:
```suggestion
  has_one :autosave_face, class_name: "Face", autosave: true, foreign_key: :man_id, inverse_of: :autosave_man
```

(This will be `human_id` after a rebase.)

**Review by eugeneius — COMMENTED** [review]
This change looks good, can you rebase and resolve the conflicts?

**Comment by stevenweber** [comment]
Thanks for handling the rebase @eugeneius, sorry for not getting to it sooner.
