### PR TITLE
Avoid booting in development then test for test tasks

### LINKED ISSUE #43937: Rails.env == "development" when starting system tests
When launching system tests, `Rails.env == "development"` after launching the tests, but is correctly `test` in the test themselves.

This is breaking thinks like the `dotenv-rails` gem, due to the following:
- `rails test:system` is started
- App is loaded, `Rails.env == "development"`, so `dotenv-rails` loads the env variables for `development`, and those are added to the process's `ENV` variable
- The main process then launches the tests's process, which inherits its parent's `ENV`
- `dotenv-rails` load the env variables for `test`
- But is some variables were set for `development` but dont have a value in `test`, they are still defined in the tests

### Steps to reproduce

- Create a new Rails 7 application
- Add `puts "Rails.env: #{Rails.env}"` to `config/application.rb` on line 7 (after the `Bundler.require` line)
- Run system tests: `rails test:system`

### Expected behavior
`Rails.env` should be `test`, as it is in Rails 6.1 and when running `rails test`

### Actual behavior
`Rails.env` is `development`

### System configuration
**Rails version**:
7.0.0
**Ruby version**:
3.0.3

### PR DESCRIPTION
**Pull request by etiennebarrie**
### Summary

Since #41132, we fork to run the tests from the test Rake tasks, which allows the tests to run when the task runs (previously it was only loading the tests, they ran at the process exit, which isn't helpful for rake tasks where you want to stop processing if a task dependency fails).

That means the app boots twice, first from the top of the Rakefile:
https://github.com/rails/rails/blob/b7c3b52ce530d9914717ceafc64990a225ad96c4/railties/lib/rails/generators/rails/app/templates/Rakefile.tt#L4
then in the fork that runs the test runner.

It's not ideal but it is the only way to run tests in a Rake task since they run at exit.

But that caused some weird behavior/bugs like #43937 since the application boots in development first to load the tasks and then forks to run the tests. We had mentioned some potential problems where the global state in Ruby changed from the Rakefile wouldn't be available to the test process, but we missed the opposite, where an environment variable would be set in development and then available in the child process in the test environment.

> #41132 This diverges from previous behavior because now, any changes made in the Rakefile or other code loaded by Rake won't be available to the child process.

But investigating this, I realized we could define the test tasks as Thor tasks, which take priority over Rake tasks.

We keep the Rake tasks for compatibility (`rake test:models` will continue to work), but `rails test:models` won't go through Rake anymore. 

I built it on 7-0-stable because I think it's a regression that we want to fix, but let me know if you'd rather push that as a feature for 7.1 on main.

### Other Information

There is some incompatibility as mentioned in the commit where we could run `rails test:models ARG=value --trace` but now it won't work.

Another important point is that the `test:prepare` hook won't run when it used to. If you had this in your Rakefile:
```ruby
Rake::Task['test:prepare'].enhance { puts "test:prepare enhancement" }
```

… it would run with `rails test:models` but not with `rails test`. I haven't found any mention of the `test:prepare` hook in guides or documentation so I'll look into deprecating it ([rspec calls it](https://github.com/rspec/rspec-rails/blob/v5.0.2/lib/rspec/rails/tasks/rspec.rake#L25-L26) but doesn't enhance it).

For both cases, I think it's fair since the same wouldn't work with the test task (`rails test ARG=value --trace` fails and `rails test` doesn't run the `test:prepare` task either since it's not a Rake task).

Fixes #43937

### CODE REVIEW

**Comment by rafaelfranca** [comment]
PRs always open against `main`, unless the code is only necessary in a specific branch, which is not the case here.

**Comment by ghiculescu** [comment]
We had an issue with some system tests that were failing due to the double booting (it seems to cause big issues with `Aws::STS`). Just wanted to confirm that this PR removed the double boot and fixed our issues 😍

**Comment by ghiculescu** [comment]
Apart from the merge conflict is there anything else needed for this PR to be merged? It would be an awesome bug to have fixed on main. I am happy to help if needed.

**Comment by milgner** [comment]
Getting this merged would be highly appreciated! Last week another colleague lost the data in his `development` DB when running `rails test` because the wrong database configuration was used and he forgot to explicitly specify `RAILS_ENV=test`.

**Comment by etiennebarrie** [comment]
> when running `rails test`

That part is strange because `rails test` is already not booting twice, it's a Thor command, so the Rakefile is not involved.

**Comment by milgner** [comment]
> > when running `rails test`
> 
> That part is strange because `rails test` is already not booting twice, it's a Thor command, so the Rakefile is not involved.

Oops... :thinking: After encountering the issue the first time, I did an issue search and found this one. As it describes some effects extremely similar to what we have been observing (Rails using the `development` DB when running `rails test` but working fine when running `RAILS_ENV=test rails test`), I was under the impression that this would fix things.

As such I was hopeful that our issue would be resolved soon and did not look into it any closer. But if it's more likely to be something else, I'll investigate further. Thanks for the heads-up!

File: railties/lib/rails/commands/test/test_command.rb [hunk 1]
```diff
@@ -32,6 +32,31 @@ def perform(*)
         Rails::TestUnit::Runner.parse_options(args)
         Rails::TestUnit::Runner.run(args)
       end
+
+      # Define Thor tasks to avoid going through Rake and booting twice when using bin/rails test:*
+
+      Rails::TestUnit::Runner::TEST_FOLDERS.each do |name|
+        define_method(name) do
```
Comment (artemave) [inline railties/lib/rails/commands/test/test_command.rb:39]:
```suggestion
        define_method(name) do
```
```suggestion
        define_method(name) do |*|
```

Otherwise any extra arguments/flags will be raising an error. E.g.:

```
rails test:controllers -b                                                                                                                          
Traceback (most recent call last):                                                                                                                 
        9: from bin/rails:6:in `<main>'                                 
        8: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        7: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        6: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<main>'
        5: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/command.rb:48:in `invoke'
        4: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/command/base.rb:87:in `perform'
        3: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        2: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'                                                                                                                                                                  
        1: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/home/artem/projects/slp2_chilli/lib/rails/command/test_command.rb:26:in `block (2 levels) in <class:TestCommand>': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

Comment (artemave) [inline railties/lib/rails/commands/test/test_command.rb:39]:
```suggestion
        define_method(name) do
```
```suggestion
        define_method(name) do |*|
```

Otherwise any extra arguments/flags will be raising an error. E.g.:

```
rails test:controllers -b                                                                                                                          
Traceback (most recent call last):                                                                                                                 
        9: from bin/rails:6:in `<main>'                                 
        8: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        7: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        6: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<main>'
        5: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/command.rb:48:in `invoke'
        4: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/command/base.rb:87:in `perform'
        3: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        2: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'                                                                                                                                                                  
        1: from /home/artem/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/home/artem/projects/slp2_chilli/lib/rails/command/test_command.rb:26:in `block (2 levels) in <class:TestCommand>': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

Comment (etiennebarrie) [reply railties/lib/rails/commands/test/test_command.rb:39]: Thanks for the review! Indeed we're missing the arguments.

Accepting any arguments works for the minitest args, since [it uses ARGV directly](https://github.com/minitest/minitest/blob/v5.15.0/lib/minitest.rb#L73), but it's not enough for [`--environment`](https://github.com/rails/rails/blob/v7.0.3/railties/lib/rails/test_unit/runner.rb#L22) and [`--warnings`](https://github.com/rails/rails/blob/v7.0.3/railties/lib/rails/test_unit/runner.rb#L29) which are handled in Rails::TestUnit::Runner.parse_options.

So I'm also changing this to keep the current args instead of clobbering them, and appending the folder.

File: railties/lib/rails/commands/test/test_command.rb [hunk 2]
```diff
@@ -32,6 +32,31 @@ def perform(*)
         Rails::TestUnit::Runner.parse_options(args)
         Rails::TestUnit::Runner.run(args)
       end
+
+      # Define Thor tasks to avoid going through Rake and booting twice when using bin/rails test:*
+
+      Rails::TestUnit::Runner::TEST_FOLDERS.each do |name|
+        define_method(name) do |*|
```
Comment (byroot) [inline railties/lib/rails/commands/test/test_command.rb:39]: This never receives keyword arguments?

**Review by byroot — APPROVED** [review]
one minor question, but other than that LGTM.

File: railties/lib/rails/commands/test/test_command.rb (hunk 2 above)
Comment (etiennebarrie) [reply railties/lib/rails/commands/test/test_command.rb:39]: No, it's basically an ARGV. It's called from Thor here: https://github.com/rails/thor/blob/v1.2.1/lib/thor/command.rb#L27

**Comment by rafaelfranca** [comment]
No. 7.0 doesn't receive bug fixes anymore.
