### PR TITLE
Remove week from iso8601 parts [continuation of 34683]

### LINKED ISSUE #34655: Conflict with ISO8601 serializer and parser on ActiveSupport::Duration
### Steps to reproduce
```ruby
duration = ActiveSupport::Duration.build(1000000)
duration_iso = duration.iso8601
ActiveSupport::Duration.parse(duration_iso)
```

### Expected behavior
```ruby
{:weeks => 1, :days=>4, :hours=>13, :minutes=>46, :seconds=>40}
```

### Actual behavior
```ruby
ActiveSupport::Duration::ISO8601Parser::ParsingError: Invalid ISO 8601 duration: "P1W4DT13H46M40S" mixing weeks with other date parts not allowed
```

### System configuration
Rails 5.2.1
Ruby 2.3.1

There's an Exception prohibiting mixing weeks with other date pieces. Although it seems a correct Exception, it makes the process confusing since I could measure a duration by "2 months and 1 week" in any other aspect, and it would also provide a correct behavior on ` ActiveSupport::Duration#parse`

The solutions simply remove the exception and allow it to move forward.
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/duration/iso8601_parser.rb#L106

### PR DESCRIPTION
**Pull request by st0012**
This is a continuation of #34683 and should fix #34655.

I've rebased it on master and addressed the feedback in the original PR.

### Summary

It converts the week part into days and removes it from the final result.

```ruby
# copied from a comment of original PR

duration = ActiveSupport::Duration.build(1000000)
# 1 week, 4 days, 13 hours, 46 minutes, and 40.0 seconds

duration_iso = duration.iso8601
# P11DT13H46M40S

ActiveSupport::Duration.parse(duration_iso)
# 11 days, 13 hours, 46 minutes, and 40 seconds
```

### CODE REVIEW

File: activesupport/lib/active_support/duration/iso8601_serializer.rb [hunk 1]
```diff
@@ -40,6 +42,14 @@ def normalize
           parts = @duration.parts.each_with_object(Hash.new(0)) do |(k, v), p|
             p[k] += v  unless v.zero?
           end
+
+          # Convert weeks to days and remove weeks if mixed with date parts
+          if week_mixed_with_date?(parts)
+            days_in_week = SECONDS_PER_WEEK / SECONDS_PER_DAY
+            parts[:days] = parts[:days].to_i + (parts[:weeks] * days_in_week)
```
Comment (kamipo) [inline activesupport/lib/active_support/duration/iso8601_serializer.rb]: Why `parts[:days].to_i`?

Comment (st0012) [reply activesupport/lib/active_support/duration/iso8601_serializer.rb]: Thanks for pointing it out, have updated

**Comment by maxencehenneron** [comment]
Will this be released in rails 6.1? Seems like it's a bug fix, could we have it in rails 6.0.2.3 instead?
