### PR TITLE
Fix {Public,Debug}Exceptions rendering body for HEAD

### LINKED ISSUE #55131: Response body was given for HEAD request, but should be empty (Rack::Lint::LintError) after upgrading to rails 7.1 from 7.0
### Steps to reproduce

At the moment no idea how to reproduce it.

### Expected behavior

Rack doesn't throw Rack::Lint::LintError

### Actual behavior

Rack throws Rack::Lint::LintError

### System configuration

**Rails version**:  7.1.5.1

**Ruby version**:   3.3.8

After upgrading to 7.1 I started to get random `Rack::Lint::LintError` errors in production. Seems it happens when `ActionController::RoutingError No route matches [HEAD]...` is raised. 

Any pointers on what could be broken? Not sure how to go about debugging it.

### PR DESCRIPTION
**Pull request by skipkayhil**
Fix #55131

Rack::Lint already errors in this case, it just wasn't being covered.

```
Error:
DebugExceptionsTest#test_returns_empty_body_on_HEAD_cascade_pass:
Rack::Lint::LintError: Response body was given for HEAD request, but should be empty
    /home/hartley/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rack-3.1.15/lib/rack/lint.rb:773:in 'Rack::Lint::Wrapper#verify_content_length'
    /home/hartley/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rack-3.1.15/lib/rack/lint.rb:899:in 'Rack::Lint::Wrapper#each'
    /home/hartley/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rack-3.1.15/lib/rack/response.rb:345:in 'Rack::Response::Helpers#buffered_body!'
    /home/hartley/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rack-3.1.15/lib/rack/mock_response.rb:65:in 'Rack::MockResponse#initialize'
    /home/hartley/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rack-test-2.2.0/lib/rack/test.rb:362:in 'Class#new'
    /home/hartley/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rack-test-2.2.0/lib/rack/test.rb:362:in 'Rack::Test::Session#process_request'
    /home/hartley/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rack-test-2.2.0/lib/rack/test.rb:153:in 'Rack::Test::Session#request'
    lib/action_dispatch/testing/integration.rb:297:in 'ActionDispatch::Integration::Session#process'
    lib/action_dispatch/testing/integration.rb:49:in 'ActionDispatch::Integration::RequestHelpers#head'
    lib/action_dispatch/testing/integration.rb:388:in 'ActionDispatch::Integration::Runner#head'
    test/dispatch/debug_exceptions_test.rb:189:in 'block in <class:DebugExceptionsTest>'

Error:
ShowExceptionsTest#test_rescue_with_no_body_for_HEAD_requests:
Rack::Lint::LintError: Response body was given for HEAD request, but should be empty
    /home/hartley/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rack-3.1.15/lib/rack/lint.rb:773:in 'Rack::Lint::Wrapper#verify_content_length'
    /home/hartley/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rack-3.1.15/lib/rack/lint.rb:900:in 'Rack::Lint::Wrapper#each'
    /home/hartley/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rack-3.1.15/lib/rack/response.rb:345:in 'Rack::Response::Helpers#buffered_body!'
    /home/hartley/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rack-3.1.15/lib/rack/mock_response.rb:65:in 'Rack::MockResponse#initialize'
    /home/hartley/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rack-test-2.2.0/lib/rack/test.rb:362:in 'Class#new'
    /home/hartley/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rack-test-2.2.0/lib/rack/test.rb:362:in 'Rack::Test::Session#process_request'
    /home/hartley/.local/share/mise/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/rack-test-2.2.0/lib/rack/test.rb:153:in 'Rack::Test::Session#request'
    lib/action_dispatch/testing/integration.rb:297:in 'ActionDispatch::Integration::Session#process'
    lib/action_dispatch/testing/integration.rb:49:in 'ActionDispatch::Integration::RequestHelpers#head'
    lib/action_dispatch/testing/integration.rb:388:in 'ActionDispatch::Integration::Runner#head'
    test/dispatch/show_exceptions_test.rb:73:in 'block in <class:ShowExceptionsTest>'
```

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: actionpack/lib/action_dispatch/middleware/show_exceptions.rb [hunk 1]
```diff
@@ -38,22 +38,29 @@ def call(env)
...
         request.set_header "action_dispatch.original_path", request.path_info
         request.set_header "action_dispatch.original_request_method", request.raw_request_method
         fallback_to_html_format_if_invalid_mime_type(request)
         request.path_info = "/#{status}"
         request.request_method = "GET"
+
         response = @exceptions_app.call(request.env)
-        response[1][Constants::X_CASCADE] == "pass" ? pass_response(status) : response
+
+        if response[1][Constants::X_CASCADE] == "pass" || head_request
```
Comment (Edouard-chin) [inline actionpack/lib/action_dispatch/middleware/show_exceptions.rb]: I think this should belong in the PublicException app, otherwise we'd be discarding custom headers sent by a custom PublicException app (We'd just send the X_CASCADE header).

Another small benefit if we move this in the PublicException app is that we won't need to render the template since we don't need it.

The downside is that application will have to implement this in their PublicException app if they use a custom one.

Comment (skipkayhil) [reply actionpack/lib/action_dispatch/middleware/show_exceptions.rb]: I agree, that's a much better change. I missed that ShowExceptions sets `action_dispatch.original_request_method` which is what was needed to make that work!

**Comment by Edouard-chin** [comment]
👍 !

(You can rebase from main if you want CI to be green)

File: actionpack/lib/action_dispatch/middleware/public_exceptions.rb [hunk 2]
```diff
@@ -28,7 +28,11 @@ def call(env)
       content_type = request.formats.first
       body = { status: status, error: Rack::Utils::HTTP_STATUS_CODES.fetch(status, Rack::Utils::HTTP_STATUS_CODES[500]) }
 
-      render(status, content_type, body)
+      if env["action_dispatch.original_request_method"] == "HEAD"
```
Comment (byroot) [inline actionpack/lib/action_dispatch/middleware/public_exceptions.rb:31]:
```suggestion
      if request.raw_request_method == "HEAD
```

Not a huge deal, but since we instantiated a request, we could use the slightly nicer API.

Comment (byroot) [reply actionpack/lib/action_dispatch/middleware/public_exceptions.rb:31]: Nevermind, Running your tests I see why you used that now. It's to avoid method rewrites.
