### PR TITLE
Fix index_exists? for PostgreSQL expression indexes

### LINKED ISSUE #36739: index_exists? doesn't match column names in PostgreSQL for `lower(name)`
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

TABLE_NAME = "some_table_name"
INDEX_NAME = "some_index_name"
PG_HOST = '/tmp'

# Make sure to setup your connection config!
conn_config = {
  dbname: "your_database",
  #  host: "host",
  host: PG_HOST,
  port: 5432,
  user: "",
  # password: "password"
}

# Some unique db_name
db_name = "pull_request_test_#{SecureRandom.hex}"

db_conn = PG.connect(conn_config)
db_conn.exec("CREATE DATABASE #{db_name}")

ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: db_name, host: PG_HOST)

ActiveRecord::Schema.define do
  create_table TABLE_NAME, force: true do |t|
    t.string :column1
  end

end

class AddIndexToPublicSchema < ActiveRecord::Migration[5.2]
  def up
    add_index TABLE_NAME, 'lower((column1)::text)', name: INDEX_NAME
  end
end

class BugTest < Minitest::Test
  def test_failed_add_index
    AddIndexToPublicSchema.migrate(:up)
    assert ActiveRecord::Base.connection.index_exists?(TABLE_NAME, "lower((column1)::text)", name: INDEX_NAME)
  end
end
```

This appears to happen because `indexes(TABLE_NAME).columns` returns `lower(column1)`. However, https://github.com/rails/rails/blob/d3327ca40eaea734b2302c7a9ffa0360033a7484/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L101-L103 expects the list of columns to be an array.

The workaround appears to use `index_name_exists?` to skip the column name check.

### Expected behavior

index_exists? returns `true`.

### Actual behavior

index_exists? returns `false`.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.3

### PR DESCRIPTION
**Pull request by stanhu**
Previously Rails expected indexes to be an array of columns, but
for PostgreSQL an expression index can just be a string of text.
Handle this case by forcing `Index#columns` to be an Array.

Closes #36739

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb [hunk 1]
```diff
@@ -100,7 +100,7 @@ def indexes(table_name)
       def index_exists?(table_name, column_name, options = {})
         column_names = Array(column_name).map(&:to_s)
         checks = []
-        checks << lambda { |i| i.columns == column_names }
+        checks << lambda { |i| Array(i.columns) == column_names }
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb]: I think we should change `Index#columns` to always return an array.

**Review by rafaelfranca — COMMENTED** [review]
Can you write a test case for this?

File: activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb (hunk 1 above)
Comment (stanhu) [reply activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb]: Done!

Comment (stanhu) [reply activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb]: Actually, this breaks the schema dumper, so I reverted this change. https://buildkite.com/rails/rails/builds/62458#d17be7e3-67df-49d9-89f3-87145b3bf30b
