### PR TITLE
Test virtual stored columns on create for Postgres

### LINKED ISSUE #45736: Virtual stored columns are always nil for newly created records
### Steps to reproduce
Using postgresql:

Generate a new model with one or more columns with default values, and a virtual stored column based on those other columns
Create a new record of that model
Access the value of the virtual stored column from the newly created ActiveRecord object
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem 'pg', '~> 1.4'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection "postgresql:///test"
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :counter1, null: false, default: 0
    t.integer :counter2, null: false, default: 0
    t.virtual :counter_sum, type: :integer, as: "counter1 + counter2", stored: true
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_virtual_column_value_populated
    post = Post.create!

    assert_equal 0, post.counter_sum
  end
end
```

### Expected behavior
The value of the virtual column should be *something*, in this particular case, 0

### Actual behavior
The value of the virtual column is `nil`. The test fails with the following output
```ruby
# Running:

D, [2022-08-02T13:05:17.402730 #13548] DEBUG -- :   TRANSACTION (0.1ms)  BEGIN
D, [2022-08-02T13:05:17.403136 #13548] DEBUG -- :   Post Create (0.6ms)  INSERT INTO "posts" DEFAULT VALUES RETURNING "id"
D, [2022-08-02T13:05:17.406144 #13548] DEBUG -- :   TRANSACTION (2.6ms)  COMMIT
F

Failure:
BugTest#test_virtual_column_value_populated [stored_bug.rb:37]:
Expected: 0
  Actual: nil


rails test stored_bug.rb:34



Finished in 0.011047s, 90.5240 runs/s, 90.5240 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration
**Rails version**: edge
**Ruby version**: 3.1.2
**PostgreSQL version**: 14.4

### PR DESCRIPTION
**Pull request by abaldwin88**
### Motivation / Background

PR #48241 had the nice bonus of resolving issue #45736 even though that was not the original goal. This pull request codifies the example from #45736 into the test suite.

### Checklist

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

Closes: #45736
Paging: @nvasilevski

### CODE REVIEW

File: activerecord/test/cases/persistence_test.rb [hunk 1]
```diff
@@ -47,6 +47,7 @@ def test_fills_auto_populated_columns_on_creation
     record_with_defaults = Default.create
     assert_not_nil record_with_defaults.id
     assert_equal "Ruby on Rails", record_with_defaults.ruby_on_rails
+    assert_not_nil record_with_defaults.virtual_stored_number
```
Comment (nvasilevski) [inline activerecord/test/cases/persistence_test.rb:50]: I was wondering if we could be a little bit more self-descriptive and call it something like `rand_number_x_by_ten` or maybe even `rand_number_plus_one` with a default function like `rand_number + 1` 
This way our expectation could look like:
```suggestion
    assert_equal record_with_defaults.rand_number + 1,  record_with_defaults.rand_number_plus_one
```

However I agree that at this point this seems excessive and almost like we are trying to test postgresql

My main intention here is to make the same argument reusable in an "update" test if we ever get `UPDATE` to use returning statement, so a hypothetical test for `update` could look like:

```ruby
record_with_defaults.update(rand_number: 100)
assert_equal 101, record_with_defaults.rand_number_plus_one
```

But that's up to you, it can always be refactored when actually needed

**Review by nvasilevski — APPROVED** [review]
Thank you! 👏

File: activerecord/test/cases/persistence_test.rb (hunk 1 above)
Comment (abaldwin88) [reply activerecord/test/cases/persistence_test.rb:50]: Sounds good! Since this is merged that refactor can be rolled in with the `UPDATE` + `RETURNING` pr
