### PR TITLE
AR default scopes: only include `all_queries` default scopes on `reload`

### LINKED ISSUE #46731: `defaut_scope` side effect when using `all_queries: true`
### Description
There's some inconsistency in the behaviour of default_scopes. 
As many scopes can be configured to an AR model and none of them will be applied when reloading a record. Now if there's a single one with `all_queries: true` then all of them get applied

Ref:
https://github.com/rails/rails/blob/main/activerecord/lib/active_record/persistence.rb#L1048
https://github.com/rails/rails/blob/main/activerecord/lib/active_record/persistence.rb#L1138
https://github.com/rails/rails/blob/bd7b6decb98827934ccbd53b27dc1ec997479332/activerecord/lib/active_record/scoping/default.rb#L64

### Steps to reproduce

1 - Add a `default_scope(all_queries: false { where("1=1") }` to an AR model
2 - create a record, query, and reload it - the scope is not applied in the reload query
3 - Add another default scope, now all_queries: true `default_scope(all_queries: true { where("2=2") }`
4 - repeat step 2 and inspect the query - it will include both scopes

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3", "< 1.5"
end

require "active_record"
require "minitest/autorun"
require "logger"


ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.boolean :deleted
  end
end

class Post < ActiveRecord::Base
  default_scope { where(deleted: false) }
end

class BugTest < Minitest::Test
  def test_default_scope_side_effect
    post = Post.create!
    last_query = nil

    ActiveSupport::Notifications.subscribe("sql.active_record") do |_, _, _, _, data|
      last_query = data[:sql]
    end

    expected_query = 'SELECT "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?'

    # default scope NOT applied
    post.reload
    assert_equal expected_query, last_query

    # no-op default scope - all_queries: false
    Post.default_scopes << ActiveRecord::Scoping::DefaultScope.new(lambda { where("1 = 1") }, false)

    # No changes to the query, no default scope has been applied
    post.reload
    assert_equal expected_query, last_query

    # no-op all_queries: true default scope
    Post.default_scopes << ActiveRecord::Scoping::DefaultScope.new(lambda { where("2 = 2") }, true)

    expected_modified_query = 'SELECT "posts".* FROM "posts" WHERE (2 = 2) AND "posts"."id" = ? LIMIT ?'
    # All 3 scopes are now applied
    post.reload
    assert_equal expected_modified_query, last_query
  end
end

```

### Expected behavior
Adding a `default_scope` to an ActiveRecord model should not affect how other `default_scope` behave when reloading a record. 

I would expect consistency in the behaviour of the query, so either:
- Only the `all_queries` default scopes get applied to the query upon reloading the model
- No `default_scope` gets applied upon reloading the model (as I'm not sure why such scopes are applied at all in the `reload` operation)

### Actual behavior
A model may define several `all_queries: false` default_scopes and none of them will be applied upon reloading a record. 
If a single `all_queries: true` default_scope is added to such model, then all default_scopes get applied

### System configuration
**Rails version**:
(tested on) `7.0.3.1` and on `main`

**Ruby version**:
(tested on) `3.0.5` and `3.1.2`

### PR DESCRIPTION
**Pull request by ghiculescu**
Fixes https://github.com/rails/rails/issues/46731

The current behaviour on `reload` is to apply all the default scopes, if any are marked as `all_queries: true`. The correct behaviour is to only apply `all_queries: true` default scopes on `reload`.

### CODE REVIEW

File: activerecord/lib/active_record/scoping/named.rb [hunk 1]
```diff
@@ -19,7 +19,7 @@ module ClassMethods
         #
         # You can define a scope that applies to all finders using
         # {default_scope}[rdoc-ref:Scoping::Default::ClassMethods#default_scope].
-        def all
+        def all(all_queries: nil)
```
Comment (ghiculescu) [inline activerecord/lib/active_record/scoping/named.rb:22]: Do we want to hide this argument in the docs?

Comment (eileencodes) [reply activerecord/lib/active_record/scoping/named.rb:22]: I think this is fine.

**Comment by eileencodes** [comment]
Thank you!
