### PR TITLE
Handle raise flag in translate when both main and default translation is missing.

### LINKED ISSUE #19967: ActionView translate regression since 4.1 when default is missing
Here is my test case:

```ruby
case ARGV[0]
when '4.2'
  gem "actionview", "4.2.1"
when '4.1'
  gem "actionview", "4.1.10"
when '4.0'
  gem "actionpack", "4.0.13"
else
  raise KeyError
end

gem "minitest"
require "action_view"
require "active_support/all"
require "i18n"
require "minitest/autorun"

I18n.enforce_available_locales = false
I18n.backend.store_translations(:en, hello: "Hello")

class TranslateTest < Minitest::Unit::TestCase
  include ActionView::Helpers::TranslationHelper

  def test_ok
    assert_equal "Hello", t(:hello)
  end

  def test_missing
    assert_equal "<span class=\"translation_missing\" title=\"translation missing: en.greeting\">Greeting</span>", t(:greeting)
  end

  def test_default
    assert_equal "Hello", t(:greeting, default: :hello)
  end

  def test_default_missing
    assert_equal "<span class=\"translation_missing\" title=\"translation missing: en.welcome\">Welcome</span>", t(:greeting, default: :welcome)
  end
end
```

The last test is failing since version 4.1.

```
> ruby -w test.rb 4.0
Run options: --seed 46515

# Running tests:

....

Finished tests in 0.007289s, 548.7721 tests/s, 548.7721 assertions/s.

4 tests, 4 assertions, 0 failures, 0 errors, 0 skips
```

```
> ruby -w test.rb 4.1
MiniTest::Unit::TestCase is now Minitest::Test. From test.rb:21:in `<main>'
Run options: --seed 473

# Running:

..E.

Finished in 0.019266s, 207.6196 runs/s, 155.7147 assertions/s.

  1) Error:
TranslateTest#test_default_missing:
I18n::MissingTranslationData: translation missing: en.welcome
    /Users/sema/.gem/ruby/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:311:in `handle_exception'
    /Users/sema/.gem/ruby/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:161:in `translate'
    /Users/sema/.gem/ruby/2.2.0/gems/actionview-4.1.10/lib/action_view/helpers/translation_helper.rb:68:in `translate'
    /Users/sema/.gem/ruby/2.2.0/gems/actionview-4.1.10/lib/action_view/helpers/translation_helper.rb:72:in `rescue in translate'
    /Users/sema/.gem/ruby/2.2.0/gems/actionview-4.1.10/lib/action_view/helpers/translation_helper.rb:38:in `translate'
    test.rb:37:in `test_default_missing'

4 runs, 3 assertions, 0 failures, 1 errors, 0 skips
```

```
> ruby -w test.rb 4.2
MiniTest::Unit::TestCase is now Minitest::Test. From test.rb:22:in `<main>'
Run options: --seed 19624

# Running:

.E..

Finished in 0.024629s, 162.4102 runs/s, 121.8076 assertions/s.

  1) Error:
TranslateTest#test_default_missing:
I18n::MissingTranslationData: translation missing: en.welcome
    /Users/sema/.gem/ruby/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:311:in `handle_exception'
    /Users/sema/.gem/ruby/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:161:in `translate'
    /Users/sema/.gem/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/translation_helper.rb:69:in `translate'
    /Users/sema/.gem/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/translation_helper.rb:73:in `rescue in translate'
    /Users/sema/.gem/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/translation_helper.rb:39:in `translate'
    test.rb:38:in `test_default_missing'

4 runs, 3 assertions, 0 failures, 1 errors, 0 skips
```

Is this a feature or a bug?

### PR DESCRIPTION
**Pull request by imanel**
Fixes #19967.

Quick explanation of what was happening:

[Basing on options](https://github.com/rails/rails/blob/87f876d0d32ea3e59c1c7752b6008f5ab236887f/actionview/lib/action_view/helpers/translation_helper.rb#L63-L69) `raise_error` flag is set, but unless explicit `options[:raise] = false` was provided it will be changed to `true` in first iteration (this is required for proper I18n handling). The problem is that this option is later passed to `default` call, so it's always `true` raising exception (see #19967).

This pull request changes this behavior so it will only raise exception in case of setting `options[:raise] == true` or `ActionView::Base.raise_on_missing_translations`.

### CODE REVIEW

**Comment by matthewd** [comment]
Doesn't this mean we now pass `raise: nil` to a recursive call after an initial `raise: false`?

**Comment by imanel** [comment]
You're right - fixed it and pushed new version.

**Comment by rafaelfranca** [comment]
@matthewd all yours

**Comment by semaperepelitsa** [comment]
Thanks for the fix, @imanel. I want to go further and refactor the method because it is currently very confusing. I will submit a separate pull request.

File: actionview/lib/action_view/helpers/translation_helper.rb [hunk 1]
```diff
@@ -83,6 +83,7 @@ def translate(key, options = {})
         end
       rescue I18n::MissingTranslationData => e
         if remaining_defaults.present?
+          options.delete(:raise) unless options[:raise] == raise_error
```
Comment (matthewd) [inline actionview/lib/action_view/helpers/translation_helper.rb]: Looks like we need some more tests: they're currently all passing even without the `unless` conditional.

**Comment by imanel** [comment]
@matthewd changed it so `options` are never modified (partially basing on @semaperepelitsa refactoring) and added test that made previous version not pass. I'm not sure which one (this or #20003) is more preferred by you so I'm keeping it open.

@semaperepelitsa could you please add mentioned test to your pull request? Let's make sure both of them are passing the same suite :smile:

**Comment by imanel** [comment]
And since @semaperepelitsa mentioned it - it looks like `:rescue_format` is not documented and [it's not supported anymore](https://github.com/svenfuchs/i18n/blob/master/CHANGELOG.md). Rails 5 might be good step in removing it. May I have the honour?

**Comment by imanel** [comment]
Following up possibility of `:rescue_format` removal in #20019 - let's have discussion there.

**Comment by semaperepelitsa** [comment]
My pull request is almost identical now so I'm closing it. May I also ask for this bug fix to be backported onto 4-1-stable and 4-2-stable?
