### PR TITLE
[Fix #51720] Infer association klass as top level if model has same demodularized name

### LINKED ISSUE #51720: Association with the same name as the demodularized model name is incorrectly inferred
### Steps to reproduce

I think it's easiest to explain this with a script.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3", "~> 1.4"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :namespaced_posts, force: true do |t|
  end

  create_table :posts_namespaced_posts_joins, force: true do |t|
    t.references :post
    t.references :namespaced_post
  end
end

class Post < ActiveRecord::Base
  has_one :post_namespaced_post_join
  has_one :namespaced_post, through: :post_namespaced_post_join
end

module Namespaced
  class Post < ActiveRecord::Base
    self.table_name_prefix = "namespaced_"

    has_one :post_namespaced_post_join
    has_one :post, through: :post_namespaced_post_join
  end
end

class PostNamespacedPostJoin < ActiveRecord::Base
  self.table_name = "posts_namespaced_posts_joins"

  belongs_to :post
  belongs_to :namespaced_post, class_name: "Namespaced::Post"
end

class BugTest < Minitest::Test
  def test_association_with_same_demodularized_name
    post = Post.create!
    namespaced_post = Namespaced::Post.create!
    post_namespaced_post_join = PostNamespacedPostJoin.create!(post: post, namespaced_post: namespaced_post)

    assert_equal post_namespaced_post_join, post.post_namespaced_post_join # ✅
    assert_equal post, namespaced_post.post                                # ❌
  end
end
```

Results in:

```
F

Failure:
BugTest#test_ [test.rb:62]:
Expected: #<Post id: 1>
  Actual: #<Namespaced::Post id: 1>
```

The only workaround is to update the association on `Namespaced::Post` to be:

```ruby
has_one :post, through: :post_namespaced_post_join, class_name: "::Post"
```

The `::`[ensures that it's resolved as an absolute constant](https://github.com/rails/rails/blob/793ff00442723b2ff9ed7b7fb39cae2f5608cc2b/activerecord/lib/active_record/inheritance.rb#L243-L246).

See #51721 for a proposed fix.

### Expected behavior

Association model is inferred to be a top level model that matches its name.

### Actual behavior

Association model is inferred to be the model it's defined on.

### System configuration
**Rails version**: main

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

Fixes https://github.com/rails/rails/issues/51720

### Detail

Updates `AbstractReflection#klass` and its only subclass override `MacroReflection#klass` to infer the association class as a top level class if the name of the model without module name-spacing is the same. The current inferrence is due to [this logic](https://github.com/rails/rails/blob/793ff00442723b2ff9ed7b7fb39cae2f5608cc2b/activerecord/lib/active_record/inheritance.rb#L253-L264) resolving the name in the current module first, which doesn't make sense in this specific case as it will always resolve to the model itself.

### Additional information

None.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/test/cases/reflection_test.rb [hunk 1]
```diff
@@ -181,6 +184,18 @@ def test_reflection_klass_requires_ar_subclass
...
+  def test_reflection_klass_with_same_demodularized_name
+    reflection = ActiveRecord::Reflection.create(
+      :has_one,
+      :user,
+      nil,
+      {},
+      Admin::User
+    )
+
+    assert_equal User, reflection.klass
```
Comment (joshuay03) [inline activerecord/test/cases/reflection_test.rb:196]: Before patch:

Screenshot 2024-05-03 at 1 10 59 PM

File: activerecord/test/cases/reflection_test.rb [hunk 2]
```diff
@@ -181,6 +184,30 @@ def test_reflection_klass_requires_ar_subclass
...
+  def test_reflection_klass_with_same_demodularized_different_modularized_name
+    reflection = ActiveRecord::Reflection.create(
+      :has_one,
+      :user,
+      nil,
+      { class_name: "Nested::User" },
+      Admin::User
+    )
+
+    assert_equal Nested::User, reflection.klass
```
Comment (joshuay03) [inline activerecord/test/cases/reflection_test.rb:208]: Added this to make sure we don't regress on this case.

**Comment by joshuay03** [comment]
Thank you @rafaelfranca
