### PR TITLE
Ensure ActiveRecord::Encryption.config is always ready before access

### LINKED ISSUE #2779: Support for encrypted attributes in fixtures cannot be enabled when using Rails 7.2.0
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.3.4
Rails version: 7.2.0
RSpec version: 3.13
  - rspec-core 3.13.0
  - rspec-expectations 3.13.1
  - rspec-mocks 3.13.1
  - rspec-rails 6.1.3
  - rspec-support 3.13.1

## Observed behaviour

Support for encrypted attributes in fixtures cannot be enabled when using Rails 7.2.0.

When the [`active_record_fixture_set`][0] hook in the Active Record railtie runs, the value of `ActiveRecord::Encryption.config.encrypt_fixtures` is false, and the [module is not prepended][1].

This is because the [`active_record`][2] hook has not yet run, and encryption has not been configured.

(Note, this is only an issue when `eager_loading` is not enabled, as eager loading the application causes Active Record to be loaded before RSpec loads the Active Record Test Fixtures.)

[0]: https://github.com/rails/rails/blob/fb6c4305939da06efdf2893d99130e7829c53e8b/activerecord/lib/active_record/railtie.rb#L376

[2]: 
https://github.com/rails/rails/blob/fb6c4305939da06efdf2893d99130e7829c53e8b/activerecord/lib/active_record/railtie.rb#L359

[1]: 
https://github.com/rails/rails/blob/fb6c4305939da06efdf2893d99130e7829c53e8b/activerecord/lib/active_record/railtie.rb#L379

## Expected behaviour

Setting `config.active_record.encryption.encrypt_fixtures = true` [should allow fixtures to set encrypted attributes](https://guides.rubyonrails.org/active_record_encryption.html#fixtures). Instead, a `ActiveRecord::Encryption::Errors::Decryption` exception is raised whenever an encrypted attribute is attempted to be read.

## Can you provide an example reproduction?

I've made a simple reproduction repo here: https://github.com/mbaird/fixture-encryption-bug

The [`main`](https://github.com/mbaird/fixture-encryption-bug/tree/main) branch includes the failing example, the output can be seen in [the GitHub Action run](https://github.com/mbaird/fixture-encryption-bug/actions/runs/10368721442/job/28702931419#step:5:14).

The [`rails-7-1`](https://github.com/mbaird/fixture-encryption-bug/tree/rails-7-1) branch switches to Rails 7.1, the tests pass on this branch.

I think these Rails issues may be related https://github.com/rails/rails/pull/50606, https://github.com/rails/rails/pull/48577.

### PR DESCRIPTION
**Pull request by maximerety**
### Motivation / Background

This Pull Request has been created in order to fix https://github.com/rspec/rspec-rails/issues/2779.

### Detail

Previously, `ActiveRecord::Encryption` configuration was deferred until `ActiveRecord::Base` was loaded. Therefore, accessing `ActiveRecord::Encryption.config` properties before `ActiveRecord::Base` was loaded would give incorrect results.

`ActiveRecord::Encryption` now has its own loading hook so that its configuration is set as soon as needed.

When `ActiveRecord::Base` is loaded, even lazily, it in turn triggers the loading of `ActiveRecord::Encryption`, thus preserving the original behavior of having its config ready before any use of `ActiveRecord::Base`.

This fix complements one of my previous fixes in https://github.com/rails/rails/pull/50606.

Since both Rails 7.1.4 and 7.2.* versions are affected, I'd recommend backporting this fix to `7-1-stable` and `7-2-stable`. 

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by mbaird** [comment]
Thanks for this @maximerety, I can confirm this fixes the issue in https://github.com/rspec/rspec-rails/issues/2779. 🙌🏻

File: activerecord/lib/active_record/encryption/extended_deterministic_queries.rb [hunk 1]
```diff
@@ -26,7 +26,7 @@ def self.install_support
         # some prepared statements caching. That's why we need to intercept +ActiveRecord::Base+ as soon
         # as it's invoked (so that the proper prepared statement is cached).
         ActiveRecord::Relation.prepend(RelationQueries)
-        ActiveRecord::Base.include(CoreQueries)
+        ActiveSupport.on_load(:active_record) { include CoreQueries }
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/encryption/extended_deterministic_queries.rb:29]: We should not use `on_load` inside here. Can we move to the caller?

File: activerecord/lib/active_record/encryption.rb [hunk 2]
```diff
@@ -53,4 +53,6 @@ def self.eager_load!
       Cipher.eager_load!
     end
   end
+
+  ActiveSupport.run_load_hooks :active_record_encryption, Encryption
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/encryption.rb:57]: Now that we added this, we need to document in the guides.

File: activerecord/lib/active_record/railtie.rb [hunk 3]
```diff
@@ -356,20 +356,21 @@ class Railtie < Rails::Railtie # :nodoc:
...
+        configure(
           primary_key: app.credentials.dig(:active_record_encryption, :primary_key),
           deterministic_key: app.credentials.dig(:active_record_encryption, :deterministic_key),
           key_derivation_salt: app.credentials.dig(:active_record_encryption, :key_derivation_salt),
           **app.config.active_record.encryption
+        )
 
-        auto_filtered_parameters = ActiveRecord::Encryption::AutoFilteredParameters.new(app)
-        auto_filtered_parameters.enable if ActiveRecord::Encryption.config.add_to_filter_parameters
+        auto_filtered_parameters = self::AutoFilteredParameters.new(app)
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/railtie.rb:367]: Let's keep the full namespace. It is clear

File: activerecord/lib/active_record/encryption/extended_deterministic_queries.rb (hunk 1 above)
Comment (maximerety) [reply activerecord/lib/active_record/encryption/extended_deterministic_queries.rb]: Done.

File: activerecord/lib/active_record/encryption.rb (hunk 2 above)
Comment (maximerety) [reply activerecord/lib/active_record/encryption.rb:57]: Done, thanks for the hint.

File: activerecord/lib/active_record/railtie.rb (hunk 3 above)
Comment (maximerety) [reply activerecord/lib/active_record/railtie.rb]: I reverted some changes to keep using the full namespace everywhere it was used before.

**Comment by maximerety** [comment]
@rafaelfranca Thanks for reviewing, all comments addressed 🙏
