### PR TITLE
Clear Resolvers' cache after RenderTestCases tests

### LINKED ISSUE #36154: ActionView::HelperInclusionTest#test_helper_class_that_is_being_tested_is_always_included_in_view_instance gets error
Reproduced Action View CI failure at 
https://buildkite.com/rails/rails/builds/60869#71c1ca6c-7165-4517-a08f-cd7452b93cc1 by #36153

### Steps to reproduce

```ruby
$ cd actionview
$ bin/test test/template/render_test.rb test/template/url_helper_test.rb test/template/test_case_test.rb -n "/^(?:CachedCollectionViewRenderTest#(?:test_render_partial_with_layout_using_collection_and_template)|UrlHelperControllerTest#(?:test_recall_params_should_normalize_id)|ActionView::HelperInclusionTest#(?:test_helper_class_that_is_being_tested_is_always_included_in_view_instance))$/" --seed 49076
```

### Expected behavior
It should pass.

### Actual behavior

```ruby
$ bin/test test/template/render_test.rb test/template/url_helper_test.rb test/template/test_case_test.rb -n "/^(?:CachedCollectionViewRenderTest#(?:test_render_partial_with_layout_using_collection_and_template)|UrlHelperControllerTest#(?:test_recall_params_should_normalize_id)|ActionView::HelperInclusionTest#(?:test_helper_class_that_is_being_tested_is_always_included_in_view_instance))$/" --seed 49076
Run options: -n "/^(?:CachedCollectionViewRenderTest#(?:test_render_partial_with_layout_using_collection_and_template)|UrlHelperControllerTest#(?:test_recall_params_should_normalize_id)|ActionView::HelperInclusionTest#(?:test_helper_class_that_is_being_tested_is_always_included_in_view_instance))$/" --seed 49076

# Running:

.E

Error:
ActionView::HelperInclusionTest#test_helper_class_that_is_being_tested_is_always_included_in_view_instance:
ActionView::Template::Error: undefined method `_test_fixtures_test__customer_erb__1331366542035279901_47359544243960' for #<#<Class:0x0000562581a31770>:0x0000562581a313d8>
Did you mean?  _test_fixtures_test__from_helper_erb__825249575139590611_47359544383420
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:274:in `_run'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:185:in `block in render'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:182:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:386:in `instrument_render_template'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:183:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:455:in `block in collection_with_template'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:451:in `map'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:451:in `collection_with_template'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:340:in `block (2 levels) in render_collection'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb:15:in `cache_collection_render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:339:in `block in render_collection'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:328:in `render_collection'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:318:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:22:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:304:in `in_rendering_context'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:30:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/test_case.rb:206:in `render'
    /home/yahonda/git/rails/actionview/test/template/test_case_test.rb:126:in `render_from_helper'
    /home/yahonda/git/rails/actionview/test/fixtures/test/_from_helper.erb:1:in `_test_fixtures_test__from_helper_erb__825249575139590611_47359544383420'
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:274:in `_run'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:185:in `block in render'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:182:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:386:in `instrument_render_template'
    /home/yahonda/git/rails/actionview/lib/action_view/template.rb:183:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:361:in `block in render_partial'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `block in instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications.rb:180:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:350:in `render_partial'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/partial_renderer.rb:320:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
    /home/yahonda/git/rails/actionview/lib/action_view/renderer/renderer.rb:22:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
    /home/yahonda/git/rails/actionview/lib/action_view/base.rb:304:in `in_rendering_context'
    /home/yahonda/git/rails/actionview/lib/action_view/helpers/rendering_helper.rb:30:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/test_case.rb:206:in `render'
    /home/yahonda/git/rails/actionview/lib/action_view/test_case.rb:122:in `render'
    /home/yahonda/git/rails/actionview/test/template/test_case_test.rb:136:in `block in <class:HelperInclusionTest>'


bin/test test/template/test_case_test.rb:132

.

Finished in 0.122995s, 24.3911 runs/s, 48.7823 assertions/s.
3 runs, 6 assertions, 0 failures, 1 errors, 0 skips
$
```

### System configuration
**Rails version**: master branch

**Ruby version**:ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

### PR DESCRIPTION
**Pull request by st0012**
This fixed https://github.com/rails/rails/issues/36154

The templates rendered in RenderTestCases tests will be cached by the resolvers unexpectedly. And this will break other tests when executed in certain order. I think this is due to incomplete teardown in RenderTestCases cases. So to fix this issue, we need to clear the caches on all resolvers when tearing down.

The issue is described in https://github.com/rails/rails/issues/36154 and the investigation is put in [this comment](https://github.com/rails/rails/issues/36154#issuecomment-489404632)

### CODE REVIEW

**Comment by st0012** [comment]
ping @sikachu

**Comment by kamipo** [comment]
Is the CachedCollection tests the only case that needs clearing the cache?
Are `RenderTestCases` itself or another test cases safe for the issue?

**Comment by st0012** [comment]
@kamipo It turns out the issue happens for other test class as well, so I moved the teardown into module and updated PR title/description.

File: actionview/test/template/render_test.rb [hunk 1]
```diff
@@ -7,6 +7,14 @@ class TestController < ActionController::Base
 end
 
 module RenderTestCases
+  def self.included(test_case)
```
Comment (kamipo) [inline actionview/test/template/render_test.rb]: How about just define `def teardown` and ensure calling `super` in the test classes which includes the module?

**Comment by st0012** [comment]
@kamipo updated
