### PR TITLE
Use `secret_key_base` from ENV or credentials when present locally

### LINKED ISSUE #53661: Rails 7.2 "secret_key_base must be a type of String" issue when running tests in parallel in a CI build
Ever since we upgraded our Rails app to Rails `7.2`, we have been experiencing a random `raise ArgumentError, "'secret_key_base' for #{Rails.env} environment must be a type of String"` error in our CI/CD build when running the app's tests. This issue doesn't always occur. When it does, sometimes just restarting the build works. Other times you have to restart the build several times before you get a successful build.

The stack trace in the build log shows that when the issue happens, it happens on this line of code in railties:

https://github.com/rails/rails/blob/v7.2.1.2/railties/lib/rails/application/configuration.rb#L517

Digging into this, I found that Rails 7.2 removed support for the legacy way that secrets were managed in a Rails app, e.g. via `Rails.application.secrets`, leaving  `Rails.application.credentials` as the Rails-approved way to manage secrets in your Rails app. 

Here is the [PR](https://github.com/rails/rails/pull/49618) in Rails 7.2 that removed support for `Rails.application.secrets`. 

It turns out that this PR caused some regressions that were found during beta testing of Rails 7.2, and were corrected in [this PR](https://github.com/rails/rails/pull/52062). Most importantly, this second PR introduced the behavior that when `Rails.env.local?` returns `true`, which it does when the rails environment is `test` (such as when running tests in a CI build), railties will now always generate a local `secret_key_base` stored in a file under `tmp/local_secret.txt`, and not use the one that is defined in `config/credentials.yml.enc`, which was the behavior in Rails 7.1 when we didn't have this CI issue. 

Here is the code in railties that generates the secret for local Rails environments:

```
def generate_local_secret
  key_file = root.join("tmp/local_secret.txt")

  unless File.exist?(key_file)
    random_key = SecureRandom.hex(64)
    FileUtils.mkdir_p(key_file.dirname)
    File.binwrite(key_file, random_key)
  end

  File.binread(key_file)
end
```

I believe the reason why our CI build randomly experiences the `raise ArgumentError, "'secret_key_base' for #{Rails.env} environment must be a type of String"` error is that the `generate_local_secret` method above is not thread-safe, and our CI build runs the app's tests in multiple processes using the [parallel_tests gem](https://github.com/grosser/parallel_tests). See below:

```
# Run the tests with code coverage in parallel groups to speed up things
rake parallel:drop
rake parallel:setup
CI=1 COVERAGE=1 bundle exec parallel_test spec/ --type rspec --group-by runtime --runtime-log spec/parallel_runtime_rspec.log
rake coverage:merge_report
```

One process must be opening the `tmp/local_secret.txt` file and another process must be reading the file before the first process has written to the file and closed it.

To work around this issue, we added the following to our CI build process to force the creation of the `tmp/local_secret.txt` file prior to running the tests in parallel:

```
echo $(ruby -e "require 'securerandom'; puts SecureRandom.hex(64)") > tmp/local_secret.txt
```

Once we made this change we have not experienced the issue with any subsequent CI builds (there have been 25+ builds).

### Steps to reproduce
Run a Rails app's tests in parallel using the `parallel_tests` gem, making sure that two or more processes are used. The issue doesn't always happen, but happens frequently enough that it becomes annoying.

### Expected behavior
The `generate_local_secret` method in railties should work in a use case that is using multiple processes on a build machine to run the Rails app's tests.

Here's a thought - our Rails app defines a `secret_key_base` in `config/credentials.yml.enc` for all environments, including the `test` environment. The behavior in versions of Rails < `7.2` of using `secret_key_base` in `config/credentials.yml.enc` if it exists worked for our use case. Could that behavior be restored?

### Actual behavior
Railties occasionally fails during app startup and throws an `raise ArgumentError, "'secret_key_base' for #{Rails.env} environment must be a type of String"` error.

### System configuration
**Rails version**: We are using `7.2.1.2`, but started noticing this issue when we first upgraded to `7.2`

**Ruby version**: We are using `3.3.5`, but I don't believe the Ruby version has any effect on this issue

### LINKED ISSUE #54277: Rails no longer looks for `secret_key_base` in credentials (in development)
Rails 7.1 automatically found `secret_key_base` in credentials when in development env.

Rails 7.2 doesn't look there anymore, when in development env. It now always generates a secret file and uses that.

It seems the only way to bring back credentials lookup in development is by setting it manually in development.rb:

```ruby
config.secret_key_base = credentials[:secret_key_base]
```

This change is not mentioned in Rails 7.1 -> 7.2 upgrade guide, so it was quite unsettling to find out that all my cookies stopped working after the update. (Since Rails silently switched to using the generated key over the key in my credentials file).

Here's the [relevant code](https://github.com/rails/rails/blob/4666f596861a2d53ff0d7fb055206355b5a13de2/railties/lib/rails/application/configuration.rb#L511).

Whether the solution might be to document this in the upgrade guide, or make Rails honor the key stored in credentials, it seems to be an issue worth addressing.

### PR DESCRIPTION
**Pull request by p8**
### Motivation / Background

Since 0c76f17f2dbf0d7ad90c890e6f334743cacce41f  a `tmp/local_secret.txt` is always used for `Rails.config.secret_key_base` in the test and development environments. Previously, `ENV["SECRET_KEY_BASE"]` or `Rails.application.credentials.secret_key_base` were used if present.

As the `secret_key_base` is used to generate signed IDs, it breaks Action Text attachments in development if they previously used the `secret_key_base` from ENV var or credentials. Accidentally deleting `tmp/local_secret.txt` will also break all local Action Text attachments.

The race condition in generating the local secret file, as reported in https://github.com/rails/rails/issues/53661, should be avoidable by setting `ENV["SECRET_KEY_BASE"]` or `Rails.application.credentials.secret_key_base`, but this currently doesn't work.

Fixes #53661 
Fixes #54277

### Details

When `ENV["SECRET_KEY_BASE"]` or `Rails.application.credentials.secret_key_base` is set for test or development, it should be used for the `Rails.config.secret_key_base`, instead of generating a `tmp/local_secret.txt`.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: railties/lib/rails/application/configuration.rb [hunk 1]
```diff
@@ -514,7 +514,7 @@ def secret_key_base
       end
 
       def secret_key_base=(new_secret_key_base)
-        if new_secret_key_base.nil? && generate_local_secret?
+        if new_secret_key_base.nil? && Rails.env.local?
```
Comment (skipkayhil) [inline railties/lib/rails/application/configuration.rb:517]: Does this still work if an app does `secret_key_base = nil` and has `ENV["SECRET_KEY_BASE_DUMMY"]` set?

**Review by skipkayhil — COMMENTED** [review]
The new complexity of `generate_local_secret?` makes me think the abstraction is wrong (especially since it only gets used in a single place).

What do you think about just making `secret_key_base` look more like the pre-secret removal:

```
def secret_key_base
  @secret_key_base || begin
    self.secret_key_base = if ENV["SECRET_KEY_BASE_DUMMY"]
      generate_local_secret
    else
      ENV["SECRET_KEY_BASE"] || Rails.application.credentials.secret_key_base || (generate_local_secret if Rails.env.local?)
    end
  end
end
```

File: railties/lib/rails/application/configuration.rb (hunk 1 above)
Comment (p8) [reply railties/lib/rails/application/configuration.rb:517]: hmm, yes probably not. There isn't a test case for that now. I'll try to add it.

**Comment by p8** [comment]
> The new complexity of `generate_local_secret?` makes me think the abstraction is wrong (especially since it only gets used in a single place).
> 
> What do you think about just making `secret_key_base` look more like the pre-secret removal:

Maybe that is a good direction. I'll try to update the PR.

**Comment by p8** [comment]
> What do you think about just making `secret_key_base` look more like the pre-secret removal.

Thanks @skipkayhil ! This is much cleaner! ❤️

**Comment by huda-kh** [comment]
When is this planned for release?

**Comment by maxim** [comment]
@rafaelfranca I noticed there was an unresolved [comment](https://github.com/rails/rails/pull/53705/files#r1859768183) there about setting `nil`. Should that be addressed?

**Comment by rafaelfranca** [comment]
It was

**Comment by denisahearn** [comment]
Thanks so much for fixing this issue! 

Will this fix be released as part of Rails `7.x`, or only as part of Rails `8.x`?

**Comment by p8** [comment]
@denisahearn it is backported to 7.2 as well: https://github.com/rails/rails/commit/ef5276a9dba516285ae1834dadedb727896aab40

**Comment by brendon** [comment]
@p8, @rafaelfranca, what do you think about reverting this and just support loading the secret from `config/credentials/development.yml.enc` if it exists (else fall back to the text file). If `config/credentials.yml.enc` is the source then the default behaviour shouldn't change as the assumption is that these are production credentials.

**Comment by brendon** [comment]
It's a shame this wasn't given another look before 8.0.2 was released. Now you'll have a bunch of people who are confused as to why their ActionText asset links are suddenly broken in development.

**Comment by brendon** [comment]
> I'm one of those people, and I'm disappointed to see that the release notes didn't even say much about it. It seems like deleting the `credentials.yml.enc` file fixed it though for me in my development environment (whether this has other side affects I'm not sure yet, I'm very new to Rails and just wanted to figure out how to make stuff work again while I'm trying to learn it...).

Sorry to hear that. Your best bet for now is to roll back to `8.0.1` and reinstate `credentials.yml.enc` and wait for this to be reverted hopefully. I've created a PR that allows for the best of both worlds but so far it's received little attention.

**Comment by p8** [comment]
Note that you can always use multiple values for the `secret_key_base` :
```ruby
config.before_initialize do |app|
   app.message_verifiers.rotate secret_key_base: "original_secret_key_base"
   app.message_verifiers.rotate secret_key_base: "other_secret_key_base"
end
```

**Comment by p8** [comment]
> That's fine, but suddenly changing the behaviour of the tmp file and using the same secret_key_base in credentials.yml.enc for both development and production in a patch release ...

There where multiple issues in 7.2 that this PR tries to fix.
Rails not using the `secret_key_base` from credentials in development seems [like a bug](https://github.com/rails/rails/issues/54277#issuecomment-2598764148).

I know the single credentials file is the current Rails default, but I've always used environment specific credentials, so I haven't experienced the problems you ran into.

If you have a single credentials file for dev, test and production you are probably mixing other secrets as well, for example S3 secrets. Do you store ActiveStorage uploads in the same bucket as production? Does every developer have access to these secrets?

The `secret_key_base` is the only secret that is required for running a new app. 
So I always thought  the `tmp/local_secret.txt` was used for getting an application running locally without having to define `ENV['SECRET_KEY_BASE']` or using the credentials file. 

If we use it to override the `secret_key_base` in credentials to not mix dev and production secrets, all secrets in the credentials file should have their `tmp` file. I'm not sure that is viable.
Also, I think you should be able to remove the `tmp` dir anytime without your application breaking.
So I don't think we should relying on that file to be persisted.

Would you mind opening a new issue that addresses the problem you ran into?
That would give it more visibility than this closed issue.

**Comment by brendon** [comment]
Thanks @p8, I will open a new issue. For context, this is the genesis of the encrypted secrets feature:

https://github.com/rails/rails/pull/30067#issue-247861677

In DHH's first comment he claims that the file should only be for production and that other development keys can be handled separately. Of course this wasn't too popular and it appears that multiple environment credentials were deployed via this PR:

https://github.com/rails/rails/pull/33521

You're right in that I was forced to store development secrets in that file where it made sense for them to differ (e.g. R2 storage keys). I definitely don't store development assets in my production bucket! :)

But for some other credentials it doesn't matter that they're the same. At the time I remember being frustrated at the removal of the fallback feature of the original secrets system.

I guess going forward, if nothing else is done, one needs to have an encrypted secrets file for every environment they use (including `test`) with keys repeated across those environments.

This PR is a significant breaking change for those of us with older Rails apps that have grown through all these permutations of secrets and credentials. Perhaps in the meantime you could change the 8.0.2 CHANGELOG to make it quite loud about this being a breaking change and that users need to create themselves a development encrypted credentials file and copy their tmp file `secret_key_base` across to it (in addition to all the other necessary keys in their production encrypted secrets file) in order for development to still work.

**Comment by brendon** [comment]
New issue is here: https://github.com/rails/rails/issues/54778

**Comment by AlexWayfer** [comment]
> @denisahearn it is backported to 7.2 as well: [ef5276a](https://github.com/rails/rails/commit/ef5276a9dba516285ae1834dadedb727896aab40)

It has been created in January. v7.2.2.2 has been released in August. And this commit among 355 others in 7.2 branch, but still not released: https://github.com/rails/rails/compare/v7.2.2.2...7-2-stable

I'm looking for work-arounds. Our CI fails phantomly with parallel tests.

**Comment by rafaelfranca** [comment]
> I'm looking for work-arounds

You can point to 7-2-stable.

**Comment by AlexWayfer** [comment]
> > I'm looking for work-arounds
> 
> You can point to 7-2-stable.

I'm going to update Rails to v8, it seems better.

**Comment by rafaelfranca** [comment]
Yeah, that is a possibility. We will release 7.2.x soon though, but I just want to point out that pointing to the stable branches isn't a sin. It is a totally acceptable way to get fixes earlier without the release. It is safe, because bundler locks which commit is used.

**Comment by AlexWayfer** [comment]
> Yeah, that is a possibility. We will release 7.2.x soon though, but I just want to point out that pointing to the stable branches isn't a sin. It is a totally acceptable way to get fixes earlier without the release. It is safe, because bundler locks which commit is used.

OK, I got it now, thanks.

**Comment by rafaelfranca** [comment]
Just so you can follow. The reason why I didn't release 7.2.x yet is because I'm trying to also release a last version of 7.0 and 7.1. They CI is currently broken and I'm trying to fix. After that I should release 7.2

**Comment by AlexWayfer** [comment]
> Just so you can follow. The reason why I didn't release 7.2.x yet is because I'm trying to also release a last version of 7.0 and 7.1. They CI is currently broken and I'm trying to fix. After that I should release 7.2

It was just strange to me that fix has been merged in January and 7.2 release after a half-year doesn't include it. Also it's difficult for me to imagine a new patch or minor release with 300+ commits. But it's up to you, I'm just watching and discussing, your advice about release branch is accepted (but unlikely to be applied).
