### PR TITLE
Deprecate `:pool_size` and `:pool_timeout` options for configuring connection pooling in cache stores

### LINKED ISSUE #39479: Enabling connection pooling on RedisCacheStore requires overriding/repeating default values
### Steps to reproduce

In the [edge guides for "Caching with Rails"](https://edgeguides.rubyonrails.org/caching_with_rails.html#connection-pool-options) it says that to enable connection pooling for redis, you have to specify `pool_size` and/or `pool_timeout`, and that the default values for each is `5`.

It appears that the only way to actually enable connection pooling is to specify one or both of these values, even though the convention defaults are sensible values. It might be better to have a way to enable connection pooling that doesn't require specifying values that are already defined.

```ruby
config.cache_store = :redis_cache_store, {
   # no pool settings, so it won't use the connection pool
}
```

```ruby
config.cache_store = :redis_cache_store, {
   pool_size: 5 # but this is the default value, don't set it again!
}
```

Looking up the pool options returns an empty hash if neither of those values are set:

https://github.com/rails/rails/blob/a5d1628c79ab89dfae57ec1e1aeca467e29de188/activesupport/lib/active_support/cache.rb#L168-L173

And in the redis cache store code, it checks if the hash of options is empty, which it is if neither value is set:

https://github.com/rails/rails/blob/9b4aef4be3dc58eb08f694387857b52be8050954/activesupport/lib/active_support/cache/redis_cache_store.rb#L185-L192

So no connection pooling. :(

### Expected behavior

Connection pooling can be enabled without having to override the defaults. Perhaps a `pool` option that can either be a boolean or an options hash? 

```ruby
# just turn on connection pooling

config.cache_store = :redis_cache_store, {
   pool: true
}

# OR set specific options

config.cache_store = :redis_cache_store, {
  pool: {
    size: 8, # now I can override
    timeout: 15 # and override
  }
}
```

### Actual behavior

I have to override the defaults to enable connection pooling!

### System configuration
**Rails version**: 6.0.3.1

**Ruby version**: 2.6.5

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #39479.

cc @byroot

### CODE REVIEW

File: activesupport/test/cache/behaviors/connection_pool_behavior.rb [hunk 1]
```diff
@@ -50,6 +50,35 @@ def test_no_connection_pool
...
+    emulating_latency do
+      assert_deprecated do
+        cache = ActiveSupport::Cache.lookup_store(*store, { pool_size: 2, pool_timeout: 1 }.merge(store_options))
+        cache.read("foo")
+
+        assert_raises Timeout::Error do
+          # One of the three threads will fail in 1 second because our pool size
+          # is only two.
+          3.times do
+            threads << Thread.new do
```
Comment (casperisfine) [inline activesupport/test/cache/behaviors/connection_pool_behavior.rb:67]: I don't think you need such a complicated test, I also fear it will be flaky. 

I'd recommend to just check wether pooling is enabled, you can use `instance_variable_get` or `send` if necessary to check the internal state of the store.

File: guides/source/caching_with_rails.md [hunk 2]
```diff
@@ -407,15 +407,18 @@ First, add the `connection_pool` gem to your Gemfile:
 gem 'connection_pool'
 ```
 
-Next, pass the `:pool_size` and/or `:pool_timeout` options when configuring the cache store:
+Next, set `:pool` option to `true` when configuring the cache store:
 
 ```ruby
-config.cache_store = :mem_cache_store, "cache.example.com", { pool_size: 5, pool_timeout: 5 }
+config.cache_store = :mem_cache_store, "cache.example.com", pool: true
```
Comment (casperisfine) [inline guides/source/caching_with_rails.md:413]: I think we should really make pooling the default. Most people deploy Rails in a threaded environment now, and having a single redis connection can be a major contention point.

Can be a followup though.

File: activesupport/test/cache/behaviors/connection_pool_behavior.rb (hunk 1 above)
Comment (fatkodima) [reply activesupport/test/cache/behaviors/connection_pool_behavior.rb]: I just replicated the test above 😄 Updated with the suggestion.

File: guides/source/caching_with_rails.md (hunk 2 above)
Comment (fatkodima) [reply guides/source/caching_with_rails.md:413]: Makes sense, but I agree, it probably would be better as a followup.

Comment (fatkodima) [reply guides/source/caching_with_rails.md:413]: @casperisfine When enabling pooling by default, how do you think we need to make `connection_pool` a requirement? I am not sure making `connection_pool` a dependency of `active_support` is a good idea?

Comment (byroot) [reply guides/source/caching_with_rails.md:413]: @fatkodima, no we can just display an error just like if you use `mem_cache_store` and are missing `dalli`.
