### PR TITLE
Check environment before loading Spring in boot.rb

### LINKED ISSUE #40428: Deploying to staging causes error with Spring binstub in boot.rb
### Steps to reproduce
`config/boot.rb` attempts to load spring with
```ruby
begin
  load File.expand_path("../bin/spring", __dir__)
rescue LoadError => e
  raise unless e.path.end_with?("/bin/spring")
end
```

Since this is production (and spring is development only), that load command generates an error:
`Gem::LoadError: spring is not part of the bundle. Add it to your Gemfile.`

That `LoadError` instance *does not* contain a public `#path` var/method, which causes the `.end_with?` to fail with: `NoMethodError: undefined method 'end_with?' for nil:NilClass` because `.path` ends up being nil.

I tried looking through the source (at `rails/railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt`) and am stuck with a "but how did it ever work?"

```bash
rails new tester
cd tester
bundle config --local without development:test
bundle install
bundle exec rake assets:precompile # or any other command which loads the environment
```

### Expected behavior
`e.path` should be a string.

### Actual behavior
`e.path` is `nil`.

### System configuration
**Rails version**: Master 8183963bcd6fd6bb6bc0e4dd4361b86d064fe70f

**Ruby version**: 2.7.1

### PR DESCRIPTION
**Pull request by jonathanhefner**
In #39632, `boot.rb` was changed to load `bin/spring`, with the intention of adding a check to Spring itself that would prevent Spring from running in production environments.  However, in a production environment, the Spring gem may not be installed.  Furthermore, `bin/spring` may raise an error other than `LoadError` if it has been overwritten by e.g. `bundle binstubs` as part of the deployment process.  Therefore, this commit adds the environment check to `boot.rb`.

This commit also changes the app generator to generate `bin/spring` directly, instead of delegating to `bundle exec spring binstub`.  This addresses an issue with the `--skip-bundle` flag.  Previously, `--skip-bundle` caused `bin/spring` to not be generated. Thus the user had to manually run `bundle exec spring binstub` later, though that was not documented nor explained.  Now, `bin/spring` is always generated.  Additionally, by guaranteeing that `bin/stub` is generated, we avoid the need for `rescue LoadError` in `boot.rb`.

### CODE REVIEW

File: railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt [hunk 1]
```diff
@@ -1,12 +1,12 @@
-<% unless options.skip_spring? -%>
-begin
-  load File.expand_path("../bin/spring", __dir__)
-rescue LoadError => e
-  raise unless e.path.end_with?("/bin/spring")
-end
-<% end -%>
```
Comment (stevenbuccini) [inline railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt:7]: I initially created my application with Rails@6.0 but recently have been running off Rails master.

I stumbled upon the Rails upgrade tool to upgrade my application from 6.0 to 6.1. Running the upgrade task caused this snippet code to be added to `boot.rb`.

However, this change prevented my application from deploying on Heroku. It appears that this code still looked for Spring although it wasn't installed as Spring is located in the `development` group within my Gemfile. I'm not sure why this is, but removing this snipped caused my application to successfully build.
```
-----> Detecting rake tasks
 !
 !     Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.
 !     /tmp/build_acae070e_/config/boot.rb:4:in `rescue in <top (required)>': undefined method `end_with?' for nil:NilClass (NoMethodError)
 !     from /tmp/build_acae070e_/config/boot.rb:1:in `<top (required)>'
 !     from /tmp/build_acae070e_/bin/rake:7:in `require_relative'
 !     from /tmp/build_acae070e_/bin/rake:7:in `<main>'
 !     /tmp/build_acae070e_/vendor/ruby-2.7.1/lib/ruby/2.7.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'spring' (= 2.1.1) among 140 total gem(s) (Gem::MissingSpecError)
 !     Checked in 'GEM_PATH=/tmp/build_acae070e_/vendor/bundle/ruby/2.7.0', execute `gem env` for more information
 !     from /tmp/build_acae070e_/vendor/ruby-2.7.1/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'
 !     from /tmp/build_acae070e_/vendor/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'
 !     from /tmp/build_acae070e_/bin/spring:14:in `<top (required)>'
 !     from /tmp/build_acae070e_/config/boot.rb:2:in `load'
 !     from /tmp/build_acae070e_/config/boot.rb:2:in `<top (required)>'
 !     from /tmp/build_acae070e_/bin/rake:7:in `require_relative'
 !     from /tmp/build_acae070e_/bin/rake:7:in `<main>'
```

File: railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt [hunk 2]
```diff
@@ -1,13 +1,13 @@
-<% unless options.skip_spring? -%>
-begin
+# frozen_string_literal: true
+
+ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)
+<% if spring_install? -%>
+
+if !defined?(Spring) && [nil, "development", "test"].include?(ENV["RAILS_ENV"])
   load File.expand_path("../bin/spring", __dir__)
```
Comment (eugeneius) [inline railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt:7]: If we're generating this file ourselves, it seems odd to continue to put it in `bin/`, when it's only ever going to be loaded from a file in `config/`. Or is the idea to let applications use it as a "regular" Spring binstub later?

**Review by eugeneius — COMMENTED** [review]
We can't ship 6.1 with https://github.com/rails/rails/issues/40428 unresolved, so we need to either roll forward with this fix or roll all the way back to the 6.0 behaviour.

File: railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt (hunk 2 above)
Comment (rafaelfranca) [reply railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt:7]: `bin/spring` is still a valid command. It is there so people can write custom spring commands and call them. `bin/spring rails` for example works. That file is a binstube. I don't think it should be in the config folder.

Comment (eugeneius) [reply railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt:7]: > `bin/spring rails` for example works

TIL! It seemed to me like the goal of https://github.com/rails/rails/pull/39225 was to make the Spring binstub unnecessary, but you're right that custom commands will still need it. To be honest I'm not totally clear on what we're trying to achieve with these changes, so I might bow out of reviewing this one 😬

File: railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt [hunk 3]
```diff
@@ -1,13 +1,13 @@
-<% unless options.skip_spring? -%>
-begin
+# frozen_string_literal: true
```
[the remark this answers is not in the document]
Comment (jonathanhefner) [reply railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt:1]: @rafaelfranca Thank you for fixing this in 80f7fd52b2559b83d7846b684688192279804319! :pray:

File: railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt [hunk 4]
```diff
@@ -1,13 +1,13 @@
...
+
+ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)
+<% if spring_install? -%>
+
+if !defined?(Spring) && [nil, "development", "test"].include?(ENV["RAILS_ENV"])
   load File.expand_path("../bin/spring", __dir__)
-rescue LoadError => e
-  raise unless e.path.end_with?("/bin/spring")
```
Comment (pftg) [inline railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt:5]: Hey, @eugeneius  why this has been removed? By default rails do not include spring into test env, so on CI with rails env test is not available. And before these changes, CI skipped spring. Now we have an error. I need to understand the reason in order to create a hot fix for that change.

Comment (jonathanhefner) [reply railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt:5]: @pftg Please see #40913.  Sorry for the trouble!

File: railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt [hunk 5]
```diff
@@ -1,13 +1,13 @@
-<% unless options.skip_spring? -%>
-begin
+# frozen_string_literal: true
+
+ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)
+<% if spring_install? -%>
+
+if !defined?(Spring) && [nil, "development", "test"].include?(ENV["RAILS_ENV"])
```
Comment (pftg) [inline railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt:6]: for CI these changes are not working with the default Gemfile on the board and recommendations from rails/spring. Load error handling has provided support of the CI.

So bin/spring only available on a developers machine, on production and test instances we do not have it.
