### PR TITLE
Fix with_options bug when first argument is a Proc

### LINKED ISSUE #45183: with_options does not work if first argument is proc and arity > 1
### Steps to reproduce

```ruby
require 'active_support'
require 'active_support/core_ext'

class Foo
  def self.foo(val1, **hash1)
    p val1, hash1
  end
end
Foo.foo(10, b: 20) # ok
Foo.foo(proc {}, b: 20) # ok

class Foo
  with_options(a: 30) { foo(10, b: 20) } # ok
  with_options(a: 30) { foo(proc {}, b: 20) } # raise
end
```

### Expected behavior

with_options parameter is merged into last hash-like argument

### Actual behavior

raises error
```
`foo': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

### System configuration
**Rails version**:
6.1.5

**Ruby version**:
3.1.2

### PR DESCRIPTION
**Pull request by dirceu**
An ArgumentError was being raised when methods were called with (proc, options) inside a `with_options` block:

```ruby
def my_method(arg1, **kwargs)
  [arg1, kwargs]
end

# this would raise instead of merging options
with_options(hello: "world") do
  my_method(proc {}, {fizz: "buzz"})
end
```

Fixes #45183

### CODE REVIEW

File: activesupport/test/option_merger_test.rb [hunk 1]
```diff
@@ -125,4 +132,8 @@ def method_with_kwargs(*args, **options)
     def method_with_kwargs_only(**options)
       options
     end
+
+    def method_returning_args_and_options(*args, **options)
+      [args, options]
+    end
```
Comment (jonathanhefner) [inline activesupport/test/option_merger_test.rb:138]: Instead of potentially involving kwargs (`**`) here, let's deal with positional args only:

```suggestion
    def method_with_args(*args)
      args
    end
```

And then we can move this method definition right above `method_with_options`.

File: activesupport/test/option_merger_test.rb [hunk 2]
```diff
@@ -84,13 +84,20 @@ def test_nested_method_with_options_containing_hashes_going_deep
...
     with_options(@options) do |o|
       assert_equal @options.merge(local_lambda.call), o.method_with_options(local_lambda).call
     end
   end
 
+  def test_proc_as_first_argument_with_other_options_should_still_merge_options
+    p = proc { }
+    with_options(@options) do |o|
+      assert_equal [[p], @options.merge({ a: "b" })], o.method_returning_args_and_options(p, { a: "b" })
+    end
```
Comment (jonathanhefner) [inline activesupport/test/option_merger_test.rb:98]: Single-letter names make this slightly harder to digest.  What about mirroring the other tests using the following?

```suggestion
    local_proc = proc { }
    local_options = { "cool" => true }
    
    with_options(@options) do |o|
      assert_equal [local_proc, @options.merge(local_options)], o.method_with_args(local_proc, local_options)
    end
```

**Review by jonathanhefner — COMMENTED** [review]
Thank you for fixing this! :smiley:

**Comment by dirceu** [comment]
Updated, thanks for the suggestions!

**Comment by jonathanhefner** [comment]
Thank you again, @dirceu! :tada:
