### PR TITLE
Fix: Strict Loading error after initializing association owner with primary key

### LINKED ISSUE #46392: `ActiveRecord::StrictLoadingViolationError` after initializing association owner with primary key
### Steps to reproduce

When initializing a model with an id attribute (without persisting it), working with a `has_many` association raises a `StrictLoadingViolationError`.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.new(id: 1)
    post.strict_loading!

    post.comments << Comment.new
  end
end
```

### Expected behavior

The `StrictLoadingViolationError` should not be raised, because no records are persisted and thus are not loaded lazily.

### Actual behavior

ActiveRecord will throw a `StrictLoadingViolationError`.

After some digging through the code I think it's because it tries to load the `comments` association. It does that because `ActiveRecord::Associations::Association::find_target?` (see [here](https://github.com/rails/rails/blob/2612b88abfca6ac80db1923e133d5e7822bcef0b/activerecord/lib/active_record/associations/association.rb#L274)) returns `true`. This is due to the foreign key column (in this case Post's `id` column) being present on the post model (see [here](https://github.com/rails/rails/blob/2612b88abfca6ac80db1923e133d5e7822bcef0b/activerecord/lib/active_record/associations/foreign_association.rb#L7) for the check).

I'm not sure if this use case should even be supported, so feel free to close this if initializing a model with an id should not be supported. My use case is testing serializers without creating database traffic, but I'd be fine disabling strict loading for those tests.

### System configuration
**Rails version**: main (2612b88)

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

### PR DESCRIPTION
**Pull request by ghiculescu**
Fixes https://github.com/rails/rails/issues/46392

See inline comments for explanation of the change.

### CODE REVIEW

File: activerecord/lib/active_record/associations/collection_association.rb [hunk 1]
```diff
@@ -119,7 +119,6 @@ def build(attributes = nil, &block)
       def concat(*records)
         records = records.flatten
         if owner.new_record?
-          load_target
```
Comment (ghiculescu) [inline activerecord/lib/active_record/associations/collection_association.rb:122]: Removing this line fixes the given issue. The only test that fails if you remove this line is [this one](https://github.com/rails/rails/blob/2612b88abfca6ac80db1923e133d5e7822bcef0b/activerecord/test/cases/associations/join_model_test.rb#L494), and so the other change in this file is an alternative way of keeping that functionality working.

File: activerecord/lib/active_record/associations/collection_association.rb [hunk 2]
```diff
@@ -119,7 +119,7 @@ def build(attributes = nil, &block)
...
+          loaded!
```
Comment (ghiculescu) [inline activerecord/lib/active_record/associations/collection_association.rb:122]: We need to call `loaded!` here because [this test](https://github.com/rails/rails/blob/c6b227b95b631ead7ffd5c8984b16b0fbe5b3ca4/activerecord/test/cases/associations_test.rb#L161) expects it (ref https://github.com/rails/rails/commit/df0765d8dc013ccd399d994109eaf39be4c24e81).

But I don't think we to call `load_target`; as this is a new record, I don't expect it to find any records.

File: activerecord/lib/active_record/associations/collection_association.rb [hunk 3]
```diff
@@ -249,7 +249,7 @@ def replace(other_array)
 
       def include?(record)
         if record.is_a?(reflection.klass)
-          if record.new_record?
+          if record.new_record? || owner.new_record?
```
Comment (ghiculescu) [inline activerecord/lib/active_record/associations/collection_association.rb:252]: This change is needed to make [this assertion](https://github.com/rails/rails/blob/c6b227b95b631ead7ffd5c8984b16b0fbe5b3ca4/activerecord/test/cases/associations/join_model_test.rb#L494) pass, and I think it's a more correct solution too.
