### PR TITLE
Unify raise_on_missing_translations for views and controllers

### LINKED ISSUE #24138: I18n exception feature doesn't apply to ActionController
Using `config.action_view.raise_on_missing_translations = true` for the purposes of testing translation completeness doesn't effect translations that occur within a controller, for example..

`redirect_to polymorphic_url([@thing]), notice: t('.success_message', name: @thing.name)`

Given that people use this feature for the express purpose of testing their translations, the support for t() in controllers should also support throwing exceptions.  I've ended up monkey patching for now to support this.

### LINKED ISSUE #25116: Raise on missing translations does not include controllers
The option `raise_on_missing_translations` is scoped to `ActionView`. Since `AbstractController` provides its own implementation of `translate` and `localize` it does not include the "raise on missing" behaviour.

This is problematic, I can't think of a use case where you'd want to only raise exceptions in either views or controllers. Usually, if you want to raise errors, you want the behaviour everywhere.

There was another issue addressing the issue (https://github.com/rails/rails/issues/24138) but it was closed and no pull request have emerged.

I'd be happy to create a pull request addressing the issue, but I think it's important that we decide how we want to go about implementing this.

I think the option should be moved out of `config.action_view` and instead be moved into `config.i18n.raise_on_missing_translation`. `AbstractionController` and `TranslationHelper` can then utilize this option in their implementation. Doing this would also mean deprecating `config.action_view.raise_on_missing_translations`.

### PR DESCRIPTION
**Pull request by fatkodima**
This PR generalizes `raise_on_missing_translations` config option from `action_view` scope into `i18n` so it can be used for controllers too.

Existing applications should receive deprecation warnings and continue to use old `config.action_view. raise_on_missing_translations` to affect only view's `#translate` method until they decide to switch to new option. And then it should affect both controllers and views.

Fixes https://github.com/rails/rails/issues/24138.
Fixes https://github.com/rails/rails/issues/25116.
Brief discussion [here](https://groups.google.com/forum/?fromgroups#!topic/rubyonrails-core/nNrgPhWUl-c).

### CODE REVIEW

**Comment by fatkodima** [comment]
@rafaelfranca Can you, please, review?

File: actionpack/lib/abstract_controller/translation.rb [hunk 1]
```diff
@@ -18,7 +18,9 @@ def translate(key, options = {})
         options[:default] = defaults.flatten
         key = "#{path}.#{action_name}#{key}"
       end
-      I18n.translate(key, options)
+
+      i18n_raise = options.fetch(:raise, Rails.configuration.i18n.raise_on_missing_translations)
```
Comment (eugeneius) [inline actionpack/lib/abstract_controller/translation.rb]: Action Pack shouldn't know about the `Rails` constant since that couples it to the Railties gem, which isn't one of its dependencies - it should be possible to use Action Pack outside of a Rails application.

The way configuration works (as I understand it) is:

 - During initialization, the application makes changes to `Rails.configuration`
 - After initialization, the frameworks' railties copy those values into the frameworks somewhere
 - At runtime, the frameworks use their own copy of the values to make decisions

With that in mind, I think the right thing to do here is to add a `raise_on_missing_translations` setting to `AbstractController::Base`, similar to the one on `ActionView::Base`, and set both from the i18n railtie.

**Comment by fatkodima** [comment]
@rafaelfranca Wdyt about moving this forward?

**Comment by fatkodima** [comment]
@eugeneius 
Updated with your suggestion, ready for review.

File: actionpack/lib/abstract_controller/translation.rb [hunk 2]
```diff
@@ -20,7 +26,9 @@ def translate(key, **options)
         options[:default] = defaults.flatten
         key = "#{path}.#{action_name}#{key}"
       end
-      I18n.translate(key, **options)
+
+      i18n_raise = options.fetch(:raise, ActionController::Base.raise_on_missing_translations)
```
Comment (eugeneius) [inline actionpack/lib/abstract_controller/translation.rb:30]: Referencing `ActionController::Base` here will cause it to be loaded for API-only applications that include this module manually, which is documented here:

https://guides.rubyonrails.org/api_app.html#adding-other-modules

Maybe the configuration option should be defined directly on this module?

File: actionpack/lib/abstract_controller/translation.rb [hunk 3]
```diff
@@ -20,7 +26,9 @@ def translate(key, **options)
...
+      I18n.translate(key, options.merge!(raise: i18n_raise))
```
Comment (eugeneius) [inline actionpack/lib/abstract_controller/translation.rb:31]: These options need to be splatted to prevent a warning on Ruby 2.7:

https://buildkite.com/rails/rails/builds/69325#216048d0-21ef-469c-84d4-8e967af55241

```suggestion
      I18n.translate(key, **options, raise: i18n_raise)
```

File: actionview/lib/action_view/railtie.rb [hunk 4]
```diff
@@ -43,6 +43,12 @@ class Railtie < Rails::Engine # :nodoc:
     config.after_initialize do |app|
       ActiveSupport.on_load(:action_view) do
         app.config.action_view.each do |k, v|
+          if k == :raise_on_missing_translations
+            ActiveSupport::Deprecation.warn \
+              "action_view.raise_on_missing_translations is deprecated and will be removed in Rails 6.1. " \
```
Comment (eugeneius) [inline actionview/lib/action_view/railtie.rb:48]:
```suggestion
              "action_view.raise_on_missing_translations is deprecated and will be removed in Rails 6.2. " \
```

File: guides/source/configuring.md [hunk 5]
```diff
@@ -348,6 +348,9 @@ All these configuration options are delegated to the `I18n` library.
 
 * `config.i18n.load_path` sets the path Rails uses to look for locale files. Defaults to `config/locales/*.{yml,rb}`.
 
+* `config.i18n.raise_on_missing_translations` determines whether an error should be raised for missing translations
+in controllers and views This defaults to `false`.
```
Comment (eugeneius) [inline guides/source/configuring.md:352]:
```suggestion
* `config.i18n.raise_on_missing_translations` determines whether an error should be raised for missing translations
in controllers and views. This defaults to `false`.
```

**Comment by fatkodima** [comment]
Thanks, @eugeneius ! 
Updated with your suggestions. Actually the size of this pr now is one third of the original size 💪

**Review by eugeneius — APPROVED** [review]
There's a merge conflict, would you mind rebasing? Otherwise I think this is ready! ⭐

**Comment by fatkodima** [comment]
Rebased.

**Comment by eugeneius** [comment]
Thanks! It's great to see this finally merged 🥳

**Comment by fatkodima** [comment]
❤️ 
There is another old one I would love to get merged - https://github.com/rails/rails/pull/31595
@eugeneius would you mind reopening it so I will update?

**Comment by eugeneius** [comment]
Done 👍
