### PR TITLE
Make prepared statement status thread and instance-specific

### LINKED ISSUE #36763: Rails 6 RC2 regression: (postgres) prepared statement improperly parameterized
### Steps to reproduce
~I haven't been able to create a minimal example that demonstrates the problem, unfortunately. (I tried.)~

I put together a simple app that demonstrates the problem: https://github.com/careport/racy

At root, the problem is that, in system tests, a single database connection is shared among all server threads. This interacts badly with uses of `unprepared_statement`, since the latter modifies the `@prepapred_statements` instance variable on the connection. That change is visible to other threads sharing the connection. As a consequence, some queries wind up incorrectly parameterized.

I do not yet understand why this problem doesn't manifest before commit 853f5680e8c79a51f5c0bf1624b1a5d3d3df2802. I'll continue to look into it, but it might be more obvious to someone with more knowledge of AR internals.

Old description below:
---
When running a particular system test in our test suite, we often (though not always) get the error:
```
     ActiveRecord::StatementInvalid:
       PG::ProtocolViolation: ERROR:  bind message supplies 0 parameters, but prepared statement "" requires 2
```

or, less frequently, the reverse:
```
     ActiveRecord::StatementInvalid:
       PG::ProtocolViolation: ERROR:  bind message supplies 2 parameters, but prepared statement "a21" requires 0
```
These errors occur at the same point in the program execution. It's an ActiveRecord query that does not use any Arel methods. (I mention this, because previous bug reports with similar PG driver errors were caused by [bad interaction between ActiveRecord and Arel](https://github.com/rails/rails/issues/20077). That is _not_ what is going on here.

It appears to be a race between two requests. The problem starts with commit 853f5680e8c79a51f5c0bf1624b1a5d3d3df2802, which merged #36618.

I should mention that we're using rspec-rails 4.0.0.beta2, so it could be bad interaction between rspec and rails. But the error really does not happen prior to that commit.

### Expected behavior
The database error described above should not occur.

### Actual behavior
The database error does occur.

### System configuration
**Rails version**: 6.0.0.rc2, but really anything on 6-0-stable starting with 853f5680e8c79a51f5c0bf1624b1a5d3d3df2802

**Ruby version**:
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin17]
(Though this also happens on our CI server, which runs linux, not OS X.)

### PR DESCRIPTION
**Pull request by 97jaz**
This fixes a race condition in system tests where prepared
statements can be incorrectly parameterized when multiple
threads observe the mutation of the @prepared_statements
instance variable on the connection.

Fixes #36763

### CODE REVIEW

**Review by rafaelfranca — APPROVED** [review]

**Comment by 97jaz** [comment]
Come to think of it, this isn't memory-safe. The `Concurrent::Map` isn't a weak map (as far as I know), so it will hold onto the threads even after they're dead. 

I think there's a better tool in this tool-box...

**Comment by 97jaz** [comment]
@rafaelfranca I just changed the implementation to use `Concurrent::ThreadLocalVar`, instead of `Concurrent::Map`. Otherwise, it's the safe. This should be memory-safe.

**Review by rafaelfranca — APPROVED** [review]

File: activerecord/lib/active_record/connection_adapters/abstract_adapter.rb [hunk 1]
```diff
@@ -174,6 +175,14 @@ def schema_migration # :nodoc:
                               end
       end
 
+      def prepared_statements # :nodoc:
```
Comment (matthewd) [inline activerecord/lib/active_record/connection_adapters/abstract_adapter.rb]: Should this be documented? Sounds like the attribute was before.

File: activerecord/lib/active_record/connection_adapters/abstract_adapter.rb [hunk 2]
```diff
@@ -174,6 +175,14 @@ def schema_migration # :nodoc:
...
+        @prepared_statement_status.value
+      end
+
+      def prepared_statements=(prepared_statements) # :nodoc:
```
Comment (matthewd) [inline activerecord/lib/active_record/connection_adapters/abstract_adapter.rb]: I think this can (should) be private -- no external callers

**Review by matthewd — APPROVED** [review]
Looks great!

File: activerecord/lib/active_record/connection_adapters/abstract_adapter.rb (hunk 1 above)
Comment (97jaz) [reply activerecord/lib/active_record/connection_adapters/abstract_adapter.rb]: It was previously an `attr_reader` without documentation.

File: activerecord/lib/active_record/connection_adapters/abstract_adapter.rb (hunk 2 above)
Comment (97jaz) [reply activerecord/lib/active_record/connection_adapters/abstract_adapter.rb]: Good point. Changed.

File: activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb [hunk 3]
```diff
@@ -40,7 +40,7 @@ class Mysql2Adapter < AbstractMysqlAdapter
 
       def initialize(connection, logger, connection_options, config)
         super
-        @prepared_statements = false unless config.key?(:prepared_statements)
+        self.prepared_statements = false unless config.key?(:prepared_statements)
```
Comment (97jaz) [inline activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb]: This isn't quite right. It will set the value for the current thread, but the default value will already have been set in the `super` call. So other threads won't necessarily behave correctly.

The simplest fix is just to overwrite the instance variable here with a new `ThreadLocalVar` that has the correct default. The alternative would be to communicate the default to the superclass implementation, but that seems like a pain.

Comment (matthewd) [reply activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb]: Ah, good catch. Something like `super(connection, logger, connection_options, config.reverse_merge(prepared_statements: false))` doesn't seem too terrible, but I'm happy with overwriting the instance variable too. 👍🏻

File: activerecord/lib/active_record/connection_adapters/abstract_adapter.rb (hunk 1 above)
Comment (matthewd) [reply activerecord/lib/active_record/connection_adapters/abstract_adapter.rb]: Right, so it's listed under Attributes in https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/AbstractAdapter.html. `:nodoc:` means "this is explicitly undocumented/unsupported, and not part of our promised API". To be clear, I'm not suggesting we need to write words.. just that it shouldn't disappear completely.

```suggestion
      def prepared_statements
```

File: activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb (hunk 3 above)
Comment (97jaz) [reply activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb]: Oh, well if we're allowed to pass a modified config, then I like your idea better.

File: activerecord/lib/active_record/connection_adapters/abstract_adapter.rb (hunk 1 above)
Comment (97jaz) [reply activerecord/lib/active_record/connection_adapters/abstract_adapter.rb]: Ah! Ok, got it.

File: activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb (hunk 3 above)
Comment (97jaz) [reply activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb]: Heh, once I change this and fix the mysql behavior, the test I added fails on mysql, because the test assumes that prepared statements are enabled by default. So I'm changing the test to be conditional.

**Comment by SamSaffron** [comment]
@rafaelfranca  / @matthewd 

There is a slight unintended consequence to this change I will monkey patch out of Discourse.

The implementation of RubyThreadLocalVar wacks a finalizer on the object, the finalizer spins a thread.

https://github.com//blob/bbeacbcebf72668ed04df0738df7e3a654f7c177/lib/concurrent/atomic/ruby_thread_local_var.rb#L101-L111

We use no prepared statements, but are now paying the penalty of spinning up a thread every time a connection is closed.

This has this impact on my graphs for the big multisites:

https://meta.discourse.org/t/upgrading-discourse-to-rails-6/128004/11?u=sam

Since once false this thing can never be turned true I will just implement an Immutable ThreadLocalVar class here for the cases where prepared statements are false. (bind anything but current value and it raises.

```diff --git a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb b/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb
index 91d5d08121..970a1f9e8f 100644
--- a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb
+++ b/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb
@@ -114,6 +114,18 @@ def self.quoted_table_names # :nodoc:
         @quoted_table_names ||= {}
       end
 
+      class StaticThreadLocalVar
+        attr_reader :value
+
+        def initialize(value)
+          @value = value
+        end
+
+        def bind(value)
+          raise "attempting to change immutable local var" if value != @value
+        end
+      end
+
       def initialize(connection, logger = nil, config = {}) # :nodoc:
         super()
 
@@ -132,7 +144,7 @@ def initialize(connection, logger = nil, config = {}) # :nodoc:
           @prepared_statement_status = Concurrent::ThreadLocalVar.new(true)
           @visitor.extend(DetermineIfPreparableVisitor)
         else
-          @prepared_statement_status = Concurrent::ThreadLocalVar.new(false)
+          @prepared_statement_status = StaticThreadLocalVar.new(false)
         end
 
         @advisory_locks_enabled = self.class.type_cast_config_to_boolean(
```

Thoughts? Should we patch this in Rails?

**Comment by SamSaffron** [comment]
@rafaelfranca awesome, lets first give this a shot, but if it fails we can pull this into rails. 

https://github.com/ruby-concurrency/concurrent-ruby/pull/823

**Comment by talpava** [comment]
10:31, 13 сентября 2019 г., Sam <notifications@github.com>:@rafaelfranca awesome, lets first give this a shot, but if it fails we can pull this into rails.
ruby-concurrency/concurrent-ruby#823

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
Отправлено из мобильной Яндекс.Почты: http://yandex
