### PR TITLE
Fix cache issue when different partials use the same collection

### LINKED ISSUE #20535: Issue running AutomaticCollectionCacheTest tests in a specific order
It appeared in [this build](https://travis-ci.org/rails/rails/jobs/66489622) for the commit 0965be14e22c4d1fd6befda4fd3efb942e0701ca using `--seed 49713`. Even with that seed, it does not always happen.

So far, it seems that [AutomaticCollectionCacheTest#test_explicit_render_call_with_options](https://github.com/rails/rails/blob/8beb328befa53d74fe9c7942ddb188563bd4de33/actionpack/test/controller/caching_test.rb#L400) is being called before [AutomaticCollectionCacheTest#test_caching_works_with_beginning_comment](https://github.com/rails/rails/blob/8beb328befa53d74fe9c7942ddb188563bd4de33/actionpack/test/controller/caching_test.rb#L406) and is adding the partial `customers/customer` to the cache. That prevents the action `index_with_comment` to actually render `customers/commented_customer` and provides it the cached output, since both partials do generate the same output and have the same `collection`.

I thought that ActiveSupport::Cache::MemoryStore was having issues keeping it thread-safe, but I believe is working as designed if you consider that the tests are running from the same process and thread.

@rafaelfranca any thought on this?

### PR DESCRIPTION
**Pull request by repinel**
It adds the partial `virtual_path` to the caching key: instead of something like `views/david/1` it will be `views/customers/_customer/david/1`.

@kaspth Would you think this is valid?

Fixes #20535

### CODE REVIEW

**Comment by kaspth** [comment]
I personally don't think this is the way to go. But I'll keep it open for now, and wait until we've figured something out on #20535.

**Comment by kaspth** [comment]
I've reversed my position on this, we definitely need to de something about this. But I'm not sure adding the virtual path is what we want.

I've just tried running this locally and you're right the cache keys do clash between the two templates even though they're different. It seems the digest isn't appended to the cache key in the tests (I've tried it in tests apps and those work fine). If you can figure out why the digest isn't appended (and then make it appended), we should go with that :smile:

```
D, [2015-06-15T22:34:55.608574 #93985] DEBUG -- : Caches multi read:
- views/david/1
D, [2015-06-15T22:34:55.611018 #93985] DEBUG -- : Cache write: views/david/1
D, [2015-06-15T22:34:55.613526 #93985] DEBUG -- : Caches multi read:
- views/david/1
```

**Comment by repinel** [comment]
That's the exactly the issue was having.

You are right, using the digest is better. I just wasn't sure if it was missing be design. I'll check it out later :wink:

**Comment by repinel** [comment]
@kaspth Let me know what you think about the current implementation.

It provides `fragment_name_with_digest` the `virtual_path` so it can be used to generate the key with digest and void collision.

File: actionview/lib/action_view/helpers/cache_helper.rb [hunk 1]
```diff
@@ -184,7 +184,7 @@ def cache_fragment_name(name = {}, options = nil)
         if skip_digest
           name
         else
-          fragment_name_with_digest(name)
+          fragment_name_with_digest(name, virtual_path: options.try(:[], :virtual_path))
```
Comment (kaspth) [inline actionview/lib/action_view/helpers/cache_helper.rb]: If we're changing a method anyway, it's okay to switch it to use keyword arguments completely.

File: actionview/lib/action_view/helpers/cache_helper.rb [hunk 2]
```diff
@@ -198,10 +198,12 @@ def fragment_cache_key(key)
 
     private
 
-      def fragment_name_with_digest(name) #:nodoc:
-        if @virtual_path
+      def fragment_name_with_digest(name, virtual_path: nil) #:nodoc:
```
Comment (kaspth) [inline actionview/lib/action_view/helpers/cache_helper.rb]: `virtual_path` doesn't need to be a keyword argument, when we're passing it straight down from `cache_fragment_name`.

File: actionview/lib/action_view/helpers/cache_helper.rb [hunk 3]
```diff
@@ -198,10 +198,12 @@ def fragment_cache_key(key)
...
+        virtual_path ||= @virtual_path
+        if virtual_path
           names  = Array(name.is_a?(Hash) ? controller.url_for(name).split("://").last : name)
-          digest = Digestor.digest name: @virtual_path, finder: lookup_context, dependencies: view_cache_dependencies
+          dependencies = defined?(view_cache_dependencies) ? view_cache_dependencies : []
```
Comment (kaspth) [inline actionview/lib/action_view/helpers/cache_helper.rb]: Why are we checking `defined?` here? Do we have to pass an empty array or will nil do? If the latter, we could do:

```ruby
dependencies = view_cache_dependencies if defined?(view_cache_dependencies)
```

File: actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb [hunk 4]
```diff
@@ -51,7 +51,7 @@ def collection_by_cache_keys
       end
 
       def expanded_cache_key(key)
-        key = @view.fragment_cache_key(@view.cache_fragment_name(key))
+        key = @view.fragment_cache_key(@view.cache_fragment_name(key, virtual_path: @template.virtual_path))
```
Comment (kaspth) [inline actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb]: @repinel do you have a good understanding of why `@view`'s `virtual_path` is nil, when this is called? I've forgotten parts of this code, so do fill me in if you know :smile:

File: actionview/test/template/render_test.rb [hunk 5]
```diff
@@ -636,11 +636,18 @@ class CachedCustomer < Customer; end
...
+    key = cache_key(customer, "test/_cached_customer_as")
 
     ActionView::PartialRenderer.collection_cache.write(key, 'Cached')
 
     assert_equal "Cached",
       @view.render(partial: "test/cached_customer_as", collection: [customer], as: :buyer)
   end
+
+  private
+
```
Comment (kaspth) [inline actionview/test/template/render_test.rb]: :scissors: this line

File: actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb (hunk 4 above)
Comment (repinel) [inline actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb]: I believe the `virtual_path` is only set to the context once the template is rendered. So when `fragment_name_with_digest ` is called from the partial using `cache`, it has the `@virtual_path` set.

**Comment by kaspth** [comment]
Overall, it's very good :+1:

I still want either @matthewd or @rafaelfranca to peruse it though, just to be safe :smile:

File: actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb (hunk 4 above)
Comment (kaspth) [inline actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb]: Sounds reasonable, thanks for the explanation :smile:

File: actionview/lib/action_view/helpers/cache_helper.rb (hunk 3 above)
Comment (repinel) [inline actionview/lib/action_view/helpers/cache_helper.rb]: @kaspth I was having issues with the tests on `CachedCollectionViewRenderTest`. They use `ActionView::Base` and `view_cache_dependencies` was not defined. The same will not happen if you run `AutomaticCollectionCacheTest`.

I'd rather not have to check for `view_cache_dependencies ` at all if possible. Any ideas? Thanks reviewing!

Comment (kaspth) [inline actionview/lib/action_view/helpers/cache_helper.rb]: `view_cache_dependencies` is defined as a helper method and that's why this doesn't work. Maybe we should just move all the tests to `controller/caching_test`? @rafaelfranca what do you think?

Comment (kaspth) [inline actionview/lib/action_view/helpers/cache_helper.rb]: `view_cache_dependencies` is defined as a helper method and that's why this doesn't work. Maybe we should just move all the tests to `controller/caching_test`? @rafaelfranca what do you think?

File: actionview/CHANGELOG.md [hunk 6]
```diff
@@ -1,3 +1,9 @@
+*   Add the template digest to the cache key for collection caching.
```
Comment (kaspth) [inline actionview/CHANGELOG.md]: This isn't entirely true. It works in real apps, I've seen the cache keys contain the digest there.

The tests render the collection from the controller and I think that's what screwing this up.

Comment (repinel) [inline actionview/CHANGELOG.md]: I just tried with [this sample app](https://github.com/repinel/my_app/tree/test-collection-cache) and the digest is not being attached to the cache key.

Using Rails from `master`:
```
cache/A87/A60:
views%2Fusers%2F2-20150620185152601259000

cache/A9D/470:
views%2Fusers%2F1-20150620185147798585000
```

With this fix:
```
cache/4DB/781:
views%2Fusers%2F2-20150620185152601259000%2F65ffadfc89bbc5250bc31f768b90bfdc

cache/4F1/1B1:
views%2Fusers%2F1-20150620185147798585000%2F65ffadfc89bbc5250bc31f768b90bfdc
```

@kaspth What do you think?

Comment (kaspth) [inline actionview/CHANGELOG.md]: Yep, the `@virtual_path` isn't set in `AutomaticCollectionCacheTest` `test_explicit_render_call_with_options` or `test_caching_works_with_beginning_comment` because they're both rendering in the controller.

The other actions `render 'index'` and will have a `@virtual_path` of `collection_cache/index`.

Comment (repinel) [inline actionview/CHANGELOG.md]: So, would you like to go with this?
> Always attach the template digest to the cache key for collection caching even when `virtual_path` is not directly available from the view context.

Comment (kaspth) [inline actionview/CHANGELOG.md]: :+1:, but I still want to add that this happened if you rendered in the controller, so maybe adding something like:


```
available from the view context. Which could happen if the rendering was done directly in the controller and not in a template.
```

**Comment by repinel** [comment]
I updated the last considerations. @kaspth thanks again for reviewing :smiley: 

@matthewd or @rafaelfranca let us know how it looks.

**Comment by kaspth** [comment]
@repinel can you rebase on master? Then I'll merge this :smile:

**Comment by repinel** [comment]
@kaspth It should be good now :smile:

**Comment by kaspth** [comment]
Cool! I'll just close and reopen so Travis runs :+1:

**Comment by kaspth** [comment]
@repinel :heart:

**Comment by repinel** [comment]
@kaspth thank you for all the reviews :heart:
