### PR TITLE
Fix `db:prepare` to run seeds once

### LINKED ISSUE #44957: Seed task runs multiple times and breaks with multi-database setup
### Steps to reproduce

1. Create a rails app with Rails version pointing to latest `7-0-stable` branch
2. Create multiple databases [as per docs](https://guides.rubyonrails.org/active_record_multiple_databases.html)
3. Add a print statement in `seeds.rb` file
4. Run db prepare task: `bin/rake db:prepare` - **Notice how print statement is executed multiple times**
6. Create a migration and model for the non-primary database [as per docs](https://guides.rubyonrails.org/active_record_multiple_databases.html#generators-and-migrations), eg:
```
bin/rails generate migration CreateDogs name:string --database animals
bin/rails generate scaffold Dog name:string --database animals
```
7. Add the following to `seeds.rb`
```
Dog.create!(name: "Harry")
```

8. Run db prepare task: `bin/rake db:prepare` - **Notice `ActiveRecord::NoDatabaseError` is thrown**

### Expected behavior
`seeds.rb` should run (once per environment?) after all the databases are created/migrated.

### Actual behavior
`seeds.rb` runs for every database after it's created/migrated. If there's an attempt to connect to any database other than the first one created/migrate, an exception is thrown eg:

```
ActiveRecord::NoDatabaseError: We could not find your database: animals.
```

I think this broke after https://github.com/rails/rails/pull/44820

### System configuration
**Rails version**: `7-0-stable` branch (ref: 391505c3f2d0859f7394e6bc685ba18567154ad7)

**Ruby version**: 3.1.1

### PR DESCRIPTION
**Pull request by fatkodima**
Closes #44957

I apologize, that was really introduced in https://github.com/rails/rails/pull/44820 by bad copy paste.

cc @eileencodes

### CODE REVIEW

File: railties/test/application/rake/multi_dbs_test.rb [hunk 1]
```diff
@@ -852,6 +852,28 @@ class TwoMigration < ActiveRecord::Migration::Current
...
       end
 
+      test "db:prepare runs seeds once" do
+        require "#{app_path}/config/environment"
+        Dir.chdir(app_path) do
+          use_postgresql(multi_db: true)
+
+          rails "db:drop"
+          generate_models_for_animals
+          rails "generate", "model", "recipe", "title:string"
```
Comment (nvasilevski) [inline railties/test/application/rake/multi_dbs_test.rb:862]: I'm curious about this piece, it doesn't seem like we use `Recipe` in the test

**Review by nvasilevski — COMMENTED** [review]
Thanks for a quick fix!

File: railties/test/application/rake/multi_dbs_test.rb (hunk 1 above)
Comment (fatkodima) [reply railties/test/application/rake/multi_dbs_test.rb:862]: We need migrations for both databases, so when we call `db:prepare`, it creates both databases before running migrations. And we expect seeds to run only once. 
Otherwise only `animals` database will be created and seeds will run once without code changes.

**Comment by eileencodes** [comment]
Backported to 7-0-stable in 8b426e9d58cc6dfcc12d4bdea5d30b89a0496bc4
