### PR TITLE
Use round(scale) in  ActiveModel NumericalityValidator

### LINKED ISSUE #40902: Rails 6.1 - problem with numericality validator
### Steps to reproduce
This test passes on Rails 6.0.3.4 and fails on Rails 6.1.0:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", ARGV[0]
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "mysql2")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :purchases, force: true do |t|
    t.decimal :subtotal, precision: 5, scale: 2
  end
end

class Purchase < ActiveRecord::Base
  validates_numericality_of :subtotal, less_than_or_equal_to: 999.99
end

class BugTest < Minitest::Test
  def test_numericality
    purchase = Purchase.new
    purchase.subtotal = 999.999 # 999.991 should also cause a validation error

    assert_equal 1000.0, purchase.subtotal
    assert purchase.invalid?
    assert_equal ["must be less than or equal to 999.99"], purchase.errors[:subtotal]
  end
end
```

### Expected behavior
```
$ ruby active_record_gem.rb 6.0.3.4
# ...
1 runs, 3 assertions, 0 failures, 0 errors, 0 skips
```

### Actual behavior
```
$ ruby active_record_gem.rb 6.1.0
# ...
1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration
**Rails version**: 6.1.0

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

**MySQL version**: mysql  Ver 14.14 Distrib 5.7.32, for osx10.16 (x86_64) using  EditLine wrapper

### PR DESCRIPTION
**Pull request by intrip**
### Summary

f72f743 introduces `truncate(scale)` in the `Numericality` validator.
This behaviour conflicts with ActiveRecord decimal type conversion, which uses [round(scale)](https://github.com/rails/rails/blob/v6.1.1/activemodel/lib/active_model/type/decimal.rb#L62) instead.

Changes `Numericality` validator in order to use `round(scale)` for consistency.

### Other Information

Fixes #40902

### CODE REVIEW

**Comment by intrip** [comment]
@kamipo could you take a peek?

**OT:** I don't know if I should mention you or somebody else or nobody when a PR is ready for review sorry 😞

File: activerecord/test/cases/validations/numericality_validation_test.rb [hunk 1]
```diff
@@ -103,6 +103,16 @@ def test_virtual_attribute_with_scale
...
   end
 
+  def test_virtual_attribute_with_precision_and_scale
+    model_class.attribute(:virtual_decimal_number, :decimal, precision: 4, scale: 2)
+    model_class.validates_numericality_of(
+      :virtual_decimal_number, less_than_or_equal_to: 99.99
+    )
+
+    assert_predicate model_class.new(virtual_decimal_number: 99.994), :valid?
+    assert_not_predicate model_class.new(virtual_decimal_number: 99.999), :valid?
```
Comment (kamipo) [inline activerecord/test/cases/validations/numericality_validation_test.rb:113]:
```suggestion
    subject = model_class.new(virtual_decimal_number: 99.994)
    assert_equal 99.99, subject.virtual_decimal_number
    assert_predicate subject, :valid?

    subject = model_class.new(virtual_decimal_number: 99.999)
    assert_equal 100.00, subject.virtual_decimal_number
    assert_not_predicate subject, :valid?
```

File: activerecord/test/cases/validations_test.rb [hunk 2]
```diff
@@ -187,9 +187,9 @@ def self.model_name
       validates_numericality_of :wibble, greater_than_or_equal_to: BigDecimal("97.18")
     end
 
-    assert_not_predicate klass.new(wibble: "97.179"), :valid?
-    assert_not_predicate klass.new(wibble: 97.179), :valid?
-    assert_not_predicate klass.new(wibble: BigDecimal("97.179")), :valid?
```
Comment (kamipo) [inline activerecord/test/cases/validations_test.rb:192]: These `assert_not_predicate` were originally odd/incorrect since the typecasted value `97.18` is valid for `greater_than_or_equal_to: BigDecimal("97.18")`.

Can you expand these to test both rounding up and down like https://github.com/rails/rails/pull/41019#discussion_r556250434?

File: activemodel/lib/active_model/validations/numericality.rb [hunk 3]
```diff
@@ -71,6 +71,8 @@ def parse_as_number(raw_value, precision, scale, option = nil)
           raw_value if raw_value.is_a?(Range)
         elsif raw_value.is_a?(Float)
           parse_float(raw_value, precision, scale)
+        elsif raw_value.is_a?(BigDecimal)
```
Comment (intrip) [inline activemodel/lib/active_model/validations/numericality.rb:74]: when I was adding the missing test I've realized that we didn't round `BigDecimal` when scale was given, therefore I've added this.

**Comment by intrip** [comment]
@kamipo I've done the requested changes, could you take another peek?
