### PR TITLE
Make `==(other)` method of AttributeSet safe #49670

### LINKED ISSUE #49670: Unsafe implementation of `==(other)` method of AttributeSet
### Steps to reproduce

There is a problem with the implementation of method `==(other)` of AttributeSet.
See https://github.com/rails/rails/blob/e4e242685efc74e4bacccd5c5878bc671fd63fb7/activemodel/lib/active_model/attribute_set.rb#L106-L108

So if you try to use it like this: `attribute_set == null`, then you get an NoMethodException.

The steps for reproduction are clear:
1. Get an instance of `AttributeSet` or `LazyAttributeSet`.
2. Suppose you have and instance AttributeSet in the variable `my_attribute_set`. Invoke the code below
```ruby
my_attribute_set == nil
```

### Expected behavior
It should return false. And be safe for any other instances

### Actual behavior
NoMethodException is thrown

### System configuration
**Rails version**: Rails 7

**Ruby version**: 2.7.8

### PR DESCRIPTION
**Pull request by DmitryPogrebnoy**
The `==(other)` should be able to work with any instances without exception. To do so, we check if the other instance is an AttributeSet.

### Detail

This Pull Request changes Fixes #49670

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activemodel/test/cases/attribute_set_test.rb [hunk 1]
```diff
@@ -279,6 +279,16 @@ def builder.build_from_database(values = {}, additional_types = {})
...
 
+    test "==(other) is safe to use with any instance" do
+      attributes = AttributeSet.new({})
+
+      assert_equal false, attributes == nil
+      assert_equal false, attributes == BasicObject.new
+      assert_equal false, attributes == Object.new
+      assert_equal false, attributes == 1
+      assert_equal true, attributes == attributes
+    end
```
Comment (fatkodima) [inline activemodel/test/cases/attribute_set_test.rb]:
```suggestion
    test "comparison for equality is safe to use with any instance" do
      attributes = AttributeSet.new({})

      assert_equal false, attributes == nil
      assert_equal false, attributes == 1
      assert_equal true, attributes == attributes
    end
```

Comment (DmitryPogrebnoy) [reply activemodel/test/cases/attribute_set_test.rb]: Could you please explain why we don't need to check it with BasicObject?

File: activemodel/lib/active_model/attribute_set.rb [hunk 2]
```diff
@@ -104,6 +104,10 @@ def reverse_merge!(target_attributes)
     end
 
     def ==(other)
+      if (not defined?(other.class)) || (not self.is_a?(other.class))
+        return false
+      end
+
       attributes == other.attributes
```
[the remark this answers is not in the document]
Comment (DmitryPogrebnoy) [reply activemodel/lib/active_model/attribute_set.rb]: In case of `AttributeSet.new({})` = `LazyAttributeSet.new({}, {}, {}, {})` we will get NoMethodException, because `attributes` is a protected member of LazyAttributeSet.

File: activemodel/test/cases/attribute_set_test.rb (hunk 1 above)
Comment (DmitryPogrebnoy) [reply activemodel/test/cases/attribute_set_test.rb]: And the same question about LazyAttributeSet

File: activemodel/lib/active_model/attribute_set.rb (hunk 2 above)
[the remark this answers is not in the document]
Comment (fatkodima) [reply activemodel/lib/active_model/attribute_set.rb]: Yeah, this is unfortunate that `attributes` is a protected method. The changes in this method are too complex: 
`not defined?(other.class)` will always be false because `other.class` is always defined, so this check is not needed.
We need to only check subclasses of the caller, so need `other.is_a?(self.class)`.

So something like:
```ruby
def ==(other)
  other.is_a?(self.class) && 
    attributes == other.send(:attributes) # still that ugly `send`
end
```

File: activemodel/test/cases/attribute_set_test.rb (hunk 1 above)
Comment (fatkodima) [reply activemodel/test/cases/attribute_set_test.rb]: We do not need to test against every possible object, just `nil`, something else and the same object (or object of the same class) would be enough.

File: activemodel/lib/active_model/attribute_set.rb (hunk 2 above)
[the remark this answers is not in the document]
Comment (DmitryPogrebnoy) [reply activemodel/lib/active_model/attribute_set.rb]: Ok, fixed

File: activemodel/test/cases/attribute_set_test.rb (hunk 1 above)
Comment (DmitryPogrebnoy) [reply activemodel/test/cases/attribute_set_test.rb]: Fixed

File: activemodel/lib/active_model/attribute_set.rb (hunk 2 above)
[the remark this answers is not in the document]
Comment (kamipo) [reply activemodel/lib/active_model/attribute_set.rb]: Looks like this will change the behavior `lazy_attribute_set == attribute_set` even previously true but now false.

File: activemodel/lib/active_model/attribute_set.rb [hunk 3]
```diff
@@ -104,7 +104,7 @@ def reverse_merge!(target_attributes)
     end
 
     def ==(other)
-      attributes == other.attributes
+      other.is_a?(self.class) && attributes == other.send(:attributes)
```
Comment (MatheusRich) [inline activemodel/lib/active_model/attribute_set.rb:107]: Food for thought: do we want to make `attributes` public?

File: activemodel/lib/active_model/attribute_set.rb (hunk 2 above)
[the remark this answers is not in the document]
Comment (DmitryPogrebnoy) [reply activemodel/lib/active_model/attribute_set.rb]: Good point! Then `other.is_a?(AttributeSet.class) && attributes == other.send(:attributes)` will satisfy all requirements.

File: activemodel/lib/active_model/attribute_set.rb [hunk 4]
```diff
@@ -104,7 +104,7 @@ def reverse_merge!(target_attributes)
     end
 
     def ==(other)
-      attributes == other.attributes
+      other.is_a?(AttributeSet.class) && attributes == other.send(:attributes)
```
Comment (MatheusRich) [inline activemodel/lib/active_model/attribute_set.rb:107]: I'm sorry, I'm a bit confused. Should this really be `AttributeSet.class`?

Shouldn't it be
```suggestion
      other.is_a?(AttributeSet) && attributes == other.send(:attributes)
```
Or

```suggestion
      other.is_a?(self.class) && attributes == other.send(:attributes)
```

Not 100% sure this will work:

```suggestion
      other.is_a?(class) && attributes == other.send(:attributes)
```

Comment (MatheusRich) [reply activemodel/lib/active_model/attribute_set.rb:107]: Looking at the discussion I think we want
```suggestion
      (other.is_a?(AttributeSet) || other.is_a?(LazyAttributeSet)) && attributes == other.send(:attributes)
```

Comment (kamipo) [reply activemodel/lib/active_model/attribute_set.rb:107]: How about the following code? Actually {Lazy,}AttributeSet behaves a hash of attribute objects, like ActiveRecord::Relation behaves Array (Enumerable) like.

```suggestion
      if other.is_a?(Hash)
        attributes == other
      else
        other == attributes
      end
```

https://github.com/rails/rails/blob/00dfa109d6a5f4fb13d745f83d5cc779eba3b352/activerecord/lib/active_record/relation.rb#L797-L807

Comment (DmitryPogrebnoy) [reply activemodel/lib/active_model/attribute_set.rb]: My goal is to make `==(other)` safe without any change in behaviour.

So `other.is_a?(self.class) && attributes == other.send(:attributes)` won't work, because in this case `my_lazy_attribute_set == my_attribute_set` returns false. But in the original it returned true.

A similar way to ActiveRecord::Relation also introduces behavioural changes. So I'm not sure that such an implementation is the best fit here.

So I think `other.is_a?(AttributeSet) && attributes == other.send(:attributes)` would be the best option here. @MatheusRich thank you for the point about `.class`! I missed it indeed.
