### PR TITLE
Fix inconsistent nil handling in activerecord railtie

### LINKED ISSUE #44742: Inconsistent nil handling in ActiveRecord railtie.rb
See https://github.com/rails/rails/blob/main/activerecord/lib/active_record/railtie.rb#L146

```
filename = ActiveRecord::Tasks::DatabaseTasks.cache_dump_filename(
  db_config.name,
  schema_cache_path: db_config&.schema_cache_path
)
```

This should either raise an error if db_config is nil or navigate safely, not both. The second safe navigation does nothing.

**Rails version**: main branch

### PR DESCRIPTION
**Pull request by ghousemohamed**
### Summary

Fixes #44742

Safely navigate if the `db_config` is `nil` while initializing `active_record.check_schema_cache_dump`.

### CODE REVIEW

**Comment by eugeneius** [comment]
When will `db_config` be nil here?

**Comment by ghousemohamed** [comment]
> When will `db_config` be nil here?

The default `database.yml` only comes with `development`, `test`, `production` environment.
For custom environments like say `staging`, calling...

```ruby
ActiveRecord::Base.configurations.configs_for(env_name: Rails.env).first
```

...would result in `nil`. So this will result in an `undefined method name & schema_cache_path
for nil:NilClass` error for:

https://github.com/rails/rails/blob/89e3df569c6f6ed59c2ea2ac60a068f107314af1/activerecord/lib/active_record/railtie.rb#L146-L149

**Comment by SkipKayhil** [comment]
Just for context:
- it looks like the safe navigation was added here: c565cbe738302417f6d2d1c0cdde445da92f8396, with the intention of falling back to a nil value if a database configuration with `spec_name: "primary"` didn't exist (which would result is a default `schema_cache_path` being used)
- the `spec_name: "primary"` requirement was fixed here: e7b1e118b977e9d20b858336323c335fb68ad244 (allowing non `spec_name: "primary"` databases to configure their `schema_cache_path`

Based on these changes my thinking would be that it's not possible to have a nil `db_config` here without a misconfiguration

File: activerecord/lib/active_record/railtie.rb [hunk 1]
```diff
@@ -142,10 +142,11 @@ class Railtie < Rails::Railtie # :nodoc:
         config.after_initialize do |app|
           ActiveSupport.on_load(:active_record) do
             db_config = ActiveRecord::Base.configurations.configs_for(env_name: Rails.env).first
+            next if db_config.nil?
```
Comment (eileencodes) [inline activerecord/lib/active_record/railtie.rb:145]: Let's not handle `nil`, especially since we're always taking the first config. There's nothing to go to next anyway. So in this PR just change the line below to remove the safe navigation.

**Review by eileencodes — CHANGES_REQUESTED** [review]

File: activerecord/lib/active_record/railtie.rb (hunk 1 above)
Comment (ghousemohamed) [reply activerecord/lib/active_record/railtie.rb]: Done

**Review by eileencodes — APPROVED** [review]

**Comment by eileencodes** [comment]
Thank you!
