### PR TITLE
Warn if we can't read the yaml to create database tasks

### LINKED ISSUE #36540: 6.0.0rc1 Psych::BadAlias: Unknown alias: dummy_compiler in load_database_yaml
### Steps to reproduce

database yaml
```yaml
sqlite: &sqlite
  adapter: sqlite3
  database: db/test.sqlite3

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: lazybar_ci_test
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "sqlite" %>

test:
  <<: *defaults
```

$DB env variable is 'postgresql'

`RAILS_ENV=test bundle exec rails db:migrate`

### Expected behavior

Successful execution of database migrations

### Actual behavior

Following exception is raised:

```
rails aborted!
Psych::BadAlias: Unknown alias: dummy_compiler
/home/travis/build/klyonrad/lazybar/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/application/configuration.rb:207:in `load_database_yaml'
/home/travis/build/klyonrad/lazybar/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/tasks/database_tasks.rb:147:in `for_each'
/home/travis/build/klyonrad/lazybar/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/railties/databases.rake:26:in `block (2 levels) in <main>'
/home/travis/build/klyonrad/lazybar/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/railties/databases.rake:21:in `block in <main>'
/home/travis/build/klyonrad/lazybar/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/railties/databases.rake:5:in `<main>'
/home/travis/build/klyonrad/lazybar/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:69:in `load'

....

/lib/active_support/dependencies.rb:302:in `require'
bin/rails:4:in `<main>'
Caused by:
Bootsnap::LoadPathCache::FallbackScan: 

```

### System configuration
**Rails version**: 6.0.0.rc1

**Ruby version**: 2.6.3

## Additional Notes

I removed the inline ERB and then it went through.

### PR DESCRIPTION
**Pull request by eileencodes**
Load initial database.yml once, and warn if we can't create tasks

For multiple databases we attempt to generate the tasks by reading the
database.yml before the Rails application is booted. This means that we
need to strip out ERB since it could be reading Rails configs.

In some cases like https://github.com/rails/rails/issues/36540 the ERB
is too complex and we can't overwrite with the DummyCompilier we used in
https://github.com/rails/rails/pull/35497. For the complex causes we
simply issue a warning that says we couldn't infer the database tasks
from the database.yml.

While working on this I decided to update the code to only load the
database.yml once initially so that we avoid having to issue the same
warning multiple times. Note that this had no performance impact in my
testing and is merely for not having to save the error off somewhere.
Also this feels cleaner.

Note that this will not break running tasks that exist, it will just
mean that tasks for multi-db like `db:create:other_db` will not be
generated. If the database.yml is actually unreadable it will blow up
during normal rake task calls.

Fixes #36540 

cc/ @tenderlove @jhawthorn @rafaelfranca @klyonrad

### CODE REVIEW

**Comment by eileencodes** [comment]
Oh I'm missing a commit. One sec.

File: activerecord/lib/active_record/tasks/database_tasks.rb [hunk 1]
```diff
@@ -141,10 +141,18 @@ def create_all
...
 
-      def for_each
+      def setup_initial_database_yaml
         return {} unless defined?(Rails)
 
-        databases = Rails.application.config.load_database_yaml
+        begin
+          Rails.application.config.load_database_yaml
+        rescue
+          $stdout.puts "Rails couldn't infer whether you are using multiple databases from your database.yml. If you'd like to use this feature, please simplify your ERB."
```
Comment (eileencodes) [inline activerecord/lib/active_record/tasks/database_tasks.rb]: Not sure what to say really - maybe we don't warn at all?

**Comment by eileencodes** [comment]
Ok fixed the commit.

File: railties/test/application/rake/dbs_test.rb [hunk 2]
```diff
@@ -86,6 +86,25 @@ def db_create_and_drop(expected_database, environment_loaded: true)
...
       end
 
+      test "db:create and db:drop show warning but doesn't raise errors when loading YAML with alias ERB" do
+        app_file "config/database.yml", <<-YAML
+          sqlite: &sqlite
+            adapter: sqlite3
+            database: db/development.sqlite3
+
+          development:
+            <<: *sqlite
```
Comment (rafaelfranca) [inline railties/test/application/rake/dbs_test.rb]: Should not this be an ERB? This seems to be a yaml that we can read without problem.

Comment (eileencodes) [reply railties/test/application/rake/dbs_test.rb]: Oops yes, will fix that.

Comment (eileencodes) [reply railties/test/application/rake/dbs_test.rb]: Actually this is straight up a bad test 😢 Working on fixing it.

File: activerecord/lib/active_record/tasks/database_tasks.rb (hunk 1 above)
Comment (rafaelfranca) [inline activerecord/lib/active_record/tasks/database_tasks.rb]: `$stderr` maybe?

I think for the message we could do:

"Rails couldn't infer whether you are using multiple databases from your database.yml and can't generate the test for the non-primary databases. If you'd like to use this feature, please simplify your ERB."

File: activerecord/lib/active_record/railties/databases.rake [hunk 3]
```diff
@@ -2,6 +2,8 @@
 
 require "active_record"
 
+@databases = ActiveRecord::Tasks::DatabaseTasks.setup_initial_database_yaml
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/railties/databases.rake]: I think a local variable works, but I'm fine with an instance variable

**Review by rafaelfranca — APPROVED** [review]

File: activerecord/lib/active_record/tasks/database_tasks.rb (hunk 1 above)
Comment (eileencodes) [reply activerecord/lib/active_record/tasks/database_tasks.rb]: Done.

File: activerecord/lib/active_record/railties/databases.rake (hunk 3 above)
Comment (eileencodes) [reply activerecord/lib/active_record/railties/databases.rake]: Fixed.

**Comment by eileencodes** [comment]
Backported to 6-0-stable

**Comment by jasonperrone** [comment]
Is there a way to disable this message if you're not interested in multiple database functionality and you don't want it to try inspecting your database.yml file?

**Comment by eileencodes** [comment]
The only thing would be to change your YAML to something that Rails can read. The problem is with some more complex YAML we can't tell whether you want multi-db or not.

**Comment by jasonperrone** [comment]
So our database.yml is made complex with ERB because we're using it to support multiple databases already, but not in the way that this new feature is intended. For example, our app is deployed once, but depending on the URL connects to a different database. Just multi-tenancy. It appears to me that this new feature is more geared towards one instance using two databases, one for read only actions and then one for writing. Nice feature, but it's not quite what we're doing. The yaml in our files helps us quickly define entries based on "environment type" and other factors that allow us to enumerate over our 60 databases and configure them in groups. I'm probably not explaining right so the bottom line is I can't take the ERB out of this file and I'd just love the message to go away.

**Comment by eileencodes** [comment]
At the moment I don't have time to work on hiding this message but we'll accept a PR that does.

**Comment by OmriSama** [comment]
@jasonperrone I added this feature in https://github.com/rails/rails/pull/40449 :) enjoy!

**Comment by jasonperrone** [comment]
Awesome, thank you :)
