### PR TITLE
Ensure `reload` sets correct owner for each association (ActiveRecord::Persistence)

### LINKED ISSUE #46363: Loss of state after `reload`, transaction, and after_save_commit (regression in ActiveRecord 7.0, still there in 7.1)
During an upgrade of an existing application from Rails 6.1 to 7.0 I stumbled upon a fail in our specs. Initially I noticed the problem because it caused rspec's mock to lose its stub on the record. However, it's not specific to rspec and mocks: the code below shows an example where `record` loses the change made to its `name` inside of a second `after_save_commit` callback. This only happens under several pretty specific conditions including 
a) usage of `reload`, 
b) then a `transaction` 
c) with an update of a has_one/has_many `through` association.

I managed to find that this regression happens after the changes in this commit: https://github.com/rails/rails/commit/3328cd1d69129c7e3a14661d8a0f4b76009ec9b0
In particular this line causes the problem: https://github.com/rails/rails/blob/3328cd1d69129c7e3a14661d8a0f4b76009ec9b0/activerecord/lib/active_record/persistence.rb#L838

### Steps to reproduce

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "7.1.1"
  gem "sqlite3", "1.5.3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :articles, force: true
  create_table :reviews, force: true do |t|
    t.integer "desired_article_id"
    t.string "name"
  end
  create_table :article_reviews, force: true do |t|
    t.integer  "review_id"
    t.integer  "article_id"
  end
end

class Review < ActiveRecord::Base
  belongs_to :desired_article, class_name: "Article", inverse_of: :review
  has_many :article_reviews
  has_many :articles, through: :article_reviews

  after_initialize do
    self.desired_article = build_desired_article
  end

  after_save_commit :touch_name
  def touch_name
    self.name += ' (touched)'
  end
end

class Article < ActiveRecord::Base
  has_one :review, foreign_key: :desired_article_id, inverse_of: :desired_article
  has_many :article_reviews
end

class ArticleReview < ActiveRecord::Base
  belongs_to :article, required: true
  belongs_to :review, required: true
end

class BugTest < Minitest::Test
  def test_reload_transaction_association
    record = Review.create!(name: 'Some Review Name')
    assert_equal 'Some Review Name (touched)', record.name
    record.reload
    assert_equal 'Some Review Name', record.name
    record.transaction do
      record.articles = [record.build_desired_article]
      record.save!
    end
    assert_equal 'Some Review Name (touched)', record.name # <= this assertion fails
  end
end
```

### Expected behavior

Both assert_equal calls should pass (as they do with ActiveRecord 6.1.7). Below is the result of running the script if I replace `gem "activerecord", "7.1.1"` with `gem "activerecord", "6.1.7"`.

```ruby
D, [2022-10-29T23:13:45.401247 #45166] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2022-10-29T23:13:45.401383 #45166] DEBUG -- :   Article Create (0.1ms)  INSERT INTO "articles" DEFAULT VALUES
D, [2022-10-29T23:13:45.401816 #45166] DEBUG -- :   Review Create (0.0ms)  INSERT INTO "reviews" ("desired_article_id", "name") VALUES (?, ?)  [["desired_article_id", 1], ["name", "Some Review Name"]]
D, [2022-10-29T23:13:45.402067 #45166] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2022-10-29T23:13:45.402561 #45166] DEBUG -- :   Review Load (0.1ms)  SELECT "reviews".* FROM "reviews" WHERE "reviews"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
D, [2022-10-29T23:13:45.407101 #45166] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2022-10-29T23:13:45.409435 #45166] DEBUG -- :   Article Load (0.1ms)  SELECT "articles".* FROM "articles" INNER JOIN "article_reviews" ON "articles"."id" = "article_reviews"."article_id" WHERE "article_reviews"."review_id" = ?  [["review_id", 1]]
D, [2022-10-29T23:13:45.409797 #45166] DEBUG -- :   Article Create (0.0ms)  INSERT INTO "articles" DEFAULT VALUES
D, [2022-10-29T23:13:45.410226 #45166] DEBUG -- :   Review Update (0.0ms)  UPDATE "reviews" SET "desired_article_id" = ? WHERE "reviews"."id" = ?  [["desired_article_id", 2], ["id", 1]]
D, [2022-10-29T23:13:45.412718 #45166] DEBUG -- :   ArticleReview Create (0.0ms)  INSERT INTO "article_reviews" ("review_id", "article_id") VALUES (?, ?)  [["review_id", 1], ["article_id", 2]]
D, [2022-10-29T23:13:45.412999 #45166] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
.

Finished in 0.020931s, 47.7760 runs/s, 143.3281 assertions/s.

1 runs, 3 assertions, 0 failures, 0 errors, 0 skips
```

### Actual behavior

```ruby
D, [2023-10-12T22:37:11.821085 #25655] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2023-10-12T22:37:11.821245 #25655] DEBUG -- :   Article Create (0.2ms)  INSERT INTO "articles" DEFAULT VALUES RETURNING "id"
D, [2023-10-12T22:37:11.821749 #25655] DEBUG -- :   Review Create (0.1ms)  INSERT INTO "reviews" ("desired_article_id", "name") VALUES (?, ?) RETURNING "id"  [["desired_article_id", 1], ["name", "Some Review Name"]]
D, [2023-10-12T22:37:11.822004 #25655] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2023-10-12T22:37:11.822737 #25655] DEBUG -- :   Review Load (0.1ms)  SELECT "reviews".* FROM "reviews" WHERE "reviews"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
D, [2023-10-12T22:37:11.827921 #25655] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2023-10-12T22:37:11.830498 #25655] DEBUG -- :   Article Load (0.1ms)  SELECT "articles".* FROM "articles" INNER JOIN "article_reviews" ON "articles"."id" = "article_reviews"."article_id" WHERE "article_reviews"."review_id" = ?  [["review_id", 1]]
D, [2023-10-12T22:37:11.832118 #25655] DEBUG -- :   Article Create (0.1ms)  INSERT INTO "articles" DEFAULT VALUES RETURNING "id"
D, [2023-10-12T22:37:11.832871 #25655] DEBUG -- :   Review Update (0.1ms)  UPDATE "reviews" SET "desired_article_id" = ? WHERE "reviews"."id" = ?  [["desired_article_id", 2], ["id", 1]]
D, [2023-10-12T22:37:11.837117 #25655] DEBUG -- :   ArticleReview Create (0.1ms)  INSERT INTO "article_reviews" ("review_id", "article_id") VALUES (?, ?) RETURNING "id"  [["review_id", 1], ["article_id", 2]]
D, [2023-10-12T22:37:11.837565 #25655] DEBUG -- :   Review Update (0.0ms)  UPDATE "reviews" SET "desired_article_id" = ? WHERE "reviews"."id" = ?  [["desired_article_id", 2], ["id", 1]]
D, [2023-10-12T22:37:11.837741 #25655] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
F

Finished in 0.034130s, 29.2997 runs/s, 87.8992 assertions/s.

  1) Failure:
BugTest#test_reload_transaction_association [rails_bug.rb:63]:
Expected: "Some Review Name (touched)"
  Actual: "Some Review Name"

1 runs, 3 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration
**Rails version**: 7.1.1 (same with 7.0)

**Ruby version**: 3.0.2

### PR DESCRIPTION
**Pull request by dmytro-savochkin**
### Motivation / Background

Fixes #46363 which was caused by https://github.com/rails/rails/pull/41112

Currently calling `reload` re-calculates the association cache based on the object freshly loaded from the database. The fresh object gets assigned as `owner` for each association in the association cache. That object however is not the same as `self` (even though they both point to the same record). Under some specific circumstances (using `has_one/has_many through` associations and transactions with `after_commit` callbacks) this might lead to losing the effects of assignments done inside the callback.

This commit fixes it by making `reload` point to `self` as `owner` for each association in the association cache.

I think this is safe because as far as I can see in https://github.com/rails/rails/blob/main/activerecord/lib/active_record/associations.rb#L320 it always passes `self` when creating a new association.

### Detail

This Pull Request changes `ActiveRecord::Persistence#reload` method.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [x] CI is passing.

### CODE REVIEW

**Comment by dmytro-savochkin** [comment]
@eileencodes, may I ask you to review please (since you were adding association cache line before)? Thanks!

**Comment by dmytro-savochkin** [comment]
Hey @eileencodes! Sorry to ping again but is it possible for you to review this? :)

Or, alternatively, I would be quite happy if anyone else reviewed this.

File: activerecord/lib/active_record/persistence.rb [hunk 1]
```diff
@@ -971,6 +971,7 @@ def reload(options = nil)
       end
 
       @association_cache = fresh_object.instance_variable_get(:@association_cache)
+      @association_cache.each_value { |association| association.instance_variable_set(:@owner, self) }
```
Comment (nvasilevski) [inline activerecord/lib/active_record/persistence.rb:974]: I wonder what core team folks think on that but I always feel uncomfortable about using `instance_variable_set` unless we are patching some code we have no access to. Otherwise we are using something that wasn't supposed to be used even within the framework itself and makes me think whether we should add a public method to `association` to be able to set the `owner`. To be fair it might not be a solid argument as we already set and access instance variables on the lines above and below this one 🙃 

Other than that, the PR makes sense to me.

Comment (dmytro-savochkin) [reply activerecord/lib/active_record/persistence.rb:974]: Yes, this was exactly my thinking!

I am also not very comfortable using `instance_variable_get/instance_variable_set` but in this particular case I decided to go with it because:
1. This is already done one line above and below just as you said :)
2. I wasn't completely sure my approach would be accepted (dunno, maybe some other reasons I am not aware of) so doing some major change, like trying to introduce some new public method into `association` (which in turn might require changes to the docs, etc, etc) so that it can be used in this place, seemed a bit too premature to me.

Comment (dmytro-savochkin) [reply activerecord/lib/active_record/persistence.rb:974]: But if you think it's worth it, let me know, and I will try to introduce my change via a new public method. 
However the lines above and below will still be using `instance_variable_get`, so dunno... Changing those in this PR as well seems like a bit too much for such a small problem/PR.

**Comment by dmytro-savochkin** [comment]
Hey @nvasilevski!
Sorry for bothering but maybe you know who could be added to reviewers to this?
I understand sometimes it might take a few months here for a PR to be addressed but until I am completely sure it's the only option I'd like to try fasten things up a little :)

**Comment by skipkayhil** [comment]
Please don't ping individuals for review unless they have asked you to. The best way to get feedback would be asking in the [Discord](https://rubyonrails.org/2022/6/13/rails-discord-server-is-now-open-to-the-public)

**Comment by dmytro-savochkin** [comment]
> Please don't ping individuals for review unless they have asked you to. The best way to get feedback would be asking in the [Discord](https://rubyonrails.org/2022/6/13/rails-discord-server-is-now-open-to-the-public)

Oh, wow, there is also a Discord! Thanks, I will try that.
So far however I've followed [this guide for feedback](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#get-some-feedback) and on the only thing mentioned there (ror-core mailing list) there was no reply.

**Comment by dmytro-savochkin** [comment]
This PR is still relevant for Rails 7.1.1, the issue is still there.

File: activerecord/test/cases/persistence/reload_association_cache_test.rb [hunk 2]
```diff
@@ -0,0 +1,47 @@
+# frozen_string_literal: true
+
+require "cases/helper"
+
+# The test case below is aimed to fix a bug that was noticeable only with a very specific
+# setup of models. The models are fully defined inside the test case so that they are not
+# accidentally changed later causing the bug effects to disappear.
```
Comment (rafaelfranca) [inline activerecord/test/cases/persistence/reload_association_cache_test.rb:7]: Let's move this test to where it makes sense. You can define new models by creating new classes in the test/models folder, no need to do what is being done here.

Those models here still leaks to all the other files, so you aren't really isolating those models from other tests

File: activerecord/lib/active_record/persistence.rb (hunk 1 above)
Comment (rafaelfranca) [reply activerecord/lib/active_record/persistence.rb:1079]: Yeah, let's avoid those instance variable set here. If we need to set the owner outside of that object, we should expose a writter.

Comment (dmytro-savochkin) [reply activerecord/lib/active_record/persistence.rb]: No problem, updated.

File: activerecord/test/cases/persistence/reload_association_cache_test.rb (hunk 2 above)
Comment (dmytro-savochkin) [reply activerecord/test/cases/persistence/reload_association_cache_test.rb]: Yep, updated as well.
