### PR TITLE
Defaults content_type to application/octet-stream in blob_record.js

### LINKED ISSUE #38123: Active Storage direct upload to disk fails when faced with blank content type due to unknown file type (specifically with .xls files in Chrome).
### Steps to reproduce
Using chrome, attempt to direct upload a .xls file.

- `git clone https://github.com/weilandia/empty_mime_type_xls`
- `cd empty_mime_type_xls`
- `bundle; yarn; rails db:prepare;`
- `rails test:system`

### Expected behavior
The file should upload.

### Actual behavior
File does not upload and returns the following error:

```
Error:
UploadsXlsTest#test_upload_xls:
Mime::Type::InvalidMimeType: "" is not a valid MIME type
```
### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.5

Related: https://github.com/rails/rails/issues/36514

### PR DESCRIPTION
**Pull request by weilandia**
### Summary

Defaults content_type to application/octet-stream in blob_record.js in order to resolve https://github.com/rails/rails/issues/38123.

@cushingw recommended this solution here https://github.com/rails/rails/issues/36514#issuecomment-503221829.

Closes https://github.com/rails/rails/issues/38123

### CODE REVIEW

**Comment by weilandia** [comment]
Another solution could be to be more explicit and only change the content-type when the filename has .xls

**Review by marceloperini — APPROVED** [review]

File: activestorage/app/javascript/activestorage/blob_record.js [hunk 1]
```diff
@@ -3,10 +3,11 @@ import { getMetaValue } from "./helpers"
 export class BlobRecord {
   constructor(file, checksum, url) {
     this.file = file
+    const content_type = file.type.length ? file.type : "application/octet-stream"
 
     this.attributes = {
       filename: file.name,
-      content_type: file.type,
+      content_type: content_type,
```
Comment (javan) [inline activestorage/app/javascript/activestorage/blob_record.js]: I *think* we'd be better off not sending a `content_type` at all when `file.type` is blank and letting Active Storage extract one for us: 
https://github.com/rails/rails/blob/be40e8e5afc6bcf6092392741eec7dcd02edd14a/activestorage/app/models/active_storage/blob.rb#L208
Mind giving that a try?

Comment (weilandia) [reply activestorage/app/javascript/activestorage/blob_record.js]: The problem is the Content-Type we get back in the response from the the direct_uploads controller, which is then sent to `/rails/active_storage/disk`.

I tried the following (separately):

```
# blob_record.js:7
this.attributes = {
    filename: file.name,
    byte_size: file.size,
    checksum: checksum
  }

if (file.type) {
  this.attributes.content_type = file.type;
}

# resulted in Mime::Type::InvalidMimeType: "null" is not a valid MIME type
```

```
# blob_upload.js:11

for (const key in headers) {
  this.xhr.setRequestHeader(key, headers[key] || null)
}

# resulted in Mime::Type::InvalidMimeType: "null" is not a valid MIME type
```

```
# blob_upload.js:11

for (const key in headers) {
  if (!headers[key) continue;
  this.xhr.setRequestHeader(key, headers[key])
}

# sends Content-Type over as html and results in 422
```

@javan

Comment (javan) [inline activestorage/app/javascript/activestorage/blob_record.js]: Let's shorten and inline the default: `content_type: file.type || "application/octet-stream",`

**Review by javan — APPROVED** [review]

**Comment by javan** [comment]
Thanks!

**Comment by weilandia** [comment]
@javan I noticed https://contributors.rubyonrails.org wrongly credited this commit to the branch name because it was in square brackets in the commit.  Very much not important, but wondering if there's a way to manually overwrite?  Thanks

**Comment by javan** [comment]
Wups! Opened https://github.com/rails/rails-contributors/pull/146 to fix that up.

**Comment by javan** [comment]
All better now: https://contributors.rubyonrails.org/contributors/nick-weiland/commits

**Comment by weilandia** [comment]
Thanks @javan!

**Comment by carlaraya** [comment]
It seems like the npm package (https://www.npmjs.com/package/@rails/activestorage) hasn't reflected the changes in this commit yet. The PR conversation is most likely not the right place to ask, but how can I implement this commit without waiting for the npm package to update?

**Comment by smartygus** [comment]
> It seems like the npm package (https://www.npmjs.com/package/@rails/activestorage) hasn't reflected the changes in this commit yet. The PR conversation is most likely not the right place to ask, but how can I implement this commit without waiting for the npm package to update?

@carlaraya I basically forked the Rails repo from the 6.0.2.1 release, cherry-picked the commit that made this fix, then extracted the `activestorage` subdirectory into [another git repo](https://github.com/smartygus/activestorage) to create a patched activestorage repo, which I could then use directly with yarn, because it supports adding from a git repo, but unfortunately not if the package is in a subdirectory of a repo (see [here](https://github.com/yarnpkg/yarn/issues/4725)).

So in my case, adding the patched package with yarn became: `yarn add https://github.com/smartygus/activestorage`

**Comment by javan** [comment]
I just backported this in https://github.com/rails/rails/commit/2c19a6e12c241e6ac289343e248bb01a11018226 so it'll go out in the next release.

**Comment by maurobender** [comment]
Great! Thank you so much!! I was just facing this issue after updating to rails 6.

When is the next update including this fix for the [npm package](https://www.npmjs.com/package/activestorage) planned to happen? The las update was 5 months ago.

**Comment by smartygus** [comment]
@maurobender the package you linked to is no longer used for Rails 6 (for Rails 5 only it seems). You can find the updated package here: https://www.npmjs.com/package/@rails/activestorage

**Comment by maurobender** [comment]
> @maurobender the package you linked to is no longer used for Rails 6 (for Rails 5 only it seems). You can find the updated package here: https://www.npmjs.com/package/@rails/activestorage

Thanks a lot @smartygus! Any chance of adding this to the guides (maybe [here](https://edgeguides.rubyonrails.org/active_storage_overview.html#direct-uploads))?

**Comment by smartygus** [comment]
> Any chance of adding this to the guides (maybe [here](https://edgeguides.rubyonrails.org/active_storage_overview.html#direct-uploads))?

@maurobender do you mean something to explain that the npm packages have moved? This is mentioned in the guide for upgrading from Rails 5.2 to Rails 6, and I think that's probably the most appropriate place to document such changes: https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#all-npm-packages-have-been-moved-to-the-@rails-scope
As far as I can tell, all mentions of the ActiveStorage npm package in the guides have also been updated to use the @rails/activestorage scoped package name, so I think the guides seem okay in terms of pointing people to the correct package.

Or did you have something else in mind?

File: activestorage/app/assets/javascripts/activestorage.js [hunk 2]
```diff
@@ -550,7 +550,7 @@
       this.file = file;
       this.attributes = {
         filename: file.name,
-        content_type: file.type,
+        content_type: file.type || "application/octet-stream",
```
Comment (betesh) [inline activestorage/app/assets/javascripts/activestorage.js:553]: Does it makes sense to set `null: false` for content_type in the migration, since it should never be NULL and causes errors if it is NULL?

Comment (ghiculescu) [reply activestorage/app/assets/javascripts/activestorage.js:553]: That sounds like a good idea. Would you like to make a PR?

Comment (betesh) [reply activestorage/app/assets/javascripts/activestorage.js:553]: Done: #43055
