### PR TITLE
Compare deserialized values for `PostgreSQL::OID::Hstore` types

### LINKED ISSUE #27502: Regression in PostgreSQL HStore dirty check when key order changes
### Steps to reproduce

This passes on Rails 4.2.7.1 but fails on Rails 5.0.1:

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.0.1"       # Fails
  #gem "activerecord", "4.2.7.1"    # Passes
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# PostgreSQL Specific Issue
ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: 'hstore_dirty')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  enable_extension 'hstore' unless extension_enabled?('hstore')
  create_table :posts, force: true do |t|
    t.hstore 'settings'
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def setup
    @settings = { "alongkey" => "anything", "key" => "value" }
    @post = Post.create!(settings: @settings)
  end

  def test_hstore_dirty_from_user_no_change
    # @post.settings is: {"alongkey"=>"anything", "key"=>"value"}
    assert_equal @settings, @post.settings
    @post.settings = @settings
    refute @post.changed?
  end

  def test_hstore_dirty_from_user_no_equality_change
    # @post.settings is: {"alongkey"=>"anything", "key"=>"value"}
    assert_equal @settings, @post.settings
    @post.settings = { "key" => "value", "alongkey" => "anything" }
    assert_equal @settings, @post.settings
    refute @post.changed?
  end

  def test_hstore_dirty_from_database
    @post.reload
    # The value of @post.settings is dependent on how the database decides to
    # return the HStore. For my system on PostgreSQL 9.5.4 it seems to place
    # shorter keys before longer ones.
    #
    # At this point @post.settings is: {"key"=>"value", "alongkey"=>"anything"}
    assert_equal @settings, @post.settings
    @post.settings = @settings
    refute @post.changed?
  end
end
```

### Expected behavior

The record has no changes and should not be saved or marked as dirty.

### Actual behavior

The record thinks the HStore has changed. This is causing it to be saved resulting in a cascade of effects which should be avoided (e.g. updates the `updated_at` timestamp, causing `touch` association updates, busting caches and ETags).

### System configuration

**Rails version**: 5.0.1

**Ruby version**: 2.3.3

**PostgreSQL version**: 9.5.4

### PR DESCRIPTION
**Pull request by maclover7**
### Summary

Per the regression commit below, the commit changes the behavior of
`#changed?`to consult the `#changed_in_place?` method on `Type::Value` classes.
Per this change, `PostgreSQL::OID::Hstore` needs to override this method
in order to compare the deserialized forms of the two arguments. In
Ruby, two hashes are considered equal even if their key order is
different. This commit helps to bring that behavior to `Hstore` values.

### Other Information

- Fixes regression introduced by 8e633e505880755e7e366ccec2210bbe2b5436e7
- Fixes #27502

### CODE REVIEW

File: activerecord/test/cases/adapters/postgresql/hstore_test.rb [hunk 1]
```diff
@@ -171,6 +171,28 @@ def test_changes_in_place
...
+      assert_equal settings, hstore.settings
+      refute hstore.changed?
+    end
+
+    def test_hstore_dirty_from_database_equal
+      settings = { "alongkey" => "anything", "key" => "value" }
+      hstore = Hstore.create!(settings: settings)
+      hstore.reload
+
+      assert_equal "\"key\"=>\"value\", \"alongkey\"=>\"anything\"",
```
Comment (sgrif) [inline activerecord/test/cases/adapters/postgresql/hstore_test.rb]: I'd prefer not to test database details. The assertions below this are enough.

**Review by sgrif — CHANGES_REQUESTED** [review]
One nitpick. Needs CHANGELOG entry as well

**Comment by maclover7** [comment]
@sgrif updated

FYI build is green but I had to rebase (again) to fix a merge conflict in `CHANGELOG.md` --> https://travis-ci.org/rails/rails/builds/188650236

**Comment by maclover7** [comment]
Opened #27557 to backport this PR to `5-0-stable`.

**Comment by rafaelfranca** [comment]
Backported in 45b1de6890
