### PR TITLE
Fix request.reset_session for API controllers

### LINKED ISSUE #24222: Reference to request.flash left in request.rb
### Steps to reproduce

Call reset_session on api only project.

https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/request.rb#L340

https://github.com/rails/rails/commit/add46482a540b33184f3011c5c307f4b8e90c9cc#diff-3179d24efacadd64068c4d9c1184eac3

### Expected behavior
Should reset session

### Actual behavior
Throws exception NoMethodError (undefined method `flash=' for #<ActionDispatch::Request:0x0056141a714b78>):

### System configuration
**Rails version**: 5.0.0.beta3

**Ruby version**: 2.3.0

### PR DESCRIPTION
**Pull request by maclover7**
Due to that `ActionDispatch::Flash` (the flash API's middleware) is not
included for API controllers, the `request.reset_session` method, which
relies on there being a `flash=` method which is in fact defined by the
middleware, was previously breaking. Similarly to how
add46482a540b33184f3011c5c307f4b8e90c9cc created a method to be
overriden by the flash middleware in order to ensure non-breakage, this
is how flashes are now reset.

Fixes #24222

### CODE REVIEW

File: actionpack/lib/action_dispatch/http/request.rb [hunk 1]
```diff
@@ -403,6 +403,9 @@ def logger
     def commit_flash
     end
 
+    def reset_flash
```
Comment (sikachu) [inline actionpack/lib/action_dispatch/http/request.rb]: Should this and `#commit_flash` above be `:nodoc:` too?

File: actionpack/lib/action_dispatch/http/request.rb [hunk 2]
```diff
@@ -337,7 +337,7 @@ def reset_session
       else
         self.session = {}
       end
-      self.flash = nil
+      reset_flash
```
Comment (kaspth) [inline actionpack/lib/action_dispatch/http/request.rb]: Shouldn't the flash middleware just override `reset_session`, call super and reset the flash?

File: actionpack/lib/action_dispatch/middleware/flash.rb [hunk 3]
```diff
@@ -70,6 +70,10 @@ def commit_flash # :nodoc:
           session.delete('flash')
         end
       end
+
+      def reset_flash # :nodoc:
+        set_header(Flash::KEY, nil)
```
Comment (kaspth) [inline actionpack/lib/action_dispatch/middleware/flash.rb]: Shouldn't we use the exposed API instead of writing new code?

File: railties/test/application/middleware/flash_test.rb [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+      RUBY
+
+      app('development')
+
+      get('/dump_flash')
+
+      assert_equal(200, last_response.status)
+      assert_equal('It worked!', last_response.body)
+
+      refute(middleware.include?('ActionDispatch::Flash'))
```
Comment (kaspth) [inline railties/test/application/middleware/flash_test.rb]: Prefer `assert_not`. I'd also remove the parens around the assertion calls (and `Rack::Test` calls).

File: railties/test/application/middleware/flash_test.rb [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+    end
+
+    private
+      def middleware
+        Rails.application.middleware.map(&:klass).map(&:name)
```
Comment (kaspth) [inline railties/test/application/middleware/flash_test.rb]: Why map to class name? Won't `middleware.include?(ActionDispatch::Flash)` work?

File: railties/test/application/middleware/flash_test.rb (hunk 4 above)
Comment (kaspth) [inline railties/test/application/middleware/flash_test.rb]: Also do we really want to assert on the internal middleware stack? Seems iffy.

**Comment by maclover7** [comment]
Update per comments. I wanted to assert that `ActionDispatch::Flash` is not in the middleware stack, to show that part of the bug is precisely that this middleware isn't in the `ActionDispatch::MiddlewareStack` for API applications.

File: railties/test/application/middleware/flash_test.rb [hunk 6]
```diff
@@ -0,0 +1,46 @@
...
+
+      get '/dump_flash'
+
+      assert_equal 200, last_response.status
+      assert_equal 'It worked!', last_response.body
+
+      refute Rails.application.middleware.include?(ActionDispatch::Flash)
+    end
+  end
+end
```
Comment (kaspth) [inline railties/test/application/middleware/flash_test.rb]: This test still feels misplaced to me. It's placed in `middleware/flash_test.rb` but its whole point is that the flash middleware isn't there 🤔

This is really testing calling `reset_session` in API only apps works. So aren't there some API app tests we can put this with?

Comment (maclover7) [inline railties/test/application/middleware/flash_test.rb]: From what I've been able to see inside `railties/test`, there's no centralized API-specific testing stuff...

**Comment by maclover7** [comment]
:+1:
