### PR TITLE
Disable automatic write protection on replicas

### LINKED ISSUE #42432: Blank query can't be executed on a readonly database connection
Trying to execute a blank SQL query on a readonly (role: :reading) database connection always fails with this error:

```
ActiveRecord::ReadOnlyError: Write query attempted while in readonly mode
```

### Steps to reproduce

```
ActiveRecord::Base.connected_to(role: :reading) { ActiveRecord::Base.connection.execute('').count }
ActiveRecord::ReadOnlyError: Write query attempted while in readonly mode:
```

or if you deep dive into why Rails thinks the query can't run on a readonly database:

```
Class.new.extend(ActiveRecord::ConnectionAdapters::PostgreSQL::DatabaseStatements).write_query?('')
=> true
```

### Expected behaviour

The query should be allowed to execute on a readonly connection.
It would return an empty result like when it runs on a read/write connection:

```
ActiveRecord::Base.connection.execute('').count
=> 0
```

### Actual behaviour

```
ActiveRecord::Base.connected_to(role: :reading) { ActiveRecord::Base.connection.execute('').count }
ActiveRecord::ReadOnlyError: Write query attempted while in readonly mode:
```

### System configuration

**Rails version**: Rails 6.1.3.2
**Ruby version**: ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin20

### PR DESCRIPTION
**Pull request by HParker**
This allows users to use write protection if they want, but no longer treats it as a catch all. Write protection is not accurate enough to classify all cases correctly. Instead users should configure their replicas to not allow writes and rely on the database erroring if the query is not allowed.

Alternative solution for: https://github.com/rails/rails/issues/42432
Fixes: https://github.com/rails/rails/issues/42432

### CODE REVIEW

**Comment by ghiculescu** [comment]
I am in favor of this. Is there any other reason for rails to know if the db is a replica? If not, I imagine you can remove a fair bit more code.

**Comment by eileencodes** [comment]
> Is there any other reason for rails to know if the db is a replica? If not, I imagine you can remove a fair bit more code.

Yes, we need to know a configuration is a replica so that we don't run rake tasks against it. I don't think offhand there is any other code to remove since we're not dropping replica support, just dropping the automatic prevent_writes from it. 

`prevent_writes` was designed for the case where you're sending read queries to your primary and want to make sure they behave similarly to a replica. For example if you're using the auto switcher middleware you dont want your GET requests to have any writes in them (without switching to writing) because when it goes to the replica it won't write. To make GET's going to the primary and replica behave the same, we added this functionality.

**Comment by eileencodes** [comment]
> Is there any other reason for rails to know if the db is a replica? If not, I imagine you can remove a fair bit more code.

Yes, we need to know a configuration is a replica so that we don't run rake tasks against it. I don't think offhand there is any other code to remove since we're not dropping replica support, just dropping the automatic prevent_writes from it. 

`prevent_writes` was designed for the case where you're sending read queries to your primary and want to make sure they behave similarly to a replica. For example if you're using the auto switcher middleware you dont want your GET requests to have any writes in them (without switching to writing) because when it goes to the replica it won't write. To make GET's going to the primary and replica behave the same, we added this functionality.

File: activerecord/test/cases/base_test.rb [hunk 1]
```diff
@@ -1779,22 +1778,12 @@ def test_protected_environments_are_stored_as_an_array_of_string
 
   test "#connected_to_many sets prevent_writes if role is reading" do
     ActiveRecord::Base.connected_to_many([SecondAbstractClass], role: :reading) do
-      assert SecondAbstractClass.current_preventing_writes
```
Comment (eileencodes) [inline activerecord/test/cases/base_test.rb:1782]: Instead of deleting these we should update the assertions.

**Review by eileencodes — CHANGES_REQUESTED** [review]
Thanks Adam! This also needs a changelog entry.

File: activerecord/test/cases/base_test.rb (hunk 1 above)
Comment (HParker) [reply activerecord/test/cases/base_test.rb:1782]: Thanks @eileencodes! updated

File: activerecord/CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,11 @@
+*   Disable automatic write protection on replicas
+
+    Write protection no longer automatically enable for replicas.
+    Now each application controls when to enable automatic write protection.
```
Comment (ghiculescu) [inline activerecord/CHANGELOG.md:4]: Do you think it's worth mentioning this on https://edgeguides.rubyonrails.org/active_record_multiple_databases.html too?

Comment (HParker) [reply activerecord/CHANGELOG.md:4]: I am reading now, if it was mentioned before we should probably remove it, but I don't know how/if we should mention rails not doing something you maybe didn't know it did at all before.

Comment (ghiculescu) [reply activerecord/CHANGELOG.md:4]: I had a quick read through and couldn't find any mention of this behaviour. I think `AR.while_preventing_writes` could be mentioned but it's not really in the scope of this PR.

Comment (HParker) [reply activerecord/CHANGELOG.md:4]: I can't find a spot that seems like it needs updating, but it is totally possible I am missing it. Let me know if I missed anything @ghiculescu 🙂

Comment (eileencodes) [reply activerecord/CHANGELOG.md:4]: I would add onto the guides and explain that if you want replicas to act like replicas they need to be configured with readonly users

Comment (ghiculescu) [reply activerecord/CHANGELOG.md:4]: ^ that is alluded to, kind of

image

@HParker I'll make a separate PR, because I don't think I'm making much sense here.

Comment (HParker) [reply activerecord/CHANGELOG.md:4]: Under the setup section we have:

> Second, the username for the writers and replicas should be different, and the replica user's permissions should be set to only read and not write.
> 
> When using a replica database, you need to add a replica: true entry to the replica in the database.yml. This is because Rails otherwise has no way of knowing which one is a replica and which one is the writer.

https://edgeguides.rubyonrails.org/active_record_multiple_databases.html#setting-up-your-application

In the guide already. Should I expand on that?

**Comment by ghiculescu** [comment]
Just noticed this line: https://github.com/rails/rails/blob/eca7582718225ef40a7618293a13924561194aae/activerecord/lib/active_record/connection_handling.rb#L355. Should it also be removed?  It gets called by `connected_to`; the equivalent line in `connected_to_many` has been removed.

**Comment by HParker** [comment]
Thanks @ghiculescu that line in connection_handling turned up a lot of places I missed ❤️

File: activerecord/test/cases/base_test.rb [hunk 3]
```diff
@@ -1721,7 +1721,6 @@ def test_protected_environments_are_stored_as_an_array_of_string
     SecondAbstractClass.connecting_to(role: :reading)
 
     assert SecondAbstractClass.connected_to?(role: :reading)
```
Comment (ghiculescu) [inline activerecord/test/cases/base_test.rb:1723]:
```suggestion
    assert SecondAbstractClass.connected_to?(role: :reading)
    assert_not SecondAbstractClass.current_preventing_writes
```

File: activerecord/test/cases/connection_adapters/legacy_connection_handlers_multi_db_test.rb [hunk 4]
```diff
@@ -146,7 +146,7 @@ def test_switching_connections_via_handler
             assert_equal :reading, ActiveRecord::Base.current_role
             assert ActiveRecord::Base.connected_to?(role: :reading)
             assert_not ActiveRecord::Base.connected_to?(role: :writing)
-            assert_predicate ActiveRecord::Base.connection, :preventing_writes?
+            # assert_not_predicate ActiveRecord::Base.connection, :preventing_writes?
```
Comment (ghiculescu) [inline activerecord/test/cases/connection_adapters/legacy_connection_handlers_multi_db_test.rb:149]: why is this commented?

Comment (HParker) [reply activerecord/test/cases/connection_adapters/legacy_connection_handlers_multi_db_test.rb]: 🤦 Thanks for catching that!

File: activerecord/CHANGELOG.md [hunk 5]
```diff
@@ -1,3 +1,10 @@
+*   Disable automatic write protection on replicas
```
Comment (eileencodes) [inline activerecord/CHANGELOG.md:1]:
```suggestion
*   Disable automatic write protection on replicas.
```

File: activerecord/CHANGELOG.md [hunk 6]
```diff
@@ -1,3 +1,10 @@
...
+
+    Write protection no longer automatically enable for replicas.
```
Comment (eileencodes) [inline activerecord/CHANGELOG.md:3]:
```suggestion
    Write protection is no longer automatically enabled for replicas. Write protection should be enabled by the database user settings.
```

File: activerecord/CHANGELOG.md [hunk 7]
```diff
@@ -1,3 +1,10 @@
...
+    Now each application controls when to enable automatic write protection.
```
Comment (eileencodes) [inline activerecord/CHANGELOG.md:4]:
```suggestion
```

**Review by eileencodes — CHANGES_REQUESTED** [review]
I think the CHANGELOG can be clearer - but once that's fixed and the conflicts are resolved this looks good to me 👍🏼

**Comment by HParker** [comment]
Thanks @eileencodes! updated

File: activerecord/CHANGELOG.md [hunk 8]
```diff
@@ -1,3 +1,9 @@
+*   Disable automatic write protection on replicas.
+
+    Write protection is no longer automatically enabled for replicas. Write protection should be enabled by the database user settings.
```
Comment (rafaelfranca) [inline activerecord/CHANGELOG.md:3]: Can we expand with an example what "Write protection should be enabled by the database user settings." means?

Comment (HParker) [reply activerecord/CHANGELOG.md:3]: Good idea @rafaelfranca, I put together https://github.com/rails/rails/pull/42529

I am not sure how much detail to add since it is not only database specific, but also configuration specific. Depending on how your primary and replica are setup you might want a totally different configuration. Ideally you would setup a local database user to be very similar to how your production users are setup.
