### PR TITLE
Make `restart` and `dev:cache` tasks work when customizing pid file path

### LINKED ISSUE #29306: rails dev:cache failed to restart the Rails server with custom pid file path
### Steps to reproduce
1. Start rails server with a custom pid file: `rails s -P tmp/pids/dev.pid`.
2. Toggle dev cache: `rails dev:cache`.

### Expected behavior
Rails server should be restarted successfully.

### Actual behavior
Restarting failed. Log:
```
=> Booting Puma
=> Rails 5.1.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.3.3-p222), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
* Restarting...
=> Booting Puma
=> Rails 5.1.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
A server is already running. Check /tmp/rails-test/tmp/pids/dev.pid.
Exiting
```

### System configuration
**Rails version**: Rails 5.1.1

**Ruby version**: Ruby 2.3.3

### Potential Reason
1. The pid file path is hard coded in [dev_caching.rb](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/railties/lib/rails/dev_caching.rb#L20) as `"tmp/pids/server.pid"`
2. When restarting rails with Puma, it won't remove the pid file it generated.

### PR DESCRIPTION
**Pull request by y-yagi**
Originally, it hard-coded pid file path. It can not be removed when customizing pid file path.
But rake task can not get pid file path. Therefore, do not remove file in rake task, only file that tell them that restart is in progress are created, and pid file remove in server command.

Fixes #29306

### CODE REVIEW

File: railties/lib/rails/commands/server/server_command.rb [hunk 1]
```diff
@@ -232,6 +241,13 @@ def pid
         def self.banner(*)
           "rails server [puma, thin etc] [options]"
         end
+
+        def prepare_restart
+          return unless File.exist?("tmp/run_restart.txt")
+
+          FileUtils.rm_f(server_options[:pid])
+          FileUtils.rm_f("tmp/run_restart.txt")
```
Comment (georgeclaghorn) [inline railties/lib/rails/commands/server/server_command.rb]: Forgive me if I’m missing something, but I don’t follow why this is necessary. Doesn’t Puma’s `tmp_restart` plugin handle restarts independently? The `rails` command isn’t executed on restart, right?

**Comment by georgeclaghorn** [comment]
There’s a [test failure](https://travis-ci.org/rails/rails/jobs/266405448#L1226) that seems relevant.

File: railties/lib/rails/commands/server/server_command.rb (hunk 1 above)
Comment (georgeclaghorn) [inline railties/lib/rails/commands/server/server_command.rb]: Never mind. We pass a `restart_cmd` to Puma, so the `rails server` *is* executed on restart.

File: railties/lib/rails/commands/server/server_command.rb [hunk 2]
```diff
@@ -127,6 +127,14 @@ class ServerCommand < Base # :nodoc:
       class_option "dev-caching", aliases: "-C", type: :boolean, default: nil,
         desc: "Specifies whether to perform caching in development."
 
+      class << self
+        def restart_server
+          FileUtils.mkdir_p("tmp")
+          FileUtils.touch("tmp/run_restart.txt")
```
Comment (georgeclaghorn) [inline railties/lib/rails/commands/server/server_command.rb]: It’d be clearer to include a flag that indicates a restart in the `restart_cmd`, then use that flag to determine whether to remove the PID file. Then we can keep `FileUtils.touch "tmp/restart.txt"` in `Rails::DevCaching.enable_by_file`.

**Review by georgeclaghorn — CHANGES_REQUESTED** [review]

File: railties/lib/rails/commands/server/server_command.rb (hunk 2 above)
Comment (y-yagi) [inline railties/lib/rails/commands/server/server_command.rb]: Seems fine. I added the `--restart` option and updated it to use it.

**Comment by y-yagi** [comment]
I think the fail test probably relates to the following. 
https://github.com/puma/puma/pull/1206 
https://github.com/puma/puma/pull/1345 
But it does not reproduce locally...

**Comment by y-yagi** [comment]
Hmm, the test passed...

**Review by georgeclaghorn — APPROVED** [review]
