### PR TITLE
Better error message for calling columns_hash

### LINKED ISSUE #36274: columns_hash on abstract ActiveRecord model raises obscure error
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.0.rc1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

class Comment < ActiveRecord::Base
  self.abstract_class = true
end

class BugTest < Minitest::Test
  def test_association_stuff
    Comment.columns_hash
  end
end
```

### Expected behavior

Say something about how columns_hash is unavailable on abstract models

### Actual behavior
It raises `ActiveRecord::StatementInvalid: Could not find table ''`

### System configuration
**Rails version**: 6.0.0.rc1

**Ruby version**: 2.62

### PR DESCRIPTION
**Pull request by itsWill**
### Summary

When a record does not have a table name, as in the case for a record
with `self.abstract_class = true` and no `self.table_name` set the error
message raises a cryptic:
"ActiveRecord::StatementInvalid: Could not find table ''" this patch now
raises a new error "columns_hash not available for a record with no
table".

Fixes: #36274

### Other Information

This particular issue is not related exclusively to using `abstract_class` this is more to do with a given record not having a table_name. This is usually the case with `abstract_class` however one can also have an `abstract_class` and set the `self.table_name="something"` .  This the leads to the `columns_hash` existing. 

The use case for this is someone wanting to share the table name in the abstract classes child classes, so it's defined on the abstract class.

cc: @gmcgibbon

### CODE REVIEW

File: activerecord/lib/active_record/model_schema.rb [hunk 1]
```diff
@@ -349,6 +349,9 @@ def attributes_builder # :nodoc:
       end
 
       def columns_hash # :nodoc:
+        unless table_exists?
+          raise ActiveRecord::ActiveRecordError, "columns_hash is not available for a record with no table"
```
Comment (st0012) [inline activerecord/lib/active_record/model_schema.rb]: `for a record with no table` sounds weird, because this is not a record's method and a record surely doesn't own any table. Shouldn't it be `for a model with no table`?

**Review by st0012 — CHANGES_REQUESTED** [review]

File: activerecord/lib/active_record/model_schema.rb (hunk 1 above)
Comment (itsWill) [reply activerecord/lib/active_record/model_schema.rb]: You know what, in my mind I used record to differentiate a persisted model from a non persisted model, which I just call model.

But seeing in the Rails docs that this is not a distinction that is made and that model tends to refer to an active record model, so I think your suggestion is more appropriate here and consistent, nice catch, thank you.

File: activerecord/test/cases/base_test.rb [hunk 2]
```diff
@@ -1412,6 +1412,12 @@ def test_default_values_are_deeply_dupped
     assert_not_includes SymbolIgnoredDeveloper.columns_hash.keys, "first_name"
   end
 
+  test "#columns_hash raises an error if the record has an empty table name" do
+    assert_raises(ActiveRecord::ActiveRecordError) do
+      FirstAbstractClass.columns_hash
```
Comment (st0012) [inline activerecord/test/cases/base_test.rb]: Can you also verify the error message? `ActiveRecordError` is the superclass for many other errors. So it'd safer to make sure we're getting the right error.

**Review by gmcgibbon — COMMENTED** [review]
I think we should add `NoTableError` (like `NoDatabaseError`) and raise it in [`load_schema!`](https://github.com/rails/rails/blob/3d70e9609760cb3046cf219cd49f3e9a838a0291/activerecord/lib/active_record/model_schema.rb#L486). That way we aren't checking if the table name is there too often (only on initial load and reload), and we have a more descriptive error class.

File: activerecord/lib/active_record/connection_adapters/schema_cache.rb [hunk 3]
```diff
@@ -79,9 +79,14 @@ def columns(table_name)
       # Get the columns for a table as a hash, key is the column name
       # value is the column object.
       def columns_hash(table_name)
-        @columns_hash[table_name] ||= Hash[columns(table_name).map { |col|
-          [col.name, col]
-        }]
+        @columns_hash[table_name] ||= begin
+          if table_name.blank?
+            raise ActiveRecord::NoTableError, "columns_hash is not available for a model with no table"
```
Comment (itsWill) [inline activerecord/lib/active_record/connection_adapters/schema_cache.rb]: @gmcgibbon ended up moving the raising of the exception here, since this is actually the point at which the exception is raised.

File: activerecord/lib/active_record/model_schema.rb [hunk 4]
```diff
@@ -484,6 +484,9 @@ def load_schema
         end
 
         def load_schema!
+          unless table_exists?
```
Comment (eugeneius) [inline activerecord/lib/active_record/model_schema.rb]: This will be true in two scenarios: when the model is abstract and no table is configured, or when a table is configured but it doesn't exist in the database. In the latter case I think the existing error works better, since it's clearer that the application expected the table to exist.

I think we should only raise this new error in the former case:

```suggestion
          unless table_name
```

This would conveniently also fix the railties tests that are failing:
https://buildkite.com/rails/rails/builds/61157#fdf33e0b-7168-4e4a-bb9c-ed39c4f40766/1019-1029

File: activerecord/lib/active_record/model_schema.rb [hunk 5]
```diff
@@ -484,6 +484,9 @@ def load_schema
...
+            raise ActiveRecord::NoTableError, "columns_hash is not available for a model with no table"
```
Comment (eugeneius) [inline activerecord/lib/active_record/model_schema.rb]: This error still mentions `columns_hash`, but `load_schema!` is called from several other places.

```suggestion
            raise ActiveRecord::NoTableError, "#{self} has no table configured"
```

File: activerecord/lib/active_record/model_schema.rb (hunk 4 above)
Comment (itsWill) [reply activerecord/lib/active_record/model_schema.rb]: great catch thanks!

File: activerecord/lib/active_record/model_schema.rb (hunk 5 above)
Comment (itsWill) [reply activerecord/lib/active_record/model_schema.rb]: ❤️

File: activerecord/lib/active_record/model_schema.rb [hunk 6]
```diff
@@ -484,6 +484,9 @@ def load_schema
         end
 
         def load_schema!
+          unless table_name
+            raise ActiveRecord::NoTableError, "#{self} has no table configured"
```
Comment (gmcgibbon) [inline activerecord/lib/active_record/model_schema.rb]: I would make this error more actionable by stating what they need to do to set the table name eg. `"#{self} has no table configured. Set one with #{self}.table_name="`.

**Review by gmcgibbon — COMMENTED** [review]
Needs a changelog, and perhaps a small adjustment to the error message (see comment). Otherwise LGTM 👍

File: activerecord/lib/active_record/errors.rb [hunk 7]
```diff
@@ -183,6 +183,10 @@ class PreparedStatementInvalid < ActiveRecordError
   class NoDatabaseError < StatementInvalid
   end
 
+  # Raised when a given table does not exist.
+  class NoTableError < ActiveRecordError
```
Comment (eugeneius) [inline activerecord/lib/active_record/errors.rb]: Naming this `NoTableError` makes it sound equivalent to the existing `NoDatabaseError`, but they're actually a bit different: `NoDatabaseError` is raised when a database name was specified but doesn't exist, whereas this new error will only raised when no table name is specified.

It might be interesting to explore (in another PR) raising a more specific error class when the specified table doesn't exist, as we do for other known classes of database error:

https://github.com/rails/rails/blob/v5.2.3/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L636-L661
https://github.com/rails/rails/blob/v5.2.3/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L424-L441
https://github.com/rails/rails/blob/v5.2.3/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L496-L505

The natural name for that error class would be `NoTableError`, since it _would_ be equivalent to `NoDatabaseError`, but using the name here would preclude us from using it for that purpose later.

What do you think of naming this one `TableNotSpecified` instead, by analogy to [`AdapterNotSpecified`](https://github.com/rails/rails/blob/v5.2.3/activerecord/lib/active_record/errors.rb#L38)?

Comment (itsWill) [reply activerecord/lib/active_record/errors.rb]: Yes! I really like this, I couldn't quite put to words what I didn't like about this PR but I think thats it. `NoTableError` today is not a `ActiveRecord::StatementInvalid` exception like `NoDatabaseError` that comes form the DB but rather an app level error so I'm totally digging: `TableNotSpecified`. I'll update ❤️

File: activerecord/test/cases/base_test.rb [hunk 8]
```diff
@@ -1412,6 +1412,14 @@ def test_default_values_are_deeply_dupped
     assert_not_includes SymbolIgnoredDeveloper.columns_hash.keys, "first_name"
   end
 
+  test "#columns_hash raises an error if the record has an empty table name" do
```
Comment (gmcgibbon) [inline activerecord/test/cases/base_test.rb]: This is a class method so I think `".columns_hash raises an error if the record has an empty table name"` is more appropriate.

**Review by gmcgibbon — APPROVED** [review]
LGTM. Please rebase 👍

File: activerecord/CHANGELOG.md [hunk 9]
```diff
@@ -1,3 +1,7 @@
+*   Loading the schema for a model that has no `table_name` raises a `NoTableError` error.
```
Comment (eugeneius) [inline activerecord/CHANGELOG.md]:
```suggestion
*   Loading the schema for a model that has no `table_name` raises a `TableNotSpecified` error.
```

Comment (eugeneius) [reply activerecord/CHANGELOG.md]: Sorry this PR fell off my radar for a while; other than updating the changelog entry I think it's good to go ❤️

File: activerecord/CHANGELOG.md [hunk 10]
```diff
@@ -1,3 +1,7 @@
...
+
+    *Guilherme Mansur, Eugene Kenny*
```
Comment (kamipo) [inline activerecord/CHANGELOG.md]:
```suggestion
    *Guilherme Mansur*, *Eugene Kenny*
```
