### PR TITLE
activemodel: make .model_name json encodable

### LINKED ISSUE #19050: Infinite loop calling to_json on ActiveModel::Name
Calling to_json on an ActiveModel::Name, or any data structure containing it, results in an infinite loop.

    #!/usr/bin/env ruby
    unless File.exists?('Gemfile')
      File.write('Gemfile', <<-GEMFILE)
        source 'https://rubygems.org'
        gem 'rails', '4.2.0'
        gem 'json', '1.8.1'
        gem 'sqlite3'
      GEMFILE
    
      system 'bundle'
    end
    
    require 'bundler'
    Bundler.setup(:default)
    
    require 'active_record'
    require 'minitest/autorun'
    require 'logger'
    
    # This connection will do for database-independent bug reports.
    ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
    ActiveRecord::Base.logger = Logger.new(STDOUT)
    
    ActiveRecord::Schema.define do
      create_table :books do |t|
      end
    end
    
    class Book < ActiveRecord::Base
    end
    
    class BugTest < MiniTest::Test
      def test_convert_model_name_to_json
        assert Book.model_name.to_json.present?
      end
    end

### PR DESCRIPTION
**Pull request by ianks**
Previously. calling `User.model_name.to_json` would result in an infinite recursion as `.model_name` did not respond to the `.to_json`. This patch fixesthat unexpected behavior by delegating `.to_json` to the correct handler.

resolves https://github.com/rails/rails/issues/19050

### CODE REVIEW

File: activemodel/lib/active_model/naming.rb [hunk 1]
```diff
@@ -130,7 +130,7 @@ class Name
     #
     # Equivalent to +to_s+.
     delegate :==, :===, :<=>, :=~, :"!~", :eql?, :to_s,
-             :to_str, to: :name
+             :to_str, :to_json, to: :name
```
Comment (egilburg) [inline activemodel/lib/active_model/naming.rb]: I think you should be delegating `as_json` which returns a JSON-convertible Ruby object such as a String instance. `to_json` returns the actual escape JSON, e.g. it should return `"\"User\""` rather than `"User"`

Comment (rafaelfranca) [inline activemodel/lib/active_model/naming.rb]: :+1:

**Comment by ianks** [comment]
@chancancode @rafaelfranca @egilburg 

Made changes according to comments and rebased.  https://github.com/ianks/rails/commit/c5d62cb86d958aaa68a4057b3c2578329044e674

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by rafaelfranca** [comment]
Backported as 0edb646 and 17bc8d2

**Comment by chancancode** [comment]
:+1: !
