### PR TITLE
Break long variant filenames into path chunks

### LINKED ISSUE #30662: ActiveStorage variant raises Errno::ENAMETOOLONG
### Steps to reproduce

```
# storage.yml
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

```

```
# user.rb
class User < ApplicationRecord
  has_one_attached :avatar
end
```

```
f = File.open(Rails.root.join("spec", "assets", "png.png"))
u = User.first
attachment = u.avatar.attach io: f, filename: "my avatar", content_type: "image/png"
variant = attachment.variant thumbnail: "100x100>", background: :white, gravity: :center, extent: "100x100"
variant.processed.service_url
# => Errno::ENAMETOOLONG: File name too long @ rb_sysopen - /home/myname/Work/repos/github/project/storage/va/ri/variants/XYnB7EN9Yq6agpMwzmQQJ8HP/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9PZEdoMWJXSnVZV2xzU1NJTk1UQXdlREV3TUQ0R09nWkZWRG9QWW1GamEyZHliM1Z1WkRvS2QyaHBkR1U2REdkeVlYWnBkSGs2QzJObGJuUmxjam9MWlhoMFpXNTBTU0lNTVRBd2VERXdNQVk3QmxRPSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--b8a505ddd21c7236e0f88d343c26ae1d17bcfbd5
	from (irb):17

```

### Expected behavior
no `Errno::ENAMETOOLONG` exception 

### Actual behavior
`Errno::ENAMETOOLONG` exception is raised because the file name is too long

### System configuration
**Rails version**:
master (07bac9ef93d98a1e31cd5b2ce2aabc1e57816604)

**Ruby version**:
2.3.5

**OS**
Ubuntu 16.04

### PR DESCRIPTION
**Pull request by khall**
### Summary

If a variant has a large set of options associated with it, the generated filename will be too long, causing Errno::ENAMETOOLONG to be raised. This change adds intermediary paths that retain the uniqueness of the variant while not raising the aforementioned error until the overall 1024 path limit is exceeded. Fixes #30662.

### Other Information

Initially I was worried about needing to join the chunked paths in order to be able to decode the data back into the variant information. I'm no longer sure if that's a valid use-case. Any insight as to the validity of this belief would be useful. Also all this code basically came from @marcusg, the reporter.

### CODE REVIEW

**Comment by georgeclaghorn** [comment]
If we’re going to do this, it should be done in `DiskService`. The long key problem isn’t specific to variants.

**Comment by matthewd** [comment]
Should we hash this instead, so there's no limit at all? That clearly can't work if we have to parse information back out of the filename, but without checking, I assume that's not a thing we do.

**Comment by georgeclaghorn** [comment]
We intend to: purging a blob will eventually purge its variants, too.

**Comment by georgeclaghorn** [comment]
We could just hash the encoded transformations, preserving the `variants/#{blob.id}` prefix.

**Comment by khall** [comment]
@georgeclaghorn Are you suggesting something like having variant#key return `"variants/#{blob.key}/#{variation.hash}"`? If so, is there any concern about losing the signed message passed back from ActiveSupport's message_verifier?

**Comment by georgeclaghorn** [comment]
I’m suggesting something like this:

```ruby
class Variant
  def key
    "variants/#{blob.key}/#{Digest::MD5.base64digest(variation.key)}"
  end
end
```

**Comment by georgeclaghorn** [comment]
Looks good. Could you please squash your commits into one?

**Comment by khall** [comment]
Absolutely

File: activestorage/app/models/active_storage/variant.rb [hunk 1]
```diff
@@ -50,7 +50,7 @@ def processed
 
   # Returns a combination key of the blob and the variation that together identifies a specific variant.
   def key
-    "variants/#{blob.key}/#{variation.key}"
+    "variants/#{blob.key}/#{Digest::MD5.base64digest(variation.key)}"
```
Comment (rafaelfranca) [inline activestorage/app/models/active_storage/variant.rb]: Don't we need to require `digest` in this file? Or it is being required globally in activestorage?

Comment (khall) [reply activestorage/app/models/active_storage/variant.rb]: `Digest::MD5` appears to already be loaded here. It's also used in "/app/models/active_storage/blob.rb" without a `require`, not sure where it's getting loaded.

**Comment by georgeclaghorn** [comment]
Please amend your commit message to accurately describe the change; we’re not breaking up long filenames anymore.

**Comment by matthewd** [comment]
We should use SHA256 (possibly truncated) instead of MD5, even though it's unlikely to matter for most purposes... there are systems that explicitly disable MD5 for compliance reasons.

Also, base64 assumes case-sensitive storage, which doesn't seem safe. We could use base36 or something, but probably simpler to just go with hex. It'll still be far more dense than the current raw key.

**Comment by khall** [comment]
Updated commit message and CHANGELOG message, applied SHA256 hash instead of MD5. Squashed it all.

**Comment by georgeclaghorn** [comment]
The CHANGELOG entry isn’t necessary since Active Storage hasn’t been included in a released version of Rails yet.

The test doesn’t seem particularly necessary, either.

**Comment by matthewd** [comment]
The current test does seem a little under-explanatory. But maybe if we pad it out with a `padding: "a" * 10_000`, then assert that the URL is less than 200 (say?) characters, that might be more descriptive?

I do think it's a feature (and thus test-worthy) that the storage URL can't grow unbounded... I think the current test is just too realistic :sweat_smile: to fully illustrate what it cares about.

**Comment by khall** [comment]
Updated the test (although I used "font" instead of "padding"), re-verified that test only passes with proposed fix, cleaned CHANGELOG.

**Comment by georgeclaghorn** [comment]
Thanks!
