### PR TITLE
Apply content security policy mapping when generated dynamically:

### LINKED ISSUE #44536: Content-Security-Policy: `:self` isn't turned into `'self'` when returned inside an array from a lambda
### Steps to reproduce

Sorry, I don't have a lot of time to create actual repro steps, but...

If you do something like this:

```ruby
class ApplicationController < ActionController::Base
  content_security_policy do |policy|
    policy.frame_ancestors lambda { [:self, "https://example.com"] }
  end
end
```

Then the `content-security-policy` HTTP header will look like this:

```
content-security_policy: frame-ancestors self https://example.com
```

Note that it says `self` instead of `'self'`.

This only happens when you return an array from that lambda. If you return `:self` it works fine. Also moving `:self` to outside the lambda (passed directly to `frame_ancestors` works as expected.

### Expected behavior

```
content-security_policy: frame-ancestors 'self' https://example.com
```

### Actual behavior

```
content-security_policy: frame-ancestors self https://example.com
```

### System configuration
**Rails version**: 6.0.4.4 (but I see no diff between the relevant file and `main`)

**Ruby version**: 2.6.8

### PR DESCRIPTION
**Pull request by Edouard-chin**
Apply content security policy mapping when generated dynamically:

- Fix #44536

### CODE REVIEW

File: actionpack/lib/action_dispatch/http/content_security_policy.rb [hunk 1]
```diff
@@ -345,7 +345,7 @@ def resolve_source(source, context)
             raise RuntimeError, "Missing context for the dynamic content security policy source: #{source.inspect}"
           else
             resolved = context.instance_exec(&source)
-            resolved.is_a?(Symbol) ? apply_mapping(resolved) : resolved
+            apply_mappings(Array.wrap(resolved))
```
Comment (SkipKayhil) [inline actionpack/lib/action_dispatch/http/content_security_policy.rb:348]: Should `require "active_support/core_ext/array/wrap"` be added in this file?

Comment (Edouard-chin) [reply actionpack/lib/action_dispatch/http/content_security_policy.rb:348]: Thanks, you are right!

**Comment by byroot** [comment]
Thanks Édouard !
