### PR TITLE
Fix raw_post raising when rack.input is nil

### LINKED ISSUE #52125: Some Rails integration tests break with rack 3.1
### Steps to reproduce
Any reference to `request.raw_post` will trigger an exception during integration tests. The code works fine, as do system and controller tests.

Apparently this is due to the header 'rack.input' which has now become optional, and will be nil if there is no input: https://github.com/rack/rack/pull/1997

Rails should probably check for existence of that header (or lock to an older rack version)

### Expected behavior
No test failures

### Actual behavior
```
`NoMethodError: undefined method `read' for nil
           /ruby-3.3.1/gems/actionpack-7.1.3.4/lib/action_dispatch/http/request.rb:472:in `read_body_stream'
```

### System configuration
**Rails version**: 7.1.3.4

**Ruby version**: 3.3.1

### PR DESCRIPTION
**Pull request by skipkayhil**
### Motivation / Background

Fixes #52125

### Detail

Starting in Rack 3.1, rack.input is optional, so `read_body_stream` (used by `raw_post`) can no longer call `read` unconditionally.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: actionpack/lib/action_dispatch/http/request.rb [hunk 1]
```diff
@@ -466,11 +466,13 @@ def default_session
       end
 
       def read_body_stream
-        reset_stream(body_stream) do
```
Comment (zzak) [inline actionpack/lib/action_dispatch/http/request.rb:469]: Is there anything else that calls `reset_stream`? It is private, so maybe we should move this into there to deal with nil?

Comment (rafaelfranca) [reply actionpack/lib/action_dispatch/http/request.rb:469]: Yes, you can move there. I actually refactored that code to fix this issue. I'm not sure only changing this method is enough. Rails has assumption that `request.body` will return something.

Screenshot 2024-06-17 at 2 49 30 PM

Comment (skipkayhil) [reply actionpack/lib/action_dispatch/http/request.rb:469]: I felt like `read_body_stream` was an appropriate place to check for `nil` since `reset_stream` to me implies we are passing a (non-nil) `stream`, but I don't have a strong preference and am happy to move the nil-check.

Is the goal to have `body` always return a `StringIO` even though `rack.input` can be `nil` now? Or just that we need to handle that case in Action Mailbox?

Comment (rafaelfranca) [reply actionpack/lib/action_dispatch/http/request.rb:469]: I think `body` can return `nil`, but our code should not rely on it never returning `nil`.

**Comment by skipkayhil** [comment]
Rebased and fixed the Action Mailbox controller. As I mention in the commit message, this doesn't appear to be testable inside `IntegrationTest` at the moment. It seems like `rack` and/or `rack-test` needs to be updated to allow `rack.input` to be `nil` inside `IntegrationTest`.

**Comment by zzak** [comment]
Maybe this helps:

* `Rack::MockRequest.env_for` accepts an input option:
https://github.com/rack/rack/blob/0b6f760021e01b3031128e81536fc61cef676969/lib/rack/mock_request.rb#L142
* You can also pass in options to `MockRequest#request`: https://github.com/rack/rack/blob/0b6f760021e01b3031128e81536fc61cef676969/lib/rack/mock_request.rb#L66-L67
* We configure the MockRequest in rails here: https://github.com/rails/rails/blob/6045f257fbbff039edb2542c9859488cec0dcaa9/actionpack/lib/action_dispatch/testing/test_request.rb#L17-L21

So maybe you can pass it in your test? Or you can override `env[RACK_INPUT]`?

I'm not sure it helps, but it's nice if we have test coverage, I guess.

Thanks for working on this!

**Comment by skipkayhil** [comment]
> Or you can override `env[RACK_INPUT]`

This worked 🎉 I rebased to fix the CHANGELOG conflict and now there is a working test for both places

**Comment by jimbali** [comment]
Wow, thanks for fixing and releasing this one day before I ran into the issue! 🎉
