### PR TITLE
Always reset changed attributes in becomes

### LINKED ISSUE #16881: Using becomes! on an association does not properly set the changed_attribute for the STI column
In Rails 4.1.6, when calling becomes! on an association, the single table inheritance column in the changed_attributes hash is nil instead of the previous value.

I have a unit test below that tests 4 different scenarios. The last test is the one that is failing:

```
unless File.exist?('Gemfile')
    File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', '~> 4.1.6'
    gem 'sqlite3'
    GEMFILE

    system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
    create_table :suppliers do |t|
        t.string :name
    end
 
    create_table :accounts do |t|
        t.string :type
        t.belongs_to :supplier
        t.string :account_number
    end
end

class Supplier < ActiveRecord::Base
    has_one :account
end

class Account < ActiveRecord::Base; end
class AccountA < Account; end
class AccountB < Account; end

class BugTest < Minitest::Test

    def test_changing_type
        account = AccountA.create!
        new_account = account.becomes!(AccountB)

        assert_equal 'AccountA', new_account.changed_attributes[:type]
    end

    def test_changing_type_with_reload
        account = AccountA.create!
        account.reload
        new_account = account.becomes!(AccountB)

        assert_equal 'AccountA', new_account.changed_attributes[:type]
    end

    def test_changing_type_through_association
        supplier = Supplier.create!
        supplier.account = AccountA.create!
        new_account = supplier.account.becomes!(AccountB)

        assert_equal 'AccountA', new_account.changed_attributes[:type]
    end

    def test_changing_type_through_association_with_reload
        supplier = Supplier.create!
        supplier.account = AccountA.create!
        supplier.reload
        new_account = supplier.account.becomes!(AccountB)

        assert_equal 'AccountA', new_account.changed_attributes[:type]
    end

end
```

Has anyone else run into this?

### PR DESCRIPTION
**Pull request by mfazekas**
When `becomes` changes @attributes it should also change
@changed_attributes. Otherwise we'll experience a kind of split head situation
where attributes are coming from `self`, but changed_attributes is coming
from `klass.new`. This affects the inheritance_colmn as it's changed by new
for example.

Fixes #16881

### CODE REVIEW

**Comment by arthurnn** [comment]
:+1:

File: activerecord/lib/active_record/persistence.rb [hunk 1]
```diff
@@ -197,7 +197,7 @@ def destroy!
     def becomes(klass)
       became = klass.new
       became.instance_variable_set("@attributes", @attributes)
-      became.instance_variable_set("@changed_attributes", @changed_attributes) if defined?(@changed_attributes)
+      became.instance_variable_set("@changed_attributes", defined?(@changed_attributes) ? @changed_attributes : {})
```
Comment (sgrif) [inline activerecord/lib/active_record/persistence.rb]: Please no ternaries.

Comment (mfazekas) [inline activerecord/lib/active_record/persistence.rb]: fixed, rebased to master

File: activerecord/lib/active_record/persistence.rb [hunk 2]
```diff
@@ -207,7 +207,8 @@ def destroy!
     def becomes(klass)
       became = klass.new
       became.instance_variable_set("@attributes", @attributes)
-      became.instance_variable_set("@changed_attributes", @changed_attributes) if defined?(@changed_attributes)
+      changed_attributes = @changed_attributes if defined?(@changed_attributes)
+      became.instance_variable_set("@changed_attributes",changed_attributes || {})
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/persistence.rb]: missing space after the `,`

File: activerecord/test/cases/inheritance_test.rb [hunk 3]
```diff
@@ -121,6 +121,12 @@ def test_alt_becomes_works_with_sti
     assert_kind_of Cabbage, cabbage
   end
 
+  def test_becomes_and_change_tracking_for_inheritance_columns
+    cucumber = Vegetable.find(1)
+    cabbage = cucumber.becomes!(Cabbage)
+    assert_equal ['Cucumber','Cabbage'], cabbage.custom_type_change
```
Comment (rafaelfranca) [inline activerecord/test/cases/inheritance_test.rb]: Missing space after the `,`

**Comment by rafaelfranca** [comment]
We need a changelog entry

**Comment by mfazekas** [comment]
added space after comma, added changelog, rebased to master

**Comment by rafaelfranca** [comment]
Backported at 93a6500baa6bbb331bb93ccdc14fdda5769f5ef9 and abb9269
