### PR TITLE
Recognize Windows-style paths in test runner

### LINKED ISSUE #38243: Rails test command on Windows runs all tests in a file instead of just the test specified by a line number
### Steps to reproduce

Open cmd and create a new Rails app:

```
rails new test-app
```

Change directory to the app:

```
cd test-app
```

Create a new test file at `test\sample_test.rb`:

```
require "test_helper"

class SampleTest < ActiveSupport::TestCase
  test "this is the first one" do
    assert true
  end

  test "this is the second one (will fail)" do
    assert false
  end

  test "this is the third one" do
    assert_not false
  end

  test "this is the fourth one (will fail)" do
    assert_not true
  end
end
```

Go back to cmd and run the test at a specific line number:

```
rails test test\sample_test.rb:4
```

### Expected behavior

According to [the Rails Guide](https://guides.rubyonrails.org/testing.html), when you run the rails test command on a file, specifying the line number, only the test at that line number should run.

### Actual behavior

When you run the rails test command on a file, specifying the line number, all the tests in the file are run.

In the example presented, the following output was generated:

```
Run options: --seed 25537

# Running:

F

Failure:
SampleTest#test_this_is_the_second_one_(will_fail) [C:/Users/myusername/rails/test-app/test/sample_test.rb:9]:
Expected false to be truthy.


rails test test/sample_test.rb:8

.F

Failure:
SampleTest#test_this_is_the_fourth_one_(will_fail) [C:/Users/myusername/rails/test-app/test/sample_test.rb:17]:
Expected true to be nil or false


rails test test/sample_test.rb:16

.

Finished in 0.064904s, 61.6299 runs/s, 61.6299 assertions/s.
4 runs, 4 assertions, 2 failures, 0 errors, 0 skips
```

You can see that it did not run only the test at line 4. It went on to run all the tests.

If you change the line number to 12, it does the same thing and includes preceding tests as well as the ones afterward.

### System configuration

**Operating System**: Windows 10 Enterprise Version 1909
**Command Line**: cmd.exe
**Ruby Version**: `ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]`
**Rails Version**: Rails 6.0.2.1

### PR DESCRIPTION
**Pull request by jonathanhefner**
Previously, a test runner argument had to contain a forward slash to be recognized as a path.  Now, backslashes will also be considered, enabling the use of Windows-style paths.

Fixes #38243.

### CODE REVIEW

File: railties/test/application/test_runner_test.rb [hunk 1]
```diff
@@ -320,6 +320,17 @@ def test_run_relative_path_with_trailing_slash
       end
     end
 
+    def test_run_windows_style_path
+      create_test_file :models, "account"
+      create_test_file :controllers, "accounts_controller"
+
+      # double-escape backslash -- once for Ruby and again for shelling out
+      run_test_command("test\\\\models").tap do |output|
```
Comment (jonathanhefner) [inline railties/test/application/test_runner_test.rb:328]: Windows apparently [ignores double slashes in paths](https://stackoverflow.com/questions/15969608/what-is-the-difference-between-and-in-file-path/15969841#15969841), so this test should hopefully pass on Windows even if the 2nd level of escape is not treated as an escape.

**Comment by jonathanhefner** [comment]
/cc @kaspth since you expressed interest in https://github.com/rails/rails/issues/38243#issuecomment-616791720

Should this make it into 6.1?

File: railties/test/application/test_runner_test.rb [hunk 2]
```diff
@@ -320,6 +320,17 @@ def test_run_relative_path_with_trailing_slash
       end
     end
 
+    def test_run_windows_style_path
+      create_test_file :models, "account"
+      create_test_file :controllers, "accounts_controller"
+
+      # double-escape backslash -- once for Ruby and again for shelling out
```
Comment (kaspth) [inline railties/test/application/test_runner_test.rb:327]: lololol 😄

File: railties/test/application/test_runner_test.rb (hunk 1 above)
Comment (kaspth) [reply railties/test/application/test_runner_test.rb:328]: > 2nd level of escape is not treated as an escape

One flew over the cuckoo's nest and landed right back in? 😄

**Comment by kaspth** [comment]
It should! Hereby done 🔨
