### PR TITLE
Followup of #15771

### LINKED ISSUE #24695: Optimistic locking raise ActiveRecord::StaleObjectError when lock version in database is null
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true  do |t|
    t.integer :lock_version
    t.string :title
  end

end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(lock_version: nil)

    post.title = 'some title'
    post.save!
  end
end
```

### PR DESCRIPTION
**Pull request by vipulnsward**
Make sure we handle explicitly passed nil's to lock_version as well

Fixes #24695

r? @sgrif

### CODE REVIEW

**Comment by maclover7** [comment]
Nice use of the new attributes API 👍

File: activerecord/lib/active_record/locking/optimistic.rb [hunk 1]
```diff
@@ -190,6 +190,11 @@ def deserialize(value)
         super.to_i
       end
 
+      def serialize(value)
+        # `nil` *should* be changed to 0
```
Comment (sgrif) [inline activerecord/lib/active_record/locking/optimistic.rb]: Can we kill this comment, and mention why `nil` should be changed to `0` in the commit message instead?

File: activerecord/lib/active_record/locking/optimistic.rb [hunk 2]
```diff
@@ -190,6 +190,10 @@ def deserialize(value)
         super.to_i
       end
 
+      def serialize(value)
+        super.to_i
+      end
```
Comment (vipulnsward) [inline activerecord/lib/active_record/locking/optimistic.rb]: removed

File: activerecord/lib/active_record/locking/optimistic.rb (hunk 1 above)
Comment (jeremy) [inline activerecord/lib/active_record/locking/optimistic.rb]: This is when we want a comment on the _behavior of the code_, not just a comment on the _intent of the commit_.

We have some code that intentionally explicitly coerces `nil` to an integer, and it's code that looks like it may be an inadvertent bug. A comment _on the code_ clarifies that this is desired behavior. The comment lives with the behavior, not just with the commit that introduced the behavior.

Comment (vipulnsward) [inline activerecord/lib/active_record/locking/optimistic.rb]: A similar comment still exists on deserialize. Should that suffice, or it needs to be added here as well?

Comment (jeremy) [inline activerecord/lib/active_record/locking/optimistic.rb]: Could discuss it in a comment on LockingType instead.
