### PR TITLE
Fixes failing ActionText::ContentTest test cases

### LINKED ISSUE #41782: Three of ActionText::ContentTest fail when executed after "converts Trix-formatted attachments with custom tag name"
Reproduced CI failure at https://buildkite.com/rails/rails/builds/76072#00d53283-5fff-413e-9ee1-119130ada979

### Steps to reproduce
```ruby
cd actiontext
bin/test test/unit/content_test.rb -n "/^(?:ActionText::ContentTest#(?:test_converts_Trix-formatted_attachments_with_custom_tag_name|test_canonicalizes_attachment_gallery_markup|test_canonicalizes_attachment_gallery_markup_with_whitespace|test_canonicalizes_nested_attachment_gallery_markup))$/" --seed 37598
```

### Expected behavior
It should pass.

### Actual behavior
It always fails as follows.

```ruby
$ bin/test test/unit/content_test.rb -n "/^(?:ActionText::ContentTest#(?:test_converts_Trix-formatted_attachments_with_custom_tag_name|test_canonicalizes_attachment_gallery_markup|test_canonicalizes_attachment_gallery_markup_with_whitespace|test_canonicalizes_nested_attachment_gallery_markup))$/" --seed 37598

Run options: -n "/^(?:ActionText::ContentTest#(?:test_converts_Trix-formatted_attachments_with_custom_tag_name|test_canonicalizes_attachment_gallery_markup|test_canonicalizes_attachment_gallery_markup_with_whitespace|test_canonicalizes_nested_attachment_gallery_markup))$/" --seed 37598

# Running:

.F

Failure:
ActionText::ContentTest#test_canonicalizes_nested_attachment_gallery_markup [/home/yahonda/src/github.com/rails/rails/actiontext/test/unit/content_test.rb:116]:
--- expected
+++ actual
@@ -1 +1 @@
-"<blockquote><div><action-text-attachment sgid=\"1\" presentation=\"gallery\"></action-text-attachment><action-text-attachment sgid=\"2\" presentation=\"gallery\"></action-text-attachment></div></blockquote>"
+"<blockquote><div class=\"attachment-gallery attachment-gallery--2\"><action-text-attachment sgid=\"1\" presentation=\"gallery\"></action-text-attachment><action-text-attachment sgid=\"2\" presentation=\"gallery\"></action-text-attachment></div></blockquote>"



bin/test test/unit/content_test.rb:113

F

Failure:
ActionText::ContentTest#test_canonicalizes_attachment_gallery_markup_with_whitespace [/home/yahonda/src/github.com/rails/rails/actiontext/test/unit/content_test.rb:110]:
--- expected
+++ actual
@@ -1,4 +1,4 @@
-"<div>
+"<div class=\"attachment-gallery attachment-gallery--2\">
   <action-text-attachment sgid=\"1\" presentation=\"gallery\"></action-text-attachment>
   <action-text-attachment sgid=\"2\" presentation=\"gallery\"></action-text-attachment>
 </div>"



bin/test test/unit/content_test.rb:107

F

Failure:
ActionText::ContentTest#test_canonicalizes_attachment_gallery_markup [/home/yahonda/src/github.com/rails/rails/actiontext/test/unit/content_test.rb:104]:
--- expected
+++ actual
@@ -1 +1 @@
-"<div><action-text-attachment sgid=\"1\" presentation=\"gallery\"></action-text-attachment><action-text-attachment sgid=\"2\" presentation=\"gallery\"></action-text-attachment></div>"
+"<div class=\"attachment-gallery attachment-gallery--2\"><action-text-attachment sgid=\"1\" presentation=\"gallery\"></action-text-attachment><action-text-attachment sgid=\"2\" presentation=\"gallery\"></action-text-attachment></div>"



bin/test test/unit/content_test.rb:101



Finished in 0.119176s, 33.5637 runs/s, 41.9547 assertions/s.
4 runs, 5 assertions, 3 failures, 0 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**:ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
It also reproduces with Ruby 3.0.0.

### PR DESCRIPTION
**Pull request by abhaynikam**
The test cases where failing because the test
`test_converts_Trix-formatted_attachments_with_custom_tag_name` set a
custom tag_name to `arbitrary-tag`. This test would also set the
ActionText::AttachmentGallery::ATTACHMENT_SELECTOR private constant
to `arbitrary-tag`.

Other test cases had proper ActionText::Attachment.tag_name set to
`action-text-attachment` but the constant once defined would not
reset.

This PR attempts to fix the issue by running the test cases in
isolation.

Fixes #41782

image

### CODE REVIEW

File: actiontext/lib/action_text/attachment_gallery.rb [hunk 1]
```diff
@@ -4,6 +4,12 @@ module ActionText
   class AttachmentGallery
     include ActiveModel::Model
 
+    TAG_NAME = "div"
+    cattr_accessor :attachment_selector, default: "#{ActionText::Attachment.tag_name}[presentation=gallery]"
+    cattr_accessor :selector, default: "#{TAG_NAME}:has(#{attachment_selector} + #{attachment_selector})"
```
Comment (georgeclaghorn) [inline actiontext/lib/action_text/attachment_gallery.rb:9]: These still won’t reflect `ActionText::Attachment.tag_name` changes. Let’s make them literal methods:

```ruby
class << self
  def attachment_selector
    "#{ActionText::Attachment.tag_name}[presentation=gallery]"
  end
end
```
