### PR TITLE
Fix `Enumerable#sole` for infinite collections

### LINKED ISSUE #54335: Enumerable#sole is inefficient
I've been using ActiveSupport's `Enumerator#sole` method recently and noticed something unfortunate about the implementation:

```ruby
  def sole
    case count
    when 1   then return first # rubocop:disable Style/RedundantReturn
    when 0   then raise SoleItemExpectedError, "no item found"
    when 2.. then raise SoleItemExpectedError, "multiple items found"
    end
  end
```

Unless the specific object has a more efficient implementation, calling `count` results in `enum`erating the entire collection. If there is only one item, it's re-enumerated when calling `first`. For in-memory collections this is mostly not so bad.

Although, if one does something extremely silly it becomes noticeable:

```ruby
puts Benchmark.measure {  [].to_enum.sole rescue nil }.utime
# => 5.800000000277805e-05

a = Array.new(1_000_000) # this is very silly
puts Benchmark.measure {  a.to_enum.sole rescue nil }.utime
# => 0.02890700000000379
```

But the real problem arose when used on a collection that's backed by dynamically fetching resources from an API endpoint. This is problematic for a couple reasons:

* Two requests instead of one.
* The second enumeration could have a different set of results.

Another unfortunate side-effect of using `count` under the covers is `sole` hangs forever when given an infinite sequence. (e.g. `[1].cycle.sole`)

I haven't thought this all the way through, but something like the following seems to have the same qualities as the current implementation but only pulls at most 2 items from the collection:

```ruby
    def sole
      result = nil
      found = false

      self.each_entry do |entry|
        if found
          raise SoleItemExpectedError, "multiple items found"
        end

        result = entry
        found = true
      end

      return result if found

      raise SoleItemExpectedError, "no item found"
    end
```

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #54335.

### CODE REVIEW

File: activesupport/lib/active_support/core_ext/enumerable.rb [hunk 1]
```diff
@@ -209,10 +209,16 @@ def in_order_of(key, series, filter: true)
   #   Set.new.sole        # => Enumerable::SoleItemExpectedError: no item found
   #   { a: 1, b: 2 }.sole # => Enumerable::SoleItemExpectedError: multiple items found
   def sole
-    case count
-    when 1   then return first # rubocop:disable Style/RedundantReturn
+    if is_a?(Range) && (self.begin.nil? || self.end.nil?)
```
Comment (nvasilevski) [inline activesupport/lib/active_support/core_ext/enumerable.rb:212]: Should we redefine `sole` on `Range` then so other `Enumerable` don't have to pay the price of checking `is_a(Range)` on each call? Range's implementation can perform the check and then call `super`

Comment (fatkodima) [reply activesupport/lib/active_support/core_ext/enumerable.rb]: Good idea 👍

File: activesupport/lib/active_support/core_ext/range/sole.rb [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+class Range
+  # Returns the sole item in the range. If there are no items, or more
+  # than one item, raises Enumerable::SoleItemExpectedError.
+  #
+  #   (1..1).sole   # => 1
+  #   (2..1).sole   # => Enumerable::SoleItemExpectedError: no item found
+  #   (..1).sole    # => Enumerable::SoleItemExpectedError: multiple items found
+  def sole
+    if self.begin.nil? || self.end.nil?
+      raise ActiveSupport::EnumerableCoreExt::SoleItemExpectedError, "multiple items found"
```
Comment (nvasilevski) [inline activesupport/lib/active_support/core_ext/range/sole.rb:12]: Not sure if it's worth it but wanted to mention that we have an opportunity to be more specific in the message and tell that the instance is an endless array which by definition can not represent a sole item

**Review by nvasilevski — APPROVED** [review]

File: activesupport/lib/active_support/core_ext/enumerable.rb [hunk 3]
```diff
@@ -209,10 +209,12 @@ def in_order_of(key, series, filter: true)
...
   def sole
-    case count
-    when 1   then return first # rubocop:disable Style/RedundantReturn
+    first_two = first(2)
+
+    case first_two.count
+    when 1   then first_two.first
     when 0   then raise ActiveSupport::EnumerableCoreExt::SoleItemExpectedError, "no item found"
-    when 2.. then raise ActiveSupport::EnumerableCoreExt::SoleItemExpectedError, "multiple items found"
+    when 2   then raise ActiveSupport::EnumerableCoreExt::SoleItemExpectedError, "multiple items found"
```
Comment (bogdan) [inline activesupport/lib/active_support/core_ext/enumerable.rb:217]: This causes array allocation on `first(2)`. Maybe a better implementation memory wise would be:

``` ruby
result = none = Object.new
each do |element|
  if result == none
    result = element
  else
    raise ActiveSupport::EnumerableCoreExt::SoleItemExpectedError, "multiple items found"
end
if result == none
  ActiveSupport::EnumerableCoreExt::SoleItemExpectedError, "no item found"
else
  result
end
```

Comment (fatkodima) [reply activesupport/lib/active_support/core_ext/enumerable.rb:217]: This causes object allocation (`Object.new`), which is the same. Can be extracted into a constant of course, but I would prefer simplicity over complexity in not performance critical code.

File: activesupport/lib/active_support/core_ext/range/sole.rb [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+class Range
+  # Returns the sole item in the range. If there are no items, or more
+  # than one item, raises Enumerable::SoleItemExpectedError.
+  #
+  #   (1..1).sole   # => 1
+  #   (2..1).sole   # => Enumerable::SoleItemExpectedError: no item found
+  #   (..1).sole    # => Enumerable::SoleItemExpectedError: infinite range cannot represent a sole item
+  def sole
+    if self.begin.nil? || self.end.nil?
+      raise ActiveSupport::EnumerableCoreExt::SoleItemExpectedError, "infinite range cannot represent a sole item"
```
Comment (byroot) [inline activesupport/lib/active_support/core_ext/range/sole.rb:12]: Perhaps the error message should include `inspect`?

File: activesupport/lib/active_support/core_ext/enumerable.rb (hunk 3 above)
Comment (byroot) [reply activesupport/lib/active_support/core_ext/enumerable.rb:217]: The solution proposed at the end of https://github.com/rails/rails/issues/54335#issue-2807665461 doesn't allocate and is relatively simple too, but up to you.

**Review by byroot — APPROVED** [review]

**Comment by olivier-thatch** [comment]
👋  I don't know if this was expected or not, but this PR introduced a behavior change if the element is a tuple.

Before:
```ruby
Rails::VERSION::STRING
# => "8.0.2.1"

enum = Enumerator.new(1) do |yielder|
  yielder.yield(1, "one")
end

enum.first
# => [1, "one"]

enum.rewind

enum.sole
# => [1, "one"]
```

After:
```ruby
Rails::VERSION::STRING
# => "8.0.3"

enum = Enumerator.new(1) do |yielder|
  yielder.yield(1, "one")
end

enum.first
# => [1, "one"]

enum.rewind

enum.sole
# => 1
```

IMO `each do |element|` should be replaced with `each do |*element|` to ensure the full tuple is returned.
