### PR TITLE
Make ActiveStorage::Blob keys lowercase

### LINKED ISSUE #34804: Case sensitivity of Activestorage keys creates undefined behavior
### Steps to reproduce

Create a Rails project with a SQLite database, and create two Blob objects with keys having different capitalisation but same character content. The UNIQUE index constraint will not trigger as SQLite3 has byte-equal UNIQUE constraints. I.e. it is possible to create two ActiveStorage blobs with differently-capitalised keys which will refer to the same object if the backing storage driver is case-insensitive - with possible data loss as a result.

### On SQLite3

Duplicate an existing blob row and change the capitalisation on the key. The database will allow you to proceed and alter the key value. The index is case-sensitive

### On MySQL

Set up the same project with MySQL with the default collation (`utf8_general_ci` or `utf8_mb4_general_ci`)   and verify the collation is indeed case-insensitive:

```
SELECT TABLE_SCHEMA , TABLE_NAME , TABLE_COLLATION FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME ='active_storage_blobs';
```

Edit one of the existing `active_storage_blobs` rows to contain the same `key` value as some other row, but with different capitalisation. The database will refuse to alter the row as a conflict will (correctly) be detected.

Since the checksum and other metadata is only verified on upload/save to storage, here are the conditions which can arise:

* On macOS with the `disk` storage, files with differently-capitalised keys get put into the same directory and can not be found if the storage directory is reused on a case-sensitive filesystem (see #33864). The first partitioning directory that has been created wins and will contain files made for different capitalisation
* On macOS with the `disk` storage, files with differently capitalised keys can (and will) overwrite each other if the database index is case sensitive (as it is on SQLite) 
* With SQLite there is no protection from differently-cased ActiveStorage keys being generated in the same table

IMO this is a bug that can create data loss (blobs may get overwritten). Especially if macOS is used as the originating system where data hydration is being performed

### Expected behavior

At least ActiveStorage drivers take case-sensitivity into account (for example S3 is documented case-sensitive, whereas disk storage will be used on macOS and will therefore most likely is going to be used with a case-sensitive filesystem . If case-sensitivity is important there should be a guarantee that binary identity is used at the database level so that no two Blobs with a `key` with similar capitalization can be created, ever, regardless of the storage driver used. Guarantees on case sensitivity should at least be documented, and ActiveStorage should protect the user from overwriting data. 

### Actual behavior

Bugs like #33864 where, for instance, a storage directory ported from a case-insensitive-but-case-preserving filesystem to a case-sensitive-case-preserving file system leads to ActiveStorage being unable to load blobs for download, preview or processing. The `storage` directory, once set up on Linux, can't be synced to the dominantly used macOS filesystems without data loss - and the ability is important for debugging issues on running websites locally. Capitalisation of the directories used for disk storage driver partitioning on macOS is incorrect as the directory partitions get reused regardless of capitalisation.

### System configuration
**Rails version**: activestorage (5.2.2)
**Ruby version**: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]` and `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-musl]` 

### Suggested change

I actually don't know how far reaching of a consequence this has. For example, to combat this only in the `disk` storage driver a hashing algorithm needs to be applied over the `key` before generating the path to the actual object, or the representation of the key should be converted to a lowercase alphabet - to have the same amount of entropy but a smaller alphabet for filenames. Another option is switching ActiveStorage keys to base36 instead of base58 and raising the key length to compensate.

### PR DESCRIPTION
**Pull request by julik**
### Summary

When used with case-insensitive filesystems ActiveStorage blobs might cause non-portable Disk storage directories to be created, and the UNIQUE index that gets configured on the `active_storage_blobs` table is database-dependent in terms of case-sensitivity. If the database index is case-sensitive, but the underlying filesystem is not, blobs might be overwritten and the available key space for uploaded blobs shrinks drastically. This does happen on macOS filesystems already.

This patch changes the ActiveStorage key generation from mixed-case base-58 to lowercase base-36, and increases the key size from 24 bytes to 28. When using base58 there are `58**24` possible key values, and to have the same or more possible keys with base36 we need to have `36**28`, increasing the storage requirement for the key by 4 bytes. Since the database migrations for the blobs table are not CHAR()-size-restricted (and the fix worked for me both on SQLite and MySQL) I believe this is a reasonable compromise.

Note that this will not alter the storage keys that have already been generated, their treatment wills tay unchanged. Neither will it correct the storage directory structures that were created using mixed-case keys on macOS since you need to "rekey" the stored objects if you want the storage directory to be portable to a case-sensitive filesystem.

Closes #34804 , addresses the underlying issue in #33864 for freshly-generated uploaded blobs. Unfortunately it cannot be excluded that for some people some blobs already did get overwritten if SQLite was used in combination with a case-insensitive filesystem and the Disk storage service. Neither does this change existing blob keys.

This change does have an implication that for existing S3 buckets and for other services that potentially use "naive partitioning" (first N  bytes of the given object store key) partition usage is going to become less "fair". However, AWS recently dropped the recommendation on manual key distribution for the key prefix (https://www.infoq.com/news/2018/10/amazon-s3-performance-increase) as it seems they have adopted hashing for the keys the user provides, so this would not be a problem for buckets that get created.

The advantages of using a lowercase-only key:

* Less potential issues with collation-sensitive database indices
* Removes issues with potentially case-insensitive blob stores
* Makes it easier to download blobs from a remote store to a case-insensitive filesystem for debugging

### CODE REVIEW

File: activestorage/test/models/blob_test.rb [hunk 1]
```diff
@@ -47,6 +47,16 @@ class ActiveStorage::BlobTest < ActiveSupport::TestCase
...
 
+  test "create after upload only assigns lowercase keys with 28 bytes of data" do
+    blobs = 20.times.map do
+      create_blob data: Random.new.bytes(20), filename: "rand.bin", content_type: "binary/octet-stream", identify: false
+    end
+    keys = blobs.map(&:key)
+    keys.each do |key|
+      assert_match /^[a-z0-9]{28}$/, key
+    end
+  end
```
Comment (georgeclaghorn) [inline activestorage/test/models/blob_test.rb]: We can check a single blob’s key and lean on `create_blob`’s defaults:

```ruby
test "create after upload generates a 28-character base36 key" do
  assert_match(/^[a-z0-9]{28}$/, create_blob.key)
end
```

**Review by georgeclaghorn — CHANGES_REQUESTED** [review]

**Review by sikachu — CHANGES_REQUESTED** [review]
Sorry, but I think `base58.downcase` is not really the right way to fix this.

The reason is that by generating base58 string, we could ended up with `Aaaaa...` and `aaaaa...` which when downcase will cause a key collision.

If we want to make it case insensitive, that means we have to throw away all lowercase or all uppercase characters altogether, which means we need to switch to something else. I was looking around and seems like maybe we can implement [`Base32` then downcase, or `z-base-32`](https://en.wikipedia.org/wiki/Base32) instead.

I'll let @georgeclaghorn decide what we should do next, but `base58.downcase` is definitely not what we're looking for for sure.

**Comment by julik** [comment]
@sikachu @georgeclaghorn thank you for your comments. `base58(k).downcase` is a cheap solution indeed, because otherwise I would have to add a base36 implementation to SecureRandom which would increase the API surface there (while not reused anywhere else). I can copy-paste the implementation for `base58` with base36 into the Blob class proper if that will be the preference.

@sikachu as it stands now ActiveStorage::Blob keys are not immune to collisions and this is actually a severe issue, see #34805 - but I do get your point that we should probably use the entropy source better.

**Comment by julik** [comment]
Why would you want the key to be base64 and/or base32 conformant? It does not give you extra guarantees of uniqueness or the like, but it does force you to do bookkeeping to have N-complement key lengths (28 is 4-complement) and creates those `=`s. Base58  does omit chars that look similar ("lowercase-L versus 1" etc) but I don't know if this has value when you are dealing with a "bag of keys" situation at all.

**Comment by sikachu** [comment]
Ah, I agree with you that this is a bag of key situation and hence it does not really matter. I just thought that base32 is closest to what we want to archive (single-case alphabets and numeric) and is one of the standard so adding this to the core would have a high probability of it being reused, despite this is its first usage.

I think I'm going to have to ask @georgeclaghorn if "omitting the similar looking characters" is one of the feature we want or is it just that base58 is already available so we just use it. If it doesn't matter, then maybe base36 will be fine, otherwise I think base32 will be a great addition to the core as well.

**Comment by georgeclaghorn** [comment]
Base36 sounds fine to me, but the implementation as it stands now needs to move to [the SecureRandom extension](https://github.com/rails/rails/blob/a796b993ad3717f9a0b3d5be070311ab7a0c95ba/activesupport/lib/active_support/core_ext/securerandom.rb), where it can live alongside `SecureRandom.base58`.

File: activesupport/lib/active_support/core_ext/securerandom.rb [hunk 2]
```diff
@@ -22,4 +24,24 @@ def self.base58(n = 16)
...
+  #
+  # If _n_ is not specified or is +nil+, 16 is assumed. It may be larger in the future.
+  # This method can be used over +base58+ if a deterministic case key is necessary.
+  #
+  # The result may contain alphanumeric characters in lowercase
+  #
+  #   p SecureRandom.base36 # => "4kugl2pdqmscqtje"
+  #   p SecureRandom.base36(24) # => "77tmhrhjfvfdwodq8w7ev2m7"
+  #
+  def self.base36_lowercase(n = 16)
```
Comment (georgeclaghorn) [inline activesupport/lib/active_support/core_ext/securerandom.rb]: Let’s just call this `base36`. It’s enough to document that it returns a lowercase string (as you already have).

File: activesupport/lib/active_support/core_ext/securerandom.rb [hunk 3]
```diff
@@ -22,4 +24,24 @@ def self.base58(n = 16)
...
+  # The argument _n_ specifies the length, of the random string to be generated.
+  #
+  # If _n_ is not specified or is +nil+, 16 is assumed. It may be larger in the future.
+  # This method can be used over +base58+ if a deterministic case key is necessary.
+  #
+  # The result may contain alphanumeric characters in lowercase
+  #
+  #   p SecureRandom.base36 # => "4kugl2pdqmscqtje"
+  #   p SecureRandom.base36(24) # => "77tmhrhjfvfdwodq8w7ev2m7"
+  #
```
Comment (georgeclaghorn) [inline activesupport/lib/active_support/core_ext/securerandom.rb]: :scissors: this empty line.

File: activesupport/test/core_ext/secure_random_test.rb [hunk 4]
```diff
@@ -19,4 +19,25 @@ def test_base58_with_length
...
+  def test_base36_with_length
+    s1 = SecureRandom.base36_lowercase(24)
+    s2 = SecureRandom.base36_lowercase(24)
+
+    assert_not_equal s1, s2
+    assert_equal 24, s1.length
+    assert_match /^[a-z0-9]+$/, s1
+    assert_match /^[a-z0-9]+$/, s2
+  end
+
```
Comment (georgeclaghorn) [inline activesupport/test/core_ext/secure_random_test.rb]: :scissors:

File: activesupport/lib/active_support/core_ext/securerandom.rb [hunk 5]
```diff
@@ -22,4 +24,24 @@ def self.base58(n = 16)
       BASE58_ALPHABET[idx]
     end.join
   end
+
+  # SecureRandom.base36 generates a random base36 string in lowercase.
+  #
+  # The argument _n_ specifies the length, of the random string to be generated.
```
Comment (georgeclaghorn) [inline activesupport/lib/active_support/core_ext/securerandom.rb]: I know this came from the `base58` docs, but the comma after “length” is unnecessary. Can you remove it here and above?

File: activesupport/lib/active_support/core_ext/securerandom.rb [hunk 6]
```diff
@@ -22,4 +24,24 @@ def self.base58(n = 16)
...
+  #
+  # If _n_ is not specified or is +nil+, 16 is assumed. It may be larger in the future.
+  # This method can be used over +base58+ if a deterministic case key is necessary.
+  #
+  # The result may contain alphanumeric characters in lowercase
```
Comment (georgeclaghorn) [inline activesupport/lib/active_support/core_ext/securerandom.rb]: The result *will* contain lowercase alphanumeric characters. :wink:

Please add a period to the end of this sentence.

**Review by georgeclaghorn — CHANGES_REQUESTED** [review]

File: activestorage/app/models/active_storage/blob.rb [hunk 7]
```diff
@@ -16,6 +16,8 @@
 # update a blob's metadata on a subsequent pass, but you should not update the key or change the uploaded file.
 # If you need to create a derivative or otherwise change the blob, simply create a new blob and purge the old one.
 class ActiveStorage::Blob < ActiveRecord::Base
+  BASE36_ALPHABET = ("a".."z").to_a + ("0".."9").to_a
```
Comment (georgeclaghorn) [inline activestorage/app/models/active_storage/blob.rb]: This constant is no longer used.

**Review by georgeclaghorn — APPROVED** [review]

**Comment by julik** [comment]
🎉 please squash-merge since there are quite a few interim commits

**Comment by georgeclaghorn** [comment]
Thank you! :heart:

File: activesupport/lib/active_support/core_ext/securerandom.rb [hunk 8]
```diff
@@ -4,22 +4,42 @@
...
+  # If _n_ is not specified or is +nil+, 16 is assumed. It may be larger in the future.
+  # This method can be used over +base58+ if a deterministic case key is necessary.
+  #
+  # The result will contain alphanumeric characters in lowercase.
+  #
+  #   p SecureRandom.base36 # => "4kugl2pdqmscqtje"
+  #   p SecureRandom.base36(24) # => "77tmhrhjfvfdwodq8w7ev2m7"
+  def self.base36(n = 16)
+    SecureRandom.random_bytes(n).unpack("C*").map do |byte|
+      idx = byte % 64
```
[the remark this answers is not in the document]
Comment (julik) [reply activesupport/lib/active_support/core_ext/securerandom.rb]: Might be, I would actually rewrite both base58 and base36 to use a much more pedestrian

```
n.times.map { alphabet[SecureRandom.random_number(alphabet.length) }.join
```

More method calls but probably "less clever" is better in this case. I didn't touch the implementation because I was thinking "this byte trickery for obtaining bytes from a potentially-slow SecureRandom is here for a reason"

[the remark this answers is not in the document]
Comment (julik) [reply activesupport/lib/active_support/core_ext/securerandom.rb]: Just didn't want to touch it since this is not what the PR is about and this would need microbenchmarks etc.

[the remark this answers is not in the document]
Comment (julik) [reply activesupport/lib/active_support/core_ext/securerandom.rb]: Noted, I'll open a patch for this once I'm done with #34827
