### PR TITLE
[Fix #51129] Fix issue with IDs reader on preloaded associations for composite primary keys

### LINKED ISSUE #51129: Array primary keys (e.g. composite) break `collection_singular_ids` method when using preload
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  self.primary_key = [:id]
  has_many :comments
end

class Comment < ActiveRecord::Base
  self.primary_key = [:id]
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments.create!

    assert_equal 1, post.comments.count
    assert_equal 1, Comment.count
    assert_equal post.id, Comment.take.post.id

    assert_equal Comment.ids, Post.take.comment_ids
    assert_equal Comment.ids, Post.preload(:comments).take.comment_ids
  end
end
```

### Expected behavior

`collection_singular_ids` should work the same when preloading or not.

### Actual behavior

Preloaded associations' `collection_singular_ids` returns an array of `nil` values when association was preloaded.

### Analysis

The problem lies in different handling of array arguments to `Enumerable#pluck` and `ActiveRecord::Relation#pluck`:

```ruby
      def ids_reader
        if loaded?
          target.pluck(reflection.association_primary_key) # -> Enumerable#pluck
        elsif !target.empty?
          load_target.pluck(reflection.association_primary_key) # -> Enumerable#pluck
        else
          @association_ids ||= scope.pluck(reflection.association_primary_key) # -> ActiveRecord::Relation#pluck
        end
      end
```

`ActiveRecord::Relation#pluck` efectively flattens its arguments in `#arel_columns` call, whereas `Enumerable#pluck` uses them as is.

Incidentally, arguments flattening results in column names not being processed with `#arel_column`.

### System configuration

**Rails version**: 7.1

**Ruby version**: 3.3.0

### PR DESCRIPTION
**Pull request by Jay0921**
### Motivation / Background

Fixes https://github.com/rails/rails/issues/51129.

### Detail

When using composite primary keys in a model, the `primary_key` will be an array. This raises an issue when calling the `<association>_ids` method on a preloaded association. Internally, Rails uses the `pluck` method from Enumerable to retrieve the preloaded results. However, the `pluck` method does not accept an array as its argument. To accommodate that, we need to use the splat operator to split the array into multiple arguments dynamically.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/lib/active_record/associations/collection_association.rb [hunk 1]
```diff
@@ -48,9 +48,9 @@ def writer(records)
       # Implements the ids reader method, e.g. foo.item_ids for Foo.has_many :items
       def ids_reader
         if loaded?
-          target.pluck(reflection.association_primary_key)
+          target.pluck(*reflection.association_primary_key)
         elsif !target.empty?
-          load_target.pluck(reflection.association_primary_key)
+          load_target.pluck(*reflection.association_primary_key)
         else
           @association_ids ||= scope.pluck(reflection.association_primary_key)
```
Comment (Slotos) [inline activerecord/lib/active_record/associations/collection_association.rb:55]: I believe this should also use splat operator. Not doing so result in primary keys not getting wrapped into an arel attribute node, which could lead to differences in behaviour in complex scenarios.

Specifically, in `ActiveRecord::Calculations#pluck`, the argument gets passed to `ActiveRecord::QueryMethods#arel_columns`, which doesn't have a case for processing array argument, and simply returns it as is. Meaning that `scope.pluck(:id, :tenant_id)` and `scope.pluck([:id, :tenant_id])` are subtly different.

Low level difference:
```ruby
> User.all.__send__(:arel_columns, [:id, :tenant_id])
=> 
[#<struct Arel::Attributes::Attribute
  relation=
   #<Arel::Table:0x0000000122b14f18
    @klass=User(id: uuid, email: string, password_digest: string, client: boolean, active: boolean, created_at: datetime, updated_at: datetime, practise_id: uuid, full_name: string),
    @name="users",
    @table_alias=nil,
    @type_caster=
     #<ActiveRecord::TypeCaster::Map:0x0000000122ef9a48
      @klass=User(id: uuid, email: string, password_digest: string, client: boolean, active: boolean, created_at: datetime, updated_at: datetime, practise_id: uuid, full_name: string)>>,
  name="id">,
 "\"tenant_id\""]


> User.all.__send__(:arel_columns, [[:id, :tenant_id]])
=> [:id, :tenant_id]
```

I couln't devise a scenario where this actually breaks things, but by adding a splat operator here, array and singular primary keys get handled the same way, lowering the likelyhood of bugs down the line.

**Review by Slotos — COMMENTED** [review]
Thank you so much for tackling this.

File: activerecord/lib/active_record/associations/collection_association.rb (hunk 1 above)
Comment (Jay0921) [reply activerecord/lib/active_record/associations/collection_association.rb:55]: @Slotos After diving into the code, I found that using `pluck(:id, :post_id)` and `pluck([:id, :post_id])` will produce the same results. The arguments that passed to `pluck` method will go through the `arel_columns` method twice.

The first call occurs when we try to extract the value and assign it to selected_values.
https://github.com/rails/rails/blob/23af6f37a310e16916ca788837f4a7accb2cebad/activerecord/lib/active_record/relation/calculations.rb#L306-L308

The second call occurs during the construction of the select query, where we call the `arel_columns` method again on `selected_values`, even though we had already done so once and assigned the value to `selected_values`.
https://github.com/rails/rails/blob/23af6f37a310e16916ca788837f4a7accb2cebad/activerecord/lib/active_record/relation/query_methods.rb#L1802-L1810

---

When using  `pluck(:id, :post_id)`:
The first call goes to this block and generates some Arel objects and assign to `selected_values`
https://github.com/rails/rails/blob/23af6f37a310e16916ca788837f4a7accb2cebad/activerecord/lib/active_record/relation/query_methods.rb#L1849-L1852
`selected_values` is an array of Arel objects. When we call `arel_columns` for the second time, we hit the `else` block and return the values as they are
https://github.com/rails/rails/blob/23af6f37a310e16916ca788837f4a7accb2cebad/activerecord/lib/active_record/relation/query_methods.rb#L1857-L1859

However, the process is entirely different when using `pluck([:id, :post_id])`. In this case, the first call passes through the `else` block because the argument is an array. The second call, however, matches the `Symbol` case, thus generating the Arel objects.

Comment (Jay0921) [reply activerecord/lib/active_record/associations/collection_association.rb:55]: The second call on `arel_columns` seems unnecessary. The issue is related to how `flat_map` is used inside the [arel_columns](https://github.com/rails/rails/blob/23af6f37a310e16916ca788837f4a7accb2cebad/activerecord/lib/active_record/relation/query_methods.rb#L1846C11-L1861) method.

At first glance, it might seem that `[[:name, :age]].flat_map { |field| field }` and `[:name, :age].flat_map { |field| field }` behave the same since they produce the same output. However,the underlying process reveals a critical difference, particularly in this case. The main difference is the value of `class` in both cases

```
[:id, :post_id].flat_map { |field| field.class }
# Outputs: [Symbol, Symbol]
[[:id, :post_id]].flat_map { |field| field.class }
# Outputs: [Array]
```

Changing the code as shown below will eliminate the need for the second call. However, I'm not sure about the rationale behind using `flat_map`. Nonetheless, I think this issue deserves a PR on its own. I will investigate further and open one if necessary.
```
[:id, :post_id].flatten.map { |field| field.class }
# Outputs: [Symbol, Symbol]
[[:id, :post_id]].flatten.map { |field| field.class }
# Outputs: [Symbol, Symbol]
```

File: activerecord/lib/active_record/associations/collection_association.rb [hunk 2]
```diff
@@ -48,11 +48,11 @@ def writer(records)
...
       def ids_reader
         if loaded?
-          target.pluck(reflection.association_primary_key)
+          target.pluck(*reflection.association_primary_key)
         elsif !target.empty?
-          load_target.pluck(reflection.association_primary_key)
+          load_target.pluck(*reflection.association_primary_key)
         else
-          @association_ids ||= scope.pluck(reflection.association_primary_key)
+          @association_ids ||= scope.pluck(*reflection.association_primary_key)
```
Comment (Jay0921) [inline activerecord/lib/active_record/associations/collection_association.rb:55]: The doc show pluck with multiple arguments like `(:id, :name)`, but `([:id, :name])` also works. To align with docs, we should use add the splat operator here. 

https://github.com/rails/rails/blob/23af6f37a310e16916ca788837f4a7accb2cebad/activerecord/lib/active_record/relation/calculations.rb#L266

**Review by nvasilevski — APPROVED** [review]
Let's squash commits so when someone from the core team gives a review they can merge immediately if all looks good

**Comment by eileencodes** [comment]
Thanks!

Backported to 7-2-stable in 5f7935dc1ae9a737bbab2575505404c6f2705089 and 7-1-stable in 2604adbc79824640c5380d53ea7dc8ec20897676
