### PR TITLE
Fix non_numeric_string?

### LINKED ISSUE #33801: attribute_changed? returns true when assigning a float to a BigDecimal
### Steps to reproduce

```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.1.4"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :prices, force: true do |t|
    t.decimal :amount, precision: 63, scale: 30
  end
end

class Price < ActiveRecord::Base

end

class BugTest < Minitest::Test
  def test_big_decimal_change
    amount = 0.00005
    price = Price.create!(amount: amount)
    price.amount = amount
    assert_equal false, price.attribute_changed?(:amount)
  end

  def test_previous_value_and_new_value
    amount = 0.00005
    price = Price.create!(amount: amount)
    price.amount = amount
    previous_value, new_value = price.changes[:amount]
    refute_equal previous_value, new_value
  end
end
```

Result of running this:

```
  1) Failure:
BugTest#test_big_decimal_change [test.rb:46]:
Expected: false
  Actual: true

  2) Failure:
BugTest#test_previous_value_and_new_value [test.rb:54]:
Expected 0.5e-4 to not be equal to 0.5e-4.
```

### Expected behavior
attribute_changed?(:amount) should return false.

### Actual behavior
attribute_changed?(:amount) returns true despite previous value and new_value are the same.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.1

### PR DESCRIPTION
**Pull request by yskkin**
For example, dirty checking was not right for the following case:

```
model.int_column = "+5"
model.float_column = "0.5E+1"
model.decimal_column = "0.5e-3"
```

Fixes #33801

### CODE REVIEW

File: activemodel/lib/active_model/type/helpers/numeric.rb [hunk 1]
```diff
@@ -29,7 +29,7 @@ def non_numeric_string?(value)
             # 'wibble'.to_i will give zero, we want to make sure
             # that we aren't marking int zero to string zero as
             # changed.
-            value.to_s !~ /\A-?\d+\.?\d*\z/
+            value.to_s !~ /\A[-+]?\d+\.?\d*([eE][-+]\d+)?\z/
```
Comment (kamipo) [inline activemodel/lib/active_model/type/helpers/numeric.rb]: Can you use `match?` to avoid creating unused match object and unused captures?

```diff
diff --git a/activemodel/lib/active_model/type/helpers/numeric.rb b/activemodel/lib/active_model/type/helpers/numeric.rb
index 16e14f9e5f..c9519dc908 100644
--- a/activemodel/lib/active_model/type/helpers/numeric.rb
+++ b/activemodel/lib/active_model/type/helpers/numeric.rb
@@ -29,7 +29,7 @@ def non_numeric_string?(value)
             # 'wibble'.to_i will give zero, we want to make sure
             # that we aren't marking int zero to string zero as
             # changed.
-            value.to_s !~ /\A-?\d+\.?\d*\z/
+            !/\A[-+]?\d+\.?\d*(?:[eE][-+]\d+)?\z/.match?(value.to_s)
           end
       end
     end
```

Comment (yskkin) [reply activemodel/lib/active_model/type/helpers/numeric.rb]: Thank you @kamipo.
I found `5e2` is also valid expression, so I'll change regex to `/\A[-+]?\d+\.?\d*(?:[eE][-+]?\d+)?\z/`

I also found "E-notataion" is valid for `to_d` and `to_f` but not `to_i`:

```
irb(main):001:0> require 'bigdecimal'
=> true
irb(main):002:0> require 'bigdecimal/util'
=> true
irb(main):003:0> '5e+2'.to_d
=> 0.5e3
irb(main):004:0> '5e+2'.to_f
=> 500.0
irb(main):005:0> '5e+2'.to_i
=> 5
```

Should I overwrite this method for `AM::Type::Integer`?

File: activemodel/test/cases/type/decimal_test.rb [hunk 2]
```diff
@@ -60,6 +60,7 @@ def test_changed?
         assert type.changed?(5.0, 5.0, "5.0wibble")
```
Comment (yskkin) [inline activemodel/test/cases/type/decimal_test.rb]: Now I come to think this test is not appropriate.
`model.int_column = "5.0wibble"` and `"5.0wibble".to_i` both result in `5`.

We may not need `\z` in regex.

**Comment by yskkin** [comment]
To avoid invalid numeric expression like `'wibble'` to be type-casted to `0` as commet says,
It is enough to see leading character is digit.

I updated PR based on this.

File: activemodel/test/cases/type/float_test.rb [hunk 3]
```diff
@@ -21,9 +21,10 @@ def test_type_cast_float_from_invalid_string
       def test_changing_float
         type = Type::Float.new
 
-        assert type.changed?(5.0, 5.0, "5wibble")
```
Comment (rafaelfranca) [inline activemodel/test/cases/type/float_test.rb]: Can we add a test to make sure `changed?` returns true?

Comment (yskkin) [reply activemodel/test/cases/type/float_test.rb]: I think `changed?` should return false for this case.

This test succeeds for current master:
```
  def test_float_change
    price = Price.create!(float_col: "5wibble")
    assert_equal 5.0, price.float_col
  end
```

Am I missing something?

Comment (yskkin) [reply activemodel/test/cases/type/float_test.rb]: I see. I'll update PR tomorrow.

File: activemodel/test/cases/type/float_test.rb [hunk 4]
```diff
@@ -21,9 +21,11 @@ def test_type_cast_float_from_invalid_string
...
+        assert type.changed?(5.0, 0, "wibble")
```
Comment (kamipo) [inline activemodel/test/cases/type/float_test.rb]: Can you add `assert type.changed?(0, 0, "wibble")` too?
Since `type.changed?` always returns true if differ `old_value` and `new_value` regardless of the result of `non_numeric_string?`.

**Comment by yskkin** [comment]
@kamipo done. Do you have any other concerns?

**Comment by kamipo** [comment]
Thanks!

**Comment by yskkin** [comment]
I think this should be backported.

**Comment by kamipo** [comment]
Backported in b433433d93b1f6579b7000a50b1a1460925f7b2d.
