### PR TITLE
Fix AC::Parameters#to_unsafe_h to return all unfiltered values

### LINKED ISSUE #22841: AC::Parameters#to_unsafe_h does not deep dup
```ruby
foo = ActionController::Parameters.new("f"=>{"language_facet"=>["Tibetan"]})
{"f"=>{"language_facet"=>["Tibetan"]}}
foo['f'].class
ActionController::Parameters
foo.to_unsafe_h
{"f"=>{}}
```

I would think you'd get back `{'"f"=>{"language_facet"=>["Tibetan"]}}`, right?

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
- AC::Parameters#convert_parameters_to_hashes should return filtered or
  unfiltered values based on whether it is called from `to_h` or `to_unsafe_h`
  instead of always defaulting to `to_h`.
- Fixes #22841

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
cc @jcoyne

**Comment by jcoyne** [comment]
:+1: Thanks @prathamesh-sonpatki! :smile_cat:

File: actionpack/test/controller/parameters/parameters_permit_test.rb [hunk 1]
```diff
@@ -298,6 +298,13 @@ def assert_filtered_out(params, key)
     assert_not @params.to_h.is_a? ActionController::Parameters
   end
 
+  test "to_unsafe_h returns unfiltered params even after accessing few keys" do
+    foo = ActionController::Parameters.new("f"=>{"language_facet"=>["Tibetan"]})
```
Comment (kaspth) [inline actionpack/test/controller/parameters/parameters_permit_test.rb]: Rename foo to params

File: actionpack/test/controller/parameters/parameters_permit_test.rb [hunk 2]
```diff
@@ -298,6 +298,13 @@ def assert_filtered_out(params, key)
...
+    assert_equal ActionController::Parameters, foo['f'].class
```
Comment (kaspth) [inline actionpack/test/controller/parameters/parameters_permit_test.rb]: Use asset with is_a? Like the other tests and move below to keep assertions.

Comment (kaspth) [inline actionpack/test/controller/parameters/parameters_permit_test.rb]: Then add a newline between the assertions and the setup for good measure.

File: actionpack/lib/action_controller/metal/strong_parameters.rb [hunk 3]
```diff
@@ -595,16 +595,20 @@ def new_instance_with_inherited_permitted_status(hash)
         end
       end
 
-      def convert_parameters_to_hashes(value)
+      def convert_parameters_to_hashes(value, allow_unsafe:)
```
Comment (kaspth) [inline actionpack/lib/action_controller/metal/strong_parameters.rb]: Would probably change to a regular arg called `using` that was just the method to send.

**Comment by prathamesh-sonpatki** [comment]
@kaspth Thanks for review. Took care of comments.

**Comment by kaspth** [comment]
Awesome work ❤️

**Comment by prathamesh-sonpatki** [comment]
Thanks :)
