### PR TITLE
Fix `request.ssl?` bug with Action Cable

### LINKED ISSUE #23620: ActionCable in app conflicts with force_ssl
If running actioncable in app when the app is configured with force_ssl = true the SSL middleware 301s the wss requests to https which prevents the web socket communications from connecting

### PR DESCRIPTION
**Pull request by maclover7**
This bug affects `wss://` requests when running Action Cable in-app.
Fixes #23620.

### CODE REVIEW

File: actionpack/lib/action_dispatch/http/request.rb [hunk 1]
```diff
@@ -403,10 +403,18 @@ def logger
...
+    end
+
     private
       def check_method(name)
         HTTP_METHOD_LOOKUP[name] || raise(ActionController::UnknownHttpMethod, "#{name}, accepted HTTP methods are #{HTTP_METHODS[0...-1].join(', ')}, and #{HTTP_METHODS[-1]}")
         name
       end
+
+      def secure_websocket_request?
+        get_header('Upgrade') && get_header('Upgrade').downcase == 'websocket' && get_header('rack.url_scheme') == 'wss'
```
Comment (matthewd) [inline actionpack/lib/action_dispatch/http/request.rb]: Isn't it strictly true that `wss` is secure (i.e., `ssl? == true`), regardless of whether we're doing an upgrade?

Comment (maclover7) [inline actionpack/lib/action_dispatch/http/request.rb]: I'm doing a double check to make sure that we have `wss` and also that the incoming request is a WebSocket request

**Comment by matthewd** [comment]
Per https://github.com/rails/rails/issues/23620#issuecomment-187530277, it's possible to get `wss` here without trying particularly hard / doing anything obviously unwise. It might ultimately be Rack's bug to fix, but for now, we can do the minimum necessary to avoid misbehaviour.
