### PR TITLE
Fix multiple database support for DATABASE_URL env variable

### LINKED ISSUE #36736: Rails RC2 regression in multiple datbases
This commit https://github.com/rails/rails/commit/f2ad69fe7a605b01bb7c37eeac6a9b4e7deb488e inlcuded in Rails RC2 caused a regression in case where multiple database are used and `DATABASE_URL` environment variable is set.

Reproduction of the bug is here https://github.com/morgoth/mdbug (details in commit https://github.com/morgoth/mdbug/commit/048db246bf2ec5d30bf141ac17dc68c699730514) and can be seen by running `DATABASE_URL="sqlite3:db/development.sqlite3" bin/rails r "Dog.count"` which throws an error:
```
The `animals` database is not configured for the `development` environment. (ActiveRecord::AdapterNotSpecified)

Available databases configurations are:

default
development
test
```

When running `bin/rails r "Dog.count"` all is working fine.
It doesn't matter if `DATABASE_URL` env is used in the config file or not, it's only the fact that is set as env variable.

/cc @eileencodes

### PR DESCRIPTION
**Pull request by seejohnrun**
### Summary

This PR fixes an issue where multi-database configurations were incompatible with setting a `DATABASE_URL` environment variable.  We had been using `config["database"] || config["adapter"] || ENV["DATABASE_URL"]` to determine if a multi-tier config was in place, which made the assumption that if `DATABASE_URL` was present, we were in a single-database configuration.

As part of this work, this PR also includes a light refactor to make both multi and single database configurations lead into the same code path so they behave the same.

### Other information

As mentioned in #36736, this regression was introduced as part of f2ad69fe7a605b01bb7c37eeac6a9b4e7deb488e

Thank you for the great bug report and reproduction!

---

Closes #36736

/cc @morgoth @eileencodes

### CODE REVIEW

**Comment by eileencodes** [comment]
Thanks @seejohnrun! 

Backported this to 6-0-stable 😄

File: activerecord/lib/active_record/database_configurations.rb [hunk 1]
```diff
@@ -104,18 +104,28 @@ def build_configs(configs)
         return configs.configurations if configs.is_a?(DatabaseConfigurations)
         return configs if configs.is_a?(Array)
 
-        build_db_config = configs.each_pair.flat_map do |env_name, config|
-          walk_configs(env_name.to_s, "primary", config)
-        end.flatten.compact
+        db_configs = configs.flat_map do |env_name, config|
+          if config.is_a?(Hash) && config.all? { |k, v| v.is_a?(Hash) }
```
Comment (eileencodes) [inline activerecord/lib/active_record/database_configurations.rb]: Minor but tomorrow when we pair on this let's make sure to underscore the `k` since it's not used.

**Comment by JamesDullaghan** [comment]
One thing that was noticed while trying to run ruby.ci with mutliple db setup with a read/write setup is when running `rake db:schema:load` a limited version of the configs are returned which is remedied with `include_hidden` or `include_replicas` (which as I've read will be deprecated).

I'm curious why these options haven't been included in the `database_tasks.rb` and if there's a reason for not including them? It seems ruby.ci is running the `schema:load` task and not sure if the deprecated `current_config` method is called or the `load_schema_current` method is called which calls `each_current_configuration`, but it looks like neither are passing the full options (`include_hidden`, `include_replicas` or `database_tasks`)

Let me know if there's anything that's missing, otherwise I'd love to take a stab at implementing this.
