### PR TITLE
Fix `RedisCacheStore#write_multi` with `:expires_in`

### LINKED ISSUE #49973: Using redis_cache_store, Rails.cache.write_multi does not set TTL correctly
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "redis"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_redis_ttl

    redis = Redis.new
    cs = ActiveSupport::Cache.lookup_store(:redis_cache_store)
    cs.write('foo1', 'bar', expires_in: 10)
    cs.write_multi({ 'foo2' => 'bar' }, expires_in: 11)

    assert redis.ttl('foo1') != -1
    assert redis.ttl('foo2') != -1
  end
end
```

### Expected behavior

When using `Rails.cache.write_multi` with `expires_in`, the TTL of the keys should be set, just like `Rails.cache.write`.

### Actual behavior

No TTL is set (`redis.ttl key` returns -1).

### System configuration
**Rails version**: `main`, `7-0-stable`, `7-1-stable`

**Ruby version**: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin21]

**redis**: 6.2.8

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #49973.

This options were extracted as keyword arguments and not used then.

### CODE REVIEW

**Comment by fatkodima** [comment]
Wdyt about enabling a relevant rubocop's cop for this in a follow up PR - https://docs.rubocop.org/rubocop/1.57/cops_lint.html#lintunusedmethodargument ? With it, this bug would be detected earlier.

File: activesupport/test/cache/behaviors/cache_store_behavior.rb [hunk 1]
```diff
@@ -174,6 +174,16 @@ def test_write_multi_empty_hash
     assert @cache.write_multi({})
   end
 
+  def test_write_multi_expires_in
+    time = Time.now
+    key = SecureRandom.uuid
+    @cache.write_multi({ "#{key}" => 1 }, expires_in: 10)
+
+    Time.stub(:now, time + 11) do
```
Comment (jonathanhefner) [inline activesupport/test/cache/behaviors/cache_store_behavior.rb:182]: Is there a reason to not use [`travel`](https://edgeapi.rubyonrails.org/classes/ActiveSupport/Testing/TimeHelpers.html#method-i-travel) here?

**Review by jonathanhefner — COMMENTED** [review]
Looks like this was accidentally broken in https://github.com/rails/rails/commit/f9fce850da754daca5274f402b7b6dc77c7489b9#diff-8fbbb6f4480a782f49dbae5d364199ea4242fff5f6bd36c3bb01e36bed060b09L411.

File: activesupport/test/cache/behaviors/cache_store_behavior.rb (hunk 1 above)
Comment (fatkodima) [reply activesupport/test/cache/behaviors/cache_store_behavior.rb:182]: Yeah. Copy paste from the above test.
Just noticed another problem - `"#{key}"` , interpolation is not needed. A work for another rubocop cop `Style/RedundantInterpolation`. I noticed a few offenses of it in rails. Do you think its worth enabling?

**Comment by jonathanhefner** [comment]
> Wdyt about enabling a relevant rubocop's cop for this in a follow up PR - https://docs.rubocop.org/rubocop/1.57/cops_lint.html#lintunusedmethodargument ? With it, this bug would be detected earlier.

I think it would depend on what the end result looks like for the entire Rails code base.

Personally, I am not a fan of prefixing arguments with `_`, whether they are unused or not.  Also, there doesn't appear to be a way to enforce the reverse.  i.e. If an argument goes from being unused to used, removal of the `_` prefix is not enforced.

File: activesupport/test/cache/behaviors/cache_store_behavior.rb (hunk 1 above)
Comment (jonathanhefner) [reply activesupport/test/cache/behaviors/cache_store_behavior.rb]: Personally, no.  Although I can't remember specific examples, I know there have been times when I preferred to write `"#{foo}"` instead of `foo.to_s` for stylistic reasons.

Also, given Ruby's lack of static typing, it seems like such a cop might not be very reliable.

Comment (fatkodima) [reply activesupport/test/cache/behaviors/cache_store_behavior.rb]: Yeah, no problems. This cop just detects patterns like `"#{foo}"` and suggests to replace them with `foo.to_s` (as a safe option), but many times this can be just written as `foo`.

**Comment by jonathanhefner** [comment]
Thank you, @fatkodima! :writing_hand:
