### PR TITLE
[Fix #48535]: fix behavior of `proc_for_binds` in `Arel::Nodes::HomogenousIn`

### LINKED ISSUE #48072: Cannot query string columns that use `serialize` using array of values
### Steps to reproduce

- Create a table with a string column
- Add a serializer on the column that transforms the string value
- Try to query the model with multiple values (i.e. `Model.where(serialized_field: ['value1', 'value2'])`)

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.1.7.3"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :user_id
  end
end

class Base64Coder
  def self.dump(value)
    return unless value
    Base64.encode64(value)
  end

  def self.load(value)
    return unless value
    Base64.decode64(value)
  end
end

class Post < ActiveRecord::Base
  serialize :user_id, Base64Coder
end

class BugTest < Minitest::Test
  p1 = Post.create!(user_id: '123')
  p2 = Post.create!(user_id: '456')

  def test_query_by_single_user_id
    assert_equal 1, Post.where(user_id: '123').count # Works - returns [p1]
  end

  def test_query_by_array_of_single_user_ids
    assert_equal 1, Post.where(user_id: ['123']).count, 1 # Works - returns [p1]
  end

  def test_query_by_array_of_user_ids
    assert_equal 2, Post.where(user_id: ['123', '456']).count # Doesn't work - returns []
  end

  def test_workaround
    assert_equal 2, Post.where("user_id IN (?)", ['123', '456'].map{|val| Base64.encode64(val)}).count # Works [p1, p2]
  end
end
```

### Expected behavior

`Post.where(user_id: ['123', '456'])` works (as it did in v6.0.6.1)

### Actual behavior

`Post.where(user_id: ['123', '456'])` returns an empty list.

If we look at the logs, we can see this is the query that is getting run:

```
 SELECT COUNT(*) FROM "posts" WHERE "posts"."user_id" IN (?, ?)  [["user_id", "TVRJego=\n"], ["user_id", "TkRVMgo=\n"]]
```

The issue is that the values are getting serialized twice before getting passed into the query:

```ruby
[15] pry(main)> user_id = '123'
=> "123"
[16] pry(main)> Base64.encode64(user_id)
=> "MTIz\n"
[17] pry(main)> Base64.encode64("MTIz\n")
=> "TVRJego=\n"
```

### System configuration
**Rails version**: 6.1.7.3

**Ruby version**: 2.6

### LINKED ISSUE #48535: Change in ActiveRecord JSON/JSONB Query Behavior from Rails 6.0 to 6.1
### Steps to reproduce
In Rails 6.0, create a query on a JSON/JSONB column in PostgreSQL using an array of hashes:

```ruby
store_ids = [{ "store_id" => 7 }, { "store_id" => 8 }]
where(dimensions: store_ids) # This works as expected in Rails 6.0
```

Then, run the same query in Rails 6.1:

```ruby
store_ids = [{ "store_id" => 7 }, { "store_id" => 8 }]
where(dimensions: store_ids) # This returns [] in Rails 6.1
```

### Expected behavior
The query should return the same results in Rails 6.1 as it did in Rails 6.0. The ActiveRecord should convert the array of hashes into a JSON representation that PostgreSQL can understand.

### Actual behavior
In Rails 6.1, the query returns an empty array. It appears that ActiveRecord is no longer converting the array of hashes into a JSON representation that PostgreSQL can understand.

As a workaround, I've had to convert the store IDs into strings and use PostgreSQL's `->>` operator syntax:

```ruby
store_ids = [7, 8].map(&:to_s)
where("dimensions->>'store_id' in (?)", store_ids) # This works as expected in Rails 6.1
```

### System configuration
**Rails version**: 6.1

**Ruby version**: 2.7.7

### PR DESCRIPTION
**Pull request by JohnAnon9771**
### Motivation / Background
This PR addresses the issues #48535 and #48072.

With the introduction of PR #41068, an unintended behavior surfaced, causing the `proc_for_binds` to apply casting to attributes that were already casted. Consequently, this led to the malfunctioning of queries, as noted in the referenced issues.

This commit fixes the issue by replacing the type with `ActiveModel::Type.default_value` so that the 2nd serialization is effectively a no-op. This correction has obviated the need for changes such as "Fix deterministic queries that were broken after #41068," as detailed in [this commit](https://github.com/wbotelhos/rails/commit/37361bfb4222c5d210f11e48ecee46b05ea7d50e). These changes had inadvertently caused the tests initially intended for `proc_for_binds` within `HomogeneousIn` to erroneously evaluate the `proc_for_binds` within `InWithAdditionalValues`. This resulted in false positives whenever adjustments were made to the `proc_for_binds` within `HomogeneousIn`.

Fixes #48072.
Fixes #48535.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by matthewd** [comment]
The description here says a lot about what the previous change did and what broke, but I've struggled to follow the reasoning of the change. Is the following accurate?

* The value supplied to (the block returned by) `proc_for_binds` has already been typecast to database format
* `with_cast_value` expects its value to be in application format (the "rich type" actually matching the Type)
* This difference is hidden for many default types (integer, string, etc) because the two formats are equivalent
* We need a bind attribute that knows it has already been cast, so it can still say which attribute name it belongs to, but will make no further conversion when asked for the DB value

Does `FromDatabase` do that?

**Comment by JohnAnon9771** [comment]
Sorry, I ended up messing up my location a little and I didn't realize it before pushing, I ended up bugging the bot a little... :( I'll be more careful.

**Comment by JohnAnon9771** [comment]
> The description here says a lot about what the previous change did and what broke, but I've struggled to follow the reasoning of the change. Is the following accurate?
> 
> * The value supplied to (the block returned by) `proc_for_binds` has already been typecast to database format
> * `with_cast_value` expects its value to be in application format (the "rich type" actually matching the Type)
> * This difference is hidden for many default types (integer, string, etc) because the two formats are equivalent
> * We need a bind attribute that knows it has already been cast, so it can still say which attribute name it belongs to, but will make no further conversion when asked for the DB value
> 
> Does `FromDatabase` do that?

Yes, your conclusion is correct. And `FromDatabase` really works perfectly to solve this problem, greatly simplifying the solution. Thanks for the sugestion.

File: activerecord/test/cases/log_subscriber_test.rb [hunk 1]
```diff
@@ -254,6 +256,12 @@ def test_where_in_binds_logging_include_attribute_names
       assert_match(%{["id", 1], ["id", 2], ["id", 3], ["id", 4], ["id", 5]}, @logger.logged(:debug).last)
     end
 
+    def test_where_in_binds_with_json_attribute
+      Admin::User.where(json_options: [{ a: 1 }, { b: 2 }]).load
+      wait
+      assert_match(%{[["json_options", "{\\"a\\":1}"], ["json_options", "{\\"b\\":2}"]]}, @logger.logged(:debug).last)
+    end
```
Comment (jonathanhefner) [inline activerecord/test/cases/log_subscriber_test.rb]: This tests the logging output, but what we're really trying to fix is the query, so I think we should test the query results instead.

**Review by jonathanhefner — COMMENTED** [review]
After digging into this, I think this solution is mostly on target. :+1:  I've left a few comments, but I pushed a commit to address them since I was digging into the code anyway.  I'll merge once the build is green.

**Comment by jonathanhefner** [comment]
Thank you, @JohnAnon9771! :milk_glass:
