### PR TITLE
Ensure SVG elements are closed.

### LINKED ISSUE #44563: SVG tags generated with tag helper are not self closing
### Steps to reproduce
Generate HTML using this code to output an SVG:

```
tag.div(style: "height: 100px; width: 100px") do
  tag.svg(viewBox: "0 0 100 100", xmlns: "http://www.w3.org/2000/svg") do
    tag.g(fill: "white", stroke: "green", "stroke-width": "5") do
      tag.circle(cx: 40, cy: 40, r: 25) +
        tag.circle(cx: 60, cy: 60, r: 25)
    end
  end
end
```

### Expected behavior
`<circle>` tags inside the SVG should be closed.

```
<div style="height: 100px; width: 100px">
  <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
    <g fill="white" stroke="green" stroke-width="5">
      <circle cx="40" cy="40" r="25"></circle>
      <circle cx="60" cy="60" r="25"></circle>
    </g>
  </svg>
</div>
```

SVG should look like
image

### Actual behavior
`<circle>` tags are not closed.

```
<div style="height: 100px; width: 100px">
  <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
    <g fill="white" stroke="green" stroke-width="5">
      <circle cx="40" cy="40" r="25">
      <circle cx="60" cy="60" r="25">
    </g>
  </svg>
</div>
```

The browser ends up nesting the `<circle>` tags like:

```
<div style="height: 100px; width: 100px">
  <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
    <g fill="white" stroke="green" stroke-width="5">
      <circle cx="40" cy="40" r="25">
        <circle cx="60" cy="60" r="25"></circle>
      </circle>
    </g>
  </svg>
</div>
```

The final SVG looks like:
image

Changes introduced in Rails 7 in https://github.com/rails/rails/pull/43232 broke this SVG. I think the changes are not correct. Only [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) can omit the end tag. Tags inside SVG elements are not considered void elements but rather are [foreign elements](https://dev.w3.org/html5/html-author/#foreign-elements) (elements in the SVG namespace). These elements must be closed with either an end tag (like they were before the change), or by self-closing like `<circle cx="60" cy="60" r="25" />`.

### System configuration
**Rails version**: 7.0.2.2

**Ruby version**: 3.1.1

### PR DESCRIPTION
**Pull request by davekaro**
Changes introduced in https://github.com/rails/rails/pull/43232 break SVGs
that have mulitple of the same descendant tag because they weren't being
closed. SVG elements must be closed accodoring to spec
https://html.spec.whatwg.org/multipage/syntax.html#elements-2.

Fixes https://github.com/rails/rails/issues/44563

### CODE REVIEW

File: actionview/lib/action_view/helpers/tag_helper.rb [hunk 1]
```diff
@@ -67,8 +67,9 @@ def p(*arguments, **options, &block)
 
         def tag_string(name, content = nil, escape_attributes: true, **options, &block)
           content = @view_context.capture(self, &block) if block_given?
-          if (HTML_VOID_ELEMENTS.include?(name) || SVG_VOID_ELEMENTS.include?(name)) && content.nil?
-            "<#{name.to_s.dasherize}#{tag_options(options, escape_attributes)}>".html_safe
+          self_closing = SVG_SELF_CLOSING_ELEMENTS.include?(name)
```
Comment (rafaelfranca) [inline actionview/lib/action_view/helpers/tag_helper.rb:70]: Why is this now a local variable? It changes the order of execution, which can make this method slower

Comment (davekaro) [reply actionview/lib/action_view/helpers/tag_helper.rb:70]: Good point. But it would only be slower for the void element calls. I was trying to avoid the check again when determining the self closing. Should I make a separate elsif clause instead?
