### PR TITLE
Maintain Rack 2 parameter parsing behaviour

### LINKED ISSUE #53394: Regression in request parameter parsing
### Steps to reproduce

https://github.com/rails/rails/pull/53193 causes a change of behaviour if using Rack 2. This might be considered a bug fix, but it's a non-trivial change so I thought it was worth getting some eyes over.

The issue occurs when requesting a URL that looks like this: `"/foo?date=2024-10-21&amp;user_id=123"`. With Rack 2, before https://github.com/rails/rails/pull/53193, this was parsed as:

```
{"date"=>"2024-10-21", "amp"=>nil, "user_id"=>"123", "controller"=>"test", "action"=>"index"}
```

After https://github.com/rails/rails/pull/53193 it is parsed as:

```
{"date"=>"2024-10-21", "amp;user_id"=>"123", "controller"=>"test", "action"=>"index"}
```

If you use Rack 3, it parses as the latter form regardless of Rails commit.

So https://github.com/rails/rails/pull/53193 causes a change in behaviour for Rack 2 users. Arguably it's a bug fix in Rails, and the user should fix their buggy code (they should go to `"/foo?date=2024-10-21&user_id=123"` instead). But it's a pretty subtle bug that's hard to audit for and that's been around for a very long time.

What makes it particularly subtle is that the "buggy" code results in expected params, ie. if you do `params[:user_id]` in your controller it'll return what you expect. On upgrading to the "fixed" version of Rails, will `params[:user_id]` return `nil` instead of a value.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # The last commit before https://github.com/rails/rails/pull/53193, tests fail.
  gem "rails", github: "rails/rails", branch: "main", ref: "e83cfa5466255d48cf03308dfe5d183eb8444d51"

  # The commit for https://github.com/rails/rails/pull/53193, tests pass
  # gem "rails", github: "rails/rails", branch: "main", ref: "d64611bc5a71a749d10c4da295e80fe182b5d7ea"

  # The issue is specific to Rack 2.
  gem "rack", "~> 2"

  # If you use Rack 3 the tests pass with either Rails commit.
  # gem "rack", "~> 3"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/foo" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: params.to_s
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < ActiveSupport::TestCase
  include Rack::Test::Methods

  def test_returns_success
    get "/foo?date=2024-10-21&amp;user_id=123"
    expected = %Q({"date"=>"2024-10-21", "amp;user_id"=>"123", "controller"=>"test", "action"=>"index"})
    assert_equal expected, last_response.body

    # before PR 53193, this would pass:
    # expected = %Q({"date"=>"2024-10-21", "amp"=>nil, "user_id"=>"123", "controller"=>"test", "action"=>"index"})
    # assert_equal expected, last_response.body
  end

  private
    def app
      Rails.application
    end
end

```

### Expected behavior

Honestly I'm not sure the right approach here. It would suit me if the old behaviour was supported forever, but objectively that seems silly given that it's clearly a bug.

### Actual behavior

See above

### System configuration
**Rails version**: main

**Ruby version**: 3.3

### PR DESCRIPTION
**Pull request by matthewd**
When running under Rack 3, we'll proceed with the new behaviour. That means we won't affect applications that already use Rack 3, but does also mean we can't help an application that is simultaneously bumping Rails and Rack together. 🤷🏻‍♂️

However, with this commit, we at least ensure we maintain compatibility for applications that are currently still on Rack 2 -- and we can help with the transition using deprecation warnings... though there's admittedly a decent chance such warnings will only show up in production.

Fixes #53394

### CODE REVIEW

**Comment by Schwad** [comment]
> though there's admittedly a decent chance such warnings will only show up in production.

That's good to know; at least folks looking to upgrade Rack 3 can use those logs to update their setup.

File: actionpack/lib/action_dispatch/railtie.rb [hunk 1]
```diff
@@ -31,6 +31,9 @@ class Railtie < Rails::Railtie # :nodoc:
     config.action_dispatch.debug_exception_log_level = :fatal
     config.action_dispatch.strict_freshness = false
 
+    config.action_dispatch.ignore_leading_brackets = nil
+    config.action_dispatch.strict_query_string_separator = nil
```
Comment (ghiculescu) [inline actionpack/lib/action_dispatch/railtie.rb:35]: Should these configs be documented? My understanding is that you should use them if you're upgrading from Rack 2 to Rack 3 but want to preserve Rack 2 behaviour for a little while longer. And also that they will both be removed in Rails 8.1?

**Comment by intrip** [comment]
This change applies **also to request body params** passed as `application/x-www-form-urlencoded`, not just query params. I haven't dug deeply, but it is probably a consequence of https://github.com/rails/rails/pull/53193 paired with this change. Is this behavior expected?

Example:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # with Rack 2 param parsing backward compat
  gem "rails", github: "rails/rails", branch: "main", ref: "ae60fcebafaa102df50504425e8113e3648c5faa"

  # without Rack 2 compat
  # gem "rails", github: "rails/rails", branch: "main", ref: "902d99c8c579c3e3d286d658d7c718d055e408cf"

  gem "rack", "~> 2"
end

require "minitest/autorun"
require "rack/test"

class BugTest < ActiveSupport::TestCase
  include Rack::Test::Methods

  def test_action_dispatch_parse_query_parameters
    env = {
      "REQUEST_METHOD" => "POST",
      "rack.input" => StringIO.new("content=just-one;param"),
      "CONTENT_LENGTH" => "22",
      "CONTENT_TYPE" => "application/x-www-form-urlencoded",
    }
    request = ActionDispatch::Request.new(env)
    params = request.query_parameters
    expected = { "content" => "just-one;param" }
    assert_equal(expected, request.params)
  end
end
```

/cc @matthewd
