### PR TITLE
Fix failures due to transactions

### LINKED ISSUE #24391: bundle exec rake test_mysql2 causes Mysql2::Error: SAVEPOINT active_record_1 does not exist: ROLLBACK TO SAVEPOINT active_record_1
### Steps to reproduce
```
$ cd activerecord
$ bundle exec rake test_mysql2
```

### Minimum steps to reproduce
```
$ cd activerecord
$ ARCONN=mysql2 bundle exec ruby -W -w -I"lib:test" \
  "/home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.1/lib/rake/rake_test_loader.rb" \
  "test/cases/ar_schema_test.rb" \
  "test/cases/tasks/database_tasks_test.rb"
```

### Expected behavior
Unit tests finished without errors

### Actual behavior
Tell us what happens instead
```ruby
  1) Error:
ActiveRecord::DatabaseTasksMigrateTest#test_migrate_clears_schema_cache_afterward:
ActiveRecord::StatementInvalid: Mysql2::Error: SAVEPOINT active_record_1 does not exist: ROLLBACK TO SAVEPOINT active_record_1
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `_query'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `block in query'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `handle_interrupt'
    /home/yahonda/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `query'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:235:in `block in execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:526:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:520:in `log'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:235:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:128:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/savepoints.rb:13:in `exec_rollback_to_savepoint'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:292:in `rollback_to_savepoint'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `rollback_to_savepoint'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:114:in `rollback'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:183:in `rollback_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:204:in `rescue in within_new_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:201:in `within_new_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:211:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
    /home/yahonda/git/rails/activerecord/lib/active_record/persistence.rb:277:in `update!'
    /home/yahonda/git/rails/activerecord/lib/active_record/internal_metadata.rb:22:in `[]='
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1198:in `record_environment'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1192:in `migrate_without_lock'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1137:in `block in migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1304:in `with_advisory_lock'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1137:in `migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:1011:in `up'
    /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:989:in `migrate'
    /home/yahonda/git/rails/activerecord/lib/active_record/tasks/database_tasks.rb:159:in `migrate'
    /home/yahonda/git/rails/activerecord/test/cases/tasks/database_tasks_test.rb:334:in `test_migrate_clears_schema_cache_afterward'

4826 runs, 13403 assertions, 0 failures, 1 errors, 5 skips

You have skipped tests. Run with --verbose for details.
rake aborted!
```
### System configuration
**Rails version**:
master branch including https://github.com/rails/rails/commit/133befb59b8389cb483fd4194acdcddc5e288ab4

**Ruby version**:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

debug.log shows that it is trying to rollback to the savepoint which has been already released.

```ruby
   (0.1ms)  SAVEPOINT active_record_1
   (0.3ms)  RELEASE SAVEPOINT active_record_1
   (0.2ms)  ROLLBACK TO SAVEPOINT active_record_1
```

### PR DESCRIPTION
**Pull request by vipulnsward**
We are erroring due to nested transaction failures from mysql on test_migrate_clears_schema_cache_afterward test on schema creation.

Disable transactions for this test.

Fixes #24391

r? @arthurnn

### CODE REVIEW

File: activerecord/test/cases/tasks/database_tasks_test.rb [hunk 1]
```diff
@@ -336,6 +336,7 @@ def test_migrate_receives_correct_env_vars
       ENV['VERBOSE'], ENV['VERSION'] = verbose, version
     end
 
+    self.use_transactional_tests = false
```
Comment (arthurnn) [inline activerecord/test/cases/tasks/database_tasks_test.rb]: can you move this to line 319? so it is before setup.

File: activerecord/test/cases/tasks/database_tasks_test.rb [hunk 2]
```diff
@@ -316,6 +316,8 @@ def test_drops_testand_development_databases_when_rails_env_is_development
   end
 
   class DatabaseTasksMigrateTest < ActiveRecord::TestCase
+    self.use_transactional_tests = false
```
Comment (vipulnsward) [inline activerecord/test/cases/tasks/database_tasks_test.rb]: done.

**Comment by arthurnn** [comment]
thanks

**Comment by arthurnn** [comment]
For historical reasons:
@vipulnsward and I paired on this and we saw that there was a migration happening inside a transaction for that test. As mysql don't support DDL changes inside transactions and just commits the transaction afterwards, that was leaking transaction depending on the order of tests run.
