### PR TITLE
[ActiveStorage] Return "Range Not Satisfiable" return code for partial downloads with incorrect range

### LINKED ISSUE #45890: ActiveStorage: Partial downloads with incorrect range throw a RoutingError and 404 not found
### Steps to reproduce
```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'rails', '~> 7.0.0'
  gem 'sqlite3'
end

require 'active_record/railtie'
require 'active_storage/engine'
require 'tmpdir'

class TestApp < Rails::Application
  config.root = __dir__
  config.eager_load = false
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_key_base = 'secret_key_base'
  config.hosts << 'www.example.com'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: 'Disk'
    }
  }
end

ENV['DATABASE_URL'] = 'sqlite3::memory:'

Rails.application.initialize!

require ActiveStorage::Engine.root.join('db/migrate/20170806125915_create_active_storage_tables.rb').to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true
end

class User < ActiveRecord::Base
  has_one_attached :pdf
end

require 'minitest/autorun'

# Download a file with incorrect partial byte range
class PartialDownloadTest < ActionDispatch::IntegrationTest
  test 'Partial download' do
    user = User.create!(
      pdf: {
        content_type: 'application/pdf',
        filename: 'dummy.pdf',
        io: ::StringIO.new(SecureRandom.random_bytes(1000))
      }
    )
    # Get URL for download
    get "/#{Rails.application.routes.url_helpers.rails_blob_path(user.pdf, only_path: true)}"
    assert_response :redirect
    # Download with non-existing range
    get(response.location, headers: { 'Range' => 'bytes=10000-10000' })
    # Should respond with status 416 Range not satisfiable, but throws a RoutingError and responds with 404 not found
    assert_response 416
  end
end
```

### Expected behavior
When a browser asks for a part of a file that doesn't exist (Safari is prone to doing this), the response should be 416 'Range not satisfiable'.

### Actual behavior
The response is 404 'Not found' and an ActionController::RoutingError occurs.

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 3.0.2p107

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #45890 (see there for all the details).
cc @skipkayhil

### CODE REVIEW

File: activestorage/app/controllers/concerns/active_storage/file_server.rb [hunk 1]
```diff
@@ -11,6 +11,7 @@ def serve_file(path, content_type:, disposition:)
           response.headers[name] = value
         end
 
+        response.headers.except!("X-Cascade", "x-cascade") if status == 416
```
Comment (skipkayhil) [inline activestorage/app/controllers/concerns/active_storage/file_server.rb:14]:
```suggestion
        response.headers.delete("X-Cascade", "x-cascade") if status == 416
```
Since we aren't using the return value, I think it makes sense to use Ruby `Hash#delete` over Rails `Hash#except!`

Other than that 👍 from me

Comment (fatkodima) [reply activestorage/app/controllers/concerns/active_storage/file_server.rb:14]: I wanted to make it one-liner, but `Hash#delete` accepts only one argument :(

Comment (skipkayhil) [reply activestorage/app/controllers/concerns/active_storage/file_server.rb:14]: Ah, right. Maybe `response.headers.delete_if { |header| ["X-Cascade", "x-cascade"].include?(header) } if status == 416` ? 

I definitely agree `except!` looks the cleanest. I think if we keep `except!` we should add `require "active_support/core_ext/hash/except"` to ensure the extension is loaded

Comment (fatkodima) [reply activestorage/app/controllers/concerns/active_storage/file_server.rb:16]: Good catch! Added a missing require.
