### PR TITLE
Fix number_to_currency to avoid negative format when displaying zero.

### LINKED ISSUE #42577: `number_to_currency` printing negative zero when precision > 0
In https://github.com/rails/rails/pull/37865 `number_to_currency` was fixed to properly print values that would result in a negative zero when passing `precision: 0`. However, it doesn't work when precision is > 0 as seen below.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "action_view"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  include ActionView::Helpers::NumberHelper

  def test_stuff
    assert_equal "$0", number_to_currency(-0.456789, precision: 0) # This works fine
    assert_equal "$0.0", number_to_currency(-0.0456789, precision: 1) # This does not (prints "-$0.0")
  end
end
```

**Note**: calling `number_to_currency` without specifying `precision` also causes issues, since the default value for precision is > 0.

### Expected behavior

Given the above test "$0.0" should be printed.

### Actual behavior

"-$0.0" is printed instead.

### System configuration
**Rails version**:
main

**Ruby version**:
2.7.2

### PR DESCRIPTION
**Pull request by flavorjones**
### Summary

Fix number_to_currency to avoid negative format when displaying zero.

For example, make this test pass (which without this patch returns "-$0.00"):

```ruby
assert_equal("$0.00", number_helper.number_to_currency(-0.00456789, precision: 2))
```

This PR also fixes a bug where `-0.5` displayed with `precision` 0 would incorrectly use the positive format.

Closes #42577

### Other Information

This is a more-complete version of the fix in #37865 which originally
addressed #37846.

Also see context at #39350 with respect to alternate input formats.

### CODE REVIEW

File: activesupport/lib/active_support/number_helper/number_to_currency_converter.rb [hunk 1]
```diff
@@ -11,9 +11,16 @@ def convert
...
-           (options[:precision] != 0 || number.to_f > 0.5)
-          format = options[:negative_format]
+        if number.sub!(/^-/, "")
+          number_f = number.to_f.abs
+          if number_f == 0.0
+            # likely an alternate input format that failed to parse.
+            # see https://github.com/rails/rails/pull/39350
+            format = options[:negative_format]
+          else
+            number_f *= 10**options[:precision]
```
Comment (rafaelfranca) [inline activesupport/lib/active_support/number_helper/number_to_currency_converter.rb:21]:
```suggestion
            number_f *= 10 ** options[:precision]
```

Comment (flavorjones) [reply activesupport/lib/active_support/number_helper/number_to_currency_converter.rb:21]: I originally had it with spaces and rubocop failed it saying the spaces needed to be removed.

Comment (flavorjones) [reply activesupport/lib/active_support/number_helper/number_to_currency_converter.rb:21]:
```
lib/active_support/number_helper/number_to_currency_converter.rb:21:28: C: [Correctable] Layout/SpaceAroundOperators: Space around operator ** detected.
            number_f *= 10 ** options[:precision]
                           ^^
```

Comment (rafaelfranca) [reply activesupport/lib/active_support/number_helper/number_to_currency_converter.rb:21]: What a strange cop, the idea was to avoid ` number_f*=` but it also changing the `**`. That is fine then.

**Comment by flavorjones** [comment]
@MathijsK93 Thanks for commenting, and sorry you're seeing something unexpected.

The intent of this change was to avoid formatting 'negative zero" (#42577) and so I believe the correct behavior should be

```ruby
          assert_equal("$0.00", number_helper.number_to_currency(-0.0))
```

I'll put together a PR with test coverage for this edge case and a fix.

**Comment by MathijsK93** [comment]
@flavorjones That would be very nice, thank for your reply!

**Comment by flavorjones** [comment]
See https://github.com/rails/rails/pull/43098 for followup
