### PR TITLE
redis-rb 4.0 support

### LINKED ISSUE #30527: redis gem 4+ incompatibility "Specified 'redis' for Action Cable pubsub adapter, but the gem is not loaded"
### Steps to reproduce

Using ActionCable 5.1.3 with the `redis` gem upgraded from 3.3.3 to 4.0.0 and attempting to broadcast on a channel seems to yield this exception:

```
Specified 'redis' for Action Cable pubsub adapter, but the gem is not loaded. Add `gem 'redis'` to your Gemfile (and ensure its version is at the minimum required by Action Cable).
```

Going back to ~> 3.3 makes AC work again as expected.

### Expected behavior
AC should work

### Actual behavior
An exception is raised indicating the gem is not loaded, but it seems to be.

Going back to ~> 3.3 makes AC work again as expected.

### System configuration
**Rails version**: 5.1.3

**Ruby version**: 2.4.1

### PR DESCRIPTION
**Pull request by jeremy**
* Loosen Redis version dep to `>= 3.3, < 5`
* Bump redis-namespace for looser Redis version dep
* Avoid using the underlying `redis.client` directly
* Use `Redis.new` instead of `Redis.connect`

Pending gem releases for [Sidekiq](https://github.com/mperham/sidekiq/pull/3618), [redis-namespace](https://github.com/resque/redis-namespace/pull/136), and [resque-scheduler](https://github.com/resque/resque-scheduler/pull/620).

Fixes #30527

### CODE REVIEW

File: actioncable/lib/action_cable/subscription_adapter/redis.rb [hunk 1]
```diff
@@ -2,7 +2,7 @@
 
 require "thread"
 
-gem "redis", "~> 3.0"
+gem "redis", "~> 3", "< 5"
```
Comment (matthewd) [inline actioncable/lib/action_cable/subscription_adapter/redis.rb]: This needs to be `">= 3", "< 5"`; `"~> 3"` and `"~> 3.0"` both mean the same thing.

**Review by matthewd — APPROVED** [review]
I don't suppose the new version has any better options for our `@raw_client` / `flush` hackery?

**Comment by jeremy** [comment]
Doesn't appear to.

**Comment by eileencodes** [comment]
Hey @jeremy the 5-1-stable branch is failing on travis since it auto updates the redis gem to 4.0.1. Should be be backported to the 5-1-stable branch or should 5-1-stable have a lower redis dependency requirement?
