### PR TITLE
Test when using MySQL `exec_query` returns `ActiveRecord::Result` all…

### LINKED ISSUE #34506: Result from query differs between MySQL and SQLite3
When running `exec_query` with `INSERT` (or other write commands), MySQL returns `nil`. When run with SQLite3 (and also PostgreSQL) an `ActiveRecord::Result` is returned with an empty row set.

### Steps to reproduce

MySQL script (passes):

```ruby
require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection({ "adapter" => "mysql2", "username" => "rails", "database" => "activerecord_unittest" })
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t| 
    t.string :name
  end 
end

class Post < ActiveRecord::Base
  has_many :comments
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_nil ActiveRecord::Base.connection.exec_query("INSERT INTO `posts` (`name`) VALUES ('post title')")
  end 
end
```

Sqlite3 Script (fails):

```ruby
require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t| 
    t.string :name
  end 
end

class Post < ActiveRecord::Base
  has_many :comments
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_nil ActiveRecord::Base.connection.exec_query("INSERT INTO posts (name) VALUES ('post title')")
  end 
end
```

### Expected behavior

I think all the dbs should return nil or an empty set, but not differ between dbs. 

### Actual behavior

MySQL behaves differently from SQLite3 and PostgreSQL

### System configuration
**Rails version**: master

**Ruby version**: 2.5

cc/ @rafaelfranca @tenderlove @matthewd

### PR DESCRIPTION
**Pull request by al3rez**
Fixes #34506 - When running `exec_query` with INSERT (or other write commands), MySQL returns `ActiveRecord::Result`

### CODE REVIEW

**Comment by azbshiri** [comment]
I wanted to come up with a more creative idea to return an empty result but I thought maybe it'd be over-engineering. So I just used simple if/else statements to avoid complexity.

File: activerecord/test/cases/adapters/mysql2/mysql2_adapter_test.rb [hunk 1]
```diff
@@ -69,6 +69,13 @@ def test_errors_for_bigint_fks_on_integer_pk_table
     @conn.exec_query("ALTER TABLE engines DROP COLUMN old_car_id")
   end
 
+  def test_exec_query_returns_an_empty_result
+    with_example_table do
+      result = @conn.exec_query("INSERT INTO ex (number) VALUES (1)")
+      assert result.is_a?(ActiveRecord::Result)
```
Comment (kamipo) [inline activerecord/test/cases/adapters/mysql2/mysql2_adapter_test.rb]: Use `assert_instance_of` instead.

File: activerecord/test/cases/adapters/mysql2/mysql2_adapter_test.rb [hunk 2]
```diff
@@ -69,6 +69,13 @@ def test_errors_for_bigint_fks_on_integer_pk_table
     @conn.exec_query("ALTER TABLE engines DROP COLUMN old_car_id")
   end
 
+  def test_exec_query_returns_an_empty_result
```
Comment (kamipo) [inline activerecord/test/cases/adapters/mysql2/mysql2_adapter_test.rb]: This test case should be passed by all adapters, add it in generic test cases (e.g. in `test/cases/adapter_test.rb`, not in adapter specific test cases).

File: activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb [hunk 3]
```diff
@@ -37,7 +37,11 @@ def exec_query(sql, name = "SQL", binds = [], prepare: false)
             end
           else
             exec_stmt_and_free(sql, name, binds, cache_stmt: prepare) do |_, result|
-              ActiveRecord::Result.new(result.fields, result.to_a) if result
+              if result
+                ActiveRecord::Result.new(result.fields, result.to_a) if result
```
[the remark this answers is not in the document]
Comment (azbshiri) [reply activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb]: Oh, I've missed that.

File: activerecord/test/cases/adapters/mysql2/mysql2_adapter_test.rb (hunk 2 above)
Comment (azbshiri) [reply activerecord/test/cases/adapters/mysql2/mysql2_adapter_test.rb]: How can I run specific test files using `./bin/test` script?!

Comment (kamipo) [reply activerecord/test/cases/adapters/mysql2/mysql2_adapter_test.rb]: e.g. `bin/test test/cases/adapter_test.rb -n test_select_all_always_return_activerecord_result`

Comment (azbshiri) [reply activerecord/test/cases/adapters/mysql2/mysql2_adapter_test.rb]: Thanks

File: activerecord/test/cases/adapters/mysql2/mysql2_adapter_test.rb [hunk 4]
```diff
@@ -69,6 +69,13 @@ def test_errors_for_bigint_fks_on_integer_pk_table
...
+    with_example_table do
+      result = @conn.exec_query("INSERT INTO ex (number) VALUES (1)")
+      assert_instance_of(ActiveRecord::Result, result)
```
Comment (kamipo) [inline activerecord/test/cases/adapters/mysql2/mysql2_adapter_test.rb]: Failed.
https://travis-ci.org/rails/rails/jobs/459404009#L1328-L1333

**Review by eileencodes — APPROVED** [review]
Thanks @azbshiri!

**Comment by azbshiri** [comment]
Any time
