### PR TITLE
Fix conflicts `counter_cache` with `touch: true` by optimistic locking.

### LINKED ISSUE #31199: Counter cache conflicts with touch:true by optimistic locking
### Steps to reproduce

```ruby
gem "bundler", "< 1.16"

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts do |t|
    t.integer :comments_count, default: 0
    t.integer :lock_version
    t.timestamps
  end

  create_table :comments do |t|
    t.belongs_to :post
  end
end

class Post < ActiveRecord::Base
end

class Comment < ActiveRecord::Base
  belongs_to :post, touch: true, counter_cache: true
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    Comment.create!(post: post)
  end
end
```

### Expected behavior
Should generate a single SQL to update both updated_at and counter cache column.

### Actual behavior
There are 2 SQLs raise optimistic locking exception.

Output:
```
Post Update All (0.1ms)  UPDATE "posts" SET "comments_count" = COALESCE("comments_count", 0) + 1, "lock_version" = COALESCE("lock_version", 0) + 1 WHERE "posts"."id" = ?  [["id", 1]]
Post Update All (0.1ms)  UPDATE "posts" SET "updated_at" = '2017-11-22 15:29:31.744519', "lock_version" = 1 WHERE "posts"."id" = ? AND "posts"."lock_version" = ?  [["id", 1], ["lock_version", 0]]
(0.1ms)  rollback transaction

ActiveRecord::StaleObjectError: Attempted to touch a stale object: Post.
```

### System configuration
**Rails version**: 5.1.4 or master@858baa0

**Ruby version**: 2.4.2

### PR DESCRIPTION
**Pull request by bogdanvlviv**
```
# create_table :posts do |t|
#   t.integer :comments_count, default: 0
#   t.integer :lock_version
#   t.timestamps
# end
class Post < ApplicationRecord
end

# create_table :comments do |t|
#   t.belongs_to :post
# end
class Comment < ApplicationRecord
  belongs_to :post, touch: true, counter_cache: true
end
```

Before:
```
post = Post.create!
# => begin transaction
     INSERT INTO "posts" ("created_at", "updated_at", "lock_version")
     VALUES ("2017-12-11 21:27:11.387397", "2017-12-11 21:27:11.387397", 0)
     commit transaction

comment = Comment.create!(post: post)
# => begin transaction
     INSERT INTO "comments" ("post_id") VALUES (1)

     UPDATE "posts" SET "comments_count" = COALESCE("comments_count", 0) + 1,
     "lock_version" = COALESCE("lock_version", 0) + 1 WHERE "posts"."id" = 1

     UPDATE "posts" SET "updated_at" = '2017-12-11 21:27:11.398330',
     "lock_version" = 1 WHERE "posts"."id" = 1 AND "posts"."lock_version" = 0
     rollback transaction
# => ActiveRecord::StaleObjectError: Attempted to touch a stale object: Post.

Comment.take.destroy!
# => begin transaction
     DELETE FROM "comments" WHERE "comments"."id" = 1

     UPDATE "posts" SET "comments_count" = COALESCE("comments_count", 0) - 1,
     "lock_version" = COALESCE("lock_version", 0) + 1 WHERE "posts"."id" = 1

     UPDATE "posts" SET "updated_at" = '2017-12-11 21:42:47.785901',
     "lock_version" = 1 WHERE "posts"."id" = 1 AND "posts"."lock_version" = 0
     rollback transaction
# => ActiveRecord::StaleObjectError: Attempted to touch a stale object: Post.
```

After:
```
post = Post.create!
# => begin transaction
     INSERT INTO "posts" ("created_at", "updated_at", "lock_version")
     VALUES ("2017-12-11 21:27:11.387397", "2017-12-11 21:27:11.387397", 0)
     commit transaction

comment = Comment.create!(post: post)
# => begin transaction
     INSERT INTO "comments" ("post_id") VALUES (1)

     UPDATE "posts" SET "comments_count" = COALESCE("comments_count", 0) + 1,
     "lock_version" = COALESCE("lock_version", 0) + 1,
     "updated_at" = '2017-12-11 21:37:09.802642' WHERE "posts"."id" = 1
     commit transaction

comment.destroy!
# => begin transaction
     DELETE FROM "comments" WHERE "comments"."id" = 1

     UPDATE "posts" SET "comments_count" = COALESCE("comments_count", 0) - 1,
     "lock_version" = COALESCE("lock_version", 0) + 1,
     "updated_at" = '2017-12-11 21:39:02.685520' WHERE "posts"."id" = 1
     commit transaction
```

Fixes #31199.

### CODE REVIEW

File: activerecord/test/cases/locking_test.rb [hunk 1]
```diff
@@ -399,11 +399,43 @@ def test_update_without_attributes_does_not_only_update_lock_version
...
+    assert_equal 0, car.reload.wheels_count
+    assert_not_equal previously_car_updated_at, car.updated_at
+    assert_equal 3, car.lock_version
+  end
+
   def test_polymorphic_destroy_with_dependencies_and_lock_version
     car = Car.create!
 
     assert_difference "car.wheels.count"  do
-      car.wheels << Wheel.create!
```
Comment (rafaelfranca) [inline activerecord/test/cases/locking_test.rb]: Did you need to change this test because this code is not valid anymore? Or it is because you added `touch: true` to the `Wheel` model?

Comment (bogdanvlviv) [reply activerecord/test/cases/locking_test.rb]: I changed it because I've added `touch: true` to the `Wheel` and after this code became invalid.

File: activerecord/lib/active_record/associations/builder/belongs_to.rb [hunk 2]
```diff
@@ -114,9 +114,13 @@ def self.add_touch_callbacks(model, reflection)
         BelongsTo.touch_record(record, record.send(changes_method), foreign_key, n, touch, belongs_to_touch_method)
       }}
 
-      model.after_save    callback.(:saved_changes), if: :saved_changes?
-      model.after_touch   callback.(:changes_to_save)
-      model.after_destroy callback.(:changes_to_save)
+      unless reflection.counter_cache_column
+        model.after_create callback.(:saved_changes), if: :saved_changes?
+        model.after_destroy callback.(:changes_to_save)
```
Comment (jolim) [inline activerecord/lib/active_record/associations/builder/belongs_to.rb]: I have a change in behavior which I believe is associated with removing the after_destroy callback for items with counter caches.

In 5.1.4, models chained together with belongs_to and touch: true would changed their updated_at timestamps regardless of the presence of a counter cache. Now, a model with a counter_cache won't propagate the touch past the next model.

Example:

```
class Books
    belongs_to :author, touch: true, counter_cache: true
end

class Author
  belongs_to :publisher, touch: true
end
```

In 5.1.4, when you destroy a Book, the Author and the Publisher both get new updated_at values.

In 5.1.5, only the Author is updated.

Comment (bauerd) [reply activerecord/lib/active_record/associations/builder/belongs_to.rb]: I just ran into this as well when migrating to 5.1.6.1. How was this not considered a breaking change?

Comment (bogdanvlviv) [reply activerecord/lib/active_record/associations/builder/belongs_to.rb]: Could you try `5-1-stable` branch (because `5.1.7` hasn't been released yet). I suppose it should be fixed there by https://github.com/rails/rails/commit/81dd13dfcea75ea7e65e52adfe5caed8868f5aae?

Comment (SophiaPetrova) [reply activerecord/lib/active_record/associations/builder/belongs_to.rb]: I upgraded to 5.1.7 but still experiencing this.

**Comment by bogdanvlviv** [comment]
I tried to run this reproduction script against 5.1.7
https://github.com/rails/rails/issues/31559#issue-284421762 and it works.
Could you please create a similar reproduction script for your issue?

---
Bogdan
https://bogdanvlviv.com

**Comment by thelucid** [comment]
The `after_touch` callback is not getting called when a record is destroyed. Removing `counter_cache` gives the expected behaviour. To reproduce, simply use the same setup and try destroying a comment — no touch.

**Comment by abhaynikam** [comment]
@bogdanvlviv @thelucid : I wrote the bug script like mentioned. Seems like it is working on `master` and on Rails `5.1.7` too. 

```
gem "bundler"

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "5.1.7"
  gem "sqlite3"
  gem "byebug"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts do |t|
    t.integer :comments_count, default: 0
    t.integer :lock_version
    t.timestamps
  end

  create_table :comments do |t|
    t.belongs_to :post
  end

  create_table :likes do |t|
    t.belongs_to :post
  end
end

class Post < ActiveRecord::Base
  after_touch :touched

  attr_accessor :after_touch_called

  after_initialize do
    self.after_touch_called = 0
  end

  def touched
    self.after_touch_called += 1
  end
end

class Comment < ActiveRecord::Base
  belongs_to :post, touch: true, counter_cache: true
end

class Like < ActiveRecord::Base
  belongs_to :post, touch: true
end

class BugTest < Minitest::Test
  def test_with_counter_cache
    post = Post.create
    assert_equal 0, post.after_touch_called

    comment = Comment.create(post: post)
    assert_equal 1, post.after_touch_called

    comment.destroy
    assert_equal 2, post.after_touch_called
  end
end
```

**Comment by thelucid** [comment]
@abhaynikam I'm using Postgresql on Rails 6 beta 3. It doesn't appear to be calling `after_touch` there on destroy if there is a `counter_cache` option set.

**Comment by Duleja** [comment]
Hi! I am also using PostgreSQL and it seems that the issue is present on Rails 6.0.0.

Both 'touch: true' and 'counter_cache: true' are working fine if used individually, but when combined like this:

belongs_to :some_model, counter_cache: true, touch: true

the associated record from 'some_model' table is not touched (updated), counter cache is incrementing though

**Comment by kamipo** [comment]
Can you create a new issue with reproducible script if there is still an issue?

**Comment by Duleja** [comment]
Hi! I have actually updated to rails/ruby 2.7.0/6.0.1.2 yesterday.

I tried to recreate the issue on the fresh 2.7.0/6.0.1.2 app and it seems that the issue is not present.
My fault for not checking on fresh an app first. :disappointed: 

NOTE:
I still have the issue on the previous app but that could be something with the "IdentityCache" gem that I am using or something else under the hood...
