### PR TITLE
Clear the transaction state when AR object is duped

### LINKED ISSUE #31670: ActiveRecord persisted? returns true after rollback when using duped record
```ruby
user = User.new(name: 'test')
begin
  ActiveRecord::Base.transaction do
    user.save!
    new_user = user.dup
    new_user.name = nil # invalid record
    new_user.save!
  end
rescue
  nil
end
```
This code works correctly when a `new_user` is valid record.
When `new_user` validation fails, the transaction rolls back but `user.persisted?` returns true.

I investigated this issue and concluded that after the cloning of the record, the status of the transaction is not cleared and, because of this, the code for restoring the status of the record after the rollback is not working correctly.

I can propose a patch for resolve this issue:
[fix_persisted_is_false_after_rollback.patch.gz](https://github.com/rails/rails/files/1620189/fix_persisted_is_false_after_rollback.patch.gz)

### Steps to reproduce
```ruby
# frozen_string_literal: true

begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
  end
end

class User < ActiveRecord::Base
  validates :name, presence: true
end

class BugTest < Minitest::Test
  def test_persisted_is_false_after_rollback
    user = User.new(name: 'test')

    begin
      ActiveRecord::Base.transaction do
        user.save!
        new_user = user.dup
        new_user.name = nil
        new_user.save!
      end
    rescue
      nil
    end

    assert !user.persisted?
  end
end
```

### System configuration
**Rails version**: 5.0.6

**Ruby version**: 2.4.2

### PR DESCRIPTION
**Pull request by yoreek**
Fixes #31670

### CODE REVIEW

**Comment by kamipo** [comment]
Original issue is "ActiveRecord persisted? returns true after rollback when using duped record".

Can you test that issue is fixed?

**Comment by yoreek** [comment]
@kamipo, here is the test before and after the fix:

$ git co master 
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
$ bundle exec ../persisted_after_rollback.rb
Active Record 5.2.0.beta2
-- create_table(:users, {:force=>true})
   -> 0.0050s
Create a clone using dup
persisted? = true
Create a clone using new
persisted? = false

$ git co clear_transaction_state_when_ar_object_is_duped
Switched to branch 'clear_transaction_state_when_ar_object_is_duped'
$ bundle exec ../persisted_after_rollback.rb            
Active Record 5.2.0.beta2
-- create_table(:users, {:force=>true})
   -> 0.0050s
Create a clone using dup
persisted? = false
Create a clone using new
persisted? = false

**Comment by kamipo** [comment]
Yeah, can you add the test in the commit to catch a future regression?

**Comment by yoreek** [comment]
@kamipo done

File: activerecord/test/cases/dup_test.rb [hunk 1]
```diff
@@ -157,5 +158,34 @@ def test_dup_without_primary_key
         record.dup
       end
     end
+
+    def test_dup_transaction_state_and_transaction_record_state_are_cleared
+      topic = Topic.first
+      topic.send(:set_transaction_state, ActiveRecord::ConnectionAdapters::TransactionState.new(:rollback))
+      topic.send(:remember_transaction_record_state)
```
Comment (kamipo) [inline activerecord/test/cases/dup_test.rb]: We don't need to test internal states with private methods as long as it can be tested from public API.
And also, this test case does not show that the state of the record when the transaction was rolled back has been fixed.

**Review by kamipo — CHANGES_REQUESTED** [review]
Can you add CHANGELOG entry what issue is fixed?

File: activerecord/test/cases/dup_test.rb (hunk 1 above)
Comment (yoreek) [reply activerecord/test/cases/dup_test.rb]: Thanks for review.
This test only checks that the transaction state is cleared in the duped record. I think that we must clear this state as well as other statuses. Do you think it is necessary to test the complete scheme with the rollback of the transaction?
And, unfortunately I did not find a public methods to access to `@transaction_state` and `@_start_transaction_state`, could you help me ?

Comment (kamipo) [reply activerecord/test/cases/dup_test.rb]: Since these are internal states we don't have any way to access to the states.
So it is enough to test the transaction behavior which tested in the following test rather than testing the states.

The `test_dup_record_not_persisted_after_rollback_transaction` sufficiently shows which behavior is fixed.
So we simply remove the `test_dup_transaction_state_and_transaction_record_state_are_cleared`.

Comment (yoreek) [reply activerecord/test/cases/dup_test.rb]: ok, I removed the test and added the entry to CHANGELOG.
