### PR TITLE
ActionMailer Email Preview - show date header when present 

### LINKED ISSUE #49788: [includes solution] ActionMailer Email Preview ignoring optional date header
My work requires total isolation of our GH accounts so I can't put up a PR for this right now / am not sure when I will have the bandwidth to do so, but if anyone wants an easy win:

### Steps to reproduce

[ActionMailer::Base#mail](https://api.rubyonrails.org/v7.0/classes/ActionMailer/Base.html#method-i-mail) accepts a `:date` header argument, but the [rails mailers email template doesn't check the date header and always renders Time.current.rfc2822](https://github.com/rails/rails/blob/ea4c48ad3979c8f6688339c62a4a9c3aea9f9a68/railties/lib/rails/templates/rails/mailers/email.html.erb#L96)

```ruby
class MyMailerPreview < ActionMailer::Preview
  def preview
    mail = MailKlass.find(params[:id])

    MyMailer.view_sent(mail)
  end
end

class MyMailer < ActionMailer::Base
  def view_sent(email)
    mail(
      to: email.email,
      subject: email.subject,
      date: email.sent_at
    ) do |format|
      format.html { render email.template }
    end
  end
end
```
My use case is previewing an email that was already sent.

### Expected behavior

ActionMailer template header section should render the value of `@mail.header['date']` (from `mail(date: some_timestamp)`) if the header is present
### Actual behavior

Previewed emails always render the result of `Time.current.rfc2822` without checking for the presence of `@email.header['date']`

### Solution
Replace this
https://github.com/rails/rails/blob/ea4c48ad3979c8f6688339c62a4a9c3aea9f9a68/railties/lib/rails/templates/rails/mailers/email.html.erb#L96

with this:
```ruby
    <dd id="date"><%= @email.header['date'] || Time.current.rfc2822 %></dd>
```

### System configuration
**Rails version**:
7x
**Ruby version**:
3.2

### PR DESCRIPTION
**Pull request by sampatbadhe**
### Detail

ActionMailer Email Preview - show date header when present or fallback to Time.current.rfc2822

Resolves #49788

Co-authored-by: @allisonphillips

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by Edouard-chin** [comment]
Should be quick and easy to add a test, mind adding one similar to this one ? https://github.com/rails/rails/blob/2b093271cf2e4b209039d1f183dcbcc642cc0d09/railties/test/application/mailer_previews_test.rb#L962

**Comment by sampatbadhe** [comment]
Thank you for review @Edouard-chin. I have added tests, could you please check.

File: railties/test/application/mailer_previews_test.rb [hunk 1]
```diff
@@ -989,6 +989,66 @@ def foo
...
+        class NotifierPreview < ActionMailer::Preview
+          def foo
+            Notifier.foo
+          end
+        end
+      RUBY
+
+      app("development")
+
+      Time.stub(:current, Time.local(2023, 10, 20, 10, 20, 30)) do
```
Comment (Edouard-chin) [inline railties/test/application/mailer_previews_test.rb:1017]:
```suggestion
      travel_to(Time.local(2023, 10, 20, 10, 20, 30)) do
```

**Review by Edouard-chin — COMMENTED** [review]
A minor suggestion, but it looks great otherwise. Thanks!

**Comment by jonathanhefner** [comment]
I felt like this was worth a CHANGELOG entry, so I pushed a commit to add one.

Thank you, @sampatbadhe! :mailbox:  And thank you, @Edouard-chin! :wave:
