### PR TITLE
close hijacked i/o socket after use (fixes #25613)

### LINKED ISSUE #25613: ActionCable does not close its hijacked I/O socket
### Steps to reproduce

1. Start a web server using Phusion Passenger that opens a websocket connection
2. Refresh the page a few times

### Expected behavior
There should never be more than 1 concurrent session when you run `passenger-status`. And when you close the website there should be 0.

### Actual behavior
Sessions are leaked. The amount of open sessions will steadily increase.

### System configuration
**Rails version**: Rails 5.0.0rc2 (and probably 5.0.0 too, so sorry I didn't know you guys were gonna release tonight)

**Ruby version**: 2.3

Hey guys sorry I was doing some performance testing using Phusion Passenger today, and I found this bug. I assume it's in Puma as well though I don't know how to make Puma give that info. I'll follow up with a PR.

Some extra info:

According to the Rack spec it is the applications responsibility to close the hijacked I/O socket after its done. This should likely be done in `ActionCable::Connection::Stream#clean_hijacked_io`.

### PR DESCRIPTION
**Pull request by tinco**
### Summary

This PR Fixes #25613. 
### Other Information

This behaviour is required as per the Rack spec located here:

http://www.rubydoc.info/github/rack/rack/file/SPEC

Specifically:

> "After the headers have been sent, and this hijack callback has been called, the application is now responsible for the remaining lifecycle of the IO. The application is also responsible for maintaining HTTP semantics."

### CODE REVIEW

**Comment by tinco** [comment]
I should've tested better, this PR doesn't actually solve the problem. I'll investigate a little further. Perhaps it's a problem with Passenger after all. I've made an issue here as well: https://github.com/phusion/passenger/issues/1836

**Comment by tinco** [comment]
Argh, that's what I get for pushing commits at 1am, forgot to uncomment it after checking if the test properly goes red.

So yes, this patch definitely fixes the socket leaks in Passenger and possibly also in Puma.

**Comment by rafaelfranca** [comment]
This looks good to me. Could you squash your commits?

r? @matthewd since I never used Action Cable I prefer to you give the last word.

**Comment by tinco** [comment]
OK squashed them :)

File: actioncable/lib/action_cable/connection/stream.rb [hunk 1]
```diff
@@ -50,6 +50,7 @@ def hijack_rack_socket
         def clean_rack_hijack
           return unless @rack_hijack_io
           @event_loop.detach(@rack_hijack_io, self)
+          @rack_hijack_io.close if !@rack_hijack_io.closed?
```
Comment (matthewd) [inline actioncable/lib/action_cable/connection/stream.rb]: Can it sometimes already be closed? :confused:

**Comment by tinco** [comment]
You're right, it's got sole responsibility over the socket, nothing else is going to close it. Fixed it. In the PR doc it said you preferred it if I didn't squash the commits right? Or is that only for long running PR's?

**Comment by matthewd** [comment]
Thanks, yeah, go ahead and squash now... that is indeed more for ongoing/substantial reviews.

**Comment by tinco** [comment]
Alright done :)

**Comment by matthewd** [comment]
Thanks! :heart:

**Comment by rafaelfranca** [comment]
Backported in 9cbf3b3

**Comment by lex148** [comment]
I can confirm. This fix was not merged into the 5.0.1 release but is in its release notes. Can we have it merged in for 5.0.2?

**Comment by matthewd** [comment]
@lex148 could you clarify how you confirmed that, please? Because I certainly believe it's there.

**Comment by lex148** [comment]
I download the gem file for actioncable-5.0.1 extracted and verified the patch was missing.
https://rubygems.org/downloads/actioncable-5.0.1.gem
also
https://github.com/rails/rails/blob/5-0-2/actioncable/lib/action_cable/connection/stream.rb
The fix "@rack_hijack_io.close" is missing

**Comment by matthewd** [comment]
It got moved: https://github.com/rails/rails/commit/e6b435d9d4d05bfc422eb4d1a73f3a1642332dbd

**Comment by lex148** [comment]
Awesome. thanks for your help
