### PR TITLE
Fix `#to_query` to not include `=` for nil values

### LINKED ISSUE #28322: NilClass.to_query(key) does not round-trip with Rack::Utils.parse_nested_query
### Steps to reproduce

It should ideally be possible to round-trip from a `Hash` or `ActionController::Parameters` object to a query string and back. Currently, this does not work when the value is `nil`, in which case the value round-trips to `''` instead of `nil`.

See this gist: https://gist.github.com/md5/be5d072bb2c853baf2143dd5faba69cb

### Expected behavior
Having a `nil` value in the parameters hash should result in a key with no value in the query string.

### Actual behavior
Currently, a `nil` value results in the same query string as a blank string, namely `key=`.

### System configuration
**Rails version**: Any

**Ruby version**: Any

### PR DESCRIPTION
**Pull request by byroot**
Fix: https://github.com/rails/rails/issues/28322

This is more consistent with the behavior of `Rack::Utils.parse_nested_query`.

### CODE REVIEW

File: activesupport/lib/active_support/core_ext/object/to_query.rb [hunk 1]
```diff
@@ -16,6 +16,11 @@ def to_query(key)
 end
 
 class NilClass
+  # Returns a CGI-escaped +key+.
+  def to_query(key)
+    "#{CGI.escape(key.to_param)}"
```
Comment (seanpdoyle) [inline activesupport/lib/active_support/core_ext/object/to_query.rb:21]: What is the significance of the wrapping String interpolation?

Can `CGI.escape` return something other than a String? Does interpolation produce something different from `to_s`?

Comment (byroot) [reply activesupport/lib/active_support/core_ext/object/to_query.rb]: Nah you're right.

**Comment by bogdan** [comment]
Ugh, brutal change...
