### PR TITLE
ActionMailer default values should not be evaluated when overridden

### LINKED ISSUE #42415: ActionMailer default values should not be evaluated when overridden
### Steps to reproduce
I opened a PR #41157 in January solving a small bug on ActionMailer default values that are evaluated even when they are overridden in the mailer instance method.

I never opened an issue because I could submit the PR directly. However it was marked as stale by rails-bot before someone could review it and I would love to solve this bug (the test is still failing today).

Here is the example: 

```rb
class LazyProcMailer < ActionMailer::Base
  default from: -> { flunk }, to: -> { flunk }

  def welcome
    mail from: "overridden-from@example.com", to: "overridden-to@example.com"
  end
end
```

### Expected behavior
Sending the welcome email should not fail because `from` and `to` default values are overridden in the `#welcome` method.

### Actual behavior
Sending the welcome email raises an error because the default `from` and `to` procs are evaluated even if they are overridden later on the `#welcome` method.

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 3.0.1

### PR DESCRIPTION
**Pull request by alexandreruban**
Hello !

### Summary

I ran into an issue with ActionMailer today where, when I override the default `from` or `to` headers that are defined with procs, those procs are still evaluated even if they are overridden at the action level (in the mail method). This is a problem because even if I know that the content of the proc will raise an exception and I try to override those procs at the action level, I will still get an error.

I added a test with the `LazyProcMailer`. I would like the welcome action not to raise an error.

```rb
class LazyProcMailer < ActionMailer::Base
  default from: -> { flunk }, to: -> { flunk }

  def welcome
    # This should not raise an error because the from and to options are overridden
    # in the #mail method
    mail from: "overridden-from@example.com", to: "overridden-to@example.com"
  end
end
```

### Other Information

I didn't open an issue because I could submit a pull request directly but please tell me if I need to open one. This is my first contribution to Rails so I hope I made things right. Please tell me if I need to change anything!
Thanks for Rails, it's awesome!

Closes #42415

### CODE REVIEW

**Comment by ghiculescu** [comment]
This is still relevant per https://github.com/rails/rails/issues/42415

**Comment by ghiculescu** [comment]
image

@alexandreruban do you want to reopen the PR, or make a new one?

**Comment by alexandreruban** [comment]
@ghiculescu can you repoen the PR now? I forced push after I rebased on `main` earlier today.

File: actionmailer/lib/action_mailer/base.rb [hunk 1]
```diff
@@ -901,11 +901,8 @@ def self.supports_path? # :doc:
       end
 
       def apply_defaults(headers)
-        default_values = self.class.default.transform_values do |value|
-          compute_default(value)
-        end
-
-        headers_with_defaults = headers.reverse_merge(default_values)
+        headers_with_defaults = headers.reverse_merge(self.class.default)
+        headers_with_defaults = headers_with_defaults.transform_values { |value| compute_default(value) }
```
Comment (p8) [inline actionmailer/lib/action_mailer/base.rb:905]: This changes will also call `compute_default` on `headers`, instead of just `self.class.default`.
So this would allow passing procs to mail?
```ruby
mail(from: -> { 'x' })
```

File: actionmailer/test/mailers/lazy_proc_mailer.rb [hunk 2]
```diff
@@ -0,0 +1,9 @@
+# frozen_string_literal: true
+
+class LazyProcMailer < ActionMailer::Base
+  default from: -> { flunk }, to: -> { flunk }
+
+  def welcome
+    mail from: "overridden-from@example.com", to: "overridden-to@example.com"
+  end
+end
```
Comment (p8) [inline actionmailer/test/mailers/lazy_proc_mailer.rb:9]: Maybe we could reuse `ProcMailer` instead and use a proc for `to`:
```
class ProcMailer < ActionMailer::Base
  default to: -> { "system@test.lindsaar.net" },
  ...
```
https://github.com/rails/rails/blob/main/actionmailer/test/mailers/proc_mailer.rb#L4

File: actionmailer/lib/action_mailer/base.rb (hunk 1 above)
Comment (alexandreruban) [reply actionmailer/lib/action_mailer/base.rb:905]: Yes you are right the change allows this even though I don't think someone would use it.

If you don't like it maybe we could keep something closer to what was there before by doing something like:
```rb
def apply_defaults(headers)
  default_values = self.class.default.except(*headers.keys).transform_values do |value|
    compute_default(value)
  end

  headers_with_defaults = headers.reverse_merge(default_values)
  headers_with_defaults[:subject] ||= default_i18n_subject
  headers_with_defaults
end
```

Now that I see it, I think it's better if I change it, what do you think?

File: actionmailer/test/mailers/lazy_proc_mailer.rb (hunk 2 above)
Comment (alexandreruban) [reply actionmailer/test/mailers/lazy_proc_mailer.rb:9]: I think I need the `LazyProcMailer` here. 

What I want to test here is that the default procs for `from` and `to` are *never* evaluated in the process (and so the flunk never raises an error). This test allows me to make sure about that. 

What do you think? Maybe the name `LazyProcMailer` is confusing and I should change it to something like `NeverEvaluatedDefaultHeadersMailer` to make it more precise?

File: actionmailer/lib/action_mailer/base.rb (hunk 1 above)
Comment (p8) [reply actionmailer/lib/action_mailer/base.rb:905]: Ah sorry, I finally understand the issue. I shouldn't review on this late at night.
I think the original implementation is fine.

File: actionmailer/test/mailers/lazy_proc_mailer.rb (hunk 2 above)
Comment (p8) [reply actionmailer/test/mailers/lazy_proc_mailer.rb:9]: I see the test class also has a with_default method you can use:
```ruby  
  test "proc default values are not evaluated when overridden" do
    with_default BaseMailer, to: -> { flunk } do
        email = BaseMailer.welcome(to: "overridden-from@example.com")
        assert_equal "overridden-from@example.com", email.to
      end
    end
  end
  ```

Comment (alexandreruban) [reply actionmailer/test/mailers/lazy_proc_mailer.rb]: Yes nice! 
I made the change as well, it should be all good now! 

Thank you very much again for your review 🙏
