### PR TITLE
Redesign ActionView::Template::Handlers::ERB.find_offset to handle edge cases

### LINKED ISSUE #121: Partial incompatibility with rails 7.1
I realised after upgrading to rails 7.1 that when I encounter an exception in the view, I do not get the familiar `ActionDispatch::DebugExceptions` page anymore, but rather my `exceptions_app`

After much digging, I realised there is a crash inside `ActionDispatch::DebugExceptions` when trying to display the backtrace, thus making the middleware not render the page, and the exception ends up getting caught by `ActionDispatch::ShowExceptions` down the road.

Here's the exception and the stacktrace : 

```
eval error: undefined method `last' for nil:NilClass
/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.1.1/lib/action_view/template/handlers/erb.rb:142:in `find_offset'
/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.1.1/lib/action_view/template/handlers/erb.rb:46:in `translate_location'
/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.1.1/lib/action_view/template.rb:229:in `translate_location'
/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/exception_wrapper.rb:258:in `spot'
/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/exception_wrapper.rb:302:in `extract_source'
/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/exception_wrapper.rb:206:in `block in source_extracts'
/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/exception_wrapper.rb:205:in `map'
/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/exception_wrapper.rb:205:in `source_extracts'
/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:126:in `create_template'
/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:78:in `render_for_browser_request'
  (rdbg)/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:1:in `rescue in call'
```

`better_html` sounded like a good suspect, removing it from the bundle fixes the issue.

Alternatively, disabling runtime checks fixes the issue too : 

```
BetterHtml.configure do |config|
  config.template_exclusion_filter = proc { true }
end
```

So it seems that the custom parser conflicts with the way rails 7.1 tries to extract the source.

### LINKED ISSUE #53388: Rails hangs when showing highlighted source of an exception from an erb file in development mode
### Steps to reproduce

I created a sample app for reproduction of this problem [here](https://github.com/Masa331/repro). To reproduce it clone the repo, run the application in development mode and try to visit the app in a browser. Or create your own fresh Rails app with `rails new test_app` and apply the same changes as in the reproduction commit [here](https://github.com/Masa331/repro/commit/fe811345b1c13fbd0d4547a746a4b4c0c4482151).

The problematic part is the ERB template:
```erb
<div id='<%= non_existing_method %>'>
```

### Expected behavior
Rails should show the classical error page reporting "undefined local variable or method `non_existing_method'"

### Actual behavior
The application hangs indefinitely without showing the error page. I traced the problem to [here](https://github.com/rails/rails/blob/eb7cd90230ff960940459811c2acacfe75a6daed/actionview/lib/action_view/template/handlers/erb.rb#L118) where it gets stuck in a never ending loop trying to match a string `<div id='` against a string `@virtual_path = "application/index";;@output_buffer.safe_append='<!-- BEGIN app/views/application/index.html.erb -->'; @output_buffer.safe_append='<div id=\''.freeze; @output_buffer.append=( foobar ); @output_buffer.safe_append='\'>`. In the second string there is a slash before the single quote and so no match is ever made.

This problem doesn't occur when the quotes in the ERB template are changed from single quotes to double quotes.

### System configuration
**Rails version**: 7.2.1.1

**Ruby version**: 3.2.4

### PR DESCRIPTION
**Pull request by martinemde**
### Motivation / Background

The code for finding offsets in the ERB templates outright fails in some cases, causing 500s in the error template. In other cases it will bail out early when it's possible to find and highlight correctly.

### Detail

This PR fixes many of the issues that regularly occur and correctly highlights more often. Also adds test coverage of the translate_location method on ActionView::Template, many of which failed before this fix.

### Additional information

Problems in `better-html` gem originally prompted me to dig into this, but this solves many rails-only highlight failures or crashes depending on the template. For example, the following template will cause the request to loop forever in current rails:

```erb
<%= goodcode %><%= nomethoderror %>
```

Any template where the compiled code doesn't contain the template code will also loop forever (for example a bug in the template compiler or something changing spacing).

`better-html` also reliably causes the error page to 500 because it has duplicate copies of the template code in the compiled template. The only way to fix this in better-html would be to fully patch this method to make it correct, which causes its own problems. The solution I suggest here supports better-html without doing anything explicit to do so. It merely supports the case where a string could occur multiple times in the compiled output which happens in vanilla rails, but less often than in `better-html`

Fixes: https://github.com/Shopify/better-html/issues/121
Probably Fixes: https://github.com/rails/rails/issues/53388 (I found the same infinite loop and have added test coverage for most of these cases)

CC: @byroot and @jhawthorn because you have both been looking at related issues. FYI @tenderlove, it looks like you wrote the previous implementation. 

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [X] Tests are added or updated if you fix a bug or add a feature.
* [X] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by martinemde** [comment]
I have this other pending commit to solve a problem brought up in  #48184.

https://github.com/rails/rails/commit/740e220858b4497a7ee69753d33f8f5ae1da3de8

Since I had to change the behavior of the tokenizer, I thought we could decide separately from this PR so I don't delay the rest of this fix.

File: actionview/lib/action_view/template/handlers/erb.rb [hunk 1]
```diff
@@ -105,51 +104,58 @@ def valid_encoding(string, encoding)
...
+        #   a. If B: start over with next token set (B, C).
+        #   b. If A: test error_column or advance scanner.
+        #   c. Otherwise: Advance 1 byte
+        #
+        # Prioritize matching the next token over the current token once
+        # a match for the current token has been found. This is to prevent
+        # the current token from looping past the next token if they both
+        # match (i.e. if the current token is a single space character).
         def find_offset(compiled, source_tokens, error_column)
+          require "strscan"
```
Comment (byroot) [inline actionview/lib/action_view/template/handlers/erb.rb:126]: Why move this `require` ? There's a bunch of other places in Rails that will require it anyway.

Comment (martinemde) [reply actionview/lib/action_view/template/handlers/erb.rb:126]: I was mirroring ERB::Util.tokenizer since they run together, but I have no problem with moving it back.

File: actionview/lib/action_view/template/handlers/erb.rb [hunk 2]
```diff
@@ -105,51 +105,57 @@ def valid_encoding(string, encoding)
...
-                unless compiled.scan(str)
-                  raise LocationParsingError, "Couldn't find code snippet"
-                end
-              end
-            when :OPEN
-              next_tok = source_tokens.first.last
-              loop do
-                break if compiled.match?(next_tok)
-                compiled.getch
+                compiled.pos += 1
```
Comment (martinemde) [inline actionview/lib/action_view/template/handlers/erb.rb:143]: For the curious, I tested this to make sure my assumption was correct and += is faster than `getch` or `get_byte`:

```
 Warming up --------------------------------------
            get_byte     8.005k i/100ms
              += pos    12.330k i/100ms
Calculating -------------------------------------
            get_byte     80.199k (± 0.8%) i/s -    408.255k in   5.090859s
              += pos    122.756k (± 0.7%) i/s -    616.500k in   5.022371s
```
Not like we're doing this a bunch or care about performance, but since I changed the way it worked it seemed like I should make sure I wasn't making it worse.

File: actionview/test/template/template_test.rb [hunk 3]
```diff
@@ -314,4 +326,111 @@ def test_template_inspect
...
+    compiled = "\n'.freeze; @output_buffer.append=  nomethoderror ; @output_buffer.safe_append='\n"
+
+    backtrace_location = Data.define(:lineno).new(lineno: 1)
+    spot = spot_highlight(compiled, highlight, first_lineno: 2, last_lineno: 2)
+    expected = spot_highlight(source, highlight, snippet: compiled)
+
+    assert_equal expected, new_template(source).translate_location(backtrace_location, spot)
+  end
+
+  def test_template_translate_location_with_multibye_string_before_highlight
```
Comment (byroot) [inline actionview/test/template/template_test.rb:354]: This test is failing on CI:

```
Failure:
TestERBTemplate#test_template_translate_location_with_multibye_string_before_highlight [test/template/template_test.rb:363]:
--- expected
+++ actual
@@ -1,2 +1,3 @@
-{:first_column=>5, :last_column=>18, :snippet=>"¥'.freeze; @output_buffer.append=  nomethoderror ; @output_buffer.safe_append='
-", :first_lineno=>1, :last_lineno=>1, :script_lines=>["¥<%= nomethoderror %>"]}
+{:first_column=>35, :last_column=>48, :snippet=>"¥'.freeze; @output_buffer.append=  nomethoderror ; @output_buffer.safe_append='
+", :first_lineno=>1, :last_lineno=>1, :script_lines=>["¥'.freeze; @output_buffer.append=  nomethoderror ; @output_buffer.safe_append='
+"]}
```

Comment (martinemde) [reply actionview/test/template/template_test.rb:354]: I noticed this last night too. 😬 It _was_ passing so I'll figure out what I changed.

The only failure is the multi-byte test so it's probably some byte/char inconsistency. I'll update when it's fixed.

Comment (martinemde) [reply actionview/test/template/template_test.rb:354]: There was still an unrelated failure. I re-pushed after clarifying the CHANGELOG entry to force a rebuild, but I'll just leave it alone if it fails obtaining a connection again and you can retrigger the build.
