### PR TITLE
Make ActiveSupport HashWithIndifferentAccess#to_options and alias for HashWithIndifferentAccess#symbolize_keys

### LINKED ISSUE #34359: ActiveSupport HashWithIndifferentAccess#to_options is not and alias for #symbolize_keys as of 5.2.0
### Summary

Prior to 5.2.0 (de9e323, 2cad8d7), `HashWithIndifferentAccess#to_options` acted as an alias to `HashWithIndifferentAccess#symbolize_keys`. Now, `#to_options` returns an instance of `HashWithIndifferentAccess` while `#symbolize_keys` returns and instance of `Hash`.

### Steps to reproduce

To reproduce see these [test cases for 5.2.0](https://gist.github.com/weilandia/1011fa45721b7c78c88e370e4fa37b0a).

### Expected behavior
`HashWithIndifferentAccess#to_options` should return an instance of `Hash` as it did prior to 5.2.0.  Though not explicit in the documentation, I would argue that since documentation for `Hash#to_options` states it is an alias for `Hash#symbolize_keys`, it should behave the same way for `HashWitIndifferentAccess`.

As an example for how this might impact current codebases that upgrade to Rails 5.2, if `HashWithIndifferentAccess#to_options` was used and the result was passed to a method with keyword arguments, it would work in 5.1x but not in 5.2x. This example is illustrated in both the [5.2 test cases](https://gist.github.com/weilandia/1011fa45721b7c78c88e370e4fa37b0a). and the [5.1 test cases](https://gist.github.com/weilandia/821a7092432f211469ba1cdbbca9831d).

### Actual behavior
`HashWithIndifferentAccess#to_options` returns an instance of `HashWithIndifferentAccess`

### System configuration
**Rails version**:
5.2

**Ruby version**:
Tested in 2.5.1 and 2.3.7

### PR DESCRIPTION
**Pull request by weilandia**
Fixes #34359

### Summary

Prior to 5.2.0 (de9e323, 2cad8d7), `HashWithIndifferentAccess#to_options` acted as
an alias to `HashWithIndifferentAccess#symbolize_keys`. Now, `#to_options`
returns an instance of `HashWithIndifferentAccess` while `#symbolize_keys`
returns and instance of `Hash`.

This pr makes it so `HashWithIndifferentAccess#to_options` acts as an
alias for `HashWithIndifferentAccess#symbolize_keys` once again.

### Other Information

See #34359 

Thanks!

### CODE REVIEW

File: activesupport/lib/active_support/hash_with_indifferent_access.rb [hunk 1]
```diff
@@ -289,6 +289,7 @@ def deep_stringify_keys; dup end
     undef :symbolize_keys!
     undef :deep_symbolize_keys!
     def symbolize_keys; to_hash.symbolize_keys! end
+    alias_method :to_options,  :symbolize_keys
```
Comment (gmcgibbon) [inline activesupport/lib/active_support/hash_with_indifferent_access.rb]: Nitpick: there only needs to be space between `:to_options,` and `:symnolize_keys`.

**Review by gmcgibbon — COMMENTED** [review]
I think this counts as a bug. Could you please add a changelog entry?

File: activesupport/lib/active_support/hash_with_indifferent_access.rb (hunk 1 above)
Comment (weilandia) [reply activesupport/lib/active_support/hash_with_indifferent_access.rb]: 👍

**Comment by weilandia** [comment]
@gmcgibbon thanks for the review!  I addressed your comments -- let me know if anything else stands out.

Also, do you think this issue warrants a note in the release notes/upgrade guide for 5.2?
