### PR TITLE
Avoid race condition on subscription confirmation

### LINKED ISSUE #25381: ActionCable: Unable to find subscription with identifier...
Rails 5.0.0.rc1
Ruby 2.3.1 MRI + Puma

I've only one channel `ApiChannel`, the client (iOS app) connects to the back-end, receives the subscription confirmation and immediately sends a command. Sometimes the client is greeted with `RuntimeError` exception:
https://github.com/rails/rails/blob/a8df1bc345bf062e98bda64ef9638f65292c4b56/actioncable/lib/action_cable/connection/subscriptions.rb#L70

I've added some debugging statements to the code and from time to time the `subscriptions` Hash is indeed empty (the client issues `subscribe` command before), sometimes `identifiers` method returns empty Array for non-empty `subscriptions` (but it's just `.keys` on it).

I spent a lot of time debugging this and I'm out of ideas. Am I doing anything wrong here? Any help would be appreciated!

### PR DESCRIPTION
**Pull request by palkan**
The problem is the follows:
- client sends subscriptions request;
- channel's `#subscribe` looks smth like:

``` ruby
def subscribe
  stream_from 'channel'

  # do some heavy stuff or just
  sleep 5
end
```
- channels sends a _defferred_ subscription confirmation (earlier than `#subscribe` finishes executing due to https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/channel/streams.rb#L86-L88);
- client's `connected` callback looks like this:

``` js
connected: ->
  @perfom 'some_action'
```
- `RuntimeError - Unable to find subscription with identifier` happens, 'cause we still don't have this identifier in `Connection#subscriptions` .

Fixes #25381.

### CODE REVIEW

**Comment by tomekw** [comment]
I can confirm it fixes the issue!

**Comment by maclover7** [comment]
cc @matthewd

**Comment by matthewd** [comment]
Is there another related race here? If you call `stream_from` twice, we'll transmit the confirmation when the first completes, instead of when they all have.

Assuming I'm not imagining the above, it seems like we should be able to fix them together. Perhaps by having an AtomicFixnum keep track of how many "things" are pending before we're fully subscribed, and doing the transmit when that reaches zero?

File: actioncable/test/test_helper.rb [hunk 1]
```diff
@@ -66,8 +66,11 @@ class ActionCable::TestCase < ActiveSupport::TestCase
   end
 
   def wait_for_executor(executor)
-    until executor.completed_task_count == executor.scheduled_task_count
+    # do not wait forever
+    timeout = 2
+    until timeout > 0 && executor.completed_task_count == executor.scheduled_task_count
```
Comment (matthewd) [inline actioncable/test/test_helper.rb]: This seems fair :+1:. But let's raise if we reach the timeout, so we're not relying on the surrounding test noticing the problem.

Comment (palkan) [inline actioncable/test/test_helper.rb]: Yep, make sense

**Comment by palkan** [comment]
@matthewd Updated with `AtomicFixnum`.

File: actioncable/lib/action_cable/channel/base.rb [hunk 2]
```diff
@@ -202,17 +212,21 @@ def transmit(data, via: nil)
         end
 
         def defer_subscription_confirmation!
-          @defer_subscription_confirmation = true
+          @defer_subscription_confirmation_counter.increment
         end
 
         def defer_subscription_confirmation?
-          @defer_subscription_confirmation
+          @defer_subscription_confirmation_counter.value.positive?
```
Comment (kaspth) [inline actioncable/lib/action_cable/channel/base.rb]: `positive?` is only available on Ruby 2.3, we need to require our core extension.

File: actioncable/lib/action_cable/channel/base.rb [hunk 3]
```diff
@@ -153,6 +155,14 @@ def initialize(connection, identifier, params = {})
         subscribe_to_channel
       end
 
+      # This method is called after subscription has been added to the channel.
+      # Send confirmation here to avoid race conditions when client tries to perform actions
+      # right after receiving confirmation.
+      def registered!
```
Comment (kaspth) [inline actioncable/lib/action_cable/channel/base.rb]: Either we make this sound more like `subscribed` (and remove the !) or make it clearer what it does with more words akin to `defer_subscription_confirmation!`

Comment (kaspth) [inline actioncable/lib/action_cable/channel/base.rb]: `registered` also adds an extra concept that closely mirrors `subscribed` and `confirmed` — is it meant to communicate that a subscription is about to be confirmed? Could we make that intent come out further?

File: actioncable/lib/action_cable/connection/subscriptions.rb [hunk 4]
```diff
@@ -29,7 +29,9 @@ def add(data)
         subscription_klass = id_options[:channel].safe_constantize
 
         if subscription_klass && ActionCable::Channel::Base >= subscription_klass
-          subscriptions[id_key] ||= subscription_klass.new(connection, id_key, id_options)
+          subscription = subscription_klass.new(connection, id_key, id_options)
+          subscriptions[id_key] ||= subscription
+          subscription.registered!
```
Comment (kaspth) [inline actioncable/lib/action_cable/connection/subscriptions.rb]: This allocates an extra instance of the `subscription_klass` needlessly if it's already there. How about:

```ruby
subscriptions[id_key] ||= subscription_klass.new(connection, id_key, id_options).
  tap(&:registered!)
```

File: actioncable/test/channel/stream_test.rb [hunk 5]
```diff
@@ -101,6 +103,7 @@ class StreamTest < ActionCable::TestCase
         connection = TestConnection.new
 
         channel = ChatChannel.new connection, "test_channel"
+        channel.registered!
```
Comment (kaspth) [inline actioncable/test/channel/stream_test.rb]: Is it a smell that we have to call `registered!` in tests?

File: actioncable/lib/action_cable/channel/base.rb (hunk 2 above)
Comment (palkan) [inline actioncable/lib/action_cable/channel/base.rb]: Yep, just noticed failing specs for 2.2.x.

Maybe it's better to avoid additional deps and use `> 0`?

File: actioncable/lib/action_cable/connection/subscriptions.rb (hunk 4 above)
Comment (palkan) [inline actioncable/lib/action_cable/connection/subscriptions.rb]: Yeah, we can even check the existence of the key before _constantizing_.

File: actioncable/lib/action_cable/channel/base.rb (hunk 3 above)
Comment (palkan) [inline actioncable/lib/action_cable/channel/base.rb]: We can go with the existing `subscribe_to_channel`:
- remove `subscribe_to_channel` call from `initialize';
- make `subscribe_to_channel` public;
- call `subscription.subscribe_to_channel` in `Connection::Subscriptions#add`.

It make sense, 'cause we already have `Channel::Base#unsubscribe_from_channel` public method.

File: actioncable/test/channel/stream_test.rb (hunk 5 above)
Comment (palkan) [inline actioncable/test/channel/stream_test.rb]: Actually, we don't need it here at all.

File: actioncable/lib/action_cable/channel/base.rb (hunk 3 above)
Comment (matthewd) [inline actioncable/lib/action_cable/channel/base.rb]: Actually, if we're going to make the caller invoke something after the channel is "really ready"... should we just make it `subscribe_to_channel`?

(Sorry, I realise that makes the AtomicFixnum change pointless for this problem 😔 -- though still separately valuable for the multi-subscribe other race)

File: actioncable/lib/action_cable/channel/base.rb [hunk 6]
```diff
@@ -235,11 +249,7 @@ def subscribe_to_channel
             subscribed
           end
 
-          if subscription_rejected?
-            reject_subscription
-          else
-            transmit_subscription_confirmation unless defer_subscription_confirmation?
-          end
+          reject_subscription if subscription_rejected?
```
Comment (matthewd) [inline actioncable/lib/action_cable/channel/base.rb]: We probably need to avoid `transmit_subscription_confirmation` if `subscription_rejected?`... otherwise it seems we could transmit a confirmation *after* we've transmitted a rejection.

File: actioncable/lib/action_cable/channel/streams.rb [hunk 7]
```diff
@@ -84,7 +84,8 @@ def stream_from(broadcasting, callback = nil, coder: nil, &block)
 
         connection.server.event_loop.post do
           pubsub.subscribe(broadcasting, handler, lambda do
-            transmit_subscription_confirmation
+            @defer_subscription_confirmation_counter.decrement
+            transmit_subscription_confirmation unless defer_subscription_confirmation?
```
Comment (matthewd) [inline actioncable/lib/action_cable/channel/streams.rb]: Let's name this, and push it into `base.rb` -- I know this is just a concern on the same class, but it still feels like we're getting too deep into details that don't belong here

File: actioncable/lib/action_cable/channel/base.rb (hunk 3 above)
Comment (matthewd) [inline actioncable/lib/action_cable/channel/base.rb]: ... and that's what I get for not hitting refresh 😅

File: actioncable/lib/action_cable/channel/streams.rb (hunk 7 above)
Comment (palkan) [inline actioncable/lib/action_cable/channel/streams.rb]: Done

File: actioncable/lib/action_cable/channel/base.rb [hunk 8]
```diff
@@ -201,18 +214,28 @@ def transmit(data, via: nil)
...
         end
 
         def subscription_confirmation_sent?
           @subscription_confirmation_sent
         end
 
+        def registered?
+          @registered
+        end
+
```
Comment (matthewd) [inline actioncable/lib/action_cable/channel/base.rb]: ✂️

File: actioncable/lib/action_cable/channel/base.rb [hunk 9]
```diff
@@ -169,6 +170,18 @@ def perform_action(data)
         end
       end
 
+      # This method is called after subscription has been added to the connection.
+      # Send confirmation here to avoid race conditions when client tries to perform actions
+      # right after receiving confirmation.
```
Comment (matthewd) [inline actioncable/lib/action_cable/channel/base.rb]: This comment feels like it's describing the change more than the method. In fact, we were already sending the confirmation here -- this is the method that decides (via `subscribed`) whether the subscription is going to be accepted or rejected, after all.

File: actioncable/lib/action_cable/channel/base.rb [hunk 10]
```diff
@@ -144,13 +144,14 @@ def initialize(connection, identifier, params = {})
 
         # When a channel is streaming via pubsub, we want to delay the confirmation
         # transmission until pubsub subscription is confirmed.
-        @defer_subscription_confirmation = false
+        #
+        # We use atomic fixnum to track the number of waiting tasks to avoid race conditions
```
Comment (matthewd) [inline actioncable/lib/action_cable/channel/base.rb]: Like the one below, this comment isn't pulling its weight: here it just seems to be describing the line of code. Let's change it to instead focus on the thing the assignment doesn't tell us:

```ruby
#
# The counter starts at 1 because it's awaiting a call to #subscribe_to_channel.
```

**Comment by palkan** [comment]
@matthewd Anything else I can do here?

**Comment by matthewd** [comment]
Backported as 90a530cad994892dc2b125e0543eda3eca8a9205.

Thanks! :heart:
