### PR TITLE
Stop appending preload links once the head is already 1kB

### LINKED ISSUE #48402: Link headers generated by Rails may exceed nginx's upstream limit
### Steps to reproduce

1. Create a view with 100s of javascript_include_tags.
2. You now have a response with a fairly large Link header. 
3. If that Link header is over 4kb and you are using Nginx as a reverse proxy, Nginx serves an error with `upstream sent too big header while reading response header from upstream`.

Nginx requires that the _entire_ headers of an upstream response be less than the configured `proxy_buffer_size`, which is only 4kb by default on 64bit Linux. 

Currently, Rails can generate a Link header of unlimited size (split into 8kb field/value pairs). 

### Expected behavior

At some point, adding additional assets to the Link header is not really useful. The browser will only download so many assets at once.

Should we have a limit here?

cc @casperisfine

### PR DESCRIPTION
**Pull request by casperisfine**
Fix: https://github.com/rails/rails/issues/48402

Some HTTP client and proxies have a 4kiB header limit, but more importantly including preload links has diminishing returns so it's best to not go overboard

1kB worth of preload links should be plenty.

cc @nateberkopec

### CODE REVIEW

File: actionview/lib/action_view/helpers/asset_tag_helper.rb [hunk 1]
```diff
@@ -644,30 +647,15 @@ def send_preload_links_header(preload_links, max_header_size: MAX_HEADER_SIZE)
...
-            # rindex count characters not bytes, but we assume non-ascii characters
-            # are rare in urls, and we have a 192 bytes margin.
-            last_line_offset = header.rindex("\n")
-            last_line_size = if last_line_offset
-              header.bytesize - last_line_offset
-            else
-              header.bytesize
-            end
-
+            header = +response.headers["Link"].to_s
```
Comment (gklsan) [inline actionview/lib/action_view/helpers/asset_tag_helper.rb:650]: @casperisfine Could you please help me to understand the use case of `+` here?

File: actionview/lib/action_view/helpers/asset_tag_helper.rb [hunk 2]
```diff
@@ -644,30 +647,15 @@ def send_preload_links_header(preload_links, max_header_size: MAX_HEADER_SIZE)
...
             preload_links.each do |link|
-              if link.bytesize + last_line_size + 1 < max_header_size
-                unless header.empty?
-                  header << ","
-                  last_line_size += 1
-                end
+              break if header.bytesize + link.bytesize > max_header_size
```
Comment (gklsan) [inline actionview/lib/action_view/helpers/asset_tag_helper.rb:652]: Suggestion:
```
header = [response.headers["Link"].to_s]
...
header  << link 
...
response.headers["Link"] = header.compact.join

```

**Comment by nateberkopec** [comment]
The test provides a nice idea of how many links this will append - about a dozen.

My only question - this appends the _first_ dozen links. What if those aren't the most useful ones to be appending? We _always_ want "application.js" and "application.css" to be appended, but what if there are 15 other files before that?

**Comment by casperisfine** [comment]
If you need tighter control you can do it with custom logic in the controller or a middleware.
