### PR TITLE
Clear query cache during checkin, instead of an execution callback

### LINKED ISSUE #26666: ActiveRecord Query Cache sometimes dirty and stuck enabled across threads
ActiveRecord::QueryCache using the new Rails executor may result in dirty query caches across threads. Releasing a connection early in one thread may return it to the pool with cache still enabled and dirty, and the executor loses track of the connection so may clear another, and another thread may pick up the dirty cache and never turn it off.
### Steps to reproduce

In practise this has occurred to us in a high-concurrency production environment across threads. We can reliably reproduce it with explicitly scheduled threads:

``` ruby
class Example < ActiveRecord::Base
  connection.execute <<~SQL
    CREATE TABLE examples (id int primary key);
  SQL
end

Example.create!(id: 1)

ActiveRecord::Base.connection_pool.connections.none?(&:query_cache_enabled)
# => true

thread_1_connection = nil
thread_1 = Thread.new do
  Rails.application.executor.wrap do
    thread_1_connection = ActiveRecord::Base.connection
    task = Example.find(1)
    thread_1_connection.query_cache.empty?
    # => false
    ActiveRecord::Base.clear_active_connections!
    # Sleep so thread 2 can pick up this connection
    sleep
    # The executor will grab a different connection and clear its query cache when returning from this block
  end
end

thread_2_connection = nil
thread_2 = Thread.new do
  # The executor grabs thread 1's released connection, and stores that the connection has query cache turned on by default
  Rails.application.executor.wrap do
    thread_2_connection =  ActiveRecord::Base.connection
    thread_2_connection == thread_1_connection
    # => true
    thread_2_connection.query_cache.empty?
    # => false
    sleep
    # The executor does clear the cache but doesn't change query_cache_enabled when returning here
  end
end

thread_1.wakeup
thread_1.join
thread_1_connection.query_cache_enabled
# => true

thread_2.wakeup
thread_2.join
ActiveRecord::Base.connection_pool.connections.none?(&:query_cache_enabled)
# => false

ActiveRecord::Base.connection.execute "DROP TABLE examples"
```
### Expected behaviour

ActiveRecord connections returned to the connection pool should have their query caches cleared and turned off (or back to the default).
### Actual behaviour

Threads may receive connections with dirty query caches and some connections may end up with query caching permanently enabled.
### System configuration

**Rails version**: 5.0.0.1 (master is the same)
**Ruby version**: 2.3.1
### First solution attempt

Store the connection in the executor state:

``` ruby
module ActiveRecord
  class QueryCache
    # ...
    def self.run
      connection    = ActiveRecord::Base.connection
      enabled       = connection.query_cache_enabled
      connection.enable_query_cache!

      [connection, enabled]
    end

    def self.complete((connection, enabled))
      connection.clear_query_cache
      connection.disable_query_cache! unless enabled
    end
    # ...
  end
end
```

There is still an edge case here: if the connection is returned to the pool early there is still a window where another thread may checkout the connection and see its dirty cache, and potentially store the cache is on by default, again landing us in a connection with query cache stuck enabled.

If an executor is responsible for checking out the AR connection then it's probably reasonable to assume it's also responsible for checking it back in. In practise, however, it's fairly easy to [accidentally break this assumption](https://github.com/mperham/sidekiq/pull/3166).
### A Better Solution?

Perhaps instead query caching should be enabled/cleared by the connection pool when checking connections in/out? It would prevent touching connections until they are needed. It would allow query caching in more complex deployments using multiple connection specifications. It would also be nice to be able to configure whether query caching is used at all at a connection specification level.

/cc @matthewd

### PR DESCRIPTION
**Pull request by matthewd**
It doesn't make sense for the query cache to persist while a connection moves through the pool and is assigned to a new thread.

Fixes #26666

cc @sj26

(based on https://github.com/sj26/rails/commit/ffa26c9a1a2a40d44c43b92a8dff420f4a8fe36b)

### CODE REVIEW

**Comment by matthewd** [comment]
This follows on from fa7efca553e325b2aabb087a4eddf4560c356094, but unlike that change, does not seem suitable for backport.

File: activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb [hunk 1]
```diff
@@ -4,6 +4,7 @@ module QueryCache
       class << self
         def included(base) #:nodoc:
           dirties_query_cache base, :insert, :update, :delete, :rollback_to_savepoint, :rollback_db_transaction
+          base.set_callback :checkin, :after, :disable_query_cache!
```
Comment (eugeneius) [inline activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb]: We should probably clear the query cache before the connection is checked in, rather than afterwards.

If the callback chain halts before this one can run - if there is another after callback configured, and it raises, for example - the connection would end up in the pool with a dirty cache.

**Review by rafaelfranca — APPROVED** [review]

**Comment by sj26** [comment]
Wonderful, thanks @matthewd.

Would be nice not to touch the connection until it is required. Could enabling the query cache be an after checkout callback?

If so, the only bits left in the QueryCache concern's executor complete method is connection pool cleanup, nothing to do with the query cache.

**Comment by sj26** [comment]
Although I suppose you don't necessarily always want to turn on the query cache...

**Comment by eugeneius** [comment]
If we enable the query cache in an after checkout callback, the cache will be enabled in several situations where it's not currently active. The ones I can think of are:

 - connections manually checked out via `checkout` or `with_connection`
 - connections from connection pools other than the one on `ActiveRecord::Base`
 - connections in contexts other than Rails, e.g. Sidekiq

None of these changes are necessarily bad (I would love for the multiple pools one to happen!) but it's worth carefully considering whether apps could break if they don't expect the caching behaviour.

In contrast, I think it's extremely unlikely that this change could break any application code - so I think we should ship this and decide whether to change how the cache is enabled separately.

File: activerecord/lib/active_record/query_cache.rb [hunk 2]
```diff
@@ -24,17 +24,10 @@ def uncached(&block)
...
-      [connection, enabled]
+      ActiveRecord::Base.connection.enable_query_cache!
     end
 
-    def self.complete((connection, enabled))
-      connection.clear_query_cache
-      connection.disable_query_cache! unless enabled
-
+    def self.complete(_)
       unless ActiveRecord::Base.connected? && ActiveRecord::Base.connection.transaction_open?
```
Comment (eugeneius) [inline activerecord/lib/active_record/query_cache.rb]: Right now the query cache is always disabled at the end of every request. If we instead rely on a callback to disable it when the connection returns to the pool, we'll leak connections with the query cache enabled if a transaction is left open at this point.

I think it's actually fine to say "if your app leaks connections with open transactions, the consequences will be so severe that you won't even notice the query cache problem" and not do anything about this, but I thought it was worth at least pointing out.

**Comment by matthewd** [comment]
See follow-up in #26978

**Comment by matthewd** [comment]
Backported in 9228aa8ad9a12afd40d9804c89490c8433a873f2
