### PR TITLE
Pass deseriallized defaults when copying tables in sqlite3

### LINKED ISSUE #45430: database schema: foreign key causes json default to become string instead of object
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "accounts", force: :cascade do |t|
    t.text "name"
  end

  create_table "products", force: :cascade do |t|
    t.integer "account_id"
    t.json "foo", default: {}
  end

  # If you comment this out, this test will pass
  add_foreign_key "products", "accounts", column: "account_id"
end

class Product < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_product_foo_default
    product = Product.new
    assert_equal({}, product.foo)
  end
end
```

### Expected behavior
A json column with a `default: {}` should be an empty JSON object by default.

### Actual behavior
The expected behavior is what happens until you add a foreign key. Then suddenly it quotes the braces, turning the default into a string. Note that this happens in both main and v7 (I have not tested anything else).

### System configuration
**Rails version**: main and 7.0.3

**Ruby version**: 3.0.2

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #45430.

I think, we just need to deserialize defaults when using them to recreate the table.  

cc @adrianna-chang-shopify

### CODE REVIEW

**Review by kyrofa — COMMENTED** [review]
I can confirm this solves the issue raised in #45430, it's pretty much exactly what I had in mind, thank you! May I ask that it also be backported to 7-0-stable once merged (edit: I went ahead and [proposed the backport](https://github.com/rails/rails/pull/45444))?

File: activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb [hunk 1]
```diff
@@ -497,8 +497,11 @@ def copy_table(from, to, options = {})
                  options[:rename][column.name.to_sym] ||
                  column.name) : column.name
 
+              type = lookup_cast_type_from_column(column)
+              default = type.deserialize(column.default) if column.has_default?
```
Comment (adrianna-chang-shopify) [inline activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:501]: Small nit: does it make sense to avoid looking up the cast type if there's no default?
```suggestion
              default = if column.has_default?
                type = lookup_cast_type_from_column(column)
                type.deserialize(column.default)
              end
```

**Review by adrianna-chang-shopify — COMMENTED** [review]
Thanks for taking care of this, @fatkodima ! ❤️

File: activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb (hunk 1 above)
Comment (fatkodima) [reply activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb]: It does not hurt if we check, but it may be cleaner (clearer) to do a check.
Thanks for the suggestion 👍
