### PR TITLE
Fix setting `trailing_slash: true` in route definition

### LINKED ISSUE #44373: `with_options trailing_slash: true` is broken on Rails 7
### Steps to reproduce

https://gist.github.com/WaKeMaTTa/365a79c969a959cf944fa7cf49d00973

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~> 7.0.0"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    with_options trailing_slash: true do
      get '/test/' => "test#index", as: :test
    end
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    path = app.routes.url_helpers.test_path
    assert_equal "/test/", path
    get path
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior

Having this route configuration

```ruby
routes.draw do
  with_options trailing_slash: true do
    get '/test/' => "test#index", as: :test
  end
end
```

we expect `test_path` to return `"/test/"` (like in Rails 6)

### Actual behavior

But in rails 7 when we call `test_path` we get `"/test"`.

### System configuration

**Rails version**: rails 7

**Ruby version**: ruby 3

### PR DESCRIPTION
**Pull request by casperisfine**
Ref: https://github.com/rails/rails/pull/43287
Fix: https://github.com/rails/rails/issues/44373

The `OptimizedUrlHelper` wasn't considering this option.

### CODE REVIEW

File: actionpack/lib/action_dispatch/routing/route_set.rb [hunk 1]
```diff
@@ -196,7 +196,9 @@ def initialize(route, options, route_name)
             def call(t, method_name, args, inner_options, url_strategy)
               if args.size == arg_size && !inner_options && optimize_routes_generation?(t)
                 options = t.url_options.merge @options
-                options[:path] = optimized_helper(args)
+                path = optimized_helper(args)
```
Comment (casperisfine) [inline actionpack/lib/action_dispatch/routing/route_set.rb:199]: Unless I missed something, we know for sure that `path` doesn't contain a format at this point.

**Comment by casperisfine** [comment]
This will be backported to `7-0-stable`.

cc @WaKeMaTTa, @nvasilevski, @ghiculescu (thanks for the ping, I totally didn't see the issue).

**Comment by byroot** [comment]
Some unrelated Active Support tests flaked, I'll have to look into them.

**Comment by byroot** [comment]
Backported in 7-0-stable as 3b59b096da
