### PR TITLE
Fix thread safety of prevent_writes

### LINKED ISSUE #36830: Rails 6 RC2 multi-db issue under multithreaded environment
When you use `ActiveRecord::Middleware::DatabaseSelector` with multithreaded puma, write access to db randomly fails with `ActiveRecord::ReadOnlyError: Write query attempted while in readonly mode`.

`ActiveRecord::Middleware::DatabaseSelector` has a mechanism to redirect read access to primary db for a moment. During that period, a flag named `@prevent_writes` on `ActiveRecord::ConnectionAdapters::ConnectionHandler` objects is set, and write access to db will raise `ActiveRecord::ReadOnlyError`.

However, `ActiveRecord::ConnectionAdapters::ConnectionHandler` objects are shared across threads. Changing `@prevent_writes` in one thread will cause unexpected effects on requests handled by the other threads.

### Steps to reproduce

Clone this repo, and follow the instructions.
https://github.com/kiyot/rails6-multi-db-prevent-write-race

### Expected behavior

Write access to db in writing role should succeed.

### Actual behavior

Write access to db in writing role randomly fails with `ActiveRecord::ReadOnlyError: Write query attempted while in readonly mode` under multithreaded environment.

### System configuration
**Rails version**:
6.0.0 RC2

**Ruby version**:
2.6.3

### PR DESCRIPTION
**Pull request by eileencodes**
As demonstrated in the test added and in #36830 the code that prevents
writes wasn't thread safe. If one thread does a read, then another does
a write, and then another does a read the second read will cause the
first write to be unwriteable.

This change removes the instance variable and instead uses a
getter/setter on Thread.current[:prevent_writes] for the connection
handler to set whether writes are allowed.

Fixes #36830

---

Thanks to @matthewd for helping me with writing this test.

cc/ @matthewd @tenderlove @jhawthorn 
Thanks to @kiyot for the original report

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb [hunk 1]
```diff
@@ -1003,28 +1003,33 @@ def self.discard_unowned_pools(pid_map) # :nodoc:
...
         # early discard has not occurred
         ObjectSpace.define_finalizer self, ConnectionHandler.unowned_pool_finalizer(@owner_to_pool)
       end
 
+      def prevent_writes # :nodoc:
+        Thread.current[:prevent_writes]
+      end
+
+      def prevent_writes=(prevent_writes) # :nodoc:
+        Thread.current[:prevent_writes] = prevent_writes
```
Comment (jhawthorn) [inline activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb]: It feels a little off that if we had multiple `ConnectionHandlers` this assignment would apply to all of them

**Review by rafaelfranca — APPROVED** [review]

**Review by jhawthorn — APPROVED** [review]

File: activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb (hunk 1 above)
Comment (jhawthorn) [reply activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb]: That makes sense. It feels off, but I don't see an actual problem caused by it.
