### PR TITLE
Fix touching has_one grand parent associations when the child is touched

### LINKED ISSUE #46393: Delegated parent is not touched
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", path: "../rails"
  gem "sqlite3"
  gem "debug"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with minitest 4.
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.timestamps
  end

  create_table :profiles, force: true do |t|
    t.bigint :user_id
    t.string :profilable_type
    t.bigint :profilable_id

    t.timestamps
  end

  create_table :doctors, force: true do |t|
    t.string :name
    t.timestamps
  end

  create_table :skills, force: true do |t|
    t.bigint :doctor_id
    t.string :name
    t.timestamps
  end
end

class User < ActiveRecord::Base
  has_one :profile
end

class Profile < ActiveRecord::Base
  delegated_type :profilable, types: %w[ doctor ]
  belongs_to :user, touch: true
end

class Doctor < ActiveRecord::Base
  has_one :profile, as: :profilable, touch: true
  has_many :skills
end

class Skill < ActiveRecord::Base
  belongs_to :doctor, touch: true
end

class BugTest < Minitest::Test
  def test_touching_user_after_add_doctors_skill
    new_doctor = Doctor.new name: "sebastian"
    new_profile = Profile.new profilable: new_doctor

    user = User.create!(profile: new_profile)

    previously_user_updated_at = user.updated_at

    user.profile.profilable.skills.create!(name: "diabetes_management")

    assert(previously_user_updated_at != user.reload.updated_at)
  end
end
```

### Expected behavior
When a doctors' skill is added, the user should be touched since the touch flow is skill -> doctor -> profile -> user. 

### Actual behavior
When a doctor's skill is added, doctor and profile are touched, but not the user.

### System configuration
**Rails version**:
7.0.3

**Ruby version**:
3.1.2

### PR DESCRIPTION
**Pull request by lazaronixon**
### Motivation / Background

I see this bug happening with delegated types but it can happen with any has_one association marked as touch.

```ruby
class User < ActiveRecord::Base
  has_one :profile
end

class Profile < ActiveRecord::Base
  delegated_type :profilable, types: %w[ doctor ]
  belongs_to :user, touch: true
end

class Doctor < ActiveRecord::Base
  has_one :profile, as: :profilable, touch: true
  has_many :skills
end

class Skill < ActiveRecord::Base
  belongs_to :doctor, touch: true
end
```

When you add a new skill, the touch flow should be `doctor -> profile -> user` but now it is `doctor -> profile`, user is never touched. The reason for this is that the actual logic search in `doctor` only for belongs_to parent associations marked as touch and has_one parent associations are ignored and never touched.

Fixes #46393

### CODE REVIEW

**Comment by byroot** [comment]
It would be good  to add a regression test.

File: activerecord/lib/active_record/touch_later.rb [hunk 1]
```diff
@@ -24,9 +24,14 @@ def touch_later(*names) # :nodoc:
...
 
       # touch the parents as we are not calling the after_save callbacks
-      self.class.reflect_on_all_associations(:belongs_to).each do |r|
+      self.class.reflect_on_all_associations.each do |r|
         if touch = r.options[:touch]
-          ActiveRecord::Associations::Builder::BelongsTo.touch_record(self, changes_to_save, r.foreign_key, r.name, touch, :touch_later)
+          if r.macro == :belongs_to
+            ActiveRecord::Associations::Builder::BelongsTo.touch_record(self, changes_to_save, r.foreign_key, r.name, touch, :touch_later)
+          end
+          if r.macro == :has_one
```
Comment (p8) [inline activerecord/lib/active_record/touch_later.rb:32]: This should probably be an elsif.

**Comment by lazaronixon** [comment]
> It would be good to add a regression test.

✅ @byroot
