### PR TITLE
Only compute :only and :except callback conditions once …

### LINKED ISSUE #38679: `FrozenError: can't modify frozen Array` when reusing callback arguments
### Steps to reproduce
I sometimes use the following pattern:

````
class PostsController < ApplicationController
  administrative only: [:new, :create, :edit, :update, :destroy]
end
````

where
````
def self.administrative(options = {})
  before_action :verify_admin, options
  before_action :set_something, options
end
````

This is now failing on edge Rails with `FrozenError: can't modify frozen Array` on the line where the **second** callback is defined.

This was apparently introduced in 0740adb379.

### Executable test case

https://gist.github.com/khustochka/e7f0764890ab3fb554b87b8355a2d704

### Expected behavior
It does not fail, two or more callbacks can reuse provided `options` hash.

### Actual behavior
Fails with `FrozenError: can't modify frozen Array` on the line where the **second** callback is defined. It looks like the first `before_action` call modifies the `options` hash adding an `:if` key to it, which is a frozen Array, and the call to the second `before_action` tries to add an additional condition into this array.

Stacktrace:
````
rails (e00f9c8aaea3) actionpack/lib/abstract_controller/callbacks.rb:75:in `unshift'
rails (e00f9c8aaea3) actionpack/lib/abstract_controller/callbacks.rb:75:in `_normalize_callback_option'
rails (e00f9c8aaea3) actionpack/lib/abstract_controller/callbacks.rb:68:in `_normalize_callback_options'
rails (e00f9c8aaea3) actionpack/lib/abstract_controller/callbacks.rb:93:in `_insert_callbacks'
rails (e00f9c8aaea3) actionpack/lib/abstract_controller/callbacks.rb:200:in `block (2 levels) in <module:ClassMethods>'
````

### System configuration
**Rails version**:
Edge (ec69083cf3352c78f840de50fdf20ef30334e0b1)
**Ruby version**:
2.6.5

### PR DESCRIPTION
**Pull request by casperisfine**
Ref: https://github.com/rails/rails/pull/38323
Fix: https://github.com/rails/rails/issues/38679

Only compute :only and :except callback conditions once
    
 `_normalize_callback_options` mutates the options hash, but doesn't remove the `:only` and `:except` conditions.
    
 So if you call `before_action` & al with the same option hash you end up with multiple instance of identical `:if` / `:unless` procs.

Since `_normalize_callback_options` already mutates the `options` hash, I decided to continue down that route and mutate it further by deleting the `:only` and `:except` conditions.

An alternative fix would be to dup the `options` hash before mutating it. Given that this hash comes from a DSL, I think mutating it is fine, but I'm open to implementing the alternative fix. 

Props to @khustochka and @natematykiewicz for reporting and investigating the original issue, as well as providing failing test cases.

cc @rafaelfranca @Edouard-chin @etiennebarrie

### CODE REVIEW

File: actionpack/test/abstract/callbacks_test.rb [hunk 1]
```diff
@@ -158,6 +158,56 @@ def setup
...
+      end
+
+      def define_callbacks
+        options = { only: :index }
+        CallbacksWithReusedConditions.before_action :list, options
+        CallbacksWithReusedConditions.before_action :authenticate, options
+      end
+
+      test "callbacks can be defined with reused conditions" do
+        define_callbacks
```
Comment (eugeneius) [inline actionpack/test/abstract/callbacks_test.rb:194]: This is an odd-looking test: `assert_nothing_raised { define_callbacks }` would be slightly better, but I also think it's wrong that we're defining the callbacks on the same class in multiple tests. We could create an anonymous subclass in the setup method, but how about adding the callbacks when the controller is defined, and removing the "it doesn't crash" test entirely?

Comment (casperisfine) [reply actionpack/test/abstract/callbacks_test.rb:194]: Sure. I can do that.

Comment (casperisfine) [reply actionpack/test/abstract/callbacks_test.rb]: Done.

**Comment by eugeneius** [comment]
Would you mind squashing the two commits into one?

**Comment by casperisfine** [comment]
> Would you mind squashing the two commits into one?

I didn't want to take authorship from @khustochka. I'll squash anyway and give him full authorships.

**Comment by casperisfine** [comment]
Done.

**Comment by eugeneius** [comment]
Thank you 💛
