### PR TITLE
Replace reference to WebSocket global with ActionCable.adapters.WebSocket

### LINKED ISSUE #34589: ActionCable.Connection#getState is referencing the WebSocket global rather than the configurable dependency
The WebSocket dependency of ActionCable was made configurable in 66901c1849efae74c8a58fe0cb36afd487c067cc

However, `ActionCable.Connection#getState` [was not updated](https://github.com/rails/rails/commit/66901c1849efae74c8a58fe0cb36afd487c067cc#diff-94ee9e15b064b2fc080f64c5fe0db621L70), so it is still referencing the WebSocket global:
https://github.com/rails/rails/blob/aa1ba9cb244b1e03d36aaa941ae4e91c6713b77e/actioncable/app/javascript/action_cable/connection.js#L91-L92

Here's a test that demonstrates this:

```js
import * as ActionCable from "../../../../app/javascript/action_cable/index"

const {module, test} = QUnit

module("ActionCable.Connection", () => {
  module("#getState", () => {
    test("uses configured WebSocket adapter", assert => {
      ActionCable.adapters.WebSocket = { foo: 1, BAR: "42" }
      const connection = new ActionCable.Connection({})
      connection.webSocket = {}
      connection.webSocket.readyState = 1
      assert.equal(connection.getState(), "foo")
      connection.webSocket.readyState = "42"
      assert.equal(connection.getState(), "bar")
    })
  })
})
```

### Expected behavior
The test should pass

### Actual behavior
The test currently fails on `master` with:

```
HeadlessChrome 70.0.3538 (Mac OS X 10.13.3) ActionCable.Connection > #getState uses specified URL FAILED
	Expected: "foo"
	Actual: "open"
	    at Object.<anonymous> (test/javascript/compiled/test.js:713:16)
	    at runTest (/Users/richard/src/rmacklin/rails/node_modules/qunit/qunit/qunit.js:3044:30)
	    at Test.run (/Users/richard/src/rmacklin/rails/node_modules/qunit/qunit/qunit.js:3030:6)
	    at /Users/richard/src/rmacklin/rails/node_modules/qunit/qunit/qunit.js:3257:12
	    at processTaskQueue (/Users/richard/src/rmacklin/rails/node_modules/qunit/qunit/qunit.js:2623:24)
	    at /Users/richard/src/rmacklin/rails/node_modules/qunit/qunit/qunit.js:2627:8
	
	Expected: "bar"
	Actual: null
	    at Object.<anonymous> (test/javascript/compiled/test.js:715:16)
	    at runTest (/Users/richard/src/rmacklin/rails/node_modules/qunit/qunit/qunit.js:3044:30)
	    at Test.run (/Users/richard/src/rmacklin/rails/node_modules/qunit/qunit/qunit.js:3030:6)
	    at /Users/richard/src/rmacklin/rails/node_modules/qunit/qunit/qunit.js:3257:12
	    at processTaskQueue (/Users/richard/src/rmacklin/rails/node_modules/qunit/qunit/qunit.js:2623:24)
	    at /Users/richard/src/rmacklin/rails/node_modules/qunit/qunit/qunit.js:2627:8
	
HeadlessChrome 70.0.3538 (Mac OS X 10.13.3): Executed 14 of 14 (1 FAILED) (0.097 secs / 0.184 secs)
TOTAL: 1 FAILED, 13 SUCCESS
```

### PR DESCRIPTION
**Pull request by rmacklin**
### Summary

The `WebSocket` dependency of `ActionCable.Connection` was made configurable in 66901c1849efae74c8a58fe0cb36afd487c067cc

However, the reference in `Connection#getState` was not updated to use the configurable property. This change remedies that and adds a test to verify it. Additionally, it backfills a test to ensure that `Connection#open` uses the configurable property.

Resolves #34589

### CODE REVIEW

File: actioncable/test/javascript/src/unit/connection_test.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+    test("uses the configured WebSocket adapter", assert => {
+      const FakeWebSocket = function() {}
+      ActionCable.adapters.WebSocket = FakeWebSocket
+      const connection = new ActionCable.Connection({})
+      connection.monitor = { start() {} }
+      connection.open()
+      assert.equal(connection.webSocket instanceof FakeWebSocket, true)
+    })
+  })
+})
```
Comment (javan) [inline actioncable/test/javascript/src/unit/connection_test.js]: Do these tests need to reset `ActionCable.adapters.WebSocket` to its original value?

Comment (rmacklin) [reply actioncable/test/javascript/src/unit/connection_test.js]: I believe that's handled by the `testDone` hook that you added in https://github.com/rails/rails/commit/410a32ffbdfa45aeee2c8ec0137201d3b95a33ff#diff-3f28927c13290f07f1f5db8933b6f74c:
https://github.com/rails/rails/blob/aa1ba9cb244b1e03d36aaa941ae4e91c6713b77e/actioncable/test/javascript/src/test_helpers/index.js#L9-L10
right?

Comment (javan) [reply actioncable/test/javascript/src/unit/connection_test.js]: Oh right, glad I thought of that already. 🤦‍♂️
