### PR TITLE
Use correct precision when touching `updated_at` column in upsert

### LINKED ISSUE #42992: `upsert` does not use correct precision when updating `updated_at` column.
### Steps to reproduce

Attempt to `upsert` a colliding (but different) record into table with an `updated_at` column with a non-zero `precision`.

<details><summary>Reproduction Script</summary>

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 6.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title, null: false
    t.string :author, null: false
    t.datetime :updated_at, precision: 6

    t.index :title, unique: true
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def teardown
    Post.delete_all
    super
  end

  def test_updated_at_column_has_subsecond_precision
    assert_equal 6, Post.columns.find { |c| c.name == 'updated_at' }.precision
  end

  def test_upsert_new_record
    Post.upsert({title: 'new title', author: 'new author'}, unique_by: [:title])

    assert_nil Post.first.updated_at, 'updated_at not set on creation' # out of scope of this bug report
  end

  def test_upsert_identical_record
    post = Post.create!(title: 'existing title', author: 'original author')
    refute_predicate post.updated_at.usec, :zero?, 'updated_at should have sub-second precision'
    original_updated_at = post.updated_at

    Post.upsert({title: post.title, author: post.author}, unique_by: [:title])

    assert_equal original_updated_at, post.reload.updated_at, 'updated_at should have sub-second precision'
  end

  def test_upsert_updated_record
    post = Post.create!(title: 'existing title', author: 'original author')
    refute_predicate post.updated_at.usec, :zero?, 'update_at should have fractional component'

    Post.upsert({title: post.title, author: 'new author'}, unique_by: [:title])

    refute_predicate post.reload.updated_at.usec, :zero?, 'updated_at should have sub-second precision'
  end
end
```

</details>

### Expected behavior

`upsert` should detect `updated_at` precision and use that when touching the timestamp.

e.g. if `updated_at` has a precision of `6`, it should use `CURRENT_TIMESTAMP(6)`

### Actual behavior

`upsert` implicitly uses precision `0` when touching the timestamp.

e.g. if `updated_at` has a precision of `6`, it erroneously uses `CURRENT_TIMESTAMP`

### System configuration
**Rails version**: `6.1.0`

**Ruby version**: `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin20]`

### PR DESCRIPTION
**Pull request by sambostock**
### Summary

Closes #42992 

`InsertAll` (the machinery which powers, among others methods, `upsert`) uses `CURRENT_TIMESTAMP` with an implicit precision of `0` as the default when touching `updated_at`/`updated_on`.

**This PR updates it to pass in the current time, serialized according to the column's type.**

Not all databases support increased precision for `CURRENT_TIMESTAMP` (e.g. MySQL supports `CURRENT_TIMESTAMP(6)`, but SQLite does not), so it is simpler to just serialize the current time.

#### :warning: Before Merging

- [x] Address TODO comments
- [x] Add changelog entry
- [ ] Confirm there is no reason `CURRENT_TIMESTAMP` had been chosen instead of serializing the current time, and that this won't break anything.

### CODE REVIEW

File: activerecord/lib/active_record/insert_all.rb [hunk 1]
```diff
@@ -198,7 +198,19 @@ def updatable_columns
...
+              #       i.e precision = model.columns_hash.fetch(column_name).precision
+              precision = model.columns.find { |column| column.name == column_name }.precision
+              precision ||= 0
+              # TODO: Do we even need to calculate the precision, or can we just use the max precision every time
+              #       (i.e. hardcode CURRENT_TIMESTAMP(6) or whatever the max precision is, allowed by this DB adapter)
+              # NOTE: Not all DBs allow parens after CURRENT_TIMESTAMP.
+              #         e.g. - MySQL considers CURRENT_TIMESTAMP, CURRENT_TIMESTAMP(), & CURRENT_TIMESTAMP(0) identical,
+              #                and allows up to CURRENT_TIMESTAMP(6)
+              #              - SQLite only accepts CURRENT_TIMESTAMP, and does not allow the use of parentheses at all
+              current_timestamp = precision.zero? ? "CURRENT_TIMESTAMP" : "CURRENT_TIMESTAMP(#{precision})"
```
Comment (sambostock) [inline activerecord/lib/active_record/insert_all.rb:212]: It would seem I have opened a can of worms, since there are weird scenarios like SQLite supporting fractional timestamps, but not accepting `CURRENT_TIMESTAMP(6)`.

**Is there a reason we rely on `CURRENT_TIMESTAMP` in the first place, instead of just passing in a timestamp derived from `Time.now`?**

Some quick googling finds things like 

> [The 'now' argument to date and time functions always returns exactly the same value for multiple invocations within the same sqlite3_step() call.](https://www.sqlite.org/lang_datefunc.html)

so I don't think there's any difference in the timestamps even if we perform a large bulk insert (assuming this kind of behaviour is consistent across other databases).

As far as I can tell, the only difference we'd see between using `CURRENT_TIMESTAMP` and injecting `Time.now` would be the small difference in time between the timestamp generated by the database, and the timestamp generated by us before the database receives our query, but that is likely inconsequential.

File: activerecord/lib/active_record/insert_all.rb [hunk 2]
```diff
@@ -198,11 +198,17 @@ def updatable_columns
...
+              "#{column_name}=(CASE WHEN (#{updatable_columns.map(&block).join(" AND ")}) THEN #{model.quoted_table_name}.#{column_name} ELSE #{quoted_current_timestamp_for(column_name)} END),"
             end
           end.join
         end
 
+        def quoted_current_timestamp_for(column_name)
+          connection.quote(
+            model.type_for_attribute(column_name).serialize(model.current_time_from_proper_timezone)
+          )
+        end
```
Comment (sambostock) [inline activerecord/lib/active_record/insert_all.rb:210]: My initial approach tried to dynamically set the precision of `CURRENT_TIMESTAMP` (e.g. `CURRENT_TIMESTAMP(6)` for a `precision: 6` column). This is problematic, as not all databases support extra precision on `CURRENT_TIMESTAMP` (e.g. SQLite does not).

**Is there any reason doing this is a bad idea?**

File: activerecord/lib/active_record/insert_all.rb [hunk 3]
```diff
@@ -198,7 +198,7 @@ def updatable_columns
         def touch_model_timestamps_unless(&block)
           model.timestamp_attributes_for_update_in_model.filter_map do |column_name|
             if touch_timestamp_attribute?(column_name)
-              "#{column_name}=(CASE WHEN (#{updatable_columns.map(&block).join(" AND ")}) THEN #{model.quoted_table_name}.#{column_name} ELSE CURRENT_TIMESTAMP END),"
+              "#{column_name}=(CASE WHEN (#{updatable_columns.map(&block).join(" AND ")}) THEN #{model.quoted_table_name}.#{column_name} ELSE #{quoted_current_timestamp_for(column_name)} END),"
```
Comment (sambostock) [inline activerecord/lib/active_record/insert_all.rb:201]: It occurs to me that every time we call this method, we would be using a slightly different `Time.now`. While unlikely, this could lead to something like

```sql
updated_at=(... ELSE 'fraction of a second before midnight' END),
updated_on=(... ELSE 'the next day' END),
```

I wonder if it makes sense to memoize the current time. The simplest thing would probably be to record the current time in `initialize`, since all usages of this class are of the form `InsertAll.new(...).execute`, so we don't have to worry about stale timestamps.

On a separate branch, I am looking into if it is possible to set timestamps automatically on create, so I'll likely need to memoize the time anyway (to ensure every inserted row has the same timestamps).

**Comment by sambostock** [comment]
Ahh, interesting suggestion, @tenderlove. I hadn't considered offloading that per adapter. Couple questions:

- Do you know why we take differing approaches in `insert_all` (`CURRENT_TIMESTAMP`) vs when we set timestamps on individual records (`current_time_from_proper_timezone`)?
- Do you think we should use this approach in #43003 (setting `created_at`, etc. on insert) too?
- Should we
  - generate a string with the precision matching that specific column?
    e.g. MySQL: `updated_at = CURRENT_TIMESTAMP(model.type_for_attribute("updated_at").precision)`
  - or always pass in a string for the max precision?
    e.g. MySQL: `updated_at = CURRENT_TIMESTAMP(6)`
- Similarly, does it matter how we do this for `datetime` vs `date` columns?
  e.g. SQLite `updated_on = STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')`

File: activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb [hunk 4]
```diff
@@ -441,6 +441,19 @@ def with_yaml_fallback(value) # :nodoc:
...
+      private_constant :HIGH_PRECISION_CURRENT_TIMESTAMP
+
+      # Returns an Arel SQL literal for the CURRENT_TIMESTAMP for usage with
+      # arbitrary precision date/time columns.
+      #
+      # Adapters supporting datetime with precision should override this to
+      # provide as much precision as is available.
+      def high_precision_current_timestamp
+        HIGH_PRECISION_CURRENT_TIMESTAMP
+      end
```
[the remark this answers is not in the document]
Comment (tenderlove) [reply activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:455]: > I originally thought we'd be able to just have this be the only implementation of the method, and simply override the constant in each adapter, but that doesn't seem to work.
> 
> We could do `self.class::HIGH_PRECISION_CURRENT_TIMESTAMP` but that seems wrong.

Meh.  I think this is totally fine.

**Comment by tenderlove** [comment]
> * Do you know why we take differing approaches in `insert_all` (`CURRENT_TIMESTAMP`) vs when we set timestamps on individual records (`current_time_from_proper_timezone`)?

I don't know the answer to this. Probably using `Time.now` or whatever just seemed like the easiest at the time (lol).

> * Do you think we should use this approach in [Set timestamps on `insert_all`/`upsert_all` record creation #43003](https://github.com/rails/rails/pull/43003) (setting `created_at`, etc. on insert) too?

If it's not too hard, yes.
