### PR TITLE
Fixes encoding/decoding Data object via as_json

### LINKED ISSUE #47267: Ruby 3.2 Data class when serializing to JSON  becomes empty hash string
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true, quiet: true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', '~> 7.0', '>= 7.0.4.2'
end

data = Data.define(:foo).new(:bar)
struct = Struct.new(:foo).new(:bar)

puts "ActiveSupport::JSON.encode(data): #{ActiveSupport::JSON.encode(data)}"
puts "ActiveSupport::JSON.encode(struct): #{ActiveSupport::JSON.encode(struct)}"

# => ActiveSupport::JSON.encode(data): {}
# => ActiveSupport::JSON.encode(struct): {"foo":"bar"}
```

### Expected behavior
I believe it should behave same as Struct, or Hash, serializing all keys and values

### Actual behavior
Returns empty hash string "{}"

### System configuration
**Rails version**: 7.0.4.2

**Ruby version**: ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]

### PR DESCRIPTION
**Pull request by hahmed**
### Motivation / Background

Add as_json method for the new Data object introduced in Ruby 3.2 so Data objects can be encoded/decoded.

```
data = Data.define(:name).new(:test)
data.as_json
```

This Pull Request has been created because https://github.com/rails/rails/issues/47267

cc/ @eileencodes 

### Additional information

Run the tests in Ruby 3.2 only.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activesupport/lib/active_support/core_ext/object/json.rb [hunk 1]
```diff
@@ -65,6 +65,14 @@ def as_json(options = nil) # :nodoc:
   end
 end
 
+if RUBY_VERSION >= "3.2"
+  class Data # :nodoc:
+    def as_json(options = nil)
+      Hash[members.zip(deconstruct)].as_json(options)
```
Comment (nvasilevski) [inline activesupport/lib/active_support/core_ext/object/json.rb:71]: Mainly for education purposes, can we implement it as 
```suggestion
      to_h.as_json(options)
```
which feels like a higher-level approach that is simpler to maintain. It looks like `Struct` uses a similar `zip` approach but I couldn't find a specific reason for that

Comment (nvasilevski) [reply activesupport/lib/active_support/core_ext/object/json.rb:71]: `to_h` is quicker so perhaps a better option unless I'm missing the difference
```ruby
Benchmark.ips do |x|
  x.report("to_h") { data_obj.to_h }
  x.report("members.zip(deconstruct)") { Hash[data_obj.members.zip(data_obj.deconstruct)] }

  x.compare!
end
```

```
Calculating -------------------------------------
                to_h      3.026M (±15.8%) i/s -     14.943M in   5.063868s
members.zip(deconstruct)
                          1.304M (±20.9%) i/s -      6.287M in   5.047154s

Comparison:
                to_h:  3025508.3 i/s
members.zip(deconstruct):  1304149.5 i/s - 2.32x  (± 0.00) slower
```

Comment (guilleiguaran) [reply activesupport/lib/active_support/core_ext/object/json.rb:71]: @nvasilevski out of curiosity, can you run the same benchmark for Struct?

Comment (guilleiguaran) [reply activesupport/lib/active_support/core_ext/object/json.rb:71]: Looks to me that `Array#zip` was used for historical reasons, before Struct supported `to_h`.

I've updated the code and linked the benchmarks as well: https://github.com/rails/rails/commit/a7d4d78479fc81f94ccd5e5a505f708ec87bf318

@nvasilevski thanks for your help!
