### PR TITLE
Prevent persisting invalid record:

### LINKED ISSUE #54267: [Regression] Invalid doubly-nested attributes are saved
I believe https://github.com/rails/rails/pull/53951 introduced a regression into saving nested attributes if there is more than one level of nesting. Repro:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # gem "rails", github: "rails/rails", branch: "main"
  gem "rails", github: "rails/rails", ref: "9424179306" # commit prior to change

  gem "sqlite3"

  gem "debug"
end

require "active_record/railtie"
require "minitest/autorun"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

ActiveRecord::Schema.define do
  create_table :countries do |t|
    t.string :name
  end

  create_table :tax_overrides do |t|
    t.string :name
    t.references :country
  end

  create_table :tax_override_regions do |t|
    t.string :name
    t.references :tax_override
    t.decimal :rate, precision: 10, scale: 2
  end
end

class Country < ActiveRecord::Base
  has_many :tax_overrides

  accepts_nested_attributes_for :tax_overrides
end

class TaxOverride < ActiveRecord::Base
  belongs_to :country
  has_many :tax_override_regions

  accepts_nested_attributes_for :tax_override_regions
end

class TaxOverrideRegion < ActiveRecord::Base
  belongs_to :tax_override

  validates :rate, numericality: { greater_than_or_equal_to: 0 }, allow_nil: false
end

class BugTest < ActiveSupport::TestCase
  def test_validation_issue
    country = Country.build(name: "Canada")
    tax_override = country.tax_overrides.build(name: "Tax Override for Ontario")
    tax_override_region = tax_override.tax_override_regions.build(name: "Toronto", rate: 10.0)

    country.save!

    input_attributes = {
      tax_overrides_attributes:
      {"0" =>
        {
          id: tax_override.id,
          tax_override_regions_attributes: {"0" => { rate: -0.4, id: tax_override_region.id }},
        }
      }
    }

    refute country.update(input_attributes), "Country should not have been updated"
    assert country.errors.full_messages.include?(
      "Tax overrides tax override regions rate must be greater than or equal to 0"
    )
  end
end
```

Before change, the test passes.

On main:
```
  1) Failure:
BugTest#test_validation_issue [scripts/no-validation-bug.rb:73]:
Country should not have been updated

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

cc @byroot

### PR DESCRIPTION
**Pull request by Edouard-chin**
Prevent persisting invalid record:

- Fix #54267

### Motivation / Background

- In #53951, the goal was to allow saving a record and its association even if the association had existing invalid records in the DB. We would not validate the association in that case.

  The problem of not validating, is that it stops the validation chain and it's possible that other records in subsequent relations are being modified and are invalid. e.g. `Company -has_many-> Developers -has_many-> Computers`, if a computer is changed with invalid value and the company get saved, this would bypass the computer validation and persist it.

  This commit fixes that by ensuring there are no validation errors from *changed* records in the whole association chain.

This Pull Request has been created because [REPLACE ME]

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/test/cases/nested_attributes_test.rb [hunk 1]
```diff
@@ -1206,12 +1206,19 @@ def self.name; "Guitar"; end
 end
 
 class TestNestedAttributesWithExtend < ActiveRecord::TestCase
-  setup do
-    Pirate.accepts_nested_attributes_for :treasures
-  end
-
   def test_extend_affects_nested_attributes
-    pirate = Pirate.create!(catchphrase: "Don' botharrr talkin' like one, savvy?")
+    super_pirate = Class.new(ActiveRecord::Base) do
```
Comment (Edouard-chin) [inline activerecord/test/cases/nested_attributes_test.rb:1210]: Unrelated to this change, but `Pirate.accepts_nested_attributes_for` leaks to other tests. (It makes asserting errors message from relation different as it adds `autosave: true` to the reflection).

**Comment by byroot** [comment]
LGTM. I did some very minor changes to `association_valid?` and rebased. I'll merge on green.

**Comment by Edouard-chin** [comment]
Thanks for rebasing !
