### PR TITLE
Normalize virtual attributes on ActiveRecord::Persistence#becomes

### LINKED ISSUE #41195: ActiveRecord::Persistence#becomes doesn't handle virtual attributes
### Steps to reproduce

Add a virtual attribute to an inherited model, and use `#becomes` from either the parent to the child or the child to the parent

### Expected behavior

Virtual Attributes should be correctly initialized and there shouldn't be any errors, since they have nothing to do with the database

### Actual behavior

an `ActiveRecord::UnknownAttributeError` is thrown if you try to go either direction

### System configuration
**Rails version**: 6.0.3.4 (but I was the one who submitted the last patch for becomes to correctly move items back into the initialize block like they're supposed to be, so I have the current monkey patch for the latest version, it happens on all versions at least from 6+, tested up to 6.1.1)

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux] (but also really not a cause here)

### PR DESCRIPTION
**Pull request by intrip**
### Summary

When source and target classes have a different set of attributes adapts
attributes such that the extra attributes from target are added.

Fixes #41195

Co-authored-by: SampsonCrowley <sampsonsprojects@gmail.com>
Co-authored-by: Jonathan Hefner <jonathan@hefner.pro>

### CODE REVIEW

**Review by SampsonCrowley — APPROVED** [review]
I don't remember exactly how much of this was originally my code reviewing from my phone, but what you have now looks clean.

Thanks for reviving it after I got too busy

File: activemodel/lib/active_model/attribute_set.rb [hunk 1]
```diff
@@ -94,6 +94,14 @@ def map(&block)
       AttributeSet.new(new_attributes)
     end
 
+    # Modify attributes such that:
+    # - Removes keys which doesn't exists in target_attributes
```
Comment (SampsonCrowley) [inline activemodel/lib/active_model/attribute_set.rb:98]: Pure nitpick, `which don't exist in` would be the proper grammar here

File: activemodel/lib/active_model/attribute_set.rb [hunk 2]
```diff
@@ -94,6 +94,14 @@ def map(&block)
...
+    # - Adds keys which does exists only in target_attributes.
```
Comment (SampsonCrowley) [inline activemodel/lib/active_model/attribute_set.rb:99]: And the phrase here would be `which do exist only in`

**Comment by intrip** [comment]
@SampsonCrowley thanks! I've updated the comments.

**Comment by SampsonCrowley** [comment]
It's always the changelog...

**Comment by intrip** [comment]
@SampsonCrowley I'll wait for a review before updating endlessly the changelog 😄

**Comment by intrip** [comment]
Not stale: Attached PR

File: activemodel/lib/active_model/attribute_set.rb [hunk 3]
```diff
@@ -94,6 +94,14 @@ def map(&block)
       AttributeSet.new(new_attributes)
     end
 
+    # Modify attributes such that:
+    # - Removes keys which don't exist in target_attributes
+    # - Adds keys that only exist in target_attributes.
+    def adapt_to_target!(target_attributes)
+      attributes.slice!(*target_attributes.keys)
+      attributes.merge!(target_attributes.slice!(*keys))
```
Comment (SampsonCrowley) [inline activemodel/lib/active_model/attribute_set.rb:102]: Should this be a destructive slice?

Comment (SampsonCrowley) [reply activemodel/lib/active_model/attribute_set.rb:102]: And I only mean in the merge call, `target_attributes.slice!`

Comment (intrip) [reply activemodel/lib/active_model/attribute_set.rb:102]: Could you provide a code example? I'm not sure why using `slice` is better 🤔 .

Comment (SampsonCrowley) [reply activemodel/lib/active_model/attribute_set.rb:102]: @intrip you're destructively modifying `target_attributes` by using slice! instead of slice

It's an unexpected mutation irrelevant to the code block is the difference/danger

Comment (SampsonCrowley) [reply activemodel/lib/active_model/attribute_set.rb:102]: Not sure what your looking for but code example?

I mean that the following produces the exact same result without permanent modifications to external attributes

```ruby
def adapt_to_target!(target_attributes)
      attributes.slice!(*target_attributes.keys)
      attributes.merge!(target_attributes.slice(*keys))
end
```

You could argue that the bang is a warning for changes in both hashes, but unless the memory savings is worth it, idk if I'd go that direction

Comment (intrip) [reply activemodel/lib/active_model/attribute_set.rb:102]: Oh I see your point now: your proposal doesn't work because the return value from `slice!` is different than `slice`, `slice!` returns the removed key/value pairs which in this case are all the `target_attributes` that aren't in `*keys`. Modifying `target_attributes` shouldn't be an issue because it's just a temporary value which we [ovverride thereafter](https://github.com/rails/rails/blob/3b1f90e4959a56f34dbc91bf838ecf80fa4d916c/activerecord/lib/active_record/persistence.rb#L717)

**Comment by intrip** [comment]
Still relevant, can anyone repoen?

File: activerecord/test/cases/persistence_test.rb [hunk 4]
```diff
@@ -350,6 +350,22 @@ def test_becomes_includes_changed_attributes
...
+    assert_equal 50, client.extra_size
+  end
+
+  def test_becomes_drops_extra_attributes
+    client = LargeClient.new(name: "ShrinkingCompany")
+
+    company = client.becomes(Company)
+
+    assert_equal false, company.respond_to?(:extra_size)
+  end
```
Comment (jonathanhefner) [inline activerecord/test/cases/persistence_test.rb:367]: I'm not sure what the best solution is, but I think removing source attributes may be too surprising.  For example, I would expect `assert_equal 50, client.extra_size` to pass in this test as well.  But `client.becomes(Company)` sets `client.extra_size` to `nil`.

Comment (rafaelfranca) [reply activerecord/test/cases/persistence_test.rb:367]: Reading the documentation of `becomes` the attributes of the original class should be kept, so this should return 50

Comment (intrip) [reply activerecord/test/cases/persistence_test.rb]: Changing `becomes` to remove extra attributes and still reference the same data is a bit tricky so I've changed it to not remove the extra attributes: This should keep the backward compatibility and add the ability to use the extra virtual attributes introduced by the target class. Looks good to you?

If not I can work on an implementation that hides the extra attributes when needed from `ActiveModel::AttributeSet` such that we can still reference the same copy but have the effect of "removing" extra attributes.

File: activemodel/lib/active_model/attribute_set.rb [hunk 5]
```diff
@@ -7,7 +7,7 @@
 
 module ActiveModel
   class AttributeSet # :nodoc:
-    delegate :each_value, :fetch, :except, to: :attributes
+    delegate :each_value, :fetch, :except, :slice!, to: :attributes
```
Comment (jonathanhefner) [inline activemodel/lib/active_model/attribute_set.rb:10]: Speaking of `slice!`...

`delegate` kind of serves a weird role in `AttributeSet`.  It works with `each_value` and `fetch`, if you don't look too closely at the return value of `each_value`.  But for methods like `slice!`, it returns a `Hash` where I would expect another `AttributeSet` (just like I expect `ActionController::Parameters#slice!` to return an `ActionController::Parameters`).

(`except` also has this problem, but that's outside the scope of this PR. :laughing:)

**Review by jonathanhefner — COMMENTED** [review]
> If not I can work on an implementation that hides the extra attributes when needed from `AttributeSet` such that we can still reference the same copy but have the effect of "removing" extra attributes when viewed from AR.

That behavior sounds closer to expected, but my concern would be the additional complexity and performance overhead just to solve this corner case.

The [documentation for `becomes`](https://github.com/rails/rails/blob/342bd8545a2341a4a06684cbcb17b90113498dfa/activerecord/lib/active_record/persistence.rb#L709) states that "Any change to the attributes on either instance will affect both instances."  I suppose one could argue that running an initializer *does* change attributes, and so the new attributes on the original instance should be expected.

That said, another possibility might be to remove the new attributes after the initializer completes.  The trade-off would be that the new instance would be missing some of its declared attributes.  But you could also argue that *that* is expected, due to using `becomes` instead of e.g. `Becoming.new(original.attributes)`.

File: activemodel/lib/active_model/attribute_set.rb [hunk 6]
```diff
@@ -99,6 +99,11 @@ def map(&block)
       AttributeSet.new(new_attributes)
     end
 
+    # Adds keys that only exist in target_attributes.
+    def adapt_to_target!(target_attributes)
```
[the remark this answers is not in the document]
Comment (intrip) [reply activemodel/lib/active_model/attribute_set.rb:103]: Good call, I've renamed it

**Comment by intrip** [comment]
> That behavior sounds closer to expected, but my concern would be the additional complexity and performance overhead just to solve this corner case.

Agree

> That said, another possibility might be to remove the new attributes after the initializer completes. The trade-off would be that the new instance would be missing some of its declared attributes. But you could also argue that that is expected, due to using becomes instead of e.g. Becoming.new(original.attributes).

I didn't understand this part: How can we remove the new attributes whilst still ensuring that both AttributeSet references the same underlying Hash (to synchronize changes between instances)?

In any case, I'd insist saying that just adding new attributes looks to be an ok trade-off in this case 😅

**Review by jonathanhefner — COMMENTED** [review]
> I didn't understand this part: How can we remove the new attributes whilst still ensuring that both AttributeSet references the same underlying Hash (to synchronize changes between instances)?

I was thinking of something like this (minus the encapsulation violations :grin:):

```diff
diff --git a/activerecord/lib/active_record/persistence.rb b/activerecord/lib/active_record/persistence.rb
index 2caf71d736..eb44dac269 100644
--- a/activerecord/lib/active_record/persistence.rb
+++ b/activerecord/lib/active_record/persistence.rb
@@ -710,6 +710,7 @@ def destroy!
     # If you want to change the STI column as well, use #becomes! instead.
     def becomes(klass)
       became = klass.allocate
+      original_attributes_keys = @attributes.keys

       became.send(:initialize) do |becoming|
         @attributes.reverse_merge!(becoming.instance_variable_get(:@attributes))
@@ -720,6 +721,11 @@ def becomes(klass)
         becoming.errors.copy!(errors)
       end

+      new_attributes_keys = @attributes.keys - original_attributes_keys
+      if !new_attributes_keys.empty?
+        @attributes.send(:attributes).reject! { |key, value| new_attributes_keys.include?(key) }
+      end
+
       became
     end

diff --git a/activerecord/test/cases/persistence_test.rb b/activerecord/test/cases/persistence_test.rb
index 017fccc2f3..41ce40b9b2 100644
--- a/activerecord/test/cases/persistence_test.rb
+++ b/activerecord/test/cases/persistence_test.rb
@@ -353,9 +353,7 @@ def test_becomes_includes_changed_attributes
   def test_becomes_initializes_missing_attributes
     company = Company.new(name: "GrowingCompany")

-    client = company.becomes(LargeClient)
-
-    assert_equal 50, client.extra_size
+    assert_nothing_raised { company.becomes(LargeClient) }
   end

   def test_becomes_keeps_extra_attributes
```

It would address `becomes` raising an unexpected error.  My thinking was that if you need a fully-fledged new instance, then you should use e.g. `LargeClient.new(company.attributes)`.

> In any case, I'd insist saying that just adding new attributes looks to be an ok trade-off in this case :sweat_smile:

That seems fine too.  Maybe we should add a note to the documentation?  Something like:

```ruby
    # The new instance will share a link to the same attributes as the original class.
    # Therefore the STI column value will still be the same.
    # Any change to the attributes on either instance will affect both instances.
    # This includes any attribute initialization done by the new instance.
    #
    # If you want to change the STI column as well, use #becomes! instead.
```

**Comment by intrip** [comment]
@jonathanhefner Thank you for the explanation 🙏.

I've applied your suggestions and the comment addition looks clear.

**Comment by jonathanhefner** [comment]
Thank you, @intrip! :heart:

File: activerecord/CHANGELOG.md [hunk 7]
```diff
@@ -1,3 +1,30 @@
+*   Adapts virtual attributes on `ActiveRecord::Persistence#becomes`.
+
+    When source and target classes have a different set of attributes adapts
+    attributes such that the extra attributes from target are added.
+
+    ```ruby
+    class Person < ApplicationRecord
+    end
+
+    class WebUser < Person
```
Comment (p8) [inline activerecord/CHANGELOG.md:10]: Hi @intrip, should this be `User` instead, as that is what we pass to `becomes`?
```suggestion
    class User < Person
```

Comment (jonathanhefner) [reply activerecord/CHANGELOG.md:10]: Fixed by e45947328efee37f28b964b3bd50dfb603e23d48. :+1:

Comment (p8) [reply activerecord/CHANGELOG.md:10]: Thanks! 🙂

Comment (intrip) [reply activerecord/CHANGELOG.md:10]: Thanks!
