### PR TITLE
Avoid crash to validate circular autosave association

### LINKED ISSUE #53544: Infinite loop causes memory bloat
### Steps to reproduce
From ^7.2.0, these are few changes to `lib/active_record/autosave_association.rb`
image
Example:
```
class Comment < ApplicationRecord
    ...
    has_many :child_comments, class_name: name, foreign_key: parent_comment_id_column_name, inverse_of: :parent_comment, dependent: :nullify
    belongs_to :parent_comment, class_name: name, foreign_key: parent_comment_id_column_name, inverse_of: :child_comments, optional: true
    accepts_nested_attributes_for :child_comments
    ...
end
```
With a simple database schema like this
```
Comments 
- id
- text
- parent_comment_id
- ...
```
If we accidentally self-parenting a comment like this
```
comment.parent_comment = comment
```
It will cause an infinite loop and crash the machine. The reason is `record` and `self` is the same `object_id` and they will keep appending errors till crashing

###Idea for fixing
Change from
```
...
            record.errors.each { |error|
              self.errors.objects.append(
                Associations::NestedError.new(association, error)
              )
            }
...
```
to
```
...
self.errors.objects.concat(
  record.errors.map { |error| Associations::NestedError.new(association, error) }
)
...
```

```ruby
# Your reproduction script goes here
```

### System configuration
**Rails version**:

**Ruby version**:

### PR DESCRIPTION
**Pull request by zzak**
Fixes #53544

Repro:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", ">= 7.2.0"
  gem "sqlite3"
end

require "active_record/railtie"
require "minitest/autorun"

ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
  config.secret_key_base = "secret_key_base"
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :comments, force: true do |t|
    t.integer :parent_comment_id
    t.text :text
  end
end

class Comment < ActiveRecord::Base
  has_many :child_comments, class_name: "Comment", foreign_key: "parent_comment_id", inverse_of: :parent_comment, dependent: :nullify
  belongs_to :parent_comment, class_name: "Comment", foreign_key: "parent_comment_id", inverse_of: :child_comments, optional: true
  accepts_nested_attributes_for :child_comments

  validates_presence_of :text
end

class BugTest < ActiveSupport::TestCase
  def test_association_stuff
    child = Comment.new
    child.child_comments << child
    child.save
    assert_equal 0, child.child_comments.count
  end
end
```

### CODE REVIEW

File: activerecord/lib/active_record/autosave_association.rb [hunk 1]
```diff
@@ -383,6 +383,7 @@ def association_valid?(association, record)
         end
 
         if association.options[:autosave]
+          return if record == self
```
Comment (byroot) [inline activerecord/lib/active_record/autosave_association.rb:386]:
```suggestion
          return if equal?(record)
```
I think would be more strict? I'm a bit worried about the consequence of using `==` for Active Record.
