### PR TITLE
[ci-skip] Adding options example in ActiveModel::Errors doc

### LINKED ISSUE #41124: ActiveModel::Errors#add docs example misplaced
### Steps to reproduce
Read the docs [here](https://api.rubyonrails.org/classes/ActiveModel/Errors.html#method-i-add) for the `add(attribute, type = :invalid, **options)` method is missing and example on how to pass a variable to the translation. 

### Expected behavior
There should be an example. like the one that can be seen on `added?(attribute, type = :invalid, **options)`.
something like: 
```
person.errors.add :name, :too_long, { count: 25 }
person.errors.messages                               # => {:name=>["is too long (maximum is 25 characters)"}
```
### Actual behavior
The example is misplaced on the `added?(attribute, type = :invalid, **options)` method: [here](https://api.rubyonrails.org/classes/ActiveModel/Errors.html#method-i-added-3F)

### System configuration
**Rails version**: 6.1.0

**Ruby version**: >= 2.5.0

### PR DESCRIPTION
**Pull request by Vin0uz**
👋 

This diff closes #41124

As stated in the issue, a quick example of how options can be used to be part of the generated message was missing, but appearing in another method doc (`added?`)

I didn't move the piece in `added?` because it seems to be well-belonging there, but copied the example in `add`

### CODE REVIEW

File: activemodel/lib/active_model/errors.rb [hunk 1]
```diff
@@ -381,6 +381,11 @@ def group_by_attribute
     # If +type+ is a proc, it will be called, allowing for things like
     # <tt>Time.now</tt> to be used within an error.
     #
+    # If +type+ is compatible, +options+ will be injected in the translation.
```
Comment (gmcgibbon) [inline activemodel/lib/active_model/errors.rb:384]: Instead of placing this here, I would put it directly under the `If +type+ is a symbol...` line and add an example with and without interpolation like:
```
person.errors.add(:name, :blank)
person.errors.messages
# => {:name=>["can't be blank"]}

person.errors.add(:name, :too_long, { count: 25 })
person.errors.messages
# => ["is too long (maximum is 25 characters)"]
```

Comment (Vin0uz) [reply activemodel/lib/active_model/errors.rb:384]: That's indeed a nicer way to do it, thank !

**Comment by rafaelfranca** [comment]
Could you please squash your commits in one?

File: activemodel/lib/active_model/errors.rb [hunk 2]
```diff
@@ -378,6 +378,14 @@ def group_by_attribute
     # If +type+ is a symbol, it will be translated using the appropriate
     # scope (see +generate_message+).
     #
+    #   person.errors.add(:name, :blank)
+    #   person.errors.messages
+    #   # => {:name=>["can't be blank"]}
+
```
Comment (kamipo) [inline activemodel/lib/active_model/errors.rb:384]:
```suggestion
    #
```

Comment (Vin0uz) [reply activemodel/lib/active_model/errors.rb:384]: > 

🙈 thanks
