### PR TITLE
[Fix #49981] Support enum definition with symbol values

### LINKED ISSUE #49981: Enum definition with symbol values are not correctly typed_casted
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :status
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  enum :status, { draft: :draft, published: :published }
end

class BugTest < Minitest::Test
  def test_enum_symbol_value_definition_returns_nil_when_accessed_on_record
    post = Post.create!(status: :draft)
    assert_equal 'draft', post.status
    # Failure:
    # BugTest#test_enum_symbol_value_definition_returns_nil_when_accessed_on_record [rails_enum_symbol_value_issue.rb:36]:
    # Expected: "draft"
    #  Actual: nil
  end

  def test_enum_symbol_value_definition_breaks_predicates
    post = Post.create!(status: :draft)
    assert post.draft?
    # Failure:
    # BugTest#test_enum_symbol_value_definition_breaks_predicates [rails_enum_symbol_value_issue.rb:41]:
    # Expected false to be truthy.
  end

  def test_enum_symbol_value_definition_is_correclty_saved_in_database
    post = Post.create!(status: 'draft')
    assert_equal 'draft', post.attributes_before_type_cast['status']
  end
end
```

### Expected behavior

When an enum is defined with symbol values
  `enum :status, { draft: :draft, published: :published }`
a warning or an exception could be raised to force fixing, same kind as invalid enum definition.
Not sure this is the correct approach since the value is correctly persisted.

I'd expect the enum symbol value to be converted to string to allow correct type_cast.

### Actual behavior

the type_cast of a symbol value of an enum is always returning `nil`.

### System configuration
**Rails version**: main (60d05cd)

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by jean-francois-labbe**
### Motivation / Background

This Pull Request has been created because Enum definition with symbol values are not correctly typed_casted
reported here: https://github.com/rails/rails/issues/49981

Fixes #49981

### Detail
When an enum is defined with symbol values
`enum :status, { draft: :draft, published: :published }`
a warning or an exception could be raised to force fixing, same kind as invalid enum definition.
Not sure this is the correct approach since the value is correctly persisted.

I'd expect the enum symbol value to be converted to string to allow correct type_cast.

**Actual behavior**

the type_cast of a symbol value of an enum is always returning nil.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/lib/active_record/enum.rb [hunk 1]
```diff
@@ -346,6 +346,12 @@ def assert_valid_enum_definition_values(values)
           if values.keys.any?(&:blank?)
             raise ArgumentError, "Enum values #{values} must not contain a blank name."
           end
+
+          if values.values.any?(Symbol)
```
Comment (jean-francois-labbe) [inline activerecord/lib/active_record/enum.rb:350]: I don't think `assert_valid_enum_definition_values(values)` is the right place to put it. this is first implementation to validate the fix

Comment (byroot) [reply activerecord/lib/active_record/enum.rb:350]: I think it's fine. But rather to check just for symbols, it should check the type of all values to ensure it's something excpected.

Comment (jean-francois-labbe) [reply activerecord/lib/active_record/enum.rb:350]: I found that possible value types are `[Integer, String, Symbol, TrueClass, FalseClass, NilClass]`.
Is testing that the value types are in the array above or should I check that it contains only Integer or only boolean or only String and Symbols ?

Comment (jean-francois-labbe) [reply activerecord/lib/active_record/enum.rb:361]: @byroot I updated the code. I hope it does what you meant.
