### PR TITLE
remove unnessary option setting from test runner

### LINKED ISSUE #24372: Valid rake command line arguments reported as invalid on running 'test' task
### Steps to reproduce
```bash
rbenv shell 2.3.0
gem install rails -v '5.0.0.beta3'
rails new test-a
cd test-a
echo "gem 'therubyracer', platforms: :ruby" >> Gemfile
bundle install && bundle update
which rake
bundle exec which rake
#Next two lines works fine
rake --rakefile "`pwd`/Rakefile" about
rake --rakefile "`pwd`/Rakefile" --tasks
# Next two lines would fail with output: "invalid option: --rakefile"
rake --rakefile "`pwd`/Rakefile" test
bundle exec rake --rakefile "`pwd`/Rakefile" test
```
### Expected behavior
It should work ;)
Rake arguments should be passed to rake.

### Actual behavior
Got exit code 1 and "invalid option: --rakefile" output

After some 'debugging' I've next stacktrace:
```text
invalid option: --rakefile
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/test_unit/minitest_plugin.rb:57:in `plugin_rails_options'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/minitest-5.8.4/lib/minitest.rb:190:in `block (2 levels) in process_args'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/minitest-5.8.4/lib/minitest.rb:188:in `each'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/minitest-5.8.4/lib/minitest.rb:188:in `block in process_args'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/minitest-5.8.4/lib/minitest.rb:162:in `new'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/minitest-5.8.4/lib/minitest.rb:162:in `process_args'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/minitest-5.8.4/lib/minitest.rb:116:in `run'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/test_unit/minitest_plugin.rb:64:in `rake_run'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/test_unit/testing.rake:15:in `block in <top (required)>'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `block in execute'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `each'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
```
It seems test framework tries to parse all rake cli arguments

### System configuration
**Rails version**:
5.0.0.beta3

**Ruby version**:
2.3.0 by rbenv

### PR DESCRIPTION
**Pull request by y-yagi**
If run the test over the `rake` command, because of the test patterns is passed
via `rake_run` method, do not need to be obtained from the argv.

This probably fixes #24372.

### CODE REVIEW

File: railties/test/application/test_runner_test.rb [hunk 1]
```diff
@@ -502,6 +502,14 @@ def test_pass_TEST_env_on_rake_test
       assert_match '1 runs, 1 assertions', output
     end
 
+    def test_pass_rake_options
+      create_test_file :models, 'account'
+      output =  Dir.chdir(app_path) { `bin/rake --trace=stdout test` }
+
+      assert_match '1 runs, 1 assertions', output
+      assert_match 'Execute test', output
+    end
```
Comment (vipulnsward) [inline railties/test/application/test_runner_test.rb]: Can we add test from https://github.com/rails/rails/issues/24372 to accompany this?

**Comment by vipulnsward** [comment]
Nice fix. This does work for me now: 

```
rake --rakefile "`pwd`/Rakefile" test
bundle exec rake --rakefile "`pwd`/Rakefile" test
```

But 
```
rake --rakefile "`pwd`/Rakefile" routes
```
doesn't. We can probably check and include a fix for that here.

**Comment by y-yagi** [comment]
Thank you for pointing it out!

Also fixed `routes` task.

File: railties/test/application/test_runner_test.rb (hunk 1 above)
Comment (y-yagi) [inline railties/test/application/test_runner_test.rb]: You mean add a test using `--rakefile` option?

If so, I've added a test.

File: railties/lib/rails/tasks/routes.rake [hunk 2]
```diff
@@ -19,6 +19,9 @@ task routes: :environment do
 
   OptionParser.new do |opts|
     opts.banner = "Usage: rails routes [options]"
+
+    Rake.application.standard_rake_options.each { |args| opts.on(*args) }
```
Comment (kaspth) [inline railties/lib/rails/tasks/routes.rake]: This is iffy. We'd likely need to swallow rake options for every Rails command with custom option parsing.

File: railties/lib/rails/test_unit/minitest_plugin.rb [hunk 3]
```diff
@@ -54,7 +54,7 @@ def self.plugin_rails_options(opts, options)
 
     options[:color] = true
     options[:output_inline] = true
-    options[:patterns] = opts.order!
+    options[:patterns] = opts.order! unless defined?(@rake_patterns)
```
Comment (kaspth) [inline railties/lib/rails/test_unit/minitest_plugin.rb]: Would rather have the ivar override here, when it's defined, and remove the check down below.

Comment (kaspth) [inline railties/lib/rails/test_unit/minitest_plugin.rb]: Down below meaning in `plugin_rails_init` 😁

File: railties/lib/rails/tasks/routes.rake (hunk 2 above)
Comment (kaspth) [inline railties/lib/rails/tasks/routes.rake]: Hmm, come to think of it there might not be other cases since routes and test are the only rake tasks we fiddled with in Rails 5. So this feels like an ok compromise 👍

File: railties/lib/rails/test_unit/minitest_plugin.rb (hunk 3 above)
Comment (y-yagi) [inline railties/lib/rails/test_unit/minitest_plugin.rb]: Thanks for reviewing! I updated!

**Comment by kaspth** [comment]
❤️

**Comment by y-yagi** [comment]
:smile:
