### PR TITLE
Reject Railties line_filtering from AS::BacktraceCleaner test

### LINKED ISSUE #56078: BacktraceCleanerCleanLocationsTest fails when running via bin/test
### Steps to reproduce

```ruby
git clone https://github.com/rails/rails
cd rails/activesupport
bundle install
bin/test test/backtrace_cleaner_test.rb -n /test_returns_all_clean_location/
```

### Expected behavior
All of tests should pass.

### Actual behavior
These two tests fail.

```ruby
$ bin/test test/backtrace_cleaner_test.rb -n /test_returns_all_clean_location/
Running 31 tests in a single process (parallelization threshold is 50)
Run options: -n /test_returns_all_clean_location/ --seed 12502

# Running:

.F

Failure:
BacktraceCleanerCleanLocationsTest#test_returns_all_clean_locations_(:silent) [test/backtrace_cleaner_test.rb:254]:
--- expected
+++ actual
@@ -1 +1 @@
-["/home/yahonda/src/github.com/rails/rails/activesupport/test/backtrace_cleaner_test.rb"]
+["/home/yahonda/src/github.com/rails/rails/activesupport/test/backtrace_cleaner_test.rb", "/home/yahonda/src/github.com/rails/rails/railties/lib/rails/test_unit/line_filtering.rb"]



bin/test test/backtrace_cleaner_test.rb:252

F

Failure:
BacktraceCleanerCleanLocationsTest#test_returns_all_clean_locations_(defaults) [test/backtrace_cleaner_test.rb:249]:
--- expected
+++ actual
@@ -1 +1 @@
-["/home/yahonda/src/github.com/rails/rails/activesupport/test/backtrace_cleaner_test.rb"]
+["/home/yahonda/src/github.com/rails/rails/activesupport/test/backtrace_cleaner_test.rb", "/home/yahonda/src/github.com/rails/rails/railties/lib/rails/test_unit/line_filtering.rb"]



bin/test test/backtrace_cleaner_test.rb:247



Finished in 0.005119s, 586.0436 runs/s, 781.3915 assertions/s.
3 runs, 4 assertions, 2 failures, 0 errors, 0 skips
$
``` 

### System configuration

**Rails version**:  main branch

**Ruby version**: ruby 3.4.7 (2025-10-08 revision 7a5688e2a2) +PRISM [x86_64-linux]

### PR DESCRIPTION
**Pull request by zzak**
Fixes #56078 /cc @yahonda

### CODE REVIEW

File: activesupport/test/backtrace_cleaner_test.rb [hunk 1]
```diff
@@ -241,7 +241,9 @@ def setup
 
   # Adds a frame from this file to the call stack.
   def indirect_caller_locations
-    caller_locations
+    caller_locations.reject do |loc|
+      loc.path.end_with?("railties/lib/rails/test_unit/line_filtering.rb")
```
Comment (guilleiguaran) [inline activesupport/test/backtrace_cleaner_test.rb]: An alternative, not sure if it's better

```suggestion
      loc.path == Object.const_source_location('Rails::LineFiltering')[0]
```
