### PR TITLE
Use column alias of primary_key in limited_ids_for

### LINKED ISSUE #28364: Limited ids returns incorrect results
### Steps to reproduce

This query returns wrong results, because issues.id is incorrectly used as a condition for the primary key.
### Expected behavior
I removed issues.id from the order statement

>> Project.eager_load(:issues).order('issues.subject').limit(10)
  SQL SELECT  DISTINCT `projects`.`id`, issues.subject AS alias_0 FROM `projects` LEFT OUTER JOIN `issues` ON `issues`.`project_id` = `projects`.`id`  ORDER BY issues.subject LIMIT 10
  SQL SELECT `projects`.`id` AS t0_r0, `projects`.`name` AS t0_r1, `projects`.`description` AS t0_r2, `projects`.`homepage` AS t0_r3, `projects`.`is_public` AS t0_r4, `projects`.`parent_id` AS t0_r5, `projects`.`created_on` AS t0_r6, `projects`.`updated_on` AS t0_r7, `projects`.`identifier` AS t0_r8, `projects`.`status` AS t0_r9, `projects`.`lft` AS t0_r10, `projects`.`rgt` AS t0_r11, `projects`.`easy_is_easy_template` AS t0_r12, `projects`.`easy_due_date` AS t0_r13, `projects`.`author_id` AS t0_r14, `projects`.`easy_start_date` AS t0_r15, `projects`.`easy_level` AS t0_r16, `projects`.`easy_external_id` AS t0_r17, `projects`.`inherit_members` AS t0_r18, `projects`.`calculation_discount` AS t0_r19, `projects`.`calculation_position` AS t0_r20, `projects`.`client_id` AS t0_r21, `projects`.`calculation_discount_is_percent` AS t0_r22, `projects`.`client_name` AS t0_r23, `projects`.`calculation_date` AS t0_r24, `projects`.`easy_currency_id` AS t0_r25, `projects`.`easy_baseline_for_id` AS t0_r26, `projects`.`easy_currency_code` AS t0_r27, `projects`.`default_version_id` AS t0_r28, `projects`.`dmsf_description` AS t0_r29, `projects`.`dmsf_notification` AS t0_r30, `projects`.`easy_priority_id` AS t0_r31, `projects`.`easy_has_custom_menu` AS t0_r32, `issues`.`id` AS t1_r0, `issues`.`tracker_id` AS t1_r1, `issues`.`project_id` AS t1_r2, `issues`.`subject` AS t1_r3, `issues`.`description` AS t1_r4, `issues`.`due_date` AS t1_r5, `issues`.`category_id` AS t1_r6, `issues`.`status_id` AS t1_r7, `issues`.`assigned_to_id` AS t1_r8, `issues`.`priority_id` AS t1_r9, `issues`.`fixed_version_id` AS t1_r10, `issues`.`author_id` AS t1_r11, `issues`.`lock_version` AS t1_r12, `issues`.`created_on` AS t1_r13, `issues`.`updated_on` AS t1_r14, `issues`.`start_date` AS t1_r15, `issues`.`done_ratio` AS t1_r16, `issues`.`estimated_hours` AS t1_r17, `issues`.`easy_is_easy_template` AS t1_r18, `issues`.`parent_id` AS t1_r19, `issues`.`root_id` AS t1_r20, `issues`.`lft` AS t1_r21, `issues`.`rgt` AS t1_r22, `issues`.`is_private` AS t1_r23, `issues`.`activity_id` AS t1_r24, `issues`.`easy_level` AS t1_r25, `issues`.`easy_external_id` AS t1_r26, `issues`.`easy_due_date_time` AS t1_r27, `issues`.`easy_helpdesk_mailbox_username` AS t1_r28, `issues`.`easy_helpdesk_project_sla_id` AS t1_r29, `issues`.`closed_on` AS t1_r30, `issues`.`easy_is_repeating` AS t1_r31, `issues`.`easy_repeat_settings` AS t1_r32, `issues`.`easy_next_start` AS t1_r33, `issues`.`easy_start_date_time` AS t1_r34, `issues`.`calculation_position` AS t1_r35, `issues`.`calculation_rate` AS t1_r36, `issues`.`easy_ldap_entity_mapping` AS t1_r37, `issues`.`resolved_at` AS t1_r38, `issues`.`closed_at` AS t1_r39, `issues`.`easy_response_date_time` AS t1_r40, `issues`.`calculation_discount` AS t1_r41, `issues`.`calculation_discount_is_percent` AS t1_r42, `issues`.`calculation_unit` AS t1_r43, `issues`.`easy_time_to_solve_paused_at` AS t1_r44, `issues`.`easy_closed_by_id` AS t1_r45, `issues`.`easy_sms_tel_num` AS t1_r46, `issues`.`easy_sms_binding_method` AS t1_r47, `issues`.`easy_status_updated_on` AS t1_r48, `issues`.`in_easy_calculation` AS t1_r49, `issues`.`easy_reopen_at` AS t1_r50, `issues`.`easy_sprint_id` AS t1_r51, `issues`.`easy_last_updated_by_id` AS t1_r52, `issues`.`easy_time_to_solve_pause` AS t1_r53, `issues`.`easy_helpdesk_need_reaction` AS t1_r54, `issues`.`easy_story_points` AS t1_r55 FROM `projects` LEFT OUTER JOIN `issues` ON `issues`.`project_id` = `projects`.`id` WHERE `projects`.`id` IN (167, 102, 132, 168, 103, 133, 169, 104, 134, 171)  ORDER BY issues.subject
**=> #<ActiveRecord::Relation [#<Project id: 102, ....]>
=> got 10 results**

### Actual behavior

>> Project.eager_load(:issues).order('issues.id, issues.subject').limit(10)
DISTINCT doesn't work here like it was intended, project ids will not be uniq!
  SQL  **SELECT  DISTINCT `projects`.`id`, issues.id, issues.subject** AS alias_0 FROM `projects` LEFT OUTER JOIN `issues` ON `issues`.`project_id` = `projects`.`id`  ORDER BY issues.id, issues.subject LIMIT 10
  SQL SELECT `projects`.`id` AS t0_r0, `projects`.`name` AS t0_r1, `projects`.`description` AS t0_r2, `projects`.`homepage` AS t0_r3, `projects`.`is_public` AS t0_r4, `projects`.`parent_id` AS t0_r5, `projects`.`created_on` AS t0_r6, `projects`.`updated_on` AS t0_r7, `projects`.`identifier` AS t0_r8, `projects`.`status` AS t0_r9, `projects`.`lft` AS t0_r10, `projects`.`rgt` AS t0_r11, `projects`.`easy_is_easy_template` AS t0_r12, `projects`.`easy_due_date` AS t0_r13, `projects`.`author_id` AS t0_r14, `projects`.`easy_start_date` AS t0_r15, `projects`.`easy_level` AS t0_r16, `projects`.`easy_external_id` AS t0_r17, `projects`.`inherit_members` AS t0_r18, `projects`.`calculation_discount` AS t0_r19, `projects`.`calculation_position` AS t0_r20, `projects`.`client_id` AS t0_r21, `projects`.`calculation_discount_is_percent` AS t0_r22, `projects`.`client_name` AS t0_r23, `projects`.`calculation_date` AS t0_r24, `projects`.`easy_currency_id` AS t0_r25, `projects`.`easy_baseline_for_id` AS t0_r26, `projects`.`easy_currency_code` AS t0_r27, `projects`.`default_version_id` AS t0_r28, `projects`.`dmsf_description` AS t0_r29, `projects`.`dmsf_notification` AS t0_r30, `projects`.`easy_priority_id` AS t0_r31, `projects`.`easy_has_custom_menu` AS t0_r32, `issues`.`id` AS t1_r0, `issues`.`tracker_id` AS t1_r1, `issues`.`project_id` AS t1_r2, `issues`.`subject` AS t1_r3, `issues`.`description` AS t1_r4, `issues`.`due_date` AS t1_r5, `issues`.`category_id` AS t1_r6, `issues`.`status_id` AS t1_r7, `issues`.`assigned_to_id` AS t1_r8, `issues`.`priority_id` AS t1_r9, `issues`.`fixed_version_id` AS t1_r10, `issues`.`author_id` AS t1_r11, `issues`.`lock_version` AS t1_r12, `issues`.`created_on` AS t1_r13, `issues`.`updated_on` AS t1_r14, `issues`.`start_date` AS t1_r15, `issues`.`done_ratio` AS t1_r16, `issues`.`estimated_hours` AS t1_r17, `issues`.`easy_is_easy_template` AS t1_r18, `issues`.`parent_id` AS t1_r19, `issues`.`root_id` AS t1_r20, `issues`.`lft` AS t1_r21, `issues`.`rgt` AS t1_r22, `issues`.`is_private` AS t1_r23, `issues`.`activity_id` AS t1_r24, `issues`.`easy_level` AS t1_r25, `issues`.`easy_external_id` AS t1_r26, `issues`.`easy_due_date_time` AS t1_r27, `issues`.`easy_helpdesk_mailbox_username` AS t1_r28, `issues`.`easy_helpdesk_project_sla_id` AS t1_r29, `issues`.`closed_on` AS t1_r30, `issues`.`easy_is_repeating` AS t1_r31, `issues`.`easy_repeat_settings` AS t1_r32, `issues`.`easy_next_start` AS t1_r33, `issues`.`easy_start_date_time` AS t1_r34, `issues`.`calculation_position` AS t1_r35, `issues`.`calculation_rate` AS t1_r36, `issues`.`easy_ldap_entity_mapping` AS t1_r37, `issues`.`resolved_at` AS t1_r38, `issues`.`closed_at` AS t1_r39, `issues`.`easy_response_date_time` AS t1_r40, `issues`.`calculation_discount` AS t1_r41, `issues`.`calculation_discount_is_percent` AS t1_r42, `issues`.`calculation_unit` AS t1_r43, `issues`.`easy_time_to_solve_paused_at` AS t1_r44, `issues`.`easy_closed_by_id` AS t1_r45, `issues`.`easy_sms_tel_num` AS t1_r46, `issues`.`easy_sms_binding_method` AS t1_r47, `issues`.`easy_status_updated_on` AS t1_r48, `issues`.`in_easy_calculation` AS t1_r49, `issues`.`easy_reopen_at` AS t1_r50, `issues`.`easy_sprint_id` AS t1_r51, `issues`.`easy_last_updated_by_id` AS t1_r52, `issues`.`easy_time_to_solve_pause` AS t1_r53, `issues`.`easy_helpdesk_need_reaction` AS t1_r54, `issues`.`easy_story_points` AS t1_r55 FROM `projects` LEFT OUTER JOIN `issues` ON `issues`.`project_id` = `projects`.`id` WHERE `projects`.`id` IN (**NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL**)  ORDER BY issues.id, issues.subject
**=> #<ActiveRecord::Relation []>
=> got no results!**

changing the order should not have any effect on results count

### System configuration
tested on Rails 4.2.7.1 and current master
ruby 2.3.3 mingw
works correctly on sqlite, doesn't work on mysql & postgres

### PR DESCRIPTION
**Pull request by kg8m**
ActiveRecord::FinderMethods#limited_ids_for adds order_values to select in some RDBMS, e.g., PostgreSQL, MySQL, and so on. If order_values include other table's primary key, wrong primary key values may be found because they are ambiguous.

Using unique column alias makes free from ambiguity.

Fixes #28364

### CODE REVIEW

**Comment by kamipo** [comment]
I feel that this issue is not `limited_ids_for` but `columns_for_ distinct`.
`limited_ids_for` gives an alias to a string as being a single column.
(e.g. order = "authors.id, posts.id, comments.id" -> "#{order} AS alias_0")

So using `.order("authors.id", "posts.id", "comments.id")` instead works as expected in this case.

**Comment by kg8m** [comment]
@kamipo Thank you so much for your comment.😋

I feel that this issue is not `columns_for_distinct` but `limited_ids_for` because it depends on `limited_ids_for` implementation whether primary key is used or not. So I think `limited_ids_for` should be care about primary key and `order_values`.

It is too hard to always separate `order_values` like `.order("authors.id", "posts.id", "comments.id")`. Sometimes `ORDER BY` SQL is a `String` composed of multi columns due to various reasons. Parse the SQL? It may cause bugs...💀

**Comment by kamipo** [comment]
I don't think that this issue depends on `limited_ids_for` implementation since it doesn't happens for sqlite3 adapter, and at least this issue can be fixed without `limited_ids_for` is changed.

```diff
diff --git a/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb b/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb
index 608258d05c..964e45d7bc 100644
--- a/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb
+++ b/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb
@@ -513,7 +513,7 @@ def columns_for_distinct(columns, orders) # :nodoc:
           s.gsub(/\s+(?:ASC|DESC)\b/i, "")
         }.reject(&:blank?).map.with_index { |column, i| "#{column} AS alias_#{i}" }
 
-        [super, *order_columns].join(", ")
+        (order_columns << columns).join(", ")
       end
 
       def strict_mode?
diff --git a/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb b/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb
index 6f3db772cd..1a31deaaf9 100644
--- a/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb
+++ b/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb
@@ -583,7 +583,7 @@ def columns_for_distinct(columns, orders) #:nodoc:
                .gsub(/\s+NULLS\s+(?:FIRST|LAST)\b/i, "")
             }.reject(&:blank?).map.with_index { |column, i| "#{column} AS alias_#{i}" }
 
-          [super, *order_columns].join(", ")
+          (order_columns << columns).join(", ")
         end
 
         def update_table_definition(table_name, base) # :nodoc:
```

**Comment by kg8m** [comment]
Sorry, my comment was wrong. This issue is `columns_for_distinct` as you say. I didn't have good idea to fix this issue by changing only `columns_for_distinct`, so I tried to fix `limited_ids_for`.

Your idea looks good to me. I reverted `limited_ids_for` changes and add a commit changing `columns_for_distinct`s. Can you check them and give feedbacks?

File: activerecord/test/cases/finder_test.rb [hunk 1]
```diff
@@ -1180,6 +1180,13 @@ def test_find_with_order_on_included_associations_with_construct_finder_sql_for_
       order("author_addresses_authors.id DESC").limit(3).to_a.size
   end
 
+  def test_find_with_eager_loading_collection_and_ordering_by_collection_primary_key
+    Comment.delete_all
+    Post.delete_all
```
Comment (kamipo) [inline activerecord/test/cases/finder_test.rb]: `delete_all`s are unnecessary.

**Comment by kamipo** [comment]
Can you add a CHANGELOG entry and squash your commits?

File: activerecord/test/cases/finder_test.rb (hunk 1 above)
Comment (kg8m) [reply activerecord/test/cases/finder_test.rb]: If removing `delete_all`s, the test succeeds even without applying the patch, doesn't it?

**Comment by kg8m** [comment]
So sorry, I took changes in `master` branch in... And added a CHANGELOG entry @ 952f6421bdb5ffa24184577e8434a8ae0f4cc876 .

**Comment by kg8m** [comment]
I will squash my commits after your chec. Or should I recreate a new PR?

File: activerecord/test/cases/finder_test.rb (hunk 1 above)
Comment (kamipo) [reply activerecord/test/cases/finder_test.rb]: I see. Prefer reusing existing fixture like `assert_equal Post.first, Post.eager_load(comments: :ratings).order("posts.id, ratings.id, comments.id").first`.

**Comment by kamipo** [comment]
It is enough to squash your commits into one in this PR.

**Comment by kg8m** [comment]
I fixed the test and squashed my commits. Thank you for your advices.

**Comment by kamipo** [comment]
Thanks!
