### PR TITLE
LocalCache with read_multi should respect version and expire

### LINKED ISSUE #54408: read_multi with ActiveSupport::LocalCache doesn't respect cache_version
### Steps to reproduce

When trying to use `Rails.cache.read_multi` when there's a local cache (like in a controller during a request, as set by the `LocalCache::Middleware`), it doesn't verify the cache version (check for `mismatched?`). I think it might also not check if the entry is expired.

This is a minimal script using a `MemCachedStore`, not sure if there's a quicker way to do it. I'm bumping the `cache_version` to reproduce, in my app I'm reproducing with an ActiveRecord object's `touch`.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  gem "dalli"
end

require "active_support"
require "minitest/autorun"

class Post
  attr_accessor :cache_version

  def to_param
    1
  end
end

class BugTest < ActiveSupport::TestCase
  def test_using_a_local_cache
    cache = ActiveSupport::Cache.lookup_store(:mem_cache_store)
    cache.with_local_cache do
      post = Post.new
      post.cache_version = "001"
      key = ["foo", post]

      cache.write(key, "contents")

      assert_equal "contents", cache.read(key)
      assert_equal "contents", cache.read_multi(key)[key]

      post.cache_version = "002"
      assert_nil cache.read(key)
      assert_nil cache.read_multi(key)[key]
    end
  end
end
```

### Expected behavior

I'd expect `read_multi` to not return anything if the `cache_version` has changed. The test fails in the last line.

I could imagine that we use a local cache during a request so that cache reads are repeatable (sort of like an ActiveRecord query cache), but the behavior is inconsistent between `read` and `read_multi`, so I feel like it's a bug.

I can also see that [`read`](https://github.com/rails/rails/blob/v8.0.1/activesupport/lib/active_support/cache.rb#L507-L513) has explicit checks for `expired?` and `mismatched?`, but [`read_multi`](https://github.com/rails/rails/blob/v8.0.1/activesupport/lib/active_support/cache.rb#L536-L548) doesn't.

### Actual behavior

`read_multi` returns "stale" cache contents from the local cache.

### System configuration
**Rails version**: 8.0.1

**Ruby version**: 3.4.1

### PR DESCRIPTION
**Pull request by zzak**
Fixes #54408

### CODE REVIEW

File: activesupport/test/cache/behaviors/local_cache_behavior.rb [hunk 1]
```diff
@@ -242,6 +242,37 @@ def test_local_cache_of_read_multi
     end
   end
 
+  def test_local_cache_of_read_multi_with_expiry
```
Comment (zzak) [inline activesupport/test/cache/behaviors/local_cache_behavior.rb:245]: These tests fail before the patch:

```
$ bin/test test/cache/stores/mem_cache_store_test.rb

Run options: --seed 61134

Failure:
MemCacheStoreTest#test_local_cache_of_read_multi_with_expiry [test/cache/behaviors/local_cache_behavior.rb:253]:
Expected # encoding: US-ASCII
#    valid: true
"JCvcplCM210bdRjF" to be nil.

bin/test test/cache/behaviors/local_cache_behavior.rb:245

MemCacheStoreTest#test_local_cache_of_read_multi_with_versions [test/cache/behaviors/local_cache_behavior.rb:272]:
Expected "contents" to be nil.

bin/test test/cache/behaviors/local_cache_behavior.rb:258
```

**Comment by mrsimo** [comment]
Thanks a lot @zzak!

File: activesupport/CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,7 @@
+*   `ActiveSupport::LocalCache` now respects version and expiry when using `#read_multi`.
+
+    *zzak*
```
Comment (byroot) [inline activesupport/CHANGELOG.md:3]: It's a bug fix, so generally we only add to the changelog when backporting.

File: activesupport/lib/active_support/cache/strategy/local_cache.rb [hunk 3]
```diff
@@ -129,17 +129,23 @@ def read_multi_entries(names, **options)
...
-            if missed_names.any?
-              local_entries.merge!(super(missed_names, **options))
-            else
-              local_entries
+            results = local_entries.each_with_object({}) do |(key, value), result|
+              normalized_key = keys_to_names[key]
+              version = normalize_version(normalized_key, options)
+
+              entry = deserialize_entry(value, **options)
+              if entry && (entry.expired? || entry.mismatched?(version))
```
Comment (byroot) [inline activesupport/lib/active_support/cache/strategy/local_cache.rb:138]:
```suggestion
              if entry && (entry.expired? || entry.mismatched?(normalize_version(keys_to_names[key], options)))
```

Would be better, because while more verbose we'd save on computing the version for missing and expired entries.

File: activesupport/lib/active_support/cache/strategy/local_cache.rb [hunk 4]
```diff
@@ -129,17 +129,23 @@ def read_multi_entries(names, **options)
...
+                local_cache.delete_entry(key)
+              else
+                result[normalized_key] = entry&.value
+              end
             end
+
+            missed_names = names - results.keys
+
+            results.merge!(super(missed_names, **options)) if missed_names.any?
```
Comment (byroot) [inline activesupport/lib/active_support/cache/strategy/local_cache.rb:147]:
```suggestion
            if results.size < names.size
              missed_names = names - results.keys
              results.merge!(super(missed_names, **options)) if missed_names.any?
            end
```

A bit of a micro-opt, but on the happy path we're save an array intersection.

File: activesupport/lib/active_support/cache/strategy/local_cache.rb (hunk 3 above)
Comment (byroot) [reply activesupport/lib/active_support/cache/strategy/local_cache.rb:138]: Also if `entry` is `nil` we should skip.

Comment (byroot) [reply activesupport/lib/active_support/cache/strategy/local_cache.rb]: Nevermind, that's part of the spec.

**Comment by byroot** [comment]
Backported to 8.0 and 7.2
