### PR TITLE
Fix `Cache::NullStore` with local caching for repeated reads

### LINKED ISSUE #45690: NullStore cache randomly blows up in asynchronous cases
### Steps to reproduce

This appears to be an esoteric bug that I found in an edge case while running asynchronous code that all queried the `NullStore` cache (which was empty).

I couldn't come up with a way to replicate without loading the entire application, nor by loading the application on another machine, but I did manage to fix it locally by adding a safe navigation operator on: https://github.com/rails/rails/blob/752b566152ca3e8daf4804c90777cc1a01d003f6/activesupport/lib/active_support/cache/strategy/local_cache.rb#L135

What I'm wondering is if this is a sensible thing to adjust to avoid this weird case.

### Expected behavior

Cache value should return `nil` and fall through to continuing code.

### Actual behavior

```ruby
undefined method `value' for nil:NilClass
   
                   deserialize_entry(payload).value
                                              ^^^^^
 /Users/mtanous/.gem/ruby/3.1.2/gems/activesupport-7.0.3.1/lib/active_support/cache/strategy/local_cache.rb:127:in `block in read_multi_entries'
    /Users/mtanous/.gem/ruby/3.1.2/gems/activesupport-7.0.3.1/lib/active_support/cache/strategy/local_cache.rb:126:in `transform_values!'
    /Users/mtanous/.gem/ruby/3.1.2/gems/activesupport-7.0.3.1/lib/active_support/cache/strategy/local_cache.rb:126:in `read_multi_entries'
    /Users/mtanous/.gem/ruby/3.1.2/gems/activesupport-7.0.3.1/lib/active_support/cache.rb:425:in `block in read_multi'
    /Users/mtanous/.gem/ruby/3.1.2/gems/activesupport-7.0.3.1/lib/active_support/cache.rb:778:in `block in instrument'
    /Users/mtanous/.gem/ruby/3.1.2/gems/activesupport-7.0.3.1/lib/active_support/notifications.rb:208:in `instrument'
    /Users/mtanous/.gem/ruby/3.1.2/gems/activesupport-7.0.3.1/lib/active_support/cache.rb:778:in `instrument'
    /Users/mtanous/.gem/ruby/3.1.2/gems/activesupport-7.0.3.1/lib/active_support/cache.rb:424:in `read_multi'
16156 /Users/mtanous/src/github.com/Shopify/grid-next/app/lib/cache.rb:35:in `read_multi'
```

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #45690, check it for the details.

It is reproducible by configuring null cache store and calling the same read operation (like `Rails.cache.read_multi("foo", "bar")`) multiple times. After the first call, the local cache will include all the keys with nils. In the second, we retrieve this nils and trying to call `.value` on it.

So I think, in the original issue one thread called read once, and another thread - again, so hence the error.

cc @CodingAnarchy @byroot

### CODE REVIEW

File: activesupport/lib/active_support/cache/strategy/local_cache.rb [hunk 1]
```diff
@@ -132,7 +132,7 @@ def read_multi_entries(keys, **options)
 
             local_entries = local_cache.read_multi_entries(keys)
             local_entries.transform_values! do |payload|
-              deserialize_entry(payload).value
+              deserialize_entry(payload)&.value
```
Comment (casperisfine) [inline activesupport/lib/active_support/cache/strategy/local_cache.rb:135]:
```suggestion
              deserialize_entry(payload).value unless payload.nil?
```

if I'm not mistaken, `payload` is `nil` here, so might as well skip `deserialize_entry`

Comment (casperisfine) [reply activesupport/lib/active_support/cache/strategy/local_cache.rb:135]: Actually nevermind, design wise it's best not to assume anything about how a nil payload may be deserialized.
