### PR TITLE
 Fix documentation of url_for module [ci skip]

### LINKED ISSUE #16160: ActionController::UrlFor requires more as a Rack-compatible request
Hi,

I tried to use ```ActionController::UrlFor``` together with grape. The documentation claimes that a Rack-compatible request is all you need to get it up and running. But my minimal Request class has to look like this (rails 4.1.2):

```ruby
class MyRequest < Rack::Request

    def symbolized_path_parameters
      ActiveSupport::Deprecation.warn(
          "`symbolized_path_parameters` is deprecated. Please use `path_parameters`"
      )
      path_parameters
    end

    # Returns a hash with the \parameters used to form the \path of the request.
    # Returned hash keys are strings:
    #
    # {'action' => 'my_action', 'controller' => 'my_controller'}
    def path_parameters
       {}
    end

    # Returns 'https://' if this is an SSL request and 'http://' otherwise.
    def protocol
      @protocol ||= ssl? ? 'https://' : 'http://'
    end

    # Returns the standard \port number for this request's protocol.
    def standard_port
      if ssl?
       443
      else
        80
      end
    end

    # Returns whether this request is using the standard port
    def standard_port?
      port == standard_port
    end

    # Returns a number \port suffix like 8080 if the \port number of this request
    # is not the default HTTP \port 80 or HTTPS \port 443.
    def optional_port
      standard_port? ? nil : port
    end
  end
```

Required are these additional methods:

* symbolized_path_parameters
* protocol
* optional_port

After this additions I could create a class like this one:

```ruby
class RoutingHelper
    include ActionController::UrlFor
    include Rails.application.routes.url_helpers

    attr_accessor :request, :env

    def initialize(env)
      self.request = MyRequest.new(env)
      self.env = env
    end

  end
```

Maybe it is a real bug or a documentation bug.

regards
dieter

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
- The request needs to be instance of ActionDispatch::Request or should
  respond to host, optional_port, protocol and
  symbolized_path_parameter.
- This documentation was correctly added in
  https://github.com/rails/rails/commit/e3b3f416b57f5642ea25078485f7e9394ad04526
  but was changed to
  https://github.com/rails/rails/commit/e1ceae576e3911f3e6708b5d19a0e3ef63769eb7.
- Fixes #16160.

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
/cc @rafaelfranca  https://github.com/rails/rails/issues/16160#issuecomment-50478097.

I used your comments in commit message :sweat_smile:

File: actionpack/lib/action_controller/metal/url_for.rb [hunk 1]
```diff
@@ -4,7 +4,10 @@ module ActionController
   #
   # In addition to <tt>AbstractController::UrlFor</tt>, this module accesses the HTTP layer to define
   # url options like the +host+. In order to do so, this module requires the host class
-  # to implement +env+ and +request+, which need to be a Rack-compatible.
+  # to implement +env+ which need to be Rack-compatible and +request+
+  # which is either instance of +ActionDispatch::Request+ or respond
```
Comment (arthurnn) [inline actionpack/lib/action_controller/metal/url_for.rb]: Maybe something like this, would be better?
`or an instace of an object that responds to ...`

Comment (shunsukeaida) [inline actionpack/lib/action_controller/metal/url_for.rb]: Also, <code>which need<b>s</b> to be</code>, perhaps?

Comment (prathamesh-sonpatki) [inline actionpack/lib/action_controller/metal/url_for.rb]: @arthurnn 
`or an object that responds to... `?

Thanks @shunsukeaida Fixing it.

Comment (prathamesh-sonpatki) [inline actionpack/lib/action_controller/metal/url_for.rb]: @arthurnn The complete sentence is

```
     - The request needs to be instance of ActionDispatch::Request or an
       object that responds to host, optional_port, protocol and
       symbolized_path_parameter.
```

Comment (arthurnn) [inline actionpack/lib/action_controller/metal/url_for.rb]: :cool:
