### PR TITLE
Fix rubocop issue for action cable -- ostruct

### LINKED ISSUE #47377: Using `ActionCable::Channel::TestCase` causes NameError: `TestServer` is missing
I came across an error `NameError: uninitialized constant ActionCable::Channel::ConnectionStub::TestServer` when I run tests with action_cable.

#47300 added `@server` in `ActionCable::Channel::ConnectionStub` as an instance of `TestServer`, and `TestServer` seems to be located in `actioncable/test`. Perhaps, Rails testing scripts usually load test helpers, so the problem hasn't occurred. However, such an implicit loading might cause unstable test behavior, so I think `TestServer` should be loaded when requiring `ActionCable::Channel::TestCase`. But I'm not sure how to do that. `TestServer` should be written inside `actioncable/lib`? That's why I opened an issue here.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source 'https://rubygems.org'

  gem "rails", github: "rails/rails", ref: "d6eec533c186c92448e7413e9af9c2a2009aca99"
end

require "action_cable"
require "minitest/autorun"
require "logger"

ActionCable.server.config.cable ||= {}
ActionCable.server.config.cable["adapter"] = "async"
ActionCable.server.config.logger = Logger.new(STDOUT)

module ApplicationCable
  class Connection < ActionCable::Connection::Base
  end
end

module ApplicationCable
  class Channel < ActionCable::Channel::Base
    def hello(data)
      ActionCable.server.broadcast("nice_#{params[:number]}", data)
    end

    private

    def subscribed
      stream_from "nice_#{params[:number]}"
      reject if Integer(params[:number], exception: false).negative?
    end
  end
end

class Test < ActionCable::Channel::TestCase
  tests ApplicationCable::Channel

  def test_hello
    subscribe number: "2"
    perform :hello, { name: "MM" }
  end
end
```

### Expected behavior

I expect the test to pass in the above example without any exceptions.

### Actual behavior

```
Error:
Test#test_hello:
NameError: uninitialized constant ActionCable::Channel::ConnectionStub::TestServer
    /Users/yutaka.kamei/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-d6eec533c186/actioncable/lib/action_cable/channel/test_case.rb:60:in `initialize'
    /Users/yutaka.kamei/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-d6eec533c186/actioncable/lib/action_cable/channel/test_case.rb:236:in `new'
    /Users/yutaka.kamei/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-d6eec533c186/actioncable/lib/action_cable/channel/test_case.rb:236:in `stub_connection'
    /Users/yutaka.kamei/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/rails-d6eec533c186/actioncable/lib/action_cable/channel/test_case.rb:241:in `subscribe'
    a.rb:43:in `test_hello'
```

### System configuration
**Rails version**:
7.1.0.alpha (d6eec533c186c92448e7413e9af9c2a2009aca99)

**Ruby version**:
3.2.0

### PR DESCRIPTION
**Pull request by hahmed**
### Motivation / Background

~~Action cable is breaking when creating a simple test like below, because of an error `NameError: uninitialized constant ActionCable::Channel::ConnectionStub::TestServer`. The test_server is now inside the lib folder, alongside a the success_adapter which it depends on.~~

```
require "test_helper"

class RandomChannelTest < ActionCable::Channel::TestCase
  test "subscribes" do
    subscribe
    assert subscription.confirmed?
  end
end
```

~~This Pull Request has been created because https://github.com/rails/rails/issues/47377 which relates to a change merged in https://github.com/rails/rails/pull/47300~~

The second commit addresses the rubocop performance issue where I added a fake config class that inherits from `ActionCable::Server::Configuration`. The `subscription_adapter` is added so it can be overridden in tests, this seems like a a better option than using a struct in which a whole bunch of vars need to be assigned/overridden. 

### Detail

Fix rubocop issue with using ostruct.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by zzak** [comment]
@hahmed Can you look at fixing the rubocop failures?

```
actioncable/lib/action_cable/test_server.rb:15:28: C: Performance/OpenStruct: Consider using Struct over OpenStruct to optimize the performance.
[12](https://github.com/rails/rails/actions/runs/4188289466/jobs/7259226717#step:4:13)
      @config = OpenStruct.new(log_tags: [], subscription_adapter: subscription_adapter, filter_parameters: [])
[13](https://github.com/rails/rails/actions/runs/4188289466/jobs/7259226717#step:4:14)
                           ^^^
[14](https://github.com/rails/rails/actions/runs/4188289466/jobs/7259226717#step:4:15)
```

File: actioncable/lib/action_cable/test_server.rb [hunk 1]
```diff
@@ -0,0 +1,44 @@
+# frozen_string_literal: true
+
+module ActionCable
+  class TestServer # nodoc
```
Comment (zzak) [inline actioncable/lib/action_cable/test_server.rb:4]:
```suggestion
  class TestServer # :nodoc:
```

File: actioncable/test/test_server.rb [hunk 2]
```diff
@@ -2,13 +2,13 @@
 
 require "ostruct"
 
-class TestServer
+class TestServer # nodoc
```
Comment (zzak) [inline actioncable/test/test_server.rb:5]:
```suggestion
class TestServer # :nodoc:
```

**Comment by palkan** [comment]
>  The test_server is now inside the lib folder, alongside a the success_adapter which it depends on.

I don't like the idea of exposing library internals just for the sake of fixing an accidentally introduce regression. SuccessAdapter doesn't make any sense for applications as well as TestServer. Channel::TestCase is meant for isolated testing, no server should be involved at all.

Here is an alternative fix: https://github.com/rails/rails/pull/47483

File: actioncable/test/stubs/test_server.rb [hunk 3]
```diff
@@ -1,18 +1,28 @@
 # frozen_string_literal: true
 
-require "ostruct"
```
Comment (zzak) [inline actioncable/test/stubs/test_server.rb:3]: Unrelated, but I do like removing `ostruct` 👍
