### PR TITLE
Fix `relation.create` to avoid leaking scope to initialization block and callbacks

### LINKED ISSUE #9894: ActiveRecord.where(hash).create callbacks inherit the where(hash)
Running rails 4.0.0-beta1 on ruby 2.0.0-p1.

It seems as though when you perform code like the below, the where clauses are inherited by any callbacks it runs.

``` ruby
Category.where(full_name: 'root/bar').create
```

The above exhibits the problem. All of the below function as intended.

``` ruby
Category.new(full_name: 'root/bar').save
Category.create(full_name: 'root/bar')
Category.where(full_name: 'root/bar').new.save
```

By debugging on the rails console it reveals:

``` ruby
# This is basically running
Category.where(full_name: 'root/bar').where(full_name: 'root').first

# When this is expected
Category.where(full_name: 'root').first
```

This also applies to the first_or_create methods. I'm yet to test the find_or_create methods or the rails 3.x series. Should I write this into an active_record test? Any advice as to where to start?

I've created an example application with this problem here https://github.com/brocktimus/rails_create_differences. Example class used below.

``` ruby
class Category < ActiveRecord::Base

  has_many :children, class_name: 'Category', foreign_key: :parent_id
  belongs_to :parent, class_name: 'Category'

  before_validation :assign_parents, on: :create

  private

  def assign_parents
    parts = full_name.split '/'
    self.name = parts.pop
    self.parent = Category.where(full_name: parts.join('/')).first_or_initialize unless parts.empty?
  end

end
```

### LINKED ISSUE #17577: Strange scoping behaviour when `first_or_initialize` takes a block.
When calling `first_or_initialize` or `first_or_create` with a block, there's some really weird interaction with ActiveRecord scopes. I believe this is caused by the same problem as #7391, #7853 and #9894 all of which were closed as "expected behaviour". However in all three of these issues, the behaviour in question presented itself in Callbacks.

I believe the fact that this behaviour also presents itself in the block parameter opens this issue up for reconsideration.

An example of the problematic behaviour:

``` ruby
[1] pry(main)> Label.where(color: "foo").first_or_initialize { p Label.all }
  Label Load (0.5ms)  SELECT  "labels".* FROM "labels"  WHERE "labels"."color" = 'foo'  ORDER BY "labels"."id" ASC LIMIT 1
  Label Load (0.3ms)  SELECT "labels".* FROM "labels"  WHERE "labels"."color" = 'foo'
#<ActiveRecord::Relation []>
```

Look closely at the generated SQL. The call to `Label.all` within the block generates the following SQL:

``` sql
SELECT "labels".* FROM "labels"  WHERE "labels"."color" = 'foo'
```

It has clearly applied the scope that `first_or_initialize` was called on. IMO this is completely unexpected. It breaks all expectations of how Ruby code usually works. In our situation, the problem presented itself in an even evil-er way. We were calling `first_or_initialize` like this:

``` ruby
Label.where(color: "foo").first_or_initialize(&:pick_color)
```

And then:

``` ruby
class Label < ActiveRecord::Base
   belongs_to :account

   def pick_color
     labels  = account.labels 
     # ...
   end
end
```

Here we'd expect `account.labels` to return all labels of the account, but it doesn't! It finds only those labels which have `color = "foo"`, since the scope is (imo) erroneously applied.

We unit tested the `pick_color` method and verified that it worked as expected, only to find that it broke in a really surprising way when we called it through `find_or_initialize`. Again it seems very unexpected that the caller of the method could affect its behaviour in such a way.

Here's a Gist using the AR bug template: https://gist.github.com/jnicklas/7c7e27e6880cd8c40ecd

EDIT:

here's a workaround in case anyone else runs into this problem. Not exactly pretty :(

``` ruby
class Label < ActiveRecord::Base
   belongs_to :account

   def pick_color
     labels  = Label.unscoped.where(account_id: account_id)
     # ...
   end
end
```

### PR DESCRIPTION
**Pull request by kamipo**
`relation.create` populates scope attributes to new record by `scoping`,
it is necessary to assign the scope attributes to the record and to find
STI subclass from the scope attributes.

But the effect of `scoping` is class global, it was caused undesired
behavior that pollute all class level querying methods in initialization
block and callbacks (`after_initialize`, `before_validation`,
`before_save`, etc), which are user provided code.

To avoid the leaking scope issue, restore the original current scope
before initialization block and callbacks are invoked.

Fixes #9894.
Fixes #17577.
Closes #31526.

### CODE REVIEW

File: activerecord/lib/active_record/relation.rb [hunk 1]
```diff
@@ -67,6 +67,11 @@ def bind_attribute(name, value) # :nodoc:
     #   user = users.new { |user| user.name = 'Oscar' }
     #   user.name # => Oscar
     def new(attributes = nil, &block)
+      current_scope = klass.current_scope(true)
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/relation.rb]: It feels to me that this is being done at the wrong level. Relation should not know about scoping. Maybe this should be done in the scoping class?

cc @matthewd

**Review by rafaelfranca — COMMENTED** [review]
Would not this cause breaking changes?

File: activerecord/lib/active_record/relation.rb (hunk 1 above)
Comment (kamipo) [reply activerecord/lib/active_record/relation.rb]: I agree that here is not best place to do this.
But Relation has `scoping` method, and already need to know the result of `klass.current_scope(true)` in some places (in `scoping`, `spawn`, etc), so I just do this here since here is only place to do this.

If we'd not like to do this here, an option is just extracting to method in the scoping class like the following:

```diff
diff --git a/activerecord/lib/active_record/relation.rb b/activerecord/lib/active_record/relation.rb
index 32f0609798..347d745d19 100644
--- a/activerecord/lib/active_record/relation.rb
+++ b/activerecord/lib/active_record/relation.rb
@@ -67,11 +67,7 @@ def bind_attribute(name, value) # :nodoc:
     #   user = users.new { |user| user.name = 'Oscar' }
     #   user.name # => Oscar
     def new(attributes = nil, &block)
-      current_scope = klass.current_scope(true)
-      block = -> record do
-        klass.current_scope = current_scope
-        yield record if block_given?
-      end
+      block = klass.current_scope_restoring_block(&block)
       scoping { klass.new(attributes, &block) }
     end
 
diff --git a/activerecord/lib/active_record/scoping.rb b/activerecord/lib/active_record/scoping.rb
index 35e9dcbffc..1142a87d25 100644
--- a/activerecord/lib/active_record/scoping.rb
+++ b/activerecord/lib/active_record/scoping.rb
@@ -30,6 +30,14 @@ def current_scope(skip_inherited_scope = false)
       def current_scope=(scope)
         ScopeRegistry.set_value_for(:current_scope, self, scope)
       end
+
+      def current_scope_restoring_block(&block)
+        current_scope = self.current_scope(true)
+        -> *args do
+          self.current_scope = current_scope
+          yield(*args) if block_given?
+        end
+      end
     end
 
     def populate_with_current_scope_attributes # :nodoc:
```

File: activerecord/test/models/bird.rb [hunk 2]
```diff
@@ -16,4 +16,9 @@ class Bird < ActiveRecord::Base
   def cancel_save_callback_method
     throw(:abort)
   end
+
+  attr_accessor :total_count
+  after_initialize do
+    self.total_count = Bird.count
```
Comment (kamipo) [inline activerecord/test/models/bird.rb]: > Would not this cause breaking changes?

Before this PR #35186, the `self.total_count = Bird.count` in `after_initialize` and the `Bird.find_by!(name: "canary")` are affected by `Bird.where(color: "green").scoping { }` in `Bird.where(color: "green").create`, so `parrot.total_count` will be 0 and `Bird.find_by!(name: "canary")` will raise `RecordNotFound`.

```ruby
canary = Bird.create!(color: "yellow", name: "canary")
parrot = Bird.where(color: "green").create do |bird|
  bird.name = "parrot"
  assert_equal canary, Bird.find_by!(name: "canary")
end
assert_equal 1, parrot.total_count
```

If anyone depends on the behavior, it is affected by this change.
But I think the leaking scope is just a bug, probably most people use a workaround `Bird.unscoped.count` and `Bird.unscoped.find_by!(name: "canary")` for a long time.

File: activerecord/lib/active_record/relation.rb (hunk 1 above)
Comment (rafaelfranca) [reply activerecord/lib/active_record/relation.rb]: That could be a nice refactoring

File: activerecord/test/models/bird.rb (hunk 2 above)
Comment (rafaelfranca) [reply activerecord/test/models/bird.rb]: :+1

File: activerecord/lib/active_record/relation.rb (hunk 1 above)
Comment (kamipo) [reply activerecord/lib/active_record/relation.rb]: Applied 4cb1438b57067d637c79d49d0662c43b5b4e64c2.

File: activerecord/test/models/bird.rb (hunk 2 above)
Comment (zarelit) [reply activerecord/test/models/bird.rb]: @kamipo Thank you for the fix :-)

Comment (rafaelfranca) [reply activerecord/test/models/bird.rb]: I'm still concerned about this breaking change. If people is relying on this behavior they may start to leak information silently like happened some years ago in the GitHub incident.

Is there any way we can detect people is relying on this behavior and show them a warning?

@tenderlove @matthewd @jeremy what do you think?

Comment (tenderlove) [reply activerecord/test/models/bird.rb]: Please correct me if I'm wrong, but if the scope is leaking, then the scope in `after_initialize` etc would depend on the context in which the object is created.  People depending on this behavior would have to have exactly one code path for initialization, otherwise they would have to do `unscoped` because the scope would be different each time.

Could we set the scope object to something that raises an exception if `unscoped` *isn't* called?

Comment (kamipo) [reply activerecord/test/models/bird.rb]: Since `scoping` is public API, people may have a usage like the case (1).
In the case (1), initialization block and callbacks are affected by the `Bird.where(color: "yellow").scoping`.
I made the case (2) working the same with the case (1) in this PR.

We could set the exception scope object for the case (2), it will make the case (2) working different back with the case (1) though...

```ruby
canary = Bird.create!(color: "yellow", name: "canary")

# (1)
Bird.where(color: "yellow").scoping do
  parrot = Bird.create!(color: "green") do |bird|
    bird.name = "parrot"
    assert_equal canary, Bird.find_by!(name: "canary")
  end
  assert_equal 1, parrot.total_count
end

# (2)
Bird.where(color: "yellow").scoping do
  parrot = Bird.rewhere(color: "green").create! do |bird|
    bird.name = "parrot"
    assert_equal canary, Bird.find_by!(name: "canary")
  end
  assert_equal 1, parrot.total_count
end
```
