### PR TITLE
Delegate child session assertions to parent session

### LINKED ISSUE #32142: Assertions in IntegrationTest sessions incorrectly reported
Assertions run inside a separate session in `ActionDispatch::IntegrationTest` are not counted in the test report.

#### TL;DR

Running this test

```ruby
class TLDRTest < ActionDispatch::IntegrationTest
  test('assert in session') { open_session.assert(true) }
end
```

reports an incorrect number of assertions

```diff
# Running:

.

Finished in 0.001477s, 677.0481 runs/s, 0.0000 assertions/s.
-1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
+1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

<details>
<summary>Full Test</summary>

```ruby
#! /usr/bin/env ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) { gem 'rails', '5.1.5', source: 'https://rubygems.org' }
require 'rails/all'
require "minitest/autorun"

class AssertionTest < ActionDispatch::IntegrationTest
  test('assert outside session') { assert(true) } # control
  test('assert in session') { open_session.assert(true) }
end

class BugTest < Minitest::Test
  def test_control
    test_instance = AssertionTest.new('test_assert_outside_session').run
    refute_predicate test_instance.assertions, :zero?
  end

  def test_actual
    test_instance = AssertionTest.new('test_assert_in_session').run
    refute_predicate test_instance.assertions, :zero?
  end
end
```

</details>

### Expected behavior

The assertions in sessions should be counted in the test report.

### Actual behavior
The assertions in sessions are not counted in the test report.

### System configuration
**Rails version**: 5.1.5

**Ruby version**: 2.4.2

----
cc. @aud

### PR DESCRIPTION
**Pull request by sambostock**
### Summary

This fixes #32142, in which assertions made in sub-sessions in `ActionDispatch::IntegrationTest` are not counted in the test run report.

By overriding the `assertions` accessor methods on the child session to use the parent's `assertions`, the count is accurately tracked.

### Other Information

- Is this the appropriate fix, or is there a better way to delegate to the parent session?
- Is this the appropriate test? Should test report output be asserted on instead?

----
cc. @aud

### CODE REVIEW

File: actionpack/lib/action_dispatch/testing/integration.rb [hunk 1]
```diff
@@ -366,6 +366,11 @@ def remove! # :nodoc:
       def open_session
         dup.tap do |session|
           session.reset!
+
+          parent = self
+          session.define_singleton_method(:assertions) { parent.assertions }
```
Comment (rafaelfranca) [inline actionpack/lib/action_dispatch/testing/integration.rb]: Instead of dynamically defining the method just define it in the Runner module.

**Review by rafaelfranca — CHANGES_REQUESTED** [review]

File: actionpack/lib/action_dispatch/testing/integration.rb (hunk 1 above)
Comment (sambostock) [reply actionpack/lib/action_dispatch/testing/integration.rb]: 🤔 I don't think that would work.

If I defined it on `Runner` wouldn't it apply to all instances of `IntegrationTest`? We need the parent to keep the original implementation, or else we'll have infinite recursion once it hits the parent.

```ruby
class Parent
  attr_accessor :attribute

  def child
    dup.tap do |duplicate|
      parent = self
      child.define_singleton_method(:attribute) { parent.attribute }
      child.define_singleton_method(:attribute=) { |a| parent.attribute = a }
    end
  end
end
```

That's the behaviour I want, in terms of all children delegating to the parent instance for `attribute`. I'm not sure how I'd be able to delegate to the parent without doing it dynamically, since we have no reference to it outside `open_session`.

Am I missing something?

Comment (sambostock) [reply actionpack/lib/action_dispatch/testing/integration.rb]: I suppose an alternative approach could be something like this.

```ruby
class ActionDispatch::Integration::Session::Runner
  attr_accessor :parent_session

  def assertions
    parent_session ? parent_session.assertions : super
  end

  def assertions=(assertions)
    parent_session ? parent_session.assertions = assertions : super
  end

  def open_session
    dup.tap do |session|
      session.reset!

      self.parent_session = self

      yield session if block_given?
    end
  end
end
```

Moves the dynamic logic into the method, rather than dynamically defining the method itself.

Comment (rafaelfranca) [reply actionpack/lib/action_dispatch/testing/integration.rb]: Yup, that is what I was referring. Just make sure to add `# :nodoc:` on the attribute and new methods.

**Comment by sambostock** [comment]
I found myself working on some integration tests and realized this never shipped 😅

- I've **rebased** on latest master, and **squashed** my previous commits.
- I realized that in that a grandchild session is opened by opening a session inside a child session, the _delegation is indirect_. Therefore, I pushed another commit which switches to storing the **root** session, not the _parent_ one.
- I noticed another relevant accessor that could result in miscounts would be **`failures`**. **Should it also be proxied to the `root_session`?**

**Comment by rafaelfranca** [comment]
> * I noticed another relevant accessor that could result in miscounts would be **`failures`**. **Should it also be proxied to the `root_session`?** What about the [various other related variables](https://github.com/seattlerb/minitest/blob/e6bc4485730403faff6966c1671cf5de72b2d233/lib/minitest.rb#L634-:641)?

I think we should make sure all of them work.

**Comment by sambostock** [comment]
I did some experimenting, and it turns out I was wrong about all those variables.

As far as I can tell, they're defined on the report, not the test itself. The only relevant instance variables are `@assertions` and `@failures`.

`@assertions` is already handled, and the following test (adapted from #32142's example) shows that `@failures` already works on Rails `5.2.3`.

<details><summary><code>@failures</code> test</summary>

```ruby
#! /usr/bin/env ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) { gem 'rails', source: 'https://rubygems.org' }
require 'rails/all'
require "minitest/autorun"

class FailuresTest < ActionDispatch::IntegrationTest
  test('flunk outside session') { assert(true) } # control
  test('flunk in session') { open_session.assert(true) }
end

class BugTest < Minitest::Test
  def test_control
    test_instance = FailuresTest.new('flunk_outside_session').run
    refute_predicate test_instance.failures, :empty?
  end

  def test_actual
    test_instance = FailuresTest.new('flunk_in_session').run
    refute_predicate test_instance.failures, :empty?
  end
end
```

</details>

I suspect this is because failures already bubble up due to their use of exceptions.

----

I have once again squashed and rebased, so unless there is other feedback, this should be good to go!
