### PR TITLE
Fix `unsubscribed` server side behavior

### LINKED ISSUE #23708: ActionCable disconnect client
I'm not if this is an issue or get something wrong. I'm using ActionCable.beta2 and i'm trying to do kind of "available online" chat feature. It's obvious that `subscribed` method is called when user is connected to channel, but `unsubscribed` is never called. I tried waiting for few hours, turning off browser or even computer. Every page refresh adds new subscriber to list, but there is no event to unsubscribe one. This leads to strange behaviour when message is broadcasted to huge amount of subscribers even when they are not really connected.

So my question is - what are the requirements to user get properly disconnected (on tab close, browser close or just navigate to subpage that don't have this channel subscription)?

PS. I set logger on disconnect in Connection too, it's just.. never called. I'm using Puma server and async adapter on development environment.

### PR DESCRIPTION
**Pull request by maclover7**
Closes #23708

Before this commit, the `unsubscribed` callbacks in Action Cable server
side channels were never called. This is because when a WebSocket
"goodbye" message was sent from the client, the Action Cable server
didn't properly clean up after the now closed WebSocket. This means that
memory could possibly skyrocket with this behavior, since part of this
commit is to properly remove closed subscriptions from the global
subscriptions hash. Say you have 10,000 users currently connected, and
then all 10,000 disconnect -- before this patch, Action Cable would
still hold onto information (and Ruby objects!) for all of these now
dead connections.

cc @dhh @matthewd

### CODE REVIEW

**Comment by jeremy** [comment]
Good catch. Test coverage to demonstrate the expected behavior?

**Comment by maclover7** [comment]
Was working on this earlier, but added a regression test to show the expected behavior. cc @matthewd since we talked about this in Campfire.

File: actioncable/test/client_test.rb [hunk 1]
```diff
@@ -198,4 +198,22 @@ def test_disappearing_client
...
     end
   end
+
+  def test_unsubscribe_client
+    with_puma_server do |port, app|
+      c = faye_client(port)
+      c.send_message command: 'subscribe', identifier: JSON.dump(channel: 'EchoChannel')
+      assert_equal({"identifier"=>"{\"channel\":\"EchoChannel\"}", "type"=>"confirm_subscription"}, c.read_message)
+      assert_equal(1, app.connections.count)
+      assert_equal(1, app.connections.first.subscriptions.method(:subscriptions).call.count)
```
Comment (maclover7) [inline actioncable/test/client_test.rb]: This is ugly (and definitely not public API), but is still necessary to demonstrate the regression test.

**Comment by maclover7** [comment]
@jeremy updated with regression test - all set to go?

File: actioncable/lib/action_cable/connection/subscriptions.rb [hunk 2]
```diff
@@ -54,7 +54,7 @@ def identifiers
       end
 
       def unsubscribe_from_all
-        subscriptions.each { |id, channel| channel.unsubscribe_from_channel }
+        subscriptions.each { |id, channel| remove({ 'identifier' => id }) }
```
Comment (matthewd) [inline actioncable/lib/action_cable/connection/subscriptions.rb]: Can we use `remove_subscription(channel)` here? This feels like unnecessary indirection (and I think I'd actually argue we *don't* want the log lines).

File: actioncable/test/client_test.rb [hunk 3]
```diff
@@ -198,4 +198,22 @@ def test_disappearing_client
...
+
+      channel = app.connections.first.subscriptions.method(:subscriptions).call.first[1]
```
Comment (matthewd) [inline actioncable/test/client_test.rb]: `method(:subscriptions).call`? :confused:

File: actioncable/test/client_test.rb [hunk 4]
```diff
@@ -198,4 +198,22 @@ def test_disappearing_client
...
+      channel.expects(:unsubscribed).returns('Goodbye from EchoChannel!')
```
Comment (matthewd) [inline actioncable/test/client_test.rb]: Is this `returns` doing what you think it is / intend it to?

Comment (maclover7) [inline actioncable/test/client_test.rb]: Yes -- I want to make sure that the `unsubscribed` method is properly called and handled.

File: actioncable/test/client_test.rb (hunk 3 above)
Comment (maclover7) [inline actioncable/test/client_test.rb]: I hate having this line, but I think this is the only way to get access to the `EchoChannel` instance -- as far as I can see, there is no non-weird way about that (or public API).
