### PR TITLE
Chain scope constraints should respect own table alias

### LINKED ISSUE #27666: Wrong query produced when through association duplicated.
### Steps to reproduce

```
# user.rb

class User
  has_one :family, through: :family_tree
  has_one :family_tree, -> { rewhere(token: nil) }, foreign_key: 'member_id'
  has_many :family_members, through: :family, source: 'members'
end
```

```
# family.rb

class Family < ActiveRecord::Base
  has_many :family_trees, -> { rewhere(token: nil) }
  has_many :members, through: :family_trees
end
```

```
# family_tree.rb
#
#  id        :integer          not null, primary key
#  family_id :integer
#  member_id :integer
#  token     :string
#

class FamilyTree < ActiveRecord::Base
  belongs_to :member, class_name: 'User', foreign_key: 'member_id'
  belongs_to :family, class_name: 'Family'

  validates :member, uniqueness: { scope: :family }
end

```

`user.family_members` makes the below query

```
SELECT "users"."id" FROM "users" 
INNER JOIN "family_trees" ON "users"."id" = "family_trees"."member_id" 
INNER JOIN "families" ON "family_trees"."family_id" = "families"."id" 
INNER JOIN "family_trees" "family_trees_family_members_join" ON "families"."id" = "family_trees_family_members_join"."family_id" 

WHERE "family_trees_family_members_join"."member_id" = $1 AND "family_trees"."token" IS NULL  [["member_id", 3363]]
```

In the result, it is different with `user.family_members` and `user.family.members`

### Expected behavior

I wrote the method named `family_members` instead of association like this

```
def family_members
  User.where(id: FamilyTree.where(family: family, token: nil).pluck(:member_id))
end
```

This is exactly what I expected.

### Actual behavior

`user.family_members` got the records which have a `family_tree` with `token` is not NULL

### System configuration

I'm using Rails 4.2.0 with Ruby 2.3.0

### PR DESCRIPTION
**Pull request by kamipo**
Fixes #27666.

### CODE REVIEW

File: activerecord/lib/active_record/associations/association_scope.rb [hunk 1]
```diff
@@ -153,14 +153,17 @@ def add_constraints(scope, owner, association_klass, refl, chain_head, chain_tai
...
 
           scope
         end
 
-        def eval_scope(klass, scope, owner)
-          klass.unscoped.instance_exec(owner, &scope)
+        def eval_scope(klass, table, scope, owner)
+          klass.unscoped.tap { |relation|
+            predicate_builder = PredicateBuilder.new(TableMetadata.new(klass, table))
+            relation.instance_variable_set(:@predicate_builder, predicate_builder)
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/associations/association_scope.rb]: This looks weird. Can we expose a setter in the relation?

**Review by rafaelfranca — CHANGES_REQUESTED** [review]

File: activerecord/lib/active_record/associations/association_scope.rb (hunk 1 above)
Comment (kamipo) [inline activerecord/lib/active_record/associations/association_scope.rb]: We have two choices.

* Expose a setter in the relation.
* Use `Relation.create` instead of `klass.unscoped` like `JoinAssociation`. https://github.com/rails/rails/blob/505463c859927408665ce141426f098fea303a4e/activerecord/lib/active_record/associations/join_dependency/join_association.rb#L48-L49

Which do you think is better?

Comment (rafaelfranca) [inline activerecord/lib/active_record/associations/association_scope.rb]: In this case use `.create`

File: activerecord/lib/active_record/associations/association_scope.rb [hunk 2]
```diff
@@ -153,14 +153,15 @@ def add_constraints(scope, owner, association_klass, refl, chain_head, chain_tai
...
           end
 
           scope
         end
 
-        def eval_scope(klass, scope, owner)
-          klass.unscoped.instance_exec(owner, &scope)
+        def eval_scope(klass, table, scope, owner)
+          predicate_builder = PredicateBuilder.new(TableMetadata.new(klass, table))
+          ActiveRecord::Relation.create(klass, table, predicate_builder).instance_exec(owner, &scope)
```
Comment (kamipo) [inline activerecord/lib/active_record/associations/association_scope.rb]: Fixed to use `Relation.create`.
