### PR TITLE
Don't eagerly compile StringJoin nodes

### LINKED ISSUE #54102: SQLite3::MismatchException: datatype mismatch when querying with a join to a has_many relationship that has a scope
### Steps to reproduce
I'm not totally sure this is a completely minimal reproduction, but it does appear to require a query joining via a has_many relationship that has a scope that contains a join.

I haven't observed this issue with PostgreSQL, only with SQLite.

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "~> 7.2.2.1"
  gem "sqlite3", "~> 2.5.0"
end

require "active_record/railtie"
require "minitest/autorun"

ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
  config.secret_key_base = "secret_key_base"
end

Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :instructors, force: true do |t|
  end

  create_table :instructor_roles, force: true do |t|
    t.integer :instructor_id
    t.integer :role_id
    t.integer :student_id
  end

  create_table :roles, force: true do |t|
  end

  create_table :students, force: true do |t|
    t.integer :status
  end
end

class Instructor < ActiveRecord::Base
  has_many :instructor_roles, -> { active }
end

class InstructorRole < ActiveRecord::Base
  belongs_to :instructor
  belongs_to :role
  belongs_to :student

  scope :active, -> {
    joins("JOIN students ON instructor_roles.student_id = students.id")
    .where("students.status = ?", 1)
  }
end

class Role < ActiveRecord::Base
  has_many :instructor_roles
end

class Student < ActiveRecord::Base
  has_many :instructor_roles
end

class BugTest < Minitest::Test
  def test_association_stuff
    # No error
    ir = InstructorRole.active.first
    # Raises an error
    i = Instructor.joins(:instructor_roles).first
  end
end

```

### Expected behavior
Not throw an exception.

### Actual behavior
`ActiveRecord::StatementInvalid: SQLite3::MismatchException: datatype mismatch`

### System configuration
**Rails version**: 7.2.2.1

**Ruby version**: ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]

This works in rails 7.1.5.1 and first appears in 7.2.0 (I haven't checked the beta or rc builds). It is still an issue in 8.0.1, but I can't currently update to 8.x due to other dependencies.

### PR DESCRIPTION
**Pull request by byroot**
Fix: https://github.com/rails/rails/issues/54102

It really isn't necessary, but also the way it was done would cause bind variables to be lost, resulting in broken queries.

### CODE REVIEW

File: activerecord/lib/active_record/associations/join_dependency/join_association.rb [hunk 1]
```diff
@@ -38,41 +38,39 @@ def join_constraints(foreign_table, foreign_klass, join_type, alias_tracker)
             chain << [reflection, table]
           end
 
-          base_klass.with_connection do |connection|
```
Comment (byroot) [inline activerecord/lib/active_record/associations/join_dependency/join_association.rb:41]: As a bonus, we no longer need to checkout the connection here. This was a big smell.
