### PR TITLE
Fixes #45868 by Using #to_hash to serialize `AS::HWIA` for stored attributes

### LINKED ISSUE #45868: ActiveRecord store deserialization fails with nested objects
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text "properties"
  end
end

class Post < ActiveRecord::Base
  store :properties
end

class BugTest < Minitest::Test
  def test_store_yaml_serialization
    post = Post.create! properties: { scalar_value: 2, nested_properties: { a: 3, b: 4 } }
    assert_equal 2, post.properties[:scalar_value]
  end
end

```

### Expected behavior
The serialization/deserialization round trip should work.

### Actual behavior
A `Psych::DisallowedClass` error is raised:
```
BugTest#test_store_yaml_serialization:
Psych::DisallowedClass: Tried to load unspecified class: ActiveSupport::HashWithIndifferentAccess
    /usr/lib/ruby/2.7.0/psych/class_loader.rb:97:in `find'
    /usr/lib/ruby/2.7.0/psych/class_loader.rb:28:in `load'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:411:in `resolve_class'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:283:in `visit_Psych_Nodes_Mapping'
    /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
    /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:340:in `block in revive_hash'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `each'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `each_slice'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `revive_hash'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
    /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
    /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:313:in `visit_Psych_Nodes_Document'
    /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
    /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
    /usr/lib/ruby/2.7.0/psych.rb:360:in `safe_load'
    .../.bundle/ruby/2.7.0/rails-241893900740/activerecord/lib/active_record/coders/yaml_column.rb:61:in `yaml_load'
    .../.bundle/ruby/2.7.0/rails-241893900740/activerecord/lib/active_record/coders/yaml_column.rb:26:in `load'
    .../.bundle/ruby/2.7.0/rails-241893900740/activerecord/lib/active_record/store.rb:275:in `load'
    .../.bundle/ruby/2.7.0/rails-241893900740/activerecord/lib/active_record/type/serialized.rb:22:in `deserialize'
    .../.bundle/ruby/2.7.0/rails-241893900740/activemodel/lib/active_model/attribute.rb:168:in `type_cast'
    .../.bundle/ruby/2.7.0/rails-241893900740/activemodel/lib/active_model/attribute.rb:43:in `value'
    .../.bundle/ruby/2.7.0/rails-241893900740/activemodel/lib/active_model/attribute_set.rb:51:in `fetch_value'
    .../.bundle/ruby/2.7.0/rails-241893900740/activerecord/lib/active_record/attribute_methods/read.rb:38:in `_read_attribute'
    .../.bundle/ruby/2.7.0/rails-241893900740/activemodel/lib/active_model/attribute_methods.rb:277:in `properties'
    serialize-case.rb:35:in `test_store_yaml_serialization'
```

The issue #45585 was marked as fixed with PR #45591, but that fix is incomplete. It does not take into account nested objects: e.g. in my example above, the top-level `properties` is converted from `HashWithIndifferentAccess` to a regular hash, but even after that conversion, `properties[:nested_properties]` remains a `HashWithIndifferentAccess`. `Activerecord::Store::IndifferentCoder#as_regular_hash` should work in a recursive fashion.

### System configuration
**Rails version**: 2418939 (7.1.0.alpha)

**Ruby version**: 2.7.4p191

### PR DESCRIPTION
**Pull request by the-spectator**
### Summary

Fixes #45868

Originally we were calling `#to_h` to serialize `ActiveSupport::HashWithIndifferentAccess` but it was serializing only top-level hash keys. 
By Using `#to_hash` to serialize `ActiveSupport::HashWithIndifferentAccess` it will also handle/convert nested objects.

### CODE REVIEW

File: activerecord/lib/active_record/store.rb [hunk 1]
```diff
@@ -290,7 +290,7 @@ def self.as_indifferent_hash(obj)
           def as_regular_hash(obj)
             case obj
             when ActiveSupport::HashWithIndifferentAccess
-              obj.to_h
+              obj.to_hash
             when Hash
               obj
```
Comment (tkalliom) [inline activerecord/lib/active_record/store.rb:295]: Maybe this is too contrived to consider, but technically you could have a `Hash` with a `HashWithIndifferentAccess` nested inside

Comment (the-spectator) [reply activerecord/lib/active_record/store.rb:295]: Great point @tkalliom. Looks like it would have to be a recursive solution.

File: activerecord/lib/active_record/store.rb [hunk 2]
```diff
@@ -290,9 +290,11 @@ def self.as_indifferent_hash(obj)
           def as_regular_hash(obj)
             case obj
             when ActiveSupport::HashWithIndifferentAccess
-              obj.to_h
+              obj.to_hash
             when Hash
-              obj
+              obj.transform_values { |value| value.is_a?(Hash) || value.is_a?(Array) ? as_regular_hash(value) : value }
+            when Array
+              obj.map { |value| value.is_a?(Hash) || value.is_a?(Array) ? as_regular_hash(value) : value }
```
Comment (tkalliom) [inline activerecord/lib/active_record/store.rb:297]: This duplicated block could be extracted, but maybe this is short enough that duplication is preferrable to indirection. Matter of taste.

**Review by tkalliom — COMMENTED** [review]
Functionally LGTM

**Comment by byroot** [comment]
I don't think we should do this. Active Record Store is responsible for the top level hash, anything inside is the responsability of the caller.

Some people might be serializing some HWIA in stores on purpose, and casting this would break their code.

You can pass a custom coder when registering the store that allows you to do all the casting that makes sense in your app, but Rails as a framework cannot assume which casting make sense.

**Comment by byroot** [comment]
Re-opening because I oversaw that `HashWithIndifferentAccess#[]=` will convert hashes into HWIA, so we do indeed need to convert that back.

However I think this does too much, just calling `.to_hash` should be enough to cast the hash that were converted automatically.

File: activerecord/lib/active_record/store.rb (hunk 2 above)
Comment (byroot) [inline activerecord/lib/active_record/store.rb:297]: We don't need that part of the change. Just the `to_h -> to_hash` is enough.

Comment (the-spectator) [reply activerecord/lib/active_record/store.rb:297]: @byroot Thank you for reviewing. If I am understanding it correctly, we should only call `HWIA#to_hash` and drop nested handling for `Hash` & `Array`. i.e
```ruby
def as_regular_hash(obj)
  case obj
  when ActiveSupport::HashWithIndifferentAccess
    obj.to_hash
  when Hash
     obj            
  else
    {}
   end
end
```

Comment (byroot) [reply activerecord/lib/active_record/store.rb:297]: Yes. `to_hash` will take care of the recursive behavior. If the top level object is already a regular hash, there is no point recursively checking the object graph.

Comment (byroot) [reply activerecord/lib/active_record/store.rb:297]: Actually, even simpler: `obj ? obj.to_hash : {}`, since `Hash#to_hash` returns self.

Comment (the-spectator) [reply activerecord/lib/active_record/store.rb:297]: 👍

Comment (the-spectator) [reply activerecord/lib/active_record/store.rb]: @byroot I opted for `obj.respond_to?(:to_hash) ? obj.to_hash : {}` as we have a test that fails when the passed object doesn't implement `#to_hash`. 

TEST "convert store attributes from any format other than Hash or HashWithIndifferentAccess losing the data" => `activerecord/test/cases/store_test.rb:208`

**Comment by byroot** [comment]
Backported to 7-0-stable. Thanks @the-spectator for the fix, and thanks @tkalliom for insisting when I misunderstood the issue.

**Comment by tkalliom** [comment]
Since the original fix #45591 was merged into 6-1-stable, should this fix of the fix be as well?

**Comment by byroot** [comment]
Done.

**Comment by dominikklein** [comment]
@byroot Any thoughts that this leads to a "changed" state when you fetch one object which has for example a store column. Afterward, the with_lock complains about an already existing lock (Locking a record with unpersisted changes is not supported. ). Do you have an idea, about a solution?

**Comment by byroot** [comment]
You mean the first time you fetch an old record that used to be serialized as `HWIA`?

Ideally you can go over you old records and update them. But yes, that's problematic. I don't see how we could handle that.

**Comment by dominikklein** [comment]
> You mean the first time you fetch an old record that used to be serialized as HWIA?
Yes, correct.

The problem is that it could be a lot of records and will take a lot of time to migrate this. 
But why is this marked as changed in this situation in the end it's the same data for the "outside".

**Comment by byroot** [comment]
> But why is this marked as changed in this situation in the end it's the same data for the "outside".

Because for checking if a serialized field is changed, Active Record compare their serialized forms, e.g:

```ruby
>> puts({"foo" => "bar"}.to_yaml)
---
foo: bar                                                                                  
=> nil                                                                                    
>> puts({"foo" => "bar"}.with_indifferent_access.to_yaml)
--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
foo: bar                                                                                  
=> nil   
```

So yeah, these columns effectively changed.

**Comment by mgruner** [comment]
In case anyone is interested, we implemented a workaround that will solve issues with failing `with_lock` calls because of the internally changed records:

```ruby
# Copyright (C) 2012-2022 Zammad Foundation, https://zammad-foundation.org/

module ActiveRecord::Locking::Pessimistic

  # https://github.com/zammad/zammad/issues/3664
  #
  # With Zammad 5.2 and Rails update from 6.1.6.2 to 6.1.7, internal database storage format
  #   of preferences columns changed from serialized `ActiveSupport::HashWithIndifferentAccess` to just serialized `Hash``.
  # The downside is that 'old' values still have the old format, and show up as changed, which prevents
  #   `with_lock` from working correctly - it would throw errors on previously modified records,
  #   making tickets/users non-updateable.
  # We work around this by suppressing the exception in just this case.
  if !method_defined?(:orig_lock!)

    alias orig_lock! lock!

    def lock!(lock = true) # rubocop:disable Style/OptionalBooleanParameter
      if persisted? && has_changes_to_save?

        # We will skip the exception in case if the changes only contain columns which are store-type and have idential value.
        skip_exception = changes.all? do |key, value|
          send(key.to_sym).instance_of?(ActiveSupport::HashWithIndifferentAccess) && Marshal.dump(value[0]) == Marshal.dump(value[1])
        end

        if skip_exception
          reload(lock: lock)
          return self
        end
      end

      orig_lock!(lock)
    end
  end
end
```
