### PR TITLE
Fix preventing writes for ApplicationRecord

### LINKED ISSUE #40559: preventing_writes? doesn't work in test environment
### Steps to reproduce

1. Turn off `ActiveRecord::Base.legacy_connection_handling`
2. Use `ApplicationRecord.connects_to()`
3. include `ActiveRecord::TestFixtures`
4. Create record from inside `ApplicationRecord.connected_to(role: :reading)` block. 

https://gist.github.com/alpaca-tc/23d658d28581fddecf3b593580f9caa4

### Expected behavior

raise `ActiveRecord::ReadOnlyError`.

### Actual behavior

Nothing was raised.

### System configuration
**Rails version**: 6.1.0.rc1

**Ruby version**: 2.7.1

---

I think that the cause is  that `#replica?` now returns false because of `ActiveRecord::TestFixtures` overwritten the pool config for reading.

`preventing_writes?` checks `replica?` at the first.
https://github.com/rails/rails/blob/b60838b0ac7a9ba8ef26ef7a6abce70fbcf84f15/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L122

`ActiveRecord::TestFixtures` removes `replica: true` option by overwriting pool config.
https://github.com/rails/rails/blob/b60838b0ac7a9ba8ef26ef7a6abce70fbcf84f15/activerecord/lib/active_record/test_fixtures.rb#L219

### PR DESCRIPTION
**Pull request by eileencodes**
Alt to https://github.com/rails/rails/pull/40966, fixes https://github.com/rails/rails/issues/40559

ApplicationRecord is special. If you have a multiple database
application we need to treat `ApplicationRecord` and
`ActiveRecord::Base` as the same connection, otherwise applications
will end up with duplicate connections to the same database. This is
problematic because there are a limited number of open connections an
application could have to a single database. By not treating
`ActiveRecord::Base` and `ApplicationRecord` the same we could
effectively double connections to a database (then multiplied by the
number of processes).

In the case of granular connection swapping we need to be able to read
`ApplicationRecord` off the stack while storing the
`connection_specification_name` as `ActiveRecord::Base`. In order to do
this we read the `current_preventing_writes` off the pool's
"owner_name" which was `connection_specification_name`.

To fix the issue here need to pass the original class to
`establish_connection` on the handler and then down to the `PoolConfig`.
We can then determine the `connection_specification_name` from the
`connection_klass` the same way we did in `resolve_config_for_connection`.
This isn't ideal, and I'd like to move away from the string class but
this has been part of the known API for awhile so I don't feel
comfortable changing that without investigation.

We can then read the `connection_klass` in `preventing_writes?` instead
of the connection specification name. If you're using a nil or string
value for your class, then multiple databases really won't work so
there's no point in supporting prevent writes for that.

Co-authored-by: John Crepezzi <john.crepezzi@gmail.com>
Co-authored-by: alpaca-tc <alpaca-tc@alpaca.tc>

cc/ @alpaca-tc

### CODE REVIEW

File: activerecord/test/cases/connection_pool_test.rb [hunk 1]
```diff
@@ -13,7 +13,7 @@ def setup
 
         # Keep a duplicate pool so we do not bother others
         @db_config = ActiveRecord::Base.connection_pool.db_config
-        @pool_config = ActiveRecord::ConnectionAdapters::PoolConfig.new("primary", @db_config)
+        @pool_config = ActiveRecord::ConnectionAdapters::PoolConfig.new(ActiveRecord::Base, @db_config)
```
Comment (eileencodes) [inline activerecord/test/cases/connection_pool_test.rb:16]: These should have always been `ActiveRecord::Base` - using primary was deprecated some time ago.

File: activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb [hunk 2]
```diff
@@ -1040,7 +1040,7 @@ def connection_pool_list(role = ActiveRecord::Base.current_role)
       end
       alias :connection_pools :connection_pool_list
 
-      def establish_connection(config, owner_name: Base.name, role: ActiveRecord::Base.current_role, shard: Base.current_shard)
+      def establish_connection(config, owner_name: Base, role: ActiveRecord::Base.current_role, shard: Base.current_shard)
```
Comment (eileencodes) [inline activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:1043]: There is a slight behavior change in this public API that now accepts the class instead of a string. We could defensively handle this but applications really should be using `establish_connection` on the handler for multiple databases and this API is new in 6.1 so I think it's ok to change it. Happy to handle a string if we disagree.

**Review by rafaelfranca — APPROVED** [review]
The fact that `ApplicationRecord` is special bothers me. Here is the problem, the name `ApplicationRecord` is not guaranteed and has nothing special. What happen if people have a `class MyApp::ApplicationRecord` class in the app? This is something we should support.

I like the direction this patch is going, but I wonder if there is a way to remove the `defined?(ApplicationRecord)` check from the library?

**Comment by eileencodes** [comment]
> What happen if people have a class MyApp::ApplicationRecord class in the app? This is something we should support.

We actually do this at github, we have a different one so I hear you. We override the private primary class method that we're using here in order to achieve that. I don't want application record to be special either, but we also can't have duplicate connections open for the same database without serious consequences for some applications. I can work on making `primary_class?` part of the public API in a separate PR. Does that work?

**Comment by eileencodes** [comment]
When I said ApplicationRecord is special, I really meant "the database that Rails connects to by default needs know which one of the classes should use the equivalent primary class". In most applications this is `ApplicationRecord`. Rails _has_ to have a connection on boot and in non-eager loaded environments only `ActiveRecord::Base.establish_connection` is called on boot by the AR Railtie. In all environments that railtie would cause a duplicate connection to the first database if we didn't handle `primary_class?` to figure out which one is "special". At GitHub we override `primary_class?` but I thought that not using `ApplicationRecord` was a strange github thing. If it's more common I'll dig more into making ApplicationRecord less special in AR and giving a path forward for apps that do change their `ApplicationRecord` to something else.

**Comment by rafaelfranca** [comment]
> `primary_class?` part of the public API in a separate PR. Does that work?

I think so. I think we can also start to generate an ApplicationRecord setting `self.primary_class = true` instead of `self.abstract_class = true`. And `self.primary_class = true` would also set `self.abstract_class = true`.

We do have many ApplicationRecord's at Shopify. I'd say something close to 20, so I guess it is better to have an easier construction like an attribute setter for this that will take over from abstract class and also defines the database connection host.

**Comment by eileencodes** [comment]
I'll work on a separate PR to make `primary_class` part of the public API later today. 👍🏻

**Comment by eileencodes** [comment]
I backported this to 6-1-stable in 5284a165b8e8821fcfca62dac360bd9ed7a674b4

**Comment by eileencodes** [comment]
Working on the test failures - didn't see them because they only happen on master with the isolated test runner.
