### PR TITLE
Backport #25364 to 4-2-stable

### LINKED ISSUE #25354: Time values not being typecast for `where` and `find` queries on a date field
I noticed this issue when I was getting inconsistent behaviour from passing `find_or_create` a Time object as the value for a query against a date field. `create` type-casts this value before saving, but it seems `find` and `where` do not.

The problem can obviously be fixed by calling `#to_date` on the Time object beforehand, or using a Date object in the first place, but I believe the type-casting behaviour should be consistent to avoid confusion.

### Steps to reproduce
__[View Test Case](https://gist.github.com/alextaylor000/df334ecc3da577ce0aaf569a3fd0f894)__

```ruby
date_as_time = Time.new(2016,06,10,19,0,0,'-08:00')
Post.create(date: date_as_time)
# INSERT INTO "posts" ("date") VALUES (?)  [["date", Wed, 10 Jun 2016]]
```

### Expected behavior
```ruby
Post.where(date: date_as_time).count
# => 1

Post.find_by(date: date_as_time)
# => <Post id: 1, date: "2016-06-10">
```

### Actual behavior
```ruby
Post.where(date: date_as_time).count
# => 0

Post.find_by(date: date_as_time)
# => nil
```

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.0p0

### PR DESCRIPTION
**Pull request by kamipo**
This PR is backport #25364 to 4-2-stable.

Currently `Type::Date#serialize` does not cast a value to a date object.
It should be cast to a date object for finding by date column correctly
working.

Fixes #25354.

r? @rafaelfranca

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Tests are failing with sqlite3, but I don't think it is related to this. I'll investigate.

**Comment by rafaelfranca** [comment]
Yes, seems it is related.

**Comment by kamipo** [comment]
Failing test was removed at 19537ecd0fcc888842a49007187c371fcb454d11 on master.
Can we remove the test on 4-2-stable?

**Comment by rafaelfranca** [comment]
Weird. But they are passing in 4-2-stable. Why they are broken in your branch?

File: activerecord/test/cases/adapters/sqlite3/quoting_test.rb [hunk 1]
```diff
@@ -58,22 +58,6 @@ def test_type_cast_false
...
-          assert_equal 10, @conn.type_cast('10', c)
-
-          c = Column.new(nil, 1, Type::Float.new)
-          assert_equal 10.1, @conn.type_cast('10.1', c)
-
-          c = Column.new(nil, 1, Type::Binary.new)
-          assert_equal '10.1', @conn.type_cast('10.1', c)
-
-          c = Column.new(nil, 1, Type::Date.new)
-          assert_equal '10.1', @conn.type_cast('10.1', c)
```
Comment (kamipo) [inline activerecord/test/cases/adapters/sqlite3/quoting_test.rb]: Actually this assert is unexpected behavior, I think.
Previously type casting against `Type::Date` was not worked.

Comment (rafaelfranca) [inline activerecord/test/cases/adapters/sqlite3/quoting_test.rb]: Oh, now I understand it. So those tests still make sense because the column information is still being used differently from 5.0, but this assertion needs to be changed or removed

File: activerecord/test/cases/adapters/sqlite3/quoting_test.rb [hunk 2]
```diff
@@ -71,7 +71,7 @@ def test_type_cast_string
           assert_equal '10.1', @conn.type_cast('10.1', c)
 
           c = Column.new(nil, 1, Type::Date.new)
-          assert_equal '10.1', @conn.type_cast('10.1', c)
+          assert_equal '2016-05-11', @conn.type_cast('2016-05-11 19:00:00', c)
```
Comment (kamipo) [inline activerecord/test/cases/adapters/sqlite3/quoting_test.rb]: Changed this assertion to expected behavior!

File: activerecord/lib/active_record/type/date.rb [hunk 3]
```diff
@@ -9,6 +9,10 @@ def klass
         ::Date
       end
 
+      def type_cast_for_database(value)
```
Comment (tmertens) [inline activerecord/lib/active_record/type/date.rb]: @kamipo I'm not sure this is sufficient to fix the underlying problem.  I tried this same solution last night (as module included onto `ActiveRecord::Type::Date` to monkey patch it), and I am seeing this method called in some cases, such as when persisting records; however, when calling `where` on the model, it is still coercing to a UTC date time string.  Here is an example (rspec) test:

```ruby
describe 'querying dates with times works around day boundaries' do
    let(:model_class) do
      model_class = Class.new(ActiveRecord::Base)
      model_class.table_name = 'date_serialization_test'
      model_class
    end

    let!(:old_record)       { model_class.create!(a_date_field: Date.new(2016, 6, 8)) }
    let!(:boundary_record)  { model_class.create!(a_date_field: Date.new(2016, 6, 9)) }
    let!(:newer_record)     { model_class.create!(a_date_field: Date.new(2016, 6, 10)) }

    before(:context) do
      ActiveRecord::Migration.new.create_table(:date_serialization_test) do |t|
        t.date :a_date_field
      end
    end

    after(:context) do
      ActiveRecord::Migration.new.drop_table(:date_serialization_test)
    end

    it 'coerces TimeWithZone to Date in current locale' do
      date = Time.new(2016, 6, 9, 23, 0, 0, '-05:00').in_time_zone
      byebug
      query = model_class.where('a_date_field >= ?', date)

      expect(query).to include boundary_record, newer_record
      expect(query).not_to include old_record
    end

    it 'coerces Time to Date in current locale' do
      date = Time.new(2016, 6, 9, 23, 0, 0, '-05:00')
      query = model_class.where('a_date_field >= ?', date)

      expect(query).to include boundary_record, newer_record
      expect(query).not_to include old_record
    end

    it 'coerces DateTime to Date in current locale' do
      date = DateTime.new(2016, 6, 9, 23, 0, 0, '-5')
      query = model_class.where('a_date_field >= ?', date)
      binding.pry
      expect(query).to include boundary_record, newer_record
      expect(query).not_to include old_record
    end

    it 'queries still work correctly using a Date object' do
      date = Date.new(2016, 6, 9)
      query = model_class.where('a_date_field >= ?', date)

      expect(query).to include boundary_record, newer_record
      expect(query).not_to include old_record
    end
  end
```

I suspect that because the `where` clause uses an SQL string, it may not be able to determine the column type?  I am finding that my issue may not be quite the same as the case this and the relate rails 5 PR solves.

Comment (kamipo) [inline activerecord/lib/active_record/type/date.rb]: > I suspect that because the `where` clause uses an SQL string, it may not be able to determine the column type?

Right, AR cannot determine the column type if using `where` with an SQL string for now.

Comment (tmertens) [inline activerecord/lib/active_record/type/date.rb]: Yes, after further investigation I determined we need to just type cast the values ourselves. Thanks @kamipo
