### PR TITLE
Deprecate implicit coercion of `ActiveSupport::Duration`

### LINKED ISSUE #27457: Adding a manipulated Activesupport::Duration to dates gives unexpected result
### Bug

Adding a manipulated Activesupport::Duration to dates gives unexpected result

### Steps to reproduce:

```ruby
[1] pry(main)> pry(main)> d = Date.parse('1 Jan 2017')
=> Sun, 01 Jan 2017
[2] pry(main)> d + 12.hours == d + 2 * 6.hours
=> false
[3] pry(main)> d + 12.hours
=> Sun, 01 Jan 2017 12:00:00 UTC +00:00
[4] pry(main)> d + 2 * 6.hours
=> Wed, 13 Apr 2135
```

### Expected behavior

I think it's safe to expect that `date + 2 * 12.hours` gives the same result as `date + 24.hours`

### Actual behavior

This is not equal. However this works fine with time/time with zone when not around daylight saving, else the same bug is present.

### Suspect

`2 * 12.hours` is converted to a number of seconds as an integer and then added to the date. The date coerce/convert the integer into a number of days and then add it.

### System configuration

Rails version: 5.0.0

Ruby version: 2.3.1

### PR DESCRIPTION
**Pull request by pixeltrix**
Currently `ActiveSupport::Duration` implicitly converts to a seconds value when used in a calculation except for the explicit examples of addition and subtraction where the duration is the receiver, e.g:

    >> 2 * 1.day
    => 172800

This results in lots of confusion especially when using durations with dates because adding/subtracting a value from a date treats integers as a day and not a second, e.g:

    >> Date.today
    => Wed, 01 Mar 2017
    >> Date.today + 2 * 1.day
    => Mon, 10 Apr 2490

To fix this we're implementing `coerce` so that we can provide a deprecation warning with the intent of removing the implicit coercion in Rails 5.2, e.g:

    >> 2 * 1.day
    DEPRECATION WARNING: Implicit coercion of ActiveSupport::Duration
    to a Numeric is deprecated and will raise a TypeError in Rails 5.2.
    => 172800

In Rails 5.2 it will raise `TypeError`, e.g:

    >> 2 * 1.day
    TypeError: ActiveSupport::Duration can't be coerced into Integer

This is the same behavior as with other types in Ruby, e.g:

    >> 2 * "foo"
    TypeError: String can't be coerced into Integer
    >> "foo" * 2
    => "foofoo"

As part of this deprecation add `*` and `/` methods to `AS::Duration` so that calculations that keep the duration as the receiver work
correctly whether the final receiver is a `Date` or `Time`, e.g:

    >> Date.today
    => Wed, 01 Mar 2017
    >> Date.today + 1.day * 2
    => Fri, 03 Mar 2017

Fixes #27457.

### CODE REVIEW

File: actionview/test/template/date_helper_test.rb [hunk 1]
```diff
@@ -832,7 +832,7 @@ def test_select_date
 
   def test_select_date_with_too_big_range_between_start_year_and_end_year
     assert_raise(ArgumentError) { select_date(Time.mktime(2003, 8, 16), start_year: 2000, end_year: 20000, prefix: "date[first]", order: [:month, :day, :year]) }
-    assert_raise(ArgumentError) { select_date(Time.mktime(2003, 8, 16), start_year: Date.today.year - 100.years, end_year: 2000, prefix: "date[first]", order: [:month, :day, :year]) }
+    assert_raise(ArgumentError) { select_date(Time.mktime(2003, 8, 16), start_year: 100, end_year: 2000, prefix: "date[first]", order: [:month, :day, :year]) }
```
Comment (pixeltrix) [inline actionview/test/template/date_helper_test.rb]: This test exhibits the exact problem I'm trying to fix - `Date.today.year - 100.years` gives `-3155757983.0` and not the probable intent of `1917`.

File: activesupport/CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,21 @@
+*   Deprecate implicit coercion of `ActiveSupport::Duration`
```
Comment (rafaelfranca) [inline activesupport/CHANGELOG.md]: This changelog is confusion. What are the cases where an implicit coercion is made?

Comment (pixeltrix) [inline activesupport/CHANGELOG.md]: Better now?

File: actionmailer/test/message_delivery_test.rb [hunk 3]
```diff
@@ -76,7 +76,7 @@ def test_should_enqueue_and_run_correctly_in_activejob
 
   test "should enqueue a delivery with a delay" do
     travel_to Time.new(2004, 11, 24, 01, 04, 44) do
-      assert_performed_with(job: ActionMailer::DeliveryJob, at: Time.current.to_f + 600.seconds, args: ["DelayedMailer", "test_message", "deliver_now", 1, 2, 3]) do
+      assert_performed_with(job: ActionMailer::DeliveryJob, at: Time.current.to_f + 600, args: ["DelayedMailer", "test_message", "deliver_now", 1, 2, 3]) do
```
Comment (pixeltrix) [inline actionmailer/test/message_delivery_test.rb]: @dhh this has now been changed to `Time.current + 600.seconds` which it what it should've been in the first place. Also changed another test to `Time.current + 1.hour` instead of `Time.now.to_f + 3600`.

File: actionview/test/template/date_helper_test.rb (hunk 1 above)
Comment (pixeltrix) [inline actionview/test/template/date_helper_test.rb]: @dhh this is the problem I'm trying to solve with the deprecation - complete misunderstanding of how durations work.

File: activesupport/lib/active_support/cache/mem_cache_store.rb [hunk 4]
```diff
@@ -156,7 +156,7 @@ def write_entry(key, entry, options)
           expires_in = options[:expires_in].to_i
           if expires_in > 0 && !options[:raw]
             # Set the memcache expire a few minutes in the future to support race condition ttls on read
-            expires_in += 5.minutes
+            expires_in += 300
```
Comment (pixeltrix) [inline activesupport/lib/active_support/cache/mem_cache_store.rb]: This change stems from the `to_i` - the memcache client expects an integer for `expires_in`.  It could be rewritten to use `5.minutes` as the receiver but I thought creating an object was wasteful this deep inside the caching code.

Comment (dhh) [inline activesupport/lib/active_support/cache/mem_cache_store.rb]: Unless we pin this as a performance bottleneck, I would always go for the clearer code. IMO, 5.minutes is much clearer than 300. This is where I really don't like to manually apply .to_i. But I could live with an alias like `expires_in += 5.minutes.in_seconds`.

File: actionmailer/test/message_delivery_test.rb (hunk 3 above)
Comment (dhh) [inline actionmailer/test/message_delivery_test.rb]: Cools. I would even go with Time.current + 10.minutes. That's the wonder of these aliases. You get to pick the scale that makes the most sense.
