### PR TITLE
Ensure array passed to preloader has no duplicate records by object_id

### LINKED ISSUE #39035: Duplicate records returned when using ActiveRecord::Associations::Preloader on preloaded records.
### Steps to reproduce
Fetch some records with `.preload`. Select a subset of those records and use `ActiveRecord::Associations::Preloader` to preload another association.

Detailed steps + code to reproduce : https://github.com/jeremy-israel/preload-duplicates-rails-6/blob/master/problem_description_and_steps_to_reproduce.md

### Expected behavior
We're expecting has_many association not to retrieve any duplicate records.

### Actual behavior
Duplicate records are returned.

### System configuration
**Rails version**: `6.0.2.2`

**Ruby version**: `ruby 2.6.6p146`

### LINKED ISSUE #39073: Preloading `has_many through` associations loads duplicated records
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "6.0.2.2"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :entities, force: true do |t|
  end

  create_table :memberships, force: true do |t|
    t.integer :parent_id
    t.integer :child_id
  end

  create_table :documents, force: true do |t|
    t.integer :entity_id
  end
end

class Entity < ActiveRecord::Base
  has_many :memberships, foreign_key: :parent_id
  has_many :children,    through: :memberships
  has_many :documents

  has_one  :parent_membership, class_name: 'Membership', foreign_key: :child_id
  has_one  :parent,            through: :parent_membership
  has_many :shared_documents,  through: :parent, source: :documents
end

class Membership < ActiveRecord::Base
  belongs_to :parent, class_name: 'Entity'
  belongs_to :child,  class_name: 'Entity'
end

class Document < ActiveRecord::Base
  belongs_to :customer
end

class BugTest < Minitest::Test
  def test_association_stuff
    parent = Entity.create!
    parent.documents.create!

    3.times do
      parent.children << Entity.create!
    end

    # Each parent and child entities have only one document
    assert_equal 1, Entity.preload(:shared_documents)[1].shared_documents.size

    # Loading the parent alongside the documents will return 3 documents
    assert_equal 1, Entity.preload(:parent, :shared_documents)[1].shared_documents.size
  end
end
```

I found two similar issues : #37891 and #39035.
Both use different types of associations and the internal ActiveRecord::Associations::Preloader
The example above uses only public API.

### Expected behavior

In the example above, each parent and children have only one document or shared document
Preloading the parent should not change this behavior.

### Actual behavior

Preloading the parent alongside shared documents duplicates the returned documents

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.6.3

### PR DESCRIPTION
**Pull request by bogdan**
Fixes #39073, #39035

### Summary

Duplicate records by `id` are possible for preloader because of `joins`. However, if duplicate objects equal by `object_id` are passed, the best fix would be to just remove duplicates.

### Other Information

Even though the issue #39073  is only happening for `though` association, it is better to implement the fix inside `AssociationPreloader` because in this way it is going to affect direct usage of `Preloader` class which are no officially documented but very popular anyway.

cc @inkstak @kamipo @alipman88

### CODE REVIEW

**Comment by inkstak** [comment]
Thanks !

File: activerecord/lib/active_record/associations/preloader/association.rb [hunk 1]
```diff
@@ -6,7 +6,7 @@ class Preloader
       class Association #:nodoc:
         def initialize(klass, owners, reflection, preload_scope)
           @klass         = klass
-          @owners        = owners
+          @owners        = owners.uniq(&:object_id)
```
Comment (kamipo) [inline activerecord/lib/active_record/associations/preloader/association.rb:9]: Use `__id__` just in case. Ref #38990

```suggestion
          @owners        = owners.uniq(&: __id__)
```

**Comment by bogdan** [comment]
@kamipo will there be a backport?

**Comment by kamipo** [comment]
Already done a4b20e4ffcdc9726f210c4e828927768497d7392.
