### PR TITLE
Orphaned attachment relationship safe navigation (42514)

### LINKED ISSUE #42514: ActiveStorage orphaned attachment relationship raises unsafe reflection
### Steps to reproduce
- Add an ActiveStorage relationship (e.g. `has_many_attached`) to a model
- Create an instance of the model
- Add an attachment to the model
- (later) remove the relationship to the model
- Delete the attachment.

### Expected behavior
Since we do not know the dependent behavior, ignore purging the blob later.

### Actual behavior
Error occurs saying `undefined method '[]' for nil:NilClass`

This is due to the use of safe navigation that wasn't applied to the hash lookup call.

### PR DESCRIPTION
**Pull request by DRSisco**
### Summary
closes #42514

Utilizes safe navigation in looking up dependent relationship.

As described in the issue, this may happen when removing an attachment relationship and some attachment records are orphaned. Deleting them through active record causes an unsafe hash lookup call.

### CODE REVIEW

**Comment by ghiculescu** [comment]
Could you please add a test to demonstrate the issue?

**Comment by DRSisco** [comment]
@ghiculescu Added test

File: activestorage/test/models/attachment_test.rb [hunk 1]
```diff
@@ -134,6 +134,15 @@ class ActiveStorage::AttachmentTest < ActiveSupport::TestCase
     assert_equal blob, ActiveStorage::Blob.find_signed(signed_id)
   end
 
+  test "can destroy attachment without existing relation" do
+    blob = create_blob
+    @user.highlights.attach(blob)
+    attachment = @user.highlights.find_by(blob_id: blob.id)
+    attachment.update_attribute(:name, 'old_highlights')
+    assert_equal attachment.send(:dependent), nil
```
Comment (nvasilevski) [inline activestorage/test/models/attachment_test.rb:142]: Nitpick: 
```suggestion
    assert_nil(attachment.send(:dependent))
```

File: activestorage/test/models/attachment_test.rb [hunk 2]
```diff
@@ -134,6 +134,15 @@ class ActiveStorage::AttachmentTest < ActiveSupport::TestCase
...
+    attachment.destroy
```
Comment (nvasilevski) [inline activestorage/test/models/attachment_test.rb:143]: Presumably it would be better to setup an expectation like:
`assert_nothing_raised { attachment.destroy }`

File: activestorage/app/models/active_storage/attachment.rb [hunk 3]
```diff
@@ -74,7 +74,7 @@ def purge_dependent_blob_later
     end
 
     def dependent
-      record.attachment_reflections[name]&.options[:dependent]
+      record.attachment_reflections[name]&.options&.[](:dependent)
```
Comment (nvasilevski) [inline activestorage/app/models/active_storage/attachment.rb:77]: Personally I find `.fetch` or `.dig` more readable for such cases
```suggestion
      record.attachment_reflections[name]&.options&.fetch(:dependent, nil)
```

File: activestorage/test/models/attachment_test.rb (hunk 2 above)
Comment (DRSisco) [reply activestorage/test/models/attachment_test.rb]: That's definitely more explicit to the intentions of that line. Thanks.

File: activestorage/app/models/active_storage/attachment.rb (hunk 3 above)
Comment (DRSisco) [reply activestorage/app/models/active_storage/attachment.rb]: Thats fair, using the safe navigator with operations looks really tacky.

File: activestorage/test/models/attachment_test.rb [hunk 4]
```diff
@@ -134,6 +134,15 @@ class ActiveStorage::AttachmentTest < ActiveSupport::TestCase
     assert_equal blob, ActiveStorage::Blob.find_signed(signed_id)
   end
 
+  test "can destroy attachment without existing relation" do
+    blob = create_blob
+    @user.highlights.attach(blob)
+    attachment = @user.highlights.find_by(blob_id: blob.id)
+    attachment.update_attribute(:name, "old_highlights")
+    assert_nil attachment.send(:dependent)
```
Comment (zzak) [inline activestorage/test/models/attachment_test.rb:142]:
```suggestion
```

File: activestorage/test/models/attachment_test.rb [hunk 5]
```diff
@@ -134,6 +134,15 @@ class ActiveStorage::AttachmentTest < ActiveSupport::TestCase
     assert_equal blob, ActiveStorage::Blob.find_signed(signed_id)
   end
 
+  test "can destroy attachment without existing relation" do
+    blob = create_blob
+    @user.highlights.attach(blob)
+    attachment = @user.highlights.find_by(blob_id: blob.id)
+    attachment.update_attribute(:name, "old_highlights")
```
Comment (zzak) [inline activestorage/test/models/attachment_test.rb:141]: Actually, if I comment out this `update_attribute` the test passes pre-patch. I wonder why? 🤔

File: activestorage/test/models/attachment_test.rb (hunk 4 above)
Comment (zzak) [reply activestorage/test/models/attachment_test.rb:142]: I don't think this test adds any value, we generally don't care about the result of calling private APIs directly

**Comment by zzak** [comment]
This will also need a [changelog](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#updating-the-changelog).

File: activestorage/test/models/attachment_test.rb (hunk 4 above)
Comment (DRSisco) [reply activestorage/test/models/attachment_test.rb:142]: I was showing the result was not purge_later but rather nil. Since this is the behavior. If later we want want to change the default behavior to purge_later for attachments without a record relationship, then this test would fail and need to be updated. 

I can remove it, but I was just making sure it would fail later if we changed that assumption, but to your point that could be tested a different way and not via the private API here.

File: activestorage/test/models/attachment_test.rb (hunk 5 above)
Comment (DRSisco) [reply activestorage/test/models/attachment_test.rb:141]: It should pass, since highlights is still defined on the User class. The idea here is that if the attachment is linked via an association that is no longer defined, then the attachment record shouldn't raise an error when deleted. 

Admittedly the developer should probably clean these up in a data-migration or a rake task if that's the intention, but this also shouldn't error either.

---

Do you think there is a better way to test this scenario? I thought it would be easiest to just simply change the association name stored on the attachment record after it is created.

Comment (zzak) [reply activestorage/test/models/attachment_test.rb:141]: @DRSisco Sorry for the possibly half-baked question but in this scenario the `:name` attribute is referencing the association?

Comment (DRSisco) [reply activestorage/test/models/attachment_test.rb:141]: @zzak Yeah, `:name` is used for the reverse lookup, so by changing name, we can mirror what it would be if the attachment still being attached to a record, but under an association that doesn't exist at this point in the code base.
