### PR TITLE
move ActiveRecord::Persistence#becomes logic into initialize block

### LINKED ISSUE #26399: ActiveRecord::Persistance#becomes and ActiveRecord::Callbacks#after_initialize interference
### Steps to reproduce

```
class A < ActiveRecord::Base

after_inititialize :check_new_record

def check_new_record
   if new_record?
      puts "NEW RECORD"
   else
      puts "RECORD STORED IN DB" 
   end
end

class B < A
end

Console:
> var1 = B.create
<Class B id=1 ....>
> var1 = B.find(1)
RECORD STORED IN DB
 <Class B id=1 ....>
> var 1 = B.find(1).becomes(A)
RECORD STORED IN DB
NEW RECORD  <<- this should be RECORD STORED IN DB
 <Class A id=1 ....>
> var1 = B.find(1).becomes(A).new_record?
RECORD STORED IN DB
NEW RECORD
false
```
### Expected behavior

ActiveRecord::Persistance#becomes should assign all it's attributes and properties  (including new_record) in a block so ActiveRecord::Callbacks#after_initialize callback is not called before instance is copied
### Actual behavior

When using ActiveRecord::Persistance#becomes with ActiveRecord::Callbacks#after_initialize callback, this callback is called as soon as 

`became = klass.new`

is called and before  

`became.instance_variable_set("@new_record", new_record?)`

so this causes inconsistency with ActiveRecord::Persistance#new_record? inside ActiveRecord::Callbacks#after_initialize callback
## Suggested solution

Use block when creating new instance in ActiveRecord::Persistance#becomes.

```
def becomes(klass)
      became = klass.new do |became|
         became.instance_variable_set("@attributes", @attributes)
         became.instance_variable_set("@mutation_tracker", @mutation_tracker) if defined?(@mutation_tracker)
         became.instance_variable_set("@changed_attributes", attributes_changed_by_setter)
         became.instance_variable_set("@new_record", new_record?)
         became.instance_variable_set("@destroyed", destroyed?)
         became.errors.copy!(errors)
      end
      became
    end
```
### System configuration

**Rails version**:
4.2.6

**Ruby version**:
2.2.0

### PR DESCRIPTION
**Pull request by SampsonCrowley**
### Summary

Wraps `ActiveRecord::Persistence#becomes` logic in the subclass initialization block

Fixes #26399 

### Other Information

When running `my_record.becomes(OtherClass)`, `after_initialize` is ran *before* attributes and variables are set. This causes problems if you expect a subclass to format values a certain way on init. I didn't see any reason that the instance variables should be set after initialize instead of in the initialize block, so I moved them to where callbacks work as expected.

### CODE REVIEW

**Comment by SampsonCrowley** [comment]
@maclover7 @eugeneius Is there anything I need to change here?

File: activerecord/test/cases/inheritance_test.rb [hunk 1]
```diff
@@ -227,6 +229,14 @@ def test_alt_becomes_works_with_sti
     assert_kind_of Cabbage, cabbage
   end
 
+  def test_becomes_sets_variables_before_initialization_callbacks
+    category = Category.find(1)
+    assert_kind_of Category, category
+    special_category = category.becomes(SpecialCategory)
+    assert_equal "GENE", special_category.special_name, "General special_name should be GENE"
+    assert_equal "GENE", category.special_name, "General special_name should be GENE"
```
Comment (eugeneius) [inline activerecord/test/cases/inheritance_test.rb:237]: Could this test use the Vegetable model instead? It's already used in this file, and isn't used elsewhere, while Category is used throughout the test suite.

File: activerecord/test/models/category.rb [hunk 2]
```diff
@@ -44,4 +44,9 @@ def self.locked
 end
 
 class SpecialCategory < Category
+  after_initialize :format_name
+
+  def format_name
+    self.special_name = name&.upcase&.gsub(/[^A-Z]/, "").presence&.slice(0..3) rescue nil
```
Comment (eugeneius) [inline activerecord/test/models/category.rb:50]: We only need to verify that the callback runs with the attributes set. Could this just be `self.special_name = name.upcase`?

File: activerecord/test/cases/attribute_methods_test.rb [hunk 3]
```diff
@@ -16,7 +16,7 @@
 class AttributeMethodsTest < ActiveRecord::TestCase
   include InTimeZone
 
-  fixtures :topics, :developers, :companies, :computers
+  fixtures :companies, :computers, :developers, :topics
```
Comment (eugeneius) [inline activerecord/test/cases/attribute_methods_test.rb:19]: This change seems unnecessary.

File: activerecord/test/cases/inheritance_test.rb (hunk 1 above)
Comment (SampsonCrowley) [reply activerecord/test/cases/inheritance_test.rb:237]: @eugenius probably. I picked SpecialCategory because there aren't any tests that involve checking the attributes in SpecialCategory, whereas all of the other inheritance models did; and adding a modified attribute in Vegetable seemed more likely to unintentionally affect other unrelated tests

File: activerecord/test/models/category.rb (hunk 2 above)
Comment (SampsonCrowley) [reply activerecord/test/models/category.rb:50]: Yeah, a more specific transformation just seemed like a more accurate test than a simple capitalization test that the transformation was definitely being made, and would still be accurately testable apply if `#name` already was formatted in all caps

File: activerecord/test/cases/attribute_methods_test.rb (hunk 3 above)
Comment (SampsonCrowley) [reply activerecord/test/cases/attribute_methods_test.rb:19]: I know cosmetic pull requests aren't accepted; but while this file was *already* being updated, an ordered list felt more easily searched for the existence of a wanted fixture than a completely random one, and therefore less likely for duplicates/errors in future additions/removals

I can remove it if it's really not acceptable to ever fix a cosmetic issue

File: activerecord/test/models/category.rb (hunk 2 above)
Comment (SampsonCrowley) [reply activerecord/test/models/category.rb]: updated for a simpler check with a directly created record to aviod the need for extra insurance

File: activerecord/test/cases/attribute_methods_test.rb (hunk 3 above)
Comment (SampsonCrowley) [reply activerecord/test/cases/attribute_methods_test.rb]: removed

File: activerecord/test/cases/inheritance_test.rb (hunk 1 above)
Comment (SampsonCrowley) [reply activerecord/test/cases/inheritance_test.rb]: updated to use Vegetable and a new `YellingVegetable` submodel

**Comment by SampsonCrowley** [comment]
@eugeneius i believe that should resolve everything you pointed out

**Comment by eugeneius** [comment]
Thank you!

File: activerecord/test/cases/attribute_methods_test.rb (hunk 3 above)
Comment (eugeneius) [reply activerecord/test/cases/attribute_methods_test.rb]: Cleaning up adjacent code as part of a larger change can be acceptable, but in this case I wasn't into it because we don't alphabetise fixture names elsewhere, and the other change to this file would be going away by switching to use the Vegetable class.

Comment (SampsonCrowley) [reply activerecord/test/cases/attribute_methods_test.rb]: Makes sense, thanks for the clarification

**Comment by SampsonCrowley** [comment]
Glad to help where I can!
