### PR TITLE
Fix regression where AJ#perform_now doesn't return the job's value:

### LINKED ISSUE #38040: ActiveJob perform_now no longer returns result of perform
Recently, ActiveJob's `.perform_now` method was updated in https://github.com/rails/rails/pull/37950 to return a boolean value indicating success or failure. Prior to the change, `.perform_now` returned the result of `.run_callbacks`, which in turn returned the result of ` perform(*arguments)`.

See: https://github.com/rails/rails/commit/9eb4b4ed01f893c2fc7ff3ee4f99301dec7ea3c2#diff-141fdcf8e028bfeca079b4ebb5cb00a3R41

It looks like the change was made to support improvements to deprecation warnings. Unfortunately it is causing problems at GitHub as we have quite a few tests (and a small number of methods in production) that rely on `.perform_now` returning the result of `.perform`. It also seems pretty likely that dependence on the previous return value isn't unique to GitHub.

The following reproduction script can be used to run an example using Rails 6.0 and 6.1

`$ ruby activejob_returnval.rb && RAILS_MASTER=1 ruby activejob_returnval.rb`

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  if ENV['RAILS_MASTER'] == "1"
    gem "rails", github: "rails/rails"
  else
    gem "rails", "6.0.0"
  end
end

require "active_job"
require "minitest/autorun"

class User
  attr_accessor :id
  def initialize(id)
    @id = id
  end

  def self.all
    (1..10).collect {|i| User.new(i)}
  end

  def has_warning?
    self.id.even?
  end

  def send_warning
    # Send a notification
  end
end

class BuggyJob < ActiveJob::Base
  def perform
    user_ids_with_warnings = []
    User.all.each do |user|
      if user.has_warning?
        user.send_warning
        user_ids_with_warnings << user.id
      end
    end
    user_ids_with_warnings
  end
end

class BuggyJobTest < ActiveJob::TestCase
  def test_return_value_returns_perform_result
    result = BuggyJob.perform_now
    assert_equal [2,4,6,8,10], result
  end
end
```

### PR DESCRIPTION
**Pull request by Edouard-chin**
This PR contains 2 commits that aren't related to each other but they were both making the wrong assumption (I initially thought that a job was either returning `true` / `false`.

cc/ @rafaelfranca

### CODE REVIEW

File: activejob/lib/active_job/instrumentation.rb [hunk 1]
```diff
@@ -18,12 +18,17 @@ module Instrumentation #:nodoc:
...
+          event_payload[:aborted] = true if defined?(@_halted_callback_hook_called) && @_halted_callback_hook_called
         end
 
         ActiveSupport::Notifications.instrument \
           "#{operation}.active_job", payload.merge(adapter: queue_adapter, job: self), &enhanced_block
       end
+
+      def halted_callback_hook(_)
+        super
+        @_halted_callback_hook_called = true
```
Comment (rafaelfranca) [inline activejob/lib/active_job/instrumentation.rb]: I think we need to find a place to reset this value otherwise when we try to run or enqueue the job in the same instance `_halted_callback_hook_called` will be `true`.

Comment (Edouard-chin) [reply activejob/lib/active_job/instrumentation.rb]: 👍 done
