### PR TITLE
Fix `ActiveRecord::FinderMethods.find` when passing multiple ids and primary key is not selected

### LINKED ISSUE #45694: Find with array returns nothing if primary key is not selected
### Steps to reproduce

When `select` is used and the primary key is not selected, the array form of `find` just returns an empty array.

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :first_name
    t.string :last_name
    t.timestamps
  end
end

class User < ActiveRecord::Base
  def name
    "#{first_name} #{last_name}"
  end
end

class BugTest < Minitest::Test
  def test_find_returns_nothing
    user1 = User.create!(first_name: "John", last_name: "Doe")
    user2 = User.create!(first_name: "Jane", last_name: "Doe")

    assert_equal User.select(:first_name, :last_name).find([user1.id, user2.id]).map(&:name), ["John Doe", "Jane Doe"]
  end
end
```

### Expected behavior
I think this should either raise (asking users to include the primary key), or automatically add the primary key to the `select`ed columns. It could also just return the records, but in that case order is not guaranteed anymore, which might be surprising to users.

### Actual behavior
An empty array is returned. In rails 6.1 this raised a KeyError which is also pretty confusing (and was the reason I originally investigated this).

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 2.7.4

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #45694.

I think it is easier and better to just raise than to introduce an implicit behavior by adding a primary key to the selected values.

### CODE REVIEW

**Comment by xjunior** [comment]
The behavior in the bug report is what I would expect, not an exception. Selecting attributes without the primary key is a valid scenario.

Also, checking if `id` is "truthy" doesn't work when the primary key is something else.

**Comment by fatkodima** [comment]
> Selecting attributes without the primary key is a valid scenario.

Sure, but you should not call `find` on it. You can get the relation from somewhere else and calling `find` on it will get empty results and you will be very surprised (not to mention it should take some time when this surprise will show itself), like the OP. 

> Also, checking if id is "truthy" doesn't work when the primary key is something else.

No, because the primary can not be `nil` or `false`.

**Comment by xjunior** [comment]
> No, because the primary can not be `nil` or `false`.

I mean if the model in question doesn't use `id` as the primary key.

**Comment by fatkodima** [comment]
If you mean `id` as a column name, then calling `#id` method actually returns the record's primary key - https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/PrimaryKey.html#method-i-id

**Comment by xjunior** [comment]
> If you mean `id` as a column name, then calling `#id` method actually returns the record's primary key - https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/PrimaryKey.html#method-i-id

that I didn't know, good info!

**Comment by simi** [comment]
Why is `ordering` done in Ruby world? Can't we just rewrite the logic to not use `in_order_of` on Array, but on Relation (https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-in_order_of) instead? That way there is no need for `primary_key` selection and we can guarantee the order.

**Comment by fatkodima** [comment]
We can't use it, at least currently, because, probably, not every dbms supports such ordering (but I was unable to find any by checking right now all the most popular). But at least not all activerecord adapters support it - https://github.com/rails/rails/blob/408d061a80a49878ad26b305616ed9ba88ee1411/activerecord/lib/active_record/relation/query_methods.rb#L523

We can move `field_ordered_value` to the `AbstractAdapter`, because all the SQL dbms have basically the same syntax. We need to merge https://github.com/rails/rails/pull/45670 first, I think.

**Comment by simi** [comment]
> We can move field_ordered_value to the AbstractAdapter, because all the SQL dbms have basically the same syntax. We need to merge https://github.com/rails/rails/pull/45670 first, I think.

Ok, let's focus on that one for now. :eyes:

**Comment by fatkodima** [comment]
Another reason to order in memory: `find` queries are very popular and the generated SQL queries are nice, clean and simple, and should perform faster too. So if to order in database, this will change. If we find 10 records, that query will became monstrous already.

**Comment by simi** [comment]
> Another reason to order in memory: `find` queries are very popular and the generated SQL queries are nice, clean and simple, and should perform faster too. So if to order in database, this will change. If we find 10 records, that query will became monstrous already.

I'm not sure that's the main purpose of AR to create nice clean and simple queries. Check the common query generated by `eager_load`. AFAIK AR is in here so you don't need to care about SQL queries at all if possible.

**Comment by fschwahn** [comment]
I did a simple benchmark, and sorting in DB (using `in_order_of`) is noticeably slower:

```ruby
require "benchmark/ips"
id_list = 100.times.map { User.create!.id }.shuffle

Benchmark.ips do |x|
  x.report("sort in ruby") { User.find(id_list) }
  x.report("sort in DB") { User.in_order_of(:id, id_list).to_a }

  x.compare!
end
```

```
Warming up --------------------------------------
        sort in ruby    80.000  i/100ms
          sort in DB    50.000  i/100ms
Calculating -------------------------------------
        sort in ruby    795.172  (± 5.2%) i/s -      4.000k in   5.044808s
          sort in DB    512.828  (± 1.8%) i/s -      2.600k in   5.071509s

Comparison:
        sort in ruby:      795.2 i/s
          sort in DB:      512.8 i/s - 1.55x  (± 0.00) slower
```

The effect increases when `id_list` becomes larger.

**Comment by casperisfine** [comment]
Ok, I looked at the issue a bit, and I don't think either of the proposed resolutions so far are really satisfactory.

Raising an explicit error while better than returning an empty array seems like giving up to me.

Ordering in DB is mentioned before may have very detrimental performance effects.

I'm wondering wether implicitly selecting the primary key when passing a list to `find()` wouldn't be better.

File: activerecord/lib/active_record/relation/finder_methods.rb [hunk 1]
```diff
@@ -507,6 +508,7 @@ def find_some_ordered(ids)
         result = except(:limit, :offset).where(primary_key => ids).records
 
         if result.size == ids.size
+          raise ArgumentError, "Primary key is not included in the custom select clause" unless result.first.id
           result.in_order_of(:id, ids.map { |id| @klass.type_for_attribute(primary_key).cast(id) })
```
Comment (casperisfine) [inline activerecord/lib/active_record/relation/finder_methods.rb:512]: That said, it's an orthogonal concern, but I think we should probably raise an error if `in_order_of` returns less elements than `result`.

**Comment by fatkodima** [comment]
@byroot Thank you for the review!

> I'm wondering wether implicitly selecting the primary key when passing a list to find() wouldn't be better.

Updated with this approach.

**Comment by byroot** [comment]
thanks!

File: activerecord/lib/active_record/relation/finder_methods.rb [hunk 2]
```diff
@@ -448,6 +448,7 @@ def find_with_ids(*ids)
         ids = ids.flatten.compact.uniq
 
         model_name = @klass.name
+        _select!(table[primary_key]) unless select_values.empty?
```
Comment (byroot) [inline activerecord/lib/active_record/relation/finder_methods.rb:451]: Hum, actually, this mutates the current instance, I don't think we should do that. Can you do a quick followup that doesn't do this?

I think you can just do it in `find_some_ordered`, at the same point where `where(primary_key => ids)`.

Sorry, I should have been more careful.
