### PR TITLE
Do not validate associated records that haven't changed

### LINKED ISSUE #17621: AR is erroneously validating existing records on a has_many :through
Its Friday, so entirely possible I just need a drink and some sleep. But after upgrading a legacy app to the latest and greatest, I've started to see unexpected validations when creating new records with existing associations on a `has_many :through`.

See attached gist: https://gist.github.com/uberllama/1d0323438700d4f23bbb

I have a Conversation class, which has many `:users` through `:conversation_users`. When a user creates a new Conversation, they specify which Users they want to include in the Conversation. This boils down to:

```ruby
class Conversation < ActiveRecord::Base
  has_many :conversation_users
  has_many :users, through: :conversation_users
end

class ConversationUser < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user
end

class User < ActiveRecord::Base
  has_many :conversation_users
  has_many :conversations, through: :conversation_users
  validates :name, presence: true
end

conversation = Conversation.new(user_ids: [1,2,3])
conversation.save
```

When calling `save` on the new Conversation instance, AR is validating the associated Users even though they are existing, non-dirty objects. This results in huge amounts of unnecessary weight on every Conversation save. It should not be the responsibility of a model to validate its associated objects unless those objects are being created or modified along with the parent model.

What am I missing?

### PR DESCRIPTION
**Pull request by byroot**
Fix: https://github.com/rails/rails/issues/17621
Redo of: https://github.com/rails/rails/pull/18612

You should be able to create a reference to an invalid record as long as you don't modify it.

This was initially fixed in https://github.com/rails/rails/pull/18612 but was reverted in https://github.com/rails/rails/commit/2c02bc0a47777ad8cf98e1465c08b1a68151803e because it was causing other bugs.

Some tests were added as part of the revert to avoid future regressions.

### CODE REVIEW

File: activerecord/lib/active_record/autosave_association.rb [hunk 1]
```diff
@@ -370,8 +370,14 @@ def validate_collection_association(reflection)
...
         return true if record.destroyed? || (association.options[:autosave] && record.marked_for_destruction?)
-
-        context = validation_context if custom_validation_context?
+        if custom_validation_context?
+          context = validation_context
+        else
+          # If the associated record is unchanged we shouldn't auto validate it.
+          # Even if a record is invalid you should still be able to create new references
+          # to it.
+          return true if !record.new_record? && !record.changed?
```
Comment (axlekb) [inline activerecord/lib/active_record/autosave_association.rb:379]: Why doesn't this use `#changed_for_autosave?`

https://api.rubyonrails.org/classes/ActiveRecord/AutosaveAssociation.html#method-i-changed_for_autosave-3F

Comment (axlekb) [reply activerecord/lib/active_record/autosave_association.rb:379]: To provide some more color, I used to be able to customize the checking of validations by overriding `#changed_for_autosave?`, but this appears to short-circuit that.  Overriding `#changed_for_autosave?` seems much more limited and safer than overriding `#new_record?` or `#changed?`

Comment (byroot) [reply activerecord/lib/active_record/autosave_association.rb:379]: If `changed_for_autosave?` passes the test suite, then please send a PR. Might just be an oversight, and might also fix https://github.com/rails/rails/issues/55771

Comment (ianterrell) [reply activerecord/lib/active_record/autosave_association.rb:379]: I can confirm that it does fix #55771 and I believe it passes the test suite (so far as I can tell locally with `./bin/test -a sqlite3`). I've created a PR with a failing test and the fix here: https://github.com/rails/rails/pull/55778

EDIT: I don't _think_ the PR test failures are from this. 😅

Comment (axlekb) [reply activerecord/lib/active_record/autosave_association.rb:379]: Thank you, @ianterrell !!!
