### PR TITLE
Fix an issue with JSON encoding of "Infinity" and "NaN" values

### LINKED ISSUE #26877: Exception when attribute is `Infinity` in `Hash`
Issue was originally opened here: https://github.com/rails-api/active_model_serializers/issues/1946
I was asked to open an issue here to see if this is a rails bug, since the exception is not limited to `active_model_serializers` and it will be raised anytime when object's `#to_json` method returns Hash with `Infinity`. 
### Steps to reproduce

use following gem for the test case `'active_model_serializers', '~> 0.10.0'`

```
class FailCase
  include ActiveModel::Serialization

  def fail; 1/0.0; end
end

class FailCaseSerializer < ActiveModel::Serializer
  attribute :fail
end

FailCaseSerializer.new(FailCase.new).to_json
```
### Expected behavior

Expected: calling `#to_json` on a serializer instance with an attribute that has value of `Infinity` should return that attribute as `null`
### Actual behavior

getting `JSON::GeneratorError: 836: Infinity not allowed in JSON` exception

When calling `to_json` on a hash that has a key with a value of `Infinity`, rails returns `null` for that key, however if the object passed to the renderer returns hash that has a key with a value of `Infinity` when calling `#to_json`, rails will not filter out invalid keys/values additionally on that hash (like it does during `Hash#to_json` and will raise error during json generation. 

```
serializer = FailCaseSerializer.new(FailCase.new)
serializer.to_hash #=> {:fail=>Infinity}
serializer.to_hash.to_json #=> {"fail":null}
serializer.to_json #=> Exception: JSON::GeneratorError: 836: Infinity not allowed in JSON
```

looking at the trace it looks like `ActiveSupport::JSON::Encoding` is receiving `Hash` not `Hash.as_json`
### System configuration

**Rails version**: `5.0.0.1`
**Ruby version**: `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]`
### Backtrace

```
Exception: JSON::GeneratorError: 836: Infinity not allowed in JSON
--
 0: /Users/afsoon/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/json/common.rb:224:in `generate'
 1: /Users/afsoon/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/json/common.rb:224:in `generate'
 2: /Users/afsoon/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:99:in `stringify'
 3: /Users/afsoon/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:33:in `encode'
 4: /Users/afsoon/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:20:in `encode'
 5: /Users/afsoon/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/core_ext/object/json.rb:37:in `to_json'
```

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
### Summary
- When `as_json` returns `Infinity` or `NaN` as the value of any of the key,
  we don't used to call `as_json` on it as it was treated as primitive.
- This used to pass `Infinity` or `NaN` to `JSON.generate` and Ruby used
  to throw an error for `Infinity/NaN not allowed in JSON.`
- This patch changes the code to call `as_json` on these primitives so
  that they are converted to proper values before being passed to
  `JSON.generate`.
- Fixes #26877.

r? @chancancode

### CODE REVIEW

**Comment by sergey-alekseev** [comment]
["The build has been terminated"](https://travis-ci.org/rails/rails/builds/171777596) :(

**Comment by prathamesh-sonpatki** [comment]
@pixeltrix I had a discussion about this issue with @matthewd at Rubyconf and he suggested that we merge and backport this change and after that deprecate the behvior from https://github.com/rails/rails/pull/2532 and https://github.com/rails/rails/pull/6096 on master, and eventually remove it in next to next release.

**Comment by pixeltrix** [comment]
@prathamesh-sonpatki sounds like a plan 😄

**Comment by prathamesh-sonpatki** [comment]
@pixeltrix So can we merge this :smile:

**Comment by pixeltrix** [comment]
Done 👍

File: activesupport/test/json/encoding_test.rb [hunk 1]
```diff
@@ -432,6 +432,28 @@ def test_exception_to_json
     assert_equal '"foo"', ActiveSupport::JSON.encode(exception)
   end
 
+  class InfiniteNumber
+    def as_json(options = nil)
+      { "number" => 1.0 / 0 }
```
Comment (simi) [inline activesupport/test/json/encoding_test.rb]: What about to use `Float::INFINITY` directly here?

Comment (pixeltrix) [inline activesupport/test/json/encoding_test.rb]: Changed in d2890f7 - thanks @simi

**Review by pixeltrix — COMMENTED** [review]
Merged 👍

File: activesupport/test/json/encoding_test.rb [hunk 2]
```diff
@@ -432,6 +432,28 @@ def test_exception_to_json
...
+  end
+
+  def test_to_json_works_when_as_json_returns_infinite_number
+    expected = { number: nil }.to_json
+    assert_equal expected, InfiniteNumber.new.to_json
+  end
+
+  class NaNNumber
+    def as_json(options = nil)
+      { "number" => 0.0 / 0 }
```
Comment (simi) [inline activesupport/test/json/encoding_test.rb]: `0.0 / 0` => `Float:NAN`

*Too late :(, is it worth to open PR for this?*

Comment (pixeltrix) [inline activesupport/test/json/encoding_test.rb]: No, I'll fix it

Comment (pixeltrix) [inline activesupport/test/json/encoding_test.rb]: Two commits later I've fixed it - more haste, less speed :smile:

**Comment by prathamesh-sonpatki** [comment]
Thanks @simi and @pixeltrix!

**Comment by prathamesh-sonpatki** [comment]
@pixeltrix Please backport this and other related commits as well.

**Comment by rafaelfranca** [comment]
Backported in 2e421ad3df

**Comment by DaniG2k** [comment]
I am still experiencing this issue in Rails 4.2.11.1. See [this StackOverflow thread](https://stackoverflow.com/questions/56477315/rails-4-jsongeneratorerror-nan-not-allowed-in-json).

**Comment by eileencodes** [comment]
@DaniG2k - Rails 4.2 hasn't been supported for bug fixes in a long time. It's only supported for security releases. If you look at the commit https://github.com/rails/rails/commit/c85d305a67f83f3a92488a641654b85b90b8747a you can see it's included in tags 5.1.0.beta1 and up. This change required a deprecation before it was merged and was a change in behavior so we couldn't backport it at the time to 4.2 and definitely can't now.

Just in case it's not on your radar, Rails 4.2 will soon no longer be supported for even security fixes so we recommend you upgraded ASAP. Also gotta say Rails 6.0 is prettty nice. 😄

**Comment by DaniG2k** [comment]
OK I'll find a workaround in the meanwhile :) thanks
