### PR TITLE
Set `attributes_for_inspect` to `[:id]` in the production environment only

### LINKED ISSUE #52728: Only `id` is shown  when inspecting records in Rails console in production
### Steps to reproduce
1. Create a new Rails app (with either Rails 7.2.1 or 8.0.0.alpha): `rails new test-app`
2. Modify `config/database.yml` so that the production database points to the development database (it's fine to keep sqlite for this demonstration):
   ```yml
   default: &default
   adapter: sqlite3
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   timeout: 5000

   development:
     <<: *default
     database: storage/development.sqlite3
   production:
     <<: *default
     database: storage/development.sqlite3
  
3. Create a dummy model: `bin/rails g model User name surname`

Now, if you enter the dev console with `bin/rails c` this is what you'll see:
```rb
test-app(dev)> User.create(name: "John", surname: "Doe")
test-app(dev)> User.first
=> #<User:0x0000000120d516c0 id: 1, name: "John", surname: "Doe", created_at: "2024-08-28 07:12:10.878368000 +0000", updated_at: "2024-08-28 07:12:10.878368000 +0000">
```

And if you enter the console in production with `bin/rails c -e production`, you'll see this:
```rb
test-ap(prod)> User.first
=> #<User:0x000000011f7f8760 id: 1>
```

As you see, while inspecting the user I only get back the `id`.

Note that if you follow those steps with Rails 7.1, the output of the development and production console match (they both show all the attributes).

### Expected behavior

I expect to see all the object attributes even on production. This behavior has changed from Rails 7.2.

### Actual behavior

From Rails 7.2 onwards, when inspecting a model instance in the production console you only get back the id and not the whole set of attributes.

### System configuration
**Rails version**:
7.2.1

**Ruby version**:
3.3.4

### PR DESCRIPTION
**Pull request by andrewn617**
### Motivation / Background

Fixes https://github.com/rails/rails/issues/52728

This Pull Request has been created because we received feedback on a few things about the `attributes_for_inspect` feature introduced in https://github.com/rails/rails/pull/49765, specifically around the default settings for this feature, which is `[:id]` in production and `:all` in test and dev. The issues are:

1. This feature should be opt in, and be `:all` in production for upgrading apps.
2. We should always use `:all` in the production console to not hinder debugging/
3. We should not use `consider_all_requests_local` to determine what to set it to

### Detail

To address 1 and 3, I changed how the defaults are set. Now the default value is `:all`, and I set it to `[:id]` in `production.rb`. This means it is also opt in as upgrading apps will need to add that line to their `production.rb`.

For 2, I used the `console` method in the active record railtie to set this it to `:all` in production in the console

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by fatkodima** [comment]
https://github.com/rails/rails/pull/52753 ?

**Comment by andrewn617** [comment]
@fatkodima I wanted to take a slightly different approach and also add a fix to the console issue. I left a comment [there](https://github.com/rails/rails/pull/52753#issuecomment-2329815984) but you beat me to it since I got distracted by a test failure 😅

File: activerecord/lib/active_record/core.rb [hunk 1]
```diff
@@ -824,7 +824,13 @@ def inspect_with_attributes(attributes_to_list)
...
 
       def attributes_for_inspect
-        self.class.attributes_for_inspect == :all ? attribute_names : self.class.attributes_for_inspect
+        self.class.attributes_for_inspect == :all ? all_attributes_for_inspect : self.class.attributes_for_inspect
+      end
+
+      def all_attributes_for_inspect
+        return [] unless @attributes
+
+        attribute_names
```
Comment (andrewn617) [inline activerecord/lib/active_record/core.rb:833]: If we do `Model.allocate.inspect` with `attributes_for_inspect = :all` we will get a no method error since `@attributes` is `nil`. So I introduced this method. We can't do `self.class.attribute_names` since it will not include virtual columns.

Alternatively we could update active model to be resilient to `@attributes` being `nil`, but there are already `nil` checks for `@attributes` in this code so I thought it was okay to continue that practice. But I am open to feedback.

Comment (p8) [reply activerecord/lib/active_record/core.rb:833]: We already do this check on line 812. 
Maybe `inspect_with_attributes` should not accept `attributes_to_list` but just call `attributes_for_inspect` itself?

Comment (andrewn617) [reply activerecord/lib/active_record/core.rb:833]: Yeah that's what I would do, however, we also need to pass this from `full_inspect` which also calls `inspect_with_attributes`.

Comment (p8) [reply activerecord/lib/active_record/core.rb:833]: Maybe:
```ruby
      def inspect_with_attributes(attributes_for_inspect=self.class.attributes_for_inspect)
        inspection = if @attributes
          attributes_to_list = if attributes_for_inspect == :all
            all_attributes_for_inspect
          else
            self.class.attributes_for_inspect
          end
          attributes_to_list.filter_map do |name|
            name = name.to_s
            if _has_attribute?(name)
              "#{name}: #{attribute_for_inspect(name)}"
            end
          end.join(", ")
        else
          "not initialized"
        end
        "#<#{self.class} #{inspection}>"
      end

    def full_inspect
        inspect_with_attributes(:all)
    end
```

Comment (andrewn617) [reply activerecord/lib/active_record/core.rb:833]: The problem is that we can't call `self.class.attributes_for_inspect` because it won't include virtual columns (there is a test testing for this).

I did think about going in something like this direction but I am not sure if it's any less complicated 🤔

Comment (andrewn617) [reply activerecord/lib/active_record/core.rb:833]: I guess we could call `self.class.attributes_for_inspect` as the default param and then `self.attributes_for_inspect` in the method body but it's somewhat awkward.

File: activerecord/lib/active_record/railtie.rb [hunk 2]
```diff
@@ -69,6 +69,7 @@ class Railtie < Rails::Railtie # :nodoc:
         Rails.logger.broadcast_to(console)
       end
       ActiveRecord.verbose_query_logs = false
+      ActiveRecord::Base.attributes_for_inspect = :all if Rails.env.production?
```
Comment (zzak) [inline activerecord/lib/active_record/railtie.rb:72]: If the default is already `:all` above, why do we need to set this here?

**Comment by zzak** [comment]
Why not use `new_defaults` to make the default `[:id]` for new apps and upgrading apps? Since it's faster.

**Comment by andrewn617** [comment]
@zzak What is 'new_defaults`, sorry I am not familiar with that and I am not seeing it in the code base. Do you just mean a framework default or something different? But I think in general it's a problem since `[:id]` is just the default wanted for prod but `:all` for dev and test - I don't think we can check the env at the time the default is applied.

**Comment by p8** [comment]
@andrewn617 we check it for some settings:
https://github.com/rails/rails/blob/caa0b512169dbecab0bcdb0017896e9b8de8814f/railties/lib/rails/application/configuration.rb#L38

**Comment by p8** [comment]
@andrewn617 I've updated the title of this PR to reflect the actual changes that got merged.

**Comment by p8** [comment]
I've added a CHANGELOG entry for this: https://github.com/rails/rails/pull/53473
