### PR TITLE
respect `pluralize_table_names` when generate fixture file. fixes #19519

### LINKED ISSUE #19519: generated fixture filename for model ignores ActiveRecord::Base.pluralize_table_names = false
When generating a model w/ `ActiveRecord::Base.pluralize_table_names` set to `false`, the singular-named table is created, correctly, but a plural-named fixture file is created, incorrectly, which raises an error on `$ rake test`:

`config/environment.rb`:

```ruby
ActiveRecord::Base.pluralize_table_names = false
```

```sh
$ rails generate model foo
      invoke  active_record
      create    db/migrate/011_create_foo.rb
      create    app/models/foo.rb
      invoke    minitest
      create      test/models/foo_test.rb
      create      test/fixtures/foos.yml
```

The plural-named fixture, `foos.yml` causes `$ rake test` to raise an error:

```
Mysql2::Error: Table 'planner_test.foos' doesn't exist
```

I am experiencing this w/ Rails 4.2.1, and I think that it was also occurring w/ 4.2.0.

thanks.

### PR DESCRIPTION
**Pull request by y-yagi**
Closes #19519

### CODE REVIEW

File: railties/test/generators/model_generator_test.rb [hunk 1]
```diff
@@ -319,6 +319,15 @@ def test_fixture_is_skipped_if_fixture_replacement_is_given
     assert_no_file "test/fixtures/accounts.yml"
   end
 
+  def test_fixture_without_pluralization
+    ActiveRecord::Base.pluralize_table_names = false
+    run_generator
+    assert_generated_fixture("test/fixtures/account.yml",
+                             {"one"=>{"name"=>"MyString", "age"=>1}, "two"=>{"name"=>"MyString", "age"=>1}})
+  ensure
+    ActiveRecord::Base.pluralize_table_names = true
```
Comment (senny) [inline railties/test/generators/model_generator_test.rb]: it's better to use a local variable instead of hardcoding the default value:

```ruby
original_pluralize_table_name = ActiveRecord::Base.pluralize_table_names
ActiveRecord::Base.pluralize_table_names = false

ensure
  ActiveRecord::Base.pluralize_table_names = original_pluralize_table_name
end
```

**Comment by senny** [comment]
@y-yagi looks good, can you add an entry to the CHANGELOG?

**Comment by y-yagi** [comment]
@senny Thanks for reviewing! I updated test and added an entry to the CHANGELOG.

File: railties/lib/rails/generators/named_base.rb [hunk 2]
```diff
@@ -141,6 +141,10 @@ def plural_file_name
           @plural_file_name ||= file_name.pluralize
         end
 
+        def fixture_file_name
+          @fixture_file_name ||= (pluralize_table_names? ? file_name.pluralize : file_name)
```
Comment (senny) [inline railties/lib/rails/generators/named_base.rb]: Instead of `file_name.pluralize` we can stick to `plural_file_name`.

Comment (y-yagi) [inline railties/lib/rails/generators/named_base.rb]: Thanks! I updated.

**Comment by senny** [comment]
@y-yagi thank you :yellow_heart:

**Comment by y-yagi** [comment]
@senny Thanks!

**Comment by erikj** [comment]
Thanks!
