### PR TITLE
raise `ArgumentError` when `SECRET_KEY_BASE` is an integer

### LINKED ISSUE #22072: Exception when SECRET_KEY_BASE is a large number
### Summary

If ENV var `SECRET_KEY_BASE` is composed only of digits, like `12387368712638765823746812735` it will be treated as a Bignum instead of a String.

### Stack trace

```
ERROR -- : no implicit conversion of Bignum into String (TypeError)
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/key_generator.rb:21:in `pbkdf2_hmac_sha1'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/key_generator.rb:21:in `generate_key'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/key_generator.rb:38:in `generate_key'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:206:in `message_verifier'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/globalid-0.3.6/lib/global_id/railtie.rb:25:in `block (2 levels) in <class:Railtie>'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:36:in `call'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:44:in `each'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/Users/kuon/Repositories/memoways/comet/config/environment.rb:5:in `<top (required)>'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
config.ru:4:in `block in <main>'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `eval'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `block in builder'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `call'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `build_app!'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:632:in `init_worker_process'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:655:in `worker_loop'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:540:in `maintain_worker_count'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:294:in `join'
/Users/kuon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
/Users/kuon/.rbenv/versions/2.2.3/bin/unicorn:23:in `load'
/Users/kuon/.rbenv/versions/2.2.3/bin/unicorn:23:in `<main>'
```

### Expected behaviour

Either crash "properly" with a warning or cast the key to a string.

### PR DESCRIPTION
**Pull request by arunagw**
If `SECRET_KEY_BASE` or other `secret` gets passed as other then string
we need to raise `ArgumentError` to know that it's a wrong argument.

Closes #22072

### CODE REVIEW

**Comment by schneems** [comment]
Will this change the value returned by `generate_key` ?

**Comment by rafaelfranca** [comment]
And why would `secrets.yml` have an integer?

**Comment by arunagw** [comment]
@schneems Nope it will not change the value as other specs are fine but I will double check.

@rafaelfranca I saw #22072 and found that it's easy to incorporate

**Comment by rafaelfranca** [comment]
It is invalid input. This should be always a string, so it should raise an
argument error if it is not a string, not accept any value. Could you
change your patch to raise the argument error?

**Comment by arunagw** [comment]
Yes. I can work on this.

**Comment by arunagw** [comment]
@rafaelfranca I have updated PR with changes. Please have a look. thanks

File: activesupport/lib/active_support/key_generator.rb [hunk 1]
```diff
@@ -8,6 +8,9 @@ module ActiveSupport
   # key in multiple incompatible contexts.
   class KeyGenerator
     def initialize(secret, options = {})
+      unless secret.kind_of?(String)
+        raise ArgumentError, "Secret must be a type of String"
```
Comment (rafaelfranca) [inline activesupport/lib/active_support/key_generator.rb]: Maybe we should check it were we assign with a proper message pointing to the secrets configuration. I think if we raise here it will not be user friendly.

**Comment by arunagw** [comment]
@rafaelfranca Yes. make sense to point user into right direction.

I found that we are also doing some secrets.yml raise in `LegacyKeyGenerator` [here](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/key_generator.rb#L58-L63). So initially i thought to raise from `KeyGenerator`.

**Comment by arunagw** [comment]
@spastorino Should we backport this to `4-2-stable`?

**Comment by spastorino** [comment]
@arunagw I wouldn't, I don't think it's that important.
