### PR TITLE
avoid error when sort mixture keys in symbol and string

### LINKED ISSUE #19314: comparison of Array with Array failed in formatter.rb
I just upgraded Rails from 4.1.6 to 4.2.0, and I'm getting a new error. The intention of my code is to take a "bad" request and redirect it to the proper URL.

Relevant [routes](https://github.com/JasonBarnabe/greasyfork/blob/c706578cc0b200b96fbde0530cb4d76a3c45f6c0/config/routes.rb#L55) (the "bad" URL is handled by `show`, the proper URL is the `meta_js` route.
```ruby
resources :scripts, :only => [:index, :show] do
  match 'code/:name.meta.js', :to => 'scripts#meta_js', :locale => nil, :via => :options
end
```

In the [controller](https://github.com/JasonBarnabe/greasyfork/blob/c706578cc0b200b96fbde0530cb4d76a3c45f6c0/app/controllers/scripts_controller.rb#L170), handling the "bad" request:
```ruby
redirect_to script_meta_js_path(params.merge({:script_id => params[:id], :name => @script.name, :format => nil}))
```
Requesting `/en/scripts/3286-tumblr-mass-post-features` with the proper `Accept` header to trigger the logic, the result is:
```
ArgumentError in ScriptsController#show
comparison of Array with Array failed

actionpack (4.2.0) lib/action_dispatch/journey/formatter.rb:44:in `sort'
actionpack (4.2.0) lib/action_dispatch/journey/formatter.rb:44:in `generate'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:710:in `generate'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:741:in `generate'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:784:in `url_for'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:279:in `call'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:222:in `call'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:334:in `block (2 levels) in define_url_helper'
app/controllers/scripts_controller.rb:170:in `block (2 levels) in show'
```
The error in formatter.rb is on:
```ruby
        message = "No route matches #{Hash[constraints.sort].inspect}"
 ```
Adding some debugging to formatter.rb, I see that `constraints` is set to:
```ruby
{:controller=>"scripts", :action=>"meta_js", :locale=>nil, :id=>"3286-tumblr-mass-post-features", "locale"=>"en", "id"=>"3286-tumblr-mass-post-features", "script_id"=>"3286-tumblr-mass-post-features", "name"=>"Tumblr - Mass Post Features", "format"=>nil, "controller"=>"scripts", "action"=>"show"}
```
Both `:id` and `"id"` are present, so maybe that's why it fails.

It's possible that my routing logic is wrong, but this looks like it's failing on giving me an error message...

### PR DESCRIPTION
**Pull request by y00rb**
when no route matches or missing required parameter, generate method will raise error.
but if mixture symbol and string in parameter, the sort method will
error:

``` bash
 comparison of Array with Array failed
```

the reason is because the sort method used <=> and thatn't work when
comparing a symble with at string:

``` bash
>> :foo <=> 'foo'
=> nil
```

this is fix #19314 in actionpack/lib/action_dispatch/journey/formatter.rb

### CODE REVIEW

File: actionpack/lib/action_dispatch/journey/formatter.rb [hunk 1]
```diff
@@ -39,7 +39,9 @@ def generate(name, options, path_parameters, parameterize = nil)
           return [route.format(parameterized_parts), params]
         end
 
-        message = "No route matches #{Hash[constraints.sort].inspect}"
+        # Merge duplicate parameters which duplicated with different formart, and make all keys as symbol
+        primarty_parameters = constraints.inject({}){|h,(k,v)| h[k.to_sym] = v; h}
```
Comment (rafaelfranca) [inline actionpack/lib/action_dispatch/journey/formatter.rb]: can we make them all strings?

Comment (y00rb) [inline actionpack/lib/action_dispatch/journey/formatter.rb]: make all string, them we can used `with_indifferent_access` method.

**Comment by y00rb** [comment]
@rafaelfranca 
Thanks for your suggestion. it is fixed now. I also changed them all string in file `actionpack/lib/action_dispatch/routing/route_set.rb` that avoid same issues when sort.

**Comment by rafaelfranca** [comment]
While this works it may make users confused. The reason they are getting this error is because they are merging user parameters with a hash what is discouraged as @pixeltrix explained at https://github.com/rails/rails/issues/19314#issuecomment-78902663 and merging string keys and symbols keys will just not show the real problem

What if, we just stop to sorting the hash?

**Comment by y00rb** [comment]
yeah, for `"foo" <=> :foo'  case, i think most saturation are user send the wrong key.
such as putting "action" or "id" on *_path/_url method. in this way, the `:action, "action"` being same value.
and the error is cause by parameter missing.
how about adding duplicated parameters on error? same key with different format(symbol, string).

**Comment by rafaelfranca** [comment]
Doesn't removing the `sort` call fix it?

**Comment by y00rb** [comment]
yes, filter duplicated parameter(string format) on error. such as 
1. compare which is duplicated keys and format as string.
2. append message after "missing_keys"
```ruby
message << " checking duplicated: #{Hash[mixed_parameters.sort].inspect}" unless mixed_parameter.empty?
```

**Comment by rafaelfranca** [comment]
Seems good

**Comment by y00rb** [comment]
I will make the changes following discussion today.
then you can review it at tomorrow.

**Comment by y00rb** [comment]
@rafaelfranca 
make minimum changes, replace sort via sort_by. event keys duplicated as string and symbol, just putting them in sorted list.

**Comment by rafaelfranca** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by rafaelfranca** [comment]
Backported as 312f086
