### PR TITLE
Fix predicate builder for polymorphic models referencing models with composite primary keys

### LINKED ISSUE #50318: `Where(relation: )` broken for polymorphic records when using composite primary keys
### Steps to reproduce

When creating a polymorphic association with composite primary keys where(relation: model) is broken. 

- Create a model with composite primary key (e.g. Post as commentable) 
- Point another model towards it with a polymorphic relation (e.g Comment)
- Comment.where(commentable: post) will raise: `ArgumentError: Expected corresponding value for ["commentable_title", "commentable_author"] to be an Array`

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, primary_key: [:title, :author], force: true do |t|
    t.string :title
    t.string :author
  end

  create_table :comments, force: true do |t|
    t.string :commentable_title
    t.string :commentable_author
    t.string :commentable_type
  end
end

class Post < ActiveRecord::Base
  has_many :comments, query_constraints: %i[commentable_title commentable_author], as: :commentable
end

class Comment < ActiveRecord::Base
  belongs_to :commentable, query_constraints: %i[commentable_title commentable_author], polymorphic: true
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(title: "post", author: "author")
    post.comments << Comment.create!

    assert Comment.where(commentable: post).exists?
  end
end
```

### Expected behavior
Correct collection should be returned. 

### Actual behavior
Error is raised instead 

### System configuration
**Rails version**: edge 

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #50318.

I needed to create 2 models for the test case, because there is no currently Cpk model where both primary key columns are not `"id"`. When one of them is named `"id"`, we do not get the error as in the linked issue https://github.com/rails/rails/blob/5c4a7a711068c1dff2bd873da510ddbb82dcadd7/activerecord/lib/active_record/reflection.rb#L875-L879

### CODE REVIEW

File: activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_value.rb [hunk 1]
```diff
@@ -42,10 +42,16 @@ def klass(value)
         end
 
         def convert_to_id(value)
+          primary_key = primary_key(value)
+
           if value.is_a?(Base)
```
Comment (jackozi) [inline activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_value.rb:47]: Maybe it's better to move the primary key assignment inside the if clause so that it's not called when hitting the else clause.

Comment (fatkodima) [reply activerecord/lib/active_record/relation/predicate_builder/polymorphic_array_value.rb]: Yeah, it was for DRYing the code, but turned out this is not working, thanks.

**Comment by fatkodima** [comment]
Opened a backport PR.
