### PR TITLE
Return "test" as the controller_name in ActionView tests

### LINKED ISSUE #42384: controller_name returns nil in Helper Specs
### Steps to reproduce

This minitest will fail
https://gist.github.com/koki-miyazaki/b3918113cb324097ebf2203213c212e9

### Expected behavior

The above test won't fail
`#controller_name` method returns `test` string

### Actual behavior

The above minitest fails
`#controller_name` method returns nil

Before 6.1.0, `controller_name` returned string `test`

The PR made `@controller` to be a subclass of `ActionView::TestCase::TestController`
https://github.com/rails/rails/pull/40125/files#diff-ce84a807f3491121a5230d37bd40454bb1407fcca71179e1a2fa76d4c0ddfa2aR105-R106
So, it's `#name` method will be nil

my project uses `controller_name` in a helper class, so the test for it is affected by the change.

### System configuration
**Rails version**:
6.1.0
**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin18]

### PR DESCRIPTION
**Pull request by HParker**
before https://github.com/rails/rails/pull/40125 test names would be
set to "test" after this change controller_name was nil when using
ActionView::TestCase.

This returns ActionView::TestCase to previous behavior returning "test"

The previous change seemed open to maintaining this behavior. The discussion in https://github.com/rails/rails/issues/42384 seems to suggest the same.

closes: https://github.com/rails/rails/issues/42384

### CODE REVIEW

**Review by zzak — APPROVED** [review]

File: actionview/test/template/test_case_test.rb [hunk 1]
```diff
@@ -56,6 +56,10 @@ class GeneralViewTest < ActionView::TestCase
       assert_same _view, view
     end
 
+    test "returns controller_name" do
+      assert_equal controller_name, "test"
```
Comment (kamipo) [inline actionview/test/template/test_case_test.rb:60]:
```suggestion
      assert_equal "test", controller_name
```

Comment (HParker) [reply actionview/test/template/test_case_test.rb]: Thanks! I still make this mistake after all these years. 🤦
