### PR TITLE
Fix decrementing counter caches for parent records using optimistic locking

### LINKED ISSUE #48320: Decrementing counter_cache column fails when optimistic locking is enabled.
### Steps to reproduce
- Create a Post model with lock_version and comments_count columns and a has_many relation with :comments.
- Create a Comment model with lock_version column and a belongs_to relation with :post, using counter_cache = true
- post = Post.create
- comment = Comment.create(post:)
- comment.destroy

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
# ActiveRecord::Base.establish_connection(adapter: "mysql2", database: "vacushop7", username: "developer", password: "developer", socket: "/tmp/mysql.sock")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :lock_version, default: 0, null: false
    t.integer :comments_count, default: 0, null: false
  end

  create_table :comments, force: true do |t|
    t.integer :lock_version, default: 0, null: false
    t.integer :post_id, null: false
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post, counter_cache: true
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    comment = Comment.create(post:)

    assert_equal 1, post.reload.comments_count
    Comment.last.destroy
    assert_equal 0, post.reload.comments_count
  end
end
```

### Expected behavior
After the comment is created, comments_count increases with 1.
After the comment is destroyed, comments_counts decreases with 1.

### Actual behavior
After the comment is created, comments_count increases indeed (correct behavior).
When the comment is destroyed, nothing happens with the comments_count column (incorrect behavior).

I've tried to locate the origin of the bug and I find in line 121 of lib/active_record/locking/optimistic.rb that when the unless-condition is removed out, it works. I don't know however if this impacts other things.

### System configuration
**Rails version**: 7.0.5

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #48320.

When used optimistic locking, it uses custom logic without calling `super` https://github.com/rails/rails/blob/e9ea600c24bb44317cf6176c34020a7d0e1060f3/activerecord/lib/active_record/locking/optimistic.rb#L125-L137 without a chance for counter cache to implement its logic. So I swapped the includes. Are there any  pitfalls this can introduce?

### CODE REVIEW

**Comment by byroot** [comment]
> Are there any pitfalls this can introduce?

Hum, not 100% sure. Changing the order is nice, but it could indeed introduce some other subtle bugs.

I wonder if we shouldn't try to fix `Optimistic#destroy_row` so that it always call `super`.

The reason it's currently bypassing the parent implementation right now, is that it want to add some extra keys in `_query_constraints_hash`.

Perhaps it should override that method to do that?

**Comment by fatkodima** [comment]
Thanks! Updated with your suggestion.

File: activerecord/lib/active_record/locking/optimistic.rb [hunk 1]
```diff
@@ -152,6 +144,13 @@ def _clear_locking_column
           clear_attribute_change(self.class.locking_column)
         end
 
+        def _query_constraints_hash
+          return super unless locking_enabled?
+
+          locking_column = self.class.locking_column
+          super.merge(locking_column => _lock_value_for_database(locking_column))
```
Comment (byroot) [inline activerecord/lib/active_record/locking/optimistic.rb:151]: I think we could have mutated the hash rather than to use `merge`, but no big deal.

**Comment by byroot** [comment]
Thanks!
