### PR TITLE
Clear AR connections in tests before forking for parallelization

### LINKED ISSUE #41176: Parallel-testing test-run raises Bad file descriptor (Errno::EBADF) using MySQL 8.0
**See below:** The issue can also be worked around by compiling the mysql2 gem using the mysql 5.7 client: https://github.com/rails/rails/issues/41176#issuecomment-772186345

**Updated** to reflect that the issue also exists under apps using Rails 6.1.1 and rails/rails. https://github.com/johnmaxwell/parallelmysql61

We updated an application to Rails 6.0.3.4 and configured it to use parallel tests. This application uses MySQL 8.0. Our team uses Macs for our development machines, and MySQL 8.0 is installed via Homebrew with little-to-no customization.

When running the test-suite in parallel with two or more workers, the tests will raise an error: `Bad file descriptor (Errno::EBADF)`  part way through the run. It's unclear what causes this issue since the exception originates from `drb/drb.rb`. 

We've tweaked the gems and poked and prodded at this application in an attempt to fix the problem to no avail. The only "fix" is to run the tests serially by changing `test_helper.rb` or using `PARALLEL_WORKERS=1` when running the test suite. This is advice that you usually find on StackOverflow when searching for this problem.

### Steps to reproduce

We have reproduced this issue in a stock Rails 6.0.3.4 application connecting to a MySQL 8.0 database: https://github.com/johnmaxwell/parallelmysql 

This simple Rails application was generated with the following commands:

```
rails new parallelmysql -d mysql
./bin/rails db:create 
./bin/rails g model User name:string
./bin/rails db:migrate
```

We give `test/models/user_test.rb` the following content. This gives us a bunch of time-consuming tests for the parallel test suite to run.

```ruby
require 'test_helper'

class UserTest < ActiveSupport::TestCase
  200.times do |i|
    test "test-case ##{i}: creates #{i} records" do
      i.times do
        User.create!(name: SecureRandom.alphanumeric(20))
      end
      assert_equal i, User.count
    end
  end
end
```

### Expected behavior

Running the tests with the following command should run the test suite to completion using 2 test workers. `PARALLEL_WORKERS=2 ./bin/rails test` 

### Actual behavior

The tests suite fails without running to completion with the following output:

```
$ PARALLEL_WORKERS=2 ./bin/rails test
Running via Spring preloader in process 9204
Run options: --seed 6137

# Running:

......#<Thread:0x00007ffcb81416c8 /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1259 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	10: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1262:in `block in make_pool'
	 9: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1237:in `_execute'
	 8: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
	 7: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
	 6: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1239:in `block in _execute'
	 5: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1268:in `block (2 levels) in make_pool'
	 4: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1268:in `each'
	 3: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1270:in `block (3 levels) in make_pool'
	 2: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1334:in `alive?'
	 1: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1002:in `alive?'
/Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1002:in `wait_readable': Bad file descriptor (Errno::EBADF)
#<Thread:0x00007ffcb81416c8 /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1259 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	10: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1262:in `block in make_pool'
	 9: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1237:in `_execute'
	 8: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
	 7: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
	 6: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1239:in `block in _execute'
	 5: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1268:in `block (2 levels) in make_pool'
	 4: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1268:in `each'
	 3: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1270:in `block (3 levels) in make_pool'
	 2: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1334:in `alive?'
	 1: from /Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1002:in `alive?'
/Users/john/.rbenv/versions/2.7.2/lib/ruby/2.7.0/drb/drb.rb:1002:in `wait_readable': Bad file descriptor (Errno::EBADF)
```

### System configuration
**Rails version**: 6.0.3.4, 6.1.1 & rails/rails:e8d7181ad6fd040b60c25752c1a60d939e4a8505
**Ruby version**: 2.7.2p137
**MySQL version**: 8.0.22, 8.0.23
**MacOS versions**: 10.15.7

### PR DESCRIPTION
**Pull request by flavorjones**
### Motivation / Background

Works around #41176 which seems to affect the mysql2 adapter built with the mysql8 client library on MacOS.

### Detail

This PR introduces a before-fork hook into ActiveSupport::Testing::Parallelization, which is invoked immediately before spawning the worker processes.

This PR also implements a before-fork hook in ActiveRecord::TestDatabases to clear connections, to avoid the symptoms of poor fork-safety in the mysql2 8.0 client / mysql2 adapter.

We see this problem relatively often at 37s when running large test suites on MacOS development machines.

### Additional information

This PR does not directly address the fork-safety issue in the mysql8 client library, but closing connections in a test process before forking doesn't have any obvoius negative impacts that I know of, and so my hope is something like this would be an acceptable tradeoff.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [-] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by flavorjones** [comment]
An interesting historical note: I tried previously to introduce some pre-fork behavior to Rails generally in https://github.com/rails/rails/pull/52931#issuecomment-2351365601 to address an unrelated fork-safety issue with sqlite.

The thoughts at that time were that we don't want to mess with parent processes' open connections because it requires stopping the world (i.e., getting a lock on all connections might be hard to do in a timely fashion on a live web server). Which I think is a reasonable worry and I was able to create an alternative post-fork fix that lives inside the sqlite3-ruby gem.

cc @dhh who has thoughts about whether/when/if/how we should allow the framework to close connections before forking.

File: activesupport/lib/active_support/testing/parallelization.rb [hunk 1]
```diff
@@ -32,7 +40,14 @@ def initialize(worker_count)
         @url = DRb.start_service("drbunix:", @queue_server).uri
       end
 
+      def before_fork
+        Parallelization.before_fork_hooks.each do |cb|
+          cb.call
+        end
```
Comment (byroot) [inline activesupport/lib/active_support/testing/parallelization.rb:46]:
```suggestion
        Parallelization.before_fork_hooks.each(&cb)
```

/nitpick

File: activerecord/lib/active_record/test_databases.rb [hunk 2]
```diff
@@ -4,6 +4,11 @@
 
 module ActiveRecord
   module TestDatabases # :nodoc:
+    ActiveSupport::Testing::Parallelization.before_fork_hook do
+      puts "PREFORK: clearing connections"
```
Comment (byroot) [inline activerecord/lib/active_record/test_databases.rb:8]: This output may be annoying.

**Review by byroot — COMMENTED** [review]
I don't have any strong opinion against it.

Regardless of your issues with mysql2, a pre-fork hook is always sensible as users may need to do other fork preparation.

A post fork hook would probably make sense too.

That being said, I would have prefered to figure out what the `mysql2` problem actually is, but given how shitty `libmysqlclient` is, and that we know have `trilogy`, it might not be worth the effort. If anything I'd rather start considering a timeline to extract `Mysql2Adapter` into its own gem, and winding down support.

**Comment by byroot** [comment]
Just to give some more actionable feedback. I think we shouldn't just provide `before_fork`, but also `after_fork` for consistency with most other fork callback systems. Other than that I'm OK with this change.

**Comment by matthewd** [comment]
Looks like `after_fork_hook` is already there.

So yeah I think ✂️ the `puts` and this is fine.

I'd like to imagine we could fix the underlying issue in mysql2, because this _shouldn't_ be necessary, but given it's only happening at the start of test parallelisation (where I imagine it'd be moderately rare to even have a connection to clear?)... yeah, it's fine. 😅

File: activerecord/lib/active_record/test_databases.rb (hunk 2 above)
Comment (flavorjones) [reply activerecord/lib/active_record/test_databases.rb:8]: ugh, this was unintentional! 🤦

**Comment by flavorjones** [comment]
> I would have prefered to figure out what the mysql2 problem actually is

The underlying issue was diagnosed in [this comment](https://github.com/rails/rails/issues/41176#issuecomment-1492649116) by @jgloudon. On MacOS the mysql8 client library is using kqueue which creates a file descriptor that is not carried into the child process, allowing for the FD to be re-used, and hilarity ensues. It's not clear if it can be worked around / fixed in the ruby driver, but that library has not had high PR velocity lately.

I've addressed the concerns raised in the review notes. Thanks for your time!

File: activerecord/lib/active_record/test_databases.rb (hunk 2 above)
Comment (zzak) [reply activerecord/lib/active_record/test_databases.rb]: It's a feature.
