### PR TITLE
Deprecate `where.not` working as NOR and will be changed to NAND in Rails 6.1

### LINKED ISSUE #31209: The construct "where.not" doesn't respect boolean algebra
### Steps to reproduce

When two predicates A and B are given to a `where` clause, Rails combines them using `AND`, which is the expected behavior. 
```ruby
Model.where(col1: 1, col2: 2).to_sql

# => SELECT "models".* FROM "models" WHERE "models"."col1" = 1 AND "models"."col2" = 2
```

When the clause is negated (using `where.not`), Rails distributes the `NOT` to every predicate before combining them using `AND`. Why? 

```ruby
Model.where.not(col1: 1, col2: 2).to_sql

# => SELECT "models".* FROM "models" WHERE ("models"."col1" != 1) AND ("models"."col2" != 2)
```

### Expected behavior

`NOT(A AND B)` = `NOT(A) OR NOT(B)` 

In my example, the query should look like:
```sql
SELECT "models".* FROM "models" WHERE ("models"."col1" != 1) OR ("models"."col2" != 2)
```

### Actual behavior

`NOT(A AND B)` = `NOT(A) AND NOT(B)` (wrong)

It's worth noting that the correct behavior can still be obtained by writing SQL directly:

```ruby
Model.where.not('"models"."col1" = 1 AND "models"."col2" = 2').to_sql
# => SELECT "models".* FROM "models" WHERE (NOT ("models"."col1" = 1 AND "models"."col2" = 2))
```

It makes the construct `where.not(...)` behave very differently depending on the kind of arguments which are passed to it.

The culprit seems to be located here : https://github.com/rails/rails/blob/be81b5066074fee8126144d072c6132b93d1fe39/activerecord/lib/active_record/relation/where_clause.rb#L74

### System configuration
**Rails version**: 5.1.4

**Ruby version**: MRI 2.4.2

### PR DESCRIPTION
**Pull request by kamipo**
`where.not` with polymorphic association is partly fixed incidentally at
213796f (refer #33493, #26207, #17010, #16983, #14161), and I've added
test case e9ba12f to avoid lose that fix accidentally in the future.

In Rails 5.2, `where.not(polymorphic: object)` works as expected as
NAND, but `where.not(polymorphic_type: object.class.polymorphic_name,
polymorphic_id: object.id)` still unexpectedly works as NOR.

To will make `where.not` working desiredly as NAND in Rails 6.1, this
deprecates `where.not` working as NOR. If people want to continue NOR
conditions, we'd encourage to them to `where.not` each conditions
manually.

```ruby
all = [treasures(:diamond), treasures(:sapphire), cars(:honda), treasures(:sapphire)]
assert_equal all, PriceEstimate.all.map(&:estimate_of)
```

In Rails 6.0:

```ruby
sapphire = treasures(:sapphire)

nor = all.reject { |e|
  e.estimate_of_type == sapphire.class.polymorphic_name
}.reject { |e|
  e.estimate_of_id == sapphire.id
}
assert_equal [cars(:honda)], nor

without_sapphire = PriceEstimate.where.not(
  estimate_of_type: sapphire.class.polymorphic_name, estimate_of_id: sapphire.id
)
assert_equal nor, without_sapphire.map(&:estimate_of)
```

In Rails 6.1:

```ruby
sapphire = treasures(:sapphire)

nand = all - [sapphire]
assert_equal [treasures(:diamond), cars(:honda)], nand

without_sapphire = PriceEstimate.where.not(
  estimate_of_type: sapphire.class.polymorphic_name, estimate_of_id: sapphire.id
)
assert_equal nand, without_sapphire.map(&:estimate_of)
```

Resolves #31209.

### CODE REVIEW

**Comment by kamipo** [comment]
I'll going to merge the deprecation in 6.0 to will fix `where.not` in 6.1.
Let me know if anyone has any objection.

File: activerecord/lib/active_record/relation/query_methods.rb [hunk 1]
```diff
@@ -41,18 +41,31 @@ def initialize(scope)
...
 
         where_clause = @scope.send(:where_clause_factory).build(opts, rest)
 
         @scope.references!(PredicateBuilder.references(opts)) if Hash === opts
-        @scope.where_clause += where_clause.invert
+
+        if not_behaves_as_nor?(opts)
+          ActiveSupport::Deprecation.warn(<<~MSG.squish)
+            NOT conditions will no longer behave as NOR in Rails 6.1.
+            To continue using NOR conditions, NOT each conditions manually
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/relation/query_methods.rb]: This message is confusing. How about?

```
To continue using NOR conditions, chain each `NOT` condition manually.
```

Comment (kamipo) [reply activerecord/lib/active_record/relation/query_methods.rb]: I'm not sure that people want to hurry to migrate to new method, since we have left this issue alone for 5 years (oldest one #14161 I can find).

This issue has already mitigated by 213796f (e9ba12f), and will eventually be fixed even if new method isn't introduced.
