### PR TITLE
Relax the prism test parser conditions

### LINKED ISSUE #51956: Rails 7.2: Parsing tests with prism makes it impossible to run spec-style tests by line number
### Steps to reproduce
* Create a new rails project and add `minitest-spec-rails` as a dependency.
* Write a test class with the following lines:
```rb
require "test_helper"

class MyTest < ActiveSupport::TestCase
  test "it does something" do
    assert true
  end

  it "does something else" do
    assert true
  end
end
```

Use the test runner and try to run both by line number:
```sh
$ bin/rails test test/channels/connection_test.rb:4
Running 2 tests in a single process (parallelization threshold is 50)
Run options: --seed 8960

# Running:

.

Finished in 0.002918s, 342.6654 runs/s, 342.6654 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

```sh
$ bin/rails test test/channels/connection_test.rb:8
Running 2 tests in a single process (parallelization threshold is 50)
Run options: --seed 30964

# Running:



Finished in 0.000656s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

I have bisected this to PR #51006. I think this is because of the explicit name check against `test` for call/def nodes? It doesn't look like the ripper one does that

### System configuration
**Rails version**: 7.2.0.beta1

**Ruby version**: 3.3.1

### PR DESCRIPTION
**Pull request by Earlopain**
### Motivation / Background

Closes #51956

### Detail

Checking explicitly against `test` break extensions that provide their own methods to generate tests, like `minitest-spec-rails` or `minitest-rails`. The ripper parser had no such checks, so I just dropped those.

cc @kddnewton

### Additional information

Needs backporting to 7.2. Maybe changelog?

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Review by kddnewton — COMMENTED** [review]
Ahh I missed that it didn't check that. Thanks!

File: railties/test/test_unit/test_parser_test.rb [hunk 1]
```diff
@@ -38,6 +38,19 @@ def test_oneline; assert true; end
     assert true
     assert_not false
   }
+
+  # Emulate minitest/spec. Check that extensions can provide aliases
```
Comment (rafaelfranca) [inline railties/test/test_unit/test_parser_test.rb:42]: Can we use something else to test this? We really don't want to make like we support minitest/spec or any syntax that looks like rspec.

**Review by rafaelfranca — CHANGES_REQUESTED** [review]

File: railties/test/test_unit/test_parser_test.rb (hunk 1 above)
Comment (Earlopain) [reply railties/test/test_unit/test_parser_test.rb]: Yeah, sure. I made it look more generic
