### PR TITLE
ActiveRecord PostgreSQL adapter: parse quoted values in range output

### LINKED ISSUE #37647: ActiveRecord fails to parse BCE (negative) dates in PostgreSQL time ranges
### Steps to reproduce

Executable test case:
https://gist.github.com/chrisandreae/cfac1fe1e2e2b2b987e3aa826f803c86

* Create an ActiveRecord model for a table with a `tsrange` column
* Create and persist a record with a time range including a BCE (negative) year.
  `m = Model.create(period: (::DateTime.new(-1000, 1, 1, 0, 0) .. Time.now.utc))`
* Reload the model and observe that the `begin` of the loaded range has been changed to a positive date:
  `> model.reload.period.begin`
  `=> 1001-01-01 00:00:00 UTC`

This is caused by missing handling for nested quoting of range values in `ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Range`.

### Expected behavior
The tsrange attribute should be reloaded with the same `DateTime` values as when persisted.

### Actual behavior
The tsrange attribute is reloaded with the absolute value of the year stored in
the database: for example, the year `-1000` is persisted as `1001 BC`, and so loaded as
`1001`.

### System configuration
**Rails version**:
`master` as of 803c6ba

**Ruby version**:
ruby 2.5.5p157

### PR DESCRIPTION
**Pull request by chrisandreae**
### Summary

When formatting the bound values of range types, PostgreSQL quotes the value using double-quotes in certain conditions: if its formatted representation contains parentheses, commas, double quotes, backslashes or whitespace (manual section 8.17.5, 8.16.6).

In particular this affects timestamps, which include whitespace and so will be formatted with double-quotes, for example `["2018-01-01 00:00:00",)`.

However, the parser for range values in `ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Range#cast_value` doesn't check for or extract quoted values. This results in a string potentially containing nested quotes being passed to the parser for the subtype.

In the case of timestamp ranges (where the subtype is `OID::DateTime`), this causes two problems:
 * The special-case handling for BCE in `DateTime#cast_value` is bypassed, resulting in incorrect positive instead of negative year values (Issue #37647).
 * `ActiveModel::Type::DateTime`'s `fast_string_to_time` parser can't be used and falls back to the `fallback_string_to_time` parser using `Date._parse`.

This change updates `Range#extract_bounds` to extract nested quoted values.

Fixes #37647

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb [hunk 1]
```diff
@@ -69,13 +69,24 @@ def type_cast_single_for_database(value)
...
+                to:            (value[-2] == "," || to == "infinity") ? infinity : unquote(to),
                 exclude_start: (value[0] == "("),
                 exclude_end:   (value[-1] == ")")
               }
             end
 
+            def unquote(value)
+              if value[0] == '"' && value[-1] == '"'
+                value[1..-2].tap do |quoted_value|
+                  quoted_value.gsub!('""','"')
```
Comment (chrisandreae) [inline activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb]: While PostgreSQL is permissive about accepting multiple escape styles for double quotes in input (`\"` or `""`), the output format always uses `""` (see manual 8.16.6)

Comment (kamipo) [reply activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb]: Can you note the manual link on the code why we unquote two characters?

File: activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb [hunk 2]
```diff
@@ -69,13 +69,24 @@ def type_cast_single_for_database(value)
...
-                to:            (to == "" || to == "infinity") ? infinity : to,
+                from:          (from == "" || from == "-infinity") ? infinity(negative: true) : unquote(from),
+                to:            (to == "" || to == "infinity") ? infinity : unquote(to),
                 exclude_start: value.start_with?("("),
                 exclude_end:   value.end_with?(")")
               }
             end
 
+            def unquote(value)
+              if value[0] == '"' && value[-1] == '"'
```
Comment (kamipo) [inline activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb:80]: `value[0]` and `value[-1]` allocates a new string, use non-allocation `start_with?` and `end_with?`.

```suggestion
              if value.start_with?('"') && value.end_with?('"')
```

File: activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb [hunk 3]
```diff
@@ -69,13 +69,24 @@ def type_cast_single_for_database(value)
...
+                value[1..-2].tap do |quoted_value|
+                  quoted_value.gsub!('""', '"')
+                  quoted_value.gsub!('\\\\', '\\')
+                end
```
Comment (kamipo) [inline activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb:84]: `tap` has an extra overhead, just use `unquoted_value = value[1..-2]` instead.

```suggestion
                unquoted_value = value[1..-2]
                unquoted_value.gsub!('""', '"')
                unquoted_value.gsub!('\\\\', '\\')
                unquoted_value
```

Comment (kamipo) [reply activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb:84]: Also, can you add tests for the quoted two characters? Looks like any test isn't failed if we lose the lines.

Comment (chrisandreae) [reply activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb]: This is rather tricky to obtain using only Postgres's range types as test cases, as none of the standard ranges' bound types use `"` or `\` in their serialization formats. I've added a test that defines and uses a varchar range in order to allow bound values that require escaping.

**Comment by chrisandreae** [comment]
Well, this is awkward:
```
Error:
PostgresqlRangeTest#test_custom_range_value_escaping:
ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  malformed range literal: "[ca\t,do"g)"
DETAIL:  Unexpected end of input.
```

Because Rails doesn't do any escaping when serializing bound values, including a bound value which requires escaping fails.

Can this problem be addressed as a separate issue/PR? As it stands, this PR fixes the more common case of receiving ranges with quoted timestamps from Postgres and failing to properly unquote them before passing the bound value to `OID::DateTime`.

**Comment by kamipo** [comment]
If custom range type which is required escape/unescape in range did not work entirely, I'd prefer to fix only tsrange in this PR (I'll merge it and then backport to 6-0-stable).

**Comment by chrisandreae** [comment]
Sure, I've split the changes to serialization and the corresponding test into a separate commit and opened a separate PR: https://github.com/rails/rails/pull/39585

File: activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb [hunk 4]
```diff
@@ -69,13 +69,30 @@ def type_cast_single_for_database(value)
...
+            # sections 8.17.5, 8.16.6). Within a double-quoted string, literal "
+            # and \ characters are themselves escaped. In input, PostgreSQL
+            # accepts multiple escape styles for " (either \" or "") but in
+            # output always uses "" (see 8.16.6).
+            def unquote(value)
+              if value.start_with?('"') && value.end_with?('"')
+                unquoted_value = value[1..-2]
+                unquoted_value.gsub!('""', '"')
+                unquoted_value.gsub!('\\\\', '\\')
+                unquoted_value
```
Comment (kamipo) [inline activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb:90]: Is this part still necessary? Regardless of unquoting the quoted characters or not, that doesn't work for now.

Comment (chrisandreae) [reply activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb:90]: Well, it's strictly still part of Postgres' output spec, so it seems wrong to leave it out just because Rails doesn't yet have the corresponding serialization side.

It also does work, for deserialization from Postgres: if there's a string range value `"ca\\t"..."do\"g"` in the database, Postgres will output that as `["ca""t","do\\g")` and Rails will correctly parse that with this code.

It's just that without the code that we split off into #39585, Rails is still lacking a way to perform the other direction and send such a value _to_ Postgres.

Comment (kamipo) [reply activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb:90]: Basically Active Record doesn't fully support custom type.
If you'd like to leave it for custom type, at least I'd not prefer untested change (i.e. all behavior change should be covered by tests).

Comment (chrisandreae) [reply activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb:90]: I think the problem is that this escaping handling handling is not specifically for custom types: it's about meeting Postgres' [specification for ranges](https://www.postgresql.org/docs/12/rangetypes.html#RANGETYPES-IO). Their documentation is clear on the cases where Postgres escapes the output and requires escaping on the input. It's actually only a coincidence that the formatting for the default range types happens to only include whitespace (and so not require input escaping).

I am happy to write a specific test that exercises this behavior. But the test for it will have to be a bit awkward, because we have chosen to hold back for now from correctly _serializing_ range values: it will have to only test the parsing. For the test to be nicer, we would have to reintroduce correcting the serialization to the PR.

Comment (chrisandreae) [reply activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb:90]: Done: I've written a test for the parsing behavior.

File: activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb [hunk 5]
```diff
@@ -69,13 +69,30 @@ def type_cast_single_for_database(value)
...
                 exclude_end:   value.end_with?(")")
               }
             end
 
+            # When formatting the bound values of range types, PostgreSQL quotes
+            # the bound value using double-quotes in certain conditions (manual
+            # sections 8.17.5, 8.16.6). Within a double-quoted string, literal "
+            # and \ characters are themselves escaped. In input, PostgreSQL
+            # accepts multiple escape styles for " (either \" or "") but in
+            # output always uses "" (see 8.16.6).
```
Comment (kamipo) [inline activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb:84]: Can you add the link for the doc?

Example:

https://github.com/rails/rails/blob/55f519f5b62db017077e2fc8aef31ba31708e038/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L296-L297
https://github.com/rails/rails/blob/1944a7e74c6c1b7a6234414a00d294412c05fde1/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L219-L221
https://github.com/rails/rails/blob/5fdf76f8fd585bdd8ba6a5d9a6132b673b8b205f/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L69-L74

File: activerecord/test/cases/adapters/postgresql/range_test.rb [hunk 6]
```diff
@@ -163,6 +168,12 @@ def test_custom_range_values
     assert_nil @empty_range.float_range
   end
 
+  def test_custom_range_value_escaping
+    insert_range(id: 106, string_range: '["ca""t","do\\g")')
+    escaped_range = PostgresqlRange.find(106)
+    assert_equal("ca\\t"..."do\"g", escaped_range.string_range)
```
Comment (kamipo) [inline activerecord/test/cases/adapters/postgresql/range_test.rb:174]: It is weird why the assertion is passed. Looks like `insert_range` doesn't support `string_range`.

https://github.com/rails/rails/blob/b119b4c4bf86d34fd6063fdbe4796dec30781a82/activerecord/test/cases/adapters/postgresql/range_test.rb#L433-L455

Comment (chrisandreae) [reply activerecord/test/cases/adapters/postgresql/range_test.rb:174]: I'll fix that, but that _is_ weird!

File: activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb (hunk 5 above)
Comment (chrisandreae) [reply activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb:84]: Certainly!

Comment (kamipo) [reply activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb:84]: Also, to be honest I'd not prefer to mention about dynamic section number, actually section number is a little fragile.

Example:

image

https://www.postgresql.org/docs/12/libpq-envars.html

image

https://www.postgresql.org/docs/11/libpq-envars.html

Comment (chrisandreae) [reply activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb:84]: Sure, happy to make that change

File: activerecord/test/cases/adapters/postgresql/range_test.rb [hunk 7]
```diff
@@ -363,6 +380,16 @@ def test_ranges_correctly_escape_input
...
   end
 
+  def test_ranges_correctly_unescape_output
+    @connection.execute(<<~SQL)
+      INSERT INTO postgresql_ranges (id, string_range)
+      VALUES (106, '["ca""t","do\\\\g")')
+    SQL
+
+    escaped_range = PostgresqlRange.find(106)
+    assert_equal('ca"t'...'do\\g', escaped_range.string_range)
```
Comment (kamipo) [inline activerecord/test/cases/adapters/postgresql/range_test.rb:390]: Is it possible to find the cause why the assertion is passed even if actually `string_range` is not inserted?

**Comment by kamipo** [comment]
Looks good to me except one weird thing.

Can you squash commits into one?
https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits

**Comment by chrisandreae** [comment]
No problem, happy to squash into one commit.

File: activerecord/test/cases/adapters/postgresql/range_test.rb (hunk 7 above)
Comment (chrisandreae) [reply activerecord/test/cases/adapters/postgresql/range_test.rb:390]: Figured it out. This test suite's `setup` block silently `skip`s the test case if there is a `StatementInvalid` exception during creating the table and types. Because at that point I had not yet fixed the `teardown` to include `DROP TYPE IF EXISTS stringrange`, this exception handler was hit on subsequent tests with a `#PG::DuplicateObject: ERROR:  type "stringrange" already exists`, and so after the first test, the rest of the whole test suite was being skipped.

Fortunately I had already fixed this error, so the current branch actually runs the tests.

**Comment by mkamensky** [comment]
This fails with an error in `unquote` when the value is `nil`, since it does not respond to `start_with?`

**Comment by chrisandreae** [comment]
Are there circumstances in which Postgres will emit a String value that doesn't contain a comma for a range type? The documentation seems to suggest this will not happen, except for the case of `empty`, which is separately handled: https://www.postgresql.org/docs/current/rangetypes.html#RANGETYPES-IO

**Comment by mkamensky** [comment]
> Are there circumstances in which Postgres will emit a String value that doesn't contain a comma for a range type? The documentation seems to suggest this will not happen, except for the case of `empty`, which is separately handled: https://www.postgresql.org/docs/current/rangetypes.html#RANGETYPES-IO

Is it obvious that the input will come from Postgres? I hit it during validation tests, where the field was set to a string by the test (simulating user input). At any rate, is it really something to rely on?
