### PR TITLE
Fix different `count` calculation when using `size` with DISTINCT `select`

### LINKED ISSUE #35214: [activerecord] DISTINCT in select being dropped when using size on the relation
### Steps to reproduce

```
Setting.select('DISTINCT key').size # select dropped
Setting.select('DISTINCT key').to_a.size # returns correct result
```

Same with `DISTINCT ON`:

```
Setting.select('DISTINCT ON (key) *').size
Setting.select('DISTINCT ON (key) *').to_a.size
```

Full test case: https://gist.github.com/cwardata/2db2f7364fb827d9906834a4182a873b

### Expected behavior

```
Setting.select('DISTINCT key').size
2
Setting.select('DISTINCT key').to_a.size
2
Setting.select('DISTINCT ON (key) *').size
2
Setting.select('DISTINCT ON(key) *').to_a.size
2
```

### Actual behavior

```
Setting.select('DISTINCT key').size
3
Setting.select('DISTINCT key').to_a.size
2
Setting.select('DISTINCT ON (key) *').size
3
Setting.select('DISTINCT ON(key) *').to_a.size
2
```

### System configuration

**Rails version**: latest from Github.

**Ruby version**: `ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin14]`

### PR DESCRIPTION
**Pull request by jvillarejo**
### Summary

When using `select` with `'DISTINCT( ... )'` if you use method `size` on a non loaded relation it overrides the column selected by passing `:all` so it returns different value than count. 

Fixes #35214

### CODE REVIEW

**Comment by kamipo** [comment]
This change also affects to `count(:all)`.
Can you add test case for `count(:all)` as well (e.g. ebc09ed9ad9a04338138739226a1a92c7a2707ee)?

**Comment by jvillarejo** [comment]
Thanks for your reply! Totally! I will add more tests cases.

**Comment by jvillarejo** [comment]
Hey @kamipo I added more test cases, as some of them didn't gave the correct original count value when reassigning the `column_name`. 

So in order to fix the issue and keep the functionality instead of changing the `column_name`, `distinct` is assigned with the `select_for_count` values. 

What do you think about this? 

Also I think the test cases about `size` shouldn't be on `test/cases/calculations_test.rb` file but inside `test/cases/relation` folder. Do you think that creating a file `test/cases/relation/size_test.rb` there would be a good approach? 

Thanks!

File: activerecord/lib/active_record/relation/calculations.rb [hunk 1]
```diff
@@ -234,12 +233,14 @@ def perform_calculation(operation, column_name)
         distinct = distinct_value
 
         if operation == "count"
+          distinct = select_for_count if distinct_select?(select_for_count)
+
           column_name ||= select_for_count
           if column_name == :all
             if distinct && (group_values.any? || select_values.empty? && order_values.empty?)
```
Comment (kamipo) [inline activerecord/lib/active_record/relation/calculations.rb]:
```diff
--- a/activerecord/lib/active_record/relation/calculations.rb
+++ b/activerecord/lib/active_record/relation/calculations.rb
@@ -233,10 +233,9 @@ def perform_calculation(operation, column_name)
         distinct = distinct_value

         if operation == "count"
-          distinct = select_for_count if distinct_select?(select_for_count)
-
           column_name ||= select_for_count
           if column_name == :all
+            distinct ||= distinct_select?(select_for_count)
             if distinct && (group_values.any? || select_values.empty? && order_values.empty?)
               column_name = primary_key
             end
```

File: activerecord/lib/active_record/relation/calculations.rb [hunk 2]
```diff
@@ -234,12 +233,14 @@ def perform_calculation(operation, column_name)
         distinct = distinct_value
 
         if operation == "count"
+          distinct = select_for_count if distinct_select?(select_for_count)
```
Comment (kamipo) [inline activerecord/lib/active_record/relation/calculations.rb]: Can you remove this line in favor of https://github.com/rails/rails/pull/35361#discussion_r259570692?

File: activerecord/test/cases/calculations_test.rb [hunk 3]
```diff
@@ -460,6 +460,44 @@ def test_should_count_manual_select_with_include
...
+  end
+
+  def test_size_with_distinct_with_loaded_size
+    size = Account.distinct(:firm_id).size
+    loaded_size = Account.distinct(:firm_id).load.size
+    assert_equal size, loaded_size
+  end
+
+  def test_size_with_manual_select_with_group_with
+    c = Account.select("DISTINCT accounts.firm_id").group("accounts.firm_id").size
```
Comment (kamipo) [inline activerecord/test/cases/calculations_test.rb]: This should return 5, since it should be the same result with `Account.select("DISTINCT accounts.firm_id").group("accounts.firm_id").load.size`.

File: activerecord/test/cases/calculations_test.rb [hunk 4]
```diff
@@ -460,6 +460,44 @@ def test_should_count_manual_select_with_include
...
+    assert_equal 5, Account.select("DISTINCT accounts.firm_id").count(:all)
+  end
+
+  def test_should_count_with_manual_distinct_select_and_distinct
+    assert_equal 4, Account.select("DISTINCT accounts.firm_id").distinct(:id).count
+  end
+
+  def test_should_count_manual_select_with_group_with_count_all
+    c = Account.select("DISTINCT accounts.firm_id").group("accounts.firm_id").count(:all)
+    assert_equal([[nil, 1], [1, 1], [2, 1], [6, 2], [9, 1]].to_h, c)
```
Comment (kamipo) [inline activerecord/test/cases/calculations_test.rb]: Don't use `.to_h`, but just a hash like here.

https://github.com/rails/rails/blob/1cf72affe0ac0c7dac557fe463d2153c758bf7af/activerecord/test/cases/calculations_test.rb#L765-L769

File: activerecord/test/cases/calculations_test.rb [hunk 5]
```diff
@@ -460,6 +460,44 @@ def test_should_count_manual_select_with_include
...
+  end
+
+  def test_size_manual_select_distinct
+    assert_equal 5, Account.select("DISTINCT accounts.firm_id").size
+  end
+
+  def test_size_with_manual_distinct_select_with_loaded_size
+    size = Account.select("DISTINCT accounts.firm_id").size
+    loaded_size = Account.select("DISTINCT accounts.firm_id").load.size
+    assert_equal size, loaded_size
```
Comment (kamipo) [inline activerecord/test/cases/calculations_test.rb]: > Also I think the test cases about `size` shouldn't be on `test/cases/calculations_test.rb` file

Yes, just put them in `test/cases/relations_test.rb` for now.

https://github.com/rails/rails/blob/be442ccd8342baf39e73b01a6fdd38e1a3b15c2c/activerecord/test/cases/relations_test.rb#L957-L973

File: activerecord/test/cases/calculations_test.rb (hunk 4 above)
Comment (jvillarejo) [reply activerecord/test/cases/calculations_test.rb]: I tried to use:
`{ nil => 1, 1 => 1, 2 => 1, 6 => 2, 9 => 1 }` 
But code climate threw errors

File: activerecord/test/cases/relations_test.rb [hunk 6]
```diff
@@ -935,6 +935,13 @@ def test_size_with_eager_loading_and_custom_order_and_distinct
     assert_queries(1) { assert_equal 11, posts.load.size }
   end
 
+  def test_size_with_eager_loading_and_manual_distinct_select_and_custom_order
+    accounts = Account.select("DISTINCT accounts.firm_id").order('accounts.firm_id')
```
Comment (kamipo) [inline activerecord/test/cases/relations_test.rb]: Use double quotes.

https://codeclimate.com/github/rails/rails/pull/35361

image

File: activerecord/test/cases/calculations_test.rb (hunk 3 above)
Comment (jvillarejo) [reply activerecord/test/cases/calculations_test.rb]: Somehow executing:
```ruby
Account.select("DISTINCT accounts.firm_id").group("accounts.firm_id").size
# { nil => 1, 1 => 1, 2 => 1, 6 => 2, 9 => 1 }
```
Now returns the hash. But I agree that it should return the same of: 
```ruby
Account.select("DISTINCT accounts.firm_id").group("accounts.firm_id").load.size
# 5
```
Should I investigate this for this PR ?

File: activerecord/test/cases/relations_test.rb (hunk 6 above)
Comment (jvillarejo) [reply activerecord/test/cases/relations_test.rb]: Woops sorry! :man_facepalming:

File: activerecord/lib/active_record/relation/calculations.rb (hunk 2 above)
Comment (jvillarejo) [reply activerecord/lib/active_record/relation/calculations.rb]: Done!

File: activerecord/test/cases/calculations_test.rb (hunk 5 above)
Comment (jvillarejo) [reply activerecord/test/cases/calculations_test.rb]: There is a weird situation added a test with `includes`:
```ruby
def test_size_with_eager_loading_and_manual_distinct_select_and_includes
  accounts = Account.select("DISTINCT accounts.firm_id").includes(:firm).order("firms.id")

  assert_queries(1) { assert_equal 5, accounts.size }
  assert_queries(1) { assert_equal 5, accounts.load.size }
end
```
It raises:
`# ActiveRecord::StatementInvalid: SQLite3::SQLException: near "DISTINCT": syntax error`
I can investigate further if you want. 

But this also gets raised when using:
```ruby
Account.distinct(:credit_limit).select("DISTINCT accounts.firm_id").count(:all)
# ActiveRecord::StatementInvalid: SQLite3::SQLException: near "DISTINCT": syntax error
```

What do you think about this?

File: activerecord/test/cases/calculations_test.rb (hunk 3 above)
Comment (kamipo) [reply activerecord/test/cases/calculations_test.rb]: Feel free to create another PR.

File: activerecord/test/cases/calculations_test.rb (hunk 5 above)
Comment (kamipo) [reply activerecord/test/cases/calculations_test.rb]: This is an issue for `count` with eager loading.
I'd prefer to address it in another PR, since it is a little complex than what this PR fixes.

File: activerecord/test/cases/calculations_test.rb (hunk 3 above)
Comment (localhostdotdev) [reply activerecord/test/cases/calculations_test.rb]: As an user, I expect `.group.size` (same as `.group.count`) to return an hash. And doing `.load.size` / `to_a.size` would return a collection of the instances of the model and then how many of them there are.

Comment (kamipo) [reply activerecord/test/cases/calculations_test.rb]: Originally, `relation.size` behaves fragile, that is a breaking change though.

```ruby
relation = Post.left_joins(:comments).group(:id)
relation.size # => return a hash
relation.each { |record| puts record.id }
relation.size # => return an integer

relation = Post.left_joins(:comments).group(:id)
relation.count # => return a hash
relation.each { |record| puts record.id }
relation.count # => return a hash

relation = Post.left_joins(:comments).group(:id)
relation.length # => return an integer
relation.each { |record| puts record.id }
relation.length # => return an integer
```

File: activerecord/test/cases/calculations_test.rb (hunk 5 above)
Comment (jvillarejo) [reply activerecord/test/cases/calculations_test.rb]: Ok I'll work it in another PR!

**Review by kamipo — APPROVED** [review]
Looks good to me.
Can you add changelog entry and squash your commits into one?

File: activerecord/test/cases/calculations_test.rb (hunk 3 above)
Comment (jvillarejo) [reply activerecord/test/cases/calculations_test.rb]: But in my opinion `size` and `load.size` should have the same return value the difference should be that when using just `size` if the collection is loaded it will not execute a query but if it isn't it executes a query without loading the collection instances. 

That they return different values when the collection is loaded and when it isn't is confusing.

**Comment by jvillarejo** [comment]
Done! This is my first Rails PR :smile:. Is it correct?

**Comment by kamipo** [comment]
Thanks! And congrats on your first Rails contribution 🎉
