### PR TITLE
Only remove connection for an existing pool if the config is different

### LINKED ISSUE #41855: Connection closed during migrations under certain circumstances
MVCE: https://github.com/joshleblanc/sharding-migrations-bug

### Steps to reproduce

Create a new rails application

Create a sharded database with 

```yml
# database.yml
development:
  default:
    database: default
  archive:
    database: archive
```

```ruby
# application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to shards: {
    default: {writing: :default, reading: :default},
    archive: {writing: :archive, reading: :archive}
  }
end
```

Create any model, then add a second migration that queries the database using the model, then runs an `execute` statement.

```ruby
class ThisShouldBreak < ActiveRecord::Migration[6.0]
  def up
    Author.count
    execute "SELECT * from authors"
  end

  def down
    # no-op
  end
end
```

### Expected behavior

The migration should run

### Actual behavior

The connection is closed during the migration, triggering a rollback.

### System configuration
**Rails version**: Rails 6.1.3.1

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]

### LINKED ISSUE #41876: `prepare called on a closed database` when accessing ActiveRecord objects whilst using multiple databases
### Steps to reproduce

1. Have a rails codebase with multiple databases according to [this](https://guides.rubyonrails.org/active_record_multiple_databases.html#setting-up-your-application) - replicated on a [new rails codebase](https://github.com/mtcmorris/multi-db-migration-issue/commit/7900c2b2fa70113d0d512249bef8c53a3e10255f)

2. Write a migration than accesses an ActiveRecord object

```ruby
class TestMigrationIssue < ActiveRecord::Migration[6.1]
  def change
    add_column :boats, :name, :string

    # Any ActiveRecord query on any model will cause this issue
    Boat.update(name: "Something")

    change_column_null :boats, :name, false
  end
end
```

3. Run `bundle exec rails db:migrate:primary`

### Expected behavior

Migration should complete

### Actual behavior

```
== 20210408060158 TestMigrationIssue: migrating ===============================
-- add_column(:boats, :name, :string)
   -> 0.0018s
-- change_column_null(:boats, :name, false)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

prepare called on a closed database
vendor/bundle/ruby/2.7.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `initialize'
vendor/bundle/ruby/2.7.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `new'
vendor/bundle/ruby/2.7.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `prepare'
vendor/bundle/ruby/2.7.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:193:in `execute'
vendor/bundle/ruby/2.7.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:659:in `rollback'
```

The database is closed (`change_column_null`) fails.

pg adapter has the same issue

### System configuration
**Rails version**: 6.1.3.1

**Ruby version**: 2.7.2

### LINKED ISSUE #42873: Horizontal sharding & migration with data changing script
Hello folks and @eileencodes 

I was trying the Horizontal sharding and couldn't go through this. Thanks for your job anyway 👍 

### Steps to reproduce
``` shell
git clone https://github.com/alpracka/sharding_migrations
cd sharding_migrations && bundle
bin/rails db:create
bin/rails db:migrate
```

### Expected behavior
Migrations should be finished on all databases.

### Actual behavior
Migration with data changing script is not finished and goes to zombie mode.

Few notes:
- No matter if the script is written like reversible block or def up/down methods.
- PostgreSQL:
It just hangs out like on the gif below.
- SQLite:
It seems to work **but** doesn't work if there are some records in the database. But it seems to be a different issue as `reset_column_information` doesn't work in this case 🤷‍♂️.
- MySQL:
All migrations are finished **but** the data changing script is performed only on the primary database because all Animal records in the primary_shard_one database have nil value of the attribute `lives`.

### System configuration
**Rails version**: 6.1.4 (I also tried the main branch with same results)

**Ruby version**: 3.0.1

alt text

### LINKED ISSUE #43004: Horizontal sharding & migration with data changing script (symlink)
I believe this [issue](https://github.com/rails/rails/issues/42873) should be reopened.

### PR DESCRIPTION
**Pull request by eileencodes**
Previously Rails would always remove the connection if it found a
matching class in the pool manager. Therefore if
`ActiveRecord::Base.establish_connection` was called with the same
config, each time it was called it would be clobbered, even though the
config hasn't changed and the existing connection is prefectly fine. As
far as I can tell from conversations and reading the history this
functionality was added for ActiveRecord tests to be able to clobber the
connection and use a new config, then re-establish the old connection.
Essentially outside Rake tasks and AR tests, this functionality doesn't
have a ton of value.

On top of not adding a ton of value, this has resulted in a few bugs. In
Rails 6.0 I made it so that if you established a connection on
`ApplicationRecord` Rails would treat that connection the same as
`ActiveRecord::Base.` The reason for this is that the Railtie
establishes a connection on boot to the first database, but then if
you're using multiple databases you're calling `connects_to` in your
`ApplicationRecord` or primary abstract class which essentially doubles
your connections to the same database. To avoid opening 2 connections to
the same database, Rails treats them the same.

However, because we have this code that removes existing connections,
when an application boots, `ApplicationRecord` will clobber the
connection that the Railtie established even though the connection
configs are the same.

This removal of the connection caused bugs in migrations that load up a
model connected to `ApplicationRecord` (ex `Post.first`) and then calls
`execute("SELECT 1")` (obviously a simplified example). When `execute`
runs the connection is different from the one opened to run the
migration and essentially it is lost when the `remove_connection` code
is called.

To fix this I've updated the code to only remove the connection if the
database config is different. Ultimately I'd like to remove this code
altogether but to do that we first need to stop using
`Base.establish_connection` in the rake tasks and tests. This will fix
the major bugs until I come up with a solution for the areas that
currently need to call `establish_connection` on Base.

The added benefit of this change is that if your app is calling
`establish_connection` multiple times with the same config, it is now
3x faster than the previous implementation because we can return the
found pool instead of setting it up again. To benchmark this I
duplicated the `establish_connection` method to use the new behavior
with a new name.

Benchmark script:

```ruby
require "active_record"
require "logger"
require "benchmark/ips"

config_hash = { "development" => { "primary" => { "adapter" => "mysql2", "username" => "rails", "database" => "activerecord_unittest"}}}
ActiveRecord::Base.configurations = config_hash

db_config = ActiveRecord::Base.configurations.configs_for(env_name: "development", name: "primary")

ActiveRecord::Base.connected_to(role: :writing, prevent_writes: true) do
  Benchmark.ips do |x|
    x.report "establish_connection with remove" do
      ActiveRecord::Base.establish_connection(db_config)
    end

    x.report "establish_connection without remove" do
      ActiveRecord::Base.establish_connection_no_remove(db_config)
    end

    x.compare!
  end
end
```

Benchmark results:

    
```
Warming up --------------------------------------
establish_connection with remove
                            4.677k i/100ms
establish_connection without remove
                        19.501k i/100ms
Calculating -------------------------------------
establish_connection with remove
                            41.252k (±11.3%) i/s -    205.788k in   5.075525s
establish_connection without remove
                        179.205k (± 6.9%) i/s -    897.046k in   5.029742s

Comparison:
establish_connection without remove:   179205.1 i/s
establish_connection with remove:    41252.3 i/s - 4.34x  (± 0.00) slower
```

Other changes:

1) sqlite3 now disconnects and reconnects the connection when `purge` is
called. This is necessary now that a new connection isn't created
everyt time `establish_connection` is called. Without this change to
purge the new database is left in an inaccessible state causing a
readonly error from the sqlite3 client. This wasn't happening in mysql
or postgres because they were already reconnecting the db connection.
2) I added `remove_connection` to tests that use `ApplicationRecord`.
This is required because `ApplicationRecord` or any class that is a
`primary_abstract_class` will be treated the same as
`ActiveRecord::Base`. This is fine in applications because they are
shared connections, but in the AR test environment, we don't want those
connnections to stick around (we want AR::Base back).
3) In the async tests I removed 2 calls to `establish_connection`. These
were causing sqlite3 tests to leak the state of async_executor because
it's stored on the connection. I'm not sure why these were calling
`establish_connection` but it's not necessary and was leaking state when
now that we are no longer removing the connection.

Fixes: #41855
Fixes: #41876
Fixes: #42873
Fixes: #43004

cc/ @matthewd as we talked about this today.

### CODE REVIEW

**Comment by eileencodes** [comment]
This has a change of behavior in that if you used to depend on `establish_connection` to remove an existing connection that's identical to the one you're establishing, it no longer is removed. This would avoid a `database closed` error but I can't imagine why you'd want this functionality. If applications really want to remove connections before establishing, then I think they should do that explicitly.

File: activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb [hunk 1]
```diff
@@ -103,30 +103,32 @@ def connection_pool_list(role = ActiveRecord::Base.current_role)
...
-        # Protects the connection named `ActiveRecord::Base` from being removed
-        # if the user calls `establish_connection :primary`.
-        if owner_to_pool_manager.key?(pool_config.connection_specification_name)
+        # If there is an existing pool with the same values as the pool_config
+        # don't remove the connection. Connections should only be removed if we are
+        # establishing a connection on a class that is already connected to a different
+        # configuration.
+        pool = retrieve_connection_pool(pool_config.connection_specification_name, role: role, shard: shard)
+
+        unless pool && pool.db_config == db_config
```
Comment (matthewd) [inline activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:115]: Does this retain the `ActiveRecord::Base` / `:primary` protection mentioned in the above-removed comment? (Assuming we need to)

File: activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb [hunk 2]
```diff
@@ -103,30 +103,32 @@ def connection_pool_list(role = ActiveRecord::Base.current_role)
...
-        pool_manager.set_pool_config(role, shard, pool_config)
+        payload = {
+          spec_name: pool_config.connection_specification_name,
+          shard: shard,
+          config: db_config.configuration_hash
+        }
 
-        message_bus.instrument("!connection.active_record", payload) do
-          pool_config.pool
+        ActiveSupport::Notifications.instrumenter.instrument("!connection.active_record", payload) do
```
Comment (matthewd) [inline activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:130]: It's unlikely to matter either way in practice (mostly because the whole point of being okay with changing this is that we don't think real people are doing widespread same-config re-establishment in the first place), but I feel like we should only do this if the call had an effect.

**Review by matthewd — APPROVED** [review]
Just to write out the words: we _could_ deprecate this behaviour... but I don't feel like that's necessary. 

In general I don't see this as an API-observable behaviour change: whether a subsequently-checked-out connection comes from a fresh pool or one that already existed is immaterial to the caller. I think you'd need to be doing something notably odd to detect the difference; and correspondingly there isn't a good way for a caller to respond to a deprecation... adding their own `if` to avoid calling `establish_connection` if the new and existing configs match would be ugly, ultimately pointless, and force them to interact with much lower-level APIs than they were before.

File: activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb (hunk 2 above)
Comment (eileencodes) [reply activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:130]: Yea I was on the fence about this. My first implementation didn't instrument but then I wasn't sure if someone still wanted to know that establish_connection was called. Removing it makes an existing pool 4x faster than the prior behavior.

File: activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb (hunk 1 above)
Comment (eileencodes) [reply activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:115]: That was for when we were deprecating primary as a name for ActiveRecord::Base and since that's been deprecated and removed I think we no longer need this. I wrote the original comment and went back to the original PR to verify that.

File: activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb (hunk 2 above)
Comment (eileencodes) [reply activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:130]: I'm leaving this in place for now. I made a refactor that skipped and included other changes when we have a pool, but that refactor resulted in a mysql2 test run with a bunch of flakes I couldn't reproduce locally. I'm going to do that refactor in a followup PR so I can more easily isolate what's going on there from the other fixes here.

File: activerecord/lib/active_record/tasks/sqlite_database_tasks.rb [hunk 3]
```diff
@@ -33,9 +33,11 @@ def drop
 
       def purge
         drop
+        connection.disconnect!
       rescue NoDatabaseError
       ensure
         create
+        connection.reconnect!
```
Comment (eileencodes) [inline activerecord/lib/active_record/tasks/sqlite_database_tasks.rb:40]: Action Mailbox and other related libraries are relying on loading the schema before test runs via `db:test:prepare` which calls `db:schema:load` which calls `db:purge`. With the changes in connection management we no longer are re-establishing the connection so anything that called purge would fail with a sqlite3 error. I noticed that this behavior was not reproducible in mysql2 and found that the `purge` method there reconnects to the new database. I implemented that same behavior in `purge` here. Previously this was working "fine" because we were always removing the connection even if it was the same. Now that we're not removing the connection we want to reset it so we don't have a bad connection.

File: activerecord/test/cases/primary_class_test.rb [hunk 4]
```diff
@@ -110,6 +110,7 @@ def test_application_record_shares_a_connection_with_active_record_by_default
       assert_predicate ApplicationRecord, :application_record_class?
       assert_equal ActiveRecord::Base.connection, ApplicationRecord.connection
     ensure
+      ApplicationRecord.remove_connection
```
Comment (eileencodes) [inline activerecord/test/cases/primary_class_test.rb:113]: Rails apps treat `ApplicationRecord` OR the class named `primary_abstract_class` (example below) the same as `ActiveRecord::Base` in order to avoid opening duplicate connections to the same database. In a real app we want these connections to be shared and if `ApplicationRecord.establish_connection` is called it shouldn't replace  or duplicate `ActiveRecord::Base`.

However, in the AR tests we don't actually want `ApplicationRecord` shared with `ActiveRecord::Base` beyond these tests so we need to remove the connection when the test is complete. Previously `establish_connection` was handling this for us, but now we need to do it explicitly. In an app these would actually be shared, but in our tests we don't want to share this global state.

File: activerecord/test/cases/relation/load_async_test.rb [hunk 5]
```diff
@@ -231,12 +231,10 @@ class LoadAsyncNullExecutorTest < ActiveRecord::TestCase
       def setup
         @old_config = ActiveRecord.async_query_executor
         ActiveRecord.async_query_executor = nil
-        ActiveRecord::Base.establish_connection :arunit
```
Comment (eileencodes) [inline activerecord/test/cases/relation/load_async_test.rb:234]: I removed these because I found that the sqlite3 async tests were failing with some seeds and my changes. After debugging I found that the connection that was opened had `asycn_query_executor` set to `nil` rather than the global executor default. I don't know why these tests were re-establishing a connection, there would be one in the pool to pick up. Removing this fixed the tests that incorrectly had the wrong query executor. I believe this works because it will open a new connection for both tests (there wont be one in the pool). Previously calling `establish_connection` was ensuring there was an existing pool (with async executor set to nil) but we don't want to use that one so it's better not to establish a connection at all.

**Review by eileencodes — COMMENTED** [review]
I've solved all the failures in the sqlite3 tests. I've left comments on all the changes and why I made the changes I did.

CC'ing a few before merge - let me know if you think this change is problematic. The TL;DR is that if we have an existing pool with the same config, role and shard, AR no longer removes the connection and creates a new one, it simply returns the existing connection. If apps want to clobber an existing connection with a new config that still works the same as before. I've only changed behavior for calling `establish_connection` when the pool already exists. This change fixes some bugs in migrations when the connection goes away (because connects_to was called) and the migration expects it to be there (via execute).

cc/ @byroot @matthewd @jhawthorn @tenderlove

**Comment by eileencodes** [comment]
I'm going to merge this mainly because I need to make more changes and don't want to deal with conflicts. If anyone has an objection please let me know and I will revert.

File: activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb (hunk 2 above)
Comment (rafaelfranca) [reply activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:130]: Our own code inside fixtures consume this instrumentation, but this instrumentation is private (that is why it starts with `!`) so people should not be using.

Comment (eileencodes) [reply activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:130]: Oh good to know, I want to change the keys in a followup PR anyway so I'll hopefully get rid of it then.
