### PR TITLE
Fix host display when X_FORWARDED_HOST authorized

### LINKED ISSUE #40230: HostAuthorization: confusing error message when using multiple hostnames
### Steps to reproduce
Calling the application with different values for `HTTP_HOST` and `HTTP_X_FORWARDED_HOST` while HostAuthorization is enabled (i.e. `config.hosts` is set/active) while at least HTTP_HOST is **not** present in `config.hosts`.

### Expected behavior
Error message that displays the user that both hostnames are checked and need to be added to `config.hosts`.

Example:
```
Blocked hosts: HTTP_HOST, HTTP_X_FORWARDED_HOST
---------------------------------------------------------------------------------------------
To allow requests to HTTP_HOST, HTTP_X_FORWARDED_HOST, add the following to your environment configuration:
config.hosts << "HTTP_HOST"
config.hosts << "HTTP_X_FORWARDED_HOST"
```

### Actual behavior
Output
```
Blocked host: HTTP_X_FORWARDED_HOST
---------------------------------------------------------------------------------------------
To allow requests to HTTP_X_FORWARDED_HOST, add the following to your environment configuration:
config.hosts << "HTTP_X_FORWARDED_HOST"
```

If you then add `HTTP_X_FORWARDED_HOST` to `config.hosts` the error message is still displayed (unchanged) if HTTP_HOST is missing.

### System configuration
**Rails version**: 6.0.3.3 (should be present since introduction of HostAuthorization in v6.0.0.beta1)

**Ruby version**: any

I created a commit that changes / fixes that behavior ([See here](https://github.com/Eusebius1920/rails/commit/c63f7b07fd47651708bd4ce4ca8dd6106537d68f)) in a forked repository. I can create a pull request if needed / wanted.

**Edit**: Fixed wrong header name in issue description

### PR DESCRIPTION
**Pull request by skipkayhil**
### Motivation / Background

Previously, when a Request had a non-authorized HTTP_HOST but an authorized HTTP_X_FORWARDED_HOST, the HTTP_X_FORWARDED_HOST value would be displayed as the one being blocked. However, this could be confusing for users since that value would already be added to `config.hosts`.

### Detail

This commit addresses the issue by tweaking how the blocked host is displayed. Instead of always displaying Request#host (which will return X_FORWARDED_HOST when present whether or not that's the host being blocked), each host being blocked will be displayed on its own.

### Additional information

Fixes #40230
Supercedes #46158

cc @Eusebius1920 I added you as a coauthor for your work on the previous PR

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: actionpack/test/dispatch/host_authorization_test.rb [hunk 1]
```diff
@@ -284,7 +284,7 @@ class HostAuthorizationTest < ActionDispatch::IntegrationTest
     }
 
     assert_response :forbidden
-    assert_match "Blocked host: 127.0.0.1", response.body
+    assert_match "Blocked hosts: www.example.com", response.body
```
Comment (skipkayhil) [inline actionpack/test/dispatch/host_authorization_test.rb:287]: This and the other test change demonstrate the issue: the displayed blocked host previously would be HTTP_X_FORWARDED_HOST even though that value was already added to `config.hosts`. The correct value here should be HTTP_HOST
