### PR TITLE
Fix query cache for pinned connections in multi threaded transactional tests

### LINKED ISSUE #55689: Query cache does not work in system tests in Rails 7.2+
### Steps to reproduce

At GitLab, we are upgrading to Rails 7.2 and noticed that all our requests made from system specs were no longer using the query cache.

I dug into the code and found the query cache refactor in https://github.com/rails/rails/commit/85742ce529b028812066cd6070e7de2ff3d44bc8 and other subsequent changes related to that.

Based on that, the pool now owns the caches and it keeps a set of cache stores per thread. Now the problem happens when there is a pinned connection.

Here's the sequence of events:

1. RSpec thread checks out a connection and sets `connection.query_cache` to a new cache store based on the current thread. This connection is then pinned. The cache store for this connection and pool is disabled.
2. RSpec thread makes a web request to Puma
3. Puma processes the request and the Rails executor hook enables the query cache on a new cache store based on the Puma thread.
4. Puma thread checks out a connection and gets the same pinned connection. `checkout_and_verify` is not called in this code path so `connection.query_cache` still points to the cache store owned by the RSpec thread.
 
   This cache store isn't the one enabled by the executor hook so this request does not use the query cache. 

### System configuration

**Rails version**: 7.2

**Ruby version**: 3.3.9

### PR DESCRIPTION
**Pull request by byroot**
Fix: https://github.com/rails/rails/issues/55689
Fix: https://github.com/rails/rails/pull/55696

When a pinned connection is used across separate threads, each thread should have its own query cache store.

@engwan

### CODE REVIEW

File: activerecord/test/cases/query_cache_test.rb [hunk 1]
```diff
@@ -323,17 +322,16 @@ def test_query_cache_across_threads
...
         started.wait
 
         thread_1_connection = ActiveRecord::Base.lease_connection
         assert_not_equal thread_1_connection, thread_2_connection
-        assert_cache :dirty, thread_2_connection
         checked.set
         thread.join
-
-        assert_cache :off, thread_2_connection
       }.call({})
```
Comment (engwan) [inline activerecord/test/cases/query_cache_test.rb]: Since the new behavior only applies to pinned connections, we can actually restore this test to what it was and it should still pass.

Though I guess this is also fine.

**Review by engwan — COMMENTED** [review]
Thanks @byroot. I think this looks good.

Just a small comment regarding the test.

File: activerecord/test/cases/query_cache_test.rb (hunk 1 above)
Comment (byroot) [reply activerecord/test/cases/query_cache_test.rb]: Ah nice. Good catch.

**Comment by byroot** [comment]
Probably should backport this to 8-0 and 7-2.
