### PR TITLE
Quote empty ranges like other empty enumerables

### LINKED ISSUE #35135: ActiveRecord generates invalid SQL string for empty range array condition
### Steps to reproduce

When constructing an ActiveRecord statement using an [Array Condition](https://edgeguides.rubyonrails.org/active_record_querying.html#array-conditions), ActiveRecord generates an invalid SQL string when the condition is an empty range (i.e. `0...0`).

As an example: `Post.where('id = ?', 0...0)`

The error raised is `ActiveRecord::StatementInvalid: SQLite3::SQLException: near ")": syntax error`, but I've confirmed this occurs on both SQLite and PostgreSQL.

Here's a project template to reproduce the issue:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_empty_range
    Post.create!

    assert_equal 1, Post.all.count

    # SQL generated is:
    # SELECT "posts".* FROM "posts" WHERE "posts"."id" BETWEEN 0 AND 0
    # This appropriately resolves to an empty ActiveRecord Relation
    assert_equal 0, Post.where(id: 0..0).count

    # SQL generated is:
    # SELECT "posts".* SELECT "posts".* FROM "posts" WHERE "posts"."id" >= 0 AND "posts"."id" < 0
    # This appropriately resolves to an empty ActiveRecord Relation
    assert_equal 0, Post.where(id: 0...0).count

    # SQL generated is
    # SELECT "posts".* FROM "posts" WHERE (id in (0))
    # This appropriately resolves to an empty ActiveRecord Relation
    assert_equal 0, Post.where('id in (?)', 0..0).count

    # SQL generated is
    # SELECT "posts".* FROM "posts" WHERE (id in ())
    # This appropriately resolves to an empty ActiveRecord Relation
    assert_equal 0, Post.where('id in (?)', 0...0).count

    # SQL generated is
    # SELECT "posts".* FROM "posts" WHERE (id = 0)
    # This appropriately resolves to an empty ActiveRecord Relation
    assert_equal 0, Post.where('id = ?', 0..0).count

    # This is the line that throws an ActiveRecord::StatementInvalid error
    # SQL generated is SELECT "posts".* FROM "posts" WHERE (id = )
    # !!! This raises an ActiveRecord::StatementInvalid error !!!
    assert_equal 0, Post.where('id = ?', 0...0).count
  end
end
```
I've noted the behavior for other statements involving ranges, all of which resolve to a valid SQL statement.

### Expected behavior

A where array condition using an empty array should return an empty ActiveRecord relation, as no value can resolve to a range with zero values.

### Actual behavior

ActiveRecord raises an `ActiveRecord::StatementInvalid` error

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.1

### PR DESCRIPTION
**Pull request by pjrebsch**
Resolves #35135.

Fixes the case where an empty range is provided as a bind variable. Active Record tried to map and join the range's items' quoted values, so when the range was empty, the resulting string would be empty which would often result in an invalid SQL statement.

There was a check in place to try to handle empty enumerables, but it only checked if the value responded to `empty?`, and since a `Range` doesn't have that method, the quoting method assumed that it wasn't empty and proceed to map it and use the result.

This fixes the problem by mapping first and then checking if the result is `empty?` since at that point it should always be an array.<sup>[[Thanks!]](https://github.com/rails/rails/pull/35449#pullrequestreview-211024151)</sup>

### CODE REVIEW

File: activerecord/lib/active_record/sanitization.rb [hunk 1]
```diff
@@ -165,7 +165,9 @@ def replace_named_bind_variables(statement, bind_vars)
 
         def quote_bound_value(value, c = connection)
           if value.respond_to?(:map) && !value.acts_like?(:string)
-            if value.respond_to?(:empty?) && value.empty?
+            is_empty = (value.respond_to?(:empty?) && value.empty?) ||
+              (value.is_a?(Range) && value.none?)
```
Comment (matthewd) [inline activerecord/lib/active_record/sanitization.rb]: Instead of adding an extra special-case for Range, how about we move the `empty?` check to after the `map` -- at that point we know it's an array, so it's safe to call.

That way we'll fix the problem for all enumerables, and not just go from (ones that support `empty?`) to ((ones that support `empty?`) + `Range`).

```ruby
quoted = value.map { |v| c.quote(v) }
if quoted.empty?
  c.quote(nil)
else
  quoted.join(",")
end
```

Comment (pjrebsch) [reply activerecord/lib/active_record/sanitization.rb]: Yep, that's a better approach. I'll make your proposed change and rebase.

**Comment by kamipo** [comment]
Thanks!
