### PR TITLE
Strip final newline from Action View renders

### LINKED ISSUE #42201: Final newline rendered in partials
### Steps to reproduce

See [test repo](https://github.com/boardfish/view_component-bug). `bundle && rails s`, then navigate to localhost:3000.

The test repo has a partial that renders an anchor tag. The file ends with a newline, which is commonly established as a standard.

Identified in github/view_component#913. It's worth checking out that issue and the linked PR for some further insight.

### Expected behavior

The following should be rendered:

```html
<p>
  <a href="https://simon.fish">Add Test template here</a>, <a href="https://simon.fish">Add Test template here</a>, and also <a href="https://simon.fish">Add Test template here</a>
</p>
```

### Actual behavior

The following is rendered:

```html
<p>
  <a href="https://simon.fish">Add Test template here</a>
, <a href="https://simon.fish">Add Test template here</a>
, and also
  <a href="https://simon.fish">Add Test template here</a>
</p>
```

The newlines introduced by `render` appear as a singular space before the commas in the first two instances. It renders like this:

Screen Shot 2021-05-12 at 13 52 09

I'm aware that `<%= -%>` is expected to strip trailing whitespace, but it doesn't appear to do so when rendering partials or ViewComponents. I figure this is most likely an ActionView-specific problem.

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.7.2p137

### PR DESCRIPTION
**Pull request by boardfish**
### Summary

Closes #42201

Introduces the `strip_trailing_newlines` option to `ActionView::Template::Handlers::ERB`, which removes trailing newlines from rendered output. This means that partials can be rendered inline without introducing additional whitespace to the output, which affects how the browser may render it.

### Other Information

To save you recapping those issues, ending files with a newline is something of a standard, as explained by [this StackOverflow thread's answers](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file). We lint for this @raisedevs. Ordinarily, it doesn't introduce problems, but Rails renders trailing newlines, which are interpreted by the browser as whitespace. So when a partial is rendered inline with other text, the newlines cause a space between the rendered partial and the next character.

I think it should be the default that trailing newlines are stripped, and I'm not sure it'd be harmful to introduce that. But I've kept `false` as the default because that's how things are now.

<details>
<summary>Some questions I had while writing this</summary>

:wave: This is my first contribution to Rails, so I've tried to be meticulous about it. But there are a few questions I have around this:

- ~~I imagine the config option might have a place in the documentation, so I'll look to update this if that's correct.~~ Added to the Guides.
- I'm not 100% confident that this is the best implementation. It achieves what I want it to, but I don't know if it's better placed in `ActionView::Template::Handlers`.
- I'm also not sure if my test is in the right part of the suite.
- As mentioned back over on the issue, this doesn't also resolve github/view_component#913. Assuming that library still uses `render_in`, it might be possible to fix that, but whether that's even Action View's responsibility is another story entirely.
</details

Thanks in advance for checking this out, folks.

### CODE REVIEW

**Comment by zzak** [comment]
@boardfish Nice work! I think we probably want to add a changelog, but since we're defaulting to the current behavior I think this is a reasonable approach.

**Comment by zzak** [comment]
> I imagine the config option might have a place in the documentation, so I'll look to update this if that's correct.

🤔 I'm not sure but maybe looking at similar config options (and their origin) will give us a good idea of requirements.

> I'm not 100% confident that this is the best implementation. It achieves what I want it to, but I don't know if it's better placed in ActionView::Template::Handlers.

I'm also not familiar enough here to make a firm decision, but @jhawthorn may be a good person to ask.

> I'm also not sure if my test is in the right part of the suite.

Here too.

> As mentioned back over on the issue, this doesn't also resolve github/view_component#913. Assuming that library still uses render_in, it might be possible to fix that, but whether that's even Action View's responsibility is another story entirely.

This seems we would at least be providing a path forward for them to use in a future release? Correct me if I'm wrong but it seems there is nothing on Rails side to do here.

**Comment by boardfish** [comment]
RE documentation, I'll do some digging. I think the fact that the option is commented and in the config files is sufficient, but it wouldn't hurt to be sure.

> This seems we would at least be providing a path forward for them to use in a future release? Correct me if I'm wrong but it seems there is nothing on Rails side to do here.

I guess the real question is whether this config option should affect the output of `render_in` too, or whether that should be the responsibility of the object that implements it.

**Comment by zzak** [comment]
> I guess the real question is whether this config option should affect the output of render_in too, or whether that should be the responsibility of the object that implements it.

I see that [render](https://api.rubyonrails.org/v6.1.3/classes/ActionController/Renderer.html#method-i-render) mentions this method but I've never actually seen it used:

> If an object responding to render_in is passed, render_in is called on the object, passing in the current view context.
> Otherwise, a partial is rendered using the second parameter as the locals hash.

Could you show me an example? It looks like it's up to the Object which implements this method to define that behavior.

**Comment by boardfish** [comment]
`render_in` is quite new. I seem to remember it was merged in to Rails to help enable ViewComponent to work more seamlessly. 

Having had a look in the ViewComponent codebase, `render_in` seems to be what outputs the compiled template to a string. Its job is to use the view context (if necessary) and output something as a string so that Action View can add it to the view. `render_in` can output a HTML-safe string.

I don't feel we should make a change to `render_in` itself to strip trailing newlines - it's the responsibility of the object to handle that output. But if we strip trailing newlines before the result of `render_in` is added to the template, then that's very clearly in Action View territory and it's more justifiable for the config option to control that output. I'm still on the fence as to whether we should do that at all, though — should it be the responsibility of the object with `render_in` to strip its own trailing newlines?

**Comment by boardfish** [comment]
Documentation for this should probably be added to the section on [Configuring Action View](https://guides.rubyonrails.org/configuring.html#configuring-action-view) in the Rails guides.

**Comment by boardfish** [comment]
I've realized a potential flaw in what I've got here - I'm not sure the option should be commented out in the environment-specific config. I imagine folks would typically set this option in `config/application.rb`.

**Comment by zzak** [comment]
@boardfish w/r/t where to put the config I'm not sure, but I think `config/app` makes sense (you probably won't be changing render behavior between environments).

Going back to what you said about `render_in`, I think it makes sense to assume the object defining this method will decide what to do with newlines.

**Comment by boardfish** [comment]
Sounds good. I'll make that change and then this ought to be ready for wider review.

**Comment by boardfish** [comment]
There we go!

**Review by zzak — APPROVED** [review]
LGTM, I think you may need to squash your commits but that can also wait until after some closer review

**Comment by jhawthorn** [comment]
@boardfish thank you for the thoughtful PR and description of the issue ✨.

> I think it should be the default that trailing newlines are stripped, and I'm not sure it'd be harmful to introduce that. But I've kept false as the default because that's how things are now.

I think I agree. It would be nice if we could avoid extraneous, unintentional whitespace by default.

One question I have is whether there are cases we'd want to keep that whitespace. For example, we probably want a newline at the end of the full document (ie. usually the layout) we should probably have a newline to meet that same "text file" standard 😅.

Another case might be when using, say, `render collection: `, newlines would be more readable (but I'm not 100% convinced either way on this one).

> I'm not 100% confident that this is the best implementation. It achieves what I want it to, but I don't know if it's better placed in ActionView::Template::Handlers.

Yeah. My biggest concern with this currently is where we call `@body.chomp`, body isn't a string, it's an OutputBuffer. Calling chomp will remove its html-safety (if you turn this on by default you should see many tests fail on escaping). We should also not expect that method to be available on the output buffer (it isn't if streaming) and we shouldn't try to modify it.

I feel like this might make more sense to implement as part of the ERB (Erubi) handler. I'd argue the "extra" newline is a detail of ERB's syntax (that its source forms the output), and trailing newlines from many other handlers (`.builder`, `.ruby`) are intentional. It _might_ be possible to call `chomp` on the ERB source... (but I haven't tested 😅)?

**Comment by boardfish** [comment]
Thanks for checking this out, @jhawthorn. I'll investigate dealing with this at the ERB level tomorrow. To answer some of your concerns:

- I think a newline after each partial in a `render collection:` might be reasonable, if only because there are alternatives to setting `display: inline` on each element, such as rendering inside a flex container. 
- I'm less confident about a newline at the end of a HTTP response, but it's worth investigation. 

Other template handlers might also require this change, but I'm not sure that should be within the remit of this PR. I can handle those in further PRs, which should be a lot easier if the solution for ERB can be defined in this one. 

It'd help me to know which tests to keep an eye on to make sure escaping is still safe.

**Comment by boardfish** [comment]
Okay, I've moved it to where I think makes sense, though I'm aware it doesn't have consideration for those edge cases at present. I was also curious about this:

> Calling chomp will remove its html-safety (if you turn this on by default you should see many tests fail on escaping).

Where were you able to do this? Hopefully with the change being where it is now, this shouldn't be a problem, but it'd be helpful to know how to check this out.

Also, when it comes to squashing my commits, I suppose it'd be best to squash them into one, right?

**Comment by zzak** [comment]
> Also, when it comes to squashing my commits, I suppose it'd be best to squash them into one, right?

@boardfish Yeh generally you will be asked to do this once the PR is approved (perhaps verbally first).

It sounds like the remaining question is how this affects the html-safety behavior? Should we just make it default and run the tests to verify that?

Do we still have to worry about non-Erb templates, e.g. builder being an issue here?

**Comment by boardfish** [comment]
> Should we just make it default and run the tests to verify that?

I've given this a shot just now. I didn't investigate the test output super thoroughly, but in all the cases I saw, failures only ever arose because a newline was part of the test expectation.

> Do we still have to worry about non-ERB templates, e.g. builder being an issue here?

This code theoretically shouldn't interfere with any other templates now. If a similar change needs to be introduced for other template types, I think that can be done separately.

File: actionview/lib/action_view/template/handlers/erb.rb [hunk 1]
```diff
@@ -45,6 +45,9 @@ def call(template, source)
           # Always make sure we return a String in the default_internal
           erb.encode!
 
+          # Strip trailing newlines from the template if enabled
+          erb.chomp! if ActionView::Base.strip_trailing_newlines
```
Comment (jhawthorn) [inline actionview/lib/action_view/template/handlers/erb.rb:49]: Now that this only affects ERB, maybe this should be a class attribute in this file on `ActionView::Template::Handlers::ERB`?

**Comment by jhawthorn** [comment]
Left one more suggestion (moving the config option) but I think with that and a squash this is good to go 🚀 😁

File: railties/lib/rails/generators/rails/app/templates/config/application.rb.tt [hunk 2]
```diff
@@ -50,5 +50,8 @@ module <%= app_const_base %>
     # Don't generate system test files.
     config.generators.system_tests = nil
 <%- end -%>
+
+    # Strip trailing newlines from rendered output.
+    # config.action_view.strip_trailing_newlines = false
```
Comment (eugeneius) [inline railties/lib/rails/generators/rails/app/templates/config/application.rb.tt:55]: I don't think we should generate this comment for every new application, given that similar placeholders were removed in https://github.com/rails/rails/commit/28dcadc0140dfdebe87d5e691fd709c0a9ae0bae because they weren't changed often to warrant inclusion.

Comment (boardfish) [reply railties/lib/rails/generators/rails/app/templates/config/application.rb.tt:55]: Not sure I agree — I think it's too early to confirm this.

File: actionview/lib/action_view/template/handlers/erb.rb (hunk 1 above)
Comment (boardfish) [reply actionview/lib/action_view/template/handlers/erb.rb:49]: In the event that this functionality gets implemented for other template handlers, I suppose we'd move it back to `ActionView::Base`, right?

This seems reasonable — I'll get it in and then squash those commits.

**Comment by boardfish** [comment]
All suggestions addressed, and I've rebased against `main` too.

I took the option out of the documentation and `application.rb` because now that this is isolated to ERB, it might not be relevant to all cases. If there's a need for it in other template handlers, the config option can be moved back into `ActionView::Base` and more widely documented.

**Comment by jhawthorn** [comment]
Awesome! Thanks so much @boardfish
