### PR TITLE
More concise Arel `Or` ast and make `Or` visitor non recursive

### LINKED ISSUE #39032: "Stack level too deep" when `inject`ing a lot of activerecord relations via `#or`
### Steps to reproduce
execute a file in the following gist https://gist.github.com/trushkevich/9d8cdc3c7466e7bc793ae7075534db4f
```ruby
ruby inject_or_stack_level_too_deep.rb
```
### Expected behavior
`test_ok` passes
`test_parser_stack_overflow` passes
`test_stack_level_too_deep` passes

### Actual behavior
`test_ok` passes
`test_parser_stack_overflow` fails
`test_stack_level_too_deep` fails

### System configuration
**Rails version**:
5.2.3, 6.1.0.alpha

**Ruby version**:
2.4.1, 2.6.3

### PR DESCRIPTION
**Pull request by kamipo**
Before this, 1000 `Or` nodes will raise "stack level too deep" due to
visiting too deep Arel ast.

This makes more concise Arel `Or` ast and `Or` visitor non recursive if
`Or` nodes are adjoined, as a result, "stack level too deep" is no
longer raised.

```ruby
class Post < ActiveRecord::Base
end

posts = (0..500).map { |i| Post.where(id: i) }

Benchmark.ips do |x|
  x.report("inject scopes") { posts.inject(&:or).to_sql }
end
```

Before:

```
Warming up --------------------------------------
      where with ids     9.000  i/100ms
Calculating -------------------------------------
      where with ids     96.126  (± 2.1%) i/s -    486.000  in   5.058960s
```

After:

```
Warming up --------------------------------------
       inject scopes    10.000  i/100ms
Calculating -------------------------------------
       inject scopes    101.714  (± 2.9%) i/s -    510.000  in   5.018880s
```

Fixes #39032.

### CODE REVIEW

File: activerecord/lib/arel/visitors/to_sql.rb [hunk 1]
```diff
@@ -578,9 +578,41 @@ def visit_Arel_Nodes_And(o, collector)
...
+              tree[o.right] = o
+              o = o.right
+              next
+            end
+
+            visit o.right, collector
+
+            done = o
+            o = tree[o]
+          end
```
Comment (jonathanhefner) [inline activerecord/lib/arel/visitors/to_sql.rb:613]: Would this work as well?

```suggestion
          stack = [o]

          while (o = stack.pop)
            if o.is_a?(Arel::Nodes::Or)
              stack << o.right
              stack << o.left
            else
              visit o, collector
              collector << " OR " unless stack.empty?
            end
          end
```

File: activerecord/lib/active_record/relation/where_clause.rb [hunk 2]
```diff
@@ -39,10 +39,16 @@ def or(other)
...
         else
-          or_clause = WhereClause.new(
-            [left.ast.or(right.ast)],
-          )
-          common + or_clause
+          left = left.ast
+          left = left.expr if left.is_a?(Arel::Nodes::Grouping)
+
+          right = right.ast
+          right = right.expr if right.is_a?(Arel::Nodes::Grouping)
```
Comment (jonathanhefner) [inline activerecord/lib/active_record/relation/where_clause.rb:46]: This is a safe transformation because of the fact that SQL `OR` has lower precedence than `AND`, yes?

**Review by jonathanhefner — COMMENTED** [review]
This is great! :rocket:

File: activerecord/lib/arel/visitors/to_sql.rb (hunk 1 above)
Comment (kamipo) [reply activerecord/lib/arel/visitors/to_sql.rb]: 👍 I've got the same feedback to use stack from a friend.

File: activerecord/lib/active_record/relation/where_clause.rb (hunk 2 above)
Comment (kamipo) [reply activerecord/lib/active_record/relation/where_clause.rb:46]: I think yes.
