### PR TITLE
Clearing optional CPK in belongs_to should preserve PK

### LINKED ISSUE #54882: AR throws exception when trying to unset optional composite foreign key
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books, force: true, primary_key: %i[number] do |t|
    t.integer :number
    t.string :title
  end

  create_table :chapters, force: true, primary_key: %i[book_number number] do |t|
    t.integer :book_number
    t.integer :number
    t.string :title
  end

  add_column :books, :favorite_chapter_number, :integer, null: true
end

class Book < ActiveRecord::Base
  self.primary_key = %i[number]

  has_many :chapters, inverse_of: :book

  belongs_to :favorite_chapter, class_name: "Chapter", foreign_key: %i[number favorite_chapter_number], optional: true
end

class Chapter < ActiveRecord::Base
  self.primary_key = %i[book_number number]

  belongs_to :book, foreign_key: :book_number, inverse_of: :chapters
end

class BugTestUsingModel < Minitest::Test
  def test_association_stuff
    book = Book.create!(number: 1, title: "First book")
    book.chapters << Chapter.create!(number: 1, title: "Chapter one") << Chapter.create!(number: 2, title: "Chapter two")

    book.update!(favorite_chapter: book.chapters.second)
    assert_equal Chapter.find([1,2]), book.favorite_chapter
    # All good so far

    # Now unset favorite chapter (it's optional)
    book.update!(favorite_chapter: nil) # This nullifies the primary key as well.
  end
end
```

### Expected behavior

It should just unset the optional composite foreign key association.

### Actual behavior

Throws the exception with the following stack trace:

```
  1) Error:
BugTestUsingModel#test_association_stuff:
ActiveRecord::StatementInvalid: SQLite3::MismatchException: datatype mismatch
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb:100:in 'SQLite3::Statement#step'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb:100:in 'ActiveRecord::ConnectionAdapters::SQLite3::DatabaseStatements#perform_query'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:560:in 'block (3 levels) in ActiveRecord::ConnectionAdapters::DatabaseStatements#raw_execute'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activesupport/lib/active_support/concurrency/share_lock.rb:186:in 'ActiveSupport::Concurrency::ShareLock#yield_shares'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activesupport/lib/active_support/dependencies/interlock.rb:41:in 'ActiveSupport::Dependencies::Interlock#permit_concurrent_loads'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:559:in 'block (2 levels) in ActiveRecord::ConnectionAdapters::DatabaseStatements#raw_execute'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1027:in 'block in ActiveRecord::ConnectionAdapters::AbstractAdapter#with_raw_connection'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activesupport/lib/active_support/concurrency/null_lock.rb:9:in 'ActiveSupport::Concurrency::NullLock#synchronize'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:996:in 'ActiveRecord::ConnectionAdapters::AbstractAdapter#with_raw_connection'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:558:in 'block in ActiveRecord::ConnectionAdapters::DatabaseStatements#raw_execute'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activesupport/lib/active_support/notifications/instrumenter.rb:58:in 'ActiveSupport::Notifications::Instrumenter#instrument'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1147:in 'ActiveRecord::ConnectionAdapters::AbstractAdapter#log'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:557:in 'ActiveRecord::ConnectionAdapters::DatabaseStatements#raw_execute'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:601:in 'ActiveRecord::ConnectionAdapters::DatabaseStatements#internal_execute'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:176:in 'ActiveRecord::ConnectionAdapters::DatabaseStatements#exec_update'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in 'ActiveRecord::ConnectionAdapters::DatabaseStatements#update'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:27:in 'ActiveRecord::ConnectionAdapters::AbstractAdapter#update'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/persistence.rb:278:in 'block in ActiveRecord::Persistence::ClassMethods#_update_record'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:417:in 'ActiveRecord::ConnectionAdapters::ConnectionPool#with_connection'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_handling.rb:310:in 'ActiveRecord::ConnectionHandling#with_connection'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/persistence.rb:277:in 'ActiveRecord::Persistence::ClassMethods#_update_record'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/persistence.rb:893:in 'ActiveRecord::Persistence#_update_row'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/locking/optimistic.rb:93:in 'ActiveRecord::Locking::Optimistic#_update_row'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/persistence.rb:915:in 'ActiveRecord::Persistence#_update_record'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/attribute_methods/dirty.rb:234:in 'ActiveRecord::AttributeMethods::Dirty#_update_record'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/callbacks.rb:449:in 'block (2 levels) in ActiveRecord::Callbacks#_update_record'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/timestamp.rb:140:in 'ActiveRecord::Timestamp#record_update_timestamps'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/callbacks.rb:449:in 'block in ActiveRecord::Callbacks#_update_record'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activesupport/lib/active_support/callbacks.rb:109:in 'ActiveSupport::Callbacks#run_callbacks'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activesupport/lib/active_support/callbacks.rb:913:in 'ActiveRecord::Base#_run_update_callbacks'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/callbacks.rb:449:in 'ActiveRecord::Callbacks#_update_record'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/timestamp.rb:122:in 'ActiveRecord::Timestamp#_update_record'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/persistence.rb:902:in 'ActiveRecord::Persistence#create_or_update'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/callbacks.rb:441:in 'block in ActiveRecord::Callbacks#create_or_update'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activesupport/lib/active_support/callbacks.rb:120:in 'block in ActiveSupport::Callbacks#run_callbacks'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/autosave_association.rb:406:in 'ActiveRecord::AutosaveAssociation#around_save_collection_association'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activesupport/lib/active_support/callbacks.rb:129:in 'block in ActiveSupport::Callbacks#run_callbacks'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activesupport/lib/active_support/callbacks.rb:140:in 'ActiveSupport::Callbacks#run_callbacks'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activesupport/lib/active_support/callbacks.rb:913:in 'ActiveRecord::Base#_run_save_callbacks'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/callbacks.rb:441:in 'ActiveRecord::Callbacks#create_or_update'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/timestamp.rb:127:in 'ActiveRecord::Timestamp#create_or_update'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/persistence.rb:424:in 'ActiveRecord::Persistence#save!'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/validations.rb:54:in 'ActiveRecord::Validations#save!'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/transactions.rb:384:in 'block in ActiveRecord::Transactions#save!'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/transactions.rb:436:in 'block (2 levels) in ActiveRecord::Transactions#with_transaction_returning_status'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:360:in 'ActiveRecord::ConnectionAdapters::DatabaseStatements#transaction'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/transactions.rb:432:in 'block in ActiveRecord::Transactions#with_transaction_returning_status'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:417:in 'ActiveRecord::ConnectionAdapters::ConnectionPool#with_connection'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_handling.rb:310:in 'ActiveRecord::ConnectionHandling#with_connection'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/transactions.rb:428:in 'ActiveRecord::Transactions#with_transaction_returning_status'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/transactions.rb:384:in 'ActiveRecord::Transactions#save!'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/suppressor.rb:56:in 'ActiveRecord::Suppressor#save!'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/persistence.rb:580:in 'block in ActiveRecord::Persistence#update!'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/transactions.rb:436:in 'block (2 levels) in ActiveRecord::Transactions#with_transaction_returning_status'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:627:in 'block in ActiveRecord::ConnectionAdapters::TransactionManager#within_new_transaction'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activesupport/lib/active_support/concurrency/null_lock.rb:9:in 'ActiveSupport::Concurrency::NullLock#synchronize'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:624:in 'ActiveRecord::ConnectionAdapters::TransactionManager#within_new_transaction'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:370:in 'ActiveRecord::ConnectionAdapters::DatabaseStatements#within_new_transaction'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:362:in 'ActiveRecord::ConnectionAdapters::DatabaseStatements#transaction'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/transactions.rb:432:in 'block in ActiveRecord::Transactions#with_transaction_returning_status'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:417:in 'ActiveRecord::ConnectionAdapters::ConnectionPool#with_connection'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/connection_handling.rb:310:in 'ActiveRecord::ConnectionHandling#with_connection'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/transactions.rb:428:in 'ActiveRecord::Transactions#with_transaction_returning_status'
    /home/jarl/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/bundler/gems/rails-fd886fe46ad6/activerecord/lib/active_record/persistence.rb:578:in 'ActiveRecord::Persistence#update!'
    demo2.rb:61:in 'BugTestUsingModel#test_association_stuff'
```

### System configuration

**Rails version**: edge

**Ruby version**: 3.4.2

### See also

https://github.com/rails/rails/issues/54881

### PR DESCRIPTION
**Pull request by zzak**
Fixes: #54882

/cc @jarl-dk

### CODE REVIEW

File: activerecord/lib/active_record/associations/belongs_to_association.rb [hunk 1]
```diff
@@ -135,7 +135,9 @@ def replace_keys(record, force: false)
             target_key_values = record ? Array(primary_key(record.class)).map { |key| record._read_attribute(key) } : []
 
             if force || reflection_fk.map { |fk| owner._read_attribute(fk) } != target_key_values
+              owner_pk = Array(owner.class.primary_key)
               reflection_fk.each_with_index do |key, index|
+                next if record.nil? && owner_pk.include?(key)
```
Comment (nvasilevski) [inline activerecord/lib/active_record/associations/belongs_to_association.rb:140]: It's a nitpick and I'm ok with not doing it in this PR but this method keeps growing and it started to be really hard to follow it. I wonder if it might be worth looking into refactoring it. 
First I think we should be able to get rid of `if reflection_fk.is_a?(Array)` in favor of treating everything as an `Array()`, even single-column PK/FKs. And then perhaps we could semantically split it into two parts: one part for the "replace" flow and the other one is "nullify" flow where `record` is `nil`.

Again, not a blocking comment, just thinking out loud as we check for the `record` presence multiple time and it feels like we could check it once and as early as possible

**Review by nvasilevski — APPROVED** [review]
Makes sense, the "shared" part of the PK/FK shouldn't be reset. Thank you!

**Comment by jarl-dk** [comment]
I can confirm this fixes #54881 and #54882. Looking forward to a new Rails release with this included.

**Comment by jarl-dk** [comment]
What is this merge waiting for?

**Comment by jarl-dk** [comment]
@zzak Can you please merge this?

**Comment by jarl-dk** [comment]
> @zzak Can you please merge this?

@zzak ping
