### PR TITLE
Fix collision check when using a generator and using the force option

### LINKED ISSUE #37403: NamedBase generators don't respect force option like their documentation indicates.
NamedBase generators don't respect `force` like their documentation describes.

### Steps to reproduce

`rails g --help`

```
...
  -f, [--force]    # Overwrite files that already exist
```

`rails g model VendorUser user:references` 

("oops, forgot 'vendor'")

`rails g model VendorUser user:references vendor:references --force`

> The name 'VendorUser' is either already used in your application or reserved by Ruby on Rails. Please choose an alternative and run this generator again.

### Expected behavior

Should continue to generate the model and migration, removing any previously-generated files of the same name.

### Actual behavior

Exits generator.

### System configuration
**Rails version**: 6.0.0

**Ruby version**: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin17]

### PR DESCRIPTION
**Pull request by joshmn**
### Summary

Fixes #37403 and #37538 

Generators that inherit from NamedBase have options `--force` or `-f` available to overwrite files that already exist. Prior to this PR, using this option would raise an error saying that the constant already existed or the name was reserved. See https://github.com/rails/rails/pull/36603 for more info.

### Other information

The migration generator respected this already.

### CODE REVIEW

File: railties/lib/rails/generators/base.rb [hunk 1]
```diff
@@ -252,6 +252,7 @@ def self.inherited(base) #:nodoc:
         def class_collisions(*class_names)
           return unless behavior == :invoke
           return if options.skip_collision_check?
+          return if options.force?
```
Comment (joshmn) [inline railties/lib/rails/generators/base.rb]: I'm not sure if we want to define `ignore_collisions?` and chain these two together. I thought it was better left as is to indicate that this is explicitly skipped from options.
