### PR TITLE
Fix IRB deprecation warning on tab-completion

### LINKED ISSUE #37097: [Rails 6] Pry and irb completion breaks on a minimal example with a rails-originated (spurious?) deprecation
### Steps to reproduce
1.
```
git clone https://github.com/steakknife/mce-erroneous-source-annotation-extractor-deprecation && \
cd mce-erroneous-source-annotation-extractor-deprecation && \
rails db:migrate && \
rails c
```
2. `User.create!`
3. Type `User.last.` and hit <kbd>tab</kbd>

### Expected behavior

`User` methods completion

### Actual behavior
```
        $  rails c
Loading development environment (Rails 6.1.0.alpha)
irb(main):001:0> ActiveSupport::Deprecation.debug = true
=> true
irb(main):002:0> User.last.DEPRECATION WARNING: SourceAnnotationExtractor is deprecated! Use Rails::SourceAnnotationExtractor instead. (called from run at ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor/command.rb:27)
~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/completion.rb:174:in `include?'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/completion.rb:174:in `block (2 levels) in <module:InputCompletor>'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/completion.rb:173:in `each_object'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/completion.rb:173:in `block in <module:InputCompletor>'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/input-method.rb:151:in `readline'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/input-method.rb:151:in `gets'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:473:in `block (2 levels) in eval_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:647:in `signal_status'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:472:in `block in eval_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:189:in `buf_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:104:in `getc'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/slex.rb:206:in `match_io'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/slex.rb:76:in `match'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:292:in `token'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:266:in `lex'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:236:in `block (2 levels) in each_top_level_statement'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `loop'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `catch'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:489:in `eval_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:428:in `block in run'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:427:in `catch'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:427:in `run'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:383:in `start'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands/console/console_command.rb:70:in `start'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands/console/console_command.rb:19:in `start'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands/console/console_command.rb:102:in `perform'
  ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/command/base.rb:65:in `perform'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/command.rb:45:in `invoke'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands.rb:18:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<main>'
DEPRECATION WARNING: SourceAnnotationExtractor is deprecated! Use Rails::SourceAnnotationExtractor instead. (called from run at ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor/command.rb:27)
~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/completion.rb:175:in `block (2 levels) in <module:InputCompletor>'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/completion.rb:173:in `each_object'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/completion.rb:173:in `block in <module:InputCompletor>'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/input-method.rb:151:in `readline'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/input-method.rb:151:in `gets'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:473:in `block (2 levels) in eval_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:647:in `signal_status'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:472:in `block in eval_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:189:in `buf_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:104:in `getc'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/slex.rb:206:in `match_io'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/slex.rb:76:in `match'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:292:in `token'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:266:in `lex'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:236:in `block (2 levels) in each_top_level_statement'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `loop'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `catch'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:489:in `eval_input'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:428:in `block in run'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:427:in `catch'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:427:in `run'
  ~/.rubies/ruby-2.6.4/lib/ruby/2.6.0/irb.rb:383:in `start'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands/console/console_command.rb:70:in `start'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands/console/console_command.rb:19:in `start'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands/console/console_command.rb:102:in `perform'
  ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  ~/.gem/ruby/2.6.4/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/command/base.rb:65:in `perform'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/command.rb:45:in `invoke'
  ~/.gem/ruby/2.6.4/bundler/gems/rails-782d28030730/railties/lib/rails/commands.rb:18:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<main>'
```

### System configuration
**Rails version**: 6.0.0 or master ( 782d28030730c14658a7cd66ee81e7f16c0a12cd )

**Ruby version**: 2.6.4

**OS**: macOS 10.14.6 (18G87)

### PR DESCRIPTION
**Pull request by jonathanhefner**
IRB invokes `#hash` (via a call to `Hash#include?`) and `#instance_methods` on each object in `ObjectSpace.each_object(Module)` when performing tab-completion on chain of method calls.  This patch prevents a deprecation warning from being printed when any of those objects are a `ActiveSupport::Deprecation::DeprecatedConstantProxy`.

Fixes #37097.

### CODE REVIEW

**Comment by jonathanhefner** [comment]
The build errors appear to be unrelated.  Something to do with failing to build `eventmachine` native extensions?

File: activesupport/lib/active_support/deprecation/proxy_wrappers.rb [hunk 1]
```diff
@@ -145,6 +145,10 @@ def inspect
         target.inspect
       end
 
+      # Don't give a deprecation warning on methods that IRB may invoke
+      # during tab-completion.
+      delegate :hash, :instance_methods, to: :target
```
Comment (jonathanhefner) [inline activesupport/lib/active_support/deprecation/proxy_wrappers.rb]: I considered future-proofing this with
```ruby
delegate *BasicObject.public_methods, to: :target
```
but that seems too heavy-handed.  Would
```ruby
delegate :hash, *BasicObject.public_methods.grep(/methods/), to: :target
```
be better?

**Comment by kaspth** [comment]
Thanks! Let's just keep it to this and see how well this fares in future Ruby versions. I'd rather not add the dynamic delegate just yet.

**Comment by swrobel** [comment]
Will this be backported to 6-0-stable?

**Comment by joallard** [comment]
Thanks @kaspth, is there a way we can get this merged to 6-0-stable?

**Comment by rafaelfranca** [comment]
Backported

**Comment by joallard** [comment]
Thanks so much!

**Comment by vixalien** [comment]
Can you explain to the non-intelligent people what to do? Do we update rails, downgrade it or update ruby

**Comment by jonathanhefner** [comment]
@vixalien This fix will be included in Rails 6.0.3, though I'm not sure when that will be released.  In the mean time, if you're feeling bold, you can point your Gemfile to the `6-0-stable` branch of Rails:

```ruby
gem "rails", github: "rails/rails", branch: "6-0-stable"
```
