### PR TITLE
Fix child association loading in `:n_plus_one_only` mode

### LINKED ISSUE #49473: Strict loading in `:n_plus_one_only` mode should not eager load child associations
### Description
Strict loading in `:n_plus_one_only` mode is designed to prevent performance issues when deeply traversing associations. It allows `Person.find(1).posts`, but _not_ `Person.find(1).posts.map(&:category)`. This fix avoids the surprise that occurs when `person.posts.first` eagerly loads the whole association rather than allowing the user to manage the child association.

This fixes a serious ordering issue. Without strict loading, `person.posts.first` is guaranteed to return the first post in primary key order. On the other hand, `person.posts.load.first` is nondeterministic. The database is not guaranteed to return in a consistent order, in particular under load with other operations occurring. This is a rude surprise when trying to use `:n_plus_one_only` mode.

### Steps to reproduce

This can be reproduced via any `has_many` association. Here's an example using ActiveRecord test models:
```ruby
person = Person.find(1)
person.strict_loading!(mode: :n_plus_one_only)
person.posts.first
# SELECT * FROM posts WHERE person_id = 1; -- non-deterministic order
```

### Expected behavior

```ruby
person = Person.find(1)
person.strict_loading!(mode: :n_plus_one_only)
person.posts.first # this is 1+1, not N+1
# SELECT * FROM posts WHERE person_id = 1 ORDER BY id LIMIT 1;
```

### Actual behavior

```ruby
person = Person.find(1)
person.strict_loading!(mode: :n_plus_one_only)
person.posts.first
# SELECT * FROM posts WHERE person_id = 1; -- non-deterministic order
```

### Proposed fix
Please see #48785 

### System configuration
**Rails version**: `rails (7.0.7.2)`
**Ruby version**: `ruby 3.2.2`

### PR DESCRIPTION
**Pull request by reid-rigo**
### Motivation / Background

Fixes #49473

Strict loading in `:n_plus_one_only` mode is designed to prevent performance issues when deeply traversing associations. It allows `Person.find(1).posts`, but _not_ `Person.find(1).posts.map(&:category)`. This fix avoids the surprise that occurs when `person.posts.first` eagerly loads the whole association rather than allowing the user to manage the child association.

This fixes a serious ordering issue. Without strict loading, `person.posts.first` is guaranteed to return the first post in primary key order. On the other hand, `person.posts.load.first` is nondeterministic. The database is not guaranteed to return in a consistent order, in particular under load with other operations occurring. This is a rude surprise when trying to use `:n_plus_one_only` mode.

### Detail

Before:

```ruby
person = Person.find(1)
person.strict_loading!(mode: :n_plus_one_only)
person.posts.first
# SELECT * FROM posts WHERE person_id = 1; -- non-deterministic order
```

After:

```ruby
person = Person.find(1)
person.strict_loading!(mode: :n_plus_one_only)
person.posts.first # this is 1+1, not N+1
# SELECT * FROM posts WHERE person_id = 1 ORDER BY id LIMIT 1;
```

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/test/cases/strict_loading_test.rb [hunk 1]
```diff
@@ -53,6 +54,10 @@ def test_strict_loading_n_plus_one_only_mode
     developer.strict_loading!(mode: :n_plus_one_only)
     assert_predicate developer, :strict_loading?
 
+    # Does not eager load a child association
+    developer.projects.first
+    assert_not_predicate developer.projects, :loaded?
+
```
Comment (p8) [inline activerecord/test/cases/strict_loading_test.rb:60]: There already is a lot going on in this test.
Moving the described issue to a new test case would make the problem more clear.

Comment (reid-rigo) [reply activerecord/test/cases/strict_loading_test.rb]: Thanks for taking a look, @p8. I broke this into a separate test case in 4c90fdf1ce1634cdd3a56214dc7ec96cf2501a3e

File: activerecord/test/cases/strict_loading_test.rb [hunk 2]
```diff
@@ -672,6 +673,14 @@ def test_strict_loading_violation_logs_on_polymorphic_relation
     ActiveRecord.action_on_strict_loading_violation = old_value
   end
 
+  def test_strict_loading_in_n_plus_one_only_mode_does_not_eager_load_child_associations
+    developer = Developer.first
+    developer.strict_loading!(mode: :n_plus_one_only)
+    developer.projects.first
+
+    assert_not_predicate developer.projects, :loaded?
```
Comment (p8) [inline activerecord/test/cases/strict_loading_test.rb:681]: I hope I'm understanding it correctly, but we can assert that calling firm on the project won't raise anymore now?
Where it did previously.
```suggestion
    assert_not_predicate developer.projects, :loaded?
    
    assert_nothing_raised do
      developer.projects.first.firm
    end
```

Comment (reid-rigo) [reply activerecord/test/cases/strict_loading_test.rb:681]: That's correct. Committed suggestion

File: activerecord/lib/active_record/associations/collection_association.rb [hunk 3]
```diff
@@ -303,7 +303,7 @@ def null_scope?
 
       def find_from_target?
         loaded? ||
-          owner.strict_loading? ||
+          (owner.strict_loading? && owner.strict_loading_all?) ||
```
Comment (p8) [inline activerecord/lib/active_record/associations/collection_association.rb:306]: If `strict_loading_all?` returns `true`, `strict_loading?` is always `true`?
```suggestion
          owner.strict_loading_all? ||
```

Comment (p8) [reply activerecord/lib/active_record/associations/collection_association.rb:306]: Ah never mind. You can call `strict_loading!(false, mode: :all)` and the `mode` will still be set to `:all`.

File: activerecord/test/cases/strict_loading_test.rb [hunk 4]
```diff
@@ -672,6 +673,18 @@ def test_strict_loading_violation_logs_on_polymorphic_relation
     ActiveRecord.action_on_strict_loading_violation = old_value
   end
 
+  def test_strict_loading_in_n_plus_one_only_mode_does_not_eager_load_child_associations
```
Comment (p8) [inline activerecord/test/cases/strict_loading_test.rb:676]: Could you move this test under `test_strict_loading_n_plus_one_only_mode`, so all `:n_plus_one_only` tests are grouped together?
I've also split that test into two separate tests. You probably need to rebase on main.

Comment (reid-rigo) [reply activerecord/test/cases/strict_loading_test.rb]: Of course. Moved in d32ce805bf7ad7eeeb910afbe632ba66d48707d0. I also tweaked the test name slightly to better align with the others.

File: activerecord/CHANGELOG.md [hunk 5]
```diff
@@ -1,3 +1,28 @@
...
+    person.posts.first # this is 1+1, not N+1
+    # SELECT * FROM posts WHERE person_id = 1 ORDER BY id LIMIT 1;
+    ```
+    Strict loading in `:n_plus_one_only` mode is designed to prevent performance issues when
+    deeply traversing associations. It allows `Person.find(1).posts`, but _not_
+    `Person.find(1).posts.map(&:category)`. With this change, child associations are no
+    longer eagerly loaded, to match intended behavior and to prevent non-deterministic
+    order issues caused by calling methods like `first` or `last`.
+    Fixes #49473.
+    *Reid Lynch*
```
Comment (p8) [inline activerecord/CHANGELOG.md:24]:
```suggestion

    *Reid Lynch*
```

Comment (p8) [inline activerecord/CHANGELOG.md:24]: We usually show the examples after the description of the change.
I think we can also skip the description of `:n_plus_one_only`:

```suggestion
    With this change, child associations are no
    longer eagerly loaded, to match intended behavior and to prevent non-deterministic
    order issues caused by calling methods like `first` or `last`.
    Fixes #49473.
    
    Before:

    ```ruby
    person = Person.find(1)
    person.strict_loading!(mode: :n_plus_one_only)
    person.posts.first
    # SELECT * FROM posts WHERE person_id = 1; -- non-deterministic order
    ```

    After:

    ```ruby
    person = Person.find(1)
    person.strict_loading!(mode: :n_plus_one_only)
    person.posts.first # this is 1+1, not N+1
    # SELECT * FROM posts WHERE person_id = 1 ORDER BY id LIMIT 1;
    ```

    *Reid Lynch*
```

**Comment by p8** [comment]
Hi @reid-rigo. Could you squash your commits?

**Comment by reid-rigo** [comment]
@p8 done

**Review by p8 — APPROVED** [review]

**Comment by gjtorikian** [comment]
👋 Is there a process for when `ready` PRs are merged?
