### PR TITLE
Check whether the current attribute being read is aliased or not before reading

### LINKED ISSUE #26417: Cache key behaviour for alliased timestamps
### Steps to reproduce

I a simple model

``` ruby
class Epixcms::Movies::Movie < ActiveRecord::Base
  alias_attribute :updated_at, :modified_date
  alias_attribute :created_at, :create_date
end

movie = Epixcms::Movies::Movie.new
movie.modified_date = Time.zone.now
movie.cache_key
```
### Expected behavior

It should respect the defined alias and include the modified_date into the cache_key
### Actual behavior

It does not include the modified_date
### System configuration

Rails 4.2.7.1
Ruby 2.3.0

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
### Summary
- If aliased, then use the aliased attribute name.
- Fixes #26417.

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
r? @sgrif 

Sean, should we apply same change to `write_attribute` as well?

**Comment by matthewd** [comment]
> should we apply same change to write_attribute as well?

:+1: read & write should work the same way

**Comment by prathamesh-sonpatki** [comment]
Thanks, I will update it.

**Comment by prathamesh-sonpatki** [comment]
@matthewd done, please review.

File: activerecord/lib/active_record/attribute_methods/write.rb [hunk 1]
```diff
@@ -29,7 +29,13 @@ def __temp__#{safe_name}=(value)
       # specified +value+. Empty strings for Integer and Float columns are
       # turned into +nil+.
       def write_attribute(attr_name, value)
-        write_attribute_with_type_cast(attr_name, value, true)
+        name = if self.class.attribute_alias?(attr_name)
```
Comment (esparta) [inline activerecord/lib/active_record/attribute_methods/write.rb]: Is not exactly the same code done in `attributes_method/read.rb`?

**Comment by sgrif** [comment]
I think this is fine short term. Longer term I want to push this down to AtrributeSet

**Comment by prathamesh-sonpatki** [comment]
@sgrif Sure, I can work on it now as well, should I move it to `ActiveRecord::AttributeSet`.

I see we have `name = attribute_alias(name) if attribute_alias?(name)` at lot of places. It would be good if that happens behind the scenes. Let me know your thoughts.

**Comment by sgrif** [comment]
@prathamesh-sonpatki Can you rebase? This is fine for now to fix the bug regardless of future refactoring.

**Comment by prathamesh-sonpatki** [comment]
@sgrif  done, I had started working on pushing the `add_alias` method to attribute set but did not finish it yet. Here is my WIP attempt so far: https://github.com/prathamesh-sonpatki/rails/commit/3928ac6943c38fb2c961423bc150b2a37b375653

Right now lot of tests also fail so this is just my playing around the code :) But I tried to push the `add_alias` method onto the attribute set for every AR instance.
