### PR TITLE
Fix `update_all/delete_all` on CPK model relation with join subquery

### LINKED ISSUE #49597: update_all on a joined query with composite primary keys generates invalid SQL
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books, force: true, primary_key: %i[number] do |t|
    t.integer :number
    t.string :title
  end

  create_table :chapters, force: true, primary_key: %i[book_number number] do |t|
    t.integer :book_number
    t.integer :number
    t.string :title
  end
end

class Book < ActiveRecord::Base
  has_many :chapters, foreign_key: :book_number, inverse_of: :book
end

class Chapter < ActiveRecord::Base
  self.primary_key = %i[book_number number]

  belongs_to :book, foreign_key: :book_number, inverse_of: :chapters
end

class BugTest < Minitest::Test
  def test_association_stuff
    book = Book.create!(number: 1, title: "First book")
    book.chapters << Chapter.create!(book:, number: 1, title: "Chapter one")

    assert_equal 1, book.chapters.count
    assert_equal 1, Chapter.count
    assert_equal 1, Chapter.joins(:book).where(book: {title: "First book"}).update_all(title: "Chapter")
  end
end
```

### Expected behaviour
The expected behaviour is for the test to pass.
The expected generated SQL is
```sql
UPDATE "chapters" SET "title" = ? WHERE ("chapters"."book_number", "chapters"."number") IN (SELECT "chapters"."book_number", "chapters"."number" FROM "chapters" INNER JOIN "books" "book" ON "book"."number" = "chapters"."book_number" WHERE "book"."title" = ?)  [["title", "Chapter"], ["title", "First book"]]
```

A working example using rails 7.0 and [composite_primary_keys](https://github.com/composite-primary-keys/composite_primary_keys) gem is here:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 7.0.8"
  gem "sqlite3"
  gem "composite_primary_keys", "~> 14.0.0"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books, force: true, primary_key: %i[number] do |t|
    t.integer :number
    t.string :title
  end

  create_table :chapters, force: true, primary_key: %i[book_number number] do |t|
    t.integer :book_number
    t.integer :number
    t.string :title
  end
end

class Book < ActiveRecord::Base
  has_many :chapters, foreign_key: :book_number, inverse_of: :book
end

class Chapter < ActiveRecord::Base
  self.primary_key = %i[book_number number]

  belongs_to :book, foreign_key: :book_number, inverse_of: :chapters
end

class BugTest < Minitest::Test
  def test_association_stuff
    book = Book.create!(number: 1, title: "First book")
    book.chapters << Chapter.create!(book:, number: 1, title: "Chapter one")

    assert_equal 1, book.chapters.count
    assert_equal 1, Chapter.count
    assert_equal 1, Chapter.joins(:book).where(book: {title: "First book"}).update_all(title: "Chapter")
  end
end
```

### Actual behaviour
The test case fails with
```shell
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: chapters.["book_number", "number"]
```

The actual generated SQL is
```sql
UPDATE "chapters" SET "title" = ? WHERE "chapters"."[""book_number"", ""number""]" IN (SELECT "chapters"."[""book_number"", ""number""]" FROM "chapters" INNER JOIN "books" "book" ON "book"."number" = "chapters"."book_number" WHERE "book"."title" = ?)  [["title", "Chapter"], ["title", "First book"]]
```
### System configuration
**Rails version**: `7.1.1` and also `main`

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by nvasilevski**
Fixes https://github.com/rails/rails/issues/49597

Currently Rails generates an invalid SQL when using `update_all`/`delete_all` on composite primary models relations with a join subquery due to composite primary key being treated as a single key:
```sql
UPDATE "my_table" SET "my_column" = ? WHERE "my_table"."[""pk_col1"", ""pk_col2""]" IN (SELECT "my_table"."[""pk_col1"", ""pk_col2""]"
```

This PR changes `update_all` and `delete_all` SQL to build a proper subquery which utilizes what sometimes referred as a row-constructor statement:
```sql
UPDATE "my_table" SET "my_column" = ? WHERE ("my_table"."pk_col1", "my_table"."pk_col2") IN (SELECT "my_table"."pk_col1", "my_table"."pk_col2" ...
```

### CODE REVIEW

File: activerecord/lib/arel/visitors/to_sql.rb [hunk 1]
```diff
@@ -930,7 +930,8 @@ def prepare_update_statement(o)
             stmt.limit = nil
             stmt.offset = nil
             stmt.orders = []
-            stmt.wheres = [Nodes::In.new(o.key, [build_subselect(o.key, o)])]
+            columns = o.key.is_a?(Array) ? Arel::Nodes::Grouping.new(o.key) : o.key
```
Comment (rafaelfranca) [inline activerecord/lib/arel/visitors/to_sql.rb:933]: This is a smell. We should build a new node when building the AST instead of pushing the logic to the visitor. Can you take a look if we can build a different node instead of having to check the type of the key here?

**Review by rafaelfranca — CHANGES_REQUESTED** [review]

File: activerecord/lib/arel/visitors/to_sql.rb (hunk 1 above)
Comment (rafaelfranca) [reply activerecord/lib/arel/visitors/to_sql.rb:933]: Any updated on a different approach?

Comment (nvasilevski) [reply activerecord/lib/arel/visitors/to_sql.rb:933]: Sorry, I lost track of this PR. 
I'll try to get back to it this week

Comment (nvasilevski) [reply activerecord/lib/arel/visitors/to_sql.rb]: I changed the implementation but it's not drastically different from the original one. The main idea is to prevent the visitor from caring about whether the key is composite or not and simply always use `Grouping` node for the `SELECT (<column_or_columns>) IN ()` subselect query

Having additional parenthesis doesn't change the query and unlikely will result in any noticeable performance impact

File: test_composite_pk.rb
Comment (rafaelfranca) [inline test_composite_pk.rb:1]: This file should be deleted

**Review by rafaelfranca — CHANGES_REQUESTED** [review]

File: test_composite_pk.rb
Comment (nvasilevski) [reply test_composite_pk.rb:1]: done, thanks!
