### PR TITLE
Fix the message verifier encoding issue

### LINKED ISSUE #20416: ActiveSupport::MessageVerifier raises "ArgumentError: invalid byte sequence in UTF-8" on malformed cookie
Last night, we received a bunch of error notifications like this:

```ruby
ArgumentError: invalid byte sequence in UTF-8
/gems/activesupport-4.2.1/lib/active_support/core_ext/object/blank.rb:117 in ===
/gems/activesupport-4.2.1/lib/active_support/core_ext/object/blank.rb:117 in blank?
/gems/activesupport-4.2.1/lib/active_support/message_verifier.rb:38 in verify
/gems/activesupport-4.2.1/lib/active_support/message_encryptor.rb:64 in decrypt_and_verify
/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:535 in decrypt_and_verify
/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:516 in []
app/controllers/application_controller.rb:50 in current_user
app/controllers/application_controller.rb:61 in authenticate
```

and it turns out, the following code raises the error when an invalid string (e.g. "\xff") is given as the cookie value, set by a (potentially malicious) client.

```ruby
def current_user
  @current_user ||= User.find_by(id: cookies.encrypted[:user_id]) if cookies[:user_id]
end
```

Considering that it's a client error (or an attack attempt), we shouldn't raise an error and return 500.

Here's a minimal repro:

```ruby
verifier=ActiveSupport::MessageVerifier.new('secret')
verifier.verify("\xff")
ArgumentError: invalid byte sequence in UTF-8
```

I would suggest that `MessageVerifier#verify` will check if `signed_message` is a `valid_encoding?` before checking `blank?`.

```ruby
def verify(signed_message)
  raise InvalidSignature if !signed_message.valid_encoding? || signed_message.blank?
  ...
```

Let me know what you think.

### PR DESCRIPTION
**Pull request by repinel**
Fixes #20416 

``` ruby
verifier = ActiveSupport::MessageVerifier.new('secret')
verifier.verify("\xff") # => ArgumentError: invalid byte sequence in UTF-8
```

### CODE REVIEW

File: activesupport/lib/active_support/message_verifier.rb [hunk 1]
```diff
@@ -44,7 +44,7 @@ def initialize(secret, options = {})
     #   tampered_message = signed_message.chop # editing the message invalidates the signature
     #   verifier.valid_message?(tampered_message) # => false
     def valid_message?(signed_message)
-      return if signed_message.blank?
+      return if signed_message.nil? || !signed_message.valid_encoding? || signed_message.blank?
```
Comment (repinel) [inline activesupport/lib/active_support/message_verifier.rb]: Any suggestion? I thought about just using `.to_s` but it seems about `1.4x` slower than checking with `.nil?`

File: activesupport/test/message_verifier_test.rb [hunk 2]
```diff
@@ -36,13 +38,25 @@ def test_simple_round_tripping
...
 
   def test_verified_returns_false_on_invalid_message
-    assert !@verifier.verified("purejunk")
+    message = @verifier.generate(@data)
+    mock = MiniTest::Mock.new
+    mock.expect(:call, false, [message])
+    @verifier.stub(:valid_message?, mock) do
+      assert !@verifier.verified(message)
+    end
+    mock.verify
```
Comment (kaspth) [inline activesupport/test/message_verifier_test.rb]: I don't see the point of changing to a mock here. What does this get us?

File: activesupport/lib/active_support/message_verifier.rb (hunk 1 above)
Comment (kaspth) [inline activesupport/lib/active_support/message_verifier.rb]: It's probably fine like this.

Comment (matthewd) [inline activesupport/lib/active_support/message_verifier.rb]: Is `nil` (or more generally, any non-string) a reasonable argument for this method to be given? That sounds a lot like the caller's problem to me.

Comment (kaspth) [inline activesupport/lib/active_support/message_verifier.rb]: Good point, @matthewd, but we do test for nil input: https://github.com/repinel/rails/blob/fix-message-verifier-encoding-issue/activesupport/test/message_verifier_test.rb#L26

Comment (repinel) [inline activesupport/lib/active_support/message_verifier.rb]: Yes, the test is the main reason why I added the condition.

File: activesupport/test/message_verifier_test.rb (hunk 2 above)
Comment (repinel) [inline activesupport/test/message_verifier_test.rb]: I added the `expect` so `verified` could be tested based on the `valid_message?` behavior. It seems to me that without the mock, we would have to duplicate cases that `valid_message?` is being tested against in `test_valid_message`.

Comment (kaspth) [inline activesupport/test/message_verifier_test.rb]: I don't think we need to duplicate the cases here. @matthewd what do you think about this?

Comment (repinel) [inline activesupport/test/message_verifier_test.rb]: @kaspth @matthewd If you guys think the existing test is enough, I can just revert this one.

Comment (kaspth) [inline activesupport/test/message_verifier_test.rb]: I'm in favor of removing the mock and stubbing here and in the other test :+1:

**Comment by repinel** [comment]
@kaspth I removed the `expect`. I should be better now :smiley:

File: activesupport/test/message_verifier_test.rb [hunk 3]
```diff
@@ -24,6 +24,7 @@ def test_valid_message
     data, hash = @verifier.generate(@data).split("--")
     assert !@verifier.valid_message?(nil)
     assert !@verifier.valid_message?("")
+    assert !@verifier.valid_message?("\xff")
```
Comment (matthewd) [inline activesupport/test/message_verifier_test.rb]: Can we throw a `# invalid encoding` on the end of this line, please?

The rest seem self-explanatory as to why they're here, but at a glance, it may not be obvious how this differs from `"purejunk"`.

Comment (repinel) [inline activesupport/test/message_verifier_test.rb]: I'm not sure if I follow. Instead of returning `false` on this case, I would `raise` something like `InvalidEncoding`? If so, wouldn't `verify` end up raising the same instead of `InvalidSignature`?

Comment (kaspth) [inline activesupport/test/message_verifier_test.rb]: I think @matthewd's use of "throw" mislead you a bit. He just wants an `# invalid encoding` comment added to the line in the test :smile:

Comment (repinel) [inline activesupport/test/message_verifier_test.rb]: Yes, I head my mind on the exception. Thanks!

The comment should now be there.

**Comment by matthewd** [comment]
Thanks!

**Comment by yob** [comment]
We're seeing this issue on a rails 4.1 app - is there any chance of it being backported to `4-1-stable` or `4-2-stable`?

**Comment by repinel** [comment]
It should be fine. @rafaelfranca What do you think?

**Comment by greysteil** [comment]
We're seeing this too, so I've put in a PR to backport to `4-2-stable` (the code there is actually a bit different because the class was refactored in https://github.com/rails/rails/pull/17727). Backport to `4-1-stable` would be trivial from there.

**Comment by greysteil** [comment]
(And big :heart: to @repinel for fixing this in the first place!)
