### PR TITLE
Fix problem with accessing deprecated constant proxy's subclass

### LINKED ISSUE #36313: Rails 6.0.0.rc1 Missing Deprecation SourceAnnotationExtractor::Annotation
I discovered this issue while upgrading a small app that uses `haml_rails` which is using `SourceAnnotationExtractor::Annotation` in version 1.

https://github.com/indirect/haml-rails/blob/86a48a59d7c31fcaacd35fdffa17551fb24e131c/lib/haml-rails.rb#L49

Here is the PR that introduced the changes https://github.com/rails/rails/pull/32065

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'rails', '6.0.0.rc1'
end

require "active_support"
require "active_support/core_ext/object/blank"
require "rails/source_annotation_extractor"
require "minitest/autorun"

def extractor
  SourceAnnotationExtractor
end

def annotation
  SourceAnnotationExtractor::Annotation
end

class SourceAnnotationExtractorTest < ActiveSupport::TestCase
  test 'test_stuff' do
    assert_not_nil extractor
  end
  test 'more_stuff' do
    assert_not_nil annotation
  end
end
```

### Expected behavior
I would expect both tests to pass with a Deprecation warning pointing to the updated module info.

### Actual behavior
The main class SourceAnnotationExtractor has the warning, but ::Annotation outputs `TypeError: Rails::SourceAnnotationExtractor is not a class/module`

### System configuration
**Rails version**:
6.0.0.rc1
**Ruby version**:
2.6.2p47

### PR DESCRIPTION
**Pull request by sikachu**
This commit fixes #36313.

After #32065 moved `SourceAnnotationExtractor` into `Rails` module, it broke the ability to access `SourceAnnotationExtractor::Annotate` directly as user would get this error:

    TypeError: Rails::SourceAnnotationExtractor is not a class/module

This commit fixes the issue by making `DeprecatedConstantProxy` to inherit from `Module` and then defines `method_missing` and `const_missing` to retain the previous functionality.

Thank you @matthewd for the [idea](https://github.com/rails/rails/pull/32065#issuecomment-378794102) of how to fix the issue!

### CODE REVIEW

File: activesupport/lib/active_support/deprecation/proxy_wrappers.rb [hunk 1]
```diff
@@ -144,8 +159,15 @@ def target
           ActiveSupport::Inflector.constantize(@new_const.to_s)
         end
 
-        def warn(callstack, called, args)
-          @deprecator.warn(@message, callstack)
+        def const_missing(name)
+          if target.const_defined?(name)
+            ActiveSupport::Deprecation::DeprecatedConstantProxy.new("#{@old_const}::#{name}", "#{@new_const}::#{name}")
+          end
```
Comment (matthewd) [inline activesupport/lib/active_support/deprecation/proxy_wrappers.rb]: I don't feel strongly about it, but I was imagining this would do the same `@deprecator.warn` as `method_missing` (and then a `const_get`) -- so the message would still be talking about the renamed constant, rather than the child.

The only reason I think that might be important is if the child has itself been renamed or otherwise deprecated... perhaps better to complain that you meant `Deprecatee::New` over `Deprecatee::Old`, plus the second complaint that you accessed `Deprecatee::New::Descendant` when you should be using `Deprecatee::New::BetterDescendant`, instead of building a message that explicitly claims `Deprecatee::New::Descendant` is a new good thing. 

---

On a separate minor note, I think this should have an `else super`?

**Comment by sikachu** [comment]
@matthewd I use `@deprecator.warn` just like in `method_missing`, and use `const_get` as your feedback. I also added another test just to make sure we get both `NameError` and deprecation message when someone tries to access a constant that isn't exist on the new constant.

Would you mind taking another look and merge it if you think it's good to go?

File: activesupport/lib/active_support/deprecation/proxy_wrappers.rb [hunk 2]
```diff
@@ -120,7 +120,14 @@ def warn(callstack, called, args)
     #   # => DEPRECATION WARNING: PLANETS is deprecated! Use PLANETS_POST_2006 instead.
     #        (Backtrace information…)
     #        ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]
-    class DeprecatedConstantProxy < DeprecationProxy
+    class DeprecatedConstantProxy < Module
+      def self.new(*args, &block)
```
Comment (matthewd) [inline activesupport/lib/active_support/deprecation/proxy_wrappers.rb]: Is this needed?

`initialize`'s first argument is `old_const`, which is a string and should never be nil, so I don't think this method is necessary.

Comment (sikachu) [reply activesupport/lib/active_support/deprecation/proxy_wrappers.rb]: Yep, removed (was copied and paste from the `DeprecationProxy` class).

**Comment by sikachu** [comment]
I removed the `new` method. Ready for another look!

**Comment by sikachu** [comment]
@matthewd actually, removing that cause this test to fail:

https://github.com/rails/rails/blob/a59b2305792dd7012a8abc2e4b1a7d9037e8e208/activesupport/test/deprecation/proxy_wrappers_test.rb#L20-L23

So, I've brought back that `self.new` method to retain the functionality.

**Comment by matthewd** [comment]
I'll merge because this has been waiting on me for ages (🙈), but I think that's a bad test (this class expects to receive strings containing the old/new constant names, not actual constant references) and can be deleted.

**Comment by nvick** [comment]
🎉thanks to you all!
