### PR TITLE
Only enqueue analysis jobs when blob is analyzable

### LINKED ISSUE #37767: ActiveStorage should not create sidekiq jobs when there are no analyzers
My application stores a bunch of stuff with ActiveStorage. Because we treat it as a blob store, we do not use analyzers on this, and they are disabled in our config. However, I've started seeing a bunch of jobs in `active_storage_analysis`

### Steps to reproduce

1. Set `config.active_storage.analyzers.clear`
2. Use ActiveStorage
3. Observe `active_storage_analysis` jobs

### Expected behavior

Because there are no configured analyzers, I expect there to be no jobs enqued

### Actual behavior

Jobs are enqued. This can be a noticeable resource impact, and can slow down other parts of a job processing system.

### System configuration
```
ruby '2.6.3'
gem 'rails', '6.0.0'
```

### PR DESCRIPTION
**Pull request by gmcgibbon**
### Summary

Analyze inline when blob is analyzed with `NullAnalyzer`. I believe it is cheaper to do this as opposed to doing the no-op analysis in a job.

Fixes https://github.com/rails/rails/issues/37767.

### CODE REVIEW

File: activestorage/app/models/active_storage/attachment.rb [hunk 1]
```diff
@@ -36,7 +36,13 @@ def identify_blob
     end
 
     def analyze_blob_later
-      blob.analyze_later unless blob.analyzed?
+      return if blob.analyzed?
+
+      if blob.analyzable?
+        blob.analyze_later
+      else
+        blob.analyze
```
Comment (kaspth) [inline activestorage/app/models/active_storage/attachment.rb]: Don’t see the point of running analyze if the blob isn’t analyzable. Otherwise it shouldn’t be called analyzable because that’s not what it’s checking then.

File: activestorage/app/models/active_storage/attachment.rb [hunk 2]
```diff
@@ -36,7 +36,13 @@ def identify_blob
     end
 
     def analyze_blob_later
-      blob.analyze_later unless blob.analyzed?
```
Comment (kaspth) [inline activestorage/app/models/active_storage/attachment.rb]: Would think this would just be `blob.analyze_later if blob.analyzable? && !blob.analyzed?`?

File: activestorage/app/models/active_storage/blob/analyzable.rb [hunk 3]
```diff
@@ -42,6 +42,11 @@ def analyzed?
     analyzed
   end
 
+  # Returns true if the blob's analyzer isn't +ActiveStorage::Analyzer::NullAnalyzer+.
+  def analyzable?
+    analyzer_class != ActiveStorage::Analyzer::NullAnalyzer
```
Comment (kaspth) [inline activestorage/app/models/active_storage/blob/analyzable.rb]: Don’t think we’d need mention NullAnalyzer again for this. Can we split out the detect in analyzer_class or move the NullAnalyzer reference to analyzer?

File: activestorage/app/models/active_storage/attachment.rb (hunk 1 above)
Comment (gmcgibbon) [reply activestorage/app/models/active_storage/attachment.rb]: I was thinking from a data consistency perspective it would make sense to no-op analyze a blob that doesn't need analysis, but maybe not. I'll refactor to not run analysis at all and see what that looks like.

Comment (kaspth) [reply activestorage/app/models/active_storage/attachment.rb]: Seems like the question we want to ask them is about deferring the analyze and we’d need some structure around that.

Maybe `analyze_later?` and put that in analyze_later?

File: activestorage/app/models/active_storage/blob/analyzable.rb [hunk 4]
```diff
@@ -42,16 +42,21 @@ def analyzed?
...
     end
 
     def analyzer
-      analyzer_class.new(self)
+      (analyzer_class || ActiveStorage::Analyzer::NullAnalyzer).new(self)
     end
 
     def analyzer_class
-      ActiveStorage.analyzers.detect { |klass| klass.accept?(self) } || ActiveStorage::Analyzer::NullAnalyzer
+      ActiveStorage.analyzers.detect { |klass| klass.accept?(self) }
```
Comment (kaspth) [inline activestorage/app/models/active_storage/blob/analyzable.rb]: Think we should extract an `acceptable_analyzer_class` method instead of moving the NullAnalyzer into `analyzer`

`analyze_later?` would then be `acceptable_analyzer_class.present?`

File: activestorage/app/models/active_storage/blob/analyzable.rb [hunk 5]
```diff
@@ -42,16 +42,21 @@ def analyzed?
     analyzed
   end
 
+  # Returns true if the blob's analyzer is present.
+  def analyze_later?
+    analyzer_class.present?
+  end
```
Comment (kaspth) [inline activestorage/app/models/active_storage/blob/analyzable.rb]: Another thing we could try:

```ruby
def analyze_later
  if analyzer.analyze_later?
     ActiveStorage::AnalyzeJob.perform_later(self)
  else
    analyzer.analyze
  end
end
```

Comment (gmcgibbon) [reply activestorage/app/models/active_storage/blob/analyzable.rb]: I tried this approach and I think it is better. It gives us the option of enabling inline analysis for other analyzers and the logic is easier to follow.

**Review by kaspth — APPROVED** [review]
Perfect! I like how this matches the class level `accept?` nicely too.

**Review by georgeclaghorn — APPROVED** [review]
