### PR TITLE
Remove keys from local_cache in RedisCacheStore#delete_matched

### LINKED ISSUE #38627: `RedisCacheStore#delete_matched` doesn't play well with local cache
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem 'redis'
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_with_local_cache
    client = ActiveSupport::Cache::RedisCacheStore.new

    client.with_local_cache do
      client.write('my_key#123', 'xxx')
      client.delete_matched('my_key#*')

      # Passes
      assert client.send(:bypass_local_cache) { client.read('my_key#123') }.nil?

      # Fails
      assert client.read('my_key#123').nil?
    end
  end
end
```

### Expected behavior
Test should pass or at least rails should provide a way to handle that case without hacky `#send(:bypass_cache) { }`

### Actual behavior
Test fails, we're reading stale value from local cache.

### System configuration
**Rails version**: 6 & master

**Ruby version**: 2.7

### PR DESCRIPTION
**Pull request by ojab**
### Summary

Right now we're not deleting keys from local cache. Fixes #38627

### CODE REVIEW

**Review by rafaelfranca — CHANGES_REQUESTED** [review]
Same as https://github.com/rails/rails/pull/38630#pullrequestreview-368273868

**Comment by ojab** [comment]
@rafaelfranca hopefully fixed

**Comment by rafaelfranca** [comment]
Do we need to include a new private method? I think if we only define `delete_matched` in the local store calling super and clearing the cache is enough, like `increment` is doing. Have you tried that?

**Comment by ojab** [comment]
Yep, works too.

File: activesupport/lib/active_support/cache/strategy/local_cache.rb [hunk 1]
```diff
@@ -107,6 +107,11 @@ def cleanup(**options) # :nodoc:
           super
         end
 
+        def delete_matched(key, options = nil)
```
Comment (eugeneius) [inline activesupport/lib/active_support/cache/strategy/local_cache.rb:110]:
```suggestion
        def delete_matched(key, options = nil) # :nodoc:
```

File: activesupport/lib/active_support/cache/strategy/local_cache.rb [hunk 2]
```diff
@@ -107,6 +107,11 @@ def cleanup(**options) # :nodoc:
...
+          local_cache && local_cache.clear
```
Comment (eugeneius) [inline activesupport/lib/active_support/cache/strategy/local_cache.rb:111]: I think we should match the implementation of `clear` and `cleanup`, so it's easier to tell that they're doing the same thing:

```suggestion
          return super unless cache = local_cache
          cache.clear
```

File: activesupport/test/cache/behaviors/local_cache_behavior.rb [hunk 3]
```diff
@@ -102,6 +102,23 @@ def test_local_cache_of_delete
...
+      skip
+    end
+
+    @cache.with_local_cache do
+      @cache.write("foo", "bar")
+      @cache.write("fop", "bar")
+      @cache.write("bar", "foo")
+      @cache.delete_matched("fo*")
+      assert_nil @cache.read("foo")
+      assert_nil @cache.read("fop")
```
Comment (eugeneius) [inline activesupport/test/cache/behaviors/local_cache_behavior.rb:118]: Should we assert that non-matching keys can still be read correctly? Otherwise, why write `bar` to the cache at all?

```suggestion
      assert_nil @cache.read("fop")
      assert_equal "foo", @cache.read("bar")
```

File: activesupport/test/cache/stores/redis_cache_store_test.rb [hunk 4]
```diff
@@ -274,14 +274,6 @@ def emulating_unavailability
...
 
   class DeleteMatchedTest < StoreTest
-    test "deletes keys matching glob" do
-      @cache.write("foo", "bar")
-      @cache.write("fu", "baz")
-      @cache.delete_matched("foo*")
-      assert_not @cache.exist?("foo")
-      assert @cache.exist?("fu")
-    end
-
```
Comment (eugeneius) [inline activesupport/test/cache/stores/redis_cache_store_test.rb:284]: Why delete this test?

Comment (ojab) [reply activesupport/test/cache/stores/redis_cache_store_test.rb:284]: It's duplicated by the new test in local_cache_behavior.

File: activesupport/lib/active_support/cache/strategy/local_cache.rb [hunk 5]
```diff
@@ -107,6 +107,12 @@ def cleanup(**options) # :nodoc:
           super
         end
 
+        def delete_matched(key, options = nil) # :nodoc:
```
Comment (eugeneius) [inline activesupport/lib/active_support/cache/strategy/local_cache.rb:110]: I missed this last time, looks like the parameter is called `matcher` everywhere else:

```suggestion
        def delete_matched(matcher, options = nil) # :nodoc:
```

File: activesupport/test/cache/stores/redis_cache_store_test.rb (hunk 4 above)
Comment (eugeneius) [reply activesupport/test/cache/stores/redis_cache_store_test.rb:284]: The new test is wrapped in `with_local_cache`, which changes the behaviour of `delete_matched`. I'd like to keep the separate test coverage for `delete_matched` without the local cache, since the local cache is not always active (e.g. in jobs, or on the console).

**Review by eugeneius — COMMENTED** [review]
Could you add a changelog entry? It looks like https://github.com/rails/rails/pull/38630 had one you can reuse.

**Comment by eugeneius** [comment]
Thank you!
