### PR TITLE
Preserve readonly flag only for readonly association

### LINKED ISSUE #24093: Eager loaded belongs_to associations are always readonly
### Steps to reproduce

https://gist.github.com/bquorning/0ac738564824aa8ce57b

### Expected behavior

Eager loaded belongs_to associations should not be readonly.

### Actual behavior

Eager loaded belongs_to associations are always readonly.

### System configuration
**Rails version**: v5.0.0.beta1 and up, including latest master

**Ruby version**: All.

### Extra

It seems the issue was introduced in #18097.

### PR DESCRIPTION
**Pull request by k0kubun**
### Summary

I fixed a bug in https://github.com/rails/rails/pull/18097. See  #24093 for detail.
In this patch, I made eager-loaded association readonly only when it was specified as readonly.

Fixes #24093

### CODE REVIEW

File: activerecord/test/cases/associations/eager_test.rb [hunk 1]
```diff
@@ -1419,6 +1419,24 @@ def test_eager_load_multiple_associations_with_references
     assert david.readonly_comments.first.readonly?
   end
 
+  test "eager-loading non-readonly association" do
+    # has-one
```
Comment (maclover7) [inline activerecord/test/cases/associations/eager_test.rb]: has_one

File: activerecord/test/cases/associations/eager_test.rb [hunk 2]
```diff
@@ -1419,6 +1419,24 @@ def test_eager_load_multiple_associations_with_references
...
+    firm = Firm.where(id: "1").eager_load(:account).first!
+    assert_not firm.account.readonly?
+
+    # has_and_belongs_to_many
+    project = Project.where(id: "2").eager_load(:developers).first!
+    assert_not project.developers.first.readonly?
+
+    # has-many :through
```
Comment (maclover7) [inline activerecord/test/cases/associations/eager_test.rb]: has_many

File: activerecord/test/cases/associations/eager_test.rb (hunk 1 above)
Comment (k0kubun) [inline activerecord/test/cases/associations/eager_test.rb]: Fixed and squashed in https://github.com/k0kubun/rails/commit/ffd4b4bfb115a950cece40527fbed31ed39d8df0

File: activerecord/test/cases/associations/eager_test.rb (hunk 2 above)
Comment (k0kubun) [inline activerecord/test/cases/associations/eager_test.rb]: Fixed and squashed in https://github.com/k0kubun/rails/commit/ffd4b4bfb115a950cece40527fbed31ed39d8df0

File: activerecord/lib/active_record/associations/join_dependency.rb [hunk 3]
```diff
@@ -272,7 +272,11 @@ def construct(ar_parent, parent, row, rs, seen, model_cache, aliases)
             construct(model, node, row, rs, seen, model_cache, aliases)
           else
             model = construct_model(ar_parent, node, row, model_cache, id, aliases)
-            model.readonly!
+            join_scope = node.reflection.klass.unscoped
+            join_scope = join_scope.instance_exec(nil, &node.reflection.scope) if node.reflection.scope
+            if join_scope.values[:readonly]
+              model.readonly!
+            end
```
Comment (sgrif) [inline activerecord/lib/active_record/associations/join_dependency.rb]: This implementation is reaching into a lot of internals of other objects. Can you refactor this to something a bit more contained?

Comment (k0kubun) [inline activerecord/lib/active_record/associations/join_dependency.rb]: How about this? https://github.com/k0kubun/rails/commit/198b2856dbf00c3b6b57bccdf4daeeae62601cc3

**Comment by bquorning** [comment]
@sgrif Do you have time for a 2nd review? In my opinon, this (and #24093) should be added to [the 5.0.0 milestone](https://github.com/rails/rails/milestones/5.0.0).

**Comment by sgrif** [comment]
We are well beyond the feature freeze for the 5.0 milestone. This bug isn't critical enough to mark as a release blocker. It will be resolved in 5.0l.1

**Comment by bquorning** [comment]
@jeremy Do you want to add this PR to the 5.0.1 milestone, as per Sean’s comment above?

**Comment by maclover7** [comment]
Solves #25835 as well.

File: activerecord/lib/active_record/associations/join_dependency.rb [hunk 4]
```diff
@@ -272,7 +272,9 @@ def construct(ar_parent, parent, row, rs, seen, model_cache, aliases)
             construct(model, node, row, rs, seen, model_cache, aliases)
           else
             model = construct_model(ar_parent, node, row, model_cache, id, aliases)
-            model.readonly!
+            if node.reflection.scope_for(node.base_klass).values[:readonly]
```
Comment (kamipo) [inline activerecord/lib/active_record/associations/join_dependency.rb]: `values` dup new Hash. It is better to use `readonly_value`.
https://github.com/rails/rails/blob/v5.0.0/activerecord/lib/active_record/relation.rb#L678-L680
https://github.com/rails/rails/blob/v5.0.0/activerecord/lib/active_record/relation/query_methods.rb#L73-L75

Comment (k0kubun) [inline activerecord/lib/active_record/associations/join_dependency.rb]: Thanks to catch it. Fixed so in https://github.com/rails/rails/pull/24099/commits/411e4597d552aa091cfe3dc76a83bdaffe02da1a.

**Comment by johanlunds** [comment]
Just FYI, to help someone else running into this in the meantime: our workaround was to `.reload` the record before updating it.

**Comment by rafaelfranca** [comment]
Backported in 3cffae5
