### PR TITLE
`NumberHelper`: handle very large numbers

### LINKED ISSUE #49461: ActiveSupport::NumberHelper number_to_currency loss of precision in Rails 7.x
### Steps to reproduce
```
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"
require 'action_view'

  
class BugTest < Minitest::Test
include ActionView::Helpers::NumberHelper
  
  def test_large_number_to_currency
    large_string = "123456789012345678.91"
    
    assert "$123,456,789,012,345,678.91" == number_to_currency(large_string, locale: :en)
  end
end
```

or manually in console:
```
> include ActionView::Helpers::NumberHelper
> large_string = "123456789012345678.91"
> large_bd = BigDecimal(large_string)

> number_to_currency(large_string, locale: :en)
=> "$123,456,789,012,345,680.00"
> number_to_currency(large_bd, locale: :en)
=> "$123,456,789,012,345,680.00"
```

### Expected behavior
```
# (Rails 6.1.7.6)
> include ActionView::Helpers::NumberHelper
=> Object
> large_string = "123456789012345678.91"
=> "123456789012345678.91"
> large_bd= BigDecimal(large_string)
=> 0.12345678901234567891e18

> number_to_currency(large_string, locale: :en)
=> "$123,456,789,012,345,678.91"
> number_to_currency(large_bd, locale: :en)
=> "$123,456,789,012,345,678.91"
```

### Actual behavior
```
# (Rails 7.0.8)
> include ActionView::Helpers::NumberHelper
=> Object
> large_string = "123456789012345678.91"
=> "123456789012345678.91"
> large_bd = BigDecimal(large_string)
=> 0.12345678901234567891e18

> number_to_currency(large_string, locale: :en)
=> "$123,456,789,012,345,680.00"
> number_to_currency(large_bd, locale: :en)
=> "$123,456,789,012,345,680.00"

```

Starting in Rails 7, precision is limited to 17 leftmost digits. Previously string and BigDecimal input values with more precision were preserved.

https://github.com/rails/rails/pull/43098 looks like where the change in behavior was introduced possibly with `valid_float?` always performing a float conversion.

### System configuration
**Rails version**: Rails 7.0.8

**Ruby version**: ruby 3.1.3p185

### PR DESCRIPTION
**Pull request by ghiculescu**
Fixes https://github.com/rails/rails/issues/49461

Added @fatkodima as co-author.

### CODE REVIEW

File: activesupport/lib/active_support/number_helper/number_converter.rb [hunk 1]
```diff
@@ -173,8 +175,13 @@ def default_value(key)
...
 
-        def valid_float?
-          Float(number, exception: false)
+        def valid_bigdecimal
+          case number
+          when Float, Rational
+            number.to_d(0)
+          else
+            BigDecimal(number, exception: false)
+          end
```
Comment (ghiculescu) [inline activesupport/lib/active_support/number_helper/number_converter.rb:184]: This is the big fix. The other changes are because this method was renamed since its return type was changed.

Comment (willcosgrove) [reply activesupport/lib/active_support/number_helper/number_converter.rb:184]: Would there be a problem with something like this?
```suggestion
          case number
          when Float, Rational
            number.to_d(0)
          else
            number.to_d rescue nil
          end
```

I recently ran into a problem where I'm using a ["lazy object"](https://github.com/HornsAndHooves/lazy_object) that gets passed to a number helper. Previously this worked fine, but now `BigDecimal()` is not converting the object, because it sees the number as a `LazyObject` instead of the nested object being delegated to.

If my object was sent `to_d`, it would behave as expected. Interestingly, `Float(lazy_object)` works, but `BigDecimal(lazy_object)` does not.

Comment (fatkodima) [reply activesupport/lib/active_support/number_helper/number_converter.rb:184]: Can you define `to_str` on you object and try to see if it works? As per documentation https://ruby-doc.org/stdlib-3.1.1/libdoc/bigdecimal/rdoc/Kernel.html#method-i-BigDecimal

Comment (willcosgrove) [reply activesupport/lib/active_support/number_helper/number_converter.rb:184]: Since the lazy object wraps an Integer, I would need to define to_str on Integer which I would prefer not to do. I will just change my code to not give the number helper a lazy object, since I'm sure this is not going to impact many other people.
