### PR TITLE
Fix parsing of jsonified expiry date on AS::Message::Metadata for old json format

### LINKED ISSUE #39548: ActiveSupport::MessageVerifier is broken if `ActiveSupport.use_standard_json_time_format = false`
This PR https://github.com/rails/rails/pull/37983

specifically this line: https://github.com/rails/rails/commit/557dbcf1ed5a73420fb41f5899bce28ef0a21373#diff-a40dd89507c50053b464ecefd717f343R10

assumes that `expires_at` is in ISO 8601 format.
However, it isn't always this case if `ActiveSupport.use_standard_json_time_format = false` because `Time#as_json` would return a non ISO 8601 string thus breaking the message verifier.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'activesupport', '6.0.3'
end

require 'active_support'
require 'active_support/core_ext/object/blank'
require 'active_support/json'
require 'minitest/autorun'

class MessageVerifierTest < Minitest::Test
  def test_message_verifier
    ActiveSupport.use_standard_json_time_format = false
    verifier = ActiveSupport::MessageVerifier.new("Hey, I'm a secret!")

    assert_equal 'hi', verifier.verify(verifier.generate('hi', expires_at: Time.now.utc + 10))
  end
end

```

### Expected behavior
It works.

### Actual behavior
It raises an exception:

```
Minitest::UnexpectedError: ArgumentError: invalid date: "2020/06/05 17:44:39 +0000
```

### System configuration
**Rails version**: 6.0.3

**Ruby version**: 2.6.3

### PR DESCRIPTION
**Pull request by vipulnsward**
Fix parsing of jsonified expiry date when on AS::Message::Metadata, when `ActiveSupport.use_standard_json_time_format = false`

Fixes #39548

cc @kaspth

### CODE REVIEW

File: activesupport/lib/active_support/messages/metadata.rb [hunk 1]
```diff
@@ -67,6 +67,14 @@ def match?(purpose)
         def fresh?
           @expires_at.nil? || Time.now.utc < @expires_at
         end
+
+        def parse_expires_at(expires_at)
+          if ActiveSupport.use_standard_json_time_format
+            Time.iso8601(expires_at)
+          else
+            Time.parse(expires_at)
+          end
```
Comment (allolex) [inline activesupport/lib/active_support/messages/metadata.rb:76]: You might consider reducing complexity by having your parse method handle whatever value is being assigned.

```ruby
          return expires_at unless expires_at.is_a?(String)
          return Time.iso8601(expires_at) if ActiveSupport.use_standard_json_time_format
          Time.parse(expires_at)
```

Comment (vipulnsward) [reply activesupport/lib/active_support/messages/metadata.rb:76]: I thought about it, in most cases `ActiveSupport.use_standard_json_time_format` would be `true`, it's better to short-circuit above, instead of passing it here.

Comment (mechanicles) [reply activesupport/lib/active_support/messages/metadata.rb:76]: @allolex No. The implemented version looks simple to read.

**Comment by wpliao1989** [comment]
Should we reopen this?

**Comment by wpliao1989** [comment]
What's the status on this PR? Can I do anything to push this forward? This is blocking us from 6.0.3 and beyond for security patches.
