### PR TITLE
Time columns should support time zone aware attributes

### LINKED ISSUE #3145: Time is created in UTC with local time
When a Model is created using the mass assignment, and the model has a time attribute.

The Time attribute is created in local time but with UTC time zone even with config.time_zone properly setted.

I was studying this wrong behavior and guess that the error is here:

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb#L62

As you can see, in the line 62 it only consider :datetime and :timestamp. it does not consider :time to be timezone aware.

### PR DESCRIPTION
**Pull request by sgrif**
The types that are affected by `time_zone_aware_attributes` (which is on by default) have been made configurable, in case this not the desired behavior for existing applications.

Fixes #3145

### CODE REVIEW

File: activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb [hunk 1]
```diff
@@ -59,9 +62,31 @@ def inherited(subclass)
...
+          result = enabled_for_column &&
+            time_zone_aware_types.include?(cast_type.type)
+
+          if enabled_for_column &&
+            !result &&
+            cast_type.type == :time &&
+            time_zone_aware_types.include?(:not_explicitly_configured)
+            ActiveSupport::Deprecation.warn(<<-MESSAGE)
+              Time columns will become time zone aware in Rails 5.1. This
+              sill cause `String`s to be parsed as if they were in `Time.zone`,
```
Comment (henrik) [inline activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb]: Typo: sill

File: activerecord/test/cases/multiparameter_attributes_test.rb [hunk 2]
```diff
@@ -250,8 +250,8 @@ def test_multiparameter_attributes_on_time_only_column_with_time_zone_aware_attr
         }
         topic = Topic.find(1)
         topic.attributes = attributes
-        assert_equal Time.utc(2000, 1, 1, 16, 24, 0), topic.bonus_time
-        assert topic.bonus_time.utc?
+        assert_equal Time.zone.local(2000, 1, 1, 16, 24, 0), topic.bonus_time
+        assert_not topic.bonus_time.utc?
```
Comment (henrik) [inline activerecord/test/cases/multiparameter_attributes_test.rb]: I might be misunderstanding things, but won't this assertion fail if someone runs this test on a UTC machine?

**Comment by tehransenf** [comment]
Good content it was very benefical thanks a lot
https://www.itelegram.org telegram news

**Comment by tehransenf** [comment]
Great article thanks a lot

<a href="https://www.itelegram.org/index.php/contact-us/blog/68-2017-10-03-09-54-12">افزایش ممبر واقعی تلگرام</a> 
<a href="https://www.itelegram.org">خرید ممبر تلگرام</a>
<a href="https://www.itelegram.org/index.php/contact-us/blog/69-2017-10-11-19-15-30   ">افزایش ممبر تلگرام</a>
<a href="https://www.itelegram.org/index.php/contact-us/blog/70-2017-10-11-19-27-08  ">افزایش ممبر ایرانی کانال تلگرام</a>
<a href="https://www.itelegram.org">خرید ممبر کانال تلگرام</a>
<a href="https://www.itelegram.org">خرید ممبر</a>
