### PR TITLE
Fix `undefined method uncached` for polymorphic belongs_to #20426

### LINKED ISSUE #20426: undefined method `uncached' on empty polymorphic belongs_to with force_reload
when calling the association method with `force_reload: true` on a uninitialized belongs_to association a `NoMethodError` is raised in `singular_association.rb:7` [1]

Other than a comment on an old issue refering to this line (#2386) I couldn't find anything useful on this issue. The error could be reproduced with Rails v4.1.10, v4.2.0 and master.

Any thoughts?

[1] Test case
```ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', github: 'rails/rails'
    gem 'arel', github: 'rails/arel'
    gem 'sqlite3'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true  do |t|
  end

  create_table :comments, force: true  do |t|
    t.references :commentable, polymorphic: true, index: true
  end
end

class Post < ActiveRecord::Base
  has_one :comment, as: :commentable
end

class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

class BugTest < Minitest::Test
  def test_belongs_to_force_reload_nil
    assert_equal Comment.new.commentable(force_reload: true), nil
  end
end
```

[2] output
```
bakki :: devel/rails > ruby has_one_force_reload_nil_test.rb                                                                                                              1
-- create_table(:posts, {:force=>true})
D, [2015-06-03T21:20:08.012423 #32623] DEBUG -- :    (0.3ms)  CREATE TABLE "posts" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)
   -> 0.0082s
-- create_table(:comments, {:force=>true})
D, [2015-06-03T21:20:08.013247 #32623] DEBUG -- :    (0.1ms)  CREATE TABLE "comments" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "commentable_type" varchar, "commentable_id" integer)
D, [2015-06-03T21:20:08.036462 #32623] DEBUG -- :    (0.1ms)  select sqlite_version(*)
D, [2015-06-03T21:20:08.036967 #32623] DEBUG -- :    (0.1ms)  CREATE  INDEX "index_comments_on_commentable_type_and_commentable_id" ON "comments" ("commentable_type", "commentable_id")
   -> 0.0244s
Run options: --seed 39301

# Running:

E

Finished in 0.009509s, 105.1660 runs/s, 0.0000 assertions/s.

  1) Error:
BugTest#test_has_one_force_reload_nil:
NoMethodError: undefined method `uncached' for nil:NilClass
    /Users/sdecaste/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-ae5f2b4e79f3/activerecord/lib/active_record/associations/singular_association.rb:7:in `reader'
    /Users/sdecaste/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-ae5f2b4e79f3/activerecord/lib/active_record/associations/builder/association.rb:111:in `commentable'
    has_one_force_reload_nil_test.rb:42:in `test_has_one_force_reload_nil'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

### PR DESCRIPTION
**Pull request by jamesdabbs**
Closes #20426

Unitialized polymorphic `belongs_to` associations raise an error while attempting to reload, as they attempt to make an uncached reload, but don't have a klass to fetch uncachedly.

As best I can tell, this is the only case where `klass` might be `nil` [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/singular_association.rb#L7), and in this case there's no cache to bypass. It's unclear to me whether it's better to fall through to `reload` here (which _is_ safe - it [notices it doesn't have a key](https://github.com/rails/rails/blob/3e36db4406beea32772b1db1e9a16cc1e8aea14c/activerecord/lib/active_record/associations/association.rb#L176), and doesn't make a query) or not.

Feedback or logic check 100% welcome. First Rails PR here, so be gentle.

### CODE REVIEW

File: activerecord/lib/active_record/associations/singular_association.rb [hunk 1]
```diff
@@ -3,7 +3,7 @@ module Associations
     class SingularAssociation < Association #:nodoc:
       # Implements the reader method, e.g. foo.bar for Foo.has_one :bar
       def reader(force_reload = false)
-        if force_reload
+        if force_reload && klass
```
Comment (arthurnn) [inline activerecord/lib/active_record/associations/singular_association.rb]: I think the problem now, is that instead of getting the error, the `force_reload` will not work for `polymorphic`. as it will not call `reload`.

Comment (jamesdabbs) [inline activerecord/lib/active_record/associations/singular_association.rb]: It is entirely possible I'm being dense here, but if the polymorphic
association hasn't set a `klass`, then what is there to reload? Shouldn't
the reader always return `nil` in that case?

**Comment by senny** [comment]
looks like a reasonable fix to me. I added an entry to the changelog in the merge commit (https://github.com/rails/rails/commit/5e75f51692cc92ad346fecc4a63fa628c8024149).

@jamesdabbs thank you :yellow_heart:
