### PR TITLE
Stop generating bundler binstub:

### LINKED ISSUE #54563: `AuthenticationGeneratorTest#test_authentication_generator_without_bcrypt_in_gemfile` fails with ruby 3.5.0dev at 8-0-stable branch
Managed to reproduce CI failure https://buildkite.com/rails/rails-nightly/builds/1743#0194e34b-f698-4d98-bab0-b33a54988830

### Steps to reproduce
- Install Ruby master branch
- Run these steps
```ruby
git clone https://github.com/rails/rails
cd rails
git checkout 8-0-stable
bundle update --bundler
bundle install
cd railties
bin/test test/generators/authentication_generator_test.rb -n test_authentication_generator_without_bcrypt_in_gemfile
```

### Expected behavior
It should pass.

### Actual behavior

```ruby
$ bundle update --bundler
$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 0f74cc00ee..b983513184 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -727,4 +727,4 @@ DEPENDENCIES
   websocket-client-simple

 BUNDLED WITH
-   2.5.16
+   2.7.0.dev
$ bin/test test/generators/authentication_generator_test.rb -n test_authentication_generator_without_bcrypt_in_gemfile
... snip ...
F

Failure:
AuthenticationGeneratorTest#test_authentication_generator_without_bcrypt_in_gemfile [test/generators/authentication_generator_test.rb:67]:
Expected /\ngem "bcrypt"/ to match "source \"https://rubygems.org\"\n\n# Bundle edge Rails instead: gem \"rails\", github: \"rails/rails\", branch: \"main\"\ngem \"rails\", \"~> 8.0.1\"\n# The modern asset pipeline for Rails [https://github.com/rails/propshaft]\ngem \"propshaft\"\n# Use sqlite3 as the database for Active Record\ngem \"sqlite3\", \">= 2.1\"\n# Use the Puma web server [https://github.com/puma/puma]\ngem \"puma\", \">= 5.0\"\n# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]\ngem \"importmap-rails\"\n# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]\ngem \"turbo-rails\"\n# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]\ngem \"stimulus-rails\"\n# Build JSON APIs with ease [https://github.com/rails/jbuilder]\ngem \"jbuilder\"\n\n# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]\n\n# Windows does not include zoneinfo files, so bundle the tzinfo-data gem\ngem \"tzinfo-data\", platforms: %i[ windows jruby ]\n\n# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable\ngem \"solid_cache\"\ngem \"solid_queue\"\ngem \"solid_cable\"\n\n# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]\ngem \"kamal\", require: false\n\n# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]\ngem \"thruster\", require: false\n\n# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]\n# gem \"image_processing\", \"~> 1.2\"\n\ngroup :development, :test do\n  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem\n  gem \"debug\", platforms: %i[ mri windows ], require: \"debug/prelude\"\n\n  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]\n  gem \"brakeman\", require: false\n\n  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]\n  gem \"rubocop-rails-omakase\", require: false\nend\n\ngroup :development do\n  # Use console on exceptions pages [https://github.com/rails/web-console]\n  gem \"web-console\"\nend\n\ngroup :test do\n  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]\n  gem \"capybara\"\n  gem \"selenium-webdriver\"\nend\n".


bin/test test/generators/authentication_generator_test.rb:62



Finished in 32.881722s, 0.0304 runs/s, 0.0912 assertions/s.
1 runs, 3 assertions, 1 failures, 0 errors, 0 skips
$
```

### System configuration

**Rails version**:  8-0-stable branch. It does not reproduce at main branch

**Ruby version**:  ruby 3.5.0dev (2025-02-18T12:09:06Z master e9ba334fd1) +PRISM [x86_64-linux]

### PR DESCRIPTION
**Pull request by Edouard-chin**
### Motivation / Background

- Fix #54563
- Prevent `rails new` from throwing a warning and `bin/rails g authentication` from crashing when Bundler cuts a new release.

### Detail

In a future version of Bundler, running `bundle binstub bundler` will no longer generate a `bin/bundle` binstub. The reason for this change upstream is well explained in https://github.com/rubygems/rubygems/pull/8345.

#### Problem

When the change in Bundler is cut into a release, generating new rails application will throw a Bundler warning, and the AuthenticationGenerator which makes use of `bin/bundle` will stop working.

#### Solution

Stop generating a bundler binstub and modify the generator to use the same bundler command as the rest of the codebase.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: railties/lib/rails/generators/rails/authentication/authentication_generator.rb [hunk 1]
```diff
@@ -42,9 +46,9 @@ def configure_authentication_routes
       def enable_bcrypt
         if File.read(File.expand_path("Gemfile", destination_root)).include?('gem "bcrypt"')
           uncomment_lines "Gemfile", /gem "bcrypt"/
-          Bundler.with_original_env { execute_command :bundle, "install --quiet" }
```
Comment (Edouard-chin) [inline railties/lib/rails/generators/rails/authentication/authentication_generator.rb:45]: Worth to note that `execute_command` is public API, and if an application generator was doing `execute_command(:bundle)`, then this will no longer work (as `bin/bundle` will no longer exist).

However, in the documentation of `execute_command` it is mentioned that only `rails` or `rake` can be used. 
https://github.com/rails/rails/blob/0f9de98e869e82b726c0da62d9e5e36c2b0e9d8e/railties/lib/rails/generators/actions.rb#L458-L460

**Review by skipkayhil — APPROVED** [review]

File: railties/lib/rails/generators/rails/authentication/authentication_generator.rb (hunk 1 above)
Comment (kamipo) [reply railties/lib/rails/generators/rails/authentication/authentication_generator.rb:45]: I don't think it was intentional that these private methods were leaked into the API doc.

These were originally protected methods, and protected methods were leaked into the API doc whether intended or not.

When we changed the visibility of these methods to private, `# :doc:` was added to keep them visible to the API doc. d1daf4c31301f5f5917b877fd63a817f5f4608ed

**Comment by Edouard-chin** [comment]
Thanks!
