### PR TITLE
Fix ActiveRecord grouped calculations on joined tables on column present in both tables

### LINKED ISSUE #46892: Group by using a joined table column with the same name as a enum column fails
### Steps to reproduce
```ruby
class Customer < ActiveRecord::Base
  enum status %i[active slipping lost recovered]
  has_many :purchases
end

class Purchase < ActiveRecord::Base
  belongs_to :customer
  status :string
end
```
`purchases` table

| id | customer_id | status |
| :-: |       :------:     |    :-:    |
| 1 | 1 | shipped |
| 2 | 1 | shipped |
| 3 | 2 | delivered |
| 4 | 2 | returned |
| 5 | 1 | delivered |

### Expected behavior
```
Customer.joins(:purchases).group("purchases.status").count

{ "shipped" => 2, "delivered" => 2, "returned" => 1 }
```

### Actual behavior
```
{ nil => 5 }
```

### System configuration
**Rails version**:
6.1.7
**Ruby version**:
2.7

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #46892.

The previous logic always used a root class (`klass`) from the relation to get the column type, which is incorrect and the class from where that column came from should be used. 
Similar solution (`column.try(:type_caster)`) is used in many other places through the `calculations.rb` file.

### CODE REVIEW

File: activerecord/lib/active_record/relation/calculations.rb [hunk 1]
```diff
@@ -491,9 +491,10 @@ def execute_grouped_calculation(operation, column_name, distinct) # :nodoc:
           end
 
           key_types = group_columns.each_with_object({}) do |(aliaz, col_name), types|
-            types[aliaz] = type_for(col_name) do
-              calculated_data.column_types.fetch(aliaz, Type.default_value)
-            end
+            types[aliaz] = col_name.try(:type_caster) ||
```
Comment (byroot) [inline activerecord/lib/active_record/relation/calculations.rb:494]: Hum, I prefer to avoid `.try` as it's a huge footgun.

I'm not sure I fully understand the patch here. Is `col_name` expected to be `nil` or to be a type that doesn't implement `#type_caster`?

Comment (fatkodima) [reply activerecord/lib/active_record/relation/calculations.rb:494]: > Is col_name expected to be nil or to be a type that doesn't implement #type_caster?

This. It could be a string.

Comment (byroot) [reply activerecord/lib/active_record/relation/calculations.rb:494]: Ok. Can we use a `case / when String / else` instead?

Comment (byroot) [reply activerecord/lib/active_record/relation/calculations.rb:494]: Ah wait, I missed the:

>  (column.try(:type_caster)) is used in many other places through the calculations.rb file.

Let's keep it consistent we can refactor later. SOrry.

**Comment by byroot** [comment]
Thank you!
