### PR TITLE
[ci skip] fix the `collection.clear` guide

### LINKED ISSUE #20170: Wrong documentation (or implementation) of has_many clear
the documentation for Rails 4.1.7 specifies that the method clear:
> Removes every object from the collection. This destroys the associated objects if they are associated with dependent: :destroy

However, given that ActiveRecord::Associations::CollectionProxy#clear simply delegates to delete_all and with the change to the implementation of delete_all this is no longer tru:
> Removes all records from the association without calling callbacks on the associated records. It honors the :dependent option. However if the :dependent value is :destroy then in that case the  :delete_all deletion strategy for the association is applied.

This may be an error in the documentation that needs to be updated, or an undesired effect of the new implementation of delete_all. I personally think that clear should keep honoring the dependent :destroy flag, for backwards compatibility among other reasons.

### PR DESCRIPTION
**Pull request by repinel**
Improve the guide about `has_many` `collection.clear` to indicate the behavior for each dependent strategy according to `collection.delete_all`.

Based on #17179, I changed the `collection.delete` docs to also clarify the default strategy for each `hm` and `hm:t` associations.

Fixes #20170.

### CODE REVIEW

File: activerecord/lib/active_record/associations/collection_proxy.rb [hunk 1]
```diff
@@ -470,15 +470,15 @@ def destroy_all
...
-      # +has_many+ associations, the deletion is done according to the strategy
-      # specified by the <tt>:dependent</tt> option. Returns an array with the
-      # deleted records.
-      #
-      # If no <tt>:dependent</tt> option is given, then it will follow the default
-      # strategy. The default strategy is <tt>:nullify</tt>. This sets the foreign
-      # keys to <tt>NULL</tt>. For, +has_many+ <tt>:through</tt>, the default
-      # strategy is +delete_all+.
+      # Deletes the +records+ supplied from the collection according to the strategy
+      # specified by the +:dependent+ option. If no +:dependent+ option is given,
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/associations/collection_proxy.rb]: I think it needs to use `<tt>` for symbols

File: activerecord/lib/active_record/associations/collection_proxy.rb [hunk 2]
```diff
@@ -470,15 +470,15 @@ def destroy_all
...
+      # then it will follow the default strategy.
+      #
+      # For +has_many :through+ associations, the default deletion strategy is
+      # +:delete_all+.
+      #
+      # For +has_many+ associations, the default deletion strategy is +:nullify+.
+      # This sets the foreign keys to +NULL+.
       #
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/associations/collection_proxy.rb]: We need to talks about the return since it was removed from the original text

File: activerecord/lib/active_record/associations/collection_proxy.rb (hunk 1 above)
Comment (repinel) [inline activerecord/lib/active_record/associations/collection_proxy.rb]: `echo "+:dependent+" | rdoc --pipe` still outputs `<p><code>:dependent</code></p>`

Comment (rafaelfranca) [inline activerecord/lib/active_record/associations/collection_proxy.rb]: For `delete_all` too?

Comment (repinel) [inline activerecord/lib/active_record/associations/collection_proxy.rb]: Yes, for `+:delete_all+` using the same idea you get `<p><code>:delete_all</code></p>`.

File: activerecord/lib/active_record/associations/collection_proxy.rb (hunk 2 above)
Comment (repinel) [inline activerecord/lib/active_record/associations/collection_proxy.rb]: The statement should be back.

**Comment by repinel** [comment]
@rafaelfranca Thanks for reviewing!
