### PR TITLE
Fix polymorphic `belongs_to` to correctly use parent's `query_constraints`

### LINKED ISSUE #50315: Polymorphic association in model with query constraints pointing to incorrect records
### Steps to reproduce

While working on #50297 I found another bug related to query constraints for Polymorphic associations. I am looking into this but I created an issue here as I suspect there might be similar issues related to the usage of Query constraints.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', '7.1'
  gem 'sqlite3'
  gem 'pry'
end

require "active_record"
require "logger"
require 'minitest/autorun'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  create_table :comments, force: true do |t|
    t.integer :tenant_id
    t.references :commentable, polymorphic: true, null: false
    t.string :body
    t.integer :position
  end

  create_table :authors, force: true do |t|
    t.integer :tenant_id
  end
end

class Author < ActiveRecord::Base
  query_constraints :tenant_id, :id

  has_many :comments, as: :commentable
end 

class Comment < ActiveRecord::Base
  query_constraints :tenant_id, :id

  belongs_to :commentable, polymorphic: true
end

class BugTest < Minitest::Test
  # Case when Author with tenant_id exists
  def test_when_id_exists
    author_1 = Author.create!(tenant_id: 1)
    author_2 = Author.create!(tenant_id: 1)
    comment = Comment.create(tenant_id: 1, commentable_id: author_2.id, commentable_type: 'Author')

    # BUG: Makes a query with tenant_id
    assert_equal author_2.id, comment.commentable.id 
  end

  # Case when Author with tenant_id does not exist
  def test_when_id_does_not_exist
    author = Author.create!(tenant_id: 11)
    comment = Comment.create(tenant_id: 11, commentable_id: author.id, commentable_type: 'Author')

    assert_equal author.id, comment.commentable&.id 
  end
end
```

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 2.7.8

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #50315.

For polymorphic association with query constraints, we get incorrect value for primary key (specifically, `"id"` in the referenced issue) here
https://github.com/rails/rails/blob/5c4a7a711068c1dff2bd873da510ddbb82dcadd7/activerecord/lib/active_record/reflection.rb#L870-L882

which then incorrectly matches with foreign key (specifically, `["tenant_id", "commentable_id"]` in the referenced issue) here https://github.com/rails/rails/blob/5c4a7a711068c1dff2bd873da510ddbb82dcadd7/activerecord/lib/active_record/associations/association_scope.rb#L58-L63

With this change, `association_primary_key` now correctly returns `["tenant_id", "id"]`.

### CODE REVIEW

File: activerecord/lib/active_record/reflection.rb [hunk 1]
```diff
@@ -870,7 +870,7 @@ def association_class
       def association_primary_key(klass = nil)
         if primary_key = options[:primary_key]
           @association_primary_key ||= -primary_key.to_s
-        elsif !polymorphic? && ((klass || self.klass).has_query_constraints? || options[:query_constraints])
+        elsif (klass || self.klass).has_query_constraints? || options[:query_constraints]
```
Comment (eileencodes) [inline activerecord/lib/active_record/reflection.rb:873]: Hrm, I originally added the `!polymorphic?` check because `klass` can't always be computed on those associations, but this seems to be working fine based on the tests.

**Comment by eileencodes** [comment]
Thanks @fatkodima - I backported this to 7-1-stable in 59e72b0b69a8dd3b91a52232ba77c9ce60b28289
