### PR TITLE
Run inline jobs in separate threads

### LINKED ISSUE #37526: Inline ActiveJob clears `CurrentAttributes` erroneously
### Steps to reproduce

1. Set a value during seeding in a class that inherits from `ActiveSupport::CurrentAttributes`
2. Run code that enqueues a job via `ActiveJob` (e.g. uploading a file via `ActiveStorage`)
3. Note that the value from step 1 is cleared

Because the database is [seeded with the inline adapter](https://github.com/rails/rails/pull/34953), jobs run inline in seeding. When the job is run, the executor [resets all current attributes](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/railtie.rb#L23). Here's [a commit](https://github.com/jpcody/activejob-currentattributes/commit/4363b36277950bc79a06ff2dfa0142ed91eee4bd) that exhibits the issue.

In my app, I'm iterating over customers and seeding a logo for each then seeding users for each. The iteration uses `Current.set(customer: customer) { yield }`, and within the yield we attach a logo. After that logo is attached, `Current.customer` is reset to nil because `ActiveStorage::AnalyzeJob.perform_later(self)` runs .

### Expected behavior
Jobs run inline should not clear `CurrentAttributes`.

### Actual behavior
`CurrentAttributes` are cleared.

### System configuration
**Rails version**: Rails 6.0.0
**Ruby version**: ruby 2.6.5p114

### PR DESCRIPTION
**Pull request by gmcgibbon**
### Summary

Closes https://github.com/rails/rails/issues/37526.

Runs inline jobs in separate threads so that thread locals (eg. current attributes) are properly scoped and reset when running jobs inline.

### CODE REVIEW

**Review by kaspth — APPROVED** [review]

File: activejob/test/integration/queuing_test.rb [hunk 1]
```diff
@@ -145,4 +146,12 @@ class QueuingTest < ActiveSupport::TestCase
     assert job_executed "#{@id}.2"
     assert job_executed_at("#{@id}.2") < job_executed_at("#{@id}.1")
   end
+
+  test "inline jobs run on separate threads" do
+    skip unless adapter_is?(:inline)
+
+    assert_nil Thread.current[:job_ran]
+    ThreadJob.perform_later
+    assert_nil Thread.current[:job_ran]
```
Comment (eileencodes) [inline activejob/test/integration/queuing_test.rb]: I think this test needs 2 threads to test that threading is working correctly. Otherwise you just have one thread and it will always pass regardless of the Thread.new block

Comment (gmcgibbon) [reply activejob/test/integration/queuing_test.rb]: I agree this test could be better. I tried inspecting the thread spun up by the inline adapter, but `Thread.list` doesn't show it because it dies immediately after joining. How can I use two threads to make this test better?

Comment (Edouard-chin) [reply activejob/test/integration/queuing_test.rb]: That should do it

```diff
diff --git a/activejob/test/integration/queuing_test.rb b/activejob/test/integration/queuing_test.rb
index 7c92496331..a7d3865c42 100644
--- a/activejob/test/integration/queuing_test.rb
+++ b/activejob/test/integration/queuing_test.rb
@@ -150,8 +150,15 @@ class QueuingTest < ActiveSupport::TestCase
   test "inline jobs run on separate threads" do
     skip unless adapter_is?(:inline)

-    assert_nil Thread.current[:job_ran]
+    t1 = Thread.new do
+      ThreadJob::LatchManager.latch1.wait
+      assert_nil Thread.current[:job_ran]
+      assert(ThreadJob::LatchManager.job_thread[:job_ran])
+      ThreadJob::LatchManager.latch2.count_down
+    end
+
     ThreadJob.perform_later
+    t1.join
     assert_nil Thread.current[:job_ran]
   end
 end
diff --git a/activejob/test/jobs/thread_job.rb b/activejob/test/jobs/thread_job.rb
index 804d18b4a9..27218760a0 100644
--- a/activejob/test/jobs/thread_job.rb
+++ b/activejob/test/jobs/thread_job.rb
@@ -1,7 +1,24 @@
 # frozen_string_literal: true

 class ThreadJob < ActiveJob::Base
+  class LatchManager
+    class << self
+      attr_accessor :job_thread
+
+      def latch1
+        @@latch1 ||= Concurrent::CountDownLatch.new
+      end
+
+      def latch2
+        @@latch2 ||= Concurrent::CountDownLatch.new
+      end
+    end
+  end
+
   def perform
     Thread.current[:job_ran] = true
+    LatchManager.job_thread = Thread.current
+    LatchManager.latch1.count_down
+    LatchManager.latch2.wait
   end
 end
```

**Comment by sedubois** [comment]
This seems to cause newly persisted resources not to be visible in the inline job:

https://github.com/rails/rails/issues/40552#issuecomment-723148216
