### PR TITLE
Don't skip some columns in `column_types` on Postgres

### LINKED ISSUE #41651: ActiveRecord::Result#column_types is often missing data
### Regression in ActiveRecord::Result column_types

In my app (which uses PostgreSQL) I have several reporting features that construct TEMP DB views on the fly and query them with ActiveRecord's `exec_query` functionality. When I run these queries, I depend upon the values in the `column_types` attribute of the [ActiveRecord::Result object ](https://api.rubyonrails.org/classes/ActiveRecord/Result.html) to contain all of the column names and associated types.

After upgrading to Rails 6.1 I have noticed most of the time, the `columns_types` hash is now empty. This seems to be caused by this commit, specifically on the line that I have highlighted. https://github.com/rails/rails/commit/71e45582b794d7cdcbd72a93dc2f3c8665859653#diff-e6fd03cad5e3437c76b6c5db106359124dc9feab8341ade39b9ae54af001fac9R58

This appears to skip adding certain items to `column_types`. From what I can see, it's clear this was an intentional decision, and that the absence of data in meaningful in some way to other parts of AR. With that said, I believe this attribute is a public-enough API surface that it should always reflect all columns in the query.

As you might expect, it's hard to understand the context of a SQL query result without knowing what data types are for each column. I think we should keep that context in the `ActiveRecord::Result` object and restore the original behavior.

### Steps to reproduce

1. In a rails console run `result = ActiveRecord::Base.connection.exec_query("SELECT 1 AS test")`
1. Run `result.column_types`

### Expected behavior
I expect that `result.column_type` will return something like `=> {"test"=>#<ActiveModel::Type::Integer:0x00007fc9fbb6fe50 @limit=4, @precision=nil, @range=-2147483648...2147483648, @scale=nil>}`

### Actual behavior
After this commit 71e45582b794d7cdcbd72a93dc2f3c8665859653, `result.column_type` returns `{}`

### System configuration
**Rails version**:Rails 6.1.3
**Ruby version**: ruby 2.7.2p137

### PR DESCRIPTION
**Pull request by ghiculescu**
Fixes https://github.com/rails/rails/issues/41651, by partially reverting https://github.com/rails/rails/pull/39097. I just reverted the line that @terracatta highlighted as problematic.

I ran the same benchmark as https://github.com/rails/rails/pull/39097 and it seems like this change does not cause a perf regression.

```ruby

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", path: "/Users/alex/code/rails" # github: "rails/rails", branch: "main"
  gem "sqlite3"
  gem "benchmark-ips"
end

require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

ActiveRecord::Schema.define do
  create_table :active_storage_blobs do |t|
    t.string   :key,          null: false
    t.string   :filename,     null: false
    t.string   :content_type
    t.text     :metadata
    t.string   :service_name, null: false
    t.bigint   :byte_size,    null: false
    t.string   :checksum,     null: false
    t.datetime :created_at,   null: false

    t.index [ :key ], unique: true
  end
end

class ActiveStorageBlob < ActiveRecord::Base
end

Benchmark.ips do |x|
  x.report("find_by") { ActiveStorageBlob.find_by(id: 1) }
end
```

This branch:

```
Warming up --------------------------------------
             find_by     1.940k i/100ms
Calculating -------------------------------------
             find_by     17.928k (± 4.8%) i/s -     91.180k in   5.098301s
```

Main:

```
Warming up --------------------------------------
             find_by     1.912k i/100ms
Calculating -------------------------------------
             find_by     17.961k (± 4.8%) i/s -     89.864k in   5.015252s
```

So it's basically the same. cc @terracatta @boblail

### CODE REVIEW

File: activerecord/test/cases/calculations_test.rb [hunk 1]
```diff
@@ -993,11 +993,24 @@ def test_pluck_functions_with_alias
...
   def test_pluck_functions_without_alias
-    assert_equal [
-      [1, "The First Topic"], [2, "The Second Topic of the day"],
-      [3, "The Third Topic of the day"], [4, "The Fourth Topic of the day"],
-      [5, "The Fifth Topic of the day"]
-    ], Topic.order(:id).pluck(
+    expected = if current_adapter?(:PostgreSQLAdapter)
+      # Postgres returns the same name for each column in the given query, so each column is named "coalesce"
+      # As a result Rails cannot accurately type cast each value.
+      # To work around this, you should use aliases in your select statement (see test_pluck_functions_with_alias).
```
Comment (ghiculescu) [inline activerecord/test/cases/calculations_test.rb:999]: This is a bit yucky, but it only happens in very specific cases: if you have select two (or more) columns that don't have an alias and use the same SQL function (eg COALESCE). This happens because of how Postgres returns column names, see https://github.com/rails/rails/pull/36186#issuecomment-618418281 for a summary.

As far as I can tell we have a few options:

- The current state, which results in this bug: https://github.com/rails/rails/issues/41651
- This PR, which fixes https://github.com/rails/rails/issues/41651 but introduces this inconsistency between databases.
- Implement the refactor in https://github.com/rails/rails/pull/36186, which adds a fair bit of overhead to every query for a relatively niche issue.

In my opinion this PR is the least bad option.
