### PR TITLE
Stop EventedFileUpdateChecker's listener only

### LINKED ISSUE #38174: Mailer classes do not load until console is reloaded (reload! is called)
### Steps to reproduce
Create a mailer using generator or manually. Add methods to this class. Start rails console and try to use these methods from this class on the console.
Example
```
class ReportMailer < ApplicationMailer
  def daily_report(args)
     #do stuff
   end
end
```

### Expected behavior
Method should have worked.

### Actual behavior
`NameError (uninitialized constant ReportMailer)` my mailer is called ReportMailer

### System configuration
Rails 6.0.1
Ruby 2.5.0

### PR DESCRIPTION
**Pull request by jonathanhefner**
When an `EventedFileUpdateChecker` instance detects a watched directory that previously did not exist, it calls `shutdown!` and then `boot!` to reinitialize its underlying listener.  Prior to this commit, `shutdown!` invoked `Listen.stop` which stops **all** listeners, globally.  This commit changes `shutdown!` to stop the checker's listener only.

Fixes #38174.

### CODE REVIEW

File: activesupport/lib/active_support/evented_file_update_checker.rb [hunk 1]
```diff
@@ -100,11 +100,12 @@ def execute_if_updated
       def boot!
         normalize_dirs!
 
-        Listen.to(*@dtw, &method(:changed)).start if @dtw.any?
+        @listener = (Listen.to(*@dtw, &method(:changed)) if @dtw.any?)
```
Comment (rafaelfranca) [inline activesupport/lib/active_support/evented_file_update_checker.rb:103]:
```suggestion
        @listener = Listen.to(*@dtw, &method(:changed)) if @dtw.any?
```

**Review by rafaelfranca — COMMENTED** [review]
👍. Can we ask for a release of the gem? Last release was in December 2019.

File: activesupport/lib/active_support/evented_file_update_checker.rb (hunk 1 above)
Comment (jonathanhefner) [reply activesupport/lib/active_support/evented_file_update_checker.rb]: That is slightly different since it won't always assign `@listener`.  Instead, I rewrote this line using a ternary operator.

**Review by kaspth — APPROVED** [review]

**Comment by jonathanhefner** [comment]
Marking as ready since 94ea7281b8eaef3ed4a55fa2edc11a39e0fe35ee bumped the `listen` gem to its current `master` revision, which has the fixes for guard/listen#476.

**Comment by eugeneius** [comment]
https://github.com/rails/rails/commit/94ea7281b8eaef3ed4a55fa2edc11a39e0fe35ee only bumped Listen in Rails' own Gemfile; new applications will still be generated with the published version. 

It's looking increasingly unlikely that a new version of Listen will be released in time for Rails 6.1. Maybe we could use `Listener.new` to work around the memory leak instead, as you alluded to in https://github.com/guard/listen/issues/476?

**Comment by jonathanhefner** [comment]
> [94ea728](https://github.com/rails/rails/commit/94ea7281b8eaef3ed4a55fa2edc11a39e0fe35ee) only bumped Listen in Rails' own Gemfile; new applications will still be generated with the published version.

@eugeneius You're right.  For some reason, I was thinking applications would pick up the locked version of Listen as a transitive dependency.

> It's looking increasingly unlikely that a new version of Listen will be released in time for Rails 6.1. Maybe we could use `Listener.new` to work around the memory leak instead, as you alluded to in [guard/listen#476](https://github.com/guard/listen/issues/476)?

Unfortunately, that would only fix the first leak that I mentioned.  But hopefully the next release of the Listen gem isn't too far off.  The last remaining issue in the [v3.3.0 milestone](https://github.com/guard/listen/milestone/7) is being worked on presently: guard/listen#496.

**Comment by ColinDKelley** [comment]
Yes, I can confirm that `listen 3.3.0` milestone is now complete. I just tagged `3.3.0.pre.1`. I'm working through some auth issues now to get it pushed to rubygems. We have been running substantially the same version in production at our company for the last 3 months, but we'd like to run exactly this pre-release next week.

**Comment by ColinDKelley** [comment]
`listen` [v3.3.0.pre.2](https://github.com/guard/listen/releases/tag/v3.3.0.pre.2) has been released to rubygems. If anyone has a chance to try it with Rails 6.1, that would be very helpful. We hope to release it at the end of next week, barring any surprises.

Thanks @thibaudgg for the rubygems auth help!

**Comment by jonathanhefner** [comment]
@ColinDKelley Rails `master` branch tests all pass with Listen v3.3.0.pre.2: #40506. :tada:

**Comment by ColinDKelley** [comment]
Thanks for checking that, @jonathanhefner!

**Comment by ColinDKelley** [comment]
FYI, `listen` [v3.3.0](https://github.com/guard/listen/releases/tag/v3.3.0) has been released!

If there are any surprises, please let us know right away by filing a [listen issue](https://github.com/guard/listen/issues).
