### PR TITLE
Active Job: Correctly use the desired test adapter in tests

### LINKED ISSUE #37270: Rails 6 inconsistently overrides ActiveJob queue_adapter setting with TestAdapter
### Summary

Like many folks, I set this in my `config/environments/test.rb` file:

```ruby
config.active_job.queue_adapter = :inline  
```

The reason I do this is to have easy-to-test, deterministic behavior of any potentially async delayed jobs triggered by the application. Under Rails 5, all of my tests (children of `ActiveSupport::TestCase` and `ActionDispatch::SystemTestCase` alike) would respect this queue adapter. However, under Rails 6, any built-in Rails test case that includes `ActiveJob::TestHelper` will also override this setting for all descendants of `ActiveJob::Base` ([relevant source](https://github.com/rails/rails/blob/master/activejob/lib/active_job/test_helper.rb#L39-L41)).

The net effect of this is that my `perform_later` and `deliver_later` calls to jobs aren't being fired synchronously (or, in fact, at all) during my system tests, which is leading to test failures upon upgrading to Rails 6.

### Steps to reproduce

Here are two tests that demonstrates the problem:

```ruby
require "test_helper"

class JobTest < ActiveSupport::TestCase
  class SomeJob < ActiveJob::Base
    cattr_accessor :job_ran

    def perform
      @@job_ran = true
    end
  end

  def test_some_job
    assert_equal :inline, Rails.application.config.active_job.queue_adapter
    assert_equal ActiveJob::QueueAdapters::InlineAdapter, SomeJob.queue_adapter.class

    SomeJob.perform_later

    assert_equal true, SomeJob.job_ran
  end
end

class JobSystemTest < ActionDispatch::SystemTestCase
  class OtherJob < ActiveJob::Base
    cattr_accessor :job_ran

    def perform
      @@job_ran = true
    end
  end

  def test_other_job
    assert_equal :inline, Rails.application.config.active_job.queue_adapter
    assert_equal ActiveJob::QueueAdapters::InlineAdapter, OtherJob.queue_adapter.class

    OtherJob.perform_later

    assert_equal true, OtherJob.job_ran
  end
end
```

### Expected behavior

I would expect the behavior to have remained as it did under Rails 5, where the `active_job.queue_adapter` setting would be respected for all of Rails' test types.

### Actual behavior

The first test, which descends from `ActiveSupport::TestCase` will pass and behave as it did under Rails 5. However, the second test, descending from from `ActionDispatch::SystemTestCase` will now fail under Rails 6, because `OtherJob`'s `queue_adapter` will have been reset by `ActiveJob::TestHelper` to be an instance of `TestAdapter`

```
JobSystemTest#test_other_job [/Users/justin/code/testdouble/present/test/lib/job_test.rb:33]:
--- expected
+++ actual
@@ -1 +1 @@
-ActiveJob::QueueAdapters::InlineAdapter
+ActiveJob::QueueAdapters::TestAdapter
```

### System configuration
**Rails version**: 6.0.0 as well as [6-0-stable](https://github.com/rails/rails/tree/2bc6a948a2f46f8cf2d44506af1be235691c84b5), as of today.

**Ruby version**: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

### PR DESCRIPTION
**Pull request by ghiculescu**
### Motivation / Background

Currently if you set `config.active_job.queue_adapter = (anything)` in `config/application.rb` or `config/environments/test.rb`, this config will be respected by some test cases but not others.

Specifically, in `ActionDispatch::IntegrationTest`, `ActionMailer::TestCase`, and `ActiveJob::TestCase`, the test adapter will still be `TestAdapter`, while in other test cases it will be `InlineAdapter`.

I think you'd expect that if you set the test adapter for an environment, that test adapter would be available everywhere in that environment. For example, you might want to use the Delayed Job test adapter in your test environment so that you can have your test code more closely match production. The feedback on https://github.com/rails/rails/issues/37270 echoes this, but the workaround suggested there of disabling the test adapter on specific klasses is not reliable.

### Detail

The logic to determine which queue adapter a job uses is quite confusing.

Here is how it works on `main` currently:

1. If running in a test, and the test class includes `ActiveJob::TestHelper` and overrides `queue_adapter_for_test`, then the `queue_adapter_for_test` adapter is used.
2. Otherwise, if running in a test, and the test class includes `ActiveJob::TestHelper`, then the `:test` adapter is used.
3. Otherwise, if `self.queue_adapter` is set on the job class, that adapter is used.
4. Otherwise, if `self.queue_adapter` is set on the job's superclass (eg. `ApplicationJob`), that adapter is used. 
5. Fall back to `Rails.application.config.active_job.queue_adapter` as configured by the user.
6. If not configured by the user, `Rails.application.config.active_job.queue_adapter` defaults to `:async`.
7. Fall back to `:async` if no Rails config set (eg. using Active Job as a standalone).

As noted above, only some of the built in test classes include `ActiveJob::TestHelper`. Also, setting a queue adapter on a specific job class is rare (typically you would not want different jobs to be performed by different backends). So in practice, in development/production, option 5 is used. And in test, options 2 and 5 are used, depending on the type of test.

This PR changes the logic to work as follows:

1. If `self.queue_adapter` is set on the job class, that adapter is used.
2. Otherwise, if `self.queue_adapter` is set on the job's superclass (eg. `ApplicationJob`), that adapter is used. 
3. If running in a test, and the test class includes `ActiveJob::TestHelper` and overrides `queue_adapter_for_test`, then the `queue_adapter_for_test` adapter is used.
4. Fall back to `Rails.application.config.active_job.queue_adapter` as configured by the user.
5. If not configured by the user, `Rails.application.config.active_job.queue_adapter` defaults to `:test` if `Rails.env.test?`, otherwise it defaults to `:async`.
6. If running in a test, and the test class includes `ActiveJob::TestHelper`, and no other adapter has been set (eg. using Active Job as a standalone), then use `:test`.
7. Otherwise, fall back to `:async`.

The key changes are:

- Now, if you set a `queue_adapter` on a job class, that will always be respected.
- The `queue_adapter_for_test` override still works, but it no longer takes priority over a queue adapter set on a specific job class. Since I think both of these techniques are rare, and the impact of this change only exists in a test environment, I think it is a relatively safe change.
- The default queue adapter in Rails config is now env-dependent. (It's `:test` in the `test` environment, and `:async` in all others.)

The default rails environment templates suggest [setting a specific queue adapter only in production](https://github.com/rails/rails/blob/f46d3452ae30c46d3e213c687decbbca0cee9119/railties/lib/rails/generators/rails/app/templates/config/environments/production.rb.tt#L79C12-L79C12). For users who do that, there will be no changes to behaviour with this PR.

For users who are more granular, by setting per-job queue adapters, things should continue to work as expected with this PR.

**The real change is for users who set a default queue adapter across all environments (as in this issue: https://github.com/rails/rails/issues/37270). For them, this PR solves the issue where some tests use the desired queue adapter, and other tests don't.**

### Additional information

Fixes: https://github.com/rails/rails/issues/37270

ref: https://github.com/bensheldon/good_job/issues/846
ref: https://github.com/rails/rails/issues/26360 - this PR changes the behavior here, which I think was overzealous.

I extracted out some other PRs to fix internal issues while working on this: https://github.com/rails/rails/pull/48623, https://github.com/rails/rails/pull/48626. I also extracted https://github.com/rails/rails/pull/48599 out as a non-controversial fix prior to this PR.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Review by cmunny95 — COMMENTED** [review]
Seems like a solid approach to me and it would be great to see this fixed! I'd be happy to run the patch and verify once the test suite has been updated

File: activejob/test/cases/test_helper_test.rb [hunk 1]
```diff
@@ -15,6 +15,10 @@
 require "models/person"
 
 class EnqueuedJobsTest < ActiveJob::TestCase
+  setup do
+    skip unless adapter_is?(:test)
```
Comment (ghiculescu) [inline activejob/test/cases/test_helper_test.rb:19]: On `main` the test adapter is always `:test` inside these tests (regardless of what adapter is set in ENV).

Comment (ghiculescu) [reply activejob/test/cases/test_helper_test.rb:19]: Should add another set of test classes for non-test adapters.

File: activejob/test/jobs/logging_job.rb [hunk 2]
```diff
@@ -1,8 +1,8 @@
 # frozen_string_literal: true
 
 class LoggingJob < ActiveJob::Base
-  def perform(dummy)
-    logger.info "Dummy, here is it: #{dummy}"
+  def perform(*dummy)
```
Comment (ghiculescu) [inline activejob/test/jobs/logging_job.rb:4]: https://github.com/rails/rails/pull/48623

File: activejob/lib/active_job/queue_adapters/async_adapter.rb [hunk 3]
```diff
@@ -95,7 +95,7 @@ def enqueue(job, queue_name:)
 
         def enqueue_at(job, timestamp, queue_name:)
           delay = timestamp - Time.current.to_f
-          if delay > 0
+          if !immediate && delay > 0
```
Comment (ghiculescu) [inline activejob/lib/active_job/queue_adapters/async_adapter.rb:98]: https://github.com/rails/rails/pull/48626

**Comment by northeastprince** [comment]
@rafaelfranca can we get this merged?

**Comment by jrochkind** [comment]
This would be a really welcome fix to a very confusing challenge in setting up your tests how you want. (I actually do want some test classes using :inline and others using :test).

It would be great if some way could be found to get maintainer attention to make progress on this!

**Comment by gjtorikian** [comment]
I understand this is slated for 7.2. But for those of us who prefer to pin the rails dependency to a SHA, could this be merged ?

**Comment by ghiculescu** [comment]
I don't know if it'll be in 7.2. @byroot or @rafaelfranca do you have a verdict on that? If this is something you're conceptually okay with, I will work on the merge conflicts to get it mergable 👍

**Comment by byroot** [comment]
I don't have full context and wonder why it was done that way, but your point make sense to me.

I'd say rebase and ping me when it's done. Rafael can revert if he disagrees.

File: activejob/lib/active_job/test_helper.rb
Comment (ghiculescu) [inline activejob/lib/active_job/test_helper.rb:1]: @jonathanhefner in light of [your recent docs changes](https://github.com/rails/rails/commits/main/activejob/lib/active_job/test_helper.rb?author=jonathanhefner), I'd love if you could review if the docs in this file all make sense for this PR 😍

File: activejob/test/cases/test_helper_test.rb [hunk 4]
```diff
@@ -14,2054 +15,2138 @@
...
+    teardown do
+      queue_adapter.perform_enqueued_jobs = @perform_enqueued_jobs
+      queue_adapter.perform_enqueued_at_jobs = @perform_enqueued_at_jobs
     end
   end
+end
+
+
+class EnqueuedJobsTest < ActiveJob::TestCase
+  if adapter_is?(:test)
```
Comment (ghiculescu) [inline activejob/test/cases/test_helper_test.rb:39]: This is needed becuase you can't `skip` since https://github.com/rails/rails/pull/50188. Alternative would be to put a `force_skip` in a `setup` block.

File: activejob/CHANGELOG.md [hunk 5]
```diff
@@ -1,3 +1,16 @@
+*   All tests now respect the `active_job.queue_adapter` config
+
+    Previously if you had set `config.active_job.queue_adapter` in your `config/application.rb`
+    or `config/environments/test.rb` file, the adapter you selected was previously not used consistently
+    across all tests. In some tests your adapter would be used, but other tests would use the `TestAdapter`.
+
+    In Rails 7.1, all tests will respect the `queue_adapter` config if provided. If no config is provided,
```
Comment (byroot) [inline activejob/CHANGELOG.md:7]:
```suggestion
    In Rails 7.2, all tests will respect the `queue_adapter` config if provided. If no config is provided,
```

File: activejob/lib/active_job/queue_adapter.rb [hunk 6]
```diff
@@ -61,6 +60,15 @@ def queue_adapter=(name_or_adapter)
...
 
       private
+        def with_default_if_no_adapter_set
+          value = yield
+          if value.nil?
+            self.queue_adapter = :async
+            value = yield
+          end
+          value
+        end
```
Comment (byroot) [inline activejob/lib/active_job/queue_adapter.rb:70]: This method is really a bit weird. I think I'd rather see a much more straightforwrd:

```ruby
self.queue_adapter = :async if _queue_adapter.nil?
```

In both `queue_adapter` and `queue_adapter_name`.

File: activejob/lib/active_job/test_helper.rb [hunk 7]
```diff
@@ -39,10 +39,10 @@ def enable_test_adapter(test_adapter)
     end
 
     def before_setup # :nodoc:
-      test_adapter = queue_adapter_for_test
-
       queue_adapter_changed_jobs.each do |klass|
-        klass.enable_test_adapter(test_adapter)
+        if (test_adapter = test_adapter_should_be(klass))
```
Comment (byroot) [inline activejob/lib/active_job/test_helper.rb:43]: Not a big fan of that `test_adapter_should_be` name, I'm really struggling a bit too much to understand what it does.

Maybe it would make more sense to just inline it here. Or to move the responsability to call `enable_test_adapter` there and rename it. But I'd do the former.

File: activejob/lib/active_job/queue_adapter.rb (hunk 6 above)
Comment (ghiculescu) [reply activejob/lib/active_job/queue_adapter.rb]: Yeah that was pretty funky. Thanks.

File: railties/test/application/active_job_adapter_test.rb [hunk 8]
```diff
@@ -0,0 +1,217 @@
+# frozen_string_literal: true
```
[the remark this answers is not in the document]
Comment (ghiculescu) [reply railties/test/application/active_job_adapter_test.rb:1]: Ahh I didn't know that existed. Happy to move the test, or you can if you like.

**Comment by searls** [comment]
Thanks so much for digging into this and fixing it!! Bumps to #37270 have been irritating my inbox for nearly 5 years! ❤️

File: railties/test/application/active_job_adapter_test.rb (hunk 8 above)
[the remark this answers is not in the document]
Comment (zzak) [reply railties/test/application/active_job_adapter_test.rb:1]: It's just a knit, but I think moving files around is cosmetic enough to not warrant a PR. Maybe next time? :pray:
