### PR TITLE
[Fix #50897] Autosaving `has_one` sets foreign key attribute when unchanged

### LINKED ISSUE #50897: Incorrectly raising `ReadonlyAttributeError` when that attribute hasn't changed
Rails 7.1 sets `raise_on_assign_to_attr_readonly` to true. In the following repro I set a column unrelated to `updater_id` yet the error is still being set. If I stop setting this column the error goes away.

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord.raise_on_assign_to_attr_readonly = true

ActiveRecord::Schema.define do
  create_table :forum_topics, force: true do |t|
    t.integer :updater_id
    t.text :title
  end

  create_table :forum_posts, force: true do |t|
    t.integer :updater_id
    t.integer :forum_topic_id
    t.text :body
  end
end

class ForumTopic < ActiveRecord::Base
  has_one :original_forum_post, -> { order("forum_posts.id asc") }, class_name: "ForumPost", inverse_of: :forum_topic
  validates_associated :original_forum_post
  accepts_nested_attributes_for :original_forum_post
end

class ForumPost < ActiveRecord::Base
  attr_readonly :forum_topic_id
  belongs_to :forum_topic

  before_validation do |rec|
    # next # Skipping setting this column makes the error go away
    if persisted?
      rec.updater_id = 456
    else
      rec.updater_id = 123
    end
  end
end

class BugTest < Minitest::Test
  def test_readonly_attr_exception
    topic = ForumTopic.create!(title: "Hi!", original_forum_post_attributes: { body: "What's up?" })
    topic.update(title: "nevermind") # => ActiveRecord::ReadonlyAttributeError: forum_topic_id
    assert_equal(456, topic.original_forum_post.updater_id)
  end
end
```

### System configuration
**Rails version**: master

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

Fixes https://github.com/rails/rails/issues/50897

Similar to https://github.com/rails/rails/pull/46759

### Detail

Updates `ActiveRecord::AutosaveAssociation#save_has_one_association` to only update the foreign key attribute on the child record if it has changed. This makes its behaviour consistent with `belongs_to` associations and ensures that `ActiveRecord::ReadOnlyAttributeError` isn't raised when no changes have been made to the attribute.

### Additional information

None.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/test/cases/autosave_association_test.rb [hunk 1]
```diff
@@ -302,6 +302,13 @@ def test_callbacks_firing_order_on_save
     eye.update(iris_attributes: { color: "blue" })
     assert_equal [false, false, false, false], eye.after_save_callbacks_stack
   end
+
+  def test_foreign_key_attribute_is_not_set_unless_changed
+    eye = Eye.create!(iris_with_read_only_foreign_key_attributes: { color: "honey" })
+    assert_nothing_raised do
+      eye.update!(override_iris_with_read_only_foreign_key_color: true)
```
Comment (joshuay03) [inline activerecord/test/cases/autosave_association_test.rb:309]: Before patch:
Screenshot 2024-01-28 at 7 21 26 pm
