### PR TITLE
Fix a backtracking problem in String#truncate_words

### LINKED ISSUE #19070: truncate_words is hanging on certain texts (Rails 4.2 new method)
Hi all,

When you cut and paste the following into rails console with Rails 4.2. It hangs...

    "Hello,\n    I am available at after 12 every sunday. Saturday afternoons after 2\npm. 2 hours every session.\n\n2015-02-23 20:02 GMT+08:00 Name <email@example.com>:".truncate_words(30)

Scenario: I am trying to parse inbound emails. The hanging is causing 504s to happen eventually, when all threads are taken up as Mandrill keeps retrying.

In the above case, changing 30 to 20 returns successfully (and introduces truncation). I would narrow down the string to try to see what's causing it but I haven't found a shorter string in which this recurs.

### PR DESCRIPTION
**Pull request by nygrenh**
There was a problem in String#truncate_words where with certain inputs the regular expression evaluation would hang due to catastrophic backtracking. 

Fixes #19070.

### CODE REVIEW

**Comment by ernsheong** [comment]
:+1:

File: activesupport/test/core_ext/string_ext_test.rb [hunk 1]
```diff
@@ -249,6 +249,19 @@ def test_truncate_words_with_separator_and_omission
...
 
+  def test_truncate_words_with_complex_string
+    begin
+      assert_nothing_raised do
+        Timeout.timeout(10) do
+          complex_string = "aa aa aaa aa aaa aaa aaa aa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaa aaaa aaaaa aaaaa aaaaaa aa aa aa aaa aa  aaa aa aa aa aa a aaa aaa \n a aaa <<s"
+          assert_equal complex_string.truncate_words(80), complex_string
+        end
+      end
+    rescue Timeout::Error
```
Comment (rafaelfranca) [inline activesupport/test/core_ext/string_ext_test.rb]: Is this rescue necessary? I think `assert_nothing_raised` will already handle this case.

Comment (nygrenh) [inline activesupport/test/core_ext/string_ext_test.rb]: Without the rescue when the method hangs the test will error instead of fail. I think the assert_nothing_raised is actually unnecessary.

Comment (rafaelfranca) [inline activesupport/test/core_ext/string_ext_test.rb]: Right. Let remove the `assert_nothing_raised`

Comment (nygrenh) [inline activesupport/test/core_ext/string_ext_test.rb]: Done

**Comment by rafaelfranca** [comment]
Backported as 384cc1f60dda50e91eee894599b3c8391e6df682
