### PR TITLE
Fix asynchronous destroying of polymorphic `belongs_to` associations

### LINKED ISSUE #53764: dependent: :destroy_async fails with polymorphic belongs_to relationships ("ArgumentError: Polymorphic associations do not support computing the class")
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record/railtie"
require "active_job"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.references :owner, polymorphic: true
  end
end

class Post < ActiveRecord::Base
end

class Comment < ActiveRecord::Base
  belongs_to :owner, polymorphic: true, optional: true, dependent: :destroy_async
end

class BugTest < ActiveSupport::TestCase
  def test_association_stuff
    post = Post.create!
    comment = Comment.create!(owner: post)

    comment.destroy!

    assert_equal 0, Post.count
    assert_equal 0, Comment.count
  end
end
```

### Expected behavior

The test should delete the comment and enqueue an `ActiveRecord::DestroyAssociationAsyncJob`, which will then delete the post.

### Actual behavior

An error is raised: "ArgumentError: Polymorphic associations do not support computing the class."

If I change `:destroy_async` to `:destroy` in the `Comment` model, the test passes.

If I change the polymorphic relation for a regular one, it works as expected.

### System configuration
**Rails version**: 8.0.0 and 7.1.4.1 at least

**Ruby version**: 3.3.0

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #53764.

### CODE REVIEW

File: activerecord/test/activejob/destroy_association_async_test.rb [hunk 1]
```diff
@@ -209,6 +210,20 @@ class DestroyAssociationAsyncTest < ActiveRecord::TestCase
     DestroyAsyncParent.delete_all
   end
 
+  test "polymorphic belongs_to" do
```
Comment (zzak) [inline activerecord/test/activejob/destroy_association_async_test.rb:213]: @fatkodima FYI, this test is failing pretty consistently for me locally:

```
$ bin/test --seed 16437

Failure:
DestroyAssociationAsyncTest#test_polymorphic_belongs_to [test/activejob/destroy_association_async_test.rb:219]:
`Author.count` didn't change by -1, but by -2.
Expected: 3
  Actual: 2


bin/test test/activejob/destroy_association_async_test.rb:213
```

Have tried with mysql2, postgres, and sqlite3_mem.

Comment (fatkodima) [reply activerecord/test/activejob/destroy_association_async_test.rb:213]: Thanks for reporting, I will take a look.
