### PR TITLE
Fix has_many inversing recursion on models with recursive associations

### LINKED ISSUE #40867: Rails 6.1: has_many_inversing breaks belongs_to relations with the same name as the model
### TLDR;

A `belongs_to` relation with the same name as the model breaks in certain scenarios when `Rails.application.config.active_record.has_many_inversing` is enabled.

```ruby
class Team < ActiveRecord::Base
  # very simple tree of teams
  belongs_to :team, optional: true
end
```

### Full Disclosure

The project I work on, actually does something like this:

```ruby
class Team < ActiveRecord::Base
  belongs_to :team, optional: true  # parent
  has_many :teams                 # children
end
```

I recommend against doing that. It is confusing. We're taking this regression as an opportunity to rename the relations in our codebase. I've created this issue as documentation for the next person who stumbles upon this.
 
### Reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", '=6.1.0'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

#
# Flipping this setting breaks/fixes the tests below.
#
ActiveRecord::Base.has_many_inversing = true

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :teams, force: true do |t|
    t.integer :team_id
    t.integer :external_link
  end
end

class Team < ActiveRecord::Base
  belongs_to :team, optional: true

  # For some business purposes,
  # the closest ancestor that is linked can be used
  # as stand-in if this team is not linked.
  def linked_team_without_cycle_detect
    t = self
    while t do
      return t if t.external_link.present?
      t = t.team
    end
    return nil
  end

  # Once upon a time, our team tree was corrupted
  # and contained cycles.
  def linked_team_with_cycle_detect
    t = self
    seen = []
    while t do
      seen << t
      return t if t.external_link.present?
      t = t.team
      return nil if seen.include?(t)
    end
    return nil
  end

end

class BelongsToWithSameNameAsModel < Minitest::Test

  # This one hangs and has to be killed.
  def test_linked_team_without_cycle_detect
    parent = Team.create!(external_link: 1)
    child = Team.create!(team_id: parent.id, external_link: 2)
    grandchild = Team.create!(team_id: child.id, external_link: 3)

    assert_equal parent, parent.linked_team_without_cycle_detect
    assert_equal child, child.linked_team_without_cycle_detect
    assert_equal grandchild, grandchild.linked_team_without_cycle_detect

    child.update_attribute(:external_link, nil)
    grandchild.update_attribute(:external_link, nil)

    assert_equal parent, parent.linked_team_without_cycle_detect
    assert_equal parent, child.linked_team_without_cycle_detect
    assert_equal parent, grandchild.linked_team_without_cycle_detect
  end

  # This one fails the last assertion.
  def test_linked_team_with_cycle_detect
    parent = Team.create!(external_link: 1)
    child = Team.create!(team_id: parent.id, external_link: 2)
    grandchild = Team.create!(team_id: child.id, external_link: 3)

    assert_equal parent, parent.linked_team_with_cycle_detect
    assert_equal child, child.linked_team_with_cycle_detect
    assert_equal grandchild, grandchild.linked_team_with_cycle_detect

    child.update_attribute(:external_link, nil)
    grandchild.update_attribute(:external_link, nil)

    assert_equal parent, parent.linked_team_with_cycle_detect
    assert_equal parent, child.linked_team_with_cycle_detect
    assert_equal parent, grandchild.linked_team_with_cycle_detect
  end

end
```

### PR DESCRIPTION
**Pull request by gmcgibbon**
### Summary

Fixes https://github.com/rails/rails/issues/40867

Corrects inversing behaviour on models with recursive relationships.

Eg.
```rb
class Branch
  has_many :branches
  belongs_to :branch, optional: true
end
```

Since the automatic inversing is always singular, it is possible for the inverse of a `belongs_to` -> `has_many` to be itself (when both are on the same model). I played with looking up the plualized reflection when `reflection == self`, but I did not see a change in behaviour, need to see if it being set somewhere else.

This change also adds a guard for manually set recursive inverses, which we may need a custom error type for.

### CODE REVIEW

File: activerecord/lib/active_record/reflection.rb [hunk 1]
```diff
@@ -234,6 +234,9 @@ def check_validity_of_inverse!
           if has_inverse? && inverse_of.nil?
             raise InverseOfAssociationNotFoundError.new(self)
           end
+          if has_inverse? && inverse_of == self
+            raise ArgumentError, "Recursive association #{name}."
```
Comment (gmcgibbon) [inline activerecord/lib/active_record/reflection.rb:238]: I probably need a custom error type here and a better error message.

File: activerecord/lib/active_record/reflection.rb [hunk 2]
```diff
@@ -624,6 +627,7 @@ def automatic_inverse_of
         # with the current reflection's klass name.
         def valid_inverse_reflection?(reflection)
           reflection &&
+            reflection != self &&
```
Comment (gmcgibbon) [inline activerecord/lib/active_record/reflection.rb:630]: ☝️ I could alternatively automatically look up the plualized reflection, but I don't know if that is needed. The inverse may be set somewhere else.

File: activerecord/test/cases/associations/inverse_associations_test.rb [hunk 3]
```diff
@@ -720,6 +721,31 @@ def test_with_has_many_inversing_does_not_trigger_association_callbacks_on_set_w
...
+    with_has_many_inversing do
+      main = Branch.create!
+      feature = main.branches.create!
+      topic = feature.branches.build
+
+      assert_equal(main, topic.branch.branch)
+    end
+  end
+
+  def test_recursive_inverse_on_recursice_model_has_many_inversing
```
Comment (DylanReile) [inline activerecord/test/cases/associations/inverse_associations_test.rb:735]:
```suggestion
  def test_recursive_inverse_on_recursive_model_has_many_inversing
```

File: activerecord/lib/active_record/reflection.rb (hunk 2 above)
Comment (DylanReile) [reply activerecord/lib/active_record/reflection.rb:630]: `self` seems more robust

**Review by LilyReile — APPROVED** [review]
LGTM, just needs a custom error class

File: activerecord/lib/active_record/associations.rb [hunk 4]
```diff
@@ -73,6 +73,18 @@ def corrections
...
   end
 
+  class InverseOfAssociationRecursiveError < ActiveRecordError #:nodoc:
+    attr_reader :reflection
+    def initialize(reflection = nil)
+      if reflection
+        @reflection = reflection
+        super("Inverse association for #{reflection.name} (#{reflection.options[:inverse_of].inspect} in #{reflection.class_name}) is recursive.")
+      else
+        super("Inverse association is recursive.")
```
Comment (zzak) [inline activerecord/lib/active_record/associations.rb:83]: Could you add a test for this case?

Comment (gmcgibbon) [reply activerecord/lib/active_record/associations.rb]: Looking at the code path again, this seems like an impossible scenario. The error is always raised with `self`, and I don't think `self` can ever be `nil` in the context of a reflection (or ever?). I was just copying from `InverseOfAssociationNotFoundError`, but that `else` also seems to be impossible as well. Will open a PR to fix that too if we agree.
