### PR TITLE
Avoid setting `ActiveRecord::Base.configurations` twice in db rake ta…

### LINKED ISSUE #38330: rake db clears previously-set ActiveRecord::Base.configurations
I am using the rails 6 "multiple databases" API to run a multi-tenant setup. Each tenant has its own database. Instead of enumerating each tenant in my `database.yml`, that file references a single "template" tenant database. At application launch, an initializer appends a hash config object for each tenant database to the `ActiveRecord::DatabaseConfigurations` object.

The issue is that `rake db` tasks reload database configurations set at rails boot. This happens in `db:load_config` [here](https://github.com/rails/rails/blob/1d1991430dc5174a54abe5c2f6ecb3fd180a829e/activerecord/lib/active_record/railties/databases.rake#L19) which calls into [here](https://github.com/rails/rails/blob/1d1991430dc5174a54abe5c2f6ecb3fd180a829e/activerecord/lib/active_record/railtie.rb#L41) and results in re-reading the application's `database.yml`.

**Configuration:** rails 6.0.2.1

**Steps to reproduce**
1. Modify `ActiveRecord::Base.configurations` from an initializer
2. Run `rake db:drop` or similar

**Expected behavior**
* `ActiveRecord::Base.configurations` is unchanged (same as after step 1)

**Actual behavior**
* `ActiveRecord::Base.configurations` gets reinitialized from `database.yml`

### PR DESCRIPTION
**Pull request by tgxworld**
Resolves https://github.com/rails/rails/issues/38330

### CODE REVIEW

File: activerecord/lib/active_record/railtie.rb [hunk 1]
```diff
@@ -39,8 +39,6 @@ class Railtie < Rails::Railtie # :nodoc:
     rake_tasks do
       namespace :db do
         task :load_config do
-          ActiveRecord::Tasks::DatabaseTasks.database_configuration = Rails.application.config.database_configuration
```
Comment (tgxworld) [inline activerecord/lib/active_record/railtie.rb:42]: This was first added way back in 2013 as part of https://github.com/rails/rails/commit/d1d7c86d0c8dcb7e75a87644b330c4e9e7d6c1c1 but this is no longer loaded because [`ActiveRecord::Base.configurations` is set once `ActiveRecord` is loaded](https://github.com/rails/rails/blob/7da82b0fc32a3257d9bc44605783d8aa1a7474a1/activerecord/lib/active_record/railtie.rb#L219).

File: activerecord/lib/active_record/railties/databases.rake [hunk 2]
```diff
@@ -19,7 +19,10 @@ db_namespace = namespace :db do
   end
 
   task load_config: :environment do
-    ActiveRecord::Base.configurations       = ActiveRecord::Tasks::DatabaseTasks.database_configuration || {}
+    if ActiveRecord::Base.configurations.empty?
+      ActiveRecord::Base.configurations = ActiveRecord::Tasks::DatabaseTasks.database_configuration
```
Comment (tgxworld) [inline activerecord/lib/active_record/railties/databases.rake:23]: Actually I do wonder if this line is still relevant considering that the databases rake task is under `railties`. We also have multiple spots in the rake task that references Rails.

Comment (eileencodes) [reply activerecord/lib/active_record/railties/databases.rake:23]: The tasks the reference Rails are only multiple database tasks. Since we need Railties to parse the database configuration to get the task names we decided that if you're using Active Record outside of a Rails application that we cannot support multiple database tasks.

**Comment by eileencodes** [comment]
I tested this in an application and it seems to work fine and we can merge this.

I want to note however the original issue is using configurations in a non-standard, non-recommended way. The configurations may break in other ways that we potentially will be unable to fix.

File: activerecord/lib/active_record/railties/databases.rake (hunk 2 above)
Comment (tgxworld) [reply activerecord/lib/active_record/railties/databases.rake:23]: Thank you for clarifying :+1: We’ll continue to set the configurations the DatabaskTasks class then.
