### PR TITLE
Clear ActiveRecord object memoized by take

### LINKED ISSUE #36977: Memoization issue with `take` resulting in returning wrongly memoized ActiveRecord object on query using find_by/where
### Script to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  ruby "2.6.3"

  gem "sqlite3"
  gem "rails", '6.0.0'
end

require "active_record"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: "bug_test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def setup
    10.times do |idx|
      Post.create!(name: idx.to_s)
    end
    @posts = Post.all
    # Pick any arbitrary post using take
    @cached_post = @posts.take
  end

  def test_issue_with_where
    10.times do |idx|
      post_name = idx.to_s
      # Skip for cached post name
      next if post_name == @cached_post.name

      # Get the specific post with name `idx`
      # The post returned will be the cached one since rails is caching the
      # output of take on https://github.com/rails/rails/blob/b9ca94caea2ca6a6cc09abaffaad67b447134079/activerecord/lib/active_record/relation/finder_methods.rb#L504
      idx_post = @posts.where(name: post_name).take

      # This assertion should fail whereas it's passing right now because of
      # memoization by take
      assert_equal post_name, idx_post.name

      # Since memoized post is being returned by take, object_id will be same
      assert @cached_post.object_id != idx_post.object_id
    end
  end

  def test_issue_with_find_by
    10.times do |idx|
      post_name = idx.to_s
      # Skip for cached post name
      next if post_name == @cached_post.name

      idx_post = @posts.find_by(name: post_name)

      # This assertion should fail whereas it's passing right now because of
      # memoization by take
      assert_equal post_name, idx_post.name

      # Since memoized post is being returned by take, object_id will be same
      assert @cached_post.object_id != idx_post.object_id
    end
  end
end
```
All the assertions in the above script should be false whereas they are true because of the bug

Problem is with this line
https://github.com/rails/rails/blob/b9ca94caea2ca6a6cc09abaffaad67b447134079/activerecord/lib/active_record/relation/finder_methods.rb#L504

### Expected behavior

Every time `find_by` or `where` is called on an ActiveRecord relation, it should query the DB every time

### Actual behavior

Querying ActiveRecord relation returns the ActiveRecord object memoized by `take` if `take` was called on the relation before query using `find_by` or `where`

### System configuration
**Rails version**:
6.0.0

**Ruby version**:
2.6.3

### PR DESCRIPTION
**Pull request by anmolarora**
### Summary
`ActiveRecord` object is memoized when `take` is called on a relation which is returned when `where/find_by` is called on the same relation.
This memoized state of the object needs to be cleared.

Fixes #36977

### CODE REVIEW

File: activerecord/test/cases/relations_test.rb [hunk 1]
```diff
@@ -2050,6 +2050,32 @@ def test_relation_with_private_kernel_method
     assert_equal [accounts(:signals37)], sub_accounts.available
   end
 
+  def test_where_with_take_memoization
+    5.times do |idx|
+      Post.create!(title: idx.to_s, body: idx.to_s)
+    end
+
+    posts = Post.all
```
Comment (matthewd) [inline activerecord/test/cases/relations_test.rb]: Let's put an `order(:title)` on here, otherwise the test will fail sporadically when the database happens to return "3" in the first `take`

Comment (anmolarora) [reply activerecord/test/cases/relations_test.rb]: There is only one Post in the DB with title '3'. 
Will this still be a problem?

Comment (matthewd) [reply activerecord/test/cases/relations_test.rb]: Oh, sorry, I was concerned that "3" might get [legitimately] chosen as `first_post`, and then the `assert_not_equal` would fail -- but it's comparing `object_id`, so it will actually be fine even if they both contain the same row. :+1:
