### PR TITLE
Raise an error only when `require_master_key` is specified

### LINKED ISSUE #31283: ActiveSupport::EncryptedFile::MissingKeyError in default generated app
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

```bash
$ rails --version
Rails 5.2.0.beta2
$ rails new rails52
$ cd rails52
$ grep -r "config.require_master_key" *
config/environments/production.rb:  # config.require_master_key = true
$ ls config/master.key
config/master.key
$ bundle
# clipped
$ RAILS_ENV=production rake environment
$ rm config/master.key
$ RAILS_ENV=production rake environment
rake aborted!
ActiveSupport::EncryptedFile::MissingKeyError: Missing encryption key to decrypt file with. Ask your team for your master key and write it to /Users/caleb.thompson/code/rails52/config/master.key or put it in the ENV['RAILS_MASTER_KEY'].
```

### Expected behavior

I have not specified that I am using the master key (the line in config/production.rb is commented out). I should be able to not have config/master.key and loading the environment should work correctly.

### Actual behavior

I get the `ActiveSupport::EncryptedFile::MissingKeyError` error, which says that I do need the master key.

This happens for development as well, but the config isn't specified in that environment file by default. The value for `config.require_master_key` by default should be false.

### System configuration
**Rails version**: 5.2.0.beta2

**Ruby version**: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

### PR DESCRIPTION
**Pull request by y-yagi**
To prevent errors from being raise in environments where credentials is unnecessary.

Context: https://github.com/rails/rails/issues/31283#issuecomment-348801489

Fixes #31283

### CODE REVIEW

**Comment by y-yagi** [comment]
Slightly related with #31333.

File: activesupport/lib/active_support/encrypted_configuration.rb [hunk 1]
```diff
@@ -11,8 +11,9 @@ class EncryptedConfiguration < EncryptedFile
     delegate :[], :fetch, to: :config
     delegate_missing_to :options
 
-    def initialize(config_path:, key_path:, env_key:)
-      super content_path: config_path, key_path: key_path, env_key: env_key
+    def initialize(config_path:, key_path:, env_key:, raise_if_missing_key:)
+      super content_path: config_path, key_path: key_path,
+        env_key: env_key, raise_if_missing_key: raise_if_missing_key
```
Comment (schneems) [inline activesupport/lib/active_support/encrypted_configuration.rb]: Do we have style preferences for kwargs? I like splitting them up to be on newlines:

```ruby
super content_path: config_path, 
      key_path:     key_path,
      env_key:      env_key, 
      raise_if_missing_key: raise_if_missing_key
```

or

```ruby
super content_path: config_path, 
        key_path:   key_path,
        env_key:    env_key, 
        raise_if_missing_key: raise_if_missing_key
```

But it does add a lot of extra whitespace

File: activesupport/lib/active_support/encrypted_file.rb [hunk 2]
```diff
@@ -26,18 +26,20 @@ def self.generate_key
...
 
 
-    attr_reader :content_path, :key_path, :env_key
+    attr_reader :content_path, :key_path, :env_key, :raise_if_missing_key
 
-    def initialize(content_path:, key_path:, env_key:)
+    def initialize(content_path:, key_path:, env_key:, raise_if_missing_key:)
       @content_path, @key_path = Pathname.new(content_path), Pathname.new(key_path)
-      @env_key = env_key
+      @env_key, @raise_if_missing_key = env_key, raise_if_missing_key
```
Comment (schneems) [inline activesupport/lib/active_support/encrypted_file.rb]: Can you make this two lines? This causes an array to be allocated where one isn't needed. So instead of 

```ruby
@env_key, @raise_if_missing_key = env_key, raise_if_missing_key
```

I would

```ruby
@raise_if_missing_key = raise_if_missing_key
@env_key = env_key

**Review by schneems — COMMENTED** [review]
Made one comment about avoiding an array allocation and another question on syntax. 

Over all it looks good. I think we need a test for the default case where no key is present and no error is raised. 

Currently these are the only tests that are being touched in this PR: 


- raise MissingKeyError when key is missing
- credentials raises error when require_master_key is specified and master key does not exist
- can not get credentials when master key does not exist
- show credentials
- show command raise error when require_master_key is specified and key does not exist
- show command raise error when require_master_key is specified and key does not exist

Thanks a ton for all your work! ❤️

File: activesupport/lib/active_support/encrypted_configuration.rb (hunk 1 above)
Comment (y-yagi) [reply activesupport/lib/active_support/encrypted_configuration.rb]: As far as I know, we do not have style preferences for kwargs. But I think the first format you presented is seems good. I updated to use it.

**Comment by y-yagi** [comment]
Thank you for detailed review! 
I fixed format, added more tests, and showed clear message if key could not be found with the show command.

File: activesupport/lib/active_support/encrypted_configuration.rb [hunk 3]
```diff
@@ -11,8 +11,11 @@ class EncryptedConfiguration < EncryptedFile
     delegate :[], :fetch, to: :config
     delegate_missing_to :options
 
-    def initialize(config_path:, key_path:, env_key:)
-      super content_path: config_path, key_path: key_path, env_key: env_key
+    def initialize(config_path:, key_path:, env_key:, raise_if_missing_key:)
+      super content_path: config_path,
+            key_path:     key_path,
+            env_key:      env_key,
+            raise_if_missing_key: raise_if_missing_key
```
Comment (kaspth) [inline activesupport/lib/active_support/encrypted_configuration.rb]: I believe the style before is our preferred one.

File: activesupport/lib/active_support/encrypted_file.rb [hunk 4]
```diff
@@ -26,18 +26,21 @@ def self.generate_key
     end
 
 
-    attr_reader :content_path, :key_path, :env_key
+    attr_reader :content_path, :key_path, :env_key, :raise_if_missing_key
 
-    def initialize(content_path:, key_path:, env_key:)
+    def initialize(content_path:, key_path:, env_key:, raise_if_missing_key:)
       @content_path, @key_path = Pathname.new(content_path), Pathname.new(key_path)
       @env_key = env_key
```
Comment (kaspth) [inline activesupport/lib/active_support/encrypted_file.rb]: Also preferred the `@env_key, @raise_if_missing_key = …` assign. The extra array allocation ain't really an appropriate concern at this level. People aren't likely to instantiate a ton of instances of this class, so 1 extra array is a drop in a bucket.

File: activesupport/lib/active_support/encrypted_file.rb [hunk 5]
```diff
@@ -26,18 +26,21 @@ def self.generate_key
...
+      @raise_if_missing_key = raise_if_missing_key
     end
 
     def key
       read_env_key || read_key_file || handle_missing_key
     end
 
     def read
+      return unless key
```
Comment (kaspth) [inline activesupport/lib/active_support/encrypted_file.rb]: Why do we need this?

Won't we also need to make sure `write` will raise without a key? And that `config` on Encrypted Configuration returns an empty hash?

File: activesupport/lib/active_support/railtie.rb [hunk 6]
```diff
@@ -49,17 +49,6 @@ class Railtie < Rails::Railtie # :nodoc:
...
-    initializer "active_support.require_master_key" do |app|
-      if app.config.respond_to?(:require_master_key) && app.config.require_master_key
-        begin
-          app.credentials.key
-        rescue ActiveSupport::EncryptedFile::MissingKeyError => error
-          $stderr.puts error.message
-          exit 1
-        end
-      end
-    end
```
Comment (kaspth) [inline activesupport/lib/active_support/railtie.rb]: How will the error look when booting a Rails app in production with `require_master_key = true`?

I added the rescue to prevent the backtrace from distracting from what were trying to communicate.

File: activesupport/test/encrypted_file_test.rb [hunk 7]
```diff
@@ -13,7 +13,7 @@ class EncryptedFileTest < ActiveSupport::TestCase
     File.write(@key_path, ActiveSupport::EncryptedFile.generate_key)
 
     @encrypted_file = ActiveSupport::EncryptedFile.new \
-      content_path: @content_path, key_path: @key_path, env_key: "CONTENT_KEY"
+      content_path: @content_path, key_path: @key_path, env_key: "CONTENT_KEY", raise_if_missing_key: true
```
Comment (kaspth) [inline activesupport/test/encrypted_file_test.rb]: Let's replace `\` with parens here and in the other test. This makes @rafaelfranca sleep better at night 😄

File: railties/lib/rails/application.rb [hunk 8]
```diff
@@ -469,10 +469,13 @@ def credentials
...
     #   Rails.application.encrypted("config/special_tokens.yml.enc", key_path: "config/special_tokens.key")
     def encrypted(path, key_path: "config/master.key", env_key: "RAILS_MASTER_KEY")
+      require_master_key = config.respond_to?(:require_master_key) && config.require_master_key
+
       ActiveSupport::EncryptedConfiguration.new(
         config_path: Rails.root.join(path),
         key_path: Rails.root.join(key_path),
-        env_key: env_key
+        env_key: env_key,
+        raise_if_missing_key: require_master_key
```
Comment (kaspth) [inline railties/lib/rails/application.rb]: Think `config[:require_master_key]` could spare us the `respond_to?` check.

File: railties/lib/rails/commands/credentials/credentials_command.rb [hunk 9]
```diff
@@ -33,8 +34,18 @@ def edit
...
-        say Rails.application.credentials.read.presence ||
-          "No credentials have been added yet. Use bin/rails credentials:edit to change that."
+        credentials = Rails.application.credentials.read.presence
+
+        if credentials
+          say credentials
+        elsif Rails.application.credentials.key.nil?
+          say(<<-end_of_message.squish)
+            Missing encryption key to decrypt secrets with.
+            Ask your team for your master key and put it in ENV["RAILS_MASTER_KEY"].
```
Comment (kaspth) [inline railties/lib/rails/commands/credentials/credentials_command.rb]: What's the use of this? Won't `edit` need the same instructions? 😊

File: activesupport/lib/active_support/encrypted_file.rb (hunk 5 above)
Comment (y-yagi) [reply activesupport/lib/active_support/encrypted_file.rb]: If there is no key check, it will decrypt with an empty key and `ActiveSupport::MessageEncryptor::InvalidMessage` will be raise, to prevent it. 

> Won't we also need to make sure write will raise without a key?  

Do we support write without key? I thought that it would be better just to prevent errors from being read. 
In the case of write, if the user incorrectly designates key, I think that encrypted files will be generated unintentionally. So, if do not specify key, do not have to support write, what do you think?

> And that config on Encrypted Configuration returns an empty hash? 

If the read result is empty, it is supposed to return an empty hash, so this is okay. 
https://github.com/rails/rails/blob/bc2e08034d4ee5e38536928ae0cb90210d27ddcf/activesupport/lib/active_support/encrypted_configuration.rb#L45

File: activesupport/lib/active_support/railtie.rb (hunk 6 above)
Comment (y-yagi) [reply activesupport/lib/active_support/railtie.rb]: If it remains as it is, the back trace will be showed. That is certainly noisy. 
I restored it.

File: railties/lib/rails/application.rb (hunk 8 above)
Comment (y-yagi) [reply railties/lib/rails/application.rb]: Unfortunately, `Rails::Application::Configuration` does not support `[]` method for now.

```ruby
config[:require_master_key]
#=> NoMethodError Exception: undefined method `[]' for #<Rails::Application::Configuration:0x005600b330a840 
```

If it says to add a method, I agree!

File: railties/lib/rails/commands/credentials/credentials_command.rb (hunk 9 above)
Comment (y-yagi) [reply railties/lib/rails/commands/credentials/credentials_command.rb]: This is for show messages that can understand when there is no key. 
(If this is not present, `No credentials have been added yet. Use bin/rails credentials:edit to change that."` is showed) 

`edit` is now unnecessary because master key creation is done whenever there is no key.

File: railties/test/application/configuration_test.rb [hunk 10]
```diff
@@ -707,6 +707,14 @@ def index
       assert_match(/Missing.*RAILS_MASTER_KEY/, error)
     end
 
+    test "credentials does not raise error when require_master_key is false and master key does not exist" do
```
Comment (swrobel) [inline railties/test/application/configuration_test.rb]: Does this also apply to the case where `require_master_key` isn't specified?

Comment (y-yagi) [reply railties/test/application/configuration_test.rb]: Yes, it applies. Behavior when `require_master_key` is not specified is the same as behavior when false is specified.

File: railties/lib/rails/application.rb (hunk 8 above)
Comment (kaspth) [reply railties/lib/rails/application.rb]: Oh! I thought it was an instance of `ActiveSupport::OrderedOptions`. Nevermind then.

Comment (kaspth) [reply railties/lib/rails/application.rb]: No wait, we should just add the `attr_accessor`.

File: railties/lib/rails/commands/credentials/credentials_command.rb (hunk 9 above)
Comment (kaspth) [reply railties/lib/rails/commands/credentials/credentials_command.rb]: This now blurs two error checks alongside the normal read flow. What do you think of joining those two like this?

```ruby
say Rails.application.credentials.read.presence || missing_credentials_explainer

def missing_credentials_explainer # Could use a better name.
  if Rails.application.credentials.key.nil?
    "Missing master key to decrypt credentials. See bin/rails credentials --help"
  else
    "No credentials…"
  end
end
```

Same would go for the encrypted command.

File: railties/lib/rails/application.rb (hunk 8 above)
Comment (y-yagi) [reply railties/lib/rails/application.rb]: Oh, :+1:

File: railties/lib/rails/commands/credentials/credentials_command.rb (hunk 9 above)
Comment (y-yagi) [reply railties/lib/rails/commands/credentials/credentials_command.rb]: :+1:  I fixed!

File: activesupport/lib/active_support/encrypted_file.rb (hunk 5 above)
Comment (kaspth) [reply activesupport/lib/active_support/encrypted_file.rb]: > In the case of write, if the user incorrectly designates key, I think that encrypted files will be generated unintentionally. So, if do not specify key, do not have to support write, what do you think?

I'm not sure what you mean. I think it would make sense that `write` always raises if there's no key. Otherwise wouldn't users end up with a file that couldn't be *en*crypted? I guess it would still raise an error, we'd just rather have it be a KeyMissing one 😊

File: railties/lib/rails/commands/encrypted/encrypted_command.rb [hunk 11]
```diff
@@ -72,6 +72,14 @@ def encrypted_file_generator
 
           Rails::Generators::EncryptedFileGenerator.new
         end
+
+        def missing_encrypted_message(key:, file_path:)
+          if key.nil?
+            "Missing '#{options[:key]}' to decrypt data. See bin/rails encrypted:help"
```
Comment (kaspth) [inline railties/lib/rails/commands/encrypted/encrypted_command.rb]: Mixing `key` and `options[:key]` is confusing. What's one or the other? Could renaming the `key` improve the clarity?

Comment (y-yagi) [reply railties/lib/rails/commands/encrypted/encrypted_command.rb]: `options[:key]` stores key path and `key` stores key for data decrypt. So I renamed `options[:key]` to `key_path`. What do you think?

**Comment by kaspth** [comment]
❤️
