### PR TITLE
Pass default values for `translate` through I18n

### LINKED ISSUE #26032: ActionView::Helpers::TranslationHelper#translate doesn't support Hash as default translation
Helper method `translate` in view doesn't support Hash as option :default,  but `I18n.t` and `translate` in controller do support it.

```
 irb(main):001:0> ApplicationController.helpers.t :count, default: { one: '1 msg', other: '%{count} msgs' }, count: 2
=> "1 msg"

irb(main):003:0> I18n.t :count, default: { one: '1 msg', other: '%{count} msgs' }, count: 2
=> "2 msgs"

irb(main):007:0> ApplicationController.new.t :count, default: { one: '1 msg', other: '%{count} msgs' }, count: 2
=> "2 msgs"
```

### LINKED ISSUE #41277: ActionView::Helpers::TranslationHelper.translate no longer executes Proc as default option in Rails 6.1
Rails 6.0.3.4:
```ruby
irb(main):001:0> I18n.t(:foobar, default: Proc.new { 'the default' })
=> "the default"
irb(main):002:0> include ActionView::Helpers::TranslationHelper
=> Object
irb(main):003:0> translate(:foobar, default: Proc.new { 'the default' })
=> "the default"
```

Rails 6.1.1:
```ruby
irb(main):001:0> I18n.t(:foobar, default: Proc.new { 'the default' })
=> "the default"
irb(main):002:0> include ActionView::Helpers::TranslationHelper
=> Object
irb(main):003:0> translate(:foobar, default: Proc.new { 'the default' })
=> #<Proc:0x000055d6898cc188@(irb):3>
```

### LINKED ISSUE #41380: ActionView::Helpers::TranslationHelper.translate doesn't replace aliases in defaults
### Steps to reproduce
`
class Hugo
  include ActionView::Helpers::TranslationHelper
end
I18n.translate(:hugo, default: 'Should replace %{alias}', alias: 'Replaced')
Hugo.new.translate(:hugo, default: 'Should replace %{alias}', alias: 'Replaced')
`
leads to:
"Should replace Replaced"
"Should replace %{alias}"

### Expected behavior
Alias replacement should work for keys in locale file as well as for defaults

### Actual behavior
Alias replacement only works for keys found in locale file but not for default string

### System configuration
Rails version: 6.1.1
Ruby version: jRuby 9.2.0.14

### PR DESCRIPTION
**Pull request by jonathanhefner**
A default value can be a string that needs interpolation, Hash that needs resolution via the `:count` option, or a Proc that needs evaluation.  Therefore, pass default values through `I18n.translate` to handle these cases.

Fixes #26032.
Fixes #41277.
Fixes #41380.

### CODE REVIEW

File: actionview/lib/action_view/helpers/translation_helper.rb [hunk 1]
```diff
@@ -94,7 +94,9 @@ def translate(key, **options)
             break translated unless translated.equal?(MISSING_TRANSLATION)
           end
 
-          break alternatives.first if alternatives.present? && !alternatives.first.is_a?(Symbol)
+          if alternatives.present? && !alternatives.first.is_a?(Symbol)
```
Comment (seanpdoyle) [inline actionview/lib/action_view/helpers/translation_helper.rb:97]: Does ensuring that `alternatives` exists as an Array give us an opportunity to re-arrange this conditional?

```ruby
alternatives = Array.wrap(options.delete(:default) || []).compact

# ...
case alternatives.first
when NilClass # maybe `when nil`?
  break false
when Symbol
  key = alternatives.shift
else
  break I18n.translate(**options, default: alternatives)
end
```

Comment (jonathanhefner) [reply actionview/lib/action_view/helpers/translation_helper.rb:97]: Avoiding that array allocation was initially done in #32747, so I wanted to preserve that behavior.

Also, however, `translate(:missing, default: nil)` should return `nil`, while `translate(:missing, default: [])` should return a missing translation error.  To support these two cases, the `alternatives.present?` check differentiates between `[nil]` and `[]`.  Using `case alternatives.first` would only handle the former.

(And to make things more complicated, `translate(:missing, default: [nil])` should return a translation missing error, to mirror `I18n.translate`.  Hence the `compact` on line 74 and the `alternatives.first && ...` on line 98.)

**Comment by rafaelfranca** [comment]
Can you add a CHANGELOG entry?

**Comment by jonathanhefner** [comment]
@rafaelfranca Done!  (Sorry for the delay! :pray:)

**Comment by xuanxu** [comment]
:wave: @rafaelfranca This change didn't make it to 6.1.2 (its assigned milestone) nor 6.1.3, is it still expected to be merged soon?

**Review by marivaldo — APPROVED** [review]

**Comment by pnikrat** [comment]
Is it expected to be merged for another patch release (6.1.4 I presume) ?

**Comment by eugeneius** [comment]
Thank you @jonathanhefner! Great work, as always.

**Comment by eugeneius** [comment]
Backported to 6-1-stable in https://github.com/rails/rails/commit/14f4e233c9da687d122975d82e09ca51f1213f48.

**Comment by jonathanhefner** [comment]
Thank you, @eugeneius!! :heart:
