### PR TITLE
[Fix #50230] Preserve serialized timezone when deserializing with `ActiveJob::Serializers::TimeWithZoneSerializer`

### LINKED ISSUE #50230: ActiveJob::Serializers::TimeWithZoneSerializer does not preserve the timezone
### Steps to reproduce

```ruby
require 'active_job'
require 'active_job/arguments'
require 'active_support/all'

Time.zone = 'Europe/London' #=> "Europe/London"
time = Time.zone.parse('2023-12-01T14:30:00Z') #=> Fri, 01 Dec 2023 14:30:00.000000000 GMT +00:00
serialized_time = ActiveJob::Serializers::TimeWithZoneSerializer.serialize(time) #=> {"_aj_serialized"=>"ActiveJob::Serializers::TimeWithZoneSerializer", "value"=>"2023-12-01T14:30:00.000000000+00:00"}
gmt_deserialized_time = ActiveJob::Serializers::TimeWithZoneSerializer.deserialize(serialized_time) #=> Fri, 01 Dec 2023 14:30:00.000000000 GMT +00:00
Time.zone = 'America/Los_Angeles' #=> "America/Los_Angeles"
pst_deserialized_time = ActiveJob::Serializers::TimeWithZoneSerializer.deserialize(serialized_time) #=> Fri, 01 Dec 2023 06:30:00.000000000 PST -08:00
Time.zone = nil #=> nil
utc_deserialized_time = ActiveJob::Serializers::TimeWithZoneSerializer.deserialize(serialized_time) #=> 2023-12-01 14:30:00 +0000
```

### Expected behavior

Since `ActiveSupport::TimeWithZone` stores information about the time zone I expect that this information should be preserved when serializing time. Changing the `Time.zone` should not affect objects serialized with a different time zone.

### Actual behavior

Deserialization of a serialized `TimeWithZone` uses always the current `Time.zone` and not the one that was used to create a `TimeWithZone` object instance.

### System configuration
**Rails version**:
6.1.7.1 but the behaviour is the same in 7.x

**Ruby version**:
3.1.3p185

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

Fixes https://github.com/rails/rails/issues/50230

### Detail

This Pull Request changes `ActiveJob::Serializers::TimeWithZoneSerializer` to include the time zone of the provided time with zone object in the serialized hash which is then used during deserialization.

### Additional information

A side effect of this change is that `ActiveJob::Serializers::TimeWithZoneSerializer` now inherits directly from `ActiveJob::Serializers::ObjectSerializer` instead of `ActiveJob::Serializers::TimeObjectSerializer` in order to define it's own `#serialize`. I don't see another way to implement this while preserving the current inheritance.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activejob/test/serializers/time_with_zone_serializer_test.rb [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+    assert_instance_of ActiveSupport::TimeWithZone, time
+    assert_equal "America/Los_Angeles", time.time_zone.name
+
+    serialized_time = ActiveJob::Serializers::TimeWithZoneSerializer.serialize(time)
+    Time.zone = "Europe/London"
+    deserialized_time = ActiveJob::Serializers::TimeWithZoneSerializer.deserialize(serialized_time)
+
+    assert_instance_of ActiveSupport::TimeWithZone, deserialized_time
+    assert_equal "America/Los_Angeles", deserialized_time.time_zone.name
```
Comment (joshuay03) [inline activejob/test/serializers/time_with_zone_serializer_test.rb:20]: Before patch:
Screenshot 2023-12-02 at 4 05 08 pm

File: activejob/test/serializers/time_with_zone_serializer_test.rb [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+  ensure
+    Time.zone = time_zone_before
+  end
+
+  test "#deserialize uses current time zone when serialized without one" do
```
Comment (joshuay03) [inline activejob/test/serializers/time_with_zone_serializer_test.rb:25]: This is the current functionality when provided a time without a time zone.

**Comment by joshuay03** [comment]
> Right now previous version of Rails can't understand that new format, and your patch isn't able to deal with the old format.

Hmm that's a valild concern.

> At the very least the new code must be able to read the old format, and ideally the old code is able to read the new format OR the new format must be behind a configuration flag so that you can deploy a new version of Rails that understand both formats, and then in a later deploy you can flip the switch.

I'm assuming by old and new code you mean the actual application code? Meaning once upgraded, there could be jobs queued that should (but currently don't) consider that the time zone will be preserved?

I think a configuration flag makes the most sense in that case. I'll look into it.

Also, do you think it's worth deprecating the old behaviour / enabling the config by default in a future version?

**Comment by joshuay03** [comment]
> No I mean the framework code. Deploys aren't atomic, and even if they were, when you deploy there will still be some jobs in the queue generated by the old version of the serializer, and some workers still using the old version of the serializer might pick job serialized with the new version.

> App code is much less of a concern.

Sorry, I'm not understanding why we need a flag then. The only real difference here is an extra `time_zone` key and value included during serialization, and only if it's available during deserialization is it used, else it defaults to the old behaviour (use the current time zone). So this implementation is compatible with the old format, it's just that the deserialized value may now be in a different time zone cause it's preserved, which may require adjustments to app code only.

Also, the old behaviour is accidentally mimiced by the second test case I've added, but I'm now realising this test is not even realistic cause of [this check](https://github.com/rails/rails/blob/67fb4414e598d29e7b3ea6024ffd2edd7bff4775/activejob/lib/active_job/serializers.rb#L33). In that test case, `time_zone` will be `nil`, which sort of simulates a hash serialized with the old value. I'll will be removing this, but it's proof of the compatibility.

**Comment by byroot** [comment]
> orry, I'm not understanding why we need a flag then.

My bad, I'm the one that was confused about the previous format. All good.

**Comment by byroot** [comment]
Backported to 7-0-stable and 7-1-stable.
