### PR TITLE
Fix `rotate(on_on_rotation:)` and `#on_rotation`

### LINKED ISSUE #54357: "on_rotation" callback is not called for ActiveRecord Signed Id
`on_rotation` is supported by `MessageVerifier`, but the Signed Id implementation does not pass it through. This feature is very useful for secret-key rotation and monitoring the usage of old keys.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  gem "sqlite3"
end

require "active_record/railtie"
require "minitest/autorun"

ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
  config.secret_key_base = "secret_key_base"

  ActiveRecord::Base.signed_id_verifier_secret = "new_secret"
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
end

class BugTest < ActiveSupport::TestCase
  def test_association_stuff
    Post.create! id: 1

    on_rotation_is_called = false

    # signed Id of "1" with "old_secret"
    signed_id_with_old_secret = "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoicG9zdCJ9fQ--e3c0118ae573077a32264dc32acc63800352323c41039b0e096af64bd6ecc28b"

    Post.signed_id_verifier.rotate "old_secret", on_rotation: -> { on_rotation_is_called = true }
    assert Post.find_signed!(signed_id_with_old_secret, on_rotation: -> { on_rotation_is_called = true })

    assert on_rotation_is_called
  end
end
```

### Expected Behavior
`on_rotation` should be called, and `on_rotation_is_called` should become true.

### Actual Behavior
The `on_rotation` method from `rotate` or `find_signed!` is not called, leaving `on_rotation_is_called` as false.

### Suggestions
1. Call `on_rotation` when it is set using the `rotate` method. This would require updating the `read_message` method in `activesupport/lib/active_support/messages/rotator.rb` file.

2. Call `on_rotation` when it is set using `find_signed`/`find_signed!`. These methods would need to accept `on_rotation` as an optional argument.

3. Implement both solutions.

### PR DESCRIPTION
**Pull request by byroot**
Ref: https://github.com/rails/rails/pull/44179
Fix: https://github.com/rails/rails/issues/54357

`MessageVerifier` and `MessageEncryptor` were intended to accept an `on_rotation` callback from the `#rotate` method or from the `#on_rotation` method.

This is particularly useful for codecs that aren't created by the user, but by the framework, like `ActiveRecord::Base.signed_id_verifier`

cc @AliSepehri, @jonathanhefner 

We should backport this to 8.0 and 7.2 (potentially 7.1?), because it was a documented feature, but never worked.

### CODE REVIEW

File: activesupport/lib/active_support/messages/rotator.rb [hunk 1]
```diff
@@ -11,10 +11,16 @@ def initialize(*args, on_rotation: nil, **options)
...
-      def rotate(*args, **options)
+      def rotate(*args, on_rotation: nil, **options)
+        @on_rotation = on_rotation if on_rotation
         fall_back_to build_rotation(*args, **options)
       end
 
+      def on_rotation(&on_rotation)
+        @on_rotation = on_rotation
+        self
+      end
```
Comment (jonathanhefner) [inline activesupport/lib/active_support/messages/rotator.rb:22]: Elaborating on what I said in https://github.com/rails/rails/issues/54357#issuecomment-2616371900, the intended API for <code>MessageVerifier<strong>s</strong></code> was the `#on_rotation` method, not `rotate(on_rotation: ...)`.  Also, the intended API for `MessageVerifier` was `new(on_rotation: ...)`, not `rotate(on_rotation: ...)`.

The idea was that only one `on_rotation` callback is called (not one per verifier), so that callback was specified in a singular way.

Comment (byroot) [reply activesupport/lib/active_support/messages/rotator.rb:22]: Right, but then the use case exposed in https://github.com/rails/rails/issues/54357 isn't super convenient, unless I'm missing something?

Comment (jonathanhefner) [reply activesupport/lib/active_support/messages/rotator.rb:22]: The holistic approach would be to configure `Rails.application.message_verifiers.on_rotation(...)`, and then initialize `signed_id_verifier` from that, similar to [how it is done](https://github.com/rails/rails/blob/fc906ea0b9aef363d3443e631108d027bb850092/activerecord/lib/active_record/railtie.rb#L328-L334) for `generated_token_verifier`.

I think adding a `MessageVerifier#on_rotation` method is okay, but it may be a foot gun when instances are shared between classes.  I checked, and `signed_id_verifier` is _not_ shared, but if someone wrote something like `Post.shared_verifier.on_rotation(...)`, it would inadvertently change `Comment.shared_verifier`.

I wouldn't support `rotate(on_rotation: ...)`, though, for the reasons previously mentioned.
