### PR TITLE
Fixes #47909 when using order or unscope

### LINKED ISSUE #44964: ActiveRecord malformed SQL statements with `where.missing` and `where.associated` clauses for parent/children associations
There is an edge case with ActiveRecord's `where.associated` and `where.missing` clauses when using them with same-table parent/children associations, causing those to generate what I believe is not the expected SQL statement.

## Classic behavior ✅ 

```ruby
class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

Post.where.associated(:comments).to_sql
# => "SELECT \"posts\".* FROM \"posts\" INNER JOIN \"comments\" ON \"comments\".\"post_id\" = \"posts\".\"id\" WHERE \"comments\".\"id\" IS NOT NULL"

Post.where.missing(:comments).to_sql
# => "SELECT \"posts\".* FROM \"posts\" LEFT OUTER JOIN \"comments\" ON \"comments\".\"post_id\" = \"posts\".\"id\" WHERE \"comments\".\"id\" IS NULL"
```

## Edge case behavior 👁️ 

```ruby
class Post < ActiveRecord::Base
  belongs_to :template, class_name: "Post", inverse_of: :children, optional: true
  has_many :children, class_name: "Post", inverse_of: :template, foreign_key: :template_id
end
```

### Expected behavior

ActiveRecord's `joins` method generates an alias `children_posts`. This alias is properly used in the SQL statement

```ruby
Post.where.associated(:children).to_sql
# => ""SELECT \"posts\".* FROM \"posts\" INNER JOIN \"posts\" \"children_posts\" ON \"children_posts\".\"template_id\" = \"posts\".\"id\" WHERE \"children_posts\".\"id\" IS NOT NULL""

Post.where.missing(:children).to_sql
# => "SELECT \"posts\".* FROM \"posts\" LEFT OUTER JOIN \"posts\" \"children_posts\" ON \"children_posts\".\"template_id\" = \"posts\".\"id\" WHERE \"children_posts\".\"id\" IS NULL""
```

### Actual behavior ❌ 

ActiveRecord's `joins` method generates an alias `children_posts`. but that alias is not used in the SQL statement. Instead, it's the original table name `posts`

```ruby
Post.where.associated(:children).to_sql
# => ""SELECT \"posts\".* FROM \"posts\" INNER JOIN \"posts\" \"children_posts\" ON \"children_posts\".\"template_id\" = \"posts\".\"id\" WHERE \"posts\".\"id\" IS NOT NULL""

Post.where.missing(:children).to_sql
# => "SELECT \"posts\".* FROM \"posts\" LEFT OUTER JOIN \"posts\" \"children_posts\" ON \"children_posts\".\"template_id\" = \"posts\".\"id\" WHERE \"posts\".\"id\" IS NULL""
```

### System configuration
**Rails version**: Edge, `main` branch (to the date of creation of this issue)

**Ruby version**:  tested on  2.7.4

### Steps to reproduce

[This branch](https://github.com/EmCousin/rails/tree/bug/active-record-where-missing-same-table) contains a test that reproduces the problem as well as a proposition to fix it. The solution I came up with is to add a `#aliased_table_name` instance method to the `Reflection` class, that returns the proper alias if needed.

You can also run the test below. It fails with `rails/rails`'s `main` branch, whereas it succeeds in [`EmCousin/rails/bug/active-record-where-missing-same-table`](https://github.com/EmCousin/rails/tree/bug/active-record-where-missing-same-table) 

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  ### The test fails with "rails/rails"'s `main` branch ###
  # gem "rails", github: "rails/rails", branch: "main"
  gem "rails", github: "EmCousin/rails", branch: "bug/active-record-where-missing-same-table"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.references :template, foreign_key: { to_table: :posts }
  end
end

class Post < ActiveRecord::Base
  belongs_to :template, class_name: "Post", optional: true
  has_many :children, class_name: "Post", inverse_of: :template, foreign_key: :template_id, dependent: :nullify
end

class WhereAssociatedMissingTest < Minitest::Test
  def test_where_associated_expected_sql_statement
    expected_sql_statement = <<-SQL.squish
      SELECT "posts".*
      FROM "posts"
      INNER JOIN "posts" "children_posts" ON "children_posts"."template_id" = "posts"."id"
      WHERE "children_posts"."id" IS NOT NULL
    SQL

    assert_equal expected_sql_statement, Post.where.associated(:children).to_sql
  end

  def test_where_associated_unexpected_sql_statement
    unexpected_sql_statement = <<-SQL.squish
      SELECT "posts".*
      FROM "posts"
      INNER JOIN "posts" "children_posts" ON "children_posts"."template_id" = "posts"."id"
      WHERE "posts"."id" IS NOT NULL
    SQL

    assert unexpected_sql_statement != Post.where.associated(:children).to_sql
  end

  def test_where_associated
    Post.destroy_all
    post = Post.create!
    post.children << Post.create!

    assert_equal 2, Post.count
    assert_equal 1, Post.where.associated(:children).count
  end

  def test_where_missing_expected_sql_statement
    expected_sql_statement = <<-SQL.squish
      SELECT "posts".*
      FROM "posts"
      LEFT OUTER JOIN "posts" "children_posts" ON "children_posts"."template_id" = "posts"."id"
      WHERE "children_posts"."id" IS NULL
    SQL

    assert_equal expected_sql_statement, Post.where.missing(:children).to_sql
  end

  def test_where_missing_unexpected_sql_statement
    unexpected_sql_statement = <<-SQL.squish
      SELECT "posts".*
      FROM "posts"
      LEFT OUTER JOIN "posts" "children_posts" ON "children_posts"."template_id" = "posts"."id"
      WHERE "posts"."id" IS NULL
    SQL

    assert unexpected_sql_statement != Post.where.missing(:children).to_sql
  end

  def test_where_missing
    Post.destroy_all
    post = Post.create!
    post.children << Post.create!

    assert_equal 2, Post.count
    assert_equal 1, Post.where.missing(:children).count
  end
end

```

Note : my sincerest apologies for my imperfect English. This is my first issue to the Rails repository. Any suggestions welcome so I can improve it 🙏

### LINKED ISSUE #47909: Unexpected alias added by where.missing(...)
Hi. I've upgrading my project to use unreleased Rails from `main`, and got an error.

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  if ARGV[0] == "main"
    gem "rails", github: "rails/rails", branch: "main"
  else
    gem "activerecord", "7.0.4.3"
  end

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table(:books, force: true) do |t|
    t.references :progress
  end

  create_table(:progresses, force: true) do |t|
    t.references :book
    t.integer :percentage, default: 0, null: false
  end
end

class Book < ActiveRecord::Base
  has_one :progress

  scope :without_progress, -> do
    where.missing(:progress)
  end

  scope :completed, -> do
    joins(:progress).merge(Progress.completed)
  end
end

class Progress < ActiveRecord::Base
  scope :completed, -> do
    where(percentage: 100)
  end
end

class BugTest < Minitest::Test
  def test_bug
    assert_equal 0, Book.completed.count
    assert_equal 0, Book.without_progress.count
    assert_equal 0, Book.without_progress.completed.count
  end
end
```

The last assertion passes on 7.0.4.3 and fails on `main` because `where.missing(:progress)` adds a table alias in `main`.
See query produced by `Book.where.missing(:progress)`:
```sql
-- Rails main
SELECT "books".* FROM "books" LEFT OUTER JOIN "progresses" "progress" ON "progress"."book_id" = "books"."id" WHERE "progress"."id" IS NULL

-- Rails 7.0.4.3
SELECT "books".* FROM "books" LEFT OUTER JOIN "progresses" ON "progresses"."book_id" = "books"."id" WHERE "progresses"."id" IS NULL
```

### Expected behavior
Rails 7.0.4.3 does not add alias for "progresses" table and returns 0:
```sql
SELECT COUNT(*) FROM "books" INNER JOIN "progresses" ON "progresses"."book_id" = "books"."id" WHERE "progresses"."id" IS NULL AND "progresses"."percentage" = ?
```

### Actual behavior
Rails `main` aliases "progresses" to "progress" and raises exception:
```sql
SELECT COUNT(*) FROM "books" INNER JOIN "progresses" "progress" ON "progress"."book_id" = "books"."id" WHERE "progress"."id" IS NULL AND "progresses"."percentage" = ?
```
Error: `ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: progresses.percentage`

### System configuration
**Rails version**: main (7.1.0.alpha)

**Ruby version**: `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]`

### LINKED ISSUE #48651: Behaviour of `where.missing` changed in rails 7.0.6
### Steps to reproduce

Create a model called `Publisher` that has an enum on the `name` attribute.

```ruby
class Publisher < ApplicationRecord
  belongs_to :listing

  enum name: {
    foo: 0,
    bar: 1
  }
end
```

Create another model named `Listing` that has a `has_many` association and scoped `has_one` associations to `Publisher`.

```ruby
class Listing < ApplicationRecord
  has_many :publishers, dependent: :destroy
  has_one :foo_listing, -> { foo }, class_name: Publisher.name
  has_one :bar_listing, -> { bar }, class_name: Publisher.name
end
```

Create an instance of Listing that has a `foo` publisher but not a `bar` publisher (using Factory Bot here for brevity).

```ruby
create(:listing, publishers: [build(:publisher, :foo)])
```

Run a query using `where.missing` to select listings with a `foo` publisher but not a `bar` publisher.

```ruby
Listing.joins(:foo_listing).where.missing(:bar_listing)
```

### Expected behavior

The query should return the listing created above. This works in Rails 7.0.5.1.

### Actual behavior

No records are returned in Rails 7.0.6.

The table alias seems to have changed in the generated SQL.

Rails 7.0.5.1:

```sql
SELECT listings.*
FROM listings
    INNER JOIN publishers ON publishers.name = 0 AND publishers.listing_id = listings.id
    LEFT OUTER JOIN publishers bar_listing ON bar_listing.name = 1
        AND bar_listing.listing_id = listings.id
WHERE bar_listing.id IS NULL
```

Rails-7.0.6:

```sql
SELECT listings.*
FROM listings
    INNER JOIN publishers ON publishers.name = 0 AND publishers.listing_id = listings.id
    LEFT OUTER JOIN publishers bar_listings_listings ON bar_listings_listings.name = 1
        AND bar_listings_listings.listing_id = listings.id
WHERE publishers.id IS NULL
```

Explicitly creating the left join and checking for blank ID works in 7.0.6:

```ruby
Listing.joins(:foo_listing).left_joins(:bar_listing).where(bar_listing: {id: nil})
```

### System configuration

**Rails version**: 7.0.6

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by paulreece**
This fix corrects the logic in both the associated and missing methods. If the reflection.options hash has a key/value pair for :class_name it will use the association. This fixes [48651](https://github.com/rails/rails/issues/48651) which was not returning the correct value when using an enum association and querying for a record that had one key of the enum but was missing another. This also fixes [44964](https://github.com/rails/rails/issues/44964) where ActiveRecord was not properly aliasing self-referencing relations. If the reflection.options doesn’t contain the key/value pair then it will use the reflection.table_name. This fixes  [47909](https://github.com/rails/rails/issues/47909) in which a user was trying to find records that were either missing a relation or were missing a relation that was ordered or unscoped or were missing a relation that was using extends in the query which resulted in an ActiveRecord Exception. It also allows for using extends in any of these capacities.

* [ X] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [X ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ X] Tests are added or updated if you fix a bug or add a feature.
* [X ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by zhuravel** [comment]
This break the following test:

``` ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  if ARGV[0] == "main"
    gem "rails", github: "rails/rails", branch: "main"
  elsif ARGV[0] == "pull_request_48861"
    gem "rails", github: "rails/rails", ref: "refs/pull/48861/head"
  else
    gem "activerecord", "7.0.6"
  end

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table(:books, force: true) do |t|
    t.references :progress
  end

  create_table(:progresses, force: true) do |t|
    t.references :book
    t.integer :percentage, default: 0, null: false
  end
end

module Pagination
  def page(number)
    # pagination code goes here
  end

  def per_page(number)
    # pagination code goes here
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  default_scope do
    extending(Pagination) # See https://apidock.com/rails/ActiveRecord/QueryMethods/extending
  end
end

class Book < ApplicationRecord
  has_one :progress

  scope :without_progress, -> do
    where.missing(:progress)
  end

  scope :completed, -> do
    joins(:progress).merge(Progress.completed)
  end
end

class Progress < ApplicationRecord
  scope :completed, -> do
    where(percentage: 100)
  end
end

class BugTest < Minitest::Test
  def test_bug
    books = Book.order(created_at: :desc) # or `books = Book.unscope(:where)`

    assert_equal 0, books.completed.count
    assert_equal 0, books.without_progress.count
    assert_equal 0, books.without_progress.completed.count
  end
end
```

Run with:
``` sh
ruby bug_test.rb pull_request_48861 # fails with code from this pull request
ruby bug_test.rb main # fails with code from Rails main
ruby bug_test.rb # passes on ActiveRecord v.7.0.6
```

**Comment by paulreece** [comment]
Yes I noticed that locally this morning too when I was testing other use cases.  I'm in the process of building a fix into this.  Thanks bringing it to my attention!

**Comment by paulreece** [comment]
@zhuravel I built in your default_scope extend into my test app which helped narrow it down :).  I think this should work for our needs now.

File: activerecord/lib/active_record/relation/query_methods.rb [hunk 1]
```diff
@@ -76,7 +76,7 @@ def associated(*associations)
         associations.each do |association|
           reflection = scope_association_reflection(association)
           @scope.joins!(association)
-          if @scope.values.size > 1
+          if reflection.options[:class_name] || (reflection.options[:class_name] && @scope.values[:extending])
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/relation/query_methods.rb:79]: Is there any case where `reflection.options[:class_name]` is `false` but `(reflection.options[:class_name] && @scope.values[:extending])` is `true`?

I don't get why this isn't only `reflection.options[:class_name] && @scope.values[:extending]`

Comment (paulreece) [reply activerecord/lib/active_record/relation/query_methods.rb]: Rafael, thanks for the feedback.  I had initially thought so because of an earlier iteration of this but I just ran it with out the `Or` clause and it works! Just pushed up a version with the `Or` removed.

File: activerecord/lib/active_record/relation/query_methods.rb [hunk 2]
```diff
@@ -127,7 +127,20 @@ def scope_association_reflection(association)
           reflection
         end
     end
+    # {:order=>[#<Arel::Nodes::Descending:0x0000000108ef8400 @expr=#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x0000000108618998 @name="books", @
```
Comment (eileencodes) [inline activerecord/lib/active_record/relation/query_methods.rb:130]: Can you remove these comments?

**Comment by eileencodes** [comment]
Thank you!

**Comment by eileencodes** [comment]
Backported this and https://github.com/rails/rails/pull/48861 to 7-0-stable.
