### PR TITLE
Fix async queries to work with query cache and other cached async queries

### LINKED ISSUE #50776: Rails 7.1.3: async_count returns a completed Promise instead of the value
### Steps to reproduce
Following this issue https://github.com/rails/rails/issues/50399

I updated my application to Rails `7.1.3` and now `async_count` returns `#<ActiveRecord::Promise status=complete>` instead of the value directly

I created a reproduction repo (same as last time) and updated the case 

https://github.com/guillaumebriday/async_count_bug

- here is the controller: https://github.com/guillaumebriday/async_count_bug/blob/main/app/controllers/posts_controller.rb#L5- 
- here is the view: https://github.com/guillaumebriday/async_count_bug/blob/main/app/views/posts/index.html.erb#L10-L11

ping @fatkodima 

### Actual behavior
We need to use `.value.value` to get the actual value instead of `.value` only as it was before

Screenshot 2024-01-16 at 21 05 29

### System configuration
**Rails version**: 7.1.3

**Ruby version**: 3.3.0

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #50776.

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb [hunk 1]
```diff
@@ -107,7 +107,12 @@ def select_all(arel, name = nil, binds = [], preparable: nil, async: false) # :n
 
           if async
             result = lookup_sql_cache(sql, name, binds) || super(sql, name, binds, preparable: preparable, async: async)
-            FutureResult::Complete.new(result)
+
+            if result.is_a?(FutureResult)
```
Comment (navidemad) [inline activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:111]: I tried your fix still same issue.
I found with that change it worked.

```suggestion
            if result.is_a?(FutureResult::Complete)
```

```ruby
result.class
ActiveRecord::FutureResult::Complete

result
#<ActiveRecord::FutureResult::Complete:0x0000000142b451c0
 @result=
  #<ActiveRecord::Result:0x0000000141c96778
   @column_types=
    {0=>#<ActiveModel::Type::Integer:0x0000000142271508 @limit=8, @precision=nil, @range=-9223372036854775808...9223372036854775808, @scale=nil>,
     "count"=>#<ActiveModel::Type::Integer:0x0000000142271508 @limit=8, @precision=nil, @range=-9223372036854775808...9223372036854775808, @scale=nil>},
   @columns=["count"],
   @hash_rows=nil,
   @rows=[[70]]>>

(ruby@puma: cluster worker 3: 94614 [yespark-rails]#95708) result.is_a?(FutureResult)
false
(ruby@puma: cluster worker 3: 94614 [yespark-rails]#95708) result.is_a?(FutureResult::Complete)
true
```

File: activerecord/test/cases/calculations_test.rb [hunk 2]
```diff
@@ -1242,6 +1242,11 @@ def test_calculation_with_query_cache
       count = ShipPart.count
       assert_async_equal count, ShipPart.async_count
     end
+
+    ShipPart.cache do
+      count = ShipPart.async_count
+      assert_equal count.value, ShipPart.async_count.value
```
Comment (franzliedke) [inline activerecord/test/cases/calculations_test.rb:1248]: For consistency?

```suggestion
      assert_async_equal count.value, ShipPart.async_count
```

Comment (fatkodima) [reply activerecord/test/cases/calculations_test.rb:1248]: Will not work, because `nil?` method is not defined on the `ActiveRecord::Promise`.

File: activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb (hunk 1 above)
Comment (navidemad) [reply activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:111]: You can find a reproducible case there:
https://gist.github.com/navidemad/e4af727d335faa3148d4675e698cba4e

File: activerecord/test/cases/calculations_test.rb (hunk 2 above)
Comment (franzliedke) [reply activerecord/test/cases/calculations_test.rb:1248]: Huh? If `count.value` returns a promise, something is wrong anyway, right? (Which is the bug we're talking about here.)

Comment (fatkodima) [reply activerecord/test/cases/calculations_test.rb]: Yeah, thanks. I missed that the `count.value` stayed in your example, so it works.

File: activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb (hunk 1 above)
Comment (fatkodima) [reply activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb]: Can you test now?

File: activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb [hunk 3]
```diff
@@ -107,7 +107,12 @@ def select_all(arel, name = nil, binds = [], preparable: nil, async: false) # :n
 
           if async
             result = lookup_sql_cache(sql, name, binds) || super(sql, name, binds, preparable: preparable, async: async)
-            FutureResult::Complete.new(result)
+
+            if result.is_a?(FutureResult) || result.is_a?(FutureResult::Complete)
```
Comment (fatkodima) [inline activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:111]: We need to test for both classes, because when async is configured in the app - we have `FutureResult::SelectAll` class and when not, `FutureResult::Complete`.

See https://github.com/rails/rails/blob/25b7f640749e0dbbf731a7f5696e5c785195f922/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L609-L636

Comment (franzliedke) [reply activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:111]: Good spot!

I don't suppose we can find a solution involving duck typing or something different more polymorphy-friendly? 🤔 

At least we could move this `if / else` in a method within the `FutureResult` module, to make it more likely for this case to be added if another class is added there?

```ruby
FutureResult.wrap(result)
```

Comment (byroot) [reply activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:111]: Yes. Would be good to introduce a predicate that is common to all `Result` classes. e.g. `Result#future?`

Comment (byroot) [reply activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:111]: But `FutureResult.wrap` is nice too.

Comment (fatkodima) [reply activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb]: Thank you for suggestions! ❤️ I implemented a `FutureResult.wrap` and also update a few places in the codebase to use it.

**Review by byroot — APPROVED** [review]

File: activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb (hunk 1 above)
Comment (navidemad) [reply activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb]: sorry for the delay, it works with your latest change
