### PR TITLE
Select only relevant SQL for payload name on eagerload test

### LINKED ISSUE #56456: ActiveRecord::InstrumentationTest#test_payload_name_on_eager_load fails
Managed to reproduce CI failure at https://buildkite.com/rails/rails/builds/125002#019b4e4d-69d7-4f38-8274-3de58d83bde6/L1449 and confirmed it also reproduces on main branch.

### Steps to reproduce

```ruby
cd activerecord
bundle exec rake db:postgresql:rebuild
ARCONN=postgresql bin/test "test/cases/active_record_schema_test.rb" "test/cases/active_record_test.rb" "test/cases/adapter_prevent_writes_test.rb" "test/cases/adapter_test.rb" "test/cases/aggregations_test.rb" "test/cases/annotate_test.rb" "test/cases/arel/attributes/attribute_test.rb" "test/cases/arel/attributes/math_test.rb" "test/cases/arel/attributes_test.rb" "test/cases/arel/collectors/bind_test.rb" "test/cases/arel/collectors/composite_test.rb" "test/cases/arel/collectors/sql_string_test.rb" "test/cases/arel/collectors/substitute_bind_collector_test.rb" "test/cases/arel/crud_test.rb" "test/cases/arel/delete_manager_test.rb" "test/cases/arel/factory_methods_test.rb" "test/cases/arel/insert_manager_test.rb" "test/cases/arel/nodes/and_test.rb" "test/cases/arel/nodes/as_test.rb" "test/cases/arel/nodes/ascending_test.rb" "test/cases/arel/nodes/bin_test.rb" "test/cases/arel/nodes/binary_test.rb" "test/cases/arel/nodes/bind_param_test.rb" "test/cases/arel/nodes/bound_sql_literal_test.rb" "test/cases/arel/nodes/case_test.rb" "test/cases/arel/nodes/casted_test.rb" "test/cases/arel/nodes/comment_test.rb" "test/cases/arel/nodes/count_test.rb" "test/cases/arel/nodes/cte_test.rb" "test/cases/arel/nodes/delete_statement_test.rb" "test/cases/arel/nodes/descending_test.rb" "test/cases/arel/nodes/distinct_test.rb" "test/cases/arel/nodes/equality_test.rb" "test/cases/arel/nodes/extract_test.rb" "test/cases/arel/nodes/false_test.rb" "test/cases/arel/nodes/filter_test.rb" "test/cases/arel/nodes/fragments_test.rb" "test/cases/arel/nodes/grouping_test.rb" "test/cases/arel/nodes/homogeneous_in_test.rb" "test/cases/arel/nodes/infix_operation_test.rb" "test/cases/arel/nodes/insert_statement_test.rb" "test/cases/arel/nodes/named_function_test.rb" "test/cases/arel/nodes/node_test.rb" "test/cases/arel/nodes/not_test.rb" "test/cases/arel/nodes/or_test.rb" "test/cases/arel/nodes/over_test.rb" "test/cases/arel/nodes/select_core_test.rb" "test/cases/arel/nodes/select_statement_test.rb" "test/cases/arel/nodes/sql_literal_test.rb" "test/cases/arel/nodes/sum_test.rb" "test/cases/arel/nodes/table_alias_test.rb" "test/cases/arel/nodes/true_test.rb" "test/cases/arel/nodes/unary_operation_test.rb" "test/cases/arel/nodes/update_statement_test.rb" "test/cases/arel/nodes/window_test.rb" "test/cases/arel/nodes_test.rb" "test/cases/arel/select_manager_test.rb" "test/cases/arel/table_test.rb" "test/cases/arel/update_manager_test.rb" "test/cases/arel/visitors/dispatch_contamination_test.rb" "test/cases/arel/visitors/dot_test.rb" "test/cases/arel/visitors/mysql_test.rb" "test/cases/arel/visitors/postgres_test.rb" "test/cases/arel/visitors/sqlite_test.rb" "test/cases/arel/visitors/to_sql_test.rb" "test/cases/assertions/query_assertions_test.rb" "test/cases/associations/belongs_to_associations_test.rb" "test/cases/associations/bidirectional_destroy_dependencies_test.rb" "test/cases/associations/callbacks_test.rb" "test/cases/associations/cascaded_eager_loading_test.rb" "test/cases/associations/deprecation_test.rb" "test/cases/associations/eager_load_includes_full_sti_class_test.rb" "test/cases/associations/eager_load_nested_include_test.rb" "test/cases/associations/eager_singularization_test.rb" "test/cases/associations/eager_test.rb" "test/cases/associations/extension_test.rb" "test/cases/associations/has_and_belongs_to_many_associations_test.rb" "test/cases/associations/has_many_associations_test.rb" "test/cases/associations/has_many_through_associations_test.rb" "test/cases/associations/has_many_through_disable_joins_associations_test.rb" "test/cases/associations/has_one_associations_test.rb" "test/cases/associations/has_one_through_associations_test.rb" "test/cases/associations/has_one_through_disable_joins_associations_test.rb" "test/cases/associations/inner_join_association_test.rb" "test/cases/associations/inverse_associations_test.rb" "test/cases/associations/join_model_test.rb" "test/cases/associations/left_outer_join_association_test.rb" "test/cases/associations/nested_error_test.rb" "test/cases/associations/nested_through_associations_test.rb" "test/cases/associations/required_test.rb" "test/cases/associations_test.rb" "test/cases/asynchronous_queries_test.rb" "test/cases/attribute_methods/read_test.rb" "test/cases/attribute_methods/time_zone_converter_test.rb" "test/cases/attribute_methods_test.rb" "test/cases/attributes_test.rb" "test/cases/autosave_association_test.rb" "test/cases/base_prevent_writes_test.rb" "test/cases/base_test.rb" "test/cases/batches_test.rb" "test/cases/binary_test.rb" "test/cases/bind_parameter_test.rb" "test/cases/boolean_test.rb" "test/cases/cache_key_test.rb" "test/cases/calculations_test.rb" "test/cases/callbacks_test.rb" "test/cases/clone_test.rb" "test/cases/coders/json_test.rb" "test/cases/coders/yaml_column_test.rb" "test/cases/collection_cache_key_test.rb" "test/cases/column_alias_test.rb" "test/cases/column_definition_test.rb" "test/cases/comment_test.rb" "test/cases/connection_adapters/adapter_leasing_test.rb" "test/cases/connection_adapters/connection_handler_test.rb" "test/cases/connection_adapters/connection_handlers_multi_db_test.rb" "test/cases/connection_adapters/connection_handlers_multi_pool_config_test.rb" "test/cases/connection_adapters/connection_handlers_sharding_db_test.rb" "test/cases/connection_adapters/connection_swapping_nested_test.rb" "test/cases/connection_adapters/merge_and_resolve_default_url_config_test.rb" "test/cases/connection_adapters/mysql_type_lookup_test.rb" "test/cases/connection_adapters/registration_test.rb" "test/cases/connection_adapters/schema_cache_test.rb" "test/cases/connection_adapters/standalone_connection_test.rb" "test/cases/connection_adapters/statement_pool_test.rb" "test/cases/connection_adapters/type_lookup_test.rb" "test/cases/connection_handling_test.rb" "test/cases/connection_management_test.rb" "test/cases/connection_pool_test.rb" "test/cases/core_test.rb" "test/cases/counter_cache_test.rb" "test/cases/custom_locking_test.rb" "test/cases/database_configurations/hash_config_test.rb" "test/cases/database_configurations/resolver_test.rb" "test/cases/database_configurations/url_config_test.rb" "test/cases/database_configurations_test.rb" "test/cases/database_selector_test.rb" "test/cases/database_statements_test.rb" "test/cases/date_test.rb" "test/cases/date_time_precision_test.rb" "test/cases/date_time_test.rb" "test/cases/defaults_test.rb" "test/cases/delegated_type_test.rb" "test/cases/dirty_test.rb" "test/cases/disconnected_test.rb" "test/cases/dup_test.rb" "test/cases/encryption/cipher/aes256_gcm_test.rb" "test/cases/encryption/cipher_test.rb" "test/cases/encryption/concurrency_test.rb" "test/cases/encryption/config_test.rb" "test/cases/encryption/configurable_test.rb" "test/cases/encryption/contexts_test.rb" "test/cases/encryption/derived_secret_key_provider_test.rb" "test/cases/encryption/deterministic_key_provider_test.rb" "test/cases/encryption/encryptable_record_api_test.rb" "test/cases/encryption/encryptable_record_message_pack_serialized_test.rb" "test/cases/encryption/encryptable_record_test.rb" "test/cases/encryption/encrypted_fixtures_test.rb" "test/cases/encryption/encrypting_only_encryptor_test.rb" "test/cases/encryption/encryption_schemes_test.rb" "test/cases/encryption/encryptor_test.rb" "test/cases/encryption/envelope_encryption_key_provider_test.rb" "test/cases/encryption/extended_deterministic_queries_test.rb" "test/cases/encryption/key_generator_test.rb" "test/cases/encryption/key_provider_test.rb" "test/cases/encryption/key_test.rb" "test/cases/encryption/message_pack_message_serializer_test.rb" "test/cases/encryption/message_serializer_test.rb" "test/cases/encryption/message_test.rb" "test/cases/encryption/null_encryptor_test.rb" "test/cases/encryption/properties_test.rb" "test/cases/encryption/read_only_null_encryptor_test.rb" "test/cases/encryption/scheme_test.rb" "test/cases/encryption/unencrypted_attributes_test.rb" "test/cases/encryption/uniqueness_validations_test.rb" "test/cases/enum_test.rb" "test/cases/errors_test.rb" "test/cases/excluding_test.rb" "test/cases/explain_subscriber_test.rb" "test/cases/explain_test.rb" "test/cases/filter_attributes_test.rb" "test/cases/finder_respond_to_test.rb" "test/cases/finder_test.rb" "test/cases/fixture_set/file_test.rb" "test/cases/fixtures_test.rb" "test/cases/forbidden_attributes_protection_test.rb" "test/cases/habtm_destroy_order_test.rb" "test/cases/hot_compatibility_test.rb" "test/cases/i18n_test.rb" "test/cases/inheritance_test.rb" "test/cases/inherited_test.rb" "test/cases/insert_all_test.rb" "test/cases/instrumentation_test.rb" "test/cases/integration_test.rb" "test/cases/invalid_connection_test.rb" "test/cases/invertible_migration_test.rb" "test/cases/json_attribute_test.rb" "test/cases/json_serialization_test.rb" "test/cases/locking_test.rb" "test/cases/log_subscriber_test.rb" "test/cases/marshal_serialization_test.rb" "test/cases/message_pack_test.rb" "test/cases/migration/change_schema_test.rb" "test/cases/migration/change_table_test.rb" "test/cases/migration/check_constraint_test.rb" "test/cases/migration/column_attributes_test.rb" "test/cases/migration/column_positioning_test.rb" "test/cases/migration/columns_test.rb" "test/cases/migration/command_recorder_test.rb" "test/cases/migration/compatibility_test.rb" "test/cases/migration/create_join_table_test.rb" "test/cases/migration/exclusion_constraint_test.rb" "test/cases/migration/foreign_key_test.rb" "test/cases/migration/index_test.rb" "test/cases/migration/invalid_options_test.rb" "test/cases/migration/logger_test.rb" "test/cases/migration/pending_migrations_test.rb" "test/cases/migration/references_foreign_key_test.rb" "test/cases/migration/references_index_test.rb" "test/cases/migration/references_statements_test.rb" "test/cases/migration/rename_table_test.rb" "test/cases/migration/schema_definitions_test.rb" "test/cases/migration/unique_constraint_test.rb" "test/cases/migration_test.rb" "test/cases/migrator_test.rb" "test/cases/mixin_test.rb" "test/cases/modules_test.rb" "test/cases/multi_db_migrator_test.rb" "test/cases/multiparameter_attributes_test.rb" "test/cases/multiple_db_test.rb" "test/cases/nested_attributes_test.rb" "test/cases/nested_attributes_with_callbacks_test.rb" "test/cases/normalized_attribute_test.rb" "test/cases/null_relation_test.rb" "test/cases/numeric_data_test.rb" "test/cases/persistence/reload_association_cache_test.rb" "test/cases/persistence_test.rb" "test/cases/pooled_connections_test.rb" "test/cases/prepared_statement_status_test.rb" "test/cases/primary_class_test.rb" "test/cases/primary_keys_test.rb" "test/cases/query_cache_test.rb" "test/cases/query_logs_test.rb" "test/cases/quoting_test.rb" "test/cases/readonly_test.rb" "test/cases/reaper_test.rb" "test/cases/reflection_test.rb" "test/cases/relation/and_test.rb" "test/cases/relation/delegation_test.rb" "test/cases/relation/delete_all_test.rb" "test/cases/relation/field_ordered_values_test.rb" "test/cases/relation/load_async_test.rb" "test/cases/relation/merging_test.rb" "test/cases/relation/mutation_test.rb" "test/cases/relation/or_test.rb" "test/cases/relation/order_test.rb" "test/cases/relation/predicate_builder_test.rb" "test/cases/relation/select_test.rb" "test/cases/relation/structural_compatibility_test.rb" "test/cases/relation/update_all_test.rb" "test/cases/relation/where_chain_test.rb" "test/cases/relation/where_clause_test.rb" "test/cases/relation/where_test.rb" "test/cases/relation/with_test.rb" "test/cases/relation_test.rb" "test/cases/relations_test.rb" "test/cases/reload_models_test.rb" "test/cases/reserved_word_test.rb" "test/cases/result_test.rb" "test/cases/sanitize_test.rb" "test/cases/schema_dumper_test.rb" "test/cases/schema_loading_test.rb" "test/cases/scoping/default_scoping_test.rb" "test/cases/scoping/named_scoping_test.rb" "test/cases/scoping/relation_scoping_test.rb" "test/cases/secure_password_test.rb" "test/cases/secure_token_test.rb" "test/cases/serialization_test.rb" "test/cases/serialized_attribute_test.rb" "test/cases/shard_keys_test.rb" "test/cases/shard_selector_test.rb" "test/cases/signed_id_test.rb" "test/cases/statement_cache_test.rb" "test/cases/statement_invalid_test.rb" "test/cases/store_test.rb" "test/cases/strict_loading_test.rb" "test/cases/structured_event_subscriber_test.rb" "test/cases/suppressor_test.rb" "test/cases/table_metadata_test.rb" "test/cases/tasks/database_tasks_test.rb" "test/cases/test_databases_test.rb" "test/cases/test_fixtures_test.rb" "test/cases/time_precision_test.rb" "test/cases/timestamp_test.rb" "test/cases/token_for_test.rb" "test/cases/touch_later_test.rb" "test/cases/transaction_callbacks_test.rb" "test/cases/transaction_instrumentation_test.rb" "test/cases/transaction_isolation_test.rb" "test/cases/transactions_test.rb" "test/cases/type/adapter_specific_registry_test.rb" "test/cases/type/date_time_test.rb" "test/cases/type/integer_test.rb" "test/cases/type/string_test.rb" "test/cases/type/time_test.rb" "test/cases/type/type_map_test.rb" "test/cases/type/unsigned_integer_test.rb" "test/cases/type_caster/connection_test.rb" "test/cases/type_test.rb" "test/cases/types_test.rb" "test/cases/unconnected_test.rb" "test/cases/unsafe_raw_sql_test.rb" "test/cases/validations/absence_validation_test.rb" "test/cases/validations/association_validation_test.rb" "test/cases/validations/i18n_generate_message_validation_test.rb" "test/cases/validations/i18n_validation_test.rb" "test/cases/validations/length_validation_test.rb" "test/cases/validations/numericality_validation_test.rb" "test/cases/validations/presence_validation_test.rb" "test/cases/validations/uniqueness_validation_test.rb" "test/cases/validations_test.rb" "test/cases/view_test.rb" "test/cases/yaml_serialization_test.rb" "test/cases/adapters/postgresql/active_schema_test.rb" "test/cases/adapters/postgresql/array_test.rb" "test/cases/adapters/postgresql/bind_parameter_test.rb" "test/cases/adapters/postgresql/bit_string_test.rb" "test/cases/adapters/postgresql/bytea_test.rb" "test/cases/adapters/postgresql/case_insensitive_test.rb" "test/cases/adapters/postgresql/change_schema_test.rb" "test/cases/adapters/postgresql/cidr_test.rb" "test/cases/adapters/postgresql/citext_test.rb" "test/cases/adapters/postgresql/collation_test.rb" "test/cases/adapters/postgresql/composite_test.rb" "test/cases/adapters/postgresql/connection_test.rb" "test/cases/adapters/postgresql/create_unlogged_tables_test.rb" "test/cases/adapters/postgresql/datatype_test.rb" "test/cases/adapters/postgresql/date_test.rb" "test/cases/adapters/postgresql/dbconsole_test.rb" "test/cases/adapters/postgresql/deferred_constraints_test.rb" "test/cases/adapters/postgresql/domain_test.rb" "test/cases/adapters/postgresql/enum_test.rb" "test/cases/adapters/postgresql/explain_test.rb" "test/cases/adapters/postgresql/extension_migration_test.rb" "test/cases/adapters/postgresql/foreign_table_test.rb" "test/cases/adapters/postgresql/full_text_test.rb" "test/cases/adapters/postgresql/geometric_test.rb" "test/cases/adapters/postgresql/hstore_test.rb" "test/cases/adapters/postgresql/infinity_test.rb" "test/cases/adapters/postgresql/integer_test.rb" "test/cases/adapters/postgresql/interval_test.rb" "test/cases/adapters/postgresql/invertible_migration_test.rb" "test/cases/adapters/postgresql/json_test.rb" "test/cases/adapters/postgresql/ltree_test.rb" "test/cases/adapters/postgresql/money_test.rb" "test/cases/adapters/postgresql/network_test.rb" "test/cases/adapters/postgresql/numbers_test.rb" "test/cases/adapters/postgresql/optimizer_hints_test.rb" "test/cases/adapters/postgresql/partitions_test.rb" "test/cases/adapters/postgresql/postgresql_adapter_prevent_writes_test.rb" "test/cases/adapters/postgresql/postgresql_adapter_test.rb" "test/cases/adapters/postgresql/postgresql_rake_test.rb" "test/cases/adapters/postgresql/prepared_statements_disabled_test.rb" "test/cases/adapters/postgresql/quoting_test.rb" "test/cases/adapters/postgresql/range_test.rb" "test/cases/adapters/postgresql/referential_integrity_test.rb" "test/cases/adapters/postgresql/rename_table_test.rb" "test/cases/adapters/postgresql/schema_authorization_test.rb" "test/cases/adapters/postgresql/schema_test.rb" "test/cases/adapters/postgresql/serial_test.rb" "test/cases/adapters/postgresql/statement_pool_test.rb" "test/cases/adapters/postgresql/timestamp_test.rb" "test/cases/adapters/postgresql/transaction_nested_test.rb" "test/cases/adapters/postgresql/transaction_test.rb" "test/cases/adapters/postgresql/type_lookup_test.rb" "test/cases/adapters/postgresql/utils_test.rb" "test/cases/adapters/postgresql/uuid_test.rb" "test/cases/adapters/postgresql/virtual_column_test.rb" "test/cases/adapters/postgresql/xml_test.rb" -n "/^(?:ActiveRecord::Encryption::SchemeTest#(?:test_should_create_a_encryptor_well_when_compress_is_false)|TransactionInstrumentationTest#(?:test_transaction_instrumentation_on_failed_rollback)|ActiveRecord::InstrumentationTest#(?:test_payload_name_on_eager_load))$/" --seed 11440 -v
```

### Expected behavior
It should pass.

### Actual behavior
`ActiveRecord::InstrumentationTest#test_payload_name_on_eager_load` fails.

```
$ ARCONN=postgresql bin/test "test/cases/active_record_schema_test.rb" "test/cases/active_record_test.rb" "test/cases/adapter_prevent_writes_test.rb" "test/cases/adapter_test.rb" "test/cases/aggregations_test.rb" "test/cases/annotate_test.rb" "test/cases/arel/attributes/attribute_test.rb" "test/cases/arel/attributes/math_test.rb" "test/cases/arel/attributes_test.rb" "test/cases/arel/collectors/bind_test.rb" "test/cases/arel/collectors/composite_test.rb" "test/cases/arel/collectors/sql_string_test.rb" "test/cases/arel/collectors/substitute_bind_collector_test.rb" "test/cases/arel/crud_test.rb" "test/cases/arel/delete_manager_test.rb" "test/cases/arel/factory_methods_test.rb" "test/cases/arel/insert_manager_test.rb" "test/cases/arel/nodes/and_test.rb" "test/cases/arel/nodes/as_test.rb" "test/cases/arel/nodes/ascending_test.rb" "test/cases/arel/nodes/bin_test.rb" "test/cases/arel/nodes/binary_test.rb" "test/cases/arel/nodes/bind_param_test.rb" "test/cases/arel/nodes/bound_sql_literal_test.rb" "test/cases/arel/nodes/case_test.rb" "test/cases/arel/nodes/casted_test.rb" "test/cases/arel/nodes/comment_test.rb" "test/cases/arel/nodes/count_test.rb" "test/cases/arel/nodes/cte_test.rb" "test/cases/arel/nodes/delete_statement_test.rb" "test/cases/arel/nodes/descending_test.rb" "test/cases/arel/nodes/distinct_test.rb" "test/cases/arel/nodes/equality_test.rb" "test/cases/arel/nodes/extract_test.rb" "test/cases/arel/nodes/false_test.rb" "test/cases/arel/nodes/filter_test.rb" "test/cases/arel/nodes/fragments_test.rb" "test/cases/arel/nodes/grouping_test.rb" "test/cases/arel/nodes/homogeneous_in_test.rb" "test/cases/arel/nodes/infix_operation_test.rb" "test/cases/arel/nodes/insert_statement_test.rb" "test/cases/arel/nodes/named_function_test.rb" "test/cases/arel/nodes/node_test.rb" "test/cases/arel/nodes/not_test.rb" "test/cases/arel/nodes/or_test.rb" "test/cases/arel/nodes/over_test.rb" "test/cases/arel/nodes/select_core_test.rb" "test/cases/arel/nodes/select_statement_test.rb" "test/cases/arel/nodes/sql_literal_test.rb" "test/cases/arel/nodes/sum_test.rb" "test/cases/arel/nodes/table_alias_test.rb" "test/cases/arel/nodes/true_test.rb" "test/cases/arel/nodes/unary_operation_test.rb" "test/cases/arel/nodes/update_statement_test.rb" "test/cases/arel/nodes/window_test.rb" "test/cases/arel/nodes_test.rb" "test/cases/arel/select_manager_test.rb" "test/cases/arel/table_test.rb" "test/cases/arel/update_manager_test.rb" "test/cases/arel/visitors/dispatch_contamination_test.rb" "test/cases/arel/visitors/dot_test.rb" "test/cases/arel/visitors/mysql_test.rb" "test/cases/arel/visitors/postgres_test.rb" "test/cases/arel/visitors/sqlite_test.rb" "test/cases/arel/visitors/to_sql_test.rb" "test/cases/assertions/query_assertions_test.rb" "test/cases/associations/belongs_to_associations_test.rb" "test/cases/associations/bidirectional_destroy_dependencies_test.rb" "test/cases/associations/callbacks_test.rb" "test/cases/associations/cascaded_eager_loading_test.rb" "test/cases/associations/deprecation_test.rb" "test/cases/associations/eager_load_includes_full_sti_class_test.rb" "test/cases/associations/eager_load_nested_include_test.rb" "test/cases/associations/eager_singularization_test.rb" "test/cases/associations/eager_test.rb" "test/cases/associations/extension_test.rb" "test/cases/associations/has_and_belongs_to_many_associations_test.rb" "test/cases/associations/has_many_associations_test.rb" "test/cases/associations/has_many_through_associations_test.rb" "test/cases/associations/has_many_through_disable_joins_associations_test.rb" "test/cases/associations/has_one_associations_test.rb" "test/cases/associations/has_one_through_associations_test.rb" "test/cases/associations/has_one_through_disable_joins_associations_test.rb" "test/cases/associations/inner_join_association_test.rb" "test/cases/associations/inverse_associations_test.rb" "test/cases/associations/join_model_test.rb" "test/cases/associations/left_outer_join_association_test.rb" "test/cases/associations/nested_error_test.rb" "test/cases/associations/nested_through_associations_test.rb" "test/cases/associations/required_test.rb" "test/cases/associations_test.rb" "test/cases/asynchronous_queries_test.rb" "test/cases/attribute_methods/read_test.rb" "test/cases/attribute_methods/time_zone_converter_test.rb" "test/cases/attribute_methods_test.rb" "test/cases/attributes_test.rb" "test/cases/autosave_association_test.rb" "test/cases/base_prevent_writes_test.rb" "test/cases/base_test.rb" "test/cases/batches_test.rb" "test/cases/binary_test.rb" "test/cases/bind_parameter_test.rb" "test/cases/boolean_test.rb" "test/cases/cache_key_test.rb" "test/cases/calculations_test.rb" "test/cases/callbacks_test.rb" "test/cases/clone_test.rb" "test/cases/coders/json_test.rb" "test/cases/coders/yaml_column_test.rb" "test/cases/collection_cache_key_test.rb" "test/cases/column_alias_test.rb" "test/cases/column_definition_test.rb" "test/cases/comment_test.rb" "test/cases/connection_adapters/adapter_leasing_test.rb" "test/cases/connection_adapters/connection_handler_test.rb" "test/cases/connection_adapters/connection_handlers_multi_db_test.rb" "test/cases/connection_adapters/connection_handlers_multi_pool_config_test.rb" "test/cases/connection_adapters/connection_handlers_sharding_db_test.rb" "test/cases/connection_adapters/connection_swapping_nested_test.rb" "test/cases/connection_adapters/merge_and_resolve_default_url_config_test.rb" "test/cases/connection_adapters/mysql_type_lookup_test.rb" "test/cases/connection_adapters/registration_test.rb" "test/cases/connection_adapters/schema_cache_test.rb" "test/cases/connection_adapters/standalone_connection_test.rb" "test/cases/connection_adapters/statement_pool_test.rb" "test/cases/connection_adapters/type_lookup_test.rb" "test/cases/connection_handling_test.rb" "test/cases/connection_management_test.rb" "test/cases/connection_pool_test.rb" "test/cases/core_test.rb" "test/cases/counter_cache_test.rb" "test/cases/custom_locking_test.rb" "test/cases/database_configurations/hash_config_test.rb" "test/cases/database_configurations/resolver_test.rb" "test/cases/database_configurations/url_config_test.rb" "test/cases/database_configurations_test.rb" "test/cases/database_selector_test.rb" "test/cases/database_statements_test.rb" "test/cases/date_test.rb" "test/cases/date_time_precision_test.rb" "test/cases/date_time_test.rb" "test/cases/defaults_test.rb" "test/cases/delegated_type_test.rb" "test/cases/dirty_test.rb" "test/cases/disconnected_test.rb" "test/cases/dup_test.rb" "test/cases/encryption/cipher/aes256_gcm_test.rb" "test/cases/encryption/cipher_test.rb" "test/cases/encryption/concurrency_test.rb" "test/cases/encryption/config_test.rb" "test/cases/encryption/configurable_test.rb" "test/cases/encryption/contexts_test.rb" "test/cases/encryption/derived_secret_key_provider_test.rb" "test/cases/encryption/deterministic_key_provider_test.rb" "test/cases/encryption/encryptable_record_api_test.rb" "test/cases/encryption/encryptable_record_message_pack_serialized_test.rb" "test/cases/encryption/encryptable_record_test.rb" "test/cases/encryption/encrypted_fixtures_test.rb" "test/cases/encryption/encrypting_only_encryptor_test.rb" "test/cases/encryption/encryption_schemes_test.rb" "test/cases/encryption/encryptor_test.rb" "test/cases/encryption/envelope_encryption_key_provider_test.rb" "test/cases/encryption/extended_deterministic_queries_test.rb" "test/cases/encryption/key_generator_test.rb" "test/cases/encryption/key_provider_test.rb" "test/cases/encryption/key_test.rb" "test/cases/encryption/message_pack_message_serializer_test.rb" "test/cases/encryption/message_serializer_test.rb" "test/cases/encryption/message_test.rb" "test/cases/encryption/null_encryptor_test.rb" "test/cases/encryption/properties_test.rb" "test/cases/encryption/read_only_null_encryptor_test.rb" "test/cases/encryption/scheme_test.rb" "test/cases/encryption/unencrypted_attributes_test.rb" "test/cases/encryption/uniqueness_validations_test.rb" "test/cases/enum_test.rb" "test/cases/errors_test.rb" "test/cases/excluding_test.rb" "test/cases/explain_subscriber_test.rb" "test/cases/explain_test.rb" "test/cases/filter_attributes_test.rb" "test/cases/finder_respond_to_test.rb" "test/cases/finder_test.rb" "test/cases/fixture_set/file_test.rb" "test/cases/fixtures_test.rb" "test/cases/forbidden_attributes_protection_test.rb" "test/cases/habtm_destroy_order_test.rb" "test/cases/hot_compatibility_test.rb" "test/cases/i18n_test.rb" "test/cases/inheritance_test.rb" "test/cases/inherited_test.rb" "test/cases/insert_all_test.rb" "test/cases/instrumentation_test.rb" "test/cases/integration_test.rb" "test/cases/invalid_connection_test.rb" "test/cases/invertible_migration_test.rb" "test/cases/json_attribute_test.rb" "test/cases/json_serialization_test.rb" "test/cases/locking_test.rb" "test/cases/log_subscriber_test.rb" "test/cases/marshal_serialization_test.rb" "test/cases/message_pack_test.rb" "test/cases/migration/change_schema_test.rb" "test/cases/migration/change_table_test.rb" "test/cases/migration/check_constraint_test.rb" "test/cases/migration/column_attributes_test.rb" "test/cases/migration/column_positioning_test.rb" "test/cases/migration/columns_test.rb" "test/cases/migration/command_recorder_test.rb" "test/cases/migration/compatibility_test.rb" "test/cases/migration/create_join_table_test.rb" "test/cases/migration/exclusion_constraint_test.rb" "test/cases/migration/foreign_key_test.rb" "test/cases/migration/index_test.rb" "test/cases/migration/invalid_options_test.rb" "test/cases/migration/logger_test.rb" "test/cases/migration/pending_migrations_test.rb" "test/cases/migration/references_foreign_key_test.rb" "test/cases/migration/references_index_test.rb" "test/cases/migration/references_statements_test.rb" "test/cases/migration/rename_table_test.rb" "test/cases/migration/schema_definitions_test.rb" "test/cases/migration/unique_constraint_test.rb" "test/cases/migration_test.rb" "test/cases/migrator_test.rb" "test/cases/mixin_test.rb" "test/cases/modules_test.rb" "test/cases/multi_db_migrator_test.rb" "test/cases/multiparameter_attributes_test.rb" "test/cases/multiple_db_test.rb" "test/cases/nested_attributes_test.rb" "test/cases/nested_attributes_with_callbacks_test.rb" "test/cases/normalized_attribute_test.rb" "test/cases/null_relation_test.rb" "test/cases/numeric_data_test.rb" "test/cases/persistence/reload_association_cache_test.rb" "test/cases/persistence_test.rb" "test/cases/pooled_connections_test.rb" "test/cases/prepared_statement_status_test.rb" "test/cases/primary_class_test.rb" "test/cases/primary_keys_test.rb" "test/cases/query_cache_test.rb" "test/cases/query_logs_test.rb" "test/cases/quoting_test.rb" "test/cases/readonly_test.rb" "test/cases/reaper_test.rb" "test/cases/reflection_test.rb" "test/cases/relation/and_test.rb" "test/cases/relation/delegation_test.rb" "test/cases/relation/delete_all_test.rb" "test/cases/relation/field_ordered_values_test.rb" "test/cases/relation/load_async_test.rb" "test/cases/relation/merging_test.rb" "test/cases/relation/mutation_test.rb" "test/cases/relation/or_test.rb" "test/cases/relation/order_test.rb" "test/cases/relation/predicate_builder_test.rb" "test/cases/relation/select_test.rb" "test/cases/relation/structural_compatibility_test.rb" "test/cases/relation/update_all_test.rb" "test/cases/relation/where_chain_test.rb" "test/cases/relation/where_clause_test.rb" "test/cases/relation/where_test.rb" "test/cases/relation/with_test.rb" "test/cases/relation_test.rb" "test/cases/relations_test.rb" "test/cases/reload_models_test.rb" "test/cases/reserved_word_test.rb" "test/cases/result_test.rb" "test/cases/sanitize_test.rb" "test/cases/schema_dumper_test.rb" "test/cases/schema_loading_test.rb" "test/cases/scoping/default_scoping_test.rb" "test/cases/scoping/named_scoping_test.rb" "test/cases/scoping/relation_scoping_test.rb" "test/cases/secure_password_test.rb" "test/cases/secure_token_test.rb" "test/cases/serialization_test.rb" "test/cases/serialized_attribute_test.rb" "test/cases/shard_keys_test.rb" "test/cases/shard_selector_test.rb" "test/cases/signed_id_test.rb" "test/cases/statement_cache_test.rb" "test/cases/statement_invalid_test.rb" "test/cases/store_test.rb" "test/cases/strict_loading_test.rb" "test/cases/structured_event_subscriber_test.rb" "test/cases/suppressor_test.rb" "test/cases/table_metadata_test.rb" "test/cases/tasks/database_tasks_test.rb" "test/cases/test_databases_test.rb" "test/cases/test_fixtures_test.rb" "test/cases/time_precision_test.rb" "test/cases/timestamp_test.rb" "test/cases/token_for_test.rb" "test/cases/touch_later_test.rb" "test/cases/transaction_callbacks_test.rb" "test/cases/transaction_instrumentation_test.rb" "test/cases/transaction_isolation_test.rb" "test/cases/transactions_test.rb" "test/cases/type/adapter_specific_registry_test.rb" "test/cases/type/date_time_test.rb" "test/cases/type/integer_test.rb" "test/cases/type/string_test.rb" "test/cases/type/time_test.rb" "test/cases/type/type_map_test.rb" "test/cases/type/unsigned_integer_test.rb" "test/cases/type_caster/connection_test.rb" "test/cases/type_test.rb" "test/cases/types_test.rb" "test/cases/unconnected_test.rb" "test/cases/unsafe_raw_sql_test.rb" "test/cases/validations/absence_validation_test.rb" "test/cases/validations/association_validation_test.rb" "test/cases/validations/i18n_generate_message_validation_test.rb" "test/cases/validations/i18n_validation_test.rb" "test/cases/validations/length_validation_test.rb" "test/cases/validations/numericality_validation_test.rb" "test/cases/validations/presence_validation_test.rb" "test/cases/validations/uniqueness_validation_test.rb" "test/cases/validations_test.rb" "test/cases/view_test.rb" "test/cases/yaml_serialization_test.rb" "test/cases/adapters/postgresql/active_schema_test.rb" "test/cases/adapters/postgresql/array_test.rb" "test/cases/adapters/postgresql/bind_parameter_test.rb" "test/cases/adapters/postgresql/bit_string_test.rb" "test/cases/adapters/postgresql/bytea_test.rb" "test/cases/adapters/postgresql/case_insensitive_test.rb" "test/cases/adapters/postgresql/change_schema_test.rb" "test/cases/adapters/postgresql/cidr_test.rb" "test/cases/adapters/postgresql/citext_test.rb" "test/cases/adapters/postgresql/collation_test.rb" "test/cases/adapters/postgresql/composite_test.rb" "test/cases/adapters/postgresql/connection_test.rb" "test/cases/adapters/postgresql/create_unlogged_tables_test.rb" "test/cases/adapters/postgresql/datatype_test.rb" "test/cases/adapters/postgresql/date_test.rb" "test/cases/adapters/postgresql/dbconsole_test.rb" "test/cases/adapters/postgresql/deferred_constraints_test.rb" "test/cases/adapters/postgresql/domain_test.rb" "test/cases/adapters/postgresql/enum_test.rb" "test/cases/adapters/postgresql/explain_test.rb" "test/cases/adapters/postgresql/extension_migration_test.rb" "test/cases/adapters/postgresql/foreign_table_test.rb" "test/cases/adapters/postgresql/full_text_test.rb" "test/cases/adapters/postgresql/geometric_test.rb" "test/cases/adapters/postgresql/hstore_test.rb" "test/cases/adapters/postgresql/infinity_test.rb" "test/cases/adapters/postgresql/integer_test.rb" "test/cases/adapters/postgresql/interval_test.rb" "test/cases/adapters/postgresql/invertible_migration_test.rb" "test/cases/adapters/postgresql/json_test.rb" "test/cases/adapters/postgresql/ltree_test.rb" "test/cases/adapters/postgresql/money_test.rb" "test/cases/adapters/postgresql/network_test.rb" "test/cases/adapters/postgresql/numbers_test.rb" "test/cases/adapters/postgresql/optimizer_hints_test.rb" "test/cases/adapters/postgresql/partitions_test.rb" "test/cases/adapters/postgresql/postgresql_adapter_prevent_writes_test.rb" "test/cases/adapters/postgresql/postgresql_adapter_test.rb" "test/cases/adapters/postgresql/postgresql_rake_test.rb" "test/cases/adapters/postgresql/prepared_statements_disabled_test.rb" "test/cases/adapters/postgresql/quoting_test.rb" "test/cases/adapters/postgresql/range_test.rb" "test/cases/adapters/postgresql/referential_integrity_test.rb" "test/cases/adapters/postgresql/rename_table_test.rb" "test/cases/adapters/postgresql/schema_authorization_test.rb" "test/cases/adapters/postgresql/schema_test.rb" "test/cases/adapters/postgresql/serial_test.rb" "test/cases/adapters/postgresql/statement_pool_test.rb" "test/cases/adapters/postgresql/timestamp_test.rb" "test/cases/adapters/postgresql/transaction_nested_test.rb" "test/cases/adapters/postgresql/transaction_test.rb" "test/cases/adapters/postgresql/type_lookup_test.rb" "test/cases/adapters/postgresql/utils_test.rb" "test/cases/adapters/postgresql/uuid_test.rb" "test/cases/adapters/postgresql/virtual_column_test.rb" "test/cases/adapters/postgresql/xml_test.rb" -n "/^(?:ActiveRecord::Encryption::SchemeTest#(?:test_should_create_a_encryptor_well_when_compress_is_false)|TransactionInstrumentationTest#(?:test_transaction_instrumentation_on_failed_rollback)|ActiveRecord::InstrumentationTest#(?:test_payload_name_on_eager_load))$/" --seed 11440 -v
Please switch from -n/--name to -i/--include
Using postgresql
Run options: -n "/^(?:ActiveRecord::Encryption::SchemeTest#(?:test_should_create_a_encryptor_well_when_compress_is_false)|TransactionInstrumentationTest#(?:test_transaction_instrumentation_on_failed_rollback)|ActiveRecord::InstrumentationTest#(?:test_payload_name_on_eager_load))$/" --seed 11440 -v

# Running:

ActiveRecord::Encryption::SchemeTest#test_should_create_a_encryptor_well_when_compress_is_false = 0.03 s = .
TransactionInstrumentationTest#test_transaction_instrumentation_on_failed_rollback = 0.02 s = .
ActiveRecord::InstrumentationTest#test_payload_name_on_eager_load = 0.01 s = F


Failure:
ActiveRecord::InstrumentationTest#test_payload_name_on_eager_load [test/cases/instrumentation_test.rb:51]:
Expected: "Book Eager Load"
  Actual: "SCHEMA"


bin/test test/cases/instrumentation_test.rb:48


Finished in 0.153908s, 19.4921 runs/s, 32.4868 assertions/s.
3 runs, 5 assertions, 1 failures, 0 errors, 0 skips
$ 
```

### System configuration

**Rails version**: main branch

**Ruby version**: ruby 3.4.8 (2025-12-17 revision 995b59f666) +PRISM [x86_64-linux]

### PR DESCRIPTION
**Pull request by zzak**
Fixes: #56456

The SQL we are looking for is for the `books` table.

```sql
SELECT "books"."id" AS t0_r0, "books"."author_id" AS t0_r1, "books"."format" AS t0_r2, "books"."format_record_id" AS t0_r3, "books"."format_record_type" AS t0_r4, "books"."name" AS t0_r5, "books"."status" AS t0_r6, "books"."last_read" AS t0_r7, "books"."nullable_status" AS t0_r8, "books"."language" AS t0_r9, "books"."author_visibility" AS t0_r10, "books"."illustrator_visibility" AS t0_r11, "books"."font_size" AS t0_r12, "books"."difficulty" AS t0_r13, "books"."cover" AS t0_r14, "books"."symbol_status" AS t0_r15, "books"."isbn" AS t0_r16, "books"."external_id" AS t0_r17, "books"."original_name" AS t0_r18, "books"."published_on" AS t0_r19, "books"."boolean_status" AS t0_r20, "books"."tags_count" AS t0_r21, "books"."created_at" AS t0_r22, "books"."updated_at" AS t0_r23, "books"."updated_on" AS t0_r24, "authors"."id" AS t1_r0, "authors"."name" AS t1_r1, "authors"."author_address_id" AS t1_r2, "authors"."author_address_extra_id" AS t1_r3, "authors"."organization_id" AS t1_r4, "authors"."owned_essay_id" AS t1_r5, "authors"."published_author_id" AS t1_r6 FROM "books" LEFT OUTER JOIN "authors" ON "authors"."id" = "books"."author_id"
```

But there are other `sql.active_record` notifications which come through, like:

```sql
SHOW max_identifier_length
```

So we just need to filter, like the other tests in this file.

### CODE REVIEW

File: activerecord/test/cases/instrumentation_test.rb [hunk 1]
```diff
@@ -48,7 +48,8 @@ def test_payload_name_on_update_all
     def test_payload_name_on_eager_load
       ActiveRecord::Base.schema_cache.add(Author.table_name)
       notification = capture_notifications("sql.active_record") { Book.eager_load(:author).to_a }
-      assert_equal "Book Eager Load", notification.first.payload[:name]
+        .find { _1.payload[:sql].match?("SELECT") }
```
Comment (fatkodima) [inline activerecord/test/cases/instrumentation_test.rb:51]: `_1` is not obvious in this case - you need to read the previous code to know what it refers to. I initially thought it is `book`.

```suggestion
        .find { |notification| notification.payload[:sql].match?("SELECT") }
```

Comment (zzak) [reply activerecord/test/cases/instrumentation_test.rb:51]: @fatkodima Thanks for taking a look!

I understand, but this is the same for all the other tests here:
https://github.com/rails/rails/blob/92481359a7f74261059a292a7cea61e68144b57e/activerecord/test/cases/instrumentation_test.rb#L26-L46

Comment (fatkodima) [reply activerecord/test/cases/instrumentation_test.rb:51]: I would suggest not repeating the same bad pattern, but up to you.

Comment (zzak) [reply activerecord/test/cases/instrumentation_test.rb:51]: It's a [core feature](https://docs.ruby-lang.org/en/master/Proc.html#class-Proc-label-Anonymous+block+parameters) to Ruby, added in [2.7](https://github.com/ruby/ruby/blob/v2_7_0/NEWS#label-Numbered+parameters) -- so I think it's safe to use.

I was always taught to adapt to the consistency of the code in the file or project you're editting, but I understand that syntax sugar maybe confusing.

I'm happy to make it easier to read though if you feel strongly about it. :bow:

**Comment by yahonda** [comment]
As the reporter of #56456, I've confirmed that this pull request addresses the issue.
I appreciate the earlier feedback on `_1`, but since it's already used in instrumentation_test.rb, I think it's consistent to use it here as well. I'm going to merge this.
