### PR TITLE
Optimise length of default index name for polymorphic references.

### LINKED ISSUE #38655: Enhancement: shorten the default index name on polymorphic references
Not a bug but more of a small enhancement - I'm willing to submit a PR for this but wanted some feedback first before I spent any time on it.

### Steps to reproduce

When you create a polymorphic reference in a migration, Rails will generate an index by default using a combination of the ID and type column as the index name (the default behaviour when specifying an index over multiple columns):

```
create_table :widgets do |t|
  t.references :factory, polymorphic: true
end
```

This will produce an index named `index_factories_on_widget_type_and_widget_id`.

Postgres has a limit of only 63 characters for its index name. The above index name is already 44 characters and your table and association names don't need to be much longer before you increase the likelihood of it failing due to the index name length. This happened to me today and it's happened to me on numerous occasions before in this specific scenario.

### Desired behavior

It's easily worked around by setting an explicit index name but in the name of "convention over configuration" it would make more sense if the default when using `references` was for it to use the *reference name*, making the index name in the above scenario:

`index_factories_on_widget`.

That's a 17 character difference and greatly reduces the chance of this happening in the first place (you typically only realise once you've run the migration, it's failed and then you need to go back and change your migration);

### System configuration

**Rails version**: 6.0.2.1
**Ruby version**: 2.6.5

### PR DESCRIPTION
**Pull request by lukeredpath**
### Summary

This reduces the possibility of generating index names that are too long for certain databases (e.g. Postgres which has a 63 character limit) by naming the index based on the reference name rather than the type and id columns (the default behaviour of t.index).

This still allows the name to be explicitly specified by passing options.

Fixes #38655.

### CODE REVIEW

**Comment by lukeredpath** [comment]
@rafaelfranca PR as requested.

**Comment by lukeredpath** [comment]
Ugh, sorry I forgot Github's resolve conflicts creates a merge commit. I will rebase that now.

**Comment by rafaelfranca** [comment]
Thank you for the pull request. We can't change the index name for existent migrations. It should only be applied when the migration inherits from `ActiveRecord::Migration[6.1]`. So you need to change your patch to keep the old index name when the migration are not using the 6.1 version. Can you take a look on that?

**Comment by lukeredpath** [comment]
@rafaelfranca looking into it now - I think I've figured out how it works, just trying to get a failing test in `compatibility_test.rb` and then I'll push up a fix.

**Comment by lukeredpath** [comment]
@rafaelfranca right, I think that's looking good now.

**Comment by lukeredpath** [comment]
I've taken the approach of setting a private option in the overridden `references` method instead of trying to wrap `ReferenceDefinition` in a compatibility layer like `TableDefinition`. I tried this approach initially but because each call to `references` creates a new instance, wrapping it was tricky and my code was getting uglier and uglier. 

The internal option seemed like a reasonable compromise as it didn't require much modification even though it arguably introduces some legacy cruft in to the main implementation but if somebody has a better suggestion fo how to handle this I'll be happy to take another look.

File: activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb [hunk 1]
```diff
@@ -163,8 +163,18 @@ def polymorphic_options
...
-          as_options(index)
+        def polymorphic_index_name(table_name)
+          "index_#{table_name}_on_#{name}"
+        end
+
+        def index_options(table_name)
+          index_options = as_options(index)
+
+          # legacy reference index names are used on versions 6.0 and earlier
+          return index_options if options[:uses_legacy_reference_index_name]
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb:174]: Let's rename to `:_ uses_legacy_reference_index_name` to make explicit it is private.

**Comment by lukeredpath** [comment]
@rafaelfranca change made, build passing and rebased against master.

**Comment by lukeredpath** [comment]
Is there anything else I can do to help with getting this merged?

**Comment by lukeredpath** [comment]
I'm still keen to get this merged in if somebody is able to help get this over the line - @rafaelfranca, anyone?

**Comment by lukeredpath** [comment]
Is anyone able to look at this please? @rafaelfranca @pixeltrix

File: activerecord/lib/active_record/migration/compatibility.rb [hunk 2]
```diff
@@ -16,32 +16,13 @@ def self.find(version)
...
-      end
-
-      class V5_2 < V6_0
         module TableDefinition
-          def timestamps(**options)
-            options[:precision] ||= nil
+          def references(*args, **options)
+            options[:_uses_legacy_reference_index_name] = true
             super
           end
```
Comment (eugeneius) [inline activerecord/lib/active_record/migration/compatibility.rb:23]:
```suggestion
          end
          alias :belongs_to :references
```

We'll need to support [`add_reference` and `add_belongs_to`](https://github.com/rails/rails/blob/28a4d973318092ffe74a4e4ecbe8794a38dc6c99/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L970-L973) as well.

**Comment by eugeneius** [comment]
Regarding `_uses_legacy_reference_index_name`, what do you think of this approach to wrapping `ReferenceDefinition`:

```patch
diff --git a/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb b/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb
index 57c387d09c..493d93583f 100644
--- a/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb
+++ b/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb
@@ -195,9 +195,6 @@ def polymorphic_index_name(table_name)
         def index_options(table_name)
           index_options = as_options(index)

-          # legacy reference index names are used on versions 6.0 and earlier
-          return index_options if options[:_uses_legacy_reference_index_name]
-
           index_options[:name] ||= polymorphic_index_name(table_name) if polymorphic
           index_options
         end
diff --git a/activerecord/lib/active_record/migration/compatibility.rb b/activerecord/lib/active_record/migration/compatibility.rb
index ea727a12b2..6b1a2643a6 100644
--- a/activerecord/lib/active_record/migration/compatibility.rb
+++ b/activerecord/lib/active_record/migration/compatibility.rb
@@ -16,10 +16,17 @@ def self.find(version)
       V6_1 = Current

       class V6_0 < V6_1
+        class ReferenceDefinition < ConnectionAdapters::ReferenceDefinition
+          def index_options(table_name)
+            as_options(index)
+          end
+        end
+
         module TableDefinition
           def references(*args, **options)
-            options[:_uses_legacy_reference_index_name] = true
-            super
+            args.each do |ref_name|
+              ReferenceDefinition.new(ref_name, **options).add_to(self)
+            end
           end
         end
```

**Comment by lukeredpath** [comment]
I'm not sure when I'll have a chance to pick this up at the moment as I've just started a new role - your suggestion looks like a significant improvement over the private variable which felt a bit hacky though. If anybody else is able to jump on this that would be awesome.

**Comment by eugeneius** [comment]
I pushed those changes to your branch before merging. Thanks for working on this!
