### PR TITLE
Always save ActiveStorage::Blob before uploading to service

### LINKED ISSUE #34805: Activestorage does not reserve keys which can lead to overwritten blob contents
### Steps to reproduce

Override `ActiveStorage::Blob.generate_unique_secure_token` to generate the same value. Use a method that under the hood calls `create_after_upload!`. The database constraint will fire, but if the upload already has taken place and the target objectunder `key` has been overwritten.

```ruby
class << ActiveStorage::Blob
  def generate_unique_secure_token
    "totallyunique"
  end
end
ActiveStorage::Blob.generate_unique_secure_token #=> "totallyunique"
first_io = StringIO.new("this is the first file")
ActiveStorage::Blob.create_after_upload!(io: first_io, filename: "first", content_type: nil, metadata: nil)
```

which will suceed of course:

```
  Disk Storage (1.4ms) Uploaded file to key: totallyunique (checksum: XakcIjGK3ozqY7O5U6rM4Q==)
   (0.1ms)  begin transaction
  ActiveStorage::Blob Create (1.1ms)  INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "metadata", "byte_size", "checksum", "created_at") VALUES (?, ?, ?, ?, ?, ?, ?)  [["key", "totallyunique"], ["filename", "first"], ["content_type", "application/octet-stream"], ["metadata", "{\"identified\":true}"], ["byte_size", 22], ["checksum", "XakcIjGK3ozqY7O5U6rM4Q=="], ["created_at", "2018-12-27 01:43:21.937627"]]
   (0.8ms)  commit transaction
```

Now attempt uploading a second IO

```ruby
second_io = StringIO.new("surprising overwrite!")
ActiveStorage::Blob.create_after_upload!(io: second_io, filename: "second", content_type: nil, metadata: nil)
```

which of course does fail, but only after the upload has completed

```
  Disk Storage (1.2ms) Uploaded file to key: totallyunique (checksum: yahylFonzap1Lv/ah3Ubdg==)
   (0.1ms)  begin transaction
  ActiveStorage::Blob Create (0.4ms)  INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "metadata", "byte_size", "checksum", "created_at") VALUES (?, ?, ?, ?, ?, ?, ?)  [["key", "totallyunique"], ["filename", "second"], ["content_type", "application/octet-stream"], ["metadata", "{\"identified\":true}"], ["byte_size", 21], ["checksum", "yahylFonzap1Lv/ah3Ubdg=="], ["created_at", "2018-12-27 01:44:51.045319"]]
   (0.0ms)  rollback transaction
Traceback (most recent call last):
        1: from (irb):13
ActiveRecord::RecordNotUnique (SQLite3::ConstraintException: UNIQUE constraint failed: active_storage_blobs.key: INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "metadata", "byte_size", "checksum", "created_at") VALUES (?, ?, ?, ?, ?, ?, ?))

```
and the original data has been lost

```
irb(main):014:0> File.read('<storage location>/to/ta/totallyunique')
=> "surprising overwrite!"
```

This can be especially nasty in combination with #34804 

### Expected behavior

ActiveStorage does something to prevent data overwrite when there is going to be a key collision. Either key reservation, or a check if the key is already being used that would force the key to be regenerated. Maybe something like a database-controlled atomic sequence should be used instead.

### Actual behavior

ActiveStorage overwrites the data of the upload before failing in a database constraint (regardless of service)

### System configuration

**Rails version**: activestorage=(5.2.2)

**Ruby version**: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]`

For me this warrants actually overwriting the `key` method in Blob with something that uses an atomic monotonic counter to generate keys, regardless whether they do get consumed or not.

### PR DESCRIPTION
**Pull request by julik**
### Summary

Closes #34805 

This PR will be contentious as there is an assumption made that it is possible, with a sufficiently random `key`, to permit the user to upload to the storage without reserving that key first. I believe the assumption is flawed because it makes the following situation possible:

* User A uploads a PDF of an important legal document (I'm exaggerating, on purpose)
* 4 months pass
* User B edits his comment on something totally unrelated and ponders adding a NSFW picture as an attachment to that comment. Because the user A is unlucky, the picture gets issued the same `key` as the legal document user A has already uploaded.
* The text editing control user B is using preemptively uploads the file under the `key` so that saving the comment is fast once the user is done writing. It does receive an error from the ActiveStorage endpoint and tries again. The legal document of the user A is at this point overwritten, and at this stage has been irrecoverably lost. The legal document has been replaced with the NSFW picture.

So I believe, however unlikely (the value spread for the `key` is very very large indeed) this introduces a possibility of a very sneaky data corruption, which would overwrite data uploaded by the users of the application. This is exacerbated by the fact that when you generate a pre-signed URL to an external service the service will most likely not verify the checksum for you. This means that a person meaning to download the legal document of User A is going to receive the NSFW picture from User B, without any warning.

I know the solution proposed here was probably not the one desired (not holding a DB transaction during upload is a valid requirement) but I believe having risks of silent user data clobbering is worse. 

There are a few ways to solve this problem:

* Only use storage backends which support "upload here or error if already taken". Off the top of my head only Redis supports this with SETNX, and then again you need to hold the entire set in memory in Redis for this to work. S3 will happily overwrite on any PUT (it will also overwrite your checksum value)
* Pre-reserve keys using a deterministic sequence number obtained from the database. I tried this and it causes deadlocks on MySQL and is hard to do if your database does not have native cheap sequences. PostgreSQL does but most other databases do not.
* And the last option: insert the row into the database before allowing the upload to take place, so that the database observes the constraint and refuses if the key is taken.

I think part of the reason for this is the method naming for `generate_unique_secret_token`, because despite it is name it offers no actual guarantees of uniqueness - and it does recommend adding a database constraint on top. The problem here is rather we deliberately allow a state change on an external service which cannot be rolled back before allowing this index to fire.

I've left the test failing for now because they make assumptions about how `build...` is supposed to work in this case. I do believe that these assumptions should be changed to prevent user data corruption, but would like to poll first.

If the concern is holding a DB transaction open maybe the scope of this transaction should somehow be reduced to key reservation only, I just don't know if ActiveRecord has this facility or not.

_Empirical evidence_ - I work for a company that does lots of file uploads, and I did see wrong things happen, more than once. Some of those wrong things did involve probabilities and preemptive key generation.

### CODE REVIEW

File: activestorage/app/models/active_storage/blob.rb [hunk 1]
```diff
@@ -53,19 +53,21 @@ def find_signed(id)
     # When providing a content type, pass <tt>identify: false</tt> to bypass automatic content type inference.
     def build_after_upload(io:, filename:, content_type: nil, metadata: nil, identify: true)
       new(filename: filename, content_type: content_type, metadata: metadata).tap do |blob|
+        blob.reserve_key!
```
Comment (lsylvester) [inline activestorage/app/models/active_storage/blob.rb]: I think that this makes the documentation for this method ("returns new, unsaved blob instance") incorrect and the method name misleading. 

I think that if the possible key collision is an issue, the `build_*` methods should be removed - and we should instead corresponding `create_*` methods.

I If we are creating before uploading I don't think that the `reserve_key!` method would still be required.

Comment (julik) [reply activestorage/app/models/active_storage/blob.rb]: > I think that if the possible key collision is an issue, the build_* methods should be removed - and we should instead corresponding create_* methods.

I would vote for that too. Don't know how much "public-ness" is attached to those build methods though, so not my call to make. "Create before upload always" is the proposed solution anyway.

Comment (georgeclaghorn) [reply activestorage/app/models/active_storage/blob.rb]: I think I’m okay with removing `build_after_upload`. `build_after_unfurling` will likely need to stay to preserve desirable behaviors of the attaching API, but it’s strictly internal and used safely.

**Comment by julik** [comment]
@georgeclaghorn I'll try to decipher

> This method doesn’t need to reserve the resulting blob’s key. In fact, we don’t want it to do so: it’s used to build a blob that is saved with an attached record and uploaded only after the create transaction commits. If that transaction rolls back, the unused blob should not be left behind in the DB.

Do I understand correctly that in case of `build_after_unfurling` the actual upload takes place in an `after_commit`?

> I think I’m okay with removing build_after_upload. build_after_unfurling will likely need to stay to preserve desirable behaviors of the attaching API, but it’s strictly internal and used safely.

I don't see it used from anywhere but the Blob class itself, so that's a 👍  from me if agreement has been reached.

**Comment by georgeclaghorn** [comment]
> Do I understand correctly that in case of build_after_unfurling the actual upload takes place in an `after_commit`?

That’s [correct](https://github.com/rails/rails/blob/260b273106168ba7a122c76c79a3b7f4a3209559/activestorage/lib/active_storage/attached/model.rb#L56).

**Comment by julik** [comment]
Ok, so 🔪  `build_after_upload` is what we go for?

**Comment by georgeclaghorn** [comment]
:+1:

**Comment by julik** [comment]
Will do. What can we do for those still on Rails 5 in this situation?

File: activestorage/app/models/active_storage/blob.rb [hunk 2]
```diff
@@ -49,26 +50,22 @@ def find_signed(id)
...
-    def create_after_upload!(io:, filename:, content_type: nil, metadata: nil, identify: true)
-      build_after_upload(io: io, filename: filename, content_type: content_type, metadata: metadata, identify: identify).tap(&:save!)
+    # Creates a new blob instance and then uploads the contents of
+    # the given <tt>io</tt> to the service. The blob instance is going to
+    # be saved before the upload begins to prevent the upload clobbering another due to key collisions.
+    # When providing a content type, pass <tt>identify: false</tt> to bypass
+    # automatic content type inference.
+    def create_and_upload!(io:, filename:, content_type: nil, metadata: nil, identify: true)
+      build_after_unfurling(io: io, filename: filename, content_type: content_type, metadata: metadata, identify: identify).tap do |blob|
+        blob.save! # To ensure the uniqueness constraint in the database fires before uploading
```
Comment (georgeclaghorn) [inline activestorage/app/models/active_storage/blob.rb]: I’d like to see an internal `create_after_unfurling` method do this part:

```ruby
def create_after_unfurling!(io:, filename:, content_type: nil, metadata: nil, identify: true) #:nodoc:
  build_after_unfurling(io: io, filename: filename, content_type: content_type, metadata: metadata, identify: identify).tap(&:save!)
end

# ...
def create_and_upload!(io:, filename:, content_type: nil, metadata: nil, identify: true)
  create_after_unfurling!(io: io, filename: filename, content_type: content_type, metadata: metadata, identify: identify).tap do |blob|
    blob.upload_without_unfurling(io)
  end
end
```

File: activestorage/app/models/active_storage/blob.rb [hunk 3]
```diff
@@ -49,26 +50,22 @@ def find_signed(id)
...
+        blob.upload(io, identify: identify)
```
Comment (georgeclaghorn) [inline activestorage/app/models/active_storage/blob.rb]: Note that we want to `upload_without_unfurling`, since we’ve already computed the blob’s checksum and extracted its content type in `build_after_unfurling`.

File: activestorage/app/models/active_storage/blob.rb [hunk 4]
```diff
@@ -156,7 +153,7 @@ def service_headers_for_direct_upload
   # you specify a +content_type+ and pass +identify+ as false.
   #
   # Normally, you do not have to call this method directly at all. Use the factory class methods of +build_after_upload+
```
Comment (georgeclaghorn) [inline activestorage/app/models/active_storage/blob.rb]: `build_after_upload` doesn’t exist anymore.

**Review by georgeclaghorn — CHANGES_REQUESTED** [review]

**Comment by julik** [comment]
@georgeclaghorn if there is a `RecordNotUnique` should recovery be attempted? Or do we consider it a "once in a lifetime" event?

**Comment by georgeclaghorn** [comment]
I’m fine with not recovering.

**Comment by julik** [comment]
Any chance of this making 6.0?

**Comment by julik** [comment]
@georgeclaghorn Any chance of getting this to move forward?

**Comment by cpsoinos** [comment]
Any word on when this will be merged? It's been causing a lot of problems in my app.

**Comment by julik** [comment]
@cpsoinos on Rails 5 I use this patch for now but indeed would be great if this could get merged (and hopefully even backported). https://gist.github.com/julik/4195b74774dc21dcd2cbd694a25102ce

**Comment by cpsoinos** [comment]
@julik thanks for the gist! After seeing this PR I implemented a patch myself that essentially runs the logic you have in `create_and_upload!`, though that's in the business-logic layer of my app. Currently monitoring how it does.

**Comment by julik** [comment]
@georgeclaghorn is there anything I can do?

**Comment by julik** [comment]
@georgeclaghorn Would you like me to rebase and update?

**Comment by georgeclaghorn** [comment]
Hi Julik,

Sorry for the delay here. Please do rebase.

Last thing: on revisiting this, I don’t think we can remove `.build_after_upload` and `.create_after_upload` without deprecation. Can you restore them and add deprecation warnings? Then we can remove them in 6.2.

**Comment by julik** [comment]
Glad we can back to 🔧  on this.

Can I make `create_after_upload` an alias for `create_and_upload` + deprecation (which it factually is)?

**Comment by georgeclaghorn** [comment]
I would personally prefer to restore them with their original behavior, but I don’t feel strongly either way.

**Comment by julik** [comment]
I opted for aliasing because the original behaviour of `create_after_upload` leads to the original issue (overwriting), while I believe just having it do something sensible instead and not break API consumers should be good enough ;-)

**Review by georgeclaghorn — APPROVED** [review]
Can you please add a changelog entry?

**Comment by georgeclaghorn** [comment]
Backported to 6-0-stable (without the deprecations) in 7e23c05.
