### PR TITLE
Fix ActionText::Attachable#as_json

### LINKED ISSUE #45949: ActionText::Attachable#as_json override is breaking ActiveStorage::Blob#as_json when blob is not persisted
### Steps to reproduce
from rails console:
```ruby
ActiveStorage::Blob.build_after_unfurling(io: StringIO.new('asd'), filename: 'asd.txt').as_json
```

[Reproduction script](https://gist.github.com/balbesina/30fbdafbfee4b71b06209d9e950f4128)

### Expected behavior
ActiveStorage::Blob#as_json returns a Hash

### Actual behavior
ActiveStorage::Blob#as_json raises exception
```
/Users/dhh/.rvm/gems/ruby-3.1.2/gems/globalid-1.0.0/lib/global_id/uri/gid.rb:167:in `validate_model_id': 
Unable to create a Global ID for ActiveStorage::Blob without a model id. (URI::GID::MissingModelIdError)
```

### System configuration
**Rails version**: Rails 7.0.3.1
**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

### PR DESCRIPTION
**Pull request by alexandreruban**
Closes #45949 

Before this commit, using ActionText and calling `#as_json` on a non-persisted `ActiveStorage::Blob` raised an error.

This is because `ActionText::Attachable` is included in `ActiveStorage::Blob` and overrides the `#as_json` method to expose a global signed id. However, a global signed id can only be generated on a persisted instance.

This commit fixes the issue by making sure the blob is persisted before exposing the global signed id.

### CODE REVIEW

File: actiontext/lib/action_text/attachable.rb [hunk 1]
```diff
@@ -64,7 +64,9 @@ def previewable_attachable?
     end
 
     def as_json(*)
-      super.merge(attachable_sgid: attachable_sgid)
+      super.tap do |json|
+        json.merge(attachable_sgid: attachable_sgid) if persisted?
+      end
```
Comment (skipkayhil) [inline actiontext/lib/action_text/attachable.rb:69]: When I tested this locally, it looked like `as_json` includes `id: nil` when the record is not persisted. Instead of not including `attachable_sgid` at all, should it just be set to `nil`?

Comment (alexandreruban) [reply actiontext/lib/action_text/attachable.rb]: @skipkayhil thanks a lot for your comment.
I just made the change so that we include `attachable_sgid` and set it to `nil`.

File: actiontext/test/unit/attachable_test.rb [hunk 2]
```diff
@@ -0,0 +1,17 @@
+# frozen_string_literal: true
+
+require "test_helper"
+
+class ActionText::AttachableTest < ActiveSupport::TestCase
+  test "as_json is a hash when the attachable is persisted" do
+    attachable = ActiveStorage::Blob.create_after_unfurling!(io: StringIO.new("test"), filename: "test.txt")
+
+    assert_kind_of Hash, attachable.as_json
```
Comment (rafaelfranca) [inline actiontext/test/unit/attachable_test.rb:9]: Why we don't assert that the hash should be?

Comment (alexandreruban) [reply actiontext/test/unit/attachable_test.rb]: @rafaelfranca thanks for your comment. 
I asserted what the hash should be, squashed my commits and rebased on main.
