### PR TITLE
Fix retrieving default value for text column for MariaDB

### LINKED ISSUE #38218: Migration on Mariadb: text column default value reads back with extra quotes
### Steps to reproduce
With MariaDB / possibly also MySQL, text column with a default value is not recorded properly into schema.rb. Instead of empty string, it reads back as a pair of quotes.

```
create_table do |t|
      t.text :content, null: false, default: ''
end
```

### Expected behavior

In schema.rb

```
t.text "content", default: "", null: false
```

### Actual behavior

```
t.text "content", default: "''", null: false
```

### System configuration
**Rails version**: 5.2.4.1

**Ruby version**: 2.5.5p157 (2019-03-15 revision 67260)

MariaDB: 10.3.18-MariaDB-0+deb10u1

---

I'm not even sure if this has been reported before, since it seems to be easy to hit. The table is created properly, but somehow read back is incorrect.

```
CREATE TABLE ... ( `content` text DEFAULT '' NOT NULL )

+-------------+---------------+------+-----+---------+----------------+ 
| Field       | Type          | Null | Key | Default | Extra          |
+-------------+---------------+------+-----+---------+----------------+        
| content     | text          | NO   |     | ''      |                |
+-------------+---------------+------+-----+---------+----------------+
```

And inserting a record indeed gives me empty string, instead of a pair of quotes.

I found this issue because when I create a model I get a pair of quotes in the content field by default.

I only tested against Debian MariaDB. Possibly affecting MySQL also.

### LINKED ISSUE #41240: Unable to set default JSON value on a text column with MariaDB
### Steps to reproduce

```rb
require "active_record"

ActiveRecord::Base.establish_connection(
  adapter: "mysql2",
  database: "...",
  username: "...",
  password: "...",
)

class MyRecord < ActiveRecord::Base
  serialize :col, JSON
end

ActiveRecord::Schema.define do
  create_table :my_records, force: true do |t|
    t.text :col, default: "[]"
  end
end

record = MyRecord.create
```

### Expected behavior

I expect that `my_records.col` column default value will be set to `'[]'` (empty string in SQL).

### Actual behavior

The `my_records.col` column default value gets set to the SQL equivalent of `'\'[]\''` (`"'[]'"` in Ruby), which fails to get JSON-parsed when the record is saved. The error with reversed stack trace (sorry):

```
        39: from tmp/ar.rb:20:in `<main>'
        38: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/persistence.rb:38:in `create'
        37: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/suppressor.rb:44:in `save'
        36: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:315:in `save'
        35: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
        34: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:212:in `transaction'
        33: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
        32: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
        31: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
        30: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
        29: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'
        28: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
        27: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/transactions.rb:315:in `block in save'
        26: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/validations.rb:47:in `save'
        25: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/persistence.rb:470:in `save'
        24: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/timestamp.rb:129:in `create_or_update'
        23: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/callbacks.rb:328:in `create_or_update'
        22: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
        21: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:101:in `run_callbacks'
        20: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/callbacks.rb:328:in `block in create_or_update'
        19: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/persistence.rb:906:in `create_or_update'
        18: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/timestamp.rb:111:in `_create_record'
        17: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/callbacks.rb:332:in `_create_record'
        16: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
        15: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:101:in `run_callbacks'
        14: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/callbacks.rb:332:in `block in _create_record'
        13: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/attribute_methods/dirty.rb:212:in `_create_record'
        12: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/dirty.rb:146:in `changes_applied'
        11: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/dirty.rb:249:in `forget_attribute_assignments'
        10: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/attribute_set.rb:88:in `map'
         9: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/attribute_set.rb:88:in `transform_values'
         8: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/attribute.rb:67:in `forgetting_assignment'
         7: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/attribute.rb:55:in `value_for_database'
         6: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/attribute.rb:42:in `value'
         5: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.2.2/lib/active_model/attribute.rb:164:in `type_cast'
         4: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/type/serialized.rb:22:in `deserialize'
         3: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/coders/json.rb:11:in `load'
         2: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/json/decoding.rb:23:in `decode'
         1: from /Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Users/jankomarohnic/.rbenv/versions/2.6.5/lib/ruby/2.6.0/json/common.rb:156:in `parse': 767: unexpected token at ''[]'' (JSON::ParserError)
```

I've tried all the combinations:

```rb
t.text :col, default: [] # ~> TypeError: can't quote Array
t.json :col, default: [] # ~> JSON::ParserError: 767: unexpected token at ''[]''
t.json :col, default: -> { "'[]'" } # ~> JSON::ParserError: 767: unexpected token at ''[]''
t.json :col, default: -> { "[]" } # ~> Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '[])' at line 1
``` 

It appears that Active Record is doing some conversion work here that I don't want it to do, even in the block version of `:default` value, where I thought it's supposed to interpret my string as raw SQL.

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.6.5

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #38218
Fixes #41240

All adapters support `text` columns with defaults, except MySQL (but MariaDB >= 10.2.1 [supports](https://mariadb.com/kb/en/create-table/#default-column-option)).

### CODE REVIEW

File: activerecord/test/cases/defaults_test.rb [hunk 1]
```diff
@@ -83,6 +83,28 @@ def test_default_strings_containing_single_quotes
...
 end
 
+if supports_text_column_with_default?
+  class DefaultTextTest < ActiveRecord::TestCase
+    class DefaultText < ActiveRecord::Base; end
+
+    setup do
+      @connection = ActiveRecord::Base.connection
+      @connection.create_table :default_texts do |t|
+        t.text :text_col, default: "Smith"
```
Comment (kamipo) [inline activerecord/test/cases/defaults_test.rb:93]: Can you also add a test for quotes like here?

https://github.com/rails/rails/blob/9e9e11f05963ff5312a2fa1fa8bae5a6aa0e6dbe/activerecord/test/cases/defaults_test.rb#L67-L68

https://github.com/rails/rails/blob/9e9e11f05963ff5312a2fa1fa8bae5a6aa0e6dbe/activerecord/test/cases/defaults_test.rb#L77-L79

Comment (fatkodima) [reply activerecord/test/cases/defaults_test.rb:93]: Added

**Comment by intrip** [comment]
@fatkodima @kamipo  I didn't see your PR and accidentally created a similar one https://github.com/rails/rails/pull/41726 🤦 

I'll close my PR buy if you want you can port the extra test that I've added for the SchemaDumper: https://github.com/rails/rails/blob/f6453e2164ae9b368afbfc24174250b2745dbdea/activerecord/test/cases/schema_dumper_test.rb#L622-L626

**Comment by janko** [comment]
Would love to see this one merged 🤘. Currently we can't set default values for serialized JSON columns on MariaDB.

**Comment by lfalcao** [comment]
👀

**Comment by intrip** [comment]
@fatkodima could you please fix the conflicts? Also please check https://github.com/rails/rails/pull/40822#issuecomment-804152118 incase you'd like to pull in the extra tests.

**Comment by fatkodima** [comment]
Rebased and pulled the test case.
Wow, got a nice build number on Buildkite - https://buildkite.com/rails/rails/builds/77777 😄

File: activerecord/lib/active_record/connection_adapters/mysql/schema_statements.rb [hunk 2]
```diff
@@ -167,6 +167,9 @@ def new_column_from_field(table_name, field)
             elsif type_metadata.extra == "DEFAULT_GENERATED"
               default = +"(#{default})" unless default.start_with?("(")
               default, default_function = nil, default
+            elsif type_metadata.type == :text && default
+              # strip and unescape quotes
+              default = default[1...-1].gsub("\\'", "'")
```
Comment (zzak) [inline activerecord/lib/active_record/connection_adapters/mysql/schema_statements.rb:172]: Is `gsub` the right operation here? I wonder if this might be costly 🤔

Comment (fatkodima) [reply activerecord/lib/active_record/connection_adapters/mysql/schema_statements.rb:172]: Did you mean replace it with `gsub!`? `text` columns with default are not popular enough, I think, and default values in the db most of the time have small values in them.

Comment (zzak) [reply activerecord/lib/active_record/connection_adapters/mysql/schema_statements.rb:172]: @fatkodima Sorry I was misconnecting the dots here. This code probably isn't being called during a request so maybe we don't have to worry about the performance of `gsub`. Please correct me if I'm wrong! :bow:

**Review by lfalcao — APPROVED** [review]

File: activerecord/lib/active_record/connection_adapters/mysql/schema_statements.rb (hunk 2 above)
Comment (fatkodima) [reply activerecord/lib/active_record/connection_adapters/mysql/schema_statements.rb:172]: It is used in https://github.com/rails/rails/blob/8a7a9d0a0b27e113e6d0a6087299c4bd41d29738/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L114-L119
which runs once for each table, when columns list for the first time is needed, and then cached in `SchemaCache` - 
https://github.com/rails/rails/blob/8a7a9d0a0b27e113e6d0a6087299c4bd41d29738/activerecord/lib/active_record/connection_adapters/schema_cache.rb#L110-L114

**Review by zzak — APPROVED** [review]

**Comment by kmooventhan98** [comment]
Why Mysql2 not supporting this?
```ruby
Mysql2::Error: BLOB, TEXT, GEOMETRY or JSON column 'my_field_name' can't have a default value
```

**Comment by byroot** [comment]
This error is returned by the MySQL server. You won't get an answer on this thread.
