### PR TITLE
[Fix #52304] Avoid computing `klass` if reflection is a `belongs_to` in `ActiveRecord::AutosaveAssociation#inverse_belongs_to_association_for`

### LINKED ISSUE #52304: "Polymorphic associations do not support computing the class." error when creating a record with a `has_one :through`
### Steps to reproduce

This is a regression between `7-2-stable` and `main`.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # Gem passes:
  # gem "rails", "7.1.3.4"

  # 7.2 passes:
  # gem "rails", github: "rails/rails", branch: "7-2-stable"

  # Edge fails:
  gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3", "~> 1.4"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :sponsors, force: true do |t|
  end

  create_table :members, force: true do |t|
  end

  create_table :certificates, force: true do |t|
    t.integer :member_id
    t.integer :certificatable_id
    t.string :certificatable_type
  end
end

class Sponsor < ActiveRecord::Base
  has_one :certificate, as: :certificatable, validate: true
  has_one :member, through: :certificate
end

class Member < ActiveRecord::Base
end

class Certificate < ActiveRecord::Base
  belongs_to :member
  belongs_to :certificatable, polymorphic: true, validate: true, inverse_of: :certificate
end

class BugTest < Minitest::Test
  def test_association_stuff
    Sponsor.create!(member: Member.create!)
  end
end

```

### Expected behavior

Test should pass.

### Actual behavior

```
  1) Error:
BugTest#test_association_stuff:
ArgumentError: Polymorphic associations do not support computing the class.
    rails-69d904e60f78/activerecord/lib/active_record/reflection.rb:500:in `compute_class'
    rails-69d904e60f78/activerecord/lib/active_record/reflection.rb:439:in `_klass'
    rails-69d904e60f78/activerecord/lib/active_record/reflection.rb:431:in `klass'
    rails-69d904e60f78/activerecord/lib/active_record/reflection.rb:261:in `inverse_of'
    rails-69d904e60f78/activerecord/lib/active_record/autosave_association.rb:470:in `inverse_belongs_to_association_for'
    rails-69d904e60f78/activerecord/lib/active_record/autosave_association.rb:322:in `validate_single_association'
    rails-69d904e60f78/activerecord/lib/active_record/autosave_association.rb:228:in `block in define_autosave_validation_callbacks'
```

### System configuration
**Rails version**: `main`

**Ruby version**: 3.2

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

Fixes https://github.com/rails/rails/issues/52304
Ref: https://github.com/rails/rails/pull/49847

### Detail

Adds a condition in `ActiveRecord::AutosaveAssociation#inverse_belongs_to_association_for` to return early if the current reflection is a `belongs_to`, as the inverse can't possibly be a `belongs_to` as well. This then ensures that polymorphic `belongs_to` reflections don't have their class computed which raises an error like the one in the linked issue (see https://github.com/rails/rails/pull/31895 for why this happens).

An alternative fix, specifically for the linked issue is to simply return if `reflection.polymorphic?`, but imo what I've currently got is better since it handles non-polymorphic cases as well, and will short circuit in all cases where the inverse logic is not applicable.

**Edit:** Some more context in https://github.com/rails/rails/pull/52305#issuecomment-2222227506

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by ghiculescu** [comment]
I probably should have made a PR, but the tests in https://github.com/rails/rails/issues/52304 are copy-pasted from replication tests I wrote in https://github.com/rails/rails/blob/main/activerecord/test/cases/associations/has_one_through_associations_test.rb to confirm the issue.

So you'd need to add a `Certificate` model and a `Sponsor` model.

File: activerecord/test/cases/autosave_association_test.rb [hunk 1]
```diff
@@ -314,8 +314,18 @@ def test_callbacks_on_child_when_parent_autosaves_child
     assert_equal 1, eye.iris.after_save_callbacks_counter
   end
 
+  def test_callbacks_on_child_when_parent_autosaves_polymorphic_child_with_inverse_of
+    drink_designer = DrinkDesigner.create!(chef: Chef.new)
```
Comment (joshuay03) [inline activerecord/test/cases/autosave_association_test.rb:318]: Without patch:
Screenshot 2024-07-11 at 12 49 24 pm

File: activerecord/test/cases/autosave_association_test.rb [hunk 2]
```diff
@@ -324,6 +334,16 @@ def test_callbacks_on_child_when_child_autosaves_parent
     assert_equal 1, iris.after_save_callbacks_counter
   end
 
+  def test_callbacks_on_child_when_polymorphic_child_with_inverse_of_autosaves_parent
+    chef = Chef.create!(employable: DrinkDesigner.new)
```
Comment (joshuay03) [inline activerecord/test/cases/autosave_association_test.rb:338]: Without patch:
Screenshot 2024-07-11 at 12 49 40 pm

**Comment by joshuay03** [comment]
> I probably should have made a PR, but the tests in #52304 are copy-pasted from replication tests I wrote in [`main`/activerecord/test/cases/associations/has_one_through_associations_test.rb](https://github.com/rails/rails/blob/main/activerecord/test/cases/associations/has_one_through_associations_test.rb?rgh-link-date=2024-07-11T06%3A59%3A05Z) to confirm the issue.
> 
> So you'd need to add a `Certificate` model and a `Sponsor` model.

All good, I've added some failing tests similar to the ones I added in https://github.com/rails/rails/pull/49847.

It turns out this is only an issue if the validate association callbacks are run (either through `validate: true` like you did or autosave which I'm doing with `accepts_nested_attributes_for`) **AND** `:inverse_of` is set on the polymorphic `belongs_to` association.

Without the `inverse_of` the class seems to compute just fine. Might be something to look into separately but I'm gonna consider it out of scope for this since the condition I added is a good change anyway.

File: activerecord/test/cases/autosave_association_test.rb [hunk 3]
```diff
@@ -314,8 +314,18 @@ def test_callbacks_on_child_when_parent_autosaves_child
     assert_equal 1, eye.iris.after_save_callbacks_counter
   end
 
+  def test_callbacks_on_child_when_parent_autosaves_polymorphic_child_with_inverse_of
+    drink_designer = DrinkDesigner.create!(chef: ChefWithPolymorphicInverseOf.new)
```
Comment (joshuay03) [inline activerecord/test/cases/autosave_association_test.rb:318]: Without patch:
Screenshot 2024-07-11 at 1 05 04 pm

File: activerecord/test/cases/autosave_association_test.rb [hunk 4]
```diff
@@ -324,6 +334,16 @@ def test_callbacks_on_child_when_child_autosaves_parent
     assert_equal 1, iris.after_save_callbacks_counter
   end
 
+  def test_callbacks_on_child_when_polymorphic_child_with_inverse_of_autosaves_parent
+    chef = ChefWithPolymorphicInverseOf.create!(employable: DrinkDesigner.new)
```
Comment (joshuay03) [inline activerecord/test/cases/autosave_association_test.rb:338]: Without patch:
Screenshot 2024-07-11 at 1 06 05 pm
