### PR TITLE
[Fix #49999] properly reference from Arel::Attribute args

### LINKED ISSUE #49999: Expect `ActiveRecord::Relation#order` to take `Arel::Attributes::Attribute` and properly `reference` joined table
### Steps to reproduce

```ruby
Topic.includes(:posts).order(Post.arel_table[:created_at])
```

### Expected behavior

```ruby
Topic.includes(:posts).order(Post.arel_table[:created_at])
# SELECT "topics"."id" AS t0_r0..."posts"."id" AS t1_r0...FROM "topics" LEFT OUTER JOIN "posts" ON "posts"."topic_id" = "topics"."id" ORDER BY "posts"."created_at"
```

### Actual behavior

```ruby
Topic.includes(:posts).order(Post.arel_table[:created_at])
# SELECT "topics".* FROM "topics" ORDER BY "posts"."created_at"
# ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "posts"
```

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by mylesboone**
### Motivation / Background

Fixes #49999 

### Detail

ActiveRecord::Relation#order now properly references Arel::Attribute arguments

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by tenderlove** [comment]
Seems like CI fails. Do you mind taking a look? Thanks!

File: activerecord/lib/active_record/relation/query_methods.rb [hunk 1]
```diff
@@ -1998,6 +1998,12 @@ def column_references(order_args)
             arg
           when Hash
             arg.keys.select { |e| e.is_a?(String) || e.is_a?(Symbol) }
+          when Arel::Attribute
+            "#{arg.relation.name}.#{arg.name}"
+          when Arel::Nodes::Ordering
+            if arg.relation.is_a?(Arel::Attribute)
```
Comment (matthewd) [inline activerecord/lib/active_record/relation/query_methods.rb:2004]: This feels like we're smashing through the Arel tree structure rather than treating it _as_ a tree... plus the stringifying just to then parse and de-string :confused:

Comment (mylesboone) [reply activerecord/lib/active_record/relation/query_methods.rb]: @matthewd I have refactored to no longer stringify/parse and instead handle each case directly.

**Comment by rafaelfranca** [comment]
Thank you for the pull request. I tried to apply to 7-1-stable but it doesn't apply. Can you open a new PR against that branch?

**Comment by mylesboone** [comment]
@rafaelfranca #52128 submitted against 7-1-stable
