### PR TITLE
Fix syntax error in user.rb

### LINKED ISSUE #52894: Syntax error in user.rb when using lambdas
Recent [changed on user.rb ](https://github.com/rails/rails/commit/9f8a3db328db9386e47a84138c49c410d36b7e78) introduced a syntax error with the usage of lambdas.

### Steps to reproduce

Compile the file with:

```
ruby -c railties/lib/rails/generators/rails/authentication/templates/models/user.rb 
```

### Expected behavior
```
Syntax OK
```

### Actual behavior
```
ruby: railties/lib/rails/generators/rails/authentication/templates/models/user.rb:5: syntax error, unexpected '|' (SyntaxError)
...es :email_address, with: -> { |e| e.strip.downcase }
...  
```

### System configuration
**Rails version**:

**Ruby version**:
Visible with versions 2.6 and 3.5

### Solution
Use the correct syntax for the lambda:
```
  normalizes :email_address, with: lambda { |e| e.strip.downcase }
```
or
```
  normalizes :email_address, with: -> (e) { e.strip.downcase }
```

### PR DESCRIPTION
**Pull request by andrewn617**
### Motivation / Background

Fixes https://github.com/rails/rails/issues/52894

### Detail

Fix a syntax error introduced in https://github.com/rails/rails/commit/9f8a3db328db9386e47a84138c49c410d36b7e78

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: railties/lib/rails/generators/rails/authentication/templates/models/user.rb [hunk 1]
```diff
@@ -2,5 +2,5 @@ class User < ApplicationRecord
   has_secure_password
   has_many :sessions, dependent: :destroy
 
-  normalizes :email_address, with: -> { |e| e.strip.downcase }
+  normalizes :email_address, with: -> (e) { e.strip.downcase }
```
Comment (kamipo) [inline railties/lib/rails/generators/rails/authentication/templates/models/user.rb:5]: Can you omit the parentheses?
We usually don't use parentheses for a single argument.

```
% git grep -n ' with: -> '
actionpack/lib/action_controller/metal/rate_limiting.rb:40:      #         by: -> { request.domain }, with: -> { redirect_to busy_controller_url, alert: "Too many signups on domain!" }, only: :new
actionpack/lib/action_controller/metal/rate_limiting.rb:47:      def rate_limit(to:, within:, by: -> { request.remote_ip }, with: -> { head :too_many_requests }, store: cache_store, **options)
actionpack/test/controller/rate_limiting_test.rb:13:  rate_limit to: 2, within: 2.seconds, by: -> { params[:rate_limit_key] }, with: -> { head :forbidden }, only: :limited_with
activerecord/lib/active_record/normalization.rb:18:    #     normalizes :email, with: -> email { email.strip.downcase }
activerecord/lib/active_record/normalization.rb:70:      #     normalizes :email, with: -> email { email.strip.downcase }
activerecord/lib/active_record/normalization.rb:71:      #     normalizes :phone, with: -> phone { phone.delete("^0-9").delete_prefix("1") }
activerecord/lib/active_record/normalization.rb:101:      #     normalizes :email, with: -> email { email.strip.downcase }
activerecord/test/cases/normalized_attribute_test.rb:9:    normalizes :name, with: -> name { name.titlecase }
activerecord/test/cases/normalized_attribute_test.rb:10:    normalizes :manufactured_at, with: -> time { time.noon }
activerecord/test/cases/normalized_attribute_test.rb:70:      normalizes :name, with: -> name { name&.titlecase || "Untitled" }, apply_to_nil: true
activerecord/test/cases/normalized_attribute_test.rb:88:      normalizes :name, with: -> name { name.reverse }
activerecord/test/cases/normalized_attribute_test.rb:97:      normalizes :name, with: -> name { name.succ }
guides/source/7_1_release_notes.md:91:  normalizes :email, with: -> email { email.strip.downcase }
guides/source/7_1_release_notes.md:92:  normalizes :phone, with: -> phone { phone.delete("^0-9").delete_prefix("1") }
railties/lib/rails/generators/rails/authentication/templates/controllers/sessions_controller.rb:3:  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }
railties/lib/rails/generators/rails/authentication/templates/models/user.rb:5:  normalizes :email_address, with: -> { |e| e.strip.downcase }
```

Comment (andrewn617) [reply railties/lib/rails/generators/rails/authentication/templates/models/user.rb]: 👍
