### PR TITLE
Fix destroy of has_one with multiple belongs_to

### LINKED ISSUE #50948: Destroying bi-directional has_one through association only works from one end
### Summary

Given a `has_one :through` association with `dependent: :destroy`, destroying the parent destroys the through record and the far end.  However if the association is bi-directional, destroying only works from one end – and the end which succeeds depends on the order of `belongs_to` declarations in the join model.  I believe it should work from both ends.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :lefts, force: true do |t|
  end

  create_table :rights, force: true do |t|
  end

  create_table :middles, force: true do |t|
    t.references :left, foreign_key: true
    t.references :right, foreign_key: true
  end
end

class Left < ActiveRecord::Base
  has_one :middle, dependent: :destroy
  has_one :right, through: :middle
end

class Middle < ActiveRecord::Base
  belongs_to :left, dependent: :destroy
  belongs_to :right, dependent: :destroy
end

class Right < ActiveRecord::Base
  has_one :middle, dependent: :destroy
  has_one :left, through: :middle
end

class BugTest < Minitest::Test
  def test_destroying_left_destroys_right
    left = Left.create!
    right = Right.create!
    middle = Middle.create! left: left, right: right

    left.destroy
    assert right.destroyed?
  end

  def test_destroying_right_destroys_left
    left = Left.create!
    right = Right.create!
    middle = Middle.create! left: left, right: right

    right.destroy
    assert left.destroyed?
  end
end
```

### Expected behavior

I expect:

- `left.destroy` to also destroy its `middle` and its `right`
- `right.destroy` to also destroy its `middle` and its `left`

### Actual behavior

- `right.destroy` destroys its `middle` and its `left`
-  `left.destroy` destroys its `middle` but does not destroy its `right`

However if I reverse the order of `Middle`'s `belongs_to` declarations, `right.destroy` stops working and `left.destroy` starts working.

### Patch

This patch fixes the behaviour and does not break any existing tests (via `bundle exec rake test:sqlite3`):

```diff
diff --git i/activerecord/lib/active_record/callbacks.rb w/activerecord/lib/active_record/callbacks.rb
index 29c72d1024..6e9c68b747 100644
--- i/activerecord/lib/active_record/callbacks.rb
+++ w/activerecord/lib/active_record/callbacks.rb
@@ -418,7 +418,7 @@ module ClassMethods
 
     def destroy # :nodoc:
       @_destroy_callback_already_called ||= false
-      return if @_destroy_callback_already_called
+      return true if @_destroy_callback_already_called
       @_destroy_callback_already_called = true
       _run_destroy_callbacks { super }
     rescue RecordNotDestroyed => e
```

Credit for the patch belongs to [Alex](https://stackoverflow.com/a/77917179/151007).

### System configuration

**Rails version**: 7.1.3

**Ruby version**: 3.3.0

### PR DESCRIPTION
**Pull request by airblade**
With a bi-directional has one through association, where the join model belongs to each parent with `dependent: :destroy`, destroying either parent should destroy the through record and the other parent.

    class Left < ActiveRecord::Base
      has_one :middle, dependent: :destroy
      has_one :right, through: :middle
    end

    class Middle < ActiveRecord::Base
      belongs_to :left, dependent: :destroy
      belongs_to :right, dependent: :destroy
    end

    class Right < ActiveRecord::Base
      has_one :middle, dependent: :destroy
      has_one :left, through: :middle
    end

However this only worked from one end.  When destroying the "non-working" end, the join model was correctly destroyed but the other end was not.

In the example above:

- `right.destroy` correctly destroys its `middle` and its `left`;
- `left.destroy` destroys its `middle` but not its `right`.

The end which worked depended on the order of `belongs_to` statements in the join model.

This commit ensures that the no matter which end you destroy, the far end is destroyed (along with the join record).

Fixes #50948.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/test/cases/associations/has_one_through_associations_test.rb [hunk 1]
```diff
@@ -473,4 +476,20 @@ def test_cpk_stale_target
 
     assert_predicate(book.association(:order_agreement), :stale_target?)
   end
+
+  def test_bidirectional_has_one_through_destroys_from_both_ends
```
Comment (Edouard-chin) [inline activerecord/test/cases/associations/has_one_through_associations_test.rb:480]: We should be able to simplify the issue without the need to have a `through` relation. I think there should be existing models/fixtures in the codebase to reproduce the problem:

<details>
<summary> Bug report </summary>

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :pilots, force: true do |t|
  end

  create_table :cars, force: true do |t|
    t.integer :pilot_id
    t.integer :copilot_id
  end
end

class Pilot < ActiveRecord::Base
  has_one :car, dependent: :destroy
end

class Car < ActiveRecord::Base
  belongs_to :pilot, dependent: :destroy
  belongs_to :copilot, class_name: "Pilot", dependent: :destroy
end

class BugTest < Minitest::Test
  def test_destroy
    pilot = Pilot.create!
    copilot = Pilot.create!
    car = Car.create!(pilot: pilot, copilot: copilot)

    pilot.destroy!

    assert_raises(ActiveRecord::RecordNotFound) { car.reload }
    assert_raises(ActiveRecord::RecordNotFound) { pilot.reload }
    assert_raises(ActiveRecord::RecordNotFound, "The Copilot wasn't destroyed") { copilot.reload }
  end
end
```
</details>

**Review by Edouard-chin — COMMENTED** [review]
CI seems failing because of the new added tables. I wrote a bug template to reproduce the problem without a `through` relation which should help you reproduce without the need to create new tables and models

File: activerecord/test/cases/associations/has_one_through_associations_test.rb (hunk 1 above)
Comment (airblade) [reply activerecord/test/cases/associations/has_one_through_associations_test.rb:480]: The existing models have so much stuff in them that I couldn't find any to suit my left/middle/right setup, so I added new ones.

I agree that the bug can be reproduced with two belongs_to relations pointing to the same class; we don't need two different classes on the other end of the relations.

Comment (airblade) [reply activerecord/test/cases/associations/has_one_through_associations_test.rb:480]: Out of curiosity, why do you prefer `assert_raises(ActiveRecord::RecordNotFound) { car.reload }` to `assert_predicate(car, :destroyed?)`?

Comment (airblade) [reply activerecord/test/cases/associations/has_one_through_associations_test.rb:480]: Is `Pilot` a new class?  I can find [`Car`](https://github.com/rails/rails/blob/main/activerecord/test/models/car.rb) but not `Pilot`.

Comment (Edouard-chin) [reply activerecord/test/cases/associations/has_one_through_associations_test.rb:480]: > Is Pilot a new class?

It was just an example to find a similar setup in the codebase. This two models are what you are looking for (just need to add `dependent :destroy` on both side of the association). The diff will be much smaller and we don't need to add new tables/models https://github.com/rails/rails/blob/cb47c12aa5ec907204c9e9c26fd57a86d2f0d86f/activerecord/test/models/user.rb#L16
https://github.com/rails/rails/blob/cb47c12aa5ec907204c9e9c26fd57a86d2f0d86f/activerecord/test/models/room.rb#L4-L5

> Out of curiosity, why do you prefer assert_raises(ActiveRecord::RecordNotFound) { car.reload }

No reason in this case, `assert_predicate(car, :destroyed?)` is fine too!

**Comment by airblade** [comment]
@Edouard-chin All the tests are passing now.  Ready for you to look at again.

**Review by Edouard-chin — APPROVED** [review]
👍

**Comment by airblade** [comment]
@Edouard-chin Thanks for reviewing!  Presumably I should combine all the commits into a single commit and rewrite the commit message?

**Comment by Edouard-chin** [comment]
Yes please :). Someone from the core team will give this the final merge when they get a chance.

Thanks for your work on this!

**Comment by airblade** [comment]
All done!  Thanks for all the guidance :-)

**Comment by airblade** [comment]
The build test failures are unrelated (they concern ActiveStorage).

**Comment by airblade** [comment]
The build failure is due to unrelated test failures in ActiveStorage.

**Comment by airblade** [comment]
> Someone from the core team will give this the final merge when they get a chance.

@Edouard-chin Is there a way to get this noticed by the core team?

**Comment by skipkayhil** [comment]
> Is there a way to get this noticed by the core team?

I added it to the next 7.1 milestone so it should be reviewed the next release. If you want it merged quicker you could bring it up on [discord](https://discord.gg/d8N68BCw49)

**Comment by airblade** [comment]
@skipkayhil Thank you.

**Comment by airblade** [comment]
I just rebased and re-pushed this.  The test failure is entirely unrelated.

@byroot Do you think it would be possible to slip this into 7.2.0?

**Comment by airblade** [comment]
@byroot Thank you very much!
