### PR TITLE
Fix migrations compatibility for polymorphic references default index name

### LINKED ISSUE #41547: Different index name is given when running migration in Rails 6.1
### Steps to reproduce

```
git clone git@github.com:JunichiIto/index_name_sandbox.git
bundle install
rails db:create
rails db:migrate
git diff
```

Then, you will see:

```diff
diff --git a/db/schema.rb b/db/schema.rb
index 38de2d5..5834f92 100644
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -23,7 +23,7 @@ ActiveRecord::Schema.define(version: 2021_02_25_025817) do
     t.datetime "updated_at", null: false
     t.string "widget_type"
     t.bigint "widget_id"
-    t.index ["imageable_type", "imageable_id"], name: "index_pictures_on_imageable_type_and_imageable_id"
+    t.index ["imageable_type", "imageable_id"], name: "index_pictures_on_imageable"
     t.index ["widget_type", "widget_id"], name: "index_pictures_on_widget_type_and_widget_id"
   end
```

### Expected behavior

`git diff` should show nothing. (no difference)

### Actual behavior

- [The polymorphic index name that was defined in Rails 5.2](https://github.com/JunichiIto/index_name_sandbox/blob/main/db/migrate/20210225025058_create_pictures.rb#L5) will change in Rails 6.1.
- But [the polymorphic index name that was defined in Rails 6.0](https://github.com/JunichiIto/index_name_sandbox/blob/main/db/migrate/20210225025817_add_widget_reference_to_pictures.rb#L3) will not change in Rails 6.1.

This issue seems to be related to https://github.com/rails/rails/pull/38717 (And I give a mention to @lukeredpath and @eugeneius )

### System configuration
**Rails version**: Rails 6.1.3

**Ruby version**: Ruby 2.7.2

### LINKED ISSUE #41693: ActiveRecord migrations with polymorphic references create indexes with different name
### Steps to reproduce

Create a table with a polymorphic `references` in a < 6.0 migration, run the migration with ActiveRecord 6.

This was most probably introduced by e8437a68f614d61722d94445a9792ccde5dfa0da.

<details>
<summary>Minimal testcase</summary>

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.1.3"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

class CreateSettings < ActiveRecord::Migration[5.0]
  def self.up
    create_table :settings do |t|
      t.references :target, null: false, polymorphic: true
    end
  end
end

class BugTest < Minitest::Test
  def test_migration_up
    CreateSettings.migrate(:up)
    assert CreateSettings.index_name_exists?(:settings, :index_settings_on_target_type_and_target_id)
  end
end
```

</details>

### Expected behavior

The created index should have the same name when the migration runs in ActiveRecord 6 than it had in ActiveRecord 5, in this case, `index_settings_on_target_type_and_target_id`.

### Actual behavior

The migration creates an index with a different name: `index_settings_on_target`.

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 2.7.2p137

### LINKED ISSUE #44268: references/belongs_to method create a column as integer when migration version is 6.0 even if we use PostgreSQL/MySQL
### Steps to reproduce

sample app is here https://github.com/willnet/rails701-migration-bug-sample 

1. `rails new -d postgresql rails701-migration-bug-sample`
1. cd rails701-migration-bug-sample
1. rails g model parent
1. rails g model child parent:references
1. modify db/migrate/YYYYMMDD_create_children.rb from `ActiveRecord::Migration[7.0]` to `ActiveRecord::Migration[6.0]`
1. rails db:create
1. rails db:migrate
1. see schema.rb

### Expected behavior

references/belongs_to method create a column as bigint if we use PostgreSQL/MySQL

### Actual behavior

references/belongs_to method create a column as integer if we use PostgreSQL/MySQL

This behavior seemed to be introduced by https://github.com/rails/rails/pull/43295 

### System configuration

- Rails 7.0.1
- Ruby 3.1.0

### PR DESCRIPTION
**Pull request by fatkodima**
Most changes are extracting existing test cases into a separate module to easily test agains all affected rails versions.

Closes #41693
Closes #41547
Closes #44268

Some `super`s in `def compatible_table_definition(t)` bodies were missing and this caused some compatibility classes to not took its place properly. 

I also haven't found a good way to override `ConnectionAdapters::ReferenceDefinition#index_options` (like mentioned in https://github.com/rails/rails/pull/38717#issuecomment-624204682), so used an original implementation (hash private option) from that PR.

### CODE REVIEW

**Review by zzak — APPROVED** [review]
@JunichiIto confirmed this is working so I'm willing to give it a 👍 based on that, but I haven't looked closely at the code to be certain.

**Comment by ziaulrehman40** [comment]
THis issue is still happening

**Comment by fatkodima** [comment]
@p8 Can you, please, review?

File: activerecord/test/cases/migration/compatibility_test.rb [hunk 1]
```diff
@@ -269,81 +269,120 @@ def migrate(x)
...
+end
+
+module LegacyPolymorphicReferenceIndexTest
+  ["6.0", "5.2", "5.1", "5.0", "4.2"].each do |version|
+    klass = Class.new(ActiveRecord::TestCase)
+    klass.class_eval <<~RUBY
+      include LegacyPolymorphicReferenceIndexTestCases
+
+      self.use_transactional_tests = false
+
```
Comment (p8) [inline activerecord/test/cases/migration/compatibility_test.rb:376]: Does using a block for Class not work here?
```suggestion
    klass = Class.new(ActiveRecord::TestCase) do
      include LegacyPolymorphicReferenceIndexTestCases

      self.use_transactional_tests = false

```

File: activerecord/test/cases/migration/compatibility_test.rb [hunk 2]
```diff
@@ -269,81 +269,120 @@ def migrate(x)
...
+      def self.name
+        "V#{version.underscore}"
```
Comment (p8) [inline activerecord/test/cases/migration/compatibility_test.rb:378]: Is underscore necessary for versions like "6.0"?

**Review by p8 — COMMENTED** [review]
@fatkodima This basically reverts the following change right?
https://github.com/rails/rails/pull/38717#issuecomment-711416085

And does this PR take into account https://github.com/rails/rails/pull/43295 ?

File: activerecord/test/cases/migration/compatibility_test.rb (hunk 1 above)
Comment (fatkodima) [reply activerecord/test/cases/migration/compatibility_test.rb:618]: We need to use `version` in its methods (`name` and `migration_class`) , so for block version to work we need to write something like `VERSION = version` or `@@version = version` and use it inside that methods. Or use a `class_eval`. Not sure which approach is better.

File: activerecord/test/cases/migration/compatibility_test.rb (hunk 2 above)
Comment (fatkodima) [reply activerecord/test/cases/migration/compatibility_test.rb:620]: It is only used to give anonymous classes in tests a name for easier debugging.
```
Error:
#test_polymorphic_add_reference_uses_all_column_names_in_index
```

vs
```
Error:
V6.0#test_polymorphic_add_reference_uses_all_column_names_in_index:
```

**Comment by fatkodima** [comment]
@p8 Thank you for the review!

> This basically reverts the following change right?
> #38717 (comment)

Yes.

> And does this PR take into account #43295 ?

Updated this PR to take that into.

**Comment by ZilvinasKucinskas** [comment]
Ported PR changes to v7.0.2.3 and tested by running on a project I am trying to migrate from 7.0.0 to 7.0.2.3 (`db/schema.rb` has lots of changes from `bigint` to `integer`):

```bash
bundle exec rake db:drop db:create db:migrate
git diff db/schema.rb
```

No more issues. `references` and `belongs_to` methods create a column as `bigint`. 👍 

A temporary solution until this is merged might be adding explicit `type: :bigint` option to old migrations (which is tedious work).

**Comment by tvdeyen** [comment]
This needs to be back ported to 6.1.x as well

**Comment by rafaelfranca** [comment]
> This needs to be back ported to 6.1.x as well

6.1 doesn't receive bugfixes anymore.

**Comment by tvdeyen** [comment]
But Rails 6.1.5 has been released last week that introduced this bug to 6.1.x


Quoting the release notes 

> If you find any regression, please let us know in the issue tracker so we can fix as soon as possible.

This is a major issue for all mysql users and gem engines supporting mysql, forcing users to either upgrade to 7.0 or stay below 6.1.5

Can you please reevaluate?

File: activerecord/test/cases/migration/compatibility_test.rb [hunk 3]
```diff
@@ -601,6 +535,111 @@ def precision_implicit_default
...
+
+    ActiveRecord::Migrator.new(:up, [migration], @schema_migration).migrate
+
+    assert connection.index_exists?(:testings, [:widget_type, :widget_id], name: :index_testings_on_widget_type_and_widget_id)
+    assert connection.index_exists?(:testings, [:gizmo_type, :gizmo_id], name: :index_testings_on_gizmo_type_and_gizmo_id)
+  end
+end
+
+module LegacyPolymorphicReferenceIndexTest
+  ["6.0", "5.2", "5.1", "5.0", "4.2"].each do |version|
```
Comment (rafaelfranca) [inline activerecord/test/cases/migration/compatibility_test.rb:624]: Can we avoid this metaprogramming and just define all classes? This list isn't going to grow anymore.

**Comment by rafaelfranca** [comment]
Some context is missing here. The code being changed here exists since 6.1.0, so how was tris introduced in 6.1.5?

File: activerecord/test/cases/migration/compatibility_test.rb (hunk 2 above)
Comment (p8) [reply activerecord/test/cases/migration/compatibility_test.rb:632]: Sorry for the ate reply, but I don't think `underscore` does anything for the values in:
```["6.0", "5.2", "5.1", "5.0", "4.2"]```.

Comment (fatkodima) [reply activerecord/test/cases/migration/compatibility_test.rb:632]: Ah, right, I misinterpreted it as like "why we need these versions in name".

**Comment by rafaelfranca** [comment]
Ok. I see https://github.com/rails/rails/pull/43295 is the one that introduced the issue in 6.1.5. I'll apply this to 6.1.x as well.

File: activerecord/test/cases/migration/compatibility_test.rb (hunk 3 above)
Comment (fatkodima) [reply activerecord/test/cases/migration/compatibility_test.rb]: Yes, reworked.

**Comment by rafaelfranca** [comment]
This patch doesn't apply clearly on 6-1-stable. @fatkodima do you want to work in a version for that branch?

**Comment by tvdeyen** [comment]
> Ok. I see #43295 is the one that introduced the issue in 6.1.5. I'll apply this to 6.1.x as well.

Thank you
