### PR TITLE
Fix ActionMailer assertions don't work for parameterized mail with legacy delivery job

### LINKED ISSUE #37605: assert_enqueued_emails does not work when sending a parameterized email
### Steps to reproduce
When I run `assert_enqueued_emails` I noticed it only works with `ActionMailer::DeliveryJob` and does not work with a `ActionMailer::Parameterized::DeliveryJob`. 

Does work
```
assert_enqueued_emails 1 do
  SubscriptionMailer.welcome.deliver_later
end
```

Does not work
```
assert_enqueued_emails 1 do
  SubscriptionMailer.with(User.first).welcome.deliver_later
end
```
So it appears the `assert_enqueued_emails` only works when you aren't sending a parameterized email.

### Expected behavior

This should result in a passed test
```.```

### Actual behavior
Running the above results in a failure
```1 jobs expected, but 0 were enqueued.```

### System configuration
**Rails version**:
Rails 6.0.0
**Ruby version**:
ruby 2.6.2p47

I believe the issue may be from the following line. When `delivery_job` is called on i.e. `SubscriptionMailer` it will only returns `ActionMailer::DeliveryJob` and not `ActionMailer::Parameterized::DeliveryJob`. I believe it needs to check for both?
https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/actionmailer/lib/action_mailer/test_helper.rb#L159

### PR DESCRIPTION
**Pull request by bogdanvlviv**
We should backport this to `6-0-stable`.

Fixes https://github.com/rails/rails/issues/37605

### CODE REVIEW

**Review by Edouard-chin — APPROVED** [review]

File: actionmailer/lib/action_mailer/test_helper.rb [hunk 1]
```diff
@@ -155,7 +155,8 @@ def assert_no_enqueued_emails(&block)
       def delivery_job_filter(job)
         job_class = job.is_a?(Hash) ? job.fetch(:job) : job.class
 
-        Base.descendants.map(&:delivery_job).include?(job_class)
+        Base.descendants.map(&:delivery_job).include?(job_class) ||
+        ActionMailer::Parameterized::DeliveryJob == job_class
```
Comment (Edouard-chin) [inline actionmailer/lib/action_mailer/test_helper.rb]: There is no rubocop rules for that sadly, but I think the convention is to indent multiline conditions 

```ruby
Base.descendants.map(&:delivery_job).include?(job_class) ||
  ActionMailer::Parameterized::DeliveryJob == job_class
```

Comment (bogdanvlviv) [reply actionmailer/lib/action_mailer/test_helper.rb]: Fixed.

**Comment by kaspth** [comment]
Backported to 6-0-stable in 7601b18a69

**Comment by kaspth** [comment]
Thanks, Bogdan! 🙌
