### PR TITLE
[Fix #54591] Raise an error in order dependent finder methods when the model has no order columns

### LINKED ISSUE #54591: Inconsistent finder method behaviour without primary key and implicit_order_column
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record/railtie"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
  config.secret_key_base = "secret_key_base"

  config.active_record.encryption.primary_key = "primary_key"
  config.active_record.encryption.deterministic_key = "deterministic_key"
  config.active_record.encryption.key_derivation_salt = "key_derivation_salt"
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :posts, force: true, id: false do |t|
    t.integer :order_column, null: false
  end
end

class Post < ActiveRecord::Base
  # self.implicit_order_column = "order_column"
end

class BugTest < ActiveSupport::TestCase
  def test_first_and_last_without_primary_key_and_order_column
    Post.create! order_column: 3
    Post.create! order_column: 1
    Post.create! order_column: 2

    assert_nothing_raised { Post.first } # ✅
    assert_nothing_raised { Post.last } # ❌
  end
end

```

### Expected behavior

Both `first` and `last` should either return a result without ordering or raise an error.

### Actual behavior

`first` returns a result without ordering, `last` raises:

```
ActiveRecord::IrreversibleOrderError: Relation has no current order and table has no primary key to be used as default order
```

### System configuration

**Rails version**: Edge

**Ruby version**: 3.4.2

### PR DESCRIPTION
**Pull request by joshuay03**
### Motivation / Background

Fixes https://github.com/rails/rails/issues/54591
Follow-up to https://github.com/rails/rails/pull/54607

### Detail

1. Adds a new error `ActiveRecord::MissingRequiredOrderError` which gets raised in `ActiveRecord::FinderMethods#ordered_relation` (used by `#last` and and all `find_nth*` methods) when there are no `order_values` and no order columns to be used for the default order.
2. Updates a similar case where `ActiveRecord::IrreversibleOrderError` is raised in `ActiveRecord::QueryMethods#reverse_sql_order` to have a message consistent with this new error.

cc @byroot

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/lib/active_record/errors.rb [hunk 1]
```diff
@@ -552,6 +552,11 @@ class SerializationFailure < TransactionRollbackError
...
   end
 
+  # OrderError is raised when a relation needs to be ordered but does not have any
+  # order columns to use.
+  class OrderError < ActiveRecordError
+  end
+
   # IrreversibleOrderError is raised when a relation's order is too complex for
   # +reverse_order+ to automatically reverse.
   class IrreversibleOrderError < ActiveRecordError
```
Comment (skipkayhil) [inline activerecord/lib/active_record/errors.rb:562]: I like how `IrreversibleOrderError` is self-documenting; it has a sentence describing it but you can generally tell what it does without having to look it up. Should `OrderError` be something like `MissingRequiredOrderError` so that its more self-documenting?

File: activerecord/lib/active_record/relation/finder_methods.rb [hunk 2]
```diff
@@ -638,8 +638,15 @@ def find_last(limit)
...
-        if order_values.empty? && !_order_columns.empty?
-          order(_order_columns.map { |column| table[column].asc })
+        if order_values.empty?
+          if !_order_columns.empty?
+            return order(_order_columns.map { |column| table[column].asc })
+          end
+
+          raise OrderError, <<~MSG.squish
+            Relation has no current order, and #{model} has no order columns to use as a default.
+            At least one of `implicit_order_column`, `query_constraints`, or `primary_key` must be set on the model.
```
Comment (skipkayhil) [inline activerecord/lib/active_record/relation/finder_methods.rb:648]: I think `must be set` isn't quite correct, because you could also specify an `order` on the relation? (same concern with the change to the other error)

Comment (joshuay03) [reply activerecord/lib/active_record/relation/finder_methods.rb:648]: > because you could also specify an order on the relation?

Yes that's what this first bit is alluding to:

> Relation has no current order,

But I can make it more clear by specifying that in the suggestion as well 👍🏽

File: activerecord/lib/active_record/errors.rb (hunk 1 above)
Comment (joshuay03) [reply activerecord/lib/active_record/errors.rb:562]: I like that, will action 👍🏽

Comment (joshuay03) [reply activerecord/lib/active_record/errors.rb]: Done!

File: activerecord/lib/active_record/relation/finder_methods.rb (hunk 2 above)
Comment (joshuay03) [reply activerecord/lib/active_record/relation/finder_methods.rb]: Done, let me know if it's clearer now.

File: activerecord/test/cases/finder_test.rb [hunk 3]
```diff
@@ -1055,10 +1056,93 @@ def test_last_on_loaded_relation_should_not_use_sql
...
+    assert_nil Edge.implicit_order_column
+    assert_nil Edge.query_constraints_list
+    error = assert_raises(ActiveRecord::MissingRequiredOrderError) do
+      Edge.all.last
+    end
+    assert_equal <<~MSG.squish, error.message
+      Relation has no current order, and Edge has no order columns to use as a default.
+      Set at least one of `implicit_order_column`, `query_constraints` or `primary_key` on
+      the model when no `order `is specified on the relation.
+    MSG
```
Comment (byroot) [inline activerecord/test/cases/finder_test.rb:1111]: I'm not sure it's worth matching the whole message. Something like `assert_match "Relation has no current order"` is enough and less things to change if we decide to reword the error message.

**Review by byroot — APPROVED** [review]
I like this a lot. I'll wait a couple days to see if someone opposes though.

**Comment by byroot** [comment]
I wonder if this should be considered breaking enough to warrant a framework default and a deprecation.

Which is debatable because this is solving a bug, but prior you'd get a somewhat unpredictable behavior but "working" behavior, now you'd get a straight error.

File: activerecord/test/cases/finder_test.rb (hunk 3 above)
Comment (joshuay03) [reply activerecord/test/cases/finder_test.rb]: Addressed.

**Comment by joshuay03** [comment]
> > I wonder if this should be considered breaking enough to warrant a framework default and a deprecation.
> > Which is debatable because this is solving a bug, but prior you'd get a somewhat unpredictable behavior but "working" behavior, now you'd get a straight error.
> 
> Hmm, yeah, that's a good point, I can see the argument for a deprecation notice. I will action soon 👍🏽

Action-ed! Hopefully I've done all the things right...

**Comment by byroot** [comment]
Uh, just realized this fell through the cracks, I'll try to rebase it.

File: activerecord/lib/active_record/relation/finder_methods.rb [hunk 4]
```diff
@@ -638,8 +638,27 @@ def find_last(limit)
...
-        if order_values.empty? && !_order_columns.empty?
-          order(_order_columns.map { |column| table[column].asc })
+        if order_values.empty?
+          if !_order_columns.empty?
+            return order(_order_columns.map { |column| table[column].asc })
+          end
+
+          if ActiveRecord.raise_on_missing_required_finder_order_columns
+            raise MissingRequiredOrderError, <<~MSG.squish
+              Relation has no order values, and #{model} has no order columns to use as a default.
```
Comment (byroot) [inline activerecord/lib/active_record/relation/finder_methods.rb:648]:
```suggestion
              Relation has no order values, and #{model.name} has no order columns to use as a default.
```

`model` is a AR class here right? I think we should just use the name, because otherwise `AR::Base.inspect` can be super long and hard to read.

Comment (byroot) [reply activerecord/lib/active_record/relation/finder_methods.rb:648]: Nevermind, `AR::Base.to_s` no longer include columns.

**Comment by joshuay03** [comment]
Thank you!
