### PR TITLE
Ensure custom PK types are casted in through reflection queries

### LINKED ISSUE #35839: "has_many through" association doesn't behave consistently when using a custom-typed PK column
### Steps to reproduce

```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
  gem 'uuidtools'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table 'tokens', id: :binary, limit: 16, force: true
  create_table 'users', force: true

  create_table 'token_users', force: true do |t|
    t.integer 'user_id'
    t.binary 'token_id', limit: 16, null: false
  end
end

class UuidType < ActiveRecord::Type::Binary
  def serialize(value)
    super(cast_to_uuid(value)&.raw)
  end

  def deserialize(value)
    cast_to_uuid(super(value)).to_s
  end

  def cast_value(value)
    cast_to_uuid(value).to_s
  end

  private

  def cast_to_uuid(value)
    return if value.nil?

    case value.size
    when 16 then UUIDTools::UUID.parse_raw(value) # From `uuidtools` gem
    when 36 then UUIDTools::UUID.parse(value)     # From `uuidtools` gem
    end
  end
end

class User < ActiveRecord::Base
end

class Token < ActiveRecord::Base
  attribute :id, UuidType.new, default: SecureRandom.uuid

  has_many :token_users
  has_many :users, through: :token_users
end

class TokenUser < ActiveRecord::Base
  attribute :token_id, UuidType.new

  belongs_to :user
  belongs_to :token
end

class IssueTest < Minitest::Test
  def test_association_with_uuid
    token = Token.create!
    token.users << User.create!

    assert_equal 1, token.reload.token_users.count
    assert_equal 1, token.reload.users.count
  end
end
```

### Expected behavior

The SQL `where` clause generated for `has_many` is similar to the following and works perfectly:
```sql
WHERE column = x'4e254953bcdb4793a485ac04131565a7'
```

I would expect the one generated for `has_many :through` to be similar...

### Actual behavior

But instead, it generates:
```sql
WHERE column = '4e254953-bcdb-4793-a485-ac04131565a7'
```

The problem is that the second one (`has_many :through`) doesn't include the `x` prefix and also doesn't remove the hyphens (If I manually do that, it solves the issue).

It doesn't return any error, but also **doesn't return any results**.

### System configuration

**Rails version**: `6.0.0.beta3` (master)

**Ruby version**: `2.6.2`

I was able to replicate the issue with both **MySQL** and **SQlite** and both **Rails 5** and **6**.

Thank you.

### PR DESCRIPTION
**Pull request by gmcgibbon**
### Summary

Make sure primary keys with non-integer types (eg. binary) can be correctly type casted in queries using through reflections.

Fixes https://github.com/rails/rails/issues/35839.

I deferred this check to happen when the through reflection computes its class and memoizes the result. Still, I'm curious if this one time runtime check is too expensive. Thoughts?

### CODE REVIEW

File: activerecord/lib/active_record/reflection.rb [hunk 1]
```diff
@@ -764,7 +764,16 @@ def through_reflection?
       end
 
       def klass
-        @klass ||= delegate_reflection.compute_class(class_name)
+        @klass ||= delegate_reflection.compute_class(class_name).tap do |klass|
+          if ! parent_reflection.is_a?(HasAndBelongsToManyReflection) &&
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/reflection.rb]:
```suggestion
          if !parent_reflection.is_a?(HasAndBelongsToManyReflection) &&
```

File: activerecord/lib/active_record/reflection.rb [hunk 2]
```diff
@@ -764,7 +764,16 @@ def through_reflection?
...
+             ! klass.reflections.include?(options[:through].to_s) &&
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/reflection.rb]:
```suggestion
             !klass.reflections.include?(options[:through].to_s) &&
```

**Review by rafaelfranca — APPROVED** [review]

**Comment by ekampp** [comment]
This breaks ActiveStorage associations for UUID primary keys. It also breaks has_many with the through option with UUID primary keys.

**Comment by gmcgibbon** [comment]
@ekampp Can you open an issue and reproduce the problem in [the bug report template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb)? Thanks!

**Comment by ekampp** [comment]
I guess I can, but wouldn't it be better to have some more thorough tests rather than everybody having to open individual bug reports on every ID type?

**Comment by ekampp** [comment]
I see this in the code for this PR: `active_record.type_for_attribute(active_record.primary_key).type != :integer`

This will always trigger the NotImplementedError for anything other than integers, right?

**Comment by gmcgibbon** [comment]
> I guess I can, but wouldn't it be better to have some more thorough tests rather than everybody having to open individual bug reports on every ID type?

That isn't really the point. I want to see why this change is causing you trouble first before we try and fix anything. Also, we can only guess at how to solve a problem without reproduction steps.

> This will always trigger the NotImplementedError for anything other than integers, right?

If you don't have the correct associations in place to properly type cast IDs, yes. Please read the issue this PR fixes for context.

**Comment by ekampp** [comment]
> If you don't have the correct associations in place to properly type cast IDs, yes. 

I don't actually see any tests in this PR for any PK types other than integers? So how are you even sure that your PR correctly handles anything other than Integers?

**Comment by ekampp** [comment]
In any case. Here is the [demo project](https://github.com/ekampp/pk_cast_demo) that illustrates the problem.

**Comment by ekampp** [comment]
The error message I'm getting is: 

> In order to correctly type cast [sic] Structure.id, Account needs to define a :project association.

But the account doesn't have a single project association. It has multiple project associations. So the error message seems to also be incorrect.

**Comment by crispinheneise** [comment]
This is still a problem with `has_many :through` when using UUIDs for primary keys: 

```rb
# Table name: documents
#
#  id          :uuid             not null, primary key
class Document < ApplicationRecord
  has_many :sections
  has_many :paragraphs, through: :sections
end

# Table name: sections
#
#  id                      :uuid             not null, primary key
#  document_id             :uuid
class Section < ApplicationRecord
  belongs_to :document
  has_many :paragraphs
end

# Table name: paragraphs
#  id            :uuid             not null, primary key
#  section_id    :uuid             not null
class Paragraph < ApplicationRecord
  belongs_to :section
end
```

```rb
irb(main)> document.paragraphs
Traceback (most recent call last):
        1: from (irb):5
NotImplementedError (In order to correctly type cast Document.id, Payment needs to define a :sections association.)
```

**Comment by mattes** [comment]
Not just `:uuids`, custom `::ActiveRecord::Type`'s don't work either. See https://stackoverflow.com/questions/60242514/rails-custom-activerecordtype-fails-when-using-class-name-in-has-many-throu

**Comment by jeremy** [comment]
Updated #38340 to reflect that @crispinheneise and @mattes. Thank you.

**Comment by crispinheneise** [comment]
I just opened a new issue #38724, but I can close it since it's pretty much a dup.

**Comment by crispinheneise** [comment]
This is the block that is raising the exception: 

https://github.com/rails/rails/blob/99b607e6ad681b17de40d6cc55aa3af7989305db/activerecord/lib/active_record/reflection.rb#L772-L780

**Comment by crispinheneise** [comment]
I added a test script to reproduce this error in https://github.com/rails/rails/issues/38340#issuecomment-598952864

File: activerecord/lib/active_record/reflection.rb [hunk 3]
```diff
@@ -764,7 +764,16 @@ def through_reflection?
       end
 
       def klass
-        @klass ||= delegate_reflection.compute_class(class_name)
+        @klass ||= delegate_reflection.compute_class(class_name).tap do |klass|
+          if !parent_reflection.is_a?(HasAndBelongsToManyReflection) &&
+             !klass.reflections.include?(options[:through].to_s) &&
+             active_record.type_for_attribute(active_record.primary_key).type != :integer
```
Comment (josh-m-sharpe) [inline activerecord/lib/active_record/reflection.rb:770]: re: https://github.com/rails/rails/issues/38340 I updated this line to be:

`![:integer, :uuid].include?(active_record.type_for_attribute(active_record.primary_key).type)`

This "Works" in the sense that it allows my hacking around with the new ActiveStorage proxy feature to continue.
