### PR TITLE
[close #22917] Don't output to `STDOUT` twice

### LINKED ISSUE #22917: Logger is expected to respond to `broadcast_messages`
The logger method was added by @nwjsmith  in this commit https://github.com/rails/rails/commit/e12ffb76ffcedd150e7d0c3dc4f93472aa4790cb and docs in https://github.com/nwjsmith/rails/commit/5f73c3cd51eb367b07c1a150092e6f8df3bdd759 Rails now expects a logger to have a `broadcast_messages` method. This is a method that does not exist on the other loggers such as the standard lib's logger. When you try to set another logger it will break. Setting your logging to STDOUT for example will be broken:

```
      logger       = ::Logger.new(STDOUT)
      logger       = ActiveSupport::TaggedLogging.new(logger)
```

Since Ruby's stdlib logger does not have a `broadcast_messages` method. 

```
irb(main):004:0> Rails.logger.warn("foo")
NameError: undefined local variable or method `broadcast_messages' for #<RailsStdoutLogging::StdoutLogger:0x007fd3fa901db8>
	from /Users/richardschneeman/.gem/ruby/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/logger.rb:14:in `block (2 levels) in broadcast'
	from /Users/richardschneeman/.rubies/ruby-2.3.0-preview2/lib/ruby/2.3.0/logger.rb:497:in `warn'
	from (irb):4
	from /Users/richardschneeman/.gem/ruby/2.3.0/gems/railties-5.0.0.beta1/lib/rails/commands/console.rb:65:in `start'
	from /Users/richardschneeman/.gem/ruby/2.3.0/gems/railties-5.0.0.beta1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/richardschneeman/.gem/ruby/2.3.0/gems/railties-5.0.0.beta1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/richardschneeman/.gem/ruby/2.3.0/gems/railties-5.0.0.beta1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/richardschneeman/.gem/ruby/2.3.0/gems/railties-5.0.0.beta1/lib/rails/command.rb:20:in `run'
	from /Users/richardschneeman/.gem/ruby/2.3.0/gems/railties-5.0.0.beta1/lib/rails/commands.rb:19:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
```

### PR DESCRIPTION
**Pull request by schneems**
When `rails console` or `rails server` are used along with a logger set to output to `STDOUT` then the contents will show up twice. This happens because the logger is extended with `ActiveSupportLogger.broadcast` with a destination of STDOUT even if it is already outputting to `STDOUT`.

Previously PR #22592 attempted to fix this issue, but it ended up causing NoMethodErrors. A better approach than relying on adding a method and flow control is to inspect the log destination directly. For this `ActiveSupport::Logger.logger_outputs_to?` was introduced

``` ruby
logger = Logger.new(STDOUT)
ActiveSupport::Logger.logger_outputs_to?(logger, STDOUT)
# => true
```

To accomplish this we must look inside of an instance variable of standard lib's Logger `@logdev`. There is a related Ruby proposal to expose this method in a standard way: https://bugs.ruby-lang.org/issues/11955

### CODE REVIEW

File: activesupport/test/logger_test.rb [hunk 1]
```diff
@@ -17,6 +17,14 @@ def setup
     @logger  = Logger.new(@output)
   end
 
+  def test_log_outputs_to
+    assert Logger.logger_outputs_to?(@logger, @output),          "Expected logger_outputs_to? @output to return true but was false"
+    assert Logger.logger_outputs_to?(@logger, @output, STDOUT),  "Expected logger_outputs_to? @output or STDOUT to return true but was false"
+
+    assert ! Logger.logger_outputs_to?(@logger, STDOUT),         "Expected log_outputs? to STDOUT to return false, but was true"
```
Comment (rafaelfranca) [inline activesupport/test/logger_test.rb]: `assert_not`

Comment (rafaelfranca) [inline activesupport/test/logger_test.rb]: Also better to not align the messages, if we need to change something in one line we would have to change in others too.

The message is also using `log_outputs?` instead of `logger_outputs_to?`

File: railties/lib/rails/commands/server.rb [hunk 2]
```diff
@@ -137,7 +137,9 @@ def log_to_stdout
         console.formatter = Rails.logger.formatter
         console.level = Rails.logger.level
 
-        Rails.logger.extend(ActiveSupport::Logger.broadcast(console))
+        unless ActiveSupport::Logger.logger_outputs_to?(Rails.logger, $stdout)
```
Comment (rafaelfranca) [inline railties/lib/rails/commands/server.rb]: Why here it is using `$stdout` instead of `STDOUT` like other places?

File: activesupport/lib/active_support/logger.rb [hunk 3]
```diff
@@ -1,3 +1,4 @@
+require 'active_support/core_ext/module/attribute_accessors'
```
Comment (rafaelfranca) [inline activesupport/lib/active_support/logger.rb]: Is this still needed?

**Comment by rafaelfranca** [comment]
I agree that this approach is better but for me it is relying in something that is not public and we don't have guarantees if it will still work in the future.

File: railties/lib/rails/commands/server.rb (hunk 2 above)
Comment (schneems) [inline railties/lib/rails/commands/server.rb]: I matched $stdout to the existing usage in the file. I'll switch them both over to STDOUT.

**Comment by schneems** [comment]
> relying in something that is not public and we don't have guarantees if it will still work in the future.

I designed this to fail gracefully, when something doesn't have that instance variable or that variable doesn't respond to `dev` then it will not return `true`. In that case we will always log to STDOUT which is no different from the behavior we have today. That interface hasn't changed in a very long time but I will stick around and maintain this code if the interface changes, I can accommodate any updates to Logger.

**Comment by schneems** [comment]
updated

**Comment by rafaelfranca** [comment]
Seems good to me. I think the `broadcast_message` option is documented in the guides as well in the CHANGELOG, we should remove it too. :shipit:

**Comment by schneems** [comment]
I did a grep and removed all mentions of `broadcast_message`.

**Comment by eileencodes** [comment]
I don't think it made it into the guides. The original PR didn't have a changelog and I didn't add one.  Here's the doc PR which was just in the code https://github.com/rails/rails/commit/a13032cab141c3faa99702a1de904192d99a07ea

**Comment by jonathan-mui** [comment]
I attempted to follow https://github.com/rails/rails/pull/22592, but found out that has since been changed with this PR. How should this change be used in the environment config file to prevent duplicate logging?

**Comment by pboling** [comment]
@jonathan-mui and googlers: you shouldn't have to do anything for Rails 5, it will just work.  That's what this PR does.  You can find an alternative for Rails 4 here: https://github.com/rails/rails/issues/11415#issuecomment-281789530
