### PR TITLE
Prevent double firing the before save callback of new object when the parent association saved in the callback

### LINKED ISSUE #26661: Accessing ActiveRecord relation from ActiveModel::Validator mutates the collection
### Steps to reproduce

```ruby
require "bundler/setup"
require 'active_record'
require 'sqlite3'

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Schema.define do
  create_table :applied_gift_cards, force: true do |t|
    t.references :checkout, null: false
  end
  create_table :checkouts, force: true do |t|
  end
end

class GiftCardValidator < ActiveModel::Validator
  def validate(model)
    puts "count inside validator: #{model.checkout.applied_gift_cards.size}"
  end
end

class Checkout < ActiveRecord::Base
  has_many :applied_gift_cards
end

class AppliedGiftCard < ActiveRecord::Base
  belongs_to :checkout

  validates :checkout, presence: true
  validates_with GiftCardValidator
end

checkout = Checkout.create!
checkout.applied_gift_cards.create!
checkout.applied_gift_cards.create!

puts "records created: #{checkout.applied_gift_cards.size}"
checkout.reload
puts "records created: #{checkout.applied_gift_cards.size}"
```

### Expected behavior

It's expected that after calling `create!` two times, the `checkout.applied_gift_cards.size` value will be `2`

### Actual behavior

```
count inside validator: 0
count inside validator: 0
records created: 1
records created: 2
```

### System configuration
**Rails version**: master (`21ecf42730de2004a95d913038c1f417c24496be`)

**Ruby version**: 2.3.0

The bug only affects >= 5.0. Rails 4.2 works fine:

```
count inside validator: 0
count inside validator: 1
records created: 2
records created: 2
```

?r @sgrif 
cc @rafaelfranca

### LINKED ISSUE #28599: Double save plus attribute_changed? deprecation warning if save called from before_save
### Steps to reproduce

I have the following app

```ruby
class Order < ApplicationRecord
  has_many :details
  validate :validate_name, if: lambda { |obj| obj.name_changed? }

  def validate_name
    puts "validate_name"
  end
end

class Detail < ApplicationRecord
  belongs_to :order
  before_save :update_order

  def update_order
    order.name += ' (updated)'
    order.save
  end
end
```

(As you can see, `Detail#save` can be called from the before_save callback since `Order#save` saves its children.)

Now, do

```ruby
o = Order.create! name: 'An order'
o.details.create!
```

### Expected behavior
I expect this to work without deprecation warnings.

### Actual behavior
I'm getting a deprecation warning that suggest the behavior of `attribute_changed?` changed from inside after callbacks, but this is not inside one (I could of course not use the deprecation warning's suggested fix of changing to `saved_change_to_attribute?` since it's not saved yet).

> DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead. (called from block in <class:MyModel> at /Users/magnus/Code/rails_test/api/app/models/my_model.rb:2)

### System configuration
**Rails version**: 5.1.0.rc1 and master

**Ruby version**: 2.4.1

### PR DESCRIPTION
**Pull request by kamipo**
Related #18155, #26661, 268a5bb, #27434, #27442, and #28599.

Originally #18155 was introduced for preventing double insertion caused
by the after save callback. But it was caused the before save issue
(#26661). 268a5bb fixed #26661, but it was caused the performance
regression (#27434). #27442 added new record to `target` before calling
callbacks for fixing #27434. But it was caused double firing before save
callback (#28599). We cannot add new object to `target` before saving
the object.

This is improving #18155 to only track callbacks after `save`.

Fixes #28599.

### CODE REVIEW

**Comment by superacidjax** [comment]
Thanks for this fix. This behavior was driving me crazy with my test suite.

**Comment by matthewd** [comment]
I really like how neat this feels! But adding the block parameter to the public `save` / `save!` methods doesn't seem great :confused:

**Comment by kamipo** [comment]
Actually we don't need to change the `save` / `save!` methods in `Suppressor`, `Transactions`, and `AttributeMethods::Dirty` because calling `super` can propagate a block unless adding the block parameter.

https://github.com/rails/rails/blob/v5.1.0.rc1/activerecord/lib/active_record/suppressor.rb#L41-L48
https://github.com/rails/rails/blob/v5.1.0.rc1/activerecord/lib/active_record/transactions.rb#L306-L314
https://github.com/rails/rails/blob/v5.1.0.rc1/activerecord/lib/active_record/attribute_methods/dirty.rb#L34-L46

But the deepest `save` / `save!` methods in `Persistence` need to pass args to `create_or_update`. It can not be realized except by adding the block parameter.

https://github.com/rails/rails/blob/v5.1.0.rc1/activerecord/lib/active_record/persistence.rb#L124-L155

File: activerecord/lib/active_record/associations/has_many_association.rb [hunk 1]
```diff
@@ -29,14 +29,9 @@ def handle_dependency
         end
       end
 
-      def insert_record(record, validate = true, raise = false)
+      def insert_record(record, validate = true, raise = false, &block)
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/associations/has_many_association.rb]: Do we need to capture the block? I don't seems used.

File: activerecord/lib/active_record/associations/has_many_through_association.rb [hunk 2]
```diff
@@ -35,15 +35,11 @@ def concat_records(records)
         records
       end
 
-      def insert_record(record, validate = true, raise = false)
+      def insert_record(record, validate = true, raise = false, &block)
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/associations/has_many_through_association.rb]: Same about capturing the block

File: activerecord/lib/active_record/persistence.rb [hunk 3]
```diff
@@ -121,8 +121,8 @@ def persisted?
     #
     # Attributes marked as readonly are silently ignored if the record is
     # being updated.
-    def save(*args)
-      create_or_update(*args)
+    def save(*args, &block)
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/persistence.rb]: This is the public method and like @matthewd pointed it is not good to add a block to this method. Since we need it can we at least remove `&block` from the method signature on rdoc using the `:args:` directive?

File: activerecord/lib/active_record/persistence.rb [hunk 4]
```diff
@@ -100,6 +100,10 @@ def persisted?
       !(@new_record || @destroyed)
     end
 
+    ##
+    # :call-seq:
+    #   save(*args)
```
Comment (kamipo) [inline activerecord/lib/active_record/persistence.rb]: I tried using `:args:` to remove `&block` but didn't work at least in my local.
So I used `:call-seq:` instead, then it worked properly.

image

**Review by rafaelfranca — APPROVED** [review]
Awesome. Could you squash the commits?

**Comment by kamipo** [comment]
Squashed!

**Comment by rafaelfranca** [comment]
Backported in 9d112c2527

**Comment by kamipo** [comment]
This is also an issue for 5-0-stable.
https://github.com/rails/rails/blob/v5.0.2/activerecord/lib/active_record/associations/collection_association.rb#L434-L441

**Comment by rafaelfranca** [comment]
@kamipo could you create a backport PR. It doesn't apply clearly.
