### PR TITLE
Make time travel work with subclasses of Time/Date/Datetime

### LINKED ISSUE #27614: Time travel using TimeHelpers breaks subclasses of Time
For some ungodly reason, some libraries like Rubyzip subclass Ruby's built in `Time` class. This is a problem when `travel_to` stubs `Time.now`, because the value returned from then calling `now` on a `Time` subclass, such as `Zip::DOSTime` would return an instance of `Time` instead of returning an instance of `Zip::DOSTime`.

I'm unsure of how to best solve this problem. The current implementation of `TimeHelpers` assumes that simply returning a static value is adequate, and this implementation is correct for the classes itself, but does not work when subclassing. Of course one could make a case that core classes shouldn't be subclassed, like Aaron wrote on his blog a while ago, but code like this is out there, and in my case caused breakage in the app I was working on, and it seems like tracking down and fixing such broken code would be a game of whack-a-mole.

Timecop has had the same issue, documented [here](https://github.com/travisjeffery/timecop/issues/25) and applied a [fix](https://github.com/travisjeffery/timecop/commit/da726032513d0d3bc72ceab0bea08e05f3944234) to work around this issue. However, looking at this fix it seems that the way it is implemented is by being aware of the workings of `Time` in the actual stubbing. The [`SimpleStubs`](https://github.com/rails/rails/blob/7f19f30819dd5a5a788ad9d8b12b5dda76559a12/activesupport/lib/active_support/testing/time_helpers.rb#L6) class that Rails uses is a very basic generic stubbing class, but it would need to be much more aware of the internal workings of `Time` to apply such a fix. This class is `#:nodoc:` so changing it should be okay, I think?

### Steps to reproduce

``` ruby
irb(main):015:0> Zip::DOSTime.now.class
=> Zip::DOSTime
irb(main):016:0> travel_to 1.day.ago
=> nil
irb(main):017:0> Zip::DOSTime.now.class
=> Time
```

I also wrote a test case for this within the rails test suite [here](https://github.com/rails/rails/compare/master...jnicklas:time-travel-now-test). [Here](https://gist.github.com/jnicklas/88b3f06ab395c904f48b736ecdd8c0ea) it is using the template.

### Expected behavior

Calling `now` on a subclass of `Time` after time traveling should return an instance of the subclass.

### Actual behavior

Calling `now` on a subclass of `Time` after time traveling returns an instance of `Time`.

### System configuration
**Rails version**: affects all Rails versions since the addition of `travel_to`, verified against `master`.
**Ruby version**: `2.3.3`

### PR DESCRIPTION
**Pull request by jnicklas**
Closes #27614

Previously when calling `now` on a subclass of e.g. `Time` it would return an instance of `Time` instead of returning an instance of the subclass. This way, we always return the correct class.

### CODE REVIEW

File: activesupport/lib/active_support/testing/time_helpers.rb [hunk 1]
```diff
@@ -134,9 +134,9 @@ def travel_to(date_or_time)
           now = date_or_time.to_time.change(usec: 0)
         end
 
-        simple_stubs.stub_object(Time, :now, now)
-        simple_stubs.stub_object(Date, :today, now.to_date)
-        simple_stubs.stub_object(DateTime, :now, now.to_datetime)
+        simple_stubs.stub_object(Time, :now) { at(now.to_i) }
+        simple_stubs.stub_object(Date, :today) { parse(now.to_date.to_s) }
```
Comment (jnicklas) [inline activesupport/lib/active_support/testing/time_helpers.rb]: There is probably a more performant way of implementing this, but I figured that this way is simple and the performance of it probably doesn't matter.

Comment (pixeltrix) [inline activesupport/lib/active_support/testing/time_helpers.rb]: How about `jd(now.to_date.jd)` ?

File: activesupport/lib/active_support/testing/time_helpers.rb [hunk 2]
```diff
@@ -134,9 +134,9 @@ def travel_to(date_or_time)
...
+        simple_stubs.stub_object(DateTime, :now) { parse(now.to_datetime.to_s) }
```
Comment (pixeltrix) [inline activesupport/lib/active_support/testing/time_helpers.rb]: For `DateTime` you can use `Rational`, e.g:

``` ruby
simple_stubs.stub_object(DateTime, :now) { jd(now.to_datetime.jd + Rational(now.seconds_since_midnight, 86400)) }
```

File: activesupport/lib/active_support/testing/time_helpers.rb (hunk 1 above)
Comment (matthewd) [inline activesupport/lib/active_support/testing/time_helpers.rb]: This one looks like it could use `jd`. I don't think DateTime has any similar single-number in+out representation, though.

Comment (pixeltrix) [inline activesupport/lib/active_support/testing/time_helpers.rb]: > I don't think DateTime has any similar single-number in+out representation, though.

@matthewd `DateTime.jd` can take a `Rational` with the fraction part representing the time as a fraction of a day. Unfortunately there's no easy way to get that number - it may be worth adding such a method to Active Support.

File: activesupport/lib/active_support/testing/time_helpers.rb (hunk 2 above)
Comment (jnicklas) [inline activesupport/lib/active_support/testing/time_helpers.rb]: I tried this but it seems that Time zone information is lost this way. I found a similar implementation which does preserve time zone implementation though.

File: activesupport/lib/active_support/testing/time_helpers.rb (hunk 1 above)
Comment (jnicklas) [inline activesupport/lib/active_support/testing/time_helpers.rb]: Updated! Thanks for the hint.

File: activesupport/lib/active_support/testing/time_helpers.rb (hunk 2 above)
Comment (pixeltrix) [inline activesupport/lib/active_support/testing/time_helpers.rb]: > seems that Time zone information is lost this way

Ah, that would make sense since a [Julian Day][1] is in [Universal Time][2].

[1]: https://en.wikipedia.org/wiki/Julian_day
[2]: https://en.wikipedia.org/wiki/Universal_Time

**Comment by pixeltrix** [comment]
@jnicklas thanks! 👍

**Comment by pixeltrix** [comment]
Backported to 5-0-stable in 477ae8d

**Comment by pixeltrix** [comment]
Also managed to backport it to 4-2-stable in d7ac341 - had to adjust the stubbing in the tests.
