### PR TITLE
Accept empty list of attributes for `insert_all`, `insert_all!` and `upsert_all`

### LINKED ISSUE #45710: Model.upsert_all raises ArgumentError if passed an empty array
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    empty_array = []
    Post.create(empty_array)

    assert_raises(ArgumentError) do
      Post.upsert_all(empty_array)
    end
  end
end

```

Which like... is on purpose as we can see in this lil snip, but why?

https://github.com/rails/rails/blob/d96609505511a76c618dc3adfa3ca4679317d008/activerecord/lib/active_record/insert_all.rb#L5-L11

### Expected behavior
Nothing happens, same as `Model.create` when passed an empty array. Or like... most things that accept arrays.

### Actual behavior
Raises `initialize: Empty list of attributes passed (ArgumentError)`

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.1.2

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #45710.

Originally, I wanted to update `InsertAll` class (instead of changing 3 methods) to handle empty arrays, but that special handling become kinda ugly and more complex than needed. I think, it is better and simpler to just handle that case in each of the 3 methods. 

cc @byroot

### CODE REVIEW

File: activerecord/lib/active_record/persistence.rb [hunk 1]
```diff
@@ -143,7 +143,9 @@ def insert(attributes, returning: nil, unique_by: nil, record_timestamps: nil)
       #     { id: 2, title: "Eloquent Ruby" }
       #   ])
       def insert_all(attributes, returning: nil, unique_by: nil, record_timestamps: nil)
-        InsertAll.new(self, attributes, on_duplicate: :skip, returning: returning, unique_by: unique_by, record_timestamps: record_timestamps).execute
+        if attributes.any?
+          InsertAll.new(self, attributes, on_duplicate: :skip, returning: returning, unique_by: unique_by, record_timestamps: record_timestamps).execute
+        end
```
Comment (byroot) [inline activerecord/lib/active_record/persistence.rb:148]:
```suggestion
        return if attributes.empty?
        InsertAll.new(self, attributes, on_duplicate: :skip, returning: returning, unique_by: unique_by, record_timestamps: record_timestamps).execute
```

It's a bit of a nitpick, but I'm always a bit uneasy with `Array#any?` being used as a shortcut for `!array.empty?`, it's not strictly equivalent because `[false, nil].any? # => false`.

In this case all the array elements should be arrays themselves, so valid input can't possibly be falsy, but someone may pass some invalid input have end up with a weird behavior.

**Comment by simi** [comment]
Any reason to not return [ActiveRecord::Result.empty](https://github.com/rails/rails/blob/195f20dca8bd1f58359ae3c1b89ac3bda094ddac/activerecord/lib/active_record/result.rb#L39) when attributes are empty? If I remember well it wasn't implemented at the time of the original implementation and that was probably the reason to raise. But empty was implemented meanwhile. :pray:

**Comment by byroot** [comment]
> Any reason to not return [ActiveRecord::Result.empty](https://github.com/rails/rails/blob/195f20dca8bd1f58359ae3c1b89ac3bda094ddac/activerecord/lib/active_record/result.rb#L39)

Makes sense to me. 👍

**Comment by fatkodima** [comment]
Updated with `ActiveRecord::Result.empty`.

File: activerecord/lib/active_record/persistence.rb [hunk 2]
```diff
@@ -143,7 +143,11 @@ def insert(attributes, returning: nil, unique_by: nil, record_timestamps: nil)
       #     { id: 2, title: "Eloquent Ruby" }
       #   ])
       def insert_all(attributes, returning: nil, unique_by: nil, record_timestamps: nil)
-        InsertAll.new(self, attributes, on_duplicate: :skip, returning: returning, unique_by: unique_by, record_timestamps: record_timestamps).execute
+        if attributes.empty?
```
Comment (simi) [inline activerecord/lib/active_record/persistence.rb:146]: To prevent this wrap 3 times it would be possible as well to create something like `InsertAll.execute` and do this simple check in there.

File: activerecord/test/cases/insert_all_test.rb [hunk 3]
```diff
@@ -63,8 +63,10 @@ def test_insert_all
   end
 
   def test_insert_all_should_handle_empty_arrays
-    assert_raise ArgumentError do
+    assert_no_difference -> { Book.count } do
+      Book.insert_all []
```
Comment (simi) [inline activerecord/test/cases/insert_all_test.rb:67]: You can also assert empty result in here right now.

**Comment by simi** [comment]
@byroot are you ok with theoretical backward in-compatibility of this? Original behaviour of raising exception is undocumented and with this PR it is actually closer to documentation.

> Returns an [ActiveRecord::Result](https://api.rubyonrails.org/classes/ActiveRecord/Result.html) with its contents based on :returning (see below).

Other than that LGTM! :muscle:

**Comment by byroot** [comment]
Yeah I'm ok with the backward compatibility guarantees here. We're in an edge case, most likely people who encountered this behavior are either rescuing `ArgumentError` to silence it, or checking `insert.empty?` prior to invoke the method.

So I don't see how this could cause any undesirable behavior on existing code.
