### PR TITLE
`Pathname.blank?` only returns true for `Pathname.new("")`

### LINKED ISSUE #44452: Pathname.presence has surprising semantics
Because `Object#blank?` bounces to `empty?` if it exists, and because `Pathname#empty?` checks whether the directory/file is empty, the result is, I venture, not the intended semantics.  IMHO, `Pathname#blank?` should check whether this is `Pathname.new('')`.

### Steps to reproduce
```ruby
p = Pathname.new('/tmp/foo')  # Where /tmp/foo does not exist.
p p.presence # => #<Pathname:/tmp/foo>
p.mkpath
p p.presence  # => nil

p Pathname.new('').blank? # => false
```

### Expected behavior

I expect `Pathname#blank?` to behave like `to_s.empty?`, or, arguably, like `to_s.blank?`.

### Actual behavior

Tells whether the file/dir is empty.

### System configuration
**Rails version**:

7.0.1

**Ruby version**:

2.7.4

### PR DESCRIPTION
**Pull request by byroot**
Fix: https://github.com/rails/rails/issues/44452

We don't ignore blank path strings because as surprising as it is, they
are valid paths:

```ruby
>> path = Pathname.new(" ")
=> #<Pathname: >
>> path.write("test")
=> 4
>> path.exist?
=> true
```

Previously it would end up calling `Pathname#empty?` which returned true
if the path existed and was an empty directory or file.

That behavior was unlikely to be expected.

### CODE REVIEW

File: activesupport/lib/active_support/core_ext/pathname/blank.rb [hunk 1]
```diff
@@ -0,0 +1,16 @@
+# frozen_string_literal: true
+
+require "pathname"
+
+class Pathname
+  # An Pathname is blank if it's empty:
+  #
+  #   Pathname.new("").blank?      # => true
+  #   Pathname.new(" ").blank?     # => false
+  #   Pathname.new("test).blank?  # => false
```
Comment (jasl) [inline activesupport/lib/active_support/core_ext/pathname/blank.rb:10]: missing an `"`? (should be `Pathname.new("test").blank?`)

Comment (byroot) [reply activesupport/lib/active_support/core_ext/pathname/blank.rb:10]: Thanks, fixed in https://github.com/rails/rails/commit/c9c1768a91c2b6e6ca68268ed87b3a7327ab81dd
