### PR TITLE
Fix crash for invalid Content-Type in ShowExceptions middleware

### LINKED ISSUE #51228: It is not possible to handle "not a valid MIME type" error using the exceptions_app = self.routes when the value of CONTENT_TYPE header is invalid
### Steps to reproduce

almost same as
https://github.com/rails/rails/issues/43094

1. Generate a new application:

```
rails new InvalidMimeTypeApp --skip-action-mailer --skip-action-mailbox --skip-action-text --skip-active-storage --skip-action-cable --skip-sprockets --skip-spring --skip-listen --skip-javascript --skip-turbolinks --skip-jbuilder --skip-test --skip-system-test --skip-bootsnap
```

2. Apply the following diff:

```
diff --git a/app/controllers/application_controller.rb b/app/controllers/application_controller.rb
index 09705d1..1b28aee 100644
--- a/app/controllers/application_controller.rb
+++ b/app/controllers/application_controller.rb
@@ -1,2 +1,13 @@
 class ApplicationController < ActionController::Base
+    def about
+        render '/about'
+    end
+
+    def not_found
+        render json: { error: "some error message" }, status: :not_found
+    end
+    
+    def unsupported
+        render json: { error: "some error message" }, status: :unsupported_media_type
+    end
 end
diff --git a/config/application.rb b/config/application.rb
index e28b261..d960e3c 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -38,5 +38,7 @@ module InvalidMimeTypeApp
 
     # Don't generate system test files.
     config.generators.system_tests = nil
+
+    config.exceptions_app = self.routes
   end
 end
diff --git a/config/environments/development.rb b/config/environments/development.rb
index ff757b7..5b3fdfb 100644
--- a/config/environments/development.rb
+++ b/config/environments/development.rb
@@ -12,7 +12,7 @@ Rails.application.configure do
   config.eager_load = false
 
   # Show full error reports.
-  config.consider_all_requests_local = true
+  config.consider_all_requests_local = false
 
   # Enable server timing
   config.server_timing = true
diff --git a/config/routes.rb b/config/routes.rb
index a125ef0..36308ca 100644
--- a/config/routes.rb
+++ b/config/routes.rb
@@ -7,4 +7,8 @@ Rails.application.routes.draw do
 
   # Defines the root path route ("/")
   # root "posts#index"
+
+  get "/about", to: "application#about"
+  match "/404", to: "application#not_found", via: :all
+  match "/415", to: "application#unsupported", via: :all
 end
```

3. Run the server and cURL the application with an invalid request:

```
 curl -i -X POST -H "Content-Type: invalid;" http://localhost:3000/about
HTTP/1.1 500 Internal Server Error
content-type: text/plain; charset=utf-8
x-request-id: 122a50df-16d0-465a-97d6-f0dc4b7bed85
x-runtime: 0.004729
server-timing: 
Content-Length: 182

500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.%                                                                                                                                                         (base) 
```

### Expected behavior

The application calls the `ApplicationController#not_found` or `ApplicationController#unsupported` action as stated in the `config/routes.rb` file.

This PR can fix the behavior but I don't know why this PR was not merged.
https://github.com/rails/rails/pull/46757

Since the `ActionController::RoutingError (No route matches [POST] "/about"):` error occurs first, a 404 error would be sufficient for my use, but it may be more appropriate to have a 415 error drawn.

### Actual behavior

The application raises [500 Internal Server Error with the generic message](https://github.com/rails/rails/blob/v6.1.4.1/actionpack/lib/action_dispatch/middleware/show_exceptions.rb#L20-L24) as it cannot parse the invalid MIME type. The application logs the following lines:

```
Started POST "/about" for 127.0.0.1 at 2024-03-01 19:15:41 +0900
  
ActionController::RoutingError (No route matches [POST] "/about"):
  
Error during failsafe response: "invalid" is not a valid MIME type
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/http/mime_negotiation.rb:45:in `rescue in block in content_mime_type'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/http/mime_negotiation.rb:38:in `block in content_mime_type'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/rack-3.0.9.1/lib/rack/request.rb:107:in `fetch'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/rack-3.0.9.1/lib/rack/request.rb:107:in `fetch_header'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/http/mime_negotiation.rb:37:in `content_mime_type'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_controller/metal/params_wrapper.rb:294:in `_wrapper_enabled?'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_controller/metal/params_wrapper.rb:260:in `process_action'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/activerecord-7.1.3.2/lib/active_record/railties/controller_runtime.rb:32:in `process_action'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/abstract_controller/base.rb:160:in `process'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionview-7.1.3.2/lib/action_view/rendering.rb:40:in `process'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_controller/metal.rb:227:in `dispatch'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_controller/metal.rb:309:in `dispatch'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/routing/route_set.rb:32:in `serve'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/journey/router.rb:51:in `block in serve'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/journey/router.rb:124:in `each'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/journey/router.rb:124:in `find_routes'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/journey/router.rb:32:in `serve'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/routing/route_set.rb:882:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/middleware/show_exceptions.rb:52:in `render_exception'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/middleware/show_exceptions.rb:37:in `rescue in call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.3.2/lib/rails/rack/logger.rb:37:in `call_app'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.3.2/lib/rails/rack/logger.rb:24:in `block in call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/activesupport-7.1.3.2/lib/active_support/tagged_logging.rb:135:in `block in tagged'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/activesupport-7.1.3.2/lib/active_support/tagged_logging.rb:39:in `tagged'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/activesupport-7.1.3.2/lib/active_support/tagged_logging.rb:135:in `tagged'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/activesupport-7.1.3.2/lib/active_support/broadcast_logger.rb:240:in `method_missing'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.3.2/lib/rails/rack/logger.rb:24:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/middleware/request_id.rb:28:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/rack-3.0.9.1/lib/rack/method_override.rb:28:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/rack-3.0.9.1/lib/rack/runtime.rb:24:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/activesupport-7.1.3.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/middleware/server_timing.rb:59:in `block in call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/middleware/server_timing.rb:24:in `collect_events'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/middleware/server_timing.rb:58:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/middleware/static.rb:25:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/rack-3.0.9.1/lib/rack/sendfile.rb:114:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/actionpack-7.1.3.2/lib/action_dispatch/middleware/host_authorization.rb:141:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/railties-7.1.3.2/lib/rails/engine.rb:536:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'
****/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

### System configuration
**Rails version**:
7.1.3.2

**Ruby version**:
3.1.4

### PR DESCRIPTION
**Pull request by Earlopain**
### Motivation / Background

Closes #51228. This is the same as #43104 but for the Content-Type header.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by casperisfine** [comment]
cc @byroot

File: actionpack/lib/action_dispatch/middleware/show_exceptions.rb [hunk 1]
```diff
@@ -67,9 +67,17 @@ def render_exception(request, wrapper)
...
         # If the MIME type for the request is invalid then the @exceptions_app may not
         # be able to handle it. To make it easier to handle, we switch to HTML.
-        request.formats
-      rescue ActionDispatch::Http::MimeNegotiation::InvalidType
-        request.set_header "HTTP_ACCEPT", "text/html"
+        begin
+          request.content_mime_type
+        rescue ActionDispatch::Http::MimeNegotiation::InvalidType
+          request.set_header "CONTENT_TYPE", "text/html"
+        end
```
Comment (skipkayhil) [inline actionpack/lib/action_dispatch/middleware/show_exceptions.rb:74]: I'm not sure this is the right fix. Why is the `CONTENT_TYPE` being set to `text/html`? That's almost certainly not the correct type for request parameters.

Comment (Earlopain) [reply actionpack/lib/action_dispatch/middleware/show_exceptions.rb:74]: Probably not, yes. But any other type that is more likely to be correct like application/json or form data will also only be correct by chance. The client already sent bogus data.

I went with symetry with `HTTP_ACCEPT`, however I have no problems with using something like `application/x-www-form-urlencoded` instead

Comment (rafaelfranca) [reply actionpack/lib/action_dispatch/middleware/show_exceptions.rb:74]: This is the the content type of the error page we want rendered. The request parameters aren't sent to the error page.

Comment (skipkayhil) [reply actionpack/lib/action_dispatch/middleware/show_exceptions.rb:74]: Isn't that what the existing `HTTP_ACCEPT` header controls?

The backtrace in the linked issue is coming from `ParamWrapper#_wrapper_enabled?`, and if the exception is rescued in that method then a second error is raised when the exceptions app tries to call `filtered_parameters` (because its unable to parse the invalid `CONTENT_TYPE` of the request params)

Comment (rafaelfranca) [reply actionpack/lib/action_dispatch/middleware/show_exceptions.rb:74]: HTTP_ACCEPT doesn't control the CONTENT_TYPE. The problem of the issue isn't that the exception is raised on `_wrapper_enabled?` but that the exceptions application also raises an error in the same place. If the content-type is made valid it would not and the correct exception page would be rendered.
