### PR TITLE
Don't fail ImageAnalyzer on unsupported types

### LINKED ISSUE #36065: ImageAnalyzer incorrectly assumes that it can handle all images
### Steps to reproduce

1) Attach a .heic image to a model using active storage

### Expected behavior

no crashes

### Actual behavior

the analyze job crashes

```
E, [2019-04-23T15:03:07.688988 #27434] ERROR -- : [ActiveJob] [ActiveStorage::AnalyzeJob] [ac0cc544-ca92-435a-b489-a216eee92931] Error performing ActiveStorage::AnalyzeJob (Job ID: ac0cc544-ca92-435a-b489-a216eee92931) from Sidekiq(default) in 247.25ms: MiniMagick::Error (`identify -format %[orientation] /tmp/ActiveStorage20190423-27434-xfqooz.heic[0]` failed with error:
identify-im6.q16: no decode delegate for this image format `HEIC' @ error/constitute.c/ReadImage/504.
):


```

### System configuration
**Rails version**:
5.2.2

**Ruby version**:
ruby-2.4.0

This happens because the ImageAnalyzer assumes that ImageMagic can handle all image types. Unfortunately it can't.

The blob correctly identifies a .heic file as an image based on the content_type (image/heic)

The ImageAnalyzer incorrectly assumes that it can handle all images and sends things off to ImageMagic

ImageMagic (as of 6.9.7-4) can't handle .heic files, so it throws an error which means that sidekiq re-enqueues the job a bunch of times.

---

For the specific case of .heic, at some point my Ubuntu repo will end up with a more up-to-date version of ImageMagik which can handle the file, however there is always going to be a new image file (or an old one) that it can't handle.

It would seem like a good idea to provide some kind of config option for the ImageAnalyzer allowing users to override specific cases (e.g. don't try to analyze `image/xxx`, and possibly do try to analyze `picture/yyy`)

### PR DESCRIPTION
**Pull request by itsWill**
### Summary

Fix: #36065

The ImageAnalyzer passes a image to ImageMagick without checking if the
image is supported by ImageMagick. This patch checks that image is
supported and if not logs an error and returns an empty hash instead of
raising an error. This is the same error handling we do when we
encounter a LoadError when mini_magick is not installed.

### Other Information

This is a breaking change I was hoping to get a quick feedback on the idea and see if this is an approach worth persuing. We skip the image analysis on a `LoadError` so I thought we could skip it on an unsupported type as well.

One option is to also make this behaviour configurable. 

Another option is to raise a generic `ActiveStorage::UnsupportedImage` error so clients don't have to rescue a low level `MiniMagick::Error`.

### CODE REVIEW

File: activestorage/lib/active_storage/analyzer/image_analyzer.rb [hunk 1]
```diff
@@ -34,7 +34,13 @@ def metadata
       def read_image
         download_blob_to_tempfile do |file|
           require "mini_magick"
-          yield MiniMagick::Image.new(file.path)
+          image = MiniMagick::Image.new(file.path)
+          if image.valid?
+            yield image
+          else
+            logger.info "Skipping image analysis because mini_magick doesn't support the file"
```
Comment (itsWill) [inline activestorage/lib/active_storage/analyzer/image_analyzer.rb]: I'm tempted to move the `rescue LoadError` here since having the logging happen in the two methods makes it a bit harder to read, if we like this approach I'm happy to amend the PR.

File: activestorage/test/analyzer/image_analyzer_test.rb [hunk 2]
```diff
@@ -29,4 +29,13 @@ class ActiveStorage::Analyzer::ImageAnalyzerTest < ActiveSupport::TestCase
     assert_equal 792, metadata[:width]
     assert_equal 584, metadata[:height]
   end
+
+  test "analyzing an unsupported image type returns nil width and height metadata" do
+    blob = create_file_blob(filename: "bad_file.bad", content_type: "image/bad_type")
```
Comment (itsWill) [inline activestorage/test/analyzer/image_analyzer_test.rb]: Create a new fixture here, but we could also mock and stub the assertions.

File: activestorage/lib/active_storage/analyzer/image_analyzer.rb [hunk 3]
```diff
@@ -34,7 +34,13 @@ def metadata
       def read_image
         download_blob_to_tempfile do |file|
           require "mini_magick"
-          yield MiniMagick::Image.new(file.path)
+          image = MiniMagick::Image.new(file.path)
+          if image.valid?
```
Comment (georgeclaghorn) [inline activestorage/lib/active_storage/analyzer/image_analyzer.rb]: Leave a blank line above the conditional.

File: activestorage/lib/active_storage/analyzer/image_analyzer.rb (hunk 1 above)
Comment (georgeclaghorn) [reply activestorage/lib/active_storage/analyzer/image_analyzer.rb]: Please do.

This message is misleading: it’s ImageMagick that fails to decode the image.

File: activestorage/test/analyzer/image_analyzer_test.rb [hunk 4]
```diff
@@ -29,4 +29,13 @@ class ActiveStorage::Analyzer::ImageAnalyzerTest < ActiveSupport::TestCase
...
+
```
Comment (georgeclaghorn) [inline activestorage/test/analyzer/image_analyzer_test.rb]: :scissors: this blank line.

File: activestorage/test/analyzer/image_analyzer_test.rb [hunk 5]
```diff
@@ -29,4 +29,13 @@ class ActiveStorage::Analyzer::ImageAnalyzerTest < ActiveSupport::TestCase
     assert_equal 792, metadata[:width]
     assert_equal 584, metadata[:height]
   end
+
+  test "analyzing an unsupported image type returns nil width and height metadata" do
```
Comment (georgeclaghorn) [inline activestorage/test/analyzer/image_analyzer_test.rb]: Name this test “analyzing an unsupported image type” to match the others in this file. The test itself is clear as to what outcome it expects.

File: activestorage/test/analyzer/image_analyzer_test.rb (hunk 2 above)
Comment (georgeclaghorn) [reply activestorage/test/analyzer/image_analyzer_test.rb]: Use `create_blob(data: "", ...)` to avoid the empty fixture.

**Review by georgeclaghorn — CHANGES_REQUESTED** [review]

**Review by georgeclaghorn — APPROVED** [review]
Can you please add a CHANGELOG entry?

File: activestorage/lib/active_storage/analyzer/image_analyzer.rb (hunk 1 above)
Comment (georgeclaghorn) [reply activestorage/lib/active_storage/analyzer/image_analyzer.rb]: Please do move the `LoadError` rescue down.

**Comment by itsWill** [comment]
👍 done and squashed!

**Comment by ConfusedVorlon** [comment]
That was quick. Thank you.

For anyone coming to this issue before this reaches production; I wrote up a quick description on how to work around it with a custom analyzer.

https://blog.hobbyistsoftware.com/2019/04/active-storage-adding-a-custom-analyzer-for-unsupported-image-type/
