### PR TITLE
Don't add `bin/brakeman` if brakeman is not in bundle

### LINKED ISSUE #52576: `bin/brakeman` added when running `rails app:update` even without brakeman in Gemfile
### Steps to reproduce

Upgrading a Rails 7.1 application to Rails 7.2 adds a `bin/brakeman` when running `bin/rails app:update` after upgrading the gem.

### Expected behavior

Either of these solutions would be acceptable:

* `bin/brakeman` is not added unless it's already in the Gemfile.
* `brakeman` is added to the Gemfile.

But the first one seems favorable.

### Actual behavior

`bin/brakeman` is added but doesn't work:

```console
$ bin/brakeman 
/Users/etienne/.gem/ruby/3.3.4/gems/bundler-2.5.17/lib/bundler/rubygems_integration.rb:265:in `block in replace_bin_path': can't find executable brakeman for gem brakeman. brakeman is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/etienne/.gem/ruby/3.3.4/gems/bundler-2.5.17/lib/bundler/rubygems_integration.rb:304:in `block in replace_bin_path'
	from bin/brakeman:7:in `<main>'
```

### System configuration
**Rails version**:
7.1.3.4 then 7.2.0
**Ruby version**:
3.3.4

### PR DESCRIPTION
**Pull request by etiennebarrie**
Running `bin/rails app:update` with Rails 7.2.0 adds `bin/brakeman` even if it's not in the Gemfile already.

This checks whether brakeman is in the bundle (can be required), otherwise skips brakeman for the application generator.

### Motivation / Background

Fixes #52576 

### Detail

Repro repository:
https://github.com/etiennebarrie/rails-app/tree/bin-brakeman
we can see `bin/brakeman` gets added: https://github.com/etiennebarrie/rails-app/commit/4adad1519da8f7334ffd9dee0d89d7a67dcd1187

With the fix applied on top of to 7.2.0:
https://github.com/etiennebarrie/rails-app/tree/bin-brakeman-fixed-not-added `bin/brakeman` is not added in https://github.com/etiennebarrie/rails-app/commit/01f6ea5ab8c8cb7d65aeb69164ce846ee496440a
but it's still added if it's in the Gemfile:
**Edit:** with neither `bin/brakeman` nor `bin/rubocop` added:
https://github.com/etiennebarrie/rails-app/commit/39c8543c38f223747dc37c4bfd4ec496645599fd
https://github.com/etiennebarrie/rails-app/tree/bin-brakeman-fixed-added in 
https://github.com/etiennebarrie/rails-app/commit/fab069a0a9c28555fde004e3289ef0e41ef20e11

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by etiennebarrie** [comment]
Also handled `bin/rubocop` in the same way. `bin/thrust` will need to be handled for Rails 8.0, but since it won't be cherry-pickable, I won't add it to this PR.

File: railties/lib/rails/commands/app/update_command.rb [hunk 1]
```diff
@@ -87,6 +89,13 @@ def asset_pipeline
               nil
             end
           end
+
+          def skip_gem?(gem_name)
+            require gem_name
```
Comment (Earlopain) [inline railties/lib/rails/commands/app/update_command.rb:94]: I wonder if `gem gem_name` works here. Requiring rubocop takes quite a while, 0.7 seconds on my machine and that would be quite a bit faster.

Comment (etiennebarrie) [reply railties/lib/rails/commands/app/update_command.rb:94]: Yes good catch, I also get some time saved (the printed symbols are just to make sure the code runs):
```console
etiennebarrie/rails-app (bin-brakeman-fixed-added $) $ time bin/rails app:update:bin --force                                                                                                                                                                                    
:require
:require
       exist  bin
   identical  bin/brakeman
   identical  bin/rails
   identical  bin/rake
   identical  bin/rubocop
   identical  bin/setup

real	0m0.725s
user	0m0.471s
sys	0m0.247s
etiennebarrie/rails-app (bin-brakeman-fixed-added $) $ time bin/rails app:update:bin --force                                                                                                                                                                                    
:gem
:gem
       exist  bin
   identical  bin/brakeman
   identical  bin/rails
   identical  bin/rake
   identical  bin/rubocop
   identical  bin/setup

real	0m0.424s
user	0m0.261s
sys	0m0.153s
```
