### PR TITLE
Disable foreign keys during `alter_table` for sqlite3 adapter

### LINKED ISSUE #31988: change_column_null tries to drop table [ActiveRecord][SQLite][Mac]
### Description [ActiveRecord][SQLite]

Hi. I try to add a not null constraint to varchar(string in active record) field to table called categories but at some point of code execution I get a *DROP TABLE* error.

### Steps to reproduce

* Create a project: `rails new blog`
* Create a model: `rails g model Category name:string`
* Create another model: `rails g model Entry name:string category:references`
* Do migrate: `rails db:migrate` 
* Add some code to seeds:
```ruby
categories = [
    { id: 1, name: 'Category 1' }
]
Category.create! categories

entries = [
    { id: 1, name: 'Entry 1', category_id: 1 }
]
Entry.create! entries

```
* Do seeds: `rails bd:seed`
* Generate a new empty migration: `rails g migration AddNotNullToCategories`
* Try to use change_column_null with name attribute in categories table:
```ruby
class AddNotNullToCategories < ActiveRecord::Migration[5.1]
  def change
    change_column_null :categories, :name, false
  end
end
```
* Do migrate to get the error: `rails db:migrate` 

### Expected behavior

The not null constraint must be added field name in the table categories.

### Actual behavior

An error for try to delete the categories table:

```
== 20180213223453 AddNotNullToCategories: migrating ===========================
-- change_column_null(:categories, :name, false)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::ConstraintException: FOREIGN KEY constraint failed: DROP TABLE "categories"
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `step'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `block in each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `loop'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:152:in `map'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:152:in `block in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:95:in `prepare'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:251:in `block (2 levels) in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:250:in `block in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:249:in `execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:471:in `drop_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:435:in `move_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:427:in `block in alter_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:426:in `alter_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:370:in `change_column_null'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/Users/rowend/Projects/rails-bug-report/blog/db/migrate/20180213223453_add_not_null_to_categories.rb:3:in `change'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:792:in `exec_migration'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `ddl_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1150:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
ActiveRecord::InvalidForeignKey: SQLite3::ConstraintException: FOREIGN KEY constraint failed: DROP TABLE "categories"
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `step'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `block in each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `loop'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:152:in `map'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:152:in `block in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:95:in `prepare'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:251:in `block (2 levels) in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:250:in `block in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:249:in `execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:471:in `drop_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:435:in `move_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:427:in `block in alter_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:426:in `alter_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:370:in `change_column_null'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/Users/rowend/Projects/rails-bug-report/blog/db/migrate/20180213223453_add_not_null_to_categories.rb:3:in `change'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:792:in `exec_migration'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `ddl_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1150:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
SQLite3::ConstraintException: FOREIGN KEY constraint failed
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `step'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `block in each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `loop'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:152:in `map'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:152:in `block in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:95:in `prepare'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:251:in `block (2 levels) in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:250:in `block in execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:249:in `execute'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:471:in `drop_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:435:in `move_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:427:in `block in alter_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:426:in `alter_table'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:370:in `change_column_null'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/Users/rowend/Projects/rails-bug-report/blog/db/migrate/20180213223453_add_not_null_to_categories.rb:3:in `change'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:792:in `exec_migration'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `ddl_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1150:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/Users/rowend/Projects/rails-bug-report/blog/vendor/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### System configuration
**OS version**: macos High Sierra 10.13.2

**Rails version**: 5.1.4

**Ruby version**: 2.4.1

**Sqlite version**: 3.19.3

Thank you for the support and all the work you do.

### PR DESCRIPTION
**Pull request by yahonda**
### Summary

Unlike other databases, changing SQLite3 table definitions need to create a temporary table.
While changing table operations, the original table needs dropped which caused
`SQLite3::ConstraintException: FOREIGN KEY constraint failed` if the table is referenced by foreign keys. This pull request disables foreign keys by `disable_referential_integrity`.

Also `disable_referential_integrity` method needs to execute `defer_foreign_keys = ON`
to defer re-enabling foreign keys until the transaction is committed.

https://www.sqlite.org/pragma.html#pragma_defer_foreign_keys

Fixes #31988

### Other Information

- This pull request has been validated with sqlite3 3.8.2 on Ubuntu 14.04 LTS and sqlite3 3.22.0 on Ubuntu 18.04 LTS.

```
$ sqlite3 --version
3.8.2 2013-12-06 14:53:30 27392118af4c38c5203a04b8013e1afdb1cebd0d
```
```
$ sqlite3 --version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt1
```

This feature has been introduced since 
[SQLite Release 3.8.0 On 2013-08-26](https://www.sqlite.org/releaselog/3_8_0.html) . Also according to git blame at cloned SQLite repository, `defer_foreign_keys` pragma has been implemented
since `version-3.8.0` https://github.com/mackyle/sqlite/commit/8ebb3ba5a1188807b54c3fbda5ee37394d66c898

- <Models>.reset_column_information added to address `ActiveModel::UnknownAttributeError`

```ruby
Error:
ActiveRecord::Migration::ForeignKeyChangeColumnTest#test_change_column_of_parent_table:
ActiveModel::UnknownAttributeError: unknown attribute 'name' for ActiveRecord::Migration::ForeignKeyChangeColumnTest::Post.
```

### CODE REVIEW

**Comment by yahonda** [comment]
I have validated this pull request works with SQLite version 3.8.2 on `Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic x86_64)`

Then executed `PRAGMA defer_foreign_keys = ON;` manually from sqlite3 command line tool. It looks like this command is a no-op for SQLite 3.8.2 which does not support `defer_foreign_keys`.

```ruby
$ sqlite3
SQLite version 3.8.2 2013-12-06 14:53:30
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> PRAGMA defer_foreign_keys;
0
sqlite> PRAGMA defer_foreign_keys = ON;
sqlite> PRAGMA defer_foreign_keys = 0;
sqlite> .quit
$
```

**Comment by saiqulhaq** [comment]
what will happened if sqlite3 is below 3.8.2 version?

**Comment by yahonda** [comment]
This pull request works with SQLite 3.8.2. I also have created a SQL script file.

```
$ sqlite3 --version
3.8.2 2013-12-06 14:53:30 27392118af4c38c5203a04b8013e1afdb1cebd0d
$ curl https://raw.githubusercontent.com/yahonda/diag32865/master/01_foreign_keys_and_defer_foreign_keys.sql | sqlite3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1530  100  1530    0     0  41991      0 --:--:-- --:--:-- --:--:-- 42500
1
0
1|mypost
$
```

**Comment by yahonda** [comment]
According to git blame at cloned sqlite repository, `defer_foreign_keys` pragma has been implemented
since `version-3.8.0` https://github.com/mackyle/sqlite/commit/8ebb3ba5a1188807b54c3fbda5ee37394d66c898

**Comment by yahonda** [comment]
At first, I misunderstood that `defer_foreign_keys` feature has been supported since SQLite Release 3.12.0, which is wrong. This feature has been implemented and documented since 3.8.0. 3.12.0 added support for `disables RESTRICT actions on foreign key.`

"https://www.sqlite.org/releaselog/3_12_0.html
> The PRAGMA defer_foreign_keys=ON statement now also disables RESTRICT actions on foreign key.

https://www.sqlite.org/releaselog/3_8_0.html
> Added the defer_foreign_keys pragma and the sqlite3_db_status(db, SQLITE_DBSTATUS_DEFERRED_FKS,...) C-language interface.

Thanks.

**Comment by yahonda** [comment]
I have made a proposal at Rails core mailing list  to bump the minimum version of SQLite to 3.8 for Rails 6 https://groups.google.com/forum/#!topic/rubyonrails-core/OoHD65yjkvk

**Comment by rafaelfranca** [comment]
Yes. Let's raise the minimal version for Rails 6.

**Comment by yahonda** [comment]
Thanks for the suggestion. I have opened #32923 to bump the minimum version of SQLite to 3.8 for Rails 6.

File: activerecord/test/cases/migration/foreign_key_test.rb [hunk 1]
```diff
@@ -19,6 +19,52 @@ def test_foreign_keys
           assert_equal "fk_name", fk.name unless current_adapter?(:SQLite3Adapter)
         end
       end
+
+      if current_adapter?(:SQLite3Adapter)
```
Comment (kamipo) [inline activerecord/test/cases/migration/foreign_key_test.rb]: The condition is unnecessary since the test case should pass for all adapters which support foreign keys.

Comment (yahonda) [reply activerecord/test/cases/migration/foreign_key_test.rb]: It got failures with all bundled adapters https://travis-ci.org/rails/rails/builds/381658874 then reverted change then now it is tested with `sqlite3` adapters only.

Comment (kamipo) [reply activerecord/test/cases/migration/foreign_key_test.rb]: The reason which got failures is that dropping tables defined in https://github.com/rails/rails/blob/master/activerecord/test/schema/schema.rb after loaded.

Comment (yahonda) [reply activerecord/test/cases/migration/foreign_key_test.rb]: ah, you are right.

Comment (yahonda) [reply activerecord/test/cases/migration/foreign_key_test.rb]: Now using `Rocket` and `Astronaut` models not to conflict with other test files.

**Comment by robinboening** [comment]
@rafaelfranca Is there a reason this PR only made it into rails v6.0.0.beta1 release (https://github.com/rails/rails/releases/tag/v6.0.0.beta1 )? It was already merged one year ago and imo it fixes a broken behaviour which I jut experienced in rails 5.2.3.

Thanks
Robin
