### PR TITLE
Purge variants with their blobs

### LINKED ISSUE #31290: Purge blob and all variants
### Steps to reproduce

I have a model named  "event" which has a "logo" attachment.

Inside the rails console, called event.logo.purge

It only purged the main blob and did not purge all the other variants.

### Expected behavior
All variants should be purged, or should exist an option to do that.

### System configuration
**Rails 5.2.0.beta2**:

### PR DESCRIPTION
**Pull request by georgeclaghorn**
Fixes #31290.

### CODE REVIEW

File: activestorage/app/models/active_storage/blob.rb [hunk 1]
```diff
@@ -270,7 +270,8 @@ def analyzed?
   # deleted as well or you will essentially have a dead reference. It's recommended to use the +#purge+ and +#purge_later+
   # methods in most circumstances.
   def delete
-    service.delete key
+    service.delete(key)
+    service.delete_prefixed("variants/#{key}/") if image?
```
Comment (kaspth) [inline activestorage/app/models/active_storage/blob.rb]: Why do we only want this for `image?` variants? Isn't it a little sneaky that the `delete` behavior is different depending on the blob type?

File: activestorage/lib/active_storage/service/azure_storage_service.rb [hunk 2]
```diff
@@ -51,16 +51,32 @@ def delete(key)
       end
     end
 
+    def delete_prefixed(prefix)
+      instrument :delete_all, prefix: prefix do
```
Comment (kaspth) [inline activestorage/lib/active_storage/service/azure_storage_service.rb]: Fixed the instrumentation name to match the others in: 7609ca08ce

File: activestorage/lib/active_storage/service/azure_storage_service.rb [hunk 3]
```diff
@@ -51,16 +51,32 @@ def delete(key)
...
+        marker = nil
+
+        loop do
```
Comment (kaspth) [inline activestorage/lib/active_storage/service/azure_storage_service.rb]: Could this potentially block forever? Or does `list_blobs` time out? Does it raise an exception when it does?

File: activestorage/lib/active_storage/service/disk_service.rb [hunk 4]
```diff
@@ -48,16 +48,24 @@ def delete(key)
       end
     end
 
+    def delete_prefixed(prefix)
+      instrument :delete_prefixed, prefix: prefix do
+        Dir.glob(path_for("#{prefix}*")).each do |path|
```
Comment (kaspth) [inline activestorage/lib/active_storage/service/disk_service.rb]: `Dir.glob` can potentially return `.` and `..`. Should we do something specific here to filter them out? Or are they always filtered out via the prefix? (What happens if there's a blank prefix?)

File: activestorage/lib/active_storage/service/gcs_service.rb [hunk 5]
```diff
@@ -47,16 +47,22 @@ def delete(key)
       end
     end
 
+    def delete_prefixed(prefix)
+      instrument :delete_prefixed, prefix: prefix do
+        bucket.files(prefix: prefix).all(&:delete)
```
Comment (kaspth) [inline activestorage/lib/active_storage/service/gcs_service.rb]: Feels strange that the `gcs` API object uses `all` and not `each` 😄

**Review by kaspth — COMMENTED** [review]
Looks great! Just had some follow up questions out of curiosity mostly 😊

File: activestorage/app/models/active_storage/blob.rb (hunk 1 above)
Comment (georgeclaghorn) [reply activestorage/app/models/active_storage/blob.rb]: Non-image blobs don’t have variants. Skipping this saves an unnecessary API call.

File: activestorage/lib/active_storage/service/azure_storage_service.rb (hunk 2 above)
Comment (georgeclaghorn) [reply activestorage/lib/active_storage/service/azure_storage_service.rb]: Gah, thanks!

File: activestorage/app/models/active_storage/blob.rb (hunk 1 above)
Comment (kaspth) [reply activestorage/app/models/active_storage/blob.rb]: Ah, right 👍

File: activestorage/lib/active_storage/service/azure_storage_service.rb (hunk 3 above)
Comment (georgeclaghorn) [reply activestorage/lib/active_storage/service/azure_storage_service.rb]: We can provide the `:timeout` option to `list_blobs` if we wish, but it returns a limited number of blobs for each call (5,000 by default), so I don’t see why it’d block indefinitely.

File: activestorage/lib/active_storage/service/disk_service.rb (hunk 4 above)
Comment (georgeclaghorn) [reply activestorage/lib/active_storage/service/disk_service.rb]: > `Dir.glob` can potentially return `.` and `..`.

I was under the impression it would only do so if we set the `FNM_DOTMATCH` flag:

```ruby
irb(main):006:0> Dir.glob("/Users/george/Desktop/*")
=> []
irb(main):007:0> Dir.glob("/Users/george/Desktop/*", File::Constants::FNM_DOTMATCH)
=> ["/Users/george/Desktop/.", "/Users/george/Desktop/..", "/Users/george/Desktop/.DS_Store", "/Users/george/Desktop/.localized"]
```

Is that platform-dependent?

> Or are they always filtered out via the prefix?

In Active Storage’s own usage, yes.

> What happens if there's a blank prefix?

All objects are deleted. That seems *correct*, though perhaps not desirable.

Comment (kaspth) [reply activestorage/lib/active_storage/service/disk_service.rb]: > Is that platform-dependent?

Not sure. It could be Ruby version dependent. I definitely remember seeing it in our app on Ruby 2.2.

> All objects are deleted. That seems correct, though perhaps not desirable.

I meant to say: if `.` and `..` are included and the prefix is blank would it delete the current and parent directories?

File: activestorage/lib/active_storage/service/azure_storage_service.rb (hunk 3 above)
Comment (kaspth) [reply activestorage/lib/active_storage/service/azure_storage_service.rb]: 👍, the `loop do` just had me a bit worried 😊

File: activestorage/lib/active_storage/service/disk_service.rb (hunk 4 above)
Comment (georgeclaghorn) [reply activestorage/lib/active_storage/service/disk_service.rb]: > In Active Storage’s own usage, yes.

I’m wrong. Active Storage’s usage of `delete_prefixed` would theoretically encounter this.

> Not sure. It could be Ruby version dependent. I definitely remember seeing it in our app on Ruby 2.2.

I’m not seeing it on Ruby 2.2:

```ruby
irb(main):002:0> RUBY_VERSION
=> "2.2.8"
irb(main):003:0> Dir.glob("/Users/george/Desktop/*")
=> []
irb(main):004:0> Dir.glob("/Users/george/Desktop/*", File::Constants::FNM_DOTMATCH)
=> ["/Users/george/Desktop/.", "/Users/george/Desktop/..", "/Users/george/Desktop/.DS_Store", "/Users/george/Desktop/.localized"]
```

> I meant to say: if `.` and `..` are included and the prefix is blank would it delete the current and parent directories?

If they’re returned by `Dir.glob`, yes.

**Comment by victorbueno** [comment]
@georgeclaghorn Thank you for the fix!

File: activestorage/lib/active_storage/service/disk_service.rb (hunk 4 above)
Comment (kaspth) [reply activestorage/lib/active_storage/service/disk_service.rb]: Ah, I was thinking of `Dir.entries`. No worries here then 👍
